### ISSUE TITLE
Please document `parseMissingKeyHandler` option

### ISSUE THREAD

**Issue by stefanb2** [i18next/i18next#1000]
Documentation for this `init()` option is missing. I only discovered it via https://stackoverflow.com/questions/41708626/get-i18next-to-fallback-to-no-translation:

```javascript
i18n.init({
   ...
   parseMissingKeyHandler: (key) => {
       return .... some string that replaces "key" as translation...;
   },
   ...
});
```

**Comment by jamuhl** [comment]
https://www.i18next.com/configuration-options.html#missing-keys

**Comment by jamuhl** [comment]
oh issue 1000...wow...took some time to get here ;)

**Comment by stefanb2** [comment]
Yeah, my bad. Sorry.

Somehow in searching I ended up [here](http://i18next.github.io/i18next/pages/doc_features.html) which seems to be obsolete. Can this be updated to point to the official documentation?

**Comment by jamuhl** [comment]
hm...yes...thats the old v1 docs...sorry for getting there (that is still online for all the v1 users)

-> https://i18next.com for the current docs.
