### ISSUE TITLE
overridden interpolation settings - interpolation function incorrectly calculating key (edge case)

### ISSUE THREAD

**Issue by orzechowskid** [i18next/i18next#1001]
with i18next 10.2.1:

```
const i18next = require('i18next');

i18next.init({
    interpolation: {
        prefix: `__`,
        suffix: `__`
    },
    lng: 'en',
    debug: true,
    resources: {
        en: {
            translation: {
                myKey: '__mi__-mile (__km__-kilometer)'
            }
        }
    }
}, function() {
    console.log(i18next.t('myKey', {
        mi: '1',
        km: '1.6'
    }));
});
```
I see this printed to console:

```
i18next::interpolator: missed to pass in variable miundefinedkm for interpolating __miundefinedkm__-kilometer)
-kilometer)
```

([RunKit link](https://runkit.com/embed/ep06xk8p2o7r))

i18next seems to be getting confused when searching for interpolation start/end tokens.

I get the expected results if I remove hyphens from the translated value:
`        myKey: '__mi__ mile (__km__ kilometer)' // -> "1 mile (1.6 kilometer)"`
or if I remove the first hyphen:
`        myKey: '__mi__ mile (__km__-kilometer)' // -> "1 mile (1.6-kilometer)"`
but not if I remove only the second hyphen:
`        myKey: '__mi__-mile (__km__ kilometer)' // -> "kilometer)"`

**Comment by jamuhl** [comment]
not sure why...https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L47

need to dig into the regex at some point...but currently hard on time - if you got an idea to fix it a PR would be welcome.

**Comment by orzechowskid** [comment]
https://github.com/i18next/i18next/blob/d87888e8372cc2fe2783ec6c9858dec8bd80a21b/src/Interpolator.js#L50

this only happens when:
1) multiple interpolations are present, AND
2) any interpolation but the last is immediately followed by the string described by `interpolation.unescapePrefix`

The easy workaround is to set `interpolation.unescapePrefix` to something other than `-`.  I'm a bit pressed for time too but I'll have a think and see if I can come up with a PR.

thanks!

**Comment by jamuhl** [comment]
ah...than everything is ok...`__` are the old v1 prefix/suffix and it's unescape was https://github.com/i18next/i18next/blob/master/test/backward/compatibility/v1.js#L7 removing the unescapePrefix (setting it to null)

**Comment by jamuhl** [comment]
with everything ok i just mean...i know understand why it happens...still will need to fix that at some point (sorry to be unclear)...will need to play around a little with regex (not something i'm very good at ;)) to find some way to not allow the regex to have the prefix/suffix inside...

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-translation-parser/blob/master/src/parse.js#L11

regex excluding like above: `'(\{\{[^\}]+\}\}'` all but looking char: [^\}]

**Comment by patch** [comment]
I’m experiencing this same issue with the following `interpolation` settings:
```
prefix: '__',
suffix: '__',
unescapePrefix: ':'
```
For translation like: `Foo __BAR__: __BAZ__` (which is the format of some of the resulting translations, not the source English text)

**Comment by jamuhl** [comment]
like said above the solution is very simple - just not allow the `unescapePrefix` in the regex built here: https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L48

`const regexpStr = `${this.prefix}(.+?)${this.suffix}`;`

will get something like:

const regexpStr = `${this.prefix}([^${this.unescapePrefix}]+?)${this.suffix}`;

**Comment by jamuhl** [comment]
Just tried to make this work by adjusting the regex detections -> result will do more harm than solve. Which means would solve your case where:

- suffix is equal to prefix
- multiple values to interpolate exist
- the unescapePrefix is successor of the suffix

only option to solve this...override the unescapePrefix in this cases:

```js
t('myKey', {
  interpolation: {
    prefix: '__',
    suffix: '__',
    unescapePrefix: 'notWithME'
  }
}`
```

Hope that is sufficient as a workaround...won't invest anymore time into this - but open to a PR solving this (and passing all tests)

**Comment by jamuhl** [comment]
closing this now...after a year of inactivity (no PR) i guess there won't be a solution
