### ISSUE TITLE
[question] using i18next in multiple files

### ISSUE THREAD

**Issue by hovancik** [i18next/i18next#1002]
Hi folks, 
this might be dumb question, but I am fighting with it few days: 

I have electron app where I initialize i18next like this: 

```
const i18next = require('i18next')
const Backend = require('i18next-node-fs-backend')

startI18next()

function startI18next () {
  i18next
    .use(Backend)
    .init({
      lng: 'en',
      fallbackLng: 'en',
      debug: true,
      backend: {
        loadPath: `${__dirname}/locales/{{lng}}.json`,
        jsonIndent: 2
      }
    }, function(err, t) {
      global.shared.i18next = i18next
    })
}
```
I do `global.shared.i18next = i18next` so I can use i18next in electron renderer process like this: 

```
const {remote} = require('electron')

let translation = remote.getGlobal('shared').i18next.t(element.dataset.i18next)
```

One more thing that I do is that I have utility classes, that would need some translations too. As they are not either main or renderer process of electron, I can't use `remote` there. 

Example of my utility class: 

```
let formatRemaining = function (seconds) {
  if (seconds < 60) {
    return `${seconds + 1} seconds left`
  } else {
    return `${Math.trunc((seconds / 60) + 1)} minutes left`
  }
}

module.exports.formatRemaining = formatRemaining

```

What I've tried is: 

```
const t = require('../main.js')

let formatRemaining = function (seconds) {
  if (seconds < 60) {
    return `${seconds + 1} ${t('secondsLeft')}`
  } else {
    return `${Math.trunc((seconds / 60) + 1)} ${t('minutesLeft')}`
  }
}
```

and `module.exports.t = i18next.t` in main. 

What I am getting is: 
```
Uncaught Exception:
TypeError: t is not a function
```

As my knowledge of node is not very big, I guess I might be doing something really stupid and easy to fix. Any ideas welcome ;]

**Comment by jamuhl** [comment]
if you require`const t = require('../main.js')` the export should be `module.exports = i18next.t` i guess -> personally i would `module.exports = i18next` and `const i18n = require('../main.js')` and use it as `${seconds + 1} ${i18n.t('secondsLeft')}`

**Comment by hovancik** [comment]
So I changed my code to:

```
const i18n = require('../main.js')

let formatRemaining = function (seconds) {
  if (seconds < 60) {
    return `${seconds + 1} ${i18n.t('secondsLeft')}`
  } else {
    return `${Math.trunc((seconds / 60) + 1)} ${i18n.t('minutesLeft')}`
  }
}
```

and in main `module.exports = i18next`

And I still get `TypeError: i18n.t is not a function `

To be complete, I call my util like this in main : 
```
const Utils = require('./utils/utils')
Utils.formatRemaining(number)
```

**Comment by jamuhl** [comment]
hm...can you console.log(i18n)?!?

else try `const i18next = require('i18next')` in your Utils file...

**Comment by hovancik** [comment]
It gives `{}`. 

The `require('i18next')` thing, you mean to use it directly in my utils? I would need to init it again, right? And thus I would loose my cross-app ability to change language etc.

**Comment by jamuhl** [comment]
hm...that's strange...

this is your main.js i guess:

```
const i18next = require('i18next')
const Backend = require('i18next-node-fs-backend')

startI18next()

function startI18next () {
  i18next
    .use(Backend)
    .init({
      lng: 'en',
      fallbackLng: 'en',
      debug: true,
      backend: {
        loadPath: `${__dirname}/locales/{{lng}}.json`,
        jsonIndent: 2
      }
    }, function(err, t) {
      global.shared.i18next = i18next
    })
}

module.exports = i18next
```

no `require('i18next')` will require the initialized instance

**Comment by hovancik** [comment]
so this is main.js: 
```
.
.
const i18next = require('i18next')
const Backend = require('i18next-node-fs-backend')
startI18next()
const Utils = require('./utils/utils')
.
.
.

function startI18next () {
  i18next
    .use(Backend)
    .init({
      lng: 'en',
      fallbackLng: 'en',
      debug: true,
      backend: {
        loadPath: `${__dirname}/locales/{{lng}}.json`,
        jsonIndent: 2
      }
    }, function(err, t) {
      global.shared.i18next = i18next
    })
}
.
.
let timeleft = Utils.formatRemaining(breakPlanner.scheduler.timeLeft / 1000.0)
.
.
module.exports = i18next
```

So I wonder maybe it depends in what place I do export and requiring Utils? 

Anyway, doing just `const i18next = require('i18next')` in my Utils worked. 

Many thanks!

**Comment by hovancik** [comment]
@jamuhl there is still one thing that I am fighting with: 

I include my utils also in another class, in which it does not work properly: when I call  ``formatRemaining` I'm getting undefined. So I tried to print i18next inside that function and what seeing is:

```
//if I call Utils inside my main.js
I18n { // a lot of stuff} 
```

```
//calling in another file
[object Object]
```
Maybe you've seen this somewhere before?
