### ISSUE TITLE
Missing translation key before XHR finish loading resources

### ISSUE THREAD

**Issue by wijdench** [i18next/i18next#1004]
Hi, after loading the first react page I have console error
 `i18next::backendConnector: successfully loaded namespaces common, nav, search, backoffice for languages en via multiloading {en: {…}}

 i18next::backendConnector: successfully loaded namespaces common, nav, search, backoffice for languages fr via multiloading {fr: {…}}

i18next: languageChanged fr

 i18next: initialized {debug: true, initImmediate: true, ns: Array(4), defaultNS: "common", fallbackLng: {…}, …}

 i18next::translator: missingKey fr backoffice  
 i18next::translator: missingKey fr backoffice  

XHR finished loading: GET "http://test/locales/resources.json?lng=en&ns=common+nav+search+backoffice".
 XHR finished loading: GET "http://test/locales/resources.json?lng=fr&ns=common+nav+search+backoffice".`

And when i change the language i've got this error 
i18next: languageChanged en
 i18next::translator: missingKey en backoffice  
 i18next: languageChanged fr
 i18next::translator: missingKey fr backoffice  

but all components are sucsessfully translated in my pages locally and i 'm not sure if it will affect the deployed version of my app.

Thanks for your help.

**Comment by jamuhl** [comment]
looks like you're code is calling t() somewhere without providing a key?!? https://github.com/i18next/i18next/blob/master/src/Translator.js#L126

log output should normally be something like `i18next::translator: missingKey fr backoffice YOURKEY EVENTUALDEFAULTVALUE`

**Comment by jamuhl** [comment]
closing for now...feel free to reopen if still an issue.
