### ISSUE TITLE
TypeError: this.backend[fcName] is not a function

### ISSUE THREAD

**Issue by szabolcsx** [i18next/i18next#1006]
Hi,

I get the following error if I try to use the XHR backend: `TypeError: this.backend[fcName] is not a function`.

Here is how I'm initializing my i18next instance:
``` TS
import * as i18n from "i18next";
import * as XHR from "i18next-xhr-backend";
import * as reactI18Next from "react-i18next";

const backend: XHR.BackendOptions = {
    loadPath: "{{lng}}",
    parse: data => data,
};

const instance = i18n
    .use(XHR)
    .use(reactI18Next)
    .init({
        backend,
        fallbackLng: "en",
        ns: ["translations"],
        defaultNS: "translations",
        react: { wait: true },
    });

export const translate = reactI18Next.translate("translations");
export interface TranslateProps extends reactI18Next.InjectedTranslateProps {}

export default instance;
```

TypeScript version: 2.6.2
i18next version: 10.2.1
xhr backend version: 1.5.0

Any ideas why am I getting this error?

**Comment by jamuhl** [comment]
could you turn on `debug:  true` in init options?!? rather sure you get some msg of no backend was added.

could you also console.log(XHR) - must be something with that import i guess

**Comment by jamuhl** [comment]
Not sure why...but looks like you have to do something like:

`import { default as XHR } from "i18next-xhr-backend";`

to get the default export imported correctly

**Comment by szabolcsx** [comment]
That is unfortunately not working. The TypeScript compiler actually expects an item named default to be exported.

If I make the following change in the type definition however, it works:
``` TS
// export = I18NextXhrBackend;
export default I18NextXhrBackend;
```
Maybe it is a problem of the type definitions.

**Comment by jamuhl** [comment]
Alternatively you can:

```js
const instance = i18n
    .use(XHR.default)
```

**Comment by szabolcsx** [comment]
That also gives me a compiler error.

**Comment by jamuhl** [comment]
argh...those typescript...never was a friend of it ;)...might have something todo with the definitions like you said...idk

**Comment by szabolcsx** [comment]
I created an issue for the type definitions: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/22192

**Comment by jamuhl** [comment]
closing for noe
