### ISSUE TITLE
Disable internolation by i18n.t(key, options)

### ISSUE THREAD

**Issue by lomaster1** [i18next/i18next#1007]
I know my localication string has not dynamic values, but when I use i18n.t('somekey') interpolation check the string.

I want to disable interpolation via options for performance reason, because interpolation takes more than half the time (milliseconds but if string many?). 

For example, i18n.t('somekey', { disableInterpolation: true }).

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/src/Translator.js#L171

PR will be accepted

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/pull/1050

published in i18next@11.3.0
