### ISSUE TITLE
changeLanguage - globally or in local scope?

### ISSUE THREAD

**Issue by alksandar** [i18next/i18next#1011]
Hi!
Just a quick question, will calling i18next.changeLanguage(lng) change the language globally or just in the local scope?
Sorry if the question has already been asked or it can be found in the docs, I wasn't able to find the answer in either of those.
Best regards!

**Comment by jamuhl** [comment]
globally...to get a scoped function use: https://www.i18next.com/api.html#getfixedt

**Comment by alksandar** [comment]
Thank you for the quick answer!
