### ISSUE TITLE
Regarding `addResourceBundle` and cache plugin

### ISSUE THREAD

**Issue by KatSick** [i18next/i18next#1012]
When i perform `addResourceBundle` does to override values in cache?

**Comment by jamuhl** [comment]
should work: https://github.com/i18next/i18next/blob/master/src/i18next.js#L62 everytime we get an added event from the resourceStore the cache plugins save function gets called...

and addResourceBundle should trigger that: https://github.com/i18next/i18next/blob/master/src/ResourceStore.js#L88

but all should...not had time to check if there is a test for this and had no time to validate it's still actually working - but from looking at code it should work ;)

**Comment by jamuhl** [comment]
could this be closed? or still need more information - or does the expected behaviour not work as it should?
