### ISSUE TITLE
i18next.t() doesn't work

### ISSUE THREAD

**Issue by DMShamonov** [i18next/i18next#1013]
After update i18next to 10.3.0 (from 10.2.2), i18next.t() doesn't work in my React app.

It's how I init i18next:
```
i18next.init({
    lng: locale,
    resources:
        LocaleAdapter.transformLocalesToi18nextResourceObjectNotation(_merge(
          appLocales,
          locales,
        )),
});
```

If I revert to 10.2.2, it's working.

**Comment by DMShamonov** [comment]
No, I don't have errors in console. And in i18next debug mode all well.
i18next.t() just nothing returns.

**Comment by jamuhl** [comment]
updating one of the react-i18next/examples right now....will see if there is anything wrong i guess

**Comment by jamuhl** [comment]
hm...wasn't able to reproduce this...both loading translations via xhr or passing in via options.resources worked. Must be something more specific to your code - but i don't see what it could be from your configuration.

Could you `console.log(i18next.services.resourceStore.data);`

**Comment by DMShamonov** [comment]
From `console.log(i18next.services.resourceStore.data);` I get `Uncaught TypeError: Cannot read property 'data' of undefined`, and it's happens only with i18next 10.3.0

This is how I init my app:
1. From my react-app I call `App.init()`. 'App' controller located in `/node_modules/MY_PACKAGE/src/...`
2. In App.init() I init i18next.
3. Next I call i18next.t() in component in my react-app. That's all...

If I call `console.log(i18next.services.resourceStore.data);` from 'App' controller located in `/node_modules/MY_PACKAGE/src/...`, I get object with translations strings.

Then, if I call `console.log(i18next.services.resourceStore.data);` from component in my react-app (after App.init()), I get this error `Uncaught TypeError: Cannot read property 'data' of undefined`.

But if I do all this with i18next 10.2.2 then all well...

**Comment by jamuhl** [comment]
do you use a translate hoc or render props (i18n) from react-i18next -> looks to me as you call i18next.t before the translations were loaded - and that causes that problem. Not sure why there is a difference in 10.2.2 vs 10.3.0.

**Comment by jamuhl** [comment]
the only change from 10.2.2 to 10.3.0 is this. https://github.com/i18next/i18next/commit/3cb51cea60209131152f4835e649561dc0a381ec

**Comment by DMShamonov** [comment]
I use [i18next](https://www.npmjs.com/package/i18next), not `react-i18next` package:
```
import i18next from 'i18next';
...
<p>{i18next.t('common.example_string')}</p>
...
```

**Comment by jamuhl** [comment]
could you try with i18next v10.3.0 and set `saveMissingPlurals` to false in init options - at least that should give you same behaviour.

But still you should consider using react-i18next to avoid "not yet loaded" issues ;)

**Comment by DMShamonov** [comment]
Ok, later I will check this option. Thanks.

**Comment by DMShamonov** [comment]
With `saveMissingPlurals: false` I have same result.
When I call i18next.t(), i18next.init() finished and translation uploaded already.

And interestingly, this error is only in `10.3.0`

**Comment by jamuhl** [comment]
out of ideas...could you provide a minimal stripped down version of your code so i could reproduce this? would help me a lot...

**Comment by DMShamonov** [comment]
Ok, but a little later

**Comment by jamuhl** [comment]
sure no need to rush - and 10.3.0 does not have any changes you need...just like to make sure there is no bug that will freeze you on not being able to update to future versions of i18next

**Comment by DMShamonov** [comment]
Of Course. Thanks! :)

**Comment by DMShamonov** [comment]
Hi @jamuhl! 
I understanded why I catched this error... 
It's because I used different instance of `i18next` in my app o_O
In external package I usage `10.2.2` version, but in my app I use `10.3.0` version of `i18next`.
It's my fault, sorry for this issue...

**Comment by jamuhl** [comment]
glad you found the cause...if there is anything else...let me know.
