### ISSUE TITLE
is there a list of accepted language code? en, fr, de, and? (resources parameter)

### ISSUE THREAD

**Issue by 1c7** [i18next/i18next#1015]
What kind of standard i18next using?
```javascript
export default i18n.init({
  debug: true,
  lng: ReactNativeLanguages.language,
  fallbackLng: 'en',
  resources: { en, fr, de } // what can I put here??
});
```
what language code are accepted for `resources`?     

can I use 
`zh`(Chinese) `zh-hk`(Chinese, Hong Kong) `zh-tw`(Chinese Tai Wan) `ru`(Russian) ?

the document didn't say anything about this. (https://www.i18next.com/#language)

Thanks!

**Comment by jamuhl** [comment]
all supported following the ISO norm:

lng-(script)-REGION-(extensions)

zh, zh-HK or zh-hant-HK

lookup will always be concrete to fallback, eg.: from -> to |||  zh-HK -> zh -> en

**Comment by 1c7** [comment]
@jamuhl  Thank you very much!

**Comment by tonix-tuft** [comment]
https://github.com/i18next/i18next/issues/1015#issuecomment-363769807

@jamuhl  Could you please provide a link as a reference where all the supported language codes which can be passed as `lng` to i18next are found? I couldn't find any.

Thank you!

**Comment by jamuhl** [comment]
like said you can pass all of them -> plural rules exist for: https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L6 (you can add your own pluralrules on the fly if not there)
