### ISSUE TITLE
Static site generator?

### ISSUE THREAD

**Issue by alvarotrigo** [i18next/i18next#1016]
Can i18next be used to create multiple .html files in different languages?
Using a static site and I only need multiple versions of the same HTML page in different languages.

**Comment by jamuhl** [comment]
can be used yes...by including it in the generation process of the static site generator....

never done...so can't be of big help...our approach is more to translate on client or server side on runtime...

**Comment by alvarotrigo** [comment]
Ok, I'll then keep using [/node-static-i18n](https://github.com/claudetech/node-static-i18n), which is using i18next.
