### ISSUE TITLE
TypeError: _i18next2.default.use is not a function

### ISSUE THREAD

**Issue by PerpetualWar** [i18next/i18next#1017]
Hello, 

I'm trying to setup testing suite with jest+ vue-test-utils or karma+jasmine+vue-test-utils (both throw same errors).

Is this problem with library or not ? Any idea how this can be solved ?

```
 TypeError: _i18next2.default.use is not a function

      34 |
      35 | i18next
    > 36 |      .use(Locize)
      37 |      .init(i18nextOptions);
      38 |
      39 | export default new VueI18Next(i18next);

      at Object.<anonymous> (src/app/locale/i18n.js:36:1)
      at Object.<anonymous> (src/app/store/modules/account/mutations.js:6:13)
      at Object.<anonymous> (src/app/store/modules/account/index.js:7:18)
      at Object.<anonymous> (src/app/store/index.js:17:16)      at src/app/pages/home/index/index.vue:24:14
      at Object.<anonymous> (src/app/pages/home/index/index.vue:230:3)
      at Object.<anonymous> (test/unit/home.spec.js:10:14)
```

**Comment by jamuhl** [comment]
do you have this only in the test suite or in general (running website)

**Comment by PerpetualWar** [comment]
only in test suite when I try to mock i18next.... without mock it says i18next is not defined.

Any help is appreciated.

**Comment by jamuhl** [comment]
looks like the import does not be compatible with webpack

try `import { default as i18next } from 'i18next';`

**Comment by PerpetualWar** [comment]
where exactly ? if you mean in test, how do I initialize it, like this: 

```
beforeEach(() => {
    cmp = shallow(Home, {
      i18next
    });
  });
```

of you meant something else ?

**Comment by PerpetualWar** [comment]
ok, I only import it directly in locale file, and I setup options there. 

I switched it: 
```// import i18next from 'i18next';
import { default as i18next } from 'i18next';
import VueI18Next from '@panter/vue-i18next';```

still same error. Any other idea ?

**Comment by jamuhl** [comment]
not really...just do a console.log of i18next...seems to be import related...

```js
// import i18next from 'i18next';
import { default as i18next } from 'i18next';
console.log(i18next); // -> must be undefined i guess
import VueI18Next from '@panter/vue-i18next';
```

not had such an issue ever...hard to help without having options to debug...but must be related to import.

**Comment by PerpetualWar** [comment]
```
i18next
	.use(Locize)
	.init(i18nextOptions);

export default new VueI18Next(i18next);
```

Can I somehow mock this i18next.use(Locize), would it work like that ?

Like I said , I only need to fix this in tests.

**Comment by jamuhl** [comment]
for react -> but might help anyway: https://react.i18next.com/misc/testing.html

**Comment by jamuhl** [comment]
you can mock away i18next completely i think -> just provide a function `t` on it returning first prop and noops for the rest

```js
const i18next = {
  use: () => {},
  init: () => {},
  t: key => key
}
```

**Comment by PerpetualWar** [comment]
Thanks will try that out. ;)

**Comment by PerpetualWar** [comment]
ok, when I mock it like this: 

```
import { shallow, mount, createLocalVue } from '@vue/test-utils';
// import i18n from './__mocks__/i18nextMock';
import Home from '../../src/app/pages/home/index/index.vue';

jest.mock('i18next', () => ({
  use: jest.fn(() => ({})),
  init: jest.fn(() => ({})),
  t: k => k
}));

describe('Home Component', () => {

  let cmp;

  beforeEach(() => {
    cmp = shallow(Home);
  });

  it('something', () => {
    console.log('bleh');
    expect(2+2).toBe(4);
    // expect(cmp.vm).toBeTruthy();
  });

});
```
it throws similar but different error: 


● ```
Test suite failed to run

    TypeError: _i18next2.default.use(...).init is not a function

      36 | i18next
      37 |      .use(Locize)
    > 38 |      .init(i18nextOptions);
      39 |
      40 | export default new VueI18Next(i18next);
      41 |

      at Object.<anonymous> (src/app/locale/i18n.js:38:1)
      at Object.<anonymous> (src/app/store/modules/account/mutations.js:6:13)
      at Object.<anonymous> (src/app/store/modules/account/index.js:7:18)
      at Object.<anonymous> (src/app/store/index.js:17:16)
      at src/app/pages/home/index/index.vue:24:14
      at Object.<anonymous> (src/app/pages/home/index/index.vue:230:3)
      at Object.<anonymous> (test/unit/home.spec.js:16:96)
```

now it complains of init not being a function.... even though both use and init are mocked.

Any suggestion would else could I try in this mock ?

**Comment by jamuhl** [comment]
you will need to return this from your use function:

```js
const i18next = {
  use: () => { return this; },
  init: () => {},
  t: key => key
}
```

**Comment by PerpetualWar** [comment]
if I set : 

```
jest.mock('i18next', () => ({
  use: () => { return this; },
  init: () => { },
  t: k => k
}));
```

it says:  TypeError: Cannot read property 'init' of undefined

The same error if I remove ` return this` , just the same (when it's empty function).

**Comment by jamuhl** [comment]
then try returning the constant itself `return i18next`

**Comment by jamuhl** [comment]
in the end just make the function chain work ;)

**Comment by PerpetualWar** [comment]
```
jest.mock('i18next', () => ({
  use: () => {
    return {
      init: () => { }
    };
  },
  t: k => k
}));
```

This partially worked to get another error msg: 

```
TypeError: this.i18next.on is not a function

      38 |      .init(i18nextOptions);
      39 |
    > 40 | export default new VueI18Next(i18next);
      41 |
```

**Comment by jamuhl** [comment]
seems the vue-i18next depends on the event emitter build in...you will have to mock that too

evetual a good idea to ask there `@panter/vue-i18next` what functions on i18next are needed to have a complete mock

**Comment by jamuhl** [comment]
closing for now...feel free to reopen if still some issue

**Comment by instinctcoder** [comment]
i have same issue. but i'm using typescript and react

i follow the last setup from above comment, is there anyway to get rid this?

```

jest.mock('i18next', () => ({
    use: () => {
      return {
        init: () => { }
      };
    },
    t: k => k
  }));
```

give me this error  _i18next.default.init is not a function too

**Comment by PerminovEugene** [comment]
Something wrong with imports in module. I've changed my code to
`const i18n =  require('i18next').default;` and this works fine

**Comment by jamuhl** [comment]
Nothing wrong with imports...depends on the environment picking commonjs or es6 module...

**Comment by lukehutton-clearly** [comment]
Thanks for comments, I got it working with:

```
import i18next from "i18next";

jest.mock("i18next", () => ({
  use: () => { return i18next },
  init: jest.fn()
}));
```

**Comment by manav-0** [comment]
I'm also getting same error : _i18next.default.addResourceBundle is not a function

Although, My error was resolved via adding this two changes.

1) create __mocks__ folder in your /src directory
2) then create new flle named "react-i18next.js"
3) then simply pase the code as instructed here : https://github.com/i18next/react-i18next/blob/master/example/v9.x.x/test-jest/__mocks__/react-i18next.js
4) then go into your */.test.js file
5) then add mock function like below
`jest.mock("i18next", () => ({
  addResourceBundle: jest.fn(),
}));`

And woooo.. It works!!
