### ISSUE TITLE
options.overloadTranslationOptionHandler is not a function

### ISSUE THREAD

**Issue by TomasRup** [i18next/i18next#1018]
Hi,

We are getting this error:
```
Uncaught TypeError: _this5.options.overloadTranslationOptionHandler is not a function
    at fixedT (i18next.js:298)
```

FYI: We are doing SSR, that might be one of the reasons we get this.
i18next version: ```10.3.0```

**Comment by jamuhl** [comment]
looks like you calling that function before init

**Comment by TomasRup** [comment]
is it a must to do init? Can't I just do the `createInstance`?

**Comment by TomasRup** [comment]
I am asking, because I am solving an issue right now: I own a library that has i18next and my library user has i18next.

When I do i18next.init from my library, the resources on my library user side gets f*cked up 😄 
So I am wondering what is the way to solve this.

**Comment by jamuhl** [comment]
nope...create instance just creates it...does not init if not called with callback `createInstance(opts, cb);`

so not having called init...will not work

**Comment by TomasRup** [comment]
So I can have only one instance per global context?

**Comment by jamuhl** [comment]
what you mean by global context...?!?

`import i18next from 'i18next'` will give you the main instance (shared if import somewhere else)

with your additional instances `createInstance ` you can do what you like -> append to window or global -> whatever you like...

**Comment by TomasRup** [comment]
Let's say you have a web that does `import i18next from 'i18next'`
And I have a library that also does `import i18next from 'i18next'`

Let's say you are using my library: you call `init` and I call `init` - we get unexpected behaviour.
As in my case, the main instance gets changes, so in my web, I can see the translations of my library.

How can I avoid having a "main, shared instance"?

**Comment by jamuhl** [comment]
as you create a lib to be reused i would say you should do something like:

```js
// i18n.js in your module
import i18next from 'i18next';

const i18n = i18next.createInstance();
i18n.init({ /* your options */ });

export default i18n;

// in your other files instead of importing i18next you
import i18n from './i18n';
```

**Comment by TomasRup** [comment]
@jamuhl I am talking about two separate npm modules :-) I.e. a library could be reused by anyone around the world.

**Comment by jamuhl** [comment]
and the solution above says...do not use the share instance but use the one created by you - not sure what your concern there is...

**Comment by TomasRup** [comment]
aaaa, sorry, you are totally right. Thank you!
As always - you are super fast on assisting with issues 👍 🏅

**Comment by jamuhl** [comment]
you're welcome
