### ISSUE TITLE
Issue using T function when resources is a json file

### ISSUE THREAD

**Issue by dannstuff** [i18next/i18next#1020]
Hi, im having an issue with my t function not returning a value when i pass resources a variable linked to a json file. Here is my i18n init - 
``i18n
    .init({
        lng: 'en',
        debug: appEnv.debug,
        resources: {
            en: {
                translation: {
                    milestones,
                },
            },
        },
        interpolation: {
            escapeValue: false,
        },
        react: {
            wait: true,
            nsMode: 'default',
        },``

I have imported 'milestones' like this - `import * as milestones from '../../public/_i18n/en/milestones.json';`

milestones is a standard json file following this format - 
``    "milestone_Kickoff_title": `"Setup" ``

yet when I try - `console.log(i18n.t('milestone_Kickoff_title'));
` I still get 'missing translation milestone_Kickoff_title' -- any ideas? am I using the T function correctly? because if i put the contents of that json file directly into the resources I have no issue searching it. 
Thanks! dan

**Comment by jamuhl** [comment]
try 

`i18n .init({ lng: 'en', debug: appEnv.debug, resources: { en: { translation: { ...milestones, }, }, }, interpolation: { escapeValue: false, }, react: { wait: true, nsMode: 'default', },`

**Comment by dannstuff** [comment]
@jamuhl hey man! thanks for the reply, it seems to work in this structure --
 ``        resources: {
            en: {
                translation: milestones,
            },
        },``

However, if i were searching a key that looks like this  -- 
 "milestone.Dossier.title": "Property `Information",
it seems to not return, im guessing this is to do with the '.' separating the words?

**Comment by jamuhl** [comment]
yes, per default i18next uses `.` for nesting

json:

```
json
{
  "Dossier": {
     "title": "Property `Information"
  }
}
```

you can turn this off by setting `keySeparator: false` on i18next.init

**Comment by jamuhl** [comment]
Closing for now...if still questions or unclear feel free to reopen
