### ISSUE TITLE
[Feature Request] pass options to addResources and addResourceBundle

### ISSUE THREAD

**Issue by olivierpascal** [i18next/i18next#1022]
Sometimes you want to load resource bundles in background without triggering events and re-rendering the whole app (ie. with react-i18next).

`addResource()` has a handy option (`options.silent`) which disable the event emitting. Is it possible to have the same with `addResources()` and `addResourceBundle`?

**Comment by jamuhl** [comment]
Would you mind creating a pullrequest?

**Comment by olivierpascal** [comment]
Sure!
