### ISSUE TITLE
i18next::translator: missingKey undefined translation 

### ISSUE THREAD

**Issue by Simone-cogno** [i18next/i18next#1025]
I have the json file in 3 folders on the `locales` folder. Like this:

<project_path>/locales/en/translation.json
<project_path>/locales/de/translation.json
<project_path>/locales/it/translation.json
```
{
    "test": "Test in english"
}
```
i18next initialization code:
```
const i18next = require('i18next');
const middleware = require('i18next-express-middleware');
const languageDetector = new middleware.LanguageDetector();
console.log( __dirname + `/locales/{{lng}}/{{ns}}.json`)
i18next
    .use(languageDetector)
    .init({
        backend: {
            loadPath: __dirname + `/locales/{{lng}}/{{ns}}.json`,
            addPath: __dirname +`/locales/{{lng}}/{{ns}}.missing.json`
        },
        locales:['en', 'de', 'it'],
        fallbackLng: {
            'default': ['en']
        },
        saveMissing: false,
        debug: true
    }, (err, t) => {
        if(err){
            console.error(err);
            throw new Error(err);
        }
        console.log(t('test'));
    });
```

I got in the console:
`i18next::translator: missingKey undefined translation test test`
`test`

Any idea why the key is missing? The path to the JSON is set correctly.

**Comment by jamuhl** [comment]
you call t inside the callback - on that time language is still undefined

the language detection for the express middleware is run on every request and out of that only works inside a request. For test you still can: `console.log(t('test', { lng: 'en' }));`

PS: what is `locales:['en', 'de', 'it'],` ?!? for sure that's not in the documentation. do you mean `preload`

**Comment by Simone-cogno** [comment]
I've found the problem I didn't add the  `i18next-node-fs-backend` module. Didn't know that was really necessary. Now it works thanks.

Here the code I used: 
```
const i18next = require('i18next');
const Backend = require('i18next-node-fs-backend');
const middleware = require('i18next-express-middleware');
const languageDetector = new middleware.LanguageDetector();
console.log( __dirname + `/locales/{{lng}}/{{ns}}.json`)
i18next
    .use(Backend)
    .use(languageDetector)
    .init({
        backend: {
            loadPath: __dirname + `/locales/{{lng}}/{{ns}}.json`
        },
        fallbackLng: {
            'default': ['en']
        },
        saveMissing: false,
        debug: true
    }, (err, t) => {
        if(err){
            console.error(err);
            throw new Error(err);
        }
        console.log(t('test'));
    });
```
