### ISSUE TITLE
changeLanguage do not generate error

### ISSUE THREAD

**Issue by newbie78** [i18next/i18next#1026]
Hi to all
How to get an error if the incoming language is not present in the resources list?
```
    i18next.changeLanguage(to.params.lang, (err, t) => {
      console.log(err)
    })
```
In the example I get null when the language is present in the list and when it is not there. Even if the language is "asdasd" - I still get null.

thanks

**Comment by jamuhl** [comment]
you do not get an error for language not existing...if a language exists to load or not is in your control - basically it has the languages you provide and fallbacks for all other languages to the defined fallback. So not having a language is no error in this case - i hope that is understandable.

you get an error for failed loading eg. in case backend is not reachable.

**Comment by jamuhl** [comment]
Feel free to reopen if still an issue...
