### ISSUE TITLE
fallbackLng doesn't work properly when is defined as object 

### ISSUE THREAD

**Issue by radeno** [i18next/i18next#1028]
Hello,

i'm using this great plugin with Next.JS and React.
Based on this documentation https://www.i18next.com/principles/fallback.html#fallback-language my settings for fallbackLng is defined like this:
```javascript
fallbackLng: {
  cs: ['sk'],
  default: ['en', 'sk']
}
```
But this doens't work properly because fallback is not set. and checked by `curl -i "http://localhost:4000"` 

when i debugging `i18n` object missing property `.languages` and `.language` is set as undefined.

When fallback is defined as array or string everything works.

Versions:
```json
"i18next": "^10.5.0",
"i18next-browser-languagedetector": "^2.1.0",
"i18next-express-middleware": "^1.0.11",
"i18next-node-fs-backend": "^1.0.0",
"i18next-xhr-backend": "^1.5.1",
"next": "^5.0.0"
```

**Comment by jamuhl** [comment]
do not see why it shouldn't work: https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L68

there are also tests...https://github.com/i18next/i18next/blob/master/test/languageUtils.spec.js#L30

would really be great if you could debug where it goes wrong...from pure i18next source i would say it works...:(

**Comment by radeno** [comment]
I forgot to mention that i use ExpressJS. Maybe in that middleware?
Because without "accept language" it fails with "Internal server error". When i tried `curl -i -H 'Accept-Language: en' "http://localhost:4000"` it works.

**Comment by radeno** [comment]
Maybe i found it:

https://github.com/i18next/i18next-express-middleware/blob/master/src/LanguageDetector.js#L71

it expects array and zero index.

**Comment by jamuhl** [comment]
PR merged
