### ISSUE TITLE
use different resource file in a specific component

### ISSUE THREAD

**Issue by assafb81** [i18next/i18next#1029]
How do I use a specific resource file in a specific component.
I am using `i18next` in my RN app and I want to add a new ability, for specific strings I want to use a specific resource file and not the device locale as I do in the rest of the app.

for example, my component is:
```
class ComponentA extends PureComponent{
  render() {
    return(
      <View>
        <Text>{normalText}</Text>
        <Text>{resourceFileB:specificText}></Text>
      </View>
    );
  }
}

export default translate('reasourceFileA')(ComponentA );
```

`normalText` - this translate as expected
`specificText` - this text should use translation from specific translation file

I tried this in my `i18n.js` file but with no luck:

```
i18next
    .use(i18nextReactNative)
    .init({
        fallbackLng: 'en',
        resources: {
            en,
            ru,
            **reasourceFileB**,
        },

        react: {
            wait: false,
        },

        // have a common namespace used around the full app
        ns: ['common', '**reasourceFileB**'],
        defaultNS: 'common',

        debug: true,

        interpolation: {
            escapeValue: false, // not needed for react!!
            formatSeparator: ',',
            format(value, format) {
                if (format === 'uppercase') return value.toUpperCase();

                return value;
            },
        },
    });

export default i18next;
```
is there a way to use `interpolation ` function?
Thanks

**Comment by jamuhl** [comment]
Using `i18n.t('ns:key')` you can override the used namespace

in Trans component you can specify namespace override as:

```js
<Trans i18nKey="key" ns="otherNS">lorem ipsum</Trans>
```

**Comment by assafb81** [comment]
Thanks for the quick reply,
Trans component is not relevant for me as far as I see it.

I tried the second approach you suggested:
in my code I wrote: 
`const localizeName = t('ES:', name);`
and I use it like this
`<Text>{localizeName}></Text>`
and I expect to see in my app:
`custom_name - ES`

in my i18n file, my i18next configuration file I have this:
```
import i18next from 'i18next';
import i18nextReactNative from 'i18next-react-native-language-detector';

import names from './names';
import ru from './ru';
import en from './en';

i18next
    .use(i18nextReactNative)
    .init({
        fallbackLng: 'en',
        resources: {
            names,
            en,
            ru,
        },

        react: {
            wait: false,
        },

        // have a common namespace used around the full app
        ns: ['common', 'names'],
        defaultNS: 'common',

        debug: true,

        interpolation: {
            escapeValue: false, // not needed for react!!
            formatSeparator: ',',
            format(value, format) {
                if (format === 'uppercase') return value.toUpperCase();

                return value;
            },
        },
    });

export default i18next;
```

my names.js file looks like this:
```
export default {
    US: {
        name: 'custom_name - US',
        ....,
    },
    GB: {
        name: 'custom_name - GB',
        ....,
    },
    ES: {
        name: 'custom_name - ES',
        ....,    },
    DE: {
        name: 'custom_name - DE',
        ....,    },
    FR: {
        name: 'custom_name - FR',
        ....,    },
    IT: {
        name: 'custom_name - IT',
        ....,    },
    IL: {
        name: 'custom_name - IL',
        ....,    },
};
```

**Comment by jamuhl** [comment]
that does not work:

```js
        resources: {
            names,
            en,
            ru,
        },
```

structure must be lng -> ns -> key for resources...right now names act as a language ;)

and its `const localizeName = t('ES:name');`

with current structure you could access it using `names` as language and call `t` with that as lng:

`const localizeName = t('ES:name', { lng: 'names' });`

**Comment by assafb81** [comment]
is there a better way / best practice to construct the resources?

**Comment by jamuhl** [comment]
resources should look like:

```json
{
  lng1: {
    namespace1: {},
    namepace2: {},
    // ...
   }, 
  }
  lng2: {
    namespace1: {},
    namepace2: {},
    // ...
   }, 
}
```

that's all...how you construct that...matter of taste...in the end it must be lng -> ns -> key

**Comment by assafb81** [comment]
Thanks for the help!!!
most of my lngs files are as above, but this is a special case this is why I needed this exception.
