### ISSUE TITLE
require makes i18next.js to load into app.js bundle instead of vendor.js

### ISSUE THREAD

**Issue by jacekk015** [i18next/i18next#1030]
How to use that library without require?
Putting module into webpack vendor config gives me
`i18next is not defined`

If I require it, it goes to the app.js bundle.

Tried also ProvidePlugin - no go
`
 new webpack.ProvidePlugin({
    i18next: 'i18next'
  })`

```javascript
module.exports = {
  entry: {
    'js/app': [
      './src/js/app.js'
    ],
    'js/vendor': ['node_modules/webix/webix_debug.js', 'i18next', 'moment', 'moment-business', 'moment-duration-format', 'moment-timer']
  },
...```

**Comment by jamuhl** [comment]
how do you use moment?

if no require, no import, no requirejs, i18next will be like any other umd module be on window.i18next

just make sure you use the right export from dist -> there is commonjs, es, and umd if i remember right

**Comment by jacekk015** [comment]
I didn't get so far to use moment.
webix works normally as webix global.

If you put into Chrome console:
- window.i18next is undefined
- window.webix returns webix object
- window.moment is also undefined

Tried to load all version from dist. Same happens.

Webix source has int the beginning:
`if (!window.webix) 
	webix={};`

**Comment by jamuhl** [comment]
idk webix...but seems it just build to be on global scope...as you're using webpack require is defined so those other modules like moment, i18next show not up in global scope -> i would just not move them to vendor

**Comment by jacekk015** [comment]
It looks like but I'm also surprised that ProvidePlugin didn't do the job either.
It supposed to load that into global variable.

Division between app and vendor isn't critical but I've spend so many time on getting that proper config in Webpack that I'm kinda surprised I can't achieve that.

**Comment by jamuhl** [comment]
ProvidePlugin does not magically add a module to globalscope - just adds it no the vendor bundle which i guess is meant for old legacy libs like jquery

**Comment by jacekk015** [comment]
Strange.
Using expose-loader works with moment, doesn't work with i18next - still undefined.
https://github.com/webpack/webpack/issues/3128#issuecomment-366537699

```javascript
{
      test: require.resolve('i18next'),
      use: [
        {
          loader: 'expose-loader',
          options: 'i18next'
        }
      ]
    }, {
      test: require.resolve('moment'),
      use: [
        {
          loader: 'expose-loader',
          options: 'moment'
        }
      ]
    }```

```
moment
ƒ hooks() {
    return hookCallback.apply(null, arguments);
}
i18next
VM256:1 Uncaught ReferenceError: i18next is not defined
    at <anonymous>:1:1
```

​

**Comment by jamuhl** [comment]
looks like you get an umd file for moment - and possible for the i18next the es export

**Comment by jacekk015** [comment]
OK, it looks like webpack only behaves like that when on dev mode with all that hot module reloading stuff enabled.
If I build my js files it's okay, so I just ignore it and use normal require, like I should from the beginning.
