### ISSUE TITLE
Locally works fine, but on Server it gives 404 not found error!

### ISSUE THREAD

**Issue by aniruddhashevle** [i18next/i18next#1031]
Thanks for this great package.

I'm using this package using jQuery. **I've created json files for diff languages**. It works fine with me **locally**.

But when I use the same project **on server, it gives me 404 not found** for the same json files of those many languages! I've checked with the file names, paths and typos, it's proper. Also **There isn't any problem with the file access!**

/myDemo.com/locales/en/translations.json 404 (Not Found)

Do I miss something?

**Comment by jamuhl** [comment]
really. i bet there is a problem with file access over xhr -> why else would you get a 404?

that file is not found - try manually - check the network tab in your developer console...code does never lie ;)

**Comment by aniruddhashevle** [comment]
The application/json MIME type was not allowed on the server! Hence that error was there.
It's now sorted. It works smooth. Thanks.

**Comment by jamuhl** [comment]
Awesome. Glad you found it.
