### ISSUE TITLE
Crash in getPluralFormsOfKey

### ISSUE THREAD

**Issue by scharf** [i18next/i18next#1032]
I get a crash in [`getPluralFormsOfKey`](https://github.com/i18next/i18next/blob/3cb51cea60209131152f4835e649561dc0a381ec/src/PluralResolver.js#L107) when `rule` is undefined.

```javascript
getPluralFormsOfKey(code, key) {
    const ret = [];

    const rule = this.getRule(code);

    rule.numbers.forEach((n) => { // CRASH if rule is undefined!
      const suffix = this.getSuffix(code, n);
      ret.push(`${key}${suffix}`);
    });

    return ret;
  }
```

**Comment by jamuhl** [comment]
i guess that's related to using the development language code of `code` which is not supported.

i18next uses lng=dev for developer language.

But you easily can add a rule for your language by calling:

`i18next.services.pluralResolver.addRule('yourLanguage', {  numbers: [1,2], plurals: function(n) {return Number(n != 1);} });`

**Comment by jamuhl** [comment]
beside that i will add an extra validation there so it does not result in an exception.

**Comment by jamuhl** [comment]
will be fixed in next version by: https://github.com/i18next/i18next/commit/95f8a3eb065d929a70dd5f04a4bb14f7676e9bfe

**Comment by scharf** [comment]
I was a bit frustrated when I discovered `i18n` because I could not find a good document describing how to use it. Below I describe what I found useful for the project I am working on. 

## Why the language `code`?

I added the language `code` because I wanted a language that is generated form the code (using `defaultValue`) and use it as *Reference Language*. If `dev` can be used for that purpose, I'm happy to use it.

In fact, I created my own `t` function (which uses internally `i18next.t`) to easily add a default translation from within the code. Instead of writing:

```js
t('login.username', { defaultValue: 'Username' });
t('todo.list.title', { defaultValue : 'Show {{count}} Todos', count: todoCount });
```

If the second argument is a string, I use the string as `defaultValue`. Therefore I can write:

```js
t('login.username', 'Username');
t('todo.list.title', 'Show {{count}} Todos', {count: todoCount});
```

### Advantages of  the`code` language and the extended `t` function

- I see the default translation in the code. This makes finding the code for a UI element easy: I just switch to the `code` language and I can search the string in the UI in my code.
- When I change the label in the code, it shows up in Locize (the `code` language is not supposed to be changed).
- Translators see a useful default translation and they don't have to guess where `foo.bar.baz` is in the UI and what the label could be.
- If for some reasons the translation cannot be loaded, the UI shows reasonable default translations (instead of keys)
- In my `t` function, I added some (pseudo) languages 
  - `keys` which only shows the keys (that way I can see all strings that are translated in the UI)
  - `keys-lang` which shows *keys* plus the `lang` translation  (e.g. **`[login.username] Username`**)

**Comment by jamuhl** [comment]
Yes....`dev` is in i18next what you use as `code` - dev is the default fallbackLng which should be set eg. to `en` in production.

your extended t function is not needed. i18next does this already. You can even set a third param to submit the context/description for translators.

to show keys in your app you can toggle language to `cimode`

**Comment by jamuhl** [comment]
you even can set https://www.i18next.com/configuration-options.html#missing-keys updateMissing to true -> that way if you change the defaultValue for your referenceLanguage it will update that on locize.

**Comment by jamuhl** [comment]
did you already try to include the incontext-editor?

**Comment by scharf** [comment]
> `dev` is in i18next what you use as `code`

I will change this...

> if you change the defaultValue for your referenceLanguage it will update that on locize

Ah, i `updateMissing` only works if the current language is the referenceLanguage!

I am already using `updateMissing`. However, during development, it may create keys that I don't want to see. Therefore I added a toggle in dev mode so that I can send the Keys only when I think the UI is good enough. 

I did not see any description of the `cimode`.

What I am missing, is a practical guide how to use `i18next`. The documentation I found so far is a bit like describing each of the pieces of some IKEA Furniture without describing how it all has to be plugged together.

What I describe above is what I came up with, but I have no idea if that is best practices for i18next of if I am thinking in the wrong direction...

**Comment by jamuhl** [comment]
yes...updateMissing only for referenceLanguage - while saveMissing will go through to be mapped down to fallback and only submitted if equal referenceLanguage.

cimode: https://www.i18next.com/faq.html#process

the "problem" with i18next is it's made to suit you...more or less you can configure it to your will...but most time the defaults should work out...and to be honest...my writing skills are not the best.

Also it's rather difficult to go from getting started https://www.i18next.com/getting-started.html#basic-sample to all the possible details like cimode which you might / might not need. Plus when it comes to framework specific topics like using it with react (just as a sample) there a additional documentations: https://react.i18next.com/ making it not simpler ;)

**Comment by scharf** [comment]
> did you already try to include the incontext-editor?

No! I'll take a look!

**Comment by jamuhl** [comment]
locize-editor: https://github.com/locize/locize-editor#i18next-with-i18next-locize-backend

**Comment by jamuhl** [comment]
should be rather straight forward

**Comment by jamuhl** [comment]
closing for now...fix will be in the next version.
