### ISSUE TITLE
missing interpolation callback

### ISSUE THREAD

**Issue by JanTrotnow** [i18next/i18next#1033]
I wonder if there is any possibility to register a callback for missing interpolation values. I'm thinking about a construct similar to the missingKeyHandler. Is there any way to do this? If not, where to add it?

I need to extract the missing placeholder (not the dynamic value) of a translation somehow.

e.g.

If i use

`i18next.t('key', { what: 'i18next' });`

with a translation like

`{
    "key": "{{what}} is {{how}}"
`}

I'd like to get information about the missing `{{how}}`

Thank you in advance!

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L97 would be here

**Comment by antoniusostermann** [comment]
+1 for https://github.com/i18next/i18next/pull/1039

**Comment by jamuhl** [comment]
published in i18next@10.6.0
