### ISSUE TITLE
ESLint complains about ambiguous import

### ISSUE THREAD

**Issue by pke** [i18next/i18next#1035]
Given this code

```es6
import i18n from "i18next"

i18n
.use(xhr)
```

ESLint complains
> message: 'Caution: `i18n` also has a named export `use`. Check if you meant to write `import {use} from 'i18next'` instead. (import/no-named-as-default-member)' at: '3,1'

**Comment by jamuhl** [comment]
Yes...there is also a named export for use.

https://github.com/i18next/i18next/blob/master/src/index.js#L19

reason: https://github.com/i18next/i18next/issues/873

eslint is so clever...but sometimes just to clever ;)

**Comment by pke** [comment]
Thanks for the swift answer. However I am still confused. How should I import `i18n` to make ESLint happy?

**Comment by jamuhl** [comment]
you should not listen to eslint...all done correct...just add an eslint ignore comment.

**Comment by pke** [comment]
Or like this in my module:

```es6
import { use } from "i18next"
import xhr from "i18next-xhr-backend"

const i18n = use(xhr)
.use(LanguageDetector)

export default i18n
```

**Comment by MaGaKZ** [comment]
Try 
`import * as i18n from 'i18next';`
