### ISSUE TITLE
Using the same array on `whitelist` and `preload` causes `cimode` to be preloaded

### ISSUE THREAD

**Issue by ghengeveld** [i18next/i18next#1036]
Given the following config:
```js
const locales = ["nl", "fr"]
const options = {
  whitelist: locales,
  preload: locales,
  ...
}
```

On the server (Next.js) this leads to `Error: ENOENT: no such file or directory, open '.../locales/cimode/common.json'`, and in the browser it attempts to load these `cimode` language files through AJAX leading to 404 errors.

Turns out this error is caused by the `whitelist` array being [mutated in-place](https://github.com/i18next/i18next/blob/15d7e18e44640fc0a596e11a65f7e675602d2cae/src/defaults.js#L73). The workaround is obviously to avoid passing the same array to both properties, but to me this looks like an API bug.

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/src/defaults.js#L73 will change that line for next version to create a clone of the array

**Comment by ghengeveld** [comment]
Here's the PR: #1037
