### ISSUE TITLE
Doesn't work with Angular AOT builds

### ISSUE THREAD

**Issue by k-schneider** [i18next/i18next#1038]
Hello,

I'm trying to use i18next in an Angular 5 project and importing it in Typescript with: `import * as i18next from 'i18next';`.  This works great while developing locally (JIT compiler).

When running a "prod" build using `ng build --prod` this uses the AOT compiler and applies tree shaking, etc.  The build runs through fine with no errors but when trying to host the resulting application it fails miserably with a pretty generic bundle error:

```
Uncaught (in promise): TypeError: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at e.use (main.a0a26b2f184d0334c2db.bundle.js:1)
    at main.a0a26b2f184d0334c2db.bundle.js:1
```

Running a prod build with AOT disabled `ng build --prod --aot=false` works as expected.

I've tried variations on the import.. es/umd bundles directly, importing the specific functions instead of the default export, etc.  Nothing works.

Wondering if anyone has any ideas why this might be?

Thanks.

**Comment by k-schneider** [comment]
Changed to `import { default as i18next } from 'i18next';` and that seems to have fixed it up.

**Comment by jamuhl** [comment]
looks like your adding a plugin to i18next via i18next.use which gets imported as undefined...out of that you get an error here: https://github.com/i18next/i18next/blob/master/src/i18next.js#L168

find out which plugin it is and by guessing import it as `import { default as abc } from 'plugin'`
