### ISSUE TITLE
When using cloneInstance and keySeparator and dot in a translation key, I get: TypeError: Cannot set property 'undefined' of undefined

### ISSUE THREAD

**Issue by alcalyn** [i18next/i18next#1041]
I encounter a bug that prevent me to put dots in translation key, or prevent to translate.

I can easily reproduce it with nodejs 8.9 from scratch:

## Steps to reproduce

``` bash
npm install i18next
```

File **index.js**:
``` js
const i18next = require('i18next');

const i18nBase = i18next.createInstance();

i18nBase
    .init({
        defaultNS: 'translation',
        fallbackLng: 'en',
    })
;

i18nBase.addResource('en', 'translation', 'hello.world', 'Hello Word base');


const i18nExtended = i18nBase.cloneInstance({
    keySeparator: false,
});

i18nExtended.addResource('en', 'translation', 'Hello World', 'Hello Word extended WITHOUT point');
i18nExtended.addResource('en', 'translation', 'Hello World.', 'Hello Word extended WITH point');

console.log(i18nBase.t('hello.world'));
console.log(i18nExtended.t('Hello World'));
console.log(i18nExtended.t('Hello World.'));
```

## Expected

```
$ node index.js 
Hello Word base
Hello Word extended WITHOUT point
Hello Word extended WITH point
```

## Actual

```
$ node index.js 
/.../node_modules/i18next/dist/commonjs/utils.js:56
  obj[k] = newValue;
         ^

TypeError: Cannot set property 'undefined' of undefined
    at Object.setPath (/.../node_modules/i18next/dist/commonjs/utils.js:56:10)
    at ResourceStore.addResource (/.../node_modules/i18next/dist/commonjs/ResourceStore.js:91:11)
    at I18n._this2.(anonymous function) [as addResource] (/.../node_modules/i18next/dist/commonjs/i18next.js:185:48)
    at Object.<anonymous> (/.../index.js:20:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
```

## Notes

- When moving `keySeparator: false,` from the extended to the base instance, all is working fine, and I get the expected output.
- When commenting the line which adds the translation key with dot, `i18nExtended.addResource('en', 'translation', 'Hello World.', 'Hello Word extended WITH point');`, the error does not appear, and all works but the last string is not translated because removed.

## Why am I doing this

To prevent XY problem, why am I doing this ? Because I use the main instance for translating my app which uses translation keys like `hello.world`. But for a little part of my application, I don't use this translation keys format, but plain english text like `Hello world.`. So I actually use `cloneInstance` in which I want to disable separators, but translations with a dot in the text is not translating. It works when moving separator disable in the main i18next instance, but sure it breaks the rest of my application translation.

**Comment by jamuhl** [comment]
cloned instances get the same resource store which gets it separators set on first init. So there is no option to change that on a second clone.

**Comment by jamuhl** [comment]
only option would be calling `t` like `xonsole.log(i18nExtended.t('Hello World', { keySeparator: '###' }));` to get that result for now.

**Comment by alcalyn** [comment]
Ok, I didn't know some options has different behavior as an other during clone. When I see this unit test: https://github.com/i18next/i18next/blob/ac314338bfc8b6955d9002a961c9596ee401acc2/test/i18next.spec.js#L36 it appears no matter the option, it is inherited (here foo and bar).

Also, I can't override `keySeparator` in clone, but I can do it in every `t()` functions ? I find it not intuitive, and I prefer not to pass same options in every `t()`.

But I see your point when you're saying that options somehow depends on resource store, so I'll maybe need to create two differents i18next instance from `createInstance` as there are differents. But I still need to duplicate some base options like `fallbackLng`, plugins and plugins options like `LngDetector`.

**Comment by jamuhl** [comment]
More or less the problem we never thought about your case of using keySeparator=false and default on the same project.

**Comment by alcalyn** [comment]
Ok I see, this is because at this point:

https://github.com/i18next/i18next/blob/f05b0abccd7e478bb32676216efd961ac2d74e8f/src/i18next.js#L49

It does not initialize all services, and reuse the same initial ResourceStore:

https://github.com/i18next/i18next/blob/f05b0abccd7e478bb32676216efd961ac2d74e8f/src/i18next.js#L101-L105

without the overridden options

**Comment by alcalyn** [comment]
Is it relevent if I submit a PR with this fix ?

**Comment by jamuhl** [comment]
creating a new store is not an option as people rely on them being the same in case of a clone...

what we might do is passing down the options here...https://github.com/i18next/i18next/blob/master/src/Translator.js#L270 but also not sure if that is the best solution to go for as it might introduce unwanted side effects.

Not sure but honestly i guess as long your use case is an edge case monkey patching that in userland might be best by setting a new resource store after cloning...

**Comment by alcalyn** [comment]
Ok, I finally made it works by creating two instances but reusing options and override it before creation:

``` js
const i18next = require('i18next');

const options = {
    defaultNS: 'translation',
    fallbackLng: 'en',
};

const i18nBase = i18next.createInstance();

i18nBase
    .init(options)
;

const i18nExtended = i18nBase.createInstance();

i18nExtended.init({
    ...options,
    keySeparator: false,
});
```

It works because I can assume this is two differents logics and two differents resources stores.

Thank you !
