### ISSUE TITLE
integrate i18next with redux

### ISSUE THREAD

**Issue by assafb81** [i18next/i18next#1042]
Hi,
great package - very helpful and with great documentation.

I encounter one issue.
I want to let my application user to change application language.
I am using `i18next-react-native-language-detector` to detect automatically the device locale for initialization.
And I am using `i18n.changeLanguage(lng);` to change app language.

How I do use the Cache from the 2nd time the application starts? i.e the cached language is empty?
Is there a way to enable Cache from the code?

my `i18n.js` file looks like:
```
import i18next from 'i18next';
import i18nextReactNative from 'i18next-react-native-language-detector';
import Cache from 'i18next-localstorage-cache';
import en from './en';
import de from './de';
let translate; // eslint-disable-line
i18next
    .use(i18nextReactNative)
    .use(Cache)
    .init({
        fallbackLng: 'en',
        resources: { en, de },
        react: { wait: false },
        cache: {
            enabled: true,
            expirationTime: Infinity,
        },
        ns: ['common'],
        defaultNS: 'common',
        debug: true,
        interpolation: {
            escapeValue: false, // not needed for react!!
            formatSeparator: ',',
            format(value, format) {
                if (format === 'uppercase') return value.toUpperCase();
                return value;
            },
        },
    }, (err, t) => {
        translate = t;
    });
export { translate as t };
export default i18next;
```

**Comment by assafb81** [comment]
I don't use express...basically I don't have back-end side. Everything is done on in th app.

**Comment by jamuhl** [comment]
it's not about express - that detector is just a sample of doing async detection (as async storage can't get items synchronous)

**Comment by assafb81** [comment]
sorry, I could not understand:
1. where do I define `options` object?
2. how do I check if its there is a cached language or not? how it connect to the store(async storage)?

**Comment by jamuhl** [comment]
You do not need the express-middleware stuff. Just your custom detector.

The detect function should / could first look in async-storage else cache makes no sense -> cache should set not get.

use callbacks -> there is no promise support

sorry - sample for async is here: https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/js/i18n.js#L7


```js
import locale from 'react-native-locale-detector';
export default {
    init: Function.prototype,
    type: 'languageDetector',
    async: true,
    detect: (callback) => {
       const languageCode = await AsyncStorage.getItem('languageCode');
       callback(langugeCode || locale);
    },
    cacheUserLanguage: (lng) => {
        AsyncStorage.setItem('languageCode', lng);
    }
};
```

**Comment by assafb81** [comment]
are missing `async`?

```
    detect: async (callback) => {
       const languageCode = await AsyncStorage.getItem('languageCode');
       callback(langugeCode || locale);
    },
    cacheUserLanguage: async (lng) => {
        AsyncStorage.setItem('languageCode', lng);
    }
```
?

**Comment by jamuhl** [comment]
no...detect function expects using callbacks...not async-await

**Comment by assafb81** [comment]
I can't run without `async`.
when I add this I am getting an error - `lng.toLowerCase is not a function` in `Translator.translate`.
`Translator.js` 114:19

**Comment by jamuhl** [comment]
```
detect: async (callback) => {
       const languageCode = AsyncStorage.getItem('languageCode', lng => callback(lng || locale));
       ;
    },
```

or something like that...

**Comment by assafb81** [comment]
```
import locale from 'react-native-locale-detector';
import { AsyncStorage } from 'react-native';

export default {
    init: Function.prototype,
    type: 'languageDetector',
    async: true,
    detect: (callback) => {
        const languageCode = AsyncStorage.getItem('languageCode');
        callback(languageCode || locale);
    },
    cacheUserLanguage: Function.prototype,
};
```

I am getting a red screen with this:

![screenshot_20180401-154927 2](https://user-images.githubusercontent.com/28925534/38173288-68108528-35c4-11e8-94cc-fc21544663a2.png)

**Comment by jamuhl** [comment]
set react.wait true in init options

**Comment by assafb81** [comment]
same error.
in my i18n.js I changed the code to:
```
...
.init({
        fallbackLng: 'en',
        resources: {
            en,
            de,
        },

        react: {
            wait: true,
        },
....
```

**Comment by assafb81** [comment]
when I moved the code to the same file as i18n.js, same as the [exmple](https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/js/i18n.js#L7)

I don't call `languageDetector` lines of code

**Comment by jamuhl** [comment]
idk

**Comment by assafb81** [comment]
ok, I got some progress.
my i18n.js looks like this now:

```
import i18next from 'i18next';
import locale from 'react-native-locale-detector';
import i18nextReactNative from 'i18next-react-native-language-detector';
import { AsyncStorage } from 'react-native';

import en from 'PPG/src/i18n/en';
import de from 'PPG/src/i18n/de';

const STORAGE_KEY = '@APP:languageCode';
let translate; // eslint-disable-line

const languageDetector = {
    type: 'languageDetector',
    async: true, // flags below detection to be async
    detect: async (callback) => {
        const lng = await AsyncStorage.getItem(STORAGE_KEY);
        callback(lng || locale);
    },
    init: () => {},
    cacheUserLanguage: async (lng) => {
        AsyncStorage.setItem(STORAGE_KEY, lng);
    },
};

i18next
    .use(i18nextReactNative)
    .use(languageDetector)
    .init({
        fallbackLng: 'en',
        resources: {
            en,
            de,
        },
        react: {
            wait: true,
        },
        ns: ['common'],
        defaultNS: 'common',
        debug: true,
        interpolation: {
            escapeValue: false, // not needed for react!!
            formatSeparator: ',',
            format(value, format) {
                if (format === 'uppercase') return value.toUpperCase();
                return value;
            },
        },
    }, (err, t) => {
        translate = t;
    });
export { translate as t };
export default i18next;
```

I need to switch the order or the `use().use()`

since I don't know how to dispatch a redux action from here, I saved the language code in different key and I upload and save it separately from the rest of the data.

Now I encounter different issue: 
`(0, _i18n.t) is not a function` when it tries to translate somewhere in the application.

When I used cache package , it seems to work except one point - use device local on the very first time, on the rest use the redux store.

maybe that is the way to do it?

**Comment by assafb81** [comment]
the fact that I am using `import i18nextReactNative from 'i18next-react-native-language-detector';`
and not `import { reactI18nextModule } from 'react-i18next';` might have an impact?

**Comment by jamuhl** [comment]
no...different modules doing different things...the language detector detects language on init. the other asserts like the i18nextProvider that t function is available via global scope to all components (instead of using react context)

**Comment by assafb81** [comment]
what about the issue from the previous [comment ](https://github.com/i18next/i18next/issues/1042#issuecomment-377810939):
(0, _i18n.t) is not a function when it tries to translate somewhere in the application.

**Comment by jamuhl** [comment]
there is no issue...all samples work...it works on react-native on our own project and on others...this is not an issue with i18next, or react-i18next...its an issue with YOUR code...not here to do your work...ask this at stackoverflow or your lead developer....

**Comment by assafb81** [comment]
@jamuhl Thanks for your help up until now

**Comment by jamuhl** [comment]
hope you find the bug

**Comment by assafb81** [comment]
not yet. I am trying to figure out why?
I manage to write a proper `detect()` method (I think): 
```
const languageDetector = {
    init: Function.prototype,
    type: 'languageDetector',
    async: true, // flags below detection to be async
    detect: () => AsyncStorage.getItem(STORAGE_KEY)
        .then((savedDataJSON) => {
            const lng = (savedDataJSON) ? JSON.parse(savedDataJSON): 'null';
            const selectLanguage = lng || locale;
            console.log('detect - selectLanguage:', selectLanguage);
            return selectLanguage;
        }),
    cacheUserLanguage: Function.prototype,
```
I can see in the logs that its finding the right language but in `node_modules\\i18next\dist\commonjs\i18next.js` in method `I18n.prototype.getFixedT` the `lng` is null :(

**Comment by assafb81** [comment]
Thanks for your help @jamuhl.
Eventually this is the language detector I wrote:
```
const languageDetector = {
    init: Function.prototype,
    type: 'languageDetector',
    async: true, // flags below detection to be async
    detect: (callback) => AsyncStorage.getItem(STORAGE_KEY)
        .then((savedDataJSON) => {
            const lng = (savedDataJSON) ? JSON.parse(savedDataJSON): null;
            const selectLanguage = lng || locale;
            console.log('detect - selectLanguage:', selectLanguage);
            callback(selectLanguage);
        }),
    cacheUserLanguage: (lng) => {
        // do nothing
        console.log('detected lang is:', lng);
    }
```

1. I leave to the app the responsibility to save in the AsyncStorage.
2. I wanted to use the default `done` method of `i18next` package. (If you have better solution I will be more than happy to hear).

And my **i18n.js** file looks like this:
```
i18next
    .use(languageDetector)
    .init({
        fallbackLng: 'en',
        resources: {
            en,
            de,           
        },

        react: {
            wait: false,
        },

        // have a common namespace used around the full app
        ns: ['common'],
        defaultNS: 'common',

        debug: true,

        interpolation: {
            escapeValue: false, // not needed for react!!
            formatSeparator: ',',
            format(value, format) {
                if (format === 'uppercase') return value.toUpperCase();

                return value;
            },
        },
    }, (err, t) => {
        translate = t;
    });

export { translate as t };

export default i18next;
```
