### ISSUE TITLE
Can not get current language 

### ISSUE THREAD

**Issue by MattBoatman** [i18next/i18next#1045]
When I query `i18next` for current language it always comes back undefined. Retrieving keys and changing languages works fine. 
```javascript
import i18next from 'i18next';
import { reactI18nextModule } from 'react-i18next';
import en_US from './en_US.json';
import fr_CA from './fr_CA.json';
import es_US from './es_US.json';
import en_CA from './en_CA.json';

i18next.use(reactI18nextModule).init({
    resources: {
        en_US: { translations: en_US },
        fr_CA: { translations: fr_CA },
        es_US: { translations: es_US },
        en_CA: { translations: en_CA },
    },
    lng: 'en_US',
    fallbackLng: 'en_US',
    ns: ['translations'],
    defaultNS: 'translations',
    debug: true,
    react: {
        wait: true,
        defaultTransParent: 'span',
    },
});


export default i18next;
```

```javascript
import React from 'react';
import i18next, { t, changeLanguage, language } from 'i18next';

export const getLocale = () => {
    return language; //this will always be undefined,
};
```

Console logging out `i18next` shows this 
![screen shot 2018-04-17 at 8 56 12 am](https://user-images.githubusercontent.com/3319285/38870843-0e244800-421d-11e8-979f-13f350510081.png)

**Comment by MattBoatman** [comment]
That also returns `undefined`
![screen shot 2018-04-17 at 9 13 13 am](https://user-images.githubusercontent.com/3319285/38871642-6c819036-421f-11e8-94fe-7a7f97662a5f.png)

**Comment by MattBoatman** [comment]
![screen shot 2018-04-17 at 9 14 19 am](https://user-images.githubusercontent.com/3319285/38871698-90f0bfa0-421f-11e8-9128-2c88a6f9a9a5.png)

**Comment by MattBoatman** [comment]
Still the same problem after that change.

**Comment by MattBoatman** [comment]
![screen shot 2018-04-17 at 9 27 52 am](https://user-images.githubusercontent.com/3319285/38872530-77772a76-4221-11e8-9c05-fea7b5d02d10.png)
It looks like a language property is within the `default` object?

**Comment by jamuhl** [comment]
hm...do you instantly call that...almost impossible after init that value is set:

`i18next.init(opts, () => { console.warn(i18next.language); });`

**Comment by MattBoatman** [comment]
![screen shot 2018-04-17 at 9 30 53 am](https://user-images.githubusercontent.com/3319285/38872710-ea6c757c-4221-11e8-8a2c-39fd8f
![screen shot 2018-04-17 at 9 31 26 am](https://user-images.githubusercontent.com/3319285/38872724-f3c963fa-4221-11e8-870c-440e84a51f8a.png)
90923b.png)
Added that and still getting the same. I am calling `i18next.language` throughout the application

**Comment by MattBoatman** [comment]
I also changed my init file from exporting `i18next` to `i18n` to match the examples

**Comment by jamuhl** [comment]
Just made a fiddle: https://jsfiddle.net/Lf0n30xu/1/

language is set

**Comment by jamuhl** [comment]
are you using typescript?

**Comment by MattBoatman** [comment]
I am not using typescript.. `"i18next": "^10.6.0",`. Not sure what is going haywire

**Comment by jamuhl** [comment]
Also works here: https://codesandbox.io/s/n79wyvow7j see index.js

**Comment by MattBoatman** [comment]
I fixed it, it seems like accessing the `language` like this `import i18next, { t, changeLanguage, language } from 'i18next';` totally breaks it. As soon as i removed any reference to that it started to working. Thanks for the debugging help.

**Comment by MattBoatman** [comment]
For anyone else following, I was able to keep my locales using `_`

**Comment by jamuhl** [comment]
Just for the `_` ... keep in mind i18next will use `split('-')` everywhere -> so some features will not work correctly (whitelist, plural, ...)

**Comment by MattBoatman** [comment]
That's good to know, I'll leave as is then.

**Comment by HuyAms** [comment]
> are you using typescript?

I deal with the same issue and I use typescript

**Comment by jamuhl** [comment]
@HuyAms please open a new issue with detailed information so we can reproduce...i can't remote guess your code  😁
