### ISSUE TITLE
Make i18n class exportable. 

### ISSUE THREAD

**Issue by manixate** [i18next/i18next#1047]
Can we make `i18n` class exportable too? Currently, only the new object is exported. 
https://github.com/i18next/i18next/blob/b36c0a44bdfaae766944509abe0e290d13dad489/src/i18next.js#L14

The reason is basically for testing because during testing if you only use i18n then the side-effect is passed to all the other places too. e.g I am testing 2 components that are being used with `TranslateHOC`, if `componentA` changes language on i18n then `componentB` also receives the callback which I don't want to be the case. 

I can mitigate it by not wrapping my components while exporting with translate but rather by exporting them separately with the HOC. But I think i18n class should also be made exportable.

**Comment by adrai** [comment]
@jamuhl has to decide this... (but he is on vacation, right now)
Is it possible for your use case to first https://www.i18next.com/overview/api#cloneinstance before using it?
Or try to get it via: https://stackoverflow.com/questions/7662147/how-to-access-object-prototype-in-javascript

**Comment by jamuhl** [comment]
There is i18next.createInstance which gives you a new instance. Rather sure that meets your need?

**Comment by manixate** [comment]
Yeah sorry, totally missed that from the docs.
