### ISSUE TITLE
reloadResources() does not emit event 'loaded'

### ISSUE THREAD

**Issue by kennyfowler** [i18next/i18next#1053]
it seems that  calling `reloadResources()` is never emtting `loaded` because it does not use the queue (`loaded `is only emitted when processing the queue)

is this intended?

**Comment by jamuhl** [comment]
yes...as reload does not change the state directly...was ready before reloading, is ready after reloading. But open for a PR adding some reloaded event if you need that.

**Comment by kennyfowler** [comment]
no, you can close this, thx for asking
