### ISSUE TITLE
Using context with deep keys

### ISSUE THREAD

**Issue by LaurentGoderre** [i18next/i18next#1055]
Is it possible to use context with deep keys? i.e.:

```
{
  "key": {
    "nested": "Foo bar",
    "nested_short": "fb"
  }
}
```

`i18next.t("key.nested", {context: "short"});`

**Comment by jamuhl** [comment]
i guess so: https://jsfiddle.net/etgLqyc7/

**Comment by LaurentGoderre** [comment]
So sorry, I had wrong nesting
