### ISSUE TITLE
placeholder translation cannot work with i18next-express-middleware

### ISSUE THREAD

**Issue by hankivan** [i18next/i18next#1056]
I try to use i18next in my express-pug app.
It work find in 
`li 
                  a(href='/form') 
                    =t('Form') `

but cannot work fine in attribute .
pug content
`tr    From
            div
              _input.cnamestyle(data-i18n='[palceholder]company name')`_

package.json
`    "i18next": "^11.3.2",
    "i18next-express-middleware": "^1.1.1",
    "i18next-node-fs-backend": "^1.0.0",`

app.js
```
var i18n = require('i18next');
var i18nFsBackend = require('i18next-node-fs-backend');
var i18nMiddleware = require('i18next-express-middleware');
// i18next setting
i18n.use(i18nMiddleware.LanguageDetector) // auto-detect client's language
    .use(i18nFsBackend)
    .init({
            fallbackLng: "en", // backup language
            backend: {
                loadPath:  __dirname + '/app/server/locales/{{lng}}/translation.json',
            }
        });

app.use(i18nMiddleware.handle(i18n, {

}));
```

How can I fix this problem? Thanks.

**Comment by jamuhl** [comment]
`tr From div _input.cnamestyle(data-i18n='[palceholder]company name')` where you got that syntax from? that looks like clientside integration using jquery-i18next - not pug

pug would be something like: `input.cnamestyle(placeholder=t('company name'))` i guess

**Comment by hankivan** [comment]
Thanks, it works by`input.cnamestyle(placeholder=t('company name'))`.
