### ISSUE TITLE
Something wrong with period

### ISSUE THREAD

**Issue by Skyge** [i18next/i18next#1060]
There is something wrong with translation when i use i18n in React.
ok, i config like this in a file named i18n.jsx:

    import i18n from 'i18next';
    import XHR from 'i18next-xhr-backend';
    import {reactI18nextModule} from 'react-i18next';
    i18n
        .use(XHR)
        .use(reactI18nextModule)
        .init({
            fallbackLng: 'en',
            backend:{
                loadPath: '/static/locales/{{lng}}/{{ns}}.json'
            },
            // have a common namespace used around the full app
            ns: ['translations'],
            defaultNS: 'translations',
            debug: true,
            interpolation: {
                escapeValue: false, // not needed for react!!
             },

            react: {
                wait: true
            }
        });
    export default i18n;

i use like this:
index.jsx:

    import React from "react";
    import ReactDOM from "react-dom";
    import {I18nextProvider} from "react-i18next";
    import i18n from "../common/i18n.jsx";
    import App from "./app.jsx";
    ReactDOM.render(
      <I18nextProvider i18n={i18n}>
        <App/>
      </I18nextProvider>,
      document.getElementById("root")
    );

i write in app.jsx:

    import i18n from "../../common/i18n.jsx";
    class App extends React.Component{
        render(){
            return (
             <Content/>
            )
        }}

i write in Content.jsx:

    import React from 'react';
    import {translate} from "react-i18next";

    @translate(['translations'], {wait: true})
    class ContentHead extends React.Component {
        render() {
        const {t} = this.props;
        return (
            <div>
                <ul>
                    <li>{t('此处价格为2.8')} ></li>
                </ul>
              </div>
            )}}

these all my writing,i can get the correct translation when i repalce  {t('此处价格为2.8')}  with {t('此处价格')},so maybe the question is about the punctuation period,maybe i should add another configuration parameter or something else.if you can give me a direction to search, i will be grateful.

**Comment by jamuhl** [comment]
set keySeparator to false or to something not used: https://github.com/i18next/react-i18next/blob/master/example/locize-example/src/i18n.js#L23

the `.` separates so you could do like in the samples: https://www.i18next.com/translation-function/essentials#accessing-keys

so disabling that feature will do the trick for you: https://www.i18next.com/principles/fallback#key-fallback

**Comment by Skyge** [comment]
@jamuhl  Thank for your advice,i had tried to use parameter  keySeparator : 'false',but it didnot work,so i open this issu,but you gave me the same method i had done,i know there is something wrong with my Explorer, so i clear all my caches, and now it works.Thanks for you help even though i asked a silly question. Best wishes!

**Comment by jamuhl** [comment]
glad it works for you now...if there is anything else let me know.
