### ISSUE TITLE
Plurals don't work

### ISSUE THREAD

**Issue by pedrofracassi** [i18next/i18next#1061]
My ``music.json` namespace looks like this:
```json
  "addedFromPlaylist": "**{{count}} song** from {{- playlistName}} {{duration}} has been added to the queue!",
  "addedFromPlaylist_plural": "**{{count}} songs** from {{- playlistName}} {{duration}} have been added to the queue!"
```

And my code looks like this:
```js
t('music:addedFromPlaylist', {count, playlistName, duration})
```

But when I run it I always get `addedFromPlaylist`, no matter what the `count` is. Am I doing something wrong?

**Comment by jamuhl** [comment]
if you get `addedFromPlaylist` it looks like translations were not loaded. a) it loads async and you just call t function to early or b) there is something wrong in your configuration / setup

set debug: true on init and check the console output for statements "failed loading"

**Comment by pedrofracassi** [comment]
The translations do load. When I said `addedFromPlaylist` I meant its text. t returns the right text, but in singular form even when count =/= 1

**Comment by jamuhl** [comment]
not sure works on my fiddle: https://jsfiddle.net/eL3f7wyt/

**Comment by jamuhl** [comment]
languages must be in form `en-US` it's what all the detectors will give you.

just replace `_` with `-` before setting lng in i18next - will be the best solution as we rely on that

**Comment by pedrofracassi** [comment]
I can change the folder names on Crowdin to match the format. Thanks for helping me!

**Comment by jamuhl** [comment]
you should use https://locize.com -> to support us (it's the translation management made by us - see whats possible https://www.youtube.com/watch?v=9NOzJhgmyQE&t=17s - not only for react!)

**Comment by pedrofracassi** [comment]
Unfortunately I can't. Our project is open source and the is crowdsourced too. Thanks for suggesting it, tho.

**Comment by jamuhl** [comment]
guess we could close this.

**Comment by chrismacp** [comment]
Ouch this bit me too, spent a while trying to work it out but this ticket saved me. I'm so used to using the underscore format in other tools/languages I didn't even think of it.

**Comment by stee-ren** [comment]
Has something broke in this library. The fiddle posted above doesn't actually work correctly:
https://jsfiddle.net/eL3f7wyt/
If you look carefully, the Singular translation is ALWAYs taken - could this possibly be to do with the local set on the browser (if it isn't with a - instead of a _

**Comment by jamuhl** [comment]
@stee-ren plurals changed: https://www.i18next.com/translation-function/plurals

**Comment by jamuhl** [comment]
@stee-ren in detail: https://www.i18next.com/misc/migration-guide#v-20-x-x-to-v-21-0-0

**Comment by siffash** [comment]
> languages must be in form `en-US` it's what all the detectors will give you.
> 
> just replace `_` with `-` before setting lng in i18next - will be the best solution as we rely on that

Unfortunately we can't change `en_US` to `en-US` (this is what we're getting from the backend and this format is used throughout the whole application). Is it possible to add an internal check in i18next whether `_` is being used instead of `-`, and in this case to replace `_` with `-` only to get the correct plurals?
