### ISSUE TITLE
Use namespace wrong ?

### ISSUE THREAD

**Issue by gfelot** [i18next/i18next#1063]
7 languages to handle. It's easy thanks to i18next.
I also have to translate the legal term of this app. It's a long text made with several paragraph. So I decided to use the namespace feature but surely I didn't understand how to use it right.

`confFile.js`
```javascript
import i18next from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

import de from '../i18n/de.json';
import en from '../i18n/en.json';
import es from '../i18n/es.json';
import fr from '../i18n/fr.json';
import frCGU from '../i18n/fr_CGU';
import it from '../i18n/it.json';
import nl from '../i18n/nl.json';
import pt from '../i18n/pt.json';


i18next.use(LanguageDetector).init({
  resources: {
    de,
    en,
    es,
    fr,
    frCGU,
    it,
    nl,
    pt
  },
  ns: ['common', 'frCGU'],
  defaultNS: 'common',
  detection: { order: ['navigator'] },
  fallbackLng: 'fr',
  // have a common namespace used around the full app
  interpolation: {
    escapeValue: false, // not needed for react!!
    formatSeparator: '.'
  },
  react: { wait: true }
});

export default i18next;
```

`fr.json`
```json
{
  "translation": {
    "title": "Demande d'Assistance",
    "header-contrat": "Mes informations",
    "name": "Nom",
    "firstname": "Prénom",
    "phone": "Tél",
     ...
  } 
}
```
`fr_CGU.json`
```json
{
  "translation": {
    "mention": "Mentions Legales",
    "editor": {
      "title": "Editeurs",
    ...
  }
}
```

And I try to use it like this `t('frCGU:mention')`.

What's wrong with this approach ?

**Comment by jamuhl** [comment]
frCGU is defined as a language, correct would be:

fr.json:
```
{
  "translation": {
    "title": "Demande d'Assistance",
    "header-contrat": "Mes informations",
    "name": "Nom",
    "firstname": "Prénom",
    "phone": "Tél",
     ...
  },
  "cgu": {
    "mention": "Mentions Legales",
    "editor": {
      "title": "Editeurs",
    ...
  }
}
```

`t('cgu:mention') // -> Mentions Legales`
`t('translation:title') // -> Demande d'Assistance === t('title') as translation is default namespace`

if passing resources first level in json is the namespace - using xhr namespaces would be separate files

**Comment by gfelot** [comment]
Ok I see. `translation` is by default the `common` namespace. But how to do it if I wanna split into 2 file `translation` AND `cgu` ?

**Comment by jamuhl** [comment]
Then make something like:

```js
// ...
import translationFR from '../i18n/fr_translation.json';
import cguFR from '../i18n/fr_CGU.json';

// ...
i18next.use(LanguageDetector).init({
  resources: {
    de,
    en,
    es,
    fr: {
      translation: translationFR,
      cgu: cguFR,
    }
    it,
    nl,
    pt
  },
```

those files then should only have the keys (not nested in namespace)...hope you understand how i mean

**Comment by jamuhl** [comment]
Beside that i would consider using a xhr backend and load translations on the fly - to reduce bundlesize. Bundling all translations can increase bundlesize significantly. Or even have a look into https://locize.com for translation management and serving

**Comment by gfelot** [comment]
I'm not familiar with xhr backend and load translation. 
For the namespace you mean that we cannot do `t('cgu:fob.bar')`, right ?

**Comment by jamuhl** [comment]
sure you can

```js
// ...
import translationFR from '../i18n/fr_translation.json';
import cguFR from '../i18n/fr_CGU.json';

// ...
i18next.use(LanguageDetector).init({
  resources: {
    de,
    en,
    es,
    fr: {
      translation: translationFR,
      cgu: cguFR,
    }
    it,
    nl,
    pt
  },
```

with cgu.json
```
{
  fob: {
    bar: 'hello'
  }
}
```

**Comment by gfelot** [comment]
So i don't know what you mean by `those files then should only have the keys (not nested in namespace)...hope you understand how i mean` ;)

**Comment by jamuhl** [comment]
before:

{
  "translation": {
    "mention": "Mentions Legales",
    "editor": {
      "title": "Editeurs",
    ...
  }
}

after

{

    "mention": "Mentions Legales",
    "editor": {
      "title": "Editeurs",
    ...
  
}

**Comment by jamuhl** [comment]
as namespaces no are defined here:

    fr: {
      translation: translationFR,
      cgu: cguFR,
    }

**Comment by jamuhl** [comment]
guess we can close this for now...right?
