### ISSUE TITLE
shows only part of text

### ISSUE THREAD

**Issue by RollinSafary** [i18next/i18next#1064]
if you've

`const value: number = 123456`
`const text:string ='anyString:' + value `
using text in creating text object will show only text after `:`

`const textObject = this.add.text(0, 0, text)`
result is `123456`, but must be `anyString:123456`

if we remove` :` from string, everything works

`const value: number = 123456`
`const text:string ='anyString' + value `
result is` anyString123456`

**Comment by adrai** [comment]
... just guessing...
probably because of the nsSeparator ':' see: https://www.i18next.com/overview/configuration-options
