### ISSUE TITLE
Data load before i18next backend init.

### ISSUE THREAD

**Issue by meganlin** [i18next/i18next#1065]
I used Import data array from the data.js file, and used t('KeyName') in the data.js,
but seems the file load before backend init, and it do the translate but cannot get the lang value.
data.
`import React ,{Component} from 'react';

import Repeator from '../components/Repeator';
import ProdMonitor from '../containers/ProdMonitor';

import i18n from "../../i18n/i18n";

  var tabitemsNew = [
      {
        id: 0,
        title: i18n.t('KeyName'),
        completed: false,
        component: Repeator
      }
    ];

  export default tabitemsNew;`
![-1](https://user-images.githubusercontent.com/8220790/41587462-e16e3874-73e1-11e8-837a-2171e2782354.jpg)

**Comment by jamuhl** [comment]
use: https://www.i18next.com/overview/api#events

or delay translation to rendering

**Comment by meganlin** [comment]
hi, 
thank you for your suggestion.
i use i18n in component, use the translate HOC.
i think it the best way for the solution. 
it work.
