### ISSUE TITLE
Strange problems with path.

### ISSUE THREAD

**Issue by markolofsen** [i18next/i18next#1067]
My repo example with i18 [https://github.com/markolofsen/razzle-material](https://github.com/markolofsen/razzle-material)

When I open [http://localhost:3000/?lng=de](http://localhost:3000/?lng=de) thats route does not work:
[http://localhost:3000/locales/de/translations.json](http://localhost:3000/locales/de/translations.json)

Any ideas?

**Comment by jamuhl** [comment]
idk...looks like you serve them in server...at least:

https://github.com/markolofsen/razzle-material/blob/master/src/server/index.js#L33

looks like:

https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/server.js#L30

**Comment by markolofsen** [comment]
@jamuhl I use `.use('/locales', express.static(__dirname + './../locales'))`because `/locales` folder calls from subfolder.
- /server
-- server.js
- /locales

**Comment by jamuhl** [comment]
no idea if that makes a diff...just test...in the end it's an express issue you will need to make sure those translations are served by your server

**Comment by jamuhl** [comment]
did you figure out what was happening?

**Comment by markolofsen** [comment]
@jamuhl  not yet. I did it with nextjs — all awesome

**Comment by jamuhl** [comment]
so i guess we could close this for now...
