### ISSUE TITLE
Missing languages in the language list

### ISSUE THREAD

**Issue by closingin** [i18next/i18next#1068]
I don't know if this belongs here or in react-18next, but my language list is wrong after instantiation. I can correctly change the language using `changeLanguage()`, but logging the language list never shows the whole list.

```javascript
// Simplified code

import de from './de.json'
import fr from './fr.json'
import en from './en.json'
import es from './es.json'

const resources = { de, fr, en, es } // contains the 'translation' namespace

i18n
  .use(LanguageDetector)
  .init({
    fallbackLng: 'fr',
    resources
  })
```

```javascript
// In a React method

this.props.i18n.changeLanguage('en')

console.log(this.props.i18n.language)   // => en
console.log(this.props.i18n.languages)  // => Array ["en", "fr"]
```

In the above console.log, the only listed languages are the currently selected one and the fallback one. If I change to another language (german for example), it will discard the "en" and change it to "de" : `["de", "fr"]`. But isn't it supposed to display the whole list every time ?

I tried to add these options on init :
```
{
  whitelist: ['fr', 'en', 'es', 'de'],
  preload: ['fr', 'en', 'es', 'de']
}
```

But it doesn't change anything.

**Comment by jamuhl** [comment]
no...sorry for being unclear in documentation:

i18n.language -> will be whatever was detected or set during init -> so basically the users choice
i18n.languages -> will be the ordered list of languages that will be used to lookup translations, eg. ["en", "fr"] -> will first try to find a translation key in en and if not found in fallback "fr"

**Comment by closingin** [comment]
So you mean that when I use `changeLanguage()`, it just pushes the user's choice to the top of the array, and i18n selects the first available language in this array ? If so, yes documentation is very unclear ! Thanks for clarification though.

Do I have a way to know the entire list of available languages so ? Currently I loop through the keys of `i18n.options.resources`, but I don't know if that's a good idea.

**Comment by jamuhl** [comment]
no lets try again:

i18next.language - is either detected language or what you set on init or i18next.changeLanguage
i18next.languages - is the lookup hierarchy of locales based on i18next.language combined with your set fallback and whitelist settings

so if you `i18next.changeLanguage('ru-RU')` it will set i18next.language to ru-RU and as you do not define a whitelist i18next.languages will be ['ru-RU', 'ru', 'fr'] in your case as you did not define a whitelist. (Having a xhr backend it now would try to load ru-RU and ru) -> So it will just find translations on fr as ru-RU and ru are empty.

**Comment by closingin** [comment]
That's kind of what I said, I guess. Anyway. What about my second question ?

**Comment by jamuhl** [comment]
There is no list of languages loaded into the resource store if you mean that. It's a non relevant information for i18n -> important is only target language and what we can best provide (fallback)

**Comment by jamuhl** [comment]
But i guess `Object.keys(i18next.services.resourceStore.data);` would give you a list of every locale loaded into i18next

**Comment by closingin** [comment]
I would use it to generate a dynamic language selector on a menu, but alright. Thanks for your fast replies ! 👍

**Comment by jamuhl** [comment]
ok i see...guess you can either pull those like mentioned Object.keys(i18next.services.resourceStore.data); or provide them yourself...as you know which languages you have.

Using our Translation management https://locize.com you would be able to get the languages from the used backend or API: https://docs.locize.com/integration/api#fetch-the-available-languages

**Comment by MariusMeiners** [comment]
the documentation should be updated as this is really confusing :(

**Comment by jamuhl** [comment]
@MariusMeiners  regarding what

**Comment by PeterBenc** [comment]
> @MariusMeiners regarding what

One would expect `languages` to include all defined languages in resources. (I just spent half an hour debugging this) IMO if you don't want to keep such a list in the i18n the `languages` should be renamed to something more specific. 

I also wanted to loop through those display them in simple select.
```
<select onChange={handleChange}>
      {i18n.languages.map((language, i) => (
        <option key={i} value={language} selected={language === i18n.languages[0]}>
          {languageLabels[language]}
        </option>
      ))}
 </select>
```

and I expected this to work.

**Comment by jamuhl** [comment]
@PeterBenc your resources should not really contain all languages you provide - at least not in web - for mobile that might be ok...

so you should keep track of what languages you support yourself or use the supportedLanguages for that...

reading the docs it should be clear what and why i18next.languages exist and is not the same as i18next.language https://www.i18next.com/overview/api#languages

**Comment by PeterBenc** [comment]
I get that now, I read the docs and tbh I initially skipped the explanation for `languages` since it seemed self-explanatory. My only point was that maybe `translations` is a bit too general name tho I can't think of a better naming. Anyway thanks for the quick reply and suggestions :) I ll use `supportedLanguages`.

**Comment by rohitjpsingh** [comment]
i18n.services.backendConnector.backend.getLanguages((err, ret) => {
      console.log('ret:',ret);
      if (err) return // TODO: handle err...
      setLngs(ret);
    });

**Comment by rohitjpsingh** [comment]
I'm getting one eng languages in react js. I have total two languages en and de. I'm using also locize and following this 
    https://locize.com/blog/how-to-internationalize-react-i18next/
    
    please help me.

**Comment by jamuhl** [comment]
@rohitjpsingh did you already add content (translations) for your german content -> my guess that language only shows up if there is any content (not completely translated but at least one string so the CDN has some content)

**Comment by adrai** [comment]
@rohitjpsingh I suspect you've loaded stale language data because of the caching, the https://docs.locize.com/integration/api#fetch-the-available-languages request is cached 1h by default...
In case you need more help, send an email at: support@locize.com

**Comment by rohitjpsingh** [comment]
Thank you guys for supporting. Issue has been fixed automatically now.

**Comment by rohitjpsingh** [comment]
> @rohitjpsingh I suspect you've loaded stale language data because of the caching, the https://docs.locize.com/integration/api#fetch-the-available-languages request is cached 1h by default...
> In case you need more help, send an email at: [support@locize.com](mailto:support@locize.com)

yes, you're absolutely right. It's taking time approx 1 hour to refresh. thanks

**Comment by chordmemory** [comment]
I believe presenting a user the list of all available languages to allow them to select theirs (if the automatic inference is not appropriate, e.g. non native speaker in a country) is a valid use case.

It'd be great if there was an api built in to i18n next that backend plugins could override, as opposed to the current solution which seems to depend on your choice of backend.

This would mean our code would not have to change significantly when we change our backend plugin (which is a likely scenario currently).

**Comment by jamuhl** [comment]
@chordmemory I don't really think that it is needed to add a list of all languages to i18next itself -> this static list could be either provided by the dev or an independent module (rather sure some lists already exist on github)

(the locize-backend provides a list of languages used in the translation project as a convenience)

**Comment by closingin** [comment]
It's been a while since I commented on this issue, but I still think that a native way to get the entire list of available languages could be useful.

> or provide them yourself...as you know which languages you have.

Most of the time I actually don't know what languages I have, so I prefer to have a dynamic way to generate my languages list. Imagine that I add a new supported language to either locize or phrase (or whatever backend you use). If I download then inject all of them during the build phase, based on an api call (which I do), I don't know which ones I have available to me.

Of course crafting the language menu on my own is "fine", I don't add new languages to my application that often. But you know how it goes, we're just lazy developers.

It could be as simple as a getter maybe? I haven't checked the source code to see if there's a class for it though.
```js
get languageList () {
    return Object.keys(this.services.resourceStore.data);
}
```

**Comment by adrai** [comment]
> It's been a while since I commented on this issue, but I still think that a native way to get the entire list of available languages could be useful.
> 
> > or provide them yourself...as you know which languages you have.
> 
> Most of the time I actually don't know what languages I have, so I prefer to have a dynamic way to generate my languages list. Imagine that I add a new supported language to either locize or phrase (or whatever backend you use). If I download then inject all of them during the build phase, based on an api call (which I do), I don't know which ones I have available to me.
> 
> Of course crafting the language menu on my own is "fine", I don't add new languages to my application that often. But you know how it goes, we're just lazy developers.
> 
> It could be as simple as a getter maybe? I haven't checked the source code to see if there's a class for it though.
> 
> ```js
> get languageList () {
>     return Object.keys(this.services.resourceStore.data);
> }
> ```

A solution like that built directly in i18next would only work if all resources/languages are preloaded, so working with a lazy loading backend or similar would just give a wrong language list...

**Comment by rickstaa** [comment]
> @spike-barry-northern The point is - i18next has no idea (nor a need) for languages you provide - it only knows what language was detected or set and from there builds a list of languages to load and to look translations up from.

@jamuhl so if I understand it correctly [i18next](https://github.com/i18next) combined with [i18next-http-backend](https://github.com/i18next/i18next-http-backend) by default loads languages on the spot. Meaning that if a language is detected, it looks in the specified `loadPath` to see if a translation file is present there, and if it is, it loads the translations and adds the language to the `languages` object. Additionally, users can preload languages on construction by specifying them in the `supportedLngs` initialization option.

I'm asking because I, like @closingin, wanted to create a dynamic language selection menu. The `Object.keys(i18next.services.resourceStore.data);` doesn't seem to be available when using the [i18next-http-backend](https://github.com/i18next/i18next-http-backend) backend. Therefore, I now use [a GitHub action](https://github.com/rickstaa/github-emoji-picker/blob/main/.github/workflows/update_supported_locals.yml) to retrieve the languages available in the `public/locales` folder and use the outcome of this action in the [supportedLngs](https://github.com/rickstaa/github-emoji-picker/blob/25b2e51cf004fbccbb44b94b777ab2abd17102dd/src/i18n.ts#L25) option. Is there a better way to find out the languages that are supported through `i18next`, or is `i18next` loading languages on the spot?

**Comment by adrai** [comment]
@rickstaa with a remote backend plugin you need something like you've described with your github action. Alternatively if you're using locize, you can use: https://github.com/locize/i18next-locize-backend#backendgetoptions

**Comment by jamuhl** [comment]
@rickstaa just a correction: Additionally, users can preload languages on construction by specifying them in the `supportedLngs` initialization option. <<-- it's `preload` to preload additional languages https://www.i18next.com/overview/configuration-options#languages-namespaces-resources

**Comment by michael-lynch** [comment]
If you manually set `supportedLngs` in your config file, you may as well just export it.

**i18n.ts**
```
export const supportedLngs = ['en', 'fr'];

i18n.init({
  ...
  supportedLngs
}):

export default i18n;
```
Then you can build a language select, for example.

**SelectLang.ts**
```
import { MouseEvent } from 'react';
import { supportedLngs } from '../../i18n';
import { useTranslation } from 'react-i18next';

export const SelectLang = () => {
  const { i18n, t } = useTranslation();
  
  const handleChangeLang = (e: MouseEvent<HTMLSelectElement>) => {
    i18n.changeLanguage(e.target.value);
  }
  
  return (
    <select onChange={handleChangeLang}>
      {supportedLngs.map((lang) => {
        <option key={`lang-${lang}`} value={lang}>{t(lang)}</option>
      }
    </select>
  );
}
```

**Comment by tomihbk** [comment]
> But i guess `Object.keys(i18next.services.resourceStore.data);` would give you a list of every locale loaded into i18next

Thanks a bunch! This was it. I was able to achieve a list of available languages : 

```react
              <ScrollView>
                {Object.keys(i18n.services.resourceStore.data)
                  .map((lang) => {
                    return (
                      <TouchableOpacity key={lang}>
                        <Text>{lang}</Text>
                      </TouchableOpacity>
                    )
                  })}
              </ScrollView>
```
