### ISSUE TITLE
Translator: No plural when saving missing with count equal to 0

### ISSUE THREAD

**Issue by Chcap** [i18next/i18next#1071]
Hello,

when using a `BackendConnector` and having a missing translation with a `count` attribute equal to zero, the `BackendConnector.create` is called only with the `key` case, and not its plural forms.
In consequence, if the count value is random and by (bad) luck the first random value is `0`, then, the plural values are not created.

The solution is in the [Translator](https://github.com/i18next/i18next/blob/master/src/Translator.js#L158)  where the case when `count` is zero should not be counted as falsy.

**Comment by jamuhl** [comment]
good catch...will be fixed

**Comment by Chcap** [comment]
I opened the PR https://github.com/i18next/i18next/pull/1072 to fix it :)
