### ISSUE TITLE
Please change 't' method name to trans or translate

### ISSUE THREAD

**Issue by kowalk** [i18next/i18next#1073]
Why are you implement methods with such name? The method name should tell us method purpose, also please add this rule to your linter. Thanks :)

**Comment by jamuhl** [comment]
because typing `t('key')` is well known and used widely. Faster to type...

**Comment by kowalk** [comment]
@jamuhl Seriously "faster to type" in age of IDE... ability to read code (=quality) should be your priority not a speed of typing

**Comment by jamuhl** [comment]
IDE - i use VIM ... just joking

but anyway that function is called `t` and it will stay so for another 6 years...if you do not like it make an aliase...
