### ISSUE TITLE
Is it possible to use a key with spaces?

### ISSUE THREAD

**Issue by JemiloII** [i18next/i18next#1075]
So if I have a json that looks like this:

```json
{
  "welcome": {
    "title": "welcome",
    "author": "garyvee",
    "to the shooooooow": "to the shooooooow",
  }
}
```

I can get title and author by doing: `i18next.t('welcome.title');` or `i18next.t('welcome.author');`

but when I try: `i18next.t('welcome["to the shooooooow"]');` it doesn't work. Is it possible to use a key with spaces?

**Comment by jamuhl** [comment]
the key is a string not javascript object -> `i18next.t('welcome.to the shooooooow');`

**Comment by JemiloII** [comment]
oh! i'll try that

**Comment by JemiloII** [comment]
Awesome! It works! I guess I never would have thought about doing it this way, had the javascript standard in mind about how objects work~

**Comment by power725** [comment]
Wonderful!
It works well.
Thanks.
