### ISSUE TITLE
Plural suffixes for unknown languages

### ISSUE THREAD

**Issue by maulerjan** [i18next/i18next#1078]
Hi,

I'm using i18next with React. Everything works nicely except plurals.

I'm testing with Czech (cs) language.

After some time I finally understood how the suffixes work, but the problem is my translators won't understand that (or it will consume too much time for them in order to understand).

What I would prefer instead of current system would be a simple suffix based on actual count, so for example (in Czech) instead of this mapping:
```
{ count: 1 } -> key_0
{ count: 2 || 3 || 4 } -> key_1
{ count: 0 || 5 || 6 || ... } -> key_2
```
it would work with simply specifying the count as a suffix:
```
{ count: 0 } -> key_0
{ count: 1 } -> key_1
{ count: 2 } -> key_2
{ count: AnythingExceptZeroOrSingular } -> key_plural
```
I think it would be much clearer and easier to understand.

Is there any way of doing that?

Thanks!

**Comment by jamuhl** [comment]
That does not really work...languages work not like this...do you want to add 1000 keys if your count goes to 1000? Doesn't make sense. We can't make a extra rule for czech - all the rules are based on cldr: http://www.unicode.org/cldr/charts/33/supplemental/language_plural_rules.html

if you're translators are not able to do this standard conversion for plurals i suggest using something like https://locize.com which does this job for the translators (guess they at least understand there are more than one form for plurals)

**Comment by maulerjan** [comment]
Thanks for a quick info, I will definitely check the Locize service. And you're right it wouln't make much sense, I didn't know there are languages with such extensive naming ranges.

For anyone having the same concerns, there's a [tool](https://jsfiddle.net/jamuhl/3sL01fn0/#tabs=result) linked in docs which can help generating the correct suffix based on provided count.

**Comment by vituchon** [comment]
@jamuhl Hi there and excuse me please... but ¿is this ok?

![image](https://user-images.githubusercontent.com/1927644/201425427-81044355-5d8c-4381-86e7-e00b4ce4fde2.png)

I used the  "ar" language

**Comment by jamuhl** [comment]
https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html#ar

the tool uses i18next builtin plural resolver which relies on Intl API: https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L112

so those values are correct (as long as the browsers Intl API is up-to-date)

**Comment by vituchon** [comment]
Thanks @jamuhl enlightening as usual! Is so not natural to me to handle the numbers like that... hope to have no problems when counting the goals in the world soccer championship :laughing:
