### ISSUE TITLE
comments for translators

### ISSUE THREAD

**Issue by obsidianart** [i18next/i18next#108]
While translating the application in 12 languages I noticed I need sometime to give some additional information to the translators. There's a way to add a comment that will be read in your interface or that will be translated by the po/json converter?
At the moment I'm using omegaT with the json plugin from rainbow but I wanted to know if there's a not documented function to add translation additional information directly

P.S. sorry if issues is not the right place fot that.

**Comment by meglio** [comment]
Have comments been implemented since then?

**Comment by jamuhl** [comment]
not in the way specified here:

but you can call `i18next.t(key, defaultValue, comment/context)` -> this is also supported on  https://locize.com to pass context informations to translators.

**Comment by meglio** [comment]
So, currently no comment is possible in JSON, right?

**Comment by jamuhl** [comment]
No not by default - but like @obsidianart mentioned you can add them - but remove them anyway as those comments add significant size not needed.

**Comment by jamuhl** [comment]
@meglio you can use fluent (https://github.com/i18next/i18next-fluent) instead of json - which allows for comments in the translation catalog.

**Comment by Aarbel** [comment]
Still, would be really nice to bring documentation on lokalise elements

**Comment by jamuhl** [comment]
@Aarbel sorry ... I don't understand your request? more documentation pages for locize...what you mean by lokalise elements?
