### ISSUE TITLE
Missing Keys with function getResource()

### ISSUE THREAD

**Issue by endbay** [i18next/i18next#1080]
Hey. I've try to code an endpoint in express. That the .json file served based on the detection (without query string like in i18next-express-middleware). I've used i18next normal just to render PUG and missing keys wasn't a problem yet.

I'm currently try to serve the json file via req.i18n.getResource(), that's working pretty good right now. But missing keys won't be served.

```json
//locales/de.json
{
  "login": "Einloggen",
  "logout": "Ausloggen",
}
```

```json
//locales/en.json
{
  "login": "Login",
  "logout": "Logout",
  "more": "More"
}
```

```js
//my options
i18n.use(i18nMiddleware.LanguageDetector)
    .use(i18nFilesystem)
    .use(session)
    .init({
        debug: true,
        load: 'languageOnly',
        preload: ['en', 'de'],
        ns: ['translation', 'frontend'],
        whitelist: ['en', 'de'],
	defaultNS: 'translation',
	fallbackNS: 'translation',
        fallbackLng: 'en',
        saveMissing: true,
        backend: {
			loadPath: path.join(__dirname, '/locales/{{lng}}/{{ns}}.json'),
        },
        detection: {
            order: ['cookie', 'header'],
            lookupCookie: 'i18n'
        },
        interpolation: {
            format: function (string, mode) {
                if (mode === 'capitalize') {
                    return string[0].toUpperCase() + string.slice(1);
                } else {
                    return string;
                }
            }
        }
    });

app.use(i18nMiddleware.handle(i18n));

//my route
app.get('/locales/lang.json', (req, res) => {
	let langFile = req.i18n.getResource(req.i18n.languages[0], 'frontend');
	res.send(langFile);
});
```

I want result should be with german detection:
```
{
  "login": "Einloggen",
  "logout": "Ausloggen",
  "more": "More"
}
```

Is this possible with any options?

**Comment by jamuhl** [comment]
Currently on a short vacation. Will have a look later this week. 

Von meinem iPhone gesendet

**Comment by jamuhl** [comment]
`i18next.getResource` only hits the resource store directly. so there won't be any save missings.

But you can access objects too using the regular t function: https://www.i18next.com/translation-function/objects-and-arrays#objects

But normally you would the client just load the json files like you load them via fs on server side: https://github.com/i18next/react-i18next/blob/master/example/nextjs_withAppJS/server.js#L36 and let the client it's xhr backend do the job: https://github.com/i18next/i18next-xhr-backend

**Comment by jamuhl** [comment]
ok...so this could be closed? Seems like you got your custom solution running? Or anything not working?
