### ISSUE TITLE
i18next and MongoDB authentication

### ISSUE THREAD

**Issue by Papipone** [i18next/i18next#1083]
I am facing an issue to initialize the `i18next` with `i18next-mongodb-backend`. How to connect to a MongoDB database when an authentication is required? Is it even possible?

```
i18next
    .use(mongoBackend)
    .use(i18nextMiddleware.LanguageDetector)
    .init({
        backend: {
            host: 'localhost',
            port: 27017,
            db: 'my_database',
            collection: 'my_collection',
            // authentication option?
```

Thanks for your answer.

**Comment by jamuhl** [comment]
Please ask the question over at the specific backend implementation: https://github.com/gian788/i18next-node-mongodb-backend#readme
