### ISSUE TITLE
load: 'unspecific' not working

### ISSUE THREAD

**Issue by RobertHeim** [i18next/i18next#1084]
Hey,

we have two languages `de` and `en`. What I would expect from using `load: 'unspecific'` is the following:

Browser language is `de` => load `de`
Browser language is `de-de` => load `de`
Browser language is `de-at` => load `de`
// ... same for all other `de-*`
Browser language is `en` => load `en`
Browser language is `en-US` => load `en`
Browser language is `en-GB` => load `en`
// ...same for all other `en-*`
Browser language is anything else => load fallback (`en`)

However, it does not work for me. When pointing my browser to `http://localhost:3000/?lng=de-at#/` the `en` translations are loaded and not `de`.

This is our configuration:
```
import i18n from 'i18next';
import LngDetector from 'i18next-browser-languagedetector';
import { reactI18nextModule, translate } from 'react-i18next';

import de from './de';
import en from './en';

i18n
  .use(LngDetector)
  .use(reactI18nextModule)
  .init({
    load: 'unspecific', // always load the unspecific resource file (eg. en instead of en-US).
    fallbackLng: 'en',
    whitelist: ['de', 'en'],
    debug: true,

    interpolation: {
      escapeValue: false, // not needed for react as it does escape per default to prevent xss!
    },

    resources: {
      de: {
        translation: de,
      },
      en: {
        translation: en,
      },
    },

    react: {
      wait: true,
    },
  });
```
Did we configure anything wrong?

**Comment by jamuhl** [comment]
from where do you have that the value for load can be unspecific?

load can be:
'all' --> ['en-US', 'en', 'dev'],
'currentOnly' --> 'en-US',
'languageOnly' --> 'en'

https://www.i18next.com/overview/configuration-options#languages-namespaces-resources

**Comment by RobertHeim** [comment]
Thanks!
