### ISSUE TITLE
getLanguageBundle

### ISSUE THREAD

**Issue by chacestew** [i18next/i18next#1086]
Hi - I'm wondering if it makes sense to add a store method similar to `getResourceBundle` that returns all namespaces loaded for that language? i.e. `getLanguageBundle(lng)`

My use case is for server rendering. I am loading only the namespaces needed into each cloned `i18n` instance. Then I serialize and send down the whole language object via HTML to hydrate `initialI18nStore` (react-i18next). Currently it's necessary to iteratively call `getResourceBundle` for each ns to build this object - it would be helpful if there was a method to return it instantly.

**Comment by jamuhl** [comment]
good question...basically that is like accessing `i18next.services.resourceStore.data[lng]`

for sure does not hurt...just naming is a little difficult...getResourceBundles would be more expecting an array of those. getLanguageBundle i do not really like the bundle side...as bundle more or less reflect the loaded file (namespace)...eventual something like `getDataByLanguage` idk

**Comment by chacestew** [comment]
I like the benefit of using an official API to avoid breaking changes if the store object structure changes. Even if that only happens in a major bump at least it's one fewer migration step. Agree that `Data` is more accurate than `Bundle` as a description for this func.

**Comment by jamuhl** [comment]
Feel free to provide a PR - else i will add this when finding time for doing so.
