### ISSUE TITLE
Adding resource to en.json

### ISSUE THREAD

**Issue by ceilat** [i18next/i18next#1089]
I am trying to add new key-value pair to my en.json file using addResource API.

this is how my JSON struct right now:
 
```
 "CATALOG": {
    "NEW_PACKAGE_FORM": {
      "NAME": "Name",
      "VERSION": "Version"
    }
  },
```

is it possible to write into the JSON file itself using addResource API ?
how i add new key-value to` CATALOG.NEW_PACKAGE_FORM` ?

**Comment by jamuhl** [comment]
no...add resource is just to add internal.

for missing handling there is: https://www.i18next.com/overview/configuration-options#missing-keys

=> set saveMissing: true on init and let the backend send the missings to your backend where you can take those values and write your json (eg. using i18next-express-middleware)

or use our https://locize.com and get that all bootstrapped for you.

**Comment by ceilat** [comment]
@jamuhl Thanks
