### ISSUE TITLE
Maintain current selected language on page reload.

### ISSUE THREAD

**Issue by alliswell2day** [i18next/i18next#1090]
I will like to know how i can load current selected language after i reload my page, for example my active language is "en", after i change to "cn" and refresh page language return to "en", i want to store the selected "cn" to load after refresh page. Thanks

<a class="btn btn-white set_en active"><i class="flag-icon flag-icon-us"></i></a>
<a class="btn btn-white set_cn"><i class="flag-icon flag-icon-cn"></i></a>

![1](https://user-images.githubusercontent.com/16883846/43979674-20da401a-9d1e-11e8-8a2e-4cabdace9be0.png)

i18next-1.11.2.js
[https://gist.github.com/alliswell2day/1635afd364b0e8f791c0bc40083c4786](url)

**Comment by jamuhl** [comment]
why the hell are you using i18next 1.11.2 and still got questions for implementation details like storing lng over requests - that version is old and is not supported anymore.

Anyway...when you set language store your language in localstorage or similar and on init use that value or `en` as fallback.

But easier would be using https://github.com/i18next/i18next-browser-languageDetector with a newer version of i18next

**Comment by alliswell2day** [comment]
Thanks
