### ISSUE TITLE
handle :: properly

### ISSUE THREAD

**Issue by sibelius** [i18next/i18next#1093]
I'd like to have a key like this

`ADMIN::A::B`

right now this is translating to this:

`.A..B`

any guess what I'm doing wrong?

is there any option to enable `::`?

**Comment by jamuhl** [comment]
`:` is reserved to separate a namespace from the key -> you can set nsSeparator to false on init to avoid this

**Comment by sibelius** [comment]
nsSeparator: '#',

fixed

tks for the quickly response

maybe we should add defaults to docs as well

**Comment by jamuhl** [comment]
https://www.i18next.com/overview/configuration-options#misc there are defaults? or what you mean?
