### ISSUE TITLE
Translations not updating

### ISSUE THREAD

**Issue by lorife** [i18next/i18next#1094]
Hello, 
first of all thank you for this great software. 

I'm having a problem, everything works great but every time I update the json files, i do not see the updates. If I open a new anonymous tab in firefox I see them, but it looks like there's a cache somewhere.
How can i force an update? I tried F5 or CTRL+F5 and it does not work. This is the part where I configure i18next.

```
// Se non passo una lingua, la imposto undefined in modo che la rileva l'oggetto
	if(lng == ""){
		lingua_attiva = undefined;
	};

	var i18nextInstance = i18next
		.use(i18nextXHRBackend)
	  .use(i18nextBrowserLanguageDetector)
		.init({
			detection: {
				// Escludo localStorage. Praticamente ricorda l'ultima lingua usata.
				//order: ['querystring', 'cookie', 'localStorage', 'navigator', 'htmlTag'],
				order: ['querystring', 'cookie', 'navigator', 'htmlTag']
			},
			fallbackLng: 'en',
		  lng: lingua_attiva,
		  debug: true,
		  ns: ['common'],
      defaultNS: 'common',
		  backend: {		  		      
	      loadPath: './i18n/{{lng}}/{{ns}}.json',
	      crossDomain: true,
	      parse: function(data) {
	        // queste 3 righe sotto mi fanno utilizzare il json che include anche la lingua.
	        // infatti, nel caso di un file per lingua, la lingua non andrebbe messa. Solo che ci sono delle estensioni
	        // come quella di PHP che la vogliono lo stesso. Per questo la lascio e la escludo.
		      var json = JSON.parse(data);  // --> { en: {  ... } }
		      var m = Object.keys(json); // --> ['en']
		      return json[m[0]]; // --> { common: { ... } }
		    }
	    }
		}, function(err, t) {
			// initialized and ready to go!

			// Se in ingresso non avevo passato nessuna lingua, la imposto adesso con quella rilevata
			if(lingua_attiva == undefined){
				lingua_attiva = i18nextInstance.language.substr(0, 2);;
			};

			// Se la lingua non è tra quelle abilitate, forzo inglese
			if((lingua_attiva != 'it')&&(lingua_attiva != 'en')){
				lingua_attiva = 'en';
			};

			ConfiguraMainWebsite();
		  AggiornaTraduzioni();
		});

	// Dal momento che i nomi delle colonne non si possono tradurre quando cambio la lingua
	// allora se succede faccio un reload della pagina
	i18next.on('languageChanged', function (lng_new) {
    //AggiornaTraduzioni();
    if((lingua_attiva != lng_new)&&(lingua_attiva != undefined)){
      window.location = "index.php?lng="+lng_new;
    };
  });

  // Configuro le opzioni per utilizzare jquery nelle traduzioni
  jqueryI18next.init(i18nextInstance, $, {
	  tName: 't', // --> appends $.t = i18next.t
	  i18nName: 'i18n', // --> appends $.i18n = i18next
	  handleName: 'localize', // --> appends $(selector).localize(opts);
	  selectorAttr: 'data-i18n', // selector for translating elements
	  targetAttr: 'i18n-target', // data-() attribute to grab target element to translate (if diffrent then itself)
	  optionsAttr: 'i18n-options', // data-() attribute that contains options, will load/set if useOptionsAttr = true
	  useOptionsAttr: true, // see optionsAttr
	  parseDefaultValueFromContent: true // parses default values from content ele.val or ele.text
	});
```

and this is a part of the italian json file:

```
{
  "it": {
    "nav": {
        "home": "Elenco Servizi",
        "details": "Dettagli",
        "temp": "Temperature",
        "gps": "GPS",
        "docs": "Documenti",
        "cpanel": "Pannello di controllo",
        "sreq": "Richiesta servizio",
        "analysis": "Analisi",
        "tabmanager": "Gestione Tabelle",
        "supp_lst": "Borderò"
    },
    "btn": {
        "welcome": "Benvenuto {{user}}",
        "welcome_guest": "Benvenuto, clicca per fare il login!",
        "view": "Vedi",
        "mobile": "Mobile",
        "find": "Cerca",
        "reset": "Reset",
        "edit": "Modifica",
        "update": "Aggiorna",
        "logout": "Disconnetti",
        "upl_pers": "Carica file personali",
        "upl_serv": "Carica file servizio",
        "link": "Collega",
        "unlink": "Scollega",
        "srv_details": "Vedi dettagli servizio",
        "add_status": "Aggiungi esito",
        "autofix": "Autofix",
        "enable_af": "Abilita autofix",
        "disable_af": "Disabilita autofix",
        "search_as400": "Ricerca AS400",
        "ofd": "Uscita"
    },
```

Could you help me? 
thank you!

**Comment by jamuhl** [comment]
as long you're not using a cache backend (eg. using localStorage) the only way i that this happens is that your browser caches the xhr requested. How do you host your translations? Do you use a no-cache flag on that request?

**Comment by lorife** [comment]
thank you for your answer. 
I'm working in local now so everything is in my computer:

C:\Apache24\htdocs\progetti\Ufficiali\Progetti PHSE\tracking_web\index.php
C:\Apache24\htdocs\progetti\Ufficiali\Progetti PHSE\tracking_web\en\common.json

I removed localstorage (as in the code I posted) and I do not now how to check "no-cache flag on that response". How do I check that?

**Comment by jamuhl** [comment]
In your browser open the development console and check in the network tab the requests done for loading your translations C:\Apache24\htdocs\progetti\Ufficiali\Progetti PHSE\tracking_web\en\common.json -> check the values for cache espiration , ...

Not much i can help you with fixing that - not used PHP ever

**Comment by lorife** [comment]
Hello, 
I checked index.php and cache expiration is not set (i'm attaching a screenshot). 

Why do you talk about php? my problem is actually in javascript (as you see in the screenshot).

All those columns get translated meaning it "see" the json file. 
those 2 missing columns are new but in the file are present. The proof is that if I open an anonymous tab in firefox i see them.

I use i18n like this:

i18next.t('generic_short.volume')



![screenshot 25](https://user-images.githubusercontent.com/2658137/44714494-b8bd0d00-aab5-11e8-84a6-43c7df6a7700.png)

**Comment by jamuhl** [comment]
Because the translations are loaded by the client -> but need to be provided by the server which in your case seems to be PHP.

Are the translations actually loaded -> set debug: true on init of i18next and check the console log output

**Comment by lorife** [comment]
Now it works, I don't know why..i did not do anything. I just clicked for the thousand time F5.

Until some minutes ago the json file was loaded but those 2 translations were not (it kept saying they were missing). 

Now i added another translation and i have the problem again. it looks like it does not reload the new json file.

**Comment by lorife** [comment]
I just tried, let's say the json file is:

```
{
  "it": {
    "nav": {
        "home": "hello",
```
and javascript is:

`i18next.t('nav.home')`

and it's working. 
now if I change "hello" with "bye bye" and hit F5 it works, it updates. 
But if I change "home" with "home2" on both json and javascript it does not work

**Comment by jamuhl** [comment]
like said...sounds like some caching issue between apachi and your browser

**Comment by lorife** [comment]
mmm...i tried doing the same with chrome and it's not doing the same. It looks a problem with firefox. 
Well thank you anyway and sorry for your time.

**Comment by jamuhl** [comment]
you're welcome

**Comment by jamuhl** [comment]
Closing this for now...if still having an issue feel free to reopen this or adding a new issue.
