### ISSUE TITLE
how to ignore country in language code

### ISSUE THREAD

**Issue by MassimilianoCuccia** [i18next/i18next#1095]
The language detector correctly detect the language code (language and country) in use on my iPad, infact when I console.log(i18n.language) I get it_IT or en_UK (as iPad configuration).
but, in my dictionary, I don't want to define country specific translations, so I defined translation only for language code.

> i18n
>   .use(languageDetector)
>   .init({
>     fallbackLng: 'en',
>     // the translations
>     // realworld load that via xhr or bundle those using webpack
>     resources: {
>       en: {
>         home: {
>           title: 'Welcome'
>         }
>       },
>       de: {
>         home: {
>           title: 'Willkommen'
>         }
>       },
>       it: {
>         home: {
>           title: 'Benvenuto'
>         }
>       },
>       // have a initial namespace
>       ns: ['translation'],
>       defaultNS: 'translation',
>       interpolation: {
>         escapeValue: true // not needed for react
>       }
>     }
>   });

I expect that it_IT will fallback to it, instead i18next fallback to en (as defined into fallbackLng)
how to ignore country portion of detected language code ?

thanks

**Comment by jamuhl** [comment]
it_IT is invalid -> needs to be it-IT -> that way it will fallback to it

futher you can set `load: 'languageOnly'` on init to avoid even loading regional locales

**Comment by MassimilianoCuccia** [comment]
Thanks for your feedback, but 

That was the output of console.log(i18n.language);
I am running a react-native app on iPad
it_IT is what my console.log write as detected language if iPad language is italian.
en_GB if the language is English UK
maybe there is a problem in my language detector?

setting load does not solve.
>  [cut][cut][cut]
>   .init({
>     fallbackLng: 'en',
>     load: 'languageOnly',
>  [cut][cut][cut]

**Comment by jamuhl** [comment]
what detector do you use?

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/js/i18n.js#L10 -> see the replace of `_` with `-`

**Comment by MassimilianoCuccia** [comment]
Here is the code I'm using now, modified to replace underscore in language code

const languageDetector = {
  type: 'languageDetector',
  async: true, // async detection
  detect: (cb) => {
    return Expo.Util.getCurrentLocaleAsync()
      .then(lng => {
        console.log("lng:" + lng);
        cb( lng.replace('_', '-') ); })
  },
  init: () => {},
  cacheUserLanguage: () => {}
}

This works,
Thanks @jamuhl !

**Comment by MassimilianoCuccia** [comment]
the error is in your blog post
https://medium.com/@jamuhl/translate-your-expo-io-react-native-mobile-application-aa220b2362d2

**Comment by jamuhl** [comment]
thanks -> fixed

**Comment by MassimilianoCuccia** [comment]
good work!
many thanks

**Comment by jamuhl** [comment]
Thank you for pointing out

**Comment by otaviobps** [comment]
I'm having the same issue.

```
i18n.use(backend)
    .use(detector)
    .use(initReactI18next)
    .init({
        fallbackLng: 'en',
        load: 'languageOnly',
        interpolation: { escapeValue: false },
        keySeparator: false,
        nsSeparator: false,
        backend: {
            loadPath: '/locales/{{lng}}/{{ns}}.json',
            addPath: '/locales/{{lng}}/{{ns}}.json',
        },
    });
```

When I `console.log(i18n.language)` I get `en-US`. Any fix for this?

**Comment by jamuhl** [comment]
@otaviobps docs say rather well what i18n.language vs i18n.languages is: https://www.i18next.com/overview/api#language

**Comment by burtyish** [comment]
Note that you can now use i18next.resolvedlanguage, introduced in v21.0.0
