### ISSUE TITLE
ngettext replacement ?

### ISSUE THREAD

**Issue by gunzino** [i18next/i18next#1096]
Hello,

Currently we hare using ngettext function in our PHP app. This function includes default values for both singular and plural strings.

If we use i18next in our JS app the programmer is able to specify only one version of the  default string (which could be key or defaultValue property). Therefore, he has to add the plural version to the translation file manually. Using ngettext in PHP the app is fully functional without programmer touching the translation files.

I would like to ask if you plan to add some function that could be used to replace ngettext ?

Thnaks.

**Comment by jamuhl** [comment]
the save missing feature https://github.com/i18next/i18next/blob/master/src/Translator.js#L158 will already create the needed keys for both singular and plural - just it uses the same defaultValue...but i guess that is ok - as it's not the developers concern to get both singular and plural correct -> translators will/should review texts made by developers anyway.

So eg. using https://locize.com you will get all that out of the box - without having to handle the saveMissings on your backend

**Comment by jamuhl** [comment]
So is your need more related to defining defaultValues for all possible plural forms (depending on your language)?

**Comment by gunzino** [comment]
We are just used to that application is fully working with default english language with any newly feature added. Also we have some applications that are not going to be translated anytime soon but may be translated in the future. Therefore singular and plural value in english (or any other language with one plural form) is enough for the application to work - in this case not any translation files are needed. If we migrate to i18next we have to create english translation file and fill it with all the plurals. Also that file has to be manually managed by programmers if they add new feature.

**Comment by jamuhl** [comment]
ok i see...basically you would prefer the key to be the fallback (which works for i18next) but for plural cases you like to add the defaults.

we fallback either to default value or key here: https://github.com/i18next/i18next/blob/master/src/Translator.js#L121

when doing a translation lookup we return found or not found value here: https://github.com/i18next/i18next/blob/master/src/Translator.js#L278

we could add the needed pluralSuffix from here: https://github.com/i18next/i18next/blob/master/src/Translator.js#L254 to that return value

and than use that suffix (if exists = isAPlural) to check if there is some `defaultValue_plural` or depending on other language having multiple pluralforms `defaultValue_[0|1|2|...]`

Would that help?

**Comment by gunzino** [comment]
Yeah definitely that would be great feature ;)

**Comment by jamuhl** [comment]
If you feel comfortable you might add a PR...else i will see what i can do...not to complicated...but currently limited on time.

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/commit/94173ea7000b48b9cdd145cf8685a074f98760b5
