### ISSUE TITLE
How to nest/include the whole object when define resouce?

### ISSUE THREAD

**Issue by qjs2000** [i18next/i18next#1098]
My locale resource has come common parts:
It looks like:
```
{
"KafkaSource": {
 "name":"Kafka Source",
 "topic":"Kafka Topic",
 "servers":"Bootstrap Servers",
},
"KafkaSink": {
 "name":"Kafka Sink",
 "topic":"Kafka Topic",
 "servers":"Bootstrap Servers",
}
}
```

Since KafkaSource and kafkaSink have the common parameters. I only want to define once.
I can use "nesting" feature to define them:
```

{
"KafkaSource": {
 "name":"Kafka Source",
  parameters:{
   "topic":"Kafka Topic",
   "servers":"Bootstrap Servers",
 }

},
"KafkaSink": {
 "name":"Kafka Sink",
 parameters:{
	"topic":"$t{KafkaSource.parameters.topic}",
	"servers":"$t{KafkaSource.parameters.servers}",
 }
}
}
```

But it can be very tedious since it will have a lot of parameters under it, and it also doesn't decrease the line number of resource.

How can i nesting/include the whole object to save a lot more work? 
It may look like: 
```
{
"KafkaSource": {
 "name":"Kafka Source",
  parameters:{
   "topic":"Kafka Topic",
   "servers":"Bootstrap Servers",
 }

},
"KafkaSink": {
 "name":"Kafka Sink",
 parameters:{{KafkaSource.parameters}}
}
}
```

Is there some way to acheive this purspose?

**Comment by jamuhl** [comment]
no...there is no way to do this....sorry.

**Comment by qjs2000** [comment]
Ok, hope this feature in the future.

Thanks Jan!
