### ISSUE TITLE
Is there any event can be fired when fallback?

### ISSUE THREAD

**Issue by aiyagaze** [i18next/i18next#1099]
Hey,

I want to log the missing transaltions, but the missingKey event doesn't work when fallback is enabled. Is there any other event i can use to get the missing translation with successful fallback? Or is there an event can be fired when fallback? I really don't want to disable the fallback

Thanks a lot

**Comment by jamuhl** [comment]
missing is currently only there to detect keys that are completely missing in your translations - not "even" existing in your source language.

For asserting keys exist in target language you can use tools like https://locize.com or similar.
