### ISSUE TITLE
clean way to get current language...

### ISSUE THREAD

**Issue by AlexCppns** [i18next/i18next#1103]
I have been trying to get the current language in my react application (with typescript) and I have been struggling to get the current language from the api in a clean way. Right now I have an ugly hack that looks like:

```
import * as i18next from "i18next"

...
const currentLang = (i18next as any).default.language
```

Edit: I found that even that is not bulletproof, I don't have the current language in my staging environment, I am guessing language is undefined... is there the right way to do it documented somewhere?

**Comment by jamuhl** [comment]
```js
import i18next from 'i18next';

i18next.use(someLngDetector).init(someOptions, () => {
  // initialization done
  i18next.language; // -> detected language
});
```

that's the right way - at least for javascript usage 😢don't ask me for translation to typescript (not using it - never will use it - and won't tell my personal opinion about typescript here)

**Comment by AlexCppns** [comment]
@jamuhl I actually don't want the detected language but the one being used.

**Comment by jamuhl** [comment]
i18next.languages holds the array of languages used to translate in order of priority -> so i18next.languages[0] might be what you search

**Comment by AlexCppns** [comment]
It's not working, the language used is 'en' and what I get from languages[0] is 'en-US'...

**Comment by andrewhartwig** [comment]
> that's the right way - at least for javascript usage 😢don't ask me for translation to typescript (not using it - never will use it - and won't tell my personal opinion about typescript here)

I feel like you just did @jamuhl

**Comment by jamuhl** [comment]
@andrewhartwig ok...guilty in this case...now get the stones out and bring your punishment 😄

**Comment by gavinlynch** [comment]
so there is no actual answer to the specific question being asked?
