### ISSUE TITLE
reloadResources() doesn't work reliably for consecutive calls

### ISSUE THREAD

**Issue by victornpb** [i18next/i18next#1105]
It only works the first time, consecutive calls doesn't do anything.

If I call `i18next.changeLanguage(i18next.language)` then call `i18next.reloadResources()` it will fire multiple times.

![image](https://user-images.githubusercontent.com/3372598/46218916-3aee5a80-c31c-11e8-846a-536e6286a81d.png)

```
i18next.use(i18nextXHRBackend).init({
    debug: false,
    appendNamespaceToCIMode: true,
    lng: userInfo.get('lang') || intl.detectUserLang(),
    fallbackLng: 'en-US', // See: http://i18next.com/translate/#resolve
    load: 'currentOnly',  // See: http://i18next.com/translate/#resolve
    backend: {
        // allow cross domain requests
        crossDomain: true,
        loadPath: JSON.parse(config_file).localeURL + '/{{-ns}}/{{lng}}.json',
        queryStringParams: { b: version.build }
    },
    parseMissingKeyHandler(_key) {
        return null; //handled inside the createi18nAlias function
    },
    ns: [
        'menu/top-menu',
        'menu/perfect-store',
        'menu/reports',
         (...)
```

**Comment by jamuhl** [comment]
Sorry, I don't get the problem...reload like load will queue the load and callback if loaded -> as it is 4 time the same stuff to reload the first one loading will trigger the callback for all followup calls to reload as it fulfills the requested files to load.

**Comment by victornpb** [comment]
with the network tab opened on devTools, it does not start any network requests after the first callback fired.

**Comment by jamuhl** [comment]
will have to build a reproducing sample the next days...

**Comment by jamuhl** [comment]
hey @victornpb i think it works like intended. Just made a fiddle: https://jsfiddle.net/4wpLae7r/

run it - and open console to see the effect.

calling reloadResources 4 times -> will deduplicate those loading (good thing)
calling reloadResources after reloadResources is done -> will trigger a reload
calling reloadResources time based after timeout of 2s -> will trigger a reload

**Comment by victornpb** [comment]
OK, there's something *VERY WEIRD* going on, and I can't quite understand.

I added A button with `onclick="i18next.reloadResources(null,null,()=>{console.log('Reloaded!')})"`

I spam click it and it workds every time. BUT if i run the same line `i18next.reloadResources(null,null,()=>{console.log('Reloaded!')})` on the devTools It only works once, and after that the button also breaks.

https://jsfiddle.net/Victornpb/4wpLae7r/13/

![tom-delonge-wtf1](https://user-images.githubusercontent.com/3372598/46377601-6603e180-c66f-11e8-8db7-9a23253efa4a.gif)

**Comment by jamuhl** [comment]
Can reproduce it...somehow if calling through console -> https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L128 this starts being not the backendConnector anylonger but i18next.services -> result is loading stays in the load for the first reload stays pending -> no further reload gets triggered (all button clicks end in the queue waiting for the pending request to be successful)

**Comment by victornpb** [comment]
it looks like it is a google chrome bug. If I set breakpoint on the code and try to step it, it works. But if I disable the breakpoints, call it twice so it breaks then enable the breakpoints, and run it again my breakpoint DOESN'T break.

**Comment by jamuhl** [comment]
@victornpb sounds to me like quantum physics...so i see it - but i don't understand it 😄
