### ISSUE TITLE
How to override/reinitialize format function?

### ISSUE THREAD

**Issue by mir3z** [i18next/i18next#1109]
I'm using i18next in node.js + express. I18next instance is created upon application start. Each request's body has some custom options that have to be passed to formatter. So far I haven't found any clean way to do that, except the following ugly workaround:

```
// In request handler:
i18n.services.interpolator.__myOptions = {/* my optiont */}

// In formatter:
const options = this.__myOptions;
```

What's the preffered aprroach to achieve this?
I expect something like:
```
i18n.options.interpolation.format = createMyFormatter();
```

or

```
i18n.setFormatter(createMyFormatter());
```

should be possible.

**Comment by jamuhl** [comment]
what the heck is formatter? there is only i18next.options.format

**Comment by mir3z** [comment]
That's what I meant - sorry.

**Comment by jamuhl** [comment]
You can set format once and without extra options. There is no way to pass additional options to it. The format must be completely specified in the translation.

You might try creating a postProcessor for your use case: https://www.i18next.com/misc/creating-own-plugins#post-processor might be more suitable
