### ISSUE TITLE
react navigation listener willFocus doesn't fire when withNamespaces()

### ISSUE THREAD

**Issue by hoekma** [i18next/i18next#1110]
I'm having problems using react-native, i18next and react-navigation event handler willFocus.  I have isolated it to the withNamespaces being present in my exported module.  The i18N translations work but it doesn't call my handler.

Here is my handler initialization within my component:

```
async componentDidMount() {
        try {
            console.log('sensor.list.container.componentDidMount()')
            this._sub = this.props.navigation.addListener(
                'willFocus',
                this.load
            )
        } 
    }


async componentWillUnmount() {
        try {
            this._sub.remove()
        }
    }

```

It never executes this.load when I export my component with:
`export default withNamespaces()(connect(mapStateToProps, mapDispatchToProps)(SensorList))`

However, it reliably executes this.load when I export my component with:
`export default connect(mapStateToProps, mapDispatchToProps)(SensorList)`

Interestingly, this event handler does work if it is the top-level of stack navigator, but does not fire if I have done a .push() or a .navigate() to get to the page.

Any thoughts?

**Comment by jamuhl** [comment]
might be more a question for react-navigation / stackoverflow -> at least unless it's a clear issue with react-i18next.

I will leave this open...eventual others see this and got an idea...personally i can't help much without having a sample to reproduce...

If there is an issue in react-i18next and you find a solution would be great when you could share your insights.

**Comment by hoekma** [comment]
@jamuhl --

I was able to recreate the problem by making some enhancements to your example project for reactnative-expo.  You can check out the project from  https://github.com/hoekma/i18next

The test is whether it shows the text "Before willFocus" or "After willFocus" on Home and Page2 to determine whether the event handler fired. 

on page Home, you will see 'After willFocus' because the event fires.  
on page Page2, you will see 'Before willFocus' because the event does not fire.

Also on Page2,  if you comment the line that exports withNamespaces and uncomment the line that just says 'export Page2' , the text will change to 'After willFocus' 

After digging around in the react-navigation source code, I wasn't able to figure out what was different unfortunately.  But something in withNamespaces seems to be interfering with the react-navigation event handler.

**Comment by jamuhl** [comment]
no idea...doesn't make sense...

**Comment by jamuhl** [comment]
just thought further about it...i guess it is just a timing issue. The event fires before that component gets rendered. The reason for this might be you set wait: true on the `withNamespaces` component which will  now call loadNamespaces which more or less immediatly return loaded as you pass those translations on init.

Just try setting wait: false here: https://github.com/hoekma/i18next/blob/master/js/pages/Page2.js#L79

**Comment by jamuhl** [comment]
Had luck - not even sure why this came to my mind...seems sometimes a little distance is all to free my mind again 😂
