### ISSUE TITLE
Interpolation escapeValue : false ... not working?

### ISSUE THREAD

**Issue by t7m** [i18next/i18next#1112]
I'm trying to substitute a span with text into a string. The string is:
Your search for {{1}} returned no results.

Using this string...
`let searchTermSpan  = '<span class="entered-search">' + searchTerm + '</span>';`

Hoping to get the result:
`Your search for <span class="entered-search">bad search term</span> returned no results.`

But it is showing that result escaped, not unescaped.

This is what's in the markup:
`<h5>{t( "CategoryPage.NoSearchResultsHeaderWithText", { 1: searchTermSpan, interpolation: { escapeValue: false } } )}</h5>`
        
What am I doing wrong?

**Comment by jamuhl** [comment]
is this react?

**Comment by t7m** [comment]
Yes of course.

**Comment by jamuhl** [comment]
react by design escapes html entities - please read -> https://zhenyong.github.io/react/tips/dangerously-set-inner-html.html

optional solution: use react-i18next and it's Trans component: https://github.com/i18next/react-i18next

**Comment by t7m** [comment]
I understand that react escapes, but then what is the point of **escapeValue:false** that is provided here?

Can you explain "its Trans component?" I just want to substitute {{1}} with a a span tag. Can't i18next-react do this?

**Comment by jamuhl** [comment]
That is for non react usage...it will escape every value interpolated into the translation and eg. is set false in react samples: https://github.com/i18next/react-i18next/blob/master/example/react/src/i18n.js#L22

not doing so would result in double escaping.

**Comment by t7m** [comment]
Ok, so is there a solution other than dangerouslySet? Clearly I can't be the only person ever who has wanted to put a span inside translatable text.

**Comment by jamuhl** [comment]
Like said -> the Trans component: https://react.i18next.com/components/trans-component

**Comment by t7m** [comment]
Previously you said:

> optional solution: use react-i18next and it's Trans component: https://github.com/i18next/react-i18next

So that link wasn't helpful. I'll try this new link, thanks. Although a working example would be nice.

**Comment by t7m** [comment]
Well it's as clear as mud to me, sorry.

I guess I'll find another way. Just wanted to substitute in some text.

**Comment by jamuhl** [comment]
well, like said - the "problem" is - react is safe by design...the only option is dangerously-set-inner-html...😄

**Comment by Pontvs** [comment]
@jamuhl Oh, of course. Thank you kindly!

**Comment by t7m** [comment]
I would love to use the Trans Component but the examples make no sense to me. I want to make

`This text shows {1} that is a span with text.`
... with ...
`This text shows <span>THIS TEXT</span> that is a span with text.`

Can you please explain how to do this?

**Comment by jamuhl** [comment]
https://react.i18next.com/components/trans-component#sample this is more or less 1:1 the same

For translation: https://react.i18next.com/components/trans-component#how-to-get-the-correct-translation-string

For setup: https://github.com/i18next/react-i18next/tree/master/example/react

**Comment by t7m** [comment]
Those examples are simply too abstract. I guess I'm moving on.

**Comment by jamuhl** [comment]
it's not abstract...did you read it...just wrap your jsx with Trans - set debug true on i18n init and see the strings via missings...

idk...just follow the sample...it's no dead simple but not complicted like hell either...;) where do you struggle at the moment?

**Comment by t7m** [comment]
I've looked at it over and over, it is not clear. I have this string...
This text shows {1} that is a span with text.
... and want to make {1} include a span element. Your example doesn't seem to be similar. I already have the string resource, so why would I put a trans tag with a raw string in it again? Makes no sense.

**Comment by jamuhl** [comment]
because it's the way it works...either you wrap and have the functionality...or use some dangerouslyBlabla...why is it so hard to understand...

before:

```js
<h5>
  Your search for <span class="entered-search">bad search term</span> returned no results.
</h5>
```

after:

```js
<h5>
  <Trans i18nKey="CategoryPage.NoSearchResultsHeaderWithText">
   Your search for <span class="entered-search">bad search term</span> returned no results. 
 </Trans>
</h5>
```

translation:

```
"CategoryPage.NoSearchResultsHeaderWithText": "Your search for <1>bad search term</1> returned no results. "
```

**Comment by jamuhl** [comment]
the point is somehow you need to interpolate the react component into the translation. To do so you need that inside you jsx and a marker where to place that. Doing that in code as a real thing makes it easier for the dev -> he does not have to care for the right translation -> the missing handler will do.

anyway...the only other option is using dangerouslyInsertInnerHtml...your choice...as long you know what you're doing risks for XSS is under control...

**Comment by adrai** [comment]
> you have a translation that you set in i18nKey="", so then why do you need to also put the original text of the translation _in the body too?_ It doesn't make sense.

If you're working with i18nKey's you can also completely omit the content, without problem.
`<Trans i18nKey="onlyKey" />`

to know more about the Trans component => https://react.i18next.com/components/trans-component#trans-props
![image](https://user-images.githubusercontent.com/1086194/46909111-967c3300-cf2d-11e8-8e40-50dff25304af.png)

**Comment by t7m** [comment]
OK, I finally got around to implementing this, and every example I've seen is incomplete. In short, nothing works. I can get the output to include the SPAN tags but not the input value.

 The translation text is:
`Your search for <0>{{searchTerm}}</0> returned 0 results`

The element is:

            <Trans 
                i18nKey="CategoryPage.SearchReturnedZero"
                values={ {searchTerm : searchTerm } } 
                defaultVariables={ {searchTerm : searchTerm } } 
                searchTerm={searchTerm}
                components={ [<span className="entered-search"></span>] }>
            </Trans>

Note that "values" and "defaultVariables" and "searchTerm" are all just guesses. I haven't used all three at the same time. None of them work.

The resulting output is:
`<h5>Your search for <span class="entered-search"></span> returned 0 results</h5>`

So what am I missing?

**Comment by t7m** [comment]
If it helps anyone, none of the solutions to my problem were in any documentation, nor were they on this page. The solution for me was:

Translation text:
`Your search for <0>{{searchTerm}}</0> returned 0 results`

The code:
```
            <Trans 
                i18nKey="CategoryPage.NoSearchResultsHeaderWithText"
                values={ { searchTerm : searchTerm } }
                components={ [<span className="entered-search">{searchTerm}</span>] }>
            </Trans>
```

The result is:
`Your search for <span class="entered-search">blorp</span> returned 0 results`

**Comment by jamuhl** [comment]
@t7m that is not needed...this is the workaround to support ICU format in combination with macros...all the samples work - in your case:

```js
// jsx
<Trans i18nKey="CategoryPage.NoSearchResultsHeaderWithText">
  Your search for <span className="entered-search">{{searchTerm}}</span> returned 0 results
</Trans>

// json string of CategoryPage.NoSearchResultsHeaderWithText
Your search for <1>{{searchTerm}}</1> returned 0 results
```

And that workaround for ICU is documented here: https://react.i18next.com/misc/using-with-icu-format#using-the-trans-component

**Comment by t7m** [comment]
I'm not sure what you are saying that's not needed. I just demonstrated the only way it works and you say something isn't needed? 

I don't want ...Your search for .... in the Trans element because that text only belongs in the translation file.

If you have a different way than what I've demonstrated that works, I'd love to hear it. No one has provided it. I showed the answer that works, and you're telling me something isn't needed.

**Comment by jamuhl** [comment]
Like said...what you show here is not the default way of doing it...anyway it works and was originally meant for usage with ICU.

So if it works for you and it's your preferred way - great....

**Comment by t7m** [comment]
This wasn't my preferred way. But since no one has yet to show a simple way -- there are no working examples on this comments thread -- of inserting a span with text into a string, it's my opinion that this is the only way to do it.

**Comment by robin-taulia** [comment]
@t7m thank you for posting your solution! I was also stuck and the documentation did not help at all.

**Comment by jamuhl** [comment]
All free to contribute to the documentation or code:

Still fact is:

```js
            <Trans 
                i18nKey="CategoryPage.NoSearchResultsHeaderWithText"
                values={ { searchTerm : searchTerm } }
                components={ [<span className="entered-search">{searchTerm}</span>] }>
            </Trans>
```

is 100% the same as:

```js
<Trans i18nKey="CategoryPage.NoSearchResultsHeaderWithText">
  Your search for <span className="entered-search">{{searchTerm}}</span> returned 0 results
</Trans>
```

Just the index of the child is different - so using `<1>` instead of `<0>` and all described https://react.i18next.com/latest/trans-component even how to get to the translation https://react.i18next.com/latest/trans-component#how-to-get-the-correct-translation-string and also the alternative @t7m uses: https://react.i18next.com/latest/trans-component#alternative-usage

But like said - OSS is about contributing
