### ISSUE TITLE
Configure Locale Settings in i18next instance

### ISSUE THREAD

**Issue by butchyyyy** [i18next/i18next#1113]
I'm using i18next with i18next-react using the translation HOC and would love a way to locale spefici settings in the i18n instance so i can use them in my components.
The locale settings would include stuff like:
  - Decimal separator
  - Thousands separator
  - Date format
  -   ...

Any chance this will get added into the i18next or it's something i should solve by writing my own plugin.

**Comment by jamuhl** [comment]
beside that if it's only about passing down additional props you can import: https://github.com/i18next/react-i18next/blob/master/src/index.js#L11

and pass info like any context provider: https://github.com/i18next/react-i18next/blob/master/src/I18nextProvider.js#L23

**Comment by butchyyyy** [comment]
It's about passing down additonal properties. My idea was to specify locale settings on i18n initialization

Something like:
```
i18n.init({
  localeSettings: [
    cs: {
      decimalSeparator: ",",
      thousandsSeparator: " ",
    },
    en: {
      decimalSeparator: ".",
      thousandsSeparator: ".",
})
```
And then in example component that renders decimal separator set by current language/locale

```
const Separator: React.SFC<InjectedI18nProps> = (props: InjectedI18nProps) => {
  return <h1>{`The current decimal separator is: ${props.i18n.localeSettings.decimalSeparator}`}</h1>
}

export default translate()(Separator)
```

I'll look into the code you posted

**Comment by jamuhl** [comment]
Having:

```js
i18n.init({
  localeSettings: [
    cs: {
      decimalSeparator: ",",
      thousandsSeparator: " ",
    },
    en: {
      decimalSeparator: ".",
      thousandsSeparator: ".",
})
```

you can access that again like:

```js

props.i18n.options.localeSettings

```

**Comment by butchyyyy** [comment]
But in that case i access localeSettings for all languages, so to get the settings for the currently selected one i would have to access the property like so:

```
props.i18n.options.localeSettings[props.i18n.language].decimalSeparator
```

**Comment by jamuhl** [comment]
yes...right...you might just make a little helper function to get that easier and add to i18n on after init call.

```js
i18n.init(/* ... */)

i18n.getLocaleSetting = function(name) {
  // eg. en-US
  if (i18n.options.localeSettings[i18n.language]) {
   return i18n.options.localeSettings[i18n.language][name];
  } 
  // try only en
  else if (i18n.options.localeSettings[i18n.language.split('-')[0]) {
    return i18n.options.localeSettings[i18n.language.split('-')[0]][name];
  }
  // take fallback
  else {
    return i18n.options.localeSettings[i18n.options.fallbackLng][name];
  }
}
```

**Comment by butchyyyy** [comment]
Oooh, tested and this will do what i want.

Still thinking about possibility to make it work not using accessor method (getLocaleSetting), but by introducing ```localeSettings``` property on the i18n instance object so it could be accessed by: ```props.i18n.localeSettings.decimalSeparator```.

Would it be possible by handling ```onLanguageChanged``` event
Or by writing a plugin?

**Comment by jamuhl** [comment]
hm...what you can do is using the `onLanguageChanged` event for sure...be creative ;)

**Comment by butchyyyy** [comment]
Works like a charm
```typescript
i18instance.on("languageChanged", (lng: string) => {
  i18instance.localeSettings = options.localeSettings[lng]
})
```
Also did following augmentation of the DefinitelyTyped typings to make it type safe
```typescript
import i18next from "i18next"

declare module "i18next" {
  interface LocaleSettings {
    decimalSeparator: string
    thousandsSeparator: string
  }

  interface LocaleSettingOptions {
    [key: string]: LocaleSettings
  }

  interface InitOptions {
    localeSettings: LocaleSettingOptions
  }

  interface i18n {
    localeSettings: LocaleSettings
  }
}
```

Thanks a lot for the help, closing

**Comment by jamuhl** [comment]
awesome...
