### ISSUE TITLE
Interpolation format function never gets called

### ISSUE THREAD

**Issue by goras** [i18next/i18next#1116]
Hi!

I've been trying to get the interpolation format function to work or even get called at all, but either I'm missing something very obvious or it's broken somehow.

As an example I used the [jsfiddle](https://jsfiddle.net/jamuhl/dvk0e8a9/#tabs=js,result,html) mentioned in the basic sample in the [documentation](https://www.i18next.com/overview/getting-started). The edited js looks like this:
```
i18next.init({
  lng: 'en',
  debug: true,
  interpolation: {
    // This function never gets called
    format: function(value) {
        alert("Format!")
        return value
    }
  },
  resources: {
    en: {
      translation: {
        "key": "hello world {{ text }}"
      }
    },
    de: {
      translation: {
        "key": "hello welt {{ text }}"
      }
    }
  }
}, function(err, t) {
  // init set content
  updateContent();
});

function updateContent() {
  document.getElementById('output').innerHTML = i18next.t('key', { text: "TEST" } );
}

function changeLng(lng) {
  i18next.changeLanguage(lng);
}

i18next.on('languageChanged', () => {
  updateContent();
});
```

The format function above never gets called. Any idea what's causing this or what I'm missing?
Thanks!

**Comment by jamuhl** [comment]
yes very obvious: https://www.i18next.com/translation-function/formatting

you need to have something like: `"key": "hello welt {{ text, myFormat }}"`

**Comment by goras** [comment]
Ahhh of course! Thanks a lot for the quick reply :)
