### ISSUE TITLE
onAdded event handler not called

### ISSUE THREAD

**Issue by Tobbe** [i18next/i18next#1119]
The `.on('added', () => {})` event handler isn't invoked when I call `addResource`. What am I doing wrong?

```
i18next
  .on('added', () => {
    print('added new resource');
  })
  .on('initialized', () => {
    print('initialized');
  })
  .init({
    fallbackLng: 'en',
    debug: true,
  });

setTimeout(() => {
  i18next.addResource('en', 'translation', 'SIGNUP', 'Sign up');
  print('getResource: ' + i18next.getResource('en', 'translation', 'SIGNUP'));
}, 1000);
```
https://jsfiddle.net/k428opj1/

The actual adding and getting of the translation works just fine, and the "initialized" message is printed, but the expected "added new resource" message is never printed.

**Comment by jamuhl** [comment]
that was a mistake in the documentation...sorry for that. It's no corrected:

https://www.i18next.com/overview/api#store-events

it's `i18next.store.on('added', () => {})` while i18next store is only available after init

```js
i18next
  .init({
    fallbackLng: 'en',
    debug: true,
  })
  .on('added', () => {
    print('added new resource');
  })
  .on('initialized', () => {
    print('initialized');
  });

setTimeout(() => {
  i18next.addResource('en', 'translation', 'SIGNUP', 'Sign up');
  print('getResource: ' + i18next.getResource('en', 'translation', 'SIGNUP'));
}, 1000);
```

**Comment by Tobbe** [comment]
Thanks for the fast response and fix! 👍 

To chain it, I did this:

```
i18next
  .init({
    fallbackLng: 'en',
    debug: true,
  })
  .on('initialized', () => {
    print('initialized');
  })
  .store.on('added', () => {
    print('added new resource');
  });
```

At first I had to call to `.store.on('added'` first, and then `.on('init...` but that didn't work. I guess `.store.on(` returns the store instance. Does it? And `i18next.on(` returns the `i18next` instance?

**Comment by jamuhl** [comment]
yes would return the store instance...so keeping that last will do.
