### ISSUE TITLE
Hebrew plural support

### ISSUE THREAD

**Issue by LeonardDrs** [i18next/i18next#1120]
Hi,

I'm using i18next for a while now but I just noticed that the Hebrew support seems out to date with the spec.
Based the [JSFiddle](https://jsfiddle.net/3sL01fn0/38/) found in the doc (edited to display the `he-IL` language), we are using the basic plural form, whereas this [doc](http://www.unicode.org/cldr/charts/33/supplemental/language_plural_rules.html#he) specifies multiple plural category.

Is there any plan to update this rule?

**Comment by jamuhl** [comment]
Agree…might need a new rule: https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L40

Would you be open to provide a PR?

**Comment by LeonardDrs** [comment]
Yes, started with a PR there: 
https://github.com/translate/l10n-guide/pull/71

Might be a 404, as there is some issues on Github [side](https://status.github.com/messages)

Following with a PR on this repo as well.

**Comment by jamuhl** [comment]
Agree…might need a new rule: https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L40 <https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L40>

Would you be open to provide a PR?

**Comment by jamuhl** [comment]
yes github is a little instabil today...but seems having recovered now...PR was merged...thank you
