### ISSUE TITLE
hebrew support for `something_plural` got broken

### ISSUE THREAD

**Issue by vzaidman** [i18next/i18next#1122]
after pr #1121 (which is abviously great :D thank you @LeonardDrs!)

hebrew support for `something_plural` got broken.

**Comment by jamuhl** [comment]
you will need to change those plurals to the form: https://www.i18next.com/translation-function/plurals#languages-with-multiple-plurals

hm...for next time we should make such changes in a major (breaking) version - sorry for not being to aware of the impact.

**Comment by vzaidman** [comment]
maybe we should release a minor version with reverting this fix and a major version with it?

**Comment by vzaidman** [comment]
what about allowing the word plural to indicate "any plural"?

**Comment by vzaidman** [comment]
@LeonardDrs please note*

**Comment by vzaidman** [comment]
what about allowing "plural" to exist in all languages for >1?

**Comment by jamuhl** [comment]
not going in for that...as it's wrong

**Comment by jamuhl** [comment]
apply that to chinese or russian...just not the right thing

**Comment by vzaidman** [comment]
so maybe we should allow this form only for certain languages?

**Comment by jamuhl** [comment]
if requested by more people i would say yes - but in current state?!?

you can solve this in userland by overriding `i18next.services.pluralResolver.getSuffix` https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L119

**Comment by vzaidman** [comment]
great. thank you.

**Comment by jamuhl** [comment]
if not happy with that you might provide some more details on how you would implement this or better a PR to review.

**Comment by 0xR** [comment]
Could you update the migration guide? I was considering whether the upgrade to 12 is safe.

**Comment by jamuhl** [comment]
@0xR  https://www.i18next.com/misc/migration-guide#v-11-x-x-to-v-12-0-0


And don’t forget to star this repo. Make a tweet or have a look at our https://locize.com -> there are many ways to help this project :pray:

**Comment by vzaidman** [comment]
i'd link to https://www.i18next.com/translation-function/plurals in the description as well

**Comment by jamuhl** [comment]
@vzaidman done

**Comment by vzaidman** [comment]
too bad i can't star 5 times :P

**Comment by LeonardDrs** [comment]
Hi!
Sorry @jamuhl, it was a breaking change for Hebrew indeed, did not paid attention enough. That's on me.

Thanks for your updates!

**Comment by jamuhl** [comment]
@LeonardDrs no need to take this on you...let's say we both missed it -> but thanks to @vzaidman we could react and revert the mistake...

**Comment by vzaidman** [comment]
by the way, for those who are interested, I end up using:
```
      const origGetSuffix = ctx.i18n.services.pluralResolver.getSuffix;
      ctx.i18n.services.pluralResolver.getSuffix = (code, count, ...other) => {
        if (code === 'he') {
          if (count > 1) {
            return '_plural';
          }
          return '';
        }
        return origGetSuffix.call(ctx.i18n.services.pluralResolver, code, count, ...other);
      };
```

**Comment by dagan-arbox** [comment]
@vzaidman where do you place this code?
my code example:
` init: (language) => {
        return new Promise((resolve, reject) => {
            i18next
                .use(languageDetector)
                .use(translationLoader)
                .init({
                    fallbackLng: config.fallback,
                    ns: config.namespaces,
                    defaultNS: config.defaultNamespace,
                    lng: language ? language : config.fallback,
                    interpolation: {
                        escapeValue: false,
                        format(value, format) {
                            if (value instanceof Date) {
                                return date.format(value, format);
                            }
                        }
                    },
                    react: {
                        // ...
                        hashTransKey: function(defaultValue) {
                            // return a key based on defaultValue or if you prefer to just remind you should set a key return false and throw an error
                        },
                        defaultTransParent: 'div', // a valid react element - required before react 16
                        transEmptyNodeValue: '', // what to return for empty Trans
                        transSupportBasicHtmlNodes: true, // allow <br/> and simple html elements in translations
                        // transKeepBasicHtmlNodesFor: ['br', 'strong', 'i'], // don't convert to <1></1> if simple react elements
                    }
                }, (error) => {
                    if (error) {
                        return reject(error);
                    }
                    date.init(i18next.language)
                        .then(resolve)
                        .catch(error => reject(error));
                });
        });

    },`

**Comment by vzaidman** [comment]
```
18n.init({
    ...
  });

  const origGetSuffix = i18n.services.pluralResolver.getSuffix;
  i18n.services.pluralResolver.getSuffix = (code, count, ...other) => {
    if (code === 'he') {
      if (count > 1) {
        return '_plural';
      }
      return '';
    }
    return origGetSuffix.call(i18n.services.pluralResolver, code, count, ...other);
  };

```
