### ISSUE TITLE
(help) How to parse data-18n?

### ISSUE THREAD

**Issue by Flynrod** [i18next/i18next#1124]
Hello,

I would like to point out that I am starting with i18next and have been looking for ways to solve my problem but without really understanding or succeeding.

I am currently using i18next (vanilla) in a development environment with webpack (but with the official i18n library, not any loaders/plugins here). 
My problem is that i18next does not parse the "data-18n" html tags.
(I tried to try jquery.i18n but I got a lot of error which led me to use i18next vanilla.)

```javascript
i18next
    .use(i18nextXHRBackend)
    .use(i18nextBrowserLanguageDetector)
    .init({
      fallbackLng: 'fr',
      debug: true,
      backend: {
        loadPath: 'translations/{{lng}}.json',
        crossDomain: true
      }
    }, function(err, t) {
      $(".container").i18n();
    });

    function updateContent() {
      document.getElementById('presentation').innerHTML = i18next.t('nav.presentation');
      document.getElementById('location').innerHTML = i18next.t('nav.location');
      document.getElementById('medias').innerHTML = i18next.t('nav.medias');
    }
    
    $('#fr').click(function() {
      i18next.changeLanguage('fr');
      /* location.reload(); */
    });

    $('#nl').click(function() {
      i18next.changeLanguage('nl');
      /* location.reload(); */
    });
    
    i18next.on('languageChanged', () => {
      updateContent();
    });
```

Hoping you can tell me more about this problem. :)

**Comment by jamuhl** [comment]
i18next itself does not care for data-i18n - it is not web only:

choose one of:

- jquery-i18next
- https://github.com/mthh/loc-i18next as a html5 comparable implementation to jquery-i18next
- https://github.com/i18next/i18nextify as a vdom solution

**Comment by Flynrod** [comment]
Thank you very much! :) I'm going to open an exit on the repo of the library I'm using.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
