### ISSUE TITLE
vue-i18next: Reduce the number of implementations - join the forces on one implementation

### ISSUE THREAD

**Issue by jamuhl** [i18next/i18next#1125]
i18next goal was always to be usable in all the UI frameworks out there. While i18next got a wide adoption and react-i18next (https://github.com/i18next/react-i18next) got very popular we struggle in being successful on vue.js.

One main problem I currently see there are three implementations developers can choose from. This spreads activity, adds the burden of having to choose on devs and make doing "marketing" for those harder.

I really would love to see i18next being more successful in the vue.js community.

So I would love to have your inputs on:

- Would it make sense to join all the implementations (contributors/maintainers) to one "more official" implementation optionally under i18next organization? Would you be willing to help with code, documentation, samples, tweets, medium posts, ...?
- Do you have ideas on how to spread the word more?
- ...

**Comment by jamuhl** [comment]
@claudiocro @rse @bluelovers

**Comment by bluelovers** [comment]
![default](https://user-images.githubusercontent.com/167966/47822850-a5256f80-dda0-11e8-98eb-1d4817d466ac.png)

download number is super dead

**Comment by jamuhl** [comment]
@bluelovers agree...nowadays sadly it's not enough to build it - and people will come. The semi success of react-i18next (compare it to react-intl which has the numbers *4) comes from a lot of factors - having worked a lot on documentation and samples, having made endless tweets, posts and articles.

So you think - we should invest or invest no more time into bringing i18next to vue?!?

**Comment by bluelovers** [comment]
i don't know lol
