### ISSUE TITLE
Long texts

### ISSUE THREAD

**Issue by nanom1t** [i18next/i18next#1127]
Hello,

Is there any solutions to translate long texts with i18next? 

For example, I want to translate Terms of service and Privacy policy on my website. It is unconvinient to store large texts in JSON format. Maybe there are some plugins for translating html or is it better to store texts in database?

Thanks

**Comment by jamuhl** [comment]
store it as one key/value in the JSON -> and use markdown

**Comment by nanom1t** [comment]
Like this?
```
{
"long_text": "<h1>Terms of service</h1><p>....</p>"
}
```

**Comment by nanom1t** [comment]
@jamuhl Yes, but as I said I have a very long texts. Before setting it to JSON key-value I need to manually remove all new lines and make a single line from long text. If I want to modify this text I need again reformat it, save and remove all new lines/spaces again.

For example:
```
<h1>Terms of service</h1>

<h2>The Summary</h2>

<p>The User Agreement ("Terms of Use") establishes the rules for using the service («Application» or «Service»). When we mention Service, we mean the current website, together with all affiliated websites and applications.</p>

<p>The Terms constitute a binding legal agreement between you as user («User») and the Service Administration («we» or «us»). The present Agreement is a public document and may be altered and/or added to by the Service Administration unilaterally without providing any special notification to a User.</p>

<p>The Terms apply whenever you visit our Service, whether or not you have chosen to register with us, so please read them carefully. By accessing, using, registering for or receiving services offered by our Service you are accepting and agreeing to be bound by the Terms.</p>

<p>IF YOU DO NOT ACCEPT AND AGREE TO THE TERMS THEN YOU MUST NOT ACCESS OR USE THE APP OR SITE.</p>

<h2>Use of the service</h2>

<p>You warrant that you have the right, authority and capacity to enter into and be bound by the Terms and that by using out Service you will not be violating any law or regulation of the country in which you are resident. You are solely responsible for your compliance with all applicable local laws and regulations.</p>

<p>You further warrant that you have not been convicted of, nor are subject to any court order relating to assault, violence, sexual misconduct or harassment.</p>

<h2>Content</h2>

<p>You are able to post or upload all kinds of things, including photographs, emails, messages, live streamed audiovisual content and other content («Content»). When you are using the Service you may not post, send or upload any Content which:</p>
....
```

**Comment by jamuhl** [comment]
Hm...guess this is what a "translation management" is for...there is no way to circumvent the technical restrictions. Eg. have a look at ours: https://locize.com

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by nanom1t** [comment]
Ok. Thank you.

**Comment by javierguzman** [comment]
@nanom1t did you solve this without using locize at the end somehow? I am in the same situation and I am not sure locize is what I need, at least right now. I am building an application on my own and they offer only 14 days for free as far as I am aware. For me , in my personal situation, it would be better to be free until you exceed certain limits. Also, it looks like a tool more suitable for people who want to write something in one language and then use the machine to translate on the fly. In my situation I want to take advantage I know several languages and do the translation myself as the machines still lose some tiny details in how to say certain things.

**Comment by jamuhl** [comment]
@javierguzman locize is about translation - being you translating or your translators...while we over the option to use machine translations - we really do not promote doing so...our personal opinion about machine translations is still they are ok for a first fast iteration - but not ok for production in most cases...(personally we would never use them in production).

Personally we use markdown for long texts...but other options might work too -> in the end it's a key and a value in your json if using i18next (or a markdown file you lazy load using some dynamic load using current lng in file name)...

**Comment by javierguzman** [comment]
@jamuhl Hello Jan! Good to know for future I can use locize and provide the translations myself, indeed I agree I would not use runtime machine translation in production.

You have just said "or a markdown file you lazy load" does that mean we can load markdown files directly rather than a json when using i18next or react-i18next? That would be good enough for me right now, at least is better than having to call t('translation') in every paragraph for certain scenarios where you need a lot of text like privacy policy for example. Do you know if there is an example somewhere of this? Because I have not managed to find anything in a quick glance.

As always thank you Jan.

**Comment by jamuhl** [comment]
@javierguzman it's a little work to glue things together but nothing too complicated.

**Comment by javierguzman** [comment]
@jamuhl all right! I might give a go in a couple of weeks. I might try first with an empty project so maybe I could make a pull request later on for the examples folder.

**Comment by javierguzman** [comment]
Hello all,

As promised! I just managed to create my terms and conditions in different languages using markdown and dynamic import. Not sure if it the most efficient way but it works!

I have created a gist for people to take a look in future and see the basic structure that needs to be in place:

https://gist.github.com/javierguzman/35c214a771c7e39f8eb00f601504b6f7

**Comment by rparree** [comment]
This is using client-side rendering. Did you try-out any solution that involves ssr?

**Comment by javierguzman** [comment]
@rparree No yet. In future I would like to do stuff like this in the server, but not now. However, from my ignorant point of view, the concept should not be very different, should it?

**Comment by rparree** [comment]
@javierguzman Problem is i'm use mdx. I have it somewhat working, but still get an error. 

The page is displayed correctly in the correct language, but i get this error on top of it the first time i access the page

```
Unhandled Runtime Error
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

This is the code i'm using: https://gist.github.com/rparree/c5db7abbab314ef39d3ca6208b8302bf

**Comment by rparree** [comment]
Found a solution: https://gist.github.com/rparree/c5db7abbab314ef39d3ca6208b8302bf

**Comment by javierguzman** [comment]
Thanks for sharing @rparree I might use your code as future reference when I start porting stuff to server side rendering :)

**Comment by yairEO** [comment]
I've switched my `json` format translation files to [`json5`](https://json5.org/) format, which allows multiple lines per key, which allows me to easily translate long text blocks. 

I am using `Parcel` is my bundler for [my website](https://www.future-fortune.com/), and it supports importing `json5` files, so all I had to do is rename the file extension to `.json5` and change the import file name also:

```js
import en from './en.json5'
```

multi-line is then written as so:

```json5
"tour": {
    "welcome": "<0>Welcome To <1>Future Fortune</1> Financial Calculator</0> \
      <1> \
        <0>Plan your retirement</0> with ease, projecting different future scenarios, living off \
        your investments by a monthly withdrawal \
      </1> \
      <2>👉 &nbsp; Best used on desktop computer 🖥️</2> \
      <3> \
        This website does not use a server \
        therefore the data you provide cannot be stored. \
        There is no sign-in so your identity is unknown \
      </3>"
  }
```
