### ISSUE TITLE
V13: Roadmap

### ISSUE THREAD

**Issue by jamuhl** [i18next/i18next#1129]
- [x] Typescript definitions
- [x] Promise support

Will be breaking as returning Promises eg. on i18next.init() will replace the previous return value (this) for chaining calls.

**Comment by jamuhl** [comment]
Promises: https://github.com/i18next/i18next/pull/1130

**Comment by jamuhl** [comment]
@schettino - do you have time to add typescript here in the next few weeks?

**Comment by schettino** [comment]
I'm going to start right away

**Comment by jamuhl** [comment]
@schettino awesome...but no need to rush...take the time needed.

**Comment by schettino** [comment]
Checking this out. I'll review it in order to get this out asap. I'm looking forward writing the typedefs for the hooks. @jamuhl how's the roadmap for releasing them and how stable they are

**Comment by jamuhl** [comment]
@schettino regarding the react-i18next hooks i would say it won't have any changes (or just smaller) as there was no feedback for some time and a few comments like this one: https://github.com/i18next/react-i18next/issues/590#issuecomment-443009608

so there is more or less just SSR (next.js), types and test coverage that are to be done before releasing (when react releases v16.x containing hooks: https://reactjs.org/blog/2018/11/27/react-16-roadmap.html (currently Q1 2019))
