### ISSUE TITLE
Is it possible to have Multiple contexts?

### ISSUE THREAD

**Issue by FranciscoGileno** [i18next/i18next#1132]
Hi,

Is there a way to achieve multiple contexts?

My scenario is:
```
t('title', { context: ['step-name', 'step-status'] })
```

it would look at: `title_step-name_step-status`

**Comment by jamuhl** [comment]
no...but that is not what context is meant for -> why not just building a dynamic key on your side like eg. `t(\`title-${step-name}-${step-status}\`)` ?!? you can even do fallback like context would do by passing multiple keys: `t([\`title-${step-name}-${step-status}\`, \`title-${step-name}\`])`

**Comment by FranciscoGileno** [comment]
It makes sense.

Thank you!

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by sgara** [comment]
Hi! This is something I'd like to see as well for a bit of a different use case:
I'm building a survey where some questions and/or answers depend on interviewee's gender or on their role (professional, customer, ...) or both, or none. 
Using a single `${gender}-${role}` key requires duplication of many identical translations, and I don't see any way to overcome this... do you have any idea? Thanks!
