### ISSUE TITLE
Pass a format type to the format function

### ISSUE THREAD

**Issue by leanazulyoro** [i18next/i18next#1133]
It would be nice if the interpolation.format function would recibe an indicator of what the value actually is (e.g. "date", "number", "currency"). That way we could just chose a more specific formatter function for each type, with a simple switch statement for example.

The current implementation receives only the value, this means one has to analyse it in order to determine what formatter to apply.

In my case I'm using moment.js and numeral.js.
For *moment.js* is easy enought: just an `value instanceof Date`is enought.
But, for *numeral.js*, it get's uglier: to determine if it actually is a value numeral.js would handle, I need to actually call the numeral function, and check if the returned value is undefined:
```javascript
const num = numeral(value);
if (num.value()) return numeral(value).format(format)
```

This way is really inefficient, since the value has to be analysed for each case until one fits. That may lead to, as demostrated, calling functions to check if a certain formatter library can handle the value. 

This is what I have right now:
```javascript
const dateFormatter = (value) => (format, lng) => moment(value).format(format);
const numberFormatter = (value) => (format, lng) => numeral(value).format(format);

// choose a formatter by analysing the value
const chooseFormatter = (value) => {
  if(value instanceof Date) return dateFormatter(value);
  let num = numeral(value);
  if (num.value()) return numberFormatter(value);
  return value;
};

const i18nConfig = i18n
.init({
   //...
    interpolation: {
      format: (value, format, lng) => chooseFormatter(value)(format, lng)
    },
  // ...
});
```

This is what I would like it to be:
```javascript
const dateFormatter = (value, format, lng) => moment(value).format(format);
const numberFormatter = (value, format, lng) => numeral(value).format(format);

// get a formatter by type
const getFormatter = (type) => {
  switch (type) {
    case 'date': return dateFormatter;
    case 'number': return numberFormatter;
    default: return value
  }
};

const i18nConfig = i18n
.init({
   //...
    interpolation: {
      format: (value, type, format, lng) => getFormatter(type)(value, format, lng)
    },
  // ...
});
```

The question is: where would the "type" come from?
Could it just be the interpolation "key" that gets passed to the format function?
for instance, given the following interpolated string:
```
"The current date is {{date, MM/DD/YYYY}}"
```
the format function would receive the string "date" as the type.

Could we do something like this?
thanks!

**Comment by leanazulyoro** [comment]
The above could actually be a default implementation of the format function, and just provide an option like "formatMap" that would take and object of the sort:
```javascript
{
  "date": dateFormatterFunction,
  "number": numberFormatterFunction
  "other": otherFormatterFunction
}
```

**Comment by jamuhl** [comment]
why not just solve it like:

```js
const i18nConfig = i18n
.init({
   //...
    interpolation: {
      format: (value, typeAndFormat, lng) => {
         const [type, format] = typeAndFormat.split('---');

    switch (type) {
    case 'date': return moment(value).format(format);
    case 'number': return numeral(value).format(format);
    default: return value
  }
      }
    },
  // ...
});
```

with:

`"The current date is {{date, date---MM/DD/YYYY}}"`

**Comment by leanazulyoro** [comment]
I thought that yes, but it's kinda using some parameter for something it was not ment to, isn't it?

**Comment by jamuhl** [comment]
hm..in the end it's a custom format - not just the format you pass to something like moment.

**Comment by jamuhl** [comment]
personally i use it more like something "meaningful" than as a 1:1 format of moment.js, ....like eg.

format = `shortDate`, `fromNow`, ...not giving the full format option to choose from to the translators.

**Comment by leanazulyoro** [comment]
I get it, you're using the format parameter as the key to know what it is that you're formatting.
That makes sense, still it's kinda confusing, most of all because in the docs there's an example that shows it as I described above: https://www.i18next.com/translation-function/formatting

I could do something like that to work around it. But the way I see it, the format function could have it's implementation hidden by having that "type" parameter (or some other name), after all I don't think there would be much more logic in it than just distribute values to formatter functions IMHO.

**Comment by jamuhl** [comment]
The sample shows both options. So nothing is hindering doing what you like...while adding a third param will need changes in endless places (not only in this repo). So for now i would not like to add a third param to add a type while you can use a combined typeFormat passed to your format function.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by bdrazen** [comment]
Any way to pass dynamic variables into the format parameter? Something like `"The current date is {{date, {{value}}---MM/DD/YYYY}}"` doesn't seem to work.
