### ISSUE TITLE
cimode breaks site when arrays or objects used in translation files

### ISSUE THREAD

**Issue by fi5u** [i18next/i18next#1134]
I make use of arrays and objects in the translation files. When I switch to cimode the site breaks since the page is expecting an array of strings for a translation key. Is there any way to override the functionality of the cimode to somehow generate an array of strings in cimode?

**Comment by fi5u** [comment]
Ok, I understand, thanks for the clarification. I'll probably just build something into my code to handle these situations.

Many thanks.

**Comment by jamuhl** [comment]
If you still come up with an idea let me know. For now it seems the best solution to solve it in userland.

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
