### ISSUE TITLE
defaultNS option is ignored

### ISSUE THREAD

**Issue by yjacobowitz** [i18next/i18next#1135]
I upgraded from v11.6.0 => v12.0.0 and noticed that the defaultNS property in options is not working.

My options look like this: 
`const options = {
fallbackLng: 'en-US',
lng: 'en-US',
lowerCaseLng: true,
 load: 'currentOnly',
 ns: 'common',
defaultNS: 'common',
debug: false,
react: { wait: true },
  keySeparator: '~',
  nsSeparator: false,
interpolation: { escapeValue: false }, // not needed for react
};`

I noticed in the documentation that the default value for defaultNS was changed from 'common' to 'translation' but this should not affect my current code since I explicitly set 'common' as my defaultNS and ns, and yet the t function still tries to load 'translation'. Any ideas how to fix this?

**Comment by jamuhl** [comment]
defaultNS always was `translation`. Guess cause is react only: https://github.com/i18next/react-i18next/blob/master/src/NamespacesConsumer.js#L95

could you open an issue there: https://github.com/i18next/react-i18next

**Comment by jamuhl** [comment]
but even there it only would "emergency" fallback in cases there is no i18n instance found:

https://github.com/i18next/react-i18next/blob/master/src/NamespacesConsumer.js#L88 -> https://github.com/i18next/react-i18next/blob/master/src/NamespacesConsumer.js#L105

Could you please add more code to see what is wrong in your codebase?

**Comment by yjacobowitz** [comment]
yeah I'll open an issue there, I see that common.json is loaded but t function tries to load from translation, even though I explicitly set the defaultNS to common. Only when I change the name of the file to translation.json it works: 

This is with the options that I wrote before:
![image](https://user-images.githubusercontent.com/17860133/48698134-fd58d000-ebee-11e8-9e65-81cc29efd382.png)

![image](https://user-images.githubusercontent.com/17860133/48698192-1feae900-ebef-11e8-91f9-fe3a6aeb81fe.png)

So for some reason I am getting defaultNS undefined even though I set it to 'common' and you can see the t function uses the namespace 'translation'

**Comment by jamuhl** [comment]
best provide a sample on https://codesandbox.io/s/l4qrory2nl...seems really something is wrong with your configuration

**Comment by yjacobowitz** [comment]
fixed this by changing ns and defaultNS to "translation" and changing common.json -> translation.json

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by JoshMcCullough** [comment]
> fixed this by changing ns and defaultNS to "translation" and changing common.json -> translation.json

So not fixed, but worked-around. I'm running into this as well. `translation.json` is being fetched even though my `defaultNS` is something else.
