### ISSUE TITLE
onMissingKey fired even when the keys exist

### ISSUE THREAD

**Issue by richardhsueh** [i18next/i18next#1137]
I am using "i18next-xhr-backend" to load the language file from external link
And here is the init setting that i used.
```
i18n
  .use(backend)
  .use(reactI18nextModule)
  .init({
    lng: 'en',
    fallbackLng: 'en',
    ns: ['translation'],
    keySeparator: false,
    interpolation: {
      escapeValue: false 
    },
    backend: {
      loadPath: 'locales/{{lng}}/{{ns}}.json',
      addPath: '/api'
    },
    saveMissing: true
  })
  .on('missingKey', function(lngs, namespace, key, res) {console.log(lngs, namespace, key, res)});
```

And somehow it fired on all the keys, even though there is only one missing key.
![screenshot 2018-11-22 at 12 48 41 pm](https://user-images.githubusercontent.com/33024986/48882390-f7642880-ee54-11e8-95a2-e0f98b48e3f8.png)

Any idea what causing this? 
Is it the setting incorrect or what ?

**Comment by jamuhl** [comment]
It does send save missing if your code is accessing a key before it was loaded...https://github.com/i18next/i18next/blob/master/src/Translator.js#L160

So it might be only one key is missing in your JSON - but your applications uses all the keys before it loaded that JSON - so for the code all of them are missing in that moment of first render...

Try setting:

```js
i18n
  .use(backend)
  .use(reactI18nextModule)
  .init({
    // ....
    react: { wait: true } 
  });
```

https://react.i18next.com/components/withnamespaces#withnamespaces-options ----> wait

**Comment by richardhsueh** [comment]
I see. It all makes sense now. But one more question.
Currently i have set up two language (en & fr), but it seems it won't check fr language file for that missing key, since the "fallbackLng" is set to "en", is it possible to also check all language file ?

**Comment by jamuhl** [comment]
Sadly i18next itself only checks for getting a value when resolving a key -> so if it does not find it in eg. "fr" but in the defined fallbackLng it won't trigger missing.

a) to make sure all keys exist in all languages there are translation management tools like our https://locize.com

b) set fallbackLng to false and use: https://www.i18next.com/overview/configuration-options#missing-keys --> saveMissingTo: 'current'

**Comment by richardhsueh** [comment]
Got it! Thanks a lot. 🙏

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
