### ISSUE TITLE
How to make a site with pretty URLs?

### ISSUE THREAD

**Issue by johndelmez** [i18next/i18next#1138]
Hello,

First of all, I read this issue which seemed to me to correspond to solving my problem but I don't understand it after several rereading and testing: https://github.com/i18next/react-i18next/issues/325

I also tried this one (with .htaccess) : https://github.com/i18next/i18next/issues/144
But it gives a 404 error.

I recently tried to make a site with i18next, which works fine but I would like to be able to add nicer URLs with country codes.

Example instead of (which change the language):
```
https://www.mywebsite.com/index.html?lng=fr-BE
```
this
```
https://www.mywebsite.com/fr-BE
```

Knowing that **I can't use back-end language like PHP,** etc... that I use an **Apache web server** and that I only use **i18next** with **jquery.i18next**.

To describe my problem a little more in depth, how could I make sure that when a user arrives on any page it adds the country code?
What if it already has a country code in the URL, change the user's language?

And above all, is it possible?

Thank you for reading my issue and hoping that you can help me with my problem. :)

P.S.: Please excuse me for my English

**Comment by jamuhl** [comment]
you really should ask this question on stackoverflow.com - it is not related to i18next directly...you can use https://github.com/i18next/i18next-browser-languageDetector -> detection from path to set language in i18next to get the translations in needed language.

What you ask is about navigation / routing...which depends on http rewrite whatever your using for redirecting serverside -> or if done clientside custom code in your clientside router to set location.href like needed.
