### ISSUE TITLE
Language detection by domain

### ISSUE THREAD

**Issue by lucasfeliciano** [i18next/i18next#1139]
I've been trying to implement a language detection by domain but I've been struggling to find a good solution.

I have the same setup as the example of with `nextjs` in this repository.

Also, I looked at the dependencies `i18next-browser-languagedetector` and `i18next-express-middleware` to figure out if would be the best place to do that since we have `subdomain` detection mode there, how ever I didn't even find that mode at: `i18next-express-middleware` 

https://github.com/i18next/i18next-express-middleware/blob/master/src/LanguageDetector.js

I would love to help on the implementation of this feature I just need some direction to know which path the `i18next` want fo follow

What I'm trying to achieve is: 

`domain.nl`: `nl`
`domain.es`: `es`
`domain.com`: `en`

**Comment by jamuhl** [comment]
not sure if mapping a domain to a language is a good option -> domain.ch -> what do you set language to (we have 4 languages in switzerland).

but both browser and express language detector have an easy option to add a custom detection function to it.

https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality
https://github.com/i18next/i18next-express-middleware#adding-own-detection-functionality

**Comment by lucasfeliciano** [comment]
That is clever!

And it will work for my use case!

Thanks for the quick reply!

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
