### ISSUE TITLE
Creating own postprocessor typescript

### ISSUE THREAD

**Issue by tp-team-14** [i18next/i18next#1141]
Hi,
I want to posprocess translation if it contains unicode character and change it for string
From documentation i have created this code
```
const stringBreaksPostprocessor = {
  type: 'postProcessor',
  name: 'stringBreaksPostprocessor',
  process: (value: string, key: string, options: Object, translator: any) => {
    return value.replace(/\\u(\w\w\w\w)/g, (a, b) => {
      let charcode = parseInt(b, 16);
      return String.fromCharCode(charcode);
    });
  },
};

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(reactI18nextModule)
  .use(stringBreaksPostprocessor)
  .init({
    fallbackLng: 'de',
    ns: ['translations'],
    defaultNS: 'translations',
    debug: false,
    interpolation: {
      escapeValue: true,
    },
    react: {
      wait: true,
    },
  });
```

Problem is when i run my code i get
`no-unused-expression: unused expression, expected an assignment or function call`
And error points to method `permanentRegister` more specific to line
`   return orig.apply(this, arguments);`

**Comment by jamuhl** [comment]
Can't make anything out of this error - but seems only related to you code? or can you point to the issue in i18next code `return orig.apply(this, arguments);` doesn't tell me anything

**Comment by jamuhl** [comment]
any update on this?

**Comment by jamuhl** [comment]
closing due inactivity
