### ISSUE TITLE
The 'format' function cannot be overridden inside a t invocation

### ISSUE THREAD

**Issue by Kovensky** [i18next/i18next#1154]
Related to #1034.

The problem here is that Interpolator only updates its `this.format` function when it's constructed, but not when it's `.init`ed: https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L15

When it's `.init`ed inside the `t` implementation, the 2nd argument is (correctly) not `true`, so it completely ignores the `format` option: https://github.com/i18next/i18next/blob/master/src/Translator.js#L194

---

(personally, I think this instance reuse / dynamic updating is incredibly dangerous and definitely not reentrant or thread-safe, but I come from languages with more concurrency than javascript)

**Comment by jamuhl** [comment]
> (personally, I think this instance reuse / dynamic updating is incredibly dangerous and definitely not reentrant or thread-safe, but I come from languages with more concurrency than javascript)

fully agree...done that as a workaround - was never the plan to do it like that...so that part might get a rewrite someday

still reply stays the same as on https://github.com/i18next/i18next/issues/1034 we are aware it's not possible....PR changing that would be welcome

**Comment by jamuhl** [comment]
Where in the doc this is stated - could you give me the link...easier than searching through all docs

**Comment by Kovensky** [comment]
Oops. It's in here: https://www.i18next.com/translation-function/formatting#additional-options

**Comment by jamuhl** [comment]
just published an update removing that...should be online in a few minutes.
