### ISSUE TITLE
translate option in selectbox

### ISSUE THREAD

**Issue by Esty1** [i18next/i18next#1155]
Hi,
thanks on the code!
I try translate the text in the option of a select box, but its not work.
can you help please?
here is my code:
```
<select class="chosen-select" name="country" tabindex="2">
    <option data-i18n="country" value="">Choose a Country...</option>
</selecet>

```
thanks

**Comment by jamuhl** [comment]
do you use jquery-i18next? if so please provide a full codesandbox, jsfiddle, what ever...no reason this should not work

**Comment by jamuhl** [comment]
feel free to reopen with a sample to reproduce
