### ISSUE TITLE
addResourceBundle works unexpectedly

### ISSUE THREAD

**Issue by Elminday** [i18next/i18next#1156]
Code:

```
import i18next from 'i18next';

i18next.init();
i18next.addResourceBundle('en', 'namespace1', {
  key: 'hello from namespace 1',
});
console.log(i18next.t('namespace1:key')); // key
console.log(i18next.t('key')); // key
```

Why I do not get `hello from namespace 1' ?

**Comment by jamuhl** [comment]
did you set lng to en?

**Comment by Elminday** [comment]
```
const OPTIONS = {
  lowerCaseLng: true,
  fallbackLng: 'en',
};

i18n
  .use(BrowserLanguageDetector)
  .init(OPTIONS);

i18n.use('en', 'namespace1', { key: 'hello from namespace 1' });
console.log(i18n.t('namespace1:key'));
console.log(i18n.t('key'));
```

This way should it fallback to 'en'?

**Comment by Elminday** [comment]
Adding:
```i18n.changeLanguage('en');``` 
does not change anything though.

**Comment by jamuhl** [comment]
```js
import i18next from 'i18next';

i18next.init({
  fallbackLng: 'en'
});
i18next.addResourceBundle('en', 'namespace1', {
  key: 'hello from namespace 1',
});
console.log(i18next.t('namespace1:key')); // key
console.log(i18next.t('key')); // key
```

should work

**Comment by Elminday** [comment]
It does, I had mistype... Thanks a ton for help!

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by jamuhl** [comment]
yes -> alternative you could add resources on init: https://www.i18next.com/how-to/add-or-load-translations#add-on-init

**Comment by Elminday** [comment]
One more question. I can not find anything related in documentation.
How do you propose to decouple resource files (different bundles).

```
const UserBundle = {
  en: {
    module: 'User window',
  },
};

const DocumentsBundle = {
  en: {
    module: 'User window',
  },
};
```

User bundle does not know anything about document bundle and likewise.
However we want to use the same i18next instance, and load it on demand with different bundles

**Comment by jamuhl** [comment]
Not sure what you like to achieve...you mean using namespaces? https://www.i18next.com/translation-function/essentials#accessing-keys-in-different-namespaces
