### ISSUE TITLE
Memory leak when upgrading from 11.10.2 to 13.1.0

### ISSUE THREAD

**Issue by lewilewilewi** [i18next/i18next#1159]
This is with Babel 7, node 10.14.x
Not sure what's going on here, but reverting from 13.1.0 back to 11.10.2 removed the leak.

**Comment by jamuhl** [comment]
Can you add steps how to reproduce the leak?

**Comment by eilonmore** [comment]
Can verify here. so far it happened to us only in development, using a hot-reloading + SSR.
version - 13.1.2

**Comment by jamuhl** [comment]
closing for now...feel free to reopen with reproducable sample
