### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by desmeit** [i18next/i18next#1160]
I get the following errors:

`i18nextXHRBackend.min.js:1 Access to XMLHttpRequest at 'file:///XXX/languages/de.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

`i18next.min.js:1 i18next::backendConnector: loading namespace translation for language de failed failed parsing languages/de.json to json`

My code:

```
  <script src="js/i18nextXHRBackend.min.js" ></script>
    <script src="js/i18next.min.js" ></script>
    <script src="js/jquery-i18next.min.js" ></script>
```

```
        i18next.use(i18nextXHRBackend);
	  i18next.init({
		 			debug: true,
					lng: 'de',
					fallbackLng: 'de',// falls ein Key oder eine Sprache nicht vorhanden ist
					backend: {
					  loadPath: 'languages/{{lng}}.json'
					}
					 }, function(err, t) {
					jqueryI18next.init(i18next, $);
					$('.view-main').localize();
					
					console.log('error ' + err);
				  });
```

JSON File:

```
{
	
	text: {
                t1: 'Deutsch',
            	t2: 'Englisch',
				t3: 'Sprachen',
				t4: 'Mein Text',
             }
}
```

Any idea?

**Comment by jamuhl** [comment]
https://www.google.com/search?q=cors+chrome+local+file&oq=cors+chrome+local+file&aqs=chrome..69i57j0l2.5513j1j7&sourceid=chrome&ie=UTF-8

**Comment by desmeit** [comment]
Thanks but I have the same issue, also open Chrome like this:

open /Applications/Google\ Chrome.app/ --args --disable-web-security

**Comment by jamuhl** [comment]
Still problem is there...you can't access JSON from filesystem in chrome without toggling security settings...

**Comment by desmeit** [comment]
hmm, now I tested it in Safari and the CORS Issue is gone away, but I get this:

`i18next::backendConnector: loading namespace translation for language de failed – "failed parsing languages/de.json to json"`

But you said here

https://github.com/i18next/i18next/issues/905

it is not necessary to provide the namespace .

**Comment by jamuhl** [comment]
failed parsing -> looks like not valid json -> https://jsonlint.com/ paste your content there

**Comment by desmeit** [comment]
That was it. Thanks

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
