### ISSUE TITLE
i18next::translator: missingKey

### ISSUE THREAD

**Issue by das-schaf** [i18next/i18next#1161]
I am facing missingKey errors since migrating from i18next 1.11.2 to 13.1.0. Resources provided by i18next-express-middleware are prefixed with language and namespace, e.g. {"de":{"translation":{"home":{"title":"Hallo Welt!"}}}} though the original resource file only consists of {"home":{"title":"Hallo Welt!"}}

I managed to reproduce this issue using the i18next-express-middleware basic example.

```
i18next
  .use(Backend)
  .use(i18nextMiddleware.LanguageDetector)
  .init({
    backend: {
      loadPath: __dirname + '/locales/{{lng}}/{{ns}}.json',
      addPath: __dirname + '/locales/{{lng}}/{{ns}}.missing.json'
    },
    fallbackLng: 'en',
    preload: ['en', 'de'],
    saveMissing: true
  });

app.use(i18nextMiddleware.handle(i18next));
app.get("/locales/resources.json", i18nextMiddleware.getResourcesHandler(i18next));
```

Version 1.11.2 was able to parse this kind of resource so i18n.t('home.title') lead to 'Hallo Welt'. The latest i18next version returns an error instead: "i18next::translator: missingKey de-DE translation home.title home.title" 

I have to prefix every i18next request like this: i18next.t('de.translation.home.title') to get "Hallo Welt".

i18next is initialized this way:

```
var i18nextOptions = {
  lng: 'de-DE',
  fallbackLng: 'de',
  backend: {
    loadPath: '/locales/resources.json?lng={{lng}}&ns={{ns}}'
  },
  debug: true
  };

i18next
.use(i18nextXHRBackend)
.init(i18nextOptions);
```

**Comment by jamuhl** [comment]
https://www.i18next.com/misc/migration-guide#v-10-x-x-to-v-11-0-0

removes the support for multiload (multiRead) in backends

**Comment by das-schaf** [comment]
Thx @jamuhl! That did the trick.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
