### ISSUE TITLE
Translate arrays

### ISSUE THREAD

**Issue by desmeit** [i18next/i18next#1162]
I have an array like this:

```
myApp.calendar({
...
	monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August' , 'September' , 'October', 'November', 'December'],
```

How is it possible to access and translate them? I think it should work with i18next.t('array', { returnObjects: true });
but how should I localize the calendar?

**Comment by jamuhl** [comment]
`i18next.t('array', { returnObjects: true });` - yes correct.

In detail it might be better to post development related questions like this on stackoverflow -> as this is more a i don't know how to do it - than i18next has an issue
