### ISSUE TITLE
React - Save missing keys doesn't work

### ISSUE THREAD

**Issue by jleeraert-conclusion** [i18next/i18next#1171]
I'm quite new to React and i18next, I've been researching all day if it's possible to load and save translations via the i18next-xhr-backend or the i18next-node-fs-backend. Using the XHR-backend I was able to load the translations from my public/locales folder, but it tries to do a POST to the same folder for saving missing keys which doesn't work. 

Is there something I can do to automatically let it save the missing keys somewhere in the client? We would rather avoid having the translations set up in the backend.

this is my i18n file:
```import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import { reactI18nextModule } from 'react-i18next';
import backend from 'i18next-xhr-backend';

i18n
	.use(LanguageDetector)
	.use(backend)
	.use(reactI18nextModule)
	.init({
		backend: {
			// for all available options read the backend's repository readme file
			loadPath: './locales/{{lng}}/{{ns}}.json',
			addPath: 'i18n/{{lng}}/{{ns}}'
		},
		fallbackLng: {
			'de-DE': ['en', 'nl'],
			'en-GB': ['en'],
			'en-US': ['en'],
			'en-NL': ['en', 'nl'],
			'nl-NL': ['nl', 'en'],
			'nl-BE': ['nl', 'en'],
			default: 'en'
		},
		saveMissing: true,
		nonExplicitWhitelist: true,
		debug: true,
		interpolation: {
			escapeValue: false // not needed for react as it escapes by default
		},
		ns: ['common', 'login'],
		// special options for react-i18next
		// learn more: https://react.i18next.com/components/i18next-instance
		react: {
			wait: true
		}
	});

i18n.changeLanguage('nl-NL');

export default i18n;
```

**Comment by jamuhl** [comment]
`public` folder gets served using the webpack dev server - you can use https://www.i18next.com/overview/configuration-options#missing-keys -> missingKeyHandler to do something inside the browser -> store missings into localStorage whatever -> but you can't write a file to your project folder

alternative use https://locize.com with the https://github.com/locize/i18next-locize-backend

win - win -> you get those missings working, incontext editing, ... and a translation management, plus support us ;)

**Comment by jleeraert-conclusion** [comment]
@jamuhl Okay thank you for your reply. I'll take it up with the PO and see if I can get them to try locize.
