### ISSUE TITLE
How can I use i18next json v2 when saving missing plurals?

### ISSUE THREAD

**Issue by ilearnf** [i18next/i18next#1174]
Hello!
I am trying to save missing plurals translation. In the `i18next.init` I've passed the `saveMissing: true` and `compatibilityJSON: "v2"` options. But when plural keys are saved I get the keys for the json v3. For example in russian language I have key_0, key_1, key_2, but expect to have key_1, key_2, key_5.
How can I make it work as expected? Or if it is not possible how can I convert plural keys from v3 to v2?

Thank you in advance!

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/src/Translator.js#L164 make sure plural is called with options count and you turned on saveMissingPlurals in initOptions

**Comment by ilearnf** [comment]
Thank you for the answer @jamuhl. I mean the other thing.
This is the example fiddle - [example](https://jsfiddle.net/e34fmxg8/2/).
In this example I have the plural keys saved - foo_0, foo_1, foo_2. But I want them to be foo_1, foo_2, foo_5 as it is in i18next JSON v2.

**Comment by jamuhl** [comment]
could you try with i18next@13.1.4

**Comment by ilearnf** [comment]
okay, thank you!

**Comment by tonix-tuft** [comment]
Sorry @jamuhl , what was the use case to update the JSON format in v3 to `key_0`, `key_1`, `key_2` instead of e.g. v1 format `key`, `key_plural_2`, `key_plural_5` (e.g. for the Russian language)?

Aren't `key`, `key_plural_2`, `key_plural_5` more intuitive than `key_0`, `key_1`, `key_2` for translators?

Thank you.

**Comment by jamuhl** [comment]
@tonix-tuft ...if we would change the suffixes in future we would use "many, few, other" like in ICU

**Comment by tonix-tuft** [comment]
OK, still I don't get why the keys now are index-based in v3 (`key_0`, `key_1`, etc.).

It's just my curiosity.

**Comment by jamuhl** [comment]
before that change it was based on a test number -> the index is inline with what gettext basically does in it's .mo / .po files
