### ISSUE TITLE
How to import i18next? (NodeJS, TypeScript, ES6)

### ISSUE THREAD

**Issue by mehmetnyarar** [i18next/i18next#1177]
Hi,

How can i use `i18next` in a Node/TypeScript project? Below code fails:

```
// Express middleware
import * as i18nextMiddleware from 'i18next-express-middleware'

// i18next
import { default as i18next } from 'i18next' // i18next is undefined
// import i18next from 'i18next' // Suggests 'default' which is undefined too
// import { /* Nothing here */ } from 'i18next'

const i18nextOptions: i18next.InitOptions = {
  preload: ['ru', 'kz', 'en']
}
const languageDetector = new i18nextMiddleware.LanguageDetector(null, {
  order: ['header'],
  caches: false
}, {
  fallbackLng: 'ru'
})
i18next.use(languageDetector).init(i18nextOptions) // i18next is undefined
app.use(i18nextMiddleware.handle(i18next))
```

`const i18next = require('i18next')` works but I don't get typings.

**Comment by jamuhl** [comment]
`import i18next from 'i18next';` ?!?

**Comment by adrai** [comment]
Can you create a test repository with your setup that reproduces it?

**Comment by mehmetnyarar** [comment]
@adrai Yep, [here it is](https://github.com/mehmetnyarar/i18next-node-ts).

**Comment by adrai** [comment]
never used ts-node, but perhaps it’s because of this? https://github.com/TypeStrong/ts-node/issues/505#issuecomment-356774721

**Comment by adrai** [comment]
or: https://github.com/TypeStrong/ts-node/issues/311#issuecomment-295010761

**Comment by ilearnf** [comment]
@mehmetnyarar, hi! try `import * from "i18next"`. In my case it works but my tslint is arguing about it.

**Comment by DaNautilus** [comment]
@mehmetnyarar, as a workaround you can try this:

```typescript
import * as i18next from 'i18next'

i18next.default
  .use(languageDetector)
...
```

**Comment by DaNautilus** [comment]
@mehmetnyarar, you can try to import methods separately like this

```typescript
import { use, init } from 'i18next';

use(languageDetector);
init({
...
});
...
```

**Comment by mehmetnyarar** [comment]
thank you all for the replies.

@adrai i don't expect `ts-node` to compile `i18next`, so [TypeStrong/ts-node#505 (comment)](https://github.com/TypeStrong/ts-node/issues/505#issuecomment-356774721) is not the case.

Following through [TypeStrong/ts-node#311 (comment)](https://github.com/TypeStrong/ts-node/issues/311#issuecomment-295010761), I removed `allowSynthenticModules` from `tsconfig.json` and imported as suggested `import * as x from`. I can say, removing the option didn't make any difference, and when i import like `import * as i18next from 'i18next'`, VSC suggests to use `i18next.default`and it's also undefined.

[#1128](https://github.com/i18next/i18next/issues/1128) is absolutely related, but no solution there as well.

@ilearnf, is it possible to import like that? as far as i know, imports can be done in one of 3 ways: `import sth from 'sth'` or `import * as sth from 'sth'` or `import { sth } from sth`.

@DaNautilus there are no exported members in `i18next`. To be exact:

```
`[ts] Module '".../node_modules/i18next"' has no exported member 'use'. [2305]`
`[ts] Module '".../node_modules/i18next"' has no exported member 'init'. [2305]`
```

Looking at the source code:

1. In `i18next/index.js`, it exports `default` from `commonjs`:

```javascript
module.exports = require('./dist/commonjs/index.js').default;
```

2. In `index.d.ts`, it exports `i18next` where ` i18next` is declared as a namespace before that.

```javascript
declare namespace i18next {
  interface i18n extends WithT {
    // ..
  }
}

declare const i18next: i18next.i18n
export default i18next
```

I'm not sure whether having same name for the namespace and exported member affects things badly but I think the 'undefined' problem comes from `declare const i18next: i18next.i18n`.

**Comment by jamuhl** [comment]
the `module.exports = require('./dist/commonjs/index.js').default;` is for node usage not supporting importing default as main import

try `import * as i18next from 'i18next/dist/commonjs/';`

**Comment by mehmetnyarar** [comment]
@jamuhl it works yes, but i don't get typings. I guess it's same as doing `require`.

**Comment by rosskevin** [comment]
@mehmetnyarar you should probably be using `esmoduleinterop`.  I PR'd a fix for you.  Check the diff to see what I did to make it work.

https://github.com/mehmetnyarar/i18next-node-ts/pull/1

**Comment by andrewbranch** [comment]
`esModuleInterop` does work around this issue, but there are people with large projects that can't just flip on that compiler option. Correct typings would yield correct consumption of the library with _either_ value for `esModuleInterop`. As it stands, it's completely broken for anyone not using that compiler option.

**Comment by rosskevin** [comment]
@andrewbranch you can choose not to use `esModuleInterop`, just adjust your imports accordingly.  If you think it is broken, you need to create a repo with a reproduction and file a new issue.

**Comment by andrewbranch** [comment]
@rosskevin Hmm, I think what I was seeing is actually an issue with ts-jest and default imports not playing well together. My bad!

**Comment by polRk** [comment]
```
i18next_1.default.init({
                  ^

TypeError: Cannot read property 'init' of undefined
```

tsconfig
```

{
  "compilerOptions": {
    "lib": [
      "esnext",
      "dom"
    ],
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017"
  },
  "compileOnSave": true,
  "include": [
    "src"
  ]
}

```
I can not use esModuleInterop, because many other libraries fall back

**Comment by polRk** [comment]
But this is work
```
// import i18next from 'i18next'
import * as i18next from 'i18next'

import { enLocales } from './locales/en'
import { ruLocales } from './locales/ru'

// @ts-ignore
i18next.init({
  debug: true,
  resources: { en: enLocales, ru: ruLocales },
})

```

**Comment by polRk** [comment]
You have very bad typings

**Comment by jamuhl** [comment]
@polRk if there is something wrong or bad - you're free to provide a PR containing improvements incl. tests (cc @rosskevin )

**Comment by sellalone** [comment]
try this

````
import { default as i18n } from 'i18next';
const i18n = require('i18next').default;
````

**Comment by rosskevin** [comment]
@sellalone that is unnecessary.

Without esModuleInterop:
`import * as i18next from 'i18next'`

With esModuleInterop:
`import i18next from 'i18next'`

I am locking this so this is the last comment and avoids future confusion.
