### ISSUE TITLE
Genitive case plurals

### ISSUE THREAD

**Issue by ilearnf** [i18next/i18next#1178]
Hi!
In some languages there are genitive case plurals which form is slightly different from the nominative case plurals. For example Russian language and the phrase "the bank of two rivers".  In russian it will be translated as "берег 2 рек" and "2 рек" would be here the genitive case of the plural form of the word "река" ("river").  However nominative case - "2 rivers" would be tranlsated as "2 реки". The difference here  is "2 реки" (nominative case) -> "2 рек" (genitive case).
This situation also is described here - [on the unicode.org](http://cldr.unicode.org/index/cldr-spec/plural-rules) in the section "Multiple nouns".

How can this be handled in i18next?
Thank you in advance!

**Comment by jamuhl** [comment]
combine context with plural

**Comment by jamuhl** [comment]
https://www.i18next.com/translation-function/context#combining-with-plurals

**Comment by ilearnf** [comment]
It seems to be not that simple. 
Fro example:
count === 1 -> “берег 1 реки» («the bank of 1 river”)
count === 2  -> “берег 2 рек» («the bank of 2 rivers”)
But also
count === 101 -> “берег 101 реки» («the bank of 101 rivers”). 
The last case should be the same plural as in the first one. But as far I understand this cannot be simply implemented with combining context as plurals. 

Correct me if I’m wrong. If everything is right what are the options?

**Comment by ilearnf** [comment]
Thank you for the answer @jamuhl.
but how can I tell i18next what key should it use for each {{count}}?
the rule for this case is - 
`if (count % 10 === 1 && count % 100 !== 11) return key_genetive_1`
`else return key_genetive_2`.

key_genetive_1 = "реки", key_genetive_2 = "рек". there are no other keys for this keys.
could this logic be implemented?

**Comment by jamuhl** [comment]
https://www.i18next.com/translation-function/plurals#how-to-find-the-correct-plural-suffix
