### ISSUE TITLE
Decode html special characters from JSON

### ISSUE THREAD

**Issue by desmeit** [i18next/i18next#1181]
I have a lot of html special characters in my JSON file, for example:

```
{
	"text": {
		"t1": "Max &amp; Moritz",
        }
}
```

How can I decode it for using in html? Is there an option or something?

Thanks

**Comment by jamuhl** [comment]
i18next does not encode the values it returns by calling `t` - only case is when interpolating values (there you can use option escape: false https://www.i18next.com/translation-function/interpolation#unescape)

**Comment by jamuhl** [comment]
where do you run into issues with this?

**Comment by desmeit** [comment]
I work with a translation tool (MEMSOURCE). And when I download the translated Json File I get instead of "&" the special character "&amp;". The problem is that it will be displayed incorrectly in the app.

**Comment by jamuhl** [comment]
So the issue is with memsource changing your content. With https://locize.com this would not happen and you would support us ;) (works perfect for i18next - incl. saveMissing, CDN, incontext editing)

**Comment by desmeit** [comment]
Looks nice. Unfortunately, I didn't know it before. Now everything is already translated.😬 But I will have a look at it.

**Comment by jamuhl** [comment]
Cool...sadly there is not much i can do from i18next side -> there is no convert those changes back. You might add a custom post processor reverting those changes -> https://www.i18next.com/misc/creating-own-plugins#post-processor

**Comment by desmeit** [comment]
Thank you.

**Comment by desmeit** [comment]
Regarding locize, I have one question: Ist it also possible to translate html files and Word files with it?

**Comment by jamuhl** [comment]
@desmeit locize acts as a translation management tool for websites and applications (Depending on some sort of catalog format of translations: JSON, XLIFF, PO,...). So translating sales, marketing, ... documentations in html, word, pdf is not in the focus. We just started work on another platform build for that case - but yet not ready for primetime...
