### ISSUE TITLE
Mocking the t function currently yields error

### ISSUE THREAD

**Issue by rosskevin** [i18next/i18next#1185]
extracted from #1180 
/cc @nikolay-borzov 

```ts
import i18next from 'i18next';

/**
 * Exercises in mocking
 */
const mockWithT: i18next.WithT = {
  t: key => key as string,
};
```

```ts
test/typescript/mock.test.ts:7:13 - error TS2322: Type 'string' is not assignable to type 'TResult'.

7   t: key => key as string,
              ~~~~~~~~~~~~~

  index.d.ts:472:5
    472     t<
            ~~
    473       TResult extends string | object | Array<string | object> = string,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ...
    478       options?: TOptions<TValues>,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    479     ): TResult;
        ~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.
```

The untyped workaround is:

```ts
const mockWithT: i18next.WithT = {
  t: ((key: string) => key) as any,
};
```

I can't spend more time on this.  Anyone with better solutions can PR them to `test/typescript/mock.test.ts`

**Comment by rosskevin** [comment]
I'm not sure this is an issue that needs more attention as it is just a mock.  It is nice to have but certainly not required.  Very strange that I could not get it to work in a very simple way, but I made a bunch of improvements along the way to attempt it.  

Thoughts/PRs are welcome - I've spent an entire morning trying to solve it and ended up with a big refactoring PR.

**Comment by VincentLanglet** [comment]
@rosskevin Is it done, now ?

**Comment by rosskevin** [comment]
It still used the `any` work around. Not sure about an easier path.

**Comment by rosskevin** [comment]
I'm going to close this out, it may be related to #1194.  I'd like to see it improved, but as I noted there, since types are working for 99.9999% of usage, there isn't much benefit to leaving this lingering.

With that said, if anyone wants to PR an improvement, please do so!
