### ISSUE TITLE
allow 'TemplateStringsArray' as parameter of t function in type declaration

### ISSUE THREAD

**Issue by noru** [i18next/i18next#1189]
I originally create this issue on `react-i18next` side, but I found it makes more sense ( and easier ) to add type support here. Would you please consider it?

https://github.com/i18next/react-i18next/issues/701

> Is your feature request related to a problem? Please describe.
> I'd like to reduce a pair of parenthesis by using string literal:
> 
> t\`some_key\` // instead of t('some_key')
> which is 98% of the case in my code base. It doesn't effect anything, only need the type support.
> 
> I can raise a PR if it is acceptable.
> 
> Describe the solution you'd like
> simply add types to the declaration file

```javascript
// index.d.ts...
// NOTE: somewhat duplicate of WithT.t but cannot use interface - not sure why I can't find a workable reuse pattern
  type TFunction = <
    TResult extends string| object | Array<string | object> | undefined = string,
    TKeys extends string {| TemplateStringsArray} = string, //  simply add the quoted thingy, the same with the 't' in 'WithT'
    TValues extends object = object
  >(
    key: TKeys | TKeys[],
    options?: TOptions<TValues>,
  ) => TResult;
```

**Comment by jamuhl** [comment]
Please provide a PR with this and close https://github.com/i18next/react-i18next/pull/705 if not needed any longer

**Comment by jamuhl** [comment]
@noru you still got plans for a PR - or should we close this?

**Comment by drewxiuxiuxiu** [comment]
Im sorry it's chinese new year recently. I'll pr it asap.

**Comment by noru** [comment]
#1199

**Comment by jamuhl** [comment]
pubished in i18next@15.0.3
