### ISSUE TITLE
Redux integrate

### ISSUE THREAD

**Issue by sm2017** [i18next/i18next#1190]
How can I change locate when id `dispatch({type:"CHANGE_LOCALE",locale:"en-US"})` ? 

I know that `i18next.changeLanguage(lng)`  can change locale , but how to trigger render again?

**Comment by jamuhl** [comment]
do you use react-i18next? if so using the HOC or render prop or hook should be all needed.

else you will need to create some root component listening to: https://www.i18next.com/overview/api#onlanguagechanged and trigger a rerender when getting that event.

**Comment by jamuhl** [comment]
Can you please make a sample where it is not working...eg. on codesandbox (this works out of the box)

**Comment by sm2017** [comment]
@jamuhl I found my problem , Now react-i18next works well in my project
Thanks a lot

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
