### ISSUE TITLE
joinArrays empty string bug

### ISSUE THREAD

**Issue by niksajanjic** [i18next/i18next#1191]
If you want to join your strings by passing an empty string `{ joinArrays: '' }` that will not work and the result will be `undefined`.

https://codepen.io/anon/pen/XOpPjB

What is wrong with the code is the fact that `joinArrays` variable is a part of multiple if/else conditions which will always be false for an empty string and that is what causes this bug.

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/src/Translator.js#L143 should be an easy fix to check for `joinArrays  !== undefined`

If you like provide a PR to speed this up.

**Comment by jamuhl** [comment]
Can you try i18next@14.1.1

**Comment by niksajanjic** [comment]
I just tried it on this same Codepen, passing new version and it works. I'll close the issue. Thanks for fixing it.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
