### ISSUE TITLE
i18next internal logging needs to be suppressed. 

### ISSUE THREAD

**Issue by tusharcoepit** [i18next/i18next#1192]
i18next emits following logging in console log. There should be a way to suppress these logs.

i18next: languageChanged en-US
i18next: initialized {debug: true, initImmediate: true, ns: Array(1), defaultNS: "translations", fallbackLng: Array(1), …}

**Comment by jamuhl** [comment]
-> set init option debug: false (instead of true) 🧐

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
