### ISSUE TITLE
Extract given namespace

### ISSUE THREAD

**Issue by teawithfruit** [i18next/i18next#1193]
Hello, and thanks for this great library!
I didn’t found a way to get the current namespace or a way to extract the namespace of a key that is given to the t function. Is it possible to do it in some way?

What do you think about the possibility of a callback or a promise for the t function? Or maybe about a ```getNamespace(key)``` function?

Thanks

**Comment by teawithfruit** [comment]
Yes sure.
I have different namespaces which represent different areas. Not every key is set in every namespace, but in the default namespace. That means, that the default namespace should be used, if a key is not provided in a specific namespace.
Specific namespaces are loaded over the ```missingKey``` event with ```loadNamespace```.

My idea is to check if a given key is set in a specific namespace. If the namespace is not loaded, it should be.
That works.

The problem I have right now is, that the ```t``` function is faster than the namespace loader. In fact that means, that I always get the translation after a second try.
So I want to write a function which first checks if the namespace is provided. If not, than it should be loaded. If the key is provided in the new loaded namespace than it should be returned. If not, the default namespace should be used.
At this position I can’t check if the current namespace is the default namespace or a specific one which will be loaded. This is why I ask for something like ```getNamespace``` and a promisified ```t``` function.

**Comment by jamuhl** [comment]
uf...were should i start...

t function can't be async and should not be...

you need to control loading namespaces -> that function provides a callback or promise.

rendering should be delayed until translations are loaded. Easy doable ... 

Means in short - when user navigates to an area - load that namespace and delay rendering until loaded

**Comment by teawithfruit** [comment]
Ok, I understand, that the t function can't be async.
But I need a way to get the current namespace of a requested key. Right noe I've done it this way.
```js
async exists(key) {
  let that = this

  let exists = that.i18n.exists(key)
  if(exists == false) {
    const namespace = key.match(/^[^:]+/gm)[0]
    await that.load(namespace)

    exists = that.i18n.exists(key)
  }

  return exists
}
```

**Comment by jamuhl** [comment]
if it works - it works. Still for me that approach is not the best - checking on every key if that namespace is loaded adds extra processor time needed - i still prefer a load based on navigation (loading namespaces when going to an area - not on accessing a key)
