### ISSUE TITLE
The current approach to a generic "t" function is wrong...

### ISSUE THREAD

**Issue by Jessidhia** [i18next/i18next#1194]
...but doing it right is going to be really hard.

Probably related to #1185.

The status quo does happen to work for most of the current use cases, but the way the `t` function uses generics right now is nearly meaningless.

First, the `TKeys` generic argument is useless. It is only used in a single parameter and does no work other than forcing the compiler to instantiate a type. The same goes for `TValues` -- it just causes the compiler to infer a more specific type than `object` for the argument but it still means no more than `object` because it is not actually used to relate any types.

As-is, unless you explicitly (and redundantly) pass in the generic arguments, these generics have no meaning. They are effectively just a more memory-heavy version of only accepting `string | string[]`, or only accepting `object & TOptionsBase`.

`TResult`, on the other hand, is effectively a hack to write an `as` cast. Again, it is not related to any of the input types, so you can give anything you want as `TResult`. It is slightly better than `any` in that, if there is a contextual type that is 100% compatible with the `extends`, the contextual type will be used instead, but if there is a contextual type that is not, the generic widens completely. This small sample is enough to demonstrate the issue and no, the solution is not to add `| null` to the `extends`:

```ts
// no contextual type, uses generic default
const test1 = t('foo')
// with contextual types
const test2: string = t('foo')
const test3: string | null = t('foo') // errors
```

---

The correct solution is to have an `interface` mapping keys to possible values that belongs to the `i18next` instance itself. Expressing this in `react-i18next` is more complicated but is doable (something similar to how `styled-components` supports themes).

First, we're going to need something like:

```ts
interface AvailableTranslations {
  'foo': {
    options: { bar: string }
    return: string
  }
  'bar.baz': {
    options: {}
    return: object[]
  }
}
```

This `AvailableTranslations` (which is an `interface` so it is augmentable) would be a generic argument to `createInstance` and could default to `Record<string, { options?: Record<string, any>; return: string | string[] | ... }>` if not supplied. A more advanced hack could be used to implement something like `styled-component`'s `DefaultTheme` -- an `interface` that, if augmented by the user, takes effect instead of the "actual default".

The `t` function would not really be a "free TFunction" but one that receives that `AvailableTranslations` interface as a generic interface (say, `TData` or whatever). This _then_ could be used to make an actual type-safe `t` function:

```ts
type TFunction<TData extends Record<string ...> = Record<string, ...>> = {
  // unfortunately typescript doesn't allow conditionally-optional arguments
  // hack it with an overload that returns never if the options are required
  <TKey extends keyof TData>(
    key: TKey | TKey[]
  ): undefined extends TData[TKey]['options']
    ? TData[TKey]['return']
    : never
  <TKey extends keyof TData>(
    key: TKey | TKey[],
    options: TData[TKey]['options'] extends undefined
      ? TOptionsBase
      : Exclude<TData[TKey]['options'], undefined> & TOptionsBase,
  ): TData[TKey]['return']
}
```

This would allow for codegen to autogenerate interfaces declaring the translations you support, with their required values, and then the `key` could actually be used to infer the valid `options` and `return` types because its generic is actually used to relate the types of arguments, or the type of the return.

**Comment by rosskevin** [comment]
We are open to PRs, a change like this should probably target `next` since we are quickly approaching it.

Generics were added to support another user's use case. Most users won't notice them unless casting the result type to a non-string. 

Please PR and ping me for a review.

**Comment by rosskevin** [comment]
I haven't heard back from @Jessidhia about submitting a PR.  I'm going to close this as `good enough` for 99.9999% of the users.  

I would like to see it be absolutely and esoterically correct, but there may not be a benefit to users given the effort.  @Jessidhia (or anyone else) if you are interesting in submitting a PR in this direction, please let me know and we'll reopen this to track the improvement.
