### ISSUE TITLE
i18next Inits without a t function

### ISSUE THREAD

**Issue by carlosafw** [i18next/i18next#1195]
I'm probably doing something wrong but couldn't find anything similar googling.

i18next initiates without any errors but without a t function.

`
import store from './store/store'
import { getUserLanguage } from './store/appstate/reducer'
import XHR from 'i18next-xhr-backend'
import i18next from "i18next"

class Translation {

    i18next = i18next;

    constructor() {
        this._initialized = this._initialize();
    }

    createTransl(userLanguage) {
        return new Promise(resolve => {
            this.i18next
                .use(XHR)
                .init({
                    lng: 'br',
                    backend: {
                        loadPath: `/static/lang/${userLanguage}.json`,
                    }
                }, () => {resolve()});
        })
    }

    async _initialize() {
        const userLanguage = getUserLanguage(store.getState());
        await this.createTransl(userLanguage);
    }

    async translate(content)  {
        await this._initialized;
        return this.i18next.t(content);
    }

}

export default Translation;
`

**Comment by jamuhl** [comment]
almost can't be -> `t` already exists on i18next even before calling init: https://github.com/i18next/i18next/blob/master/src/i18next.js#L276

**Comment by carlosafw** [comment]
[Check it out](https://imgur.com/a/XGhkKAx)

**Comment by jamuhl** [comment]
found it on the prototyp?

**Comment by carlosafw** [comment]
Yes.
