### ISSUE TITLE
Nesting Question

### ISSUE THREAD

**Issue by hishayness** [i18next/i18next#1197]
Hello!

Is it possible for the translate function, or perhaps another function be exposed for processing nesting values?
{
  "some_key1": "Total: {{item}}",
  "some_key2": "${{price}}"
}

So we have an util that produces many different results. One possible result is "$t(common:some_key2, { 'price': 100 })"

That is then fed to a translate call like below
t('common:some_key1', { item: "$t(common:some_key2, { 'price': '100' })" })
// -> "Total: $100"

Sometimes we would like to just call the util and display the resulting translation. So would something like this be possible?

someFunction("$t(common:some_key2, { 'price': '100' })")
// -> "$100"

**Comment by jamuhl** [comment]
call `t('common:some_key2', { 'price': '100' })`

**Comment by jamuhl** [comment]
eg. use a regex to get `"common:some_key2"` and `"{ 'price': '100' }"` from your string...then parse the second to json and call t function as shown above

**Comment by hishayness** [comment]
Thanks for the quick response!

I was hoping to accomplish it without having to run some additional processing since the i18next lib already does this on nested fields. 

Nevertheless, I decided to pass in `t` reference into the utility method as there were a couple of results that needed translations. 

Great work on i18next!

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
