### ISSUE TITLE
TypeScript: can't pass default value to "t" as second argument

### ISSUE THREAD

**Issue by maksis** [i18next/i18next#1198]
Using `t('key', 'Default value')` (as documented in https://www.i18next.com/translation-function/essentials#passing-a-default-value) currently causes the following error: 

`Argument of type '"Default value"' is not assignable to parameter of type 'TOptions<object> | undefined'.`

I'm using version 14.1.1

**Comment by rosskevin** [comment]
@jamuhl are the docs wrong?  I see `defaultValue` as a key in the options, so ts would allow:

```
i18next.t('key', {defaultValue: 'default value to show'});
```

but not:
```
i18next.t('key', 'default value to show');
```

**Comment by rosskevin** [comment]
I don't spot the case where the string defaultValue as a second arg is allowed/tested in https://github.com/i18next/i18next/blob/master/test/translator/translator.translate.defaultValue.spec.js

**Comment by jamuhl** [comment]
both is allowed...having second function argument a string it's used as defaultValue using https://github.com/i18next/i18next/blob/master/src/Translator.js#L66

which defaults to https://github.com/i18next/i18next/blob/master/src/defaults.js#L39

**Comment by jamuhl** [comment]
new tests do not yet cover all cases - that's the reason why we run the old compatibility tests...
