### ISSUE TITLE
IE11 - error with opened debugging console and page reload

### ISSUE THREAD

**Issue by pospichalales** [i18next/i18next#1200]
I am getting Unable to get property * of undefined or null reference when I have opened console in IE11 and refresh the page.
The error is from EventEmitter.js `_this.observers[event] = _this.observers[event] || [];`

How to reproduce:
1/ Open www.ersworkout.cz in Internet Explorer 11
2/ Open debugging console (F12)
3/ Reload the page
4/ You should see Unable to get property * of undefined or null reference

**Comment by jamuhl** [comment]
Is this with version 15 only or already an issue with v14?!?? No IE (mac user) so will be not easy to reproduce...

**Comment by pospichalales** [comment]
I have 15.0.1. Previously I had 10.6.0 and there was no such issue. I may try it with v14.

**Comment by jamuhl** [comment]
could you check again with i18next@15.0.2

**Comment by pospichalales** [comment]
Just checked, but it did not helped. Getting error everytime with opened console. Without opened console, the page loads without issue.

**Comment by pospichalales** [comment]
Sorry! It is working well now, I had turned on document compatibility mode - IE10. With default setting to IE11, it is good.

**Comment by jamuhl** [comment]
hm...the only thing needed to get it work on v15.0.2 is the Promise shim:

`<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"></script>`

https://jsfiddle.net/p4ekqdtm/3/

**Comment by jamuhl** [comment]
Thank you for reporting back...just saw your latest reply now...hadn't refreshed the browser.

**Comment by ilanbm** [comment]
> Sorry! It is working well now, I had turned on document compatibility mode - IE10. With default setting to IE11, it is good.

But it still doesn't work on <=IE10

is i18next suppose to support IE10?

**Comment by jamuhl** [comment]
With polyfilling it should / might work...never tested to deep...as you know...it's IE

**Comment by jamuhl** [comment]
but will accept PR making things better!

**Comment by ilanbm** [comment]
> With polyfilling it should / might work...never tested to deep...as you know...it's IE

These are the polyfils I use:
default,matchMedia,String.prototype.repeat,document.querySelector,Element.prototype.append,Promise,Set,Map,Array.prototype.find,Array.prototype.forEach,Symbol,Symbol.iterator,Symbol.replace,RegExp.prototype.flags,Element.prototype.closest,Element.prototype.matches,fetch,Object.setPrototypeOf,Object.assign,Array.from

Is there any polyfil missing that can solve this error?

**Comment by jamuhl** [comment]
like said before...this is OSS - i do not care for IE - but open for contribution
