### ISSUE TITLE
Why not use CLDR plural categories?

### ISSUE THREAD

**Issue by Shepard** [i18next/i18next#1202]
When writing translation calls with counts, i18next appends a number suffix for the chosen plural category to the translation key to pick.

Why not use the category names standardised by CLDR (http://cldr.unicode.org/index/cldr-spec/plural-rules)? I've seen this used in various places, I've used it like this in the past and I think it greatly improves the readability of the data. And, well, it's more or less a standard.

Was this done to reduce the size of the translation resource files being sent to the client? I mean, the categories aren't that much longer than the numbers and in my experience you don't end up with that many labels needing plural forms in an interface anyway to be relevant.

**Comment by jamuhl** [comment]
In time of writing it was taken from GNU gettext and reflected the index - so it was simple to use in https://github.com/i18next/i18next-gettext-converter

So it's a "historical thing" - i already thought a few times about changing to the `zero, one, few, many, other` names - but still feeling unsure about it (benefits vs. migration efforts).

Always got an eye on https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/PluralRules getting full support there would mean we could change the plural rules and just use the browser ones.

**Comment by Shepard** [comment]
Sure, but that could be a long wait. :-) Especially if you want to keep supporting legacy browsers. A polyfill is probably the way to go. I've been using https://github.com/eemeli/make-plural in the past but a proper polyfill would be nice (as long as you can set it up in a way that only the rules in the languages you need are transferred to the browser).

If you do switch to that in the future the migration efforts would still be a problem though, right?
I wonder if a configuration option could be a way to go. I'm considering using i18next for a new project and so I don't have any translation resources that need migrating yet and could just start with such an option turned on. But I completely understand if you don't want to add more options for such things that just add code and complexity. As a workaround I could just add a transformation step for my translation resources that maps the category names to the gettext index.

**Comment by jamuhl** [comment]
make-plural is an option i like to avoid...compared to our plural-rules code it's very heavy creating function for every language. An option would be creating an additional mapping in our plural resolver containing those new suffixes...

we currently support v1, v2, v3 and a non simplified version of v3 using suffixes for eg. en-US too (_0, _1)

So having a v4:
- taking `zero, one, many,...` from https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L6 an additional array on every set
- returning it here with v4 option set: https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L143

Sametime we might think about changing the separator from `_` to `.` so we could have:

```js
'key': {
   'one': 'an item',
   'other': '{{count}} items'
}
```

instead of: 

```js
'key_one': 'an item',
'key_other': '{{count}} items',
```

What do you think?

**Comment by Shepard** [comment]
Well I don't really know the code yet but it looks good. :-)
And I do like the suggestion of splitting off the plural forms into a sub-object literal by switching to a `.` syntax.
How would I tell it to use this v4?

**Comment by jamuhl** [comment]
changing like https://www.i18next.com/misc/json-format#i-18-next-json-v2

```js
i18next.init({
  compatibilityJSON: 'v4'
});
```

**Comment by Shepard** [comment]
Looks good! 👍

**Comment by jamuhl** [comment]
If you like you might create a PR...else keeping this open until i got the time for it.

**Comment by jamuhl** [comment]
The more I think about this - the more uncertain I get. How big is the benefit of this change is. CLDR plural suffix tell not more as plain numbers - it's a construct.

If we do this change we on the same go could change it to ICU - but on the other hand - not a fan of breaking things for the thousands of apps out there - so it's what we already started with things like i18next-icu, i18next-fluent, ... choose what ever i18n format you like with i18next.

In a next step we could make this interoperability with other i18n frameworks more prominent - or wait for a i18n format to become the final standard (won't ever happen i guess)

**Comment by Shepard** [comment]
It's fair enough. I can see that it would increase the complexity of the code and potentially introduce interoperability issues. And there's workarounds: if I want to use the category labels in my translation files, I just have to add a conversion step that changes them to the numbers before handing it over to i18next.

So I can see why you wouldn't want to accept any changes here. :-)
Feel free to close this ticket.

**Comment by srl295** [comment]
`Intl.PluralRules` is supported in Ecma402 and supports the CLDR categories https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules

**Comment by jamuhl** [comment]
@srl295 thanks for sharing

**Comment by srl295** [comment]
@jamuhl would you consider replacing the current code with `Intl.PluralRuies()` ? Then that code wouldn't need to be updated in i18next, for example:

```js
new Intl.PluralRules("cy").select(6) // == "many"
```

**Comment by jamuhl** [comment]
@srl295 https://github.com/i18next/i18next/issues/1202#issuecomment-477013818 basically that did not change...the change would be breaking, for older (IE I look at you) browsers you would have to polyfill the Intl API.

Currently, there are talks around extending the Intl API with support for an i18n message format...might be ICU or fluent...as soon we got more details about the direction this is going we will start fully supporting the Intl API (message parsing, formatting, plurals, ...) in a new major release.

**Comment by srl295** [comment]
@jamuhl please take a look at http://blog.unicode.org/2020/01/new-unicode-working-group-message.html if you haven't already… thanks!

**Comment by jamuhl** [comment]
@srl295 thanks for pointing out...I'm already member there and already stated there that I'm open to direct i18next to the syntax / outcome of that work (includes the cldr plurals usage)...honestly I'm waiting very long for this move - hopefully that will make i18n a lot less painful...👍
