### ISSUE TITLE
array or object translation not added by addResources()

### ISSUE THREAD

**Issue by jckh1234** [i18next/i18next#1203]
I found the addResources() method cannot add array/object translation, but addResource() works

Using version 14.1.1

    const resources = {
        en: {
          translation: {
            "arrayKey": [1,2,3]
          }
        }
    }

    i18n
      .use(LanguageDetector)
      .init({
        resources,
        fallbackLng: 'en',
        debug: true,
      });

    console.log(i18n.t('arrayKey', {returnObjects:true}));
    //output [1,2,3]

    i18n.addResources('en', 'someNamespace', { arrayKey: ['a', 'b', 'c']})
    console.log(i18n.t('someNamespace:arrayKey', {returnObjects:true}));
    //missingKey error

    i18n.addResource('en', 'anotherNamespace', { arrayKey: ['x', 'y', 'z']})
    console.log(i18n.t('anotherNamespace:arrayKey', {returnObjects:true}));
    //work, output ['x', 'y', 'z']

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/src/ResourceStore.js#L66

**Comment by jamuhl** [comment]
could you try with i18next@15.0.3

**Comment by jckh1234** [comment]
It works with i18next@15.0.3. Thanks

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
