### ISSUE TITLE
Multiple keys on same value

### ISSUE THREAD

**Issue by davidwandar** [i18next/i18next#1207]
Is it possible to add/define keys that share a value. I would like to avoid this:
`{
  "codaA" : "a value",
  "codaB" : "a value",
  "codaC" : "a value",
  "codaD" : "another value",
  "codaE" : "another  value",
  "codaF" : another  value",
}`

is something like 
`{
  ["codaA","codaB", "codaC"] : "a value",
  ["codaD", "codaE", "codaF"] : "another  value",
}`
possible in some way?

**Comment by jamuhl** [comment]
it's still javascript / JSON you can't access `MyObject["["codaA","codaB", "codaC"]"]`-> the thing you can do is https://www.i18next.com/translation-function/nesting

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
