### ISSUE TITLE
Browser support and required shims

### ISSUE THREAD

**Issue by ThomasVandenbon** [i18next/i18next#1210]
I've just upgraded from i18next version 10.4.1 to the latest version, following the [migration-guide](https://www.i18next.com/misc/migration-guide), as I couldn't find a full changelog.

After upgrading I launched my phantomjs tests and came to the conclusion that I require a shim for Promise. I can add a shim for Promise, but I also want to be sure I don't need any other shims (I need to support IE10).

I looked through the documentation for an indication of browser support or required shims, but I couldn't find anything.

Is this information not available?

**Comment by jamuhl** [comment]
Promise is the only thing added that might be not IE friendly
