### ISSUE TITLE
"/translations/de/common.json" outside of src folder 

### ISSUE THREAD

**Issue by prwinkmr** [i18next/i18next#1214]
Dear Jamuhl,

I want to keep my .json file("/translations/de/common.json") outside of src folder say in public folder, which react does not allow normally. Please suggest me some solution.  If possible please put an example.

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/tree/master/example/react/public we do the same on our sample...why should react not allow that?

Do you try `import` from there or loading via `i18next-xhr-backend`?

**Comment by prwinkmr** [comment]
I was trying to load from loadPath.

**Comment by jamuhl** [comment]
public is `/` no need to prefix /public/..

**Comment by prwinkmr** [comment]
Yes that worked.
Thank you

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
