### ISSUE TITLE
Question about translation file format

### ISSUE THREAD

**Issue by BThibaut** [i18next/i18next#1215]
Hello !

I just discovered i18next and I'd like very much to use it on my apps, but my TMS export translation into a XLIFF file per language. Unfortunately I didn’t see any tool to parse an XLIFF file to i18next JSON format.

Do you have any solution to that ?
Maybe I could create a new tool for i18next to do that ?

**Comment by jamuhl** [comment]
solution...use https://locize.com that way you get a better TMS whit optimal i18next support (and also support us).

beside that -> xliff is a format not easy to consume in client side script (JSON is supported in javascript while xliff is a custom xml format -> still you can use our: https://github.com/locize/xliff -> still unfair other TMS get the cash - and we the work 🥺)

**Comment by BThibaut** [comment]
Thank you for your answer. I'll take a look at Locize.
