### ISSUE TITLE
Can I obtain a translated JSON array?

### ISSUE THREAD

**Issue by prwinkmr** [i18next/i18next#1216]
Dear Jamuhl,

I am giving my requirement below and the problem area is in bold letter. Is this possible to translate this with i18next.t(...)

//I am loading this with the help of loadPath
{student : [
    			{'name':'rahul',
				 'roll':30}, 
				{'name':'Praween',
				 'roll':10},
				{'name':'Umesh',
				 'roll':20},
				{'name':'Nitin',
				 'roll':50},
				{'name':'Pawan',
				 'roll':32},
				{'name':'Priyanka',
				 'roll':3},
				{'name':'Radha',
				 'roll':37}]
};

//I want to use it here to get an array object matching the if condition
let studentObject= <b>i18next.t(student)</b>.filter(student =>{
					 if(student.roll>30)
						return student;
});

//I want an alert for the first object from obtained object
alert(studentObject[0].name);

Please suggest a soln.

**Comment by jamuhl** [comment]
https://www.i18next.com/translation-function/objects-and-arrays

**Comment by prwinkmr** [comment]
In case of arrayOfObjects from documentation we will have to give index explicitly but filter function is self looping so no idea about index.
I need a translated array from i18next.t('student') but I am getting undefined.

**Comment by jamuhl** [comment]
please make a fiddle to reproduce: https://jsfiddle.net/jamuhl/dvk0e8a9/#tabs=js,result,html

should work if done right...

**Comment by prwinkmr** [comment]
https://jsfiddle.net/prwinkmr/gn4t62Lp/2

**Comment by jamuhl** [comment]
read the docs: https://www.i18next.com/translation-function/objects-and-arrays#objects

set `returnObjects: true` on init - bang

**Comment by prwinkmr** [comment]
https://jsfiddle.net/8yubs37a/
It worked.
Thank you

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
