### ISSUE TITLE
missingKeyHandler with updateMissing

### ISSUE THREAD

**Issue by mbecker-bemit** [i18next/i18next#1222]
I'm in search of a way to change the displayed key for a missing key after getting the missing translation from the backend.

Scenario:
- React app with locales using webpack-bundled loader with i18next-xhr-backend
- Missing keys should be served from general backend Api not from ReactApp

i18next-xhr-backend: Searched for "other domain on missing key" etc. in relation to addPath, but seems not designed to work in this manner.

Is it possible to post the missing keys to an Api and use the result to display? Tried different options and could not get the values beeing updated.

Current parts:

React, having a key_scope `defaults.types.` having the native translations, but `type` comes from the Api (different domain, different server). When type is not in react locales it should get posted to the Api-backend to fetch the needed translation.

```
{t(key_scope + type, type)}
```

in i18n.init(config), missingKeyHandler gets called but seems not to be able to update the value
```
debug: true,
saveMissing: true,
updateMissing: true,
appendNamespaceToMissingKey: true,
missingKeyHandler: (lng, ns, key, fallbackValue, updateMissing, options) => {
    // testing especially one key
    if(ns === 'page--shop-product' && key === 'defaults.types.event-item') {
        // thought about references, but also updateMissing is false everytime
        options.defaultValue = 'Event Item;

        // first try was to return the value/a promise
        return 'Event Item';
    }
},
// also tried parseMissingKeyHandler, but no promise seems to be supported, what i think i would need to get the result form an Api
parseMissingKeyHandler(key)
    /*return new Promise(res => {
        res('Event Item');
    });*/
    return key;
},
```

Debug logs:
`i18next::translator: missingKey en page--shop-product defaults.types.event-item event-item`

Didn't quite understand how `updateMissing` was meant to work.

Thanks for your time and suggestions!

**Comment by jamuhl** [comment]
saveMissing is only meant to post a missing to the backend - not to get back results for that missing key (so it's a feature to use during development).

parseMissingKeyHandler is only a helper to highlight those keys during development in the UI by making them stand out more.

updateMissing -> naming is a little misleading -> having a key and a defaultValue i18next will check it the defaultValue has changed in comparison to the received data - if so - it will send an update request to server.

**Comment by mbecker-bemit** [comment]
Okay so misunderstood the possibilities here, thanks for your reply!

Come to this solution now, as using bundled locales i already got a `ajax` function registered for `i18next-xhr-backend`, so modified this to use multiple endpoints and merging the return values.

This way there are (a lot) unneeded network requests, but the response should getting cached with the `i18next-localstorage-backend`.

Do you got any hints if theres a better way?

```
function loadLocales(url, options, callback, data) {
    try {
        let waitForLocale = import ('../locales/' + url + '.json');
        let waitForBackendLocale = new Promise(resolve => {
            // mocking data for one namespace/language, todo: here fetch from backend
            if('en/page--shop-product' === url) {
                resolve({
                    defaults: {
                        types: {
                            "event-item": "Event Item"
                        }
                    }
                });
            }
            resolve(false);
        });

        Promise.all([waitForLocale, waitForBackendLocale])
            .then(data => {
                if(data[1]) {
                    // when received something from backend, deepmerge into bundled locales
                    data[0] = merge(data[0], data[1]);
                }
                callback(data[0], {status: '200'});
            });
    } catch(e) {
        callback(null, {status: '404'});
    }
}
```

**Comment by jamuhl** [comment]
if it works - it works ;)

**Comment by abea** [comment]
It seems pretty clear that `missingKeyHandler` is not meant to allow devs to decide how to handle and display a string if the key is not found. Is there another way to do that? Some hook to make a final decision how to handle unknown keys (aside from setting a single default value)?

**Comment by abea** [comment]
Ah it looks like that's `parseMissingKeyHandler`. I think that'll get me where I need to be. 👍
