### ISSUE TITLE
IE10 - 'Unable to get property * of undefined or null reference'

### ISSUE THREAD

**Issue by ilanbm** [i18next/i18next#1226]
I am getting Unable to get property * of undefined or null reference when I have opened console in **IE10** and refresh the page.
The error is from EventEmitter.js _this.observers[event] = _this.observers[event] || [];

How to reproduce:
1/ Open in Internet Explorer 11
2/ Open debugging console (F12)
3/ Reload the page
4/ You should see Unable to get property * of undefined or null reference

**Comment by jamuhl** [comment]
Accepting PR's regarding IE usage..
