### ISSUE TITLE
Try eslint-plugin-i18next to make sure all literal strings are translated

### ISSUE THREAD

**Issue by edvardchen** [i18next/i18next#1229]
I had made [eslint-plugin-i18next](https://github.com/edvardchen/eslint-plugin-i18next) to make sure all literal strings are translated except some special cases.

Try it and hope it can help you too. :)

**Comment by edvardchen** [comment]
Sure

**Comment by jackie-oaknorth** [comment]
for literal strings, if they are translated with the variable name instead of the hardcoded string, would the plugin able to understand it, or nontheless it will scream at all non-wrapped literals ?
something like:
const orderState = ["literal string1", "literal string2"];
orderState.map(state =>
    <input text={i18n.t(state)} />);

**Comment by edvardchen** [comment]
You are safe to use variable everywhere, including the call `i18n.t`. 

The plugin only checks the hand-code literal string. 

Because variables mostly were initialized by literals.

**Comment by jackie-oaknorth** [comment]
just to confirm, so for the above example, the plugin won't scream, even if we have the no-literal-string rule on right?

**Comment by edvardchen** [comment]
No. It would scream at the first line (but won't at the second line)

**Comment by jackie-oaknorth** [comment]
It looks like an issue to be fixed. the strings are already translated as part of the variable (on the second line). while the plugin was still screaming for basically hardcoding.

**Comment by edvardchen** [comment]
Unless we can make sure the variable only be used by `i18n.t`, not be rendered in JSX `<span>{orderState}</span>`, not be passed to another function call, etc

That is not easy to achieve.
