### ISSUE TITLE
Issue with plural if singular form resource does not include `count`.

### ISSUE THREAD

**Issue by rudgutter** [i18next/i18next#1230]
Hey!

I'm having trouble with plurals where the singular resource text does not want to use the number from `count` in the actual text.

Example: 
```
JS:
i18next.t('invoiceDueInXDays', { count: X });

Resource texts:
"invoiceDueInXDays": "Invoice due tomorrow",
"invoiceDueInXDays_plural": "Invoice due in {{ count }} days"
```

This results in "Invoice due tomorrow" no matter how high `count` is and a console log warning that says `no plural rule for: {{ locale }}`. But if I change `invoiceDueInXDays` to be for example "Invoice due in {{ count }} day" for the singular resource it works just fine.
¨
Would love to see `count` not being required in the actual text.

**Comment by jamuhl** [comment]
`i18next.t('invoiceDueInXDays', { count: X });` no double {{ 

is X a number (not string)...?

**Comment by rudgutter** [comment]
> `i18next.t('invoiceDueInXDays', { count: X });` no double {{
> 
> is X a number (not string)...?

I messed up, Edited now. X is always a number. I want the singular if X is 1.

**Comment by rudgutter** [comment]
> And what language did you set? either set it on init `lng: 'en'` or use a detector

The language is swedish/`sv`.

**Comment by jamuhl** [comment]
https://jsfiddle.net/vLr2sqmx/2/ works

**Comment by rudgutter** [comment]
> https://jsfiddle.net/vLr2sqmx/2/ works

You are correct. I see now that creative renaming of my language files has had some unwanted effects on the language code used to init 18next. All fixed now.

Thanks for your help and your time. Appreciate it :)
