### ISSUE TITLE
load "languageOnly" being ignored in 15.0.9?

### ISSUE THREAD

**Issue by ugogo** [i18next/i18next#1233]
Hey guys 👋 

I'm currently upgrading a React app

```diff
- "i18next": "10.6.0",
- "i18next-browser-languagedetector": "^2.2.4",
- "react-i18next": "7.5.1",
+ "i18next": "15.0.9",
+ "i18next-browser-languagedetector": "^3.0.1",
+ "react-i18next": "10.8.1",
```

My `resources` are built like this

```js
{
  en: {translations: {…}}
  fr: {translations: {…}}
  it: {translations: {…}}
  sv: {translations: {…}}
}
```

And this is how `i18next` is called

```js
const initOpts = {
  whitelist: translatedCountries,
  nonExplicitWhitelist: true,
  fallbackLng: "en",
  load: "languageOnly",

  debug: process.env.NODE_ENV === "development",

  detection: {
    caches: null, // we don't want (yet) to store the user language
  },

  interpolation: {
    escapeValue: false,

    // compatibility with existing locales
    prefix: "{",
    suffix: "}",
  },

  resources,
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init(initOpts);
```

With the previous version, my locales were correctly loaded and translated, but with the new one I have this error every time

```
i18next::translator: missingKey fr-FR translation navigation_title_dashboard navigation_title_dashboard
```

_Note that I'm using `load: "languageOnly"_

Is there something I'm missing?

Thanks 🙏

**Comment by jamuhl** [comment]
Does your i18n.js export the return value of i18next.init?!?

If so migration guide would tell you that i18next.init now not returns "this" but a Promise.

Just export i18next itself

**Comment by jamuhl** [comment]
that is correct...just was my thought as you get a missing...

that missing - is it really missing in your file for `fr` and `fallbackLng`?

that the missing shows `fr-FR` is no big deal - it's like i18n.language will be fr-FR -> while i18n.languages which is used to resolve translations will be `['fr', 'fallbackLng']`

**Comment by ugogo** [comment]
No locales have been updated since I only upgraded the packages' version
I created a repo reproducing the error if that might help you: https://github.com/ugogo/i18next-debug

**Comment by jamuhl** [comment]
🤷‍♂️your sample is broken:

a) https://github.com/ugogo/i18next-debug/blob/master/src/i18n.js#L20 `languages` is internal -> do not set that
b) https://github.com/ugogo/i18next-debug/blob/master/src/i18n.js#L12 default namespace is `translation` not `translations`

**Comment by jamuhl** [comment]
Fixing this all looks ok:

Calling `http://localhost:3000/?lng=fr-FR`

Ends in:

i18n.language: `fr-FR`
i18n.languages: `['fr', 'en']`

<img width="886" alt="Screenshot 2019-04-25 at 16 38 43" src="https://user-images.githubusercontent.com/977772/56744345-9d0b2300-6778-11e9-9494-ec09c07f1217.png">

**Comment by ugogo** [comment]
Hahaha 🤦‍♂️ 
It was indeed a `translation` vs `translations` mistake

Thanks for the help @jamuhl 🙌
