### ISSUE TITLE
Treat objects as missing keys when returnObjects is false

### ISSUE THREAD

**Issue by acc15** [i18next/i18next#1234]
Currently (v15.1.0) if key points to object `i18next.t(key)` returns `undefined` even if `returnNull` and `returnEmptyString` is false.
Also if fallback key is provided its ignored resulting in `undefined`.

Simple reproduction test:

    const i18next = require("i18next");
    i18next.init({
        lng: "en",
        debug: true,
        resources: {
            en: {
                translation: {
                    a: {
                        b: "WoW"
                    }
                }
            }
        },
        returnEmptyString: false,
        returnNull: false,
        returnObjects: false,
        parseMissingKeyHandler: key => {
            console.log("Missing key: " + key);
            return key;
        }
    }).catch(err => console.log("i18n error", err));
    console.log("Single key: " + i18next.t("a")); // => undefined (must be 'a')
    console.log("Key with fallback: " + i18next.t(["a", "a.b"])); // => undefined (must be 'WoW')

May be i missed some point, 
but that behavior looks very strange 
especially when i18next ignores fallback keys.

**Comment by jamuhl** [comment]
Simple:

`i18next.t('a');` exists and would return an object `{ b: "WoW" }` which is not allowed by setting `returnObjects: false`

`i18next.t(["a", "a.b"]);`  "a" exists (therefore no fallback) and would return an object `{ b: "WoW" }` which is not allowed by setting `returnObjects: false`

**Comment by acc15** [comment]
Is there any way to return `key` instead of `undefined`? 

Without `returnObjects` its actually can be considered as a `typo` (like `a.`, `a.c`, etc), therefore it would be nice if i18next can help handle such kinds of typos.

**Comment by acc15** [comment]
See #1288
