### ISSUE TITLE
Change language dynamically

### ISSUE THREAD

**Issue by wguillen3** [i18next/i18next#1235]
Does i18next provide the facility to change the language dynamically inside the react native app?

Suppose in my app I have 3 checkboxes.

1. English
2. French
3. German

When I click on any checkbox I want to change the language to my whole app to the specified language.

Does i18next support to change the language at run time in react native?

**Comment by jamuhl** [comment]
Please have a look at: https://github.com/i18next/react-i18next

and the sample for react-native: https://github.com/i18next/react-i18next/tree/master/example/react-native
