### ISSUE TITLE
How to create/use a custom plugin?

### ISSUE THREAD

**Issue by tonix-tuft** [i18next/i18next#1237]
Hello,

I've tried to create a custom plugin (`./myPlugins/atTrimmerPostProcessor`):

```
const plugin = {
    type: 'postProcessor',
    name: 'atTrimmer',
    process: function (value, key, options, translator) {
        console.log('IT WORKS!');
        return trimCharacterMask(value, '@')
    }
}
export default plugin
```

And use it like this:

```
import atTrimmer from './myPlugins/atTrimmerPostProcessor'
...

i18n
    .use(atTrimmer)
...
```

However, the `t` function does not fire the `process` callback (I cannot see 'IT WORKS!' in the console) and the translated strings are not trimmed.

**Comment by jamuhl** [comment]
did you enable the post processor -> only `.use(...)` is not enough

`i18next.t('key', { postProcess: 'atTrimmer'});`

or for all

`i18next.init({ postProcess: ['atTrimmer'] })`

**Comment by tonix-tuft** [comment]
Nevermind,

I found out that I needed to add the following line in `.init` also:

```
import atTrimmer from './myPlugins/atTrimmerPostProcessor'
...

i18n
    .use(atTrimmer)
    ...
    .init({
        ...
        postProcess: ['atTrimmer']
    })
```
