### ISSUE TITLE
how to set initLanguage from queryString?(?lang=en)

### ISSUE THREAD

**Issue by huanglijiao** [i18next/i18next#1242]
https://github.com/isaachinman/next-i18next/issues/300

**Comment by huanglijiao** [comment]
there is no window on server...
`export default {
name: 'myDetectorsName',

lookup(options) {
// options -> are passed in options
return 'en';
},

cacheUserLanguage(lng, options) {
// options -> are passed in options
// lng -> current language, will be called after init and on changeLanguage
`
in function lookup, we can get req or query on server?  we can get it from options??

**Comment by jamuhl** [comment]
no window on server -> but req https://github.com/i18next/i18next-express-middleware/blob/master/src/languageLookups/querystring.js#L11 did you look at next-i18next using i18next-express-middleware on serverside...?
