### ISSUE TITLE
Using java ResourceBundle property files

### ISSUE THREAD

**Issue by henrik242** [i18next/i18next#1243]
Is it possible to use a java-type properties file as resourcebundle?  Typically a `Messages_nb_NO.properties` with `key = value` entries.

It's read from java using `java.util.ResourceBundle.getBundle("Messages", new Locale("nb", "NO"))`

**Comment by jamuhl** [comment]
Either by converting it to JSON or parsing that on the fly using the parse function on the xhr-backend option

**Comment by henrik242** [comment]
Thanks!
