### ISSUE TITLE
dynamic joinArrays or formatSeparator

### ISSUE THREAD

**Issue by Taylor123** [i18next/i18next#1245]
I'm not sure if i'm looking in the wrong place in the docs, but is there a built in way to have a dynamic separator based on array length like the following example?

"I have a cat"
"I have a cat and dog"
"I have a cat, dog, and fish"
"I have a cat, dog, fish, and snake"

**Comment by jamuhl** [comment]
No...but if i remember right there is a draft / experimental implementation for that on the Intl API of chrome

**Comment by jamuhl** [comment]
If ok i will close this for now...we can reopen this as this Intl addition get widely adopted in all the browsers out there.
