### ISSUE TITLE
`addResources` does not support `[object Object]` values

### ISSUE THREAD

**Issue by i8ramin** [i18next/i18next#1250]
Not sure why this is the case, but for some reason the `addResources` method does not seem to handle message bundles defined as objects (`[object Object]`), but only `[object Array]`. This is the line of code in question:

https://github.com/i18next/i18next/blob/31201aae794b4ab19abc7a21735630c50c97606a/src/ResourceStore.js#L68-L71

For example, given the following key/value:

```json
{
  "footer": {
    "copyright": "Copyright © 2019"
  },
}
```

The value of `Object.prototype.toString.apply(resources[m])` is actually `[object Object]` and not `[object Array]`. With this change, it will check for both (although I am not sure when it would be `[object Array]`)

Got a PR for a potential fix here: https://github.com/i18next/i18next/pull/1249

**Comment by jamuhl** [comment]
addResources is just a import an array of addResource

for importing full files there is: https://www.i18next.com/overview/api#addresourcebundle
