### ISSUE TITLE
mimicking inheritance through fallback

### ISSUE THREAD

**Issue by zd-project** [i18next/i18next#1251]
Hi, I would like to know how to achieve the following behavior elegantly.

Say I have a key with an object:

```json
{
    "a": {
        "b": "c",
        "d": "e"
    },
    "a_aContext": {
        "b": "f",
    }
}
```
For my api I would like to return complete object a (returnObjects: true) in both situations but I also want to only store the diff in "a_aContext". I can't think of any better way to do so other than looping through "a" object and add back the missing translations.

Is there a better way?

**Comment by zd-project** [comment]
Actually, what is happening right now is this
when I do
```javascript
t('a', {context: 'aContext', returnObjects: true});
```
The result is
```json
{
    "b": "c",
}
```

Which I do not understand at all....

**Comment by jamuhl** [comment]
returnObjects...take object but still handles all the keys inside as single translations -> doing interpolation, nesting,... on them...so might be using returnObjects and context is to much breaking a consistent behaviour
