### ISSUE TITLE
saveMissing does not save missing keys

### ISSUE THREAD

**Issue by reZach** [i18next/i18next#1252]
### i18next-node-fs-backend v2.1.3

Having trouble following the already-closed issues around this. In my application, **saveMissing** is not saving any missing keys in the _way that I expect_, can you please advise if this is the proper way to use saveMissing. The intention of the below config is to add missing translations for "de" - German.

    const config = {
        fallbackLng: "de",
        whitelist: ["en", "de", "fr"]
    };    

    const i18n = require('i18next');
    const i18nextBackend = require('i18next-node-fs-backend');

    const i18nextOptions = {
        backend: {
            // path where resources get loaded from
            loadPath: './app/utils/i18n/locales/{{lng}}/{{ns}}.json',

            // path to post missing resources
            addPath: './app/utils/i18n/locales/{{lng}}/{{ns}}.missing.json',

            // jsonIndent to use when storing json files
            jsonIndent: 4,
        },
        debug: true,
        interpolation: {
            escapeValue: false
        },
        namespace: "transaction",
        saveMissing: true,
        fallbackLng: config.fallbackLng,
        whitelist: config.whitelist,
        react: {
            wait: false
        }
    };

    if (!i18n.isInitialized){
        i18n.use(i18nextBackend).init(i18nextOptions).then(function(value){
            i18n.changeLanguage(config.fallbackLng, (err, t) => {
                if (err){
                    return console.log("couldn't change language");
                }
            });
        });
    }

    export default i18n;

If I omit **fallbackLng**, i18n tries to switch the language to "dev" as [mentioned in the docs](https://www.i18next.com/overview/configuration-options#languages-namespaces-resources) and will actually try to write missing translations to the dev path (/locales/dev/translation.missing.json) in the config above. Only when the fallbackLng is equal to the language I'm trying to catch missing translations for will the missing translation keys get saved to file.

Is there a way that allows me to **not** have to change fallbackLng everytime I want to capture missing translations for a language?

**Comment by jamuhl** [comment]
you can use saveMissingTo https://www.i18next.com/overview/configuration-options#missing-keys

but still as a lookup will only trigger a missing if the key could not be found in either current language or fallback - that won't help a lot until setting fallbackLng to false

For keeping keys consistent over multiple languages you best use a translation management system like our https://locize.com

**Comment by reZach** [comment]
Thank you @jamuhl, that worked as you said.

For those who happen to view this issue later, the following settings are necessary for generating missing entries for languages that are found in your **whitelist** in your i18n config file.

    saveMissingTo: "current",
    fallbackLng: false

**Comment by Tommuh** [comment]
> Thank you @jamuhl, that worked as you said.
> 
> For those who happen to view this issue later, the following settings are necessary for generating missing entries for languages that are found in your **whitelist** in your i18n config file.
> 
> ```
> saveMissingTo: "current",
> fallbackLng: false 
> ```

Thank you !!
