### ISSUE TITLE
Local translations are not loaded when there is no network connection

### ISSUE THREAD

**Issue by JohannesKlauss** [i18next/i18next#1253]
I have an React Native app and we load the translation files locally like this:

```
i18n.use(localeDetector).init({
  debug: __DEV__ && Config.DEV_HIDE_TRANSLATION_WARNINGS !== 'true',
  initImmediate: false, // https://www.i18next.com/overview/configuration-options#initimmediate
  fallbackLng: FALLBACK_LANG,
  saveMissing: true,
  parseMissingKeyHandler: key => {
    const currentLocaleInUse = CURRENT_LOCALE_IN_USE || 'de-DE';
    const resource = staticResources[currentLocaleInUse];
    const keyParts = key.split('.');
    let res = resource;
    keyParts.forEach(k => {
      res = res[k];
    });
    return res;
  },
  resources: {
    cs: {translation: require('../../i18n/cs/messages.json')},
    de: {translation: require('../../i18n/de/messages.json')},
    fr: {translation: require('../../i18n/fr/messages.json')},
    nl: {translation: require('../../i18n/nl/messages.json')},
    pl: {translation: require('../../i18n/pl/messages.json')},
    ro: {translation: require('../../i18n/ro/messages.json')},
    sk: {translation: require('../../i18n/sk/messages.json')},
    hu: {translation: require('../../i18n/hu/messages.json')},
    ...(__DEV__
      ? {en: {translation: require('../../i18n/en/messages.json')}}
      : {}),
  },
  react: {
    usePureComponent: true,
  } as any,
});
```

But when the app has no network connection the translation do not get loaded even though init logs say, that the selected language file is loaded. But through out the app the values are not displayed and inside the logs i18next says, that the keys are missing.

Does i18next rely on network connection on init?

**Comment by jamuhl** [comment]
no...i18next does not rely on network connection...only when you add a backend - passing resources on init is all needed...

You do not add any backend - so nothing gets loaded via network - your resources passed in are used.

if you get missings you might need to check why those do not exist -> wrong namespace, wrong language,... => also check i18next.services.resourceStore.data having your translations

**Comment by JohannesKlauss** [comment]
If I have a internet connection, everything works fine. So it has to have something to do with the unavailable network.

`i18next.services.resourceStore.data` exists and has the translations as values when network is on, but the keys as values when network is off.

**Comment by jamuhl** [comment]
so it does not have them without network...but my guess is that has more to do with how you bundle that...seems those `cs: {translation: require('../../i18n/cs/messages.json')},` are creating lazy bundles or something like that...

like said...i18next has no code for connection to the network...as it's just a core used in javascript envs -> all that networking is part of backend implementations.

**Comment by JohannesKlauss** [comment]
But the object dumped by the i18n when initialized has all the needed translations and their values are correct. So it does get loaded.
And I just realized that not all translations are missing. And another thing is very odd:
When online, the created resources object looks like this:
![Bildschirmfoto 2019-05-29 um 13 29 43](https://user-images.githubusercontent.com/6214415/58553778-17b2dc80-8216-11e9-94b4-a7d1651de4f6.png)

When offline i18n adds another object to the resources object:
![Bildschirmfoto 2019-05-29 um 13 30 20](https://user-images.githubusercontent.com/6214415/58553805-27322580-8216-11e9-8b7e-625730be302a.png)

The created `de_DE` object has the translation keys as values and only those keys, that are currently shown on the screen.

**Comment by jamuhl** [comment]
Guess difference in missings is more due to adding the "en" translations only for __DEV__ -> no idea why you do that

Does your localDetector change de_DE to de-DE? make sure you get languages in the format lng-REGION

**Comment by jamuhl** [comment]
In the end i'm just guessing...but the problems are not with i18next - like said - there is no network dependency...if you do not believe go through debugging...must be something you added or your typescript bundler does...

**Comment by JohannesKlauss** [comment]
The localDetector changes it the other way round. When I switch the language all keys are getting translated correctly, even if I am offline.
If I close the app and reopen it, the translations are gone. Switching the language fixes it again even though there is no internet connection. So there has to be some bug in the init process. Are you sure that there is not one line depending on a connection somewhere? It just seems weird to me, since it's only on init time.

**Comment by JohannesKlauss** [comment]
Also setting the json explicitly in the i18n resource object on init doesn't help.

**Comment by jamuhl** [comment]
like said...look at the code ... there is 200% nothing depending on the network - we used i18next on react-native apps for years in production - never had an issue...

**Comment by JohannesKlauss** [comment]
You're indeed right. It's a problem with the apps connection handling. Thank you for you patience, your answers led me to the bug fix. Thank you very much.

**Comment by goushik** [comment]
Hey @JohannesKlauss 
I'm using i18next for translation in React native with typescript

I am also facing similar issue
Any suggestion how to fix it

**Comment by JohannesKlauss** [comment]
@goushik I sadly don't have access to the project anymore and can't really remember what the issue was. Sorry

**Comment by goushik** [comment]
Hey @JohannesKlauss 

I fixed it
thank you

**Comment by sedannaim** [comment]
Having the same issue @goushik how did you manage to sort it?
