### ISSUE TITLE
TResult inferred incorrectly when result of t passed into a function accepting null

### ISSUE THREAD

**Issue by TLadd** [i18next/i18next#1254]
If I pass the return value of calling the `t` function, to a function that accepts `string | null`, Typescript seems to be doing some kind of inference on `TResult` where it assumes `string | object | (string | object)[] | undefined` instead of the default `string`. Codesandbox: https://codesandbox.io/s/thirsty-tdd-exc2x

```
import i18n from "i18next";
import "./styles.css";

function operateOnString(x: string | null) {
  return x;
}

const definitelyAString = i18n.t("hello");

// Works
operateOnString(definitelyAString);

// Type Error Argument of type 'string | object | (string | object)[] | undefined' is not assignable to parameter of type 'string | null'.
operateOnString(i18n.t("hello"));
```

I'm lucky enough where I can just modify my functions/components to accept `string | undefined` instead (which doesn't cause this issue), but would be ideal if `null` didn't result in inferring a value other than the default `string`.

**Comment by rosskevin** [comment]
There is no way that I am aware to tell typescript that it should default the type to string when it could be one of many types to solve this error. null !== undefined

As-is the parameterized type is by default set as string, but that is not going to satisfy strict null checking for tsc (which I do recommend).

I'm on vacation for the next four days so it will be some time before I can look. There are tests in this area already (passing the result to a function). If this is important to you, please PR a potential solution (I'm not aware of one at this time).

I agree it would be nice for inference to just work here, perhaps by adding null to the type, but as I recall this may be trickier than expected.
