### ISSUE TITLE
Can I translate a React component?

### ISSUE THREAD

**Issue by davebertz** [i18next/i18next#1257]
I have an svg image imported as a React component like this: 
`import {ReactComponent as img} from '../img/img_en.svg';`

But I also have a french version of this image that I would like to render when the user selects french as language. 

`import {ReactComponent as img} from '../img/img_fr.svg';`

Any idea how I should do this? Tried looking into it without success.

**Comment by jamuhl** [comment]
import {ReactComponent as fr_img} from '../img/img_fr.svg';
import {ReactComponent as en_img} from '../img/img_en.svg';

now take whichever matchet i18next.language better

**Comment by davebertz** [comment]
I was using i18next.language() instead of i18next.language, which was throwing me an error, New to i18next, sorry for the dumb question. It works now, thank you.

**Comment by jamuhl** [comment]
glad you got it to work...

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
