### ISSUE TITLE
fallback order with multiple namespaces

### ISSUE THREAD

**Issue by mooflu** [i18next/i18next#1260]
https://github.com/i18next/i18next/blob/5e6d296d392c455d0e06bc08b53110f0aacfb0c7/src/Translator.js#L332

Let's say I have an english and a german dictionary, each with 2 namespaces: professional and google.
I.e. I want it to pick the professional translation first and fallback to google translation

ns: ['professional', 'google']
defaultNS: professional
fallbackNS: google
fallbackLng: en

I would have expected for it to search across all namespaces in a given language, then fallback to en. 
i.e. 
de->professional, de->google, en->professional, en->google

The code (link at the top) loops over namespaces for each language:
de->professional, en->professional, de->google, en->google
i.e. if there is no professional de translation it uses english instead of de google translation.

I ended up putting all our master english in to en->google (no entries in en->professional) in order to get 
de->professional, de->google, en->google

Am I using this wrong?

**Comment by jamuhl** [comment]
No nothing wrong...it's a historical thing...started like that... then suddenly came fallbackNamespaces to the fallbackLng and we never thought of people using it that way.

Guess we can change that order in future...but that will be a breaking change.

**Comment by mooflu** [comment]
FWIW, we're in the process of switching to backend loading and the BackendConnector does search across namespaces in a given language. I.e. the opposite of what the Translator does.

https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L40

**Comment by jamuhl** [comment]
@mooflu The two are not related - but look...why not just doing a PR -> create an option which enables new behavior while keeping old as default

**Comment by mooflu** [comment]
Thanks for the quick reply. I thought the BackendConnector had a fallback mechanism similar to Translator - sorry for the noise, should have looked closer.
