### ISSUE TITLE
cloneInstance() does not preserve language

### ISSUE THREAD

**Issue by OlegZee** [i18next/i18next#1261]
I'm using cloneInstance to pass i18next instance with different default NS to a different components. I noticed that cloneInstance() does not copy language setting.

Here's initialization code in "viewer" component:

		import i18next from './i18n';
		...
		constructor(element: any, options?: any, xi18n?: i18next.i18n) {
		    ...
		    const i18n = (xi18n || i18next).cloneInstance({ fallbackLng: 'en', defaultNS: 'viewer' });
		    if(xi18n != null) i18n.changeLanguage(xi18n.language);

Notice the second line is a workaround for things to work.

**Comment by jamuhl** [comment]
The clone instance is there to share the resources - main reason was to have a different language.

**Comment by jamuhl** [comment]
But should copy language over: https://github.com/i18next/i18next/blob/master/src/i18next.js#L414 - so might be an issue it does not have same language (after creation)...You might add a PR or let me check this when I got time for it

**Comment by OlegZee** [comment]
> But should copy language over: https://github.com/i18next/i18next/blob/master/src/i18next.js#L414 - so might be an issue it does not have same language (after creation)...You might add a PR or let me check this when I got time for it

You are perfectly correct, I saw this an evidence **it should work** while debugging internals, but apparently it does not.

**Comment by jamuhl** [comment]
My guess: https://github.com/i18next/i18next/blob/master/src/i18next.js#L418 creating the translator came later -> and we forgot to set `clone.translator.language = clone.language;`

**Comment by jamuhl** [comment]
actually this should work: https://github.com/i18next/i18next/blob/master/test/i18next.spec.js#L55

might be just a timing issue -> you check immediately after cloning the creation itself is async: https://github.com/i18next/i18next/blob/master/src/i18next.js#L138

setting `initImmediate: true` in clone options should give you correct result in a sync way.
