### ISSUE TITLE
Problem with unpkg CDN?

### ISSUE THREAD

**Issue by KenLFG** [i18next/i18next#1262]
Hi, I've been using the unpkg.com URLs for a little while and haven't had much problems with it until tonight (first time I've used it since Friday). 

Going here:
https://unpkg.com/i18next/i18next.js

(per the docs), redirects you here:
https://unpkg.com/i18next@17.0.1/i18next.js

And gets you a 404 (as a script include) and this if you pull it up directly in a browser:
`Cannot find "/i18next.js" in i18next@17.0.1`

I tried on a whim going here (in a browser):
https://unpkg.com/i18next

and was redirected here:
https://unpkg.com/i18next@17.0.1/index.js

which displays:
`/* eslint no-var: 0 */
var main = require('./dist/cjs/i18next.js');

module.exports = main;
module.exports.default = main;`

Which doesn't help me much on the front-end...

This a temporary problem or something that needs fixing? Or are the docs in need of an update (https://www.i18next.com/overview/getting-started)?

**Comment by jamuhl** [comment]
Yes, docs need an update: https://github.com/i18next/i18next/blob/master/CHANGELOG.md#1700

**Comment by jamuhl** [comment]
changed it now: https://app.gitbook.com/@i18next/s/i18next/overview/getting-started#load-from-cdn hope there are no other places...

**Comment by KenLFG** [comment]
Forgive my ignorance but do I need to include it in a different way if it's a UMD module (was the original build before 1.7.0.1 a UMD by default)?

I ask because if I just update my script tag as follows:

`  <script src="https://unpkg.com/i18next/dist/umd/i18next.js"></script>
  <script src="https://unpkg.com/i18next-xhr-backend/i18nextXHRBackend.js"></script>
  <script src="https://unpkg.com/i18next-browser-languagedetector/i18nextBrowserLanguageDetector.js"></script>`

As listed in the Getting Started docs, I'm getting errors about the .use and .t functions:

`global.js:209 Uncaught TypeError: i18next.use is not a function
    at Module.eval (global.js:209)
    at eval (global.js:385)
    at Module../app/js/lib/global.js (global.js:133)
    at __webpack_require__ (global.js:20)
    at global.js:84
    at global.js:87
(anonymous) @ global.js:209
(anonymous) @ global.js:385
./app/js/lib/global.js @ global.js:133
__webpack_require__ @ global.js:20
(anonymous) @ global.js:84
(anonymous) @ global.js:87
nav_user_menu.js:31 Uncaught TypeError: i18next.t is not a function
    at eval (nav_user_menu.js:31)
    at Module../app/js/components/admin/nav_user_menu.js (nav_admin.js:109)
    at __webpack_require__ (nav_admin.js:20)
    at Module.eval (nav_admin.js:5)
    at eval (nav_admin.js:30)
    at Module../app/js/admin/nav_admin.js (nav_admin.js:97)
    at __webpack_require__ (nav_admin.js:20)
    at nav_admin.js:84
    at nav_admin.js:87`

My init looks like this:

`
// i18next Setup //
i18next
.use(i18nextXHRBackend)
.use(i18nextBrowserLanguageDetector)
.init({
  fallbackLng: 'en',
  debug: true,
  ns: ['translation'],
  nsSeparator: '::',
  defaultNS: 'translation',
  backend: {
    loadPath: window.global_i18next_load_path,
    crossDomain: true
  }
}, function(err, t) {
  // init set content

});
`

Or, wait, could it be the link is going to the wrong version? I'm seeing it, if I just click through in a browser, go to 16.0.0?

`https://unpkg.com/i18next@16.0.0/dist/umd/i18next.js`

That matches the version hosted on cdnjs, though. Is cdnjs preferred over unpkg.com for script includes (versus NPM/webpack/etc.)?

**Comment by jamuhl** [comment]
must fix the link...

also had to bring back the old location as to much users seems to use the non fixed version:

---- note done on other issues ----
brought back in i18next@17.0.2

but be aware any update when using https://unpkg.com/i18next/i18next.min.js could be breaking as it redirects to lastest version (which could be major and API breaking)

you should use a fixed version like https://unpkg.com/i18next@16.0.0/i18next.min.js to make sure there is nothing breaking when using latest

**Comment by KenLFG** [comment]
Okay, thanks for the advice. The unpkg links to the latest version don't seem to be working again. This time it's just a 500 error constantly. Is the 17.x version not ready yet? Should I just stick with the 16.0.0.0 one (seems to be more consistently up)?

**Comment by KenLFG** [comment]
Also, any suggestions for the xhr-backend and browser-languagedetector plugins? They both use the unpkg URLs so I'm getting the same problem with them:

https://unpkg.com/i18next-xhr-backend/i18nextXHRBackend.js
https://unpkg.com/i18next-browser-languagedetector/i18nextBrowserLanguageDetector.js

I'm talking in terms of direct links to versions or equivalent URLs for cdnjs.com, if they exist.

**Comment by jamuhl** [comment]
@KenLFG not sure why their CDN currently is that slow...but guessing they are aware of it
