### ISSUE TITLE
 How to use the translation in the web component 

### ISSUE THREAD

**Issue by sowmiyaseshadriii** [i18next/i18next#1265]
thanks for the package.
I have implemented `i18next-express-middleware` and working fine for multilanguage.
I am using `lit-element polymer` in front-end, How to use the translation in the web component, and is it possible to pass the json file to web component, Is there any way to pass it as response on client side components.kindly help and thanks
```
//app.js
i18next
  .use(Backend)
  .use(i18nextMiddleware.LanguageDetector)
  .init({
    backend: {
      loadPath: path.join(__dirname + '/locales/{{lng}}.json'),
      addPath: __dirname + '/locales/{{lng}}.missing.json'
    },
    detection: {
      order: ['path','cookie','querystring'],
      caches: ['cookie']
    },
    fallbackLng: 'en',
    preload: ['en', 'zh'],
    saveMissing: true
  });
  app.use(bodyParser.urlencoded({ extended: true }));
  app.use(bodyParser.json());
  app.use(i18nextMiddleware.handle(i18next));

//component.js
import { LitElement, html, css
} from "https://unpkg.com/@polymer/lit-element/lit-element.js?module";
export class Element extends LitElement {

  static get properties() {
    return {
       translate: {type: Object}
    }
 constructor() {
    super();
}

render(){
  <p>${t.list}</p> // not displaying
} 
}

//index.ejs
<div>
 <h1><%=t("home.headertitle")%></h1>  //working fine in  template 
 <my-element></my-element> 
</div>


```

**Comment by jamuhl** [comment]
client side you can use: i18next with the xhr-backend...on serverside use statics to serve them...

**Comment by sowmiyaseshadriii** [comment]
thanks for reply, can you please provide sample, and also I have tried using https://github.com/vlaraort/litelement-i18next-mixin since am using litelement

**Comment by jamuhl** [comment]
would love todo so...but as you might expect i did not use every frontend tech out there...so i got not experience with that myself...
