### ISSUE TITLE
Do not send language cookie if not necessary

### ISSUE THREAD

**Issue by cesarvarela** [i18next/i18next#1269]
Hi, I would like to make setting the language cookie only when a language is set through a query string.

Right now for every request, even if the cookie is already set, I see that this cookie is added:

`Set-Cookie: next-i18next=en; path=/; expires=Sun, 21 Jun 2020 21:16:06 GMT`

This doesn't play nice with CDNs

**Comment by jamuhl** [comment]
I guess this is related to the i18next-browser-languagedetector: https://github.com/i18next/i18next-browser-languageDetector

you can add a custom detector for cookie like: https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality

And set only how you like: https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/cookie.js#L2
