### ISSUE TITLE
Do not refresh when language change but translate

### ISSUE THREAD

**Issue by sowmiyaseshadriii** [i18next/i18next#1270]
I would like to know is it possible to translate without refresh/reload, 
when i select language it only translates when refresh.

Pleas help

```

i18next
  .use(Backend)
  .use(i18nextMiddleware.LanguageDetector)
  .init({
    backend: {
      loadPath: path.join(__dirname + '/locales/{{lng}}.json'),
      addPath: __dirname + '/locales/{{lng}}.missing.json'
    },
    detection: {
      order: ['path','cookie','querystring'],
      caches: ['cookie']
    },
    fallbackLng: 'en',
    preload: ['en', 'zh'],
    saveMissing: true
  });
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use(i18nextMiddleware.handle(i18next));
```

**Comment by jamuhl** [comment]
doing serverside translation there is no way of doing it without a refresh ;)

on the client it depends on what UI Framework you use...eg. react-i18next solves that for react,... https://www.i18next.com/overview/supported-frameworks

**Comment by sowmiyaseshadriii** [comment]
thanks for reply, is it possibe to translate language code within URL, translates works fine but
I have a common header file which is used for all pages, is it possibe to change language code alone.

< a href="/fr/about" >About Us< /a > // if french selected
----
< a href="/en/about" >About Us< /a >// if english selected

**Comment by jamuhl** [comment]
sure it's possible...you just have to code it

**Comment by sowmiyaseshadriii** [comment]
thanks for reply
