### ISSUE TITLE
How to fix the error when I use i18next with externals method in TypeScript?

### ISSUE THREAD

**Issue by kingller** [i18next/i18next#1272]
I find the export method of `index.d.ts` is
```
export default i18next;
```
But when I use i18next with externals method as bellow (webpack.config.js)
```
{
        externals: { i18next: 'i18next' }
}
```
My script url is
```
<script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/i18next/17.0.4/i18next.min.js"</script>
```
the code is compiled to:
```
 i18next_1['default'].t
```
but the default is `undefined`, then the error happens.
If I change the export method of` index.d.ts` as `@types/i18next`
```
export = i18next;
```
It works well.
Can you change the export method?
Or, how can I specify the definition file to `@types/i18next`?
Wish get your help, thanks.

**Comment by kingller** [comment]
Sorry, when I don't use externals of webpack, it needs `export default i18next;`, otherwise the error will happen. 
My `tsconfig.json` file is
```
{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": true,
        "strictNullChecks": false,
        "module": "commonjs",
        "target": "ESNext",
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "allowSyntheticDefaultImports": true, // 允许使用 ES2015 默认的 import 风格
        "moduleResolution": "node",
        "allowJs": true,
        "baseUrl": "."
    },
    "include": [
        "./src/**/*"
    ]
}
```
I don't know how to support the two methods. Can you help me?

**Comment by rosskevin** [comment]
`esModuleInterop: "true"` in tsconfig I believe will solve your problem.  

This is possibly another side effect of using namespaces I mention in #1271

**Comment by kingller** [comment]
It's OK now. Thanks very much.
