### ISSUE TITLE
Is getDataByLanguage a public api?

### ISSUE THREAD

**Issue by mooflu** [i18next/i18next#1273]
Changelog mentions it under (11.6.0) 
https://github.com/i18next/i18next/blob/master/CHANGELOG.md#1160
but I don't see it in documentation or typescript definition file.

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/src/i18next.js#L116 yes it is.

We just never added it to the docs

**Comment by jamuhl** [comment]
https://www.i18next.com/overview/api#getdatabylanguage

**Comment by jamuhl** [comment]
@msftjayongg pull request welcome...add test case for regression and ping @rosskevin when ready
