### ISSUE TITLE
In Production, translation is not working

### ISSUE THREAD

**Issue by sowmiyaseshadriii** [i18next/i18next#1275]
Localhost translation works completely fine, but when deployed in production, text is not being translated.
Please help
am using i18next-express-middleware.

```
i18next
  .use(Backend)
  .use(i18nextMiddleware.LanguageDetector)
  .init({
    backend: {
      loadPath: path.join(__dirname + '/locales/{{lng}}.json'),
      addPath: __dirname + '/locales/{{lng}}.missing.json'
    },
    detection: {
      order: ['path','cookie','querystring'],
      caches: ['cookie']
    },
    fallbackLng: 'en',
    preload: ['en', 'zh-hans'],
    saveMissing: true
  });
```

**Comment by jamuhl** [comment]
if it works local...but not on your server you will need to read debug output from your server...guess loadPath is wrong or you got no access to read there...idk

**Comment by sowmiyaseshadriii** [comment]
@jamuhl   thanks for reply in production when i check with network tab its `set-cookie: i18next=zh-Hans; path=/; expires=Thu, 09 Jul 2020 01:18:19 GMT` and my locale file name is `zh-hans`  its because of that.

Any Idea

**Comment by sowmiyaseshadriii** [comment]
@jamuhl  thanks for reply 
I have updated the code with debugging and error logs
In that case when i run, am getting error since i dont have any files or preload options in `zh.json`,
Initially had but renamed , please help
 ```
[ { Error: ENOENT: no such file or directory, open 'C:\Sowmiya\Projects\send4x\locales\zh.json'
    errno: -4058,
    code: 'ENOENT',
    syscall: 'open',
    path: 'C:\\Projects\\pro\\locales\\zh.json' } ]
```
```
i18next
  .use(Backend)
  .use(i18nextMiddleware.LanguageDetector)
  .init({
    backend: {
      loadPath: path.join(__dirname + '/locales/{{lng}}.json'),
      addPath: __dirname + '/locales/{{lng}}.missing.json'
    },
    detection: {
      order: ['path','cookie','querystring'],
    },
    fallbackLng: 'en',
    preload: ['en', 'zh-Hans'],
    saveMissing: true,
    debug: true
  },(err, t) => {
    if(err){
        console.error(err);
        throw new Error(err);
    }
    console.log(t('header.title'));
  });

```

**Comment by jamuhl** [comment]
see the last sample here: https://www.i18next.com/principles/fallback#fallback-language --> fallbackLng can be an object -> add an extra case for `zh` having fallback to `zh-Hans` (if i remember right script part of a locale should start with uppercase so `Hans/Hant` not `hans/hant`)

**Comment by sowmiyaseshadriii** [comment]
I have updated the changes, but still am receiving the error

But I dont have `zh` in preload  or locales foler `zh.json` not sure why receiving the error. please help
```
[ { Error: ENOENT: no such file or directory, open 'C:\Sowmiya\Projects\send4x\locales\zh.json'
   errno: -4058,
   code: 'ENOENT',
   syscall: 'open',
   path: 'C:\\Projects\\pro\\locales\\zh.json' } ]
```

```
i18next
  .use(Backend)
  .use(i18nextMiddleware.LanguageDetector)
  .init({
    backend: {
      loadPath: path.join(__dirname + '/locales/{{lng}}.json'),
      addPath: __dirname + '/locales/{{lng}}.missing.json'
    },
    detection: {
      order: ['path','cookie','querystring'],
      caches: ['cookie']
    },
    fallbackLng: {
      'zh-hans': ['zh-Hans'],
      'zh': ['zh'],
      'default': ['en']
    },
    preload: ['en', 'zh-Hans'],
    saveMissing: true,
    debug: true
  },(err, t) => {
    if(err){
        console.error(err);
        throw new Error(err);
    }
  });
```

**Comment by jamuhl** [comment]
zh will be tried to be loaded as a locale inheritance from eg zh-Hans --- like for `de-DE` it will also try to load `de``

nothing to worry - those do not crash your app - just a warning - should not crash your server

**Comment by sowmiyaseshadriii** [comment]
@jamuhl  thanks is the way code correct?

**Comment by jamuhl** [comment]
if it works it is correct - if not - then not...looks correct to me...but depends on your overall server setup....

**Comment by sowmiyaseshadriii** [comment]
okay thanks @jamuhl

**Comment by b-asaf** [comment]
Hi @sowmiyaseshadriii,
I am encountering the same issue - the resources are not found in production, only in development mode I can see the translations.
I am also using webpack 4.
```
backend: {
  loadPath: `${config.rootUrl}../lang/{{lng}}/{{ns}}.json`,
},
```

The resources files are located in:
`public/lang/en/....json`
and I see them
in the production in the folder:
`lang/en/....json`
But it does not look for them over there :(

**Comment by jamuhl** [comment]
@b-asaf there is a difference in - I can see the files on filesystem - and the browser can load them - does your server expose those files? can you type the root to them and those JSON files show up?

**Comment by b-asaf** [comment]
the location of the resources is:
`projectName\public\lang\en\XXX.json`

the location in production is:
`/inetput/wwwroot/XXXstaticContent\lang\en\XXX.json`

**Comment by jamuhl** [comment]
@b-asaf nothing to do where the files are...the path must be reachable from browser...not filesystem

**Comment by b-asaf** [comment]
this is the error I see in the browser:
![browserError](https://user-images.githubusercontent.com/28925534/62860174-fe470a00-bd07-11e9-8829-0e85a59c5da6.JPG)

**Comment by jamuhl** [comment]
holy moly...how to get you to understand...it's not an issue of your i18n config...it's your server not hosting the JSONs...

**Comment by b-asaf** [comment]
I will check my server...thanks for the help

**Comment by G07cha** [comment]
To anyone else who finds this ticket looking for a solution for Next.js, I just had to import `path` and add `localePath` prop to config in `next-i18next.config.js` file:

```js
localePath: path.resolve('./public/locales')
```

This will correctly resolve the path to locale folder in environments like Vercel.

**Comment by bmclive305** [comment]
> To anyone else who finds this ticket looking for a solution for Next.js, I just had to import `path` and add `localePath` prop to config in `next-i18next.config.js` file:
> 
> ```js
> localePath: path.resolve('./public/locales')
> ```
> 
> This will correctly resolve the path to locale folder in environments like Vercel.

After 2 days this was best solution. Thank you!
