### ISSUE TITLE
Falling back through language detectors

### ISSUE THREAD

**Issue by andrewtcymmer** [i18next/i18next#1276]
I'm trying to write an app that uses both browser language detection and a custom language detector that queries Redux state. The desired behavior is to run the browser language detector first, then the custom detector, so that if the custom (second) detector does not find a setting in redux state then it the result of the browser (first) detector is used. The observed behavior is that I am seeing i18next think its language setting is now `undefined` when I expected it to be the result from the previous language detector plugin.

Note that once I log into my app and have the part of redux state I expect from the user, this works as expected. After logging out, when on unauthenticated routes, is where the trouble is. I would rather not split my single i18n configuration into two if it can be avoided. If there is another recommended way to do this by design, I would gladly take your suggestions.

Here's the relevant code:

```
import i18next from 'i18next';
import { initReactI18next } from 'react-i18next';
import LngDetector from 'i18next-browser-languagedetector';
import get from 'lodash.get';

let reduxStore;
// Note: this is called in another part of the app immediately after creating the redux store.
export function connectTranslationsToRedux(store) {
  reduxStore = store;
}

const ReduxLangDetector = {
  type: 'languageDetector',
  name: 'redux',
  async: false,
  init: (services, detectorOptions, i18nextOptions) => {
    const { order } = detectorOptions;
    order.push('redux');
  },
  detect: () => {
    let languagePref;
    if (reduxStore && reduxStore.getState) {
      const currentState = reduxStore.getState();
      return get(currentState, ['login', 'user', 'languagePreference']);
    }
    // else return undefined
  },
  cacheUserLanguage: () => {},
};

i18next
  .use(LngDetector)
  .use(ReduxLangDetector)
  .init({
    // ...
    detection: {
      order: ['navigator', 'redux'],
    },
  });
```

A screenshot of the warning I see in the console is attached. The text is `react-i18next:: i18n.languages were undefined or empty`.
![Screen Shot 2019-07-08 at 5 24 52 PM](https://user-images.githubusercontent.com/29125201/60843688-5fc60700-a1a5-11e9-8aec-6a2e4fd65a60.png)

**Comment by jamuhl** [comment]
The issue is you can only use one language detector plugin!!! so `.use(ReduxLangDetector)` will overwrite the `.use(LngDetector)` and only the one from redux is used.

Just use the browser language detector and add an additional lookup for redux: https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality

**Comment by andrewtcymmer** [comment]
Thank you for your prompt response. I have the detection working the way I want now, by following the segment of the manual in the link you posted. Closing this issue - thanks again!
