### ISSUE TITLE
Arabic variables order in dir=rtl

### ISSUE THREAD

**Issue by alexandru-tomescu** [i18next/i18next#1277]
Hi. 

First of all thank you for this great package, it suits most of our needs. However we are having some issues with the order of words (variables) of translated result string in arabic, when rtl on html is enabled. (when we are changing the language, we are setting the direction of that language on html also). We are declaring `{{var}} word2 word1`, but in the DOM we see `word2 word1 {{var}}`. Probably you already know of this problem. Can you help us ? 

Thank you

**Comment by jamuhl** [comment]
not sure but isn't that the sense of rtl support? to change the order from ltr to rtl...actually I got no idea...never had to support rtl languages myself yet.

**Comment by alexandru-tomescu** [comment]
@jamuhl the  library itself does the job well. I tried a post processor, and i can see the result to be rendered on the DOM seems to be fine. But if html has attribute dir = rtl then on the DOM the result si not correct...

**Comment by jamuhl** [comment]
are you using english texts or arabic to test? if I remember makes a difference - but not sure

**Comment by alexandru-tomescu** [comment]
well... we have 2 jsons: english ,with english text and arabic with arabic text

**Comment by alexandru-tomescu** [comment]
but the variables are in different order for arabic, of course.

**Comment by jamuhl** [comment]
Honestly not easy for me to assist...as it's very hard to say where the problem is -> If you got an idea and a fix for the situation I would gladly add something to i18next...

**Comment by alexandru-tomescu** [comment]
sure, we will investigate more on this and i will return here to post the conclusions if we will find positive ones

**Comment by jamuhl** [comment]
closing due inactivity
