### ISSUE TITLE
Why is the key with context not picking up the translation from json file

### ISSUE THREAD

**Issue by sindhuanamal** [i18next/i18next#1278]
Hi, i am translating a string say
<div>{t('zoom', context: 'icon name')}</div>

and in the transaltion.json i have it as
"zoom context:icon name": "sometranslation"

Now when i switch the language i dont see the "sometranslation" applied to zoom? but if i remove manually the context from key it gets applied meaning below works
"zoom": "sometranslation"

this is my i18n.js file
import i18n from 'i18next';
import Backend from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

const fallbackLng = ['en'];
const availableLanguages = ['en', 'fi'];

export const languages = [
    {
        'name': 'English',
        'twc_code': 'en_US',
        'i18next_code': 'en',
    },
    {
        'name': 'finnish',
        'twc_code': 'fi',
        'i18next_code': 'fi',
    },
    {
        'name': 'Swedish',
        'twc_code': 'sv',
        'i18next_code': 'sv',
    },
];

i18n
    .use(Backend)
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
        backend: {loadPath: '/static/locales/{{lng}}/{{ns}}.json'},
        caches: [],
        fallbackLng,
        debug: false,
        nsSeparator: false,
        keySeparator: false,
        whitelist: availableLanguages,
        nonExplicitWhitelist: true,
        interpolation: {
            escapeValue: false,
        },
    });

export default i18n;

Could you please let me know what's causing the problem

**Comment by jamuhl** [comment]
do you read documentations? https://www.i18next.com/translation-function/context

`"zoom context_icon name": "sometranslation"`

**Comment by sindhuanamal** [comment]
hmm got it now seems like i  have the context scanned differently from scanner. will fix it there. thanks.

**Comment by sindhuanamal** [comment]
Sorry to reopen this issue. but i did not get it to working.
i have the string 
<div>{t('zoom', {context: 'icon name'})}</div>
so this creates two keys namely
"zoom": "without context",
"zoom_icon name": "with context",

now if i remove this key "zoom_icon name": "with context",  within json file the string still gets translated with key "zoom": "without context" 

shouldn't this be the case?
i was expecting it not to translate it with "without context" string.

Thanks.

**Comment by jamuhl** [comment]
not sure what you understand under context (it's the same as select in messageformat)

not finding the key with given context it will fallback to the key not having the context...that's the sense of it...else just use no context but the key directly

**Comment by sindhuanamal** [comment]
okay.
