### ISSUE TITLE
store using Redis?

### ISSUE THREAD

**Issue by ubreddy** [i18next/i18next#1279]
I am using i18next on server side and the number of resources scale quite high... is it possible to not use inmemory store of i18next and use something like redis instead for keeping the sources by lang and namespace.

My namespaces can easily get into thousands...
Currently I see very little documentation around it.

**Comment by jamuhl** [comment]
no...you can load them from redis - but will always keep the translation in memory after loading...

think about how to load/unload that data on each request - not sure if that is better - and redis does nothing different...will cache loaded stuff also in memory...only dumbs to fs

**Comment by ubreddy** [comment]
ok. thank you. will think of alternate solution.
