### ISSUE TITLE
 data-i18n place holder show blank till change language 

### ISSUE THREAD

**Issue by starking8b** [i18next/i18next#1280]
I worked on  data-i18n to translate my web page, I want to thank you for a great helpful tool, but my problem is placeholder not show the text till I change the language 
`<input type="text" name="name" id="name" class="name active translate-text"   data-i18n="[placeholder]name"`>
I am using the resources file to tranlsate the items.
when I open my web page the placeholder not show the text it is just blank , but when I change the language it show the translation successfully

**Comment by jamuhl** [comment]
timing issue...do you translate the content before loaded transaltions? -> set debug: true on init and check if init done logs before or after you render translations -> if before call your translate UI function in the init callback or Promise...
