### ISSUE TITLE
How to use it in vue to auto update?

### ISSUE THREAD

**Issue by qq240814476** [i18next/i18next#1283]
# In Vue

 when language changed, I need refresh Vue page to update,but how to auto update it?

**Comment by jamuhl** [comment]
Not sure for vue - in react-i18next we got higher order components doing this.

You might ask over here: https://github.com/panter/vue-i18next they for sure have more vue knowhow than me...

**Comment by bodograumann** [comment]
I am using `@panter/vue-i18next` and everything is automatically updated after changing the language. Not sure if this is intended or just coincidental.

**Comment by jamuhl** [comment]
better use the issues on the `@panter/vue-i18next` for questions regarding it...
