### ISSUE TITLE
feat: Declare compatibilityJSON (JSON Schema version) as data in json itself

### ISSUE THREAD

**Issue by rhofer** [i18next/i18next#1284]
# Situation

According [json-format](https://www.i18next.com/misc/json-format) , the json schema version is decleared in code, within `i18next.init()` and not in the json itself. By connecting this translation resource (json) to a translation tool as [weblate](https://github.com/WeblateOrg/weblate), this tool only imports the json itself and does not build any relation to the code. Hence, from a translation tool perspective, it is hardly possible to smoothly figuring out which i18next json schema is in use.

# Request

Request to include the json schema version as part of the schema definition and hence as data in the json itself (may results in i18next JSON v4), for example to set at the file's beginning:

```json
{
   "i18next": {
      "compatibilityJSON": "v3"
   },


}
```

# Benefits
- translation tools to smoothly detect schema version and hence doing import/export correct and automatic
- allows for file based (stand allone) schema validation, e.g. as plug-in support during coding in your preferred code editor as visual studio code, atom, et.al.

**Comment by jamuhl** [comment]
Nothing against this...just how should this happen. The JSON files are external to i18next -> they get uploaded directly to translation tools - so only way to achieve this would be to reject files that do not contain such a definition.

Further devs can still independent of JSON schema version change interpolation, nesting prefix/suffix. Even toggle plurals to always use the index numbers instead of _plural.

This configuration variety is a legacy of i18next - starting with i18next that was a successfactor as devs could reconfigure it to match their preferred style. Nowadays hopefully most use the defaults with v3.

**Comment by rhofer** [comment]
**Translation Tool Import**
Not necessarily. Assuming importer has specified `i18next json format` it should anyways run cascading checks, as:
1. is it a JSON at all: yes -> import; no -> reject/complain
1.  i18next schema version unclear, e.g. import with latest schema (or latest implemented schema)
    - assuming v1 applies, but importer expects v3 (or vice versa), something like `key_plural_1` would be imported as a simple, self standing key. It won't be detected as belonging to a "plural bundle". Not nice, but still tool wouldn't crash and it still would be somehow translatable. (Remark: when connecting a new SW project to e.g. weblate, this is something I usually check manually in translation tool ui, how the strings are represented there.)
    - assuming v3 applies to file and importer, this should end up (close to) prefect.

From this point of view, if schema version is decleared in file, the importer/exporter rules can be detected and set automatically. Otherwise, either guess (automatic) or delegate to user to pick the right version.

**Interpolation, nesting, prefixes/suffixes**
A translation tool anyways need to expose something like `"keyInterpolate": "replace this {{value}}"` unchanged to the translator. Translator must know that something like `{{value}}` or `%d` etc. is a variable to be taken over into target, unchanged. Same for nesting as `"keyNesting": "reuse $t(keyDeep.inner)"`.
However the developer decides for what syntax is presenting prefix/suffix for a specific case, it must made clear to the translator in any case that this is a programmatic part and nothing to be translated.

**toggle plurals index**
I wasn't aware of this (since I didn't find it in documentation). That adds another level of granularity, means indication of "v3" simply isn't sufficient since variants/flavors are possible. This might even requires something like:
```json
{
   "i18next": {
      "compatibilityJSON": "v3",
      "togglePluralsToAlwaysUseIndex": "true" or "false"
   },


}
```
And in my opinion, the more variability within a certain version is possible, the more urgent it is to have it kind of self contained defined within / along the data.

**Question**: is there even more variability possible?

**legacy**
Generally is a burden, I know it well enough 😉 , therefore this declaration (assuming introduced with v4) should be backwards compatible from i18next perspective, but allow better/more automated handling in translation tools. For example, i18next in the next version could read out these parameters from the json, but still allow to overwrite them in e.g. `i18next.init()` and/or even requires this setting in case the json doesn't have it at all.
Corner cases: what happens (today) if
- i18next core used (old version), doesn't know about v3 but `"compatibilityJSON"` is decleared as `"v3"` and according json fulfils v3?
- `"compatibilityJSON"` has been forgotten and isn't set at all?

**Comment by jamuhl** [comment]
this has one wrong assumption -> that we do something with those json when imported...that is not the case -> so there is no internal format that all v1 to v3 get converted to. All is done during runtime either when creating keys to lookup based on `key` and `count` or when creating the regex for interpolation.

Did you already had cases were customers requested support for v1/v2?

**Comment by jamuhl** [comment]
closing due inactivity
