### ISSUE TITLE
Flashing keys before translations finished  loading

### ISSUE THREAD

**Issue by gloompi** [i18next/i18next#1285]
Hello!
After I migrated to hooks and updated library to 10th version, it started flashing keys.
Before open this issue, I looked everywhere for solution and found only similar issues opened for SSR app.

Here is short video, that shows what is going wrong:
![Screen Recording 2019-07-18 at 8 10 23 PM](https://user-images.githubusercontent.com/20446664/61468494-f8cbfd80-a9af-11e9-85a0-b77390779989.gif)

My i18next config:
<img width="784" alt="Screen Shot 2019-07-18 at 11 02 21 PM" src="https://user-images.githubusercontent.com/20446664/61468760-9a534f00-a9b0-11e9-9816-64611c4a64cb.png">

It is how I included it in index file
<img width="784" alt="Screen Shot 2019-07-18 at 11 03 01 PM" src="https://user-images.githubusercontent.com/20446664/61468775-a2ab8a00-a9b0-11e9-9575-d5b809ca8bb1.png">

It is how my translations are contained
<img width="194" alt="Screen Shot 2019-07-18 at 11 05 21 PM" src="https://user-images.githubusercontent.com/20446664/61469166-4d23ad00-a9b1-11e9-91e1-cd624b537988.png">

And I'm transforming them to json
<img width="537" alt="Screen Shot 2019-07-18 at 11 05 38 PM" src="https://user-images.githubusercontent.com/20446664/61469326-8b20d100-a9b1-11e9-8ac5-bf16d7270cff.png">

Here how I'm using them
<img width="784" alt="Screen Shot 2019-07-18 at 11 04 21 PM" src="https://user-images.githubusercontent.com/20446664/61469371-a55aaf00-a9b1-11e9-922b-bec2128dfbdb.png">

**Comment by jamuhl** [comment]
v10 uses Suspense to show loading state - while v9 used a render `null` until loaded

-> you set useSuspense to false ->> therefore it's up to you to handle not ready states: https://react.i18next.com/latest/usetranslation-hook#not-using-suspense

**Comment by gloompi** [comment]
@jamuhl thank you a lot! it solved my problem 😊
