### ISSUE TITLE
something wrong in function getScriptPartFromCode of LanguageUtil 

### ISSUE THREAD

**Issue by huanglijiao** [i18next/i18next#1289]
```
getScriptPartFromCode(code) {
    if (!code || code.indexOf('-') < 0) return null;

    const p = code.split('-');
    if (p.length === 2) return null;
    p.pop();
    return this.formatLanguageCode(p.join('-'));
  }
```

according to https://www.iana.org/assignments/language-tags/language-tags.xhtml#language-tags-1,  format as:  language-script-region-variant-extension-privateuse

then if p.length === 2, should it return this.formatLanguageCode(code) ?

**Comment by adrai** [comment]
why do you think so?
Btw. tags are obsolete

**Comment by jamuhl** [comment]
I don't know if you know what that function is used for?

if locale = `zh-Hant-CN` it extracts `zh-Hant` which gets added to the lookup for languages. So the function does what it is meant to do...

**Comment by huanglijiao** [comment]
I know if locale = zh-Hant-CN it extracts zh-Hant. but if locale=zh-Hant, it return null?

**Comment by jamuhl** [comment]
check the usage -> https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L103 if your locale is already zh-Hant it was already added to resolve hierarchy which was used to lookup your keys...if you use that function as a public API that's not the intention of it...

**Comment by huanglijiao** [comment]
Thanks! I got it!
