### ISSUE TITLE
Nesting with parameters

### ISSUE THREAD

**Issue by Euophrys** [i18next/i18next#1290]
Hello. In order to have my translations dynamically update, I need to nest them, but I keep getting parsing errors no matter what I try. Here's an example call and the translation lines:

```let result = t(`history.verbose.discard`, {tile: '$t(shuupai, {"value": "$t(values.six)", "suit": "$t(suits.characters)"})'});```

```
values: {
            six: "six"
        },
        suits: {
            characters: "characters"
        },
        shuupai: "{{value}} of {{suit}}"
},
history: {
            verbose: {
                discard: "You chose to discard the {{tile}}, which",
```

This ends up coming out as `You chose to discard the of ", "suit": "characters"}), which` and giving the error `i18next::interpolator: failed parsing options string in nesting for key shuupai SyntaxError: "JSON.parse: unterminated string at line 1 column 26 of the JSON data"`. Trying `JSON.parse('{"value": "$t(values.six)", "suit": "$t(suits.characters)"}')` works fine so I assume the string manipulation is doing something strange.

What's the correct way to do this? Looking at [issue 842](https://github.com/i18next/i18next/issues/842) leads me to believe this should be possible...

**Comment by jamuhl** [comment]
Idk...not even understand what you try...but looks doing something too complicated in concatenating things together -> which will result in not working in translations most time anyway as you fix how a sentence is build up...

**Comment by lstarky** [comment]
Try changing " to ' for the JSON key strings.  I don't know for sure if this will fix your error but it might.

let result = t(`history.verbose.discard`, {tile: '$t(shuupai, {'value': "$t(values.six)", 'suit': "$t(suits.characters)"})'});
