### ISSUE TITLE
saveMissing #i18next #saveMissingTo 

### ISSUE THREAD

**Issue by vand07** [i18next/i18next#1292]
I was trying to save the missing keys . i have given the following options

{
fallbackLng: false,
 saveMissing: true,
 saveMissingTo: 'current'} 
It throws an error  Cant post to http://localhost:3000/locales/add/en/translation.

I tried giving a path where i have a blank JSON file to save the missing keys.
addPath: '/assets/locales/missing/{{lng}}.{{ns}}.json' ..Now it complains saying the that it cant post to the path http://localhost:3000/assets/locales/missing/fr.translation.json(eventhough file is there.)What am i missing?..Please help me understand.

**Comment by adrai** [comment]
Do you have more details? What’s the exact error?
How does your setup look like?
Do you have an example repo?

**Comment by jamuhl** [comment]
save missing needs a real endpoint to post data to - not some webpack file in a folder...

**Comment by vand07** [comment]
@adrai 
Hi..This is a simple project..Where i have the init options as 
export function i18nInit() {
    return i18next
        .use(i18nextXHRBackend)
        .use(i18nextBrowserLanguageDetector)
        .init({
            debug: true,
            whitelist: ['en', 'fr],
            backend: {
                loadPath: '/assets/locales/{{lng}}.{{ns}}.json',
            },
        });
}
 en.translation.json
{
    "msg": "Hello World"
  }
  
My translation
const translateValue = i18next.t('msg');

I want to save the missing key somewhere...eg:suppose if i am missing the key "msg" from my json.
so i tried 
{
fallbackLng: false,
saveMissing: true,
saveMissingTo: 'current'}

then it shows in the console
 Cant post to http://localhost:3000/locales/add/en/translation.

I tried giving a path where i have a blank JSON file to save the missing keys.
addPath: '/assets/locales/missing/{{lng}}.{{ns}}.json' ..Now it complains saying the that it cant post to the path http://localhost:3000/assets/locales/missing/fr.translation.json(eventhough file is there.)What am i missing?..Please help me understand.

**Comment by vand07** [comment]
> save missing needs a real endpoint to post data to - not some webpack file in a folder...

ohh..how can i do that?thnaks for the reply..pls help

**Comment by jamuhl** [comment]
Spinning up a "real" server - even if a local one...eg. an express server (using i18next-express-middleware).

Or give https://locize.com a try...replacing xhr backend with i18next-locize-backend

**Comment by vand07** [comment]
> Spinning up a "real" server - even if a local one...eg. an express server (using i18next-express-middleware).
> 
> Or give https://locize.com a try...replacing xhr backend with i18next-locize-backend
Thanks man :).Appreciate it
