### ISSUE TITLE
Translate template literals

### ISSUE THREAD

**Issue by nithinM** [i18next/i18next#1293]
Hi Team,
I'm wondering is that possible to translate ES6 template literals using i18next. 
Please share me some sample if it's possible.

Thank you

Example
```
let name = 'Bob';
let amount = 100;
const myText = i18next.t(`Hello ${name}, you have ${amount}:c(CAD) in your bank account.`);
```

**Comment by jamuhl** [comment]
Works not that way...you build a key `Hello Bob, you have 100 in your bank account.` so correct is:

`const myText = i18next.t('Hello {{name}}, you have {{amount, currencyCAD}} in your bank account.', { name, amount });``

- https://www.i18next.com/translation-function/interpolation#basic
- https://www.i18next.com/translation-function/formatting

**Comment by nithinM** [comment]
Hi @jamuhl ,

Thanks for the reply. It's work for me.
