### ISSUE TITLE
TypeScript use plugin issue

### ISSUE THREAD

**Issue by Kamahl19** [i18next/i18next#1294]
After updating to 17.0.7, TS does not build due to this error

```
Argument of type 'typeof I18NextXhrBackend' is not assignable to parameter of type 'BackendModule | LoggerModule | LanguageDetectorModule | LanguageDetectorAsyncModule | I18nFormatModule | ThirdPartyModule[]'.
  Type 'typeof I18NextXhrBackend' is missing the following properties from type 'ThirdPartyModule[]': pop, push, concat, join, and 27 more.  TS2345
```

The same happens if I use i18next-react

```
Argument of type '{ type: string; init(instance: i18n): void; }' is not assignable to parameter of type 'BackendModule | LoggerModule | LanguageDetectorModule | LanguageDetectorAsyncModule | I18nFormatModule | ThirdPartyModule[]'.
  Type '{ type: string; init(instance: i18n): void; }' is missing the following properties from type 'LanguageDetectorAsyncModule': async, detect, cacheUserLanguagets(2345)
```

Always the first used plugin throws an errors

**Comment by heavenshell** [comment]
I've got same error at using `i18next-browser-languagedetector`. 

Reproducable code is here.
https://codesandbox.io/s/blissful-star-3hyf0

```
TS2345: Argument of type 'typeof I18nextBrowserLanguageDetector' is not assignable to parameter of type 'BackendModule | LanguageDetectorModule | LanguageDetectorAsyncModule | LoggerModule | I18nFormatModule | ThirdPartyModule[]'.         
  Type 'typeof I18nextBrowserLanguageDetector' is missing the following properties from type 'ThirdPartyModule[]': pop, push, concat, join, and 25 more.       
Version: typescript 3.5.3
```

**Comment by eiskalteschatten** [comment]
I have this error too.

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/pull/1291

**Comment by gencer** [comment]
Hit the same issue. Downgraded to `17.0.6` until this fixed.

**Comment by rosskevin** [comment]
This is a consequence of locking down the modules from `use(any)` to use one of the defined module types.

I'm starting to reconcile where changes need to be made...here or in the other projects (or both).

**Comment by rosskevin** [comment]
i18next-xhr-backend was incorrect, but also required type fixes here in #1296 as well.  https://github.com/i18next/i18next-xhr-backend/pull/319

**Comment by rosskevin** [comment]
i18next-browser-languageDetector also had some errors, and errors here https://github.com/i18next/i18next-browser-languageDetector/pull/180

**Comment by rosskevin** [comment]
react-i18next was also incorrect https://github.com/i18next/react-i18next/pull/912

PRs are up, it will be a cascading set of releases.

**Comment by rosskevin** [comment]
Note the checklist in #1296 - this and all of the cascading PRs must be merged and released before attempting to update your package.json to get the fixes.  It should be 17.0.8 here.

**Comment by Mcat12** [comment]
@rosskevin Why was this not released as a breaking change? It is clearly not backwards compatible.

I still see this TS error after updating all components.

**Comment by rosskevin** [comment]
@Mcat12 because this project is not responsible for every downstream project's use, correct or incorrect as they may be.

This release tightened types, which is correct, and the downstream projects were incorrect and updated simultaneously by me, a volunteer who doesn't even use all of those projects.

**Comment by Kamahl19** [comment]
@rosskevin thanks for fixing it, you are doing great job :)

IMHO in this case semver required a version bump. Any change that might break something eg. type tightening of the public API, even if it's fixing a bug, requires a proper version bump. When you create a library, you cant think of all other projects using it, but you must stick to your current API, however wrong it is, until you bump major version. In case of TS, types are part of the API. Maybe I am wrong, I am not an semver expert, but thats how i think it should work to keep things stable. 

I am still experiencing an issue with XHR module. Am I doing something wrong? https://github.com/i18next/i18next-xhr-backend/pull/319#issuecomment-517946389

**Comment by rosskevin** [comment]
This public API did not change, it was more accurately expressed in the types hence no major version bump. It did not break the runtime and if the downstream was actually using the previously defined module types, it wouldn't break anything. As you see, the downstream project's types were incorrect, which is not the concern of this project.

If you have a problem with that project, you should file an issue there, or better yet a PR to a test that proves your problem. As I left it, tests there pass with this version of i18next. If that is not the case, again, it is an issue for that project not this one.

**Comment by gencer** [comment]
Prpbme is, on that repo and in typescript test, you used init. Not `i18n.use`. This is a sample for this case:

```
import i18n from "i18next"
import Backend from "i18next-xhr-backend"
import { initReactI18next } from "react-i18next"

i18n
  .use(Backend) // Error here
  .use(initReactI18next) // If you remove above, error will be here...
  .init({
    fallbackLng: "en",
    debug: false,
    ns: ["translations"],
    defaultNS: "translations",
    keySeparator: ".", // we use content as keys
    interpolation: {
      escapeValue: false,
    },
    react: {
      bindI18n: "languageChanged",
      transEmptyNodeValue: "",
      useSuspense: false,
    },
    backend: {
      loadPath: "/locales/{{lng}}/{{ns}}.json",
    },
  })

export default i18n
```

Upgraded both extensions. Not working.

**Comment by gencer** [comment]
With latest commits it works now.

Thanks!
