### ISSUE TITLE
Have Trans ICU macro support defaults for eslint/prettier compatibility

### ISSUE THREAD

**Issue by redbugz** [i18next/i18next#1295]
We are trying to use i18next with ICU message format. Our existing setup uses eslint and prettier, but they are not happy using the Trans macro:

```jsx
import { Trans } from 'react-i18next/icu.macro'

const Link = ({children, to}) => (<a href={to}>{children}</a>)

const Demo = () => (
  <Trans i18nKey="test">
    Trainers: <Link to='/trainers'>{ trainersCount, number }</Link>
  </Trans>
)
```
ESLint complains that `{ trainersCount, number}` is an invalid use of a sequence, and prettier reformats it to `{(trainersCount, number)}` and then we get errors that `number` is not defined.

I thought perhaps that we could get around using invalid JSX syntax by using the `defaults` attribute for the expression, but this is not currently supported (using the Trans macro without children throws an error). I would be willing to create a PR to add this support if it is considered a good idea:
```jsx
import { Trans } from 'react-i18next/icu.macro'

const Link = ({children, to}) => (<a href={to}>{children}</a>)

const Demo = () => (
  <Trans 
    i18nKey="test"
    defaults="Trainers: <Link to='/trainers'>{ trainersCount, number }</Link></Trans>"
  />
)
```
This would transform/replace the `defaults` attribute with the proper `defaults` and `components` parsed expressions if there are no children.

```jsx
import { Trans } from 'react-i18next'

const Link = ({children, to}) => (<a href={to}>{children}</a>)

const Demo = () => (
  <Trans i18nKey="test" 
    defaults="Trainers: <0>{trainersCount, number}</0>" 
    components={[<Link to='/trainers'>{(trainersCount)}</Link>]} 
    values={{ trainersCount }}
  />
)
```

Another alternative could be to create custom components or babel macros like `<DateFormat />` and `<NumberFormat />` to replace the ICU expressions with components to keep ESLint, prettier, and other code parsing tools happy.

And obviously we can just put the ICU strings in the json files ourselves and not use `defaults` or the macro, but we've come to like having the text in the component instead of just the key.

What would be the suggested solution/best practice in this case? I am willing to help build the solution if that is helpful. I've looked at the Trans macro code and tests and I think I understand it well enough to make a PR.

**Comment by jamuhl** [comment]
Sure a PR would be accepted...currently I think the suggestion of allowing default might be the best option...

Adding `<DateFormat />` and `<NumberFormat />` could be added too - really open to this - not using this myself so hard to say what people use / would love to use.
