### ISSUE TITLE
T doesn't work properly when have ':' in your key! for example with dates!

### ISSUE THREAD

**Issue by mohsen89z** [i18next/i18next#1299]
When I use t function with a key that contains `:`, I get the after parts of the `:`.
So whenever I try to translate something like a date I get the following result:
`t('05 July 2019 10:07') //=> "07"`
Currently, I'm trying to translate with the following trick, But I would love to have a better solution!
`t('default:'+date)`

**Comment by jamuhl** [comment]
`:` is used to split namespace from key => `i18next.t('ns:key')`

you can set `nsSeparator` to `false` if you do not need it: https://www.i18next.com/overview/configuration-options#misc

in general: https://www.i18next.com/translation-function/essentials#accessing-keys-in-different-namespaces
