### ISSUE TITLE
Encoding special characters (accent)

### ISSUE THREAD

**Issue by Jeelig** [i18next/i18next#13]
Hi, I'm a new user. 
I have an issue with special characters, I can't display them correctly in my page.
Here is what i got in my json (fr-FR) file :

{
    "app": {
      "name": "i18n",
       "welcome": "Bienvenus à tous"
    }
}

When the text is displayed, the accent is not shown as it should be.
I tried to change the "à" with "&agrave;" but it doesn't solve the problem.
Anyone know what I can do ti make it work?

**Comment by PhaedrusTheGreek** [comment]
My Translation.json file was somehow messed up.  I copied and pasted the text into another file and resaved it, and it was fine.  Originally I edited the file in eclipse, but i switched to notepad++

**Comment by thananhtuan2011** [comment]
12313 đây là commment

**Comment by anabeatrizzz** [comment]
Hello,
For me, translation only occurs when the JSON key doesn't have a special character (í, ê, ã, etc).
I already have `<meta charset="UTF-8">` in my HTML and saved the JSON file with encoding UTF-8 (I'm using Sublime Text).

**Comment by gtusar** [comment]
This happend to me when I created a file in Visual Studio. The translations on page had � inside.
I opened the same file with Visual Studio **Code**, I saw the � chars there also. I replaced the texts and saved a file which solved my issue.
