### ISSUE TITLE
fallbackLng behaviour proposal

### ISSUE THREAD

**Issue by tomma5o** [i18next/i18next#1302]
Hi ✋,
In my company (and many others) we use a tool for manage i18next translations,
when I create a key only in the English language the tool creates that **i18n_key** in every language with a value of empty string.

Basic example of structure
```
{
  en: {
    my_label: "Hello World"
  },
  es: {
    my_label: ""
  },
  it: {
    my_label: ""
  },
}
```

The fallbackLng check: if the **_key_** doesn't exist I fallback in the chosen language.
Is possible to add another check if the **_value_** is empty I fallback in the default language? or there are some behaviour that I haven't considered?

Thanks for your work ;)

**Comment by jamuhl** [comment]
Hm...using https://locize.com to manage translations this would not happen ;) - and you would support our work.

Anyway: https://www.i18next.com/overview/configuration-options#translation-defaults --> `returnEmptyString` option will do the trick

**Comment by tomma5o** [comment]
Thanks @jamuhl,
I’ve missed that! Is really full of feature and options i18next.

For https://locize.com need to try it, i’ve see in the Doc (yes i’ve read that ;) ) that tool
