### ISSUE TITLE
Question: How to Translate Libraries?

### ISSUE THREAD

**Issue by bodograumann** [i18next/i18next#1303]
Unfortunately I could not find any information about this in the documentation. Hopefully you can help me here. (Or is there some other support forum / chat?)

I am translating a vue application using `i18n` and `@panter/vue-i18n`. Some of the texts I would have to translate are inside separate npm packages. (In order to be used by multiple applications) What is the best approach to translate these texts?

I’m especially interested in whether there are existing best-practices or any tools to help.

1. Is it possible to make the translation optional, so that existing applications can use the library as-is? My guess is, that I would have to always translate and simply use the current language as default. That would be an unfortunate overhead for all the applications that would normally not need to include `i18next`.
2. The solution I currently have in mind, would mean importing `i18next` in the library and calling `init` on it. Is it ok to call `init` multiple times, i.e. once in each of the libraries without parameters and once in the main applications with all the necessary options? 
3. The examples did not make that clear for me, but now–looking into ways to load more translation resources: Does every translation resource have a namespace? Maybe you could add more details about the structure of the `resources` option to the [docs](https://www.i18next.com/overview/configuration-options).
4. If I first call `init()` and `addResourceBundle` from a library and later call `init({ resources: {…})` in my main application, will all the resources be present?

**Comment by jamuhl** [comment]
If your modules are rather simple - not using to much strings and no interpolation, ... needed I wouldn't use i18next. In case of modules i would go the same way as eg. moment.

1) Have a set of strings in a JSON file / JS file. Use the strings from there and add a function to set those strings. This way a consumer of your module can still load those via i18next and pass them down to your module.

Or just let them inject a `t` function which is used by your module afterwards - the default would be `k => k` just returning the key you called it with (in this case keys can be your fallback value)

2) yes you can call init multiple times - but that might overwrite settings that should be different. even more passing in resources overwrite all resources in the store.

3/4) better use addResourceBundle - but even then - if a project calls init with resources in option your resources will be gone

**Comment by bodograumann** [comment]
Thank you, your suggestion was very helpful. The libraries concerned at the moment actually do contain only few texts.

With `i18next` present I translate using
```
text => $t(text, {
	ns: libraryNamespace,
	nsSeparator: false,
	keySeparator: false
})
```

and without it I default to `text => text`.

That way I can rely on the main application to call `init` and register the translation in the library with `addResourceBundle`.
