### ISSUE TITLE
TS: issues with import and language detector (browser)

### ISSUE THREAD

**Issue by mharj** [i18next/i18next#1304]
Seems that TS support is now someway broken. (typescript 3.5.3, i18next 17.0.9)
```typescript
import i18next from 'i18next'; 
```
asks to use allowSyntheticDefaultImports, if I change to
```typescript
import * as i18next from 'i18next'; 
```
for TS thinks it's ok except on compile  
```
export 'use' (imported as 'i18next') was not found in 'i18next'
```

Also browser detection is not really happy with TS and already throwing error on VSC "problems" tab
```
No inputs were found in config file '/node_modules/i18next-browser-languagedetector/tsconfig.json'. Specified 'include' paths were '["./indext.d.ts","./test/**/*.ts*"]' and 'exclude' paths were '[]'.
```
which probably causes language detector not to be valid type for i18next.use()
Currently this can be quick "fixed" with ```// @ts-ignore``` on i18next setup file

**Comment by rosskevin** [comment]
`allowSyntheticDefaultImports` both `false` and `true` is tested as working, see `tests/typescript` source and `npm run pretest` to see how those work and verify imports are working.  An array of tests are there, including validation of `use`.

If you can find a problem, please PR a breaking test so I can take a look and reopen.

If you have a problem with `i18next-browser-languagedetector`, please file an issue there.  In this case it looks like we should just make sure to add `tsconfig.json` to `.npmignore`

**Comment by rosskevin** [comment]
FYI I just merged cleanup of that package - it may be annoying in vscode but is not actually the source of any problem.  https://github.com/i18next/i18next-browser-languageDetector/pull/181

**Comment by mharj** [comment]
thanks!, seems that plain TS and i18next works ok, but something goes wrong in current React application. I'll do some testing later with default create react app setup.

**Comment by mharj** [comment]
```typescript
import * as i18next from "i18next";
import LanguageDetector from "i18next-browser-languagedetector";
i18next.use(LanguageDetector).init({});
```
on base React app setup will give ```Attempted import error: 'use' is not exported from 'i18next' (imported as 'i18next').```
and as with direct TS compiler this seems to works ok, so I think something is different when React using Babel to compile those, also might be reason why React created tsconfig is allowSyntheticDefaultImports: true by default

**Comment by rosskevin** [comment]
@mharj you have a local problem.  I have definitively tested interop (with both import styles), and nonInterop both here, and in https://github.com/i18next/i18next-browser-languageDetector/pull/182

Note that I added tests to that PR, everything works and required no changes.

**Comment by jjilek** [comment]
Hello, 
today, I updated to i18next@17.0.11 in one of my projects and I have same problem. This is my code:

`
import i18next from 'i18next';
import XHR from 'i18next-xhr-backend';
import {initReactI18next} from "react-i18next";

i18next.use(XHR).use(initReactI18next).init({...});

export default i18next;
`

On another project I use i18next@17.0.6 and everything works fine :-(

**Comment by rosskevin** [comment]
@jjilek there are tests in this project that prove it works.  If you find a bug, please open a PR with a breaking test and I will take a look.
