### ISSUE TITLE
Translate a backend text with client side i18n

### ISSUE THREAD

**Issue by romanogit** [i18next/i18next#1305]
I receive responses from an API that I would like to translate.

The response has an already pre-formatted text.

Sometime is says: "John won the game". Sometime is says "You have 3 cards left".

I am not worried about plurals, I can live with "1 cards left", but how can I make a generic key?

For example:
```
'\s+ won the game': '(1) ganhou o jogo'
and
`You have \d+ cards left': 'você tem (1) cartas sobrando'.
```

Is this possible. To use regexp in keys?

I am sorry if I missed this in documentation

**Comment by jamuhl** [comment]
Interpolation works like https://www.i18next.com/translation-function/interpolation and no...keys can't be in the form of regex

**Comment by romanogit** [comment]
@jamuhl ,
I don't know how to use interpolation in my example.
The thing is that the string from the backend comes ready. I cannot change it, but I want to translate at in the frontend.
I think interpolation needs a parameter being passed with the proper key/values, right?

**Comment by jamuhl** [comment]
Honestly no idea how to solve this...it's a bad idea from the backend to pass down error messages that contain dynamic values...

So only way i currently see is for every such message you got - you will have to extract the variables and create a static key.

**Comment by romanogit** [comment]
Thanks, I will work on the backend side to split the messages.

**Comment by jamuhl** [comment]
Guess this will be the best solution - at least without doing a lot of magic or hard work in the client...
