### ISSUE TITLE
Interpolation with symbols $& in inserted value gets wrong result

### ISSUE THREAD

**Issue by DmitriyMaximov** [i18next/i18next#1306]
I have same template string:
```
{
  "key": "Hello {- __text} world"
}
```
When I called 
`i18next.t("key", { "__text": "$&3432" })`

I was received this value: "Hello 343234323432...3432 world". And 3432 repeated 1000 times.
This is because in Interpolator you use the code

```
while ((match = this.regexpUnescape.exec(str))) {
      value = handleFormat(match[1].trim());
      str = str.replace(match[0], value);
```
But symbols $& is special for String.replace. See this https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter

Fix, please.

**Comment by jamuhl** [comment]
why should this be fixed? it's a wrong usage...

if that is relevant for you - feel free to provide a PR

**Comment by DmitriyMaximov** [comment]
Tell me what exactly is the wrong usage? How to call a function if these characters can be in the inserting values?

**Comment by jamuhl** [comment]
interpolating `i18next.t("key", { "__text": "$&3432" })` what should `$&3432` mean?

**Comment by DmitriyMaximov** [comment]
It is sample of user input. 
The text is inserted into the template, then rendered in the react element that encodes the value for html.
And it is expected that this value will simply be inserted in the right place, because the i18next documentation says nothing that such a combination cannot be used or that it is special symbols.

**Comment by jamuhl** [comment]
🤷‍♂️like said...if it's important to you - feel free to create a PR
