### ISSUE TITLE
Complex replacement i18n vs i18next?

### ISSUE THREAD

**Issue by ssuess** [i18next/i18next#1309]
> I posted this in the jQuery i18next repo, but think it might belong here instead

I am evaluating the differences and ease of use between jQuery i18n and i18next, and it seems that it is much less work in certain cases to translate using i18n, but perhaps I am missing something. For example, how would I write this i18n phrase:

`var phrase = $1 has $2 {{plural:$2|kitten|kittens}}. {{gender:$3|He|She}} loves to play with {{plural:$2|it|them}}.`

`$.i18n( phrase, 'john', 2, 'male');`

in i18next? What is good about this way of writing (i18n) is that the context and entire sentence is clear, but I am not sure at all how I would achieve the same contextual clarity using i18next in a single translated line with 3 variables (1 normal variable, one plural, and one gender). Can you tell me how I might achieve the same using i18next syntax?

it SEEMS like I would have to do something really convoluted like:
````
{
"phrase": "{{ nameVar }} has $t('kittenWithCount', {count: {{ kittenCount }}). t('gender', { context: {{ genderVar }} }) loves to play with $t('kittennumber', {count: {{ kittenCount }})",
"kitten": "kitten",
"kitten_plural": "kittens",
"kittenWithCount": "{{count}} kittens",
"gender_male": "he",
"gender_female": "she",
"kittennumber": "it",
"kittennumber_plural": "them"
}
````
Or am I missing something fundamental?

**Comment by jamuhl** [comment]
https://www.i18next.com/translation-function/context#combining-with-plurals

**Comment by ssuess** [comment]
Thanks for your response. But not sure how that link illuminates anything different or simpler than in my example above, perhaps I am missing something?

**Comment by jamuhl** [comment]
```js
{
      "kitty_male": "{{name}} has a kitten and he loves to play with it",
      "kitty_female": "{{name}} has a kitten and she loves to play with it",
      "kitty_male_plural": "{{name}} has {count} kittens and he loves to play with them",
      "kitty_female_plural": "{{name}} has {count} kittens and she loves to play with them"
}
```

`$.i18n.t('kitty', { name: 'John', context: 'male' });``

**Comment by ssuess** [comment]
Thanks, that helps clarify a bit.
