### ISSUE TITLE
Preprocessor plugins

### ISSUE THREAD

**Issue by xgbuils** [i18next/i18next#1311]
Hi!

I was trying to solve the problem of using special plural translations for the cases when count variable is 0. I found a solution in #45. This is my adapted solution: 

``` JavaScript
const i18next = require('i18next')

const specialZero = (count) => ({
    context: count === 0 ? 'none' : 'some',
    count
})

i18next.init({
  lng: 'en',
  resources: {
    en: {
      translation: {
        key_none: 'No items',
        key_some: '{{count}} item',
        key_some_plural: '{{count}} items'
      }
    }
  }
}, function(err, t) {
  console.log(i18next.t('key', specialZero(0))) // No items
  console.log(i18next.t('key', specialZero(1))) // 1 item
  console.log(i18next.t('key', specialZero(3))) // 3 items
});
```

However I don't feel comfortable with this solution because I have to import the `specialZero` function for each file where I need it. I read the [creating own plugins section](https://www.i18next.com/misc/creating-own-plugins) in the docs. In particular, I read postprocessor plugin section. I thought could be interesting to have preprocessor plugin types. Then, given a key and their intepolation object, new translation could be returned. The zero special pluralization is a particular use case:

``` JavaScript
{
  type: 'preProcessor',
  name: 'specialZero',
  process: function(key, interpolationObj, options, translator) {
    return translator.translate(key, {
      context: interpolationObj.count === 0 ? 'none' : 'some',
      ...interpolationObj
    });
  }
}
```

What do you thing about implementing preprocessor plugins?

Cheers!

**Comment by jamuhl** [comment]
can be solved using: https://github.com/i18next/i18next-intervalPlural-postProcessor

**Comment by jamuhl** [comment]
Not completely against a preprocessor - but just adding more to i18next that already is full of options and features...

**Comment by xgbuils** [comment]
I read about `intervalPlural-postProcessor` and it's true that we can implement special 0 case using this configuration:

```
key: '{{count}} item',
key_plural: '{{count}} items',
key_interval: '(0){No items};'
```
However I think there could be more nicer ways to apply it without poluting the original syntax of i18next (using context).

Maybe we don't need preprocessors and postprocessors. Maybe translator processors with well choosen `process` arguments could bring solutions that allows to extend the translation process in two ways: using context or adding a new syntax.

I will try to make a translation processor proposal in another issue that brings the same functionality as post processors, allows enhance translations using context and converts formatting and inperpolation in default transtation processors instead of managing a particular method `extendTranslation`.

Thanks!
