### ISSUE TITLE
missing keys on load - possible delay

### ISSUE THREAD

**Issue by nicolasvahidzein** [i18next/i18next#1312]
Hello, there are few similar issues but i don't seem to get the info i need to fix this. I am pulling missing keys on load of my app because it seems that when i18 initializes in my vue app it hasn't had time to set the language which is strange.

Any advice on this? i18 is the first module i load but still i get the missing keys message flashing.

Let me know if i can provide the code you might need. Thanks! PS this is one of my all time favorite packages, makes localization fun!!

**Comment by nicolasvahidzein** [comment]
here is my code just in case:

```
import i18next from 'i18next'
import store from '@/store/store'
import XHR from 'i18next-xhr-backend'
import { Validator } from 'vee-validate'
import moment from 'moment'

export default function (Vue) {
	
	Vue.i18nextlocalization = {
		
		initiatei18next () {
			if (store.state.traceDebug === true) { 
				console.log('initiatei18next function in i18next.js')
			}
			
			console.log('i18 $$ before setting lang and fallbacklang: ' + i18next.language)
			
			i18next
			.use(XHR)
			.init({
				lng: 'en',
				fallbackLng: 'en',
				debug: true,
				backend: {
					
					loadPath: '/localization/locales/{{lng}}/{{ns}}.json',
					allowMultiLoading: false,
					crossDomain: true,
					
				}
			
			}, function (err, t) {
				
				if (store.state.traceDebug === true) {
					console.info('i18next.language', i18next.language)
				}
				
				if (err) {
					console.log(err)
				}
				
				store.commit('changeLocale', 'en')
				
			})
			
			console.log('i18 $$ bottom of the constructor')
			
			console.log('i18 $$ before after setting lang and fallbacklang: ' + i18next.language)
			
		},
		
		listenToi18nextChanges () {
			if (store.state.traceDebug === true) { console.log('listenToi18nextChanges function in i18next.js') }
			
			i18next.on('languageChanged', () => {
			  this.updateContent()
			})
			
		},
		
		updateContent () {
			// document.getElementById('output').innerHTML = i18next.t('key')
			if (store.state.traceDebug === true) { console.log('changeLanguage function in i18next.js Language changing to: ' + i18next.language) }
			
			//change it in the store to tell everyone to update
			store.commit('changeLocale', i18next.language)
			
			//also change at the same time the vee validate locate to stay in sync
			Validator.localize(i18next.language)
			
			//change locale in moment js
			moment.locale(i18next.language)
		}
		
	}
	
	Object.defineProperties(Vue.prototype, {
		$i18nextlocalization: {
			get () {
				return Vue.i18nextlocalization
			}
		}
	})
}

```

**Comment by nicolasvahidzein** [comment]
i was reading another of your github issues and i discovered we could monitor when it was initialized. So the question i have now is how can i make my main.js wait before moving forward?

i am initializing i18 next and it takes a while to load, how do i pause main.js until i know the languages are set? Thank you sir!

**Comment by jamuhl** [comment]
every function that can trigger a load of translations (.init, .changeLanguage, loadNamespaces) has an optional callback which gets called when i18next has done loading and is ready. Alternatively, those functions also return a Promise if you prefer a Promise based API.

Not sure how things work in vue but for react we made a component that calls the loadNamespaces and while not ready renders a "loading" view...

**Comment by nicolasvahidzein** [comment]
Ok thank you Jan @jamuhl, i will have to get the help from someone more experienced then me for this. It's not a huge issue right now and it works great, will just fix it later. Cheers.

**Comment by jamuhl** [comment]
you might ask over at vue-i18next how they solved this? https://github.com/panter/vue-i18next
