### ISSUE TITLE
Interpolation defaultVariables not recognized on t()

### ISSUE THREAD

**Issue by rbeer** [i18next/i18next#1314]
Expected behavior:
Missing variables get filled by their `defaultVariables` value, when passing option to t(), as stated in the [docs](https://www.i18next.com/translation-function/interpolation#additional-options).

Actual behavior:
Variable gets replaced with empty String and warning is thrown:
`i18next::interpolator: missed to pass in variable screenName for interpolating`
Pattern matching is fine, the `screenName` variable gets detected in the `title` text, but there is no reference to passed in `options.interpolation.defaultVariables`.

Sample:
Using
```json
{
  "title": "Hello {{screenName}}!",
}
```
and calling
```js
i18next.t('title', {
  interpolation: {
    defaultVariables: {
      screenName: 'foo'
    }
  }
});
```
results in:
```
Hello !
```

Passing
```js
interpolation: { defaultVariables: { ... } }
```
to i18next.init() works fine.
Problem with that is, that I need translations for the default value, which are obviously not yet available at that time.

**Comment by jamuhl** [comment]
you're right...seems that got lost somewhere...will fix this in the next days.

**Comment by rbeer** [comment]
Very hacky, might interfere with the instanciation feature, but just setting the `defaultVariables` after init() works for me.

```js
await i18next.init({ ... });
i18next.options.interpolation.defaultVariables = {
  screenName: 'foo'
};
```

By the way: Thanks for this package! Have just played with it since yesterday, but loving it, already. :) :+1:

**Comment by jamuhl** [comment]
hm...strange...I not even see we read defaultVariables...my guess is we need to merge those again here: https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L74

instead of using data the interpolation values passed in in `t(key, { screenName: 'name' })` we should merge the defaultVariables first

**Comment by rbeer** [comment]
That's pretty much where I ended up while stepping through, earlier.
I've noticed that the options *do* reach the function, values just aren't applied.
I can give it a try, tomorrow (UTC+1). Looks simple enough.

**Comment by jamuhl** [comment]
Already late here too...let's see who's first tomorrow ;) either I will fix and publish an update or merge your PR and publish

**Comment by rbeer** [comment]
Ok, I've started with https://github.com/rbeer/i18next/commit/feb0527412e1f24c928c30cbbf771fa4b5029505

It's really ugly, though.
Test `Interpolator interpolate() - with null interpolation value - not filled by missingInterpola
tionHandler` still fails.

Is this by design? Smells a bit POLA to have `undefined` values result in `''` and `null` in `key`, to be honest.

**Comment by jamuhl** [comment]
at least you started...I had no time to look at it...hope tomorrow will be better

**Comment by jamuhl** [comment]
should be fixed in i18next@17.0.13

**Comment by rbeer** [comment]
Doesn't work.
The combined data needs to include the `options` object passed to the function, since `this.options.interpolation.defaultVariables` is `undefined`.

That's not the case in your test, because you init() the Interpolator with the option.
Guessing that does not happen, when you pass options to t() and then eventually to `interpolate`.

**Comment by jamuhl** [comment]
The interpolator gets constructed with the i18next.options : https://github.com/i18next/i18next/blob/master/src/i18next.js#L73

**Comment by rbeer** [comment]
But calling t() does not create a new Interpolator, does it?
My example, where I initialised everything without `defaultVariables`, ends up like this:
![1314-devtools](https://user-images.githubusercontent.com/3411649/63935298-6febbb80-ca5d-11e9-9e80-73bbe502fb31.png)

**Comment by jamuhl** [comment]
Why should you `t(key, { interpolation: { defaultVariables: { ...vars } } }` ?

just `t(key, { ...vars })`

**Comment by rbeer** [comment]
I was looking for a way to set the `defaultVariables` after initialization, since I need translations for default values.

So I guess to achieve that, the only option is to replace the Interpolator after calling init() or or using the direct approach: https://github.com/shadowban-eu/shadowban-eu-frontend/blob/dev/src/js/i18n.js#L30 ?

**Comment by jamuhl** [comment]
But you call it here: https://github.com/shadowban-eu/shadowban-eu-frontend/blob/dev/src/js/i18n.js#L23

so you could just add interpolation to init...but if you need to set them way later...after eg. login and you like to set defaultVariable for username...that might makes sense...and there is currently no other way than setting it the way you do it...

Honestly, I was never a fan of those defaultVariables...not sure why those are needed as how many translations need the same variables (even if you got them in 4 t calls still better to add them 4 times in the t options...)

**Comment by rbeer** [comment]
I'm just always careful with reaching into objects of 3rd-party modules. Maybe too much so. :sweat_smile: 
Also, I realized that I just shouldn't be so lazy and replace that "just loop them all" approach with some real decision making.

Thanks for the help! :)
