### ISSUE TITLE
Key manipulation

### ISSUE THREAD

**Issue by shahafan** [i18next/i18next#1315]
I'm having a language file I get from a third party api and all of the keys in it contains a constant prefix, something like:
```
{
    "prefix_word1": "Word 1",
    "prefix_word2": "Word 2"
}
```

I'm trying to avoid writing everywhere that prefix in my code and tried to figure out a way to manipulate the keys before they are being sent to the translator function and I can't seem to find the way to do it.

My goal is to be able to call `t('word1')` instead of `t('prefix_word1')`

I've managed to accomplish this using a postprocessor plugin but it feels bad because it looks for the key twice while I know it will fall on the first time.

```
{
  type   : 'postProcessor',
  name   : 'addPrefix',
  process: (value, key, options, translator) => translator.translate(`$prefix_${key}`, options),
}
```

Any better way to do it?

**Comment by jamuhl** [comment]
No...there comes nothing to my mind to solve this out of the box

**Comment by shahafan** [comment]
What do you suggest though?
Should I write a preprocessor pr?

**Comment by davezuko** [comment]
If you absolutely don't care about the prefix, then how about transforming the language file before giving it to i18n?

```js
const resource = await loadPrefixedResource()
stripPrefixes(resource)
i18next.addResourceBundle('en', 'translations', resource)

function stripPrefixes(obj) {
  for (const [key, value] of Object.entries(obj)) {
    delete obj[key]
    obj[key.replace("prefix_", "")] = value
  }
}
```

**Comment by jamuhl** [comment]
closing this for now...feel free to reopen with suggestions - currently looks this is out of the scope of this module and can be solved like shown above
