### ISSUE TITLE
Typescript import broken

### ISSUE THREAD

**Issue by Gr33nbl00d** [i18next/i18next#1316]
In version 17.0.2
import i18next from "i18next";

Worked fine now i get a compiler error:

S1259: Module '"i18next/index"' can only be default-imported using the 'esModuleInterop' flag

index.d.ts: This module is declared with using 'export = ', and can only be used with a default import when using the esModuleInterop flag

It seeems that the problem is in the last line of index.d.ts

If i remove the import and let the IDE (Webstorm) import i18next again it imports it as:
import * as i18next from "i18next";

Autocompletion in the ide works fine but in the browser i get:
Uncaught TypeError: i18next.use is not a function

**Comment by Gr33nbl00d** [comment]
Temporary workarround:

import * as i18next from "i18next";

// @ts-ignore
i18next.default.use(backend).init({

**Comment by rosskevin** [comment]
This is proven working as tested by the `pretest` script.  We test both with and without `esModuleInterop`.

Please update your dependency to the latest which at this time is 17.0.13 - you are 11 releases behind.

If you spot a problem with the tests (and related tsconfigs for interops), please PR your scenario as a breaking test so I can take a look and fix.

**Comment by whodoeshua** [comment]
This problem still come up in version `17.2.0` and temporary workarround is work for me.
