### ISSUE TITLE
bundle size is too big

### ISSUE THREAD

**Issue by zsolt-dev** [i18next/i18next#1318]
Hi,

I really like i18next, but if I will not find any way to make it smaller, I will have to switch to something else. It is taking 38kB of my bundle. 

I serve the bundle compressed, but it is still a lot of CPU cycles processing javascript. My point is that 38kB of JS !== 38kB of jpg image. 

I use only t() function, nothing more, so it seems like a low hanging fruit to remove replace i18next with something else of just my own implementation.

<img width="239" alt="i18next" src="https://user-images.githubusercontent.com/18726534/64423532-0dbb3800-d0a7-11e9-8d03-e1359fe393d5.png">

Am I doing something wrong with tree shaking?

**Comment by jamuhl** [comment]
no, you do nothing wrong with tree shaking...

**Comment by SalahAdDin** [comment]
> no, you do nothing wrong with tree shaking...


So, what's the problem the bundle size? For me, the bundle size is even bigger:
![Screenshot 2022-11-15 at 13 40 40](https://user-images.githubusercontent.com/5034215/201899231-71731834-2f1f-42c9-ade4-63509221bc3d.png)

**Comment by jamuhl** [comment]
@SalahAdDin 37.9kB was around v19 -> https://github.com/i18next/i18next/blob/master/CHANGELOG.md sadly all the patches and new features add to current size.
