### ISSUE TITLE
Is it possible to fallback all locales of a language to a single locale?

### ISSUE THREAD

**Issue by yads** [i18next/i18next#1319]
As an example, I'd like all `en-*` locales to fallback to `en-US`. Is this possible to do without listing them out? Currently I'm having to do:

```
fallbackLng: {
  'en-CA': ['en-US'],
  'en-UK': ['en-US'],
  ...
}
```

ideally I'd be able to do something like
```
fallbackLng: {
  'en': ['en-US']
}
```

So all en languages for which a translation file isn't provided, fallback to US.

**Comment by jamuhl** [comment]
`en-CA`, `en-UK`, ... already fallback to their non-regional variant `en` (which can be content in en-US)

what you would like to see in your request currently is not possible but doable:

https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L78

add something like: `if (!found) found = fallbacks[this. getLanguagePartFromCode(code)];` after the line above.

And adding a test case here for regression: https://github.com/i18next/i18next/blob/master/test/languageUtils.spec.js#L29

**Comment by yads** [comment]
I guess in theory instead of specifying a fallback, When building the resource bundle I could set `en` and `en-US` to the same bundle, that way other en locales fallback to `en` which just happens to be the same as `en-US`

**Comment by jamuhl** [comment]
@yads that's the idea

**Comment by dietergeerts** [comment]
> `en-CA`, `en-UK`, ... already fallback to their non-regional variant `en` (which can be content in en-US)
> 
> what you would like to see in your request currently is not possible but doable:
> 
> https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L78
> 
> add something like: `if (!found) found = fallbacks[this. getLanguagePartFromCode(code)];` after the line above.
> 
> And adding a test case here for regression: https://github.com/i18next/i18next/blob/master/test/languageUtils.spec.js#L29

Isn't this something that can be implemented? Imho, this is something that is common to do, no?

**Comment by jamuhl** [comment]
@dietergeerts I don't know if this is rather common...we mostly have a file `en` around which is a copy of `en-US`

https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L78 adding `f (!found) found = fallbacks[this. getLanguagePartFromCode(code)];` might be sufficient to achieve what you like...not tested - you might provide a PR for this feature if really needed by you

**Comment by dietergeerts** [comment]
> we mostly have a file en around which is a copy of en-US

Well, for use, that would need to be `en-GB`, as that's our default fallback, but `en` stands for `en-US` actually, so that's why I don't do this.

We solved it now by setting just 1 fallback to `en-GB`, and let `nl-*` fallback to the default `nl` file, which actually is `nl-NL`, and is something we want. Of course, once we need other fallbacks that aren't the default, then we'll need this feature, but in the meantime, we are fine.

So we don't need any change right now, though documentation-wise, this is not clear, hence the fact that we assumed this fallback would work, which it doesn't. So docs could be improved on this.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
