### ISSUE TITLE
URLs in documentation provide old versions

### ISSUE THREAD

**Issue by Gamadril** [i18next/i18next#1323]
The Getting Started page provides outdated links for the CDN versions of the library:

<pre>
https://unpkg.com/i18next/dist/umd/i18next.js​ => https://unpkg.com/i18next/dist/umd/i18next.js
​https://unpkg.com/i18next/dist/umd/i18next.min.js => https://unpkg.com/i18next@16.0.0/dist/umd/i18next.min.js

https://unpkg.com/i18next/dist/esm/i18next.js​ => https://unpkg.com/i18next@16.0.0/dist/esm/i18next.js
​https://unpkg.com/i18next/dist/cjs/i18next.js => https://unpkg.com/i18next@16.0.0/dist/esm/i18next.js
</pre>
After I noticed that, I understood why the minified version (unpkg.com) returned undefined when accessing i18next.language while not minified worked as expected during development.

**Comment by jamuhl** [comment]
What page are you talking about? https://www.i18next.com/overview/getting-started#load-from-cdn those links work or do i miss something?

**Comment by Gamadril** [comment]
yes, this page. Check the targets: 3 of them are pointing to the old 16.0.0 release.

**Comment by jamuhl** [comment]
should be updated now
