### ISSUE TITLE
"Cannot read property 'changeLanguage' of undefined"

### ISSUE THREAD

**Issue by rahul-nimblechapps** [i18next/i18next#1327]
the browser told me that "Cannot read property 'changeLanguage' of undefined" and then I console the i18next object,there is not changeLanguage in it !
should I load a plugin about changeLanguage?
how to fixed this problem?

**Comment by rahul-nimblechapps** [comment]
### fdsfdsfds
gfdgfdg

> 

-  @gfdg`gfdgdfgfdgfd` @ @ @ @franck34

**Comment by jamuhl** [comment]
Did you find the solution?

**Comment by jamuhl** [comment]
How do you import i18next? CDN, webpack? If webpack can you paste your i18n.js where you init i18next and export it for further usage?

**Comment by rahul-nimblechapps** [comment]
actually the reason was about this **Unknown error** I forgot to import it in my component file, so that why I got this error but now I imported it n it's working fine but now it does not translate n showing me an error like  **"t is not a function"**

**Comment by jamuhl** [comment]
How do you access `t` - looks like...you're not importing i18next and use t but use t on undefined...show more code...I can't help without seeing what you do - calling this errors is just showing you do things wrong that are basic level of javascript programming
