### ISSUE TITLE
Plurals not working with Trans component

### ISSUE THREAD

**Issue by k4r1** [i18next/i18next#1330]
When using the `<Trans />` component, the pluralisation (based on count) does not work, and in addition, count is not rendered at all.

Is there an additional option we need to pass to `<Trans />` to get it to behave properly? 

Minimal example to reproduce:

**en-gb.json**
```
"testKey": "Hello, one {{ object }} ({{ count }})",
"testKey_plural": "Hello, many {{ object }}s ({{ count }})"
```

**index.tsx**
```
<>
  <Translation>{(t) => t('testKey', { count: 1, object: 'World' })}</Translation>
  <br />
  <Translation>{(t) => t('testKey', { count: 2, object: 'World' })}</Translation>
  <br />

  <Trans i18nKey="testKey" values={{ count: 1, object: 'World' }} />
  <br />
  <Trans i18nKey="testKey" values={{ count: 2, object: 'World' }} />
  <br />
</>
```

Produces:
```
Hello, one World (1)
Hello, many Worlds (2)
Hello, one World ()
Hello, one World ()
```

Note: For the `<Trans />` component, both of them use the singular form, and in addition nothing is rendered inside the brackets at the end where we'd expect to see `count`.

**Comment by k4r1** [comment]
Version `"i18next": "^17.0.6"`

**Comment by jamuhl** [comment]
count has to be set also as a prop on Trans `<Trans count={5} ...`

**Comment by jamuhl** [comment]
as it gets set here: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L240

if you like providing a PR changing that to: `count: count || values.count`

**Comment by k4r1** [comment]
Yes I just spotted this actually, thanks for the help! I may well open a PR onto `react-i18next` to resolve, in the mean time passing the count as its own prop works.
