### ISSUE TITLE
How to set the browser languages as i18next languages

### ISSUE THREAD

**Issue by jango07** [i18next/i18next#1338]
I want to set all the languages set in my browser as the i18next languages. I have used
import Browser from 'i18next-browser-languagedetector';
i18next
.use(Browser)

Will it get all the languages set as browser languages?
How can I console and see whether it is taking my browser languages?

**Comment by jamuhl** [comment]
Did you read the readme? https://github.com/i18next/i18next-browser-languageDetector

**Comment by jamuhl** [comment]
import LanguageDetector from 'i18next-browser-languagedetector';

you import the detector not a specific detection source

you set prio by setting order array in options: https://github.com/i18next/i18next-browser-languageDetector#detector-options

**Comment by jango07** [comment]
Thanks for your reply
1. If I use this import LanguageDetector from 'i18next-browser-languagedetector';
 I will get 404 error....
I have used it like this import LanguageDetector  from '/node_modules/i18next-browser-languagedetector/dist/es/index.js'; and it works for me 
Now I get the browser language as en-US.

Is this the right approach ?Please guide me..

2. If I console navigator.languages I get en-US and es-US
But in the i18next I could see it only takes the navigator.language and not navigator.languages.
How I got to know is through the console msgs.
It loads en-US trnaslation files but not es-US files.
Appreciate any help..

**Comment by jamuhl** [comment]
the detector can only return one language by design -> so from navigator you will only get the one with highest prio.

**Comment by jango07** [comment]
Thanks for you reply.
So what if I want to set all  the browser languages ?
If suppose I have two languages en-US and es-US in the browser.
I want first priority as en-US, if it fails fetch es-US and so on...
Is there any way I could implement this?

**Comment by jamuhl** [comment]
you can set whitelist on i18next.init...so if en-US is not in the whitelist it should pick the es-US

**Comment by jango07** [comment]
I believe in white list we have to define the values.
or do you mean to set it whitelist : navigator.languages ?

**Comment by jango07** [comment]
yes...I got it..
that is my question , navigator.languages is an array of languages.
So do yu mean I need to set it to the whitelist as whitelist: navigator.languages ?

**Comment by jamuhl** [comment]
no...it's the language you provide

**Comment by jango07** [comment]
I want something which is set as browser languages :(

**Comment by jamuhl** [comment]
that's what it does:

- it detects language from navigator: https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/navigator.js#L10
- check against whitelist: https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/index.js#L73

so you say in whitelist you got languages `es-US` translated as you got that translations for es-US...the detector detects `['en-US', 'es-US']` it picks en-US as en-US is not whitelisted...
