### ISSUE TITLE
postprocessor: which language has been hit?

### ISSUE THREAD

**Issue by srischard** [i18next/i18next#1340]
hi all,

background:
I'm implementing a `postprocessor` to format my messages and I want to cache my compiled expressions

setup:
I got a set of languages and a fallback chain.
In the postprocessor `process: (value, key, options, translator)` I got a value.
In `translator` I can see the original requested `language`.

But where I can see from which language and namespace the value has been taken?

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/src/Translator.js#L100

resolved has https://github.com/i18next/i18next/blob/master/src/Translator.js#L383 -> usedLng

but that won't get passed down to postprocessor

**Comment by srischard** [comment]
it's is possible to pass this down to the postprocessor  by merging `usedLng` & `usedNS` in options
maybe in `extendTranslation`

```
  extendTranslation(res, key, options, resolved) {
    if (this.i18nFormat && this.i18nFormat.parse) {
      res = this.i18nFormat.parse(
        res,
        options,
        resolved.usedLng,
        resolved.usedNS,
        resolved.usedKey,
        { resolved },
      );
    }
   .....
      res = postProcessor.handle(postProcessorNames, res, key, options, this);
    }

    return res;
  }
```

**Comment by jamuhl** [comment]
think simplest would be changing that call to:

`res = postProcessor.handle(postProcessorNames, res, key, { ...options, resolved }, this);`

that way we do not have to change the function params...

**Comment by jamuhl** [comment]
PR would be welcome
