### ISSUE TITLE
HMR for i18next

### ISSUE THREAD

**Issue by martijnmichel** [i18next/i18next#1345]
Is this possible, or would it be possible to add this feature?

**Comment by jamuhl** [comment]
Never looked to deep into HMR for translation files -> never needed that feature as we split developing from translating...

Sure can this be added...feel free to provide a pull request.

**Comment by martijnmichel** [comment]
I have no idea on howto implement this though..

**Comment by jamuhl** [comment]
Me neither...

**Comment by felixmosh** [comment]
This thread got me inspired, so I've wrote [i18next-hmr](https://github.com/felixmosh/i18next-hmr)🔥 that works on server & client 🥳

**Comment by jamuhl** [comment]
@felixmosh mind adding a PR to add i18next-hmr to the https://www.i18next.com/overview/plugins-and-utils

**Comment by felixmosh** [comment]
I will do it after I stabilise it, currently applied it on my huge next-js app.

**Comment by felixmosh** [comment]
@jamuhl done :]
https://github.com/i18next/i18next-gitbook/pull/105

**Comment by martijnmichel** [comment]
I have a big project with translations and also .md files import from subdirectories in a quasar app.. any idea how i can make this work? because currently it isnt yet.

`
import enUS from "./en-us/translation.json";
import enUS_md from "./en-us";

import nlNL from "./nl-nl/translation.json";
import nlNL_md from "./nl-nl";

export default {
  "en-US": { translation: enUS, md: enUS_md },
  "nl-NL": { translation: nlNL, md: nlNL_md }
};`

**Comment by felixmosh** [comment]
@martijnmichel I'm not sure, but if you are importing all of your translation json files into the bundle, they should trigger updates without my plugin in.

My plugin is for a case where your are not importing any translation files, and using `xhr` / `node fs` to grub it dynamically. In this why webpack is "unaware" of changes in these files, and that what i18next-hmr solves.

**Comment by jamuhl** [comment]
@martijnmichel I currently not even understand what is not working?

**Comment by martijnmichel** [comment]
hmm.. right,.. im changing the way im using i18next to where i stop using md files but my main question (what i meant when i started this post) was is it possible to reload questions without the whole page refreshing... isnt that hmr?

Currently if i change only one letter in translation.json, everything refreshes.

**Comment by felixmosh** [comment]
i18next-hmr, when translation changes, triggers `i18next.reloadResources` to fetch the new translations, and then `i18next.changeLanguage` to "trigger" ui update, In React apps this changes text only without reloading any thing.

If you are not working with React, can you provide a repo that will show how your setup works, I will check why it refreshes the entire page.

**Comment by martijnmichel** [comment]
I'm using quasar (vue) and vue-i18next. I can't provide a repo because its private. But mainly its like this:

Boot file i18n.js
`import Vue from "vue";
//import VueI18n from "vue-i18n";
import i18next from "i18next";
import LanguageDetector from "i18next-browser-languagedetector";

import VueI18Next from "@panter/vue-i18next";

import messages from "src/i18n";

//import { applyI18NextHMR } from "i18next-hmr";

Vue.use(VueI18Next);

import moment from "moment";

i18next.use(LanguageDetector).init({
  resources: messages,
  fallbackLng: "en-US",
  ns: ["translation", "md", "wiki"],
  defaultNS: "translation"
});

const i18n = new VueI18Next(i18next);

moment.locale(i18next.language);

if (process.env.NODE_ENV === "development") {
  //applyI18NextHMR(i18next);
}

export default ({ app }) => {
  app.i18n = i18n;
};
export { i18n };`

Translation files:
`import enUS from "./en-us/translation.json";

import nlNL from "./nl-nl/translation.json";

export default {
  "en-US": { translation: enUS },
  "nl-NL": { translation: nlNL }
};`

**Comment by felixmosh** [comment]
@martijnmichel if you are importing the translation files into the bundle, you don't need my hmr plugin.
Cause webpack will hot reload it module.

My plugin is for a case when you are fetching translation files in the client side, (that means that webpack is not watching translations at all).

I this example has the same setup as yours?
https://github.com/panter/vue-i18next/tree/master/examples

**Comment by martijnmichel** [comment]
I dont understand what you mean with importing into the bundle and i dont know if im fetching files on the client side. sorry :(

The files are in subdirs of the src of my vue app. It will be made into an app for cordova ios/android.

As said, it detects changes but reloads the page.

**Comment by felixmosh** [comment]
I see from your code that you are not using `i18next-xhr-backend`, and consuming translations by importing `json` files and providing it to i18next as `resources`...

Anyway, can you open an issue in `i18next-hmr` repo, I will add a vue-i18next example.
And explore a setup without `i18next-xmr-backend` :]

**Comment by martijnmichel** [comment]
I can, but.. should i actually import differently?

**Comment by felixmosh** [comment]
> I can, but.. should i actually import differently?

It depends on what you want to achieve, 
your way imports **all** the languages into the bundle, even-though, the user will use only one of them, that means that your bundle is larger unnecessary.

The other way, fetching it at the client side, the bundle won't have any language, and it will fetched separately on the client side.

It is a matter of tradeoffs.

**Comment by martijnmichel** [comment]
true.. i was going to replace the import statements with async functions later. 
but both options should be able to reload translations without page refresh right?

thanks for your effort!

**Comment by felixmosh** [comment]
In your case, you can just not use my plugin at all, but use a native hmr api...

Instead of:
```js
if (process.env.NODE_ENV === "development") {
  applyI18NextHMR(i18next);
}
```
Into this:
```js
if (module.hot) {
  module.hot.accepts('src/i18n', () => {
    // this method will be invoked each time webpack sees a change in `src/i18n` import
    const newResources = require('src/i18n');
    Object.keys(newResources).forEach(lang => {
      const langObj = newResources[lang];

      Object.keys(langObj).forEach(namespace => {
        const nsResource = langObj[namespace];
        i18next.addResourceBundle(lang, namespace, nsResource, true, true);
      });
    });
  });
}

```

Based on [`addResourceBundle`](https://www.i18next.com/overview/api#addresourcebundle);

**Comment by martijnmichel** [comment]
It says module and require are undefined :(

In the case of require i was already aware this was the case and didnt find a solution on the web yet.

**Comment by felixmosh** [comment]
Are u using webpack? Typescript?

**Comment by martijnmichel** [comment]
webpack yes, typescript no

**Comment by felixmosh** [comment]
I'm not familiar with Vue nor Quasar, can you make a repo with i18next setup in it so I will be able to work on it?

**Comment by martijnmichel** [comment]
https://codesandbox.io/s/exciting-roentgen-ggcdb

although on codesandbox module and require seem to be defined :S

**Comment by martijnmichel** [comment]
Sorry, will make a repo instead of codesandbox

**Comment by felixmosh** [comment]
Look at this, https://codesandbox.io/s/quasar-vue-i18next-hmr-m44bn,

I've enabled `hot: true` in `quasar.conf.js` under **devServer**, and my code works, the app is just not consuming any translations (and I don't how how to do that) but you can see that my console log was fired.

**Comment by felixmosh** [comment]
Looks like VueI18Next is not listening on translation change as react-i18next does... need to investigate in this direction.

**Comment by martijnmichel** [comment]
Hmm yes i see, it gets fired but doesnt change.. but it still doesnt solve my module and require are not defined issue. But i guess that has nothing to do with i18next ;/

**Comment by martijnmichel** [comment]
i turned off no-undef in eslint to test my main app.. now it gets triggered but doesnt actually reload text

**Comment by felixmosh** [comment]
We need to find out what will reload Vue, I see that there is a listener on `langChanged` event, but it not seems to work, https://github.com/panter/vue-i18next/blob/master/src/i18n.js#L18-L20

Looks like an issue in `vue-i18next`

**Comment by martijnmichel** [comment]
Fixed it by doing:
```
if (module.hot) {
  module.hot.accept("src/i18n", () => {
    // this method will be invoked each time webpack sees a change in `src/i18n` import
    const newResources = require("src/i18n");
    _.each(newResources, res => {
      _.each(res, (lang, langKey) => {
        _.each(lang, (namespace, nsKey) => {
          i18next.addResourceBundle(langKey, nsKey, namespace, true, true);
        });
      });
    });
  });
}
```

**Comment by felixmosh** [comment]
And this reloads the UI?

Your require has `export default` therefore you need to reference `.default` :]
```js
if (module.hot) {
  module.hot.accept("src/i18n", () => {
    // this method will be invoked each time webpack sees a change in `src/i18n` import
    const newResources = require("src/i18n").default;
      _.each(newResources, (lang, langKey) => {
        _.each(lang, (namespace, nsKey) => {
          i18next.addResourceBundle(langKey, nsKey, namespace, true, true);
        });
      });
  });
}
```

**Comment by martijnmichel** [comment]
ah, yes i guess that will work too! :)) im so happy haha.. finally hmr for my translation files.
