### ISSUE TITLE
Language codes with hyphen are not formatted and therefore loaded

### ISSUE THREAD

**Issue by littlemooon** [i18next/i18next#1346]
# Problem

Languages such as `zh-Hans` fail to preload

# Investigation

During `getLanguagePartFromCode` the language code is split by `-` and passed into `formatLanguageCode`.

This then returns `if (typeof code === 'string' && code.indexOf('-') > -1) {`

Therefore any string with a hyphen always fails to be formatted.

https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L27-L33
```
  getLanguagePartFromCode(code) {
    if (!code || code.indexOf('-') < 0) return code;

    const p = code.split('-');
    return this.formatLanguageCode(p[0]);
  }

  formatLanguageCode(code) {
    // http://www.iana.org/assignments/language-tags/language-tags.xhtml
    if (typeof code === 'string' && code.indexOf('-') > -1) {
      const specialCases = ['hans', 'hant', 'latn', 'cyrl', 'cans', 'mong', 'arab'];
      let p = code.split('-');
```

# Potential solution

I presume you want to split the code after formatting (this works for me):
```
getLanguagePartFromCode(code) {
  if (!code || code.indexOf('-') < 0) return code;

  return this.formatLanguageCode(code).split('-')[0];
}
```

**Comment by jamuhl** [comment]
I don't see the difference both return `zh`  calling formatLanguageCode only makes sure the first part (language) gets lowercased.

`this.formatLanguageCode('zh-Hans').split('-')[0]` = `this.formatLanguageCode('zh-Hans'.split('-')[0])` = 'zh'

https://github.com/i18next/i18next/blob/master/src/i18next.js#L174 preload also does not call that...

see: https://github.com/i18next/i18next/blob/master/test/languageUtils.spec.js all works as expected...

my guess -> you set language to `zh-Hans` have set init option `load: 'languageOnly'` therefore you get only `zh` in `i18next.languages`
