### ISSUE TITLE
i18n CLI doesn't generate plural forms when count is present

### ISSUE THREAD

**Issue by jmccarrell-lmi** [i18next/i18next#1347]
When I have the following in my code.
```
i18n.t('CC Admin', { count: 22 });
```

I'd expected the following key to be added:
```
'CC Admin_plural': 'CC Admin_plural',
```

**Comment by jamuhl** [comment]
Sorry but what is i18n CLI?!?

**Comment by jamuhl** [comment]
Any update on this...I really would like to help you - but currently, I got no clue what the i18n CLI is?!?

**Comment by jmccarrell-lmi** [comment]
This is definitely the wrong place haha, sorry about that.

I should be posting in the issues for https://github.com/i18next/i18next-parser
