### ISSUE TITLE
Typescript module import doesn't work for me

### ISSUE THREAD

**Issue by jtheisen** [i18next/i18next#1350]
There's already [this ticket](https://github.com/i18next/i18next/issues/1177) talking about it, but it's locked with a last comment from @rosskevin.

As you can see in the following sandbox, although the typings agree, you get a run-time error (which is also shown in the editor, it's still a runtime-error and intellisense shows you that the typings are properly recognized):

https://codesandbox.io/s/sad-galois-d4e4h

Importing with

```
import i18next from "i18next"
```

works at runtime, but then the typings don't fit.

**Comment by rosskevin** [comment]
Hells @jtheisen, I have been taking another look at this in the past 24 hours.

Your sincere and honest answer to this question will be most helpful in determining my next steps, please don't read into it.

Up to this point, why have you decided against using `esModuleInterop: true`?

**Comment by jtheisen** [comment]
I think you are right that this option is an ok solution. The typescript documentation recommends it being true anyway, so there seems to be no reason not to. Sorry that I didn't see that earlier. I'll close this then.
