### ISSUE TITLE
'i18next' is declared but its value is never read

### ISSUE THREAD

**Issue by Kamahl19** [i18next/i18next#1353]
After upgrading to v19, the `'i18next' is declared but its value is never read.` error shows. According to the https://github.com/i18next/i18next/pull/1352 it should just work, because I have `esModuleInterop: true` and I import i18next like this `import i18next from 'i18next';`. However I only use the type from i18next like `i18next.TFunction`

Edit: solved it by just doing `import { TFunction } from 'i18next';` :)

**Comment by Kamahl19** [comment]
So actually this is not an issue, it would just be helpful to add a not to import Types from i18next this way after upgrading to v19

**Comment by rosskevin** [comment]
This is a valid error.

**Comment by krnlde** [comment]
@rosskevin did you intent to close this issue, despite being a valid error?

**Comment by Kamahl19** [comment]
This is not an issue. It's just that since v19 you have to import types differently and it's not mentioned in the Changelog

**Comment by rosskevin** [comment]
It is a user linting error. Are you getting it from an i18next source file or your own? If it is your own code there is nothing for us to do here.

**Comment by krnlde** [comment]
I get it in my own code. But in the changelog it mentioned "it just works" if I have `esModuleInterop: true`, but that's not true. A migration path is needed, which s indicated by the major version bump but not reflected in the changelog.

**Comment by krnlde** [comment]
For reference, here's the migration path: https://github.com/i18next/i18next/pull/1352

**Comment by rosskevin** [comment]
@krnlde the PR shows sample code with both use of the default and a named import.  If you do not know what these are, or why you get the error, I suggest reading about these fundamentals of the JavaScript language.

If you are using esModuleInterop, you need no changes. If not, you need changes as indicated by the major version bump.
