### ISSUE TITLE
Chinese fallback languages don't get loaded correctly

### ISSUE THREAD

**Issue by jvonasek** [i18next/i18next#1354]
Hi, I have translations for both Simplified (zh-Hans) and Traditional (zh-Hant) chinese.

I defined these fallbacks:
```
{
  'fr-BE': ['fr'],
  'fr-CA': ['fr'],
  'fr-LU': ['fr'],
  'fr-CH': ['fr'],
  'zh-CN': ['zh-Hans'],
  'zh-TW': ['zh-Hant'],
  default: 'en',
}
```

I use language detector, when browsing the site with "fr-BE" locale, the "fr" files get correctly loaded, but when browsing with "zh-TW", the site is briefly shown in correct "zh-Hant" language, but after few seconds, the translations disappear and only the keys are displayed (not even "en" default)

I think the problem is, that I don't have "zh" file, but i18next tries to use it anyway, even if backend returned empty response for that language.

i18next version is 19.0.0

My config 
```
i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: {
      'fr-BE': ['fr'],
      'fr-CA': ['fr'],
      'fr-LU': ['fr'],
      'fr-CH': ['fr'],
      'zh-CN': ['zh-Hans'],
      'zh-TW': ['zh-Hant'],
      default: 'en',
    },
    debug: true,
    keySeparator: false,
    interpolation: {
      escapeValue: false,
    },
    backend: {
      loadPath: '/api/locale/{{lng}}/{{ns}}',
    },
    react: {
      useSuspense: true,
    },
  })
```

**Comment by jamuhl** [comment]
`'zh-CN': ['zh-Hans'],` -> use `zh-CN` -> `zh` -> `zh-Hans`

you need to define all fallbacks it should use -> `'zh-CN': ['zh-Hans', 'en'],`

default is only used were no custom definition is set...

**Comment by jvonasek** [comment]
Thanks for the heads up, turned out I also had unexpected side effect in the app that triggered the fallback option to reset.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
