### ISSUE TITLE
init should be sync when using language detection

### ISSUE THREAD

**Issue by macco3k** [i18next/i18next#1355]
I'm using i18next for both our .net core backend and our frontend. We are using a mix of knockout and pure typescript to render our views, so that some labels for the page actually end up in the typescript file as variables, e.g. `const div_text = i18next.t('some_key')` which are either used directly to generate some virtual dom elements, or are later bound via knockout observables.

I'm currently initializing i18next like the following in our `init.ts` script:
``` typescript
import Backend from 'i18next-chained-backend';
import LocalStorage from 'i18next-localstorage-backend';
import XHR from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import i18next from 'i18next';

const supportedCultures = ['nl-NL', 'en-US'];

i18next
    .use(LanguageDetector)
    .use(Backend)
    .init({
        load: 'currentOnly',    // only load the currently selected language
        fallbackLng: 'nl-NL',
        whitelist: supportedCultures,
        // additional namespaces need to be loaded in the scripts which make use of them
        ns: ['common'],
        defaultNS: 'common',
        backend: {
            backends: [LocalStorage, XHR],
            backendOptions: [
                {},
                {
                    loadPath: '/locales/{{lng}}/{{ns}}.json',
                }
            ]
        },
        detection: {
            // keys or params to lookup language from
            lookupCookie: 'Fooks.user-culture', // straight from .net core            
            // only detect languages that are in the whitelist
            checkWhitelist: true
        }
    }); 

export { i18next as localizer };
```
Later in the view file we import i18next and use it straight away like so:
``` typescript
import { localizer } from '../../../init';
// snip...
header = localizer.t('mutation_type')//'Soort mutatie'
// snip...
```
Unfortunately, since the init is executed async, when the translation function gets called, the language is not yet set (as the detector plugin has yet to be run), and i18next falls back to dutch, despite the cookie being set to `en-US`. 

Is there a neat workaround for this? I know I could just use `initImmediate: false`, though I'd rather find a solution which allows us to keep the async loading of resource files through xhr, and just wait for the detector to be run synchronously.

**Comment by jamuhl** [comment]
Not the detection is the problem...loading via xhr is async...

Really the only correct way to solve your problem use the init callback or Promise to delay rendering until ready...

Using multiple namespaces loaded during app usage use `loadNamespaces` to assert they are loaded

If not working for you ... pass in resources on init, use an xhr backend having sync request flag set, and use initImmediate

**Comment by macco3k** [comment]
Well, deferring the update until the promise is done would require way too effort for now, so I'll just stick with the `initImmediate: false` option for now. Perhaps I'll try to bundle resources in init.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
