### ISSUE TITLE
nesting takes only the fallbackNS

### ISSUE THREAD

**Issue by ubreddy** [i18next/i18next#1356]
fallbackNS initialed to 'default'

when in current namespace I have a key value like below

namespace | key | value
-- | -- | --
default | defaultMsg | Hello!
current | okMsg | this is great!
current | msg1 | $t(okMsg)

code 
` t(current:msg1)`

The above is returning  okMsg.

Expected :   this is great!

When I debug I see that the nesting is trying to look up the key okMsg only in fallback namespace and not in current namespace and hence unable to find the key / value for okMsg in that namespace.

**Comment by jamuhl** [comment]
`$t(okMsg)` is like a call to `t(okMsg)` -> no ns defined, lookup in default

=> specify where to search that key `$t(current:okMsg)`

**Comment by ubreddy** [comment]
ok. Would have been better if the current namespace is used for nesting too... 
Thank you for clarifying.
closing the issue, then.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
