### ISSUE TITLE
languaje fallback doesn't not work

### ISSUE THREAD

**Issue by JorgeMoralesLopez** [i18next/i18next#1357]
I am using the "i18next": "^ 19.0.0" with react native and expo. The translations work fine but when I try to set the fallback language = "en", if I open the app with a device that has a regional configuration that the app doesn't have, I should put "en", however it doesn't.

i18n.js
`
export const fallback = "en";
export const supportedLocales = {
    en: {
        name: "English",
        translationFileLoader: () => require('../lang/en.json'),

        // en is default locale in Moment
        momentLocaleLoader: () => Promise.resolve(),
    },
    // es: {
    //     name: "Spanish",
    //     translationFileLoader: () => require('../lang/es.json'),
    //     momentLocaleLoader: () => import('moment/locale/es'),
    // },
};
export const defaultNamespace = "common";

export const namespaces = [
    "common",
    "Profile",
    "Event"
];
`

i18n index.js
init
`
init: () => {
        return new Promise((resolve, reject) => {
            i18next
                .use(languageDetector)
                .use(translationLoader)
                .init({
                    fallbackLng: config.fallback, //"en"
                    ns: config.namespaces,
                    defaultNS: config.defaultNamespace,
                    interpolation: {
                        escapeValue: false,
                        format(value, format) {
                            if (value instanceof Date) {
                                return date.format(value, format);
                            }
                        }
                    },
                }, (error) => {
                    if (error) { return reject(error); }

                    date.init(i18next.language)
                        .then(resolve)
                        .catch(error => reject(error));
                });
        });
    },`

**Comment by jamuhl** [comment]
i18next.language is set to whatever is detected...regardless of what you think you support or not. not using whitelist everything is accepted as detected language...

i18next.languages will be the array of languages used ordered by prio used to resolve translations

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
