### ISSUE TITLE
Support for locale versions

### ISSUE THREAD

**Issue by mozzan** [i18next/i18next#1358]
I am searching for versioning the locale files. (Or any configuration that we can use for disable the  client's previous locale file in LocalStorage)
Just like https://github.com/i18next/i18next-localstorage-backend#cache-backend-options
The reason is we add some locale strings, and after deployment it's not found because of the localstorage.

Does this library have this kind of configuration?
Thank you.

**Comment by jamuhl** [comment]
you already provided the link to the documentation where you find the options to do so...so where do you struggle?

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
