### ISSUE TITLE
How to programmatically validate translation values and keys?

### ISSUE THREAD

**Issue by acidoxee** [i18next/i18next#1362]
Hi, I'm trying to integrate some automatic validation of translation keys and values with [eslint-plugin-i18n-json](https://github.com/godaddy/eslint-plugin-i18n-json#i18n-jsonvalid-message-syntax).

I was wondering if there already exist some validation functions for keys and values to detect incorrect formatting, based on an i18next configuration? This would enable us to catch those mistakes as soon as possible.

I should mention that we are using the default i18next interpolation, not a custom one.

Thanks a lot

**Comment by jamuhl** [comment]
only thing I know is https://github.com/i18next/i18next-translation-parser but we use that for syntax highlighting and not validation

**Comment by acidoxee** [comment]
I see, this may be used for validation purposes, but probably not as-is.

Do you plan in the future to release such a validation utility?

**Comment by jamuhl** [comment]
No there is no such plan...

**Comment by acidoxee** [comment]
Alright, thanks anyway!
