### ISSUE TITLE
Does fallback languages follow locale resolving?

### ISSUE THREAD

**Issue by fromi** [i18next/i18next#1363]
The documentation about fallbacks here is missing a detail: https://www.i18next.com/principles/fallback

If I configure this: `fallbackLng: ['fr_FR', 'en_US']`, is it equivalent to this configuration: `fallbackLng: ['fr_FR', 'fr', 'en_US', 'en']` or not?
To paraphrase, does the "locals resolving" rule in the documentation always apply (which would be great), or it applies only to the current language?

**Comment by jamuhl** [comment]
applies only to current language...not to fallbacks defined.

**Comment by fromi** [comment]
Thanks, I will configure the fallbacks accordingly
