### ISSUE TITLE
Typescript: type of "i18next.services.resourceStore" is wrong

### ISSUE THREAD

**Issue by fromi** [i18next/i18next#1364]
I'm trying to access the resource store datas for Server Side Rendering.

I use: `i18next.services.resourceStore`, witch is of type 'Resource'
I expect `i18next.services.resourceStore['en']` to work, but instead I have to do:
`i18next.services.resourceStore.data['en']`

That data property does not exist for Typescript. It looks like i18next.services.resourceStore is not of ResourceType, but i18next.services.resourceStore.data is. Maybe a 'ResourceStore' is missing in the middle?

**Comment by rosskevin** [comment]
Please PR and tag me.

**Comment by rosskevin** [comment]
Relevant runtime code from `i18next.js`:

```js
      this.store = new ResourceStore(this.options.resources, this.options);

      s.resourceStore = this.store;
```

from ts

```ts
export interface Services {
  resourceStore: Resource;
}
```

I'm not familiar with this portion of the api, but @jamuhl is pretty specific and indeed this looks incorrect.  Still looking.

**Comment by rosskevin** [comment]
I'm sending a PR and I have modeled what i see in the runtime.

it does appear that access is correct via 

```ts
const resourceStore: ResourceStore = i18next.services.resourceStore;
resourceStore.data['en'];
```

So indeed `ResourceStore` was missing, but it looks like access remains the same from a user perspective.

**Comment by fromi** [comment]
Looks good! Access remains the same indeed, it will only be more convenient for people using Typescript.
Thanks

**Comment by jamuhl** [comment]
`resourceStore.data` is "not" (but no one says you can't directly access it) part of the public API -> i18next.getDataByLanguage(lng) === resourceStore.data['en'];

**Comment by fromi** [comment]
Thanks! I will report that is next-i18next project then, I took my inspiration from there:
https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.tsx#L131

Actually, it is quite convenient for Server Side Rendering to grab all the data at once instead of having to loop on each loaded language: we need the full store at once for useSSR hook here: https://react.i18next.com/latest/ssr#using-the-usessr-hook

Maybe a way to get all the data need to reach public API for this purpose?

**Comment by jamuhl** [comment]
@fromi the idea is not to pass down the full store (might be good enough for your case to pass down one language -> but depending on size you like to "cherry" pick the used namespaces only -> that's what https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.tsx#L131 does)

that's why we: https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L37 that can be read out https://github.com/i18next/react-i18next/blob/master/src/context.js#L46

**Comment by fromi** [comment]
I am working on a Serverless version actually: the full store in my case matches exactly the languages and namespaces as it was initialized on the serverless only for that purpose:

1. I get the language based on the path + the fallback languages based on the request accept language header.
2. I get the initial namespaces from the HOC parameters
3. I create an i18next instance that will preload all that languages and namespaces
4. I pass the languages, namespaces and full store data to the component's initial properties so he can init the store without fetching the data again on the client side.

So unless I am mistaken, passing the full store is fine for my use case, isn't it?

**Comment by jamuhl** [comment]
@fromi seems ok for your case
