### ISSUE TITLE
Need to load translations from API call at application start up.

### ISSUE THREAD

**Issue by salmanlone** [i18next/i18next#1367]
I need to load my translation files from an API call at the time of start-up of application. Kindly help in

- Loading translations from API call.

- Save translations from API call to public/locales/{ln}/{ln.json}

**Comment by jamuhl** [comment]
`start-up of application` on clientside or serverside?

clientside use https://github.com/i18next/i18next-xhr-backend it will load from any server endpoint and load/store translations for i18next usage in client...

server -> using node.js? use eg. https://github.com/i18next/i18next-node-remote-backend to load from remote server API or purely https://www.npmjs.com/package/request -> save to public folder using node.js fs -> https://nodejs.org/api/fs.html

**Comment by jamuhl** [comment]
also you might read https://www.i18next.com/how-to/add-or-load-translations to get a better understanding of how to pass translations to i18next

**Comment by salmanlone** [comment]
Hi, Meanwhile i have achieved this functionality by doing
  .init({
    backend: {
      loadPath:
        translate_api +
        "/bulk/messages?ids=1&ids=501&ids=658&ids=533",
      allowMultiLoading: true,
      crossDomain: true
    }

Although i am getting my translation from api with GET call but now i want to do it with post call including values in body. Can you help to know how i18lnext send post call for loading translations at loadPath?

**Comment by jamuhl** [comment]
you can set whatever you like for ajax call -> https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L13 like eg. default: https://github.com/i18next/i18next-xhr-backend/blob/master/src/ajax.js -> just change https://github.com/i18next/i18next-xhr-backend/blob/master/src/ajax.js#L44 to always `POST`

sidenote...multiloading is not supported anylonger without using: https://github.com/i18next/i18next-multiload-backend-adapter

**Comment by salmanlone** [comment]
Thanks for the references, just one question

if i use ajax call for POST call then how i will set it to loadPath? i searched into test cases and example for sample code but couldn't find anything. I am assuming that our translation gets load at loadPath (which i am using right now for GET call). If i use ajax call then there must be some return value to set loadPath value. right?

**Comment by jamuhl** [comment]
read the code: 

read is the function called to load translations -> it interpolates lng, ns into loadPath and calls the load function which calls the ajax function: https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L48
