### ISSUE TITLE
Load translation files from server

### ISSUE THREAD

**Issue by kamranpoladov** [i18next/i18next#1370]
Is there any way to load translations from the server? I am receiving json from there and want to use it instead of client-side json files. 

My current approach:

```
i18n
    .use(XHR)
    .use(LanguageDetector)
    .init({
        fallbackLng: 'en',
        debug: false,

        keySeparator: false,

        partialBundledLanguages: true,

        interpolation: {
            escapeValue: false,
            formatSeparator: ','
        },

        resources: {
            en: {
                translations: loadEn().then(response => {
                    response = JSON.stringify(response);
                    return response
                })
            },
            ru: {
                translations: loadRu().then(response => {
                    response = JSON.stringify(response);
                    return response;
                })
            },
            es: {
                translations: loadEn().then(response => {
                    response = JSON.stringify(response);
                    return response;
                })
            }
        },

        ns: ['translations'],
        defaultNS: 'translations',

        react: {
            useSuspense: false
        }
});
```

`response` is just a JSON string with "key": "value" pairs.

**Comment by jamuhl** [comment]
You do not have to pass `resources` when using a XHR backend: https://www.i18next.com/how-to/add-or-load-translations

**Comment by kamranpoladov** [comment]
> You do not have to pass `resources` when using a XHR backend: https://www.i18next.com/how-to/add-or-load-translations

Okay, shall I just pass a link from server to `loadPath`? Can you please share some sample code because in the documentation they load files from the client I suppose.

**Comment by kamranpoladov** [comment]
I have a separate endpoint to load all the languages and separate endpoint to load resources for each language specifically. To load a resource, I have to pass params with lang code to request

**Comment by adrai** [comment]
sample with xhr-backend:

jquery: https://github.com/adrai/i18next-main-differentiator/blob/master/jquery/index.html#L63
react: https://github.com/adrai/i18next-main-differentiator/blob/master/react/src/i18n.js#L7
vue: https://github.com/adrai/i18next-main-differentiator/blob/master/vue/app.js#L3
angular: https://github.com/adrai/i18next-main-differentiator/blob/master/angular/directive.js#L4

**Comment by jamuhl** [comment]
multiload is described here: https://github.com/i18next/i18next-multiload-backend-adapter
