### ISSUE TITLE
Using with Svelte/Sapper 

### ISSUE THREAD

**Issue by ehsanonline** [i18next/i18next#1371]
How can I use i18next in a [Svelte](https://github.com/sveltejs/svelte)/[Sapper](https://github.com/sveltejs/sapper) app? unfortunately there is no plugin to integrate these two, yet.

**Comment by adrai** [comment]
Seems nobody currently did “opensource” such a plugin.

If you like you can easily create one, just use the i18next “core” and inject your plugin... like vie-i18next: https://github.com/panter/vue-i18next

Would you like to extend the community? -Just have a try... as soon it’s released we can then insert it in the list.
What do you think?
