### ISSUE TITLE
18next::translator: missingKey

### ISSUE THREAD

**Issue by aminejih** [i18next/i18next#1372]
I did this config
import i18n from 'i18next';
import Backend from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { reactI18nextModule } from 'react-i18next';

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(reactI18nextModule)
  .init({
    fallbackLng: 'ar',
    debug: true,
    whitelist: ['en', 'ar'],

    backend: {
      loadPath: '/public/locale/{{lng}}/{{ns}}.json',
    },
    react: {
      wait: true,
    },

    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
    resources: {
      en: { translation: 'en' },
      ar: { translation: 'ar' },
    },
  });

export default i18n;
 but when I fires the onClick event to change the language to the arabic by the this.props.i18n.changeLanguage('ar') function I get the error i18next::translator: missingKey ar 
common 
I'm using withNameSpaces wrapper
how can I change the language using a button

**Comment by jamuhl** [comment]
That warning only tells you that the key does not exist: ` i18next::translator: missingKey ar
common` -> normally there is also the key in that message....so check if that exists and if all get loaded and you do not render before loading via backend happens...

**Comment by batsev** [comment]
I have similar problem.
This is the code i got:
```
import i18next from 'i18next'
import XHR from 'i18next-xhr-backend'
i18next.use(XHR).init(
  {
    lng: 'en-en',
    debug: true,
    fallbackLng: false
  },
  function() {
    // i18next is done asynchronously; this is the callback function
    console.log(i18next.t('notificationMessages'))
  }
)
```
This the response in the console:
![IMG_1577](https://user-images.githubusercontent.com/42235938/71418220-7e985700-267a-11ea-8d66-906da3e90abd.jpg)
Locales folder is in the root directory of the project
```
locales
├── en-en
       └── translation.json
```

**Comment by batsev** [comment]
I fixed it myself. Had to manually put locales folder in dist.

**Comment by akiratfli** [comment]
when init options lng include '-' character this problem occur.
https://jsfiddle.net/tbnae0cp/

**Comment by jamuhl** [comment]
https://www.i18next.com/overview/configuration-options#languages-namespaces-resources see option `lowerCaseLng`   not `-` is the problem but lowercase of the country part in locale

**Comment by ctq123** [comment]
> https://www.i18next.com/overview/configuration-options#languages-namespaces-resources see option `lowerCaseLng`. Not `-` is the problem but lowercase of the country part in locale.

thanks
