### ISSUE TITLE
Ability to disable multiple plurals

### ISSUE THREAD

**Issue by felixmosh** [i18next/i18next#1374]
I'm building an app that `Hebrew` is the main language.

I18next is defined for `Hebrew` to use multiple plurals, but, because I'm using numbers these variations are not relevant.

This forces me to specify all variants like so:
```
{
  ...
    "BEDROOM": "חדר שינה אחד",
    "BEDROOM_1": "$t(BEDROOM_plural)",
    "BEDROOM_2": "$t(BEDROOM_plural)",
    "BEDROOM_3": "$t(BEDROOM_plural)",
    "BEDROOM_plural": "{{count}} חדרי שינה",
  ...
}
```
I've found [simplifyPluralSuffix](https://www.i18next.com/overview/configuration-options#translation-defaults), but it is exactly the **opposite** of what I need.

There is any config that will fallback to _plural if there is no key for specific variant?

Will you accept a PR with this feature (configured via `options`)?

**Comment by felixmosh** [comment]
Probably related to https://github.com/i18next/i18next/pull/1369, if this PR will be approved there is no need to my suggestion.

**Comment by jamuhl** [comment]
You  can overwrite the plural rules like:

`i18next.services.pluralResolver.addRule('he', { numbers: [1,2,20,21], plurals: function(n) {return Number(n != 1);} })`

https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L90

**Comment by mixj93** [comment]
> numbers: [1,2,20,21]

What does `numbers` means here?

**Comment by felixmosh** [comment]
It is related to some internal logic, what I did is to override with the english rule,

```
  i18next.services.pluralResolver.addRule('he', i18next.services.pluralResolver.getRule('en'));
```
