### ISSUE TITLE
Retry flag?

### ISSUE THREAD

**Issue by andresilveirah** [i18next/i18next#1375]
Hi, I've seen some backend plugins calling the `callback` function passing a `boolean` as a way to set a sort of _retry flag_. Unfortunately I didn't find this flag documented anywhere and, from the very lazy quick search I've made, I saw that https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L138 will retry it by default up to 5 times. 

So I just wanted to double check if it's necessary for the `backend` plugin to handle `retrying` or if the plugin should leave that to `i18next`.

**Comment by jamuhl** [comment]
You're right...i18next backendConnector will handle the retry so backends do not need to repeat that logic over and over...eg. for the xhr backend based on http status https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L53 the connector will then retry: https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L140

**Comment by andresilveirah** [comment]
Perfect, thank you for the reply @jamuhl

**Comment by lenadss** [comment]
Hi guys,

Is there any possibility to configure that retry mechanism? For example set retry attempts to 3, not 5, or to disable at all?

**Comment by jamuhl** [comment]
@lenadss what's your usecase?
