### ISSUE TITLE
API to pre-fetch translation files based on current route

### ISSUE THREAD

**Issue by dcworldwide** [i18next/i18next#1376]
When language files are split into route specific namespaces. It would be a nice opt-in optimisation if we can instruct i18next to pre-fetch translation files for child routes. This will greatly reduce rendering delays when the user navigates the app. 

Using react-router. 

https://stackoverflow.com/questions/59404578/pre-fetch-i18next-translation-files-based-on-current-route

**Comment by jamuhl** [comment]
You can fetch anything anytime using the API: https://www.i18next.com/overview/api#loadnamespaces

A solution has to come from userland - we won't do specific solutions to a router implementation....

**Comment by dcworldwide** [comment]
Ok thanks.

Before I close, will i18next.loadNamespaces() only ever load translations for the current language?

**Comment by jamuhl** [comment]
- yes, only loads for current language
- only loads things not already loaded -> to force a reload use: https://www.i18next.com/overview/api#reloadresources
- you can import i18next or the export from i18n.js --> https://github.com/i18next/react-i18next/blob/master/example/react/src/i18n.js#L26 (as long you do not use i18next.createInstance the main instance is a singleton you can just import anywhere)

**Comment by dcworldwide** [comment]
Awesome. Thankyou for your time. Happy new year.
