### ISSUE TITLE
translationResolved event?

### ISSUE THREAD

**Issue by ervasive** [i18next/i18next#1380]
Hi there.

So, here's a crazy idea. Would it make sense to introduce the `translationResolved` or similar event to have the ability to catch all queried translations at runtime?

[Somewhere here](https://github.com/i18next/i18next/blob/master/src/Translator.js#L102):

```javascript
translate(keys, options) {

   ...

    // resolve from store
    const resolved = this.resolve(keys, options);
    this.emit('missingKey', resolved)

   ...

}
```

Here's a couple of use-cases:
1. Let's say that I want to get only translation messages used by a particular route/page (during an SSR run) and then pre-bundle them within the resulting HTML and have them ready to rock on i18n instance init on the client-side.
2. Collect dynamically created translation ids (again during an SSR run) ex. `t(`${foo}`-bar)` which isn't possible with static extractors like `https://github.com/gilbsgilbs/babel-plugin-i18next-extract` etc.

There are probably some show-stoppers here that I don't see, but I would be interested in such a feature.

Thanks kindly

**Comment by jamuhl** [comment]
Guess it's not practical out of following reasons:

- performance (events)
- you can't use this on the client -> or at least you won't be able to proper load keys not loaded without loading complete namespaces

=> split into namespaces as needed to not send full language down

For missing keys there is already an event / eventhandler and backends support submitting them to the backend implementation: eg. locize.com can add all new / missing keys during development this way...

For usage information we even track every resource access via: https://github.com/locize/locize-lastused/blob/master/src/index.js#L61 (so if you really like to build something custom - there you find some inspiration)

**Comment by ervasive** [comment]
> For usage information we even track every resource access via: https://github.com/locize/locize-lastused/blob/master/src/index.js#L61 (so if you really like to build something custom - there you find some inspiration)

Oh, interesting. Thank you for the reply and the hint
