### ISSUE TITLE
need to get available languages list from backend.

### ISSUE THREAD

**Issue by pavel-grom** [i18next/i18next#1382]
Hello. I need to get available languages list from backend.
But backend plugin allows only get translates from backend.
How can I do this?

**Comment by jamuhl** [comment]
There is no such option....

**Comment by jamuhl** [comment]
Why you need that list?

**Comment by pavel-grom** [comment]
I need to get available languages and translates from api, that sets in admin panel.
But I done this by another way - got languages before i18next initialization by sync request.
