### ISSUE TITLE
`missingInterpolationHandler` documentation does not match TS declaration

### ISSUE THREAD

**Issue by smhutch** [i18next/i18next#1383]
Currently the `missingInterpolationHandler` documentation does not match the typescript function declaration. I'm currently using the Typescript types in my project to ensure we always pass valid configuration options.

## TS
https://github.com/i18next/i18next/blob/72703cd62ab1a640a5e954c6455f02704d6c431c/index.d.ts#L287

## Docs
```
function(text, value) { return 'stringWithAlternativeValueOrUndefined' };
gets called in case a interpolation value is undefined.
This method will not be called if the value is empty string or null
```

## Related confusions
1. I don't understand the purpose of the third argument. Could it be an optional argument?
2. When a missing variable is found (i.e. `missing_var`) the value argument is an array with `['{missing_var}', 'missing_var`]. Note in my case I'm using this syntax for variables `{variable}. I don't understand currently why this is an array, as the docs imply it's a string. Currently I pluck the first value from this array, and use it to log an error.
3. The docs imply the following return type `undefined | string`

## Current workaround.
I'm currently working around this by passing `null` as a third argument.

Please let me know if you have any further questions. Happy to help where possible. Thanks! 😄

**Comment by jamuhl** [comment]
1) idk...might had some value for the one adding that handler (personally I never had the need for this feature)

2) https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L125 it's (translationString, missingRegexMatch, options) => { return someString }

3) return what you like to have interpolated instead...

If you like changes to the types - feel free to provide a PR (incl. tests as needed) and ping @rosskevin for review
