### ISSUE TITLE
Interpolation formatting does not support default format(s)

### ISSUE THREAD

**Issue by mjbcopland** [i18next/i18next#1384]
The `format` argument of the formatter function is optional but must be supplied during interpolation in order for any custom formatting to take effect.

Consider the following example

```js
i18next.init({
  lng: "en",
  interpolation: {
    escapeValue: false,
    format: function(value, format, lng) {
      return value.toLocaleString(lng);
    },
  }
});

console.log(
  i18next.t("Total {{amount}} since {{date}}", {
    amount: 123456.789,
    date: new Date()
  })
);
```

```
Total 123456.789 since Wed Jan 22 2020 17:03:40 GMT+0000 (Greenwich Mean Time)
```

I don't see any reason why the interpolated values should not be formatted, yet that is the case. We can force formatting by supplying an empty format (include the separator but no value), but this is unintuitive, easily missed, and only discoverable by [inspecting the source](https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L79).

```js
console.log(
  i18next.t("Total {{amount,}} since {{date,}}", {
    amount: 123456.789,
    date: new Date()
  })
);

```

```
Total 123,456.789 since 1/22/2020, 17:03:40
```

**Comment by jamuhl** [comment]
And why should I expect any formatting happening with this:

```js
i18next.t("Total {{amount}} since {{date}}", {
    amount: 123456.789,
    date: new Date()
  })
```

This says use the raw value (toString if needed)

```js
i18next.t("Total {{amount, number}} since {{date, dateShort}}", {
    amount: 123456.789,
    date: new Date()
  })
```

says to format it and can be changed by translators as needed.

**Comment by mjbcopland** [comment]
I guess my question is why are we using the raw value and/or toString when a custom formatter exists? I feel like my toLocaleString example above is a reasonable enough use-case.

**Comment by jamuhl** [comment]
You do not like to call functions if not needed to call them...just out of performance reason...

**Comment by jamuhl** [comment]
Can merge your PR - but really do not agree in the behaviour is / should be default anytime in future
