### ISSUE TITLE
Translation nesting with i18nFormat plugin

### ISSUE THREAD

**Issue by butchyyyy** [i18next/i18next#1386]
Hi, i just tried to use translation nesting as described in https://www.i18next.com/translation-function/nesting only to find out it does not work when using i18nFormat plugin. 

I can understand why you might not want to do the nesting as it could interfere with the i18nFormat plugin, but it would be great to put a disclaimer into the documentation to avoid people getting headache in the future.

Also is there a way to invoke the nesting functionality from the i18nFormat plugin?

**Comment by jamuhl** [comment]
yes, nesting is part of the i18next specific format...depending on changed i18nFormat something similar is supported (eg. i18next-fluent with referencing)...so changing the format switches to only support what's in that format

**Comment by jamuhl** [comment]
you can access the nesting function from i18next.services.interpolator -> but that won't work nicely I guess...

**Comment by butchyyyy** [comment]
We went with the ICU format becauses we felt like it's easier to handle plurals there (especially multiple plurals in one translation).
Might consider going back to i18n format and handle multiple plurals with nested translations.

For now calling this in our icu i18n format extension seems to do the trick:

`result = i18n.services.interpolator.nest(result, (...args) => t(...args), {})`

**Comment by jamuhl** [comment]
ICU format is limited to a single string by definition - might be ok to use nesting the way you did...it's just not part of the specification...so IDK for sure

**Comment by butchyyyy** [comment]
Well aware it's a hacky solution out of the definition of the ICU format.

Thanks for the tips
