### ISSUE TITLE
query string 

### ISSUE THREAD

**Issue by mohamadsdg** [i18next/i18next#1387]
why query string is disappear after change route ?
i use react-router-dom for routing .

**Comment by jamuhl** [comment]
there is no magic integration with the react-router...you have to append querystring yourself on route change...

**Comment by mohamadsdg** [comment]
I guess that wouldn't be the case .. It seems great to add this feature

**Comment by jamuhl** [comment]
There is no way to add this in react-i18next -> react-router is just one of the routers used out there - we can't support them all - so this needs to be done in userland.

**Comment by jamuhl** [comment]
note: adding the query for lng over and over again is not needed -> the current language will be persisted in localStorage or cookie (if set so)

**Comment by mohamadsdg** [comment]
The main reason for this
Identify the type of language with URL that is very useful for sharing site links on social networks .
The link should specify which language is used

> note: adding the query for lng over and over again is not needed -> the current language will be persisted in localStorage or cookie (if set so)

**Comment by jamuhl** [comment]
Ok...I see your case...still not much I can do from our site...we have no control over the used router and therefore can't add the querystring param from within i18next - if you can think of a way feel free to provide a pullrequest...👍
