### ISSUE TITLE
TS error when trying to .map an array returned by t('someKey', { returnObjects: true })

### ISSUE THREAD

**Issue by aslauris** [i18next/i18next#1390]
**Example translation file:**

`{
"someKey": [
  "String 1",
  "String 2",
  "String 3",
]
}`

**Example usage:**

`t('someKey', { returnObjects: true }).map((string) => {
...
})`

**The above example produces the following TS error:**

> Property 'map' does not exist on type 'string'.

I guess there is some issue with TS types? Thanks in advance!

**Comment by rosskevin** [comment]
There is nothing wrong with the types.  Please read the interface:
https://github.com/i18next/i18next/blob/master/index.d.ts#L631

And look at the tests:
https://github.com/i18next/i18next/blob/master/test/typescript/t.test.ts#L17

How would tsc infer that are expecting a `string|object|array`?  It cannot, and the highest use case is `string`, therefore you will need to use a parameter to cast to the intended `TResult`
