### ISSUE TITLE
Using initial resources stops requests to XHR backend along with fallbackLng

### ISSUE THREAD

**Issue by MrBudapest** [i18next/i18next#1391]
Looking at the document:
https://www.i18next.com/overview/configuration-options

It implies I can choose to initialize i18next with resources and then use i18next-xhr-backend and fallbackLng to obtain translations not available in the initial resources. Have I miss understood the document or is this a defect?

My package.json i18next versions appear to be up to date:
"i18next": "^19.1.0",
"i18next-browser-languagedetector": "^4.0.1",
"i18next-xhr-backend": "^3.2.2",
"react-i18next": "^11.3.1",

My config:
`const resources = {
  en: {
    translation: translationEN,
  },
};

i18n
  .use(XHR)
  .use(LanguageDetector)
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    resources,
    fallbackLng: 'en', // use en if detected lng is not available
    load: 'languageOnly',
    interpolation: {
      escapeValue: false, // react already protect from xss
    },
    react: {
      wait: true,
      transSupportBasicHtmlNodes: true,
    },
    backend: {
      loadPath: Directory.CONTEXT_ROOT + '/locales/{{lng}}/{{ns}}.json',
      crossDomain: true,
    },
  });`

Removing the resources line enables my react app to make XHR calls for the translations file and fall back correctly. However, when I try to initialize the resources as per the code above, no XHR requests are made and my react web app fails to load:
Unhandled Rejection (Error): withI18nextTranslation(ErrorBoundary)

Thank you for your help in advance.

**Comment by tonyob** [comment]
I think setting the "partialBundledLanguages" option to true will achieve what you want.

**Comment by MrBudapest** [comment]
Thanks excellent.
