### ISSUE TITLE
i18next issue with angular projects

### ISSUE THREAD

**Issue by jango07** [i18next/i18next#1392]
I am trying to use i18next in my angular project.
I have initialized i18next in my app module and tried an example in my app component .It worked fine :)
Now I am trying to use i18next  in my component which is inside the **projects** folder.
It throws error saying i18next is not defined.What could go wrong ? Do i need to initialize i18next anywhere else ?

Thanks
jango

**Comment by jamuhl** [comment]
What do you use for modules? ES modules, webpack bundling, commonjs, UMD, ?!?

I would say you need to import i18next in every module! Having some sort of module system i18next is not appended to global.
