### ISSUE TITLE
i18next + locize optimization

### ISSUE THREAD

**Issue by cullsin** [i18next/i18next#1393]
Hi, 

we have configured locize + i18next. When we do benchmark, On the initial load i18next configuration takes 2sec to load and allow user to perform the action in the homepage. I have presented our configuration below. I am looking for 2 performance change. Also, it blocks the Javascript main thread.

1. load namespace only required in the homepage, instead of load all namespace.
2. fetch all namespace once, than fetching by namespace which add ''n" namespace requests.

Can you please help me optimizing locize.

              /** @format */

          import i18n from 'i18next';
          import moment from 'moment';
          import LocizeEditor from 'locize-editor';
          import LocizeBackend from 'i18next-locize-backend';
          import LanguageDetector from 'i18next-browser-languagedetector';

          import { captureException } from '@sentry/browser';
          import { reactI18nextModule } from 'react-i18next';
          import { getLocaleBasedOnHost } from 'utils/i18nHelper';

          const { locale, version, backendUrl } = getLocaleBasedOnHost();

          i18n
            .use(LocizeBackend)
            .use(LocizeEditor)
            .use(LanguageDetector)
            .use(reactI18nextModule)
            .init(
              {
                lng: locale,
                fallbackLng: 'sv-SE',
                debug: false,
                ns: [
                  'lang_1',
                  'lang_2',
                  'lang_3',
                  'lang_4',
                  'lang_5',
                  'lang_6',
                  'lang_7',
                  'lang_8',
                  'lang_9',
                  'lang_10',
                  'lang_11',
                  'lang_12',
                  'lang_13',
                  'lang_14',
                  'lang_15'
                ],
                defaultNS: 'lang_2',
                interpolation: {
                  escapeValue: false,
                  format(value, format) {
                    // date formatting for locales
                    if (format) {
                      return moment(value).format(format);
                    }
                    return value;
                  }
                },
                backend: {
                  projectId: '3265de08-cdc0-4c54-9b90-0363b49f3f7a', // <-- replace with your projectId
                  referenceLng: 'sv-SE',
                  version: version,
                  loadPath: `${backendUrl}{{projectId}}/{{version}}/{{lng}}/{{ns}}`
                },
                returnObjects: true,
                  load: 'currentOnly',
                react: {
                  wait: true
                  //omitBoundRerender: false,
                }
              },
              (error) => {
                if (error) {
                  // Sending error to sentry
                  captureException(error);
                }
              }
            );

          export default i18n;

**Comment by jamuhl** [comment]
We can't support multiload (one request for multiple namespaces) as those get published as files to our CDN (there is not server processing that call and building a response for it - cloudfront -> S3)

You can use a production version to optimize latency -> https://faq.locize.com/#/misc/latency-optimization-tips-for-optimal-performance (having the files published to edge locations help a lot)

Also as you're using react - there is no real need to load all namespaces upfront -> just call them on demand using the withTranslation HOC or useTranslation hook: 

https://react.i18next.com/latest/usetranslation-hook#loading-namespaces
https://react.i18next.com/latest/withtranslation-hoc#loading-namespaces

**Comment by jamuhl** [comment]
And it does use the main thread as it's relevant for rendering -> there is no high CPU usage calculations -> not blocking as everything is async (just runs in main thread - which is 200% ok)

**Comment by cullsin** [comment]
Can you please suggest ( which configuration option to disable ) how to stop loading while in the configuration. I will use react HOC to load on demad. 

https://react.i18next.com/guides/multiple-translation-files

**Comment by adrai** [comment]
https://github.com/locize/i18next-locize-backend/issues/318#issuecomment-584591229
