### ISSUE TITLE
Interpolation within returnedObjectHandler

### ISSUE THREAD

**Issue by nbaosullivan** [i18next/i18next#1394]
Hi there, I'm wondering what the suggested approach is for interpolation when using returnedObjectHandler, as this is defined within init options, but the interpolater isn't available at that point.

Here's what I'm currently doing in i18n.js (based on the interpolator), which works - but I'm wondering if there's a suggested approach.

```
const regexpStr = `{{(.+?)}}`;
const regexp =new RegExp(regexpUnescapeStr, 'g');
[..]
i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
   [..]
   returnedObjectHandler: function(key, value, options) {
        let translation = value['translation'];
        // Interpolator not available at this point, so use custom interpolation.
        let match;
        while ((match = regexp.exec(translation))) {
            // Get the value of our replacement variable.
            value = options[match[1].trim()];
            translation = translation.replace(match[0], value);
        }
        // console.log(options);
        return (translation !== undefined) ? translation : key;
    },
[..]
```

Thanks!

**Comment by jamuhl** [comment]
you can access i18next.services.interpolator that has: https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L67

but omitting the returnObjectHandler and setting returnObjects: true will give you the object and the values including further interpolation, nesting, ...

**Comment by nbaosullivan** [comment]
Hi @jamuhl - thank you so much for getting back so quickly, using `i18next.services.interpolator.interpolate(str, data, lng, options)` works perfectly.

 I'm using this in combination with react-i18next and setting `returnObjects: true` gives the error `Objects are not valid as a React child`. How does the t function know which property/index to output if just setting `returnObjects:true`?

Thanks again!

**Comment by jamuhl** [comment]
returnObjects gives you a JS object in JSON notation -> for sure that is no valid react child...

can you give a little more context what you like to achieve?

**Comment by nbaosullivan** [comment]
I am storing translations as objects, with each key having an object with property `translation` (the language-specific translated string), and sibling properties providing metadata used when syncing translations with an external system (metadata includes versioning). Everything is working just using `returnedObjectHandler`, but with react-i18next setting `returnObjects:true` results in the previously mentioned error. I was just wondering if an object is returned when `returnObjects: true`, and there's no `returnedObjectHandler` set (which is what I thought you were suggesting, when you said omit `returnedObjectHandler`), how do you define what the `Trans` and `t` function actually output? Thanks again for your time - my initial request has been resolved, so happy to close this.

**Comment by jamuhl** [comment]
Both `t` and `Trans` more or less do not know what todo with an object -> they expect a string to be renderen (Trans also maps react children into the translations)

**Comment by nbaosullivan** [comment]
So when omitting `returnedObjectHandler`, how can you provide the expected string to `t` and `Trans` with `returnObjects:true`?

**Comment by jamuhl** [comment]
Guess I do not understand what you're doing...return objects is about returning objects not about returning strings (returning objects eg. to pipe them into a library for validation,...)

**Comment by nbaosullivan** [comment]
No worries, a misunderstanding on my behalf I think then, thanks very much for your time.

**Comment by jamuhl** [comment]
So if I understand right - you try to get `someKey.translation` using `t('someKey', { returnObjects: true})` -> where your handler does pick `translation` on the object...why not just accessing `t('someKey.translation')`?

Still using the handler should work in Trans, t usage in react (if returning a string like expected) https://github.com/i18next/i18next/blob/master/src/Translator.js#L125

**Comment by nbaosullivan** [comment]
Here's how it's currently working: I retrieve `someKey.translation` by using `t('someKey')` and define `returnedObjectHandler` on init (as seen in code above),  to return the `translation` value from the object.

Regarding `t('someKey.translation')` it's a good point, and that's cool that the t function could handle objects without defining `returnedObjectHandler`, but these keys are defined by multiple developers on the project and it feels like unnecessary repetition adding `translation` to the end of every key, so would prefer to handle that separately. 

My question was really around whether there was a parsing function available when `returnObjects: true` when you suggested omitting `returnedObjectHandler`,  but I think just using `returnedObjectHandler` makes sense for me.

**Comment by jamuhl** [comment]
Another option would be overriding the t function on i18next: https://github.com/i18next/i18next/blob/master/src/i18next.js#L299

replacing it with a function that takes the key and calls the original with a modified key array `t(['original.translation', 'original'], options)`

**Comment by nbaosullivan** [comment]
Nice, I like that, can that override be defined on init?

**Comment by jamuhl** [comment]
not directly. you will need todo something like:

```js
i18n.init(options, () => {
  const originalT = i18n.t;
  i18n.t = (key, options) => (i18n.t([`${key}.translation`, key], options));
})
```

**Comment by nbaosullivan** [comment]
Great stuff, thanks very much for the example and all your time. Happy to close this and hopefully this will be useful to others.
