### ISSUE TITLE
Keys can not contain commas if they are nested

### ISSUE THREAD

**Issue by mgroenhoff** [i18next/i18next#1395]
The following translation will not work because there is a comma in the key. It is assumed that the first comma is separating the key from the options.

```js
i18next.t('some key with a nested message {{message}}', {
    message: '$t(some other key that has a literal , in it and {{num}} options, { 'num': 1 })'
});
```
This will cause a lookup for the key "some other key that has a literal " instead of "some other key that has a literal , in it and {{num}} options". It would be nice if there was a way to escape the key or an option to change the separator character for the key and the options.

**Comment by jamuhl** [comment]
Feel free to provide a PR - relevant code line should be here: https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L160

**Comment by jamuhl** [comment]
i18next@19.3.0 has a new option: `options.interpolation.nestingOptionsSeparator: ','` hope that helps

**Comment by mgroenhoff** [comment]
Thanks! I think it would. Would you mind adding it to the TypeScript types :relaxed:?

**Comment by jamuhl** [comment]
just for you i18next@19.3.1 😁

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:

**Comment by mgroenhoff** [comment]
Awesome! Thank your for the quick feedback. 👍
