### ISSUE TITLE
Tree shaking support

### ISSUE THREAD

**Issue by stalniy** [i18next/i18next#1396]
First of all, thank you very much for this library, it's awesome! :)

It'd be good to have a tree shaking support, so the unused functionality (like pluralization or interpolation, namespaces) can be shaked out by webpack or rollup in order to reduce the resulting app bundle size

**Comment by jamuhl** [comment]
can you elaborate a little on that request...how should that technical work - even how should that be technical possible?

**Comment by stalniy** [comment]
Rollup & Webpack are JavaScript bundlers. Thanks to ES6 static import/export they can analyze the source code imports and mark non import exports as unused. Later this unused exports are removed by uglifier (at least this is how it works in webpack). 

For more info take a look at this:
-  https://www.codingame.com/playgrounds/7463/tree-shaking-in-javascript-with-rollup
- https://webpack.js.org/guides/tree-shaking/
- https://medium.com/javascript-in-plain-english/tree-shaking-in-javascript-bundlers-cf5c9583b13d

**Comment by jamuhl** [comment]
I know how tree shaking works...I ask you how you would add this to i18next where features used is determined by the runtime - not build time...

**Comment by stalniy** [comment]
So, then your question was quite unclear, dont' you think so? ;)

The only way to do is during build time and it's quite doable. Make a library to be configurable via plugins. For example:

```js
import i18next from 'i18next' // fully featured i18n with all plugins enabled - full bundle

import { i18n, pluralize } from 'i18next' // i18n refers to core logic only

export default i18n()
  .use(pluralize())

// it can also be more OOP way
import { I18n, Pluralizer } from 'i18next' // uses only core and pluralization logic

export default new I18n({
  Pluralizer
});
```

**Comment by jamuhl** [comment]
The only part currently I see that might work this way is the plurals. Interpolation is used by other plugins too (mostly the backends). While currently, I might be open for a PR adding this - it's not completely the right direction I like to go in the future. The plan looks more to make the i18n format a plugin so interpolation, plural will get part of a i18n format you can choose of. i18next-icu, i18next-fluet are example of this...the i18next format might be such a plugin in future too.

So it will be something like:

```js
import { I18n, I18nextFormat } from 'i18next' // uses only core and pluralization logic

export default new I18n({
  i18nFormat: I18nextFormat
});
```

**Comment by stalniy** [comment]
I see.

 It’s a pity because I wanted to use this lib on one of my projects. I used it like 6 years ago and it was really helpful. 

Unfortunately 37+ KB of minified code for i18n service is too much in my opinion. 

I looked to the libs which have similar functionality and they are smaller - https://www.npmtrends.com/i18next-vs-vue-i18n-vs-node-polyglot

I thought that it’d be possible to remove something  unused to shrink the size but

So then fill free to close this issue as I will try to find some alternative library for now.

**Comment by jamuhl** [comment]
The problem is comparing bananas with apples - i18next is the only library in the field that adds more functionality than an i18n syntax runtime.

Means if you do not need: language detection, backend integrations, the runtime missing feature, flexible fallback handling, ... then yes - i18next has too many features for your case.

And it's 10kb gzipped ;) https://bundlephobia.com/result?p=i18next@19.1.0

**Comment by hc-codersatlas** [comment]
It's not that we dont' "need" all the features, but for different projects it may not be all of it but in different permutations. Proper treeshaking support would fix all of this. It's likely a better idea than creating plugins manually as tools like webpack and/or even native js has worked this out already and more efficiently.

**Comment by jamuhl** [comment]
@hc-codersatlas plugins are there for a good reason...and:

- not every environment that consumes i18next depends on webpack
(- webpack won't be here forever  (believe it or not))
- adding all plugins in the main js module would lead to a big problem -> who does assert the quality of those? eg. just the backends https://www.i18next.com/overview/plugins-and-utils#backends

but might be I miss some feature of native js that does it better - so would be happy to learn some more details to make this better

**Comment by hc-codersatlas** [comment]
@jamuhl maybe webpack is a bad choice of words. It could be rollup, or anything - a build tool. A bit further back was grunt and then some pre-processing was then on the server side - doesn't matter. It's the idea of it - which has always existed.

I'm not sure about the 3rd party 1s - maybe it should be a plugin, but there are 1st party 1s unless I'm mistaken so...

> The problem is comparing bananas with apples - i18next is the only library in the field that adds more functionality than an i18n syntax runtime.

Not sure what does this have to do with performance and/or optimizing it? There's always room for improvement? Does it always have to be take 1 and not the other? How about the only library that adds more functionality and is smaller / faster?

**Comment by jamuhl** [comment]
> Not sure what does this have to do with performance and/or optimizing it? There's always room for improvement? Does it always have to be take 1 and not the other? How about the only library that adds more functionality and is smaller / faster?

Nothing said against that. Like always - i18next is a community project - if you like to help - we happily accept a PR.

**Comment by stalniy** [comment]
> The problem is comparing bananas with apples - i18next is the only library in the field that adds more functionality than an i18n syntax runtime.
> 
> Means if you do not need: language detection, backend integrations, the runtime missing feature, flexible fallback handling, ... then yes - i18next has too many features for your case.
> 
> And it's 10kb gzipped ;) https://bundlephobia.com/result?p=i18next@19.1.0

No, it’s not :) check node-polyglot for example. 

Backend integration should be as simple as:

```JS
i18n.onChange(lang => import(`./langs/${lang}.json`))
```

Check [vue i18n for the real example](https://kazupon.github.io/vue-i18n/guide/lazy-loading.html)

**Comment by stalniy** [comment]
On bundlephobia please pay attention to download time. It’s 100ms slower than for [vue-i18n](https://bundlephobia.com/result?p=vue-i18n@8.15.4) as an example

**Comment by jamuhl** [comment]
@stalniy you're right...feel provide a PR

**Comment by zsolt-dev** [comment]
I am currently trying to switch from i18next due to bundle size. Its not only about download times but "time to interactive" too.

My whole project in preact is smaller than i18next. 

I think bundle size should be taken more seriously. 

I am trying to switch to:
https://bundlephobia.com/result?p=@lingui/core@2.9.1

**Comment by adrai** [comment]
@zsolt-dev If bundle size is that important for you I can understand.
I would appreciate if you could help on how to optimize i18next even more...
Can you share some insights on your app? How is it possible it is smaller than i18next?
Are you bundling also the translations? If so why not lazy load them with something like i18next-http-backend?
Can you also share some information about your “time to interactive”.
Any help is welcome.

**Comment by jamuhl** [comment]
To finally close this...

**If your project is smaller than 50kb -> don't use an i18n lib at all**

If your project is bigger -> using i18next might have benefits...

Stop comparing with other i18n libs that just load one language set -> There I would say don't waste your download limit and use an object, lodash.get and the browsers Intl API for plurals.

I18next is about getting the job done - done right and with flexibility in what you can do...show me one i18n lib having more freedom of doing things, have a that huge ecosystem of backends, frontend integrations, parsers, ... plus comes with a translation management as a service https://locize.com which makes both developers and translators life easier.

Never forget...i18n is just one part in the puzzle -> the biggest part is not developers job but translators, localization managers, content creators.

And to have a last word...find any js lib that has a almost 10 years of history and is more or less still backwards compatible with v1!!! There are more important things than 10kB

**Comment by bay007** [comment]
I haven't added in formkit's i18n support 
```js
//removed
import { es, en } from "@formkit/i18n";
```

My final bundle is about 700 kb, analyzing bundle size distribution i had watched i18n is about 500K, from my perspective is a lot.


![image](https://github.com/i18next/i18next/assets/8164038/293d56b1-f6a8-40f0-907f-2b1355053384)



my package.json versions
```json
"dependencies": {
		"@formkit/addons": "1.5.0 ",
		"@formkit/themes": "1.5.0 ",
		"@formkit/vue": "1.5.0 ",
.
.
.
```
