### ISSUE TITLE
Uncaught Error: Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by reZach** [i18next/i18next#1397]
Hello,

I've [build my own i18next backend](https://github.com/reZach/i18next-electron-fs-backend), and I'm seeing an error when the framework `callback` is being executed, might you know what could be going on? I'll obviously be investigating further but I thought I should ask first. It appears this happens when calling the `read` method.
```javascript
read(language, namespace, callback){
  readfile(filename, (error, data) => {
    // when we get here, 'data' is an empty object, this is what matches my translation file

    if (error) return callback(error, false); // no retry
    callback(null, data); // looks like the error is thrown here
}
```

**error**
Cannot read property 'split' of undefined

The i18next version I am using is 19.0.3.

**Comment by reZach** [comment]
The problem looks to be occurring on [this line](https://github.com/i18next/i18next/blob/9787aa76d63e75f22ccc025868fe60b3f7f3ea37/src/i18next.js#L246).

**Comment by reZach** [comment]
Hold on, let me add more detail later as I work through this.

**Comment by reZach** [comment]
I've made a MVP for you to test this problem. Please follow the steps [here](https://github.com/reZach/broken-i18n). (simple install git repo, install deps and run)

What I am seeing is we call the "read" method for the backend. The read method finds no values for translations in the file (notice `data` is an empty object - I expect this to be a common use-case, that is why I posted this issue here), and then calls the `callback` parameter.
![image](https://user-images.githubusercontent.com/4740370/74703018-85060380-51d1-11ea-9c30-956a66229947.png)

The i18next _eventually_ calls a callback when trying to load namespaces. 
![image](https://user-images.githubusercontent.com/4740370/74702850-f5605500-51d0-11ea-9ee2-f153a7631ed4.png)

...but then fails because it is not initialized and throws the error?
![image](https://user-images.githubusercontent.com/4740370/74702907-2b9dd480-51d1-11ea-9af2-b67402de4c45.png)

![image](https://user-images.githubusercontent.com/4740370/74703143-df9f5f80-51d1-11ea-9b4e-d8a868139249.png)

**Comment by jamuhl** [comment]
Tried to get more information where the error happens -> seems it's during the setT which is nothing than the setState function of useState -> so this is not an issue with i18next but might have todo with react + electron - as we do not get this on reactjs used in web/react-native. Rather strange...

**Comment by reZach** [comment]
Thanks for looking at this. I'm willing to spend a day or two trying to get i18next-react working in electron, can you tell me the instructions for getting i18next-react to work locally? (I plan to add log messages and debug that to test around).

Is it?
Clone i18next-react
`npm i`
`npm run build`??

**Comment by jamuhl** [comment]
yes `clone -> npm i -> npm run build` or going to the node_modules folder of your electron project and add the console.log there directly

**Comment by reZach** [comment]
@jamuhl Here is what I found (perhaps we can move this issue to react-i18next repository as issue belongs there. Github has a transfer feature I think):

[This code](https://github.com/facebook/react/issues/13991#issuecomment-435587809) needs to be added in your (my) own projects, otherwise you see this error when loading your library. It fixes #3 (I'm _pretty_ sure).
```javascript
module.exports = {
  // other config
  resolve: {
    alias: {
      react: path.resolve("./node_modules/react")
    }
  }
};
```

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

I don't know where this is actually happening in the repo (i18next-react) itself, but it's getting added somehow.

Anyways, adding that and we eventually get the error again `Uncaught Error: Uncaught TypeError: Cannot read property 'split' of undefined`. What is interesting is that the line it fails on is when we get to `React.createElement`, _but_ if you call that by itself the error doesn't get thrown, it's only when we return do we see the error.
![image](https://user-images.githubusercontent.com/4740370/74796423-25b9f900-528e-11ea-83c0-0973d63d9b9d.png)

Maybe this can point you to something in the framework?? Doesn't this get rendered inside `<I18nextProvider>` somehow or another thing?

**Comment by jamuhl** [comment]
If you do not return the created element - it only get's created but never rendered -> no render loop - no reconciliation - no problem...

**Comment by reZach** [comment]
Ok. I'm going to try and also clone i18next locally and find all places `.split` is called and then maybe we can figure out what is happening here. I'll try later today.

**Comment by jamuhl** [comment]
I got a bad feeling it's not inside i18next, react-i18next but in react or react-dom

**Comment by reZach** [comment]
The googling I've done so far leads me to believe that these issues are in libraries and not react/react-dom. We will see when I investigate (or get closer to the issue).

**Comment by reZach** [comment]
@jamuhl it turns out the issue was in my backend. I was using a local variable named the same as my parameter, `key`, and that was causing `key` to be undefined. Calling `.split()` on it threw the error.

[The backend](https://github.com/reZach/i18next-electron-fs-backend) has been updated (1.3.1) and I'm closing this issue, thanks for looking at this with me.

**Comment by jamuhl** [comment]
@reZach glad you stayed on it and found the cause...👍
