### ISSUE TITLE
Typescript BackendConnector data 

### ISSUE THREAD

**Issue by madlandproject** [i18next/i18next#1400]
There is an issue with i18next's typings when writing a backend plugin in typescript. With the current typing it isn't possible to avoid the retry loop.

The `BackendConnector` code checks if the `data` parameter is "truthy" in combination with an non-null `error` parameter to determine whether to retry or not.

https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L137

However the typings for this process are the following. 

```
// I have only included the relevant types/members here for brevity

export type ResourceKey =
  | string
  | {
      [key: string]: any;
    };

export type ReadCallback = (err: CallbackError, data: ResourceKey) => void;

export interface BackendModule<TOptions = object> extends Module {
  read(language: string, namespace: string, callback: ReadCallback): void;
}

```

I think the ReadCallback Typing should look more like this:

```
export type ReadCallback = (err: CallbackError, data?: ResourceKey|boolean) => void;
```

I'm relatively new to i18next and I'm not sure this is the best solution. Thanks for your input.

**Comment by jamuhl** [comment]
@rosskevin looks correct to me...you agree? If so, I hope @madlandproject provides a PR?

**Comment by rosskevin** [comment]
`data?: ResourceKey|boolean` is the same as `data: undefined|ResourceKey|boolean`.

If it can be undefined then yes, that looks like the right change.

**Comment by madlandproject** [comment]
`data: undefined|ResourceKey|boolean` forces you to pass a second parameter:
`callback(new Error(`Backend loading error`), undefined);`

Whereas `data?: ResourceKey|boolean` doesn't:
`callback(new Error(`Backend loading error`));`

Given the code checks truthy-ness of the second parameter, the second solution is better for shorter code, but if you would rather require an explicit second parameter `data: ResourceKey|boolean` should suffice.

I can prepare a PR for whichever you prefer.

**Comment by rosskevin** [comment]
Technically I agree with you @madlandproject - I was just noting that `undefined` was accepted when using `?` and if that's right for the runtime, then it's the right proposal.  I should have chosen my words more carefully, sorry.

Please PR, and be sure to add an additional usage test in `test/typescript`
