### ISSUE TITLE
Multiple levels of nesting

### ISSUE THREAD

**Issue by peterjuras** [i18next/i18next#1401]
Hi!

Is it possible to do multiple levels of nesting? Right now I have a use case where I want to capitalize a string in one language but not another. The string however should also use other resource keys. As an example, right now I have to structure my code in the following way, since nesting `$t` is not possible:

```ts
const keys = {
  "capitalize": "{{text, capitalize}}",
  "greeting": "$t(single-greeting, {'name': '{{name}}', 'context': '{{gender}}' })",
  "single-greeting_male": "Lieber {{name}}",
  "single-greeting_female": "Liebe {{name}}"
};
const string = t("capitalize", { text: t("greeting", { name: "Alex", gender: "male" });
```

This is not optimal, since I have languages where the first letter should not be capitalized. Is there the possibility or a plugin which allows multiple nested `$t` calls? I'd imagine it in the following way:

```ts
const keys = {
  "capitalize": "{{text, capitalize}}",
  "greeting": "$t(capitalize, { 'text': $t(single-greeting, {'name': '{{name}}', 'context': '{{gender}}' }) })",
  "single-greeting_male": "Lieber {{name}}",
  "single-greeting_female": "Liebe {{name}}"
};
const string = t("greeting", { name: "Alex", gender: "male" });
```

**Comment by jamuhl** [comment]
Never tried...but I guess nesting in "nesting options" does not work -> but never tried.

you might also try format to uppercase first letter depending on language... the format function gets that passed in: https://www.i18next.com/translation-function/formatting#basic
