### ISSUE TITLE
defaultValue not working in nested function $t

### ISSUE THREAD

**Issue by FortinFred** [i18next/i18next#1402]
As stated in the documentation, it's possible to pass options to be nested.

https://www.i18next.com/translation-function/nesting#passing-options-to-nestings

I have been trying to get the defaultValue to work without success.

```
nestedKey: '$t(MISSING_KEY, { "defaultValue": "HELLO" })'
```
I still get MISSING_KEY.

**Comment by jamuhl** [comment]
documentation says it's possible to pass options to nested - defaultValue is not an option -> it is the defaultValue on the `t` call (so you can't pass that down to some inner options)

**Comment by FortinFred** [comment]
Wow that was fast !!! :) Thanks,

It's obvious there's something I'm not getting here.

I tought that $t was a proxy call to the `t` function for which we have the following options:

https://www.i18next.com/translation-function/essentials#overview-options

defaultValue is listed in the options of the `t` function.

I'm confused

**Comment by jamuhl** [comment]
While it looks like a proxy and almost do that - there are limitations...like eg. you can't define a defaultValue for the inner `$t` from the outer `t` call...

what you can do is mapping a value to the count `$t(girls, {'count': {{girls}} })` <- takes the girls value and maps that to count...
