### ISSUE TITLE
Add Support for Subfolders (localeStructure)

### ISSUE THREAD

**Issue by DovahBrownies** [i18next/i18next#1404]
Is it possible to add support for subfolders in the `locales` folder? So, for example, instead of:
```
.
└── locales
    └── en
        ├── home.json
        └── header.json
```
We'd be able to do:
```
.
└── locales
    └── en
        ├── pages
        |   └── home.json
        └── components
            └── header.json
```

by setting the `localStructure` as something like: `{{lng}}/{{dir}}/{{ns}}`

I think this would open up doors for a neater structure.

**Comment by jamuhl** [comment]
How do you get the `dir` value? We do know which language and which namespace to load - but from where should we get the directory?

An option to do this would be an own backend: https://www.i18next.com/misc/creating-own-plugins#backend

**Comment by DovahBrownies** [comment]
Perhaps an extra argument can be added to `withTranslation()` where `dir` can be specified?
`withTranslation('common', 'pages')(HomePage)`

**Comment by jamuhl** [comment]
So you need to know the directory everywhere you define loading namespaces...all API functions loadNamespaces, hasLoadedNamespace,....and even the init array of namespaces...

If you ask me - this is not an improvement...but if you really need this I would go with a custom backend and define some sort of map for namespace -> dir

**Comment by DovahBrownies** [comment]
Understood.

**Comment by haggen** [comment]
Why not support slashes inside namespaces, e.g. `withTranslation("pages/home")(Home)`. Now itwould be just a matter of using the namespace as a dumb string part of the locale file path. Nothing fancy going on. i.e. `localesDir + namespace` which I believe is more of less what it's being done, right?

**Comment by jamuhl** [comment]
not tested...but I guess there is no reason a namespace can not include a `/`
