### ISSUE TITLE
Context information in cimode

### ISSUE THREAD

**Issue by mskelton** [i18next/i18next#1405]
In our application, we are wanting to use cimode for end-to-end testing, but one thing that we are struggling with is translations with context.  For example, a translation such as `4 apples` that is called like so: `t('apples', { count: 4 })` will return `apples` in `cimode`.  The problem is we have no way to test that we properly passed a count of 4 to the `t` function.

What would the recommended approach to this problem be?

**Comment by jamuhl** [comment]
Honestly no idea...in my over ten years working with i18next I never tested my applications translations using unit tests and CI mode. We had end-to-end tests but those used the fallback language in most cases.

You might intercept the function with sinon and test the passed params...

**Comment by mskelton** [comment]
Thanks for the insight!
