### ISSUE TITLE
I would like to translate url-like strings

### ISSUE THREAD

**Issue by rmariuzzo** [i18next/i18next#1406]
Given the following resources:
**`en.json`**
```json
{
  "route.home": "/:language/home"
}
```
**`es.json`**
```json
{
  "route.home": "/:language/inicio"
}
```

I would like to use this lib as:
```ts
i18n.t('route.home')
```

I'm getting: `language/home` instead of `/:language/home`. I tried disabling interpolation and other configs without success. Is that currently possible?

**Comment by rmariuzzo** [comment]
I found a way to do it changing the `nsSeparator` to something different than the default: `:`.

**Comment by jamuhl** [comment]
Are you sure you're sample above is correct? I got zero issues with getting `/:` inside a value -> values get only interpolated, nested, ... but not handled by nsSeparator...also `i18n.t('route.home')` would expect nested json so you would have to set keySeparator to false...
