### ISSUE TITLE
How to apply a formatter in nested translations

### ISSUE THREAD

**Issue by saveman71** [i18next/i18next#1407]
I'm sharing [this question](https://stackoverflow.com/q/38867564/2367848) here:

> 
> I would like to format nested translations with i18next
> 
> Given the resources:
> 
>     {"translation":{
>        "en":{
>          "food" : "bread",
>          "food_is_good" : "$t(food), that's not bad"
>         }
>      }
> 
> and a formatting function:
> 
>     function format(value, format, lng) {
>       if (value==undefined) return value;
>       switch (format) {
>           case 'capitalize': return _.capitalize(value);
>           default : return value;
>       }
>     }
> 
> that is used in the initialization of i18next:
> 
>     ...
>     interpolation: { format: format },
>     ...
> 
> I would like the output to be "Bread, that is not bad".
> So I hoped that something like:
> 
>     {
>       ...
>       "food_is_good_1" : "$t(food,capitalize), that's not bad",
>       "food_is_good_2" : "{{$t(food),capitalize}}, that's not bad",
>       "food_is_good_3" : "{{food,capitalize}}, that's not bad",
>       ...
>      }
> 
> would do the trick. 
> The first option displays errors : `"failed parsing options string in nesting"`
> The last two options warn: `missed to pass in variable food,capitalize for interpolating {{food,capitalize}}` 

Is this possible? If not, what's missing to implement this?

**Comment by jamuhl** [comment]
There are two things...

a) nesting happens after interpolation -> food_is_good_2, food_is_good_3 do not work
b) nesting has options -> having a `,` does trigger options parsing not format handling

Might be it's enough to handle format here https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L188 like done here https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L129

**Comment by saveman71** [comment]
Permalinks of the above links:

https://github.com/i18next/i18next/blob/233eb5a3d43e4cfdfc9e09f63bdf82021de38014/src/Interpolator.js#L188

https://github.com/i18next/i18next/blob/233eb5a3d43e4cfdfc9e09f63bdf82021de38014/src/Interpolator.js#L129

:)

>nesting happens after interpolation

so the capitalize filter would have no idea of the value of the nested field anyway?

**Comment by jamuhl** [comment]
`{{$t(food),capitalize}}, that's not bad` even if the order would be different and nesting would happen first -> it would nest `bread` and interpolation would search the variable bread in the t options to be interpolated and formatted -> therefor the above links where formatting might be added for nested values...
