### ISSUE TITLE
Moving to Typescript question

### ISSUE THREAD

**Issue by javierguzman** [i18next/i18next#1408]
Hello!

I am moving my express/react application into Typescript and in express I am moving the auth middleware at the moment:
```
export const isLoggedIn = (req: Request, res: Response, next: NextFunction) => {
  if (req.isAuthenticated()) {
    next();
  }
  return res.status(401).send({
    type: errorTypes.LOGIN_ERROR_LOGIN_NEEDED,
    payload: req.t(`auth:${errorTypes.LOGIN_ERROR_LOGIN_NEEDED}`)
  });
};
```
The issue is that Typescript does not complaint about req.isAuthenticated as I have installed @types/passport therefore it detects that Request has that function. However, for t I get the following message:
'Property t does not exist on type 'Request<ParamsDictionary'' 

As far as I understand i18next is done in Typescript and it should be able to grab that automatically as with isAuthenticated, isn´t that right?

I know I can fix the problem by creating my own Request interface extending from Request and adding t as TFunction. However, I would like to know if what I am observing is normal.

Thank you in advance and kind regards.

**Comment by jamuhl** [comment]
I don't know. There are some types here: https://github.com/i18next/i18next-express-middleware for the express stuff...but not sure (zero interested in typescript)

**Comment by javierguzman** [comment]
Hello @jamuhl ! I already use that middleware so if it does not grab it automatically then I guess I will have to continue using the fix I mentioned before. Maybe if I become more familiar to TS I will be able to understand the reasons, but so far this should do.

Thank you for your help!
