### ISSUE TITLE
[ASK] Is good idea to use interval to execute i18next.reloadResources continuously?

### ISSUE THREAD

**Issue by laodemalfatih** [i18next/i18next#1409]
Example:

```js
i18next.init();

setInterval(() => {
  i18next.reloadResources();
}, 86400000); // Reload resources every one day
```

**Comment by jamuhl** [comment]
serverside? clientside it seems to be useless as mostly a session won't be a day long - I guess - but might be different for your project - idk?

**Comment by laodemalfatih** [comment]
right, what i mean is server side.

**Comment by jamuhl** [comment]
On serverside it can make sense - if it does not restart anyway ;)

We also do that for our i18next-node-locize-backend as default to assert servers get updated.

**Comment by laodemalfatih** [comment]
Thanks
