### ISSUE TITLE
Backend Connector load the namesapaces in a component and don't in other 

### ISSUE THREAD

**Issue by SaadEla** [i18next/i18next#1411]
I am using Whithnamespaces
My i18n config
![code](https://user-images.githubusercontent.com/45466806/77561433-f9ae1b00-6ebe-11ea-8552-cc2d16e9e4ca.png)

It charge in this component and don't charge in other one
![image](https://user-images.githubusercontent.com/45466806/77561568-2a8e5000-6ebf-11ea-9b06-228f309c8356.png)

**Comment by SaadEla** [comment]
I get also this false warning
![image](https://user-images.githubusercontent.com/45466806/77562201-0121f400-6ec0-11ea-9c60-2cfcb6268916.png)

**Comment by jamuhl** [comment]
the warning can't be wrong...please provide a codesandbox for reproduction...rather sure you do not use HOC or hook somewhere or set useSuspense to false on it...

what version are you using...withNamespaces is outdated

**Comment by SaadEla** [comment]
This is how i use it it work in a component and don't work in other
![code](https://user-images.githubusercontent.com/45466806/77567603-b310ee80-6ec7-11ea-9f63-0df09422c16e.png)

**Comment by jamuhl** [comment]
I don't see anything wrong...but honestly why you're using v9 and not current version?

you will have to provide a full sample on codesandbox for reproduction

**Comment by SaadEla** [comment]
"i18next": "^19.3.3"
"i18next-xhr-backend": "^3.2.2"
 "react-i18next": "^9.0.10"

**Comment by SaadEla** [comment]
i think that the v9 is the last v of react-i18next?

**Comment by SaadEla** [comment]
really i can t see the pb why the backend connector is charging namespaces in some components and not in others

**Comment by jamuhl** [comment]
v10 is current version...and namespaces are loaded if not already loaded...

**Comment by SaadEla** [comment]
In this component it s not working

![image](https://user-images.githubusercontent.com/45466806/77569484-91653680-6eca-11ea-884d-49b1e11b637b.png)

In this one it s working 

![image](https://user-images.githubusercontent.com/45466806/77569569-af329b80-6eca-11ea-8d21-103e8bd060bb.png)



AND REALLY SORRY SORRY FOR DISTURBING U

**Comment by jamuhl** [comment]
Is the component that does not work in a subfolder?

**Comment by SaadEla** [comment]
![image](https://user-images.githubusercontent.com/45466806/77570234-b4dcb100-6ecb-11ea-803d-985f12ab5894.png)

**Comment by jamuhl** [comment]
Then I would check the network tab and see what the content of that `locales/fr/auth.json` call is when failing...as it seems non valid json

**Comment by jamuhl** [comment]
did you found the issue?

**Comment by jamuhl** [comment]
?

**Comment by SaadEla** [comment]
Nooop and it's not a json problem i check it if valid. I am trying all i can  ^^

**Comment by jamuhl** [comment]
you get an error here: https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L60 so something is wrong there...like said...there must be something wrong...just set a breakpoint...must be on your side...

**Comment by SaadEla** [comment]
But the warning still show on working component's..

**Comment by jamuhl** [comment]
On the working component it says something about namespace `translation` which is the default namespace defined in i18next. Which you can remove by setting eg. `ns: ['auth'], defaultNS: 'auth'` on i18next init

**Comment by SaadEla** [comment]
yes but after that it shows the riht ns auth wich i gived as param in whithenamespaces HOC

**Comment by jamuhl** [comment]
yes...there it works...but I'm interested in the non working ResetPassword console output...=> where it says it can't be parsed

**Comment by SaadEla** [comment]
yes i know but it's valid json format 100%

**Comment by jamuhl** [comment]
Obviously you get something else loaded there - as JSON.parse does not throw an error just because it's in the mood...why not just set a breakpoint and look?

**Comment by SaadEla** [comment]
i have found a thing my second componant had a route whith parameter(/reset/:email), i deleted the parameter (turning it to a simple route /reset) in the route and it's worked. so it was due the route whith parameter?

**Comment by SaadEla** [comment]
update: it don't work also in child routes (/reset/pass/page)

it work just on routes like (/reset)

**Comment by jamuhl** [comment]
again... check the network tab -> you would see you don't get the auth.json file

Your set path: `locales/{{lng}}/{{ns}}.json` is a relative path

change it to `/locales/{{lng}}/{{ns}}.json` like the default is https://github.com/i18next/i18next-xhr-backend#backend-options and it will work

**Comment by SaadEla** [comment]
it worked i love u
--> i go donate u are my savior

**Comment by jamuhl** [comment]
glad we found it ...
