### ISSUE TITLE
Interpolation and nesting

### ISSUE THREAD

**Issue by YassineDM** [i18next/i18next#1412]
In the following example, I don't know if it is a JSON parsing error but I can't seem to make interpolation and nesting work:
namespaceA.json
```json
{
	"keyA1": "{{text}} interpolated"
}
```
namespaceB.json
```json
{
	"keyB1": "Text to interpolate",
	"keyB2": "$t(namespaceA:keyA1, {'text': '$t(keyB1)'})"
}
```
I expect:
```javascript
i18next.t('namespaceB:keyB2');
// -> 'Text to interpolate interpolated'
```
But get:

> keyB1,{"text". "keyB1' }

**Comment by jamuhl** [comment]
Why is everyone so keen on interpolate nestings into interpolated nestings...

Short story...does not work...you can't pass nestings as interpolations values inside nesting...

**Comment by YassineDM** [comment]
Ok thx, I will think of a workaround...
