### ISSUE TITLE
en-us does not fallback to en

### ISSUE THREAD

**Issue by bogdansoare** [i18next/i18next#1414]
<img width="552" alt="Screenshot 2020-03-27 at 10 18 16" src="https://user-images.githubusercontent.com/2750170/77736082-64bd3600-7014-11ea-9f35-871d85e393b8.png">

I'm using this options 
```
.init({
    fallbackLng: "en",
    debug: true,

    interpolation: {
      escapeValue: false 
    }
  });
```

What am I doing wrong?

**Comment by jamuhl** [comment]
depends on what you're doing ;)

seems you're using the xhr-backend which does not be able to load the initial namespace `translation`

**Comment by bogdansoare** [comment]
yes, I don't have an `en-us` translation file I have a `en` translation
should I provide an explicit whitelist ?

**Comment by jamuhl** [comment]
you can set init option `load: 'languageOnly'`

**Comment by bogdansoare** [comment]
understood, thank you for the info 🙏
