### ISSUE TITLE
Language override not working

### ISSUE THREAD

**Issue by sagendejonge** [i18next/i18next#1416]
I am trying to show two languages at once.  Language is set to English (en), but for specific text, I also want to show Japanese (jp).  From the documentation I assumed this would work to get Japanese when needed:

`i18n.t("name", { lng: "jp" })`

However, it still comes out as English.

**Comment by jamuhl** [comment]
should work - at least if the key `name` in the namespace `translation` in language `jp` is available...else it depending on your setup will fallback to key `name` or whatever is defined and loaded in fallbackLng

**Comment by MartijnR** [comment]
I am experiencing the same as @sagendejonge. The translation is available, and the override `lng` is part of the `whitelist` used to initialize i18next.

**Comment by MartijnR** [comment]
Figured it out. Sorry about that. For my use case when switching to another language I should just call `i18next.changeLanguage( lng );` first.

**Comment by adrai** [comment]
@sagendejonge do you still have this issue?

**Comment by sagendejonge** [comment]
@adrai Yes, this is still an issue for me. I can provide a minimal example if that helps?

Btw, I haven't tested @MartijnR solution yet, but that seems like a workaround as expected behaviour would be to return whatever language passed into i18n.t("name", lng_choice) for 'lng_choice' right?  Of course, if it is available, which it is in my case.

**Comment by jamuhl** [comment]
@sagendejonge If the extra language was loaded (which does not happen magically) it works...but sure...feel free to provide a codesandbox for reproduction

**Comment by jamuhl** [comment]
closing due inactivity...feel free to reopen with reproducible sample

**Comment by jessicaonly** [comment]
Hi! If anyone found this the way I did, @jamuhl hinted at it with his comment about loading the language -- an more explicit solution to get this to work is:

(in your `i18next.init`, passed in as an option)

```
i18next.init({
... 
// whatever other options you have, e.g. lng 
preload: ['jp', 'es', 'en'...]
...
```

The language that you want to translate to (in this case, Japanese) has to be preloaded for this to work. More info here: https://www.i18next.com/overview/configuration-options -- after that, `i18n.t("name", { lng: "jp" })` should work!

**Comment by MasteringBOX** [comment]
@jessicaonly I have added the preload option but I still can't use this feature. Any thoughts?

**Comment by anatoly314** [comment]
@jessicaonly, try this code if you still have the issue:

````js
const i18nextOptions = {
    debug: true,
    initImmediate: false,
    fallbackLng: 'en',
    lng: 'en',
    preload: ["en", "de"],
    ns: 'translation',
    defaultNS: 'translation',
    backend: {
        loadPath: './src/i18n/locales/{{lng}}/{{ns}}.json'
    }
}


i18n
    .use(FsBackend)
    .init<FsBackendOptions>(i18nextOptions)


await i18n.changeLanguage("en")
console.log(i18n.t('home.title', {
    lng: "de"
}))
````
