### ISSUE TITLE
Fallback without considering country code

### ISSUE THREAD

**Issue by 1valdis** [i18next/i18next#1422]
I have the following config for `init`:
```javascript
{
    preload: ['no', 'en'],
    load: 'languageOnly',
    fallbackLng: {
      nb: ['no'],
      nn: ['no'],
      default: ['en'],
    },
    backend: {
      loadPath: path.resolve(__dirname, 'locales/{{lng}}.json'),
    },
}
```
If I send something like `nb-NO` here, it falls back to `en` instead of `no`, having this array of languages in the request (I'm using Express middleware): `["nb", "en"]`.
How do I fallback any `nb*` or `nn*` language, with or without country code, and any `no*` language with code to just `no`? The docs didn't help with that.
<details>
  <summary>Offtopic</summary>
  I was using `i18n` previously and I find out it was immensely easier to accomplish in it, I had to pass `no` and `en` locales to it and

```
fallbacks: {
  nb: 'no',
  nn: 'no',
},
```
and it would just work, setting `en` for any non-nb*, nn*, or no* language. And now I'm messing with that for 2 hours trying to get it working...
</details>

**Comment by jamuhl** [comment]
https://www.i18next.com/principles/fallback#fallback-language

there is no wildcard -> you have to define every language `nb-NO` , ...

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L76

guess adding : `if (!found) found = fallbacks[this. getLanguagePartFromCode(code)];` would make it work for your usecase

**Comment by adrai** [comment]
PR: https://github.com/i18next/i18next/pull/1424

**Comment by 1valdis** [comment]
Wow, that is an incredibly swift response. Thank you very much!

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “💜Sponsor Button”.

There are many ways to help this project 🙏
