### ISSUE TITLE
Unexpected looping when using unescaped interpolation

### ISSUE THREAD

**Issue by sgoldthorp** [i18next/i18next#1423]
I am finding that when the string I pass in for interpolation contains the characters "$&" everything before and after gets repeated 1000 times. For example, if my translation is `'test' : '{{- test}}'`, `i18next.t('test', {test: '$&foo'})` returns 'foofoofoofoo...' (repeated 1000 times). `i18next.t('test', {test: 'bar$&foo'})` returns 'barbarbar...foofoofoo...' (everything before * 1000, everything after * 1000). The error being logged is `i18next::interpolator: missed to pass in variable - test for interpolating`. The issue does not happen when the unescape character is removed. Thanks.

**Comment by jamuhl** [comment]
PR welcome

**Comment by adrai** [comment]
@sgoldthorp Which i18next version are you using? Can you try with v19.4.1 ?

**Comment by adrai** [comment]
@sgoldthorp btw: welcome to GitHub ;-)

**Comment by sgoldthorp** [comment]
@adrai Thanks - we're currently on 13.1.5. Will try the latest version

**Comment by sgoldthorp** [comment]
@adrai Updating to v19.4.1 fixed it - thanks

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.
If you liked my support / work - I would enjoy a coffee sponsored using the “💜Sponsor Button”.
There are many ways to help this project 🙏
