### ISSUE TITLE
resources option is only applied for one language

### ISSUE THREAD

**Issue by namlt3820** [i18next/i18next#1425]
## Describe the bug
I’m trying to migrate my react code to nextjs code, and I intend to send all translations (english and japanese) to my client so that user can switch freely without making a call to server. I didn’t use the usual way of storing translation (public/static/locales/`lg`/`ns`), instead I used the resources option, like this:
```javascript
const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'en',
  otherLanguages: ['jp', 'en'],
  lng: 'en',
  fallbackLng: 'en',
  preload: ['jp', 'en'],
  defaultNS: ['translations'],
  ns: ['translations', ‘header’, ‘footer’,…],
  use: [initReactI18next],
  resources: {
    en: {
      ….
    },
    jp: {
      …
    },
  }
});
```
But for some reason, only the english translation got included in the resources sent to the client. When I called i18next.changeLanguage(‘jp’), the client tried to query the static/locales/jp folder from the server, which of course failed. But when I refreshed the page, I got the japanese translation in resources, along with the english one. So I think I’m missing some configuration option here, to send all translations to client. 

## Occurs in next-i18next version
 "i18next": "^19.0.3",
"react-i18next": "^11.2.7",
"next-i18next": "^4.2.1",
"next": "^9.3.1",

## Steps to reproduce
I think the nexti18next instance I used above caused the problem.

## Expected behaviour
To send all translations to client via resource option.

## OS
 - Device: MBP OS High Sierra
 - Browser: Firefox 74.0

**Comment by jamuhl** [comment]
please open your request over at: https://github.com/isaachinman/next-i18next
