### ISSUE TITLE
initReactI18next not recognized as a module when upgrading from 19.3.4 to 19.4.1

### ISSUE THREAD

**Issue by yann-combarnous** [i18next/i18next#1426]
Since upgrading i18next to version 19.4.1, my Jest tests are failing (version of react-i18next: 11.3.4, using CRA 3.4.1):

```
  You are passing a wrong module! Please check the object you are passing to i18next.use()

      12 | import { initReactI18next } from 'react-i18next';
      13 | 
    > 14 | i18n.use(initReactI18next)
```

The code starts as follows:
```
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

i18n.use(initReactI18next).init({
  fallbackLng: 'en',
  ns: ['translations'],
  defaultNS: 'translations',
});
```

**Comment by jamuhl** [comment]
the check is: https://github.com/i18next/i18next/blob/master/src/i18next.js#L200 with initReactI18next = https://github.com/i18next/react-i18next/blob/master/src/context.js#L59

So the question is - what is initReactI18next in your case?

**Comment by adrai** [comment]
@yann-combarnous Can't reproduce it: https://codesandbox.io/s/react-i18next-gkv68?file=/src/i18n.js

**Comment by yann-combarnous** [comment]
Thank you for the quick turnaround. Found the root cause: a mock was added for "react-i18next" in common test utils. The interesting part is that until 19.4.1, I did not get above warning. 

So this is a good thing it errors now. Apologies.

**Comment by saurkadam** [comment]
Sorry but can you please explain a bit more I am also facing the same issue. What exactly you mean by common test utils?

**Comment by drcoolsanjeev** [comment]
@yann-combarnous could you please explain the resolution a bit more?

**Comment by mattgreenfield** [comment]
@saurkadam @drcoolsanjeev 

I'm afraid I don't have the fix but I think @yann-combarnous is saying that they are mocking "react-i18next" in jest and that the mock was missing `initReactI18next`?
A 'mock' is where you tell jest to look at the 'mocked' function rather than the 'real' one/

Here's an example of a mock that includes `initReactI18next`, although it doesn't fix this issue for me. https://github.com/i18next/react-i18next/blob/master/example/test-jest/src/__mocks__/react-i18next.js

**Comment by lambbyrd** [comment]
This solved the error for us inside of our jest.mock of 'react-i18next':

`initReactI18next: {
    type: '3rdParty',
    init: jest.fn(),
  },`

**Comment by bharat-dussa** [comment]
even i use the above method i am still getting the same issue
