### ISSUE TITLE
How to handle plural possession of a name ending in s?

### ISSUE THREAD

**Issue by bitttttten** [i18next/i18next#1427]
I have a string that looks like this:

```js
{
    "heading": "Check out all of {{ name }}'s bikes",
}
```
Which works great until you use a name such as Socrates, or Jesus. Then the string gets translated into:

"Check out all of Socrates's bikes"

Which is grammatically incorrect. I tried to dig around the docs although I couldn't find any instances of handling this, my first instinct is to implement some logic like:

```js
{
    "heading": "Check out all of {{ name }}'s bikes",
    "heading_name_ends_with_s": "Check out all of {{ name }}' bikes",
}
```

```js
t(name.endsWidth('s') ? "heading_name_ends_with_s" : "heading", { name })
```

Is there a better approach?

**Comment by jamuhl** [comment]
Nope. Such language specific linguistic challenges are hard to implement in form of code...i would try doing it as a formatter: https://www.i18next.com/translation-function/formatting

If lng is English and format `addHisShortForm` and value ends with `s` return formatted name

**Comment by bitttttten** [comment]
Okay thanks! The formatter looks like an interesting way to solve the problem, I'll look into it :)
