### ISSUE TITLE
Problems translating button label/value | ReactJS

### ISSUE THREAD

**Issue by ItzaMi** [i18next/i18next#1429]
The last solution I saw to my problem was from 2013 and it seems that it's not relevant anymore (at least that's what I figured).
Here's my problem.
I'm using React with Typescript and feeding the info with JSON files. My title works properly but I can't figure out why my button isn't translating and instead is grabbing the string inside 
```label={t('Learn React')} ```

I have a button component (which I'm also using for Storybook)
```
const Button: FC<Props> = ({
  label,
  type,
}) => {
  return (
    <button
      type={type || 'button'}
    >
      <span className={css.label}>{text('Label', label)}</span>
    </button>
  )
}
```

that I'm using here
```
const Home: React.FC<{ title: string; label: string }> = ({ title, label }) => {
  return (
    <div className={css.host}>
      <p className={css.text}>{title}</p>
      <Button
        label={label}
      ></Button>
    </div>
  )
}
```

and Home is being used here
```
const Page: React.FC<{ title: string; label: string }> = ({ title, label }) => {
  return (
    <div className={css.host}>
      <BrowserRouter>
        <Switch>
          <Route path="/not-logged-in-page">
            <Home title={title} label={label} />
          </Route>

          <Redirect from="/" to="/logged-in-page" />
        </Switch>
      </BrowserRouter>
    </div>
  )
}

const Loader = () => (
  <div className="App">
    <div>loading...</div>
  </div>
)

export default function App() {
  const { t } = useTranslation()
  return (
    <Suspense fallback={<Loader />}>
      <Page title={t('title')} label={t('label')} />
    </Suspense>
  )
}
```

My JSON is looking like this
```
{
  "title": "Title",
  "label": "Learn React"
}
```

My title works perfectly fine and I have no problems with it but the same doesn't happen with my Button. It ends up taking the value set to
``` label={t('label')} ```
that is inside <Page />

Am I tackling this wrong? I'm fairly new to this and it's my first time using i18next but it everything seemed ok until the button part!

**Comment by jamuhl** [comment]
I'm not really able to follow your code...

1) label gets set to "Learn React" <Page title={t('title')} label={t('label')} />
2) that string gets passed to Button via props -> prop.label = "Learn React"

but what is `text('Label', label)` in your Button - where is this function?

**Comment by ItzaMi** [comment]
The ```{text('Label', label)}``` is part of the Storybook and it goes to button.stories.jsx. I felt like it wouldn't had much to the issue (maybe I'm wrong)

**Comment by jamuhl** [comment]
So it shows `label` instead of `Learn React`?

How do you load the translations?

**Comment by ItzaMi** [comment]
Yes, exactly.
I'm using the **Load using a backend plugin** method as shown on the website.  
```
i18next
  .use(Backend)
  .init({
    backend: {
      // for all available options read the backend's repository readme file
      loadPath: '/locales/{{lng}}/{{ns}}.json'
    }
  });
```

**Comment by jamuhl** [comment]
Did you set `useSuspense: false` or why does it not get triggered here:

```js
export default function App() {
  const { t } = useTranslation()
  return (
    <Suspense fallback={<Loader />}>
      <Page title={t('title')} label={t('label')} />
    </Suspense>
  )
}
```

The Suspense does not wrap the component using useTranslation

**Comment by ItzaMi** [comment]
That was it! Thank you!

I had ```useSuspense: false``` since that was a solution that I saw. I deleted it and I got the message **Add a <Suspense fallback=...> component higher in the tree to provide a laoding indicator or placeholder to display** so I went up one level and wrapped my App component with Suspense and it worked.  
  
I was fairly sure that I had Suspense in the right place but clearly I was wrong!
Thank you for your patience!

**Comment by jamuhl** [comment]
you're welcome

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
