### ISSUE TITLE
Nested interpolations have their leading whitespace stripped

### ISSUE THREAD

**Issue by pcwiek** [i18next/i18next#1430]
Working version: `19.3.4`
Latest tested version: `19.4.2`

Template (`template.json` file):
```json
"new-message": {
  "from-missing": "",
  "from": " from {{creator.firstName}} {{creator.lastName}}",
  "title": "New message$t(template:new-message.{{from}}, { 'defaultValue': '' })",
  "body": "You have a new message$t(template:new-message.{{from}}, { 'defaultValue': '' })."
}
```

Please note the leading whitespace in `from`.

Before:
```
     "notification": Object {
    -         "body": "You have a new message from Bob Dylan.",
    -         "title": "New message from Bob Dylan",
            },
```

After:
```
     "notification": Object {
    +         "body": "You have a new messagefrom Bob Dylan.",
    +         "title": "New messagefrom Bob Dylan",
            },
```

It seems that the leading whitespace is stripped. Adding a trailing whitespace, as in:
```
"New message $t(...)"
```
is problematic, because it doesn't look good with `from-missing` where we don't have the creator name and there's always a whitespace between the content and the final period (`You have a new message.` vs `You have a new message .`)

 Is there a way to include a leading whitespace from the nested interpolation in the final message?

**Comment by adrai** [comment]
Should be fixed in v19.4.3

**Comment by pcwiek** [comment]
Thank you @adrai !

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.
If you liked my support / work - I would enjoy a coffee sponsored using the “💜Sponsor Button”.
There are many ways to help this project 🙏
