### ISSUE TITLE
Nesting with namespaces does not seems to work

### ISSUE THREAD

**Issue by hovancik** [i18next/i18next#1431]
Hi, 

taking an example from Docs, but turning it into namespaced one seems to break it.

https://jsfiddle.net/vt06ao9c/

Or is my syntax wrong? 

```
translation: {
      	"test": {
         "girlsAndBoys": "$t(test:girls, {'count': {{girls}} }) and {{count}} boy",
       	 "girlsAndBoys_plural": "$t(test:girls, {'count': {{girls}} }) and {{count}} boys",
       	 "girls": "{{count}} girl",
       	 "girls_plural": "{{count}} girls"
        }

      }
```

```
i18next.t('test.girlsAndBoys', { count: 2, girls: 1 })
```

Expected: `1 girl and 2 boys`
Result: `girls and 2 boys`

**Comment by jamuhl** [comment]
`$t(test:girls, {'count': {{girls}} })` ---> `test:` says look in another namespace (file) called `text`

should be `$t(test.girls, {'count': {{girls}} })`

**Comment by hovancik** [comment]
Cheers, you're right. Thanks!
