### ISSUE TITLE
Not loading namespaces

### ISSUE THREAD

**Issue by gorillaboy777** [i18next/i18next#1432]
Hi! I don't know where to write this issue. (I write about problems of open source libs for the first time, so sorry) There is a problem with `react-i18next`, but the root of the problem is in `i18next`.
Problem is this. 
I pass empty string is `lng`, and `en-US` as `fallbackLng`
As we passed empty string as `lng`, we will have `l = ""` [here](https://github.com/i18next/i18next/blob/master/src/i18next.js#L239)
and it will lead to never setting `this.languages`.
But it will use translation with `en-US` language.
And not setting `this.languages` leads to `const result` being equal `true` [here] (https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L41)
And at the very end, `result` that equals `true` prevent loading necessary namespaces, and we will se keys instead of translations.

**Comment by adrai** [comment]
2 questions:

Why do you want lng to be an empty string?
Can you provide a codesandbox example?

**Comment by adrai** [comment]
@gorillaboy777 any more infos?

**Comment by gorillaboy777** [comment]
Hi, so sorry for not responsing for long period of time.

1) We get languages from BE, alongside whitelisted languages.
2) this is demo https://codesandbox.io/s/long-fire-ytvg5

**Comment by adrai** [comment]
2 options:
1. Load languages from your BE first and afterwards initialize i18next accordingly
or
2. Set lng to “en”, init i18next, load languages from your BE and afterwards changeLanguge on i18next

**Comment by gorillaboy777** [comment]
Yes, we've managed with this kind of behavior, i've wrote, because for me it was not obvious, that lib will not use fallback language, so i wanted you to know it.

**Comment by adrai** [comment]
There is probably a third option: create an own language detector plugin
