### ISSUE TITLE
Incompatibility with Material UI 4.9.10 Tooltip component.

### ISSUE THREAD

**Issue by kumarunster** [i18next/i18next#1435]
The typedefinition of  TFunctionResult in https://github.com/i18next/i18next/blob/5fa77054d644990e8baf8ac4a9817fbef4711684/index.d.ts#L635 allows types `null` and `undefined` as the result of translation function.

however this types are not compatible with material ui tooltip type change introduced in 4.9.10, see this issues for reference: https://github.com/mui-org/material-ui/issues/20701 and https://github.com/mui-org/material-ui/issues/20537.

Could you verify, if null and undefined are really needed here as a result of translation function?

Thanks in advance.

**Comment by jamuhl** [comment]
for sure I know the result of a t call can be null (not sure about undefined). But actually I'm not sure how this is incompatible with types in material UI....

**Comment by rosskevin** [comment]
@kumarunster try to remove undefined and run tests. If it works, PR it. Y recollection is that it is necessary.

**Comment by kumarunster** [comment]
@jamuhl @rosskevin thanks for your quick answers.

Unfortunately, material-ui guys **explicitly excluded null and undefined** from Tooltip tittle property type:

```TypeScript
title: Exclude<React.ReactNode, null | undefined>; 
```
See linked issues in the description and this [code line](https://github.com/mui-org/material-ui/blob/99ca172ffd3c775240e710f647bb7880c328f7c7/packages/material-ui/src/Tooltip/Tooltip.d.ts#L99)

so removing undefined would not help here, because null would be still present.

@eps1lon and @oliviertassinari rejects that change reversion.

From the user perspective it is a nightmare, because it requires either type redefinition of i18next types or casting useTranslate hook to any, which both are ugly workarounds.

**Comment by jamuhl** [comment]
So, I guess there is no solution...but changing types to something wrong just because of this is not the way to go.

**Comment by oliviertassinari** [comment]
@kumarunster Have you tried casting the value to a string? Do you have a full example?

**Comment by rosskevin** [comment]
You can also just use `t('foo') || ''` as the prop value. While inconvenient it is probably the shortest usage given the constraints.

**Comment by oliviertassinari** [comment]
@rosskevin Yeah, it would work too, keep the tooltip hidden if the translation is missing.

**Comment by eps1lon** [comment]
If you don't want to catch missing translation and don't want to catch broken UI at the type level you can use `t('foo')!`. This is no runtime implication.

**Comment by kumarunster** [comment]
@eps1lon excellent, thanks for that hint

**Comment by traverse** [comment]
I just ran into this issue myself and ended up solving it by providing the generic for the result explicitly e.g.
```ts
t<string>('foo')
```
I hope that this might help others in the future.

**Comment by adriangonzalezrodrigo** [comment]
> I just ran into this issue myself and ended up solving it by providing the generic for the result explicitly e.g.
> 
> ```ts
> t<string>('foo')
> ```
> 
> I hope that this might help others in the future.

this doesn't work for me. I have to declare a constant to store the translation and use this translation in the Tooltip:

const someKeyTranslated = t('MY_KEY');

<Tooltip title={someKeyTranslated}>
