### ISSUE TITLE
Translation starting with {{count}} seems reversed?

### ISSUE THREAD

**Issue by SidOfc** [i18next/i18next#1436]
Hello, I am working on an application that uses i18next and react-i18next. I was not exactly sure where to post this issue so I decided to choose i18next as it seems to be a general issue.

**versions**:
- **i18next**: `19.4.3`,
- **react-i18next** : `11.3.5` 

**Problem**
I have a `t` call in a React component which looks like this: `t('forms.filesChosen', {count: value.length})`.

The translations for this call look like this:
```json
{
    "forms": {
        "filesChosen": "1 file selected",
        "filesChosen_plural": "{{count}} files selected"
    }
}
```

When I upload 2 files, it will not show `2 files selected`, but rather `files selected 2` (The same goes when uploading 1 file):

![image](https://user-images.githubusercontent.com/3225058/80213741-ec10c000-8639-11ea-8edf-bf7d0e07a1b6.png) 

I am unsure if `_plural` is always used due to `count` presence in object options.

Even more bizarre, the fix seems to be to not have `"{{count}}"` at the **start** of the translation.
e.g. if I change above JSON like so:
```json
{
    "forms": {
        "filesChosen": "whatisthissorcery?!? 1 file selected",
        "filesChosen_plural": "whatisthissorcery?!? {{count}} files selected"
    }
}
```

The output is exactly as desired:

![image](https://user-images.githubusercontent.com/3225058/80213657-cb486a80-8639-11ea-9a70-aec381e7fa9b.png)

**however** not all random strings work, if I only use a space or a dot (e.g. `. {{count}} files selected`) the translations are still broken in this situation.

**last, but not least**

I tripple checked some things to make sure I wasn't going mad myself:
- Are translations loaded from proper source file? **Yes**
- Are there any duplicate keys in the translation file? **Not for this key**

**edit:**

Is this a me problem, or an actual bug? Please advise :)

**Comment by SidOfc** [comment]
Since this happened after a package update, I decided to roll it back and see if it also occured in older version we used before, I can confirm it also happens in:

versions:
    **i18next**: `19.4.2`,
    **react-i18next** : `11.3.4`

**Comment by adrai** [comment]
I'm not able to reproduce it.
Tested with the same versions.
Can you create a codesandbox example?

**Comment by jamuhl** [comment]
check the fiddle: https://jsfiddle.net/jamuhl/734sdvwh/1/ 

looks like it works...?!?

**Comment by SidOfc** [comment]
@jamuhl thanks for creating the fiddle, I was also working on an example that uses `useTranslation()` / `withTranslation()`. As I mentioned before, I am unsure if this is me, i18next, or react-i18next. Your test shows that `i18next` is fine at least, but I am still not convinced that this is something I'm causing.

What I will do is close this issue for now until I've reproduced it myself in a repository. Cheers for the effort and quick response :+1:

**Comment by jamuhl** [comment]
Yes, would love to see this reproducable...currently hard to say where it goes wrong...i18next seems to do it right -> react-i18next basically just uses that function - so I'm not sure where that should come from...?!?

Would be awesome if you find the cause and in any case keep us updated. 👍

**Comment by SidOfc** [comment]
@jamuhl man oh man I am starting to believe I'm a total retard actually. I recreated pretty much the minimal setup that the project with issues is using to no avail, it is solid and **working without fault**.

I also noticed two issues with my initial post, which is that we also use the `moment` library AND `i18next-xhr-backend`. Even after adding those it kept working properly.

I am also using a custom hook in my project, which does this:
```js

import {useTranslation} from 'react-i18next';
import {prefixedT} from '../util';

export default function usePrefixedTranslation(prefixKey) {
    const {t} = useTranslation();

    return {t, pt: prefixKey ? prefixedT(prefixKey, t) : t};
}
```

The `prefixedT` part is not important as I'm just extracting `t` from my custom hook. (so I'm not calling it directly, but rather via a custom hook). Just figured I'd put it out there for others.

The only difference would be the actual build tool we're using but yeah, highly doubt that has anything to do with it. For now, my post-mortem is contained within this repo: https://github.com/SidOfc/i18next-count-failed-repro. I figure it may be useful to keep it around in case anyone else has the same issue as they can refer to this issue.

If I do find something down the road I'll definitely let you know, in the meantime I'll work around what seems to be a portion of self-inflicted magic.

Since I was a bit premature on posting my issue, and you guys responded **very fast**, I'd like to just donate ~30 euro so you guys can grab a beer or two. I checked GH sponsor but it's monthly which I don't really feel like doing, is there any place I can just dump some money @jamuhl / @adrai ?

**Comment by jamuhl** [comment]
That's strange...but there are days like this...😁

No need for the donation...make some nice tweet, recommend i18next to your friends or if needing a translation management tool - give our https://locize.com a try...

**Comment by SidOfc** [comment]
Already using Locize and i18n at work for roughly 2 years I think now :)

thanks again for both your efforts and of course, maintaining the project. There's no other translation project I'd rather recommend :+1:. For now, heading back into the shadows :wave:

**Comment by SidOfc** [comment]
Reporting back here to state that I am in fact, a retard indeed. It was no where in the tech stack, but rather my own lack of understanding of the `direction` CSS property.

The direction was set to `rtl` rather than `ltr` in order to trim the field from the left side rather than right... :facepalm: :man_facepalming: :woman_facepalming: 

Once again apologies and hopefully someone else landing here can benefit from this message too :)

Thanks again @jamuhl and @adrai for your quick replies!

**Comment by adrai** [comment]
@SidOfc all ok, don't worry ;-)
