### ISSUE TITLE
About v13 change and browser support

### ISSUE THREAD

**Issue by aoisummer** [i18next/i18next#1438]
On getting started page of docs, the basic example use classic callback method. I test it in IE 11 but shows error "Promise is not defined". Does this means browser **MUST** has Promise supported even I don't use it?

browser | v12.1.0 | v13.0.0 | v13.0.0+polyfill
------- | ------- | ------- | ----------------
IE 11 with IE 9 mode | work | error | work
IE 11 with IE 10 mode | work | error | work
IE 11 | work | error | work
Firefox 28 | work | error | work
Firefox 29 | work | work | work

**Comment by jamuhl** [comment]
outdated browsers - eventual?

**Comment by adrai** [comment]
@aoisummer would this work for you? https://github.com/i18next/i18next/tree/promise

**Comment by adrai** [comment]
fyi: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
![image](https://user-images.githubusercontent.com/1086194/80304665-c4476680-87b7-11ea-88a4-8c231a3f2580.png)

**Comment by aoisummer** [comment]
> 
> @aoisummer would this work for you? https://github.com/i18next/i18next/tree/promise (promise branch)

This version works well.

**Comment by jamuhl** [comment]
IE11 is a dead horse...if you need to support that - use polyfills

**Comment by ChenGuanglin0924** [comment]
> IE11 is a dead horse...if you need to support that - use polyfills

I pollfilled the i18next, it still doesn't work

**Comment by tt4g** [comment]
@ChenGuanglin0924 [https://github.com/stefanpenner/es6-promise] is works for me.

Example `index.js`:

```javascript
require('es6-promise').polyfill();

new Promise(function (resolve) {
  setTimeout(function () {
    resolve('Promise!');
  }, 300);
}).then(function (result) { console.log(result); });
```
