### ISSUE TITLE
i18n.use() definition not compatible with source code

### ISSUE THREAD

**Issue by zhoutwo** [i18next/i18next#1440]
Hi, I'm using TypeScript 3.8.3 and i18next 19.4.4, and when I create my custom backend module, and ran into issues.

If I create a class and generate the definition, with some importing and fixing compilation errors, I get this:

```typescript
class MyBackend implements BackendModule<MyBackendOptions> {
  type: 'backend' = 'backend';
  init(services: Services, backendOptions: MyBackendOptions, i18nextOptions: InitOptions): void {}

  create(languages: string[], namespace: string, key: string, fallbackValue: string): void {}

  read(language: string, namespace: string, callback: ReadCallback): void {}
```

However, if I do
```typescript
i18n.use(MyBackend)
```
I get
```
Uncaught Error: You are passing a wrong module! Please check the object you are passing to i18next.use()
```
Which points to
```javascript
if (!module.type) throw new Error('You are passing a wrong module! Please check the object you are passing to i18next.use()');
```

However, I double-checked the type definition:
https://github.com/i18next/i18next/blob/v19.4.4/index.d.ts#L815-L817
https://github.com/i18next/i18next/blob/v19.4.4/index.d.ts#L791
```typescript
export type Newable<T> = { new (...args: any[]): T };
```

The `Newable<T>` type does not have a property called `type`. It only constructs one with the property.
This means I cannot pass in the constructor like the built-in modules. I have to instantiate it outside and call `use()` on it.

One potential solution here is to use:
```typescript
export type ModuleNewable<T extends Module> = { 
  new (...args: any[]): T;
  type: T["type"];
};

// ...

use<T extends Module>(
    module: T | ModuleNewable<T> | ThirdPartyModule[] | ModuleNewable<ThirdPartyModule>[],
  ): i18n;
```

Then, `MyBackend` will become:
```typescript
class MyBackend implements BackendModule<MyBackendOptions> {
  static type: 'backend' = 'backend';
  type: 'backend' = 'backend'; // This is here because I didn't touch "Module" definition
  // ...
```

And now I can pass the constructor into `i18n.use()` and it works.

However, I do see that this definition breaks the exported type of `i18next-browser-languagedetector`, which makes my recommendation slightly risky.

For now, I think you can tell people to add `static type: 'backend' = 'backend';`, which is defining more than the interface, but TypeScript does not error out for extra static fields.

**Comment by jamuhl** [comment]
Don't fully get it...as I don't use typescript...in the end in JS it's https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L21

If typescript makes everything harder than needed - 🤷‍♂️

**Comment by zhoutwo** [comment]
Hi @jamuhl , what allowed that code to work was https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L83 , which, cannot be done in TypeScript as of now, hence the whole block of explanation.

If it's too much work to change the existing definitions, I understand. But, maybe a note for TypeScript users could be helpful and easy to add:
> Due to [limitation of TypeScript](https://stackoverflow.com/a/13955591), when declaring a class to implement a Module, add a static property "type" like so:
```typescript
class MyModule implements Module {
    // Choose among 'backend' | 'logger' | 'languageDetector' | 'postProcessor' | 'i18nFormat' | '3rdParty'
    static type: 'backend' = 'backend';
    // Continue implementing as normal
    // ...
}
```
In fact, `static type: 'backend' = 'backend'; ` is the line that achieves the same thing `Backend.type = 'backend';`

**Comment by jamuhl** [comment]
Might be alone with the opinion...but how to add statics to a class should be basic knowledge...not something we have to tell people...but like said...might be just my opinion...

**Comment by zhoutwo** [comment]
My opinion is that when there is an interface (`BackendModule`), people expect that if they implement the interface, they should be good to go. In my case, that wasn't so, hence raising this issue.

That said, it is a rather minor issue since 1. I was able to figure out that I needed the static field and 2. For those who cannot, they will probably create an instance and it is still perfectly valid. So I'm fine with not acting on this issue. Thank you for your timely response!

**Comment by jamuhl** [comment]
If you like to improve the typings -> PR and mention @rosskevin

**Comment by zhoutwo** [comment]
Sounds good. Thank you!
