### ISSUE TITLE
Localization Format Plugin Support

### ISSUE THREAD

**Issue by akshayr-tavisca** [i18next/i18next#1441]
Hi, We are planning to add i18next to our enterprise application, although  the package is able to solve majority of our issues, I have some issues with providing localization support to the package.

As per the docs we can integrate **Momentjs**, **NumeralJs**, **INTL API**, 

> https://www.i18next.com/translation-function/formatting#formatting

Do we need to write each and every format function or is there any ready to use **package/utility/plugin** available which we can connect and play with i18next.

Any  help/leads on these will  be appreciated.

**Comment by jamuhl** [comment]
as far i know - there is no utility/plugin

**Comment by akshayr-tavisca** [comment]
Thank you for the quick response,

Does someone else know is there any sample example where i18next team has consumed **Moment js** or **NumeralJs** or **INTL API** and written a custom format function for localization.

i18next is really nice package  for translations.
How to provide Localization support to the application using i18next.

(Formats e.g. dates , currency,  separators, currency  number  etc)

**Comment by jamuhl** [comment]
idk...but actually it's no complex task todo...just use the https://www.i18next.com/translation-function/formatting and implement what you need.
