### ISSUE TITLE
Release notes for v18 and v19?

### ISSUE THREAD

**Issue by jesspagan** [i18next/i18next#1443]
Hi!

Going through our project stack, I noticed that the i18next v17 we are currently using is two major versions behind. I want to check the different between these major versions to understand the risks, fixed, enhancements or new features that those version provide, before going forward with upgrading it.

Hope posting this question here is ok. I am not aware of any other channel to ask about this.

Thanks,
Jessica

**Comment by adrai** [comment]
Hi Jessica,

May I ask what is exactly missing?

https://github.com/i18next/i18next/blob/master/CHANGELOG.md

**Comment by jesspagan** [comment]
Hi Adriano,

I was looking at the releases section like I normally do with react stuff, instead of the CHANGELOG. Thanks for the help.

![image](https://user-images.githubusercontent.com/3449831/80990642-85369800-8deb-11ea-8f70-a5886f4be600.png)
