### ISSUE TITLE
Feature request: Support multiple languageDetector plugins

### ISSUE THREAD

**Issue by brandones** [i18next/i18next#1444]
I'd like to use two different languageDetector plugins. One is the [browser-languageDetector](https://github.com/i18next/i18next-browser-languageDetector). The other is a [custom language detector](https://www.i18next.com/misc/creating-own-plugins#languagedetector) I wrote so that I could use async:

```js
const sessionLanguageDetector = {
  type: "languageDetector",
  async: true,
  init: function(services, detectorOptions, i18nextOptions) {},
  detect: function(callback) {
    getSession().then(session => callback(session?.defaultLocale));
  },
  cacheUserLanguage: function(lng) {  // this doesn't ever appear to get called
    sessionStorage.setItem("i18nextLng", lng);
  },
};
```

This behavior isn't documented anywhere so I didn't fully expect it to work. What happens is that usually, the language detector that is `use`d last is used, and the other is ignored. So
```js
i18n.use(sessionLanguageDetector).use(browserLanguageDetector)
```
will only use the browser language detector, not the session language detector.

Sometimes, however, when the `sessionLanguageDetector` is provided second, JS execution stops at some point -- presumably an exception is thrown and swallowed. Silent failure.

Since this didn't quite work out, this is a feature request! Fun!

I would like to be able to use these two language detection modes, with some deterministic order of precedence.

**Comment by jamuhl** [comment]
A detector itself can have multiple lookups: https://github.com/i18next/i18next-http-middleware/tree/master/lib

**Comment by brandones** [comment]
Yes, but it's unable to reuse another detector. If I wanted to detect based on session location, query string, html tag, and cookie, I would have to re-implement the latter three.

Perhaps a good alternative would be if `browser-lanugageDetector` allowed its constituent lookups to be imported? e.g. 
```js
import { cookie, htmlTag } from 'i18next-browser-languagedetector/browserLookups'
```

**Comment by jamuhl** [comment]
> I would have to re-implement the latter three

The lookups are separated...it's just a copy over...

you already can add: https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality ---> but no async

**Comment by brandones** [comment]
Right. While I'm not a fan of copy-pasting code around (for all the reasons packages and imports were invented), these lookups are each simple enough, and based on stable enough APIs, that its probably not a problem.
