### ISSUE TITLE
How to provide HTML content as key values and use them unescaped ? 

### ISSUE THREAD

**Issue by sushant-tavisca** [i18next/i18next#1445]
# Using HTML values as keys.

I have prepared a sample code for my use case:

```typescript
i18next.init({
	lng: 'en',
	debug: true,
	resources: {
		en: {
			translation: {
				"key": "Hello <a href='#'><b>World</b></a>"
			}
		}
	}
});
@customElement('app-hello')
export default class HelloComponent extends LitElement {
	render() {
		return html`
			<h3>Custom Header</h3>
			<div>Refer the following link: ${i18next.t("key")}<div>
		`;
	}
	createRenderRoot() {
		return this;
	}
}
```
I want the content in the key, to be parsed as HTML instead of string. Is there an out of the box support for such cases, without manually parsing string to HTML ?

**Comment by jamuhl** [comment]
The problem is not i18next, you can get a translation containing HTML and set innerHTML of an element via javascript...so the problem you need to find out how to not escape in subcomponents (or whatever you're using here)

**Comment by nilamsavani** [comment]
Hi @jamuhl @adrai  ,

I have a key value which is as below:

`
"Fetched schedules: success": "Horaires récupérés: Succès",
` 
As it is having `:`, I am getting an error. How can I escape `:`?

**Comment by adrai** [comment]
@nilamsavani You need a different nsSepartor -> https://www.i18next.com/overview/configuration-options#misc

**Comment by nilamsavani** [comment]
@adrai  Thanks.

`
{
   "Fetched schedules: success": "Fetched schedules success 1",
   "Fetched groups: success": "Fetched groups success 1",
   "Fetched devices: success": "Fetched devices success 1",
   "Created command: success": "Created command success 1",
   "Updated schedule: success": "Updated schedule: success 1",
   "WARNING: Cannot find the group for this schedule": "WARNING: Cannot find the group for this schedule 1",
}
`

My translation file is something like this. Do I need different keySeparator or nsSeparator as my key is having `:`? 

If you have any example of it can you please share a link of it?

**Comment by adrai** [comment]
@nilamsavani Try to set both options to false

**Comment by nilamsavani** [comment]
setting `false` for both options worked. 

Thank you for your quick reply @adrai
