### ISSUE TITLE
TFunction return value is reported as `any` by VS Code

### ISSUE THREAD

**Issue by stevendesu** [i18next/i18next#1446]
![Screen Shot 2020-05-07 at 2 57 57 PM](https://user-images.githubusercontent.com/1384974/81334130-8ed23100-9073-11ea-91e9-565a53844ebc.png)

I tried looking at the definition file to figure out the cause of this issue, but the definition for `TFunction` is beyond my TypeScript expertise:

```
export interface TFunction {
  // basic usage
  <
    TResult extends TFunctionResult = string,
    TKeys extends TFunctionKeys = string,
    TInterpolationMap extends object = StringMap
  >(
    key: TKeys | TKeys[],
    options?: TOptions<TInterpolationMap> | string,
  ): TResult;
  // overloaded usage
  <
    TResult extends TFunctionResult = string,
    TKeys extends TFunctionKeys = string,
    TInterpolationMap extends object = StringMap
  >(
    key: TKeys | TKeys[],
    defaultValue?: string,
    options?: TOptions<TInterpolationMap> | string,
  ): TResult;
}
```

I'm not sure off-hand what's wrong or how to fix it, but it's causing issues with even simple code:

```
import i18n from "i18next";

i18n.init({}).then(t =>
{
	console.log(t("key"));
});
```

These 3 LLOC are throwing ESLint errors because of the ***possibility*** that I failed to handle a Promise (even though `t` never returns a Promise):

![Screen Shot 2020-05-07 at 3 07 29 PM](https://user-images.githubusercontent.com/1384974/81334770-8cbca200-9074-11ea-972a-c006f4e0d97a.png)

**Comment by jamuhl** [comment]
why not use google? https://stackoverflow.com/questions/43980188/what-could-this-be-about-tslint-error-promises-must-be-handled-appropriately

**Comment by stevendesu** [comment]
@jamuhl The problem isn't that I don't understand the error message. It's that I don't understand why TypeScript is reporting the return type of the `t()` method to be `any`. The link you provided is zero help.

Basically TypeScript believes `t("key")` can return "any possible value type" (including Promises), even though in practice it only returns a string.

Therefore my IDE (ESLint, specifically) believes that there may be an unhandled Promise. **There isn't an unhandled Promise**. The link you provided shows how to handle a Promise, if there were one. But there isn't one.

**Comment by jamuhl** [comment]
init return a promise - you don't catch...that causes the typescript error:

reads: https://stackoverflow.com/questions/43980188/what-could-this-be-about-tslint-error-promises-must-be-handled-appropriately

That's a crappy error message. A better one might be,

every expression of type Promise must end with a call to .catch or a call to .then with a rejection handler (source).

**Comment by stevendesu** [comment]
![Screen Shot 2020-05-07 at 4 01 52 PM](https://user-images.githubusercontent.com/1384974/81339388-1a4fc000-907c-11ea-9120-aaf691e29a3a.png)

I'm getting errors not from `init`, but from the return value of `t`. It's being treated as `any`.

I may have neglected the `catch()` in my overly simplified example, but I'm using `async/await` in my actual code and running into the same issues.

**Comment by jamuhl** [comment]
leaving this open for TS users that might help out

**Comment by stevendesu** [comment]
So far I have two potential fixes, neither as elegant as I'd like:

```
// Declare the function's return type
server.decorate("toolkit", "__", function(key: string): string
{
    return translate(key);
});

// Store the result from `translate(key)` into a variable:
server.decorate("toolkit", "__", function(key: string): string
{
    const words = translate(key);
    return words;
});
```

The fact that the second one works makes me wonder if this is a bug with TypeScript or ESLint instead of the i18next definitions
