### ISSUE TITLE
Help wanted: i18next cloneInstance not respecting fallbacks

### ISSUE THREAD

**Issue by stevendesu** [i18next/i18next#1449]
I have a fairly simple NodeJS application (a HapiJS web server) with all of my translation files sitting on a `./locales` folder:

```
+ My project
| - /locales
|    | - en-US.json
|    | - en-GB.json
|    | - es.json
|    | - fr-BR.json
|    | - etc...
| - /src
| - /test
| - etc...
```

I've written a `resolveLangauges()` method. This method starts with the HTTP `Accept-Language` header and produces a list of valid languages by looking at:

 - The specific languages requested (e.g. if you request `en-US`, then any "English" should be acceptable)
 - The languages common to the specific regions requested (e.g. if you requested `pt-BR`, then any language spoken in Brazil should be acceptable)
 - The ISO-639-1 macro languages (e.g. if you requested `nn` then `no` should be acceptable)
 - The historical context of related languages (e.g. if you requested any romance language, then `es` should be acceptable)
 - etc

It generates an ordered list of languages using your reported preference. For example, an HTTP `Accept-Language` header of `es-AR;q=0.5, ja;q=0.3, en-US;q=1` would be interpreted as:

 - Prefer United States English
 - Next, prefer any other English (e.g. "en-GB", "en", etc)
 - Next, prefer Argentinian Spanish
 - Next, prefer any other Spanish (e.g. "es-ES", "es", "es-BR", etc)
 - Next, prefer any Japanese
 - Next, prefer any language spoken in America ("en-*", "en", "es-*", "es")
 - Next, prefer any language spoken in Argentina (Spanish, English, Italian, German, French)
 - Next, prefer any language related to the above languages (for instance, Esperanto or Catalan)

After doing all of this, we get a huge array of about 100 "acceptable" languages (note that "language" is used loosely here, as `en`, `en-GB`, and `en-US` are 3 separate languages) sorted by preference. We de-duplicate this array and then filter it for only languages for which we have translation files.

After this filtering step, the results of language resolution are cached (using the `Accept-Language` header as a hash) to speed up future requests.

My goal now is **for this request** to utilize the resolved language list for my fallback languages.

I've written a unit test where I provide translation files for `fr-BR`, `es`, `en-US`, and `ja`. I then have a missing translation key in the `fr-BR` file (the key is also missing in the `ja` file, but is defined in the `es` and `en-US` files). Next I make a request which uses the missing translation key with an `Accept-Language` header of `pt-BR`. Because I have no `pt` translation files, but I've listed the region as Brazil, `fr-BR` is the first language file that should be tested. Next, since Portuguese and Spanish are related, `es` is the next language file that should be tested. Finally, we fall back to `en-US` as a last resort before simply returning the key.

In order for the i18next instance to be properly configured per-request, I create a unique instance in a callback that runs when the request is first received (but before I've processed it to determine what to return). Because I want all of my instances to share the same collection of translation files (loaded from disk) I use `cloneInstance` against a global instance of i18next in order to create this instance.

The problem is that the clone is not respecting the list of fallback languages I provide it. Here's what I'm seeing:

```
// ...
await i18next.use(fsBackend).init({
    lng: options.defaultLang,
    fallbackLng: [options.defaultLang],
    nsSeparator: false,
    keySeparator: false,
    backend: {
        loadPath: options.directory + "/{{lng}}.json",
        addPath: options.directory + "/{{lng}}-missing.json"
    }
});

server.ext("onRequest", async (request, h) =>
{
    const resolvedLanguageList = resolveLanguages();
    console.log(resolvedLanguageList); // ["fr-BR", "es", "en-US"]
    const clone = i18next.cloneInstance({
        lng: resolvedLanguageList[0]
        fallbackLng: resolvedLanguageList
    });
    await clone.init();
    console.log(clone.options.fallbackLng); // ["fr-BR", "es", "en-US"]
    console.log(clone.languages); // ["fr-BR", "fr", "ja"]
    request.plugins.i18n = clone;
});
// ...
```

I don't even have an `fr.json` language file, so I don't know what `fr` is doing in the list of acceptable languages. But because it's not loading `es` or `en-US`, it's failing to find the key at all (it's not in `fr-BR`, there is no `fr`, and it's not in `ja`) so the server is simply returning the translation key instead of the Spanish or English translation.

Am I doing something wrong in my request to `cloneInstance`?

**Comment by stevendesu** [comment]
One quick update:

Just to test if it would work, I gave up on `cloneInstance` and instead wrote the following:

```
			// ...
			const clone = i18next.createInstance();
			await clone.init({
				lng: resolved[0],
				fallbackLng: resolved,
				nsSeparator: false,
				keySeparator: false,
				backend: {
					loadPath: options.directory + "/{{lng}}.json",
					addPath: options.directory + "/{{lng}}-missing.json"
				}
			});
			console.log(clone.options.fallbackLng);
			console.log(clone.languages);
			console.log(clone.t("missing.key"));
			// ...
```

This worked perfectly. Because each instance is loading its own version of the backend, I worry that this is going to cause performance issues or excessive disk access, but it functions at least

**Comment by jamuhl** [comment]
a clone expects the fallbacks to be the same...it's more or less just for having a copy around having a different language set...the problem starts here where the clone asks for the languages to lookup: https://github.com/i18next/i18next/blob/master/src/i18next.js#L258 (that service uses the options passed in on generation - main instance - and therefore has the initial fallback languages https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L87)

"fr" because i18next always tries the language only part as a fallback...if not set to `load: 'currentOnly'`

Which seems at least from my perspective correct my language is de-CH (swissgerman) and I would prefer fallback in de (german) anytime over our other country languages fr-CH, it-CH.

**Comment by stevendesu** [comment]
@jamuhl Is the `cloneInstance` method using the original instance's fallbacks a bug? [The documentation for `cloneInstance`](https://www.i18next.com/overview/api#cloneinstance) demonstrates passing a new value for both `fallbackLng` and `defaultNS`

Regarding always trying the language only part as a fallback, that makes sense and is fine. That's actually the first fallback that will be tried in my list of resolved languages, the only difference being that I filter out any languages for which I don't have translation file. Therefore I convert `de-CH` to `de`, then remove `de` if I don't have a translation file for it.

**Comment by jamuhl** [comment]
not really a bug...more some sort of limitation - as it shares all internals with the main instance - it's a limitation

might be that could be fixed the same way we override the translator in the clone: https://github.com/i18next/i18next/blob/master/src/i18next.js#L481 

might be other modules would need that too - not only the languageUtils...there also might be circular issues as languageUtils is used in translator too...so I not really think it's something easy fixable...

using a fallbackLng as object might be sufficient? https://www.i18next.com/principles/fallback#fallback-language

**Comment by jamuhl** [comment]
closing due inactivity..
