### ISSUE TITLE
Missing types for i18next store

### ISSUE THREAD

**Issue by stmegabit** [i18next/i18next#1450]
I18next has [store events](https://www.i18next.com/overview/api#store-events), but there types are missing in [declaration file](https://github.com/i18next/i18next/blob/master/index.d.ts)

**Comment by adrai** [comment]
Do you like to submit a PR?

**Comment by stmegabit** [comment]
OK, i'll send PR a little later

**Comment by jamuhl** [comment]
published in i18next@19.4.5
