### ISSUE TITLE
Rejecting non-whitelisted language

### ISSUE THREAD

**Issue by FernandoGOT** [i18next/i18next#1463]
## 🐛 Bug Report

I'm testing this lib and got some warnings (`i18next::languageUtils: rejecting non-whitelisted language code: pt`) when using my native language `pt-BR` (Brazil), I consider this to be a bug since I don't have the `pt` (Portugal) language in my project, and I don't want for my site to fallback to it, it's too different for most Brazilians to understand.

## To Reproduce

Just create a simple project and add these settings:

```js
{
    debug: true,

    lng: 'pt-BR',
    fallbackLng: 'en',
    whitelist: ['en', 'pt-BR'],

    interpolation: {
      escapeValue: false
    },
    backend: {
      loadPath: '/locales/{{lng}}/{{ns}}.json',
    }
 }
```

[CodeSnadbox](https://codesandbox.io/s/i18next-pt-br-warnings-9166d)

* See console for the warnings

## Expected behavior

Since I just declared the `pt-BR` language and explicitly declared that the fallback is always `en`, then there is no reason for the code to search for the `pt` language and do no warnings are going to be generated

## Your Environment

- *runtime version*: Chrome 83.0.4103.97
- *i18next version*: 19.4.5
- *react-i18next version*: 11.5.1
- *i18next-http-backend version*: 1.0.15
- *os*: Mac

**Comment by jamuhl** [comment]
set `load: 'currentOnly' learn about what it does here: https://www.i18next.com/overview/configuration-options#languages-namespaces-resources

learn why it loaded `pt` without this setting here: https://www.i18next.com/principles/fallback

thank you for using i18next
