### ISSUE TITLE
not loading before page load

### ISSUE THREAD

**Issue by nicolasvahidzein** [i18next/i18next#1468]
This might be a config issue but when i access my vue based site after clearing the cache i don't get the strings translated. I get the variable names:

messages.profile_tokennotfound_title

Any idea how i can force i18next and my app to load the translations before displaying the page?

this is my i18next initialization code:

```
Vue.i18nextlocalization = {
		
		initiatei18next () {
			if (store.state.traceDebug === true) { 
				console.log('initiatei18next function in i18next.js')
			}
			
			console.log('i18 $$ before setting lang and fallbacklang: ' + i18next.language)
			
			i18next
			.use(XHR)
			.init({
				lng: 'en',
				fallbackLng: 'en',
				debug: true,
				backend: {
					
					loadPath: '/localization/locales/{{lng}}/{{ns}}.json',
					allowMultiLoading: false,
					crossDomain: true,
					
				}
			
			}, function (err, t) {
				
				if (store.state.traceDebug === true) {
					console.info('i18next.language', i18next.language)
				}
				
				if (err) {
					console.log(err)
				}
				
				store.commit('changeLocale', 'en')
				
			})
			
			i18next.on('initialized', function(options) {
				
				console.log('i18 $$ i18 is initialized')
				
			})
			
			console.log('i18 $$ bottom of the constructor')
			
			console.log('i18 $$ before after setting lang and fallbacklang: ' + i18next.language)
			
		},
		
		listenToi18nextChanges () {
			if (store.state.traceDebug === true) { console.log('listenToi18nextChanges function in i18next.js') }
			
			i18next.on('languageChanged', () => {
				this.updateContent()
			})
			
		},
		
		updateContent () {
			// document.getElementById('output').innerHTML = i18next.t('key')
			if (store.state.traceDebug === true) { console.log('changeLanguage function in i18next.js Language changing to: ' + i18next.language) }
			
			//change it in the store to tell everyone to update
			store.commit('changeLocale', i18next.language)
			
			//also change at the same time the vee validate locate to stay in sync
			Validator.localize(i18next.language)
			
			//change locale in moment js
			moment.locale(i18next.language)
		}
		
	}
	
	Object.defineProperties(Vue.prototype, {
		$i18nextlocalization: {
			get () {
				return Vue.i18nextlocalization
			}
		}
	})
```

Thanks

**Comment by jamuhl** [comment]
Well - the i18next.init/loadNamespace has the callback or promise and there are the events too triggering changeLanguage, ...

In react-i18next we use those to delay rendering using a HOC (or hook) and trigger rerender on needed events

For vue I'm not sure - as I do not know the internals of cue (never used it myself) but you might ask for help here: https://github.com/panter/vue-i18next (they should know how to do it right)

**Comment by nicolasvahidzein** [comment]
ok will try to figure that out. Thanks.

**Comment by brunodevel** [comment]
Hey @nicolasvahidzein, did you find a solution to this?

**Comment by nicolasvahidzein** [comment]
No @brunodevel bruno it's driving me nuts. You?

I'm not using vue next but just i18next and i can't figure out why it's not working, also i can't reproduce it because clearing the cash does not seem to be the determining factor.

**Comment by adrai** [comment]
Would be nice to have a codesandbox or similar to play a bit...

**Comment by adrai** [comment]
Seems vue-i18next is binding the loaded event: https://github.com/panter/vue-i18next/blob/master/src/i18n.js#L19 so it will rerender when the translations are loaded via xhr/http
Am I correct @claudiocro ?

**Comment by brunodevel** [comment]
@adrai that seems to be right. I can check it by using the parseMissingKeyHandler method:
```javascript
i18next.use(i18nextBackend).init({
    lng: currentLocale,
    fallbackLng: fallbackLocale,
    ns: [defaultNamespace],
    defaultNS: defaultNamespace,
    saveMissing: true,
    backend: {
        loadPath: '/redesign/lang/{{lng}}/{{ns}}.json',
    },
    parseMissingKeyHandler(key) {
        return '_'.repeat(key.length);
    },
});
```
In the initial rendering, I see the underscores, then the translated texts once the messages are loaded and after this any missing keys.
