### ISSUE TITLE
i18next::translator: missingKey en translation

### ISSUE THREAD

**Issue by prabhjot3** [i18next/i18next#1473]
For localization purpose I am using i18next in my create react app. I am getting i18next::translator: missingKey en translation error in console. Can anyone help here?

Below is my i18n.js file

import i18n from 'i18next';
import Backend from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';
import { TRANSLATE_FILE_PATH } from 'constants/AppConstants';

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    backend: {
      loadPath: TRANSLATE_FILE_PATH,
    },
    whitelist: [
      'en', 'de',
    ],
    fallbackLng: 'en',
    debug: true,
    interpolation: {
      escapeValue: false,
    },
  });

export default i18n;

![image](https://user-images.githubusercontent.com/8606795/85297322-38ed0780-b4c0-11ea-94b5-df937cd8373f.png)

**Comment by jamuhl** [comment]
follow the sample: https://github.com/i18next/react-i18next/tree/master/example/react

use hook or HOC to make sure translations are loaded before accessing them

**Comment by prabhjot3** [comment]
I am using withTranslation() hoc to access the t function and I guess translations are loaded before accessing them. PFB:

![image](https://user-images.githubusercontent.com/8606795/85302689-1f02f300-b4c7-11ea-9857-f13df2748bf5.png)

**Comment by jamuhl** [comment]
Then something is wrong with your code...

Not sure if that last line is complete but looks like you're calling the `t` function somewhere with an empty key.

**Comment by prabhjot3** [comment]
The last line is complete and I am not getting a specific key missing error, that is where I am assuming that I am not calling the t function with an empty key.

**Comment by adrai** [comment]
Can you create a reproducable example?
Hard to help, without.

**Comment by prabhjot3** [comment]
Actually I found the issue in my code, someone was trying to translate a dynamic message from redux and that is why I was getting the missing key logs. Have fixed that. We can close this issue.

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏

**Comment by Pushpendra92** [comment]
I am trying to access S3 bucket file but for some reason I am getting missing key error - 
`i18next::translator: missingKey ch`
`i18next::translator: missingKey en`

I have used the boilet plate code from the i18n-react repo only.

I am attaching the codesandbox playground. Can someone let me know what is wrong with my code?
https://codesandbox.io/s/react-i18next-forked-poi7m?file=/src/app.js

**Comment by jamuhl** [comment]
@Pushpendra92 check the console.log or network tab:

![image](https://user-images.githubusercontent.com/977772/94608316-8f2acd00-029d-11eb-966e-9146e11be8df.png)

the URL you defined is not accessible

**Comment by InanBerkin** [comment]
@jamuhl I think you should try `https://i18ntest.s3.ap-south-1.amazonaws.com/locales/en/translations.json`, so `en` not `en-US`

**Comment by adrai** [comment]
the namespace is incorrect: translation => translations

**Comment by jamuhl** [comment]
@InanBerkin both failed...and yes adriano is right...the default namespace is translation not translations...https://github.com/i18next/i18next/blob/master/src/defaults.js#L6

**Comment by jamuhl** [comment]
the screenshot even showed you the two warning i18next logs for you - what else can we do to help you?

**Comment by Srishti5ingh** [comment]
Hey @prabhjot3 

Can you specify what should be the syntax of { TRANSLATE_FILE_PATH } in your code?
Sorry, I am very new to all this.  But please respond.
My files are in, public\locales\de and public\locales\en

import { initReactI18next } from 'react-i18next';
import { TRANSLATE_FILE_PATH } from 'constants/AppConstants';  
--------------> what is contants/AppConstants?

i18n
.use(Backend)
.use(LanguageDetector)
.use(initReactI18next)
.init({
backend: {
loadPath: TRANSLATE_FILE_PATH,     -----?
},

**Comment by prabhjot3** [comment]
> Hey @prabhjot3
> 
> Can you specify what should be the syntax of { TRANSLATE_FILE_PATH } in your code?
> Sorry, I am very new to all this. But please respond.
> My files are in, public\locales\de and public\locales\en
> 
> import { initReactI18next } from 'react-i18next';
> import { TRANSLATE_FILE_PATH } from 'constants/AppConstants';
> --------------> what is contants/AppConstants?
> 
> i18n
> .use(Backend)
> .use(LanguageDetector)
> .use(initReactI18next)
> .init({
> backend: {
> loadPath: TRANSLATE_FILE_PATH, -----?
> },

@Srishti5ingh  
TRANSLATE_FILE_PATH = `${HOST_URL}/locales/{{lng}}/{{ns}}.json`;
where host_url will be your host, for eg http://localhost:3000

**Comment by Srishti5ingh** [comment]
Thank you so much @prabhjot3.
If you have got some time, can you take a look at my code?
