### ISSUE TITLE
Unable to create a new independend instance

### ISSUE THREAD

**Issue by shwao** [i18next/i18next#1477]
## 🐛 Bug Report

The functions `createInstance` and `cloneInstance` apparently do not create a new instance or clone it. When i use either of them it will change the original instance.

I try to create a clone or new instance and load a different namespace called "email". **I do not want this namespace to be loaded in the original instance.** Thats why im trying the obvious choices `cloneInstance` and `createInstance`. But with both of them the namespaces in the original instance will change and load the email namespace on next page load.

The description text of `cloneInstance` reads: 
> Creates a clone of the current instance. Shares store, plugins and initial configuration. Can be used to create an instance sharing storage but ***being independent on set language or namespaces***.

"independent on set language or namespaces" means to me that the namespaces or language of the original instance should not change. Why would they?

## To Reproduce
Code to initialize the main instance for express:
```ts
const i18nextInstance = i18next.createInstance({
	supportedLngs: ["de_DE", "en_US"],
	fallbackLng: "en_US",
	defaultNS: "translation",
	backend: {
		loadPath: `${__dirname}/locales/{{lng}}/{{ns}}.json`,
		addPath: `${__dirname}/locales/{{lng}}/{{ns}}.missing.json`,
	},
});

i18nextInstance
	.use(Backend)
	.use(i18NextHttpMiddleware.LanguageDetector)
	.init();

i18nextInstance.languages = ["de_DE", "en_US"];

app.use(i18NextHttpMiddleware.handle(i18nextInstance));
```
Then in a function to send emails i clone the instance but with settings to load the "email" namespace. The instance works and is usable but it is not a clone nor independent on set language or namespaces.
```ts
const clonedInstance = i18nInstance.cloneInstance({
	ns: ["email"],
});
```
I also tried to use `createInstance` which does not work for me because of an (probably unrelated) error with react suspense. However it also changes the original instance!

## Expected behavior
I would expect the function `cloneInstance` to do what the description says and be ***independent on set language or namespaces***. The same with `createInstance`. When i use both of them i would expect to get a new instance that can be changed without changing the original instance.

**Comment by jamuhl** [comment]
`cloneInstance` can have set lng and defaultNS independent of it's instance it was cloned of...`createInstance` shares nothing

**Comment by jamuhl** [comment]
cloneInstance is there to share the resourceStore filled with translations (so those do not get loaded multiple times)

**Comment by shwao** [comment]
So when i change the `ns` or `defaultNS` properties the new resource "email" will be loaded in to the shared `resourceStore`?
But even when i use `i18nInstance.createInstance({ ns: ["email"] })` to create a new instance it still shares the store. And also when i dont use the original `i18nInstance` but import it, it still shares the store:
```
import i18next from "i18next";
i18next.createInstance({ ns: ["email"] })
```
So the store is global?
Is there any way to either create a completly new instance with a seperate store or tell i18next to download only the "translation" namespace?

**Comment by jamuhl** [comment]
Are you sure createInstance shares the store? https://github.com/i18next/i18next/blob/master/src/i18next.js#L487

**Comment by jamuhl** [comment]
or https://github.com/i18next/i18next/blob/master/test/i18next.spec.js#L13

**Comment by shwao** [comment]
I create two seperate instances for express and for sending emails. They both use the `i18next-fs-backend`:
```
import i18next from "i18next";
const Backend = require("i18next-fs-backend");

const i18nextInstance = i18next.createInstance().use(Backend);
```
And when i load a resource in one of them it will appear in the other one. Is it maybe because `Backend` is cached?

**Comment by jamuhl** [comment]
Please stop guessing...backend does not cache...if both have the data it's because both loaded the namespaces...set debug: true on init and check your console output...

**Comment by shwao** [comment]
The debug output confirmed that the email namespace is loaded, but not why.. But i found it. It was a mistake, i passed the original instance instead of the new one. Ill go over in the corner and be ashamed. 

Thanks for your fast reply and work on this awesome project!

**Comment by jamuhl** [comment]
haha...no worry...can happen...glad you figured it out.
