### ISSUE TITLE
PO Database 

### ISSUE THREAD

**Issue by mark-lester** [i18next/i18next#1478]
## 🚀 Feature Proposal
Support po data stored in a database, get and put resource to retrieve from that.
subsequent utilities to output po files from the DB
enhancement of schema to include "domain", essentially a unique project id.  

## Motivation
I want to share, reuse and modify sets of translations. 

## Example
1. editor application now easy. 
2. import from a global repo all translations for all terms in your ceded database of translations
3. upload new or updated translations to global repo (using your github id)
 
subsequently can develop arbitration process for assigning default and accredited status etc.

## Plan
I am  looking at getPath and setPath and working where we are at. I will build an overlay package for those methods and just get this to work, and that will probably be enough. I dont propose at this early stage, if ever, to integrate it directly into this, I am just RFC and FYI and sanity checking both the missing DB interface and also the missing global, public translation DB.

If this is something you have discussed or have requests or ideas on how it should be done, please comment.
I will be using Sequelize.

**Comment by jamuhl** [comment]
> I want to share, reuse and modify sets of translations.

use our https://locize.com for management

or build your own backend: https://www.i18next.com/misc/creating-own-plugins#backend

**Comment by jamuhl** [comment]
https://www.i18next.com/overview/plugins-and-utils#backends --> mongodb-backend might be a inspiration

**Comment by mark-lester** [comment]
many thanks.
I found this http://littlesvr.ca/ostd/index.php. Is this a rival system ?. 
I want native edit capability because I want the users themselves, if they will at least identify themselves, to have the ability to provide translation to stuff we have to in languages we havent done. I'll discuss that in some detail if you like. 
I then want that developer to be able to upload those, seamlessly via an api not by literally uploading a pot file, and the translations we got from his users added to a global open repo, and new translations for his phrases being returned..
Can I do that with your stuff ?.

We'd then need some arbitration model so I was considering writing it as a githib application, but not on diffs of pot files, something more granular, selecting and voting on best or defaults, removing spam etc. If someone is already running a free to use central repo, and will handle this kind of user supplied translations, and has an api so that I can, given a password or git credentials, do the synching automatically, then I am done. But I need to be able to edit them locally, both via full application but lso via a widget that the user can right click on anything translatable if he is in edit mode on the end application itself.

I'll have a good look at the backend stuff, sorry, I just couldnt work out where the stuff was coming in and out though I hadnt located the listener to the add message :).  Thanks a lot for the package.

**Comment by jamuhl** [comment]
> I found this http://littlesvr.ca/ostd/index.php. Is this a rival system ?.

I wouldn't look at that as rival (some free - and from the look - not too useful - but I might be wrong)

With https://locize.com you can do something like https://www.youtube.com/watch?v=9NOzJhgmyQE using:

- https://github.com/locize/locize-editor
- and using https://docs.locize.com/guides-tips-and-tricks/working-with-translators#use-the-crowdbased-service might help with letting users translate part of your app

**Comment by mark-lester** [comment]
I do sincerely apologize :).I am still getting my head round whats going on. I am really in the game of building my take no prisoners stack and got to the translation stuff.  Thanks so much for i18next. 
Do you have an API so I can programmatically synch translations. My aim, certainly what is happening with this high profile open data project I am playing with, is that the user can hover over untranslated stuff in their own language and provide translations. At the very least I need a local .pot file editor. I will generate a REST interface to a DB and then write the backend to use that and look at how synching can be done.  

I ended writing this pile below, I would delete it, it was really just getting my purpose in life sorted, but I'll leave it there as I was trying to explain what I am doing, which is building my stack.


I just hit the i18n stuff, something I have had some experience of, I built the news and media platform and interface management for Yahoo sometime way way back. And indeed, my first ever ever job was to write a program to translate the TABS accounting software, written in BASIC 1.0. That was a very long time ago indeed.Purely to demonstrate where I am, here is what I am inventing. Along with some stackware to make sequelize to backbone more seamless, and a thing called ViewPoint for marionette, i have just been playing with the templating, a matter close to my heart. 
I have thought up a very simple and effective scheme for handling multi phase template execution. There are three key stages of potential execution imo.1. First time exec. could also be done at a compile or install stage. Typically translation stuff, could also be fixed includes and anything else static.
2.On delivery. Paint the page at request time. 
3.On render. In the client
I code these distinctly with {%, {@ and {{ and override the handlebars delimiters. To translate things using the __ stuff in the handlebars-i18n stuff you would go{%__"translate me"%} 
meaning translate using t() the first time for any language setting. I shorthand that to 
{""translate me""}, 
and can thus interpret it as{@__"translate me"@}
meaning run t() at delivery timewe then just have a .edit sub dir everywhere and chose that as the target, and if you have edit set we adapt the search path and you get live translations (from reload) and i wwe can stick a div tag round it so we can light things up and pop up a widget if you right click.
I then add extensions __hdbs and _hdbs, for execute on delivery time , so if I have a dynamic , change pn every load, homoe page with stuff that we can translate, go 
index.html._hdbs.__hdbsand code the once only as {% and the everytime as {@

If you have stuff that can be resolved once only, such as translations, you add a __hdbs extension.Soindex,html.__hdbswhich means run first time for any given language context
upon request, if there is an __hdbs file, look in the __hdbs/<LANGUAGE CODE> directory for that file, if its missing or older, regen and output.To run the handlebars code everytime, you need to code the actions as {@ and add a _hdbs  
If I have a dynamic home page that also has translatable stuff, I will haveindex.html._hdbs.__hdbswhen requested we first seek for index.html[._hdbs].__hdbsas there is a __hdbs we execute is, so if we have fr set we will have a file__hdbs/fr/index.html._hdbswe then interpolate the __hdbs/fr directory into the path, ie add an extra entry for every one there, and then attempt index.html_hdbs, if we dont find that then we will just return a raw index.html
So I had better get on with that.




    On Thursday, 9 July 2020, 13:02:08 GMT+7, Jan Mühlemann <notifications@github.com> wrote:  
 
 



I found this http://littlesvr.ca/ostd/index.php. Is this a rival system ?.


I wouldn't look at that as rival (some free - and from the look - not too useful - but I might be wrong)

With https://locize.com you can do something like https://www.youtube.com/watch?v=9NOzJhgmyQE using:
   
   - https://github.com/locize/locize-editor
   - and using https://docs.locize.com/guides-tips-and-tricks/working-with-translators#use-the-crowdbased-service might help with letting users translate part of your app

**Comment by jamuhl** [comment]
nice...did something similiar if I remember right around 15years ago in the C#, ASP.NET MVC world...

locize comes with a full API: https://docs.locize.com/integration/api

**Comment by mark-lester** [comment]
wow. plenty of api. many thanks.
i still need to write an editor, including a widget one that integrates into the actual application interface. "translate me".
I will then look at synching, uploading and drawing translations via the API.
Of course handlbars doesnt like asynchronous promises but there is a fix for that, but I will need to ensure thats handled OK in the handlebars i18next bridge. Enabling handlebars to work synchornously with data transfers is a massive help to the handlebars coder. We dot need this client side, but server side I want to ask for the data at the top of, and inside, the execution of the template, sometimes.
I want is to be able to populate the DB just by running the templates. So you can run data through it if you like, e.g. football team names, if you run the translation further up the template stack. I want application users to be able to contribute their own translations, and I want new terms to pass through the translation cycle (i.e. bounce through you) unseen for new translations. It just happens, we are now in mongolian. 
I'll keep you posted.
