### ISSUE TITLE
Support underscore tag separator

### ISSUE THREAD

**Issue by x1ddos** [i18next/i18next#1484]
https://www.unicode.org/reports/tr35/#Unicode_Language_and_Locale_Identifiers defines both `-` and `_` as tags separator.

While this package supports only the former, many systems report locale with underscore `_`. This results in [getLanguagePartFromCode](https://github.com/i18next/i18next/blob/8c631604/src/LanguageUtils.js#L19-L34) returning `de_DE` for input `de_DE` on such systems. The expected return value is `de`.

**Comment by jamuhl** [comment]
I guess it's easier to convert `_` to `-` in userland for those few systems not using `-`...than supporting both in the complete ecosystem

**Comment by x1ddos** [comment]
> I guess it's easier to convert `_` to `-` in userland for those few systems not using `-`...than supporting both in the complete ecosystem

I kind of makes i18next package an incomplete implementation of the standards.

**Comment by benma** [comment]
Looking through the other issues, there are other people that have been bitten by this. Seems like `_` is still in use unfortunately.

The fix in the code should be trivial, so I vote for adding it. If not, maybe the docs could be extended to cover the language tags and requirements, and that this workaround might be needed?

**Comment by jamuhl** [comment]
@x1ddos there are n-standards...what I learned in 10 years of i18next -> fewer options are better -> the fewer variations the more it is a standard...everything else is a configuration mess, allowing all kind of "standards". i18next for sure has too much configuration options and enforcing one standard for interpolation suffix/prefix, locales, ... would be better in long term.

> The fix in the code should be trivial

Sure solving it only in i18next would be trivial...but i18next is more than the i18next repo.
