### ISSUE TITLE
be able to optimize language files (en.json, pt-br.json and so on)

### ISSUE THREAD

**Issue by sibelius** [i18next/i18next#1485]
## 🚀 Feature Proposal

Be able to trim keywords used in a given project

## Motivation

We have a monorepo with some frontends, like this:
packages
- app1
- app2
- app3
- i18n

We have all localized strings inside i18n that are shared among app1, app2, app3.
Can we generate at the build time en.json files that only contain keys used in app1?
Can we even go further and code split keys per app route?

## Example

If user is accessing the user login, the best ux would be to only load keys for the login route, not for the whole app

**Comment by jamuhl** [comment]
https://www.i18next.com/principles/namespaces

**Comment by sibelius** [comment]
is there a way to make this less manual?

**Comment by jamuhl** [comment]
depends on your frontend framework...for react it's rather simple...

for others...how should i18next do the magic...? Any ideas?

**Comment by sibelius** [comment]
how is with React simpler?

I think fbt (https://github.com/facebook/fbt) knows all components that called them

and then can generate the minimal .json file per route

not sure if we can do the same with i18next

the i18next-scanner already does some tracking but misses some dynamic usages

not sure how to solve the dynamic parts of i18n

**Comment by jamuhl** [comment]
hooks, HOC define what namespaces are used saveMissing feature builds your json...simple enough for me (eg. using locize or some express server)

**Comment by jamuhl** [comment]
If you got better ideas...contributions are very welcome

**Comment by sibelius** [comment]
can I lazy load some translations files?

I have my default app language (pt-br), and I only wants to load en.json (English version), when the user changes the language

what is the best way to achieve this

I'd like to have something using `await import()` webpack api

**Comment by jamuhl** [comment]
https://www.i18next.com/how-to/add-or-load-translations

**Comment by sibelius** [comment]
Can I add more keys and values to a given language resource? Without needing a namespace?

**Comment by jamuhl** [comment]
there is always a namespace (default `translation`)
