### ISSUE TITLE
skipOnVariables prevents multiple placeholders

### ISSUE THREAD

**Issue by rynti** [i18next/i18next#1490]
## 🐛 Bug Report

When using skipOnVariables, it appears that all interpolation stops as soon as a placeholder with a variable-like syntax is encountered (for example a placeholder that contains the string `"{{foobar}}"`). I'm not sure if this is the desired behavior, and it definitely was unexpected for me. I would've thought that skipOnVariables just doesn't perform interpolation for the placeholder value itself, but still keeps performing interpolation after that placeholder was replaced with its value.

## To Reproduce

I have created [a codesandbox](https://codesandbox.io/s/i18next-skiponvariables-multiple-placeholders-1701x?file=/src/index.js) to demonstrate the case.

These steps need to be followed to reproduce:

1. Initialize i18next with `interpolation.skipOnVariables: true`
2. Setup a template where you use multiple placeholders (or the same placeholder multiple times)
3. Invoke it where one placeholder has a variable syntax like `{{test}}` (Make sure this placeholder is not only used as the last placeholder in the template, because in that case it works fine)

## Expected behavior

I expect all placeholders to be replaced with their values that I passed to the `t` function, and not that it stops interpolation completely after it encounters one variable-like placeholder.

## Your Environment

- *runtime version*: node v12
- *i18next version*: 19.6.1
- *os*: Windows

**Comment by rynti** [comment]
Although this could be considered a different bug, but I also noticed that `skipOnVariables` is missing from the TypeScript definition file. I wanted to create a pull request for that, but since I am unclear on what the desired behavior of skipOnVariables is, I am unable to write the proper documentation text for it.

**Comment by adrai** [comment]
should be fixed with v19.6.2

**Comment by rynti** [comment]
Wow, thank you very much! Can confirm that it is fixed in 19.6.2.
