### ISSUE TITLE
Locale "ht" is missing from PluralResolver.js

### ISSUE THREAD

**Issue by marcja** [i18next/i18next#1491]
## 🐛 Bug Report

Locale "ht" is missing from [PluralResolver.js](https://github.com/i18next/i18next/blob/master/src/PluralResolver.js). Tools such as [i18next-parser](https://github.com/i18next/i18next-parser) expect there to be a valid PluralResolver for each desired locale. Since "ht" has no PluralResolver, i18next-parser fails when passed this locale.

## To Reproduce

Configure i18next-parser.config.js with:

```js
module.exports = {
  locales: ["ht"]
};
```

and run it against a codebase. Fails with a null-reference exception at https://github.com/i18next/i18next-parser/blob/master/src/transform.js#L130. The root cause is that there is no setting for "ht" at https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L15. 

## Expected behavior

Given that "ht" [doesn't support plurals](https://www.howtocreole.com/2018/03/plural-words-haitian-creole.html), "ht" should be added at https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L15. For example:

```js
  { lngs: ['ay','bo','cgg','fa','ht','id','ja','jbo','ka','kk','km','ko','ky','lo',
    'ms','sah','su','th','tt','ug','vi','wo','zh'], nr: [1], fc: 3 },
```

## Your Environment

- *runtime version*: node v14
- *i18next version*: 19.6.1
- *os*: Mac

**Comment by adrai** [comment]
released with v19.6.3
