### ISSUE TITLE
Step by step tutorial on setting up a project with i18next on React Native 

### ISSUE THREAD

**Issue by naishe** [i18next/i18next#1493]
Hey guys,

I have authored a 3 part tutorial based on my experience with i18next integration in a React Native project. 

- It covers basics to advance use cases and covers how to manage translations.
- It links back to appropriate documentation URLs for i18next and react-i18next
- It accompanies functioning React Native code for each part

I think it will be really helpful for the people not acquainted with localization and i18next to get going.

**It will be awesome if you consider linking these articles in the documentation.**

These links have no paywall, no advertisement of any sort. (the sk part in the query string bypasses the paywall)

**PART 1: THE BASICS**  
https://medium.com/cybermonkey/multiple-language-support-in-react-native-part-1-fa6966b62332?sk=ae13f7ed429fc83208f033321129ea55

**PART 2: RESOURCE ORGANIZATION AND SWITCHING LANGUAGES**  
https://medium.com/cybermonkey/mastering-multiple-language-support-in-react-native-part-2-d33262acc21d?sk=e670ed196678a2ffbd38899301d69c32

**PART 3: ADVANCE USAGE**  
https://medium.com/cybermonkey/mastering-multiple-language-support-in-react-native-part-3-d8091339c767?sk=20a5424484a055640a2b4139f6547774

The companion code repository is here: 
https://github.com/naishe/rn_multilanguage

Please free to provide suggestions. I would appreciate stars on the repo and claps on the Medium article.

Thanks!

**Comment by adrai** [comment]
Just scrolled through your article... 👍

May I ask why you didn't choose i18next-fs-backend to load the translations? Was there some issue?

Btw: it would be nice if you could update this example to the latest react-native version: https://github.com/i18next/react-i18next/tree/master/example/react-native
and add a hint in the readme and/or code to look at your example to see a more complete example.

What do you think?

**Comment by naishe** [comment]
I think your suggestions sound fantastic!

As far as the fs-backend is concerned, I was able to get things done with by splitting files and importing them into `index.ts`, so I did not look any further. I will give  i18next-fs-backend a try (because it looks fun) and update the tutorial mentioning this another way of loading translation. I think it worth it.

I will have a look at the React Native example and update the example over the weekend.

**Comment by naishe** [comment]
Hey, @adrai , I have looked into i18next-fs-backend. It seems like it depends on Node.js's fs module. Which is not available in React Native. One way could be installing rn-nodify which does not seem like a lightweight library. Do you know any other way to make fs-backend to work in React Native?

**Comment by adrai** [comment]
Ahh, didn't know react-native was not able...
Maybe https://www.npmjs.com/package/react-native-fs ?
Else keep it as is.

**Comment by naishe** [comment]
Yeah, looked into that as first go to dependency, there are two problem

1. i18next-fs-backend requires 'fs' module, react-native-fs module exports from 'react-native-fs' namespace
2. react-native-fs is too invasive (as in you need to poke into Java and Gradle files for Android)

So, I guess that's a no go.
