### ISSUE TITLE
Handling failed language change

### ISSUE THREAD

**Issue by NAllred91** [i18next/i18next#1495]
I have a PWA that often will be used offline. If the user tries to change the language while offline the request for translations will fail. There doesn't seem to be any mechanism for retrying these failed requests.

## Current Behavior
For example, I load the app with the language set to `en` and then go offline.  I then attempt to change the language to `es` using the following:
```
i18n.changeLanguage('es', (err, t) => {
// I get an error here, this is good!
})
```

I notice the language failed, so I reset it back to `en`. All good so far.

But now, if I call change `i18n.changeLanguage` while still offline I get no error:
```
i18n.changeLanguage('es', (err, t) => {
// No error this time, this is not good!
})
```

Also, all subsequent calls to `i18n.changeLanguage('es')` don't make additional xhr requests.

At this point I seem to be stuck, and I can never load `es` without refreshing the page.

## Expected Behavior
When offline, every time I call `i18n.changeLanguage` it should make an xhr request for that language and give me an error when it fails.

**Comment by NAllred91** [comment]
Looks like what I can when loading fails is the following:
```
delete i18n.services.backendConnector.state['es|translation']
```

Now I can retry my request to load `es`. This doesn't seem like the best way to handle this problem though.

**Comment by jamuhl** [comment]
Isn't this a little much asked from an i18n lib to also handle offline cases? Regarding the error...not sure where this does fail...might be in the backendConnector...which has a retry logic on fail and then finally gives up on network timeout. Not sure...might be easier to just disable the change language button if offline...as there is no way to change it while offline if not already having translations loaded....

**Comment by NAllred91** [comment]
I think this is a reasonable request.

I'm not asking that the i18n lib handles the offline cases, I'm just asking that it gives me the ability to handle them myself.

Specifically, it seems to me that every time I call `changeLanguage` it should make the attempt to load again if it does not have the translations loaded.

```
i18n.changeLanguage('es', (err, t) => {
// I should always get an error here if 'es' is not available at this point.
})
```

As far as I can tell, doing some version of this gives me the behavior I expect:
```
i18n.changeLanguage('es', (err, t) => {
    if(err) {
        delete i18n.services.backendConnector.state['es|translation'];
        ....
    }
    .....
})
```

But I don't think I should need to reach this far in to i18n to get this behavior.

**Comment by NAllred91** [comment]
My use case is offline, but you can imagine that the user just has a bad internet connection and for some reason the request to get `es` translations fails.  I should be able to recognize that failure and try again.

**Comment by NAllred91** [comment]
I'm not sure if this is helpful, but this is my custom i18n plugin I'm using to read translations using webpack's code splittling.

```
i18n.use({
    type: 'backend',
    read: async (
        language: string,
        namespace: string,
        callback: (err: any, translation?: any) => void
    ) => {
        if (language === 'en' && namespace === 'translation') {
            callback(null, en);
        } else {
            try {
                const translation = await import(
                    `Messages/${language}/${namespace}.json`
                );
                callback(null, translation);
            } catch (err) {
                callback(err);
                // This should not be necessary, but it is in order to be able to retry loading translations.
                delete i18n.services.backendConnector.state[`${language}|${namespace}`];
            }
        }
    },
})
```

It seems to work fine this way, it just took me awhile to figure out this bit. But I don't think this should be necessary to get the behavior I expect?
```
delete i18n.services.backendConnector.state[`${language}|${namespace}`];
```

**Comment by jamuhl** [comment]
Just like said...happy to accept a PR.

```js
i18n.changeLanguage('es', (err, t) => {
// I should always get an error here if 'es' is not available at this point.
})
```

just checked the code - seems the error gets (should get) passed down:

a) https://github.com/i18next/i18next-http-backend/blob/master/lib/index.js#L63
b) https://github.com/i18next/i18next/blob/master/src/i18next.js#L195
c) https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L124

So for offline I'm not sure where we loose that error...therefore PR welcome

Regarding the state -> you can reloadResources when coming back online or PR:

- https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L98 (if offline error set state to -2)
- if state -2 set pending like: https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L53

**Comment by NAllred91** [comment]
I haven't had a chance to test this out yet, but it looks like the issue is here https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L52

Deleting lines 51 and 52 would mean if the state is an error, we would fall in to the final `else` and the state would become `pending` again.  

When lines 51 and 52 are in place, we end up hitting this line when making a request for translations that have previously had an error: (https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L164).

And once we get to line 164, we get our `changeLanguage` callback called with no error.


I'll give this a try soon, but do you see any reason why lines 51 and 52 in BackendConnector.js can't be removed?

**Comment by jamuhl** [comment]
The point is...on error you don't want to request again in most cases - what the backend connector really does is deduplicate requests made (eg. think of react-i18next components loading namespaces individually on each component)...if one fails you don't like to make same failing request over and over...so you can't just remove line 51/52 to make your offline case work.

line 164 -> but that means you once got an error -> and on that second request we omit requesting again (cause of above reason)

But based on your analysis an option might be instead of doing nothing here: https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L52 an error gets added and returned to line 164 where the error gets returned in the callback if nothing to load.

**Comment by NAllred91** [comment]
I guess I'm not understanding why you wouldn't want to request again? The subsequent request would only be attempted on calls to `i18n.changeLanguage`.  I would expect that every time you call `i18n.changeLanguage` it makes a best effort attempt to get the requested translations?

I'm imagining the following scenario:

1. User selects a language in a dropdown and loading fails (for any reason. Server issues, user offline, request timeout, missing authentication, etc), this calls the following code:
```
i18n.changeLanguage('es', (err, t) => {
   // err is truthy in this case
  if(err) ... show some error notification to the user ...
})
```

2. The user sees the error notification and the language is not changed.
3. Some time later the user tries to change the language again. If the translation is not loaded, an attempt to get it should be made.


Maybe removing https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L52 has an impact on other situations besides just calls to `i18n.changeLanguage`?  (Like the react-i18next components loading namespaces individually on each component scenario you mentioned)

Do you agree that `i18n.changeLanguage` should always attempt to load translations if they don't exist? If not, I may look into setting up a better way of clearing errors manually so we can retry.

**Comment by jamuhl** [comment]
I'm ok with changing:

But based on your analysis an option might be instead of doing nothing here: https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L52 an error gets added and returned to line 164 where the error gets returned in the callback if nothing to load.

This gives you the needed info to call...i18next.reloadResources to force reload them.
