### ISSUE TITLE
Use of a universal observer to update all translations dynamically

### ISSUE THREAD

**Issue by zipel** [i18next/i18next#1496]
## 🚀 Feature Proposal

Hello, I would like to propose an easier way of handling each translatable element in plain javascript.

I have spent some time digging into the documentation and playing around with the framework but I haven't found a way to grab the elements I want to translate in a generic way rather than getting each one of them separately using

`document.getElementById('something').innerHTML = i18next.t('key');`

(as stated in the user guide)

## Example

In my example, I am having a dynamically generated website using RactiveJS (not that popular I know). I am trying to use something like

`<span data-i18n="title"></span>`

in my HTML file and/or any other combination of attributes like the super useful 

`data-i18n="[placeholder]key1;[value]key2"`.

I am using plain Javascript and the thing is, I haven't seen a way of setting the Javascript code to actually check every element that contains the attribute `data-i18n` and translate it on the fly.

Please let me know if this feature already exists in which case I should close this issue

**Comment by adrai** [comment]
Maybe I misunderstood, but probably you're not looking for a new feature but for another Framework...
Something like:
https://github.com/i18next/jquery-i18next
https://github.com/mthh/loc-i18next
?

**Comment by jamuhl** [comment]
you're looking for https://github.com/i18next/i18nextify i guess

**Comment by zipel** [comment]
I was probably looking for i18nextify thank you! 

I have a problem using that though, as far as I can see the option `ignoreTags: ['SCRIPT']` is hardcoded as a default in the i18nextify.js file and I am having all my HTML code wrapped into script tags as I am importing external templates so it does not translate anything for me at the moment. Unless this option is only supposed to ignore translating the actual script tag and not its children too.

In that case I must be missing something, I am using `keyAttr: 'i18next-key'` so I assume I have to use it like e.g.:
`<button on-click="sendClicked" id="sendButton" type="submit" i18next-key="send-button"></button>`

**Comment by adrai** [comment]
I assume you then need to create a specific module for Reactivejs... like https://github.com/i18next/react-i18next or https://github.com/panter/vue-i18next

**Comment by zipel** [comment]
I created a custom made decorator to use i18next, containing everything (eg updateSingleElement(node, key, attribute, parameter), updateContent(), createParameterObj(parameter)) and I used it like this:

`<input type="text" as-i18n="{key:'contactMail', attribute:['placeholder']}">`

but it seemed like an overkill to create functionalities that already exist.

I actually managed to make i18nextify work right now (I realized that everything can potentially be a key by itself without using `someAttr="someKey"` necessarily) but I have a weird problem at the moment, the translations get displayed in the elements maybe one out three tries (refreshes of the page) for no apparent reason. I am thinking that sometimes maybe the i18nextify kicks in earlier than the page has finished loading but that shouldn't be a problem for the observer, right?

**Comment by zipel** [comment]
**Update:** I noticed the forceRerender() function that updates the content exactly as I want it to if I run it with a timeout (for example 1 sec) after the init function. But this way it is not optimised, do you know if I can call forceRerender() after everything is finished loading in case it is needed?

**Comment by jamuhl** [comment]
should already wait for init callback before initial render: https://github.com/i18next/i18nextify/blob/master/src/index.js#L161

**Comment by zipel** [comment]
I managed to make almost everything to work (including setting options for interpolating dynamic content) but I am still experiencing weird behavior on some parts of the page. Basically, I am able to see some of the keys before the content is loaded via the JSON file and styling the body with `style="display: none"` does not seem to help. I am sure this is outside the scope of this issue though, so I am thinking of creating a new issue under _i18nextify_ instead, and describe what is happening more comprehensively. 

In any case, thank you so much for a great framework and for all your support of course!
