### ISSUE TITLE
Support for POSIX style locale codes

### ISSUE THREAD

**Issue by fildon** [i18next/i18next#1497]
## 🚀 Support for POSIX style locale codes

Currently i18next supports identifying the 'language part' of locale codes in the form [primarylanguage]-[region] e.g. `en-GB`. 

This proposed feature would add support for POSIX style locale codes of the form [language[_territory] e.g. `en_GB`

## Motivation

The distinction between `en-GB` and `en_GB` styles of locale code may seem trivial, but as-is i18next only supports the hyphenated style, whereas the underscored style has long been a feature of POSIX systems. As such using POSIX style locale codes with i18next is not easily possible. 

For a precise example of where this breaks down: PluralResolver will fail to find plural rules for locales of the form `en_GB`. This is due to it trying to fetch the plural rule by calling src/LanguageUtils.js > getLanguagePartFromCode(code) which will try to split the code by '-'. As such in the case of `en_GB` no plural rule is found. 

## Possible implementations

There's a couple ways this could be supported. In all places where the language code is extracted from the whole locale code, a check could be made to split by either '-' or '_'. 
For example in LanguageUtils.js:
```js
  getLanguagePartFromCode(code) {
    if (!code || !code.includes(['-', '_'])) return code;

    const p = code.split(/-|_/);
    return this.formatLanguageCode(p[0]);
  }
```

It might be even better to add a user configurable optional locale separator to provide compatibility with any arbitrary locale separator symbol. This could be made to default to '-' to copy the existing behaviour

**Comment by adrai** [comment]
I would not recommend to add the possibility to i18next to handle multiple locale formats. This would get more work for other plugins / frameworks / toolings around i18next and its ecosystem to handle this...

I suggest your convert the codes for i18next.

**Comment by fildon** [comment]
Ah ok, I see the concern here.

Perhaps instead there would be scope for a localeMapper plugin which maps usages of underscored locales to hyphenated locales. 

I can't immediately see a way to do this with the existing plugin system however 🤔

**Comment by fildon** [comment]
I'm going to close this issue, since I can see that this is not a feasible change right now.
