### ISSUE TITLE
Chain support for addResources

### ISSUE THREAD

**Issue by mafar** [i18next/i18next#1498]
Chain should be supported if possible for addResources atleaset

**Does not work:**
```
// does not work 

i18next
  .addResources('en', 'common', Lang_EN)
  .addResources('de', 'common', Lang_DE);
```
**Working:**
```
// but this works.

  i18next.addResources('en', 'common', Lang_EN)
  i18next.addResources('de', 'common', Lang_DE);
```

**Comment by adrai** [comment]
My I ask what the advantage is to have that chained?
btw: Why not creating a PR?

**Comment by mafar** [comment]
I was assuming since docs were not clear and there was already chaining in main examples at docs like this
```
i18next.use().use().init()
```

This was just a proposal for improvement and not a blocker in any sense so please go ahead and close it.
I did ran into it and figured out later that thsi command does not support chain.
Will see if i have time to make commit.

**Comment by adrai** [comment]
should be chainable with v19.7.0

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
