### ISSUE TITLE
Plurals: Passing 2 as a count selects translation key with suffix _1 for ru-RU

### ISSUE THREAD

**Issue by Yuripetusko** [i18next/i18next#1499]
## 🐛 Bug Report

Passing `2` as a count selects translation key with suffix `_1`

## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

https://codesandbox.io/s/react-i18next-forked-yqmyn

```js
// I would expect key `photoUploadSuccessful_1` to be used
t("photoUploadSuccessful", { count: 1 }) // Ваши фотографии успешно загружены!
```

## Expected behavior

``

```js
// Ваша фотография успешно загружена!
```

## Your Environment

- *runtime version*: node v16
- *i18next*:19.6.1
- *os*: Mac

**Comment by jamuhl** [comment]
did you read: https://www.i18next.com/translation-function/plurals ?

**Comment by Yuripetusko** [comment]
> did you read: https://www.i18next.com/translation-function/plurals ?

I did and according to docs `i18next.t('key', {count: 1}); // -> "singular"` should return `"key_1": "singular",` but in my case `count: 2` would return `"key_1": "singular",`

**Comment by Yuripetusko** [comment]
Unless I am missing something from the docs

**Comment by jamuhl** [comment]
https://www.i18next.com/translation-function/plurals#how-to-find-the-correct-plural-suffix -> try the utility listed:

![image](https://user-images.githubusercontent.com/977772/90440314-4ea13680-e0d7-11ea-8ebe-d85c32c3343c.png)

key_1 is not singular!

**Comment by Yuripetusko** [comment]
Thanks will try in the morning and report back, but according to my codesandbox above this is incorrect and suffix _2 is used when count: 1 is used. But will use this utility to dig further, thanks

**Comment by Yuripetusko** [comment]
Ok I see this is correct behaviour apparently, very confusing :) 

![image](https://user-images.githubusercontent.com/666169/90486098-5d680780-e130-11ea-9fb5-c08242c4ee51.png)
