### ISSUE TITLE
Improve docs for failedLoading event

### ISSUE THREAD

**Issue by erasmo-marin** [i18next/i18next#1500]
## 🚀 Feature Proposal

Improve the `failedLoading` event docs. Right now the description is:

> Gets fired if loading resources failed.

I think would be nice to be more specific since current description can be confusing, for example, does it fires for every retry? it fires after all retries? etc...

## Motivation

I'm trying to understand my logs on sentry

## Example

> Gets fired after all retries failed for a specific language.

**Comment by adrai** [comment]
https://www.i18next.com/overview/api#onfailedloading added additional info regarding the retries.
