### ISSUE TITLE
How to get i18n.language to only be set to non country code languages?

### ISSUE THREAD

**Issue by drj17** [i18next/i18next#1502]
## 🐛 Bug Report

With the `load: languageOnly` option I would expect the `i18n.language` value to not include the country code

## To Reproduce

```js
import i18n from "i18next";
import Backend from "i18next-http-backend";
import LanguageDetector from "i18next-browser-languagedetector";
import { initReactI18next } from "react-i18next";

i18n
  // load translation using http -> see /public/locales
  // learn more: https://github.com/i18next/i18next-http-backend
  .use(Backend)
  // detect user language
  // learn more: https://github.com/i18next/i18next-browser-languageDetector
  .use(LanguageDetector)
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init({
    fallbackLng: "en",
    debug: true,
    load: "languageOnly",
    supportedLngs: ["en", "de", "fr", "es"],
    interpolation: {
      escapeValue: false // not needed for react as it escapes by default
    }
  });

export default i18n;
```

## Expected behavior

i18.language to be `en`, but it's still `en-US`.  This is a problem because I have selector where the current value is i18n.language and the values are the supported languages, and it's rendering `en-US` instead of `English` because the option is `<option value='en'>English</option>`

**Comment by jamuhl** [comment]
i18n.language will always be exact detected locale. i18n.languages will be an array containing locales in order of priority for resolving a key (i18n.languages[0] might be what you search)

**Comment by drj17** [comment]
AH okay, thanks for the clarification, I'll close this then.

**Comment by mfcoxo** [comment]
I ran into this "issue" today. Removing the ` load: "languageOnly"` seems to make `i18n.language ` display "correctly" based on what is indeed selected.
It makes 2 requests: one for "en-US" and one for "en" that will indeed succeed.
Is this the intended behaviour? Seems strange to have to use `i18n.languages[0]`

**Comment by jamuhl** [comment]
it's how i18next handles the "fallback chain" https://www.i18next.com/principles/fallback#language-fallback

**Comment by burtyish** [comment]
Note that you can now use [`i18next.resolvedlanguage`](https://www.i18next.com/overview/api#resolvedlanguage), introduced in v21.0.0
