### ISSUE TITLE
Not supporting different case with latest bugfix

### ISSUE THREAD

**Issue by sofi-d** [i18next/i18next#1503]
## 💥 Regression Report

With previous version we were able to use path detection as <my_domain>/pt-br or <my_domain>/pt-BR
In the latest version this behavior is not longer possible, only works with pt-BR

This is due to line added in latest bugfix where indexOf checks for strict comparison disregarding casing: 

if (found && detections.indexOf(found) < 0) found = undefined

so "found" results  undefined, while in previous version was defined as the detected language.

## Last working version

Worked up to version: 3.0.3

Stopped working in version: 3.0.4

## To Reproduce

Configure path detection and input a URL with /pt-br, it will default to es-AR

```js
  fallbackLng: 'es-AR',
  supportedLngs: ['es', 'pt'],
  nonExplicitSupportedLngs: true,
  detection: {
    order: ['path'],
    lookupFromPathIndex: 0
  }
```

## Expected behavior

I expect it to work as previous version, with both lower or uppercase, or else if this is intended behavior, maybe docs should be updated to take this into account.

## Your Environment

- *runtime version*: node v14.9.0
- *i18next version*: i.e. 19.7.0
- *os*: Mac

**Comment by adrai** [comment]
Do you mean i18next-http-middleware ?
If so, it was part of the major version v3.0.0 (but fixed in v3.0.4)
It's intended to match exactly.

**Comment by sofi-d** [comment]
Yeah , sorry, mixed the github repos 🤦 alright, we'll consider that then. Thanks!

**Comment by adrai** [comment]
fyi: with i18next-http-middleware@3.0.5 there is now a ignoreCase option, this should be useful for your use case

**Comment by sofi-d** [comment]
Great! Thank you
