### ISSUE TITLE
Regional locale doesn't fallback to generic locale

### ISSUE THREAD

**Issue by christianlundberg** [i18next/i18next#1505]
## 🐛 Bug Report

When it detects a region locale which isn't supported, it doesn't load the more generic locale.

In my case, I'm only supporting English (es) and Spanish (es). Chrome detected the language as "en", so it was the only one to correctly translate anything. The other browsers detected regional locales, but i18next didn't seem to fallback to the more generic locale so it wasn't able to translate anything and instead it only outputs the translation keys.

## To Reproduce

```js
//i18n.ts
import i18next from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import Backend from 'i18next-http-backend';
import { initReactI18next } from 'react-i18next';

i18next
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: 'en',
    detection: {
      order: ['localStorage', 'navigator'],
      lookupLocalStorage: 'preferredLanguage',
      caches: ['localStorage'],
      excludeCacheFor: ['cimode'],
    },
    interpolation: {
      escapeValue: false,
    },
  });

//App.tsx
...
console.log(i18n.languages);
//Chrome: ["en"]
//Firefox: [ "en-US", "en" ]
//Edge: ["es-419", "es", "en"]
//IE: ["es-MX", "es", "en"]
```

## Expected behavior

When detecting "en-US", it should fallback to "en"; "es-419", "es-MX" and other variations should fallback to "es"

## Your Environment

- *runtime version*: Chrome, Firefox, Internet Explorer 11, Edge
- *i18next version*: 19.7.0
- *os*:  Windows,

**Comment by jamuhl** [comment]
? are 

//Chrome: ["en"]
//Firefox: [ "en-US", "en" ]
//Edge: ["es-419", "es", "en"]
//IE: ["es-MX", "es", "en"]

your outputs...looks correct es-X fallbacks to es and finally if not found in es to en

**Comment by christianlundberg** [comment]
@jamuhl 

Doesn't seem to do anything then, I don't understand what's wrong. Firefox, Edge and IE only output the translation key.

`
t(`hello.world`) 
//hello.world (Firefox, Edge, IE)
//Hello world! (Chrome)
`
 Chrome correctly outputs the translated text because it detected "en".

Translation files are as follows:

/locales/en/translation.json
/locales/es/translation.json

**Comment by jamuhl** [comment]
try setting debug: true on init...looks like translations get not loaded correctly

**Comment by christianlundberg** [comment]
@jamuhl 

These are the logs for Firefox, which detects en-US:

```
i18next::backendConnector: loaded namespace translation for language en 
Object { loading: "Loading", language: {…} }
i18next.js:22
i18next::backendConnector: loading namespace translation for language en-US failed failed parsing /locales/en-US/translation.json to json i18next.js:22
i18next: languageChanged en-US i18next.js:22
i18next: initialized 
Object { debug: true, initImmediate: true, ns: (1) […], defaultNS: (1) […], fallbackLng: (1) […], fallbackNS: false, whitelist: false, nonExplicitWhitelist: false, supportedLngs: false, nonExplicitSupportedLngs: false, … }
i18next.js:22
i18next::translator: missingKey en-US translation language.en-US language.en-US i18next.js:22
```

**Comment by jamuhl** [comment]
It says `loading namespace translation for language en-US failed failed parsing /locales/en-US/translation.json to json` the content you load seems to be a js object and not JSON

do you check by calling `i18n.t(`language.${i18n.language}`)` ?!? or why there is a missing key `language.en-US`
