### ISSUE TITLE
"'Promise' in undefined" in IE11

### ISSUE THREAD

**Issue by ChenGuanglin0924** [i18next/i18next#1507]
## 🐛 Bug Report

When i use ie11 with i18next, the browser report a error `'Promise' in undefined`. I tried `@babel/runtime, @babel/plugins-transform-runtime` and `@babel/polyfill`, but it still doesn't work.

## To Reproduce

at least steps to reproduce the behavior:

babel.config,js
```js

// with out `@babel/runtime`
module.exports = function (api) {
    api.cache(true);
    const presets = [
        [
            '@babel/preset-env',
            {
                useBuiltIns: 'usage',
                corejs: 3
            }
        ],
        '@babel/preset-react',
        '@babel/preset-typescript'
    ];
    const plugins = [
        '@babel/plugin-syntax-dynamic-import'
    ];
    
    return {
        presets,
        plugins
    };
};

// with `@babel/runtime`
module.exports = function (api) {
    api.cache(true);
    const presets = [
        [
            '@babel/preset-env',
            {
                useBuiltIns: 'usage',
                corejs: 3
            }
        ],
        '@babel/preset-react',
        '@babel/preset-typescript'
    ];
    const plugins = [
        '@babel/plugins-transform-runtime',
        '@babel/plugin-syntax-dynamic-import'
    ];
    
    return {
        presets,
        plugins
    };
};
```

webpack.config.js
```

rules: [
     {
          test: /\.(tsx|ts|js)$/,
          use: ['babel-loader']
      },
]

```

## Expected behavior

```js
i18next works in ie11
```

## Your Environment

- *@babel/runtime version*: i.e. @babel/runtime@latest, @babel/plugin-transform-runtime@latest 
- *i18next version*: i.e. 19.3.4
- *webpack version*: i.e. 4.44.1

**Comment by adrai** [comment]
https://github.com/i18next/i18next/issues/1438#issuecomment-619591144

**Comment by adrai** [comment]
To check if you polyfilled Promise, go to your developer console, or in your code and try to log Promise or window.Promise
