### ISSUE TITLE
docs: Add .use() use-case for the createInstance docs

### ISSUE THREAD

**Issue by philippefutureboy** [i18next/i18next#1509]
## 🚀 Feature Proposal

Suggested improvement to the docs - https://www.i18next.com/overview/api#createinstance :

From:

*Providing a callback will automatically call init.*

To:

Providing a callback will automatically call init. **If you wish to add a plugin using the `use` method, do not pass a callback. Instead create the instance without a callback, call use on the instance and then call init manually.**

```js
const i18nInstance = i18n.createInstance();
i18nInstance.use(Backend)
return new Promise((resolve, reject) => {
    i18nInstance.init(config, (err, t) => {
      if(err) {
        reject(err);
      } else {
        resolve(t);
      }
    });
  });
```

## Motivation

Took me an hour an a half to figure out why the backend was not loaded because I was using `.use` on the export of i18next instead of with the instance. I know it can sound obvious, but I was getting errors and it wasn't clear what was causing it.
Also side-note promisifying init does not work (`require('util').promisify(i18nInstance.init)(config)`) even though the signature make me feel like it should 🤔

**Comment by jamuhl** [comment]
No need to use promisify -> init already returns a Promise

PR welcome to improve the text...
