### ISSUE TITLE
nesting recursively key with context

### ISSUE THREAD

**Issue by hextion** [i18next/i18next#1510]
## 🐛 Bug Report

Nested recursively keys with `context` don't work

## Code snippet

```js
import i18next from 'i18next';

i18next.init(
  {
    lng: 'en',
    debug: true,
    resources: {
      en: {
        translation: {
          test_foo: "foo $t(test, { 'context': 'bar' })",
          test_bar: "bar $t(test, { 'context': 'baz' })",
          test_baz: 'baz',
        },
      },
    },
  },
  function (err, t) {
    console.log(t('test', { context: 'foo' }));
    /* expected output */
    // "foo bar baz"

    /* actual output */
    // i18next.js:22 i18next::translator: It seems you are nesting recursively key: test in key: test
    // i18next::interpolator: missed to resolve test, { 'context': 'baz' } for nesting bar $t(test, { 'context': 'baz' })
    // "foo bar "
  }
);

```

## Your Environment

- *runtime version*: node js v12.18.4, chrome v85
- *i18next version*: 19.8.1
- *os*: macOS 10.15.6

**Comment by jamuhl** [comment]
Correct. You can't nest context...not even sure why one would do that? what is your use case?

**Comment by hextion** [comment]
Oops! I have been using this in my work (as in the example ones).
It worked on i18next@19.0.2 so I assumed this should work on i18next@19.8.1
I am done own investigation in source code and I got the bug (or undocumented feature maybe?) was broken in i18next@19.5.5
https://github.com/i18next/i18next/blob/c9be7ad858f2bcfe4f28b353af1bc3ed796cd592/src/Translator.js#L300

**Comment by hextion** [comment]
@jamuhl is there any way to return old behavior? Or I should fix i18next resources?

**Comment by adrai** [comment]
@hextion should be "fixed" in v19.8.2 with https://github.com/i18next/i18next/commit/d736006837d9b9284ef8a6e7a391f36bcc83d61e

**Comment by hextion** [comment]
@adrai @jamuhl big thanks for help! guys, you're awesome

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
