### ISSUE TITLE
Deno version is outdated and without type definitions

### ISSUE THREAD

**Issue by Zorgatone** [i18next/i18next#1512]
## 🚀 Feature Proposal

Push version v19.8.2 to Deno registry

## Motivation

Currently on https://deno.land/x/i18next the version is still v19.6.3 and does not include Typescript type definitions, just plain Javascript files

## Example

```typescript
import i18next from "https://deno.land/x/i18next@v19.8.2"

i18next.init // Here intellisense kicks in without the need to install other modules with the typings (ex: avoid node_modules and @types)
```

**Comment by adrai** [comment]
The webhook had an issue with the payload... should be fixed now.
Regarding the types, feel free to help.
i18next is written in JS and offers some types as index.d.ts

**Comment by Zorgatone** [comment]
I think deno needs a `mod.ts` file (to drop the /index.js last part of the import url), and in it you can reference the index.d.ts types (which I do not see pushed in the deno package) and re-export index.js

**Comment by adrai** [comment]
Why not just import it like this?
`import i18next from 'https://deno.land/x/i18next/index.js'`
or this?
`https://deno.land/x/i18next@v19.8.2/index.js`

like here: https://github.com/i18next/i18next-fs-backend/blob/master/example/deno/index.js

**Comment by adrai** [comment]
If you think this could be optimized, just try a PR

**Comment by Zorgatone** [comment]
It will give an error that that module is not declared in typescript, and if you declare it only it will have a any type. (Types aren't loaded)

**Comment by adrai** [comment]
This example works for me: https://github.com/i18next/i18next-fs-backend/blob/master/example/deno/index.js
Does it work for you too?

**Comment by adrai** [comment]
Ahh, your source is probably a .ts file... this is why you are getting the problem...
If your source file was a js file it would work without any problems.

Feel free to contribute to improve this behaviour... I'm not a deno and nor a TypeScript specialist

**Comment by adrai** [comment]
What works for me in a ts file is this:

```ts
// @deno-types="https://cdn.jsdelivr.net/gh/i18next/i18next/index.d.ts"
import i18next from 'https://deno.land/x/i18next/index.js'
```
