### ISSUE TITLE
i18Next language selection works differently in Incognito/Normal Chrome browser.

### ISSUE THREAD

**Issue by gautam1109** [i18next/i18next#1514]
## 🐛 Bug Report

This issue starts happening after recent changes in chrome Incognito mode. I have raised the issue to chrome and they closed it as designed change for the them. https://bugs.chromium.org/p/chromium/issues/detail?id=1139744

## To Reproduce
1. Open the URL: https://codesandbox.io/s/8187wm9yj8?file=/src/i18n.js In both normal and Incognito mode of Chrome. If you have english as default language the content will come in English in both the browser.
2. Goto Chrome Lanuage setting and add the language in order Dutch, German, English (Detutch is not supported in the example)
3. Refersh both the browser. Incogito - Content will appear in English, Normal mode: Content will appear in German.

The reason for this is, navigator.languages API returns different result in normal and Incognito mode.

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

Ideally both the browser should return the same result. i18Next should just consider the first language from the navigator.langugages API and should not iterate over it.

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. any, deno, browser Chrome latest- 86.0.4240.80
- *i18next version*: i.e. any
- *os*: any
- *any other relevant information*

**Comment by jamuhl** [comment]
Not an issue - we take what browsers give. If incognito mode downgrades the languages options - that's not the problem of i18next. Also, I not agree if this inconsistency is really a problem.

Anyway if you like a changed behaviour just add a own detection function doing so: https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality
