### ISSUE TITLE
Allow for nested namespaces

### ISSUE THREAD

**Issue by ahmedosama5200** [i18next/i18next#1516]
## 🚀 Feature Proposal

**Currently the structure of translation files goes like this:**
Folder(language) contains files(namespaces)

**What I am talking about is this:**
Folder(language) contains folders and files

## Motivation
I think you get the point. this way, we could further organize namespaces inside folders.
I am not sure if this feature is already supported. I read through the docs and they didn't talk about that at all

**Comment by adrai** [comment]
There is no subfolder concept in i18next and not in i18next-fs-backend...

https://github.com/i18next/i18next-fs-backend/issues/13

**Comment by ahmedosama5200** [comment]
Thank you so much. I think now, I understand why you don't support it.
