### ISSUE TITLE
i18n.isInitialized always returns true

### ISSUE THREAD

**Issue by ahmedosama5200** [i18next/i18next#1519]
## 🐛 Bug Report

Whenever you call `i18n.isInitialized`, it always returns true, no matter before or after calling init.
Also, I haven't really found this property listed in the api docs [here](https://www.i18next.com/overview/api)

## To Reproduce
https://codesandbox.io/s/react-i18next-forked-732kh?file=/src/index.js

**Comment by jamuhl** [comment]
because it is internal...and no...it is false before calling init https://github.com/i18next/i18next/blob/master/src/i18next.js#L154

**Comment by jamuhl** [comment]
your log statement is after init is done...just add one in i18n.js before calling init

**Comment by ahmedosama74574** [comment]
Seriously man, It always returns true
![Capture](https://user-images.githubusercontent.com/72021045/99361729-36e67380-28bb-11eb-8725-994cec1800d1.PNG)

**Comment by ahmedosama5200** [comment]
It actaully returns `undefined` which is techincally false. I am sorry about that. Codesandbox uses hot reloading. I had to refresh the page in order to see it return `undefined`

**Comment by adrai** [comment]
Yes, undefined is falsy and isInitialised is an internal api anyway.
