### ISSUE TITLE
i18next looks for en language when I don't specify it.

### ISSUE THREAD

**Issue by Ghosty669** [i18next/i18next#1522]
I've implemented the necessary i18next code to allow me to load and use my translation file but I'm seeing that my app is also attempting to load an apparent default file as well and I don't know how to turn this off.

My i18next.ts looks like this :

import i18next from "i18next";
import { initReactI18next } from "react-i18next";
import HttpApi from "i18next-http-backend";

console.log("In i18next.ts")
i18next
  .use(initReactI18next)
  .use(HttpApi)
  .init({
    lng: "en-US",
    interpolation: {
      escapeValue: false,
    },
    fallbackLng: 'en-US',
    debug: true,
    backend: {
      loadPath: `/locales/{{lng}}/{{ns}}.json`
    },
  });
  
export default i18next;

I then set up my index.ts to look like this 

import ReactDOM from 'react-dom';
import React from 'react';
import App from './App';
import "./main.css";
import "./localization/i18next";
ReactDOM.render(
    <React.StrictMode>
        <React.Suspense fallback="Loading...">
            <App />
        </React.Suspense>
    </React.StrictMode>,
    document.getElementById('root')); 

While this works fine, during the page load, I'm seeing the following error being reported:

![image](https://user-images.githubusercontent.com/15817129/101054452-d0cb4300-3580-11eb-860c-ba977afde568.png)

Any ideas what might be causing this?

**Comment by adrai** [comment]
set the load option to 'currentOnly'

https://www.i18next.com/overview/configuration-options
![image](https://user-images.githubusercontent.com/1086194/101054670-6b2f8480-3589-11eb-992d-271ebc957ead.png)

**Comment by Ghosty669** [comment]
Thanks! Worked a treat!

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
