### ISSUE TITLE
Improve documentation to API

### ISSUE THREAD

**Issue by jamiechong** [i18next/i18next#1525]
I'm having a hard time understanding the difference between `addResources` and `addResourceBundle`. The docs state:

> i18next.addResources(lng, ns, resources)
> Adds multiple key/values.
> 
> i18next.addResourceBundle(lng, ns, resources, deep, overwrite)
> Adds a complete bundle.
> 

I guess I'd like to know what the term "bundle" means and how it's different than a group of key/value pairs for a specific namespace.

**Comment by jamuhl** [comment]
Bundle means adding a complete translation file (JSON -> i18next namespace) and emits one event.

Add resources is to add a few keys and will emit an event per key added.

**Comment by jamiechong** [comment]
Okay that helps a bit. Thanks! I also notice that these functions require a `namespace` param, but it'd be nice if I could provide a bundle with multiple namespaces. Like this: 

```
i18next.addNamespaceBundle({
  "ns1": {
    "key": "value",
    ...
  },
  "ns2": { ... }
}
```

And it'd also be nice to be able to add an entire store - the same schema as what is accepted in `init({ resources })`, which is languages and namespaces together.

```
const resources = {
  "en": {
    "ns1": { ... },
    "ns2": { ... },
  },
  "fr": { ... }
}

i18n.replaceResourceStore(resources);
i18n.mergeResourceStore(resources);

```

**Comment by jamuhl** [comment]
never had a real use case that needed to replace the store or merge one -> the other functions are basically public but also used internally.
