### ISSUE TITLE
You may not call store.getState() while the reducer is executing

### ISSUE THREAD

**Issue by azotklas** [i18next/i18next#1527]
I have a website. in which this code

```
import i18n from "i18next";
import type { InitOptions } from "i18next";
import { initReactI18next } from 'react-i18next';
const options: InitOptions = {
  fallbackLng: 'en_US',
  nsSeparator: '^',
  ns: ['translations'],
  defaultNS: 'translations',

  keySeparator: false,

  interpolation: {
    escapeValue: false,
    formatSeparator: ','
  },

  react: {
    wait: false,
    bindI18n: 'languageChanged',
    nsMode: 'default'
  }
};
i18n
.use(initReactI18next)
.init(options)
```

then I change the language in the code in this way

```
if (payload.lang) {
   if (!i18n.hasResourceBundle(payload.lang, 'translations')) {
       i18n.addResourceBundle(payload.lang, 'translations', payload.translationTable, true, true);
    }
    i18n.changeLanguage(payload.lang)
 }
```

    
    
it works good, but sometimes when I refresh the page this error appears and breaks my site. 
**Error: You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.**
what could be the problem?

**Comment by azotklas** [comment]
it started to happen after updating modules
```
 "i18next": "9.0.1", =>  "i18next": "19.8.4",
  "react-i18next": "6.0.4", =>  "react-i18next": "11.7.3",
```
  
if you comment  
`i18n.changeLanguage(payload.lang),`
 then the error is not reproducible

**Comment by jamuhl** [comment]
Did you trigger some store update onLanguageChange?

The issue is somewhere inside your code...i18next has no store.getState function

**Comment by azotklas** [comment]
> Вы запускали обновление магазина на LanguageChange?
> 
> Проблема где-то внутри вашего кода ... i18next не имеет функции store.getState

**Comment by azotklas** [comment]
> Did you trigger some store update onLanguageChange?

yes, i triggered some store update onLanguageChange

**Comment by jamuhl** [comment]
then it's a redux issue?

**Comment by azotklas** [comment]
yes. sorry)
