### ISSUE TITLE
TFunction translation not working in EJS template render

### ISSUE THREAD

**Issue by mtbvang** [i18next/i18next#1528]
## 🐛 Bug Report

I have method that renders EJS templates and pass in the i18next.t function for the EJS template to do translations by setting the i18next t function as an attribute on the data object:

    const data = {
        			email: user.email,
        			id: user.id,
                    t: i18nT
        		};

The data object is passed into ejs.renderFile(). The only way I can get the translation in the EJS template to work is when I set the i18nT variable to the t function from the i18next.init() functions call back. Otherwise it comes out blank. I see from the console output that the t function of the i18next instance, i18nInstance, is different to the t function set by the callback when initializing i18next. 

    function t() {
        var _this$translator;
    
        return this.translator && (_this$translator = 
           this.translator).translate.apply(_this$translator, arguments);
    }

versus:

    function () {
        return _this4.t.apply(_this4, arguments);
    }

Why is the t function of the i18nInstance object obtained from calling i18next.createInstance() different than the one from the callback? The one from the instance object doesn't not work in the EJS template render.

## To Reproduce

The full code sample:

```js
    let i18nInstance: i18n;
    let i18nT;

    const i18nextInitOptions = {
        backend: {
            loadPath: path.join(__dirname, '/locales/{{lng}}/{{ns}}.json'),
            addPath: path.join(__dirname, '/locales/{{lng}}/{{ns}}.missing.json')
        },
        debug: true,
        fallbackLng: 'da',
        preload: ['da', 'en', 'nl'],
        returnEmptyString: false,
        returnNull: false,
        saveMissing: true
    };
    i18nInstance = await i18next
        .createInstance();
    await i18nInstance
        .use(i18nextBackend)
        .init(i18nextInitOptions, async function (error, t) {
            if (error) {
                console.log(error)
            }
            i18nT = t;
        });


    console.log("i18nT: " + i18nT)
    /*
    The console.log outputs below show that i18nT when set from the callback is different to the 
    i18nInstance.t.
    i18nT: function () {
      return _this4.t.apply(_this4, arguments);
    }
     */
    
    console.log("i18nInstance.t: " + i18nInstance.t)
    /*
    console output:
    i18nInstance.t: function t() {
          var _this$translator;

          return this.translator && (_this$translator = 
             this.translator).translate.apply(_this$translator, arguments);
    }
    */

    const data1 = {
    			email: user.email,
    			id: user.id,
                t: i18nT
    		};

    // Calling htmlFromTemplate with data1 with t = i18nT the translation in the EJS template works.
    html = await this.htmlFromTemplate('ejsTemplateName.ejs', data1);

    const data2 = {
    			email: user.email,
    			id: user.id,
                t: i18nextInstance.t
    		};

    // Calling htmlFromTemplate with data2 with t = i18nextInstance.t the translation in the EJS is empty.
    html = await this.htmlFromTemplate('ejsTemplateName.ejs', data2);

    private htmlFromTemplate(templateName: string, data: Object): Promise<String> {
    		if (!templateName) return;
    		const htmlPath = path.join(__dirname, '../assets/mail-templates/' + templateName);
    		return new Promise((resolve, reject) => {
    			ejs.renderFile(htmlPath, data,(renderErr, str) => {
    				if (renderErr) {
    					appLogger.error('MAIL_RENDER: ' + renderErr, { templateName, data });
    					reject(renderErr);
    				} else resolve(str);
    			});
    		});
    	}
```

## Expected behavior

I'm new to i18next so maybe I'm not understanding how the t function is supposed to be used. I expect that the t function behaves the same way no matter where I get it from, such that I can pass the i18next.t function to EJS the same way as I can pass the function gotten from the init callback via variable assignment from the callback..

## Your Environment

- *runtime version*:node v12.14.2, express
- *i18next version*: 19.8.4
- *os*: Linux

**Comment by adrai** [comment]
Can you paste an example of your ejs file? To see how you call the t function in there...

**Comment by adrai** [comment]
btw: does it work for with this change? https://github.com/i18next/i18next/pull/1529/files

**Comment by mtbvang** [comment]
@adrai In EJS I use e.g: `<strong><%= t('mailTemplates.outOfEHChecks.userOutOf') %></strong>`

**Comment by adrai** [comment]
ahh, now I see your problem... it's not because of the t function returned by the init... it's vice-versa...

if you pass the t function like in your example:

**Comment by mtbvang** [comment]
> ahh, now I see your problem... it's not because of the t function returned by the init... it's vice-versa...
> 
> if you pass the t function like in your example:
> 
> ```js
>                const data2 = {
>     			email: user.email,
>     			id: user.id,
>     			t: i18nextInstance.t
>     		};
> ```
> 
> this will not work, because the "this" of the t function is not the same...
> Try to bind like this:
> 
> ```js
>                const data2 = {
>     			email: user.email,
>     			id: user.id,
>     			t: i18nextInstance.t.bind(i18nextInstance)
>     		};
> ```

@adrai Yes, adding the bind() worked and got rid of the error:

```
TypeError: Cannot read property 'translator' of undefined
      at t (node_modules/i18next/dist/cjs/i18next.js:2124:19)
```
I posted a SO question too if you're interested it answering it on there. https://stackoverflow.com/questions/65334374/i18next-tfunction-translation-not-working-in-ejs-template-render.

**Comment by adrai** [comment]
done ;-)

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
