### ISSUE TITLE
i18next.reloadResources behaviour concerns

### ISSUE THREAD

**Issue by keerts99** [i18next/i18next#1530]
Hi! I'm sorry, I'm quite new to i18next framework. I have a question regarding the behaviour of the i18next.reloadResources() API. Is this API tied to fallbackLng by any chance? Because I am unable to successfully call this API when the current language is set to a language that is not defined in init (and not defined as a fallbackLng), for example when I trigger changeLanguage. We are retrieving the translations through the i18next-xhr-backend plugin. I realise if I set the fallbackLng to false, the reloadResources API works for any language that is currently set. Why is the behaviour such?

**Expected Behaviour:**
Be able to reload the resources regardless of if the language is set as fallback or not.

Thanks in advance

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/src/i18next.js#L215

if not specified what to reload it reloads whatever currently is in the i18next.languages

**Comment by keerts99** [comment]
Hi sir, thank you for the response. But oddly in my situation, although lets say now there is ['en-us' ,'es-la'] in the i18n.languages array, the reload doesn't seem to work. But if the fallbackLng = en-us, alone is in the array, it somehow is able to reload. Or in my case now I set the fallbackLng = false, then only it works for nay language that is in the languages array (which is always only one language at a time in the array). So right now it looks like there can only be one language in the array to reload resources? Thats why I was wondering if the fallbacklng has anything to do with it, or if does this have to do with the regional code?

**Comment by jamuhl** [comment]
Can you provide a jsfiddle or codesandbox for reproduction?

If I create a fiddle like: https://jsfiddle.net/o0x6ef87/

depending on setting lng to `en` (=fallback) it reloads 2 files, in case of `de` 4 files --- which is what is expected...

so, I'm not sure / able to reproduce what is not working on your code
