### ISSUE TITLE
TypeError: r.use is not a function only in bundled version

### ISSUE THREAD

**Issue by AmarBouchibane** [i18next/i18next#1536]
## 🐛 Bug Report

We use i18next in our Electron app. If our app is built with electron-forge, the TypeError "r.use is not a function" occurs when the app is started. It runs perfectly in dev environment. But when I build this app the TypeError occurs.

## To Reproduce

```js
// i18n.js
const i18next = require("i18next");
const backend = require("i18next-fs-backend");

module.exports = (function () {
	function init() {
		return i18next.use(backend).init({
			lng: "de",
			fallbackLng: "en",
			supportedLngs: ["de", "en"],
			returnObjects: true,
			backend: {
				loadPath: fileSystem.getLocalesPath("/locales/{{lng}}.json")
			}
		});
	}
	return {
		init
	};
})();
```

## Expected behavior
No TypeError occurs.

## Your Environment
"devDependencies": {
    "@babel/core": "^7.11.1",
    "@babel/preset-env": "^7.11.0",
    "@electron-forge/cli": "^6.0.0-beta.53",
    "@electron-forge/maker-deb": "^6.0.0-beta.53",
    "@electron-forge/maker-rpm": "^6.0.0-beta.53",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.53",
    "@electron-forge/maker-zip": "^6.0.0-beta.53",
    "@electron-forge/plugin-webpack": "^6.0.0-beta.53",
    "@marshallofsound/webpack-asset-relocator-loader": "^0.5.0",
    "babel-jest": "^26.3.0",
    "css-loader": "^4.2.1",
    "dotenv": "^8.2.0",
    "electron": "11.1.1",
    "html-webpack-plugin": "^4.5.0",
    "jest": "^26.6.3",
    "jest-junit": "^12.0.0",
    "mini-css-extract-plugin": "^1.0.0",
    "node-loader": "^1.0.1",
    "style-loader": "^2.0.0"
  },
  "dependencies": {
    "electron-squirrel-startup": "^1.0.0",
    "file-url": "^3.0.0",
    "i18next": "^19.8.4",
    "i18next-fs-backend": "^1.0.7",
    "jsonfile": "6.1.0",
    "paclient": "0.0.2",
    "simple-node-logger": "18.12.24",
    "stream-mock": "^2.0.5",
    "ts-ebml": "2.0.0"
  }
- *runtime version*: node 14.11.0
- *i18next version*: 19.8.4
- *os*: Windows 10
- *any other relevant information*

**Comment by adrai** [comment]
Might be some bundling issue in electron or electron-forge... Never tried it...
Can you debug a bit and check the value of "i18next" => console.log(i18next)
and also backend?

**Comment by AmarBouchibane** [comment]
Of course...
```
i18next: Object [Module] {
  default: t {
    observers: {},
    options: {},
    services: {},
    logger: e {
      prefix: 'i18next:',
      logger: [Object],
      options: {},
      debug: undefined
    },
    modules: { external: [] }
  }
}
backend: Object [Module] { default: [Function: e] { type: 'backend' } }
```

**Comment by adrai** [comment]
I don't know why, but it seams you need to access that default property:
i18next.default

**Comment by adrai** [comment]
Does it work if using the import statement instead of require?

**Comment by AmarBouchibane** [comment]
So, instead of i18next I should use i18next.default?
Then this error occurs:
`Error: You are passing a wrong module! Please check the object you are passing to i18next.use()`

I can't use import because I use i18next in the main process only.

**Comment by adrai** [comment]
also backend.default

**Comment by AmarBouchibane** [comment]
Yes! :-) that works!

So, I'll have to do this to work both in dev and prod:

`const i18next_ = require("i18next");
const backend_ = require("i18next-fs-backend");

const i18next = typeof i18next_.use === "function" ? i18next_ : i18next_.default;
const backend = typeof backend_.init === "function" ? backend_ : backend_.default;`

**Comment by adrai** [comment]
🤷‍♂️ I don't know electron

**Comment by AmarBouchibane** [comment]
Okay, I also tend to believe that it's a bundling issue, as you wrote.
It works for me now.

**Comment by AmarBouchibane** [comment]
Thank you for your incredible fast help!

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
