### ISSUE TITLE
Error during SSR: Wait for the callback or Promise to resolve before accessing it

### ISSUE THREAD

**Issue by alexpermiakov** [i18next/i18next#1537]
## 🐛 Bug Report

When I define `backend` option with local url such as: `http://localhost:8000/locales/{{lng}}/{{ns}}.json` - I'm able to load and use translation  during ssr (I use Gatsby), but once I replace this url with non-localhost url, such as api.i18nexus.com service - I see `i18next::translator: missingKey` error.

## To Reproduce

```js
  i18n
    .use(initHttpBackend)
    .use(initReactI18next)
    .init({
      debug: true,
      fallbackLng: 'de_CH',
      lng: 'de_CH',
      supportedLngs: ['en', 'de', 'de_CH'],
      keySeparator: ".",
      ns: ['translations'],
      defaultNS: 'translations',
      react: {
        useSuspense: false,
      },
      backend: {
        loadPath: "https://api.i18nexus.com/project_resources/translations/{{lng}}/{{ns}}.json?api_key=myKey",
      },
    });
```
## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by jamuhl** [comment]
Guess it's related to using `_` in languages...

Hopefully, you also understand I won't look further into this...you're using i18nexus which is not a contributor to i18next. We provide https://locize.com -> So, no support for using competitor product running on our OSS brand.

**Comment by adrai** [comment]
the de_CH language code looks not i18next conform

**Comment by alexpermiakov** [comment]
Thank you, understood!
