### ISSUE TITLE
import i18next from 'i18next' causes "Cannot assign to read only property 'exports' of object '#<Object>' "

### ISSUE THREAD

**Issue by raphael10-collab** [i18next/i18next#1538]
## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

In an electron-react-typescript app when inserting this line:

     import i18next from 'i18next';

I get this error:

    A JavaScript error occurred in the main process
    Uncaught Exception:
    TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
        at Module.<anonymous> (/home/marco/webMatters/electronMatters/IPFSbase/.webpack/main/index.js:76805:16)
        at Module../src/ipfs-on-path/index.js (/home/marco/webMatters/electronMatters/IPFSbase/.webpack/main/index.js:76906:30)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/IPFSbase/.webpack/main/index.js:21:30)
        at Object../src/tray.js (/home/marco/webMatters/electronMatters/IPFSbase/.webpack/main/index.js:77843:39)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/IPFSbase/.webpack/main/index.js:21:30)
        at Module../src/main.ts (/home/marco/webMatters/electronMatters/IPFSbase/.webpack/main/index.js:76958:19)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/IPFSbase/.webpack/main/index.js:21:30)
        at Object.0 (/home/marco/webMatters/electronMatters/IPFSbase/.webpack/main/index.js:78410:18)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/IPFSbase/.webpack/main/index.js:21:30)
        at /home/marco/webMatters/electronMatters/IPFSbase/.webpack/main/index.js:85:18

This is the tsconfig.json file :  

    {
      "compilerOptions": {
        "jsx": "react",
        "allowJs": true,
        "target": "ES6",
        "module": "ESNext",
        "skipLibCheck": true,
        "esModuleInterop": true,
        "noImplicitAny": false,
        "sourceMap": true,
        "baseUrl": ".",
        "outDir": "dist",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "paths": {
          "*": ["node_modules/*"],
          "@app/*": ["./src/app/*"],
          "@static/*": ["./src/static/*"],
          "@src/*": ["./src/*"]
        }
      },
      "include": ["src/**/*"]
    }

devDependencies:

    "electron": "^11.2.1",     
    "typescript": "^4.0.2".

dependencies:

    "i18next": "^19.8.4",
    "i18next-electron-language-detector": "^0.0.10",
    "i18next-icu": "^1.4.2",
    "i18next-node-fs-backend": "^2.1.3",

    node version: v14.5.0
    O.S. : Ubuntu 18.04.4.Desktop

How to solve the problem?

**Comment by pedrodurek** [comment]
Hey @raphael10-collab, it seems your setup doesn't support CommonJS syntax. What are you using as bundler? Can you share your babel file?

**Comment by raphael10-collab** [comment]
Hi @pedrodurek !
I'm not using babel. As bundler I'm just using webpack :  

/tools/webpack  :  

    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

    // https://stackoverflow.com/questions/44008674/how-to-import-the-electron-ipcrenderer-in-a-react-webpack-2-setup
    const webpack = require('webpack');

    module.exports = [
      new ForkTsCheckerWebpackPlugin(),
      new webpack.ExternalsPlugin('commonjs', [
        'electron'
      ])
    ];

/tools/webpack/webpack.rules.js :  

    const inDev = process.env.NODE_ENV === 'development';

    module.exports = [
      {
        // Add support for native node modules
        test: /\.node$/,
        use: 'node-loader',
      },
      {
        // Webpack asset relocator loader
        test: /\.(m?js|node)$/,
        parser: { amd: false },
        use: {
          loader: '@marshallofsound/webpack-asset-relocator-loader',
          options: {
            outputAssetBase: 'native_modules',
          },
        },
      },
      {
        // Typescript loader
        test: /\.tsx?$/,
        exclude: /(node_modules|\.webpack)/,
        use: {
          loader: 'ts-loader',
          options: {
            transpileOnly: true,
          },
        },
      },
      {
        // CSS Loader
        test: /\.css$/,
        use: [{ loader: 'style-loader' }, { loader: 'css-loader' }],
      },
      {
        // Less loader
        test: /\.less$/,
        use: [
          { loader: 'style-loader' },
          { loader: 'css-loader' },
          { loader: 'less-loader' },
         ],
      },
      {
        // Images Loader
        test: /\.(gif|jpe?g|tiff|png|webp|bmp)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              publicPath: 'images',
              outputPath: inDev ? 'images' : './main_window/images',
            },
          },
        ],
      },
    ];

/tools/webpack/webpack.renderer.js :  

    /* eslint-disable @typescript-eslint/no-var-requires */
    const rules = require('./webpack.rules');
    const plugins = require('./webpack.plugins');
    const aliases = require('./webpack.aliases');

    module.exports = {
      // https://github.com/electron/electron/issues/9920
      target: 'electron-renderer',
      module: {
        rules,
      },
      plugins: plugins,
      resolve: {
        extensions: ['.js', '.ts', '.jsx', '.tsx', '.css'],
        alias: {
          // React Hot Loader Patch
          'react-dom': '@hot-loader/react-dom',
          // Custom Aliases
          ...aliases,
        },
      },
    };

/tools/webpack/webpack,main.js :  

    module.exports = {
      /**
       * This is the main entry point for your application, it's the first file
       * that runs in the main process.
       */
      entry: ['./src/main.ts'],
      // Put your normal webpack config below here
      module: {
        rules: require('./webpack.rules'),
      },
      resolve: {
        extensions: ['.js', '.ts', '.jsx', '.tsx', '.css', '.json'],
        alias: require('./webpack.aliases'),
      },
      // https://github.com/electron/electron/issues/9920
      target: 'electron-renderer'
    };

**Comment by adrai** [comment]
Maybe @AmarBouchibane can help? https://github.com/i18next/i18next/issues/1536

**Comment by AmarBouchibane** [comment]
As a packager, I use electron-forge for my Electron app.
Maybe this will help? https://github.com/electron-userland/electron-forge
