### ISSUE TITLE
Consider having the `t` function take only one parameter combining key and options

### ISSUE THREAD

**Issue by pcorpet** [i18next/i18next#1540]
## 🚀 Feature Proposal

Have the `t` function accept one parameter containing both the key and the options.

`t({key: 'Text to translate', count: 2})` would be equivalent to `t('Text to translate', {count: 2})`.

A side option would be to combine options if two parameters are given:
`t({key: 'Text to translate', count: 2}, {lang: 'fr'})` would be equivalent to `t('Text to translate', {count: 2, lang: 'fr'})`

## Motivation

In our code we sometimes don't have the `t` function ready when we define the text and options to translate, however in order to mark the strings for extraction (we use [babel-plugin-i18n-extract](https://github.com/gilbsgilbs/babel-plugin-i18next-extract)), we call them in a `prepareT` function that does nothing today.

```ts

const prepareT = key => key

const answers = [
  prepareT('yes'),
  prepareT('no'),
  prepareT('maybe'),
];

...

const localizedAnswers = answers.map(answer => t(answer));
```

However if we have options to be added we need to do some workaround to give the options to the `t` function. If `t` would accept a combined value we could update our `prepareT` function to bundle key and options easily. See below:

## Example

```ts

const prepareT = (key, options) => options ? {key, ...options} : key

const answers = [
  prepareT('yes', {defaultValue: 'Yes'}),
  prepareT('no', {defaultValue: 'No'}),
  prepareT('maybe'),
];

...

const localizedAnswers = answers.map(answer => t(answer));
```

**Comment by jamuhl** [comment]
why not:

```js
const prepareT = (key, options) => options ? [key, options] : [key]

const answers = [
  prepareT('yes', {defaultValue: 'Yes'}),
  prepareT('no', {defaultValue: 'No'}),
  prepareT('maybe'),
];

...

const localizedAnswers = answers.map(answer => t.apply(null, answer));
```

**Comment by pcorpet** [comment]
Thanks for the quick answer.

Yep that's much simpler than my previous solution, especially using spreading:
```
answers.map(answer => t(...answer))
```

I think I liked the idea not to have to apply `t` differently than usual, i.e. at dev time being able to manipulate prepared translation and strings indifferently for instance if I don't want to prepare one of the strings.

```ts
const answers = [
  prepareT('yes', {defaultValue: 'Yes'}),
  prepareT('no', {defaultValue: 'No'}),
  '🤷',
];
```

However this example is not great, as the `t` function would still be applied to the emoji and I'm abusing the fact that it would return it with no error.

I'll try your solution with my codebase and see if I run into any bumps.

**Comment by pcorpet** [comment]
I ran into many bumps, however most of them were actual mistakes (double translation or translation prepared but forgotten) so I think it's best not to be too permissive :-) The other bumps I ran into were easily fixable.

Here's how I solve the one above:
```ts
const prepareTNoExtract = prepareT;

const answers = [
  prepareT('yes', {defaultValue: 'Yes'}),
  prepareT('no', {defaultValue: 'No'}),
  prepareTNoExtract('🤷'),
];
```
