### ISSUE TITLE
Have the documentation and/or README state which browsers are supported

### ISSUE THREAD

**Issue by tomwayson** [i18next/i18next#1543]
## 🚀 Feature Proposal

Have the documentation and/or README prominently state which browsers are supported, similar to [how format.js does](https://formatjs.io/).

## Motivation

We'd like to use this in a page that must support Internet Explorer. This would be the page we'd redirect IE users to before trying to boot our application, which does **not** support IE.

I've looked through the docs and this is the only mention that I've found of browser support: https://www.i18next.com/misc/migration-guide#not-supported-any-longer-in-v-2-0-0

I've also looked through the issues and it took a long time before I saw [this comment](https://github.com/i18next/i18next/issues/1200#issuecomment-479092708), which leads me to believe that IE is not supported.

## Example

If the docs clearly said that IE was supported or not, I would not have had to read through issues and try to infer what versions were being used and whether or not this library is suitable for my purpose.

**Comment by jamuhl** [comment]
A pull request adding this is welcome.

**Comment by jamuhl** [comment]
Personal target is last 2 versions of evergreen. But also accepting PR to support eg. IE10/9 - I just can't these those old browsers myself.
