### ISSUE TITLE
Wrong fallback string when namespace contains object with the same name

### ISSUE THREAD

**Issue by gjsduarte** [i18next/i18next#1544]
## 🐛 Bug Report

Fallback returns the wrong key. In the example code below the result is "potato" when I would expect it to be "beans". This seems to happen when an object with the same name exists in the namespace.

## To Reproduce

```ts
import "./styles.css";
import { initReactI18next, useTranslation } from "react-i18next";
import i18n from "i18next";

export default function App() {
  i18n.use(initReactI18next).init({
    resources: {
      "en-US": {
        restaurant: {
          foo: {
            beans: "potato"
          }
        }
      }
    },
    keySeparator: ".",
    ns: ["restaurant"],
    defaultNS: "restaurant",
    fallbackLng: "en-US"
  });

  const { t } = useTranslation();
  return t("foo.bar.boz.beans", "beans");
}
```
[codesandbox](https://codesandbox.io/s/runtime-architecture-0y9nw?file=/src/App.tsx:23-506)

## Expected behavior

I would expect the fallback string "beans" to be picked up and rendered instead of "potato".

## Your Environment

- *runtime version*: node 14
- *i18next version*: 19.8.5
- *react-i18next version*: 11.8.5
- *os*: Mac

**Comment by adrai** [comment]
This is a regression of i18next... will investigate asap

**Comment by adrai** [comment]
Can you try with i18next v19.8.6?

**Comment by gjsduarte** [comment]
It works like a charm! 🎉  Thanks for the quick response!
