### ISSUE TITLE
i18next::translator: missingKey en-US translations 

### ISSUE THREAD

**Issue by jgarnie** [i18next/i18next#1546]
## 🐛 Bug Report

I have a translations constant that holds all the keys, that way I can access the translations by typing the key so it avoids mistakes.

however I am experiencing an issue whenever I am using the translations imported from that Translations file.

`i18next::translator: missingKey en-US translations Phone Phone

`

my i18n file looks like:

`import i18n from 'i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
import moment from 'moment'

import {TRANSLATION} from './translations'

i18n.use(LanguageDetector).init({
  // we init with resources
  resources: {
    en: {
      translations: TRANSLATION.EN,
    },
  },
  fallbackLng: 'en-US',
  debug: process.env.NODE_ENV === 'development',

  // have a common namespace used around the full app
  ns: ['translations'],
  defaultNS: 'translations',
  keySeparator: false, 
  interpolation: {
    escapeValue: false, // not needed for react!!
    formatSeparator: ',',
    format: function(value, formatting, lng) {
      if (value instanceof Date) return moment(value).format(formatting)
      return value.toString()
    },
  },
  react: {
    wait: true,
  },
})`

the coponent where I am using the Keys:

`import i18n, {T_KEYS} from '/i18n'

const Component=()=>{
return(
   <Form.Item
            name="phone"
            label={i18n.t(T_KEYS.phone)}
            rules={rules.phone}
          >
            <Input />
          </Form.Item>

)```
`
 I was wondering if anyone had a similar issue or idea since after browsing through documentation and repository I couldnt find any answer to what is happening.

what makes me confused is that when I use the translation without importing it from the file translations, it works whitout problem.
example:
`i18n.use(LanguageDetector).init({
  // we init with resources
  resources: {
    en: {
      translations: {
phone: 'phone',
    },
  },`

and in the component:

``import i18n from 'i18n'

const Component=()=>{
return(
   <Form.Item
            name="phone"
            label={i18n.t('phone')}
          >
            <Input />
          </Form.Item>

)```
``

## To Reproduce
this is the error I get on my project 
![image](https://user-images.githubusercontent.com/62890174/106589896-d1fef900-654c-11eb-9f99-04924ac52b06.png)

this is a recreation of what I am trying to implement, however I noticed that on the sandbox the error I have on my code does not apear
A [codesandbox](https://codesandbox.io/s/react-i18next-example-forked-2cncq?file=/src/Translations.js)

## Expected behavior
I am expecting to be able to use the TRANSLATIONS constant as key for ti8n without having the error in console.
```js
// Paste the expected results here
```
![image](https://user-images.githubusercontent.com/62890174/106589805-b8f64800-654c-11eb-9205-000cc0525766.png)

## Your Environment

- *runtime version*:v10.19.0
- *i18next version*: "17.3.1",s, Linux
it happens also in windows and macOS

hope you can help with the issue

**Comment by adrai** [comment]
You need to debug on your side, sorry.
Or create a reproducable example.

**Comment by jgarnie** [comment]
> You need to debug on your side, sorry.
> Or create a reproducable example.

Basically, given this start : `import i18n from 'i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
import moment from 'moment'

import {TRANSLATIONS} from './translations'

const resources = {
  en: {
    translations: TRANSLATIONS.EN,
  },
}

i18n.use(LanguageDetector).init({
  // we init with resources
  resources,
  fallbackLng: 'en',
  debug: process.env.NODE_ENV === 'development',

  // have a common namespace used around the full app
  ns: ['translations'],
  defaultNS: 'translations',
  keySeparator: false, // we use content as keys
  interpolation: {
    escapeValue: false, // not needed for react!!
    formatSeparator: ',',
    format: function(value, formatting, lng) {
      if (value instanceof Date) return moment(value).format(formatting)
      return value.toString()
    },
  },
  react: {
    wait: true,
  },
})
export const T_KEYS = TRANSLATIONS.EN
export default i18n`


how would you avoif this error messages?:
![image](https://user-images.githubusercontent.com/62890174/106600362-99661c00-655a-11eb-9e5f-f4f0d3ec441a.png)


the translations file : 
`export const TRANSLATIONS = {
  // MENU

  EN: {
phone: 'phone,
country:'country,
zip: 'zip code',
etc..
}`


and the component:
`import i18n, {T_KEYS} from '@/services/i18n'`

const component =()=>{
return(
{i18n.t(T_KEYS.name)}
{i18n.t(T_KEYS.phone)}
{i18n.t(T_KEYS.zip)}
etc.


I am not understanding what is wrong with this set up, I followed the doc
[https://react.i18next.com/legacy-v9/step-by-step-guide](url)

I would be very happy if you can have a quick look at it.
Thanks for the help anyway

**Comment by adrai** [comment]
Are you sure you're not using a http or xhr backend for i18next?

Normally this type of errors occur if you're not waiting for i18next to have loaded the translations, i.e. https://react.i18next.com/latest/withtranslation-hoc#not-using-suspense

btw: there is no wait option anymore in react-i18next...

I can't help more than this, without a reproducable example, sorry.

**Comment by jamuhl** [comment]
```js
EN: {
phone: 'phone,
country:'country,
zip: 'zip code',
etc..
}`
```

are this your keys in the translation file?

The missing log seems to request eg. `Phone` and not `phone` key

**Comment by jgarnie** [comment]
> ```js
> EN: {
> phone: 'phone,
> country:'country,
> zip: 'zip code',
> etc..
> }`
> ```
> 
> are this your keys in the translation file?
> 
> The missing log seems to request eg. `Phone` and not `phone` key

I believe you got the problem, basically I am using the response strings as keys, they dont match and hte keys since they are slightly different, then error appears, great!
I believe is just a matter of correcting it now.
EN: {
phone: 'Phone,
country:'Country,
zip: 'Zip code',
etc..
}`
as you can see the keys are different from the strings, sorry for the disturbance a thanks a lot for the help! you can close the issue
