### ISSUE TITLE
Add ability to include a description associated with a translation key.

### ISSUE THREAD

**Issue by JarekToro** [i18next/i18next#1548]
## 🚀 Feature Proposal

As far as I can tell there is no ability to add description to a translation key.

## Motivation

This would be useful when sharing the .json file with translators to give them the context they need to translate correctly.

## Example
Before, the word yield is being used differently. With no context 
```json
{
    "translationkeyA": "Yield to on coming traffic",
    "translationkeyB": "I hope to yield substantial results"
}
```

Potential Proposal
```json
{
    "translationkeyA": "Yield to on coming traffic",
    "translationkeyA_description": "to give in or hold back",
    "translationkeyB": "I hope to yield substantial results",
    "translationkeyB_description": "to produce or gain",
}
```

**Comment by jamuhl** [comment]
You can pass `tDescription` via `t` options or as third param:

```js
i18next.t('key', 'defaultValue', 'comment');
i18next.t('key', { defaultValue: 'defaultValue', tDescription: 'comment' });
```

But you will have to use a backend implementation handling that -> only one I know of is our one used with locize.com -> that saves this information for every key to add more context to the translation.
