### ISSUE TITLE
Missing key default pluralization issues

### ISSUE THREAD

**Issue by namoscato** [i18next/i18next#1549]
## 🐛 Bug Report

There seems to be some issues with default value pluralization when [`missingKeys`](https://www.i18next.com/overview/configuration-options#missing-keys) is enabled:

1. The result of interpolation is incorrect and does not seem to respect pluralization
2. The singular and plural values passed to the backend, when configured, are the same

## To Reproduce

Here's a [CodeSandbox](https://codesandbox.io/s/i18next-missing-key-pluralization-40ktz?file=/src/App.js) that illustrates the issue when evaluating:

```js
t("myMissingKey", {
    count,
    defaultValue: "{{ count }} word",
    defaultValue_plural: "{{ count }} words"
})
```

This is _not_ an issue when `saveMissing=false`.

## Expected behavior

Per the [`defaultValue` description](https://www.i18next.com/translation-function/essentials#overview-options):

> you also can define defaults for plurals by adding defaultValue_plural / defaultValue_2 -> _suffix depends on same pluralrules

I would expect the `myMissingKey` string to be pluralized correctly as `count` changes, and the missing key handler configured via a backend, should receive:

```json
{
    "myMissingKey": "{{ count }} word",
    "myMissingKey_plural": "{{ count }} words"
}
```

## Your Environment

- *runtime version*: Chrome v88
- *i18next version*: v19.8.7
- *react-i18next version*: v11.8.5
- *i18next-locize-backend version*: v4.1.9
- *os*: macOS

**Comment by adrai** [comment]
This is probably, because your first count value is 0, and this is a plural

**Comment by namoscato** [comment]
Yeah, makes sense – if the state is initialized to `1`, it's always _singular_.

With that said, is this expected behavior?

**Comment by adrai** [comment]
seems so

**Comment by namoscato** [comment]
Working with this some more over the past week, this still seems like a minor bug to me.

I'm happy to help out with a fix, but it might be a few weeks before I get around to it; feel free to point me in the right direction of the relevant code in the meantime.

**Comment by jamuhl** [comment]
@namoscato that functionality can be found here https://github.com/i18next/i18next/blob/master/src/Translator.js#L245

would be happy to accept a PR

**Comment by namoscato** [comment]
FYI, I took a pass at this in https://github.com/i18next/i18next/pull/1558.
