### ISSUE TITLE
changeLanguage() type definition is incorrect

### ISSUE THREAD

**Issue by Drarig29** [i18next/i18next#1550]
## 🐛 Bug Report

The documentation says [here](https://www.i18next.com/overview/api#changelanguage):
> Calling changeLanguage without `lng` uses the language detector to choose the language to set.

But the TS definition file has this definition ([here](https://github.com/i18next/i18next/blob/master/index.d.ts#L885)):

```ts
changeLanguage(lng: string, callback?: Callback): Promise<TFunction>;
```

So the `lng` is required when we use TypeScript.

## Expected behavior

In the codebase, the following done when the call is parameter-less:

https://github.com/i18next/i18next/blob/ad88092292cc32fe250c6352f796dd710705d0da/src/i18next.js#L296-L299

So the TS definition should be:
```ts
changeLanguage(lng?: string, callback?: Callback): Promise<TFunction>;
```

## Your Environment

- *i18next version*: 19.8.7

**Comment by ogarich89** [comment]
Why did you change the behavior in the patch version?

19.8.5 - "use fallbackLng as default lng"
