### ISSUE TITLE
fallbackLng as default lng

### ISSUE THREAD

**Issue by ogarich89** [i18next/i18next#1552]
Why did you change the behavior in the patch version?

19.8.5 - "use fallbackLng as default lng"

After update, language is always taken from "fallbackLng"
![image](https://user-images.githubusercontent.com/11867673/107884659-3899f480-6f07-11eb-97dd-fcea5ab1a4f4.png)

The behavior can be viewed in this repository
https://github.com/ogarich89/iso/tree/feature/i18next

**Comment by adrai** [comment]
It's just a fallback behaviour if nonlanguage or language detector is defined...
Does this hurt you somehow?

**Comment by adrai** [comment]
btw: you may also define ru as fallbackLng here: https://github.com/ogarich89/iso/blob/feature/i18next/src/shared/libs/i18n.ts#L11

**Comment by ogarich89** [comment]
> btw: you may also define ru as fallbackLng here: https://github.com/ogarich89/iso/blob/feature/i18next/src/shared/libs/i18n.ts#L11


I define language here: https://github.com/ogarich89/iso/blob/feature/i18next/src/server/middleware/i18next.ts#L24

Before version 19.8.5 everything worked fine

**Comment by adrai** [comment]
The problem is this: https://github.com/ogarich89/iso/blob/feature/i18next/src/server/middleware/i18next.ts#L13
`fallbackLng = 'ru'`

You are defining a fallbackLng, but i18next does not know this... it know 'en' from here: https://github.com/ogarich89/iso/blob/feature/i18next/src/shared/libs/i18n.ts#L11

in init it is 'en' and outside of i18next you define 'ru' and call changeLanguage afterwards...

So if you want ru to be the fallbackLng i18next needs to know it here: https://github.com/ogarich89/iso/blob/feature/i18next/src/shared/libs/i18n.ts#L11

The i18nextMiddleware only runs on server side, so I suspect there is some sort of timing issue

**Comment by adrai** [comment]
I suspect the changeLanguage call is done before i18next has finished to initialize

**Comment by ogarich89** [comment]
> The problem is this: https://github.com/ogarich89/iso/blob/feature/i18next/src/server/middleware/i18next.ts#L13
> `fallbackLng = 'ru'`
> 
> You are defining a fallbackLng, but i18next does not know this... it know 'en' from here: https://github.com/ogarich89/iso/blob/feature/i18next/src/shared/libs/i18n.ts#L11
> 
> in init it is 'en' and outside of i18next you define 'ru' and call changeLanguage afterwards...
> 
> So if you want ru to be the fallbackLng i18next needs to know it here: https://github.com/ogarich89/iso/blob/feature/i18next/src/shared/libs/i18n.ts#L11
> 
> The i18nextMiddleware only runs on server side, so I suspect there is some sort of timing issue


It did not help =(

**Comment by adrai** [comment]
what did not help?

**Comment by ogarich89** [comment]
Before update i18next

https://user-images.githubusercontent.com/11867673/107887484-8880b780-6f17-11eb-8e65-195ddc86c6dd.mov

After update to 19.8.5

https://user-images.githubusercontent.com/11867673/107887497-9f270e80-6f17-11eb-9c12-055d702d7c47.mov

**Comment by ogarich89** [comment]
> what did not help?
> Did you change the code to wait for i18next to initialize before calling changeLanguage?

i18next.isInitialized return true before call changeLanguage

**Comment by adrai** [comment]
on server side probably it's initialized, but on client side I don't think so

**Comment by ogarich89** [comment]
Client side: https://github.com/ogarich89/iso/blob/feature/i18next/src/client/index.tsx#L29

**Comment by adrai** [comment]
Should be better with v19.8.8
