### ISSUE TITLE
 19.8.8 always shows our app in pseudo regardless of language set

### ISSUE THREAD

**Issue by redbugz** [i18next/i18next#1554]
## 🐛 Bug Report

When upgrading our app to 19.8.8, suddenly our app always displays the pseudo locale (with the psuedo plugin) instead of the selected language. When I revert to 19.8.7, it display the correctly set language and only shows pseudo when I change the language to the pseudo locale

## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
 .use(
      new Pseudo({
        languageToPseudo: 'eo',
      })
    )
    .use(initReactI18next)
    .init({
      fallbackLng: {
        'zh-hans': ['zh', 'en'],
        'zh-Hans': ['zh-hans', 'zh', 'en'],
        default: ['en'],
      },
      postProcess: ['pseudo'],
```

## Expected behavior

Only display pseudo if that language code is set

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: 19.8.8
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
I'm not able to reproduce it... => https://codesandbox.io/s/react-i18next-forked-f20hp?file=/src/i18n.js
Can you please provide an example?

**Comment by redbugz** [comment]
I'm working on a reproduction. It appears to be because translator.language is getting set to undefined.
I'm stepping through trying to whittle it down.
when translator.language is undefined, Pseudo defaults to processing the string:
https://github.com/MattBoatman/i18next-pseudo/blob/master/src/index.js#L29
Not sure I understand why.
So it appears something changed in the timing/execution of our logic during language changes that leaves language undefined, I'm trying to figure out what it is.
I have a codesandbox that sometimes shows the problem, but only when an exception is thrown unexpectedly in one of the callbacks and only at certain times. I don't see any exception in our apps, so the sandbox error seems to simulate the condition where language gets set to undefined, but isn't a reproduction yet, and it's not consistent.
We sometimes set language a few times during initialization based on some dynamic config, so I'm guessing some timing has changed and we are falling through the cracks.

**Comment by redbugz** [comment]
I got a reproduction, looks like our dynamic language list where we re-initialize i18next is the problem.
https://codesandbox.io/s/react-i18next-forked-pqmsc?file=/src/i18n.js
Once a component loads with additional languages, everything after that is in pseudo.
If there is a better way to accomplish view/page-specific supportedLngs, let us know.

**Comment by adrai** [comment]
Had no time to check the code, but you should not call init multiple times.

**Comment by redbugz** [comment]
So if the parameters or languages need to change, I need to create a brand new i18next object and throw away the old one instead?

**Comment by adrai** [comment]
You can just call changeLanguage: https://www.i18next.com/overview/api#changelanguage

**Comment by redbugz** [comment]
> You can just call changeLanguage: https://www.i18next.com/overview/api#changelanguage

That changes the current language and enforces the current supported list/fallbacks. But not every page in our apps supports the same set of languages so I need to change the `supportedLngs` property. So for all the plugins, languagedetector, fallback, etc. to work when the actual list of supported languages for that page/view changes, I was re-initializing i18next so all of that config/init code would recalculate.
If you are saying that I can update `supportedLngs`, and then call `changeLanguage`, and that will recalculate everything instead of calling init again, I will try that.

**Comment by adrai** [comment]
Then maybe you should try createInstance or cloneInstance:

https://www.i18next.com/overview/api#instance-creation

**Comment by redbugz** [comment]
I've switched to using cloneInstance, but that does not correctly update `supportedLngs` in `isSupportedCode` in LanguageUtils, it still references the original supportedLngs from the non-cloned instance.
https://codesandbox.io/s/react-i18next-forked-bdro6?file=/src/app.js
I've confirmed the i18n instance in the provider has the new config, but the language detector still has an old copy of supportedLngs from LanguageUtils so it doesn't allow the new languages to work.
Should this be a separate issue? Or am I still doing it wrong?

**Comment by adrai** [comment]
If you change all this, you should probably use createInstance instead.

**Comment by adrai** [comment]
Ahh, you might still have an old version of the language-detector plugin.

**Comment by adrai** [comment]
Nevertheless, I suggest to use createInstance to be sure everything is "new" with the options you want to.

**Comment by redbugz** [comment]
So I continue to work on this. I've got it mostly working by using a context and putting the i18nextProvider inside a custom context that creates and maintains the new instance.
We discovered that with createInstance we have to re-attach all the plugins. Which makes sense, but wasn't really clear in the docs

```
const newInstance = i18n.createInstance();
await newInstance
    .use(LanguageDetector)
    .use(
      new Pseudo({
        languageToPseudo: "zz"
      })
    )
    .use(initReactI18next)
    .init({
      ...i18nInitOpts,
      supportedLngs: locales.concat("zz"),
      resources: i18n.store.data // copy over the existing loaded translations
    });
```
But it also reminded me why we just called init again.
Much of the code does:
`import i18next from 'i18next'`
so when you call init on that global instance, everything that imports from that stays in sync. But now that I am creating a new instance and setting it on the i18nextProvider, anything the does work on that i18next object is now sometimes out of sync.
Weird things like
```
const [t, i18n] = useTranslation()
```
`t` doesn't use the new instance, but `i18n` does,  however with
```
const {t,  i18n} = useTranslation()
```
both `t` and `i18n` use the new instance

I'm trying to work through this in a sandbox, so hopefully it's not the sandbox being weird because in theory it shouldn't matter if I use the array destructuring or the object destructuring, both should come from the Provider, but it seems to make a difference.

But for anyone else trying to solve this problem where you can't call init again on the global instance anymore, figuring out how to share the new created instance with the existing app code patterns, I am working through those issues here:
https://codesandbox.io/s/react-i18next-forked-0dibw

We may just have to create our own i18n instance that wraps the one from i18next and import from there instead when we can't use the provider.

**Comment by sibelius** [comment]
how did you fixed it?

**Comment by redbugz** [comment]
> how did you fixed it?

We pinned to 19.8.7 until we develop a fix. We have a lot of shared components, pages that handle different language sets and lazy loaded code, so it may be trickier for us that some others. I still do not have a completely working environment for when the i18next instance has to be updated in the middle of a page load, there are no errors, but components loaded before the change aren't updated with the new language. Still figuring out the right way to propagate the changes to all components with the Provider. The Provider is getting updated, but not all components are honoring the change in the provider, not sure if it's our code, or something internal to  react-i18next or one of the plugins we use yet. It's tricky debugging i18next internals, a lot to learn.
