### ISSUE TITLE
[19.8.8 breaks compatibility?] Translations keys are not found when navigating in client side rendering

### ISSUE THREAD

**Issue by devictoribero** [i18next/i18next#1555]
## 🐛 Bug Report

Version `19.8.8` breaks compatibility with `19.8.7`.

Having an application that renders in both server and client-side, when a page is loaded in the client-side, a `missing key` error is thrown even though the resources are loaded, the language too and the config passed to the `init()` is exactly the same in the server and client (compared that with `JSON.stringify()`).

## To Reproduce

I've debugged it for a couple of hours and even used the `debug=true` but can't really figure out the problem. With `19.8.7` works fine.

1. **I created a super simple case on this repository so you can see the issue**: https://github.com/devictoribero/replicate-i18next-issue
2. I also deployed it to Vercel so you have a version LIVE: https://replicate-i18next-issue-1od83fcmh.vercel.app/

## Expected behavior

Translations should work either in SSR and CSR

## Your Environment
- *i18next version*: i.e. 19.8.7

**Comment by adrai** [comment]
Seems you are initializing i18next multiple times: https://github.com/i18next/i18next/issues/1554#issuecomment-780425514

**Comment by devictoribero** [comment]
As you comment, updating the context provider looks like I've solved the issue as you can see here: https://github.com/devictoribero/replicate-i18next-issue/blob/fix/solve-duplicate-init/context/i18n.js

BUT, just want to point out that it's a breaking change. Even though I was initializing twice the library, it was working fine on the latest version.

**Comment by adrai** [comment]
> BUT, just want to point out that it's a breaking change. Even though I was initializing twice the library, it was working fine on the latest version.

You're right, but I was not thinking about users would initialize i18next multiple times.
