### ISSUE TITLE
Performance increase suggestions for the t method

### ISSUE THREAD

**Issue by Allain55** [i18next/i18next#1556]
## 🚀 Feature Proposal
I see some potential improvements that could improve the performance of the t method by around 100% in simple cases
Let's take a simple example where there is 1 language, an existing namespace and a simple, existing key is fetched without any extra params:

`i18next.t('key', {ns: 'sample'})`

The fallbackLng option is not needed here but it has a performance impact of 32-36%

In my project I need 2 fallback namespaces. In this case no fallback namespace is needed to find the value as it exists in "sample" but these extra namespaces still slow down the t method by around 30%

I also see an unexpected slowdown around 30% when a not existing namespace was given to the t method. I think it'd be better to check if a namespace exists before working with it

## Motivation
Increase the performance without breaking changes

## Example
There would be no breaking changes

**Comment by jamuhl** [comment]
Feel free to contribute a PR

**Comment by Allain55** [comment]
Thanks I think I will.
