### ISSUE TITLE
`getDataByLanguage` method returns `undefined` after initialization ( after update to 19.8.8)

### ISSUE THREAD

**Issue by kristina1lyba** [i18next/i18next#1557]
## 🐛 Bug Report

`getDataByLanguage` method returns `undefined` after initialization

## To Reproduce

Our init setup:
```js
export const initI18n = (locale: string): Promise<void> =>
  i18next
    .use({
      type: 'backend',
      read: (
        language: string,
        namespace: string,
        callback: (
          err: any | null,
          translations?: Record<string, string>
        ) => void
      ) => {
        return import(
          /* webpackChunkName: "[request]" */ `../assets/locale/messages_${language}.json`
        )
          .then((translation) => {
              console.log(translations); // TRANSLATIONS OBJECT IS PRINTED OUT
              return callback(null, translation);
           })
          .catch((error) => callback(error));
      },
    })
    .init({
      lng: locale,
      nsSeparator: false,
      keySeparator: false,
      fallbackLng: 'en',
      interpolation: {
        escapeValue: false,
      },
    })
    .then(() => {
      if (
        i18next.languages.every(
          (lang) => i18next.getDataByLanguage(lang) === undefined // THE PROBLEM IS HERE
        )
      ) {
        throw new Error(`Failed to load localization`);
      }
    });
```

## Expected behavior
`i18next.getDataByLanguage(lang)` call returns translations object instead of `undefined`

We get:
```js
console.log(i18next.languages);  // ['en']
console.log(i18next.getDataByLanguage('en'));  // undefined
console.log(i18next.isInitialized); // true
```

## Your Environment

- *runtime version*: i.e. node v12.18.2
- *i18next version*: i.e. 19.8.8
- *os*: Mac

**Comment by adrai** [comment]
Sorry, I'm not able to reproduce your issue: https://codesandbox.io/s/react-i18next-with-i18next-http-backend-forked-ogsiw?file=/src/i18n.js

Try to set debug to true and create a reproducable example.

**Comment by kristina1lyba** [comment]
I couldn't reproduce it as well but then I've checked [this issue](https://github.com/i18next/i18next/issues/1554) and found out that we also call init few times when running unit tests. 
So I've tried to add  usage of `.createInstance()` which also fails but now `languages` is `undefined`

https://codesandbox.io/s/react-i18next-with-i18next-http-backend-forked-xrl00?file=/src/i18n.js

**Comment by kristina1lyba** [comment]
@adrai Any updates?

**Comment by adrai** [comment]
Can't reproduce it

**Comment by kristina1lyba** [comment]
Sorry, it wasn't saved for some reason - here is updated sandbox
https://codesandbox.io/s/react-i18next-with-i18next-http-backend-forked-0mc57?file=/src/i18n.js

You need to reload sanboxes browser (on the right)

**Comment by adrai** [comment]
ok, I see it, but I do not believe it ;-)

need to investigate...

**Comment by adrai** [comment]
Ahhhh.... now I know why....
this != this
You're creating a new instance... so you don't have to check on the singleton i18n anymore... but on your instance:
https://codesandbox.io/s/react-i18next-with-i18next-http-backend-forked-8scr5?file=/src/i18n.js:188-232

**Comment by adrai** [comment]
Can this be closed now?

**Comment by kristina1lyba** [comment]
Yes, thank you!
