### ISSUE TITLE
Nested translations keys containing `"{{ count }}"` do not  handle pluralization or count interpolation.

### ISSUE THREAD

**Issue by jvnlwn** [i18next/i18next#1562]
## 🐛 Bug Report

Nested translations keys containing `"{{ count }}"` do not  handle pluralization or count interpolation.

## To Reproduce

See this [codesandbox](https://codesandbox.io/s/nameless-shadow-ijot1) example.

Note how the nested translation keys that contain `"{{ count }}"` produce an unexpected output where the count is not interpolated and the plural-ness is not honored.

<img width="420" alt="Screen Shot 2021-02-25 at 4 38 58 PM" src="https://user-images.githubusercontent.com/5227102/109222950-f636aa00-7787-11eb-81a7-ebee2adaf870.png">

```js
i18next.init({
  lng: "en",
  resources: {
    en: {
      translation: {
        // works as expected
        responseFromYou: '$t(numReponse, { "count": {{ responseCount }} }) from you',
        numReponse: "{{ count }} response",
        numReponse_plural: "{{ count }} responses",
        // does not work as expected
        responseFromYouAlt: '$t({{ count }} response, { "count": {{ responseCount }} }) from you',
        "{{ count }} response": "{{ count }} response",
        "{{ count }} response_plural": "{{ count }} responses"
      }
    }
  }
}).then(function (t) {
  // Works as expected:
  t("responseFromYou", { responseCount: 1 }) //=> "1 response from you"
  t("responseFromYou", { responseCount: 2 }) //=> "2 responses from you"
  // Does not work, expecting same results as above:
  t("responseFromYouAlt", { responseCount: 1 }) //=> "response from you"
  t("responseFromYouAlt", { responseCount: 2 }) //=> "response from you"
})
```

## Expected behavior

Expecting nested translation keys to always be replaced with their `t(*)` value.

## Your Environment

- *i18next version*: 19.9.0

**Comment by jamuhl** [comment]
Eventual you can try https://github.com/i18next/i18next/issues/1487

the skipOnVariable option...eventual works...but I guess no

more or less this is expected as interpolation runs before nesting the {{count}} gets replaced by '' as it has no value to interpolate

**Comment by jvnlwn** [comment]
Thank you for looking into this.

The `skipOnVariable` interpolation option does indeed "fix" this test case, but it also prevents me from doing something like:

```js
{
  responseFromYouAndOtherAlt:
    '$t({{ count }} response, { "count": {{ responseCount }} }) from you and {{ count }} other',
  responseFromYouAndOtherAlt_plural:
    '$t({{ count }} response, { "count": {{ responseCount }} }) from you and {{ count }} others'
}

t("responseFromYouAndOtherAlt", { responseCount: 1, count: 1 }) //=> "1 response from you and 1 other"
t("responseFromYouAndOtherAlt", { responseCount: 2, count: 2 }) //=> "2 response from you and 2 others"
```

While this works:
```js
{
  responseFromYouAndOther:
    '$t(numReponse, { "count": {{ responseCount }} }) from you and {{ count }} other',
  responseFromYouAndOther_plural:
    '$t(numReponse, { "count": {{ responseCount }} }) from you and {{ count }} others',
}

t("responseFromYouAndOther", { responseCount: 1, count: 1 }) //=> "1 response from you and 1 other"
t("responseFromYouAndOther", { responseCount: 2, count: 2 }) //=> "2 responses from you and 2 others"
```
 
It would seem I am looking for a `skipOnNestedVariable` interpolation option? Or maybe my expectations aren't practical?

**Comment by jamuhl** [comment]
From looking at it as a translator - it might be unpractical. Technical it might be a limitation of how nesting and interpolation are solved without using an AST parser.

I'm open to a PR - but my guess is making this work adds more complexity as needed.

**Comment by jvnlwn** [comment]
I agree with your assessment. The main reason I pursued this option is because of how **i18next-scanner** creates the translation JSON from something like:

```js
t("{{ count }} response", {
  defaultValue_plural: "{{ count }} responses",
  count: Infinity
})
```

Which would produce the JSON:
```js
{
 "{{ count }} pt": "",
 "{{ count }} pt_plural": "{{ count }} pts"
}
```

And for the lazy programmer in me, it is nice not having to name the translation key (i.e. `numReponse`). But to your point, when nesting one of these keys in a translation, it probably adds too much complexity for the human translator.

Thanks for your help!
