### ISSUE TITLE
Translation files ignored with "rejecting language code not found in supportedLngs" warning

### ISSUE THREAD

**Issue by svdHero** [i18next/i18next#1564]
## 🐛 Bug Report

I am writing a React SPA with `i18next` and `react-i18next` using create-react-app. When I load my app in the browser, I get many warnings of the following kind:
```
i18next.js:22 i18next::languageUtils: rejecting language code not found in supportedLngs: en-GB
i18next.js:22 i18next::languageUtils: rejecting language code not found in supportedLngs: en
```
as well as
```
i18next.js:22 i18next::translator: key "navBar.signIn" for languages "" won't get resolved as namespace "common" was not yet loaded This means something IS WRONG in your setup. You access the t function before i18next.init / i18next.loadNamespace / i18next.changeLanguage was done. Wait for the callback or Promise to resolve before accessing it!!!
```
I don't know why this happens, because all my translation files are present, in particular the `en-GB` one, and I use the `<Suspense/>` component.

## To Reproduce

My `index.tsx` looks like this:
```tsx
import React, { Suspense } from "react"
import ReactDOM from "react-dom"
import { BrowserRouter } from "react-router-dom"
import { MsalProvider } from "@azure/msal-react"

import App from "./App"
import { msalInstance } from "./auth"
import "./i18n"

function LoadingComponent() {
    return (
        <div>
            <h1>Loading...</h1>
        </div>
    )
}

ReactDOM.render(
    <React.StrictMode>
        <BrowserRouter basename={process.env.PUBLIC_URL}>
            <MsalProvider instance={msalInstance}>
                <Suspense fallback={<LoadingComponent/>}>
                    <App />
                </Suspense>
            </MsalProvider>
        </BrowserRouter>
    </React.StrictMode>,
    document.getElementById("root")
)
```
My `i18n.ts` looks like this:
```tsx
import i18next, { InitOptions } from "i18next"
import HttpApi from "i18next-http-backend"
import { initReactI18next } from "react-i18next"

const options: InitOptions = {
    supportedLngs: ["en-GB", "de-DE", "zh-CN"],
    lng: "en-GB",
    fallbackLng: "en-GB",
    interpolation: {
        escapeValue: false // React already prevents XSS attacks
    },
    ns: ["common", "device", "myDevices"],
    defaultNS: "common",
    debug: process.env.NODE_ENV === "development"   
}

i18next
    .use(HttpApi)
    .use(initReactI18next)
    .init(options)
```
and my `public` folder contains the translation files:
![locales](https://user-images.githubusercontent.com/24250824/109517752-e251b780-7aa9-11eb-881c-cd55329ce159.png)

What's wrong here?

## Your Environment

- *runtime*: node 14.15.5, Chrome 88.0.4324.190
- *i18next*: 19.9.1
- *i18next-http-backend*: 1.1.1
- *react-i18next*: 11.8.8",
- *os*: Windows 8.1

**Comment by jamuhl** [comment]
`i18next.js:22 i18next::translator: key "navBar.signIn" for languages "" won't get resolved as namespace "common" was not yet loaded This means something IS WRONG in your setup. You access the t function before i18next.init / i18next.loadNamespace / i18next.changeLanguage was done. Wait for the callback or Promise to resolve before accessing it!!!`

this hints the language is set to nothing at  a certain point -> therefore you get those warnings 

But without having a complete sandbox to reproduce your sample it's hard to say where you set the language to be empty (as on init you set it to "en-US"). Do you detect it somewhere and call i18n.changeLanguage?

**Comment by svdHero** [comment]
No, I do not call `i18n.changeLanguage`, but I am utterly stupid and my rubber duck did not help me either.

While debugging, I did not notice that I somehow changed
```js
supportedLngs: ["en-GB", "de-DE", "zh-CN"]
```
to
```js
supportedLngs: ["en-GB, de-DE, zh-CN"]
```
accidentally.

After fixing this, almost all my warnings are gone. The remaining one is
```
i18next.js:22 i18next::languageUtils: rejecting language code not found in supportedLngs: en
```
which is understandable, I guess, because I do not have an `en` folder.

What is the best practice here? Should I create a folder `en`? Also, when I have set `fallbackLng: "en-GB"` and have folders `de-DE` and `de-CH`, should I also create a folder `de`?
What would the fallback be, if the language detector detects `de-AT` as browser locale? Is there some magic happening behind the scenes, so that `de-DE` is the fallback for `de-AT` or should I specify all that manually through
```
fallbackLng: { 
    "en": ["en-GB"]
    "de": ["de-DE"], 
    "default": ["en-GB"]
}
```
similar to the example in [the doc](https://www.i18next.com/principles/fallback#language-fallback)?

**Comment by jamuhl** [comment]
https://www.i18next.com/principles/fallback#language-fallback

I would use pure non regional languages, eg. "en" and just have "en-US" or "en-GB" override texts as needed

**Comment by svdHero** [comment]
That's the page I've already linked above. However, I think the documentation could be more detailed on the fallback logic as well as the implications of `supportedLng` on said logic.

May I elaborate on this in a new issue? I think it could be helpful for other beginners like myself to extend the fallback documentation a little bit.

"Merci" for all the work you put into this awesome project. :slightly_smiling_face: :+1:

**Comment by jamuhl** [comment]
sure...contributions are very welcome

**Comment by svdHero** [comment]
Ok, I will do that tomorrow. Thanks again.
