### ISSUE TITLE
Return value of parseMissingKeyHandler only used once

### ISSUE THREAD

**Issue by markdon** [i18next/i18next#1565]
## 🐛 Bug Report

When i18next config has a parseMissingKeyHandler function the value returned by this function is only returned on the first call of the t() function using a key that is missing a translation. Subsequent calls to t() with the same key instead return the key.

e.g.
``` js
// parseMissingKeyHandler: () => ""
console.log("hello:" + t("hellokey", { lng: "fr-FR" })); // hello:
console.log("hello:" + t("hellokey", { lng: "fr-FR" })); // hello:hellokey
```

## To Reproduce

``` zsh
git clone https://github.com/markdon/i18next-sandbox.git
cd 18next-sandbox
npm i
npm run dev
```

## Expected behavior

When translating a key that is missing, the return value of `t()` is always the same as the return value of `parseMissingKeyHandler`

## Your Environment

- node v14, dependencies in [package.json](https://github.com/markdon/i18next-sandbox/blob/main/package.json) (which should be latest)
- *i18next version*: 19.9.1
- *os*: Mac

**Comment by jamuhl** [comment]
expected behavior: https://github.com/i18next/i18next/blob/master/src/Translator.js#L268 parsedMissing gets called as last funtion when having a missing call -> after the first missing call the key gets added to the store to avoid calling saveMissing unneeded -> so after first saveMissing call it is technically not missing anymore.

**Comment by markdon** [comment]
It sounds like parseMissingKeyHandler was added with a particular purpose in mind that wasn't clearly documented at the time. 

The documentation in [config](https://www.i18next.com/overview/configuration-options#missing-keys) and especially the [type definition](https://github.com/i18next/i18next/blob/b3771d84a873ec7e9420c7f709212af44937e3ec/index.d.ts#L296) plainly describe that the return value of parseMissingKeyHandler will be returned for missing keys. Maybe these could be updated to further explain how parseMissingKeyHandler can be used.

If we accept that parseMissingKeyHandler should only be called once and subsequent calls to t() with the same key return a cached result, should the result of parseMissingKeyHandler be the value that goes in to the store/cache?

**Comment by jamuhl** [comment]
> If we accept that parseMissingKeyHandler should only be called once and subsequent calls to t() with the same key return a cached result, should the result of parseMissingKeyHandler be the value that goes in to the store/cache?

Like said...a key can only be missing once.

Not sure why this really is important - as I never understood what the use case of this function is - and even more why one wants to have it called always --> it's saving missing -> helps with filling the JSON you need to translate -> so what is your use case with it (and if having to run this multiple time - are you using this in production?!?) I'm really confused...

**Comment by markdon** [comment]
I'm generating an XML document that that describes text on buttons plus localised labels and descriptions on those buttons. My intention was to override the output of t() when a translation does not exist for a particular locale. Having a single output value from t() (instead of key fallback) for all untranslated key/locale combinations makes it a little simpler to identify and remove related XML. 

This issue isn't important to me, I only ran in to this behaviour after writing some dodgy code that translated the same key/locale combo twice when I only need it once. The first t() call returns the value from parseMissingKeyHandler, so my use case is satisfied. 

parseMissingKeyHandler changes the value returned by t() on the first call only. The documentation for this function says:
> receives a key that was not found in `t()` and returns a value, that will be returned by `t()`

and 

> function(key) { // return value to display }

Without any knowledge of what parseMissingKeyHandler actually does and the internals of how i18next manages the store of translations, this behaviour is unexpected. There is nothing here to indicate that parseMissingKeyHandler only overrides the value returned by t() once. 

It also just seems wrong for t() to return different values when given the same inputs.

**Comment by jamuhl** [comment]
still it's for missings only -> which should only happen during dev.
