### ISSUE TITLE
unexpected behaviour translation.json is getting called 

### ISSUE THREAD

**Issue by bhargavavarma** [i18next/i18next#1566]
## 💥 Regression Report

I have not given translation value to loadNamespaces, but in my app it was getting called
[http://localhost:3000/i18n/translations/en/translation.json]()

## Last working version

Worked up to version: 19.8.4

Stopped working in version: 19.8.5

## Expected behavior

Should not call any other translation other than the values given in loadNamespaces.

## Your Environment

- *runtime version*: chrome(latest version), firefox(latest version)
- *i18next version*: 19.8.5
- *os*: Mac, Windows, Linux

**Comment by adrai** [comment]
Can you please provide more information and a reproducible example?

**Comment by bhargavavarma** [comment]
When clicking on some date from `react-datepicker` package, translation.json is getting called

**Comment by adrai** [comment]
In which example?

**Comment by bhargavavarma** [comment]
In one of my react component we have used withTranslation('translation'), if we have remove 'translation' value it was working fine as expected.
