### ISSUE TITLE
Trans Component is not safe to use

### ISSUE THREAD

**Issue by cuyl** [i18next/i18next#1567]
## 🐛 Bug Report

I think it better to have a html escape fist when extract save missing keys and unescape it in render time.

```js
// saved content
'<0>name</0><br/><0>{{ name }}</0><br/><0>{{name}}<0/>'
```
## To Reproduce

```js
import React from "react";
import { Trans } from "react-i18next";

function App() {
  const name = "opps";
  return (
    <div className="App">
        <Trans values={{ name }}>
          <span>name</span>
          <br/>
          &lt;0&gt;{"{{"} name {"}}"}&lt;/0&gt;
          <br/>
          {"<0>{{name}}<0/>"}
        </Trans>
    </div>
  );
}

export default App;
```

## Expected behavior

```html
<div class="App">
  <span>name</span>
  <br>
  &lt;0&gt;{{name}}&lt;/0&gt;
  <br>
   &lt;0&gt;{{name}}&lt;/0&gt;
</div>
```

## Current behavior

```html
<div class="App">
  <span>name</span>
  <br>
  <span>opps</span>
  <br>
  <span>oppsname</span>
</div>
```

## Your Environment

- *runtime version*: node v14, browser Chrome/88.0.4324.192 
- *i18next version*: 19.9.1
- *react-i18next version*: 11.8.8
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by jamuhl** [comment]
Sorry...but can't follow...you do useless content and then blame it's not safe?

**Comment by cuyl** [comment]
Sorry about my word, I'm not mean to blame it, and seems this is wrong place I'll reopen it in https://github.com/i18next/react-i18next. I'm just trying to provide some example to show you some edge case.

**Comment by jamuhl** [comment]
@cuyl no worry. it's ok...just there are limitations based on the complexity of the problem -> most common thing should work - edge cases can be rough and not possible to fix - but as far as I know there are no security issues
