### ISSUE TITLE
Pass key name into format function

### ISSUE THREAD

**Issue by plindse** [i18next/i18next#1569]
## 🚀 Feature Proposal

The format function receives the value of an interpolation key as the first parameter, but the name of the interpolation key is not passed in.  If a developer wants to pass options that are specific to a particular interpolation key, there is no way to know which key is being interpolated.

## Motivation

Ability to pass options for individual interpolations and be able to use the key as the identifier for formatting.  The basic use case is having two interpolation values in the same string, but each having unique formatting options that must be passed in the options -- i.e. "Show two different currencies: {{ localValue, currency }} == {{ exchangeCurrency, currency }}".   The translate command provides a way to pass in options to the formation function, but the content of the options is the same for both times the format function is called.  By knowing what interpolation key is being processed, the format function can look into the options for relevant values.  Any guessing as two which key is being formatted could lead to incorrect output.

## Example

The following example code (prior to the enhancedment) would call the interpolation.format function twice with the following values:
Call 1: format( 123.45, "currency", "en", {...,parmOptions:{value:{currency:"USD" },foreignValue:{currency:"CAD"}}} );
Call 2: format( 234.56, "currency", "en", {...,parmOptions:{value:{currency:"USD" },foreignValue:{currency:"CAD"}}} );
Incorrect output: Your transaction balance is $123.45 or $234.56

If the changes are implemented, the following example code will call the interpolation.format function twice with the following values:
Call 1: format( 123.45, "currency", "en", {...,parmOptions:{value:{currency:"USD" },foreignValue:{currency:"CAD"}}}, "value" );
Call 2: format( 234.56, "currency", "en", {...,parmOptions:{value:{currency:"USD" },foreignValue:{currency:"CAD"}}}, "foreignValue" );
Desired output: Your transaction balance is $123.45 or CA$234.56

i18next.init({
  lng: 'en',
  defaultNS: 'app',
  interpolation: {
    format: function(value, rawFormat, lng, opts, key) {
      const [format, ...additionalValues] = rawFormat.split(',').map((v) => v.trim());
      switch (format) {
        case 'currency':
          return Intl.NumberFormat(lng, {
            style: 'currency',
            currency: opts.parmOptions[key].currency
          }).format(value);
          break;
      }
      return value;
    }
  },
  resources: {
    en: {  
      app: {
        transactionValue: "Your transaction balance is {{ value, currency }} or {{ foreignValue, currency }}"
      }
    }
  }
});
i18next.t("transactionValue", { value:123.45, foreignValue: 234.56, parmOptions: { value: { currency: "USD" }, foreignValue : { currency: "CAD" } } });

**Comment by plindse** [comment]
I have a change ready to push and to open a pull request.  However, I'm getting an error when attempting to push to a new branch.  Any ideas on how to become a contributor so I can provide the code for this feature?

**Comment by adrai** [comment]
There is no need to pass the key to the format function:

**Possibility 1:**
```js
i18next.init({
  lng: 'en',
  defaultNS: 'app',
  interpolation: {
      format: function(value, rawFormat, lng, opts) {
          const [format, ...additionalValues] = rawFormat.split(',').map((v) => v.trim());
          switch (format) {
              case 'currency':
                  return Intl.NumberFormat(lng, {
                      style: 'currency',
                      currency: opts.parmOptions.currency
                  }).format(value);
                  break;
          }
          return value;
      }
  },
  resources: {
      en: {
          app: {
              transactionValue: "Your transaction balance is {{ value, currency }} or {{ foreignValue, currency }}"
          }
      }
  }
});

const currencyOptions = {
  value: {
      currency: "USD"
  },
  foreignValue: {
      currency: "CAD"
  },
  transactionValue: {
      currency: "CHF"
  }
}

console.log(i18next.t("transactionValue", {
  value: 123.45,
  foreignValue: 234.56,
  parmOptions: currencyOptions.transactionValue
}));

```

**Possibility 2:**
```js
i18next.init({
  lng: 'en',
  defaultNS: 'app',
  interpolation: {
      format: function(value, rawFormat, lng, opts) {
          const [format, ...additionalValues] = rawFormat.split(',').map((v) => v.trim());
          switch (format) {
              case 'currency':
                  return Intl.NumberFormat(lng, {
                      style: 'currency',
                      currency: opts.parmOptions[opts.key].currency
                  }).format(value);
                  break;
          }
          return value;
      }
  },
  resources: {
      en: {
          app: {
              transactionValue: "Your transaction balance is {{ value, currency }} or {{ foreignValue, currency }}"
          }
      }
  }
});
console.log(i18next.t("transactionValue", {
  key: 'transactionValue',
  value: 123.45,
  foreignValue: 234.56,
  parmOptions: {
      value: {
          currency: "USD"
      },
      foreignValue: {
          currency: "CAD"
      },
      transactionValue: {
          currency: "CHF"
      }
  }
}));
```

**Comment by plindse** [comment]
Adriano,

Thank you for your reply, but both solutions you provided format both fields with the same currency. They do not provide a way to have two different currencies on the same line.

I have a change ready that will pass the interpolation key to the format function. I have attached it to this email.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by adrai** [comment]
pass in to the options everything you need.

**Comment by plindse** [comment]
Adriano,

Thank you for your time and quick responses. I want to make sure I'm not misstating the problem I'm trying to solve. This will be my final explanation.

If the translation string is:

transactionValue:"Amount 1 {{localValue, currency}} and Amount 2 {{convertedValue, currency}}"

then from the options object alone, there is no way to know which interpolation field is being formatted. The format function gets called twice with the same options but two different amounts. The currencies must both be provided as individual settings and added to the options in the same translate request -- ie. i18next.t(transactionValue, options).

To be clear, I'm not asking for the translation key (ie. "transactionValue") to be passed. I need the interpolation key name passed in (ie. "localValue" followed by "convertedValue").

There is one work-around that would be a "solution", but it is not pretty or preferred. It would require passing the variable name twice with every interpolation:

transactionValue:"Amount 1 {{localValue, currency, localValue}} and Amount 2 {{convertedValue, currency, convertedValue}}"

Then the format function can use the name "localValue" and "convertedValue" to determine which where to find the currency definition to use. Unfortunately, the name collides with the actual value name in the options, so it would have to be added as a sub-option or have a unique name different from the key. This would also need to be provided in every case and is redundant if the variable name could simply be added to the format function.

If it would help, I can add more test cases to the code patch. I'd be glad to do so. Also, my company is looking to transition to i18next for our product. Here is a link to product I work on:
https://commerce.toshiba.com/wps/portal/marketing/?urile=wcm:path:/en-us/home/software/commerce-platforms/elera

Thank you again for your responses.

Paul Lindsey

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by adrai** [comment]
Why not using a second format?
currency2

"Amount 1 {{localValue, currency1}} and Amount 2 {{convertedValue, currency2}}"

**Comment by plindse** [comment]
Pull request has been submitted.
