### ISSUE TITLE
Reinitializing was working in version 19.8.7 but started breaking after 19.8.8

### ISSUE THREAD

**Issue by akshayr-tavisca** [i18next/i18next#1570]
## 💥 Regression Report

As per our requirements we had to use a single instance of i18next through out the application.
Within the application we are loading a base component library which works in a standalone mode (for culture) during development.
Once developed this library is packaged and published on NPM.
Within the application we are installing base components via NPM. 
Since base components are not bundled they point towards similar instance of i18next as the consumer.
Due to incorrect loading sequence even if the base component initializes the i18next instance we want it to be reinitialize by the consumer (application) which would be finally responsible for pulling resources for the loaded base components in production.

I just saw the docs stating we shouldn't ideally called init function twice, but as per our use case its essential for us to recall the init function so that even if the base component initializes the package, it is re initialized by the consumer.
Ref: https://www.i18next.com/overview/api

This was working as expected till version 19.8.7 but in 19.8.8 something broke this behaviour, I tried going through the tags but couldn't found something that would have broken the flow.

Kindly help us to resolve above issue. Looking forward to your reply

## Last working version

Worked up to version: 19.8.7

Stopped working in version: 19.8.8

## To Reproduce

Try calling init method twice for switching lng and resources, (Although this can be changed via other API as well, its important for us to have a completely fresh instance)

```js
instance = i18next.createInstance()

coreInit = (options) => {
 instance.init(options)
}
```

## Expected behavior

Should be able reinitialize the package without any side effects

```js
// Paste the results here
```

## Your Environment

- *runtime version*: i.e. node v14
- *i18next version*: i.e. 19.8.8
- *os*: Windows
- *any other relevant information*

Ref: https://github.com/i18next/i18next/compare/v19.8.7...v19.8.8

I guess due to above change lng is not changing

**Comment by adrai** [comment]
A reproducible example would help to understand what you are trying to do.


btw: maybe using cloneInstance would help

**Comment by akshayr-tavisca** [comment]
Hi @adrai thank you for the quick response,

We have a wrapper package around i18next as per our requirement we have exposed only few function out of this package,
1. Function to initialize i18next by passing configurable options from outside, (majority of the options are pre-configured)
2. Translate function to consume i18next API.

Within the package we have a class with static property

class Core {
 static i18nDefaultInstace = i18next.createInstance(),
 static isInitialized = false;

 static getDefaultInstance() {
  return i18nDefaultInstace;
 }

 // Method
 static init = (options, shouldReinitialize) => {
  if(isInitialized &7 !shouldReinitialize) {
     return i18nDefaultInstance;
   }
   isInitialized = true;
  return Core.i18nDefaultInstance.init(options)
 }
}

export const init = Core.init 
export const i18nDefault= Core.getDefaultInstance();

// Within the sdk in another file we have exported a translate function which looks like,
import { i18nDefault } from '../main'

export const t = i18nDefault.t.bind(i18nDefault);

Although we would be able to reset i18nDefaultInstace by creating a new instance with in the init method,
this would break the t function which was still pointing towards the previous instance

**Comment by adrai** [comment]
Please create a complete example, so We can test on our side.

But generally, it you have access to the i18next instance, you should also be able to access the new t function.

**Comment by akshayr-tavisca** [comment]
Ok, before tomorrow EOD  I will share an example to reproduce above issue

**Comment by akshayr-tavisca** [comment]
Hi @adrai 

You can use below test case to validate the issue, below tests work in version19.8.7 but fails in 19.8.8, kindly do help us resolve this issue

`import i18next from "i18next";
const enResources = { "en-US": { translation: { cancel_btn: "Cancel" } } };
const esResources = { "es-ES": { translation: { cancel_btn: "Cancelar" } } };
const baseConfig = {
  lng: "en-US",
  resources: {}
};

const i18n = i18next.createInstance();
const CultureList = ["en-US", "es-ES"];

describe.each(CultureList)(`Test in culture: %s for translation`, (culture) => {
  beforeAll(async () => {
    if (culture === "en-US") {
      baseConfig.resources = enResources;
    } else if (culture === "es-ES") {
      baseConfig.resources = esResources;
    }
    baseConfig.lng = culture;
    i18n.init(baseConfig);
  });

  test("should be able to handle translated values correctly", () => {
    expect(i18n.t("cancel_btn")).toBe(
      culture === "en-US" ? "Cancel" : "Cancelar"
    );
  });
});
`

**Comment by adrai** [comment]
Did not run this, but can see you're creating just 1 instance and are calling init function twice...

**Comment by akshayr-tavisca** [comment]
correct, that's why I gave title to this thread as issues with re initialization was working in 19.8.7 but started failing from 19.8.8 on wards

**Comment by adrai** [comment]
i18next was never intended to be used like you're using it.
with v19.8.8 we fixed an issue when calling changeLanguage during init...

**Comment by akshayr-tavisca** [comment]
Thank you @adrai will await response()

**Comment by akshayr-tavisca** [comment]
Comparing the diff, might help: https://github.com/i18next/i18next/compare/v19.8.7...v19.8.8

**Comment by dziraf** [comment]
We've been experiencing a similar issue for the past 2-3 weeks in our projects but were unable to find the culprit. After seeing this thread, I looked at our `node_modules` and noticed that `v19.9.1` was being used.
I degraded the version to `v19.8.7` for a quick test and it actually does help.

In our case the issue can be reproduced by simply logging in, the translations are just not there. However if the server is restarted while the user is logged in and the user refreshes the page, the translations will be there (until the user relogs).

The init function is here:
https://github.com/SoftwareBrothers/admin-bro/blob/master/src/admin-bro.ts#L107
We check if i18n is already initialized in case it's defined before in user's own code. However, when reproducing this it goes into `else`.

**Comment by adrai** [comment]
One of those moment, where fixing one issue triggers the other one....
Can you try with v19.9.2 ?

**Comment by adrai** [comment]
@dziraf your issue might be different... a small reproducible example might help.

**Comment by akshayr-tavisca** [comment]
It worked on 19.9.2, thank you for the quick help @adrai

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏

**Comment by dziraf** [comment]
@adrai `19.9.2` looks to be working for us too, thanks for the quick fix 😄

**Comment by dargmuesli** [comment]
Hmm, `19.9.2` breaks my build: https://github.com/maevsi/stomper/pull/39
I suddenly receive `undefined`: https://github.com/maevsi/stomper/pull/39/checks?check_run_id=2069463730
Btw, thanks for locize.com, my company uses it :)

**Comment by adrai** [comment]
@dargmuesli Can you please create a new issue and add a small reproducible example?
