### ISSUE TITLE
handlebars-i18n compiles to "undefined" in 19.9.2

### ISSUE THREAD

**Issue by dargmuesli** [i18next/i18next#1573]
## 💥 Regression Report

Compiling a handlebars template with [handlebars-i18n](https://github.com/fwalzel/handlebars-i18n) now return `undefined` instead of a translation: https://github.com/maevsi/stomper/pull/39
I use `i18next.changeLanguage` just before `Handlebars.compile` and I guess that's a related circumstance due to #1570.

## Last working version

Worked up to version: 19.9.1

Stopped working in version: 19.9.2

## To Reproduce / Expected behavior

See my fairly short [handlebars.ts](https://github.com/maevsi/stomper/blob/9d39cfc495fbb19c331e8f2633c534aec8f49ae3/src/handlebars.ts#L42) and [handlebars.test.ts](https://github.com/maevsi/stomper/blob/master/src/handlebars.test.ts) and their [CI result](https://github.com/maevsi/stomper/pull/39/checks?check_run_id=2069859294).
I currently don't have time to create a separate three liner, but I want to let you know either way. The linked code is already pretty short in itself.

## Your Environment

- *runtime version*: Docker - `node:14.16.0-alpine3.13@sha256:7eb57d8fd2d3ee789dbb551bdf5b0325369c3ad7a72a690e80d034041da7e42d`

**Comment by dargmuesli** [comment]
I've updated the `handlebars.ts` to point to the mentioned line.

**Comment by adrai** [comment]
![image](https://user-images.githubusercontent.com/1086194/110532287-ea9a9a00-811c-11eb-98f9-8792330fabad.png)

**Comment by dargmuesli** [comment]
Which node version do you use?

**Comment by adrai** [comment]
v14.15.5

**Comment by adrai** [comment]
just tested with v14.16.0, works

**Comment by dargmuesli** [comment]
Closing this for now as the issue seems to be with something else.

**Comment by dargmuesli** [comment]
Oh well, `yarn upgrade` solved the issue by refreshing the lockfile... 🙄🤷
