### ISSUE TITLE
Interpolation of url encodes it

### ISSUE THREAD

**Issue by Aarbel** [i18next/i18next#1576]
![image](https://user-images.githubusercontent.com/25119847/110653344-73691280-81bd-11eb-9a91-2d816486456d.png)

Outputs:

```
>> link http://localhost:3000/s/jwaVf5lB
>>> sms.text Gustave Eiffel vous invite à rejoindre le projet “Dev1 - Projet de développement” sur Clovis : http:&#x2F;&#x2F;localhost:3000&#x2F;s&#x2F;jwaVf5lB
```

i18n seems to encode url when it's a variable, how to solve this ?

**Comment by Aarbel** [comment]
Solved passing `interpolation: { escapeValue: false },` as options

**Comment by fbonhomm** [comment]
https://github.com/Clovis-team/clovis/pull/2216

**Comment by fbonhomm** [comment]
https://www.i18next.com/translation-function/interpolation#unescape
