### ISSUE TITLE
Improvement to typescript types for plugins

### ISSUE THREAD

**Issue by andreialecu** [i18next/i18next#1578]
## 🚀 Feature Proposal

Currently, the types for `i18next` expose fields that should instead be exposed by those particular plugins:

https://github.com/i18next/i18next/blob/a6e09e32301d371092abf2d3bfed1ffa31db9a18/index.d.ts#L381-L403

## Motivation

Typing them as `object`, as they are now, is not type safe, and does not assist with code completion in modern IDEs.

I believe it should be possible for the plugins themselves to augment the main `i18next` types.

For this to work however, the fields specified in the Feature Proposal above need to be removed from the definitions of `i18next` (an existing property's type cannot be replaced by augmentation)

## Example

 For example, `i18next-locize-backend` could include the following:

```ts
declare module "i18next" {
  interface InitOptions {
    backend?: I18NextLocizeBackend.BackendOptions;
  }
}
```

In this case, `backend` would be typed properly.

**Comment by andreialecu** [comment]
Related: https://github.com/locize/i18next-locize-backend/issues/336#issuecomment-798898836

**Comment by adrai** [comment]
//cc @pedrodurek

**Comment by pedrodurek** [comment]
I'll take a look and create a PR for it. Thanks @andreialecu!

**Comment by pedrodurek** [comment]
Hey @andreialecu, was it solved?

**Comment by andreialecu** [comment]
Hey @pedrodurek. 

Just updated, and yes, I can confirm that `backend` is now fully typed and provides proper documentation for it fields.

Awesome, thanks!
