### ISSUE TITLE
[BUG]: Nesting issue, can't refer to another key of the same namespace when multi-level.

### ISSUE THREAD

**Issue by simplecommerce** [i18next/i18next#1580]
## 🐛 Bug Report

When using nesting, referring to another key within the same namespace only seems to work on the primary level.

## To Reproduce

https://codesandbox.io/s/vigorous-forest-4p30y?file=/src/App.js

On the sandbox, click on the first button, it should alert with the message "hehe" inside. (this works).
* It refers to a key in the primary level.

Click on the 2nd button, it should alert with "Something wrong I know." inside. (this fails).
* It refers to a key in a nested level but on the same level as the one being called.

Click on the 3rd button, it should alert with "Something wrong I know." inside. (this works).
* Same as above, but the full path to the key is provided manually.

```js
i18next.init({
  lng: "en",
  debug: true,
  resources: {
    en: {
      translation: {
        nesting1: "$t(nesting2)",
        nesting2: "hehe",
        logs: {
          description: {
            error: {
              NOTE: "Something wrong $t(OTHER_NOTE)",
              OTHER_NOTE: "I know.",
              NOTE_WORKS:
                "Something wrong $t(logs.description.error.OTHER_NOTE)"
            }
          }
        }
      }
    }
  }
});
```

## Expected behavior

In the sandbox, I was expecting the 2nd button to actually work, since the key I am referring to, is in the same namespace and level, but it doesn't.

The only way to make it work, is to write the whole path to the key. I was expecting it to work as the first button on the primary level.

## Your Environment

latest version of i18next (19.9.2)

**Comment by adrai** [comment]
Why should this work?

`OTHER_NOTE` is not the key name, the key name is: `logs.description.error.OTHER_NOTE`

**Comment by simplecommerce** [comment]
@adrai why does this work?

```
  nesting1: "$t(nesting2)",
  nesting2: "hehe",
```
is it because `nesting` is both in the key names?

**Comment by adrai** [comment]
because nesting2 is the actual key name

**Comment by adrai** [comment]
en = language
translation = namespace
property path to actual translation = key name
i.e. 
nesting1
nesting2
logs.description.error.NOTE
logs.description.error.OTHER_NOTE
logs.description.error.NOTE_WORKS

**Comment by simplecommerce** [comment]
@adrai ok, I understand better now, I just read it wrong, I was assuming it was looking for keys matching the current level.

Thanks for your explanation!

**Comment by adrai** [comment]
you're welcome
