### ISSUE TITLE
Class getters are no longer supported

### ISSUE THREAD

**Issue by DamianHeard** [i18next/i18next#1585]
## 💥 Regression Report

Class getters are no longer supported.

## Last working version

Worked up to version: 19.8.4

Stopped working in version: 19.8.5

## To Reproduce

I've created a codesandbox [here](https://codesandbox.io/s/admiring-meadow-9nhyt).

Steps to reproduce the behaviour:

```js
import i18next from "i18next";

class Child {
  get value() {
    return "value";
  }
}

const child = new Child();

class Parent {
  get child() {
    return child;
  }
}

const instance = new Parent();

i18next
  .init({
    lng: "en",
    debug: true,
    resources: {
      en: {
        translation: {
          key: "foo getter value: {{foo.child.value}}",
        },
      },
    },
  })
  .then(function (t) {
    const translated = i18next.t("key", { foo: instance });
    // console.warning => i18next::interpolator: missed to pass in variable foo.child.value for interpolating foo getter value: {{foo.child.value}}
    document.getElementById("app").innerHTML = translated;
  });
```

## Expected behaviour

The `translated` string be `"foo getter value: value"`.

## Your Environment

- _runtime version_: node v12.17.0, npm 6.14.11
- _i18next version_: 19.9.2
- _OS_: Mac

## Additional information

[This commit](https://github.com/i18next/i18next/commit/932f5f662893376254d826e9b01dc4e4c0cd91c0) which protects against prototype pollution appears to be the root cause. `Object.hasOwnProperty()` will always return `false` for getters as they are owned by the prototype itself and not its instances. It is not clear what the intent of the property check is and whether a class getter should violate this.

I am happy to work with the maintainer here to submit a PR that either:

1. Addresses the issue should you agree this warrants attention; or
2. Beef up the documentation to explicitly call out that javascript classes are not supported as interpolation arguments.

**Comment by adrai** [comment]
This was never supported (at least by intension).
But if you know a way to solve this without removing the prototype pollution fix, feel free to submit a PR.

**Comment by DamianHeard** [comment]
Thank you for taking the time to respond to my issue. I am not a security expert so it's seems I might having unwittingly stumbled into a mine field here.

Out of curiosity, with respect to the prototype pollution fix, is there a specific ticket or report the `Object.hasOwnProperty()` check was trying to address, or was this change more about proactively trying to avoid such reports?

**Comment by adrai** [comment]
There was an issue, but originated via private e-mail... 

https://snyk.io/vuln/SNYK-JS-I18NEXT-1065979
