### ISSUE TITLE
Translation on EJS page doesn't update when language is changed

### ISSUE THREAD

**Issue by anonymous675** [i18next/i18next#1593]
## 🐛 Bug Report

I set up the i18next as the documentation said, but when I change the language of i18next the translation on the page doesn't change.

## To Reproduce

```js
const i18next = require("i18next");
const i18nextMiddleware = require('i18next-http-middleware');
const i18nextBackend = require("i18next-fs-backend");
const i18nextSupporteLngs = ["en", "he"];

i18next
    .use(i18nextMiddleware.LanguageDetector)
    .use(i18nextBackend)    
    .init({
        lng: "en",
        fallbackLng: 'en',
        supportedLngs: i18nextSupporteLngs,
        preload: i18nextSupporteLngs,
        initImmediate: false,
        ns: ['translation'],
        defaultNS: 'translation',
        backend: {
            loadPath: path.join(__dirname, "..") + '/locales/{{lng}}/{{ns}}.json',
        },
        detection: {
          order: ["querystring", "cookie", "header"]
        }
    });

app.use(i18nextMiddleware.handle(i18next));

app.get("/set-preferences", (req, res) => {

  let { language } = req.query;

  if (language && i18nextSupporteLngs.includes(language)) {
    i18next.changeLanguage(language);
    req.i18n.changeLanguage(language);
  }

  res.redirect("/");
});
```

```ejs
<a href="/articles" class="nsg-navbar__link"><%= t("navbar.articles") %></a>
```

## Expected behavior

The expected behavior is that when I change the language the text on the page should change to hebrew, but it stays English.

## Your Environment

- *runtime version*: node v12.16.1, Chrome latest version
- *i18next version*: 20.1.0
- *i18next-fs-backend version*: 1.1.1
- *i18next-http-middleware version*: 3.1.0
- *os*: Windows 10

**Comment by adrai** [comment]
It does not work like that...
i18next-http-middleware is a server side module...
changing a client side language is done via the `i18nextMiddleware.LanguageDetector`...
this means the language needs to be in one of the detection places: https://github.com/i18next/i18next-http-middleware#language-detection
i.e.
- path
- cookie
- header
- querystring
- session


for example check out this example: https://github.com/i18next/i18next-http-middleware/tree/master/example/basic-pug
when passing the query param "locale=en" it will detect this automatically: https://github.com/i18next/i18next-http-middleware/blob/master/example/basic-pug/index.js#L33
(the default is `?lng=en`: https://github.com/i18next/i18next-http-middleware#detector-options)

I hope this information helps.
