### ISSUE TITLE
Add live update of translation files

### ISSUE THREAD

**Issue by anonymous675** [i18next/i18next#1594]
## 🚀 Feature Proposal

If debug mode is activated, i18next will check every time it loads a page if the translation files have changed. If yes, it would load the new file.

## Motivation

Every time you change the translations, you have to reload the server to see the new translations.

## Example

```node.js
i18next
  .init({
    debug: true
  });
```

**Comment by adrai** [comment]
https://github.com/felixmosh/i18next-hmr
