### ISSUE TITLE
"includes" is not supported in all the browsers

### ISSUE THREAD

**Issue by gmi182** [i18next/i18next#1596]
## 🐛 Bug Report

`includes` is not supported on all the browsers.
https://caniuse.com/?search=includes
If we want to use it in an older browser, this line won't work:

https://github.com/i18next/i18next/blob/master/i18next.js#L1589

Can you change it to `indexOf`? Or should I send a PR with that?

## To Reproduce

Use the library in an older browser, i.e. Internet Explorer 10-11

```js
// Replace:
if (match[0].includes(this.formatSeparator) ...
// For:
if (match[0].indexOf(this.formatSeparator) !== -1 ...
```

## Expected behavior

When loading the library, it will work on older browsers. The next code is not supported in all the browsers:

```js
if (match[0].includes(this.formatSeparator) ...
```

## Your Environment

- *runtime version*: Internet Explorer 10/11 (any older browser)
- *i18next version*: i.e. 20.1.0
- *os*: Mac

**Comment by pedrodurek** [comment]
You could configure your project's babel to add and remove polyfills to support certain browsers. 🤔

**Comment by adrai** [comment]
@gmi182 if replacing the includes is all that has to be done to make IE working, a PR would be welcome.

**Comment by jamuhl** [comment]
if you need to support outdated browsers - polyfilling should be the way to go. 

i think we should not extend lifetime of end of life browsers by downgrading features for them.

**Comment by adrai** [comment]
> if you need to support outdated browsers - polyfilling should be the way to go.
> 
> i think we should not extend lifetime of end of life browsers by downgrading features for them.

was writing the same ;-) but then I saw: https://github.com/i18next/i18next/blob/master/src/i18next.js#L18

**Comment by adrai** [comment]
v20.2.0
