### ISSUE TITLE
Add 'Punjabi' (pa) in the list of RTL languages

### ISSUE THREAD

**Issue by alexlopezit** [i18next/i18next#1598]
https://github.com/i18next/i18next/blob/5d5962575ca620bd72ebe6da002ef34e1a9f3f40/src/i18next.js#L433

Is it possible to add Punjabi "pa" to the list for RTL languages?

**Comment by jamuhl** [comment]
Guess that is not as simple as I thought:

Punjabi is written in 3 different scripts - where two are written left to right and one right to left: https://www.quora.com/How-is-Punjabi-written

So, it depends on the script used to write it rather than the language itself

**Comment by alexlopezit** [comment]
Thanks @jamuhl I was not aware of that and looks like the official script supported should be LTR, so I am closing this issue.
