### ISSUE TITLE
Return a promise at init

### ISSUE THREAD

**Issue by nithril** [i18next/i18next#16]
It could be great if i18next return a promise a init instead (or in parallel) of using a callback.

So I can use i18next async as the jquery async way.

Thanks!

**Comment by EvanCarroll** [comment]
Should we update the docs?  And shouldn't the CB accept arguments in the function?

**Comment by jamuhl** [comment]
the >=v2.x.x documentation does not state that you get a promise back on init...there is no promise support anymore.

**Comment by EvanCarroll** [comment]
That's tragic, that's what I thought. So let's reopen? I think this feature is awesome. Especially with ES7 coming out. Promises will be everywhere. Having init() return a promise means we can yield it inside of asynchronous functions in node (which will be there very soon).

**Comment by jamuhl** [comment]
nothing against a PR adding promises...just had no time for that when i rewrote i18next.

**Comment by adyz** [comment]
I've found out that in node if you load the resources from a slow API without a promise, this will not initialize properly some times.

Also tried using the `.done()` and I get `done is not a function`  in node

**Comment by jamuhl** [comment]
right now there is no more support for promises...use the provided callback...still open for PR adding promises
