### ISSUE TITLE
Cannot switch languages.

### ISSUE THREAD

**Issue by peculiarity** [i18next/i18next#1600]
## 💥 Regression Report
I'm using `next-i18next` which depends on `react-i18next` which basically uses `i18next`. 
I have an application that load successfully the default `en` version of the website. The application uses `changeLanguage` function that is exported form the `useTranslation` hook. Whenever I would like to call the `changeLanguage` function with a non-null / non-undefined value, I keep receiving the following error. 

![change language github](https://user-images.githubusercontent.com/23715025/114000366-398e3900-985b-11eb-9b27-76a07058425e.png)

The issue that I'm having is tracked down the `i18next.js` within the `i18next` package.
(`/node_modules/i18next/dist/esm/i18next.js`)

## Last working version

We have another application that uses an older version of the `next-i18next` which uses old version of the `i18next` and it's working without any problems.

The version of the `i18next` package is : `19.4.5`

Stopped working in version: Y.Y.Y

Current application that has issues with changing languages has `i18next` package version `20.2.1`

## To Reproduce

```js
import { useTranslation } from 'next-i18next'
import React from 'react'
import ReactSelect from 'react-select'
import { Box, Card, Container, Flex, Grid, Link, Text } from 'theme-ui'

function LanguageSelect() {
  const {
    t,
    i18n: { language, changeLanguage },
  } = useTranslation('common')

  const LANGUAGE_OPTIONS = [
    { value: 'en', label: t('landing.footer.language.en') },
    { value: 'es', label: t('landing.footer.language.es') },
    { value: 'pt', label: t('landing.footer.language.pt') },
  ]

  return (
    <ReactSelect
      options={LANGUAGE_OPTIONS.filter(({ value }) => value !== language)}
      isSearchable={false}
      value={LANGUAGE_OPTIONS.find(({ value }) => value === language)}
      // @ts-ignore
      onChange={({ value }) => changeLanguage(value)}
      components={{
        IndicatorsContainer: () => null,
        ValueContainer: ({ children }) => <Flex sx={{ color: 'primary' }}>{children}</Flex>,
        SingleValue: ({ children }) => <Box>{children}</Box>,
        Option: ({ children, innerProps }) => (
          <Box
            {...innerProps}
            sx={{
              py: 2,
              pl: 3,
              pr: 5,
              cursor: 'pointer',
              '&:hover': {
                bg: 'background',
              },
            }}
          >
            {children}
          </Box>
        ),
        Menu: ({ innerProps, children }) => (
          <Card
            {...innerProps}
            sx={{
              position: 'absolute',
              borderRadius: 'large',
              p: 0,
              overflow: 'hidden',
              top: 0,
              transform: `translateY(calc(-100% + -8px))`,
              boxShadow: 'cardLanding',
            }}
          >
            {children}
          </Card>
        ),
        MenuList: ({ children }) => <Box sx={{ textAlign: 'left' }}>{children}</Box>,
        Control: ({ innerProps, children, selectProps: { menuIsOpen } }) => (
          <Box
            {...innerProps}
            sx={{
              display: 'inline-flex',
              cursor: 'pointer',
              variant: 'links.nav',
              justifyContent: 'space-between',
              alignItems: 'center',
            }}
          >
            {children}
            <Icon
              name={menuIsOpen ? 'chevron_up' : 'chevron_down'}
              size="auto"
              width="12px"
              sx={{ ml: 2 }}
            />
          </Box>
        ),
      }}
    />
  )
}
```

## Expected behavior

I expected to have the page loaded and translated into the selected page

## Your Environment

- *runtime version*: i.e. node v14.15.4
- *i18next version*: i.e. 20.2.1
- *next-i18next*: "8.1.3",
- *react-i18next*: "11.8.9",
- *typescript*: "4.1.3",
- *os*: Linux

We have `common.json` under each of the language folders: - - `public/locales/<[en, es, pt]>/common.json`

We have the following `next-i18next.config.js`
```js
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'es', 'pt'],
  },
}
```

I did some investigation and it turned out that `line:2113`  in this file `/node_modules/i18next/dist/esm/i18next.js` 
 - `this.isLanguageChangingTo = lng;` is causing the trouble because the value for `this` is `undefined`

I was debugging and basically when the application loads first, everything is fine. After I call the `changeLanguage` function with a new language then `this` is undefined and nothing continues further.

This is the code that I was debugging:
```js
{
    key: "changeLanguage",
    value: function changeLanguage(lng, callback) {
      var _this4 = this;

      console.log('DEBUG:THIS', this)


      console.log('DEBUG:LANG:VALUE', lng)
      this.isLanguageChangingTo = lng;
      console.log('DEBUG:AFTER:isLanguageChangingTo')
      var deferred = defer();
      console.log('DEBUG:AFTER:deferred')
      this.emit('languageChanging', lng);
      console.log('DEBUG:AFTER:emit')

      var done = function done(err, l) {
        if (l) {
          _this4.language = l;
          _this4.languages = _this4.services.languageUtils.toResolveHierarchy(l);

          _this4.translator.changeLanguage(l);

          _this4.isLanguageChangingTo = undefined;

          _this4.emit('languageChanged', l);

          _this4.logger.log('languageChanged', l);
        } else {
          _this4.isLanguageChangingTo = undefined;
        }

        deferred.resolve(function () {
          return _this4.t.apply(_this4, arguments);
        });
        if (callback) callback(err, function () {
          return _this4.t.apply(_this4, arguments);
        });
      };

      var setLng = function setLng(lngs) {
        var l = typeof lngs === 'string' ? lngs : _this4.services.languageUtils.getBestMatchFromCodes(lngs);

        if (l) {
          if (!_this4.language) {
            _this4.language = l;
            _this4.languages = _this4.services.languageUtils.toResolveHierarchy(l);
          }

          if (!_this4.translator.language) _this4.translator.changeLanguage(l);
          if (_this4.services.languageDetector) _this4.services.languageDetector.cacheUserLanguage(l);
        }

        _this4.loadResources(l, function (err) {
          done(err, l);
        });
      };

      if (!lng && this.services.languageDetector && !this.services.languageDetector.async) {
        setLng(this.services.languageDetector.detect());
      } else if (!lng && this.services.languageDetector && this.services.languageDetector.async) {
        this.services.languageDetector.detect(setLng);
      } else {
        setLng(lng);
      }

      return deferred;
    }
  }
```

This is the debug trace from execution:
![debug trace](https://user-images.githubusercontent.com/23715025/114003830-6132d080-985e-11eb-8dfd-ceedd156a0de.png)

**Comment by jamuhl** [comment]
looks to me more like a case of overusing es6 destruction:

```js
  const {
    t,
    i18n: { language, changeLanguage },
  } = useTranslation('common')
```

calling `changeLanguage` this way is not the same as calling `i18n.changeLanguage` as it's not bound to `the i18n instance as this`

i18n is an instance - not some module export you can deconstruct

**Comment by peculiarity** [comment]
I thought the same  but:
1. In the app where everything works we use it that way and we have no issues
2. I've tried this `i18n.changeLanguage` and the outcome was the same as the one described within the problem

**Comment by peculiarity** [comment]
That worked - thanks a lot. I've tried that before and it didn't work for some reason ( probably I did something wrong initially ). I've tried now and it works fine.

Note: It the application that everything works fine, we are using the same approach ( destructuring to the method ).

**Comment by jamuhl** [comment]
works fine -> because luck (nothing needs access to the instance in the old version -> still deconstructing everything is not so a good idea)
