### ISSUE TITLE
Multiple changeLanguage call may result in wrong order

### ISSUE THREAD

**Issue by waivital** [i18next/i18next#1605]
## 🐛 Bug Report

When call `changeLanguage` multiple times,  if `loadResources` inside the `changeLanguage` resolved in different order, then the final language will be the last resolved `changeLanguage` call, instead of the last `changeLanguage` call.
 
## To Reproduce

```js
    describe('changeLanguage', () => {
      it('it should keep changeLanguage call in order', () => {
        const instance = i18next.createInstance();
        const makeLang = (lan, delay) => ({
          delay,
          value: {
            foo: `${lan}`,
          },
        });
        const langMap = {
          en: makeLang('en', 100),
          zh: makeLang('zh', 500),
          es: makeLang('es', 300),
          jp: makeLang('jp', 200),
        };

        return new Promise(resolve => {
          instance
            .use({
              type: 'backend',
              read: function(language, namespace, callback) {
                const lang = langMap[language];

                setTimeout(() => {
                  callback(null, lang.value);
                }, lang.delay);
              },
            })
            .init(
              {
                fallbackLng: 'en',
              },
              (err, t) => {
                resolve(
                  Promise.all([
                    instance.changeLanguage('en'),
                    instance.changeLanguage('zh'),
                    instance.changeLanguage('jp'),
                    instance.changeLanguage('es'),
                  ]).then(() => {
                    expect(t('foo')).to.equal('es');
                  }),
                );
              },
            );
        });
      });
    });
```

## Expected behavior

Test not fail. The value of `t('foo')` is `es`

## Your Environment

- *runtime version*:  node v14.16.0
- *i18next version*: 20.2.1
- *os*:  Linux

**Comment by jamuhl** [comment]
do you have a real use case you run into this? can‘t think of a situation where users toggle language like this

**Comment by waivital** [comment]
I recently faced this issues when combined i18next and react-i18next with Server Side Render. 

The server side resolved language is 'zh' and the browser detector answer is 'en', because i18next init called before react hydrate, therefore changeLanguage first called with 'en' then 'zh', but the 'en' resource load a bit slower then the other, so the page result in wrong language.

When there are multiple place can cause language change (or change language twice shortly in one place), may need add some code keep it done in order.

I'm not quite sure about if its better do this work inside i18next or outside.

**Comment by jamuhl** [comment]
If you already do serverside language detection you should not detect on client again - but passing down the server language to client: https://react.i18next.com/latest/ssr#passing-initial-translations-initial-language-down-to-client

In details consider having a look at https://github.com/isaachinman/next-i18next on how it's properly done

**Comment by waivital** [comment]
Thanks for your advice. Because I need to do some async work before rendering React, the i18n’s async init process may happen earlier than the ‘useSSR’ call, then I run into this.

Create client inside React like what next-i18next do, maybe a good choice, and thanks again 😄

**Comment by scplay** [comment]
This trapped me for quite a while cause I was using a parent project passing locale param to trigger a child component to call i18n.changeLanguage inside. However, it would be called multiple times at the very beginning, which causes the final language to be different from the order I pass thru to the child component.

**Comment by waivital** [comment]
This "feature" allows random people to learn from it. 😄

**Comment by waivital** [comment]
@adrai @jamuhl @scplay I prepared a new [Pull Request](https://github.com/i18next/i18next/pull/2298) for this fix.

**Comment by adrai** [comment]
fixed in v25
