### ISSUE TITLE
Kazakh plural forms do not match CLDR

### ISSUE THREAD

**Issue by hikiko4ern** [i18next/i18next#1607]
## 🐛 Bug Report

According to [the CLDR](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html#kk), Kazakh has a singular and one plural form, however [`PluralResolver`](https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L15) defines only the singular.
The [l10n-guide](http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html) mentioned in [the code](https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L3) also describes the plural form as `n != 1`.

## To Reproduce

https://codesandbox.io/s/react-i18next-forked-qf5di

## Expected behavior

The `key_plural` key should be used if `count != 1`.

## Your Environment

- *i18next version*: i.e. 20.2.1

**Comment by jamuhl** [comment]
If you like you might provide a PR -> moving it from https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L15 to either https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L6 or https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L9

**Comment by adrai** [comment]
fixed with v20.2.2
