### ISSUE TITLE
Does not load the configured languages

### ISSUE THREAD

**Issue by kaname-png** [i18next/i18next#1610]
## 🐛 Bug Report

I try to use the configured languages but I get incorrect languages.

## To Reproduce
Load the i18next constructor

```js
i18next.init({
      lng: 'es-ES',
      fallbackLng: 'es-ES',
      keySeparator: '.',
      resources: {
        'es-ES': {
          commands: require('../utils/locales/es-ES/commands.json'),
          listeners: require('../utils/locales/es-ES/listeners.json'),
          inhibitors: require('../utils/locales/es-ES/inhibitors.json'),
          helpers: require('../utils/locales/es-ES/helpers.json'),
          services: require('../utils/locales/es-ES/services.json'),
        },
        'en-US': {
          commands: require('../utils/locales/en-US/commands.json'),
          listeners: require('../utils/locales/en-US/listeners.json'),
          inhibitors: require('../utils/locales/en-US/inhibitors.json'),
          helpers: require('../utils/locales/en-US/helpers.json'),
          services: require('../utils/locales/en-US/services.json'),
        },
      },
    });
```

![image](https://user-images.githubusercontent.com/56084970/118905265-9c520600-b8d8-11eb-8f60-c4e0ccba0691.png)

## Expected behavior
I don't get the configured languages, I only get one and the other one with the key "es", I don't know where that language appeared from.

![image](https://user-images.githubusercontent.com/56084970/118905223-8ba19000-b8d8-11eb-903c-1715cce9de76.png)

```js
  public getLangs(): string[] {
    return i18next.languages;
  }
```

## Your Environment

- *runtime version*: node v14.16.0
- *i18next version*: 20.2.2
- *os*: Windows

**Comment by adrai** [comment]
Set the load option to 'currentOnly'
https://www.i18next.com/overview/configuration-options
![image](https://user-images.githubusercontent.com/1086194/118927323-e4594300-b941-11eb-85ba-496457b92fb6.png)


This information may help: https://www.i18next.com/overview/api#languages

**Comment by jamuhl** [comment]
and https://www.i18next.com/principles/fallback#language-fallback

**Comment by kaname-png** [comment]
Excellent, thanks @adrai  for the help and reviewing what @jamuhl told me helped me a lot!
