### ISSUE TITLE
i18next::translator: missingKey de translation

### ISSUE THREAD

**Issue by maxizhukov** [i18next/i18next#1613]
## 🐛 Bug Report

I have empty reactjs project that was created without Creat-React-App and trying to setup i18next from this guide: 
https://react.i18next.com/latest/using-with-hooks but keys in t function are not working and in debug I see this message:
`i18next::translator: missingKey de translation test test`

## To Reproduce
You can clone my project from here: https://github.com/maxizhukov/book_frontend
t function is in src/components/views/HomePage.tsx
To see a this warning you need to run `npm install `=> `npm start` and open chrrome console

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```i18n.js
import i18n from "i18next"
import { initReactI18next } from "react-i18next"

import Backend from "i18next-http-backend"
import LanguageDetector from "i18next-browser-languagedetector"
// don't want to use this?
// have a look at the Quick start guide 
// for passing in lng and translations on init

i18n
	// learn more: https://github.com/i18next/i18next-http-backend
	.use(Backend)
	// detect user language
	// learn more: https://github.com/i18next/i18next-browser-languageDetector
	.use(LanguageDetector)
	// pass the i18n instance to react-i18next.
	.use(initReactI18next)
	// init i18next
	// for all options read: https://www.i18next.com/overview/configuration-options
	.init({
		fallbackLng: "en",
		debug: true,

		interpolation: {
			escapeValue: false, // not needed for react as it escapes by default
		}
	})


export default i18n

```

index.js
```
import React, {Suspense} from "react"
import ReactDOM from "react-dom"
import App from "./app"
import "./i18n"

ReactDOM.render(
	<Suspense fallback={<h1>Loading</h1>}>
		<App />
	</Suspense>, document.querySelector("#root"))
```

## Your Environment

```
"i18next": "^20.2.4",
"i18next-browser-languagedetector": "^6.1.1",
"i18next-http-backend": "^1.2.4",
"react-i18next": "^11.8.15"
```

**Comment by adrai** [comment]
afk at the moment, check the i18next debug log...
What is the output before and after that "i18next::translator: missingKey de translation test test"?

**Comment by adrai** [comment]
Run your example, I saw: 
![image](https://user-images.githubusercontent.com/1086194/119016139-e51dc380-b999-11eb-83ae-25dd24badff6.png)

So this seems not to be an i18next issue, but your webpack config issue.

This means your public locales are not part of the webpack-devserver
Adding this to your config works.
![image](https://user-images.githubusercontent.com/1086194/119016190-f6ff6680-b999-11eb-9f79-027ffd08e029.png)
