### ISSUE TITLE
Number in context is ignored/not working

### ISSUE THREAD

**Issue by pomali** [i18next/i18next#1622]
## 🐛 Bug Report

Using number as context is same as using empty/missing context. 
It fails silently. I found no mention about this in docs, and is quite unexpected.

## To Reproduce

https://codesandbox.io/s/determined-dream-2n583?file=/src/index.js

```js
// init resources.translation:
{
      issueType: "issue",
      issueType_1: "bug"
}
```
...
```js
[
      i18n.t("issueType"),                  // "issue"
      i18n.t("issueType", { context: 1 }),  // "issue"
      i18n.t("issueType", { context: "1" }) // "bug"
]
```

## Expected behavior

Not being able to use numbers as context could be intended, but current behavior is not up with my expectations.

Sensible alternatives:
- More visible failure (log in debug mode/throw error/..)
- Document behavior in docs (https://www.i18next.com/translation-function/context)
- Stringify numbers (or at least integers)

## Your Environment

- *runtime version*: Chrome 91
- *i18next version*: 20.2.2,
- *os*: Mac

**Comment by adrai** [comment]
never used context as number, but with v20.3.2 it works now ;-)

**Comment by pomali** [comment]
Wow, that was fast! Thanks :)

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
