### ISSUE TITLE
Translations and Formatting using different locales

### ISSUE THREAD

**Issue by badsyntax** [i18next/i18next#1631]
## 🚀 Feature Proposal

I'd like i18next to support different locales/languages for translations and formatting. At the moment translations and formatting are tied to the same locale. 

## Motivation

I have a use case where I want my translations in one locale, and I want numbers and dates formatted using a different locale. 

For example, a Spanish speaking South American, living and working in the US, wants to read text in Spanish (`es-MX`) but wants to see numbers and dates in (`en-US`). This is a use case I need to support in my app.

At the moment I need to shoehorn this extra locale into my formatter function, but it's not as convenient as `i18next.changeLanguage()`.

## Example

The API change is not clear as it seems i18next is built with the assumption only 1 locale will be used for both translations and formatting.

**Comment by jamuhl** [comment]
You have full control over formatting: https://www.i18next.com/translation-function/formatting#basic -> means while the language is es-MX your formatting function can still show formats for en-US

**Comment by badsyntax** [comment]
Yep, as mentioned in the issue I already do that, but it just doesn't feel right to manage the state for the extra locale outside of i18next. But it's not a problem really, I just thought maybe i18next could support this use case better.

**Comment by jamuhl** [comment]
Not sure how we should support that better -> we could not do more than store another language on i18next.lngUsedForFormatting and pass that to the format function -> but that does not bring any real benefit...or not sure what ideas you got to improve that?

**Comment by badsyntax** [comment]
I don't really have any better idea's tbh, but storing `i18next.lngUsedForFormatting` would bring real benefit in that this value is managed by i18next, so instead of me doing:

```js
interpolation: {
  escapeValue: false,
  format: (value, formatStr, languageLocale, opts) => {
    const formattingLocale = getFormattingLocaleFromSomewhere();
    return format(value, formatStr, languageLocale, formattingLocale, opts);
  },
},
```

.. it would be:

```js
interpolation: {
  escapeValue: false, 
  format: (value, formatStr, languageLocale, formattingLocale, opts) => {
    return format(value, formatStr, languageLocale, formattingLocale, opts);
  },
},
```

.. and to update i would just do `i18n.changeFormattingLanguage(lang);`. 

But I totally see it's probably not worth making this change because it would potentially break existing apis and bring little benefit to others (but I am curious if this has been brought up before as it seems like a fairly common use case). 

Thank you for the discussion, please feel free to close.

**Comment by jamuhl** [comment]
Not sure if it's a use case that is often needed -> my guess is most formatting depends less on the language than on the country code at least for currencies - hard to tell - guess having that function gives enough flexibility.

**Comment by badsyntax** [comment]
It's great that i18next is flexible enough to support this use case (even though it's not "baked in"). I will close. Thanks again for the discussion!
