### ISSUE TITLE
getBestMatchFromCodes: is it possible to select a dialect before jumping to the next language?

### ISSUE THREAD

**Issue by igorsantos07** [i18next/i18next#1632]
## 🚀 Feature Proposal

The behavior I was trying to achieve is as follows:
- available locales: pt-BR, en-US
- fallback: false (natLang keys)
- user browser requests: pt-PT, en
- user gets: pt-BR

But what actually happens: they get en-US (because en is their second language option).

I think it would make sense to look sideways before jumping into the next language (a similar dialect should be more intelligible than the second language option, which might very well be a fallback, if any).

I tried to implement this using a function for `fallbackLng`, but then I noticed it only gets called if _nothing_ useful is found before looping through the language options, so that function is almost worthless - unless I list _all_ dialects I can think of in `supportedLngs`, what's suboptimal, to say the least haha

I see there's no way to override `getBestBatchFromCodes()`... Any sense if it could be overridden? Or maybe add another option, say `tryDialects`? I think I could implement the latter.

------------

Bonus: I'm not sure I got what `load: all` and `nonExplicitSupportedLngs: true` do, from reading the docs. Would you care to explain? Then I can PR clearer docs for these.
It seems `load: all` is sort of a format standardizer, so it ignores pure languages if `currentOnly`, strips dialects if `languagueOnly`, or accepts any, and _then_ verifies if what's left is in the supported array. Right?

**Comment by jamuhl** [comment]
sideway fallback can be done using an object as fallback language -> https://www.i18next.com/principles/fallback#fallback-language

regular option is to provide `pt` as a fallback for all protuguese variants -> https://www.i18next.com/principles/fallback#locals-resolving

**Comment by jamuhl** [comment]
nonExplicitSupportedLngs -> your supported languages contains eg `en` -> the supported check also pass for all variants lie `en-US`, `en-GB`

load: all -> load all languages that are in the resolve hierarchies eg. for  `en-US` -> [`en-US`, `en`, `fallback`] (language only would only load `en` for detected `en-US` while currentOnly would only load what was detected)

**Comment by igorsantos07** [comment]
Ok, cool! I got now that the default strategy is to write the generic language and be more specific on variants.

Question: what it does if a key is not found on complex tags such as `zh-Hans-HK`? Would it look first for `zh-Hans` or jump directly to `zh`?

**Comment by igorsantos07** [comment]
Also, is there any reason for some pages to have the same h1 and h2 titles, but no other h2? Can I drop the solo h2 and move all h3 up?

**Comment by igorsantos07** [comment]
While I'm updating the config docs: where are the docs for the `cache` option? It says "check docs of plugin" but there's no cache section in the plugins page - only cache references in the backend section... What should I link to?

**Comment by jamuhl** [comment]
caching is solved in backends...using https://github.com/i18next/i18next-chained-backend and eg. a localStorage backend
