### ISSUE TITLE
Cache/memoize fallbackLng calls

### ISSUE THREAD

**Issue by igorsantos07** [i18next/i18next#1633]
## 🚀 Feature Proposal

`fallbackLng`, when a function, is called for _each_ missing key. This could be expensive, but mainly, verbose if anything is logged from that function.

## Motivation

It's a very simple function, with a single argument (the user language), so this should be fairly simple with an internal, in-memory array?

I may be able to implement it, if feedback is positive.

**Comment by jamuhl** [comment]
Not sure what you like to achieve? changing fallbackLng to an optional function would have a large impact on plugins too - and why would you call it in the missing...?!?

**Comment by igorsantos07** [comment]
I just tried to improve on the example from the docs (the last one in [this](https://www.i18next.com/principles/fallback#fallback-to-different-languages) code block), and noticed that behavior: it _does_ get called for every missing key, which could be all keys if you're using natLang and is in the default language.

Since its only input is the current language code, it's easily memoizable.

**Comment by igorsantos07** [comment]
Here's a [codesandbox](https://codesandbox.io/s/thirsty-dew-f8z8v) which shows the behavior I'm mentioning.

**Comment by jamuhl** [comment]
Wasn't even aware we added the option to have the fallbackLng as function...not sure but if the operations inside the passed in fallbackLng function is expensive...memoizing can be isolated in that function itself - nothing i18next has to do (in my opinion - @adrai what you think?)

**Comment by adrai** [comment]
We may need to ask @markdon

**Comment by igorsantos07** [comment]
In my view, there's no reason to leave optimization to the implementer on such a pure function. If you can save performance there, just do it, the implementer will be grateful for not having to think about it. I just noticed because, during implementation, I added some logging, and it simply spammed my console.

**Comment by adrai** [comment]
> In my view, there's no reason to leave optimization to the implementer on such a pure function. If you can save performance there, just do it, the implementer will be grateful for not having to think about it. I just noticed because, during implementation, I added some logging, and it simply spammed my console.

Just wanted to wait for the feedback of @markdon

**Comment by jamuhl** [comment]
Closing now. That function has (as long not console log) - zero performance impact - beside it's in 99% not used as a function. So - yes - can be added on implementation side if needed (but as the function is not async anyway there can't be any expensive operations)

**Comment by markdon** [comment]
> We may need to ask @markdon #1506

Sorry, I've been on holidays. I agree with the maintainers. This function is expected to be computationally trivial. It seems fair to leave this for such a tiny optimisation.

If someone were to look in to optimising this, it might be better to look [higher up the call stack](https://github.com/i18next/i18next/blob/b3f9d4aaa1e0d1e4ab2006402b37c37406bda53a/src/LanguageUtils.js#L120) to see why those functions are being called on every missing string.
