### ISSUE TITLE
Add option to avoid logging missingKey/updateKey(?)

### ISSUE THREAD

**Issue by igorsantos07** [i18next/i18next#1634]
## 🚀 Feature Proposal

Create an extra `logMissingKey` option that skips the current log call when a key is not found, resorting to fallback.

## Motivation

This is quite spammy when you use natLang keys (instead of using computer keys and falling back to a lang file).

I can implement it, if the feedback is positive :)

**Comment by jamuhl** [comment]
In the past there was only a log output if there was saveMissing=false or there was no user-defined missing function...so adding a flag looks good to me...

**Comment by adrai** [comment]
`debug=false` should not log anything

**Comment by igorsantos07** [comment]
@adrai so if the dev is using natLang keys they cannot debug the project, unless they deal with the never-ending list of keys? I mentioned this case specifically in the issue body...

**Comment by jamuhl** [comment]
I don't get why should there be a difference for keys in form `some.key` vs `some natural key`?!

**Comment by adrai** [comment]
> @adrai so if the dev is using natLang keys they cannot debug the project, unless they deal with the never-ending list of keys? I mentioned this case specifically in the issue body... 

Maybe we simply don't understand what you mean...
Can you provide an example?

**Comment by adrai** [comment]
The only way I could reproduce that many log statements is by not having any resources at all in the fallbackLng and having the debug flag set to true:
![image](https://user-images.githubusercontent.com/1086194/131217543-ba0fcd9f-9938-4c1d-b3d5-e7e26e03968e.png)

**Comment by igorsantos07** [comment]
Yep! That's it.

I come from a gettext background (where usually natLang keys are favored) and it really makes no sense to have a redundant translation file, where keys and values are the same.

**Comment by adrai** [comment]
For me ok, to omit the log if saveMissing is not true

**Comment by adrai** [comment]
@igorsantos07 would this be ok for you? https://github.com/i18next/i18next/pull/1646
