### ISSUE TITLE
missingKeyHandler lacks the "context"

### ISSUE THREAD

**Issue by igorsantos07** [i18next/i18next#1636]
## 🚀 Feature Proposal

Add a `context` param to `missingKeyHandler` signature.

## Motivation

The context is also part of what's needed to write a translation, right?

## Example

See this [codesandbox](https://codesandbox.io/s/thirsty-dew-f8z8v) to see how it happens.

**Comment by igorsantos07** [comment]
Actually, while I was writing this I decided to check if there were any other hidden arguments in that function... Turns out the 6th arg is an object that seems to be all the options passed to `t()`. Is it safe to use that argument? Should I add it to official docs? 

Even with it, I feel like the context should be either part of the key, or the "main arguments" (like `ns` is), but I understand it would be a breaking change.

**Comment by adrai** [comment]
Yes, these are the options and they can be used: https://github.com/i18next/i18next/blob/master/src/Translator.js#L237
I think they simply got missed in the docs... right @jamuhl ?

**Comment by jamuhl** [comment]
Can be added...99.9% of cases just don't need that 6th param

**Comment by adrai** [comment]
done

**Comment by igorsantos07** [comment]
@adrai that's actually wrong, options are the 6th argument, as I mentioned in my comment. Also, that doesn't make it clear the context is in there. Would be better to leave it explicit in the description.

**Comment by adrai** [comment]
Sorry, didn't check it twice...
![image](https://user-images.githubusercontent.com/1086194/128591210-ccbd920e-0f1e-4e06-aa5b-ae4919ce8657.png)
