### ISSUE TITLE
It seems by default i18n falls back to the translation key if no translation was found in Remote URL which i passed using HTTPBackend loadpath for the key, e.g. // No translation defined for bill_type_blank yet i18next.t('bill_type_blank') // Returns 'bill_type_blank' If no translation is found for the key on Remote LoadPath, I would prefer to fetch that same key from locales path "locales/{{lng}}/translation.json". i am already using ChainedBackend for network fallback i want the same for key fallback, How can I achieve something like this using the i18next library?

### ISSUE THREAD

**Issue by sanjaysinghal7** [i18next/i18next#1638]
## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by jamuhl** [comment]
backends only load...you will have to build a backend merging your sources

**Comment by sanjaysinghal7** [comment]
Sorry i am not able to understand what u r saying, all i want is when key is not available in remote URL its should fetch the key from locales path, below i m sending my i18 code which is working for network fallback

import i18n from "i18next";
import ChainedBackend from "i18next-chained-backend";
import HttpBackend from "i18next-http-backend";
import resourcesToBackend from "i18next-resources-to-backend";
import { initReactI18next } from "react-i18next";
import translationEng from "./locales/en/translation.json";

const bundledResources = {
  en: {
    translation: translationEng,
  }
};
i18n
  .use(initReactI18next)
  .use(ChainedBackend)
  .init({
    fallbackLng: "en",
    saveMissing: true, // Must be set to true
    parseMissingKeyHandler: (key: string) => {
      return `No translation found for "${key}"`;
    },
    // ... your i18next config
    backend: {
      backends: [HttpBackend, resourcesToBackend(bundledResources)],
      backendOptions: [
        {
          loadPath:"https://testURL.com/api/en.json";
          },
        },
      ],
    },
  });
export default i18n;

**Comment by jamuhl** [comment]
like said...backend loads a complete namespace -> so fallback in chained backend is only for a complete loadPath not for individual keys -> only option you got is creating a backend that loads both files and merges them

**Comment by sanjaysinghal7** [comment]
how to create a backend in this i18next framework?? if possible for u can u please give an example how i can achieve this?

**Comment by jamuhl** [comment]
https://www.i18next.com/misc/creating-own-plugins#backend

**Comment by sanjaysinghal7** [comment]
Hey @jamuhl  when i m trying to create a small own plugin i m facing this problem in my i18 file while using .use(myPluggin),
 Argument of type '{ type: string; name: string; process: (key: any) => void; }' is not assignable to parameter of type 'Module | ThirdPartyModule[] | Newable<ThirdPartyModule>[] | Newable<Module>'.
  Type '{ type: string; name: string; process: (key: any) => void; }' is not assignable to type 'Module'.  
     Types of property 'type' are incompatible.
      Type 'string' is not assignable to type '"postProcessor" | "3rdParty" | "backend" | "logger" | "languageDetector" | "i18nFormat"'.  TS2345
      .use(initReactI18next)
      .use(ChainedBackend)
   .use(atTrimmer)

**Comment by pedrodurek** [comment]
Hey @sanjaysinghal7, try to assert your plugin's type using `as const` to get the literal type, not a string.
```ts
const type = '3rdParty' as const;
```

**Comment by sanjaysinghal7** [comment]
hey @pedrodurek @jamuhl there are a lot of methods in new own plugin, like
  init: function() {
    /* use services and options */
  },
  read: function() {
    /* return resources */
    /* if method fails/returns an error, call this: */
    /* callback(truthyValue, null); */
  },
  // optional
  readMulti: function() {
    /* return multiple resources - useful eg. for bundling loading in one xhr request */
    /* if method fails/returns an error, call this: */
    /* callback(truthyValue, null); */
  },
  // only used in backends acting as cache layer
  save: function() {
    // store the translations
  },
  create: function() {
    /* save the missing translation */
  },
  
  where we have to put our logic for loading both files and merge them because i tried to console something in init method but its not showing in console. please suggest

**Comment by jamuhl** [comment]
`read` is the function that gets called for one namespace-lng pair -> load both there and merge -> return the merged result

**Comment by sanjaysinghal7** [comment]
@jamuhl in what format i have to send the merged result and how to read this in i18 file, if u can send me a working example it will be really helpful because i am using i18n very first time.

**Comment by jamuhl** [comment]
for the read function -> same as the JSON you delivered unmerged: https://www.i18next.com/misc/json-format#i-18-next-json-v3

**Comment by sanjaysinghal7** [comment]
@jamuhl i m not sure how to achieve this because things are already there in i18n file then how i can send this merged json from custom plugin and i18n will read this??

my own custom backend plugin file looks like this, can u please tell me where and how to send this merged data and read in i18n file??

import translationEng from "../locales/en/translation.json";
let b = {};
const plugin = {
  type: "backend" as const,
  init: function() {
    /* use services and options */
  },
  read: function() {
    fetch(
      "https://testURL.com/api/en.json",
    )
      .then(response => response.json())
      .then(jsonData => {
        // jsonData is parsed json object received from url
        console.log(jsonData);
        b = jsonData;
        const a = translationEng;
        const c = Object.assign(a, b);
        console.log(c);
      })
      .catch(error => {
        // handle your errors here
        console.error(error);
      });
    /* return resources */
    /* if method fails/returns an error, call this: */
    /* callback(truthyValue, null); */
  },
};
export default plugin;

**Comment by jamuhl** [comment]
it says:

```js
  read: function(language, namespace, callback) {
    /* return resources */
    callback(null, {
      key: 'value'
    });

    /* if method fails/returns an error, call this: */
    /* callback(truthyValue, null); */
  },
```

on success just call the callback with first param null and second the translations, on error just return true in the first param

**Comment by sanjaysinghal7** [comment]
Hey if key is not available its still not fetching data from returned merged json, and only showing key name.. am i missing something in both files or did i misconfigured something in i18n??

**i18n file** 
backend: {
      backends: [HttpBackend, backend],
      backendOptions: [
        {
          loadPath: () => {
            const a = true;
            return a
              ? "https://testURL.com/api/en.json"
              : "./locales/{{lng}}/translation.json";
          },
        },
      ],
    },
    
    
    **and in custom plugin file** 
    read: function(language: any, namespace: any, callback: any) {
    fetch(
      "https://testURL.com/api/en.json",
    )
      .then(response => response.json())
      .then(jsonData => {
        // jsonData is parsed json object received from url
        console.log(jsonData);
        b = jsonData;
        const a = translationEng;
        const c = Object.assign(a, b);
        console.log(c);
        callback(null, {
          c,
        });
      })
      .catch(error => {
        // handle your errors here
        console.error(error);
        callback(true, null);
      });

**Comment by jamuhl** [comment]
like said before using the chained-backend it uses resources from first backend if the namespace exists...don't use chained backend with your own backend that does merging

**Comment by sanjaysinghal7** [comment]
so if i will not use chained-backend then how i will be able to handle file level or network level fallback?? also HttpBackend from "i18next-http-backend" is the first parameter in backends: [HttpBackend, myplugin] option, do i need to remove this as well because it read very first from remote URL?

**Comment by jamuhl** [comment]
either you have incomplete JSON files you need to merge - or you like to have fallbacks where you take care the fallback loading has all translations...not both...

chained-backend fallback loading -> complete JSON files load fallback if **file** does not exist
your merge backend -> load two incomplete JSON files and merge them to get one complete

So if I see it right you like a fallback -> BUT: you can only have that on file level not on per key ----> make sure you update both sources regulary

**Comment by sanjaysinghal7** [comment]
Yes u got my point...
i have locale resource .json files in my project very first time when application loads i translate keys from there and parallely i want to make a call to remote json API URL, once it will download in browser i want to translate the keys from that Remote URL everytime now on words. 
IN this i want to achieve two things
1) File/Network level fallback, if remote Json URL not working fetch from locals resources.
2) If key not available in remote URL then also check local resources key first.

now can u please suggest me which approach i should follow to achieve these things using i18n.
if possible can u please share working example or example code that will be very helpful for me because i m using i18 first time and i really appreciate that u r helping and guiding me.

**Comment by jamuhl** [comment]
you can't and it makes no sense...what you like is two directional fallback...that is not needed in real world...

your one source is remote -> that gets all new keys, all updated translations
local is only a regular copy of the remote

there is no way the local resources can be more uptodate than remote -> there can't be a key in local that is not on remote

your local resources just act as a fallback (you do neither add keys there nor add translations - just copy from remote)...just update those regularly...POINT

**Comment by jamuhl** [comment]
there is a full sample on locize: https://docs.locize.com/more/backend-fallback

**Comment by sanjaysinghal7** [comment]
@jamuhl agree with your valuable point, is this possible if i used two locales translations instead fetching from remote, 
one directory will be latest one and one is old one, then will it be possible to achieve this that first it will check key in latest local directory if key not found it fetch from old directory. is their any way we can achieve this?

**Comment by jamuhl** [comment]
no...it's impossible done right. the `t` function returns its result synchronous - while loading is always done async (so you can't load async in sync function)

Having both old and new local -> you can use your merge backend and merge the two sources again -> there is no need for fallback one to the other (as both are from same source "local")

**Comment by sanjaysinghal7** [comment]
can't we use Namespace fallback
i18next by default loads its translations from one file named translation. However, you can configure it to load from multiple files, called namespaces.
Besides defining multiple namespaces to load from, you also can set fallback namespaces. Thus, if a key to translate isn't found in the given namespace, it will look it up in the indicated fallbacks. we can try to achieve this.

**Comment by jamuhl** [comment]
yes...that works...just names of namespaces need to be different

**Comment by jamuhl** [comment]
but again...I don't understand really why you're organisation is unable to have consistent up-to-date translations. Looks like you try to solve an organisational problem using code...instead of solving your localisation process problem
