### ISSUE TITLE
Performance issues when using t function on heavy file

### ISSUE THREAD

**Issue by Richacinas** [i18next/i18next#1639]
## 🐛 Bug Report

When doing performance benchmarks on Chrome Developer Tools, I can see that most of the scripting time of my app is going to the t function.

Our translation file weighs 1.7mb.

Every access to it through the mentioned function, is taking a long time, especially when we are accessing big parts of this file (let's say, 2000 lines)

![Captura de pantalla de 2021-08-11 14-32-09](https://user-images.githubusercontent.com/7046504/129029159-9eb4682f-bcc6-4dbc-9eca-c0d3472c5c9c.png)

## To Reproduce

Check console on this example (75 milliseconds to run t function):

https://codesandbox.io/s/react-boilerplate-forked-ovq6g

## Expected behavior

I would expect this library to be much faster.

At least, I would expect that this would happen only on the first access using the t function, however, it happens every time our app is using it, so that means there is not any sort of inner caching or easy way of accessing the translations. If I only do one access to a big part of our translations using this library and then I use plain JS to access to parts of the returned object, the times decrease from 3 digits milliseconds to only 1 millisecond.

## Your Environment

- *runtime version*: Node 14.15.0, Chrome browser, React 16.8.
- *i18next version*: 17.2.0
- *os*: Ubuntu 28.04LTS
- Using this library along with react-18next.

**Comment by jamuhl** [comment]
Your accessing a large object - accessing a single string -> https://codesandbox.io/s/react-boilerplate-forked-ro23z -> 0.6ms

Your accessing an object -> every translation below that object gets run through `t` doing interpolation and other stuff -> set debug true and you see there are a lot of warnings that there are missing interpolation values....

**Comment by Richacinas** [comment]
Thanks a lot for your answer.

I already guessed/tried that, however, our app is really large and you can imagine that we need to access to plenty of elements inside (in this case) `t('clientes.Empresa')`.

Do you mean that we could keep this way of doing things if we fix those interpolation values or warnings?

**Comment by Richacinas** [comment]
I understand... there is no way we can provide all those values for this interpolations to work, because many of them wouldn't be used in, let's say, `Component`. So probably the way to go is doing specific access to small parts of the translation file, as you say, right?

**Comment by jamuhl** [comment]
no...the correct way is using `t` for each key (does not hurt your performance)...not returning objects and access substrings...(that option is more or less only for passing translations to component libs)

**Comment by Richacinas** [comment]
Alright. Thank you very much for your help, it was a mistake on our end then.

Let's see how painful it is for us now to change the way we access translations on the whole app.

Closing issue...
