### ISSUE TITLE
[RFC] Deep keys : allow parent key as a viable key (ie. accept `foo` even if `foo.bar` is defined)

### ISSUE THREAD

**Issue by jdeniau** [i18next/i18next#1641]
## 🚀 Feature Proposal

Actually, we can not use a key that have a "child", ie. if I have a key named `foo.bar`, I can not use a key named `foo`.
The proposition is to allow that

### Personal motivation 

My personal motivation is that I come from Symfony, that allow this, and I use the "parent" key as a main key: 

- "foo": "Foo"
- "foo.search": "Search the Foo"
- "foo.search.description": "This is where we will search the Foo"

### Global motivation

My personal motivation can be fixed by either renaming my keys (which I'm doing), or by using the `returnedObjectHandler` function, but I think this is useful to allow this comportment for two reason:

- I think this issue comes from a technical problem (we can now have two keys named `foo` in JSON)
- I think this allow more robust and evolutive translations : if we have a `foo` key for a long time, but we want to add another key that will be a helper for foo, we can not create the logical `foo.help`, but we will need to use another "parent" like `foo_.help`

## Possible solution

We could use an empty string in the object to allow this comportment:

```json
{
  "foo": {
    "": "Foo",
    "help": "Foo helper text"
  }
}
```

### Plural

I think the plural variations will be built-in once the main feature is implemented:

```json
{
  "foo": {
    "": "Foo",
    "_0": "No foo",
    "_plural": "Some foos",
    "help": "Foo helper text"
  }
}
```

There is a tiny breaking change that I see for plurals if you have a key named `foo._plural` but I don't think this is really an issue (or at least not more that the issue with the plural keys).

**Comment by jamuhl** [comment]
Guess the best option would be to use JSON flat format in this cases.

The problem I see is `t('foo')` suddenly has to look if it is an object containing an empty string which leads to some hacky workaround done here: https://github.com/i18next/i18next/blob/master/src/Translator.js#L130 which has the drawback of not properly fallback in case the emptystring object does not exist.

Beside that - how does it act on returnObjects is enabled? Return the string or the object?!?

**Comment by jdeniau** [comment]
For me the implementation should do the same as if you call a complete key. ie. calling `foo` is the same as calling `foo.` (which does work)

If returnObjects is enabled, I would return the string, like the translator would do. 
I understand that you would not be able to get the object in that specific case, but my knowledge on i18next is still small, and I don't know the real purpose of `returnObjects`.
