### ISSUE TITLE
t.push is not a function

### ISSUE THREAD

**Issue by developdeez** [i18next/i18next#1642]
Got this when trying to show a translation in a react-toastify popup.

t.push is not a function. (In 't.push("/")', 't.push' is undefined)

Not sure why it says that
 "react-i18next": "^11.8.15",
Mozilla/5.0 (iPhone; CPU iPhone OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/92.0.4515.90 Mobile/15E148 Safari/604.1

` const { t, ready } = useTranslation('modals');
messageAdmin()
      .then(async ({ data }) => {
          if (data.messageAdmin) {
            if (ready) {
            toast.success(t('common:msgsent'));
            }.....
`

**Comment by jamuhl** [comment]
looks more like a function call to some browser.history on a minified javascript file

**Comment by developdeez** [comment]
Ok thanks Sent from Mail for Windows From: Jan MühlemannSent: Monday, August 30, 2021 10:19 PMTo: i18next/i18nextCc: developdeez; AuthorSubject: Re: [i18next/i18next] t.push is not a function (#1642) looks more like a function call to some browser.history on a minified javascript file—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
