### ISSUE TITLE
HTML tags escaping 

### ISSUE THREAD

**Issue by irangarcia** [i18next/i18next#1643]
## 🐛 Bug Report

HTML tag closing alone. I need to use a HTML tag as a child of a translation to use in a `code` tag

## To Reproduce

I couldn't reproduce the exact behavior, but it's almost like in the [CodeSandbox](https://codesandbox.io/s/react-i18next-mvlru?file=/src/app.js)
The only difference is that the Sandbox is closing just after the opening tag, and in my application, it's closing after all the text (image)
![Screenshot from 2021-08-30 23-55-58](https://user-images.githubusercontent.com/60601780/131434285-de497e3d-260b-43b5-bd31-cebd3f4b2b29.png)

The translation it's being used in this way:
```jsx
// i18n.js
en: {
  translations: {
    welcome: "Paste the script in the <0><head></0> of your website"
  }
}

// App.js
<Trans i18nKey="welcome">
    <code style={{ backgroundColor: "tomato" }} />
</Trans>
```

## Expected behavior

I need that the tag doesn't close and stay alone inside the `code`

Ex.:
Paste the script in the `<head>` of your website

## Your Environment

- *runtime version*: 14.17.5
- *i18next version*: i.e. 19.6.0
- *os*: Linux

**Comment by jamuhl** [comment]
That's caused by the html parser which parses the translation string. `<head>` is parsed but can not be closed properly

changing `<0><head></0>` to `<0><head /></0>` might be a alternative

**Comment by marcospassos** [comment]
Isn't it supposed to be escaped? If not, is there any way of explicitly escaping it?

**Comment by jamuhl** [comment]
nothing todo with escaping...it's html parsable

**Comment by marcospassos** [comment]
So, how can someone translate something that contains a literal HTML tag?

**Comment by jamuhl** [comment]
Eg. with this workaround:

```js
import React from "react";
import { Trans } from "react-i18next";

const TheCode = ({ tag }) => (
  <code style={{ backgroundColor: "tomato" }}>{`<${tag}>`}</code>
);

export default function App() {
  return (
    <div className="App">
      <h2>
        <Trans i18nKey="welcome">
          <TheCode tag="html" />
        </Trans>
      </h2>
    </div>
  );
}
```
