### ISSUE TITLE
hello can someone help me to solve that i'm so sorry cuz i put that on Documentation issue but i don't know where can i put 

### ISSUE THREAD

**Issue by Shrooomye** [i18next/i18next#1645]
error unable to parse locales from file (maybe /home/runner/evobot/locales/en.json is empty or invalid json?): 

i want to create a discord bot and every time when i start all my commands are changed from

![image](https://user-images.githubusercontent.com/89937341/131773587-0bd00d3f-49ba-4bea-b132-f73a5ae2a9c0.png)

}
  
To 

![image](https://user-images.githubusercontent.com/89937341/131773639-5c54c55a-d485-4449-8ecf-d5c2bf774f2d.png)

**Comment by adrai** [comment]
Can you please paste your original json file?

**Comment by adrai** [comment]
Your json file is not correct means, you have a "}" missing => just fix it.

**Comment by Shrooomye** [comment]
rlly, this is the all what can i do for fix the json that already was an "}" at the end and every time I wanted to start it gave an error with "{"

**Comment by Shrooomye** [comment]
look at this 

![image](https://user-images.githubusercontent.com/89937341/131854192-79a0f1d3-6b07-4044-a924-ec623d4ed37a.png)

**Comment by adrai** [comment]
remove the last comma
![image](https://user-images.githubusercontent.com/1086194/131854908-fdde6381-dd2d-43f9-9dde-894de2dbe3d6.jpeg)

**Comment by Shrooomye** [comment]
Finally now it's fine thank you for support i'm new in stuff with appointement bots

![image](https://user-images.githubusercontent.com/89937341/131856061-c545dd1a-0185-4a9e-a279-d3205e8abbb0.png)
