### ISSUE TITLE
Plural forms inaccuracy

### ISSUE THREAD

**Issue by Elindorath** [i18next/i18next#1647]
## 🐛 Bug Report

During the process of translating my application into Polish, I noticed that the Polish plural forms seem incomplete: "1.5 months" should be translated "1.5 miesiąca", not "1.5 miesiące" as it is currently.
Looking into the code, based on [this comment](https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L3), I saw that i18next use Translate House's solution. And indeed, they only support basic plural forms, considering only the integer part of the evaluated quantity.

## To Reproduce

Here is a basic [JSFiddle](https://jsfiddle.net/2s7abn0y/20/) to illustrate

## Expected behavior

i18next should be able to handle more complex scenarios regarding plural forms. The [CLDR (Common Locale Data Repository)](https://github.com/unicode-org/cldr), edited by the Unicode Consortium, seems to me to be a better approach, based on a real standard used by the majority of tools in the ecosystem, and with the assurance of its good maintenance over time (at the time of writing, [Translate House's plural forms](https://github.com/translate/l10n-guide/blob/master/docs/l10n/pluralforms.rst) are 5 years old, [Unicode's one](https://github.com/unicode-org/cldr/blob/master/common/supplemental/plurals.xml) are only 27 days old).
See how they handle [Croatian](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html#hr) or [Filipino](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html#fil) plural forms.
They maintain [this repo](https://github.com/unicode-org/cldr-json) that contains all data in JSON format, which could simplify the automatic generation of the js file.
I came across [this repo](https://github.com/nodeca/plurals-cldr) that does exactly that. I don't know if it is usable as it is, but it could serve as an example.

## Your Environment

- *runtime version*: node v14
- *i18next version*: 20.6.1
- *os*: Mac

**Comment by jamuhl** [comment]
If changing the plural handling I would go for https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules (using browsers built in forms or let devs us Intl API polyfills where needed)

For being backward compatible this would need to be something users can choose for now (old standard could be removed at some later stage) -> going for a JSON v4 (https://www.i18next.com/misc/json-format) as default with the new plural options: https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L142

**Comment by Elindorath** [comment]
I hadn't thought of the `Intl` API to fix this but since it's built on the CLDR it seems like the best option.

I am not sure why you would need a JSON v4 though.
Do you mean a format directly using plural tags like in the following example (matching the v3)?
```json
{
  "key": "value",
  "keyDeep": {
    "inner": "value"
  },
  "keyNesting": "reuse $t(keyDeep.inner)",
  "keyInterpolate": "replace this {{value}}",
  "keyInterpolateUnescaped": "replace this {{- value}}",
  "keyInterpolateWithFormatting": "replace this {{value, format}}",
  "keyContext_male": "the male variant",
  "keyContext_female": "the female variant",
  "keyPluralSimple_one": "the singular",
  "keyPluralSimple_other": "the plural",
  "keyPluralMultipleEgArabic_zero": "the plural form 0",
  "keyPluralMultipleEgArabic_one": "the plural form 1",
  "keyPluralMultipleEgArabic_two": "the plural form 2",
  "keyPluralMultipleEgArabic_few": "the plural form 3",
  "keyPluralMultipleEgArabic_many": "the plural form 4",
  "keyPluralMultipleEgArabic_other": "the plural form 5",
  "keyWithArrayValue": ["multipe", "things"],
  "keyWithObjectValue": { "valueA": "return this with valueB", "valueB": "more text" }
}
```

**Comment by adrai** [comment]
v21.0.0 is released 🎉
Thank you @Elindorath for your awesome help.
