### ISSUE TITLE
Wrap the translation inside custom component like <span> and have it's id or any other attribute set as translation key

### ISSUE THREAD

**Issue by krjj** [i18next/i18next#1657]
## 🚀 Feature Proposal

Wrapping the translation inside `<span/>` or any other component having attribute id set as the translation key.

## Motivation

The id attribute of the wrapper can be used for finding exact translated element in the DOM. 

## Example

https://codesandbox.io/s/react-i18next-example-forked-j8fks?file=/src/Renderer.jsx

So, in the above example I created postprocess plugin to wrap `<span id=KEY>` around the translation text. It works but there still are a lot of edge cases where it fails to render the translation properly.

1. [Object object] is rendered if t() is called to assign the value of interpolation args.
2. Doesn't work with `<Trans/>` component.

Is there any way to accomplish this currently in a reliable way and set onClick or other handler for that wrapper.

**Comment by adrai** [comment]
I don't think this will be possible to achieve with a postProcessor.
IMO the only way to accomplish this, is via a babel macro or similar... but I'm really not an expert in this area.

**Comment by krjj** [comment]
@adrai Thanks for babel macro suggestion. I do have following question about the postProcessor.

1. Documentation for create own plugin (https://www.i18next.com/misc/creating-own-plugins) says `Post Processors are used to extend or manipulate the translated values before returning them in t function.`. How does this work for Post Processor triggered by `<Trans/>` component ?
2. Within the context of Post Processor, is there a way to detect how the post processor was triggered (i.e whether through t() or Trans). Assume the post processor was enabled globally via init options.
3. In the above example (https://codesandbox.io/s/react-i18next-example-forked-j8fks?file=/src/Renderer.jsx) (updated code) - I am returning React Element from the post processor. Looks like t function is able to parse the value returned by it (example 1 and 2 from the above codesandbox). Example 1 works partially and Example 2 works fully. Example 1 returns [Object object] because that is what reaches the post processor. Any t() return value that is passed as options and used in interpolation for t function is converted to [Object object].

**Comment by adrai** [comment]
interpolation and postprocessor etc... does not know about react at all...

and the problem of interpolation there is, it is handling everything as string...

that's why I was suggesting a solution outside of the i18next core... like with a babel macro or similar for react-i18next
