### ISSUE TITLE
Passing `ns` to config sets the `defaultNS` to the first item in the array

### ISSUE THREAD

**Issue by JCQuintas** [i18next/i18next#1658]
## 💥 Regression Report

Whenever you pass the `ns` option when initialising the `i18next` instance, it sets the `defaultNS` to the first item in the `ns` array. Which means `useTranslation()` without any namespace returns the wrong values. 

I'm using the React nomeclature here, but I'm fairly sure this issue is in the default package, since `react-i18next` didn't change, and you can see the `defaultNS` is set when using  the `debug` option.

## Last working version

Worked up to version: 20.6.1

Stopped working in version: 21.0.1

## To Reproduce

Check the sandbox, in the file `src/i18n.ts` we init the library, if we pass `ns` to it, the first item in the array will become the `defaultNS`.

https://codesandbox.io/s/i18next-cant-use-multiple-namespaces-r6li9

## Expected behavior

I was expecting the previous behaviour, where `ns` was not tied to `defaultNS`, if this is an intended change then it should be documented on docs and migration.

**Comment by adrai** [comment]
This was intended, but not aware of someone defining the default "translation" namespace in ns option but not in defaultNS option.
Should be fixed with v21.0.2

**Comment by jamuhl** [comment]
just to make it more clear:

- defautlNS -> is a global defaultNS (global pick in i18next.t if no namespace is provided in key or options)
- ns -> defines namespaces to load (or being loaded)
- the array of namespaces used in `useTranslations` -> defines needed namespaces before rendering and for convenience sets the first as default (using i18next.getFixedT)

**Comment by JCQuintas** [comment]
> This was intended, but not aware of someone defining the default "translation" namespace in ns option but not in defaultNS option.
> Should be fixed with v21.0.2

I'm not sure I understand your point. In my head the issue doesn't seem to be that `translation` is missing from `ns`, but that previously the code below kept the `defaultNS` as `translation`, but now it doesn't. It will change the `defaultNS` to the first item in the `ns` array.

```js
{
  resources: {
    en: { ns2, translation }
  },
  ns: ["ns2"],
}
```

If you check the example on codesanbox, version v21.0.2 didn't change anything

**Comment by jamuhl** [comment]
either don't set ns in i18n options, or set defaultNS too

**Comment by JCQuintas** [comment]
Ok, it feels like an odd behaviour. But if that is intended, then can we have it documented on the configuration options?

**Comment by jamuhl** [comment]
What is odd? You pass in a namespace array in options only containing `["ns2"]` why should the defaultNS keep a namespace you do not use based on your configuration?...(translation is not in your ns array)

**Comment by adrai** [comment]
https://www.i18next.com/misc/migration-guide#defaultns
![image](https://user-images.githubusercontent.com/1086194/134490114-4d5ce9c2-9b60-4835-89f3-45889337ba10.png)


https://www.i18next.com/overview/configuration-options#languages-namespaces-resources
![image](https://user-images.githubusercontent.com/1086194/134490084-9854f291-0274-471e-9d37-0e20bcf10ca3.png)

**Comment by JCQuintas** [comment]
> What is odd? You pass in a namespace array in options only containing ["ns2"] why should the defaultNS keep a namespace you do not use based on your configuration?...(translation is not in your ns array)

Mainly because you have two config variables that sort of interact with each other. It is not a big problem now it is documented though.

Previously you could use  the `translation` namespace without having to configure it, now you would need to if using the `ns` field. It is just something you need to be aware of when configuring your app.

**Comment by JCQuintas** [comment]
@adrai thanks, I think that makes things clearer in case someone falls on this. 👍
