### ISSUE TITLE
A new RTL support for a language - ckb

### ISSUE THREAD

**Issue by emresandikci** [i18next/i18next#1659]
## 🚀 Feature Proposal

A new RTL support for a language which is Central Kurdish, language code is `ckb`

## Motivation

Missing language RTL support

## Example

This feature is just for one more language RTL support, there will not be any new usage.

**Comment by jamuhl** [comment]
If you like you might create a PR -> https://github.com/i18next/i18next/blob/master/src/i18next.js#L451 ?

**Comment by emresandikci** [comment]
> If you like you might create a PR -> https://github.com/i18next/i18next/blob/master/src/i18next.js#L451 ?

https://github.com/i18next/i18next/pull/1660
