### ISSUE TITLE
i18next, Missingkey

### ISSUE THREAD

**Issue by Neba2262** [i18next/i18next#1664]
i18next::translator: missingKey en translation

The t function is not working it does not get the key from the transaltion.json hence it only outputs what is writtien in the '..'

## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

import i18n from 'i18next';
import {initReactI18next} from 'react-i18next';

import HttpApi from 'i18next-http-backend';
import LanguageDetector from 'i18next-browser-languagedetector';

i18n
.use(HttpApi)
.use(LanguageDetector)
.use(initReactI18next)

.init({
    supportedLngs:['en','amh'],

    fallbackLng:'en',
    debug: 'true',
    detection:{
        order:['cookie','localStroage','path','subdomain'],
        caches:['cookie'],
    }, 
    interpolation:{
        escapeValue:false,
    },
    backend: {
        loadPath: '../public/assets/locales{{lng}}/translation.json'
    }
});
export default i18n;
## Expected behavior

```so i expected the t function to get that id from the translation.json file and change the text
```

## Your Environment

- *runtime version*: i.e. node v14.17.1, deno, browser chrome
- *i18next version*: i.e. 19.5.3
- *os*: Windows
- *any other relevant information*

**Comment by jamuhl** [comment]
Did you check your browser's console log? Rather sure you get a warning for failing to load the translations

**Comment by Neba2262** [comment]
i did and its trows translator: missingKey en translation error

**Comment by Neba2262** [comment]
tho it tells me that i have changed languge but it has a missingKey

**Comment by jamuhl** [comment]
and somewhere above it tells you that backendConnector failed loading your translation.json for en

**Comment by Neba2262** [comment]
Ya

**Comment by jamuhl** [comment]
so you now know what you did wrong...your loadPath is wrong

**Comment by Neba2262** [comment]
Ya i saw that and changed it but seems to throw it agian

**Comment by jamuhl** [comment]
then you think it's right...but it's wrong...it does not lie...

rather sure it should be: `../assets/locales/{{lng}}/translation.json`

**Comment by adrai** [comment]
Please provide a reproducible example... can't help like that.
I suspect your hson translation files are not loaded (you should see this also in the network tab)

**Comment by jamuhl** [comment]
so either the JSON is malformed - or the path is returning something else because it is still wrong...nothing we can do to fix your issue in your code
