### ISSUE TITLE
Keys with space don't get translated with newest version

### ISSUE THREAD

**Issue by Linda-Andersson** [i18next/i18next#1665]
## 🐛 Bug Report

We did a update to the newest version, 21.1.1, of i18next from version "19.8.7". 
Then we saw that the translations that contains space did not work anymore. So we had to go back to 19.8.7 to get it working again. So we only saw the keys and no working translations for these keys.

## To Reproduce

Update i18next to the newest version, try with a key that have a space.
A example is that the key "technicalArea.Project shared" stopped working. 

```js
t("technicalArea.Project shared")
```

## Expected behavior

We expected the translations to still be working as before even if the key contains space.
So that it gets translated to Project shared and not show the key "technicalArea.Project shared".

```js
<p>Project shared</p>
```

## Your Environment

- *runtime version*: i.e. node v14.15.1,, browser chrome
- *i18next version*: i.e. 19.8.7
- *os*: Windows

**Comment by adrai** [comment]
Can you please share a more detailed example, this seems to have been fixed in v21.1.1
https://github.com/i18next/i18next/issues/1661

**Comment by Linda-Andersson** [comment]
Thank you for the fast answer @adrai ! 
Sorry for the bad example, first time I'm writing one of these. 
But It seems like it's working now. Might have been something strange in the branch I was working in before. I tried now on our main branch and update again to 21.1.1 and it seems to be working as it should 😄

**Comment by adrai** [comment]
thank you for checking again

**Comment by Alex-Spike** [comment]
@adrai Thanks for answer.
i18next version: 21.2.4
In my case I don't need `keySeparator` I need `nsSeparator` and in this case it doesn't work.
Also in my case - `test` is namespace. And I want to take translation from this NS like:
```<Trans i18nKey="test:test welcome with space">trans</Trans>```

**Comment by adrai** [comment]
> @adrai Thanks for answer. i18next version: 21.2.4 In my case I don't need `keySeparator` I need `nsSeparator` and in this case it doesn't work. Also in my case - `test` is namespace. And I want to take translation from this NS like: `<Trans i18nKey="test:test welcome with space">trans</Trans>`

@Alex-Spike was not aware ns prefix usage was used in combination with natural language keys... this is not recommended (keys with ns prefix in combination with natural language keys)
for your use case, please update to v21.2.6 and set `nsSeparator` to `':'`

**Comment by Alex-Spike** [comment]
> @Alex-Spike was not aware ns prefix usage was used in combination with natural language keys... this is not recommended (keys with ns prefix in combination with natural language keys) for your use case, please update to v21.2.6 and set `nsSeparator` to `':'`

@adrai Thanks again for the answer.
But it still doesn't work for me. I've updated to `v21.2.6` and `nsSeparator` by default is ':'.
Here is an example with the latest version - https://codesandbox.io/s/react-i18next-example-forked-b9pxf?file=/package.json
(app.js line: 28) expected result - `test welcome with space` but I can see - `trans`.
Here is an example with version `20.6.1` - https://codesandbox.io/s/react-i18next-example-forked-b9pxf?file=/src/app.js
(app.js line: 28) expected result - `test welcome with space` and I can see - `test welcome with space`.
It means that keys with space don't work in combination with namespaces (`test:test welcome with space`)

**Comment by adrai** [comment]
@Alex-Spike you need to set the nsSeparator option, in your case the default is not sufficient

**Comment by fuzzykiller** [comment]
> you need to set the nsSeparator option, in your case the default is not sufficient => https://codesandbox.io/s/react-i18next-example-forked-9xz6l?file=/src/i18n.js:213-230

Wow, now this is some incredibly obscure hidden behavior, setting the option to the same value as the documented default value. It's only really documented in the migration instructions and in way too long example code comments, too.

> ![image](https://github.com/i18next/i18next/assets/664869/4e6675d7-3003-4693-b9fe-3756149425cf)

This is not a great developer experience IMHO. There need to be big warning boxes in the documentation.
