### ISSUE TITLE
keys without count property does not use `key_one`

### ISSUE THREAD

**Issue by marcovmun** [i18next/i18next#1666]
## 💥 Regression Report

A clear and concise description of what the regression is.

## Last working version

Worked up to version: 20

Stopped working in version: 21 json v4
## To Reproduce

```js
i18next.init({
  lng: 'en',
  debug: true,
  resources: {
    en: {
      translation: {
        "foo_one": "bar",
        "foo_other": "bars",
      }
    },
  }
}, function(err, t) {
});

console.log(i18next.t('foo');)

```

## Expected behavior

Translate foo with the foo_one (bar) instead of returning no key is found

```js
bar
```
instead of
```js
foo
```
## Your Environment

- *runtime version*: i.e. node v14, browser firefox
- *i18next version*: i.e. 21.1.1
- *os*:  Windows

I don't now if this new expected behavior, I can't anything in the documentation. I updated all json to the new v4 version with the online tool. And now some keys are not translated any more because of this.

**Comment by adrai** [comment]
The [v4 format](https://www.i18next.com/misc/json-format#i-18-next-json-v4) is more strict on this.
https://www.i18next.com/translation-function/plurals
![image](https://user-images.githubusercontent.com/1086194/135088045-6a28640b-cdbf-4c8d-ae67-7e7dc2f15df0.png)

But if this was a plural with v3, you should have had a count value there too.

btw: the converter should have done this: https://i18next.github.io/i18next-v4-format-converter-web/
![image](https://user-images.githubusercontent.com/1086194/135088459-6df9e59e-051d-401f-a338-0d7213e804a6.png)

**Comment by marcovmun** [comment]
Thank you for the quick response,  I didn't noticed this warning, may bad.

In our project the same key is used a place with count voor the plural ( or single) form and on an other place without te count, because there its always one. (an add button) 
Therefore the "foo" to "foo" key was missing in our V4 document now.

**Comment by adrai** [comment]
> Therefore the "foo" to "foo" key was missing in our V4 document now.

ahh ok, makes sense
