### ISSUE TITLE
ESM distributable doesn't work in browsers

### ISSUE THREAD

**Issue by DellCliff** [i18next/i18next#1667]
## 🐛 Bug Report

ESM distributable doesn't work in browsers.

## To Reproduce

```js
import * as I18 from "../node_modules/i18next/dist/esm/i18next.js";
```

Error in browser: Uncaught TypeError: Error resolving module specifier “@babel/runtime/helpers/esm/typeof”. Relative module specifiers must start with “./”, “../” or “/”.

## Expected behavior

I18 usable in the browser as a module without the need for babel or other similar systems.

## Your Environment

- *runtime version*: browser

**Comment by adrai** [comment]
maybe this helps: https://jspm.org/sandbox#H4sIAAAAAAAAA61WbW/aMBD+3l9xy760G0lKtRdGAdFR1JcNrS1j0z6a5CBuHTuyndJ06n/fxQltqdaNiSkils/28zx359zReRGryBYZQmJT0dvqLAdkcW8LoJOiZRAlTBu0XS+3M7/luQXLrcDeRLox7oTV/P6IZCl2vWuOi0xp60GkpEVJEAse26Qb4zWP0HeTBnDJLWfCNxET2G0SQSesFHSmKi4c6gvfpwHgdHw2giOUqJlVGk7SEh9GLHOrw5hbmFx8bpM/NjPtMJwvtwaXJksDrsKXk71vyY+jj1eHo11djG9Px5NmUhyOd4thbj8dDxcje354Pj+YvxOKH58fELDvOw0m0jyzUMar63HHnLLMxeOno6+NxmvXhtLUbEm8sWTy7jWxezEyS9v1jv5eM6AnjLmxIZo0rO2013Ngd42KxEQqwxWO3wA/WqYN/Smbogh1TvlKkYIrMtTGsTBjUNuvCTcnVRr4LcZ/ULsK1X8fNN8Gb/6OWHrRWEtQJAhgwIQYJBhdbaRkFeofJGhkFgfl6c34H3DWJ5+jPdPKqvKafZltxL8Ktb4ELhPU3G7m/BJkfVo1vcTIjjOK2mY38DHQ+vSZMoZPBQ6UNFbnERWNC7S5lhtpeRZ1fWFl+tRmN6GCWI/yv9LVbHdby3f564RVKS0rZ13cYTiGkYpzgTBOeGray9JOFdZApkQx40LAjGp+6rYZmGq1oEpjYMFtonIL/NEJk2dusk1fP+BNhFS4B4lWKULrw+udJyWdmUJGYHTUfc5nNH7F65tSXn83aO4FrWWxXlkLUu6SC5Gm3CvN51x2PSaVLFKVG6/31P2VvlIhuaYCS49ekUCo2wHMyImHtrJfYQCEIXynzw3JfS7rGFHbjam1o8YGUOAIhIHBjFFDRKB4ogsdGT1y3QNmrebTnNaUBJvgEqXSFzgaauRGCQyEmm/XGnb2V1LaCaumTT3c/Zn4BUcDel5kCAAA

**Comment by DellCliff** [comment]
@adrai Shims and polyfills are not really acceptable. They are not browser-native solutions.

**Comment by DellCliff** [comment]
The issue still stands and should not have been closed IMO.

**Comment by jamuhl** [comment]
Alternative: Providing a PR adding a special export for ESM for direct browser usage including the babel runtime....https://github.com/i18next/i18next/blob/master/rollup.config.js#L8

**Comment by adrai** [comment]
v21.2.0 should have a bundled esm file: https://cdn.jsdelivr.net/npm/i18next@21.2.0/dist/esm/i18next.bundled.js
