### ISSUE TITLE
Namespaced key with spaces doesn't work

### ISSUE THREAD

**Issue by jamesots** [i18next/i18next#1670]
## 🐛 Bug Report

If I try to translate a key which includes a namespace and a space, but doesn't include a key separator, the key is not translated. 

## To Reproduce

```js
const i18next = require('i18next')

i18next.init({
  lng: 'en',
  resources: {
    en: {
      translation: {
        errorCodes: {
          'UNAUTHORIZED': 'Unauthorized',
          'BAD REQUEST': 'Bad request'
        },
        'UNAUTHORIZED': 'Unauthorized',
        'BAD REQUEST': 'Bad request'
      }
    }
  }
})

let errorCode = 'UNAUTHORIZED' 
console.log(i18next.t(`translation:errorCodes.${errorCode}`))
console.log(i18next.t(`translation:${errorCode}`))
console.log(i18next.t(`${errorCode}`, {ns: 'translation'}))
errorCode = 'BAD REQUEST'
console.log(i18next.t(`translation:errorCodes.${errorCode}`))
console.log(i18next.t(`translation:${errorCode}`))
console.log(i18next.t(`${errorCode}`, {ns: 'translation'}))
```

## Expected behavior

With version 20.6.1, the code above prints

Unauthorized
Unauthorized
Unauthorized
Bad request
Bad request
Bad request

With version 21.2.0, it prints

Unauthorized
Unauthorized
Unauthorized
Bad request
translation:BAD REQUEST
Bad request

## Your Environment

- *runtime version*: node 14, Chrome
- *i18next version*: 21.2.0
- *os*: Mac, Windows, Linux

(This is very similar to #1661, but includes namespaces, which that defect did not.)

**Comment by adrai** [comment]
This is because of of the new natural language detection feature... https://www.i18next.com/misc/migration-guide#natural-language-detection
The only way to omit that check is to provide the keySeparator option

**Comment by jamesots** [comment]
Great! We already have ns and key separators set, so I'll just upgrade to 21.2.1 now that it's available. Thanks.
