### ISSUE TITLE
 Pluralization does not work in React Native without Intl support

### ISSUE THREAD

**Issue by andkom** [i18next/i18next#1671]
By default React Native projects does not support Intl, so pluralization in 21.x.x is broken because it requires Intl support.

**Comment by jamuhl** [comment]
Can be polyfilled or you can set i18next to use previous JSON format: https://www.i18next.com/misc/json-format#i-18-next-json-v3

**Comment by andkom** [comment]
Right, but it should throw error when Intl not found:

```
getRule(code, options = {}) {
    if (this.shouldUseIntlApi()) {
      try {
        return new Intl.PluralRules(code, { type: options.ordinal ? 'ordinal' : 'cardinal' });
      } catch {
        return; // throw error here
      }
    }

    return this.rules[code] || this.rules[this.languageUtils.getLanguagePartFromCode(code)];
  }
```

I wasted several hours for debugging :(

**Comment by adrai** [comment]
With v21.2.2 there should be logged an error now.
There's also a hint on the documentation page: https://www.i18next.com/translation-function/plurals

**Comment by andkom** [comment]
v3 fallback is broken because getRule() returns undefined:

example:

```
global.Intl = undefined;
const i18next = require('i18next');

i18next
  .init({
    lng: 'en',
    debug: true,
    resources: {
      en: {
        translation: {
          key: 'v3 item',
          key_plural: 'v3 items',
          key_one: 'v4 item',
          key_other: 'v4 items',
        },
      },
    },
  })
  .then(() => {
    console.log(i18next.t('key', { count: 0 }));
  });
```

output:

```
i18next::pluralResolver: no plural rule found for: en
i18next::pluralResolver: no plural rule found for: en
v3 item
```

**Comment by adrai** [comment]
@andkom v21.2.3 should be better, but honestly I would suggest to explicitely use 1 format version so better set the `compatibilityJSON` to `'v3'`

**Comment by andkom** [comment]
imho better to modify `shouldUseIntlApi()` than mutating options:

```
shouldUseIntlApi() {
  return !deprecatedJsonVersions.includes(this.options.compatibilityJSON) && Intl && Intl.PluralRules;
}
```

**Comment by GFean** [comment]
Adding ` compatibilityJSON: 'v3',` in i18n init method has solved an issue for me.

**Comment by mateusmarinhoo** [comment]
The only thing that worked to me was define in json.

`{
  "store": "Single Store",
  "store_plural": "Multiple Stores"
}`

`{t('store', {  count: 1 })}` - Single Store
`{t('store', {  count: 3 })}` - Multiple Stores


store_two for example, I still did'nt find how to make it work.

**Comment by adrai** [comment]
compatibilityJSON: 'v3' is not intl based only v4 is...
a _two suffix has no every language

**Comment by dieguezz** [comment]
For those still landing here, you can better install (intl-pluralrules)[https://github.com/eemeli/intl-pluralrules] polyfill

**Comment by ggat** [comment]
Thanks @adrai, all I needed was to switch to v4 in order to make sense what docs say.

> You may need to [polyfill](https://github.com/eemeli/intl-pluralrules) the [Intl.PluralRules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules) API, in case it is not available it will fallback to the [i18next JSON format v3](https://www.i18next.com/misc/json-format#i18next-json-v3) plural handling.

I would just add "which supports different suffixes than described in this doc" or "which works differently from what's described in this doc"

**Comment by Navipro70** [comment]
I think we should provide adding polyfill information as "best practice" for react native in `react-i18next` docs. Exactly for me it was a little bit tough to figure out why my react native app cannot pluralize another language (except english), for such minor thing spent some hours
