### ISSUE TITLE
cannot find variable: Intl when using i18next in Expo project

### ISSUE THREAD

**Issue by cuongnv-dev** [i18next/i18next#1672]
When using i18next in Expo project, everything work ok in IOS, but in android, a got an issue: Can't find variable: Intl

Hope someone can help me in this case

**Comment by jamuhl** [comment]
see https://github.com/i18next/i18next/issues/1671

**Comment by adrai** [comment]
It may be we need to change the check to typeof...

**Comment by cuongnv-dev** [comment]
> see #1671

I dont understand this post

**Comment by cuongnv-dev** [comment]
> It may be we need to change the check to typeof...

Do you have any solution in my case?

**Comment by adrai** [comment]
> > It may be we need to change the check to typeof...
> 
> 
> 
> Do you have any solution in my case? 

Did you try with the newest version?

**Comment by cuongnv-dev** [comment]
currently, I'm using the latest version 21.2.3

**Comment by adrai** [comment]
Can you provide a stacktrace?

**Comment by cuongnv-dev** [comment]
![Screenshot_1633195578](https://user-images.githubusercontent.com/82807964/135726517-368c6088-82dc-42dc-a410-9c13c80c1f57.png
<img width="819" alt="Screenshot 2021-10-03 at 12 26 51 AM" src="https://user-images.githubusercontent.com/82807964/135726527-188d9d24-983e-45ab-8b9b-8b5f08e1d980.png">

Here is the stacktrace in my emulator and my terminal
)

**Comment by adrai** [comment]
we will then probably create a new version in the next days... 
But for now we suggest you to set compatibilityJSON to v3 or use an Intl.PluralRules [polyfill](https://github.com/eemeli/intl-pluralrules), like described here: https://www.i18next.com/translation-function/plurals

**Comment by cuongnv-dev** [comment]
Many thanks. Hope my case will be resolve in the next update soon

**Comment by adrai** [comment]
As said... the next update will just optimize the "error case"
You need to use a polyfill anyway or configure to use the v3 format

**Comment by adrai** [comment]
v21.2.4 has just been released

**Comment by cuongnv-dev** [comment]
I have updated the newest version and it resolves my error, thanks a lot.
