### ISSUE TITLE
Q: Dynamic mentions with "and" at last mention

### ISSUE THREAD

**Issue by dickyindra** [i18next/i18next#1674]
Does i18next have features like dynamic mentions with "and" at last mention? (I don't know the name of the term)

Example:
I have resources like this:

    {
	    "eat_meat": "I eat all the meat",
	    "eat_meat_mention": "I eat all meat except {{mention}}"
    }

Sample:

    i18next.t('eat_meat', { mention: [] });
    // -> "I eat all the meat"

    i18next.t('eat_meat', { mention: ["chicken"] });
    // -> "I eat all meat except chicken"

    i18next.t('eat_meat', { mention: ["chicken", "beef"] });
    // -> "I eat all meat except chicken and beef"

    i18next.t('eat_meat', { mention: ["chicken", "beef", "pork"] });
    // -> "I eat all meat except chicken, beef, and pork"

**Comment by adrai** [comment]
Maybe the list format?

https://www.i18next.com/translation-function/formatting#list

**Comment by anchi20** [comment]
`i18next.t(['intlList', { val: ['locize', 'i18next', 'awesomeness'] });
` the first occurrence of `[` needs to be replaced with `{`, I think. Should I create a PR for it??
also I am unable to use it, list is rendering as blank for me, can you guys add more examples for this?

**Comment by adrai** [comment]
> @adrai
> 
> `i18next.t(['intlList', { val: ['locize', 'i18next', 'awesomeness'] }); ` the first occurrence of `[` needs to be replaced with `{`, I think. Should I create a PR for it?? also I am unable to use it, list is rendering as blank for me, can you guys add more examples for this?

Don't know exactly what you mean... there is a test with exactly that example: https://github.com/i18next/i18next/blob/master/test/i18next.translation.formatting.spec.js#L217

**Comment by anchi20** [comment]
> > @adrai
> > `i18next.t(['intlList', { val: ['locize', 'i18next', 'awesomeness'] }); ` the first occurrence of `[` needs to be replaced with `{`, I think. Should I create a PR for it?? also I am unable to use it, list is rendering as blank for me, can you guys add more examples for this?
> 
> Don't know exactly what you mean... there is a test with exactly that example: https://github.com/i18next/i18next/blob/master/test/i18next.translation.formatting.spec.js#L217

fixed my comment, apologies.

**Comment by adrai** [comment]
ahh, fixed the docs

**Comment by anchi20** [comment]
> ahh, fixed the docs

also don't know why but for me `A list of locize,i18next,awesome` is being printed instead of `A list of locize, i18next, and awesome` by default, i.e. format type is not conjunction (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat#using_format) and I am unable to change that.

**Comment by adrai** [comment]
> > ahh, fixed the docs
> 
> 
> 
> also don't know why but for me `A list of locize,i18next,awesome` is being printed instead of `A list of locize, i18next, and awesome` by default, i.e. format type is not conjunction (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat#using_format) and I am unable to change that.
> 
> 

The tests are working... please provide a reproducible example.
