### ISSUE TITLE
React-native release build crashes with v21.3.0

### ISSUE THREAD

**Issue by MEsteves22** [i18next/i18next#1675]
## 🐛 Bug Report

I upgraded i18next to version 21.3.0, and since then my app (react-native) crashes when I open it in release mode. In debug mode, everything seems to be working fine. I had to downgrade to v21.2.6.

Is anyone else having this problem?

## Your Environment

- *i18next version*: 21.3.0
- *react-native*: 0.64.2 
- *os*: Mac

System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 74.26 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.18.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 25, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by peterkuiper** [comment]
@adrai Same here, using Expo SDK 42.

**Comment by adrai** [comment]
I think I know what it is, but I don't know why

**Comment by mimo-10** [comment]
2024 same issue back again, the app crashes when I change language in production app
