### ISSUE TITLE
How to handle different suffix in i18next for agglutinative languages (eg. Turkish, Japanese, etc.)

### ISSUE THREAD

**Issue by Teal-labs-developer** [i18next/i18next#1685]
I am trying to add Turkish support in my product. Turkish is agglutinative language. Which means that it tends to express concepts in complex words consisting of many elements, rather than by inflection or by using isolated elements.
Currently we have created keys for `i18next` like following:
`tr/resourceExample.json`

    {
        "comment":"Yorum",
        "comment_plural":"Yorumlar",
        "select_label":"{{label}} seç"
    }

Whenever we want to add a sentence like `"Select comments"` we use

    t("resourceExample:select_label",{label:t("resourceExample:comment_plural")})

Now this works properly for languages like English or Spanish. But for Turkish, the suffix of `comment` changes if the word is used with verb.

For example, our currently key structure will give output for Turkish following:

> Yorumlar seç

But the actual expected result for Turkish is:
> Yorumları seç

The reason behind keeping this structure is that we didn't want to create new keys for `select_label` because `Select something` is used in many places where `something` can be replaced by many different words.

So, my question is that is there any functionality in `i18next` which can help in this situation?

**Comment by jamuhl** [comment]
you can try building something using https://www.i18next.com/translation-function/context

**Comment by ubaranzorlu** [comment]
The way I achieved this is to add a formatter by utilising _@erkanarslan/turkish-inflection_

```ts
import i18next from 'i18next';
import { inflect } from '@erkanarslan/turkish-inflection';

// ... Initialise i18next here

i18next.init({
    resources: {
      tr: {
        translation: {
        // I add extra backticks here to pass apostrophe properly.
          insufficient : "{{name, inflect(ek:`'--in`)}} etiketli maçı yok."
        },
        langName: 'Türkçe',
        shortName: 'tr',
      },
      en: {
        translation: {
          insufficient : "We don't have any matches tagged of {{name}}."
        },
        langName: 'English',
        shortName: 'en',
      }
    }
})

i18next.services.formatter.add('inflect', (value, lng, options) => {
    if (lng === 'tr') {
      // I added backticks to include apostrophes in the string, now I remove them
      const removeBackticksFromEk = options.ek.replace(/`/g, '');
      value = inflect(value + removeBackticksFromEk);
    }
    return value;
  });
```

Then I use it as such
```ts
//Türkçe
i18next.t("insufficient", {name: "Fenerbahçe"}); // Fenerbahçe'nin etiketli maçı yok.

//English
i18next.t("insufficient", {name: "Fenerbahçe"}); // We don't have any matches tagged of Fenerbahçe.

```
