### ISSUE TITLE
Doesn't work singular/plural forms with a few counts

### ISSUE THREAD

**Issue by IlliaHohniak-Hexa** [i18next/i18next#1686]
## 🐛 Bug Report

I use Trans tag. And I use nesting to create the translations string from few other. So I have to use a few different "count" for every key. I can't use a few counts, because Trans doesn't have such options. So I use "values". And in this case count works fine, context works fine... but "_plural" doesn't work.  

## To Reproduce

Here is code from the page:

```js
                            <Trans
                                debug={true}
                                i18nKey="billedAfterTrial"
                                values={{
                                    currencySign: currencySign,
                                    currentPrice: currentPrice,
                                    count1: periodType.count,
                                    count2: trialType.count,
                                    count3: day,
                                    context1: periodType.context,
                                    context2: trialType.context,
                                    context3: month,
                                }}
                            >
                                [$79.99] billed [yearly] after a [7-day] trial period. Contact us via
                                support@dailyfit.io to cancel.
                            </Trans>
```
Here is the translation keys:

```js
  "X period": "{{count}} week",
  "X period_plural": "{{count}} weeks",
  "X period_month": "{{count}} month",
  "X period_month_plural": "{{count}} months",
  "X period_0": "{{count}} week",
  "X period_1": "{{count}} week",
  "X period_2": "{{count}} week",
  "X period_month_0": "{{count}} month",
  "X period_month_1": "{{count}} month",
  "X period_month_2": "{{count}} month",

  "X-period": "{{count}}-week",
  "X-period_month": "{{count}}-month",

  "billedAfterTrial": "{{currencySign}}{{currentPrice}} billed every $t(X period, {\"count\": \"{{count1}}\", \"context\": \"{{ context1 }}\" }) after the $t(X-period, {\"count\": \"{{count2}}\", \"context\": \"{{ context2 }}\" }) trial period."
```
I changed 's' in the "_0, _1, _2" (we use it for Russian), but it doesn't work to. Also, I changed "_plural" to "_other". And nothing works.

## Expected behavior

I expect that if count1 will be 3, I'll get "billed every 3 months".
I get "billed every 3 month"

```js
// Paste the expected results here
```

## Your Environment

- *i18next version*: i.e. 19.9.2
- *os*: Mac

**Comment by adrai** [comment]
Can you provide a reproducible example i.e. like: https://codesandbox.io/s/react-i18next-example-4b33i?file=/src/i18n.js ?.
If you're using <v20.x.x the plural format is: https://www.i18next.com/misc/json-format#i18next-json-v3
If you're using >=v20.x.x the plural format is: https://www.i18next.com/misc/json-format#i18next-json-v4

**Comment by jamuhl** [comment]
might help too: https://www.i18next.com/translation-function/nesting#passing-options-to-nestings

**Comment by IlliaHohniak-Hexa** [comment]
@adrai  I can't do it in sandbox, because project structure in too difficult. Maybe you have another options? 
And yes, I use correct plural forms. Then I use only one count in other translations all works correct

**Comment by IlliaHohniak-Hexa** [comment]
@jamuhl  Yes, I used your doc. In all other simple cases it works correct. But here I got the mistake

**Comment by adrai** [comment]
> I can't do it in sandbox, because project structure in too difficult.

Without being able to reproduce it, it is difficult to help, sorry.

**Comment by IlliaHohniak-Hexa** [comment]
@adrai try here. Will you see a code? https://codesandbox.io/s/react-i18next-example-forked-f91kq?file=/src/app.js

**Comment by adrai** [comment]
Try to write count variables: `"count": "{{count1}}"` without the `"`
i.e. `"count": {{count1}}`

complete key:

```js
{
  billedAfterTrial: '{{currencySign}}{{currentPrice}} billed every $t(Xperiod, {"count": {{count1}}, "context": "{{ context1 }}" }) after the $t(XPeriod, {"count": {{count2}}, "context": "{{ context2 }}" }) trial period.'
}
```

**Comment by IlliaHohniak-Hexa** [comment]
@adrai  Yeah, it works! Previously I used " with both {{count}} and {{context}} or I deleted " in the both places... and it didn't work. Can you explain, why {{context}} should be with " ?

**Comment by adrai** [comment]
> @adrai  Yeah, it works! Previously I used " with both {{count}} and {{context}} or I deleted " in the both places... and it didn't work. Can you explain, why {{context}} should be with " ?

because context is a string and count is a number

**Comment by IlliaHohniak-Hexa** [comment]
@adrai sounds logical. Thanks for your help!

**Comment by IlliaHohniak-Hexa** [comment]
I have one more question. 
Previously, I used the condition that if I receive 1, then I pass in the count an empty string - this was necessary so that the number did not appear. And it worked since there were quotes around count. And now it doesn't work, since they disappeared and the string (not the number) breaks the key.
Tell me, can I somehow fix this without using a separate key for 1?

**Comment by IlliaHohniak-Hexa** [comment]
I have one more question.
Previously, I used the condition that if I receive 1, then I pass in the count an empty string - this was necessary so that the number did not appear. And it worked since there were quotes around count. And now it doesn't work, since they disappeared and the string (not the number) breaks the key.
Tell me, can I somehow fix this without using a separate key for 1?

**Comment by adrai** [comment]
> I have one more question. Previously, I used the condition that if I receive 1, then I pass in the count an empty string - this was necessary so that the number did not appear. And it worked since there were quotes around count. And now it doesn't work, since they disappeared and the string (not the number) breaks the key. Tell me, can I somehow fix this without using a separate key for 1?

can you please create an example? I don't really understand what you mean

**Comment by IlliaHohniak-Hexa** [comment]
@adrai same link https://codesandbox.io/s/react-i18next-example-forked-f91kq?file=/src/app.js 
I commented count and added one more with empty string. And it doesn't work. But i need to don't show "1". So i want to see "billed every month" not "billed every 1 month"

**Comment by adrai** [comment]
If you're using node.js >=v20.x.x and want to keep the "old" plural suffixes, set `compatibilityJSON: 'v3'` and add this missing resource: `Xperiod_month: "month"`
like here: https://codesandbox.io/s/react-i18next-example-forked-6pshb?file=/src/i18n.js:626-649

if you want to use the new plural suffix, use _other instead of _plural, like here: https://codesandbox.io/s/react-i18next-example-forked-1hmqj?file=/src/i18n.js:343-356

**Comment by IlliaHohniak-Hexa** [comment]
But this is not a flexible enough solution for me. I want to use "Xperiod" in a few different places. And somewhere I want to see "1 month" and in another place - "month". So I thought that I can pass some specific data in the case then I don't want to see "1"

**Comment by adrai** [comment]
sorry, this is how it works

**Comment by adrai** [comment]
> But maybe you have some options to do this? Can you recommend something?

Not without other dedicated keys.

**Comment by IlliaHohniak-Hexa** [comment]
Hi again. I tried to solve my problem in more creative way. And I wanted to use "object"-feature. I think, I did something wrong. Can you check it, pls? And give some advices. 
https://codesandbox.io/s/react-i18next-example-forked-f91kq?file=/src/i18n.js 
Here it works, but doesn't use plural forms (try to change var 'count1')

And I have the same in my project and it totally doesn't work. And I don't know why
![image](https://user-images.githubusercontent.com/78801565/144006748-061c5d66-acf2-450c-9951-256aa022ed2c.png)
![image](https://user-images.githubusercontent.com/78801565/144006791-b092bbf3-1925-4a38-b390-17f35070415a.png)

**Comment by IlliaHohniak-Hexa** [comment]
@adrai Hi. Please, can you answer me?

**Comment by adrai** [comment]
> @adrai Hi. Please, can you answer me?

Sorry, I didn't saw your comment....
What is the actual issue, I don't understand your question?
btw: there are languages, that handles plurals with more complex rules, that's why your check here will not work for all languages: https://codesandbox.io/s/react-i18next-example-forked-f91kq?file=/src/app.js:447-528

**Comment by IlliaHohniak-Hexa** [comment]
1. Can I work with "object"-feature like I showed in the code? When I have two object keys: with and without {{count}}. In this case lib doesn't use _plural form.

2. In the sand box it works. With mistakes but it works. In my code in the project (screenshots) it doesn't work. I just see the broken translation key on the page. And I don't know why...

**Comment by adrai** [comment]
1. As said before: <<there are languages, that handles plurals with more complex rules, that's why your check here will not work for all languages: https://codesandbox.io/s/react-i18next-example-forked-f91kq?file=/src/app.js:447-528>>

2. I don't know why... if it works in the sandbox example, there might be a different reason

**Comment by IlliaHohniak-Hexa** [comment]
And if we take only English? With key and key_plural. Why it doesn't work? And can I make it works correctly?

**Comment by adrai** [comment]
Yes, only english will work.
I don't know why doesn't work in your local project, I'm sorry. It works in the codesandbox example, so it is something you need to debug locally.

**Comment by IlliaHohniak-Hexa** [comment]
In the sandbox it doesn't work too - "every 5 week" --> should be "every 5 weeks"

**Comment by adrai** [comment]
> In the sandbox it doesn't work too - "every 5 week" --> should be "every 5 weeks"

That's only because you did not specify the _plural key, here: https://codesandbox.io/s/react-i18next-example-forked-ziui4?file=/src/i18n.js:355-405 => this works

**Comment by IlliaHohniak-Hexa** [comment]
I see... thanks. I will try to implement it

**Comment by IlliaHohniak-Hexa** [comment]
@adrai Hi. Like I wrote previously, it doesn't work in my project (screenshot). I think, the problem is in the string-keys. So the lib can't correctly get the information. I tried:
$t(Xperiod['withNumber']
$t(Xperiod[withNumber]
$t(Xperiod.withNumber

and nothing works. What do you think?
(i can't show it in the sandbox because it automatically changes string-keys to default)

**Comment by adrai** [comment]
You are trying to call: `$t(Xperiod['withNumber']` inside your translation value? This will for sure never work!

Only this notation works: `$t(Xperiod.withNumber`

**Comment by IlliaHohniak-Hexa** [comment]
@adrai if I have to use quote marks due to JSON format, how can I get 'withNumber' key?

**Comment by adrai** [comment]
> @adrai if I have to use quote marks due to JSON format, how can I get 'withNumber' key?

Sorry I have no idea what you mean.

But in general you can escape " in json:

\"

**Comment by IlliaHohniak-Hexa** [comment]
I described it... and added screenshots... 
I have to create json with keys like this: 
```
  "Xperiod": {
    "withNumber": "{{count}} week",
    "withoutNumber": "{{count}} week"
  }
  
  "billedEvery2": "{{currencySign}}{{currentPrice}} billed every $t(Xperiod.withNumber, {\"count\": {{count1}}, \"context\": \"{{ context1 }}\" }) after"
```
  
  If I write Xperiod.withNumber it doesn't work. I think because of quote marks. Do you have an idea how can I use "withNumber" key in that case?

**Comment by adrai** [comment]
![image](https://user-images.githubusercontent.com/1086194/145392270-23508124-dd6f-466f-af42-eddb460b1823.png)
![image](https://user-images.githubusercontent.com/1086194/145392321-22206d46-7491-4c79-a197-c7116b983365.png)
![image](https://user-images.githubusercontent.com/1086194/145392343-6c13e568-84d9-4004-b7d0-250ba861ce25.png)


Sorry, but for me it works...

If you can't reproduce it in codesandbox, create a new github repo and show the issue there...

**Comment by adrai** [comment]
> can you send the link to this sandbox?

https://codesandbox.io/s/react-i18next-example-forked-so5tj

=> you may need to uncheck this: https://til.hashrocket.com/posts/hl38yhiqvt-disable-codesandbox-auto-formatting

**Comment by IlliaHohniak-Hexa** [comment]
@adrai I find the problem. Here you had almost the same -  https://github.com/i18next/react-i18next/issues/373
I had `keySeparator: false` in the init

**Comment by IlliaHohniak-Hexa** [comment]
@adrai Hi. I have a strange problem again. 
https://codesandbox.io/s/react-i18next-example-forked-woem4?file=/src/i18n.js

In the key "Xperiod" I uses "Xperiod.withoutNumber_0" (---> "недельного") and it works. 
But the same structure in key "X-period" doesn't work. Even it uses context 'day' and use only default value 'week'

**Comment by adrai** [comment]
context suffix is at the end: https://codesandbox.io/s/react-i18next-example-forked-vz5e8
![image](https://user-images.githubusercontent.com/1086194/145974434-5225ea72-3174-4428-b2ba-e196acd37faa.png)

**Comment by IlliaHohniak-Hexa** [comment]
why in the key "Xperiod" it works correctly?

**Comment by adrai** [comment]
It does not work too... it is always using week

**Comment by IlliaHohniak-Hexa** [comment]
I'll check. 
But it use form ""withoutNumber_0"", and "X-period" doesn't... why?

**Comment by adrai** [comment]
This should work: https://codesandbox.io/s/react-i18next-example-forked-vz5e8?file=/src/i18n.js

**Comment by adrai** [comment]
With all the support work, can I send you an invoice for my support? 😉

**Comment by IlliaHohniak-Hexa** [comment]
Put it all on my tab. It's worth every penny!)

**Comment by IlliaHohniak-Hexa** [comment]
@adrai it doesn't work ((
I have those keys for RU
    "genitive_day": "{{count}}-дн.",
    "genitive_day_plural": "{{count}}-дн.",
    "genitive_day_0": "{{count}}-дневного",
    "genitive_day_1": "{{count}}-дневного",
    "genitive_day_2": "{{count}}-дневного",

And it doesn't use _0, _1, _2. It uses only "genitive_day" one. 
Do you have any idea why?

**Comment by adrai** [comment]
because you are only using billedEvery.singular and not billedEvery.plural in the example?

**Comment by IlliaHohniak-Hexa** [comment]
So? in the 'billedEvery.singular' i have key "X-period.genitive" . And it doesn't work

**Comment by adrai** [comment]
ahh i misunderstood, sorry...
that's because you're still using quotes for numbers:
instead of `{\"count\": \"{{count2}}\"` you should do `{\"count\": {{count2}}`

https://codesandbox.io/s/react-i18next-example-forked-vz5e8?file=/src/i18n.js:2409-2431

**Comment by haoolii** [comment]
Hello guys, I also have some confuse situation. my english i18n work correctly, but when i change language to zh, it always return plural key event the value is singular.

anyone can help me to solve this problem ?

https://codesandbox.io/s/react-i18next-plurals-forked-jgulw6?file=/public/locales/zh/translation.json

**Comment by adrai** [comment]
> Hello guys, I also have some confuse situation. my english i18n work correctly, but when i change language to zh, it always return plural key event the value is singular.
> 
> anyone can help me to solve this problem ?
> 
> https://codesandbox.io/s/react-i18next-plurals-forked-jgulw6?file=/public/locales/zh/translation.json

zh has only 1 suffix, and that's the _other suffix: https://jsfiddle.net/6bpxsgd4
<img width="408" alt="image" src="https://user-images.githubusercontent.com/1086194/231725468-48f10a4f-1701-4181-aeae-4905ef6572bd.png">

**Comment by haoolii** [comment]
> 


I not really sure what do you mean. I use 1 but it take _other key. it's wired.

**Comment by adrai** [comment]
@haoolii zh (chinese) does not differenciate singular or plural forms there is just one form so there is only the _other suffix https://en.wikipedia.org/wiki/Chinese_grammar#:~:text=Chinese%20nouns%20and%20other%20parts,%22I%2C%20me%22).

**Comment by jamuhl** [comment]
means:

en -> _one, _other (depending on singular or not)
zh -> _other (for all)

**Comment by haoleexrex** [comment]
> @haoolii zh (chinese) does not differenciate singular or plural forms there is just one form so there is only the _other suffix https://en.wikipedia.org/wiki/Chinese_grammar#:~:text=Chinese%20nouns%20and%20other%20parts,%22I%2C%20me%22).

nice, I got it. umm and other problem happean, my nextjs project use zh_TW as language key, but it seems library can't identify this langulage code. how could I solve this problem. langulage code can't be change to zh or (zh-TW)

**Comment by adrai** [comment]
Next.js and also i18next requires dashes (zh-TW).
Please do not continue to pollute other issues.
