### ISSUE TITLE
The cloneInstance function does not use language passed into options

### ISSUE THREAD

**Issue by kingjerod** [i18next/i18next#1688]
## 🐛 Bug Report

A cloned instance does not use the `lng` value passed into options. Using `changeLanguage` on that instance afterwards does work.

## To Reproduce

https://codesandbox.io/s/epic-curie-yezqr?file=/src/index.js:0-716

```js
var i18next = require("i18next");

async function start() {
  console.log("Starting");
  i18next.init({
    lng: "en",
    fallbackLng: "en",
    defaultNS: "namespace1"
  });
  i18next.addResourceBundle("en", "namespace1", {
    error_1: "English"
  });
  i18next.addResourceBundle("de", "namespace1", {
    error_1: "German"
  });
  const german = i18next.cloneInstance({ lng: "de" });
  console.log("This fails:");
  console.log("English: " + i18next.t("error_1"));
  console.log("German: " + german.t("error_1")); // shows "English"

  console.log("This works:");
  await german.changeLanguage("de");
  console.log("English: " + i18next.t("error_1"));
  console.log("German: " + german.t("error_1"));
  process.exit();
}

start();

```

## Expected behavior
It should use the German language that was passed into options.

## Your Environment

- *runtime version*: i.e. node v14.13.1
- *i18next version*: i.e. 21.4.1
- *os*: Linux (Docker)

**Comment by adrai** [comment]
You're not passing any resources on init, this means i18next will init more asynchronous...
Just pass in at least an empty resources object: https://www.i18next.com/how-to/add-or-load-translations#add-after-init
![image](https://user-images.githubusercontent.com/1086194/140816080-f55f9cc3-2e66-4552-8684-b8a4d41d422c.png)

**Comment by kingjerod** [comment]
What if I'm not uses the `resources` key at all? I'm using the `i18next-http-backend` plugin and using `load: "all",` to get them loaded on server start. cloneInstance doesn't work properly in that case either.

If I set `resources: {}` with the http backend loader then it deletes all the translations, so that's not a solution.

What is `changeLanguage` doing that works fine vs setting the language in the options?

**Comment by adrai** [comment]
If you're not setting the resources on init, you need to wait for the initialization to be finished.
init callback or promise
and the callback for createInstance

**Comment by kingjerod** [comment]
Calling await on both the `init` function and the `cloneInstance` function doesn't help. Even adding a 6 second wait before the `cloneInstance` function doesn't help. 

Here is an example of that: https://codesandbox.io/s/sharp-gauss-7oeop?file=/src/index.js

If you add `initImmediate: false` to the init function, it will work properly. You don't even need to use the callback or promise (await) on either the init or the cloneInstance (at least for local files):
https://codesandbox.io/s/stupefied-jepsen-2fsob?file=/src/index.js

It is kind of confusing why setting an option "initImmediate" to false causes things to get initialized immediately (or so it seems).

**Comment by adrai** [comment]
cloneInstance returns no promise, but has only a callback, so this works:

```javascript
var i18next = require(".i18next");

async function start() {
  console.log("Starting: ");
  await i18next.init({
    lng: "en",
    preload: ["en", "de"],
    fallbackLng: "en",
    defaultNS: "namespace1"
  });
  i18next.addResourceBundle("en", "namespace1", {
    error_1: "English"
  });
  i18next.addResourceBundle("de", "namespace1", {
    error_1: "German"
  });

  const german = i18next.cloneInstance({ lng: "de" }, (err, t) => {
    console.log("This works:");
    console.log("German: " + t("error_1"));  
  });
  console.log("This fails:");
  console.log("English: " + i18next.t("error_1"));
  console.log("German: " + german.t("error_1"));

  // console.log("This works:");
  // await german.changeLanguage("de");
  // console.log("English: " + i18next.t("error_1"));
  // console.log("German: " + german.t("error_1"));
  // process.exit();
}

start();
```

and this works too (initImmediate for cloneInstance):

```js
var i18next = require("./");

async function start() {
  console.log("Starting: ");
  await i18next.init({
    lng: "en",
    preload: ["en", "de"],
    fallbackLng: "en",
    defaultNS: "namespace1"
  });
  i18next.addResourceBundle("en", "namespace1", {
    error_1: "English"
  });
  i18next.addResourceBundle("de", "namespace1", {
    error_1: "German"
  });

  const german = i18next.cloneInstance({ lng: "de", initImmediate: false });
  console.log("This fails:");
  console.log("English: " + i18next.t("error_1"));
  console.log("German: " + german.t("error_1"));

  // console.log("This works:");
  // await german.changeLanguage("de");
  // console.log("English: " + i18next.t("error_1"));
  // console.log("German: " + german.t("error_1"));
  // process.exit();
}

start();
```

The initImmediate option only works for sync (blocking) loading backend, like [i18next-fs-backend](https://github.com/i18next/i18next-fs-backend#if-set-i18next-initimmediate-option-to-false-it-will-load-the-files-synchronously)
