### ISSUE TITLE
Only first formatter is called when using multiple formatters 

### ISSUE THREAD

**Issue by bsShoham** [i18next/i18next#1689]
## 🐛 Bug Report

When using multiple formatters as in docs, only the first formatter is called

## To Reproduce

A sandbox with reproduction of the bug
https://codesandbox.io/s/multiple-formatters-doesnt-work-dfvng
currently you'll see that only the first formatter is called (you can switch order of the formatters to see it's always the first)

## Expected behavior

Both (or more if there are) formatters will be called in the order they appear in

## Your Environment

- *runtime version*:  browser
- *i18next version*:  21.4.1
- *any other relevant information*: I'm using it with react-i18next because that's the way I'm working currently, but the logic is in the base package (i18next)

**Comment by adrai** [comment]
should be fixed with v21.4.2
