### ISSUE TITLE
French plural for one million seem to be wrong 

### ISSUE THREAD

**Issue by jfreyheit** [i18next/i18next#1691]
## 🐛 Bug Report

French plurals for powers of ten above or equal to one million display the singular form. 

## To Reproduce

```js
import i18next from "i18next";

const lang = "fr"; // Switching to "en" for example will yield the expected result

i18next.init({
  debug: true,
  fallbackLng: lang,
  resources: {
    [lang]: {
      translation: {
        key: {
          value: "micromètre",
          value_other: "micromètres"
        }
      }
    }
  }
});

console.log(i18next.t("key.value", { count: 10 ** 6 - 1 }));
console.log(i18next.t("key.value", { count: 10 ** 6 }));
console.log(i18next.t("key.value", { count: 10 ** 6 + 1 }));
```

The output is :

```
micromètres
micromètre
micromètres
```

## Expected behavior

I expect all three lines to be identical

```js
micromètres
micromètres
micromètres
```

This can also be reproduced with larger powers of ten, such as 10 ** 7, but 10 ** 5 works fine.
Also switching to another language such as "en" or "de" is okay..

## Your Environment

- *runtime version*: node v16
- *i18next version*: i.e. 21.4.2
- *os*: Linux

**Comment by adrai** [comment]
this is really strange

**Comment by adrai** [comment]
It seems this is how the plural rules for french are working: https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html
![image](https://user-images.githubusercontent.com/1086194/141644460-8b950254-ba9d-4b3f-ba78-bd9ec9daa432.png)

so this is correct
