### ISSUE TITLE
21.5.1 problem with default export (TypeScript)

### ISSUE THREAD

**Issue by rvanmil** [i18next/i18next#1692]
## 🐛 Bug Report

The following code used to work without eslint complaining:
```
import i18n from 'i18next'
i18n.t('foobar')
```

After 21.5.1 this results in the message: Caution: `i18n` also has a named export `t`. Check if you meant to write `import {t} from 'i18next'` instead. [import/no-named-as-default-member](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-named-as-default-member.md)

Changing the code to:

```
import { t } from 'i18next'
t('foobar')
```

Results in a syntax error: Module '"i18next"' has no exported member 't'. Did you mean to use 'import t from "i18next"' instead?ts(2614)

Changing the code to:

```
import { default as i18n } from 'i18next'
i18n.t('foobar')
```

Fixes the problem, but I don't think it's supposed to work this way.

## To Reproduce

https://codesandbox.io/s/i18next-typescript-import-issue-r2huh?file=/src/App.tsx

## Your Environment

- *runtime version*: react-scripts 4.0.3, react 17.0.2, typescript 4.4.4
- *i18next version*: 21.5.1
- *os*: Browser

**Comment by adrai** [comment]
Can you retry with v21.5.2 ?

**Comment by adrai** [comment]
// @pedrodurek fyi: https://github.com/i18next/i18next/commit/e7a9dd4baf0300f508ababbcea4a94a87ce6f9de

**Comment by rvanmil** [comment]
> Can you retry with v21.5.2 ?

Thanks, this fixes `import { t } from 'i18next'`. But it did not fix the eslint warning when using `import i18n from 'i18next'`.

**Comment by adrai** [comment]
> > Can you retry with v21.5.2 ?
> 
But it did not fix the eslint warning when using `import i18n from 'i18next'`.

I'm not seeing any warning here: https://codesandbox.io/s/i18next-typescript-import-issue-r2huh?file=/src/App.tsx
I'm not a TypeScript user so can you advice on how I should see that warning?

**Comment by adrai** [comment]
ahhh if import/no-named-as-default-member is enabled, the warning makes sense.
So there's probably nothing we can do here.

**Comment by rvanmil** [comment]
Yeah the issue is resolved, thanks 😊👍

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
