### ISSUE TITLE
Document expected performance metrics

### ISSUE THREAD

**Issue by amandapouget** [i18next/i18next#1693]
## Documentation issue

I see another issue in the backlog where a user had a degraded t performance caused by a large dictionary load. However, there doesn't appear to be any documentation about what "normal" performance for t() is.

For example, is 0.07ms considered a normal performance? When compared to plain string performance of 0.009ms?

## Motivation

When tracking down performance issues that only appear when t() is added, it's helpful to know what the official benchmark is for t performance. That way, one can investigate whether it's a configuration issue or something else.

(Separately, it'd be nice to document client-side caching options for executing t() but it doesn't look like those are built-in, so nothing to document there.)

**Comment by adrai** [comment]
Do you mean this? https://react.i18next.com/latest/typescript#slow-compilation-time

**Comment by amandapouget** [comment]
Thanks for the link to TypeScript as a culprit, but what is "great" results?

Also I'm requesting documentation about execution in the browser not compilation time.

**Comment by adrai** [comment]
There is currently no know specific performance metric.
fyi: https://github.com/i18next/i18next/issues/1639
