### ISSUE TITLE
chinese locale in readme does not seem to work with directly provided resources?

### ISSUE THREAD

**Issue by oshi97** [i18next/i18next#1697]
## 🐛 Bug Report

In the docs, under "how should locales be formatted", the example locale "zh-hant-HK" is given.
https://www.i18next.com/how-to/faq#how-should-the-language-codes-be-formatted
However, it doesn't seem like this works properly when you try to provide resources directly in i18next.init?

## To Reproduce

```js
const i18next = require('i18next');
const resources = {
  'zh-hant-HK': {
    translation: {
      'hi': 'translated',
    }
  }
}

i18next.init({
  lng: 'zh-hant-HK',
  nsSeparator: false,
  keySeparator: false,
  fallbackLng: [],
  resources
}).then(t => {
  console.log(t('hi'))
})
```

## Expected behavior

I would expect the console to log `translated`. Instead, I get `hi`.

## Your Environment

- *runtime version*: node 16.9.1
- *i18next version*: i.e. 21.5.3
- *os*: Mac

I noticed that if I change the resource's locale to have a capital H in`zh-Hant-HK` things will work as expected, and that the `lng` in  `i18next.init` can be either `zh-hant-HK` or `zh-Hant-HK`

**Comment by adrai** [comment]
The correct locale is: `'zh-Hant-HK'`
https://www.i18next.com/how-to/faq#how-should-the-language-codes-be-formatted
https://www.iana.org/assignments/lang-tag-apps/zh-Hant-HK
