### ISSUE TITLE
Module federation "No version" warning as a shared module with version >= 21.5.0

### ISSUE THREAD

**Issue by OriAmir** [i18next/i18next#1699]
I think that issue relates to here more than the [module fedration](https://github.com/module-federation/module-federation-examples) plugin.

After upgrading to version `21.5.0` this error appears:

```
WARNING in shared module i18next -> C:\repos\module-federation-with-i18n-issue\app2\node_modules\i18next\dist\esm\i18next.js
No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file, or manually specify version in shared config.
```
full information :
https://github.com/module-federation/module-federation-examples/issues/1248

**Comment by adrai** [comment]
Can you try with 21.5.4?

**Comment by indraraj** [comment]
> Can you try with 21.5.4?

thanks this works, though I was getting the same issue in 21.5.3
