### ISSUE TITLE
Upgrading from v20 to v21 breaks custom backend

### ISSUE THREAD

**Issue by reZach** [i18next/i18next#1700]
## 🐛 Bug Report

Upgrading from v20.6.1 to v21.0.0 causes a custom [backend](https://github.com/reZach/i18next-electron-fs-backend/blob/master/src/index.js) to stop working. I reviewed the [migration guide](https://www.i18next.com/misc/migration-guide#v-20-x-x-to-v-21-0-0) and did not see any changes that would imply a custom backend stops working. _Roughly_, this is the contents of my custom backend

```js
class Backend {
    constructor(services, backendOptions = {}, i18nextOptions = {}) {
        this.init(services, backendOptions, i18nextOptions);   
    }

    init(services, backendOptions, i18nextOptions) {
        // init code
    }

    // Writes a given translation to file
    write(writeQueue) {
        // code
    }

    // Reads a given translation file
    requestFileRead(filename, callback) {
        // code
    }

    // Reads a given translation file
    read(language, namespace, callback) {
        // code
    }

    // Not implementing at this time
    readMulti(languages, namespaces, callback) {
        throw "Not implemented exception.";
    }

    // Writes a missing translation to file
    create(languages, namespace, key, fallbackValue, callback) {
        // code
    }
}
Backend.type = "backend";

export default Backend;
```

## To Reproduce

```
git clone https://github.com/reZach/secure-electron-template.git
cd secure-electron-template
// change i18next dependency in package.json from ^20.6.1 to ^21.0.0
npm i
npm run dev
```

## Expected behavior

I expect the following error will not be thrown; **"Uncaught TypeError: Cannot read property 'use' of undefined"**

![image](https://user-images.githubusercontent.com/4740370/144176990-ad6ca890-2cb6-40a8-b1c3-ee72afa17cad.png)

## Your Environment

- *runtime version*: node v16.13.0, electron v13.6.2
- *i18next version*: 21.0.0 (20.6.1 does not have this issue)
- *os*: Windows

**Comment by jamuhl** [comment]
'Cannot read property "use" of undefined' -> looks more like i18n is undefined -> check the import (might be const i18n = require("i18next");)

**Comment by adrai** [comment]
I don't know why you used .default, but this fixes it:
![image](https://user-images.githubusercontent.com/1086194/144186403-a313eff1-4017-4c6e-be41-13fb65cd1921.png)

btw: whitelist does not exist anymore:
![image](https://user-images.githubusercontent.com/1086194/144186435-90108551-1fe0-44bb-8adb-7d6e83634702.png)
https://www.i18next.com/misc/migration-guide#removed-deprecated
![image](https://user-images.githubusercontent.com/1086194/144186475-a7bcb197-cc5b-41f4-b2ae-3f5e6338c2d2.png)

**Comment by reZach** [comment]
Thanks @adrai / @jamuhl, I'll apply these changes!
