### ISSUE TITLE
forEach loop breaking when no namespaces are set on init

### ISSUE THREAD

**Issue by DannyvanHolten** [i18next/i18next#1709]
## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
import i18n from "i18next";
import Backend from "i18next-http-backend";
import { initReactI18next } from "react-i18next";

i18n
  .use(Backend)
  .use(initReactI18next)
  .init({
     ns: [],
   })
```
Console error:
```
react_devtools_backend.js:4045 TypeError: Cannot read properties of undefined (reading 'forEach')
    at i18next.js:880
    at Array.forEach (<anonymous>)
    at Translator.resolve (i18next.js:865)
    at Translator.translate (i18next.js:744)
    at I18n.t (i18next.js:2544)
    .... etc.
```

## Expected behavior

I'm trying to upgrade from i18next 20 to i18next 21. In our app we do not load any namespaces by default and have no default translations file (all is being imported through the use of namespaces through component hooks).

Because my array of in `ns` is empty it breaks initialization. And it requires me to specify a namespaces that is loaded by default which I don't want to.

I believe this is because how the new `defaultNs` is being loaded. It seems to not check if the `ns` property actually contains values or is an empty array.

## Your Environment

- *runtime version*: node 14
- *i18next version*: i18next 21.1.6 (upgrading from 20.3.1)
- *os*: Mac
- *any other relevant information*: Running together with i18next-backend and i18next-react

**Comment by adrai** [comment]
Can you please provide a reproducible example? I'm not able to reproduce it.

**Comment by adrai** [comment]
I found it...
Can you try with v21.6.1?

**Comment by DannyvanHolten** [comment]
It is indeed fixed. WOW, this was so fast. Thanx for that!

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏

**Comment by DannyvanHolten** [comment]
P.S: Did you leave in a rogue console.log?

My console is printing my namespaces.

**Comment by adrai** [comment]
yep, sorry... v21.6.2
