### ISSUE TITLE
Using a supported language as part of a key returns the full translation object if the first language returned by the language detector doesn't have translations.

### ISSUE THREAD

**Issue by fmaximus** [i18next/i18next#1710]
## 🐛 Bug Report

Using a supported language as part of a key returns the full translation object if the first language returned by the language detector doesn't have translations.

## To Reproduce

* /locales/en/translation.json
  ```json
  {
    "languages": {
      "en": "English",
      "fr": "French"
    } 
  }
  ```
* i18n.ts
  ```ts
  import i18n from 'i18next';
  import Backend from 'i18next-http-backend';
  import LanguageDetector from 'i18next-browser-languagedetector';
  import {initReactI18next} from 'react-i18next';

  i18n
    .use(Backend)
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
      fallbackLng: 'en',
      backend: {
        loadPath: '/locales/{{lng}}/{{ns}}.json',
      },
  });
  ```

Calling `i18next.t("languages.en")` gives warning `accessing an object - but returnObjects options is not enabled!`
Calling `i18next.t("languages.en", {returnObjects: true })` returns
```
{
  translation: {
    languages: {
      "en": "English",
      "fr": "French"
    }
  }
}
```

### Call trace

* `Translator.translate("languages.en")`
* `Translator.resolve(["languages.en"])`
  * keys = `["languages.en"]`
  * namespaces = `["translation"]`
  * codes = `["en-US", "en"]`
* `Translator.getResource("en-US", "translation", "languages.en")`
* `ResourceStore.getResource("en-US", "translation", "languages.en")`
  * path = `['en-US', 'languages', 'languages', 'en']`
  * this.data
     ```
    {
        en: {
            translation: {
                languages: {
                     "en": "English",
                     "fr": "French"
                 }
             }
         }
    }
    ```
* `utils.getPath(data, ['en-US', 'translation', 'languages', 'en'])`
* `utils.getLastOfPath(data, ['en-US', 'translation', 'languages', 'en'])` 
  1. stack =  `['en-US', 'translation', 'languages', 'en']` 
  2. stack.shift
     ```js
     key = 'en-US'
     stack =  ['translation', 'languages', 'en']
     data['en-US'] = undefined

  3. stack.shift
     ```js
     key = 'translation'
     stack =  ['languages', 'en']
     data['translation'] = undefined
  4. stack.shift
     ```js
     key = 'languages'
     stack =  ['en']
     data['languages'] = undefined
  5. stack.shift
     ```js
     key = 'en'
     stack =  []
     data['en'] = {
            translation: {
                languages: {
                     "en": "English",
                     "fr": "French"
                 }
             }
         }
     }

## Expected behavior

As there is no translation available for `en-US`, 
return the translation found for `en`

```js
i18next.t("languages.en") === "English"
```

## Your Environment

- *runtime version*: browser
- *i18next version*: 19.8.5
- *os*: Windows

**Comment by adrai** [comment]
Can you please provide a reproducible example?
I'm not able to reproduce it.

Example: https://codesandbox.io/s/react-i18next-example-forked-tsvhm?file=/src/app.js:482-499

**Comment by fmaximus** [comment]
Right, seems to be fixed in the latest version.
When I change the version to the one I mentioned, it fails.
