### ISSUE TITLE
When does `.init` return an error?

### ISSUE THREAD

**Issue by rabidale** [i18next/i18next#1714]
## Documentation issue

Hi all, I've been working on a fresh implementation of i18next for our React-Native application. While I'm able to get things up and running, I discovered a weird question while writing tests. Our current initialization call looks similar to this:

```
i18next.init(
  {
    fallbackLng: config.fallback,
    ns: config.ns,
    defaultNS: config.defaultNS,
    interpolation: {
      escapeValue: false,
    },
    compatibilityJSON: 'v3',
  },
  error => {
    if (error) {
  console.log(error)
    } else {
      // report that initialization is completed
    }
  }
)
```

With this basic initialization, is there any way an error can be returned? I dug through the source code of the initialization function ([link](https://github.com/i18next/i18next/blob/master/src/i18next.js#L53)) and it appears that the initialization function will only throw an error if you are calling `.use` _and_ the module that you are using has an issue.

In the code example for the callback setup in the "Basic Sample" portion of the documentation ([link](https://www.i18next.com/overview/getting-started#basic-sample)), as well as the code example in the API section of of the documentation ([link](https://www.i18next.com/overview/api#init)), the example includes a callback that is looking for a potential error even though `.use` isn't ever called.

Is there a way for these examples to ever return an error in the callback for `.init` or is there something I'm missing?

## Motivation

My motivation for this post is to hopefully clarify the documentation for the `.init` function, as I don't see where the possible error outcomes are documented other than the source code. I think it is valuable to provide info on how this function could error out (even if it is only from calling `.use` with a bad parameter) so that we can write tests appropriately.

**Comment by adrai** [comment]
![image](https://user-images.githubusercontent.com/1086194/147947277-948941b5-2a36-40ab-b231-d63db69f86a7.png)

https://github.com/i18next/i18next/blob/master/src/i18next.js#L202

It's ok, to ignore that error on init if you want to. Alternatively there's also the [onFailedLoading event](https://www.i18next.com/overview/api#onfailedloading).

Additionally, setting the debug flag to true, will print additional information to the developer console.

**Comment by rabidale** [comment]
Thanks for the response, that helps a bit. For testing purposes, how could we intentionally trigger an `onFailedLoading` event? Would it still require us to pass a bad plugin as a param to the `.use` function?

**Comment by adrai** [comment]
onFailedLoading is never triggered by the .use function... it is triggered by the injected backend....

To trigger this programmatically in a hackie way, you could do something like this:

```js
      i18next.on('failedLoading', (lng, ns, msg) => {
        console.log({lng, ns, msg})
      });

      setTimeout(() => {
        i18next.emit('failedLoading', 'en', 'translation', 'some error');
      }, 2000)
```

**Comment by rabidale** [comment]
Got it, thanks for the help!
