### ISSUE TITLE
Passed format parameter value is truncated in options argument of custom formatter

### ISSUE THREAD

**Issue by ericb97** [i18next/i18next#1715]
## 🐛 Bug Report

When using a custom formatter, any passed parameter value with a colon in it is not fully passed to the formatter, but truncated at the colon.

## To Reproduce

See [codesandbox](https://codesandbox.io/s/agitated-galois-rmgek?file=/src/index.ts).

## Expected behavior

A colon in a parameter value should be passed along with the value after the colon.

```js
i18next.init({
  lng: "en",
  resources: {
    en: {
      translation: {
        key: "Before {{date, customdate(format: EEEE d MMMM yyyy HH:mm; otherParam: 0)}}",
      }
    }
  }
});

i18next.services.formatter.add("customdate", (value, lng, options) => {
  return `customized date in format ${options.format} (and other param ${options.otherParam})`;
});

const now = new Date();
document.getElementById("app").innerHTML = i18next.t("key", { date: now });
// Before customized date in format EEEE d MMMM yyyy HH:mm (and other param 0)
```

## Your Environment

- *runtime version*: node v14.16.0
- *i18next version*: 21.6.4
- *os*: Linux

**Comment by adrai** [comment]
should be fixed with v21.6.5

**Comment by ericb97** [comment]
Thanks for the very fast fix!

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
