### ISSUE TITLE
Allow nested namespaces in fallbackNS

### ISSUE THREAD

**Issue by rfalke** [i18next/i18next#1717]
## 🚀 Feature Proposal

Allow to address not only top-level namespace but also deeper namespaces.

## Motivation

For reasons outside of i18next the translation JSON files have to have a certain top-level namespace. It would be nice if i18next allows to specify a nested namespace as default one.

## Example

`translations_en.json`:
```
{
  "component-name": {
    "translations": {....},
    "errors": {...},
    "some-key": "....",
   ...
}
```

In the config there is:
```
    defaultNS: 'component-name',
```
If the bulk of the keys are in "translations" I would like to denote this as fallback NS:
```
    fallbackNS: 'component-name.translations',
```

**Comment by jamuhl** [comment]
where does namespace end and key nesting begin? looks to me this will introduce more pain than help the majority....but if you see a solution that does not overcomplicate things...feel free to suggest a solution providing a PR for review.

**Comment by adrai** [comment]
fyi: maybe getFixedT with keyPrefix option may help?

https://www.i18next.com/overview/api#getfixedt

**Comment by rfalke** [comment]
> where does namespace end and key nesting begin? looks to me this will introduce more pain than help the majority....but if you see a solution that does not overcomplicate things...feel free to suggest a solution providing a PR for review.

AFAI understood the `fallbackNS` is only about namespaces. So I would think the options would be split somewhere. And in https://github.com/i18next/i18next/blob/9331e28c76cb46007d4a63a95d36dfeaabcfc862/i18next.js#L517 
```
var path = [lng, ns];
```
needs to change so that path becomes `["en", "component-name", "translations"]` afterwards.

**Comment by rfalke** [comment]
> fyi: maybe getFixedT with keyPrefix option may help?
> 
> https://www.i18next.com/overview/api#getfixedt

Maybe.

Another idea would be to pre-process the translations before being passed to i18next.init() so that
```
{
  "component-name": {
    "translations": {....},
    "errors": {...},
    "some-key": "....",
   ...
}
```
becomes
```
{
  "translations": {....},
  "errors": {...},
  "some-key": "....",
   ...
}
```
