### ISSUE TITLE
unexpected at i18next.t

### ISSUE THREAD

**Issue by 86driver** [i18next/i18next#1719]
## resource
```
resource: {
  "zh_CN": {
      "translate": {
         "a.b": "ab",
         "a.b.c": "abc"
      }
  }
}
```

## use
`console.lot(i18next.t("a.b.c.d")). // output: ab `
why not output missing key a.b.c.d

it seems find a.b to the key,    how can i solve this problem,

please...

**Comment by adrai** [comment]
I can confirm...
will try to fix it in the next hours...

**Comment by adrai** [comment]
v21.6.6 fixes it

**Comment by 86driver** [comment]
> v21.6.6 fixes it

Thanks
