### ISSUE TITLE
Do not work nesting

### ISSUE THREAD

**Issue by dmalinovskiy** [i18next/i18next#1720]
## 🐛 Bug Report

Do not work nesting from documentation:
https://www.i18next.com/translation-function/nesting#passing-nesting-to-interpolated

## To Reproduce

Run code:

```js
const i18next = require('i18next');

const run = async () => {
  await i18next.init({
    lng: 'en', // if you're using a language detector, do not define the lng option
    debug: true,
    resources: {
      en: {
        translation: {
          "key1": "hello world",
          "key2": "say: {{val}}"
        }
      }
    }
  });

  console.log(i18next.t('key2', {val: '$t(key1)'}));
};

run();
```

## Expected behavior

i18next.t('key2', {val: '$t(key1)'});
// -> "say: hello world"

## Actual behavior

say: $t(key1)

## Your Environment

- *runtime version*:  node v14.16.1
- *i18next version*:  21.6.6
- *os*:  macOs 11.6.1

**Comment by adrai** [comment]
Since v21.0.0 you need to set skipOnVariables to false: https://www.i18next.com/misc/migration-guide#skiponvariables-true
![image](https://user-images.githubusercontent.com/1086194/149336683-cdaf3b76-d29c-434d-aa9d-3a6c8732384e.png)

**Comment by dietergeerts** [comment]
Any idea if this can be split, in like allowing nesting with `$t`, but keep the skipping on interpolation variables? If I just use nesting, no interpolation, it also doesn't work. We do have deep objects, so maybe that's why it doesn't work in our case?

```
{
  "ACTION": {
    "CREATE": {
      "LABEL": "Create"
    }
  },
  "REPORTS": {
    "CONSULTATION": {
      "WIZARD": {
        "SUBMIT": {
          "LABEL": "$t(ACTION.CREATE.LABEL)"
        }
      }
    }
  }
}
```

**Comment by adrai** [comment]
> Any idea if this can be split, in like allowing nesting with `$t`, but keep the skipping on interpolation variables? If I just use nesting, no interpolation, it also doesn't work. We do have deep objects, so maybe that's why it doesn't work in our case?
> 
> 
> 
> ```
> 
> {
> 
>   "ACTION": {
> 
>     "CREATE": {
> 
>       "LABEL": "Create"
> 
>     }
> 
>   },
> 
>   "REPORTS": {
> 
>     "CONSULTATION": {
> 
>       "WIZARD": {
> 
>         "SUBMIT": {
> 
>           "LABEL": "$t(ACTION.CREATE.LABEL)"
> 
>         }
> 
>       }
> 
>     }
> 
>   }
> 
> }
> 
> ```

I don't see any variable in your example, so this should work without any issues.
Can you please provide a reproducible example?

**Comment by dietergeerts** [comment]
@adrai , you are right, the option isn't needed. I was mistaken that it was, because the docs make it seem that nesting and interpolation are like almost the same.

After debugging and trying out some things, I see the issue. When I add the namespace (even though the referenced key is in the same namespace), it works. So I guess, once you have multiple namespaces, you always need to add the namespace to it?

**Comment by adrai** [comment]
it will use your fallbackNS
