### ISSUE TITLE
Inconsitent matching for capitalized formatters

### ISSUE THREAD

**Issue by bratzie** [i18next/i18next#1722]
## Documentation issue

I recently did an upgrade from an older version and spent a lot of time confused about why my `numberCompact` formatter stopped working. I read through the formatting documentation a few times, but couldn't figure out why. I started to expect it being something along the lines of the word `number` being reserved somehow. Then I started digging into the Formatting code and noticed that you lowercase the formatting references, so adding `numbercompact` as a formatter works, even though my formatting in the (v3) JSON still has an uppercase C. The relevant code for this is found [here](https://github.com/i18next/i18next/blob/9331e28c76cb46007d4a63a95d36dfeaabcfc862/src/Formatter.js#L4-L8) (I think?).

## Motivation

I think either removing the lowercasing or lowercasing in both places make sense. It would probably be reasonable to add something about only being able to add lowercase formatters to the docs over here as well.

![image](https://user-images.githubusercontent.com/1047235/150543560-2fa5677a-e192-4049-9b41-137b57c9cdee.png)

**Comment by bratzie** [comment]
I wasn't sure whether it was a bug, documentation issue or user error. So with that fix, it won't be possible to add one called numbercompact and one called numberCompact and use them separarely? (Just asking, I don't see why anyone would do that).

Thank you for the quick fix btw :)

**Comment by adrai** [comment]
yes
