### ISSUE TITLE
`hasLoadedNamespace` marked as `void` an description says „Changes the default namespace.“

### ISSUE THREAD

**Issue by ckruse** [i18next/i18next#1723]
The method `hasLoadedNamespace` is marked as `void` and the description says „Changes the default namespace.“ I guess, based on the name and the fact that this is the same description as the description for the method above (`setDefaultNamespace`) I guess that it is just a typo in the types file?

**Comment by adrai** [comment]
Yes. Would you like to send a Pull Request to address this?

**Comment by ckruse** [comment]
Yup. Done.

**Comment by adrai** [comment]
Thank you, v21.6.10 is released

**Comment by ckruse** [comment]
Thanks for you work! ❤️

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
