### ISSUE TITLE
Plural and context incompatible with `returnObjects`

### ISSUE THREAD

**Issue by jqhoogland** [i18next/i18next#1725]
## 🐛 Bug Report

When using `returnObjects`, context and plural markers (`_male`, `_female`, `_zero`, `_one`...) are left as is rather than replaced.

In principle, this could be a separate feature (it doesn't have to be a bug), but the docs do misleadingly say "The returned value supports interpolation, plurals, nesting, ..." ([see here](https://www.i18next.com/translation-function/objects-and-arrays)).

## To Reproduce

Quick example:
```json
 "custom":{
    "name": "Custom Visibility",
    "description_self_zero": "Only selected friends can see this {{item}}.",
    "description_self_one": "Visible to {{audience.0}}",
    "description_self_two": "Visible to {{audience.0}} and {{audience.1}}.",
    "description_self_three": "Visible to {{audience.0}}, {{audience.1}}, and {{audience.2}}",
    "description_self_other": "Visible to: {{audience}}",
    "description_others": "Only selected friends can see this {{item}}." 
}
```

If I now run, `t("custom", {returnObjects: true,  audience: ["hello", "world"], item: "post", context: "self"})`, I'll get back the following:

```js
{
  description_others: "Only selected friends can see this post.",
  description_self_one: "Visible to hello",
  description_self_other: "Visible to: hello,world",
  description_self_three: "Visible to hello, world, and {{audience.2}}",
  description_self_two: "Visible to hello and world.",
  description_self_zero: "Only selected friends can see this post.",
  name: "Custom"
}
```

## Expected behavior

What I'd like to get is:

```js
{
  description: "Visible to hello and world.",
  name: "Custom"
}
```

At the very least, It'd be nice to have an option that lets me choose between the two ways of rendering objects.

**Comment by jamuhl** [comment]
your expected behavior is not what returnObject was done for -> it's just returning everything interpolated, nested, ... (eg. to pass it to some rich component) but not selecting a plural or context and mix that with other content

**Comment by jqhoogland** [comment]
Ok I'm closing this and making a feature request. 

In any case, it's confusing that the docs say "The returned value supports interpolation, plurals, nesting, ..."
