### ISSUE TITLE
Handling plurals and contexts with returnObjects #1725

### ISSUE THREAD

**Issue by jqhoogland** [i18next/i18next#1726]
(This came out of [what I thought was a bug](https://github.com/i18next/i18next/issues/1725).)

## 🚀 Feature Proposal

Add an option (like `returnObjects`), maybe `parseObjects` (?), to parse context and plural markers (`_male`, `_female`, `_zero`, `_one`...). 

## Motivation

In combination with object destructuring, this would make it easier and cleaner to get several translations at once. See example.

## Example

Suppose you have the following key:

```json
 "custom":{
    "name": "Custom Visibility",
    "description_self_zero": "Only selected friends can see this {{item}}.",
    "description_self_one": "Visible to {{audience.0}}",
    "description_self_two": "Visible to {{audience.0}} and {{audience.1}}.",
    "description_self_three": "Visible to {{audience.0}}, {{audience.1}}, and {{audience.2}}",
    "description_self_other": "Visible to: {{audience}}",
    "description_others": "Only selected friends can see this {{item}}." 
}
```

If I run,`t("custom", {returnObjects: true,  audience: ["hello", "world"], item: "post", context: "self"})` (maybe with an additional option like `parseOptions: true`), I'd like to get back:

```js
{
  description: "Visible to hello and world.",
  name: "Custom"
}
```

Instead of (what is currently returned):

```js
{
  description_others: "Only selected friends can see this post.",
  description_self_one: "Visible to hello",
  description_self_other: "Visible to: hello,world",
  description_self_three: "Visible to hello, world, and {{audience.2}}",
  description_self_two: "Visible to hello and world.",
  description_self_zero: "Only selected friends can see this post.",
  name: "Custom"
}
```

Now I can use object destructuring to get all of my translations for what I'm working on in one place. It's easier to get an overview (of where my translation are) and cleaner.

```js
const {name, description} = t("custom", {...})

```

**Comment by adrai** [comment]
Such a feature would complicate a lot of things...
Is this that much worse for you?

```js
const name = t("custom.name")
const description = t("custom.description", {
  audience: ["hello", "world"],
  context: "self",
  count: 2
})
```

**Comment by jqhoogland** [comment]
In this case there are five other visibility levels, so it would make it considerably more elegant. 

I can do:

```js
const results = {}

// "private", "public", "custom"...
levels.forEach((level) => {
  const name = t(`visibility.${level}.name`)
  const description = t(`visibility.${level}.description`, {
    audience: ["hello", "world"],
    context: "self",
    count: 2
  })
  results[level] = { name, description}
})

// { private: {name: ..., description: ...}, ... }
```

How nice it would be to do!
```js
const results = t("visibility",  {
  audience: ["hello", "world"],
  context: "self",
  count: 2
})
```

Not super urgent, I'm just throwing the request out there.
