### ISSUE TITLE
Typescript definitions are incompatible with CommonJS module

### ISSUE THREAD

**Issue by krzysztof-cislo** [i18next/i18next#1727]
## 🐛 Bug Report

Bundled typescript definitions are incompatible with dist/cjs/i18next.js. This makes impossible/hard to use i18next library in TS projects where CJS modules are used. As far as I can see only ESM module is compatible with bundled index.d.ts.

## Your Environment

- *runtime version*: 16.13.1
- *i18next version*: 21.6.10

**Comment by adrai** [comment]
Please provide more information and a reproducible example.

**Comment by krzysztof-cislo** [comment]
Here is a minimum working example. 
https://github.com/krzysztof-cislo/webpack-i18next

Sorry i forgot to mention that I use webpack 5 as a bundler.

How to reproduce it? Please just do:
- `npm i`
- `npm run build`
- `node `dist/index.js`

You should see this error:
```
webpack://webpack-18next/./src/index.ts?:4
console.log(i18next_1.default.language);
                              ^
TypeError: Cannot read properties of undefined (reading 'language')
```

**Comment by adrai** [comment]
Try to set `"esModuleInterop": true` in the `tsconfig.json`:
![image](https://user-images.githubusercontent.com/1086194/152178090-4f137d1b-1801-45cc-9f71-a6a257ea802f.png)

**Comment by krzysztof-cislo** [comment]
Thanks!
