### ISSUE TITLE
React Native - Android - JSON parse fails

### ISSUE THREAD

**Issue by criszz77** [i18next/i18next#1729]
## 🐛 Bug Report

Hello!

Thank you for such an amazing library. I've been using it on web projects with React and I can honestly say I love it.

I'm going through the process of setting this up with **React Native**. Everything works very well on **IOS**, however, on **Android**  for certain languages (e.g. en_US) I have the following issue: 

![image](https://user-images.githubusercontent.com/55203625/153010313-96d19ef6-83ad-4c74-9ce9-8614a76b0e8b.png)

## To Reproduce

This is my code:

```js
import i18n from 'i18next';
import HttpApi from 'i18next-http-backend';
import { initReactI18next } from 'react-i18next';
import { getLocales } from 'react-native-localize';

i18n
  .use(HttpApi)
  .use(initReactI18next)
  .init({
    compatibilityJSON: 'v3', // <-- this line here only removes the Intl.PluralRules error, but json still fails to parse
    backend: {
      loadPath: 'https://ed.engdis.com/Languages/{{lng}}.json',
    },
    lng: getLocales()[0].languageTag.replace('-', '_'),
    fallbackLng: 'es_ES',
    supportedLngs: [
      'ar_??', // ara    - Arabic
      'pt_BR', // brz    - Portuguese (Brazil),
      'zh_TW', // chi    - Chinese (Traditional
      'zh_CN', // chs    - Chinese (Simplified)
      'ht_HT', // cre    - Haitian Creole
      'en_US', // en/eng - English (USA),
      'fil', //   fil    - Filipino,
      'de_DE', // ger    - Germany (Germany),
      'el_GR', // gre    - Greek (Greece)
      'he_IL', // heb    - Hebrew (Israel)
      'id_ID', // ind    - Bahasa (Indonesia),
      'it_IT', // ita    - Italian (Italy)
      'ja_JP', // jpn    - Japanese (Japan)
      'ko_KR', // kor    - Korean (Korea)
      'mn_MN', // mon    - Mongolian (Mongolia)
      'pt_PT', // por    - Portuguese (Portugal)
      'ru_RU', // rus    - Russian (Russia)
      'sl_SL', // slv    - Slovenian (Slovenia)
      'es_ES', // spa    - Spanish (Spain)
      'th_TH', // tha    - Thai (Thailand)
      'tr_TR', // tur    - Turkish (Turkey)
      'vi_VN', // vie    - Vietnamese (Vietnam)
    ],
    debug: process.env.NODE_ENV === 'development',
    interpolation: {
      escapeValue: false,
    },
    keySeparator: false,
    preload: ['en_US'],
  });

export default i18n;
```

## Expected behavior

Successfully parse the json file for all languages.

## Your Environment

- *runtime version*: react-native 0.67.2,
- *i18next version*:   

react-i18next 11.15.3
i18next 21.6.11 
i18next-http-backend 1.3.2
- *os*: Mac, Windows, Linux: MacOS Monterey 12.0.1 Apple Silicon

**Comment by adrai** [comment]
You may need to polyfill the Intl API for android: https://www.i18next.com/translation-function/plurals
btw: try to use correctly formatted language codes: https://www.i18next.com/how-to/faq#how-should-the-language-codes-be-formatted

**Comment by criszz77** [comment]
> You may need to polyfill the Intl API for android: https://www.i18next.com/translation-function/plurals

I tried the polyfill and it does not seem to work either. 

> btw: try to use correctly formatted language codes: https://www.i18next.com/how-to/faq#how-should-the-language-codes-be-formatted

Unfortunately, I'm building a new mobile app version for an existing backend which has everything ready for me this way.

**Comment by adrai** [comment]
How does the en_US.json look like? is it a valid JSON?

**Comment by adrai** [comment]
There's also the possibility to pass your own parse functionality: https://github.com/i18next/i18next-http-backend#backend-options

`parse: function(data) { return JSON.parse(data); },`

You could try to console.log there, and see what happens when JSON.parsing...

**Comment by criszz77** [comment]
`How does the en_US.json look like? is it a valid JSON?`

It's the **loadPath** in the backend options. You can try it yourself: https://ed.engdis.com/Languages/en_US.json

`Does it work if you directly parse in with JSON.parse() in android?`

Ok, it fails exactly here. 🤔

**Comment by adrai** [comment]
https://stackoverflow.com/questions/59000260/failing-to-parse-json-from-response-on-android-but-works-on-ios-react-native
https://github.com/facebook/react-native/issues/25701

Sorry, I'm not a mobile developer... might be some hackie android stuff...

**Comment by criszz77** [comment]
Don't worry, this was very helpful actually. I'll come back with a solution in case anybody else faces this problem.
