### ISSUE TITLE
Adding mutliple fallback languages causes site to not load

### ISSUE THREAD

**Issue by alexistbell** [i18next/i18next#1730]
We are using i18next with Locize for our translations. As we've added in more languages we've run  into an issue with Chinese. Locize uses the langauge codes zh-Hans and zh-Hant but the browser reports zh-CN and zh-TW. So we tried setting up fall back langagues like this:

```
import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
import Backend from 'i18next-locize-backend'

const languages = ['ar', 'de', 'en', 'es', 'es-MX', 'fi', 'fr', 'it', 'iw', 'ja', 'ko', 'nb', 'nl', 'sv', 'zh-CN', 'zh-TW', 'zh-Hans', 'zh-Hant']

i18n
  .use(initReactI18next)
  .use(LanguageDetector)
  .use(Backend)
  .init({
    debug: false,
    supportedLngs: languages,
    fallbackLng: {
      'zh-CN': ['zh-Hans'],
      'zh-TW': ['zh-Hant'],
      'default': ['en']
    },
    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
      format: (value, format, lng) => {
        if (value instanceof Date) {
          return DateTime.fromJSDate(value).setLocale(lng).toLocaleString(DateTime[format])
        }
        return value
      }
    },
    backend: locizeOptions,
    saveMissing: true
)}
```

originally we had fallbackLng just set to 'en' and everything works fine. If we leave it that way and switch the browser to one of the Chinese localizations the site runs fine, but it's in english. With the fallbackLng object we get this error in the browser window:

```
×
TypeError: Cannot set properties of undefined (setting 'undefined')
setPath
node_modules/i18next/dist/esm/i18next.js:227
  224 |       obj = _getLastOfPath.obj,
  225 |       k = _getLastOfPath.k;
  226 | 
> 227 |   obj[k] = newValue;
  228 | }
  229 | function pushPath(object, path, newValue, concat) {
  230 |   var _getLastOfPath2 = getLastOfPath(object, path, Object),
View compiled
ResourceStore.addResource
node_modules/i18next/dist/esm/i18next.js:455
  452 |     }
  453 | 
  454 |     this.addNamespaces(ns);
> 455 |     setPath(this.data, path, value);
      | ^  456 |     if (!options.silent) this.emit('added', lng, ns, key, value);
  457 |   }
  458 | }, {
View compiled
Connector.saveMissing
node_modules/i18next/dist/esm/i18next.js:2037
  2034 |     }
  2035 | 
  2036 |     if (!languages || !languages[0]) return;
> 2037 |     this.store.addResource(languages[0], namespace, key, fallbackValue);
       | ^  2038 |   }
  2039 | }]);
  2040 | 
View compiled
send
node_modules/i18next/dist/esm/i18next.js:773
  770 | if (_this2.options.missingKeyHandler) {
  771 |   _this2.options.missingKeyHandler(l, namespace, k, defaultForMissing, updateMissing, options);
  772 | } else if (_this2.backendConnector && _this2.backendConnector.saveMissing) {
> 773 |   _this2.backendConnector.saveMissing(l, namespace, k, defaultForMissing, updateMissing, options);
      | ^  774 | }
  775 | 
  776 | _this2.emit('missingKey', l, namespace, k, res);
View compiled
Translator.translate
node_modules/i18next/dist/esm/i18next.js:787
  784 |         });
  785 |       });
  786 |     } else {
> 787 |       send(lngs, key, defaultValue);
      | ^  788 |     }
  789 |   }
  790 | }
View compiled
I18n.t
node_modules/i18next/dist/esm/i18next.js:2562
  2559 |   value: function t() {
  2560 |     var _this$translator;
  2561 | 
> 2562 |     return this.translator && (_this$translator = this.translator).translate.apply(_this$translator, arguments);
       | ^  2563 |   }
  2564 | }, {
  2565 |   key: "exists",
View compiled
fixedT
node_modules/i18next/dist/esm/i18next.js:2544
  2541 |   options.ns = options.ns || fixedT.ns;
  2542 |   var keySeparator = _this5.options.keySeparator || '.';
  2543 |   var resultKey = keyPrefix ? "".concat(keyPrefix).concat(keySeparator).concat(key) : key;
> 2544 |   return _this5.t(resultKey, options);
       | ^  2545 | };
  2546 | 
  2547 | if (typeof lng === 'string') {
```

And nothing specific in the console log. I've tried playing around with what we have in supportedLng including only having the versions of the language code that the browser uses, the ones that locaize uses, and both. That makes no difference and I'm not sure what the correct arrangement would be.

I also noticed the error seems to be around the saveMissing feature, which we've been using for a while with no trouble. I did try adding the ```saveMissingTo: 'en'``` option but it made no difference. And also tried the ```missingKeyNoValueFallbackToKey: true``` in case that was the issue.

We tried updating the packages in case there was a bug fix out there with no luck. So the current versions we are running are: 

```
    "i18next": "^21.6.11",
    "i18next-browser-languagedetector": "^6.1.3",
    "i18next-locize-backend": "^5.0.0",
    "react-i18next": "^11.15.4",
```

Finally the issue isn't just with Chinese although that's where we've been focusing since we can't get any Chinese translations to show up. We've tried adding fallbacks for things like other localizations of Norweigan and French and the same issue happens.

If the issue is in our configuration, it should not crash the whole site, but we should get some sort of message in the console log so we can work on resolveing it. Also it would be great to have better examples of fallback language in the documentation, especially for a case like Chinese which is hardly an obscure language and where the language codes between the browser and locize are not comptable out of the box.

**Comment by adrai** [comment]
Please write an email at support@locize.com and provide your project-id.
If there is a reproducible example provide also an url so it can be checked.
btw: locize can handle any languages, so you can also rename a language, but honestly I don't think this is the root problem.
![image](https://user-images.githubusercontent.com/1086194/153445598-31a0de8a-15d2-4f23-a96b-17bfecd577ad.png)

fyi: will close this issue here, so you can continue via mail
