### ISSUE TITLE
returnEmptyString not effect

### ISSUE THREAD

**Issue by 86driver** [i18next/i18next#1733]
when i set returnEmptyString:true,  show key, not a empty string

version: 21.6.11

**Comment by adrai** [comment]
Can you provide a reproducible example?
Did you do something like this?
<img width="285" alt="image" src="https://user-images.githubusercontent.com/1086194/155302762-cbcaf78b-9ab4-49f0-a8de-99bfbf0c967b.png">

**Comment by 86driver** [comment]
> 

yes, i did so.  it show empty not "",  how can i do

**Comment by adrai** [comment]
this means you probably has no empty key, but no key at all...

seems to work as expected: https://codesandbox.io/s/kind-browser-19lzij?file=/src/index.js
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/1086194/155305315-cc68e953-3fb9-4ff6-b901-f6162b1a7467.png">
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/1086194/155305364-49fe9329-1a65-42ee-875e-1924df305b6d.png">

**Comment by 86driver** [comment]
i am sure the key consist,  
i found when i set `keySeparator: false`, it works fine, but i set `keySeparator: '.'`, it works not fine 

i saw your codesandbox,   it works fine , confused me

@adrai

**Comment by adrai** [comment]
Create a reproducible example, then we can reopen this issue.

**Comment by 86driver** [comment]
i found why cause this problem, because of my config is json not js....    so how can i solve this problem,  json config is necessary

**Comment by adrai** [comment]
> i found why cause this problem, because of my config is json not js.... so how can i solve this problem, json config is necessary. By the way, i cant provide a codesandbox demo...
> 
> @adrai

Without a reproducible example it's not easy to help.
Create a small github repo, with some reproducible steps.
