### ISSUE TITLE
i18next ICU. Using variables in t function 

### ISSUE THREAD

**Issue by IlliaHohniak-Hexa** [i18next/i18next#1737]
I change keys in my project to the ICU format. And I find the difference how Interpolation works in the Trans component and in the t-function. (And in the basic syntax)
1. This key works with Trans component
`"discountReserved": "{{count}}% discount reserved for:"`
```
<Trans i18nKey="discountReserved" count={discount}>
        44% discount reserved for:
</Trans>
```

2. This key works with t-function
`"tryFor": "try for {{currencySign}}{{currentPrice}}",`

`const customButtonTitle = t('tryFor', { currencySign, currentPrice });`

In the second case double {} doesn't work. But single {} works fine: 
`"tryFor": "try for {currencySign}{currentPrice}",`

And in the Trans double {} works perfect. Also, it works fine in Trans and t-function when I used non-ICU syntax.

QUESTION: 
How can I rewrite t-functions to make this key works?
And why are here differences in the Trans and t-function behavior?

It hard to rewrite all the same keys and start the process of the translation. So I want to find another way.

**Comment by adrai** [comment]
This may help: https://react.i18next.com/misc/using-with-icu-format#using-the-trans-component

**Comment by IlliaHohniak-Hexa** [comment]
In this and some other cases I cann't use Trans and I have to use t-function

**Comment by IlliaHohniak-Hexa** [comment]
In this and some other cases I cann't use Trans and I have to use t-function

**Comment by adrai** [comment]
double {} are for i18next format: https://www.i18next.com/misc/json-format
so when you switch to ICU you should just use the ICU format

**Comment by adrai** [comment]
You can't mix i18n format.
So if you're using ICU make sure all your translations are correct ICU format.

**Comment by IlliaHohniak-Hexa** [comment]
But it works with Trans. So why it doesn't work in t-function?

**Comment by adrai** [comment]
It is not guaranteed to work... it may work, because the Trans component is not optimal for ICU usage, and will fallback somehow to the i18next format... but this is not intended as a "feature"

**Comment by IlliaHohniak-Hexa** [comment]
Ok, I see. Thanks

**Comment by jamuhl** [comment]
simple rule. Using ICU don‘t use objects in children. no double {{}}. 

use props like defaults and values with proper icu syntax


<Trans
  i18nKey="icu_and_trans"
  defaults="We invited <0>{user}</0>."
  components={[<strong>dummyChild</strong>]}
  values={{ user }}
/>
