### ISSUE TITLE
Cannot disable grouping using number formatter with options embedded in interpolation string.

### ISSUE THREAD

**Issue by jules-ofs** [i18next/i18next#1738]
## 🐛 Bug Report

Cant disable grouping when using number formatter with options embedded in interpolation string.

## To Reproduce

https://codesandbox.io/s/vigorous-https-cpkyhb?file=/src/index.ts

## Expected behavior

Expect 
```js
i18n.services.interpolator.interpolate(
  "{{0,number(useGrouping:false)}}",
  [123456],
  "en",
  {}
)
```
to give the result 123456   ,  but I am getting 123,456

This seems to be because of the parseFormatStr routine at https://github.com/i18next/i18next/blob/430a93161b7adaf8580324ea2b2858bd7a2e71a5/src/Formatter.js#L23-L28
Line 28 above seems to undo earlier processing if the formatOption is falsey - which is probably not intended.

## Your Environment

- *runtime version*: i.e. node v14, chrome
- *i18next version*: 21.6.13
- *os*: Linux

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this? Remember to add unit tests.

**Comment by adrai** [comment]
just done so...
v21.6.14 has just been released

**Comment by jules-ofs** [comment]
thankyou!
