### ISSUE TITLE
getFixedT and returnObjects

### ISSUE THREAD

**Issue by hovancik** [i18next/i18next#1740]
## 🐛 Bug Report

`getFixedT` and `returnObjects` does not seems to work together

## To Reproduce

`sk.json`
```js
  "miniBreakIdeas": {
    "aaa": {
      "text": "aaaa!"
    }
  }
```
`en.json`
```js
"miniBreakIdeas": {
    "aaa": {
      "text": "Go grab a glass of water."
    }
}
```

language is `sk`

```js
    const t = i18next.getFixedT('en')
    console.log(i18next.t('miniBreakIdeas', { returnObjects: true }))
    console.log(t('miniBreakIdeas', { returnObjects: true }))
```

```
{ aaa: { text: 'Duj!' } }
miniBreakIdeas
```

## Expected behavior

```js
{ aaa: { text: 'aaaa!' } }
{ aaa: { text: 'Go grab a glass of water.' } }
```

## Your Environment

- *runtime version*: node v16.13.0
- *i18next version*:     "i18next": "^21.6.11",
    "i18next-fs-backend": "^1.1.4",
- *os*: Linux

**Comment by adrai** [comment]
Seems to work as expected: https://codesandbox.io/s/trusting-banzai-6ihu52?file=/src/index.js

Can you provide a reproducible example?

**Comment by hovancik** [comment]
Thanks for quick reply! 

I think it has to with getFixedT not being ready yet? Tried doing some example based on what you got: 

https://codesandbox.io/s/gifted-hooks-2s71qb?file=/src/index.js

without using timeout, i am seeing wrong stuff and it seems to me that I see it as it's what get's printed when `t` is not ready, yet.

**Comment by adrai** [comment]
This makes sense.
You have for i18next to be initialized.
You can see also the console warning logs...

**Comment by adrai** [comment]
```
i18next: hasLoadedNamespace: i18next was not initialized 
i18next::translator: key "[miniBreakIdeas.aaa](http://minibreakideas.aaa/).text" for languages "en" won't get resolved as namespace "translation" was not yet loaded This means something IS WRONG in your setup. You access the t function before i18next.init / i18next.loadNamespace / i18next.changeLanguage was done. Wait for the callback or Promise to resolve before accessing it!!!
i18next: hasLoadedNamespace: i18next was not initialized 
i18next::translator: key "[miniBreakIdeas.aaa](http://minibreakideas.aaa/).text" for languages "sk, en" won't get resolved as namespace "translation" was not yet loaded This means something IS WRONG in your setup. You access the t function before i18next.init / i18next.loadNamespace / i18next.changeLanguage was done. Wait for the callback or Promise to resolve before accessing it!!!
```

**Comment by adrai** [comment]
So, will close this, as this works as expected

**Comment by hovancik** [comment]
But does getFixedT also get initiated? In my app, where workflow is a bit different from that web example, i18next is already initiated. i18next.t works, but t from getFixedT does not.

**Comment by adrai** [comment]
There's not much magic in getFixedT. I suspect there is some timing problem in your setup.
Try to check for i18next.isInitialized before calling getFixedT

**Comment by hovancik** [comment]
Yeah it is initialized, the app is translated. I tried timeout 10 seconds after calling getFixedT but still I am not seeing results I should. 

Thanks for help anyway, I guess I'll need different approach.

**Comment by adrai** [comment]
fyi: if you're using i18next-fs-backend, you can try with `initImediate: false`

<img width="373" alt="image" src="https://user-images.githubusercontent.com/1086194/157877738-c267425b-b87e-4607-9f69-f1c642e24397.png">
