### ISSUE TITLE
how to fix "Invalid regular expression: /( |,|\?|!|;/: Unterminated group"

### ISSUE THREAD

**Issue by dieshangtianya** [i18next/i18next#1744]
### Discussed in https://github.com/i18next/i18next/discussions/1742

<div type='discussions-op-text'>

<sup>Originally posted by **dieshangtianya** March 24, 2022</sup>
I introduce i18next and react-i18next, in most devices the app works great, but in some other android pad,  I encounter a bug that issued by sentry: “Invalid regular expression: /( |,|\?|!|;/: Unterminated group“，I dug into the sourcemap and found it occurred in the **looksLikeObjectPath** function. 

```javascript
var chars = [' ', ',', '?', '!', ';'];
function looksLikeObjectPath(key, nsSeparator, keySeparator) {
  nsSeparator = nsSeparator || '';
  keySeparator = keySeparator || '';
  var possibleChars = chars.filter(function (c) {
    return nsSeparator.indexOf(c) < 0 && keySeparator.indexOf(c) < 0;
  });
  if (possibleChars.length === 0) return true;
  var r = new RegExp("(".concat(possibleChars.map(function (c) {
    return c === '?' ? '\\?' : c;
  }).join('|'), ")"));
  var matched = !r.test(key);

  if (!matched) {
    var ki = key.indexOf(keySeparator);

    if (ki > 0 && !r.test(key.substring(0, ki))) {
      matched = true;
    }
  }

  return matched;
}

```

I am wonder what happen in these devices! why does it happen only in some times? it is only a normal regular expression, and the nsSeparator, keySeparator variables are built-in.  I douted the string.concat function has been modified, maybe the nsSeparator, keySeparator has been changed in some other condition, but all assumptions are being overturned.

Anyone can give some advices about how to figure it out? </div>

**Comment by adrai** [comment]
if you're able to reproduce it, try to only use the regex (without i18next).
It may be some older devices behave differently.

**Comment by dieshangtianya** [comment]
@adrai Thanks for your replay, I will add test for it.

**Comment by dieshangtianya** [comment]
@adrai I add some code to track it as you suggested, the error still occurs in some devices.  the log code as below:
```javascript
  analyseError(error) {
    const errorKeyword = 'Invalid regular expression:';
    if (error && error.message && error.message.indexOf(errorKeyword) > -1) {
      console.log('capture invalid regular expression error');
      try {
        const expression = new RegExp(`(${[' ', ',', '?', '!', ';'].map((c) => (c === '?' ? '\\?' : c)).join('|')})`);
        console.log(expression);
        const result = expression.test('some.key');
        console.log(`regexp test for i18n successed, the result is: ${result}`);
      } catch (err) {
        console.log('regexp test for i18n failed');
        this.logSentry(err);
      }
    }
  }
```
Here when error happen,  call the analyseError function to anylyse it and found that the RegExp function can work normally, and output "regexp test for i18n successed, the result is: false".  

We can found that the device sometimes works great, but sometimes failed, is there any other possible reason for it?

**Comment by adrai** [comment]
Do you know what device?

So you're saying it first fails in i18next and then in the analyzeError function it works?

really strange behaviour

**Comment by TangJian-Eddie** [comment]
I encountered same issue. May I ask if there are any new progress

**Comment by adrai** [comment]
> I encountered same issue. May I ask if there are any new progress

not able to reproduce it
