### ISSUE TITLE
i18next.changeLanguage throws after upgrade to 21.5.0

### ISSUE THREAD

**Issue by eszthoff** [i18next/i18next#1747]
## 🐛 Bug Report

After upgrading to version 2.5.0 or higher changeLocale throws :

```
i18next.js?e390:2427 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toResolveHierarchy')
    at setLngProps (i18next.js?e390:2427:1)
    at setLng (i18next.js?e390:2471:1)
    at I18n.changeLanguage (i18next.js?e390:2488:1)
    at UserSettingsStore.eval (UserSettingsStore.ts?c515:186:17)
```

## To Reproduce
```js
// config file
import i18next from 'i18next';
import { initReactI18next } from 'react-i18next';
import HttpApi from 'i18next-http-backend';

i18next
    .use(HttpApi)
    .use(initReactI18next)
    .init({
        lng: 'en-GB',
        load: 'currentOnly',
        fallbackLng: 'en-GB',
        returnEmptyString: false,
        backend: {
            loadPath: () => 'next-assets/i18n/{{lng}}/translation.json',
            allowMultiLoading: false,
            crossDomain: false,
            withCredentials: false,
            overrideMimeType: false,
        },
    })
```

## Expected behavior

Library doesn't throw an error. Correct language files are loaded into the browser

## Your Environment

- *runtime version*: browser
- *i18next version*: i.e. 21.4.2 / 21.5.0

**Comment by adrai** [comment]
Can you please provide a reproducible example?
I'm not able to reproduce it.

**Comment by adrai** [comment]
this example seems to work: https://codesandbox.io/s/react-i18next-http-example-i1wz6h

**Comment by eszthoff** [comment]
@adrai thanks for the quick answer. I tried to reproduce it on the sandbox, and indeed failed. I still have the error on my end, but I need to leave it, as there are other priorities, and used quite a bit of time for it already. I hope I will be able to get back to it relatively soon.

**Comment by natemartins** [comment]
@eszthoff Were you able to resolve this issue?
