### ISSUE TITLE
React Native Android i18next JSON v4 compatibility 

### ISSUE THREAD

**Issue by uyend** [i18next/i18next#1749]
## 🐛 Bug Report

bumped compatibility v to `v4` from `v3`, but it throws error on Android but on iOS it's working fine
<img width="394" alt="Screen Shot 2022-04-08 at 10 40 43 am" src="https://user-images.githubusercontent.com/41275094/162341196-5646069a-0d47-4107-97af-b27d588a6579.png">

When reverting back to `v3` it does not show pluralisation as expected for both iOS and Android

| iOS v4 | Android v3 + v4 | 
| --- | --- | 
| <img width="496" alt="Screen Shot 2022-04-08 at 10 44 57 am" src="https://user-images.githubusercontent.com/41275094/162341569-ee4ebe69-1d4e-4245-83e9-ae0d7dd9e9c4.png"> | <img width="408" alt="Screen Shot 2022-04-08 at 10 44 41 am" src="https://user-images.githubusercontent.com/41275094/162341581-81742983-f8b8-43d2-8828-c2ae82553c69.png"> |
## Expected behavior
To show translated messages as opposed to key

## Your Environment
```
 "i18next": "^21.6.14",
  "react-native": "^0.67.3"
```

**Comment by adrai** [comment]
You may need to polyfill the Intl.PluralRules API: https://github.com/eemeli/intl-pluralrules

https://www.i18next.com/translation-function/plurals
