### ISSUE TITLE
_zero key returns a blank string when it's linked to another key

### ISSUE THREAD

**Issue by kg-currenxie** [i18next/i18next#1755]
## 🐛 Bug Report

When using `{ count: 0 }` option, i get an empty string back if the key's value is a link to another key, like `$(someKey)`:

```
"currency": "Currency",
"currency_other": "Currencies",
"currency_zero": "$t(currency)",
```

`t('currency', { count: 0 })` returns `''`

## To Reproduce

https://codesandbox.io/s/react-i18next-forked-ulsc3g?file=/src/app.js

## Expected behavior

I expect `t('currency', { count: 0 })` to return `Currency`

## Your Environment

"i18next": "21.6.15",
"react-i18next": "11.16.7"

**Comment by jamuhl** [comment]
<img width="548" alt="image" src="https://user-images.githubusercontent.com/977772/164206800-a8a7fc69-4a9f-4bd8-a536-f134c03b3e9c.png">

nesting supports plural lookup (it will search currency_zero not pick currency without plural) -> therefore you end in an endless loop for `_zero`

**Comment by kg-currenxie** [comment]
Oh i see! 
What we had previously, before i saw that `_zero` was already supported, was this:

```
const keyWithZeroSuffix = (key: string) => {
  return key + '_zero'
}

export const useTranslation = () => {
  const customT = (key: string | string[], options?: WithWildcards<IKnownOptions>) => {
    return t(constructKey(key), options)
  }

  const constructKey = (key: string | string[], options?: WithWildcards<IKnownOptions>) => {
    let constructedKey = key

    // Special case when `count` is 0 to have the option to have a different translation key.
    // Otherwise, it falls back to the normal `_plural` key
    const isZeroCount = options?.count === 0
    if (isZeroCount) {
      // Add `_zero` suffix to keys if that translation key exists
      constructedKey = Array.isArray(constructedKey)
        ? constructedKey.map(keyWithZeroSuffix)
        : keyWithZeroSuffix(constructedKey)
    }

    // If the count is zero (handled this case above), we need to remove it from the `options.count`,
    // otherwise `i18next` still does the default behavior and picks the `_plural` key.
    if (isZeroCount) {
      delete options!.count
    }

    return constructedKey
  }

  return { t: customT }
}
```

So in i18next, wouldn't it make sense to short-circuit the lookup when the count is 0, to stop the endless loop? :)

The thing is that we have scripts and git hooks to check for duplicate strings
So this wouldn't be allowed:
```
translations: {
  image: "image",
  image_zero: "image",
  image_other: "images",
}
```
😞

**Comment by jamuhl** [comment]
it does circuit-break https://github.com/i18next/i18next/blob/master/src/Translator.js#L346 else your application would be unresponsive.

**Comment by kg-currenxie** [comment]
Ok. Sorry, i meant, circuit-break AND follow the link to actually give me `image_zero` (somehow, i dont know how the lookups work)
I still think my "expected behavior" above makes sense, no?

**Comment by jamuhl** [comment]
The point is - like already said - the nesting is aware of plurals -> you can reference to another plural...you're referencing to the same plural so this does not work (expected behaviour).

But you can:

```js
"currencySingularRef": "Currency",
"currency": "$t(currencyMainRef)",
"currency_other": "Currencies",
"currency_zero": "$t(currencyMainRef)",
```

But honestly...I think your looking at all this to much from developer perspective by reducing duplicates...from a translator view knowing languages act very different for plurals it's not worth it (there are languages taking pluralform for zero, or have no plurals at all) -> so adding these references makes it just harder for the translator. But that's just my opinion.

**Comment by kg-currenxie** [comment]
Im happy with this solution 👌
```
"currencySingularRef": "Currency",
"currency": "$t(currencyMainRef)",
"currency_other": "Currencies",
"currency_zero": "$t(currencyMainRef)",
```

thanks :)
