### ISSUE TITLE
TS issue with <I18nContext.Consumer>

### ISSUE THREAD

**Issue by IdkMan2Usertive** [i18next/i18next#1756]
## 🐛 Bug Report

In React 18 ReactNode type has changed and this change affects next-i18next types.
Function passed to <I18nContext.Consumer> block incorrectly narrows the return type of the function.

```tsx
<I18nContext.Consumer>
  {({i18n}) => i18n.t('test')}
</I18nContext.Consumer>
```

TS error:

```
TS2322: Type 'TFunctionResult' is not assignable to type 'ReactNode'.   Type 'object' is not assignable to type 'ReactNode'. 
```

As I have investigated - the object is no longer a valid member of the ReactNode union type.

A quick fix is to explicitly define the return type of the t function:

```tsx
<I18nContext.Consumer>
  {({i18n}) => i18n.t<string>('test')}
</I18nContext.Consumer>
```

## To Reproduce

I have created a small reproduction repository:
https://github.com/usertive/next-i18next-issue-reproduction

## Expected behavior

I would like not to explicitly define the return type of the t function every time I want to use it. I have a very specific use case for which I am using <I18nContext.Consumer> and not use translation() hook.

## Your Environment

* Node v16
* i18next version: 21.6.16
* Device: MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)
* Browser: Chrome 100.0.4896.127 (Official) (x86_64)

**Comment by jamuhl** [comment]
see https://github.com/i18next/react-i18next/issues/1483

(closing this as the topic is worked on in other issue)
