### ISSUE TITLE
Option to ignore dynamic keys instead of adding them to the missing key files

### ISSUE THREAD

**Issue by kfazinic** [i18next/i18next#1757]
## 🚀 Feature Proposal

Ignore dynamic keys instead of adding them to the missing key file

## Motivation

Currently, when `saveMissing: true`, dynamic keys such as
```
t(`basePart.${customId}`)
```
are treated as missing and saved. 

Contributors to `vue-i18n-extract` [implemented a feature to ignore such keys ](https://github.com/pixari/vue-i18n-extract/issues/46#issuecomment-625217356). Would be great to have this in `i18next`. 

## Example

Consider keys containing `${\.+}` as dynamic and allow an option to exclude them from missing key files with a setting such as `saveDynamicKeysAsMissing: false` (`true` by default)

**Comment by jamuhl** [comment]
If there is no result from a translation key lookup and saveMissing is true...that key is missing...independent of dynamic or not - fact is...you like to saveMissing and that key is missing...

simple solution us a fallback key you like to show: `t([`basePart.${customId}`, 'basePart.unspecificFallback'])` that way it always has a fallback to lookup...

Beside that...i18next saveMissing is runtime not extraction - it does not see your code...that t function in your sample is called with a regular string (whatever that customId is at the call time)...

**Comment by jamuhl** [comment]
docs -> https://www.i18next.com/principles/fallback#key-fallback
