### ISSUE TITLE
nextjs i18next error

### ISSUE THREAD

**Issue by ricardolopesit** [i18next/i18next#1758]
## 🐛 Bug Report

I'am using nextjs boilerplate and i use the i18next to translate the text and when i reload the page or init the page, if the language it's not the default('en). Gives the error:"_Error: Hydration failed because the initial UI does not match what was rendered on the server."_ and "Text content does not match server-rendered HTML."

In this particular case i don't want to use the sub-domain and domain like the recommend documentation.

## To Reproduce
my code it's where in this repo:
https://github.com/ricardolopesit/next18n

## Your Environment

- *runtime version*:  node v16.14.2, next v12.1.5, react v18.0.0, react-dom v18.0.0,react-i18next v11.16.7
- *i18next version*:21.6.16
- *os*:  Ubuntu 20.04
- *browser*: Chrome v100.0.4896.127

**Comment by jamuhl** [comment]
please ask next-i18next related questions on the correct repo: https://github.com/isaachinman/next-i18next

But in general...make sure lng on server is same as on client: reading https://locize.com/blog/next-i18next/ might help...

or as it seems more a question about your code than a bug in any of the modules -> StackOverflow is your friend
