### ISSUE TITLE
Interpolation does not support fallback keys?

### ISSUE THREAD

**Issue by harry0000** [i18next/i18next#1760]
`t` function supports ["Calling with fallback keys"](https://www.i18next.com/principles/fallback#calling-with-fallback-keys) feature, but it does not work with [Interpolation](https://www.i18next.com/translation-function/interpolation). Is this documented as a limitation? Or is it a bug?

## 🐛 Bug Report

Combining "Calling with fallback keys" and "Interpolation" does not return the expected value.

#### code

- JSFiddle: https://jsfiddle.net/ogtjps6n/1/

```js
const resources = {
  en: {
    skill: {
      active: '$t([skill:name.{{unit}}.active.{{no}}.{{form}}, skill:name.{{unit}}.active.{{no}}])',
      name: {
        1: {
          active: {
            1: 'active_1',
            2: 'active_2'
          }
        },
        2: {
          active: {
            1: {
              normal: 'normal_active_1',
              changed: 'changed_active_1'
            },
            2: 'active_2'
          }
        }
      }
    }
  }
};

i18next
  .init({
    resources,
    ns: ['skill'],
    defaultNS: 'skill',
    lng: 'en',
    interpolation: {
      escapeValue: false,
    }
  });
```
```js
// these work
console.log(i18next.t('name.1.active.1'));
console.log(i18next.t('$t(name.{{unit}}.active.{{no}})', { unit: 1, no: 1 }));
console.log(i18next.t(['name.1.active.1.undefined', 'name.1.active.1']));

// these do not work
console.log(i18next.t(['name.{{unit}}.active.{{no}}.{{form}}', 'name.{{unit}}.active.{{no}}'], { unit: 1, no: 1 }));
console.log(i18next.t(['name.{{unit}}.active.{{no}}.{{form}}', 'name.{{unit}}.active.{{no}}'], { unit: 1, no: 1, form: undefined }));
console.log(i18next.t('active', { unit: 1, no: 1 }));
console.log(i18next.t('active', { unit: 1, no: 1, form: undefined }));
```
```js
// this works
console.log(i18next.t(['name.2.active.1.changed', 'name.2.active.1']));

// this does not work
console.log(i18next.t('active', { unit: 2, no: 1, form: 'changed' }));
```

#### console log results

```
"active_1"
"active_1"
"active_1"
"name.1.active.1"
"name.1.active.1"
"name.1.active.1.{{form}}, skill.name.1.active.1],{undefined"
"name.1.active.1."
```
```
"changed_active_1"
"name.2.active.1.changed"
```

#### console log results

```
"active_1"
"active_1"
"active_1"
"active_1"
"active_1"
"active_1"
"active_1"
```
```
"changed_active_1"
"changed_active_1"
```

## Your Environment

- *runtime version*: Google Chrome 100.0.4896.127 (64bit)
- *i18next version*: 21.6.16
- *os*: Windows

**Comment by jamuhl** [comment]
Works like:

1) search given key
2) interpolate, nest, post process on given result

Interpolation is the last step before returning the string...so yes...this can't work and is expected.

**Comment by harry0000** [comment]
I see. Thank you for your answer.

Are there any plans for [Nesting](https://www.i18next.com/translation-function/nesting) to support fallback keys?

```js
console.log( i18next.t('$t(name.{{unit}}.active.{{no}})', { unit: 1, no: 1 }) );

console.log( i18next.t('$t([name.{{unit}}.active.{{no}}])', { unit: 1, no: 1 }) );
```

```
"active_1"
"[name.1.active.1]"
```

**Comment by jamuhl** [comment]
not sure what the usecase for such interpolation in fallback keys is...looks more like doing keys wrong at all:

you're searching a key like `name.{{unit}}.active.{{no}}` that key does not exist at all!!!!

you should use template strings to interpolate values into keys

```js
i18next.t([`name.${unit}.active.${no}`])
```

**Comment by jamuhl** [comment]
```js
"active_1"
"[name.1.active.1]" // --> is basically the result of not finding the key and using the key itself as fallback
```

**Comment by harry0000** [comment]
@jamuhl 
I understood the answer to be that it is normally possible to define a key `"[name.1.active.1]"` in `resources` and that there are no plans to support the notation of fallback keys in Nesting. Thank you very much.

**Comment by jamuhl** [comment]
the point is i don‘t see why you need that. template string does the same

**Comment by jamuhl** [comment]
plus the template string works while your sample using interpolation does not work in any case. as the key you search does not exist in your resources

**Comment by harry0000** [comment]
> the point is i don‘t see why you need that. template string does the same

I just wanted to keep the code short in my use case, so it wasn't that serious a problem!

[playground](https://www.typescriptlang.org/play?#code/PTAEGcGsEsBtYFygN4FgBQJTYIYGMAXaANwFMkByAEgIAoBtKORAOxwFtSA6ZZAVxbQCAX2Fd8RMj2QsA9qOkAzWQCd2ogDQQY8BG07SBQhRJLdec0QF0AlBQ0Ys2feRSOw2bAEYkaTB89cQjNfd0Dwn1AKIwIvAH1TMjivezDwzwAmShj4xNI4jIo08OFi7GEHf3Cstyr0vNC69NBIvydm51V2HEQomIy4uTUehOCklMr2jrwACxwWAHNSABNswQIB2fml5dHJfJSyksmA9Jro9YG8gqKmwNK70Aep0BAud+LnsAeMaHYAB1UBFA0C8AA4WKQAB7AxQqWTsKKgiHQggUADcGAwBAAnv9SKAACqgAC8tWwMSQLD47AARqQVJVOkgvKAAD6gDJM0DKNQAfkoQ26sAo7KiW0WK1uP3Qy1IeFgOBUBLwshY4GB-yVHHASEJmPQYQAkqAAO7zYEEWRmlRCUi-cGQmFcOgUJi6PL2UBalQ6mwG42gZZq4HmliW62m20Ee3oZFOggu2gYbAUXnsUXQFje7XscCgPkpzwAA3drA43CoyB9Oq4MTEeS4VZrea4lib1dz4C46eExdACCL2FLOnLBmbXbr6wbY0rnd9rcsxYw-qAA)

```json
{
  "active": "$t([skill:name.{{unit}}.active.{{no}}.{{form}}, skill:name.{{unit}}.active.{{no}}])"
}
```

```ts
import i18next from 'i18next';

type T = {
  unit: number,
  no: 1 | 2,
  form?: 'normal' | 'changed'
}

declare const params: T;

// I want to write
i18next.t('skill:active', params);

// I dont want to write
i18next.t(
  'form' in params ?
    `skill:name.${params.unit}.active.${params.no}.${params.form}` :
    `skill:name.${params.unit}.active.${params.no}`
);
```

**Comment by jamuhl** [comment]
ok i see
