### ISSUE TITLE
Type 'TFunctionResult' is not assignable to type 'string'

### ISSUE THREAD

**Issue by ashevchenkosps** [i18next/i18next#1761]
Hello, guys, I have 
```
react-i18next v11.16.4, 
i18next": "19.9.2" 
```
and have a current type error for i18next when I use `i18next.t`. Only workaround https://github.com/isaachinman/next-i18next/issues/1781#issuecomment-1092620082 works for me.

What could be wrong? Could be a solution without the workaround above?

**Comment by danielweck** [comment]
I am getting the following error since upgrading from `21.6.14` to `21.7.1`:

`TS2339: Property 'length' does not exist on type 'TFunctionDetailedResult<object>'`
