### ISSUE TITLE
`returnDetails` not available in `InitOptions`

### ISSUE THREAD

**Issue by c7hm4r** [i18next/i18next#1765]
Sorry, there is small bug in #1764.

## 🐛 Bug Report

`returnDetails?: boolean` is part of `TOptionsBase` but of `InitOptions`. So the TypeScript Compiler yields an error when one tries to do `i18n.init({ returnDetails: true, … })`.

## To Reproduce

```typescript
i18n.init({ returnDetails: true, … });
```

## Expected behavior

It compiles.

## Your Environment

- *runtime version*: node 16
- *i18next version*: i.e. 21.7.0

**Comment by adrai** [comment]
v21.7.1

**Comment by c7hm4r** [comment]
:+1: :running_man:
