### ISSUE TITLE
Unbounded parallelism on BackendConnector.load

### ISSUE THREAD

**Issue by huntharo** [i18next/i18next#1769]
## 🐛 Bug Report

If, say, 20 languages and 400 namespaces are passed into `BackendConnector.load` then all 8,000 of those load calls will be dispatched to the backend without waiting for a single one of them to complete.  If 100,000 items are loaded then all of those would be called, and so on.

The effect of this is that backends such as `i18next-fs-backend` will run out of file descriptors when using the default async loader and other backends may try to open tens of thousands of sockets to a host.

This results in very real problems on systems with low `ulimit`'s on file descriptors, such as AWS Lambda which has a 1,024 limit.  The large number of files being opened results in `EMFILE` errors that are not raised to the caller or printed in any way unless `debug` is enabled.

The problem starts here:

https://github.com/i18next/i18next/blob/a0daee7d64b19190d9dc335a764a6e1735dfc7aa/src/BackendConnector.js#L168-L170

`this.loadOne` is called on each item in `toLoad.toLoad`.  `this.loadOne` calls `this.read` which calls `this.backend`.  The problem is that `this.read` is an "async" function with a callback but `this.loadOne` does not "await" that function, it just keeps looping.

## To Reproduce

A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

[test code](https://github.com/i18next/i18next/compare/master...huntharo:unconstrained-parallelism-demo?expand=1)

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/5617868/167281523-7f3a26a6-d970-40c2-aeb6-d2d825dfdd8e.png">

## Expected behavior

Options to address the issue:

1. Document for backend implementors that they must be aware that backends may be called tens of thousands of times and that backends must implement a parallelization limit if that is necessary to avoid reaching socket, file descriptor, etc. limits / document for users that `initImmediate` should be set to false to address resource constraint issues with large numbers of languages and namespaces
2. Implement parallelization constraint within this library - Unfortunately, this is not easy to do without adding a dependency and making other breaking changes

Once the decision is made I can potentially create a PR to update the docs.

## Your Environment

- *runtime version*: any
- *i18next version*: master
- *os*: any
- *any other relevant information*

**Comment by adrai** [comment]
Couldn't this also be solved by adapting the read function without any breaking change or dependency?
Something, like:

```diff
read(lng, ns, fcName, tried = 0, wait = 350, callback) {
    if (!lng.length) return callback(null, {}); // noting to load

+     if (this.readingCalls > this.maxParallelReads) {
+       this.waitingReads.push({ lng, ns, fcName, tried, wait, callback });
+       return;
+     }
+ 
+     this.readingCalls++;

    return this.backend[fcName](lng, ns, (err, data) => {
      if (err && data /* = retryFlag */ && tried < 5) {
        setTimeout(() => {
          this.read.call(this, lng, ns, fcName, tried + 1, wait * 2, callback);
        }, wait);
        return;
      }
      callback(err, data);
+       this.readingCalls--;
+       if (this.waitingReads.length > 0) {
+         const next = this.waitingReads.shift();
+         this.read(next.lng, next.ns, next.fcName, next.tried, next.wait, next.callback);
+       }
    });
  }
```

**Comment by huntharo** [comment]
Yes. That is a great idea. I think letting that be a configurable parameter on how many to run at once would make it safe to release to existing users. The default should probably be in the 10 to 100 range.

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this?

**Comment by huntharo** [comment]
> Would you like to send a Pull Request to address this?

Yeah, giving it a try
