### ISSUE TITLE
Contributor's Guide / Notes?

### ISSUE THREAD

**Issue by huntharo** [i18next/i18next#1770]
## Documentation issue

As a developer, it was not easy to figure out how to run unit tests in a way where a debugger could attach to allow stepping through code.

The solution I arrived at was:
- Add the `esm` development-time module
- Add '"type": "module"` to the `package.json`
- Add `import { expect } from 'chai';` in the test files
- Make sure any imports use the `.js` extension
  - For example, this one is missing a `.js` extension next to others that have one: https://github.com/i18next/i18next/blob/448e2be33042ed959d762eaff270fa804e2baaf4/test/backend/backendConnector.load.retry.spec.js#L3
- Add the `.only` to the `describe`
- Run the test file individually like this: `npx mocha --require esm test/backend/backendConnector.parallel.spec.js`
- This allowed VS Code's Debug Terminal to attach correctly and to stop at configured breakpoints

## Motivation

Collecting notes such as this would be really helpful for others trying to contribute.  

On the other hand... perhaps there is a simpler method that works that I could have used if documented :)

**Comment by adrai** [comment]
never had the need to debug with a debugger, but generally we can't just change the module type to module yet...

**Comment by huntharo** [comment]
Oh no I'm not suggesting to change the module type. I'm just noting that, because the source files are ESM, it's necessary to tell mocha that they are ESM and it seems the only way to do that is to temporarily change the package.json file. It may be possible to pass another node flag to override the package.json default.

**Comment by adrai** [comment]
the test setup is not directly done with mocha but with karma, so there might be a way to attach a debugger via karma...

**Comment by huntharo** [comment]
Yeah I tried debugging Karma first but Karma is causing transpilation and is either dropping "debugger;" statements OR it's creating more nested processes than the debug terminal can or will attach to, or in a way that the chain is lost and they are not noticed by the debug terminal. 

But yes. If we can make it work with Karma great.
