### ISSUE TITLE
The second request to the same namespace with loadNamespaces() resolves before it's loaded with version 21.8.0

### ISSUE THREAD

**Issue by AlexJayt** [i18next/i18next#1772]
## 🐛 Bug Report

When loadNamespaces() to the same namespace is called several times so that the rest of calls are made before the request to backend made by the first call is completed and translations are set to the store, they are resolved immediately, not waiting that. The problem appeared in version 21.8.0.

## To Reproduce

Sample: https://codesandbox.io/s/sweet-cache-iz108u?file=/src/app/app.component.ts

![21 8 0](https://user-images.githubusercontent.com/22254881/167896950-3a7bee44-485a-4e2f-baa6-44ee249353a6.png)

## Expected behavior

The second Promise of loadNamespaces() is resolved after translations are loaded as it was in version 21.7.1.

![21 7 1](https://user-images.githubusercontent.com/22254881/167897653-e0076ada-790a-48df-864f-795018ba591f.png)

## Your Environment

- *runtime version*: Google Chrome Version 100.0.4896.88
- *i18next version*: 21.8.0
- *os*: Windows

**Comment by adrai** [comment]
I suspect this is because of this optimization: https://github.com/i18next/i18next/pull/1768
@huntharo can you have a look at it?
btw: I created a smaller codesandbox example: https://codesandbox.io/s/react-i18next-http-example-forked-3viuft?file=/src/i18n.js

**Comment by adrai** [comment]
should be fixed with v21.8.1
