### ISSUE TITLE
Caching Intl formatters

### ISSUE THREAD

**Issue by pwolaq** [i18next/i18next#1776]
## 🚀 Feature Proposal

I have been reading the source code recently and I have noticed that [using formatters creates new intl formatter instances on every usage](https://github.com/i18next/i18next/blob/9ca694db52fe5b6f10da5debf3e106e6f615b907/src/Formatter.js#L44-L59). It has negative effect on performance and could be avoided by caching and reusing already created formatters.

## Motivation

This is rather simple and minor change that should improve formatters performance. Similar improvement has been previously introduced to Angular codebase in this PR: https://github.com/angular/angular/pull/18054/files

If you agree, I would be happy to make a PR with suggested changes.

**Comment by adrai** [comment]
if stringifying the options to generate the cache key is really a lot more performant than creating new instances in a real world szenario, ok.
Can you provide also a test proofing the performance gain?
