### ISSUE TITLE
saveMissingTo only saves current language

### ISSUE THREAD

**Issue by SerdarSanri** [i18next/i18next#1777]
## 🐛 Bug Report

when `fallbackLng:false`, `saveMissing: true` and `saveMIssingTo: 'all'` is set, missing keys only being added to current language instead of all supported languages.

## To Reproduce
i18n.js 

```js
import i18n from 'i18next';
import Backend from 'i18next-fs-backend';
import {resolve, join} from 'path';
import {lstatSync, readdirSync} from 'fs';

const localePath = resolve('./locales');

i18n
    .use(Backend)
    .init({
        backend: {
            allowMultiLoading: true,
            addPath: `${localePath}/{{lng}}/{{ns}}.json`,
            loadPath: `${localePath}/{{lng}}/{{ns}}.json`
        },
        preload: readdirSync(localePath).filter((fileName) => {
            const joinedPath = join(localePath, fileName);
            const isDirectory = lstatSync(joinedPath).isDirectory();
            return isDirectory;
        }),
        ns: readdirSync(`${localePath}/en`).filter((fileName) => {
            const joinedPath = join(`${localePath}/en`, fileName);
            const isDirectory = lstatSync(joinedPath).isDirectory();
            return !isDirectory;
        }).map(file => file.replace(/\.json/, '')),
        load: 'all',
        updateMissing: true,
        lowerCaseLng: true,
        cleanCode: true,
        defaultNS: 'common',
        nonExplicitSupportedLngs: true,
        keySeparator: false,
        fallbackLng: false,
        debug: true,
        saveMissingTo: 'all',
        saveMissing: true,
        interpolation: {
            escapeValue: false
        },
        supportedLngs: ['en', 'tr', 'de']
    });

export default i18n;

```

with above configuration, I delete all exceptions.js files, ( also tested with empty exceptions.js), if I call for `i18n.changeLanguage('de'); i18n.t('exceptions:user-not-found')`, I can see exceptions.js file gets generated in /locales/de/ folder. but even though it is set to `all` it does not create same exceptions file in other supported languages. The only way to generate them is to change language to missing one and re-trigger. 

## Expected behavior

when `saveMissingTo` is set to `all` it should create/update missing keys in all supported languages array. This will avoid developer to miss keys in different languages.

## Your Environment

- *runtime version*: node v14, server-side-node + express
- *i18next version*: 21.6.16
- *os*: Linux

**Comment by jamuhl** [comment]
`saveMissingTo: 'all'` has nothing todo with supported languages -> it will only save to all of the i18next.languages. What is basically described here: https://www.i18next.com/overview/api#languages

**Comment by SerdarSanri** [comment]
so instead of supportedLanguages, we should set the array of i18n.languages? It is not clear in documentation here 
![image](https://user-images.githubusercontent.com/651202/168874466-7309ea05-708e-4358-b561-32ee1cb28108.png)

**Comment by jamuhl** [comment]
no. there is no way to fill all your languages. savemissing is not meant to fill all your files. its there to fill the source language. 

thecwarning says it all. you access t function before having loaded.

**Comment by SerdarSanri** [comment]
that actually doesn't make any sense at all. if having fallbackLng defined and using saveMissingTo either 'all' or 'currentLang' has no affect. it doesn't even create/update the currentLanguage nor fallback language ( in case file/key is missing in either or both ). On the other hand if fallbackLng is set to false, saveMissingTo only applies to currentLanguage. what is `all` for then? Also in 3 other config property i18n has the knowledge of what languages, their locations etc information, `there is no way` doesn't seem to be logical. 

Also above case is only when I use fs-backend plugin. From front end with http-backend, for missing keys it sends add request and with a simple iteration I can add/update all language files.

```
// ....

const getFolders = () => fs.readdirSync(path.join('locales')).filter((fileName) => {
    const joinedPath = path.join(path.join('locales'), fileName);
    const isDirectory = fs.lstatSync(joinedPath).isDirectory();
    return isDirectory;
}).map(p => path.basename(p));

const updateLanguageFile = async (lang, ns, contents) => {
    const filename = path.resolve(path.join('locales', lang, `${ns}.json`));
    try {
        if (process.env.STAGE === 'local' && process.env.NODE_ENV==='development') {
            if (fs.existsSync(filename)) {
                const fileContents = fs.readFileSync(filename, {encoding: 'utf8'});
                contents = deepmerge(JSON.parse(fileContents), contents);
            }
            fs.writeFileSync(filename, JSON.stringify(contents, null, 2));
        }
    }
    catch (e) {
        console.log(e);
    }

};

router.post('/add/:ns', async (req, res, next) => {
    const {ns} = req.params;
    const currentLang = i18n.languages[0];
    let contents = req.body;

    for (const lang of getFolders()) {
        await updateLanguageFile(lang, ns, contents);
    }

    res.sendFile(path.resolve(path.join(`locales/${currentLang}/${ns}.json`)));

});

/// ...
```

I just wish similar concept was included in saveMissingTo:all

**Comment by adrai** [comment]
If I understand correctly, what you're actually looking for is something like:

`saveMissingTo: 'supportedLngs'`

right?

**Comment by jamuhl** [comment]
which might not make sense as:

- in case you got `nonExplicitSupportedLngs` set that list won't contain "all" languages you provide 
- saveMissingTo: 'supported' would not check in all supported languages if the key exists as it only uses i18next.languages for searching that key existing -> so you will eventual overwrite content

so in most cases i18next has neither all information about your languages nor is 100% sure if keys exist in any of the languages it currently did not load or not use to search that key

The main question is why do you need to write the missings to all your languages? Seems like I miss something there - as I think that is totally unneeded.

**Comment by SerdarSanri** [comment]
> If I understand correctly, what you're actually looking for is something like:
> 
> `saveMissingTo: 'supported' // uses supportedLngs array`
> 
> right?

sort of. not necessarily supportedLngs but any option that is considered as "known" languages. the problem I am trying to solve is, for instance our company has many developers around the world. they all speak english but mainly while they are developing they use the translated version of the app, in their local. The app itself supports all languages, so for instance if I am using Turkish, since it is easier for me, and add an exception, current situation is it only creates the key/ or file in locales/tr/exceptions.js file. then I have to go through each language folder and add there manually. then commit. if one or more dev forgets ( since assuming it creates automatically ) or especially if it is a front-end dev doesn't have access to backend, there is no way to handle this. some backend dev has to go through each language file in each language folder to make sure they all have same keys, either translated or not but at least they keys exist. 

if, backend was set up as I mentioned above, saveMissingTo: 'all' then when front end dev creates a key, it will be synced and exist in all language files , a translator then can take the file and update with proper translations.

**Comment by adrai** [comment]
Would you be happy by having something that would save it to the current language + fallback?

**Comment by SerdarSanri** [comment]
in current configuration, when I set fallbackLng to anything, it totally disables saveMissing functionality. If that's a really big change I can work it out by creating a plugin maybe to sync them, similar to how I did for external client connections to backend. That part works like a charm. my issue is in the backend where also uses i18next internally.

**Comment by adrai** [comment]
Maybe I get miss something, but you just have to set the `fallbackLng` option to `'en'` or whatever your source language is.

**Comment by SerdarSanri** [comment]
with this configuration

```
import i18n from 'i18next';
import Backend from 'i18next-fs-backend';
import Config from 'common/Config';
import {resolve, join} from 'path';
import {lstatSync, readdirSync} from 'fs';

const localePath = resolve('./locales');

i18n
    .use(Backend)
    .init({
        backend: {
            allowMultiLoading: true,
            addPath: `${localePath}/{{lng}}/{{ns}}${Config.get('locale.extension', '.json')}`,
            loadPath: `${localePath}/{{lng}}/{{ns}}${Config.get('locale.extension', '.json')}`
        },
        preload: readdirSync(localePath).filter((fileName) => {
            const joinedPath = join(localePath, fileName);
            const isDirectory = lstatSync(joinedPath).isDirectory();
            return isDirectory;
        }),
        ns: readdirSync(`${localePath}/en`).filter((fileName) => {
            const joinedPath = join(`${localePath}/en`, fileName);
            const isDirectory = lstatSync(joinedPath).isDirectory();
            return !isDirectory;
        }).map(file => file.replace(/\.json/, '')),
        load: 'all',
        updateMissing: true,
        lowerCaseLng: true,
        cleanCode: true,
        defaultNS: 'common',
        nonExplicitSupportedLngs: true,
        keySeparator: false,
        fallbackLng: 'en', // <---
        debug: true,
        saveMissingTo: 'fallback', // <----
        saveMissing: true,
        interpolation: {
            escapeValue: false
        },
        supportedLngs: ['en', 'tr', 'de']
    });

export default i18n;
```
and I don't have exceptions.json file in any locale folders. if I call `i18n.t('exceptions:client-not-authorized')` I get same error message in debug. 

```
i18next: languageChanged en
i18next::translator: key "client-not-authorized" for languages "en" won't get resolved as namespace "exceptions" was not yet loaded This means something IS WRONG in your setup. You access the t function before i18next.init / i18next.loadNamespace / i18next.changeLanguage was done. Wait for the callback or Promise to resolve before accessing it!!!
i18next::translator: missingKey en exceptions client-not-authorized client-not-authorized
i18next::backendConnector: did not save key "client-not-authorized" as the namespace "exceptions" was not yet loaded This means something IS WRONG in your setup. You access the t function before i18next.init / i18next.loadNamespace / i18next.changeLanguage was done. Wait for the callback or Promise to resolve before accessing it!!!
object
2022-05-17 15:41:18:4118 http POST /en/login 401 67 - 69.788 ms
```

**Comment by adrai** [comment]
create an empty {} file

**Comment by SerdarSanri** [comment]
> create an empty {} file

yes in that case file gets updated. but this means if a front end dev needs a new namespace, someone in backend has to create a blank file first in their active language then deploy. :)

**Comment by SerdarSanri** [comment]
anyways, I don't want to take too much of your time. I was just wondering if I am missing something or some config parameter that causes all `known` languages are not being updated but just active one ( or the fallback one ) it looks like it is by design. I will see if I can find a different solution.

**Comment by adrai** [comment]
if that is a new namespace, yes

**Comment by SerdarSanri** [comment]
But that's not the same behavior when fallbackLng is set to false thou. In that case namespace file gets created and updated in selected language without an error message. worst case scenario we will ask devs to only use eng for creating new namespace/keys.
