### ISSUE TITLE
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform

### ISSUE THREAD

**Issue by adduss** [i18next/i18next#1778]
## 🐛 Bug Report

Chrome is throwing improvement info that navigator.userAgent won't be supported starting from Chrome version 101 and all usages have to be replaced with navigator.userAgentData.

Occurence is in "isIE10" in file https://github.com/i18next/i18next/blob/5a9bba39a56a24b325058a6bd88516c0b19fede9/src/utils.js 

## To Reproduce
1. Use library in any project
2. Run Lighthouse report from ChromeDev tools with "Best practices" checkbox selected
3. Switch to console tab
4. Open issues - one issue found:
- Title: "Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform"
- Description: "A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown."
- More details about issue: https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html

## Expected behaviour

No issue related with library

## Your Environment

- *runtime version*:  node v16.14.0
- *i18next version*: 21.6.14
- *os*: Mac
- Chrome: v100.0.4896.127
<img width="1462" alt="Screenshot 2022-05-18 at 08 01 40" src="https://user-images.githubusercontent.com/5172081/168968150-d4141f7e-e6ee-4f44-8cd4-ef84a130c013.png">

**Comment by adrai** [comment]
v21.8.3 should only access userAgent in IE
