### ISSUE TITLE
Type 'TFunctionDetailedResult<object>' is not assignable to type 'TResult'

### ISSUE THREAD

**Issue by bulutfatih** [i18next/i18next#1780]
## 🐛 Bug Report

I am having this type error while trying to update i18next from 21.6.14 to 21.8.3

```
Type 'TFunctionDetailedResult<object>' is not assignable to type 'TResult | TResult | TResult | TResult | TResult | TResult'.
  Type 'TFunctionDetailedResult<object>' is not assignable to type 'TResult'.
    'TFunctionDetailedResult<object>' is assignable to the constraint of type 'TResult', but 'TResult' could be instantiated with a different subtype of constraint 'TFunctionResult'.ts(2322)
```

## To Reproduce

Codesandbox: https://codesandbox.io/s/objective-cartwright-3lvo0z?file=/src/index.tsx

I need to use this special case.

```js
  const { t }: { t: TFunction } = useTranslation("translation", {
    keyPrefix: "look"
  });

  const tSpecial: TFunction = (key, opts) => t(`deep.${key}`, opts);
```

## Your Environment

- *runtime version*: react 17 (typescript)
- *i18next version*: 21.8.3

Is it a known issue? Can someone guide me here, please?
Thanks in advance.

**Comment by adrai** [comment]
@pedrodurek

**Comment by pedrodurek** [comment]
Hey @bulutfatih,
You don't need to type the object `t`, typescript will infer the appropriate return type for the `t` function, and you need to type both arguments of the `tSpecial` function, and `key` argument must be a literal value.

Try something like:
```tsx
  const { t } = useTranslation("translation", {
    keyPrefix: "look"
  });

  const tSpecial = (key: 'text' | 'otherKeys', opts: UseTranslationOptions<'look'>) => t(`deep.${key}`, opts);
```

**Comment by pedrodurek** [comment]
Hey @bulutfatih, `tSpecial` and `t` function have two distinct shapes. In that case, you would need to manually create the types for `tSpecial`, like I'm doing here: https://codesandbox.io/s/kind-flower-ooqt3f?file=/src/index.tsx
