### ISSUE TITLE
`isLanguageChangingTo` is missing from `i18n` interface

### ISSUE THREAD

**Issue by francescocaveglia** [i18next/i18next#1781]
## 🐛 Bug Report

`isLanguageChangingTo` property is missing from `i18n` interface

## To Reproduce

```js
// anyfile.ts

import i18next from 'i18next';

i18next.isLanguageChangingTo;
```

getting error `Property 'isLanguageChangingTo' does not exist on type 'i18n'`

## Expected behavior

`i18n` interface should have `isLanguageChangingTo` property

## Your Environment

- *runtime version*: node v16
- *i18next version*: 21.8.4
- *typescript version*: 4.6
- *os*: Windows

**Comment by adrai** [comment]
in theory it's an internal property
