### ISSUE TITLE
`$` in values reset `nextIndex` to wrong position with `skipOnValue`, in some cases even leaving keys untranslated

### ISSUE THREAD

**Issue by Silviu-Marian** [i18next/i18next#1782]
## 🐛 Bug Report

Translating `"Save %CURRENCY%%AMOUNT%"`. Traced the problem down to a point where when the string becomes `Save $%AMOUNT%`, and the replacement for `%CURRENCY%` was `$$` [to prevent String.replace() from interpreting it as a parameter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_a_parameter) with the next search position being incremented by 2 (`'$$'.length`) instead of 1 (`'$'.length`) which is beyond the point where `%AMOUNT%` starts in this case.

File location: https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L148
It looks like it should be `todo.regex.lastIndex += safeValue.length`. Maybe.

Problem was introduced with `20.2.0`. 

Version `20.1.0` doesn't have this issue. 

## To Reproduce

https://codesandbox.io/s/i18next-skiponvariables-multiple-placeholders-forked-4htpmo?file=/src/index.js

## Expected behavior

Obvious from description. 

## Your Environment

Irrelevant.

**Comment by adrai** [comment]
This is because the regex save value length was used: https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L79

v21.8.5 should fix that

**Comment by Silviu-Marian** [comment]
Thank you gentlemen. That was pretty quick.

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
