### ISSUE TITLE
loadNamespaces() doesn't keep resolving order when the second request completes before the first one

### ISSUE THREAD

**Issue by AlexJayt** [i18next/i18next#1785]
## 🐛 Bug Report

If we make several requests with loadNamespaces() to different namespaces, in case when the second completes faster than the first one, the first promise resolves first when it's not loaded in fact yet. The bug appeared with version 21.8.0 and higher.

Case 1: The first request completes first - everything is OK

![Case 1](https://user-images.githubusercontent.com/22254881/171858743-79bb13e0-3e7a-4180-ac66-8bb7ae13c937.png)

Case 2: The second request completes first - Bug

![Case 2](https://user-images.githubusercontent.com/22254881/171858884-44d9ef5c-8ba7-4b03-9d8e-83ee137c93c3.png)

## To Reproduce

Sample: https://codesandbox.io/s/optimistic-tdd-sycrtt?file=/src/app/app.component.ts

## Expected behavior
loadNamespaces() resolves when the appropriate namespace loaded, for example as it worked with version 21.7.1

![Case 2 (21 7 1)](https://user-images.githubusercontent.com/22254881/171860436-3d9325cd-0b8e-4811-9950-2e5f5f0e490c.png)

## Your Environment

- *runtime version*: Google Chrome Version 101.0.4951.64
- *i18next version*: 21.8.7
- *os*: Windows

**Comment by adrai** [comment]
Can you create a test that reproduces your behaviour like this, please: https://github.com/i18next/i18next/blob/master/test/i18next.backend.concurrentLoad.spec.js

**Comment by adrai** [comment]
@huntharo maybe have a look at it?

**Comment by adrai** [comment]
v21.8.8 should fix that

**Comment by AlexJayt** [comment]
> Can you create a test that reproduces your behaviour like this, please: https://github.com/i18next/i18next/blob/master/test/i18next.backend.concurrentLoad.spec.js

I've created this one
https://github.com/AlexJayt/i18next/blob/order-load-test/test/i18next.backend.orderLoad.spec.js

**Comment by adrai** [comment]
have you tried v21.8.8 ?
