### ISSUE TITLE
Mismatch argument type of `t` function when passing a desired object to its options arg

### ISSUE THREAD

**Issue by mirismaili** [i18next/i18next#1786]
## 🐛 Bug Report

I copied this example from https://www.i18next.com/translation-function/interpolation#basic:
```js
i18next.t('key', { what: 'i18next', how: 'great' })
```
Then it complains:
```
Argument types do not match parameters
```
It expects I pass a [`TOptions`](https://github.com/i18next/i18next/blob/b1f6c3633faa6bf6cf31c3ea8a7a09fa62f2deb7/index.d.ts#L623-L684) to its `options`.

## Environment

- *runtime version*: node v18.2.0, IntelliJ IDEA 2022.1.2 (Ultimate Edition)
- *i18next version*: 21.8.7
- *os*: Windows 11

**Comment by adrai** [comment]
I assume you're using TypeScript... so maybe @pedrodurek can help?

**Comment by pedrodurek** [comment]
`TOptions` intersects the actual options with any arguments you pass to the `t` function: https://github.com/i18next/i18next/blob/b1f6c3633faa6bf6cf31c3ea8a7a09fa62f2deb7/index.d.ts#L694-L695

Hey @mirismaili, could you provide an example from codesandbox?

**Comment by mirismaili** [comment]
@pedrodurek Sorry! I saw this error in my IDE (IntelliJ IDEA 2022.1.2 (Ultimate Edition)):

![image](https://user-images.githubusercontent.com/15800189/172398859-3c55c82e-54a4-44c0-8b8c-cb04ce0663bc.png)

(in javascript source, not necessarily typescript)

**Comment by kricha** [comment]
any news?
