### ISSUE TITLE
Getting object is not extensible error when loading translations over http backend

### ISSUE THREAD

**Issue by maman** [i18next/i18next#1787]
## 🐛 Bug Report

Hi, I'm getting `object is not extensible` error when loading translations over http backend. This happens on both client-side web & react-native environments.

<img width="594" alt="image" src="https://user-images.githubusercontent.com/491458/171992284-75d0431d-0c72-4e8d-8837-dcd50498ae3b.png">

## Explanation

I believe this is caused by the [setPath](https://github.com/i18next/i18next/blob/master/src/utils.js#L59-L63) & [getLastOfPath](https://github.com/i18next/i18next/blob/master/src/utils.js#L29-L57) function in utils.js.

both are mutating `this.data` passed by `addResourceBundle` method directly.

when I checked the "extensibility" of `this.data` by running `Object.isExtensible(this.data)`, it return false - which means that the `this.data` object isn't supposed to be extensible.

## Your Environment

- *runtime version*: Chrome 1.0.2, React Native 0.67.2 (Hermes 0.9.0)
- *i18next version*: 21.8.8
- *os*: Mac

**Comment by adrai** [comment]
Can you create a reproducible codesandbox example?
Never seen such an error.
