### ISSUE TITLE
issue with null value for the key.

### ISSUE THREAD

**Issue by leomon38** [i18next/i18next#1790]
for example, if I put null as value to a key, what would happen?
I encounter some exception with i18next.t especially the key has "." in it
so I did this resource file for testing
```
   resources: {
       en: {
        translation: {
        "example.a@test.com" : null,
        "..": null,
        "." : null,
        "..." : null,
        "....": null,
        "...b" : null,
        "b..." : null,    
        "Loading...": null,      
        "Loading." : null,
        "Loading" : null,
        "2...20"
       }
    }
 }

```
I went thru the list and all following key will throw " Cannot read properties of null (reading 'b...')" exception
```
"example.a@test.com",
".",
"..",
"...",
"b...",
"2...20"
```

But other key will work fine and return the key itself as translation (showing below)
```
"...b",
"Loading...",
"Loading."
"Loading",
"...Loading"
```
is this a bug or something

I also tried
returnNull: false,
but it wont fix it

**Comment by jamuhl** [comment]
did you read about keys being dot delimited? keySeparator option

**Comment by adrai** [comment]
please try with v21.8.9 (was a bug in deepFind for ignoreJSONStructure = true)

**Comment by leomon38** [comment]
> please try with v21.8.9 (was a bug in deepFind for ignoreJSONStructure = true)

Yes, I installed the latest version and it fixed the problem I have.
And keySeparator: false also help for older version i18next... not to sprout out the exception

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
