### ISSUE TITLE
webpack i18next-ts-loader introduction

### ISSUE THREAD

**Issue by klis87** [i18next/i18next#1792]
## Documentation issue

I created i18next webpack loader - https://github.com/klis87/i18next-ts-loader . If you find it useful, we could add it to docs

## Motivation

Copying the https://github.com/klis87/i18next-ts-loader#motivation , this loader has the following features:
- importing json files with translations with standard ES6 modules, which can be located anywhere, especially next to components which need them
- creating autogenerated Typescript types, which gives you autocompletion in your text editor (if you use just javascript), or even type safety (if you use typescript)
- copying locale files to chosen place required by i18next
- compatibility with webpack HMR - when you update a locale file, you will see the translation updated without page reload
- content based hashing support - optionally copied locale files for i18next can contain content based hash, so that you could cache your locales forever, like you usually do for js and css files

**Comment by jamuhl** [comment]
sounds great...sure...if you like add it here: https://github.com/i18next/i18next-gitbook/blob/master/overview/plugins-and-utils.md#utils
