### ISSUE TITLE
i18next.t - Argument types do not match parameters - webstorm

### ISSUE THREAD

**Issue by nazaralynadirbek** [i18next/i18next#1793]
Webstorm 2022.1 says "Argument types do not match parameters" for this construction i18next.t("generic.timestamp", { day, time });

**Comment by adrai** [comment]
https://github.com/i18next/i18next/issues/1786#issuecomment-1148715832

**Comment by kricha** [comment]
up

**Comment by sidorovpavel** [comment]
the problem is still there (
