### ISSUE TITLE
Excessive language code rejection warning, unclear call to action

### ISSUE THREAD

**Issue by oliversalzburg** [i18next/i18next#1794]
## 🐛 Bug Report

The warning `rejecting language code not found in supportedLngs: en` is printed to the console hundreds of times whenever any view changes happen.

## To Reproduce

This has been brought up before at https://github.com/i18next/react-i18next/issues/1233 Steps should still be the same, but I'm sure the underlying conditions are obvious.

## Expected behavior

The message is logged once or not at all, because I don't even see any cause for it appearing in the first place.

We support `en-US` as a language. And we set `en-US` as the language whenever we want to use it. Yet, i18next complains constantly about an `en` language that appears nowhere in our code. This is surprising and confusing. The excessive frequency at which this warning is displayed indicates a major issue, yet nothing is visible to the consumer. I don't understand the call to action here.

Why is the language hierarchy resolved for every single translation anyway? That seems as if I misconfigured i18next.

## Your Environment

- *runtime version*: Firefox 101.1
- *i18next version*: 21.8.9
- *os*: Linux
- *any other relevant information*

**Comment by adrai** [comment]
If that message appears, there must be a reason. Can you please provide a reproducible codesandbox example?

**Comment by oliversalzburg** [comment]
@adrai I can probably build one. I have since found guidance that I can set `load: "currentOnly"` to prevent this behavior. I guess, I skipped this part in the documentation as I didn't know about this.

So I'm assuming the behavior is by design and I just missed how to properly configure my i18next. If you feel that it should still be investigated, I'd be happy to create the repro. Otherwise please close the issue :)
