### ISSUE TITLE
Unable to parse locales from file (maybe /home/container/src/Client/locales/en.json is empty or invalid json?). I hace the json with the text and is a correct json

### ISSUE THREAD

**Issue by SrVideofan** [i18next/i18next#1795]
## To Reproduce

A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
please provide a reproducible example

There is not enough information to help.

Set the debug option to true and check the developer console.

Hoes your i18next config look like?
