### ISSUE TITLE
Bug: `i18n` always trys to fetch `translation.json` even when its not the `fallbackNS` or `defaultNS`

### ISSUE THREAD

**Issue by ryami333** [i18next/i18next#1805]
## 🐛 Bug Report

In my application (with `react-i18next` and `i18n-http-backend`) our "default" translation file is `locales/{{locale}}/common.json`. We have set `defaultNS` and `fallbackNS` to `common`, and we do not have a `translation` namespace in our application at all. Despite this configuration, i18n always _tries_ to fetch a `locales/{{locale}}/translation.json` file (which fails/404s because it does not exist).

The only workaround that I have found, is to explicitly set `ns` to an empty array (instead of its default value of `undefined`). This should be unnecessary, because the _computed_ value for `ns` when it is configured as `undefined` should not include the literal value `"translation"`.

## To Reproduce

Here is a link to a Codesandbox which provides a minimal-reproduction of the issue. You will see that if you open your browser dev tools and inspect network requests - there are failed requests for `locales/en/translation.json`.
https://codesandbox.io/s/gifted-hellman-0hipkl?file=/src/App.js

## Expected behavior

There should be no request to `locales/{{locale}}/translation.json` (specifically `locales/en/translation.json` in the Codesandbox repro).

## Your Environment

- *runtime version*: Not Applicable, happens in all browsers.
- *os*: Not Applicable: happens in all operating systems.
- Dependency versions:
```
i18next: 21.8.14
i18next-http-backend: 1.4.1
react-i18next: 11.18.1
react: 18.2
react-dom: 18.2
```
```

**Comment by adrai** [comment]
the default of the ns option is 'translation', so just set it to `ns: []`
<img width="809" alt="image" src="https://user-images.githubusercontent.com/1086194/180168824-e3f7c9fd-db20-42f3-b9f6-0fa01bfb1e4c.png">

**Comment by jamuhl** [comment]
you did not set `ns` array:

```js
i18next.init({
  fallbackLng: 'en',
  ns: ['file1', 'file2'],
  defaultNS: 'file1',
  debug: true
}, (err, t) => {
  if (err) return console.log('something went wrong loading', err);
  t('key'); // -> same as i18next.t
});
```
