### ISSUE TITLE
Format function return Type 'number' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by Thebigbignooby** [i18next/i18next#1808]
## 🐛 Bug Report

I'm trying to chain multiple format functions together.
The last one expects value to be a number, since i'm using the number(options) built-in formatter.
However, TypeScript won't let me return the value as a number from the previous formatter, even though the functionality works 

I know the code works because I can see the result in storybook, But when I try running my App, TypeScript isn't happy:

## To Reproduce

In my translation file:

```json
{
    "convert.distanceWithLabel":"{{value, customConverterFromKmToMi, number(minimumFractionDigits: 0, style: 'unit', unit: 'mile')}}"
}
```

in my i18n.js init file

```js
i18n.services.formatter?.add(
  'customConverterFromKmToMi',
  (value: number, lng: string | undefined, options: Record<string, string>) => {
    console.log('options', options)
    return value * 0.621371;                // <-- This works but TypeScript won't compile
    // return `${value * 0.621371}`;    // <--- This makes the following formatter to return NaN
  }
);
```

I get the following message:
```
Argument of type '(value: number, lng: string | undefined, options: Record<string, string>) => number'
  is not assignable to parameter of type '(value: any, lng: string | undefined, options: any) => string'.
  Type 'number' is not assignable to type 'string'.
```

## Expected behavior

I expect the return type of the formatter function to be either a string or number or whatever the built-in format functions accept as inputs.

## Your Environment

- *runtime version*: typescript ~4.6.2
- *i18next version*: ^21.8.2

**Comment by adrai** [comment]
the format function result is always "casted" toString() that's why it works... best would be you also always return a string.

**Comment by Thebigbignooby** [comment]
Thanks for the swift response!

If I return a string from my custom formatter, the `number` formatter returns `NaN`

**Comment by adrai** [comment]
yes, makes sense

**Comment by adrai** [comment]
it might be this definition for the add function here, could be extended to give the possibility to define a custom return type but default to string? https://github.com/i18next/i18next/blob/master/index.d.ts#L846
@pedrodurek what do you think?

**Comment by Thebigbignooby** [comment]
hmm, I encountered this problem before the weekend.
Now, Monday morning, I tried returning as a string instead, and it works, and I'm not getting `NaN` 🤯 😅 
Sorry for this, probably a brain fart on my end.

**Comment by adrai** [comment]
if this really works for you, then can you close the issue?
