### ISSUE TITLE
Fix retry logic

### ISSUE THREAD

**Issue by mattbjordan** [i18next/i18next#1809]
## 🐛 Bug Report

- Retries of reading (fetching) the same resource are treated as separate parallel processes. 
- 5 retries are required to be attempted before read's callback function is called. (Following the execution path from i18next.init(), the callback function is what allows the promise made by i18next.init() to resolve.)

If multiple resources which do not exist are requested, then maxParallelReads is reached and the deferred promise made within i18next.init() never resolves. 

This functionality exists in the read() function at i18next.js line 2107.

## To Reproduce

```ts
import i18next, { i18n, InitOptions } from "i18next";
import Backend, { BackendOptions } from "i18next-http-backend";

const namespaces: string[] = ["ns1", "ns2", "ns3"];

const backendOptions: BackendOptions = {
  loadPath: "locales/{{lng}}/{{ns}}.json",
  crossDomain: true
};

const initOptions: InitOptions = {
  backend: backendOptions,
  ns: namespaces,
  defaultNS: namespaces[0]
};

var myInstance: i18n = i18next.createInstance();

myInstance.use(Backend);

initPromise = (myInstance.init(initOptions) as unknown) as Promise<void>;

// Gets stuck here
await initPromise;
```

Oddly, it seems that the program does not actually get stuck awaiting... but it certainly is causing hanging in the background. If you trace through the execution in a debugger, you'll see that the callback function passed into read() is never called.

What I see happening in read() though, is that attempted requests for the same resource are added to the waitingReads list. If there are multiple resources which do not exist, then the waitingReads list fills up with maxParallelReads items before the 5th retry of each requested resource in the waitingReads list is tried, thus readingCalls is never decremented and the callback function is never called.

## Suggested behavior

Attempted reads on the same resource should not be added to the waitingReads list OR remove the previous try from the list before performing another attempt and decrement readingCalls.

Additionally, it would be nice for the user to be able to set how many retries to run and what the wait/timeout timeout time should be between retries. This includes the possibility of doing zero retries. 

It would also be nice to set the above per request or per resource. Say I have a default namespace that I add to every i18next instance that I create, yet most of the time there is no JSON file created for it. It would make sense to not retry requesting that resource 5 times because it is likely to not exist, yet if I added another namespaces in a particular instance of my program, then I wouldn't mind it retrying a few times. The default retry logic can add about 10 seconds to i18next initialization if it has to retry 5 times looking for a resource that doesn't exist. It would be nice to be able to change off of that default behavior.

## Your Environment

- *runtime version*: node v16.16.0, browser: electron
- *i18next version*: 21.8.14
- *i18next-http-backend version*: 1.4.1
- *os*: Windows

**Comment by jamuhl** [comment]
related to https://github.com/i18next/i18next/pull/1771

@huntharo you might help?

**Comment by jamuhl** [comment]
https://github.com/huntharo/i18next/blob/36eb343c74f92df8ae069e60748767f7457e8075/src/BackendConnector.js#L154 indeed seems wrong filling the waitingReads - would be better to do the retries without pushing them to the waitQueue

**Comment by adrai** [comment]
@mattbjordan can you check if moving these lines would be better?

```diff
read(lng, ns, fcName, tried = 0, wait = 350, callback) {
    if (!lng.length) return callback(null, {}); // noting to load

    // Limit parallelism of calls to backend
    // This is needed to prevent trying to open thousands of
    // sockets or file descriptors, which can cause failures
    // and actually make the entire process take longer.
    if (this.readingCalls >= this.maxParallelReads) {
      this.waitingReads.push({ lng, ns, fcName, tried, wait, callback });
      return;
    }
    this.readingCalls++;

    return this.backend[fcName](lng, ns, (err, data) => {
+      this.readingCalls--;
+      if (this.waitingReads.length > 0) {
+        const next = this.waitingReads.shift();
+        this.read(next.lng, next.ns, next.fcName, next.tried, next.wait, next.callback);
+      }
      if (err && data /* = retryFlag */ && tried < 5) {
        setTimeout(() => {
          this.read.call(this, lng, ns, fcName, tried + 1, wait * 2, callback);
        }, wait);
        return;
      }
-      this.readingCalls--;
-      if (this.waitingReads.length > 0) {
-         const next = this.waitingReads.shift();
-        this.read(next.lng, next.ns, next.fcName, next.tried, next.wait, next.callback);
-      }
      callback(err, data);
 });
```

**Comment by adrai** [comment]
additionally we could omit to push to `waitingReads` if `tried > 0`

**Comment by adrai** [comment]
with v21.8.15 the promise / callback should now at least return, for the rest (custom retry logic etc... feel free to open a new PR)

**Comment by huntharo** [comment]
I'm curious as to what it did before... I wonder if it was 100% correct or if the lack of a limit on parallel reads obscured the problem?  Checking out of curiousity.
