### ISSUE TITLE
Add Customizable Retry Logic

### ISSUE THREAD

**Issue by mattbjordan** [i18next/i18next#1814]
## 🚀 Feature Proposal

Allow users to customize how read request retries are handled.

Suggested options:
- Set how many retries to perform before giving up
	- Including doing no retries
- Set how long the wait should be between retries
	- Possibly also how the wait value should increase with subsequent retries
	- Or even a different algorithm for performing retries (admittedly, this may be a bit overkill)
- (Could be nice, but probably not as useful/important:) Set the above two criteria either per request, per resource/namespace, or both

## Motivation

Currently, by default, if a request fails (throws an error), it is retried up to 5 times with an increasing delay between retries. This adds up to 10.85 wasted seconds when a request is "destined" to fail - i.e. some situation where it will never succeed regardless of the number of retries.

The read request could be destined to fail in certain situations. Perhaps the fetch api in a project is custom or from a particular package. Perhaps there are a set of tests which expect failures; each test would take a wasted 10.85 seconds extra. 

I'll also add that the default behavior doesn't have to change. The default number of retries and timeouts can stay as they are now.

## Example

```ts
import i18next, { i18n, InitOptions } from "i18next";

const namespaces: string[] = ["myNamespace"];

const initOptions: InitOptions = {
  ns: namespaces,
  defaultNS: namespaces[0],
  // Set custom retry options
  maxRetries: 2,		// Could be as low as zero
  retryTimeout: 500,		// Assuming milliseconds 
};

var myInstance: i18n = i18next.createInstance();

// Initialize with custom retry options set
myInstance.init(initOptions);
```

**Comment by jamuhl** [comment]
PR welcome

**Comment by mattbjordan** [comment]
@jamuhl How can I get permission to push a new branch in this repo so I can make PR?

**Comment by jamuhl** [comment]
You don't need any permissions: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

you can do it from a fork

**Comment by mattbjordan** [comment]
I'll add that more *could* be done here; e.g., the ability to customize the algorithm for retries such as replacing the default `previousWait * 2` timeout for each retry with a custom function and/or multiplier. However, *I* don't care enough to think about or implement more functionality right now, so I'm happy to close this issue.
