### ISSUE TITLE
Add key suffix feature

### ISSUE THREAD

**Issue by AkiraVoid** [i18next/i18next#1824]
## 🚀 Feature Proposal

We've got key prefix feature which enable us adding a prefix to key every time we call `t`, but we don't have a key suffix option.

## Motivation

JSON structure like this:

```json
{
  "key": {
    "message": "translation",
    "description": "what this translation is used for"
  }
}
```
is used usually.

## Example

Add a suffix ".message" to key, so that JSON structures which are similar to above can be handled easily.

**Comment by adrai** [comment]
The keyPrefix was introduced because of deeper/longer nested key structures.
Having a keySuffix looks not that useful IMO...
If in future there are more users requesting this, we would consider to accept a PR to i18next and react-i18next.

**Comment by AkiraVoid** [comment]
So, is there any workaround about this? I have searched for nearly 8 hours.

**Comment by AkiraVoid** [comment]
Or, `returnedObjectHandler` can do something similar, but how could I enable interpolation in this function?

**Comment by adrai** [comment]
create your own t function, something like this:

```js
const getT = (keySuffix) => (key, opt) => t(key + '.' + keySuffix, opts)

const myT = getT('message')
console.log(myT('key'))
```

**Comment by AkiraVoid** [comment]
This solution cannot use `$t()`.

**Comment by adrai** [comment]
What do you mean?
It's the same like using `t('key.message')`

**Comment by AkiraVoid** [comment]
I mean we could use:
```json
{
  "key1": "translation",
  "key2": "translated: $t(key1)"
}
```
but if I define a custom TFunction, `key2` will result in `translated: 'key1 (locale)' returned an object instead of string.`

**Comment by AkiraVoid** [comment]
I guess we need some hooks to hook into every stage of TFunction and edit the value in every stage.

**Comment by adrai** [comment]
Sorry, I don't know what you mean...
$t() knows nothing about keyPrefix or any custom suffixes... it's not t() it's a different construct for nesting inside the translations. And inside the translations you see the key structure.

**Comment by adrai** [comment]
This works without any problems:

```js
i18next.init({
  lng: 'en',
  resources: {
    en: {
      translation: {
        key: {
          message: 'this will nest $t(someOtherKey.message)',
          description: 'some description'
        },
        someOtherKey: {
          message: 'some translation',
          description: 'some other description'
        }
      }
    }
  }
})

console.log(i18next.t('key.message'))

const getT = (keySuffix) => (key) => i18next.t(key + '.' + keySuffix)
const myT = getT('message')

console.log(myT('key'))
```

**Comment by AkiraVoid** [comment]
Yes this what I am doing. But I still think we need some life cycle hooks for customizing every process of translation. Currently a plug-in can be used to load resources and do something after translation, but what can we do in translating?

**Comment by adrai** [comment]
btw, alternatively, if your complete structure is the way you only always use the message value, you can also prepare the resources before using them:

```js
const resources = {
  key: {
    message: 'this will nest $t(someOtherKey)',
    description: 'some description'
  },
  someOtherKey: {
    message: 'some translation',
    description: 'some other description'
  }
}
const preparedResources = Object.keys(resources).reduce((ret, key) => {
  ret[key] = resources[key].message
  return ret
}, {})
console.log(preparedResources)
// {
//   key: 'this will nest $t(someOtherKey)',
//   someOtherKey: 'some translation'
// }
```

**Comment by adrai** [comment]
Sorry, but I still don't understand what the pain point is here.
The i18next format works like that... you need a json, it can be a nested json or a flat json, and you can reference some other keys by using the $t() from within the translations...

Really, I don't get what you want to achieve with something like life cycle hooks, etc... sorry.

**Comment by AkiraVoid** [comment]
Sorry for my poor explanation, I will try to make it clearer.

In fact, I am not just talking about this issue, I mean we should make customization of i18next easier. i18n have many configurations, but it is hard to customize to achieve such a simple function. Also, the main code of i18n doing a lot of things and all we could do is seeing it running. Instead of adding more configurations to it, can we separate each part of code and make them independent so that we could customize each part of i18n?

**Comment by adrai** [comment]
To be honest we think there are too many configuration options currently, we were thinking of removing a lot of them to make things more "standard". It's hard to keep the compatibility of all combinations for all configuration options in all different setups with different plugins, etc...
I hope you understand.

so tldr; there is already too much flexibility

**Comment by AkiraVoid** [comment]
For example, like unified.js.

**Comment by AkiraVoid** [comment]
Anyway, I am glad to know things are getting better. I will close this issue. Thanks for you all.
