### ISSUE TITLE
I18next not working on old mac devices.

### ISSUE THREAD

**Issue by MrFarhan** [i18next/i18next#1827]
## 🐛 Bug Report

Everything works fine in all devices except old mac devices especially with IOS 12.4.

## To Reproduce

[Github repo](https://github.com/MrFarhan/next-intl-test.git).
A [Live URL](https://next-intl-test-one.vercel.app/) 

To reporduce open the same website on any other device it should show `Hello world EN` where as in mac ios version 12.4 it will show as Login.login`.

## Expected behavior
It should show `Hello world EN` 

## Your Environment

- *runtime version*: i.e. node v14, Ubuntu, browser Safari (issue is in iPad IOS version 12.4)
- *i18next version*: i.e. 19.5.3

**Comment by jamuhl** [comment]
what safari version? my guess...outdated browser not supporting Intl API or some other modern stuff....try debugging -> find whats causing the problem...shim/polyfill if your product needs to support outdated devices

**Comment by adrai** [comment]
for next-intl check out https://github.com/amannn/next-intl
if you prefer i18next then check out https://github.com/i18next/next-i18next

**Comment by MrFarhan** [comment]
@adrai I also don't have that old device, i have tested this on emulator.

**Comment by MrFarhan** [comment]
> outdated browser

@jamuhl My client reported this issue that translation is not working on his ipad, so i just installed iPad IOS version 12.4 emulator and it is creating the same issue.

**Comment by adrai** [comment]
like said... seems you're not using i18next

**Comment by MrFarhan** [comment]
Yes, Sorry for that, I have created an issue on `next-intl`.

Thank you for your time guys :)
