### ISSUE TITLE
console.log presents in browser console at the time of changing language from i18next.js

### ISSUE THREAD

**Issue by bapan25** [i18next/i18next#1831]
## 🐛 Bug Report

console.log(i18next: languageChanged) present in browser console when changing the language.

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here

const { t, i18n  } = useTranslation();

    const translateLanguage = (event) => {
        i18n.changeLanguage(event);
//logs are getting printed after this into browser console.
    }
```

## Expected behavior

There should be no logs in browser console
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
-  node v16.15.0
- *i18next version*: i.e. 19.5.3
-  21.9.1
- *os*: Mac, Windows, Linux
- *any other relevant information*
- 
![Capture](https://user-images.githubusercontent.com/32136351/189040610-070732f8-93e7-4c45-9898-5122e8730bed.PNG)

**Comment by bapan25** [comment]
![Capture](https://user-images.githubusercontent.com/32136351/189041045-801ad442-2323-4758-821d-d799b5956ce4.PNG)

**Comment by adrai** [comment]
How does your i18next config look like?
I suspect you've set debug to true.
Just set it to false.
