### ISSUE TITLE
Single quotes are replaced incorrectly using nested interpolation

### ISSUE THREAD

**Issue by evantrimboli** [i18next/i18next#1836]
## 🐛 Bug Report

When using nesting and interpolation, it seems like the single quote passed as a value is replaced by a double quote which breaks the parameter passing.

## To Reproduce

https://stackblitz.com/edit/typescript-z85e23?file=index.ts,index.html

```typescript
i18next
  .init({
    lng: 'en', // if you're using a language detector, do not define the lng option
    interpolation: {
      escapeValue: false,
    },
    resources: {
      en: {
        translation: {
          foo: '$t(bar, {"firstName": "{{firstName}}", "lastName": "{{lastName}}" })',
          bar: '{{firstName}} {{lastName}}',
        },
      },
    },
  })
  .then((t) => {
    const a = { firstName: `Cool`, lastName: `Dood` };
    const b = { firstName: `Cool`, lastName: `O'Dood` };
    console.log(t('foo', a), t('bar', a), t('foo', a) === t('bar', a));
    console.log(t('foo', b), t('bar', b), t('foo', b) === t('bar', b));
  });
```

## Expected behavior
The values should match. In the logs here the values should match and return true.

```typescript
console.log(t('foo', a), t('bar', a), t('foo', a) === t('bar', a));
console.log(t('foo', b), t('bar', b), t('foo', b) === t('bar', b));
```

## Your Environment

- *runtime version*: Chrome  104.0.5112.102
- *i18next version*: 21.9.1
- *os*: Windows

## Other info
It seems the replacement is occurring here:

https://github.com/i18next/i18next/blob/9304a251e54d58cda88fb484299bef67f2025c2e/i18next.js#L1750

**Comment by adrai** [comment]
Can you try with v21.9.2?
It is not perfect, but it should work for more use cases (also for yours)

**Comment by evantrimboli** [comment]
That resolves my issue. Thanks very much.

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
