### ISSUE TITLE
No default export in cjs modules

### ISSUE THREAD

**Issue by davidsl4** [i18next/i18next#1838]
## 🐛 Bug Report

There is no default export (module.exports.default) in CJS file.
TS definition file does declare a default export.

## To Reproduce

Not required. Open the built CJS file and scroll to the bottom to see how there are no default exports.

## Expected behavior

There should be an additional statement to assign a "default" export.

```js
module.exports.default = instance;
```

## Your Environment

- *runtime version*: node v16
- *i18next version*: i.e. i18next@21.9.2
- *os*: Mac

**Comment by adrai** [comment]
https://github.com/i18next/i18next/issues/1447#issuecomment-631543629
