### ISSUE TITLE
Allow missingInterpolationHandler to return value other than a string

### ISSUE THREAD

**Issue by pwolaq** [i18next/i18next#1844]
Hello again (and thanks for your review & merging my previous PR) :)

## 🚀 Feature Proposal
I have noticed that `missingInterpolationHandler` [does not accept values other than string](https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L132) - for example if you try to return a number you get empty string as a result. I was wondering if there is a reason behind that logic or maybe we are able to change it to allow returning any value.

## Motivation

Accepting only strings probably works in most scenarios but I can think of cases when someone would use this handler along with formatters:

```
/ * missingInterpolationHandler returns 1000 */
"You have {{ missingValue | number }} coins."

/* with current logic */
"You have NaN coins."

/* with suggested changes */
"You have 1,000 coins."
```

What do you think?

**Comment by adrai** [comment]
I don't know... this was introduced long time ago... by @JanTrotnow : https://github.com/i18next/i18next/commit/e84ab79942a3efe63390dfb3d6731edeccbc759d
