### ISSUE TITLE
joinArrays documentation & missingKeyHandler to handle any missing keys

### ISSUE THREAD

**Issue by agoenks29D** [i18next/i18next#1845]
## Documentation issue
I think you forgot to put `joinArrays` example here :  [Configuration Options - Translation Defaults](https://www.i18next.com/overview/configuration-options#translation-defaults)

## Motivation
I didn't understand what the mean from the `joinArrays` configuration and not linked to example of [Object and Array](https://www.i18next.com/translation-function/objects-and-arrays) 

## Another Question
Can i get missing key while i using `fallbackLng` found the key defined in another locale?

an example : 
- locales/
	- en/
		- app.json
	- id/
		- app.json

**locales/en/app.json** (English)
```json
{
	"title": "Hello {{ name }}",
	"description": "i18next is the best"
}
```

**locales/id/app.json** (Indonesian)
```json
{
	"title": "Halo {{ name }}"
}
```

**load-with-fs-backend.js**
```javascript
i18next.init({
	ns: ['app'],
	defaultNS: 'app',
	fallbackNS: ['app'],
	fallbackLng = ['en']
	...
}, (err, t) => {
	console.log(t('description', { lng: 'id' })) // will return : i18next is the best
});
```
Indonesian locale missing the "description" key in resource, and there not shown in `missingKeyHandler`

**Comment by jamuhl** [comment]
Thank you for reporting...just added the sample string to joinArray docs....

Regarding your question. No...if i18next can somehow find a value for given key (going through fallbackLng, fallbackNS) it won't be missing. To assert you got all translations in the various languages you provide to your users you might considering using a translation management like our locize.com or some free alternatives:

- https://github.com/locize/translation-check
- https://github.com/felixmosh/i18next-locales-sync

**Comment by agoenks29D** [comment]
Sure, thanks for the answer..
