### ISSUE TITLE
[Docs] Add new vite-plugin-i18next-loader - bundler + hmr

### ISSUE THREAD

**Issue by rosskevin** [i18next/i18next#1846]
## Documentation issue
I need to add our new plugin https://github.com/alienfast/vite-plugin-i18next-loader to the https://www.i18next.com/overview/plugins-and-utils page.

`Vite plugin to client bundle i18next locales composited from one to many json/yaml files from one to many libraries. Zero config HMR support included.`

## Motivation

Share the goodness.

I didn't see any way for me to login to gitbook to propose the change, but I'm unfamiliar with gitbook.  Any pointers and I will do it myself...

**Comment by adrai** [comment]
it's connected with github: https://github.com/i18next/i18next-gitbook/blob/master/overview/plugins-and-utils.md
Just create a PR
