### ISSUE TITLE
Add shortcut to allow auto forwarding of parameters

### ISSUE THREAD

**Issue by evantrimboli** [i18next/i18next#1847]
## 🚀 Feature Proposal

The ability to use interpolation to refer to other keys with automatic parameter forwarding. Anything with the the proposed marker would forward along all parameters passed to it.

## Motivation

Consider the following structure. The `displayName` is separated out because depending on the locale it might make sense to display it differently on different screens.

```json
{
  "detail": {
    "displayName": "$t(shared.displayName, {\"firstName\": \"{{firstName}}\", \"lastName\": \"{{lastName}}\" })"
  },
  "list": {
    "displayName": "$t(shared.displayName, {\"firstName\": \"{{firstName}}\", \"lastName\": \"{{lastName}}\" })"
  },
  "shared": {
    "displayName", "{{firstName}} {{lastName}}"
  }
}
```

Trying to forward the values on is difficult due to the escaping.

## Example

If there were some syntax similar to `$t`, say `$tf` (for forward). For example:

```typescript
// { firstName: 'Foo', lastName: 'Bar' } will automatically be forwarded on to shared
i18n.t('detail.displayName', { firstName: 'Foo', lastName: 'Bar' });
```

```json
{
  "detail": {
    "displayName": "$tf(shared.displayName)"
  },
  "list": {
    "displayName": "$tf(shared.displayName)"
  },
  "shared": {
    "displayName", "{{firstName}} {{lastName}}"
  }
}
```

Thanks for your consideration.

**Comment by jamuhl** [comment]
The escaping and adding of interpolation values inside the nesting is only needed if you need to rename the variables...the untouched variables get forwarded as is:

https://www.i18next.com/translation-function/nesting#passing-options-to-nestings just renames the count needed for plural!!!

```js
i18n.t('detail.displayName', { firstName: 'Foo', lastName: 'Bar' });
{
  "detail": {
    "displayName": "$t(shared.displayName)"
  },
  "list": {
    "displayName": "$t(shared.displayName)"
  },
  "shared": {
    "displayName": "{{firstName}} {{lastName}}"
  }
}
```

This already works with `$t()`

**Comment by evantrimboli** [comment]
Understood, can't believe I didn't check this behaviour first.

Thanks!
