### ISSUE TITLE
i18next changeLanguage not working outside of component

### ISSUE THREAD

**Issue by Bowis** [i18next/i18next#1849]
## 🐛 Bug Report

have a large amount of strings that are outside the components that i use. Such as:

defaultMaterial: {
      name: i18n.t("types.1.defaultMaterial.title"),
      footprint: i18n.t("types.1.defaultMaterial.footprint", {
        returnObjects: true,
      }),
      footprintSource: i18n.t("types.1.defaultMaterial.footprintSource", {
        returnObjects: true,
})
On a screen in my app i have build a switch that allows the user to switch languages, using: i18n.changeLanguage("en");

But it seems like the changeLanguage function does only work for the translations that are directly used in the components, not for the translations that are used in the utility function outside the components. How could I fix this?
## Expected behavior

Strings being translated correctly when changing languages.

**Comment by Bowis** [comment]
@adrai  is there a way to execute that t function again when the language has changed?

**Comment by adrai** [comment]
The problem is i18n.t is probably not called again.

If you provide a minimal reproducible example I can try to explain better...

**Comment by Bowis** [comment]
I18n init: 

```
export const resources = {
  en: {
    translation: translationEN,
  },

  nl: {
    translation: translationNL,
  },
};

i18n.use(initReactI18next).init({
  resources,
  lng: "en",
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;

Translation file 



```
"types": [
    {
      "name": "Constructie",
      "defaultMaterial": {
        "title": "Prefab Beton",
        "footprint": {
          "Aantal m2 materiaal per woning": "200 m2",
          "Aantal kg CO2 per m2 materiaal": "40,72 kg / m2",
          "Totale kg CO2 uitstoot per woning (GWP)": "200 x 40,72 = 8144 kg",
          "Totale kg CO2 opslag per woning (GWP-b)": "-",
          "Totale kg CO2 footprint per woning": "8144 kg"
        },
        "footprintSource": [
          "Bron: Alba Concepts",
          "Voor meer informatie over de berekeningen: www.albaconcepts.nl"
        ]
      },
      "materials": [
        {
          "name": "Ecococon",
          "company": "Strotec B.V.",
          "description": "Strotec is de partij achter het prefab-snelbouwsysteem EcoCocon dat in principe geschikt is voor elk gebouw. Het is voor 99% biobased en bestaat voor 10% uit hout en 89% stro. Het is damp-open, maar isoleert optimaal. Stro slaat tijdens de groei grote hoeveelheden CO2 op en is een agrarisch restproduct. Omdat het jaarlijks geoogst wordt, wordt er tot wel vijftien keer zoveel CO2 per jaar in opgeslagen als bijvoorbeeld in hout. Met dit systeem kan er zelfs CO2-negatief gebouwd worden en worden overige bouwmaterialen gecompenseerd.",
          "madeFrom": [
            "89% stro",
            "10% hout",
            "1% damp-open folie en herbruikbare metalen houtdraadbouten waarmee de elementen aaneen worden geschroefd."
          ],
          "application": "De bouwelementen worden toegepast als damp-open, constructieve binnen-buitengevels voor woningen (Eindhoven, Oostmahorn, Kaatsheuvel), Sporthal (Tegelen), scholen (Almere, Amsterdam), kantoren (Helmond) en kunnen in combinatie met CLT ook worden toegepast voor gestapelde bouw.",
          "environmentalImpact": [
            "Het materiaal is 99% biobased.",
            "Het maakt CO2-neutraal bouwen (of zelfs CO2-negatief) mogelijk.",
            "EcoCocon slaat per woning ongeveer twaalf ton CO2 op.",
            "Graan wordt jaarlijks geoogst, daardoor wordt er tot wel vijftien keer zoveel CO2 opgeslagen als bijvoorbeeld in hout.",
            "Na eventuele afbraak (vijftig tot honderd jaar) kan het materiaal per element hergebruikt worden en – uiteindelijk voor 99% – zo terug de natuur in."
          ],
          "goodToKnow": [
            "Ecococon zorgt voor een weldadig binnenklimaat; gelijkmatige temperatuur en luchtvochtigheid.",
            "Fijne akoestiek, zeker in combinatie met leem.",
            "Brandcertificaat van 120 minuten.",
            "Superisolatie (Rc 8,3), daarmee is er amper installatie nodig voor verwarming en koeling.",
            "Vormvrij bouwconcept (elk ontwerp past er in)."
          ],
          "info": ["www.strotec.nl", "www.ecococon.eu.nl"],
          "productionProcess": [
            "Graan groeit op de akker (in Nederland voldoende voor 75.000 huizen per jaar).",
            "Graan wordt geoogst en gedorst; waarbij het stro overblijft als restproduct.",
            "In een bedrijfshal worden – op basis van ontwerp – houten frames exact op maat gemaakt.",
            "In deze HSB-kratten wordt de inmiddels gedroogde stro geperst (maximaal 15% luchtvochtigheid).",
            "Dan worden de bouwelementen genummerd en last-minute op de bouw aangeleverd of in een bedrijfshal voor pre-assemblage van complete gevels.",
            "Het materiaal kan na eventuele afbraak hergebruikt worden en terug de natuur in."
          ],
          "growthOpportunities": "Omdat de bouw een grote CO2 uitstotende sector is zal de norm voor CO2-uitstoot steeds verder worden aangescherpt. Strotec biedt hier met haar volledig biobased en cradle-to-cradle bouwsysteem een serieus alternatief voor. Omdat de grondstoffen ruim voorradig zijn, zijn de groeimogelijkheden haast oneindig. Vooral omdat het -in de akkoorden van Parijs- afgesproken CO2 plafond binnen 3 tot 5 jaar bereikt is, en elk deze biobased woningen er 3 reguliere kan compenseren.De snel bouwelementen worden tot nu toe nog alleen geproduceerd in Litouwen, maar er komt een productielijn in Nederland wanneer er hier voldoende afzet is.",
          "footprint": {
            "Aantal m2 materiaal per woning": "200 m2",
            "Aantal kg CO2 per m2 materiaal": "32,85 kg / m2",
            "Totale kg CO2 uitstoot per woning (GWP)": "200 x 32.85 = 6570 kg",
            "Totale kg CO2 opslag per woning (GWP-b)": "19520 kg",
            "Totale kg CO2 footprint per woning": "6570 – 19520 = -12950 kg"
          },
          "footprintSource": [
            "CO2 berekening op basis van indicatieve EPD (Environmental Product Declaration)",
            "Bron: EPD Strotec (indicatief)",
            "Voor meer informatie over de berekeningen: www.albaconcepts.nl"
          ],
          "groundSuffix": "stro benodigd per woning"
        },
        {
          "name": "CLT",
          "company": "Ekoflin",
          "description": "CLT (Cross Laminated Timber) heeft een meerlaagse structuur en is geheel gemaakt van duurzaam geproduceerd hout. Het is een modern en bewezen degelijk bouwmateriaal. Op maat geprefabriceerde CLT panelen isoleren warmte en kunnen tegelijkertijd grote lasten dragen. Bovendien zijn ze brandwerend en hebben een geluiddempend effect. Er kan op snelle wijze mee worden geconstrueerd en het is een “droog” bouwsysteem. Tevens heeft het een zeer positieve invloed op ons wooncomfort en op het welzijn van de mensen in deze “houten omgeving”, of het nu gaat om woningen, scholen, verzorgingscentra of appartementencomplexen. Het vlakke naadloze oppervlak van het materiaal en de speciale ontwerpen zorgen voor goede bouwfysische, brandwerende en mechanische eigenschappen. Tevens wordt luchtdicht bouwen een stuk eenvoudiger vanwege het nagenoeg naadloze concept. CLT is universeel toepasbaar en makkelijk te combineren met traditionele bouwsystemen van gevels en daken. Daardoor kan het eenvoudig en flexibel worden toegepast in combinatie met bestaande gevel afwerkmaterialen zoals baksteen, stucwerk en houten gevelsystemen.",
          "madeFrom": [
            "99,4% uit duurzaam geproduceerd hout",
            "0,6% uit ecologisch verantwoorde pu-lijm"
          ],
          "productionProcess": [
            "Bouwen met hout is positief in elk opzicht. Hout staat immers bekend als een natuurlijke en duurzame grondstof met vele mogelijkheden.",
            "Binnen de productie van Binderholz worden de geleverde boomstammen volledig verwerkt tot CLT, gelamineerd hout, 3S en 5S plaatmateriaal en pellets.",
            "De energie die wordt gebruikt bij het productieproces en in de gebouwen wordt grotendeels opgewekt met eigen biomassacentrales.",
            "Hiermee leveren de producten van Binderholz in velerlei opzichten een positieve bijdrage aan een lagere CO2-uitstoot en daarmee aan de bescherming van het klimaat."
          ],
          "application": "CLT is toe te passen in woningen (PUUR Wonen in Meerhoven), scholen, appartementen (Paviljoen Eikenburg) en studentenhuisvestingen.",
          "environmentalImpact": [
            "Het materiaal is 99,6% biobased.",
            "Het maakt CO2-neutraal bouwen (of zelfs CO2-negatief) mogelijk."
          ],
          "goodToKnow": [
            "Elke m3 hout bevat ongeveer 650 kg CO2!",
            "Het gebruik van hout als duurzame grondstof vermindert de toename van CO2 in de atmosfeer en neutraliseert dus het broeikaseffect",
            "Bomen absorberen CO2 en slaan dit voor lange tijd op in de vorm van biogene koolstof.",
            "5-laags CLT hout heeft altijd een brandwerendheid van 60 minuten, met een behandeling is een brandwerendheid van 120 minuten haalbaar."
          ],
          "info": ["www.ekoflin.com"],
          "growthOpportunities": "Ekoflin speelt in op de groeiende behoefte van de markt om energiezuinig, milieubewust, snel en flexibel te bouwen.",
          "footprint": {
            "Aantal m3 materiaal per woning": "20 m3",
            "Aantal kg CO2 per m3 materiaal": "376,96 kg / m3",
            "Totale kg CO2 uitstoot per woning (GWP)": "20 x 376.96 = 7539,2 kg",
            "Totale kg CO2 opslag per woning (GWP-b)": "14360 kg",
            "Totale kg CO2 footprint per woning": "7539,2 – 14360 = -6820,8 kg"
          },
          "footprintSource": [
            "CO2 berekening op basis van indicatieve EPD (Environmental Product Declaration)",
            "Bron: EPD Ekoflin",
            "Voor meer informatie over de berekeningen: www.albaconcepts.nl"
          ],
          "groundSuffix": "bomen (30m hoog) benodigd per woning"
        }
      ]
    },
]
```


data file which is called from the components: 

```
export const data = [
  {
    type: i18n.t("selectionScreen.types.0"),
    image: construction,
    color: constructieKleur,
    defaultMaterial: {
      name: i18n.t("types.0.defaultMaterial.title", {
        lng: language ? language : i18n.language,
      }),
      footprint: i18n.t("types.0.defaultMaterial.footprint", {
        returnObjects: true,
      }),
      footprintSource: i18n.t("types.0.defaultMaterial.footprintSource", {
        returnObjects: true,
      }),
      co2: 8144,
      image: prefab,
    },
    materials: [
      {
        name: i18n.t("types.0.materials.0.name"),
        company: i18n.t("types.0.materials.0.company"),
        description: i18n.t("types.0.materials.0.description"),
        madeFrom: i18n.t("types.0.materials.0.madeFrom", {
          returnObjects: true,
        }),
        application: i18n.t("types.0.materials.0.application"),
        environmentalImpact: i18n.t("types.0.materials.0.environmentalImpact", {
          returnObjects: true,
        }),
        goodToKnow: i18n.t("types.0.materials.0.goodToKnow", {
          returnObjects: true,
        }),
        info: i18n.t("types.0.materials.0.info", {
          returnObjects: true,
        }),
        productionProcess: i18n.t("types.0.materials.0.productionProcess", {
          returnObjects: true,
        }),
        growthOpportunities: i18n.t("types.0.materials.0.growthOpportunities"),
        footprint: i18n.t("types.0.materials.0.footprint", {
          returnObjects: true,
        }),
        footprintSource: i18n.t("types.0.materials.0.footprintSource", {
          returnObjects: true,
        }),
        output: 2,
        image: strotec,
        co2: -12950,
        trees: 540,
        ground: 3300,
        groundSuffix: i18n.t("types.0.materials.0.groundSuffix"),
        features: [
          features[0],
          features[1],
          features[3],
          features[6],
          features[8],
        ],
      },
      {
        name: i18n.t("types.0.materials.1.name"),
        company: i18n.t("types.0.materials.1.company"),
        description: i18n.t("types.0.materials.1.description"),
        madeFrom: i18n.t("types.0.materials.1.madeFrom", {
          returnObjects: true,
        }),
        productionProcess: i18n.t("types.0.materials.1.productionProcess", {
          returnObjects: true,
        }),
        application: i18n.t("types.0.materials.1.application"),
        environmentalImpact: i18n.t("types.0.materials.1.environmentalImpact", {
          returnObjects: true,
        }),
        goodToKnow: i18n.t("types.0.materials.1.goodToKnow", {
          returnObjects: true,
        }),
        info: i18n.t("types.0.materials.1.info", {
          returnObjects: true,
        }),
        output: 5,
        co2: -6820,
        trees: 284,
        ground: 20,
        groundSuffix: i18n.t("types.0.materials.1.groundSuffix"),
        growthOpportunities: i18n.t("types.0.materials.1.growthOpportunities"),
        footprint: i18n.t("types.0.materials.1.footprint", {
          returnObjects: true,
        }),
        footprintSource: i18n.t("types.0.materials.1.footprintSource", {
          returnObjects: true,
        }),
        image: ekoflin,
        features: [
          features[0],
          features[1],
          features[3],
          features[6],
          features[9],
        ],
      },
    ],
  },
]
```

**Comment by Bowis** [comment]
I am sorry, but what information is missing for you, the data is called from the react native components, which also change the language. What more information would a codesandbox example provide? I am merely wondering if it is possible to fix this, otherwise I will use a database for it.

**Comment by adrai** [comment]
This is a reproducible example: https://codesandbox.io/s/react-i18next-http-example-forked-yq5h6m?file=/src/app.js

Basically, you need to make sure the i18n.t function is called after the language has been changed.

**Comment by Bowis** [comment]
@adrai Thanks, that makes sense. So converting the array into a function that returns the array makes it so that the library is able to pass on the language change? Am i understanding correctly?

**Comment by adrai** [comment]
Yes, but this is not a problem of the library, but a normal JavaScript behaviour... => https://codesandbox.io/s/react-i18next-http-example-forked-ce3yme?file=/src/app.js
