### ISSUE TITLE
V12 Type errors with children

### ISSUE THREAD

**Issue by sklawren** [i18next/i18next#1859]
In React 18, after updating to v12 and setting up the i18next.d.ts file according to the docs, I am getting a lot of TypeScript errors relating to children in native tags (like `<a>`) and custom components with `children: ReactNode`

- TS2746: This JSX tag's 'children' prop expects a single child of type 'ReactI18NextChild | Iterable ', but multiple children were provided.
- TS2746: This JSX tag's 'children' prop expects a single child of type 'ReactI18NextChild | Iterable<ReactI18NextChild>', but multiple children were provided.
- TS2322: Types of property 'children' are incompatible.     Type 'ReactI18NextChild | Iterable<ReactI18NextChild>' is not assignable to type 'ReactNode'.       Type 'Record<string, unknown>' is not assignable to type 'ReactNode'.         Type 'Record<string, unknown>' is missing the following properties from type 'ReactPortal': key, children, type, props

How do I resolve these?

**Comment by pedrodurek** [comment]
Hey @sklawren, do you mean like this?
```tsx
<a>{t('key')}</a>
```

**Comment by AndresDanciu** [comment]
Same problem, with React 18 and Typescript configured.

Example:
![image](https://user-images.githubusercontent.com/44430251/199131834-2a24878b-d2ea-4fef-8fa2-389eb50c53b3.png)

**Comment by nguyenhoanglam** [comment]
same issue

**Comment by jordan-bite** [comment]
Same issue. This is not the same error as in the above link.

**Comment by DSamniashvili** [comment]
Same issue here!! Any solutions?

**Comment by belgattitude** [comment]
Depending on setup, a workaround could be to lock i18next to v12.3.0 till we figure out. See https://github.com/i18next/i18next/issues/1881

**Comment by adrai** [comment]
v22.4.3

**Comment by MartaGolabek** [comment]
I experience similiar typescript errors after React 18 update (i18next version: 22.4.4) for translations with dynamic keys (known only at runtime), e.g. t(value).

I receive following errors:

-  `Type 'string | { label: string; text: string; tooltip: string; } | { tooltip: string; test: string; test_other: string; success_one: string; success_other: string; failure_one: string; failure_other: string; } | ... 25 more ... | { ...; }' is not assignable to type 'ReactNode'.`
- Type '{ tooltip: string; }' is not assignable to type 'ReactI18NextChild | Iterable<ReactI18NextChild>'.


The errors go away when I remove `resources` in CustomTypeOptions in i18n.d.ts file.

Can anybody help with that?

**Comment by adrai** [comment]
@MartaGolabek have you tried with v22.4.5?
If so, can you provide a reproducible example?

**Comment by MartaGolabek** [comment]
@adrai yes, I have set returnNull to false. I will try the version 22.4.5.

**Comment by MartaGolabek** [comment]
@adrai here I have reproduced one of the errors in the codesandbox: https://codesandbox.io/s/typescript-errors-after-react-18-update-8083ny?file=/src/App.tsx

The error occurs in the App.tsx component.

**Comment by adrai** [comment]
> @adrai here I have reproduced one of the errors in the codesandbox: https://codesandbox.io/s/typescript-errors-after-react-18-update-8083ny?file=/src/App.tsx
> 
> The error occurs in the App.tsx component.

No Idea of how this should work if the translations are not provided in the CustomTypeOptions...
How should TypeScript "know" there is a translation coming via backend without providing it via CustomTypeOptions?

So basically, you need to choose: Having type sage translations => CustomTypeOptions vs. having dynamic translations

alternatively, you can provide a defaultValue:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/1086194/207661746-63187912-67f6-485e-9848-785ee9b3dffc.png">

**Comment by MartaGolabek** [comment]
@adrai I think there is a misunderstanding. I do provide translations in the CustomTypeOptions:
![image](https://user-images.githubusercontent.com/15276644/207809258-0cbbd062-3a5e-4e32-8ced-5b1a270c6d7e.png)

What I fetch from the backend are thetranslation keys, but I know that they are of type `TFuncKey<"test1">` (explicitly typed) so using them in a t function should return a valid translation of type string, shouldn't it?

**Comment by adrai** [comment]
> https://codesandbox.io/s/typescript-errors-after-react-18-update-8083ny?file=/src/App.tsx

@MartaGolabek maybe you also used the wrong key in your example? Because notNested, does not exist in your json.

Try this:
<img width="764" alt="image" src="https://user-images.githubusercontent.com/1086194/207810733-0dde87f9-a91c-4ed4-9b1c-e7aff33a456a.png">

**Comment by MartaGolabek** [comment]
@adrai I have corrected the key in the example, but in the prod environment I was using correct keys. Also when I am casting the translation:
`t(keyKnownOnlyAtRuntime) as string` 
it works, but I think it is a code smell to cast it everywhere like this.

I would like to receive a value of type string from the `t` function when I am passing a correct key of type TFuncKey<"test1">.  I would be grateful for any ideas on how to fix this!

**Comment by MartaGolabek** [comment]
It seems that I am not the only one experiencing this issue: https://stackoverflow.com/questions/74195578/string-as-return-type-from-t-function-with-i18next/74860999#74860999

**Comment by MartaGolabek** [comment]
@adrai as requested I have created a failing test: https://github.com/i18next/i18next/commit/52b8b4b7050ad9e88b26b71b7d0622b30d182036

**Comment by adrai** [comment]
Thank you @MartaGolabek, I'm not a TypeScript expert, but maybe @pedrodurek or someone else can help? https://github.com/i18next/i18next/blob/54e8efe80515df92d4811a4706a331bf9e3e609a/test/typescript/custom-types/t.test.ts#L37

**Comment by MartaGolabek** [comment]
@pedrodurek any thoughts on the above issue?

**Comment by pedrodurek** [comment]
Hey @MartaGolabek, the problem is with the `Array<TFuncKey<'alternate'>>` type. This type returns an array with all key variations from `alternate` namespace. If you use `as const` to get the literal values, it'll likely solve your problem.

![Screenshot 2023-02-14 at 11 52 26 AM](https://user-images.githubusercontent.com/12190482/218830667-44c0a4ea-8034-4edd-9c2a-b9b1a82db67f.png)

However, due to a function overloading design limitation, if you pass any option to the `t` function (`t(value, {})`), the `t` function will infer the return type incorrectly. Function overloading is quite buggy, and we're overusing it. 

I've been redesigning all `t` function types to get rid of all function overloading and remove all complexity that we have in place. This redesign will certainly fix the issue that you're facing. You can take a look here: https://github.com/i18next/i18next/pull/1911

It may take a few days/weeks until we release it, so hold tight! I'll keep you posted!

**Comment by MartaGolabek** [comment]
Hey @pedrodurek, that's great news. Thank you! :)
