### ISSUE TITLE
languageOnly option has no effect on language.

### ISSUE THREAD

**Issue by amed** [i18next/i18next#1861]
## 🐛 Bug Report

By initializing i18n instance, and providing `{ load: 'languageOnly' }`, the language is written with country. 

## To Reproduce
[codesandbox](https://codesandbox.io/s/react-i18next-language-load-cp0s0o?file=/src/i18n.js)

## Expected behavior

`en` is shown on the screen of codesandbox example.

## Actual behavior

`en-us` is shown on the screen of codesandbox example.

## Your Environment

- *i18next version*: 22.0.3
- *os*: Mac

**Comment by adrai** [comment]
i18n.language is always the "detected" language, i18n.resolvedLanguge is what you're looking for: https://www.i18next.com/overview/api#resolvedlanguage
