### ISSUE TITLE
Unexpected behavior since 21.8.0 (not all namespaces are loaded after changeLanguage() was successful)

### ISSUE THREAD

**Issue by versat** [i18next/i18next#1863]
## 💥 Regression Report

I have observed issues with i18next version 21.8.0 and newer.
We are using i18next for a long time and I have tested version by version to find out that it is working for us until 21.7.1 without problems.
Starting with 21.8.0 it looks like the promise returned by changeLanguage() is resolved/settled too early. Normally all namespaces are loaded with the newly set language until the `then()` is called / promise is settled. Since 21.8.0 it seems to be called (promise settled) too early, so we get a lot of `missingKey` errors.
I have played around a bit and found out that if I set maxParallelReads to 100 everything is working as before and the translated texts are there.
Is this a known / intended behavior now that changeLanguage() maybe only loads 10 namespaces directly, then settles the promise and continues loading the rest asynchronously?

The backend (i18next-http-backend) version does not seem to have any influence, I have tested it with i18next-http-backend 1.4.4, 1.4.5 and 2.0.1. The result is the same.

## Last working version

Worked up to version: 21.7.1

Stopped working in version: 21.8.0

## To Reproduce

i18next init code:
```js
i18next
    .use(i18nextHttpBackend)
    .init({
      fallbackLng: ['en-US', 'dev'],
      ns: 'base',
      debug: true,
      defaultNS: 'base',
      joinArrays: '<br>',
      backend: {
        loadPath: 'WebES/modules/core/{{ns}}/i18n/{{ns}}_{{lng}}.json'
      }
    });
```
We have around 33 namespace files.
Calling `i18next.changeLanguage('en-US).then(() => {i18next.t('namespace30:somekey')})` results in missingKey error.
When calling i18next.t() later for other namespaces it works because in the meantime all namespaces are loaded.

## Expected behavior

When the i18next.changeLanguage() promise is settled, all translated texts are loaded (as it is written in the documentation).

## Your Environment

- *runtime version*: node v14.19.1
- *i18next version*: 21.10.0
- *i18next backend*: i18next-http-backend
- *os*: Windows
- *any other relevant information*: Framework: ExtJS

Edit: Improved reproducing description
Edit2: Added i18next backend information

**Comment by jamuhl** [comment]
did you test with current version? changes are high that got solved https://github.com/i18next/i18next/blob/master/CHANGELOG.md#2181

**Comment by versat** [comment]
> did you test with current version? changes are high that got solved https://github.com/i18next/i18next/blob/master/CHANGELOG.md#2181

Yes I have tested it with 21.8.1 and also with 22.0.4. The issue still exists for me.

**Comment by adrai** [comment]
@versat sorry, not able to reproduce it... can you please create a minimal reproducible example? A codesandbox example or a public github repo?

**Comment by versat** [comment]
Sadly I think it is not possible to create a MRE without really huge effort.
I found the workaround (by increasing the `maxParallelReads` configuration).
So if i18next looks fine, maybe we have done something wrong.
Thus I can understand if you close this issue.

**Comment by adrai** [comment]
hard to investigate without a reproducible example, sorry.
