### ISSUE TITLE
Allow unknown keys, when a `defaultValue` is provided

### ISSUE THREAD

**Issue by janpaepke** [i18next/i18next#1867]
## 💥 Regression Report

This isn't really a functional regression, more like a convenience regression, it only concerns the new [Typescript enhancements](https://www.i18next.com/overview/typescript).
When using the t function it is now impossible to use with keys that don't exist in the default namespace, even when a default value is provided, which it could fall back to.

This forces me to always add every key to my default namespace's resource file.
Usually in our workflow we only add translations inline using the defaultValue, when developing a new feature.
This is because things often change.
Only once something is production ready, we run i18next-parser to extract all keys and add translations.

## Proposal

I propose to add additional overloads for when a default value is provided (one for `t('key', 'defaultValue')`, one for `t('key', { defaultValue: 'value' })`, where the key can be any string.

## Last working version

Worked up to version: 21

Stopped working in version: 22

## To Reproduce

```ts
t('unkown.key', 'default translation')
// ⬆ No overload matches this call.
//  The last overload gave the following error.
//    Argument of type '"unkown.key"' is not assignable to parameter of type 'Normalize<{ ... }>  | TemplateStringsArray ...`
```

## Your Environment

- *runtime version*: i.e. node v16
- *i18next version*: i.e. 22.0.5
- *os*: Mac

**Comment by janpaepke** [comment]
I'll put it on my todo list. It's long. ;)

**Comment by janpaepke** [comment]
So I had some time and adding the overloads was actually pretty straight forward.

here they are:
```ts
  <
    TDefaultResult extends DefaultTFuncReturn = string,
    TInterpolationMap extends object = StringMap,
  >(
    key: string,
    options?: TOptions<TInterpolationMap> & { defaultValue: string },
  ): TFuncReturn<N, string, TDefaultResult, TKPrefix>;
  <
    TDefaultResult extends DefaultTFuncReturn = string,
    TInterpolationMap extends object = StringMap,
  >(
    key: string,
    defaultValue: string,
    options?: TOptions<TInterpolationMap> | string,
  ): TFuncReturn<N, string, TDefaultResult, TKPrefix>;
```
I tested them and they work as expected.  
They even still prefer the known keys so key autocomplete still works, when a default value is provided.

I could create a pr, but since this is a types-only changes, I failed to find the appropriate testing suite (was looking for [tsd](https://www.npmjs.com/package/tsd)).

Can you point me in the right direction?

**Comment by adrai** [comment]
https://github.com/i18next/i18next/tree/master/test/typescript
probably here: https://github.com/i18next/i18next/blob/master/test/typescript/t.test.ts
isn't it @pedrodurek ?

**Comment by janpaepke** [comment]
A quick check of those didn't help.

In `typescript/t.test.ts` I can add any key and `npm run test:typescript` doesn't fail.

The file `typescript/custom-types/t.test.ts` seems to be specifically made to test the "known keys" feature.
However running `npm run test:typescript:custom-types` also doesn't complain if I change one of the keys.
It even complains about the `@ts-expect-error` directives: `TypeScript@next compile error: 
Unused '@ts-expect-error' directive.`.

So I'm guessing this might be a configuration issue?

Pls advise.

**Comment by pedrodurek** [comment]
Hey @janpaepke, sorry for the delayed response. Actually, I'm trying to get rid of the some function overloads due to some limitations and to speed up the compilation time. I'll support what you want, just give me a few more days.

**Comment by janpaepke** [comment]
Ok sure! Let me know if I can help in any way!

Also: no need to apologise 😊.

**Comment by adrai** [comment]
@janpaepke try v22.4.0 in the meantime... it might be some performance changes will need to be done but in the meantime I added also some other t function overloads....

**Comment by janpaepke** [comment]
works as expected. I guess this concludes this issue? Should we close it?
