### ISSUE TITLE
Translation function return type DefaultTFuncReturn makes React Native errors

### ISSUE THREAD

**Issue by azuken** [i18next/i18next#1868]
## 💥 Regression Report

On React Native, we have some functions which ask for a `string | undefined` type, for example `Alert.alert()`, or @react-navigation component attributes.
Since DefaultTFuncReturn returns a `string | null` value, Typescript raise a type assignation error (TS2322).

```
TS2322: Type 'DefaultTFuncReturn' is not assignable to type 'string | undefined'.
```

Can be solved with `?? undefined` operator, but it is dirty and very redundant.

## Last working version

Worked up to version: 22.0.4

Stopped working in version: 22.0.5

## To Reproduce

```js
Alert.alert(
      t('home.accountRequiredTitle'),
      t('home.accountRequiredDescription'),
      [
        {
          text: t('home.signIn'),
          onPress: () => navigation.navigate('SignIn')
        },
        {
          text: t('home.signUp'),
          onPress: () => navigation.navigate('SignUp')
        }
      ],
      { cancelable: true }
    );
```

## Expected behavior

No Typescript error.

## Your Environment

- *runtime version*: node v18
- *i18next version*: 22.0.5
- *os*: Mac

**Comment by adrai** [comment]
This may help: https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz

**Comment by azuken** [comment]
Works lika charm! Thanks.

Didn't know such option existed, sorry for the inconvenience!
