### ISSUE TITLE
v22 Typing problem

### ISSUE THREAD

**Issue by Romanchuk** [i18next/i18next#1869]
Good day! I'm an author of [angular-i18next](https://github.com/Romanchuk/angular-i18next) package. I've struggled with issue while updating package support for v22.
The problem is that some types that i use are not accessible for import anymore

## 🚀 Feature Proposal

I found at least 2 types in my code that i can't import: **FormatFunction, Callback**

## Motivation

To make secure typed plugins we need to access all types of i18next.
Also it looks like sort of degradation, because in previous versions i could import that types.

## Example

```typescript
type FormatFunction = (
  value: any,
  format?: string,
  lng?: string,
  options?: InterpolationOptions & StringMap,
) => string;

type Callback = (error: any, t: TFunction) => void;

```

**Comment by linonetwo** [comment]
I also need `StringMap` to  write this workaround [https://github.com/i18next/next-i18next/issues/1781#issuecomment-1092620082](https://github.com/i18next/next-i18next/issues/1781#issuecomment-1092620082)

Otherwise there is a bug that says this, cause I can't write \`throw new Error(i18n._t_(\`Error.MainWindowMissing\`));\`

```
No overload matches this call.
  Overload 1 of 2, '(message?: string | undefined, options?: ErrorOptions | undefined): Error', gave the following error.
    Argument of type 'DefaultTFuncReturn' is not assignable to parameter of type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.
  Overload 2 of 2, '(message?: string | undefined): Error', gave the following error.
    Argument of type 'DefaultTFuncReturn' is not assignable to parameter of type 'string | undefined'.ts(2769)
```

**Comment by Romanchuk** [comment]
@adrai Hello, in what version it was released?

**Comment by adrai** [comment]
> @adrai Hello, in what version it was released?

v22.0.7

**Comment by Romanchuk** [comment]
@adrai Cheers!
