### ISSUE TITLE
Provide fallback for key that returnObjects

### ISSUE THREAD

**Issue by cemalokten** [i18next/i18next#1873]
Is it possible to provide a fallback for a key where `returnObjects: true`?

Standard key with fallback: `t('key', 'fallback here')`

Return objects with a fallback?: `const obj = t('obj', fallbackObjectHere? { returnObjects: true })`

**Comment by adrai** [comment]
`const obj = t('obj', { defaultValue: { some: 'fallback' }, returnObjects: true })`
