### ISSUE TITLE
i18n.init called in non-async method and with initImmediate set to false makes eslint throw error

### ISSUE THREAD

**Issue by bodycombathuang** [i18next/i18next#1875]
## To Reproduce
I have a type script code
i18n.init method is called in non-async method and initImmediate is set to false.
when I run eslint to check the code, it throws error
Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

but in https://www.i18next.com/overview/configuration-options
there is a description for initImmediate argument:
 Set it to false if your backend loads resources synchronously - that way, calling i18next.t() after init() is possible without relying on the initialization callback.

I put init method in synchrounous method, it should not make eslint throws error that i have to use await for the init method

sample.ts

import i18n from "i18next";
import Backend from 'i18next-fs-backend';
const func1=()=>
{
const resources = {
  en: {
    translation: {"a":"b"},

  },
  zh_CN: {
    translation: {"c":"d"},
  },
};

i18n.use(Backend).init({ lng:'en',resources,initImmediate:false});
};
func1();

## Expected behavior

 it should not make eslint throws error that
 Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises

or can you retain the original init method that returns promises and is for async method
and create another synchronous init method (with another name) that returns non-promise result.

in "fs" library, it has readFile (asynchronous method) and readFileSync(synchronous method_

// Paste the expected results here
```

## Your Environment

typescript version: 4.9.3
eslint version :8.29.0
- *i18next version*: i.e. 22.0.6
- *os*: windows 10
- *any other relevant information*

**Comment by adrai** [comment]
Please provide a full minimal reproducible example, like a github repository.

**Comment by bodycombathuang** [comment]
I do not have a github repository, my full code is put above, it is very simple

**Comment by bodycombathuang** [comment]
![捕获](https://user-images.githubusercontent.com/20555274/205525523-a776556b-1de0-479f-b7c6-90f4c5f4dd12.JPG)
I can reproduce when running eslint for the code, please see the screenshot

**Comment by bodycombathuang** [comment]
@adrai , "does it works for me" means eslint does not throw error for your code? did you  run eslint for my code? I have provided the reproducible example above

**Comment by adrai** [comment]
yes: https://github.com/adrai/i18next-fs-example-with-typescript/commit/63b1ddcfc3c1bfbad3fca118cb65470210bda2e1

btw: you did not provide a reproducible example. A reproducible example is something I can clone, npm install and run with exact steps to see the error....

Since I can't reproduce it and this sounds more to be an eslint topic I'm not able to help you more then that. Sorry.

**Comment by bodycombathuang** [comment]
@adrai   May I know your eslint version?

**Comment by adrai** [comment]
> @adrai   May I know your eslint version?

Haven't you seen my example?
It's all there: https://github.com/adrai/i18next-fs-example-with-typescript/blob/main/package.json

**v8.29.0**
