### ISSUE TITLE
Passing count to a nested key applies to the next keys that following it

### ISSUE THREAD

**Issue by marcalexiei** [i18next/i18next#1876]
## 🐛 Bug Report

Using a single count inside a nested key will apply the same count to all other following nested key without their own count.

Issue occurs also with v3 json syntax.

## To Reproduce

[Codesandbox](https://codesandbox.io/s/issue-with-count-inside-interpolation-p610z8?file=/src/i18n.js)

```js
import i18n from "i18next";
import LanguageDetector from "i18next-browser-languagedetector";

i18n
  .use(LanguageDetector)
  .init({
    debug: true,
    fallbackLng: "en",

    resources: {
      en: {
        translation: {
          item_one: "item",
          item_other: "items",

          thing_one: "thing",
          thing_other: "things",

          phrase: 'A: $t(thing, { "count": 2 }) B: $t(item)',
        }
      }
    },
  });

console.info(i18n.t("phrase"));

export default i18n;
```

## Expected behaviour

At the moment both A and B got plural variant:

```
A: things B: items
```

The expected behaviour  is that only A is returned with its plural variant. B uses single variant.

```
A: things B: item 
```

As a workaround you can explicit count on B:

```
phrase: 'A: $t(thing, { "count": 2 }) B: $t(item, { "count": 1 })',
```

## Your Environment

- *runtime version*: browser
- *i18next version*: 20.0.7
- *os*: Mac

**Comment by adrai** [comment]
v22.0.8 should fix that
