### ISSUE TITLE
Translating items in an array doesn't seem to work

### ISSUE THREAD

**Issue by NicoSan20** [i18next/i18next#1877]
Hello,

I saw in your documentation that it was possible to translate the elements in array, but it doesn't seem to work.

Currently I use the version 22.1.4 of i18next and I'm trying to translate 2 texts which are in an array, but only the first line is translated and returned.

Here is a small example to reproduce the problem :

```
const array = ['text1', 'text2']
const test = translate(array, { returnObjects: true });
```

The `test` variable will only contain the translation of text1.

Did I do something wrong ? Thank you in advance for your help. Regards, Nico

**Comment by jamuhl** [comment]
https://www.i18next.com/principles/fallback#calling-with-fallback-keys

it does not return all in array...it acts as fallback if first is not found!

**Comment by jamuhl** [comment]
but you can have an array in your JSON file https://www.i18next.com/translation-function/objects-and-arrays#objects

**Comment by adrai** [comment]
fyi: https://codesandbox.io/s/blissful-rgb-vl40l6?file=/src/index.js

**Comment by NicoSan20** [comment]
@jamuhl @adrai : Thank you for your fast reply. Sorry guys, but I don't understand everything. I just want to translate the 2 texts that are in my array (not in  json), (as in my example). How to do this ? Thank you for your help. Rgds

**Comment by adrai** [comment]
```js
const array = ['text1', 'text2']
array.forEach((key) => {
  const test = i18next.t(key);
})
```

**Comment by NicoSan20** [comment]
@adrai : OK, thank you, I thought this was possible to do it directly with translate function
