### ISSUE TITLE
[v12.4.0] Issues with typings

### ISSUE THREAD

**Issue by belgattitude** [i18next/i18next#1881]
## 🐛 Bug Report

There's a regression when using typed keys from 12.4.0->12.4.2.  Working when using 12.0.0 -> 12.3.0 (also relates to https://github.com/i18next/i18next/issues/1859)

## To Reproduce

Go to https://github.com/i18next/next-i18next/tree/master/examples/simple.

With 12.4.2

![image](https://user-images.githubusercontent.com/259798/206994984-57c6f81c-1d3c-49e4-9d94-ad4872935a19.png)

![image](https://user-images.githubusercontent.com/259798/206997658-0f3a0c10-4064-4455-b2fc-d2edbda078e0.png)

As seen in https://github.com/i18next/next-i18next/pull/2056

**Workaround**

- Lock i18next to 12.3.0

## Expected behavior

No bc.

## Interesting for investigation

If we send an array of namespaces to useTranslation, it's possible to make it work.... but we need to change our keys too.

![image](https://user-images.githubusercontent.com/259798/206996189-cc834d33-d018-4507-960c-1e18785b46e5.png)

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
Saw it, but I don't know why

**Comment by belgattitude** [comment]
Fixing this will potentially fix this https://github.com/i18next/i18next/issues/1859 as well.

**Comment by adrai** [comment]
try v22.4.3

**Comment by belgattitude** [comment]
Seems to work. I've tested it on https://github.com/i18next/next-i18next/pull/2058.
