### ISSUE TITLE
[Types] Return type of "t" is string | MyTranslationsObject

### ISSUE THREAD

**Issue by bhollis** [i18next/i18next#1882]
## 🐛 Bug Report

When I import `t` and use it, with a custom translations type, the return type of t is `string | MyTranslationsObject` instead of `string`

## To Reproduce

In `src/@types/i18next.d.ts`:

```ts
// import the original type declarations
import 'i18next';

const translations = { Foo: { Bar: 'Hey' } };

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'translation';
    resources: { translation: typeof translations };
  }
}
```

In some other `.ts` file:

```ts
import { t } from 'i18next';

const foo = t('Foo.Bar');
```

<img width="495" alt="Screenshot 2022-12-12 at 9 11 52 PM" src="https://user-images.githubusercontent.com/313208/207232226-baba47f0-ea4c-4d60-abdf-78d020786ddc.png">

## Expected behavior

I expected the type of `foo` to be `string`.

## Your Environment

- *runtime version*: node 18.11
- *i18next version*: 22.4.3
- *os*: Mac

**Comment by adrai** [comment]
How do your resources look like?

**Comment by adrai** [comment]
You need to write typeof, in the resources: https://www.i18next.com/overview/typescript

**Comment by adrai** [comment]
seems to work: https://github.com/i18next/i18next/blob/c0bc1a6b4c74f8c32fd9bdb84e40a38835791c76/test/typescript/custom-types/t.test.ts#L52

**Comment by bhollis** [comment]
I've changed the original example to use `typeof`, but it still doesn't work.

<img width="393" alt="Screenshot 2022-12-12 at 10 43 26 PM" src="https://user-images.githubusercontent.com/313208/207245416-536ace6c-6302-4565-95fb-f522ef6f0e28.png">

 Let me check out the i8next repo and try to get a test failing.

**Comment by bhollis** [comment]
Here you go, this reproduces my issue: https://github.com/bhollis/i18next/commit/4b3aca0756143f5d03f55aebf0c80ce78292ae31

**Comment by adrai** [comment]
v22.4.4 should fix it
