### ISSUE TITLE
[22.4.5] TS autosuggests both prefixed and un-prefixed key, with the prefixed giving a TS error.

### ISSUE THREAD

**Issue by momentiris** [i18next/i18next#1887]
## 🐛 Bug Report

`t` function autocompletes with duplicate entries, both with and without namespace prefix. If I use the prefixed version, I get a TS error.

```ts
const { t } = useTranslation();

const foo = t('ABORT') 
const foo = t('translation:ABORT')
```
First problem is that both of these shows up as suggestions. Second problem is that using the second version gives a TS error:
```
[tsserver 2769] [E] No overload matches this call.                                                                                                                                                    
 Overload 1 of 12, '(key: Normalize<{ ABORT: string;.... 
```

## To Reproduce

Set up TS as per [preferred approach](https://www.i18next.com/overview/typescript), with objects declared as const.

i18n.ts
```ts
import { initReactI18next } from 'react-i18next';
import i18n from 'i18next';

import sv from './../assets/locales/sv/translation.json';

export const defaultNS = 'translation';
export const resources = { sv: { translation: sv } } as const;

export const i18nConfig = i18n.use(initReactI18next).init({
  lng: 'sv',
  defaultNS,
  resources,
});
```
Codesandbox:
[22.4.5](https://codesandbox.io/s/quizzical-currying-q8ldis?file=/src/App.tsx)

<img width="789" alt="Screenshot 2022-12-14 at 15 20 27" src="https://user-images.githubusercontent.com/31646645/207620697-c89e0d7a-f31d-4449-8c7e-ae669b9cb35a.png">

<img width="1685" alt="Screenshot 2022-12-14 at 15 23 33" src="https://user-images.githubusercontent.com/31646645/207620968-2bd7507d-3ce2-477e-87e2-2f0228d1f75e.png">

## Expected behavior
Suggestions should not show both unprefixed and prefixed.
No suggestion should give an error.
```ts
  const { t } = useTranslation();
  t('') // only "FOO" should show up as suggestion.
```

## Your Environment

- *runtime version*:  browser lastest chrome, node 16.15.1
- *i18next version*:  22.4.2 to 22.4.5
- *os*: Mac OS Monterey  12.2.1

**Comment by adrai** [comment]
duplicate of https://github.com/i18next/i18next/issues/1886
