### ISSUE TITLE
Incompatible code between i18next v22.1.0 and i18next-fs-backend v2.1.0, causing saveMissing to report error with the callback function.

### ISSUE THREAD

**Issue by kevintap** [i18next/i18next#1890]
## 🐛 Bug Report

Incompatible code between i18next v22.1.0 and i18next-fs-backend v2.1.0, causing saveMissing to report error with the callback function.

The following commit introduced a problem with the saveMissing function when using i18next-fs-backend: https://github.com/i18next/i18next/commit/40db211bf308090e395556f416c6798d8fbae413

The i18next-fs-backend has a create function defined with arguments:
```js
  (languages, namespace, key, fallbackValue, callback)
```

The new code introduced in v22.1.0 in the commit referenced above has different expectations for the backend's create function and end up passing the options object in place of the callback to the backend. This causes an error since the expected callback object is not a function.

The above referenced commit expects that the backend's create function contain 6 arguments in order to pass a callback to the backend. If the backend's create function contains fewer than 6 arguments, then it will not pass a callback to the backend and instead pass the opts object for the 5th argument.

```js
          var fc = this.backend.create.bind(this.backend);
          if (fc.length < 6) {
            try {
              var r;
              if (fc.length === 5) {
                r = fc(languages, namespace, key, fallbackValue, opts); // <-- for i18next-fs-backend this ends up being called
              } else {
                r = fc(languages, namespace, key, fallbackValue);
              }
              if (r && typeof r.then === 'function') {
                r.then(function (data) {
                  return clb(null, data);
                })["catch"](clb);
              } else {
                clb(null, r);
              }
            } catch (err) {
              clb(err);
            }
          } else {
            fc(languages, namespace, key, fallbackValue, clb, opts);
          }
```

## To Reproduce

enable saveMissing with the default i18next-fs-backend configured

```js
error - unhandledRejection: TypeError: callback is not a function
```
## Expected behavior

No errors reported when saveMissing is enabled.

## Your Environment

- N/A

**Comment by adrai** [comment]
i18next-fs-backend v2.1.1 should fix it

**Comment by kevintap** [comment]
I think this can be closed now. i18next-fs-backend v2.1.1 resolved this. Thanks for the quick turn around.
