### ISSUE TITLE
After 22.4.4 importing TFunction freezes eslint

### ISSUE THREAD

**Issue by janpe** [i18next/i18next#1891]
## 🐛 Bug Report

After updating to `22.4.4` or higher importing `TFunction` in a file causes eslint to hang and never be completed. `22.4.3` and before work fine. 

## To Reproduce

Import `TFunction` in a file and run eslint on it.

## Expected behavior

Eslint not to freeze.

## Your Environment

- *runtime version*: node 18.12.1
- *i18next version*: 22.4.4
- *os*: Mac

**Comment by adrai** [comment]
Please provide a minimal reproducible example or even better create a failing test case here: https://github.com/i18next/i18next/tree/master/test/typescript

`npm run test:typescript:customtypes && npm run test:typescript:customtypes`

**Comment by janpe** [comment]
Sorry couldn't reproduce this in a minimal way. I'll close this. Not sure what is causing this in my environment but it works up until `22.4.3`

**Comment by CreativeTechGuy** [comment]
@janpe Thank you for opening this. I ran into this same issue when updating recently and the fact you mentioned `TFunction` lead me to piece together a minimal repro. (#1901) Appreciate you kicking this off!

**Comment by esetnik** [comment]
@janpe why was this closed?

**Comment by janpe** [comment]
> @janpe why was this closed?

As I mentioned, I closed this because I wasn't able to make a minimal repro. Follow #1901 mentioned in the comment above yours.
