### ISSUE TITLE
documentation help

### ISSUE THREAD

**Issue by fakol** [i18next/i18next#1892]
Hello, I can't figure out how to translate to <select><option>
Your documentation is superficial and I still do not understand how to implement it, even there is no example. examples are only present with <a> <ul> and <nav>
I will be grateful if you write me a complete example with select

**Comment by jamuhl** [comment]
https://www.i18next.com/overview/getting-started#basic-sample
https://www.i18next.com/overview/getting-started#extended-sample

https://jsfiddle.net/jamuhl/dvk0e8a9/#tabs=js,result,html
https://jsfiddle.net/jamuhl/ferfywyf/525/

https://www.youtube.com/watch?v=SA_9i4TtxLQ&t=4s
https://www.youtube.com/watch?v=w04LXKlusCQ

**Comment by fakol** [comment]
![image](https://user-images.githubusercontent.com/41354153/209940309-d36ec854-2fc5-4d78-b86f-16ac03248340.png)

https://locize.com/blog/jquery-i18next/

It doesn't work why I don't know

**Comment by fakol** [comment]
![image](https://user-images.githubusercontent.com/41354153/209940538-edcd8c52-8a39-4998-adf3-fa78addbc3c7.png)

I only wrote the initial code for Toko to check if the translation of the page works at all, but as it turned out, it doesn’t

**Comment by jamuhl** [comment]
guess https://github.com/i18next/jquery-i18next/tree/master/example/landing works...so must be something in your code...

try providing a codesandbox with your code...not easy to help just looking at a screenshot of code...

**Comment by fakol** [comment]
oh sorry i no use attibyte data

**Comment by fakol** [comment]
thanks for the help can close
