### ISSUE TITLE
Format numeric values during interpolation

### ISSUE THREAD

**Issue by ZMiller01** [i18next/i18next#1893]
## 🚀 Feature Proposal

When interpolating numeric values into template strings, the numbers should be formatted according to the detected locale, i.e., using `toLocaleString`.

If this is not reasonable enough to be the default behavior, it could at least be a configurable interpolation option.

## Motivation

When translating strings that may contain large numeric values, I would like to take advantage of the pluralization features built in to i18next, but I would also like my numbers to contain the correct thousands and decimal separators for the locale.

I could implement a workaround by passing a pre-formatted value in addition to the numeric value, but this seems like something the translation suite ought to do for me.

## Example

translation.json:
```
{
  "userCount_one": "{{count}} user",
  "userCount_other": "{{count}} users"
}
```

`t("userCount", {count: 10000})`

Actual: "10000 users"
Desired: "10,000 users"

Workaround:
```
{
  "userCount_one": "{{formatted}} user",
  "userCount_other": "{{formatted}} users"
}
```

```
const { t, i18n } = useTranslation();

const users = 10000;

t("userCount", {count: users, formatted: users.toLocaleString(i18n.language)});
```

**Comment by jamuhl** [comment]
rather sure you can use https://www.i18next.com/translation-function/formatting on the count variable interpolated

**Comment by ZMiller01** [comment]
@jamuhl Wasn't aware of that!

This should probably be mentioned on the documentation page for pluralization.
