### ISSUE TITLE
22.4.5 broke the types

### ISSUE THREAD

**Issue by falsandtru** [i18next/i18next#1894]
## 🐛 Bug Report

Updating from 22.4.4 to 22.4.5 broke the following code.

## To Reproduce

```ts
      interface TransDataMap {
        'Greeting': { name: string; };
      }
      function trans<K extends keyof TransDataMap>(el: HTMLElement, key: K, data: TransDataMap[K]) {
        i18next.init((err, t) =>
          el.textContent = err
            ? ''
            : t(key, data) ?? ``);
      }
```

## Expected behavior

pass

## Your Environment

- *runtime version*: v19
- *i18next version*: 22.4.5
- *os*: Windows

**Comment by falsandtru** [comment]
@adrai @pedrodurek

**Comment by falsandtru** [comment]
@adrai @pedrodurek STOP THE BOT!!

**Comment by falsandtru** [comment]
FUCK YOU

**Comment by adrai** [comment]
Please try with i18next v23.0.1 and react-i18next v13.0.0

**Comment by falsandtru** [comment]
Got errors.

```
Argument of type '[K, TransDataMap[K]]' is not assignable to parameter of type '[key: K | K[], options?: (TransDataMap[K] & InterpolationMap<DefaultTReturn<TransDataMap[K]>>) | undefined] | [key: K | K[], defaultValue: string, options?: (TransDataMap[K] & InterpolationMap<DefaultTReturn<TransDataMap[K]>>) | undefined]'.
  Type '[K, TransDataMap[K]]' is not assignable to type '[key: K | K[], defaultValue: string, options?: (TransDataMap[K] & InterpolationMap<DefaultTReturn<TransDataMap[K]>>) | undefined]'.
    Type at position 1 in source is not compatible with type at position 1 in target.
      Type 'TransDataMap[K]' is not assignable to type 'string'.
        Type '{ name: string; }' is not assignable to type 'string'.ts(2345)
(parameter) key: K extends "Greeting"
```

**Comment by adrai** [comment]
@falsandtru please provide a reproducible example

**Comment by falsandtru** [comment]
@adrai Same as the repro code at first in this issue.

**Comment by adrai** [comment]
That's just a code snippet, and nod a complete but minimal reproducible example repository or similar...
I can't see the the reason why you are wrapping the init function like that... What is your use case?
Create a new github repository showing what you want to achieve...

**Comment by falsandtru** [comment]
Then the next is how to repro:

1. Clone https://github.com/falsandtru/typed-dom
2. Run `npm i`
3. Run `npm run update`
4. Run `npm run dev`

**Comment by falsandtru** [comment]
It is a workaround. At least `TOpt['returnDetails'] extends true` would be a bug. This condition matches even when returnDetails is not set.

**Comment by adrai** [comment]
try this:
<img width="447" alt="image" src="https://github.com/i18next/i18next/assets/1086194/c3f89159-76ee-4114-b402-64e0f7971385">

**Comment by falsandtru** [comment]
Not bad suppression. But need a bug fix anyway.

**Comment by adrai** [comment]
I'm not a TS expert... @pedrodurek do you have a different idea?

**Comment by falsandtru** [comment]
Probably two problems exist.

1. `{ name: string; }` is not assignable to type `InterpolationMap<DefaultTReturn<TransDataMap[K]>>`.
2. `TOpt['returnDetails'] extends true` always matches even when returnDetails is not set.

**Comment by adrai** [comment]
regarding returnDetails... here the tests seems to work: https://github.com/i18next/i18next/blob/master/test/typescript/t.test.ts

**Comment by falsandtru** [comment]
At the first problem, type checking is failed due to the deep type inference is cut off in the middle. The second problem seems to be the same.

**Comment by adrai** [comment]
Can you provide a failing test here: https://github.com/i18next/i18next/blob/master/test/typescript/t.test.ts ?

**Comment by falsandtru** [comment]
Created #1971.

**Comment by falsandtru** [comment]
At the second problem, impossible to decide the type of T[K]['prop']. So ['prop'] checks have to be replaced with overloading such as the previous type definitions.

**Comment by falsandtru** [comment]
From the above, this bug can be fixed as the previous type definitions were working.

**Comment by adrai** [comment]
@falsandtru would you like to try a PR?

**Comment by pedrodurek** [comment]
Hey @falsandtru, the types are not broken. This is a typescript limitation where it loses the signature of `Options['returnDetails']` because `data` depends on `key`, so it infers the return type as `string | something else`. You can take a look here https://tsplay.dev/wXrD9m

Feel free to report the bug in typescript github issues or to find an workaround for it. I'll let you know if I figure something out.

**Comment by falsandtru** [comment]
This is a regression issue. This issue means that some types are broken by i18next. Additionally, as I wrote at https://github.com/i18next/i18next/pull/1971#issuecomment-1595951188, some type definitions are completely wrong, as the next.

```ts
type DefaultTReturn<TOpt extends TOptions> =
  | string
  | TReturnOptionalObjects<TOpt>
  | TReturnOptionalNull;
...
    Ret extends DefaultTReturn<TOpt>,
```

And your default type extension also pollutes and breaks other instances.

**Comment by pedrodurek** [comment]
@falsandtru, It's not a regression issue. The types here simply don't support your custom configuration due to a Typescript limitation. For the time being, you can either change your approach, or remove the `resources` definition from your `CustomTypeOptions`.

As for the `t` function return type, what are you expecting it to be?

**Comment by falsandtru** [comment]
If it is the official decision, I have no choice but to accept it.

> As for the t function return type, what are you expecting it to be?

string.

**Comment by pedrodurek** [comment]
If you have `returnObjects` set to `false`, it will be string
