### ISSUE TITLE
Compiled code became ~30% larger in v22.0.0+

### ISSUE THREAD

**Issue by tommoor** [i18next/i18next#1895]
## 🐛 Bug Report

The codebase became ~30% larger without any functional changes, it would be nice to track down what caused the increase and knock this bundle back down to the smaller size.

<img width="67" alt="image" src="https://user-images.githubusercontent.com/380914/210263122-94dd1517-b71d-4c3c-b1cd-8a4b68dd05c9.png">

## To Reproduce

See bundlephobia:
- https://bundlephobia.com/package/i18next@21.0.0
- https://bundlephobia.com/package/i18next@22.0.0

**Comment by adrai** [comment]
Why are you saying "without any functional changes"?

between v21.0.0 and v22.0.0 there were a lot of changes...

for example v21.3.0 added support for formats provided by Intl API: https://github.com/i18next/i18next/blob/master/CHANGELOG.md#2130

and v21.5.0 added named export support and updated some babel dependencies: https://github.com/i18next/i18next/pull/1681

etc....

**Comment by adrai** [comment]
I don't think there's much we can do... 
If you have any idea to decrease the size, let us know...

**Comment by tommoor** [comment]
Yes sorry – It's hard on bundlephobia to see a graph over time of the sizes so I'm just comparing one by one. It seems that the biggest change was in this PR:
https://github.com/i18next/i18next/releases/tag/v21.5.0

**Comment by adrai** [comment]
like said... no idea how to reduce size without removing functionality...
feel free to contribute if you have an idea...

**Comment by tommoor** [comment]
I will close the issue as I was initially under the impression that the increase was sudden from a change in the build process. 

Just as a side note it's kind of worrying that this dependency is so large and continues to get bigger with every update, as it does not lend itself to code splitting and needs to be in the initial bundle due to it's inclusion in every component

Many thanks.
