### ISSUE TITLE
Options passed in `replace` object can't be used as `count` for nested translation 

### ISSUE THREAD

**Issue by AlexKrupko** [i18next/i18next#1896]
## 🐛 Bug Report

Options passed in `replace` object can't be used as `count` value for nested translation. It select proper translation correctly, but doesn't pass `count` value. 
Please check a console output in codesandbox example. 

## To Reproduce

A [codesandbox](https://codesandbox.io/s/admiring-saha-8vew02?file=/src/index.js) example.

## Your Environment
- *i18next version*: i.e. 21.x, 22.x

**Comment by adrai** [comment]
1. You need to correctly specify interpolated variable in dot notation
2. it seems the replace variable name conflicts, so just use a different variable name: https://codesandbox.io/s/intelligent-mirzakhani-lyd6cc

**Comment by adrai** [comment]
fyi: v22.4.7 should now also fix the replace variable name

**Comment by AlexKrupko** [comment]
@adrai ,
it seems `replace` values are not extracted anymore and we have to use always `replace.` prefix in interpolations  - [Codesandbox](https://codesandbox.io/s/admiring-saha-8vew02?file=/src/index.js)

**Comment by adrai** [comment]
Yes, that's correct... the replace option was only for the old v1 version... where did you find the information about this old replace option functionality?

**Comment by AlexKrupko** [comment]
I guess, I saw it somewhere in docs. I use i18next starting with 18 version, probably it was there before. 
Also TS declaration contains this and my IDEA always proposes this option 
```ts
export interface TOptionsBase {
  ....
  /**
   * Object with vars for interpolation - or put them directly in options
   */
  replace?: any;
  ....
}
```

**Comment by adrai** [comment]
I see....

v22.4.8 should fix it
