### ISSUE TITLE
Typesafe Interpolation Variables

### ISSUE THREAD

**Issue by CreativeTechGuy** [i18next/i18next#1897]
## 🚀 Feature Proposal

Enable opt-in typesafe interpolation variables. Given that the user is already using #1504, this will add additional intellisense based on the contents of the string, finding any variable placeholders and requiring values to be passed for each.

## Motivation

It's easy to miss passing required interpolation variables when translating a string. This will ensure that developers get both real-time Type errors and auto complete for variable names to avoid mistakes at runtime.

## Example

[Example TypeScript sandbox](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgdsCAnMB7ANgQ2AS1XANUyR0wCN0IBnAHgGVgkoIAPROAEyqisZzgDmAGihES5St1bsuPPoKgBeKHAgA3ZAD4lUBk2kRO3AAYASAN68SggL7nzF-gDNko4qQoQb3x3BdM6AFcnJxwWG2MoAH4AKCh42ARkNCxcfDEPSXpg0JYRDIkIbQMjFXVXWISqqHMoAG0AaQgQKH43cU8oAB92zOoAXQAuKEw4FpsoYfhEFAxsPEJ3QtogkLD8pc9tQbjqvb1mNkNZM0t5ATsHc2dXAs9vCOjdvZea+qaWtrvKbt7loZGYygE2Gqg0SAA3DEYhwIABjLBIaBw-C8KBqTDoKZJWapBbfag0ABEABUABbQJwYdCoADu-AEUDhZOImDhM24xGgcFQwBG6BptIgHGG9mZrPZyCo3iJmihryqAHpFVAAHqxGHwxHI1F8jHoABM2JmKXm6U2WSJAE1UIEmaMoCyNDVrogALYARm8UFQTHsOHdBplcueCuVao1sIRXKZuvRmIAzMbknM0osOpbydRoMBaagRkioMAKTxMG7oP73d7RhwXQGIG7vAA6XQQCBRWXyhXxcPq0OvaGgSBQAByqAJVD09EYhxk3CsDO0ymmKbx5ozhL0xSOpTBFV0M9B5Uh0Kj2tjcDRiF4wzHE6nRIAClg2gvBJ3+y9e5GtTGUZe+WvYAjVHccLWoB8xz5TAoDAF84BdN8LhsD9ux7FU+2hcMAFEWDLODoECKhMAECAdhif80UMHRzFDIk4MwfgiWGJ94LkawBCJIQ6LdQJ0FwAjmKga1bXtBCnQrV0Gy9CZfTrQMZW4qoiSoBlKCE0kSypAU6QZJkWSQNkOQLbleX5QVhVFcxxUMyUkGlFCYgmTBuEo4AoU1aNCycQI4HZBYixoD5Z2ObgAGtmlQJwi3ACAouYOARAOEpZCHOLosMRpmn6TQAAowBIsiD30HdZDvcDJ0YGg0vizKPhy6IoGCo9wQASmGJCoTPGMfL8tNAuClLwsi6KaoyxK-k8KRSu4FdcTNdM+loMaEqykAcrygrSOGD4RAxDcqGGCd2vYhkPOAXL6PgolWqhC6iV4-icEE26Ynux6BPUkRanrT0WPIOEuNaQNhgAVhsV77tUwR1Mhy7oYEL63hsoypX+shAYh6EYiAA). I wrote this code to make typesafe URL path variables and realized it could be used with very minor tweaks here too. It'd be amazing if this could be integrated into the core library.

## Notes

* I know the variable placeholders can be extremely complex. This feature would only be usable for those with simple placeholders (`{{name}}`) and nothing more. As a result, it needs to be opt-in as it won't work for everyone. I believe this is still valuable as simple placeholders covers a majority of users.

**Comment by CreativeTechGuy** [comment]
Not stale

**Comment by CreativeTechGuy** [comment]
Still not stale

**Comment by CreativeTechGuy** [comment]
Not stale

**Comment by CreativeTechGuy** [comment]
Still not stale

**Comment by CreativeTechGuy** [comment]
Not stale

**Comment by CreativeTechGuy** [comment]
Not stale

**Comment by Lesik** [comment]
Resolved by !1911?

**Comment by adrai** [comment]
@pedrodurek is this already addressed with https://github.com/i18next/i18next/pull/1911/files#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8R839 ? I can't find any test for this, so I assume that is not yet addressed, right?

**Comment by adrai** [comment]
@CreativeTechGuy @Lesik you might want to help here: https://github.com/i18next/i18next/pull/1911#issuecomment-1587271614

**Comment by adrai** [comment]
Please try with i18next v23.0.1 and react-i18next v13.0.0

**Comment by adrai** [comment]
>should work....
proof here: https://github.com/locize/i18next-typescript-examples/blob/main/2/index.ts

https://github.com/i18next/i18next/issues/1953#issuecomment-1601317429
