### ISSUE TITLE
Allow appending keys to namespaces in getFixedT() function

### ISSUE THREAD

**Issue by Darhagonable** [i18next/i18next#1899]
## 🚀 Feature Proposal

Add support for using key in namespace when adding namespace as param in the getFixedT() function:
`getFixedT(null, 'namespace:key-in-namespace')`
this would also allow one to have different keys depending on the namespace like this:
`getFixedT(null, ['namespace:key-in-namespace', 'another-namespace:another-key'])`

## Motivation

I'm working on a platform with multiple different sections. I have made each section have their own namespace and each file then containing groups.
In my components i wanna use both translations from a group in my `admin-pages` namespace and `common` which is set as `fallbackNS`.
If I would use the `keyPrefix` option it won't work with the translations from `common`.

## Example

Let's say one has the two following namespaces:
common.json
```json
{
  "name": "Name",
  "version": "Version",
  "app-title": "My very good web app"
}
```

admin-pages.json
```json
{
  "users-admin-pages": {
    "first-name": "First name",
    "sir-name": "Sir name"
  },
  "devices-admin-pages": {
    "status": "Status"
  }
}
```

`common` is set as `fallbackNS`

Then one could write the code like this:
```ts
const t= i18next.getFixedT(null, 'admin-pages:users-admin-pages')
t('app-title') // My very good web app
t('first-name') // First name
t('sir-name') // Sir name
```

**Comment by adrai** [comment]
There already is a third keyPrefix argument: https://www.i18next.com/overview/api#getfixedt

**Comment by adrai** [comment]
You can call it also multiple times

**Comment by Darhagonable** [comment]
If I would use the keyPrefix option it won't work with the translations from common.
One would want have the keyprefixes for each individual namespace in this case.

**Comment by adrai** [comment]
We won't introduce more complexity in this, sorry.

**Comment by Darhagonable** [comment]
alright! thanks
