### ISSUE TITLE
locale "{lang}-{country}" doenst work while "{lang}_{country}" works

### ISSUE THREAD

**Issue by fyyyyy** [i18next/i18next#1902]
## To Reproduce

See live example
https://jsfiddle.net/47r0vsqn/27/

```js
// Paste your code here
```

## Expected behavior

de-de should work the same as de_de, probably json access bug

## Your Environment

node v18.12.1
i18next 22.4.9

**Comment by jamuhl** [comment]
locales have to be in form `{lng}-{COUNTRY}`
