### ISSUE TITLE
Types fail on incorrect count type (and probably other types)

### ISSUE THREAD

**Issue by luixo** [i18next/i18next#1904]
## 🐛 Bug Report

If user passes a `string` (or other unexpected type, like `boolean` to count property of `TFunction` options it returns `TFunctionDetailedResult<string>` type though in runtime it actually return string.

## To Reproduce

Demo: https://codesandbox.io/s/i18next-count-type-fail-demo-p0rb3i

## Expected behavior

Error on incorrect type should be shown / string should be returned.

## Your Environment

- *runtime version*: node v16
- *i18next version*: 22.4.9

**Comment by adrai** [comment]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/1086194/215330351-34051857-e11d-4eac-9b2a-a7c960fcdefa.png">
I see an error here

**Comment by pedrodurek** [comment]
Although it works in runtime, `count` should be a number
