### ISSUE TITLE
Unable to translate key that contain plus sign

### ISSUE THREAD

**Issue by MartaGolabek** [i18next/i18next#1905]
Hello,

I am using i18next (version 22.4.5) and I am experiencing a problem with a key that contains a plus sign (+) - it is not translated. As soon as I remove the plus sign, the key gets translated. I haven't found any information about such a restriction in the docs. I would like to keep the plus sign in my key, because it should match a custom type. Is there any way around this?
Specifying `keySeparator` and `nsSeparator` doesn't help as it did in case of colon (see issue https://github.com/i18next/i18next/issues/361)

```
{
    "CUSTOM+TYPE": "It is not translated",
    "CUSTOMTYPE": "It is translated without any problem"
}
```

**Comment by adrai** [comment]
Seems to work for me: https://codesandbox.io/s/eloquent-volhard-0kiu5g?file=/src/App.js:1058-1076

**Comment by MartaGolabek** [comment]
Thanks @adrai! Then it seems to be a problem with me setting!
