### ISSUE TITLE
Incorrect plural outputs for cs-CZ when using JSON v3

### ISSUE THREAD

**Issue by BryceGraves** [i18next/i18next#1906]
## 🐛 Bug Report

Plural translation outputs for `cs-CZ` do not match expected values for `JSON v3` but do for `JSON v4`

### Assumptions
This bug was created with the assumption that the v3 keys map to v4 keys like so:

0. zero
1. one
2. two
3. few
4. many
5. other

### Sandbox example (output is in console)
[![Edit magical-bouman-4ebids](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/magical-bouman-4ebids?fontsize=14&hidenavigation=1&theme=dark)

### JS Code
```js
import i18n from "i18next";

const jsonVersion = "v4";

const files = {
  v3: require("../translations/v3.json"),
  v4: require("../translations/v4.json")
};

i18n
  .init({
    lng: "cs-CZ",
    interpolation: {
      escapeValue: false
    },
    nonExplicitWhitelist: true,
    resources: {
      "cs-CZ": { translation: files[jsonVersion] }
    },
    compatibilityJSON: jsonVersion
  })
  .then((t) => {
    const output = {
      0: t("test", { count: 0 }),
      1: t("test", { count: 1 }),
      2: t("test", { count: 2 }),
      3: t("test", { count: 3 }),
      4: t("test", { count: 4 }),
      5: t("test", { count: 5 })
    };

    console.log(output);
  });
```

#### V3
```json
{
  "test_plural": "{{count}} plural",
  "test_0": "{{count}} v3: 0, v4: zero ",
  "test_1": "{{count}} v3: 1, v4: one",
  "test_2": "{{count}} v3: 2, v4: two",
  "test_3": "{{count}} v3: 3, v4: few",
  "test_4": "{{count}} v3: 4, v4: many",
  "test_5": "{{count}} v3: 5, v4: other",
  "test": "{{count}} singular"
}
```

#### V4
```json
{
  "test_plural": "{{count}} plural",
  "test_zero": "{{count}} v3: 0, v4: zero ",
  "test_one": "{{count}} v3: 1, v4: one",
  "test_two": "{{count}} v3: 2, v4: two",
  "test_few": "{{count}} v3: 3, v4: few",
  "test_many": "{{count}} v3: 4, v4: many",
  "test_other": "{{count}} v3: 5, v4: other",
  "test": "{{count}} singular"
}
```

#### JSON v3
Expected output (count => key):

0. test_0
1. test_1
2. test_3
3. test_3
4. test_3
5. test_5

Actual output (count => key):

0. test_2
1. test_0
2. test_1
3. test_1
4. test_1
5. test_2

#### JSON v4
Expected output matches actual (count => key):

0. zero
1. one
2. few
3. few
4. few
5. other

## Your Environment

- node v16
- *i18next version*: 22.4.9
- *os*: Linux
- Reproducable on older versions of i18next

**Comment by adrai** [comment]
cs has 3 plural forms for your number range.

https://jsfiddle.net/6bpxsgd4


v4: _one, _few, _other
v3: _0, _1, _2

count=1:
v3: _0
v4: _one

count=2 or 3 or 4:
v3: _1
v4: _few

count= 0, >=5:
v3: _2
v4: _other

special case for v4 with count=0 if the key _zero exists

**Comment by BryceGraves** [comment]
@adrai when comparing the `JSON Format` documentation:
```json
{
  "keyPluralMultipleEgArabic_0": "the plural form 0",
  "keyPluralMultipleEgArabic_1": "the plural form 1",
  "keyPluralMultipleEgArabic_2": "the plural form 2",
  "keyPluralMultipleEgArabic_3": "the plural form 3",
  "keyPluralMultipleEgArabic_4": "the plural form 4",
  "keyPluralMultipleEgArabic_5": "the plural form 5",
}
```
for v3 and:

```json
{
  "keyPluralMultipleEgArabic_zero": "the plural form 0",
  "keyPluralMultipleEgArabic_one": "the plural form 1",
  "keyPluralMultipleEgArabic_two": "the plural form 2",
  "keyPluralMultipleEgArabic_few": "the plural form 3",
  "keyPluralMultipleEgArabic_many": "the plural form 4",
  "keyPluralMultipleEgArabic_other": "the plural form 5",
}
```
for v4.

I expected `few` to map to `_3` in the older form. Is that not the case?

**Comment by adrai** [comment]
That's just an example for arabic.
Check my previous link to verify other languages.

**Comment by BryceGraves** [comment]
Thanks for the link for that js fiddle. I was searching for ages yesterday trying to find one that included v4.

Looking at another similar example Lithuanian (lt) behaves in the same way.

I was under the impression that the mapping would be one to one for the old numbered keys to the new text keys:
v3:      _0,     _1,     _2,     _3,        _4,       _5
v4: _zero, _one, _two, _few, _many, _other

Is that not the case?

**Comment by adrai** [comment]
It really depends on the language...
Here some insights: https://github.com/i18next/i18next-v4-format-converter/blob/main/src/index.js

used for: https://i18next.github.io/i18next-v4-format-converter-web/

**Comment by BryceGraves** [comment]
I really appreciate you taking the time to answer this. Just to clarify and confirm:

For V3 the numbered versions denote the next plural form and not a specific type of plural form.
For V4 the plural form in the key is the one you will receive.

So all languages in V4 can have the plural form postpend since it will only use ones that exist for the langue. While with V3 they cannot since not every language has the same amount of plural forms.

Does that sound about right?

**Comment by jamuhl** [comment]
@BryceGraves I'm not sure if you approach the problem correctly. Your assumtion is right you can have unused forms of plurals in v4 and it won't hurt. But liguistically no one will be able to translate to those...so yes...technically you can have those _many, _few, also for eg. english...but no one will be able to fill those translations - plus they won't ever be resolved as no count value will access that form.

**Comment by adrai** [comment]
V3 used the suffix number as number in the plural rule used by gettext: http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms

v4 uses the Intl based plural forms as suffix

**Comment by BryceGraves** [comment]
@jamuhl I think the main point of the duplication across languages that don't use the forms was because it made `Crowdin` unhappy while syncing across languages. Historically I think our translation house has just filled in higher plural forms with the last available ones when they aren't available.

Would it be possible to add a note to the JSON Format documentation page to call out the mapping isn't 1:1?

Either way updating to use the new V4 format will resolve this issue for me. I appreciate your time and assistance.

**Comment by adrai** [comment]
https://www.i18next.com/misc/json-format

<img width="804" alt="image" src="https://user-images.githubusercontent.com/1086194/216255354-31b08728-7357-48dd-a50e-d958f1ac8d37.png">


btw: with [locize](https://locize.com) you would not have such issues ;-)

locize is the official sponsor of i18next. With using locize you directly support the future of i18next.
