### ISSUE TITLE
Nesting of keys

### ISSUE THREAD

**Issue by atulmy** [i18next/i18next#1907]
While using this library, once the keys start growing, it seems we've been repeating the keys for each language, which is very tedious to maintain and diff. Is there a possibility to group by key and then for each key, we specify language?

Current:
```javascript
const resources = {
  en: {
    translations: {
      welcome: 'Welcome',
      goodbye: 'Goodbye'
    }
  },

  es: {
    translations: {
      welcome: 'Bienvenidas',
      goodbye: 'Adiós'
    }
  },
}
```

Proposed:
```javascript
const resources = {
  translations: {
    welcome: {
      en: 'Welcome',
      es: 'Bienvenidas'
    },
    goodbye: {
      en: 'Goodbye',
      es: 'Adiós'
    }
  }
}
```
When nested by key, its easier to see which translations are missing.

**Comment by adrai** [comment]
No.

**Comment by jamuhl** [comment]
makes no sense. translations get loaded by backends based on current language. changing this would mean to load all.

on bigger projects you will have to use some translation management anyway -> eg. our https://locize.com

**Comment by jamuhl** [comment]
beside that ... it should be rather easy to write a converter function taking 

```js
const resources = {
  translations: {
    welcome: {
      en: 'Welcome',
      es: 'Bienvenidas'
    },
    goodbye: {
      en: 'Goodbye',
      es: 'Adiós'
    }
  }
}
```

and converting that to needed form:

```js
const resources = {
  en: {
    translations: {
      welcome: 'Welcome',
      goodbye: 'Goodbye'
    }
  },

  es: {
    translations: {
      welcome: 'Bienvenidas',
      goodbye: 'Adiós'
    }
  },
}
```

**Comment by atulmy** [comment]
@adrai
> No.

Thanks.

@jamuhl 
> translations get loaded by backends based on current language. changing this would mean to load all.

We can still load the specific keys by current language, just pre process it or something? Transform the keys?

**Comment by atulmy** [comment]
@jamuhl that looks good, probably allow the "userland" to decide however they'd like to define the `resources` and i18next does the transform under the hood?

The DX is not scalable with repeating the keys 😓

**Comment by adrai** [comment]
> The DX is not scalable with repeating the keys 😓

Was never a problem since 2011 🤷‍♂️

**Comment by jamuhl** [comment]
backends load one namespace in one language at a time...https://www.i18next.com/how-to/add-or-load-translations#load-using-a-backend-plugin 

like said....you can do whatever you like...doing some map-reduce...or even create some on loading mechanism and use the resourceStore functions to fill translations: https://www.i18next.com/overview/api#resource-handling

DX is not practical anyway...you will see 1000 keys later also having one big resource file in your format will be a pain. Plus that format won't help in long term when you start working with translators.

**Comment by atulmy** [comment]
@jamuhl although that makes sense, will still explore more options how the DX can be made better. Thanks for the amazing library 🙏
