### ISSUE TITLE
How to properly lazy load a local resource while waiting for backend to resolve?

### ISSUE THREAD

**Issue by simonarcher** [i18next/i18next#1910]
Hi all,

So Im having some trouble trying to effectively display a local resource of translations while waiting for the backend to resolve.

I have [created a question on StackOverflow here](https://stackoverflow.com/questions/75398918/how-to-properly-use-chainedbackend-with-i18next-when-managing-server-side-transl), but not getting much activity from it so I hope its ok if I ask for help here as well :) 

So the thing Im struggling with at the moment is that currently on init of my i18n object its currently trying to load backend resources from a remote storage location.
If the user's connection is off or poor, or even if something is wrong with the server itself, then the i18n object is not initialised in time and the translations aren't loaded and the user sees our locize keys. This is obviously not super ideal.
So Im trying to set it up that at the very least to init with a local collection of translated namespaces, then "update" to the resolved resources it loads from the backend.

At the moment Ive tried a number of things but I just cant seem to crack this..

Ive tried using the ChainedBackend approach, 

``` js
import namespaces from '../config/translations/namespaces.json';

const enTranslations = require('../config/translations/generated/en.json');
const enEuTranslations = require('../config/translations/generated/en-EU.json');
const frTranslations = require('../config/translations/generated/fr-FR.json');
const beTranslations = require('../config/translations/generated/nl-BE.json');
const nlTranslations = require('../config/translations/generated/nl-NL.json');

const prebuildLanguages = {
  jsons: {
    en: enTranslations,
    'en-EU': enEuTranslations,
    'fr-FR': frTranslations,
    'nl-BE': beTranslations,
    'nl-NL': nlTranslations,
  },
  namespaces,
};

const loadResources = async (language: string, namespace: string) => {
 // IF NO CONNECTION THIS CAN TAKE A LONG TIME TO RESOLVE, LEADING TO THE INSTANCE NOT BEING INITIALISED ON TIME
  return storage()
    .ref(`${firebaseStoragePath}/${language}/${namespace}.json`)
    .getDownloadURL()
    .then((result) =>
      fetch(result)
        .then((response) => {
          return response.json();
        })
        .catch(() => {
          // @ts-ignore
          return prebuildLanguages.jsons[language][namespace];
        })
    )
    .catch((error) => {
      console.log('i18n loadResources ERROR 2', language, namespace, error);
      return prebuildLanguages.jsons[language][namespace];
    });
};

const backendOptions = {
  loadPath: '{{lng}}|{{ns}}',
  request: (options: any, url: any, payload: any, callback: any) => {
    try {
      const [lng, ns] = url.split('|');
      loadResources(lng, ns).then((response) => {
        callback(null, {
          data: response,
          status: 200,
        });
      });
    } catch (e) {
      console.error(e);
      callback(null, {
        status: 500,
      });
    }
  },
};

i18n.use(ChainedBackend).init({
  ns: namespaces,
  defaultNS: 'app_common',
  supportedLngs: ['en', 'en-EU', 'fr-FR', 'nl-BE', 'nl-NL'],
  fallbackLng: 'en',
  partialBundledLanguages: true,
  debug: true,
  backend: {
    backends: [backend, resourcesToBackend(prebuildLanguages.jsons)],
    backendOptions: [backendOptions, null],
  },
});
```

but it doesnt work because the timeout of the backend can take a couple minutes, which is not enough time to "fallback" to the local collection (so user still sees translation keys)

Ive tried using `partialBundledLanguages` and adding resources,

``` js
i18n
  .use(backend)
  .init({
    react: {
      useSuspense: false,
    },
    ns: namespaces,
    defaultNS: 'app_common',
    supportedLngs: ['en', 'en-EU', 'fr-FR', 'nl-BE', 'nl-NL'],
    fallbackLng: 'en',
    partialBundledLanguages: true,
    debug: true,
    backend: backendOptions,
  });

 i18n.addResourceBundle('en', 'app_onboarding', {  new_onboarding_landing_title: '[local] your best pictures deserve us',
});
```

 but it seems like while it loads the `partialBundledLanguages` on init, it doesnt "update" these namespaces (ie. `app_onboarding`) on the resolution of the backend files and I still see the `[local]` copy

I've tried using `resourcesToBackend` (based on this ["Lazy Load in memory translations" documentation](https://www.i18next.com/how-to/add-or-load-translations#lazy-load-in-memory-translations))...

``` js
i18n
  .use(backend)
  .use(resourcesToBackend(prebuildLanguages.jsons))
  .init({
    react: {
      useSuspense: false,
    },
    ns: namespaces,
    defaultNS: 'app_common',
    supportedLngs: ['en', 'en-EU', 'fr-FR', 'nl-BE', 'nl-NL'],
    fallbackLng: 'en',
    partialBundledLanguages: true,
    debug: true,
    backend: backendOptions
  });
```
but while it loads the local bundled translations, it doesnt update the translations once the backend is resolved either

Ive also tried creating 2 instances of the `i18n` class, one that initialised with local resources and one initialised with the backend, then use the local instance if the backend instance is not yet initialised, but of course that doesnt/wouldnt work because only one instance can be initialised. (an attempt was made :p )  

So essentially Im not sure how I should be approaching to handle this.

Is it possible that someone can guide me in the right direction here how to effectively load and use my local "`prebuildLanguages.json`" while the `backend` waits to resolved its loading of resources?

Thank you for any guidance! :) 

**Environment:**
I am using this in a React Native application, and below are my packages
```
    "i18next": "^22.4.9",
    "i18next-async-storage-backend": "^1.0.2",
    "i18next-chained-backend": "^4.2.0",
    "i18next-http-backend": "^2.1.1",
    "i18next-react-native-async-storage": "^1.0.4",
    "i18next-resources-to-backend": "^1.1.1",
```

**Comment by jamuhl** [comment]
`partialBundledLanguages` does only load things not already loaded -> eg. you bundled "en" and like other languages or sections to be loaded later (it's just about optionally have already bundled stuff)

does triggering: https://www.i18next.com/overview/api#reloadresources not work for your case?

**Comment by simonarcher** [comment]
thanks for the quick response @jamuhl !

No, I haven't come across that api function yet... do you have a suggestion when/where/how I could use it in my scenario?

**Comment by jamuhl** [comment]
using `react-i18next` you might trigger a fake 'languageChanged' event on i18next.emit to trigger a rerender using the `useTranslation` hook

**Comment by adrai** [comment]
something like this:

```js
i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    debug: !isProduction,
    fallbackLng: 'en',
    resources: {
      en: {
        translation: {
          description: {
            part2: 'SOME inmemory fallback resources'
          }
        }
      }
    }
  });


i18n.reloadResources().then(() => {
  i18n.emit('languageChanged', i18n.resolvedLanguage)
})
```

**Comment by simonarcher** [comment]
Thanks! ok, I think I might be making some small progress here, but hitting a snag with the above suggestions..

If I do this (to match my key and translation example I used originally), and where I try call the `reloadResources` when it successfully inits with the local resources...

``` js
const onInit = (options) => {
  i18n.reloadResources().then(() => {
    console.log('reloadResources done', i18n.resolvedLanguage);
  });
};

i18n.on('initialized', onInit);

i18n
  .use(Backend)
  .init({
    debug: !isProduction,
    fallbackLng: 'en',
    resources: {
      en: {
        app_onboarding: {
          new_onboarding_landing_title: 'SOME in memory fallback resources'
        }
      }
    },
   backend: backendOptions,
  });
```

then it does seem to correctly show the in memory `new_onboarding_landing_title` value, and then on a UI refresh it would display the updated server translation (if and when its downloaded)

The question I have, is that I have my `en` translations bundled in a local `en.json` file. How do I use that file as the resource for `resources` in this case?

thanks again for all the input so far! 🙌

**Comment by adrai** [comment]
depends on your json structure, if it contains also your namespace(s):

```js
//...
resources: {
      en: require('../config/translations/generated/en.json')
}
//...
```

...if not:

```js
//...
resources: {
      en: {
         app_onboarding: require('../config/translations/generated/en.json')
      }
}
//...
```

**Comment by simonarcher** [comment]
@adrai thanks!
That worked a treat for me, and I think things are working closer to how I would like them to... looking good so far!

Thanks again :)
