### ISSUE TITLE
Plural and returnObjects don't perform interpolation

### ISSUE THREAD

**Issue by acerbisgianluca** [i18next/i18next#1912]
## 🐛 Bug Report

Hi, basically I'm not able to use plurals and `returnObjects: true`, because i18next seems to look for a key without the plural suffix.

I'm not sure if this is an expected behavior or not, so I'm gonna report it.

## To Reproduce

Just run the code below:

```js
i18next.init({
        lng: 'en',
        debug: true,
        resources: {
            en: {
                translation: {
                    test_one: {
                        message: {
                            speech: 'speech: {{count}}',
                            text: 'text: {{count}}',
                        },
                    },
                    test_other: {
                        message: {
                            speech: 'speech: {{count}}',
                            text: 'text: {{count}}',
                        },
                    },
                },
            },
        },
        returnObjects: true,
    });

    console.log(i18next.t('test', { count: 1 }));
```

The code prints an object, but interpolation doesn't work and the result is: `{ message: { speech: 'speech: {{count}}', text: 'text: {{count}}' } }`.

With debug mode on, it also prints this error `i18next::translator: missingKey en translation test.message test.message`, so basically i18next seems to ignore the plural suffix while searching for the `message` key inside `test`, because `test` alone actually doesn't exist.

## Expected behavior

`{ message: { speech: 'speech: 1', text: 'text: 1' } }`

## Your Environment

- *runtime version*: node v16.17.0
- *i18next version*: 22.4.9
- *os*: Windows

**Comment by adrai** [comment]
https://github.com/i18next/i18next/issues/1726

**Comment by acerbisgianluca** [comment]
Thanks for the response, but it seems a bit different though.

In my case, the "pluralized" element is the root one, so everything inside that object should be interpolated, nested, etc. like @jamuhl said [here](https://github.com/i18next/i18next/issues/1725#issuecomment-1024493078).

While the other user would like to apply plural, context, etc. to the internal fields of a returned object, which is not my case.
I'm not familiar with i18next code, so maybe these 2 problems are linked (and probably are), but just to be sure that I explained myself correctly.

**Comment by adrai** [comment]
In your example the plural suffix key needs to be the last one.
And those suffixed keys can't have other sub values.
