### ISSUE TITLE
Unable to use i18n.format after adding formatter function with new API

### ISSUE THREAD

**Issue by marcalexiei** [i18next/i18next#1913]
## 🐛 Bug Report

Using `i18n.format` function doesn't work with new formatters (`i18next.services.formatter.add`).

When setting format function inside `interpolation` configuration I can safely format values without passing through `i18n.t`.

```ts
i18n.format(variable, 'formatter')
```

Now when adding a formatter with the new syntax this no longer works and a warning is issued in console:

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/24919330/219637289-4fdd7c13-e779-4d2a-b2e7-dd6c236e4753.png">

[The affected line should be this one](https://github.com/i18next/i18next/blob/fdaf2cb578c70ac26ff9ca88284bac22d1f94fe1/src/Formatter.js#L118)

On typescript definition `FormatFunction` has `format`, `lng`, `options` parameters marked as optional. 
The fix could just add default value to `options` param as `{}`. From the looks of it it shouldn't break other checks.

## To Reproduce

1. Go to the [code sandbox ](https://codesandbox.io/s/i18next-custom-formatter-not-working-with-i18n-format-w4t6z0?file=/src/index.ts)
2. Check the console

`"test"` string is not formatted

```ts
import { default as i18n } from "i18next";

i18n.init({
  lng: "en",
  resources: {
    en: {
      translation: { text: "my {{value, uppercase}}" }
    }
  },
  interpolation: {
    escapeValue: false // react already safes from xss
  },
  debug: true
});

i18n.services.formatter.add("uppercase", (value: string) => {
  console.info("formatter function");
  return value.toUpperCase();
});

console.info("using t with formatted inside resource ===>", i18n.t("translation:text", { value: "value" }));

console.info("using i18n.format ===>", i18n.format("test", "uppercase"));
```

## Expected behaviour

Format function is applied to the value passed to `i18n.format` so the result should be `TEST`.

## Your Environment

- *runtime version*: i.e. Chrome 110.0.5481.100
- *i18next version*: i.e. 22.4.9
- *os*: MacOS

**Comment by adrai** [comment]
v22.4.10 should address this
