### ISSUE TITLE
Missing documentation for Typescript arrays

### ISSUE THREAD

**Issue by ScreamZ** [i18next/i18next#1915]
The documentation for Typescript here is not mentioning how to deal with keys that are arrays.

```json
{
  "join_us_form": {
    "choices": ["First", "Second"]
  }
}
```

Therefore this will yield : `t("join_us_form.choices.1");` 

How can we proceed?

**Comment by adrai** [comment]
https://github.com/i18next/i18next/blob/ffb8d0670af9394c87da834f3dc86c03ad081e18/test/typescript/t.test.ts#L125

**Comment by adrai** [comment]
This all works in JS, so might be a TS only issue.

```
const i18next = require('i18next')

i18next.init({
  fallbackLng: 'en',
  resources: {
    en: {
      translation: {
        "join_us_form": {
          "choices": ["First", "Second"]
        }
      }
    }
  }
})

console.log(i18next.t('join_us_form.choices.1')) // Second
console.log(i18next.t('join_us_form.choices', { returnObjects: true })[1]) // Second
```

**Comment by ScreamZ** [comment]
I can confirm that `console.log(i18next.t('join_us_form.choices.1'))` doesn't work with Typescript but `console.log(i18next.t('join_us_form.choices', { returnObjects: true })[1])` does

**Comment by ScreamZ** [comment]
This would require the usage of [template literal types ](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) but we can't guess the array length at build tile because this is impossible to cast `as const` imported JSON… Damn :'(

**Comment by adrai** [comment]
maybe @pedrodurek can have a look at it with its new approach: https://github.com/i18next/i18next/pull/1911
