### ISSUE TITLE
Change "ns" to "namespace" to avoid ambiguity with national socialism

### ISSUE THREAD

**Issue by Leichesters** [i18next/i18next#1917]
"ns" is a term mostly used to describe National Socialists - people with the belief that some people are "better" than others. We shouldn't identify with such people and disassociate from them.

Therefore I strongly recommend to replace "ns" with "namespace".

**Comment by jamuhl** [comment]
Hi Leichesters, as you can see from the past we take such concerns serious. Just see past issues going into same direction.

use of trans: -> https://github.com/i18next/react-i18next/issues/1532
use of blacklist: -> https://github.com/i18next/i18next/issues/1466

In the case of "ns" usage I think coming to associate that with the meaning "national socalism" is to far fetched. We use that term now over 10 years and never got anyone else reporting this as an issue.

Futher just doing a quick google search with the term "ns" gives enough results like eg. ns.nl (Nederlandse Spoorwegen) or nsbikes.com which have zero association.

There are endless usages of NS to shorten something...Niederspannung, Niveauschalter, Nova Scotia, ...

NS is really official for namespace (coming from DNS) https://www.cloudflare.com/learning/dns/dns-records/dns-ns-record/

I really see your point...but we should fight national socialism where it happens - not by changing terms used in computer science for long time with completely different context and meaning.
