### ISSUE TITLE
use saveMissing in tests

### ISSUE THREAD

**Issue by vmstarchenko** [i18next/i18next#1918]
## Motivation
It would be quite useful to save missing translations during tests.

## Example
Use case:
1) Set saveMissing = true option
2) run tests
3) get updated files with missing translations

**Comment by adrai** [comment]
What prevents you from doing so?

**Comment by vmstarchenko** [comment]
Is it already possible? I looked through the documentation and did not find such a use case. Or do you mean that I can:
- start a server that saves missing translations
- run tests with the saveMissing option enabled
- in tests, the function t() will still access this locally raised server and save missing translations
?

**Comment by adrai** [comment]
i18next does not differentiate between test, dev or prod so if you can configure it, it will work.

**Comment by vmstarchenko** [comment]
Maybe this example will be useful to someone. It shows how you can enable the saveMissing option in tests. And this tests will save translations directly to the file system without using a additional local server. This example is quite rough and hasn't been tested yet for corner cases (like missing files and directories or json parsing errors).

```typescript
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

import Backend from 'i18next-http-backend';

const env = process.env.NODE_ENV;

let fs: any, path: any, publicRoot: any
if (env === 'test') {
  fs = require('fs');
  path = require('path');
  publicRoot = path.resolve(path.join(__dirname, '../public'));
}

const testingRequest = (options: any, url: any, payload: any, callback: any) => {
  if (typeof payload === 'function') {
    callback = payload
    payload = undefined
  }
  callback = callback || (() => {})

  if (payload === undefined) {
    const data = fs.readFileSync(url, { encoding: 'utf8' });
    return (async () => callback(null, { status: 200, data: data }))();
  } else {
    let missing = {};
    try {
      const missingData = fs.readFileSync(url, { encoding: 'utf8' });
      missing = JSON.parse(missingData);
    } catch {
    }
    missing = {...missing, ...payload};
    fs.writeFileSync(url, JSON.stringify(missing, undefined, 2), { encoding: 'utf8' });
    return callback(payload);
  }
};

i18n
  .use(Backend)
  .use(initReactI18next)
  .init({
    fallbackLng: 'en',
    debug: env === "development",
    saveMissing: env === 'test',
    backend: (env === 'test' ? {
      loadPath: path.join(publicRoot, '/locales/{{lng}}/{{ns}}.json'),
      addPath: path.join(publicRoot, '/locales/{{lng}}/{{ns}}.missing.json'),
      request: testingRequest,
    } : {
      loadPath: '/locales/{{lng}}/{{ns}}.json',
    }),

    interpolation: {
      escapeValue: false,
    }
  });

export default i18n;
```
