### ISSUE TITLE
Key type in post process method should be an array

### ISSUE THREAD

**Issue by Wineric** [i18next/i18next#1919]
## 🐛 Bug Report

PostProcessorModule['process'] signature says key is a string but when testing it is an array. 

## To Reproduce

```js
import i18next, { t } from "i18next";
i18next.use({
    type: "postProcessor",
    name: "foo",
    process: (_, key) => console.log(key)
}).init({
  lng: "en",
  postProcess: ["foo"],
  resources: {
   en: {translation: {key:"bar"}}
 },
});
t("key");
```

## Expected behavior

```js
export interface PostProcessorModule extends Module {
  /** Unique name */
  name: string;
  type: 'postProcessor';
  process(value: string, key: string[], options: TOptions, translator: any): string;
}
```

## Your Environment

- *runtime version*: i.e. node v14
- *i18next version*: i.e. 22.4.10
- *os*: Mac

**Comment by adrai** [comment]
it may be string or string[] based on what I see here: https://github.com/i18next/i18next-intervalPlural-postProcessor/blob/master/src/index.js#L57
v22.4.11 should address this
