### ISSUE TITLE
An error is reported when the root user executes the pipeline：root without --no-sandbox is not supported

### ISSUE THREAD

**Issue by WilliamHeaven** [i18next/i18next#1923]
## 🐛 Bug Report

An error is reported when the root user executes the pipeline：root without --no-sandbox is not supported

## Expected behavior

No error is reported when the root account is used to execute the pipeline.

## Your Environment

- *runtime version*: node v16, chrome
- *i18next version*: v22.4.11
- *os*: Linux
- *any other relevant information*

**Comment by adrai** [comment]
Sorry, but I have no idea of what you mean.
Can you please elaborate?
When does which error occur?

**Comment by WilliamHeaven** [comment]
Sorry I didn't make myself clear :(

I was trying to run `npm test`, which used `karma.conf.js` and `karma.backward.conf.js` as configuration. In these files, the [flags of HeadlessChrome](https://github.com/i18next/i18next/blob/416f317115f99ba003c9c5d42bf95ed9a6049d4f/karma.conf.js#L32) are set to `['—no-sandbox']`, which should be `['--no-sandbox']`. A dash (—) is put here instead of two hyphen (--), so I get an error when running this script as a root user of Linux, saying that `root without --no-sandbox is not supported `.

I search `--no-sandbox` option on Google, and in most case, the `flag` option should be `['--no-sandbox']`. That's why I'm rasing this issue. Hope I make myself clear this time.

**Comment by adrai** [comment]
https://github.com/i18next/i18next/commit/81c0501db8daf61aead034296d55451c68d2853e
