### ISSUE TITLE
Bug in getBestMatchFromCodes function

### ISSUE THREAD

**Issue by ogenodisho** [i18next/i18next#1927]
## 🐛 Bug Report

getBestMatchFromCodes does not return the best match from the provided codes.

## To Reproduce

Set the following i18n properties:

```js
{
    fallbackLng: "fr",
    supportedLngs: ["dev", "en", "fr"],
    nonExplicitSupportedLngs: true,
}
```

Call the following:

```js
i18n.services.languageUtils.getBestMatchFromCodes(["de"])
```

https://codesandbox.io/s/relaxed-joji-wosyxz?file=/src/app.js

## Expected behavior

The supported languages are dev, English, and French. The fallback language is French.

From these, I am attempting to get the best match for German, which doesn't exist, so I expect to get French back because that is the fallback. However, I end up getting back 'dev' instead.

I believe the root cause was introduced here: https://github.com/i18next/i18next/commit/add4e294584bd4e17c30b9f21a7b6f2ea356bba5#diff-4c175c6868688b1c06d13548d8b7543c7101f7b52c444b6ccc96d6cb4850bebfR109

```js
if (supportedLng.indexOf(lngOnly) === 0) return supportedLng;
```

In my case, it ends up evaluating this:

```js
if ('dev'.indexOf('de') === 0) return 'dev';
```

Which is incorrect. The 'dev' language happens to start with the German language code: 'de'.

## Your Environment

Codesandbox environment with the following deps:

```json
{
    "i18next": "latest",
    "i18next-browser-languagedetector": "latest",
    "i18next-http-backend": "latest",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-i18next": "11.7.0",
    "react-scripts": "3.4.1"
}
```

**Comment by adrai** [comment]
please try again with v22.4.12

**Comment by jamuhl** [comment]
just a sidenote...a correct use of "dev" would be using it as fallbackLng in development env -> saveMissings get sent to "dev" if not existing there.

"dev" should not be kept in production env settings.

But anyway @adrai already provided a fix.

**Comment by ogenodisho** [comment]
@jamuhl Yes I agree. This bug wasn't encountered in a production env. It was encountered in my development and the behaviour seemed incorrect. I tried it again with v22.4.12 and it works. Thank you @adrai .
