### ISSUE TITLE
Support fallbackNS in CustomTypeOptions 

### ISSUE THREAD

**Issue by Darhagonable** [i18next/i18next#1928]
## 🚀 Feature Proposal
Support fallbackNS in CustomTypeOptions

## Motivation
There's currently no way to use fallbackNS together with the strong typing.

## Example
https://codesandbox.io/s/missing-fallbackns-support-example-jmsgud?file=/src/App.tsx

**Comment by Darhagonable** [comment]
Not stale

**Comment by Darhagonable** [comment]
Not stale

**Comment by Darhagonable** [comment]
Not stale

**Comment by Darhagonable** [comment]
Not stale

**Comment by adrai** [comment]
@Darhagonable the redesigned types are 99% ready to be released: https://github.com/i18next/i18next/pull/1911/files
if you like you can start a PR to address also fallbackNS handling... (cc: @pedrodurek )

**Comment by adrai** [comment]
supported in v23.2.2
