### ISSUE TITLE
Utilize TypeScript 5.0 const Type Parameters

### ISSUE THREAD

**Issue by Darhagonable** [i18next/i18next#1929]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

With the release of TypeScript 5.0 [const Type Parameters](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#const-type-parameters) were added.

As mentioned in [the documentation](https://www.i18next.com/overview/typescript#type-error-template-literal) currently to use template literal with an expression one need to use const assertion as following:
```ts
// with i18next
i18next.t(`${expression}.title` as const);

// with react-i18next
const { t } = useTranslation();
t(`${expression}.title` as const);
```

Now with `const Type Parameters` this should be possible to avoid by adding const type parameter to the the `t` function typing instead.

**Comment by Darhagonable** [comment]
Not stale

**Comment by Darhagonable** [comment]
Not stale

**Comment by Darhagonable** [comment]
Not stale

**Comment by Darhagonable** [comment]
Not stale

**Comment by adrai** [comment]
should work with the new redesigned types

**Comment by adrai** [comment]
Please try with i18next v23.0.1 and react-i18next v13.0.0
