### ISSUE TITLE
separator option for Interpolation object

### ISSUE THREAD

**Issue by TomWaterson** [i18next/i18next#1930]
## 🚀 Feature Proposal

Provide users with an ability to change dot walking syntax similar to `keySeparator` property for interpolation objects.

## Motivation

I have a requirement to interpolate an object that contains dots. The interpolation object comes from the BE response of an HTTP request and some keys contain dots which breaks interpolation, and I have no control over the response.

I have tried to use the object as a dynamic resource with `addResourceStore` and nested translations, but it is getting very unwieldy and default formatting does not seem to work with nested translations, which is a common use case.

## Example

```
// Interpolation Object
const interpolate = {
  MyObject: {
    "Example.NotNested": "basic interpolation"
  }
}
// Translation resource
{
  "Basic": "A {{MyObject::Example.NotNested}}"
}

I18nextInstance.init({
      keySeparator: "::",
      interpolationKeySeparator: "::",
      nsSeparator: ":::",
})

const works = I18nextInstance.t("Basic", interpolate)

expect(works).toBe("A basic interpolation")
```

**Comment by jamuhl** [comment]
just run https://www.npmjs.com/package/unflatten over your interpolate variable

**Comment by adrai** [comment]
or try this, with v22.4.13

```js
const i18next = require('i18next')

// Interpolation Object
const interpolate = {
  MyObject: {
    "Example.NotNested": "basic interpolation"
  }
}

i18next.init({
  //keySeparator: ".",
  //nsSeparator: ":",
  fallbackLng: 'en',
  resources: {
    en: {
      translation: {
        "Basic": "A {{MyObject.Example.NotNested}}"
      }
    }
  }
})

const works = i18next.t("Basic", interpolate)
console.log(works) // A basic interpolation
```

**Comment by TomWaterson** [comment]
Thank you! Will give those options a go.
