### ISSUE TITLE
`defaultTransParent` type incompatible with Trans `parent` 

### ISSUE THREAD

**Issue by fantua** [i18next/i18next#1933]
## 🐛 Bug Report

https://github.com/i18next/i18next/blob/dd133af54f071deadbd8fd9dd95e0153b4e6deea/index.d.ts#L252

`defaultTransParent` type is missing `React.ComponentType<any>`. See `Trans` [types](https://github.com/i18next/react-i18next/blob/7026d5461409529145d99525cd2463ecd3111b0b/TransWithoutContext.d.ts#LL21C21-L21C45) definition.

## Expected behavior

it should be possible to set react component as `defaultTransParent`.

```ts
import { Text } from 'my-ui-lib';

const config: InitOptions = {
  lng: 'en',
  react: {
    defaultTransParent: Text,
  },
};
```

## Your Environment

- *i18next version*: latest master

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this?

**Comment by fantua** [comment]
Sure, I'm on it
