### ISSUE TITLE
getting unnecessary api call for not defined namespaces

### ISSUE THREAD

**Issue by chaitanya71998** [i18next/i18next#1936]
## 🐛 Bug Report

I Have updated from **19.8.4** to **21.10.0** . after updating this i was getting un-necessary fetch call for name space which i haven't loaded. this is not occurring in **19.8.4** why is it happening in **21.10.0**.
I am using custom name space `intro` but if i use some other(ex: translation) name space while using with withTranslation Hoc as did in below example i was getting a fetch call which didn't happen in **19.8.4**.
## To Reproduce
https://codesandbox.io/s/react-i18n-demo-forked-psoty7?file=/src/index.tsx
![Screenshot from 2023-04-01 12-31-43](https://user-images.githubusercontent.com/46353549/229271654-82bac0de-09cb-4181-9907-d3f1345a274e.png)
```js
export default withTranslation('translation', { withRef: true })(App)

```
## Expected behavior

When using not defined namespaces ideally it should accept it and not to fetch unnecessary api call.
```js
export default withTranslation('translation', { withRef: true })(AudioPlayer)
```

## Your Environment

- *runtime version*: i.e. node v14,
- *i18next version*: i.e. 21.10.0
- *os*: Linux
- along with i18n i am using
```json
       "i18next-http-backend": "1.1.0",
      "react-i18next": "11.18.6",
```

**Comment by jamuhl** [comment]
What you mean with "When using not defined namespaces ideally it should accept it and not to fetch unnecessary api call."

You have `intro` namespace defined as fallbackNS - so it will be loaded on init. You said in the withTranslation HOC you need the `translation` namespace so it will be loaded.

**Comment by chaitanya71998** [comment]
in a repo i was working the they have used like this
```js
export default withTranslation('translation', { withRef: true })(App)
```
When i updated from 19.8.4 to 21.10.0 it api fetches translation.json but there is no file with **translation.json**. In 19.8.4 it didn't fetch like this. i want to know why it happened on updation to 21.10.0 and how to fix this.

**Comment by jamuhl** [comment]
The behaviour is the same in 19.8.4 and 21.10.0 -> if you have the HOC `withTranslation` set to load the namespace translation it will load it. There is no difference in the functionality. The script runs in the browser which has zero connection to your filesystem...it does not know if there is a file translation.json on your server or not....so it will always try to load what you ask it to load...either getting that file back from server or a 404 file not found

**Comment by chaitanya71998** [comment]
😨  but in the webapp i was working i didn't see such fetch calls for tanslation.json file, when the version is 19.8.4. is there any thing i was missing on this.
 for reference here is changes i have done https://www.diffchecker.com/LXx0eQ3Z/

**Comment by jamuhl** [comment]
use your codesandbox https://codesandbox.io/s/react-i18n-demo-forked-psoty7?file=/src/index.tsx downgrade i18next to 19.8.4 and it will also load both namespaces...

**Comment by chaitanya71998** [comment]
yeah i checked but in the app i was working on after 19.8.4 that is from 19.8.5 i was seeing this behaviour

**Comment by chaitanya71998** [comment]
across the app there are this syntaxes,dont know why they were added. 
`export default withTranslation('translation', { withRef: true })(App)`
But to not to load translation.json file what things i need todo.
i was thinking like replacing the above syntax with  below one
`export default withTranslation([], { withRef: true })(App)`
or creating a translation file with empty object.  can you share other best practices!

**Comment by jamuhl** [comment]
on that component wrapped withTranslation you have some keys used inside t function -> add that namespace instead of translation

**Comment by chaitanya71998** [comment]
once check this snippet and why the translation.json is still being called in this snippet
https://codesandbox.io/s/testing-withtranslation-hoc-obc8oj

**Comment by jamuhl** [comment]
https://www.i18next.com/overview/api#init

you did not override the defaultNS and ns array which defaults to `translation` on init:

```js
i18next.init({
 ...
  ns: ['file1', 'file2'],
  defaultNS: 'file1',
  ...
})
```
