### ISSUE TITLE
skipOnVariables is not defaulting to true.

### ISSUE THREAD

**Issue by gcampbell-msft** [i18next/i18next#1940]
## 🐛 Bug Report

See title. We were not passing `skipOnVariables` and it was defaulting to false/undefined. 

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
return i18next.t(key, {
    ...dict,
    interpolation: {
      escapeValue: options.escapeValue ?? true,
    },
  });
```

## Expected behavior

Based on the documentation here: https://www.i18next.com/translation-function/interpolation#all-interpolation-options, it says that this variable should be based as `true`, but it doesn't seem to be, based on my debugging. 

## Your Environment

- *i18next version*: i.e. 21.3.2
- *os*:  Windows

**Comment by adrai** [comment]
please update your i18next version to at least v21.6.9 https://github.com/i18next/i18next/blob/master/CHANGELOG.md#2169
