### ISSUE TITLE
Access to all languages for building Language Selector?

### ISSUE THREAD

**Issue by blaasvaer** [i18next/i18next#1942]
I read that there is no way to get a list of all languages from i18next directly. Is this correct?

If so, then I see a management issue if you cannot create a language switcher based on the available languages already initialized in i18next.

I have to create and export an init object from where I can pull this info, and then pass that into the init function afterwards, to solve the issue.

But it seems like this is a 'missing feature', as it would be one of the first things one would naturally stumble upon using this library.

What did I miss in not seeing this option?

**Comment by adrai** [comment]
If you're adding all your translations via [init](https://www.i18next.com/how-to/add-or-load-translations#add-on-init) you could do something like this: `Object.keys(i18next.store.data)` `// this would return an array of all loaded languages.`
But if you're lazy loading translations after init or via backend plugin, how should i18next know all available languages?
i18next does not know this.
fyi: Special backend plugins like [i18next-locize-backend](https://github.com/locize/i18next-locize-backend#backendgetlanguages) may have additional functionality that would return such an information.

**Comment by blaasvaer** [comment]
Thanks. That's my point: I load them on init. And then I'd expect to be able to pull a list of currently available languages – seems to not be the case. And there's nothing in the docs on i18next.store.data. Which makes it a bit hackish in my view ... I can find info on i18next.store, but it seems to be only related to a few events.

**Comment by jamuhl** [comment]
As you load them on init...you know the languages you have yourself...so there is no real reason to export them from i18next instance.

**Comment by blaasvaer** [comment]
Erhm, yes there is. I want to be able to generate a language switcher (and all sorts of related sruff) based on these initialized languages, and not have a management situation where I would have to maintain multiple places for languages.
