### ISSUE TITLE
How to use across multiple modules?

### ISSUE THREAD

**Issue by blaasvaer** [i18next/i18next#1943]
I initialize i18next in my "Localize Module" which is loaded from my "Login Module", now HOW would I use i18next from within other modules? It doesn't seem to be available 'globally' without me trying to hack my way through it. Do I seriously have to import it into every single module, and reinitialize it (even though I've read I shouldn't call init more that once) or create instances? It seems cumbersome. Why not be able to add it to a global for being available throughout the application?

What am I missing, that makes i18next available globally across ALL my individual modules (yeah, there are a lot)?

Couldn't find anything in the docs that would clarify this.

**Comment by jamuhl** [comment]
Works like every module...

if using imports - import it where needed...

call: i18next.init once in the main module or wherever it suits you
call: i18next.t where you need translations

**Comment by blaasvaer** [comment]
Thanks, I might have been overthinking this ... ; )
