### ISSUE TITLE
The function t() alter the passed options

### ISSUE THREAD

**Issue by DavidHenri008** [i18next/i18next#1947]
## 🐛 Bug Report

When options are passed to the function ```i18n.t()``` they are being altered.

This becomes an issue when the options is a reused object, such as a constant. So after calling t() the options object now contains the lng property with the current language. But if the language is changed and the t() is called again with the same options, the old language will be used...

## To Reproduce

You can look at the console log of this [CodeSandbox](https://codesandbox.io/s/i18next-t-options-e8dl6m?file=/src/index.js)

This issue has been introduced in version 22.4.14.

## Expected behavior

The expected behavior is that the options are copied before being modified.
In fact, the function [getFixedT()](https://github.com/i18next/i18next/blob/ad67e60aa8f8144fdf165fdbe6dcfe6093d6b851/src/i18next.js#L387) does that. But it should be part of t() instead.

## Your Environment

- *runtime version*: node 18.14.2, browser Chrome
- *i18next version*: 22.4.14
- *os*:  Windows

**Comment by adrai** [comment]
You are right.
v22.4.15 should fix that.
