### ISSUE TITLE
Don't transpile to es5

### ISSUE THREAD

**Issue by MonstraG** [i18next/i18next#1948]
## 🚀 Feature Proposal

We are in 2023, and maybe we can try targeting es6 (especially because this package dropped support for IE in 3 years ago).

This can be easily done by adding 
```json
{
  "browserslist": [
    "defaults"
  ]
}
```

## Motivation

I'm using `i18next` in several applications (trough `next-i18next`), and often, `i18next` is a single biggest dependency I have at 100kb (non-minified). 

`defaults` of `browserlists` targets es6, and this single change drops esm build size  down to 81kb. (approx. -20%)

## Example

Smaller builds, faster loads worldwide.

**Comment by adrai** [comment]
we'll evaluate that for the next major

**Comment by gunjam** [comment]
I only use i18next serverside in a nodejs application so I'm less concerned about package size, but I would also like a way in require() a non-babeled version of i18next. Babel has introduced a lot of es6 polyfils into the package which have a big performance impact, the i18next object spread polyfil is the hottest code path in my whole application, replacing the npm installed package with a non-babled version of the library increaed my requests per second by 10%!

**Comment by adrai** [comment]
prepared for next major version
