### ISSUE TITLE
Customizable decimal and thousandths separator.

### ISSUE THREAD

**Issue by wg5789** [i18next/i18next#1949]
## 🚀 Feature Proposal

Regardless of the language set, it should be possible to set the decimal and thousandth separator globally and for each use of the number translation key.

## Motivation

The entire application does not always require a single-volume translation of numbers. 

## Example

Sometimes customer specific requirements is to have some places with formatted numbers may have had a period in the decimal place or a space or special character in the thousandth place.

**Comment by adrai** [comment]
Did you check the formatting feature?
It is Intl based.

https://www.i18next.com/translation-function/formatting
