### ISSUE TITLE
Javascript heap out of memory

### ISSUE THREAD

**Issue by khoi-nguyen** [i18next/i18next#1951]
## 🐛 Bug Report

Error (Javascript heap out of memory) when compiling a library that just import "useTranslation" from react-18next with tsc.

I'm trying to create a separate component library that just needs the "useTranslation" hook, while the main project has i18next set up. i18next works well on the main project, but I can't compile my component library if I import anything related to i18next. Apologies if I've made a mistake or if I've missed something obvious.

## To Reproduce

- Start with an empty folder
- `npm install i18next react-i18next`
- Create a file that just contains `import { useTranslation } from "react-i18next";`
- Run "tsc" on that file

## Expected behavior

Successful compilation

## Your Environment

- *runtime version*: node 19.9
- *i18next version*: i.e. 22.4.15
- *os*: Linux

**Comment by adrai** [comment]
probably same: https://github.com/i18next/react-i18next/issues/1608

**Comment by adrai** [comment]
@pedrodurek is currently working on this: https://github.com/i18next/i18next/pull/1911

**Comment by khoi-nguyen** [comment]
@adrai Thank you for referencing the issue. I can confirm it's the same and that downgrading ts to 4.9.5 temporarily solves the issue.

Thanks again!
