### ISSUE TITLE
t function with interpolation doesn't work without defaultValue

### ISSUE THREAD

**Issue by MasGaNo** [i18next/i18next#1953]
## 🐛 Bug Report

Given this translation key: `"k_selectedFilter": "{filter}: {value}"`.

In a previous version, I used to use such approach:
```tsx
  const { t } = useTranslation();
  t('k_selectedFilter', {
    filter: filter.label,
    value: filter.value
  })
```

Now, with the latest version (`22.4.15`), I'm facing this issue:
```
Type 'TFunctionDetailedResult<string>' is not assignable to type 'ReactNode'.ts(2322)
index.tsx(10, 3): The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & Props'
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ filter: string; value: string; }' is not assignable to parameter of type 'TOptionsBase & { filter: string; value: string; } & { defaultValue: string; }'.
      Property 'defaultValue' is missing in type '{ filter: string; value: string; }' but required in type '{ defaultValue: string; }'.ts(2769)
index.d.ts(1018, 46): 'defaultValue' is declared here.
index.d.ts(1013, 3): The last overload is declared here.
```
<img width="629" alt="image" src="https://user-images.githubusercontent.com/5469433/236154104-d1ffef9c-b752-4872-ab48-7f9d42801e15.png">

The only way for me to fix it is to add `defaultValue`:
```tsx
  const { t } = useTranslation();
  t('k_selectedFilter', {
    filter: filter.label,
    value: filter.value,
    defaultValue: ''
  })
```
<img width="247" alt="image" src="https://user-images.githubusercontent.com/5469433/236154154-38459172-00e7-4744-a352-267fa1c1adb6.png">

It seems that it's obsessed with this [rule](https://github.com/i18next/i18next/blob/master/index.d.ts#L1012):
```ts
<
    TDefaultResult extends DefaultTFuncReturn = string,
    TInterpolationMap extends object = StringMap,
  >(
    key: string | string[],
    options: TOptions<TInterpolationMap> & { defaultValue: string },
  ): TFuncReturn<ActualNS, string, TDefaultResult, TKPrefix>;
```

If I add this sample (from previous version)
```ts
<
    TDefaultResult extends DefaultTFuncReturn = string,
    TInterpolationMap extends object = StringMap,
  >(
    key: string | string[],
    options: TOptions<TInterpolationMap> | string,
  ): TFuncReturn<ActualNS, string, TDefaultResult, TKPrefix>;
```
It works as expected:
<img width="214" alt="image" src="https://user-images.githubusercontent.com/5469433/236156291-a1156998-2528-4c20-b4c3-d3ac77df9a9b.png">

## To Reproduce

Check above

## Expected behavior

Interpolation should works without any errors.

## Current workaround
```ts
// i18next.d.ts

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    resources: I18nNamespaces;
  }

  export interface TFunction<
    N extends Namespace = DefaultNamespace,
    TKPrefix = undefined,
    ActualNS extends Namespace = N extends null ? DefaultNamespace : N
  > {
    <
      TDefaultResult extends DefaultTFuncReturn = string,
      TInterpolationMap extends object = StringMap
    >(
      key: string | string[],
      options: TOptions<TInterpolationMap> | string
    ): TFuncReturn<ActualNS, string, TDefaultResult, TKPrefix>;
  }
}
```
<img width="260" alt="image" src="https://user-images.githubusercontent.com/5469433/236157468-2c21648a-470a-4327-9e12-ab89688c59bf.png">

## Your Environment

- *runtime version*: node 18.14.0
- *i18next version*: 22.4.15
- *os*: Mac

**Comment by adrai** [comment]
probably addressing with: https://github.com/i18next/i18next/pull/1911

**Comment by adrai** [comment]
Should be addressed with the new redesigned types... will release a new version soon

**Comment by adrai** [comment]
Please try with i18next v23.0.1 and react-i18next v13.0.0

**Comment by adrai** [comment]
should work....
proof here: https://github.com/locize/i18next-typescript-examples/blob/main/2/index.ts
