### ISSUE TITLE
How to turn off or on debug logging dynamically - ¿possible bug?

### ISSUE THREAD

**Issue by vituchon** [i18next/i18next#1954]
Hi Folks! Hope you are doing fine.

Sorry to bother.... 

I'm having [this situation](https://stackoverflow.com/questions/76183456/i18next-turn-on-off-debug-mode-dinamically). I don't know what door to knock, so I posted in stackoverflow and here.

Thanks in advance!

**Comment by adrai** [comment]
You can inject your custom logger plugin: https://www.i18next.com/misc/creating-own-plugins#logger

example: https://codesandbox.io/s/react-i18next-http-example-forked-kn1yuz?file=/src/i18n.js:188-363

**Comment by vituchon** [comment]
@adrai thanks for the insight! It is working.... I have make a quick test...

```
var log = false;
const myLogger = {
  type: 'logger' as ModuleType,

  log: (args:any) => {
    if (log) {
      console.log(args)
    }
  },
  warn: (args:any) => console.warn(args),
  error: (args:any) => console.error(args)
}
window.i18next.use(myLogger).use().init(i18nextOptions, () => {
    log = true;
  }
})
``` 
and when var log is set to true then I see the logger log level lines in the console (and not before!) GREAT!. The motivation are to hide log lines that ng-i18next angularjs filter produces due to not having the i18next loading yet.

If you can provime me context about what I was doing with
    `i18next.logger.setDebug(true)`
vs
    `i18next.translator.logger.setDebug(true) `

I will appreciate it very much as well!.


TD;DR;

The problem with ng-i18next, the commented lines were a proposal to fix them...

![image](https://user-images.githubusercontent.com/1927644/236502935-b7e143a5-c3f4-467c-b2c0-67612f2853be.png)

**Comment by vituchon** [comment]
I'm afraid i18next.logger.setDebug(false or true) doesn't makes any visible effect on the log IF the log starts with debug false then in keep "muted" besides doing `i18next.logger.setDebug(true)` ¿That this have any sense?

My version of i18next.js is 21.6.16

**Comment by adrai** [comment]
currently afk, will check later

**Comment by adrai** [comment]
Sorry, I was wrong... there is not a single instance of the logger... each sub-module creates its own logger instance...
So currently I suggest you create your own logger plugin and do not use the setDebug function at all.
An alternative way to workaround that and make use of the setDebug function would be to change the logger like that: https://github.com/i18next/i18next/pull/1957
But I don't know if this in-line with the original design of @jamuhl

**Comment by jamuhl** [comment]
yes there are "sub-loggers" but as far as I know only for the translator module...

I never saw a use case beside having the logger turned on/off once using options on init -> debug is only set to true in development env anyway....so who cares about getting those warnings as they are not logged during production 

enabling both loggers (main instance and the one on translator should be sufficient). I still wouldn't change the setDebug on an instance to toggle behaviour on all. If that's needed a copy of the base logger should do.

**Comment by adrai** [comment]
> only for the translator module

fyi: there are 6 sub-loggers
<img width="362" alt="image" src="https://user-images.githubusercontent.com/1086194/236605947-a2bc58f4-cb90-4dde-a7b1-2c10bb67b379.png">

**Comment by jamuhl** [comment]
still...i'm against bloating more unneeded kb into the module...just because one case of wanting selective warnings.

the case in ng-i18next is solved better like:
![236502935-b7e143a5-c3f4-467c-b2c0-67612f2853be](https://user-images.githubusercontent.com/977772/236607997-a5160a0d-77fa-4fe4-9417-9923753906c9.png)

-> the issue is there in ng-i18next...i18next.t gets used before init -> so the warning is correct.

It's not something this module has to solve...

**Comment by jamuhl** [comment]
beside that - what comes next. Turn off warnings if a namespace was not loaded as the implementation for the UI framework has no `useTranslation` like react-i18next?

**Comment by adrai** [comment]
since the setDebug function is not used at all we maybe should remove it completely

**Comment by jamuhl** [comment]
would be breaking change...as it could be used in userland (just not used internal)...in the end...all can be done...it's just not one global toggle...

```js
// turn all on
i18next.logger.setDebug(true);
i18next.translator.logger.setDebug(true);
Object.values(i18next.services).forEach(s => s.logger && s.logger.setDebug(true));
```

**Comment by adrai** [comment]
@vituchon we'll probably remove the setDebug function completely in the next major version... so like @jamuhl already suggested. the warning log is correct and ng-i18next should address this. And alternatively you can inject your own logger.

**Comment by vituchon** [comment]
@adrai @jamuhl thanks for adressing this issue.

It is not something crucial, but desirable to have it working. It happens on specific scenario due to some code of ng-i18next that try to translate prior of having i18next initialized. An I agree that the problem shall be fixed at ng-i18next level, and not here. But the project looks quite abandon.... I mean, I have [filled a bug some months ago](https://github.com/i18next/ng-i18next/issues/165) and there was no reply.

Leaving that aside and if you may allow a personal opinion => I think that the setDebug(true or false) shall be working as expected. Right now is a no op, so, you may document it well or you may fix it. There can be other cases in the future where devs would like to turn on or off this feature.

Using a custom logger works like a charm, so that was an good workaround for this. 

Thanks for taking into consideration this affair, and keep up the good work!.
