### ISSUE TITLE
Clarifications about behavior on missing keys

### ISSUE THREAD

**Issue by igorsantos07** [i18next/i18next#1961]
## Documentation issue
The behavior of `saveMissing` is not straightforward and isn't clear from the [current documentation page](https://www.i18next.com/overview/configuration-options#missing-keys). It says simply that it "calls save missing key function on backend", but I didn't find information about said "save missing key function" at `resources-to-backend` nor `localstorage-backend`, which are the two we currently use.
Similarly, `updateMissing` and `saveMissingTo` are also confusing - probably because the main `saveMissing` is hard to understand already, without some extra context?

My suggestion would be to write a small paragraph below the "missing keys" header, explaining what happens when a key is not found, and how `saveMissing` might be used in different scenarios / backends, if ever.

> Bonus: `missingKeyHandler` would benefit from some extra documentation on its arguments, such as what's the `fallbackValue` or `updateMissing`

## Motivation

The main reason here is that some developers might not be used to this type of behavior (e.g. I come from a gettext translation background) and it's hard to grasp what's that for without some extra context or explanation.

-------------
>Note: I wasn't sure if this should be opened here or at i18next-gitbook - the issue template for doc issues is a bit ambiguous, since it's for doc issues but docs are at i18next.com.... :sweat_smile:

**Comment by adrai** [comment]
added some more information: https://www.i18next.com/overview/configuration-options#missing-keys
