### ISSUE TITLE
How to turn off escaping for specific values (or at all)

### ISSUE THREAD

**Issue by rpsteiger** [i18next/i18next#1963]
<!--
### Do you have a documentation issue?
Ok, then describe it and provide some motivation on why this should be changed.

Hello, based on the documentation I do not understand how I am supposed to turn off escaping for a value:

Here's how I output the value:
```
<a class="cd-h-timeline__date"
                  data-date="01/01/2000"
                  href="#0"
                  style="left: 300px"
                  data-i18n="nav.step3"
                  ></a
```

I cannot use `-data-i18n` to to turn off escaping.
Furthermore I tried to turn off escaping globally like this:
```
const init_i18n = (settings) => {
        i18next
          .use(i18nextBrowserLanguageDetector)
          .init({
            debug: false,
            interpolation: { escapeValue: false},
            fallbackLng: 'de',
[..SNIP..]
```
This also did not work.

Can someone please help me out? If I am not mistaken then the documentation should be adjusted.

**Comment by adrai** [comment]
https://www.i18next.com/translation-function/interpolation#unescape
