### ISSUE TITLE
backendConnector: Request cannot be constructed from a URL that includes credentials: 

### ISSUE THREAD

**Issue by day0ff** [i18next/i18next#1964]
## 🐛 Bug Report

I'm trying to lazyload translations by passing credentials by URL *http://{user}:{password}@example.com/*, but I didn't get anything. The request is not happening.

Without passing credentials by URL, this works perfectly.

Here is what I'm seeing in the console with debug: true in init:
![Screenshot from 2023-05-22 10-42-17](https://github.com/i18next/i18next/assets/36659489/7a2bfa5a-3ed2-4757-8b29-768b4a2a0b1a)

## To Reproduce

```js
import i18n from "i18next";
import {initReactI18next} from "react-i18next";
import Backend from "i18next-http-backend";

i18n
  .use(initReactI18next)
  .use(Backend)
  .init({
    debug: true,
    load: "all",
    fallbackLng: FALLBACK_LOCALE,
    fallbackNS: [CUSTOM_NS, FALLBACK_NS],
    ns: [CUSTOM_NS, FALLBACK_NS],
    defaultNS: CUSTOM_NS,
    interpolation: {
      escapeValue: false,
    },
    resources,
    partialBundledLanguages: true,
    react: {useSuspense: false},
    backend: {
      saveMissing: true,
    },
  });

```

## Expected behavior

Could you fix it? Or suggest a solution.

## Your Environment

- *i18next*: 21.9.1
- *i18next-http-backend*: 2.2.0,
- *react*: 18.2.0,
- *react-i18next*: 11.18.5,
- *runtime version*: node v16.16.0
- *os*: Linux

**Comment by adrai** [comment]
The fetch api does not accept that.
You need to pass the credentials via backend options: https://github.com/i18next/i18next-http-backend#backend-options
https://stackoverflow.com/questions/45067331/request-with-url-that-includes-credentials

```js
import i18n from "i18next";
import {initReactI18next} from "react-i18next";
import Backend from "i18next-http-backend";

i18n
  .use(initReactI18next)
  .use(Backend)
  .init({
    debug: true,
    load: "all",
    fallbackLng: FALLBACK_LOCALE,
    fallbackNS: [CUSTOM_NS, FALLBACK_NS],
    ns: [CUSTOM_NS, FALLBACK_NS],
    defaultNS: CUSTOM_NS,
    interpolation: {
      escapeValue: false,
    },
    resources,
    partialBundledLanguages: true,
    react: {useSuspense: false},
    backend: {
      // loadPath: 'your/load/path',
      customHeaders: {
        authorization: `Basic ${btoa(username + ':' + password)}`
      }
    },
  });
```
