### ISSUE TITLE
i18n giving missingkey error in prod

### ISSUE THREAD

**Issue by PradeepCyble** [i18next/i18next#1966]
Hi team, 

We have implemented the i18n translation to change the language in our application. this is throwing the missingkey error some times even though the key is present in language file.  it is reproducible in production, in local environment the translation is working absolutely fine. this is observed more when we deploy the new build to prod or some time randomly. can you please let me know if there are any use case or reason why this is happening. 

## 🐛 Bug Report

```js
/import i18n from 'i18next';
import {useTranslation, initReactI18next} from 'react-i18next';
import HttpBackend from 'i18next-http-backend';
import i18next from 'i18next';

i18n.use(initReactI18next)
    .use(HttpBackend)
    .init({
        ns: ['auth'],
        defaultNS: 'auth',
        fallbackLng: 'en',
        backend: {
            loadPath: '/locale/{{lng}}/{{ns}}.json?uuid=' + new Date().getTime(),
        },
        react: {useSuspense: true}, //this line
    })
    .then((c) => {});

export const setLanguageNamespace = (type, cb) => {
    i18next.loadNamespaces(type, (err, t) => {
        i18next.setDefaultNamespace(type);
        if (!!cb) {
            cb();
        }
    });
};

```

**Comment by adrai** [comment]
Not easy to help without a reprducible example.
Set the debug option to true and provide the console logs.
I suspect the t function is called before the corresponding translations are loaded.

**Comment by PradeepCyble** [comment]
Sure, allow me to add debug and get the logs.

**Comment by PradeepCyble** [comment]
Hi Here are some logs I got, issue is after loading the page translation is looking into default ns. please refer the code snippet mentioned above.  attached the screenshot for your reference.

<img width="1437" alt="Screenshot 2023-06-01 at 9 19 28 AM" src="https://github.com/i18next/i18next/assets/132122099/e930abbd-c24c-4ff9-a5b9-1505157e50ab">

**Comment by PradeepCyble** [comment]
after loading "main" name sapce also translation method is looking into "auth" namespace

**Comment by adrai** [comment]
Why are you using the setDefaultNamespace function?
Aren't you using the useTranslation hook with the corresponding namespace?

**Comment by PradeepCyble** [comment]
We are using class components in our application soo we used  loadNamespaces and setDefaultNamespace

**Comment by adrai** [comment]
Then use the HOC: https://react.i18next.com/latest/withtranslation-hoc

**Comment by PradeepCyble** [comment]
Thanks you, Let me try that.

**Comment by PradeepCyble** [comment]
Hi adrai, I have tried the HOC method it now loading single namespace, withTranslation(['ns1', 'ns2', 'ns3']) this method loading only the first namespace, can you please tell me why is this happening. According to the documentation it should load all the name spaces and it should set first one as default rite.

**Comment by adrai** [comment]
@PradeepCyble yes it should load all namespaces... Can you please create a minimal reproducible example without react-native (I have no dev environment to test), so we can investigate your issue... Because the HOC and also the hook seems to work like expected.
