### ISSUE TITLE
addResource ignores keySeparator in options arg

### ISSUE THREAD

**Issue by hchy0422** [i18next/i18next#1968]
## 🐛 Bug Report

Based on the `addResource`  document, https://www.i18next.com/overview/api#addresource, the options argument allows to set `keySeparator` and `silence`. However, the `keySeparator` is ignored. The root cause is `addResource` doesn't use `option.keySeparator`, [L493](https://github.com/i18next/i18next/blob/master/i18next.js#L493)

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// init i18next with dot as keySeparator
i18next.init({
  fallbackLng: 'en-US',
  ns: ['translation'],
  keySeparator: '.'
}, (err, t) => {
  if (err) return console.log('something went wrong loading', err);
  t('key'); // -> same as i18next.t
});

// for some resource, key has dot, so I want to use a different keySperator
i18next.addResource('en-US', 'translation', 'pay code 1', 'locale 1', { keySperator: '|' })
i18next.addResource('en-US', 'translation', 'pay code 1.5', 'locale 1.5', { keySperator: '|' })
```

## Expected behavior

Expect to have two resource keys that are `pay code 1.5` and `pay code 1`, but `pay code 1.5` is split by `.`

```js
// expected
{
  'pay code 1': 'locale 1';
  'pay code 1.5': 'locale 1.5'
}

// actual
{
  'pay code 1': {
    '5': 'locale 1.5'
  }
}

```

## Your Environment

- *runtime version*: node v16
- *i18next version*: 22.5.0
- *os*: Mac
- *any other relevant information*

**Comment by adrai** [comment]
i18next can only handle 1 uniq keySeparator for the whole instance.

**Comment by hchy0422** [comment]
Thanks for replying. we would like to handle several special translations. Those key are defined in backend system, so we cannot change them. And we are aware of where to use a different separator while translating. 

If keySeparator are not allowed as 5th argument in addResource, why it’s added as an available argument in API document?

**Comment by adrai** [comment]
I've just aligned the addResource function to the existing getResource function... now you should be able to pass the keySeparator via options...
v22.5.1
