### ISSUE TITLE
Namspaces and Spaces

### ISSUE THREAD

**Issue by angelica-snowit** [i18next/i18next#1970]
## 🐛 Bug Report

Namespaces seems to not work as intended when key contains spaces.

## To Reproduce

```js
const i18next = require('i18next');

const LOCALES = ['it', 'en'];
const DEFAULT_LOCALE = 'it';
const ALL_NAMESPACES = ['common', 'test'];
const DEFAULT_NAMESPACE = 'common';
const DEFAULT_I18NEXT_CONFIG = {
  initImmediate: true,
  whitelist: LOCALES,
  lng: DEFAULT_LOCALE,
  preload: LOCALES,
  ns: ALL_NAMESPACES,
  defaultNS: DEFAULT_NAMESPACE,
  fallbackNS: DEFAULT_NAMESPACE,
  resources: {
    it: {
      common: {
        test1: 'common - it',
      },
      test: {
        test2: 'test - it',
        'test with a space': 'test with a space - it',
      },
    },
    en: {
      common: {
        test1: 'common - en',
      },
      test: {
        test2: 'test - en',
        'test with a space': 'test with a space - en',
      },
    },
  },
};

i18next.init(DEFAULT_I18NEXT_CONFIG).then(() => {
  console.log('Expecting "test-it":', i18next.t('test:test2'));
  console.log('Expecting "test with a space - it":', i18next.t('test:test with a space'));
  console.log('Expecting "unknown":', i18next.t('test:unknown'));
  console.log('Expecting "unknown with a space":', i18next.t('test:unknown with a space'));
});
```

## Expected behavior

Both the existing behaviour and the missing should work in the same mode with key without or with spaces.
Instead, when the key contains a space, the namespace is ignored:

Expecting "test-it": test - it
Expecting "test with a space - it": test:test with a space
Expecting "unknown": unknown
Expecting "unknown with a space": test:unknown with a space

## Your Environment

- *runtime version*: node v18.13.0
- *i18next version*: v22.5.0
- *os*: Mac

**Comment by adrai** [comment]
By default i18next tries to detect if the key looks like to be in natural language... if you don't like that, set also the `nsSeparator: ':'` option.

**Comment by adrai** [comment]
btw: the whitelist option has been renamed to supportedLngs: https://www.i18next.com/misc/migration-guide#v20.x.x-to-v21.0.0

**Comment by angelica-snowit** [comment]
Thank you!
