### ISSUE TITLE
ResourceStore options doesn't update on instance clone

### ISSUE THREAD

**Issue by GheorgheP** [i18next/i18next#1974]
## 🐛 Bug Report

When clone the instance using `i18n.cloneInstance`, the `ResourceStore` is not cloned with new options.
Specifically in my case the `keySeparator` is used from original instance.

## To Reproduce

```js
const instance = i18n.cloneInstance({
  keySeparator: '[[my-new-separator]]'
})
```

Then try to translate a text with the new instance:
```js
instance.t('my-key[[my-new-separator]]value');
```

When trying to translate with original instance key separator, it does translate.

### Cause
I investigated the problem and it is cause by the fact that we create the `ResourceStore` at the `init`, but only when new instance is created, not cloned. So it is initialised only with initial options: https://github.com/i18next/i18next/blob/18ce83f7f5a28548cef107c5cad5434ef5033a60/src/i18next.js#L83-L102

**Comment by adrai** [comment]
Better use different instances => https://www.i18next.com/overview/api#createinstance

**Comment by GheorgheP** [comment]
> i18n.cloneInstance reuses same resources -> so why should the separators be different using same translations?!?

The idea is simple. I have a react app, that uses a UI library (also made by me). So I pass to that ui library the `i18n` instance for it's internal translations. But that UI library queries that strings different from my main app (because it was made independent from my main app). 
In the end I have the necessary translations with the proper structure, but the separator strings or context/plural separators are different.

Maybe we can create something like `ResourceStore.cloneInstance` similar to `i18n.cloneInstance`, so you can change the options that doesn't affects the resources. I do understand that creating a new `ResourceStore` may no be a good idea, or a bad idea at all, but we can use the same clone strategy.

**Comment by GheorgheP** [comment]
> Better use different instances => https://www.i18next.com/overview/api#createinstance

In my case this is not a good idea as I use remote translations and creating a new instance would mean to lod twice the resources.

**Comment by adrai** [comment]
v23.1.0 introduces a new cloneInstance option:
```
const instance = i18n.cloneInstance({
  forkResourceStore: true,
  keySeparator: '[[my-new-separator]]'
})
```
