### ISSUE TITLE
Build fails at node_modules/i18next/index.d.ts in 23.2.0 

### ISSUE THREAD

**Issue by michnak** [i18next/i18next#1978]
## 💥 Regression Report

I'm unable to transpile a node app using tsc in 23.2.0

## Last working version

Worked up to version: 23.1.0

Stopped working in version: 23.2.0

## To Reproduce

Simply importing i18next

```ts
import i18next from 'i18next';
```

Leads to this:
<img width="755" alt="Screenshot 2023-06-20 at 9 22 27" src="https://github.com/i18next/i18next/assets/26062519/b98d89e7-dcd6-4c4c-9887-edc4e712fbb7">

## Expected behavior

It works fine in 23.1.0

## Your Environment

- *runtime version*: i.e. node v18.16
- *i18next version*: i.e. 23.2.0
- *os*: MacOS

**Comment by adrai** [comment]
@henrikvolmer can you have a look at this?

https://github.com/i18next/i18next/pull/1975

**Comment by adrai** [comment]
@henrikvolmer I suspect it happens as soon as you set the fallbackNS to false
<img width="419" alt="image" src="https://github.com/i18next/i18next/assets/1086194/6368c54b-8f8b-43cd-96e9-6ac70a6db7ce">

**Comment by adrai** [comment]
Try it here: https://github.com/i18next/i18next/tree/master/examples/typescript
update the i18next dep and run npm run build

**Comment by henrikvolmer** [comment]
Created a fix PR. My bad, sorry :)

**Comment by michnak** [comment]
Wow, thanks for the blazingly fast resolution!

**Comment by adrai** [comment]
v23.2.1 has just been published

**Comment by henrikvolmer** [comment]
You're welcome. Please inform me if this works for your case.

**Comment by michnak** [comment]
I'm sorry, but it's still failing on the same problem.

Here's the i18next setup - but only the import of i18next alone is enough for it to fail. 
```ts
import { join } from 'path';
import i18next from 'i18next';
import Backend from 'i18next-fs-backend';

i18next.use(Backend).init({
  initImmediate: false,
  debug: true,
  ns: ['email'],
  defaultNS: 'email',
  lng: 'en',
  fallbackLng: 'en',
  backend: {
    loadPath: join(
      // Used both on a server and in next dev server
      process.cwd().replace(/\.react-email$/, ''),
      'src/locales/{lng}/{ns}.json',
    ),
  },
});

console.log('Translations are ready');

export { i18next };
```

**Comment by adrai** [comment]
How does your i18next.d.ts file look like?

**Comment by michnak** [comment]
I don't have any.

**Comment by adrai** [comment]
So can you provide a reproducible example (repo)?

**Comment by michnak** [comment]
I'm sorry, but it's a company repo - but the use case is really simple:

I have the file above and then I'm using it like this:

```tsx
import { Button } from '@react-email/button';
import { Html } from '@react-email/html';
import React from 'react';

import { i18next } from '../core/i18next';

export default function Email() {
  return (
    <Html>
      <Button
      >
        {i18next.t('cta_button')}
      </Button>
    </Html>
  );
}
```

The thing is, that it is working fine in 23.1.0

**Comment by adrai** [comment]
The problem is, we need to see all your ts setup... for example how does your tsconfig look like?

**Comment by michnak** [comment]
```json
{
  "ts-node": {
    // Do not forget to `npm i -D tsconfig-paths`
    "require": ["tsconfig-paths/register"]
  },
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "target": "es2020",
    "sourceMap": true,
    "outDir": "./dist",
    "rootDir": "src",
    "incremental": true,
    "baseUrl": "src",
    "paths": {
      "@/*": ["*"]
    },
    "jsx": "react-jsx"
  },
  "include": ["src/**/*"]
}
```

**Comment by henrikvolmer** [comment]
Can you provide a full example in a [codesandbox](codesandbox.io)?

**Comment by michnak** [comment]
I'm setting up the codesandbox - but I'm unable to replicate it right now. I'll get to you in the evening.

**Comment by michnak** [comment]
I'm unable to replicate it in CodeSandbox. I'll get to you when I figure it out.
