### ISSUE TITLE
Can't compile with tsc (typescript)

### ISSUE THREAD

**Issue by ghostlexly** [i18next/i18next#1981]
## 🐛 Bug Report

I can't build my app after i installed i18next

## To Reproduce

I have installed i18next 23.2.0 and typescript 4.9.4

```tsx
tsc -p .
```

Results in:

```
#0 0.414 $ tsc -p .
#0 4.938 node_modules/i18next/index.d.ts(856,32): error TS2536: Type 'false' cannot be used to index type 'Keys'.
#0 4.938 node_modules/i18next/index.d.ts(856,53): error TS2344: Type 'boolean' does not satisfy the constraint 'Namespace<string>'.
#0 4.938 node_modules/i18next/index.d.ts(858,33): error TS2344: Type 'boolean' does not satisfy the constraint 'Namespace<string>'.
#0 5.020 error Command failed with exit code 2.
```

## Expected behavior

Build successfully

## Your Environment

- *runtime version*: node v18.16.0
- *i18next version*: i.e. 23.2.0
- *os*: Mac

**Comment by adrai** [comment]
Please update the i18next dependency.

**Comment by ghostlexly** [comment]
Thanks for your quick reply.

It's still buggy, here is the console:

````
node_modules/i18next/index.d.ts:853:32 - error TS2536: Type 'false' cannot be used to index type 'Keys'.

853         | ParseKeysByKeyPrefix<Keys[$FirstNamespace<_FallbackNamespace>], KPrefix>
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/i18next/index.d.ts:853:53 - error TS2344: Type 'boolean' does not satisfy the constraint 'Namespace<string>'.

853         | ParseKeysByKeyPrefix<Keys[$FirstNamespace<_FallbackNamespace>], KPrefix>
                                                        ~~~~~~~~~~~~~~~~~~

node_modules/i18next/index.d.ts:855:33 - error TS2344: Type 'boolean' does not satisfy the constraint 'Namespace<string>'.

855         | ParseKeysByNamespaces<_FallbackNamespace, Keys>
                                    ~~~~~~~~~~~~~~~~~~
````

**Comment by adrai** [comment]
Are you sure the new version is installed?
That issue has been fixed yesterday...

**Comment by adrai** [comment]
ahh not seen... you are using the older typescript version

**Comment by adrai** [comment]
@henrikvolmer ?

**Comment by ghostlexly** [comment]
Ah, my fault, you're right, upgrading to typescript 5.1.3 fixed the issue, you're awesome thanks for your help 👍

**Comment by adrai** [comment]
fyi: v23.2.2 should also work for the older TS version...
@henrikvolmer fyi: https://github.com/i18next/i18next/commit/f0c3b30c58a2909b53768c5679b85c4a8f403a59

**Comment by ScorpioCoding** [comment]
Hi there I'm using react-router 7.0 and have typescript 5.0 install.
I cannot install i18next due to it uses typescript 4.9.4.
Any suggestions?

**Comment by adrai** [comment]
i18next v24 supports TS v5 only

**Comment by ScorpioCoding** [comment]
> i18next v24 supports TS v5 only

So How Do I integrate i18next with create-react-app and react-scripts 5.0.1

**Comment by adrai** [comment]
That's a problem of react-scripts... https://github.com/facebook/create-react-app/issues/13080

if you still need ts v4, then stay on i18next v23

**Comment by ScorpioCoding** [comment]
> That's a problem of react-scripts... [facebook/create-react-app#13080](https://github.com/facebook/create-react-app/issues/13080)
> 
> if you still need ts v4, then stay on i18next v23
> 
> Alternatively, with react-scripts, you can also try to define overrides, like here: https://github.com/locize/i18next-typescript-examples/blob/main/5/package.json#L27

Overrides did the job, thank you
