### ISSUE TITLE
Wrong return type

### ISSUE THREAD

**Issue by falsandtru** [i18next/i18next#1982]
Explained in #1971.

```ts
// ok
const a: object = t('friend', { returnObjects: true });
// ok but should be an error
const b: string = t('friend', { returnObjects: true });
```

**Comment by pedrodurek** [comment]
We could constraint the return type to be `object` only when `returnObjects: true`, but I'm against doing the same if `returnObject` is set to `true` inside the `CustomOptionTypes` since it applies globally.

Up to you to decide @adrai

**Comment by adrai** [comment]
sounds reasonable

**Comment by adrai** [comment]
probably also returnDetails

**Comment by pedrodurek** [comment]
`returnDetails` is already behaving correctly 😄
