### ISSUE TITLE
Support passing `lng` to `exists` function, while still being able to rely on `fallbackLng` function in `init`

### ISSUE THREAD

**Issue by adworacz** [i18next/i18next#1989]
## 🚀 Feature Proposal
Right now, if a user configures a custom fallback function via the `fallbackLng` parameter in the i18next `init` function, that callback custom is *not* used when making an `exists` call with a specific `lng`.

I propose that an option is exposed (perhaps similar to `getFixedT`?) that enables users to pass a language to `exists`, but know that it will properly fallback based on their custom function setup in `init`.

## Motivation

While working with `exists` + fallbacks recently, I realized that `exists` does *not* fallback based on our custom function, and in order to get it properly fallback to different languages, I have to essentially rerun our fallback function to generate values to pass to the `lngs` option. This means we can't just specify *how* to fallback in one place, when initializing. We have to continually specify fallback functions to every use of `exists`.

## Example

```typescript
//translations exist for 'es', but not 'es-ES', for example

// Produces an array from a long code, like: ('es-ES') => ['es-ES', 'es']
const turnLongCodesIntoShortCodes = (longCode) => {...}

init({
  ...
  fallbackLng: (code) => turnLongCodesIntoShortCodes(code),
 ...
})

//Today
exists(key, { lng: 'es-ES' } ) // returns false, because it doesn't fallback to `es`, per the `fallbackLng` option above.
//Today's workaround, which requires *reusing* the fallback function
exists(key, { lngs: turnLongCodesIntoShortCodes('es-ES') })

//Proposal 
exists(key, { lng: 'es-ES' }) //returns true
//or something similar to getFixedT
getFixedExists('es-ES')(key) //returns true
```

**Comment by adrai** [comment]
Can you please provide a complete example?

This seems to work for me:

```js
const i18next = require('i18next')

i18next.init({
  resources: {
    es: {
      translation: {
        hi: 'there'
      }
    }
  }
})

console.log(i18next.t('hi', { lng: 'es-ES' })) // there
console.log(i18next.exists('hi', { lng: 'es-ES' })) // true
```

**Comment by adworacz** [comment]
You know what - I must be crazy. I just started retesting this behavior again after I saw you're note, and I agree with you, this already seems to work as is.

It seems that our repository was slightly misconfigured before, causing us to jump through extra hoops. By fixing that, then all the fallback logic appears to work just fine.

Apologies for the bother, resolving.
