### ISSUE TITLE
Worse typechecking performance with version 23

### ISSUE THREAD

**Issue by agos** [i18next/i18next#1991]
## 💥 Regression Report

I upgraded to i18next 23.2.6 and react-i18next 13.0.1, expecting type checking times to get better. Instead, they got markedly worse (5x by my estimate), making it unusable.

## Last working version

Worked up to version: 22.5.1

Stopped working in version: 23.0.1

## To Reproduce

I'll try to make a reproducible case, but in the meanwhile the setup is ~700 entries in the default namespace, and 10 or so other namespaces with a few tens of entries each

## Expected behavior

Typechecking, whether `tsc --noEmit` or the checks made by `ESLint`, does not get worse

## Your Environment

- *runtime version*: node 18.12.1
- *i18next version*: 23.0.1 through 23.2.6
- *os*: Mac
- tried on ts 4.9, 5.0, 5.1

**Comment by pedrodurek** [comment]
Hey @agos, could you create a reproducible example? It may be a component or specific feature that may cause the problem. The example will help us find the root cause.

**Comment by adrai** [comment]
Related? https://github.com/i18next/i18next/issues/1921#issuecomment-1614113491

**Comment by WookieFPV** [comment]
I have the same issue.
tsc and eslint for the whole codebase takes much longer.
I did some benchmarks for 2 branches (old and new version).

i18next-rollback branch:
```
"i18next": "22.5.1",
"react-i18next": "12.3.1",
```

dev branch:
```
"i18next": "23.2.6",
"react-i18next": "13.0.1",
```

```
// tooling:
"typescript": "5.1.6",
"@tsconfig/react-native": "2.0.3",
"eslint": "8.44.0",
```


### tsc:

```
hyperfine --setup "git checkout i18next-rollback && yarn" --warmup 1 --runs 3 "yarn tsc" 
Benchmark 1: yarn tsc
  Time (mean ± σ):      9.879 s ±  0.277 s    [User: 16.822 s, System: 0.767 s]
  Range (min … max):    9.694 s … 10.198 s    3 runs
 
hyperfine --setup "git checkout dev && yarn" --warmup 1 --runs 3 "yarn tsc"
Benchmark 1: yarn tsc
  Time (mean ± σ):     74.697 s ±  8.522 s    [User: 83.247 s, System: 2.416 s]
  Range (min … max):   67.029 s … 83.872 s    3 runs
```
**==> 7,5x times longer**

### eslint:

```
hyperfine --setup "git checkout dev && yarn" --warmup 1 --runs 3 "yarn lint"                                                                                                     
Benchmark 1: yarn lint
  Time (mean ± σ):     71.706 s ±  4.505 s    [User: 88.316 s, System: 4.904 s]
  Range (min … max):   66.517 s … 74.629 s    3 runs
 
hyperfine --setup "git checkout i18next-rollback && yarn" --warmup 1 --runs 3 "yarn lint"
Benchmark 1: yarn lint (
  Time (mean ± σ):     23.150 s ±  1.185 s    [User: 36.703 s, System: 3.135 s]
  Range (min … max):   22.339 s … 24.510 s    3 runs
```
**==> 3,1x times longer**

I don't know why eslint can also be affected but its reproducible in our repo.
  
I can try to setup a full repro repo if needed.
Here is a minimalistic repro:
  
We use i18next & i18next-react in a react-native app.
We only use the hook API. The setup is very basic, only 1 namespace.
But fully typechecked.
  
  
```
// file: i18n/i18nKeys.ts
  
// Enforce that Key and Object property are the same (useful for i18n translation key enum)
export type KeyEnum<T extends string> = Record<T, T>;

const keysRaw = {
  foo: 'foo',
  bar: 'bar',
} as const;

export type KeyType = keyof typeof keysRaw;

export const KEYS: KeyEnum<KeyType> = keysRaw;
```

```
// file: i18n/resources.ts.ts

// en.json is flat (without nesting)
import translationEN from './translations/';

export const resources = {
  en: { translation: translationEN },
} as const;

export type TranslationsEN = typeof resources.en.translation;
```

```
// file: i18n/index.ts

import i18next from 'i18next';
import { initReactI18next } from 'react-i18next';
import { resources } from 'i18n/resources';
   
i18next.use(initReactI18next).init({
  debug: false,
  resources,
  cache: undefined,
  fallbackLng: 'en',
  lng: 'en',
  interpolation: {
    escapeValue: false,
  },
  returnEmptyString: false,
});

export { i18next };
```

```
// i18next.d.ts

// import the original type declarations
import 'i18next';
// import all namespaces (for the default language, only)
import ns1 from 'i18n/translations/en.json';

// react-i18next versions higher than 11.11.0
declare module 'i18next' {
  // and extend them!
  interface CustomTypeOptions {
    // custom namespace type if you changed it
    defaultNS: 'ns1';
    // custom resources type
    resources: {
      ns1: typeof ns1;
    };
  }
}
```

```
// exampleComponent.tsx

import React from 'react';
import { View, Text } from 'react-native';
import { useTranslation } from 'react-i18next';
import { KeyType } from 'i18n/keys';

export const ExampleComponent = ({ translationKey }: { translationKey: KeyType }): React.JSX.Element => {
  const { t } = useTranslation();
  return (
    <View>
      <Text text={t(translationKey)} />
    </View>
  );
};
```

```
// tsconfig.json
{
  "extends": "@tsconfig/react-native/tsconfig.json",
  "exclude": [
    "android",
    "ios",
    "node_modules",
    "coverage",
    "babel.config.js",
    "metro.config.js",
    "jest.config.js",
    "index.js",
    "react-native.config.js",
    "test-reports"
  ]
}

```

Is that enough or should I provide a full repro repo ?

**Comment by pedrodurek** [comment]
Hey @WookieFPV, would you mind creating a full repro repo?

**Comment by WookieFPV** [comment]
Sure @pedrodurek,

I created a minial repro repo based on an empty react-native app.

https://github.com/WookieFPV/i18nextPerfReproRN

Thank you very much for helping 👍

**Comment by BC-M** [comment]
> Sure @pedrodurek,
> 
> I created a minial repro repo based on an empty react-native app.
> 
> https://github.com/WookieFPV/i18nextPerfReproRN
> 
> Thank you very much for helping 👍

Results on MacBook Pro M1 Max:

```
➜  i18nextPerfReproRN git:(main) ✗ yarn installOld >/dev/null && time npx tsc
npx tsc  2.18s user 0.13s system 210% cpu 1.097 total
➜  i18nextPerfReproRN git:(main) ✗ yarn installNew >/dev/null && time npx tsc
npx tsc  15.78s user 0.44s system 118% cpu 13.727 total
```

**Comment by kamui545** [comment]
> ```
> ➜  i18nextPerfReproRN git:(main) ✗ yarn installOld >/dev/null && time npx tsc
> npx tsc  2.18s user 0.13s system 210% cpu 1.097 total
> ➜  i18nextPerfReproRN git:(main) ✗ yarn installNew >/dev/null && time npx tsc
> npx tsc  15.78s user 0.44s system 118% cpu 13.727 total
> ```

Similar performance regression on one of my app, 4s -> 25s

**Comment by kitsunekyo** [comment]
for us as well. larger codebase with lots of namespaces `yarn tsc --noEmit` goes from 3s to js memory error.

```
"i18next": "^23.2.11",
"react-i18next": "^13.0.2",
```

**Comment by pedrodurek** [comment]
@WookieFPV, sorry for the delay.

Thanks to your example, I managed to find the issue and a solution. I explained a little bit further in the PR description. 
I didn't manage to benchmark using my example because my example has thousands of nested keys, while yours it's a flat object with multiple keys.

**Comment by adrai** [comment]
should be better with v23.3.0

**Comment by WookieFPV** [comment]
> @WookieFPV, sorry for the delay.
> 
> Thanks to your example, I managed to find the issue and a solution. I explained a little bit further in the PR description. I didn't manage to benchmark using my example because my example has thousands of nested keys, while yours it's a flat object with multiple keys.

Thanks for the improvement.
I can confirm that this fixes the issue:

```
22.5.1  tsc:  9.11s
23.2.11 tsc  40.15s
23.3.0  tsc: 10.87s
```

**Comment by kamui545** [comment]
Definitely better, thank you guys !

```
22.5.0 - 4.21s
23.2.11 - 25.09s
23.3.0 - 6.96s
```

**Comment by v1nn1k** [comment]
Fixed the issue for us as well! Many thanks @pedrodurek and other participants
