### ISSUE TITLE
Type issue / Regression: No t function autocomplete when value not in array  

### ISSUE THREAD

**Issue by nizans** [i18next/i18next#1992]
Hello, I have an issue with TS 5.1.3.
Autocomplete does not works, but it does works on previous TS version ( tested on 5.0.4 ).

## 💥 Regression Report

t function does not autocomplete with `typescript@5.1.3` when providing value as a string.
It does works when providing and array. but not a string.
When downgrading to `typescript@5.0.4` it works perfectly.
Type checking does work as expected so it will error when needed, but just no autocomplete

## To Reproduce

```typescript
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

export const resources = {
  en: {
    translation: {
      'Welcome to React': 'Welcome to React and react-i18next',
    },
    ns2: {
      HELLO: 'WORLD',
    },
  },
  fr: {
    translation: {
      'Welcome to React': 'Bienvenue à React et react-i18next',
    },
    ns2: {
      HELLO: 'WORLD',
    },
  },
};

export const defaultNS = 'translation';

i18n
  .use(initReactI18next) // bind react-i18next to the instance
  .init({
    fallbackLng: 'en',
    debug: true,
    interpolation: {
      escapeValue: false,
    },
    resources,
    defaultNS,
  });

i18n.t('TYPECHECKING WORKS!');
i18n.t('AUTOCOMPLETE FOR NS IS WORKING ->', { ns: 'translation' });
i18n.t(['AUTOCOMPETE WORKS HERE']);

i18n.t('NO AUTOCOMPLETE ON TS 5.1.3!!!!');
export default i18n;
``` 

```typescript
import { resources, defaultNS } from '.';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: typeof defaultNS;
    resources: typeof resources['en'];
  }
}
```
![image](https://github.com/i18next/i18next/assets/59604278/609b026d-0635-45af-ab55-5fb9e767e529)
![image](https://github.com/i18next/i18next/assets/59604278/f8183ec6-bdc0-4e53-a843-34a93ef2b1ab)

## Expected behavior

Should have autocomplete working with or without an array

## Your Environment

- *runtime version*: node v20
- *i18next version*: 23.2.6
- *os*: Windows
- typescript: 5.1.3
- react-i18next version: 13.0.1

Thanks,
Nitzan

**Comment by adrai** [comment]
https://github.com/microsoft/TypeScript/issues/54708
https://github.com/i18next/i18next/issues/1956#issuecomment-1595258734
https://github.com/microsoft/TypeScript/issues/54710

**Comment by nizans** [comment]
Look like upgrading TS to 5.1.6 fixes this issue.

@adrai thanks for the response!
