### ISSUE TITLE
i18next is not detecting the correct plural forms for Ukrainian language

### ISSUE THREAD

**Issue by Demianeen** [i18next/i18next#1995]
## 🐛 Bug Report
i18next is not detecting the correct plural forms (two, few, many) for the Ukrainian language.

## To Reproduce

I did a small reproduction, where the same code work with Russian language, but not with Ukrainian (despite they working in the same way): [Codesandbox](https://codesandbox.io/s/react-fiddle-forked-yc7cv7?file=/src/App.js)

But basically, it looks like this: 

```js
// russian
console.log(i18n.t('views', { count: 0 })); // views_zero
console.log(i18n.t('views', { count: 1 })); // views_one
console.log(i18n.t('views', { count: 2 })); // views_few
console.log(i18n.t('views', { count: 3 })); // views_many
console.log(i18n.t('views', { count: 5 })); // views_many
```

```js
// ukrainian
console.log(i18n.t('views', { count: 0 })); // views_zero
console.log(i18n.t('views', { count: 1 })); // views_one
console.log(i18n.t('views', { count: 2 })); // views_other
console.log(i18n.t('views', { count: 3 })); // views_other
console.log(i18n.t('views', { count: 5 })); // views_other
```

## Expected behavior

i18next should detect the correct plural form for the Ukrainian language and use the appropriate translation key based on the value of count. For example:

```js
console.log(i18n.t('views', { count: 0 })); // zero
console.log(i18n.t('views', { count: 1 })); // one
console.log(i18n.t('views', { count: 2 })); // two
console.log(i18n.t('views', { count: 3 })); // few
console.log(i18n.t('views', { count: 5 })); // many
```

## Your Environment

- *Chrome Version* 114.0.5735.198 (Official Build) (arm64)
- *i18next version*: 23.2.8
- *os*: Max M1
- *i18next-browser-languagedetector*: 7.1.0
- *i18next-http-backend*: 2.2.1
- *react-i18next*: 13.0.1
- *react*: 18.2

**Comment by adrai** [comment]
the official language code for Ukrainian is uk => https://www.unicode.org/cldr/charts/42/supplemental/language_plural_rules.html

<img width="1433" alt="image" src="https://github.com/i18next/i18next/assets/1086194/c9f63264-b349-4bdb-b03e-47f0716262ea">


https://codesandbox.io/s/react-fiddle-forked-4wy72t?file=/src/App.js

**Comment by andreqko69** [comment]
Same issue with `"i18next": "^23.10.0"`

<img width="397" alt="image" src="https://github.com/i18next/i18next/assets/54131690/b9ce8223-7b34-4369-bbc8-88f5779fa1a2">
