### ISSUE TITLE
Not able to params using 18n.changeLanguage in next 13 with app directory

### ISSUE THREAD

**Issue by HemaliSavaliya93** [i18next/i18next#1998]
## To Reproduce
I was trying to add localization in next13 with app directory by referring this example :- https://github.com/i18next/next-13-app-dir-i18next-example/

but not able to change language params in url 

I tried below code to changeLanguage

I referred this example :-  https://github.com/i18next/next-13-app-dir-i18next-example/

```
use client'

import Link from 'next/link'
import { useTranslation } from '../../i18n/client'
import { Header } from '../components/Header'
import { Footer } from '../components/Footer/client'
import i18next from 'i18next'
export default function Page({ params: { lng } }) {
  const { t } = useTranslation(lng, 'second-client-page')
  return (
    <>
      <main>
        <Header heading={t('h1')} />
          <button onClick={() => {i18next.changeLanguage('de'),(lng)=>{
            lng= 'de'
          }}} type="button">Change lang
          </button>
        <Link href={`/${lng}`}>
            {t('back-to-home')}
        </Link>
      </main>
      <Footer lng={lng} path="/second-client-page" />
    </>
  )
}```

## Expected behavior

It should change the url with localhost:3000/de/second-client-page
even I tried by taking i18n instance from useTranslation
```
use client'

import Link from 'next/link'
import { useTranslation } from '../../i18n/client'
import { Header } from '../components/Header'
import { Footer } from '../components/Footer/client'
export default function Page({ params: { lng } }) {
  const { t, i18n } = useTranslation(lng, 'second-client-page')
  return (
    <>
      <main>
        <Header heading={t('h1')} />
          <button onClick={() => {i18n.changeLanguage('de')}} type="button">Change lang
          </button>
        <Link href={`/${lng}`}>
            {t('back-to-home')}
        </Link>
      </main>
      <Footer lng={lng} path="/second-client-page" />
    </>
  )
}
```

- *runtime version*: i.e. node v18,
- *i18next version*: i.e. 23.2.7
- *Next*: 13.4.8

**Comment by adrai** [comment]
the changeLanguage function has no idea about routing... also in a Nwxt.js environment (server side first) it is recommended to change language by changing route by link or router/history push

**Comment by HemaliSavaliya93** [comment]
I am not talking about routing to particular route, My concern is only changing params of language while change translation language which was working in next 13, can you please help me on this?

**Comment by adrai** [comment]
Like said, changeLanguage would just work on client side parts.
Beside that, use the i18n instance returned by useTranslation.
If you still think that's an issue, ask on Stackoverflow or create a minimal reproducible example and open an issue in the correct github repo.
