### ISSUE TITLE
Joi Validation

### ISSUE THREAD

**Issue by KathishKumaranR** [i18next/i18next#2003]
### Discussed in https://github.com/i18next/i18next/discussions/2002

<div type='discussions-op-text'>

<sup>Originally posted by **KathishKumaranR** July 24, 2023</sup>
How to implement this package in Joi Validation, I have tried this but not working? so how to do this?</div>

**Comment by adrai** [comment]
ask at the joi repo or stackoverflow... but probably you need to pass in custom messages...
and instead of hardcoding the messages, you can pass in the i18next.t('mykey') result...

fyi: https://stackoverflow.com/questions/48720942/node-js-joi-how-to-display-a-custom-error-messages
