### ISSUE TITLE
Types not working with custom keySeparator

### ISSUE THREAD

**Issue by alexander7161** [i18next/i18next#2005]
## 🐛 Bug Report

I'm using a custom keySeparator of `::`, the `t` function always returns never.

## To Reproduce

https://codesandbox.io/p/sandbox/tender-bash-kpctk8

![image](https://github.com/i18next/i18next/assets/9217537/c32166e8-982f-44ae-b8c9-dbf91adec7c0)

I'll admit I have a slightly non-standard use case:

I am using `::` as my keySeparator, and have `nsSeparator` disabled. The return type of TFunction is always `never`.

But I still get a type error if they key does not exist.

## Expected behavior

The return type of TFunction is defined by the `en.json` file and behaves the same with a custom `keySeparator`. 

## Your Environment

- node v18.16.0
- *i18next version*: 23.3.0
- *os*: Mac

**Comment by adrai** [comment]
if the key does not exist, there should be an error

**Comment by pedrodurek** [comment]
Hey @alexander7161, if the key doesn't exit you need to declare a `defaultValue`.
Like this: `t("not-existing::key", 'xxx')`
or like this `t("not-existing::key", {defaultValue: 'xxx'})`

**Comment by alexander7161** [comment]
Sorry, the issue is not the error that the key doesn't exist.

![image](https://github.com/i18next/i18next/assets/9217537/af874ad5-50b9-474d-b0a4-846e234b28ae)

The issue is the type of `t` when I hover is `never` (see screenshot)

**Comment by pedrodurek** [comment]
That's a bug, I'll put a PR up to fix that

**Comment by pedrodurek** [comment]
Hey @alexander7161, sorry, actually it's behaving as expected and inferring the type as `unknown` if you pass a default value.

**Comment by pedrodurek** [comment]
It's `unknown` because we can't determine the return type based on the key, but you can narrow it down using the following approaches:

```tsx
const txt: string = t('example::deeply::nested::key::value', 'Fallback text (max {{maxLength}} characters)', { maxLength: MAX_LENGTH })}
``` 

or if you're passing the result as props to a component/function, this should work:

```tsx
type Props = {
  title: string;
}

function Component({title}: Props) {
}

function MainComponent() {
  ...
  <Component title={t('example::deeply::nested::key::value', 'Fallback text (max {{maxLength}} characters)', { maxLength: MAX_LENGTH })}} />
}

```
Let me know if that helps, if it doesn't could you share an example where it doesn't?

**Comment by alexander7161** [comment]
I see, the places where it doesn't work my component has props:
```typescript
type Props = {
  title?: string;
}
```
(string is optional)

Is it expected that the type becomes `unknown` with a `defaultValue`? I guess using `defaultValue` as a fallback is not an intended use case?

**Comment by pedrodurek** [comment]
Hey @alexander7161,
Yes, it's expected to return `unknown` with `defaultValue`, I tested here and it works as expected: https://codesandbox.io/p/sandbox/tender-robinson-lpn9vc?file=%2Fsrc%2FApp.tsx%3A6%2C17
