### ISSUE TITLE
Load language in multiples files

### ISSUE THREAD

**Issue by CodersBrothers** [i18next/i18next#201]
Hi, i have the next schema of folders:

```
-js (General js and libraries)
-css
-modules (My modules)
   - module1
       - locales (The locales for i18next)
       - images
       - views (Some partials in html)
   -...
   - module99
```

I want load each module, and each module have a file of language for this module.

In each module i started the i18next like:

``` javascript
var config = {
            resGetPath: srcLang,
            //preload: [config.user.lang],
            useCookie: true,
            //fallbackLng: config.user.lang,
            detectLngFromHeaders: false,
            debug: true,
            useLocalStorage: true
        };
        i18n.init(config, callback);
```

But always load the same language, only the first.
How i can do?

**Comment by RoseAsbenhe** [comment]
Oh, I am so sorry - there was indeed a comma too much.
I never thought that the JSON file could be invalid since it has always worked when required via javascript.

Everything is working now, thank you!
