### ISSUE TITLE
Stopped working with Next.js v13.4.10 / You are passing a wrong module! Please check the object you are passing to i18next.use()

### ISSUE THREAD

**Issue by xairoo** [i18next/i18next#2013]
## 🐛 Bug Report

I use `i18next` with [next-i18next-static-site](https://github.com/xairoo/next-i18next-static-site) to create Next.js SSG exports.
But it suddenly stopped working when I updated to the latest Next.js version.
It works while in dev mode without problems, but building will fail.

Finally I updated all dependencies one by one to narrow it down and it stopped working with `next` v13.4.10, it still works fine with v13.4.9.

_I have really no idea if this is because of Next.js or i18next, so please forgive me if I have chosen the wrong repo to post into._
I have seen that there were already problems with `i18next.use()`, but I wasn't able to get rid of this error with the notes in the issues, anyway, that's why I thought it would be good to post it in the i18next repo.

## To Reproduce

I have created two branches to test it, it's a turbo monorepo, the only difference between the two branches is the Next.js version:
- v13.4.9 / works / [live preview @ Cloudflare](https://2cfdbdf2.next-i18next-static-site.pages.dev/)  
  https://github.com/xairoo/next-i18next-static-site/tree/dev-next-v13.4.9

- v13.4.10 / fails / [live preview @ Cloudflare](https://ce6c442c.next-i18next-static-site.pages.dev/)  
  https://github.com/xairoo/next-i18next-static-site/tree/dev-next-v13.4.10

While in `/` run `npm ci` and then you can go to `examples/web` and run `npm run export && npm run serve`.
`npm run dev` just works, also the export doesn't produce an error, only when you access the page.

This error will appear in the browsers console:
```js
Error: You are passing a wrong module! Please check the object you are passing to i18next.use()
```

**Comment by adrai** [comment]
I just tested with this example and the updated next dep: https://github.com/i18next/next-i18next/commit/46791536d5c786bd879a95dc6de3b6b2d88af061#diff-7cf7543712d9b4c99e527beca377e7907fb0ba9f13e0c85839e6ddb07f5a1140
And it seems to work, so I assume there is an issue with [next-i18next-static-site](https://github.com/xairoo/next-i18next-static-site) itself... sorry, but I'm not familiar with next-i18next-static-site

**Comment by xairoo** [comment]
Yeah of course and thanks for testing! I just created this small ~200 lines package because I wanted hot reload for the translation files while in dev.

Anyway, _I solved it but I have no idea why_.
While playing around I added `console.log(initReactI18next);` before calling `i18next.use()` and it worked.

Instead of printing it, I can also use run this _twice_ `plugins.map((plugin) => i18next.use(plugin));`

```js
const createI18nextInstance = (locales, language) => {
  const plugins = [
    initReactI18next,
  ];

  plugins.map((plugin: Module) => i18next.use(plugin)); // Or console.log(initReactI18next);
  plugins.map((plugin: Module) => i18next.use(plugin));

  i18next.init({
    resources: locales,
    cleanCode: true,
    lng: language,
    supportedLngs: config.languages,
    fallbackLng: language ? language : config.defaultLanguage,
    ns: config.namespaces, // String or array of namespaces to load
    defaultNS: config.defaultNamespace, // Default namespace used if not passed to translation function
    interpolation: {
      escapeValue: false, // Not needed for react as it escapes by default
    },
    react: {
      useSuspense: false, // Not compatible with SSR
    },
    load: "languageOnly", // Remove if you want to use localization (en-US, en-GB)
  });

  return i18next;
};
```

Any ideas why this works? I really have no idea and it feels totally wrong.

**Comment by adrai** [comment]
really strange... maybe turbo is doing something strange there...
You may ask the Vercel/Next.js team

**Comment by xairoo** [comment]
Perhaps the Next.js builder is doing crazy things.
I have added a comment in the Next.js issue linked above, maybe it's interesting for you.
Cheers from Pfäffikon SZ 😀
