### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by gouych** [i18next/i18next#2015]
## 🐛 Bug Report
I installed react-i18next, i18next in package.json
when I execute npm run build: vite build && tsc src/index.ts --jsx react-jsx --declaration --emitDeclarationOnly --esModuleInterop --moduleResolution node --target ES2019 --outDir dist
it always fails to compile：

<img width="833" alt="image" src="https://github.com/i18next/i18next/assets/43327905/a4894ad1-2e2d-4102-affb-0ec389b471b9">

**Comment by ramirezmz** [comment]
I have the same error when I try to compile the app applied i18next..., I found a solution by moving the index.d.ts (node_modules/i18next/index.d.ts) to the dist folder, but it is not the best way to go

@gouych 

https://stackoverflow.com/questions/74565837/i18next-module-does-not-compile-within-react-typescript-application

**Comment by gouych** [comment]
@ramirezmz 
Thank you. I resolved the compilation error in the project using the following method
import { useTranslation } from 'react-i18next/dist/es';

**Comment by gouych** [comment]
@ramirezmz 
Thank you. I resolved the compilation error in the project using the following method
import { useTranslation } from 'react-i18next/dist/es';
