### ISSUE TITLE
Attribute Translation Broken in 23.4.4

### ISSUE THREAD

**Issue by kittonian** [i18next/i18next#2021]
## 🐛 Bug Report

When using `data-i18n="[placeholder]MY.KEY"`, which should convert on load to `placeholder="Key translation"`, it does not change at all, using only the js version of i18next (i.e. not React, Node, JQuery, etc.).

In my html I can write:

`<p data-i18n="MYKEY"></p>`

and it translates perfectly, so I'm not sure what I'm doing wrong or if there is an issue with the latest i18next revision.

## To Reproduce

Here's my init script:

```
<script src="/i18next/i18next.js"></script>
    <script src="/i18next/i18nextHttpBackend.js"></script>
    <script src="/i18next/i18nextBrowserLanguageDetector.js"></script>
    
    <script>
      i18next
        .use(i18nextHttpBackend)
        .use(i18nextBrowserLanguageDetector)
        .init(
            {
                fallbackLng: 'en',
                backend: {
                    loadPath: 'https://www.example.com/localization/{{lng}}_json',
                }
            }
        )
        .then(() => {
            document.body.querySelectorAll('[data-i18n]').forEach(element => {
                element.innerHTML = i18next.t(element.getAttribute('data-i18n'));
            });
        });
    </script>
```

I am using json files to write the translations like this:

```
{
    "contact": {
        "CONTACT_FORM_NAME_LABEL": "NAME",
        "CONTACT_FORM_NAME_PLACEHOLDER": "Enter your name"
    }
}
```

So my actual html for the input field is:

   ` <input type="text" data-i18n="[placeholder]contact.CONTACT_FORM_NAME_PLACEHOLDER">`

## Expected behavior

I expected that when the page loads, the input field will become
`<input type="text" placeholder="My translated placeholder text">`

**Comment by adrai** [comment]
i18next does not know anything about html or react, etc.... you always need the appropriate i18next library... so in your case you need jquery-i18next => [jquery-i18next](https://github.com/i18next/jquery-i18next) or [loc-i18next](https://github.com/mthh/loc-i18next)
Beside that, set the i18next init debug option to true and check the logs.

**Comment by kittonian** [comment]
Thank you for pointing that out. I have it all working properly now. Sorry for the bother.
