### ISSUE TITLE
how to add translation in website with storing selected language name in localstorage for the whole web page using dom

### ISSUE THREAD

**Issue by bsde1234** [i18next/i18next#2022]
I am trying to add i18next translation in my website. but the text is not getting translated when changing language selection. My code is below,

    document.addEventListener('DOMContentLoaded', () => {
      const languageSelect = document.getElementById('language-select');
      const storedLanguage = localStorage.getItem('languagePreference');

      if (storedLanguage) {
        languageSelect.value = storedLanguage;
      }

      i18next
        .use(i18nextHttpBackend)
        .use(i18nextBrowserLanguageDetector)
        .init({
          detection: {
            order: ['localStorage', 'navigator'],
            caches: ['localStorage'],
          },
          backend: {
            loadPath: ''
          },
          fallbackLng: 'en',
        })
        .then(() => {
          function translatePageContent() {
            const elementsToTranslate = document.querySelectorAll('p');
            elementsToTranslate.forEach(element => {
              const originalText = element.textContent.trim();
              const translatedText = i18next.t(originalText);
              element.textContent = translatedText;
            });
          }

          languageSelect.addEventListener('change', function () {
            const selectedLanguage = this.value;
            i18next.changeLanguage(selectedLanguage);
            localStorage.setItem('languagePreference', selectedLanguage);
          });

          // Translate the content on initial load
          i18next.changeLanguage(storedLanguage || 'en').then(() => {
            translatePageContent();
          });

          // Update the page content when the language changes
          i18next.on('languageChanged', () => {
            translatePageContent();
          });
        });
    });

    
    <select id="language-select">
      <option value="en">English</option>
      <option value="fr">French</option>
    </select>

    
    <p>Hello!</p>
    <p>Welcome to our website.</p>
    <p>Contact us for more information.</p>

    
    <script src="https://cdn.jsdelivr.net/npm/i18next@latest/dist/umd/i18next.min.js"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/i18next-http-backend@latest/umd/i18nextHttpBackend.min.js"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/i18next-browser-languagedetector@latest/umd/i18nextBrowserLanguageDetector.min.js"></script>

    

I tried to search for more codes but not found. I need to get a drop down list of all available translation language for i18next. Please give any assistance possible, Also what should I add in loadpath url?

**Comment by jamuhl** [comment]
with i18next you do not have to store locale in localStorage yourself...that's handled by the language-detector already: https://github.com/i18next/i18next-browser-languageDetector

using i18next with plain html I recommend using additionally: https://github.com/mthh/loc-i18next

backend load path...needs to point to your server endpoint hosting the translations...if not having a server at hand...use in code bundled resources: https://www.i18next.com/how-to/add-or-load-translations

set `debug: true` in the init options of i18next - it will help you finding any issues with your setup...

the extended example on i18next documentation found here https://www.i18next.com/overview/getting-started#extended-sample has all you tried: https://jsfiddle.net/jamuhl/ferfywyf/525/
