### ISSUE TITLE
i18next - Global default value

### ISSUE THREAD

**Issue by prajun7** [i18next/i18next#2024]
## 🚀 Feature Proposal

I'm using i18next (along with 'react-i18next') in a react-native project.

## Motivation

When the app initially loads I see a flash of the key value (e.g. home.title) before the translation file is loaded. As soon as the translations file loads this is replaced with the expected value.

I want to display nothing ('') in this case until the value loads.

I know I can set a default value on a per key basis like t('home.title', '') or t('home.title', { defaultValue: '' }) but this will be quite painful now 😄.

My question is - can I set a default value on a global level (perhaps in the init of i18n)?

This is the request from Stackoverflow by the user, [scgough](https://stackoverflow.com/users/674906/scgough)

I am also using the translation in a similar way, and I want to add a default fallback value while initializing the i18next.

**Comment by adrai** [comment]
Aren't you using Suspense?

**Comment by prajun7** [comment]
I might be doing it incorrectly but this is how I am using it,
```
  const [notificationMessage, setNotificationMessage] = useState<string>("");
  
    const onAdd = async () => {
    const success = await addItem(itemValues);
    if (success) {
      setIsAddModalOpen(false);
      setNotificationMessage(t("AddedItemSuccess"));
    }
  };
  
  ```
  
  Here I get this error, 
```
The argument of type 'DefaultTFuncReturn' is not assignable to the parameter of type 'SetStateAction<string>'.
  Type 'null' is not assignable to type 'SetStateAction<string>'
```

I understand why I am getting this error and there is some workaround, which works, like
```
      setNotificationMessage(t("AddedItemSuccess") as string);
```

Also, this works,
```
    const successMessage = t("AddedItemSuccess")
    const onAdd = async () => {
    const success = await addItem(itemValues);
    if (success) {
      setIsAddModalOpen(false);
      setNotificationMessage(successMessage);
    }
  };
```

So, I was just wondering if I can set a default value on a global level (perhaps in the init of i18n)?
So, that I don't have to use another variable or typecast it to string.

I might be wrong, please feel free to correct me.

**Comment by adrai** [comment]
Does it work if you set returnNull to false?

https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz

btw: which version of i18next are you using?

**Comment by prajun7** [comment]
I am using  `22.4.15`

**Comment by adrai** [comment]
Update your i18next dependency or set returnNull false in index.d.ts: https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz

**Comment by prajun7** [comment]
Got it. Thank you for the help.
