### ISSUE TITLE
Sunsetting built-in plural rules resolutions

### ISSUE THREAD

**Issue by Malien** [i18next/i18next#2026]
## 🚀 Feature Proposal

Can we deprecate / remove ability to use i18next in environments without `Intl.PluralRules` support? `Intl.PluralRules` can be easily polyfiled if desired. We should direct users towards such solutions, if they need it. Support for `Intl.PluralRules` is good as of now, as well as being supported in node/deno.

Removing fallback would allow us to remove [a whole bunch of logic](https://github.com/i18next/i18next/blob/9bfbc1c3c30317b8181ad4ec108266b38eb22178/src/PluralResolver.js) from the bundle, slimming it down significantly. Doing so should have significant impact on loading perf in most environments. 

This is a breaking change, and as such is better delayed until next major version bump.

**Comment by adrai** [comment]
if so, we would need to drop also support for all older format versions v1 - v3 => https://www.i18next.com/misc/json-format#i18next-json-v1
And i18next is still compatible for the original functionality:
https://github.com/i18next/i18next/blob/master/test/backward/v1.11.1.compat.js
https://github.com/i18next/i18next/blob/master/test/backward/pluralResolver.compat.js

**Comment by Malien** [comment]
I'm curious. Aren't those compatible with the `Intl` approach?

Like: 
`_one` -> `_1`
`_two` -> `_2`
`_few` -> `_3`
`_many` -> `_11`
`_other` -> `_100`

I'm fairly comfortable with CLDR plural forms (thank you [handy table](https://www.unicode.org/cldr/cldr-aux/charts/29/supplemental/language_plural_rules.html)), but don't know if the numbered ones differ.

_Also, wow. That is one hell of a compat test suite_

**Comment by adrai** [comment]
I assume, you're talking about v1-v2
v3: used the same index as used in gettext for plurals
https://www.i18next.com/misc/migration-guide#v2.x.x-to-v3.0.0
for v3 there's at least a converter: https://github.com/i18next/i18next-v4-format-converter
