### ISSUE TITLE
Unexpected behavior with `cimode` and `appendNamespaceToCIMode` when overriding `lng`

### ISSUE THREAD

**Issue by JulienZD** [i18next/i18next#2027]
## 🐛 Bug Report

When the language is set to `cimode` and the `appendNamespaceToCIMode` option is enabled, manually overriding the language via the `lng` option of the `t` function results in the key not being prefixed with the namespace.

The output *does* contain the translation key, not the configured translated value, indicating that `cimode` is still in effect.

The issue seems to be related to [this line in Translator.js](https://github.com/i18next/i18next/blob/907caeaf821976ffde47d2ff30ef1464045c2b6d/src/Translator.js#L114C5-L114C5).

## To Reproduce

[Codesandbox reproduction](https://codesandbox.io/s/i18next-cimode-bug-7qmshq?file=%2Fsrc%2Findex.js)

i18next options:
```js
i18n.init({
  ns: ['other'],
  lng: 'cimode',
  appendNamespaceToCIMode: true,
});
```

`locales/en/other.json`:
```json
{
  "myKey": "Some translated value"
}
```

## Expected behavior

The output of the translate function to always be prefixed with the namespace followed by the translation key when `appendNamespaceToCIMode` is enabled and the language at initialization is `cimode`.

```js
// Output: 'other:myKey'
i18n.t('myKey', { ns: 'other' }); 

// Output: 'myKey'
i18n.t('myKey', { ns: 'other', lng: 'en' });
```

## Your Environment

- *runtime version*: Node v18.16.1
- *i18next version*: i.e. 23.4.6
- *os*: Any

**Comment by JulienZD** [comment]
@adrai I don't think it really behaves as intended, because the output is still 'cimode'-like, even though a different language was specified. The output isn't actually the translation (e.g. "Hello world"), it's the key (e.g. "hello.world"). 

IMO the intended behaviour should be either:
1. The actual translation for the passed `lng`, because the language is no longer `cimode`
2. The key, prefixed with the namespace if `appendNamespaceToCIMode` is enabled
 
Perhaps an additional option could be added to always force the output to be 'cimode', even when a different language is specified via `t`.

I found a workaround for now by wrapping `t` in a function that always passes `lng: 'cimode'` to `t` if test mode is enabled. (Our only use case is `t(key, options)`, so this works for us)
```ts
const t = process.env.NODE_ENV === 'test' ? prepareTFunctionForTestMode(i18n.t) : i18n.t;

function prepareTFunctionForTestMode(t: TFunction) {
  const testModeTFunc = (key: string, options = {}) => {
    return t(key, { ...options, lng: 'cimode' });
  };

  return testModeTFunc as typeof t;
}
```

**Comment by JulienZD** [comment]
@adrai I think that may have broken it. It now tries to load translation files from the `cimode` directory as well, if `lng` is set to `'cimode'` in the `init()` options. See [this Codesandbox](https://codesandbox.io/s/i18next-cimode-preload-bug-84wrdx?file=%2Fsrc%2Fi18n.js)

**Comment by adrai** [comment]
next try ;-) v23.4.8

**Comment by JulienZD** [comment]
@adrai `v23.4.8` fixed the error 😄

Could it still (somewhat) be broken? My local tests had uncaught errors, because I had set `fallbackLng` to `'cimode'`. 
Apparently it tries to load resources from the fallback directory as well? (`<locales-dir>/cimode/*.json`). It didn't do that in `v23.4.6`. Here's a [Codesandbox](https://codesandbox.io/s/i18next-cimode-fallbacklng-preload-qw3d3d?file=%2Fsrc%2Fi18n.js) for v23.4.8 with the `fallbackLng` error when set to `'cimode'`. You'll see how it tries to load files from the `'cimode'` directory. 
(Simply setting `fallbacklng` to `false` fixes it, but I'm just wondering if it's still not completely right, as it didn't do this previously)

I'd still like to know if there's a possible way to always force the output to be `namespace:key` when the *initial* `lng` option is `'cimode'`, even when it gets overridden by the options of the translation function. In some of our usages of the translation function we can't guarantee that it has been configured with the correct language, so we manually pass the correct language in the options. However, for our tests we still want these to return the namespace and key, rather than the actual translation.

**Comment by adrai** [comment]
I see no reason why you would set fallbackLng to cimode, but v23.4.9 should address also that

**Comment by JulienZD** [comment]
@adrai Yeah, me neither. It got set accidentally, as I had set a `defaultLanguage` variable to `cimode` in test mode, and that got set as the `fallbackLng`.
