### ISSUE TITLE
Not calling post processor for nested values

### ISSUE THREAD

**Issue by atheck** [i18next/i18next#2030]
## 🐛 Bug Report

When using nested values, the post processor is not called.

## To Reproduce

```js
const MyPostProcessor = {
  type: "postProcessor",
  name: "myPostProcessor",
  process(value, key) {
    console.log(key);
    // Do something...
    return value;
  }
};
```

I initialize i18next with a default postProcessor:

```js
i18next
  .use(MyPostProcessor)
  .init({
    // ...
    postProcess: ["myPostProcessor"],
    // ...
  });
```

And I have a key with a nested value:

```json
"Key": "Using nested value $t(Nested)",
"Nested": "Nested Value",
```

For that nested value, the post processor is not called.

## Expected behavior

The post processor should be called with the nested value.

## Your Environment

- *runtime version*: node v18
- *i18next version*: 23.4.6
- *os*: Windows

**Comment by adrai** [comment]
post processing on nested values has been explicitly disabled in v2.0.10 (https://github.com/i18next/i18next/commit/41eb5fc3118ca5a4e5af101767346cf648411ddb) because of https://github.com/i18next/i18next/issues/479 by @jamuhl

**Comment by atheck** [comment]
Thank you for your reply @adrai. Ok, then I have to find another solution.
