### ISSUE TITLE
TS2691 error with VSCode

### ISSUE THREAD

**Issue by koji--** [i18next/i18next#2031]
## 🐛 Bug Report

<img width="1235" alt="スクリーンショット 2023-09-08 18 15 09" src="https://github.com/i18next/i18next/assets/639366/db780457-ed6f-4039-8b17-4587e49dfb87">

ts2691 error is output on VSCode.

https://github.com/i18next/i18next/commit/39783655c0eb28e12a333c5ae026e2ab611c11e6

I think it's probably due to this commit, but is this necessary?

## To Reproduce

Clone i18next and open it in VSCode.

## Expected behavior

no errors occur.

## Your Environment

- *runtime version*: node v20.5.1
- *i18next version*: 23.5.0
- *os*: Mac

**Comment by adrai** [comment]
I'm not seeing this error:
<img width="831" alt="image" src="https://github.com/i18next/i18next/assets/1086194/aa7adea7-b452-407e-b7c2-a760b924941e">

**Comment by koji--** [comment]
@adrai This error does not seem to occur if Deno extension is enabled.
The development of i18next doesn't seem to be based solely on the Deno environment, but is this okay?

**Comment by adrai** [comment]
> but is this okay

idk, I'm not a TS expert

**Comment by koji--** [comment]
I see. Then I won't mind:smile:
