### ISSUE TITLE
`fr-ca` not accepted as valid code, with no errors

### ISSUE THREAD

**Issue by ronny-lark** [i18next/i18next#2036]
## 🐛 Bug Report

I would like to use the same language codes for `i18n` and for `dayjs` so I use the ones supported by `dayjs` locale plugins to define my resource names. As such, I have 2 languages: `en` and `fr-ca` (lowercase, with hyphen).
Despite existing in `resources` and in `supportedLangs`, `i18n` seems to simply not allow `fr-ca`. Replacing `fr-ca` with `fr` works - but that's not our desired outcome, as we would like to have both `fr` and `fr-ca`.

Also works is adding `fr` to `supportedLangs` but as far as I understand the docs, it just means that we are not specifically recognizing `fr-ca` and instead falling back to `fr`.

## To Reproduce

In this example, assume the jsons are valid.
`retrieveSettings` returns local storage settings (contains the `language` as `en` or `fr-ca`).

```ts
import i18n, { LanguageDetectorModule } from 'i18next';
import { initReactI18next } from 'react-i18next';
import en from 'assets/locales/en/translation.json';
import fr_ca from 'assets/locales/fr-ca/translation.json';
import { retrieveSettings } from 'stores/settings/settings.utils';

const DEFAULT_LANGUAGE = 'en';
export const DEFAULT_NAMESPACE = 'translations';

export const resources = {
  en: {
    [DEFAULT_NAMESPACE]: en,
  },
  'fr-ca': {
    [DEFAULT_NAMESPACE]: fr_ca,
  },
} as const;

const LanguageDetector: LanguageDetectorModule = {
  type: 'languageDetector',
  detect: () => retrieveSettings().language,
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    supportedLngs: Object.keys(resources),
    fallbackLng: DEFAULT_LANGUAGE,
    ns: [DEFAULT_NAMESPACE],
    defaultNS: DEFAULT_NAMESPACE,
    partialBundledLanguages: true,
    load: 'currentOnly',
    lowerCaseLng: true,
    interpolation: {
      escapeValue: false,
    },
    nonExplicitSupportedLngs: true,
  });

export default i18n;
```

With this example, using the code `fr-ca` (for example, in local storage then reloading, or with `changeLanguage`), does not render French, and falls back to English.

## Expected behavior

I expect `fr-ca` to be recognized as normal. I could not find anywhere a list of accepted language codes that would work, or any instructions of how to add languages (other than `supportedLangs` which I already tried)

## Your Environment

- *runtime version*: All browsers
- *i18next version*: 23.4.6
- *os*: Mac, Mobile phones
- React 18.2
- i18n React 12.3

**Comment by adrai** [comment]
https://www.i18next.com/how-to/faq#how-should-the-language-codes-be-formatted

**Comment by adrai** [comment]
just remove the `nonExplicitSupportedLngs` option

**Comment by ronny-lark** [comment]
Thank you so much! This was incredibly hard to find, the `nonExplicitSupportedLngs` was simply present in my config and I did not understand what I did.

**Comment by StevenWang20230313** [comment]
> just remove the `nonExplicitSupportedLngs` option: https://codesandbox.io/s/eager-tom-58s827?file=/src/index.mjs

Hi adrai,

I have a question on it. In my react app, I don't have i18n.init. Just use i18n.changeLanguage. How set {nonExplicitSupportedLngs: true} to accept `fr-CA` language? Thanks

**Comment by adrai** [comment]
@StevenWang20230313 I don't know exactly what you mean... please create a reproducible example and describe exactly what you mean and maybe create also a new issue.

**Comment by StevenWang20230313** [comment]
> @StevenWang20230313 I don't know exactly what you mean... please create a reproducible example and describe exactly what you mean and maybe create also a new issue.

- Now, I use i18n initial below:
i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    //lng: 'en',
    nonExplicitSupportedLngs: true,
    fallbackLng: 'en-CA',
    debug: process.env.REACT_APP_STAGE === "dev",
    //supportedLngs: ["en-CA", "fr-CA", "de-DE", "zh-CN", "ja-JP", "es-MX"],

    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    }
  })

- My translation files:
public
   |
   --- locales
             |
             --- en-CA
             --- fr-CA
- In my react component, have a call
   i18n.changeLanguage(value). When the value = fr-CA, in browser console, I got the API call:  GET https://xxx.com/locales/fr/translation.json 403 (Forbidden). 
According to the folder structure, it should be `fr-CA` in URL, but now it is `fr`, so always get 403 error.

Thanks

**Comment by adrai** [comment]
https://github.com/i18next/i18next/issues/2163#issuecomment-2007722165

btw: you're just pasting code snippets... I need an example repository

**Comment by StevenWang20230313** [comment]
> [#2163 (comment)](https://github.com/i18next/i18next/issues/2163#issuecomment-2007722165)
> 
> btw: you're just pasting code snippets... I need an example repository

Thank very much! I will try it again. If I cannot solve it, I will create a repo for it and let you know. Thanks again.
