### ISSUE TITLE
Error bundled resources definition in Backend fallback example

### ISSUE THREAD

**Issue by Mweydert** [i18next/i18next#2039]
## Documentation issue

The example on how to implement a [Backend fallback with bundled resources](https://www.i18next.com/how-to/backend-fallback) contains an error.

It should be `translation` instead of `translations`:
```js
const bundledResources = {
  en: {
    translation: {
      key: 'value'
    }
  }
};
```

## Motivation

I spent some time figuring out why the example did not work on my project. Thought we can save this time for other coming to this example 😄

**Comment by adrai** [comment]
Yes, thank you.
It's fixed now.
