### ISSUE TITLE
fallbackLng param load multiple times the language

### ISSUE THREAD

**Issue by CodersBrothers** [i18next/i18next#204]
If i use fallbackLng with false load good, but if i use with some language like 'esES' make multiple loads. I think that i use correctly the callbacks... I maked a repository with my code like a bootstrap for see... maybe its my problem, but its very strange.

https://github.com/CodersBrothers/bootstrap-front

Im using require, there are a config file with config of i18next.

The system load modules (Parts of website) because is a WebAPP. Im need get all in parts for work happy.

In main.js there are tests. If you open console and run index.html

**Comment by Antarus66** [comment]
Thank you. ```load: 'current'``` and renaming all language files like ```en-US``` works for me.
