### ISSUE TITLE
Typescript Error: accessing array entry does not comply to key type

### ISSUE THREAD

**Issue by sreucherand** [i18next/i18next#2040]
## 🐛 Bug Report

According to what it says here: https://www.i18next.com/translation-function/objects-and-arrays, the following code should be valid in a react+typescript environment,

```tsx
const result1 = i18next.t('arrayJoin', { joinArrays: '+' });
// -> "line1+line2+line3"

const result2 = i18next.t('arrayJoinWithInterpolation', { myVar: 'interpolate', joinArrays: ' ' });
// -> "you can interpolate"

const result3 = i18next.t('arrayOfObjects.0.name');
// -> "tom"
```

but in reality, this:

```tsx
const result3 = i18next.t('arrayOfObjects.0.name');
```

returns a TS error:

```sh
src/App.tsx:12:29 - error TS2345: Argument of type '["arrayOfObjects.0.name"]' is not assignable to parameter of type '[key: "arrayJoin" | TemplateStringsArray | "arrayJoinWithInterpolation" | "arrayOfObjects" | "translation:arrayJoin" | "translation:arrayJoinWithInterpolation" | "translation:arrayOfObjects" | ("arrayJoin" | ... 5 more ... | "translation:arrayOfObjects")[], options?: (TOptionsBase & ... 1 more ... & InterpolationMap...'.
  Type '["arrayOfObjects.0.name"]' is not assignable to type '[key: "arrayJoin" | TemplateStringsArray | "arrayJoinWithInterpolation" | "arrayOfObjects" | "translation:arrayJoin" | "translation:arrayJoinWithInterpolation" | "translation:arrayOfObjects" | ("arrayJoin" | ... 5 more ... | "translation:arrayOfObjects")[], options?: (TOptionsBase & ... 1 more ... & InterpolationMap...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"arrayOfObjects.0.name"' is not assignable to type '"arrayJoin" | TemplateStringsArray | "arrayJoinWithInterpolation" | "arrayOfObjects" | "translation:arrayJoin" | "translation:arrayJoinWithInterpolation" | "translation:arrayOfObjects" | ("arrayJoin" | ... 5 more ... | "translation:arrayOfObjects")[]'. Did you mean '"arrayOfObjects"'?

12   const result3 = i18next.t('arrayOfObjects.0.name');
                               ~~~~~~~~~~~~~~~~~~~~~~~
```

## To Reproduce

https://github.com/sreucherand/react-i18next/tree/master/example/react-typescript/simple

```sh
yarn
yarn typechecks
```

**Comment by Gotos** [comment]
Running into the same issue. Was this issue confirmed already or is there still information missing I could try to provide?

**Comment by pedrodurek** [comment]
If your translations are placed within JSON files, currently, that's not possible due to a typescript limitation where we can extract the literal values of JSON files. https://github.com/microsoft/TypeScript/issues/32063
If you move your translations to a ts file using `as const`, it'll work.

**Comment by Gotos** [comment]
I'm actually using .d.ts files in the project I'm working on to define my resources like described in the [documentation on using i18next with TS](https://www.i18next.com/overview/typescript), so it shouldn't matter what format the actual translations are in, right? (In my case, that would be yaml, not json).

Should I provide an example for this, too? I just noticed that the setup in the example by @sreucherand is different from mine in that it doesn't use type augmentation, if I'm not mistaken.

**Comment by pedrodurek** [comment]
Hey @sreucherand, use `as const` in your translation variable to infer the most specific type. For example:
```ts
const translation = {
  key1: '',
  key2: ['a', 'b']
} as const
```

**Before:**
![Screenshot 2023-10-11 at 10 11 14 AM](https://github.com/i18next/i18next/assets/12190482/230aef68-1b3b-4b8f-a52e-fbc71b49fa1f)

**After:**
![Screenshot 2023-10-11 at 10 11 29 AM](https://github.com/i18next/i18next/assets/12190482/e27eac44-9ef4-48e6-9e44-d06582a4be7a)

**Comment by pedrodurek** [comment]
Alternatively, if you opt to continue using json files, you case use the `returnObject` option, and do something like:
```tsx
i18next.t('arrayOfObjects, {returnObjects: true})[0].name;
```

Here is an example: https://codesandbox.io/s/18n-basic-example-2-p3zp39?file=/src/App.tsx

**Comment by pedrodurek** [comment]
@Gotos, let me know if my comments help you ☝️

**Comment by sreucherand** [comment]
@pedrodurek I'm using "as const" [here](https://github.com/sreucherand/react-i18next/blob/master/example/react-typescript/simple/src/%40types/resources.ts#L5) but anyway, I put up a new example based on your code sandbox to illustrate my point: https://codesandbox.io/s/18n-basic-example-2-forked-7lgxrf?file=/src/App.tsx

See the error that come up:
![image](https://github.com/i18next/i18next/assets/4232218/207da986-256e-4edb-8365-335946d63253)

Seems like in a TS env, you're enable to use the syntax `array.index` as described in the documentation.

**Comment by Gotos** [comment]
> @Gotos, let me know if my comments help you ☝️

  Again, I'm using Type Augmentations/Interface Merging to define the type of the translations, plus I'm loading the actual translations at runtime. I don't see how the actual translation files would change the fact that the interface has an array defined that throws the type error in the `t` function. The interface for my translations is basically the same you got from the type inference you're demonstrating.

Either way: I think @sreucherand s example demonstrates the issue very well with a pretty small setup. Can you reproduce the issue with that example? I do believe my issue has the same root cause despite my setup being a little more complicated, so if it helps reproduce and fix the issue, I too would be super grateful :)

**Comment by Gotos** [comment]
Hey @pedrodurek, did you manage to reproduce the issue using @sreucherand s example? Or are you still missing some information I could try to help provide?
(No pressure tho. As much as I'd like to see this issue fixed, I am well aware that you might have a different priority. I just thought I'd check in to make sure if there's anything I could do to try to help with this. :slightly_smiling_face: )

**Comment by sreucherand** [comment]
Hi @pedrodurek, did you have the opportunity to look at this?

**Comment by Gotos** [comment]
Any updates on this, @pedrodurek? Did you manage to reproduce the bug? If there's any way to help get this bug fixed, I'd love to help - except for writing a fix myself, I unfortunately don't think I understand the type system enough to straight up provide a fix.

**Comment by adrai** [comment]
v23.7.14 should address this

**Comment by Gotos** [comment]
@sreucherand I do believe the issue you demonstrated in the sandbox is solved with v23.7.15 - could you verify if your actual use case is working now, too?

**Comment by sreucherand** [comment]
Yes it does solve my problem! Thank you so much!

**Comment by Gotos** [comment]
I'm glad to hear that! :)

**Comment by army-u8** [comment]
I also encountered the same problem @adrai @Gotos @sreucherand 
`  "i18next": "23.11.3",`
```json
{
    "403": "403 Forbidden \n You don’t have permission to access this page.",
    "500": "Looks like the server is taking too long to respond, this can be caused by either poor connectivity or an error with our servers. Please try again in a while.",
    "503": "Service temporarily unavailable.",
    "501": [
        "a",
        "b",
        "c"
    ]
}
```

<img width="484" alt="image" src="https://github.com/i18next/i18next/assets/106830983/f6e343ea-b3e6-4057-95ba-19a119afab9e">
<img width="502" alt="image" src="https://github.com/i18next/i18next/assets/106830983/d1b84673-f443-4d58-9b23-d4a7b237f0b8">

```js
i18n.d.ts
declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: typeof defaultNS;
    resources: (typeof resources)["en"];
  }
}
```

**Comment by gabrielyotoo** [comment]
I'm still facing this error in version 23.7.16
