### ISSUE TITLE
RangeError: Map maximum size exceeded

### ISSUE THREAD

**Issue by ruudandriessen** [i18next/i18next#2042]
## 💥 Regression Report

When upgrading from 23.3.0 to 23.5.1 a previous issue https://github.com/i18next/i18next/issues/2001 has re-appeared. My expectation is that either [23.4.0](https://github.com/i18next/i18next/releases/tag/v23.4.0)  or [23.4.1](https://github.com/i18next/i18next/releases/tag/v23.4.1) regressed the improvements made [here](https://github.com/i18next/i18next/pull/2004)

## Last working version

Worked up to version: 23.3.0

Stopped working in version: 23.5.1

## Expected behavior

No errors when compiling tsc.

## Your Environment

- *runtime version*: node v18.17.0
- *i18next version*: 23.5.1
- *os*: Mac

**Comment by pedrodurek** [comment]
@ruudandriessen, do you have a reproducible example?
