### ISSUE TITLE
TypeScript: ability to type TFunction such that namespace must be explicitly defined

### ISSUE THREAD

**Issue by juiceo** [i18next/i18next#2044]
## 🚀 Feature Proposal

We would like to be able to define the type of the `TFunction` such that it always requires the namespace to be explicitly defined - ideal behaviour would be like:

```tsx

const one = t('foo.bar'): ❌ 
const two = t('common:foo.bar'); ✅ 
const three = t('foo.bar',  { ns: "common" }); ✅ 
```

I think this could be achieved by supporting not passing any `defaultNS` to `CustomTypeOptions`, or in some other way being able to nullify it.

## Motivation

In our monorepo setup, we have the following types of namespaces:

- `common` for all strings which are shared between the different apps
- a separate namespace for each app, where we have all strings related to only that app

Each of the apps supports using both strings from the `common` namespace, as well as any strings that are defined for that app specifically. This results in the DevX for localization being quite clear - if you don't define any namespace, we use the default namespace for the context you are in:

```tsx
// packages/admin/i18next.d.ts

import common from 'resources/en/common.json';
import admin from 'resources/en/admin.json';

const resources = {
  en: {
    common,
    admin,
  }
} as const;

declare module 'i18next' {
	interface CustomTypeOptions {
		defaultNS: "admin";
		resources: typeof resources['en'];
	}
}

// packages/admin/some-file.ts

const one = t('foo.bar'); // Allowed, looks for string in admin resource bundle
const two = t('common:phrases.hello'); // Allowed, looks for string in common resource bundle
```

*However*, in our shared component library we would like to only allow using strings from the `common` namespace. We can define that with the existing `CustomTypeOptions`, but the syntax for accessing common strings becomes inconsistent with the other packages:

```tsx
// packages/common/i18next.d.ts

import common from 'resources/en/common.json';

const resources = {
  en: {
    common,
  }
} as const;

declare module 'i18next' {
	interface CustomTypeOptions {
		defaultNS: "common";
		resources: typeof resources['en'];
	}
}

//packages/common/some-file.ts

const one = t('common:phrases.hello') ❌  // <- This was perfectly fine under packages/admin, where multiple namespaces are defined 
const two = t('phrases.hello') ✅  // <- Allowed currently, but we would like to be more explicit about using common strings
const three = t('phrases.hello', { ns: "common" }) ✅  // <- Why is this allowed, but not common:phrases.hello ?
```

We would like to have the ability to specifically disallow strings without an explicit namespace specified, so that the DevX for using these common strings is consistent regardless of whether you are working within a specific package or in the common library. We also much prefer the `namespace:path.to.string` syntax over the `("path.to.string", { ns: "namespace" })` syntax, and I don't see a clear reason for not supporting both ways.

## Example

How this feature could work:

```tsx
// packages/common/i18next.d.ts

import common from 'resources/en/common.json';

const resources = {
  en: {
    common,
  }
} as const;

declare module 'i18next' {
	interface CustomTypeOptions {
		defaultNS: undefined; // Up for debate what would be the best way to nullify this
		resources: typeof resources['en'];
	}
}

//packages/common/some-file.ts

const one = t('common:phrases.hello')  ✅ 
const two = t('phrases.hello', { ns: "common" }) ✅ 
const three = t('phrases.hello') ❌   // <- Should be disallowed, as there is no default namespace
```

**Comment by adrai** [comment]
At runtime i18next always uses a defaultNS, so introducing this to TypeScript would not be consistent with JS.

**Comment by juiceo** [comment]
@adrai OK got it, appreciate the swift reply - I can rephrase the request as well.

Seems to me like the typing is inconsistent between a single-namespace TFunction and a multi-namespace TFunction. 

If there are two or more namespaces, both `t('namespace:path.to.string')` and `t('path.to.string', { ns: 'namespace' })` work nicely.

If there is only one namespace, `t('namespace:path.to.string')` breaks but `t('path.to.string', { ns: 'namespace' })` is still accepted.

Would it be possible to update the typing so that even with a single namespace, the `namespace:path.to.string` syntax works consistently?

**Comment by adrai** [comment]
There should be no difference between having only 1 namespace or multiple namespaces.
I just removed the second namespace in this example and it seems to work: https://github.com/i18next/i18next/tree/master/examples/typescript

Can you provide a reproducible example that shows your issue?

Beside that, `t('path.to.string', { ns: 'namespace' })` is preferred over `t('namespace:path.to.string')`

**Comment by juiceo** [comment]
Ah yes I see, it does work when using the `i18next.t` function directly. But it seems to break when passing around the `t` function as an argument to a utility function (although, not sure if this is an anti-pattern?):

```tsx
import i18next, { TFunction } from 'i18next';

const example = i18next.t("common:phrases.hello"); ✅ 

const getExample: (t: TFunction) => {
  return t('common:phrases.hello'); ❌  //  Type at position 0 in source is not compatible with type at position 0 in target.
}

const getExample: (t: TFunction) => {
  return t('phrases.hello', { ns: "common" }); ✅ 
}
```

Seems like the type of `i18next.t` is slightly different from `TFunction` in this case:

```tsx
i18next.t: TFunction<["common", ...never[]], undefined>
t: TFunction<"common", undefined>
```

Is `TFunction` the wrong argument type to be using for this sort of case?

**Comment by adrai** [comment]
Did you try to specify your functions like this? `t: TFunction<"common">`

**Comment by juiceo** [comment]
Yep, looks like it only works when passing in the namespace as an array - so:

```
t: TFunction<"common"> ❌ 
t: TFunction<["common"]> ✅ 
```

But would be great if the `TFunction` would just have the same type as `i18next.t` by default, without having to specify the namespace type argument separately

**Comment by juiceo** [comment]
Hey - I'll create another issue with the specific TS issue more clearly explained and reproduced, and close this one :)
