### ISSUE TITLE
postProcessor incorrect key when using `namespace:key` syntax in `t`

### ISSUE THREAD

**Issue by stepan662** [i18next/i18next#2049]
## 🐛 Bug Report

I'm maintaining a `postProcessor` plugin and an issue was raised in our repo, which is caused by the `key` argument containing the namespace even though it's been clearly already parsed from the key. Result is that our plugin works correctly when user does this:

t('key_name', {ns: 'namespace'})

But it breaks in this case:

t('namespace:key_name')

In the documentation these cases are described as equivalent, so I would expect the i18next to remove the namespace from the key argument in the plugin.

## To Reproduce

Create a custom post processor:

```
{
  type: 'postProcessor',
  name: 'nameOfProcessor',
  process: function(value, key, options, translator) {
    console.log(key.join('.'), options);
    return value;
  }
}
```

Use i18next with the plugin:

t('translation:key')

It logs out:

```
translation:this_is_a_key {lng: undefined, lngs: null, ns: 'translation', keyPrefix: undefined}
```

While `t('key_name', {ns: 'namespace'})` logs key without the namespace:

```
translation:this_is_a_key {lng: undefined, lngs: null, ns: 'translation', keyPrefix: undefined}
```

## Expected behavior

I think this shouldn't make a difference for the plugin, so the key should be stripped out of the namespace.

If this is not possible due to the change being a breaking change, I'd suggest to add the key in pure form to the options object, so we can use that instead of the one in the parameter.

## Your Environment

- *runtime version*: node18, chrome117
- *i18next version*: 23.5.1
- *os*: Mac

**Comment by jamuhl** [comment]
You can use `postProcessPassResolved` in i18next.init options to get a `i18nResolved` object in the options containing more details about the actually resolved value (usedKey, ...)

-> https://github.com/i18next/i18next/blob/master/src/Translator.js#L408

**Comment by stepan662** [comment]
Hmm, is this some unofficial option? I can't find this in the docs.

However, I feel like the plugin API should be shielded from these kind of things and updating the global configuration should not be a concern of the plugin, that should be a left to the user.

Or do you consider the namespace a part of the key? My understanding was that not, because it actually renders the correct key, so when accessing the cache, it loads the key already without the namespace name. It feels inconsistant.

**Comment by stepan662** [comment]
I encode the key into the translation itself in invisible characters, so later we can detect where are the translations in the dom. So the key is pretty important. I don't feel like parsing the namespace out of the key is the right way to write a plugin, as there is also some logic that it only parses the namespace out if the namespace actually exists, if I'm not mistaken. I don't want to get myself into that.

Rather I would advice our users to not to use `t('namespace:key')` but `t('key', { ns: 'namespace' })`, if anything.

**Comment by jamuhl** [comment]
You get the translator instance as 4th param -> you might use https://github.com/i18next/i18next/blob/master/src/Translator.js#L47 on that to get the key

**Comment by stepan662** [comment]
Ok, this seems to work fine. Thank you 🙂
