### ISSUE TITLE
Localized languages seem to always trigger an extra download of their root language

### ISSUE THREAD

**Issue by blordpluto** [i18next/i18next#2050]
## 🐛 Bug Report

When the library receives, for example `en-GB`, it seems to automatically generate a `languages` array with the root language as a fallback, like:

```javascript
['en-GB', 'en']
```

In our case, we are shipping full translations for every language variant. We have both 'en-GB' and 'en' dictionaries, but there is _never_ a scenario in which we want the client to download both.

Note that this is distinct from the "fallbackLng". For that we're doing something like:

```javascript
export const LOCALIZED_LNGS = ['en-gb', 'fr-ca']; // etc
export const LANGUAGE_CODES = ['de', 'en', 'es', 'fr', 'it']; // etc

// and inside the init:
    fallbackLng: (navigatorCode) => {
      // 1. Use the exact [language-country] code if available
      if (LOCALIZED_LNGS.find((ll) => ll === navigatorCode)) return [];

      // 2. Split code and look for the specific language if supported
      const navigatorLng = navigatorCode.split('-')[0];
      if (LANGUAGE_CODES.find((lc) => lc === navigatorLng)) return [];

      // 3. Add english as a fallback only if language was not found above
      return 'en';
    },
```

The problem with this is that for en-GB locales, both 'en-GB' and 'en' are downloaded on the wire. The dictionaries are fairly large, so this is a launch-time cost we a keen to avoid.

How do we turn the automatic addition of the base (non-localized) language to the array?

## Your Environment

- *runtime version*: node v18
- *i18next version*: 23.5.1
- *os*: Mac

**Comment by jamuhl** [comment]
see:

https://www.i18next.com/overview/configuration-options#languages-namespaces-resources 

fallbackLng -> false
load -> 'currentOnly'

but make sure you only set language to something you fully support (all translated)

**Comment by blordpluto** [comment]
@jamuhl Thanks, `currentOnly` definitely helps.

But it still doesn't seem to be possible to take full programmatic control. For example:

We have `en-GB` and `en` dictionaries, but not an `en-US` dictionary. For the following code...

```typescript
const fallbackLng = (navigatorCode: string) => {
  // 1. Use the exact [language-country] code if available
  let result = LOCALIZED_LNGS.find((ll) => ll === navigatorCode);
  if (result) return [result];

  // 2. Split code and look for the specific language if supported
  const navigatorLng = navigatorCode.split('-')[0];
  result = LANGUAGE_CODES.find((lc) => lc === navigatorLng);
  if (result) return [result];

  // 2a. Special case for Norway, where language codes may not match
  if (navigatorLng === 'nn') return ['nb'];

  // Use english if language was not found
  return ['en'];
};
```

... when a navigatorCode of `en-US` comes in, we get an output array of `['en-US', 'en']`. This "works" because we _do_ have an `en` dictionary, but it's a waste because the library is firing a network request for `en-US` that we know in advance is going to fail. It's unnecessary overhead, especially if it lags on the network, which we obviously can't control. Please advise? 🙏

**Comment by jamuhl** [comment]
https://www.i18next.com/overview/configuration-options#languages-namespaces-resources did you try `supportedLngs` option
