### ISSUE TITLE
Text content does not match server-rendered HTML.

### ISSUE THREAD

**Issue by bhaveshborgoankar** [i18next/i18next#2051]
## 🐛 Console Error

When we are changing languages we are getting console errors and also on refreshing the page, the error is occurring.

## This type of error is occurring 
![Screenshot from 2023-10-17 10-55-07](https://github.com/i18next/i18next/assets/92780650/789f1878-768d-49a2-b1fd-b6407feff9e2)

## Our Environment

- *Node Version*: v18.15.0
- *i18next version*: ^23.2.11
- *next*: ^13.5.2
- *react*: ^18.2.0
- *os*: Linux

**Comment by adrai** [comment]
Are you using next-i18next?
If so, use the useTranslation function of next-i18next and not of react-i18next.
Also provide a reproducible example repo.

**Comment by Kucerenko171** [comment]
@adrai Hey. But if I use custom `useTranslation` for client and server sides. 

From here: https://github.com/i18next/next-app-dir-i18next-example-ts/tree/main/app/i18n
This article: https://locize.com/blog/next-app-dir-i18n/

How can I avoid this problem?

**Comment by adrai** [comment]
The link you sent is for the Next.js app dir setup and not for the Next.js pages setup.
next-i18next is only for the pages setup.

**Comment by Kucerenko171** [comment]
Right, but I have the same problem

**Comment by adrai** [comment]
Then provide a minimal reproducible example repository

**Comment by Kucerenko171** [comment]
My problem:
`Unhandled Runtime Error
Error: Text content does not match server-rendered HTML.

Warning: Text content did not match. Server: "My Profile" Client: "Mi perfil"`

`profile/page.tsx`
`import { PublicUser } from "@/types";
import { getUser } from "@/utils/supabase/queries/auth";
import { createClient } from "@/utils/supabase/server";
import { ProfileCustomer } from "l/components/custom/profile-customer/ProfileCustomer";
import GoLoginProtection from "l/components/custom/protectedRoutes/GoLoginProtection";

export default async function ProfileCustomerPage() {
  const supabase = createClient();
  const { user } = await getUser(supabase);

  return (
    <GoLoginProtection>
      <ProfileCustomer user={user as PublicUser} />
    </GoLoginProtection>
  );
}
`
`ProfileCustomer.tsx`
`"use client";

import { useGetCurrentLng, useTranslation } from "@/app/i18n/client";
import { myProfileFormSchema } from "@/lib/validation/myProfileSchemas";
import { PublicUser } from "@/types";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "l/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormInput,
  FormItem,
  FormLabel,
  FormMessage,
} from "l/components/ui/form";
import { GoogleAutocomplete } from "l/components/ui/google-autocomplete";
import { PhoneInput } from "l/components/ui/phone-input";
import { UploadFile } from "l/components/ui/upload-file";
import Image from "next/image";
import { useEffect } from "react";
import { useForm } from "react-hook-form";

type ProfileCustomerProps = {
  user: PublicUser;
};

export function ProfileCustomer(props: ProfileCustomerProps) {
  const { user } = props;
  const lng = useGetCurrentLng();
  const { t } = useTranslation(lng, "profile-customer");

  const defaultImage =
    "https://i.insider.com/5c79a8cfeb3ce837863155f5?width=800&format=jpeg&auto=webp";

  const form = useForm({
    resolver: zodResolver(myProfileFormSchema),
    defaultValues: {
      firstName: "",
      lastName: "",
      phoneNumber: "",
      imageUrl: defaultImage,
      location: {
        country: "",
        city: "",
        zip: "",
      },
      rawLocation: "",
    },
  });

  useEffect(() => {
    if (user) {
      form.setValue("firstName", user.first_name as string);
      form.setValue("lastName", user.last_name as string);
      form.setValue("phoneNumber", user.phone_number as string);
    }
  }, [user]);

  return (
    <div className="container">
      <div className="flex flex-col gap-16 py-28">
        <h1 className="mx-2 text-center text-3xl font-semibold text-black xl:text-start">
          {t("title")}
        </h1>
        <div className="flex flex-col items-center justify-between gap-24 rounded-lg bg-background px-12 py-9 lg:gap-48 xl:flex-row xl:items-start xl:bg-white">
          <Form {...form}>
            <div className="flex w-fit flex-col items-center gap-5">
              <Image
                className="size-52 rounded-full"
                src="https://i.insider.com/5c79a8cfeb3ce837863155f5?width=800&format=jpeg&auto=webp"
                alt="avatar image"
                width={200}
                height={200}
              />
              <UploadFile />
            </div>
            <div className="flex flex-col gap-14 lg:flex-row">
              <div className="flex min-w-80 flex-col gap-7">
                <h2 className="font-medium text-black">{t("profile-info")}</h2>
                <div className="flex flex-col gap-5">
                  <FormInput
                    form={form}
                    name="firstName"
                    label={t("labels.first-name")}
                    inputProps={{
                      placeholder: t("placeholders.first-name"),
                      type: "input",
                      className: "rounded-lg",
                    }}
                  />
                  <FormInput
                    form={form}
                    name="lastName"
                    label={t("labels.last-name")}
                    inputProps={{
                      placeholder: t("placeholders.last-name"),
                      type: "input",
                      className: "rounded-lg",
                    }}
                  />
                  <FormField
                    control={form.control}
                    name="phoneNumber"
                    render={({ field }) => (
                      <>
                        <FormItem>
                          <FormLabel>{t("labels.phone-number")}</FormLabel>
                          <FormControl>
                            <PhoneInput
                              value={field.value}
                              onChange={(value) => field.onChange(value)}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      </>
                    )}
                  />
                </div>
              </div>
              <div className="flex min-w-80 flex-col gap-7">
                <h2 className="font-medium text-black">{t("address-info")}</h2>
                <div className="flex flex-col gap-5">
                  <GoogleAutocomplete
                    form={form}
                    name="rawLocation"
                    label="Location"
                    onPlaceSelect={(place: google.maps.places.PlaceResult) => {
                      const addressComponents = place.address_components || [];
                      let country = "",
                        city = "",
                        zip = "";

                      addressComponents.forEach((component) => {
                        const types = component.types;
                        if (types.includes("country")) {
                          country = component.long_name;
                        }
                        if (types.includes("locality")) {
                          city = component.long_name;
                        }
                        if (types.includes("postal_code")) {
                          zip = component.long_name;
                        }
                      });

                      form.setValue("location", { country, city, zip });
                      form.setValue(
                        "rawLocation",
                        place.formatted_address || ""
                      );
                    }}
                  />
                  <FormInput
                    form={form}
                    name="location.country"
                    label={t("labels.country")}
                    inputProps={{
                      type: "input",
                      className: "rounded-lg",
                      disabled: true,
                    }}
                  />
                  <FormInput
                    form={form}
                    name="location.city"
                    label={t("labels.city")}
                    inputProps={{
                      type: "input",
                      className: "rounded-lg",
                      disabled: true,
                    }}
                  />
                  <FormInput
                    form={form}
                    name="location.zip"
                    label={t("labels.zip-code")}
                    inputProps={{
                      type: "input",
                      className: "rounded-lg",
                      disabled: true,
                    }}
                  />
                </div>
                <Button
                  className="w-full self-end text-nowrap px-4 text-sm xl:max-w-28"
                  variant="success"
                >
                  {t("save-changes")}
                </Button>
              </div>
            </div>
          </Form>
        </div>
      </div>
    </div>
  );
}
`

**Comment by Kucerenko171** [comment]
What do I need to add?

**Comment by adrai** [comment]
Create a new repository on github with all minimal stuff there to be able to reproduce your issue.

https://minimum-reproduction.wtf/

**Comment by adrai** [comment]
I would fork this repository: https://github.com/i18next/next-app-dir-i18next-example-ts/ and then add your code until the issue is present...

**Comment by Kucerenko171** [comment]
@adrai I actually caught the problem.
It happens cause language can't be downloaded, that's why I have hydrating error.

This code helps me:
```
  const { t, ready } = useTranslation(lng, "main");

 useEffect(() => {
    if (ready) {
      setIsReady(true);
    }
  }, [ready]);

  if (!isReady) {
    return <div>Loading...</div>;
  }
```
But it looks weird. What could you suggest me?

**Comment by Kucerenko171** [comment]
How do you handle cases, when locale can't be loaded before hydration?

**Comment by adrai** [comment]
Never had such a case... so why the translations can't be loaded before hydration?

**Comment by Kucerenko171** [comment]
@adrai Can I have this problem, that I get `currentLng` like this:

For `server components`: 
```
import { cookies } from "next/headers";
export const getCurrentLng = () =>
  cookies().get(cookieName)?.value ?? fallbackLng;
```
  
For `client components`:
```
import { useCookies } from "react-cookie";
export const useGetCurrentLng = () => {
  const [cookies] = useCookies([cookieName]);

  return cookies.i18next;
};
```

**Comment by adrai** [comment]
this is probable yes

**Comment by Kucerenko171** [comment]
Okay. How should I get current language?

For `server component`:
get it from params

For `client component`:
Probably take it from `useParams` everywhere?

Am I right?

**Comment by adrai** [comment]
Like in this example: https://github.com/i18next/next-app-dir-i18next-example-ts/tree/main
you have it always in the url...
and you can also get it from the i18n instance then: i18n.resolvedLanguage
