### ISSUE TITLE
TFunc recommends invalid key when using underscore.

### ISSUE THREAD

**Issue by TomppaPackage** [i18next/i18next#2052]
## 🐛 Bug Report

When following the TypeScript setup guide on the [documentation](https://www.i18next.com/overview/typescript) and using underscores in translation keys, the expected types are broken.

`pages:test_with_underscore` in translations allows for the following;
```
pages:test_with_underscore
pages.testith_underscore
```

## To Reproduce

CodeSandbox example
https://codesandbox.io/s/zealous-babycat-lg9yjp?file=/src/App.tsx

## Expected behavior

I would expect an invalid key to throw a TypeError.

## Your Environment

- *runtime version*: Node 18, LTS
- *i18next version*: 23.5.1

**Comment by adrai** [comment]
try to set the contextSeparator option to a different character.

**Comment by TomppaPackage** [comment]
> https://codesandbox.io/s/zealous-babycat-lg9yjp?file=/src/App.tsx

No luck setting `contextSeparator` to `-` - TS still suggests keys with a `_` separator.

However, modifying the `translations.json` file to use `-` instead of `_` in the keys causes the types to be inferred correctly. 

Is this then a limitation of using `_` in translation files?

**Comment by marcalexiei** [comment]
@TomppaPackage you have to set `contextSeparator` also in `CustomTypeOptions` inside `i18n.d.ts`:

```ts
import { Dict } from "./i18n";

declare module "i18next" {
  interface CustomTypeOptions {
    resources: Dict;
    contextSeparator: "-";
  }
}
```

I updated your example and it seems to be working:
https://codesandbox.io/s/hopeful-river-nx9nwy?file=/src/App.tsx

<img width="1194" alt="Screenshot 2023-10-18 at 21 46 24" src="https://github.com/i18next/i18next/assets/24919330/2cd8743c-da81-404c-bab9-eacb65527e4c">

**Comment by TomppaPackage** [comment]
> @TomppaPackage you have to set `contextSeparator` also in `CustomTypeOptions` inside `i18n.d.ts`:
> 
> ```ts
> import { Dict } from "./i18n";
> 
> declare module "i18next" {
>   interface CustomTypeOptions {
>     resources: Dict;
>     contextSeparator: "-";
>   }
> }
> ```
> 
> I updated your example and it seems to be working: https://codesandbox.io/s/hopeful-river-nx9nwy?file=/src/App.tsx
> 
> <img alt="Screenshot 2023-10-18 at 21 46 24" width="1194" src="https://user-images.githubusercontent.com/24919330/276381638-2cd8743c-da81-404c-bab9-eacb65527e4c.png">

Yeah, that works.

```
import { Dict } from "./i18n";

declare module "i18next" {
  interface CustomTypeOptions {
    resources: Dict;
    contextSeparator: "_";
  }
}
```

This results in the correct behaviour when using `_` as a separator as well.

**Comment by predragnikolic** [comment]
Hello,

> try to set the contextSeparator option to a different character.

This looks like a workaround not a fix.
Can we reopen this ticket until a fix for this is found?

I do not think that the current default behavior is ok. 
In the screenshot you can see that I get `"homeage"`, but it should be `home_page`.

![Screenshot from 2023-11-22 20-35-40](https://github.com/i18next/i18next/assets/22029477/5ce043c4-e2b3-4b9f-ade5-2cb422610bde)

It would be much better if no one modified the d.ts file in order to workaround the issue, 
the i18next lib should maybe better handle the `_` in type inference?
