### ISSUE TITLE
Some questions about JSON Format

### ISSUE THREAD

**Issue by xuliuzhu1834** [i18next/i18next#2057]
💬 Questions / Help
----

Some questions about JSON Format 

My current resource's JSON format looks like this:

```json
"en": {
    "translation": {
        "hello": {
            "value": "Hello World",
            "nid": "123"
        }
    }
}
```
I hope that `i18next.t("hello")` returns `hello.value` by default, which is `"Hello World"`, and that `hello.nid` is recorded as additional information, such as stored in `localstorage`, but it is not displayed on the page.

How can I handle this kind of situation?

I have been reading the documentation for a long time, but still haven't found a solution. I hope to get help. Thank you very much! 🙏

**Comment by adrai** [comment]
To get the object value of the hello key, you need to pass `returnObjects: true` (https://www.i18next.com/translation-function/objects-and-arrays)

`i18next.t("hello", { returnObjects: true }) // returns { value: 'Hello World', nid: '123' }`

To get directly the nested values, you can simply do this (https://www.i18next.com/translation-function/essentials):

```
i18next.t("hello.value") // returns 'Hello World'
i18next.t("hello.nid") // returns '123
```'

**Comment by xuliuzhu1834** [comment]
My confusion is that I want to achieve that i18next.t("hello") directly returns 'Hello World', instead of i18next.t("hello.value"). I tried to use plugins to retrieve {value: "Hello World", nid: "123"}, but it didn't work. The plugin returned value or nid, not the whole object.🤔

**Comment by adrai** [comment]
What you expect is not how i18next works.

**Comment by xuliuzhu1834** [comment]
I'm trying to see if I can solve this problem using a plugin. Here are some attempts I made:

```js
const postProcessor = {
  type: 'postProcessor',
  name: 'reportPostProcessor',
  process: function(result, key, options, translator) {
    localStorage.setItem(result.nid, result.value)
    return result.value;
  },
  overloadTranslationOptionHandler(args) {
    return {
      postProcess: 'reportPostProcessor'
    }
  }
};

i18next.use(postProcessor).init({
  postProcess: ['reportPostProcessor'],
  lng: 'en',
  interpolation: {
    alwaysFormat: true,
    format: function(result, format, lng) {
      return result.value
    },
  },
  resources: {
    en: {
      translation: {
        "hello": {
          value: "Hello World",
          nid: "123"
        }
      }
    },
  }
});
```

However, the `format` function is not triggered 😢.

**Comment by adrai** [comment]
Why you don't just convert your resources json, before you pass it to i18next to be transformed like this?

from:
```
      {
        "hello": {
          value: "Hello World",
          nid: "123"
        }
      }
```
to:
```
      {
        "hello": "Hello World"
      }
```

btw: the format function is used for interpolated values, not for json manipulation:
https://www.i18next.com/translation-function/interpolation
https://www.i18next.com/translation-function/formatting

**Comment by xuliuzhu1834** [comment]
Thank you very much for your answer. I will try to use the recommended JSON solution directly and see if there are any other ways to get the corresponding nid. Thank you again!
