### ISSUE TITLE
Context Typing is slightly too strict

### ISSUE THREAD

**Issue by SimeonC** [i18next/i18next#2059]
## To Reproduce

See this [Typescript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBMAjADgHYFMAe8BmUIhwBESaWMRA3AFDUAm6AxgDYCGU6cIEdArs5xIoM2InADe1OAlQx0UHK0acAwrwDOMAgBUAnmHQB5MDGARU6iVOlwO6iLyjL1ALis2b69DFOoA5q7uHjZKpuaBksHBwKgAbqzMwHQA+o7MbkQAknEJSXAAqgBKADJU1lHSJDmJKWkAfmD4WowQzEQZAIIFJXDqABYOzHS9MOzwAO7AMH1lFXAAvjRRi+ULSzYtsuQAyuhg7KxaUBl1swvU87Q4vKiMYahwhYgAFOJwm3LYC25vH+QA-G5NFAYn4FgBKIKkEQwAB0MGeRC8PlBrlCZgssJi8RqqSgbXB62h5HhiORvgCLnR4Sx1SSeLaABoJO9zJ94PNCRdqNdbvdHgAmV6srZfeY-EXsoEwEH+CFQ4QkhFI7wUtF3DHqWk4+lpIhc6TE7CklUo-zq+5a7G5Wr4ojM35s8gQmiXIA)
Or this [CodeSandbox](https://codesandbox.io/s/elegant-frost-g7czz5?file=/src/index.ts)

The second `context` is typed as `context: string` but throws an error. Changing the type to `string|undefined` works around the error.

## Expected behavior

No typescript errors and context can be typed as a non nullable string.

## Your Environment

- *runtime version*: node 20.8.0
- *i18next version*: 23.6.0
- *os*: Mac

**Comment by adrai** [comment]
Feel free to provide a PR to address this.

**Comment by kuzvac** [comment]
@adrai can you suggest how to type context, if value for context came from api and have string type? 
If i write one of context value from translation it works, but if assign value from api, it show error:
>  Type at position 1 in source is not compatible with type at position 1 in target.
      Type '{ context: string; }' is not assignable to type 'string'.

Also if use ``t(`key_${item.id}` as const)`` it show:

> Argument of type '[`key_${string}`]' is not assignable to parameter of type

**Comment by adrai** [comment]
If it comes from api this means it is dynamic, so having types does not make sense, unless you map the dynamic value with a local hardcoded string...
@pedrodurek do you have another idea?

**Comment by kuzvac** [comment]
Thanks @adrai, mapping to `as unknown` looks like as _solution_, so `t('key', { context: item.id as unknown })` and it works and not trigger any error.

**Comment by BastLast** [comment]
Hi ! I'm facing the exact same issue, i cannot understand this
