### ISSUE TITLE
"push" isn't recognized as valid type with resources.d.ts

### ISSUE THREAD

**Issue by Opus26** [i18next/i18next#2060]
## 🐛 Bug Report

The key "push" might not be recognized as a valid type when working with i18n.service.d.ts in conjunction with NextJS-i18n.

## To Reproduce

Follow this tuto: https://www.i18next.com/overview/typescript

1. Create `example.json`:
```json
{
    "workingExample": {
        "pushNotification": "<--- ok"
    },
    "notWorkingExample": {
        "push": "<--- not ok"
    }
}
```
2. Add this line to `package.json`: 
```json
"i18n-init": "i18next-resources-for-ts interface -i ./i18n/locales/en -o ./@types/resources.d.ts && prettier --write ./@types/resources.d.ts"
```
3. Run this script to generate `@types/resources.d.ts`:
```js
yarn i18n-init
```
**@types/resources.d.ts generated**
![image](https://github.com/i18next/i18next/assets/71282839/28c37b1b-0a65-417b-acc8-42e8d326b1dc)

4. Type `t` from `I18nService`:
```js
  private readonly t: I18nService<Resources>['t'] = (
    key: PathImpl2<Resources>,
    options: TranslateOptions,
  ) => this.i18nService.t(key, options);
```
5. Call `t`:
![image](https://github.com/i18next/i18next/assets/71282839/cac60a33-19c0-44c2-8b93-0a655a6a7626)
![image](https://github.com/i18next/i18next/assets/71282839/ae9ee5c7-b3e9-484b-937b-baf5193a77a6)

## Expected behavior

Linter should suggest `example.notWorkingExample.push` and typescrit should be recognized as a valid type.

## Your Environment

- *runtime version*: v18.16.1
- *i18next version*: nextjs-i18n
- *os*: Windows
- *nestjs-i18n*: "^10.2.6"
- *i18next-resources-for-ts*: "^1.3.3"

**Comment by adrai** [comment]
Please provide a complete but minimal reproducible example.
