### ISSUE TITLE
Type errors when upgrading to 23.7.6 while using react-i18next

### ISSUE THREAD

**Issue by frontendphil** [i18next/i18next#2065]
## 🐛 Bug Report

With the upgrade to 23.7.6 we started seeing type-errors that have not been there before. Namely, that the default `i18n` type is not compatible to what `react-i18next` wants. I'm unsure whether this is a `react-i18next` or `i18next` bug. I'll start here, because it appeared with a `i18next` update and not a `react-i18next` update 🤷🏻 

## To Reproduce

A [minimal reproducible example](https://replit.com/@frontendphil/i18next-type-bug?v=1).
You need to run the repl to get the proper type-error output

```js
import {createInstance} from 'i18next'
import type {i18n} from 'i18next'
import 'react-i18next'

export const createClientInstance = async (): Promise<i18n> => createInstance()
```

**Comment by adrai** [comment]
You probably also use moduleResolution: bundler, right? like [here](https://github.com/i18next/react-i18next/issues/1693)?
if so, try to cast it (createInstance() as I18N)

**Comment by frontendphil** [comment]
Correct. Because we're also using `remix` and `remix-utils.` I've added a `@ts-expect-error` to the return, which makes the function not complain about the return value. That "solves" it for me. Maybe the types get sorted in the future :)

**Comment by adrai** [comment]
should be better with newer react-i18next versions
