### ISSUE TITLE
Typescript: Typing with Interfaces

### ISSUE THREAD

**Issue by cmeier** [i18next/i18next#2069]
Is there no feature to make the selectors typesafe yet?

I could not find it in the docs, so i implemented it myself.

I am not a total expert in making big typings, so i just tried until it worked. I'm sure there is a more elegant solution. And if done right from the beginning instead of converting the existing hook, i'm sure it will be a lot easier. My implementation only shows, that it could be possible. I didn't check if it breaks something i didn't use. I also didn't think about if namespaces and key prefixes still work, because i didn't use them until now. It might be an ugly hack, but it does what i wanted it to do and it works for me.

My solution:

type Leaves<T> = T extends object
  ? { [K in keyof T]: `${Exclude<K, symbol>}${Leaves<T[K]> extends never ? '' : `.${Leaves<T[K]>}`}` }[keyof T]
  : never;

export function useTypedTranslation<T, Ns extends Namespace = DefaultNamespace, KPrefix extends KeyPrefix<FallbackNs<Ns>> = undefined>(
  ns?: Ns,
  options?: UseTranslationOptions<KPrefix>
) {
  const translation = useTranslation(ns, options);
  const tt = <
    const Key extends ParseKeys<Ns, TOpt, KPrefix> | TemplateStringsArray,
    const TOpt extends TOptions,
    Ret extends TFunctionReturn<Ns, AppendKeyPrefix<Key, KPrefix>, TOpt>,
    const ActualOptions extends TOpt & InterpolationMap<Ret> = TOpt & InterpolationMap<Ret>,
  >(
    ...args:
      | [key: Leaves<T>, options?: TOpt & $Dictionary & { defaultValue: string }]
      | [key: Leaves<T> | Leaves<T>[], options: TOpt & $Dictionary & { defaultValue: string }]
      | [key: Leaves<T> | Leaves<T>[], defaultValue: string, options?: TOpt & $Dictionary]
  ) => {
    const convertedArgs = args as unknown as
      | [key: Key | Key[], options?: ActualOptions]
      | [key: string | string[], options: TOpt & $Dictionary & { defaultValue: string }]
      | [key: string | string[], defaultValue: string, options?: TOpt & $Dictionary];
    return translation.t(...convertedArgs);
  };

  return { ...translation, tt };  // tt for typesave translation => i made a new function "tt" to not cause breaking changes. Might be stupid..
}

export interface MyLanguageResource {
   hey: {
     you: {
        can: {
           have: {
               typesafety: string,
           };
        };
     };
   };
}

export const en: MyLanguageResource {
   hey: {
     you: {
        can: {
           have: {
               typesafety: "Hello World!",
           },
        },
     },
   },
}

=> This makes sure, that i don't misspell the selectors for my resources and that my resources are always complete. 
It also gives me intellisense in any usable IDE which makes it a lot easier to use the resources.

I am aware that if i use resources directly written in typescript, it makes them more difficult to load dynamically. 
But if i only have 3 or 4 languages i don't care much. 
I could still write the resource files in json and use just that typed hook. 
To check the resource jsons for completeness, i could also generate a json schema from the interface. 
There are json schema code generators that can take typescript interfaces as input. 

Because i normally use just one resource interface in one app, i normally do an useAppTranslation hook for that app that looks like this:

export function useAppTranslation<Ns extends Namespace = DefaultNamespace, KPrefix extends KeyPrefix<FallbackNs<Ns>> = undefined>(
  ns?: Ns,
  options?: UseTranslationOptions<KPrefix>
) {
  return useTypedTranslation<AppLanguageResource, Ns, KPrefix>(ns, options);
}

i can now use:

const { tt } = useAppTranslation();
tt('hey.you.can.have.typesafety') // => works as expected
 
 tt('hey.you.can.haveit.typesave')  // => will give me a compile error
 
 ---
 As i wrote: I i did not check, if there are any problems with the second and the third parameters yet. 
 
 Maybe someone can check it out and integrate it, 
 or explain what the problem is with such a solution and why it is not a good idea.
 Or explain how it can already be done in another way and put an easy to find example into the documentation.

**Comment by adrai** [comment]
sorry, but is this not sufficient for you? https://www.i18next.com/overview/typescript

**Comment by cmeier** [comment]
> sorry, but is this not sufficient for you? https://www.i18next.com/overview/typescript

Thanks for the quick reply! 👍 

Ok.. you are right.  

I have to admit if i would have watched the video first, i would not have written my hook ;).
So i will try again.

No offense i aprechiate any opensource library of such a quality and the documentation is also quite good! 
People doing stuff like this are heroes!

With the documentation i just really didn't get it from the beginning and could not understand why and if the hook would work. It also didn't work when i tried it first, because i must have done a mistake somewhere. Then i thought: OK it does not solve my desired goal and if, it takes a lot of time to find my mistake.

I think it would be motivating for me to find a "very very visible" example like:
t('you.can.have.typesafety') and t('spelling.mistakes.wont.compile') 

Seeing it this i would not have given up after it did not work after the first attempt. But maybe it would also have helped to go over the documentation more carfully again.
After i failed, using a directly typed hook seemed to be an easier solution for me. 
No setup needed and it was clear for me why it would work.

Thanks again :)

**Comment by adrai** [comment]
There are a couple of simple examples you can have a look at listed on that page: https://www.i18next.com/overview/typescript#some-examples
