### ISSUE TITLE
Typescript performance really slow when using a function with `ParseKeys` return type in `t`

### ISSUE THREAD

**Issue by Gr3q** [i18next/i18next#2070]
## 🐛 Bug Report

As title. Even if `t` expects the exact same type that I give to my function return type it probably still matches all of the items against each other, but I don't know for sure.

I included the workaround in the repro too.

## To Reproduce

* Clone https://github.com/Gr3q/i18next-slow-repro and `npm i` 
* Run `time npx tsc --noEmit --skipLibCheck`
  ```fish
   time npx tsc --noEmit --skipLibCheck
   ________________________________________________________
   Executed in    8.39 secs    fish           external
      usr time   10.61 secs  745.00 micros   10.61 secs
      sys time    0.44 secs    0.00 micros    0.44 secs
   ```
* Comment out `t(ReallySlow())`
* Run `time npx tsc --noEmit --skipLibCheck`
    ```fish
   time npx tsc --noEmit --skipLibCheck

   ________________________________________________________
   Executed in    1.60 secs    fish           external
      usr time    3.21 secs  877.00 micros    3.21 secs
      sys time    0.24 secs    0.00 micros    0.24 secs
   ```

## Expected behavior

It should not take about 7 seconds to typecheck that 1 line, probably. VSCode typescript language features (engine) also hangs for that long (basically every time I save a file in the project autocomplete/etc don't come back until typechecking finishes).

## Your Environment

- *runtime version*: node v21.2.0, typescript 5.3.2
- *i18next version*: 23.7.7
- *os*: Linux

**Comment by adrai** [comment]
feel free to provide a PR to improve this

**Comment by Gr3q** [comment]
God I wish I knew, I can only spare an hour or 2 to look _this year_...

**Comment by Gr3q** [comment]
bump...

**Comment by Gr3q** [comment]
I update the repo to the latest version, still the same (obviously)

**Comment by Greg-NetDuma** [comment]
I updated the repo to the latest version testing https://github.com/i18next/i18next/pull/2095 as well. All cases I could think of (including unlikely ones) are fast now.

Time on the latest with extra lines  in the repo:
```
~/R/i18next-slow-repro►time npx tsc --skipLibCheck --noEmit                                                                                                                                                                                                                                                                                       0.932s  (main|●💩?|MERGING↑1↓1) 10:26

________________________________________________________
Executed in    3.44 secs    fish           external
   usr time    5.33 secs  321.00 micros    5.33 secs
   sys time    0.16 secs    0.00 micros    0.16 secs
```

**Comment by adrai** [comment]
@marcalexiei did a great job ;-)

**Comment by Greg-NetDuma** [comment]
Yes..I'm testing this with our original project and `tsc` just crashes with out of memory again, I'm looking into it right now.

With 8Gigs of RAM allowed for node it succeeded. type-checking time went up from 78s to 157s. Also I have a bunch of errors now, I'll check if they are valid or not.

**Comment by Greg-NetDuma** [comment]
Never mind the increase is not due to the latest release, I'll open another PR when I find when it happened (somewhere between 23.5.1 and now)

**Comment by Greg-NetDuma** [comment]
This issue can be closed.
