### ISSUE TITLE
Translate one key to another language than selected by the app

### ISSUE THREAD

**Issue by Tibo-Mllr** [i18next/i18next#2078]
## 🐛 Bug Report

I wanted to fix the language of on specific usage of `t`, because for that one usage, it has to be the same language chosen by `I18n` of `aws-amplify`, event though the rest may be in another language.
However, I do not succeed to override the later chose language.
Maybe I'm missing something, but I cannot see what no matter how many forums I look into.

## To Reproduce

* Use `i18next` or `react-i18next`, and chose a language
* Try to create another `TFunction` with for example `getFixedT`, with a specific `lng`
* You get the translation only if the specific `lng` is the same as the `i18next.language`, else you just get the key not translated

```js
const t = i18next.getFixedT("de-DE");
.
.
.
<div>
		{t("See more")}
</div>
```

### What I see on my screen

"See more". If I change and set `const t = i18next.getFixedT("fr-FR")` then I see "Voir plus" as expected.

And if I keep `const t = i18next.getFixedT("de-DE")` but change the app language to German, then we see "Mehr sehen" as expected, but if I put back `const t = i18next.getFixedT("fr-FR")` (with still the app language at German) then we see just "See more"...

## Expected behavior

When we use a `getFixedT` or specify a `lng` in the options of a `t`, that this overrides the global app language.

## Your Environment

- *runtime version*: node 16.14.2
- *i18next version*: ^21.9.0
- *os*: Mac Ventura 13.6.1 (22G313)
- *browser*: Firefox 120.0.1

**Comment by adrai** [comment]
Don't know exactly what you mean but try this:

`t("i18nKey", { lng: 'de-DE' })`

If this does not help, please provide a minimal reproducible example.

**Comment by Tibo-Mllr** [comment]
No, that doesn't work, I still see the key itself.

Here is a full example if you want to test:
```js
import i18next from "i18next";
import { useTranslation } from "react-i18next";

export default function Test() {
    const { i18n } = useTranslation();
    useEffect(() => {
        i18n.changeLanguage("fr-FR");
    }, []);

    const t = i18next.getFixedT("de-DE");

    return (
        <div>
            {t("i18nKey")} // Doesn't work with { lng: "de-DE" } either
        </div>
    )
}
```

**Comment by adrai** [comment]
Sorry, but that's not a reproducible example but just a code snippet...
This is an example: https://codesandbox.io/p/sandbox/react-i18next-http-example-forked-27fhqm?file=%2Fsrc%2Fi18n.js%3A17%2C1-18%2C1

I suspect you've not loaded the language de-DE befure calling the appropriate t function...
calling getFixedT will not magically load and wait the translations for a non-loaded language...
Try to use the preload option and pass in the languages you always want to be loaded on init...
Alternatively, you try to use [loadLanguages](https://www.i18next.com/overview/api#loadlanguages) somewhere

**Comment by Tibo-Mllr** [comment]
Sorry, I never used Sandbox, I didn't understand.
Anyway, by tinkering between the `initConfig` you gave in the example and the one we have, I noticed that it was the `preload` that was at fault. We didn't have that in our config. Thanks!!

So I just have one last question @adrai : Does it affect the performances to put all the languages here ? We have approx. 1900 keys, each translated into 12 languages.
