### ISSUE TITLE
Upgrade to version newer than 23.7.6 leads to typecheck failures

### ISSUE THREAD

**Issue by rnestler** [i18next/i18next#2086]
## 🐛 Bug Report

After upgrading to any version above 23.7.6 (so 23.7.7 until 23.7.9) gives me the following error:
```
Argument of type 'import(".../node_modules/i18next/typescript/t.v4").TFunction<"translation", undefined>' is not assignable to parameter of type 'import(".../node_modules/i18next/typescript/t").TFunction<"translation", undefined>'.
```
## To Reproduce

```js
import React from "react";
import { useTranslation } from "react-i18next";
import { TFunction } from "i18next/typescript/t";

const fun = (t: TFunction) => {
  return t("foo"); // errors here
};

const Test = () => {
  const { t } = useTranslation();

  fun(t); // errors here

  return <></>;
};

export default Test;
```

## Expected behavior

The function returned by `useTranslation` and `TFunction` should have the same signature. But apparently one is using the typscript 4 definition, even if I'm using typescript 5 to check the code

## Your Environment

- *runtime version*: node v20.10.0
- *i18next version*: i.e. 19.5.9
- *os*: Linux
- *react-i18next version*: 13.5.0
- *typescript version*: 5.3.3

**Comment by adrai** [comment]
Please do import the TFunction like this:

```diff
- import { TFunction } from "i18next/typescript/t";
+ import { TFunction } from "i18next";
```

**Comment by rnestler** [comment]
I could fix it by changing the import
```diff
 import React from "react";
 import { useTranslation } from "react-i18next";
-import { TFunction } from "i18next/typescript/t";
+import type { TFunction } from "i18next";

 const fun = (t: TFunction) => {
   return t("foo");
```

But I'm still confused why the

**Comment by rnestler** [comment]
Heh that was almost at the same time. But I'm still confused why there is a mix of type definitions? How is decided if the `t.v4` definitions are used?

**Comment by adrai** [comment]
because depending on if you use the esm or cjs build and depending on the typescript version and the configured moduleResolution it requires a different interface...
