### ISSUE TITLE
disable en-US fetch

### ISSUE THREAD

**Issue by ralyodio** [i18next/i18next#209]
I put all translation files under `/lang/app.json` for example `/en/app.json` and `/fr/app.json`. However I still see a 404 request for `/en-US/app.json`.

Is there anyway to disable this? Some OS/Browsers I've tested do NOT return the country code, only language (ie: `en` not `en-US`) so I opted to just put everything under `/<lang>/` but I want to disable the fetching of `/<lang>-<COUNTRY>`

**Comment by komali2** [comment]
Was this feature merged, and if so, how can we use it?

**Comment by jamuhl** [comment]
@komali2 whitelist is now supportedLngs https://www.i18next.com/overview/configuration-options#languages-namespaces-resources
