### ISSUE TITLE
Change typescript test system

### ISSUE THREAD

**Issue by marcalexiei** [i18next/i18next#2096]
## 🚀 Feature Proposal

It's not a feature proposal but more a suggestion for managing typescript tests 😅.

After working on #2095 I think about some improvements for the typescript tests:

Right now typescript tests are performed by `tslint` in a non usual way:
E.g.: `t(....).trim()` tests if the function returns a string 😁.

Since tslint is deprecated maybe using a tool like `vitest` might give some advantage like:

* type checking support (experimental): https://vitest.dev/guide/testing-types.html#run-typechecking
* Better API to make more accurate tests: https://vitest.dev/api/expect-typeof.html 
* Workspace support (each `tests/typescript/*` scenario could be a workspace): https://vitest.dev/guide/workspace.html
  which allows to remove all `test:typescript:*` scripts to have a more clean `package.json`
* Although also karma is deprecated so in the future all tests could be migrated to vitest

If you are interested I can create a PR in the next weeks 😀.

## Motivation

Explained above

## Example

N/A

**Comment by adrai** [comment]
I'm not a TS expert and also never used vitest, so feel free to prepare a PR... I just like the workspace support to not influence outside of the test cases... so the source build etc... is not influenced and can stay the same... but under the test folder we can modify what best suits...
