### ISSUE TITLE
Events no longer firing when changing language to cimode

### ISSUE THREAD

**Issue by is-jonreeves** [i18next/i18next#2102]
## 🐛 Bug Report

During an upgrade from `23.4.6` we noted that some of our unit tests started failing. They check that the `languageChanged` event updates `<html>` attributes.

After trying various versions, we were able to narrow down that `23.4.6` works but `23.4.7` does not. And that it seems that I18n events no longer appear to fire when setting language to `cimode`.

Looking at the [source code change](https://github.com/i18next/i18next/compare/v23.4.6...v23.4.7#diff-6859f2a371e0f563ec9c27c5cf64cb82f8d91750467509caaa8f6f0e6d06dec5R221), its looks like is happening in our case because we have `preload: [Languages.NATIVE]` in our initialize config, where the code change expects `preload` to be undefined/empty (for some reason).

One workaround might be to change our production code to have a condition in it to set `preload` to empty based on NODE_ENV, but that doesn't feel like a good answer. If its important that we set `preload: []` when using `cimode` I can find a cleaner way, but right now it seems like a regression.

## To Reproduce
Something like...
```js
// Constants
const Languages = {
  NATIVE: 'en-US',
  AVAILABLE: ['en-US', 'fr-FR'],
};

// Configure
export const I18n = createInstance({
  ...,
  fallbackLng: Languages.NATIVE,
  preload: [Languages.NATIVE],
  supportedLngs: Languages.AVAILABLE,
  ...
});

// Initialize
I18n
  .use(i18nReact)
  .use(i18nHttpBackend)
  .use(languageDetector)
  .init();

// Events
I18n.on('initialized', () => console.log('I18n initialized'));   // ❌ Doesn't Fire
I18n.on('languageChanged', (lang: string) => {                   // ❌ Doesn't Fire
  console.log('I18n Language Changed')
  document.documentElement?.setAttribute('lang', lang);
  document.documentElement?.setAttribute('dir', I18n.dir(lang));
});
```

## Expected behavior

When changing language to `cimode` via `i18nInstance.changeLangauge()` any listeners attached to `i18nInstance.on('languageChanged', ...)` should be called.

A Unit Test might look something like...

```js
import { I18n } from '.';

// Mocks
let setAttributeSpy: jest.SpyInstance;

// Tests
describe('Internationalization', () => {
  beforeEach(() => {
    jest.resetAllMocks();
    setAttributeSpy = jest.spyOn(window.document.documentElement, 'setAttribute');
  });

  afterEach(() => {
    setAttributeSpy.mockRestore();
  });

  it('updates the html element attributes when the language changes', () => {
    // Setup
    const lang = 'cimode';
    setAttributeSpy.mockImplementation(() => void 0);

    // Test
    I18n.changeLanguage(lang);

    // Check
    expect(setAttributeSpy).toBeCalledTimes(2);
    expect(setAttributeSpy.mock.calls[0][0]).toBe('lang');
    expect(setAttributeSpy.mock.calls[0][1]).toBe('cimode');
    expect(setAttributeSpy.mock.calls[1][0]).toBe('dir');
    expect(setAttributeSpy.mock.calls[1][1]).toBe('ltr');
  });
});

```

## Your Environment

- *runtime version*: node 20
- *i18next version*: 23.4.7+
- *os*: Windows

**Comment by adrai** [comment]
currently afk... but I already have an idea

**Comment by adrai** [comment]
Sorry, but I'm not able to reproduce your issue.
Can you please create a minimal reproducible example?

I tried something like this:

```js
const { createInstance } = require('i18next');
const Backend = require('i18next-http-backend');

const Languages = {
  NATIVE: 'en-US',
  AVAILABLE: ['en-US', 'fr-FR'],
};

const instance = createInstance({
  debug: true,
  fallbackLng: Languages.NATIVE,
  preload: [Languages.NATIVE],
  suportedLngs: Languages.AVAILABLE,
});

instance.on('initialized', () => console.log('I18n initialized'));
instance.on('languageChanged', (lng) => {
  console.log('I18n Language Changed', lng);
});

instance.use(Backend).init();



setTimeout(() => {
  instance.changeLanguage('cimode');
}, 2000);

```

**Comment by is-jonreeves** [comment]
I created a small example on stackblitz but wasn't able to reproduce it either, so went local... Interestingly using `React` via `Vite` + `Vitest` I wasn't able to reproduce it locally either...
```ts
...
  preload: [],                        // ✅ Success in Vite/Vitest
...
  // vs
...
  preload: [Languages.NATIVE],        // ✅ Success in Vite/Vitest
...
```

So I decided to match our project as closely as I could and used `React` via `CRA`... bingo!
```ts
...
  preload: [],                        // ✅ Success in CRA/Jest
...
  // vs
...
  preload: [Languages.NATIVE],        // ❌ Failure in CRA/Jest
...
```
![bug-i18next-vite-cra](https://github.com/i18next/i18next/assets/2935156/8b3b5360-d68b-4a58-a191-c5b5adeda7db)

While reviewing our original project I noted that we have a mock in our setup files: `jest.mock('i18next-http-backend')`. I tried adding this to both projects and got some interesting results...

With the mock enabled, BOTH projects fail for `preload: [Languages.NATIVE]` and only `vite` continues to succeed with `preload: []`.

So to summarize... 

| **Vite + Vitest** | `no Mock` | `vi.mock('i18next-http-backend')` |
|------------------|---------------------|---------------|
|  `preload: []` | ✅ | ✅ |
| `preload: [Languages.NATIVE]` | ✅ | ❌|


| **CRA + Jest** | `no Mock` | `jest.mock('i18next-http-backend')` |
|------------------|---------------------|---------------|
|  `preload: []`  | ✅ | ✅ |
| `preload: [Languages.NATIVE]` | ❌ | ❌|

Not too sure what to make of the results to be honest. Its a little odd that `vite` would be different to `CRA`, but I know that vite for example uses `MODE` and `import.meta.env`, vs. `NODE_ENV` and `process.env`. Also probably how `window`, `this`, `global`, and `globalThis` are handled too. So might be related. The only other clue I can give is that removing the `i18next-http-backend` plugin entirely from the mix, everything works, so it seems like the issue might actually stemming from that plugin instead.

I've attached both local projects to play with... [bug-i18next-events.zip](https://github.com/i18next/i18next/files/13814616/bug-i18next-events.zip)

**Comment by is-jonreeves** [comment]
For what its worth... downgrading both projects via `npm i i18next@23.4.6` makes everything work (with or without mocks).

**Comment by adrai** [comment]
I suspect that's a timing issue...
your tests are also a bit strange imo... the tests do not wait for i18next to be initialized... i18next-http-backend will load the translations asynchronously... so you have to wait for it to have loaded the translations, before testing anything...

**Comment by adrai** [comment]
fyi: something like this:

```js
import { I18n } from '.';
import { setTimeout as wait } from 'node:timers/promises'

// Mocks
// jest.mock('i18next-http-backend');
let setAttributeSpy: jest.SpyInstance;

// Tests
describe('Internationalization', () => {
  beforeEach(async () => {
    // wait for i18next to be initialized...
    while (!I18n.isInitialized) await wait(100);
    jest.resetAllMocks();
    setAttributeSpy = jest.spyOn(window.document.documentElement, 'setAttribute');
  });

  afterEach(() => {
    setAttributeSpy.mockRestore();
  });

  it('updates the html element attributes when the language changes', async () => {
    // Setup
    const lang = 'cimode';
    setAttributeSpy.mockImplementation(() => void 0);

    // Test
    I18n.changeLanguage(lang);

    // Check
    expect(setAttributeSpy).toBeCalledTimes(2);
    expect(setAttributeSpy.mock.calls[0][0]).toBe('lang');
    expect(setAttributeSpy.mock.calls[0][1]).toBe('cimode');
    expect(setAttributeSpy.mock.calls[1][0]).toBe('dir');
    expect(setAttributeSpy.mock.calls[1][1]).toBe('ltr');
  });
});


```

**Comment by adrai** [comment]
this proofs, it's timing related... depending on how fast i18next loads the translations your test (without waiting) will succeed or not...

**Comment by adrai** [comment]
if you don't like to wait for i18next to be initialized, you need to set the preload option to an empty array...

**Comment by is-jonreeves** [comment]
Thanks for taking a look at this

It wouldn't have occurred to me that the initialization ended up being asynchronous, especially as its not awaitable. But I can see that opting to include an async backend plugin whose job it is to process the `preload: [...]` list that it would cause this outcome when that list is not empty.

With this in mind the simplest route for me is probably to flesh out the mock to enforce an empty preload:
```ts
jest.mock('i18next-http-backend', () => ({
  __esModule: true,
  default: class Backend {
    static type = 'backend';
    init (_s: any, _o: any, a: any) { a.preload = []; }
    read () {}
    readMulti () {}
    create () {}
  }
}));
```

I guess, the other option would be to jump through hoops to test this global behavior from within the context of a React Component and ensure that I18next instance is guaranteed to already be initialized. This would likely involve wrapping the Provider and connecting/disconnecting the listeners from inside. I'm not sure its worth the effort for our needs (considering everything is working, apart from the tests), but if anyone else is interested, it could look something like...
```tsx
...
// Initialize
instance
  .use(i18nReact)
  .use(i18nHttpBackend)
  .init();

// Listener
const I18nListener: FunctionComponent<PropsWithChildren> = ({ children }) => {
  const [ isListening, setIsListening ] = useState(false);
  const { i18n } = useTranslation();

  useEffect(() => {
    const change = (lang: string) => {
      document.documentElement?.setAttribute('lang', lang);
      document.documentElement?.setAttribute('dir', i18n.dir(lang));
    };
    i18n.on('languageChanged', change);
    setIsListening(true);
    return () => i18n.off('languageChanged', change);
  }, []);

  return isListening ? children : null;
};

// Instance
export const I18n = instance;

// Provider
export const I18nProvider: FunctionComponent<PropsWithChildren> = ({ children }) => (
  <I18nextProvider i18n={I18n}>
    <I18nListener>
      {children}
    </I18nListener>
  </I18nextProvider>
);
```

The test would then be:
```tsx
// Mocks
let setAttributeSpy: jest.SpyInstance;

// Tests
describe('Internationalization', () => {
  beforeEach(() => {
    jest.resetAllMocks();
    setAttributeSpy = jest.spyOn(window.document.documentElement, 'setAttribute');
    setAttributeSpy.mockImplementation(() => void 0);
  });

  afterEach(() => {
    setAttributeSpy.mockRestore();
  });

  it('updates the html element attributes when the language changes', async () => {
    // Setup
    const Component = () => {
      const { i18n } = useTranslation();
      useEffect(() => void i18n.changeLanguage('cimode'), []);
      return <p>Rendered</p>;
    };

    // Test
    render(
      <I18nProvider>
        <Component />
      </I18nProvider>
    );

    // Check
    await screen.findByText('Rendered');
    expect(setAttributeSpy).toBeCalledTimes(2);
    expect(setAttributeSpy.mock.calls[0][0]).toBe('lang');
    expect(setAttributeSpy.mock.calls[0][1]).toBe('cimode');
    expect(setAttributeSpy.mock.calls[1][0]).toBe('dir');
    expect(setAttributeSpy.mock.calls[1][1]).toBe('ltr');
  });
});
```

---

I should be good to move forward with the simpler mock route above. Marking as closed.

I appreciate your time and help
