### ISSUE TITLE
Unable to use import statement - only require works

### ISSUE THREAD

**Issue by ofhinterviewers** [i18next/i18next#2114]
Hi there, 

I have a Node/Express/TypeScript application and want to use i18next with it. When I try to import i18next

```ts
import i18next from 'i18next';
```

`i18next` is undefined. I've also tried:

```ts
import { default as i18next } from 'i18next
```

With no avail.

However, if I use a require statement:

```ts
const i18next = require('i18next');
```

It works. Which is odd because I have loads of other libraries I use in the project that use es6 imports (i.e. import syntax).

Is anyone able to shed some light on why this might be?

**Comment by adrai** [comment]
How does your tsconfig look like?
Probably you need to set `esModuleInterop: true`?

**Comment by ofhinterviewers** [comment]
Thanks for getting back to me @adrai - I don't have `esModuleInterop` set to `true`, but I'm trying to understand why I'd need this for my project. I've got at least two dozen dependencies and can't see what is different about `i18next` that would require me to have this. Any insight would be much appreciated :)

**Comment by adrai** [comment]
https://github.com/i18next/i18next/issues/1447

**Comment by AllenAttuned** [comment]
I'm experiencing this issue as well. We are working to convert our application to TypeScript, and we have several `i18n.t` statements which are behaving differently between JavaScript and TypeScript files.

`i18n.t('some.string')` returns `undefined` and doesn't trigger our `missingKeyHandler` (aside: using the `useTranslation` hook from `react-i18next` seems to work fine). 

Example error:

```
Uncaught (in promise) TypeError: i18next_1.default.store is undefined
```

We have `esModuleInterop: true` in our `tsconfig.json`.

```json
{
  "compilerOptions": {
    "outDir": "./dist/",
    "noImplicitAny": false,
    "module": "node16",
    "target": "ES2020",
    "lib": [
      "esnext",
      "dom"
    ],
    "jsx": "react",
    "allowJs": true,
    "checkJs": false,
    "moduleResolution": "node16",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "baseUrl": "./src",
    "paths": {
      "~/*": [
        "*"
      ]
    }
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

Relevant package versions are:
- `"i18next": "23.7.18"`
- `"react-i18next": "14.0.1"`
- `"webpack": "5.89.0"`
- `"typescript": "5.3.3"`

**Comment by AllenAttuned** [comment]
A follow-up to what my team was experiencing. Configuring the TS `module` to `ESNext` and `moduleResolution` to `Bundler` seems to have fixed our issue.

Our setup uses Webpack with the `ts-loader` to compile our TypeScript and uses the `babel-loader` for JavaScript. I'm guessing TSC was transforming the `import` statements, which could cause issues with the reset of the build process. Setting `moduleResolution` to `bundler` tells TSC that whatever bundler we use should be responsible for resolving modules.


```
{
    "compilerOptions": {
        ...
        "module": "ESNext",
        "moduleResolution": "Bundler",
        ...
    }
}
