### ISSUE TITLE
Join an array with "," and "and"

### ISSUE THREAD

**Issue by ondrejnedoma** [i18next/i18next#2117]
## 🚀 Feature Proposal

Provide developers with a way to join an array with a comma (,) for all the elements except for the last one, and then (and) for the last one. This feature is really easy to implement by the developer themselves, but having them directly in i18next would be convenient.

## Motivation

Currently I have these lines in my translation.json:
```json
{
  "missingFields_one": "Field {{missingFields}} is required",
  "missingFields_other": "Fields {{missingFields}} are required"
}
```

And I'm filling in {{missingFields}} (an array) and {{count}} with missingFields' length:
```js
t("missingFields", {missingFields: missingFields.join(", "), count: missingFields.length})
```

This will, though, join all of the items with a comma. I can include an "and" key in my translation.json and do this:
```js
const firstPart = missingFields;
const lastElement = firstPart.pop();
missingFields: [firstPart.join(", "), lastElement].join(t("and"))
```

**But I just feel that this functionality should be included out of the box.**

## Example

Provide the "and" word in all languages by default. Also account for stuff like y/e in Spanish and other exceptions. Then make a way to join the array for any placeholder:
```js
// This would still work for simple values
t("missingFields", {missingFields: "foo, bar", count: 2})
// This would be a way to make the array joined with "," and "and" automatically. "count" could also be deducted automatically
t("missingFields", {missingFields: {value: ["foo", "bar"], dynamicJoin: true}})
```

**Comment by jamuhl** [comment]
should be handled like: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat

and is implemented in i18next like described here: https://www.i18next.com/translation-function/formatting#list
