### ISSUE TITLE
i18n_t does not support choice format well

### ISSUE THREAD

**Issue by bodycombathuang** [i18next/i18next#2120]
here is my key-value pair
  "test333":"This element contains {value,choice,0#no comments|1#one comment|1<{0} comments"

i18n.t("test333", {value:1})

the output is This element contains 1 comments

I expect to see the output is This element contains one comment

**Comment by adrai** [comment]
Plurals handling works like this in i18next: https://www.i18next.com/translation-function/plurals

**Comment by bodycombathuang** [comment]
hi @adrai , can i18next handle choice format like "This element contains {value,choice,0#no comments|1#one comment|1<{0} comments"?

**Comment by bodycombathuang** [comment]
import Backend from 'i18next-fs-backend';  
i18n
    .use(Backend)
    .init({
      interpolation: { prefix: '{', suffix: '}' },
      initImmediate: false,
      lng: currentLanguage,
  
      resources,
    })

this is code for me to initiate i18next

**Comment by adrai** [comment]
no, never seen such a format
