### ISSUE TITLE
Array Interpolation

### ISSUE THREAD

**Issue by robross0606** [i18next/i18next#2125]
#1049 covered this issue in 2018, but the documentation now says the recommended solution is "legacy" beyond 21.3.0.  What is the appropriate way to interpolate an array of values (e.g. array of strings) into a larger translation where we need something other than `,` as the separator for a single translation -- not the entire translator `init`?  `Intl.ListFormat` does not appear to be adequate to the task of simply changing the list separator.  The suggestion of using `format:` would still work, but it is called out as "legacy" and therefore makes me think it would be removed in the future.

**Comment by adrai** [comment]
You can define your own format function like this: https://www.i18next.com/translation-function/formatting#adding-custom-format-function

```js
i18next.services.formatter.add('duplicate', (value, lng, options) => {
  if (format === 'duplicate') {
    return value.map(v => v * 2).join(' | ');
  }
  return value;
});
```

**Comment by robross0606** [comment]
Is `if (format === 'duplicate')` block still needed if you're already declaring the formatter with the name "duplicate"?

**Comment by adrai** [comment]
sorry, copy/paste error

**Comment by robross0606** [comment]
No worries.  Thanks!  🙂

**Comment by robross0606** [comment]
Sorry to belabor this, but when I debug the use of services, it appears the values of `value` and `lng` are backwards in the function calls.  I see the language (e.g. "en") passed in on the `value` parameter and my interpolation values showing up on the `lng` parameter.  Is the documentation backwards?

**Comment by adrai** [comment]
Don't think so: https://github.com/i18next/i18next/blob/master/test/runtime/i18next.translation.formatting.test.js#L68

**Comment by robross0606** [comment]
Sorry, my bad.  I was accidentally using `formatter.addCached()` instead of `formatter.add()`.  😊

**Comment by robross0606** [comment]
I'm sorry to keep bothering, but the documentation here is a really a bit confusing.  I'm trying to pass in the separator as an option to my interpolation like this:
```
```

**Comment by robross0606** [comment]
Sorry to keep bothering, but the documentation is a bit limited/confusing here.  I'm trying to pass in the separator as an interpolation option like this:
```
      "no-selected-terms": "Schedule '{{- scheduleInfo}}' Study Event '{{- studyEventInfo}}' has no selected Terms on Activity Item: {{termGroupPath, join(separator:' ► ')}}"
```

If I don't pass in options to my custom formatting function, it works and uses the default separator:
```
      "no-selected-terms": "Schedule '{{- scheduleInfo}}' Study Event '{{- studyEventInfo}}' has no selected Terms on Activity Item: {{termGroupPath, join}}"
```

However, the second I try to pass in options, it appears to skip my custom formatter complete.  What am I doing wrong here?

**Comment by robross0606** [comment]
Okay, I think I figured out the syntax, but this leads to what feels like an actual limitation in the design.  If I remove the `'` from my syntax like this:
```
"no-selected-terms": "Schedule has no selected Terms on Activity Item: {{termGroupPath, join(separator: ► )}}"
```

I am able to get the formatter called and the `separator` option is there.  _However_, because I had to remove the quotes, the spaces are trimmed from the option and I end up with `'►'` instead of `' ► '` which is what I need.  Is this a limitation/bug?

**Comment by adrai** [comment]
Why are you passing the separator like that, and not hardcode it in the formatter function?

**Comment by robross0606** [comment]
Because I needed the formatter to be flexible to different separators based on the translation/interpolation.  Are you saying I would need to set up a different custom formatter for every "join" delimiter?

**Comment by adrai** [comment]
The values are trimmed, while parsing...
But you can pass additional options when calling the t function, something like this:

t('no-selected-terms', { termGroupPath: '...', separator: ' ► ' })

**Comment by robross0606** [comment]
Hmmm...  The problem with this approach is that it violates separation of concerns between data presentation and code.  The separator used for a translation needs to be part of the translation data which is managed by a documentation expert -- part of the render layer.  Meanwhile, code is code and we supply the `key` and the raw data.  The documentation expert may decide to use a different separator in his declaration JSON file.  We cannot hard code that.

**Comment by adrai** [comment]
if your separators always have whitespace, you can just add the whitespace in the format function?

**Comment by robross0606** [comment]
It doesn't always have it, but I'm toying with working around this by adding a `pad` parameter.  It isn't great, but this is a definite limitation of the library.  Trimming all passed in parameters definitely limits flexibility.

**Comment by adrai** [comment]
btw: I just tested, with whitespace like this and it seems to work:  `{{termGroupPath, join(separator: ' ► ')}}`

**Comment by robross0606** [comment]
Hmmm... You're right!  I wonder why it was skipping my function before.  Okay, then!  No problems at all.  😄 🚀

**Comment by adrai** [comment]
[codesandbox](https://codesandbox.io/p/sandbox/i18next-format-ysz5fv?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrusbto500063b6fms3t7uc1%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrusbto500023b6f4z6f5j2e%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrusbto500033b6fbaxcc7vk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrusbto500053b6fs49g29w5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrusbto500023b6f4z6f5j2e%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrusbto500013b6ftnlyv2l7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clrusbto500023b6f4z6f5j2e%2522%252C%2522activeTabId%2522%253A%2522clrusbto500013b6ftnlyv2l7%2522%257D%252C%2522clrusbto500053b6fs49g29w5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrusbto500043b6fabs9rflz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrusbto500053b6fs49g29w5%2522%252C%2522activeTabId%2522%253A%2522clrusbto500043b6fabs9rflz%2522%257D%252C%2522clrusbto500033b6fbaxcc7vk%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrusbto500033b6fbaxcc7vk%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by robross0606** [comment]
I just found a problem with this.  If you try to use a `separator` of ',' it ends up in the function as `NaN` for some unknown reason.  This doesn't work:
```
{{termGroupPath, join(separator: ', ')}}
```
My guess is the parser is misunderstanding the `,` as part of the formatter chain instead of part of the parameter `separator`.
