### ISSUE TITLE
i18next.getResource() does not return all plurials variants

### ISSUE THREAD

**Issue by Toto5931** [i18next/i18next#2126]
## 🐛 Bug Report

I have those keys
```
	"key_zero": "no item",
	"key_one": "one item",
	"key_other": "{{count}} items"
```
When I do i18next.getResource('en', 'translations', 'key') it returns undefined whereas I would have expected the 3 keys variants. For simple keys it returns the resource correclty.
Is it in line with the design intent or is it a bug? The documentation is not accurate enough on this point

## To Reproduce
I will provide more detail if needed

## Expected behavior
 I would have expected the function to retrun this 
```
"key_zero": "no item",
"key_one": "one item",
"key_other": "{{count}} items"
```

## Your Environment

- *runtime version*: i.e. react-i18next
- *i18next version*: i.e. 23.7.20
- *os*: Windows

**Comment by adrai** [comment]
getResource() does just return the resource... it's not like the t function or the exists function that has the logic to resolve a key... so this behaves exactly like designed

**Comment by Toto5931** [comment]
ok thanks
