### ISSUE TITLE
Suspected memory leak

### ISSUE THREAD

**Issue by yanna92yar** [i18next/i18next#2127]
To start of: thank you maintainers & contributors 

How [i18next](https://github.com/i18next/i18next) holds selected language is unknown for me and not documented I think.
I suspect that it does using sessions on the server. 

My app uses more and more memory over time; I 'm on a development stage, so I suspected the metrics recurrent call to create a new session, then I run a separated test, with a simple curl loop on an empty GET route.

Running **heapdump** few seconds after the app bootstraps and after few minutes, then diffing the two, I have gigantic amounts of Arrays and Strings allocated, I don't understand memory well, but `i18n` seems to be in 99% of these objects.

Probably it is the responsibility of *i18nextMiddleware.LanguageDetector* ? because it is the one that uses sessions ?

## Your Environment

- *runtime version*: i.e. node v16.17.0
- *i18next version*: i.e. 23.7.16
- *os*: Linux

![Capture d'écran 2024-01-28 083615](https://github.com/i18next/i18next/assets/130276583/e0d2700a-bcee-43ae-9af7-b32f24078822)
![Capture d'écran 2024-01-28 084108](https://github.com/i18next/i18next/assets/130276583/cc39fd79-c123-4299-ba26-879d94d8a95a)
![Capture d'écran 2024-01-28 083549](https://github.com/i18next/i18next/assets/130276583/4f66ee35-29e8-48f6-a78e-433725d21673)

**Comment by adrai** [comment]
No, i18next or i18nexthttp-middleware does not store the translations in the session store... but you may do so in userland

**Comment by yanna92yar** [comment]
Hi @adrai thank you for your reply 😁
Please tell if you know a bit how to decipher those memory dumps. What's about i18n showing everywhere, in arrays and in strings. 
And second the gigantic number of sessions!

Otherwise, if there is no valuable insight to derive. Please feel free to close and thanks again 🙏
