### ISSUE TITLE
Alphabetical ordering of keys that can contain each other breaks i18next

### ISSUE THREAD

**Issue by briandipalma** [i18next/i18next#2130]
## 🐛 Bug Report

This resource file blows up i18next:

```json
{
  "currency-search.placeholder": "Seleccione el Par de Divisa",
  "currency-search.placeholder.short": "Par de Divisas"
}
```

With this stack trace:

```
i18next.js:229 Uncaught TypeError: Cannot set properties of undefined (setting 'undefined')
    at setPath (i18next.js:229:10)
    at ResourceStore.addResource (i18next.js:419:7)
    at ResourceStore.addResources (i18next.js:429:122)
    at _this2.<computed> [as addResources] (i18next.js:2161:50)
```

Specifically this code:

```javascript
function setPath(object, path, newValue) {
  var _getLastOfPath = getLastOfPath(object, path, Object),
    obj = _getLastOfPath.obj,
    k = _getLastOfPath.k;
  obj[k] = newValue; // <-- THIS LINE HERE
}
``` 

You can see the state of the code when it blows up:

![image](https://github.com/i18next/i18next/assets/1597820/b53a7268-d161-4b38-b016-773dcf6613a0)

So basically because the first key is a subkey of the next key to be added `getLastOfPath` returns an empty object because the subkey has already set the value of its path to a `string` so `canNotTraverseDeeper` short-circuits the tree creation.

**Comment by adrai** [comment]
Which i18next version did you use?
Can you reproduce it with v23.7.20 and with v23.8.1?

if it works with v23.7.20 I assume [this PR](https://github.com/i18next/i18next/pull/2128) introduced a regression //cc: @hsource

**Comment by adrai** [comment]
Ok, I think that is not related to that PR

**Comment by adrai** [comment]
please try with v23.8.2
