### ISSUE TITLE
Add Documentation for default translation file load

### ISSUE THREAD

**Issue by Maxouwell** [i18next/i18next#2133]
## Documentation issue
On the [Fallback page](https://www.i18next.com/principles/fallback), there is this sentence : 

> i18next by default loads its translations from one file named translation

I did not find the documentation explaining where and how should be theses files. I think it should be added in the doc.

**Comment by adrai** [comment]
https://www.i18next.com/principles/namespaces

**Comment by Maxouwell** [comment]
Thanks, but It does not specify where theses files should be, nor what should be the directory hierarchy ?

**Comment by adrai** [comment]
That depends on the used i18next backend...
Have you seen this video?

https://youtu.be/SA_9i4TtxLQ?si=Bcn5thJNHqXhqOsh

**Comment by Maxouwell** [comment]
I do not wish to use a backend, but want the translations bundled.
Is there a way to do it without defining the resources option ?

Reading the quote and the namespaces example it seems to imply that you can load translation files without backend.
If that not the case, the doc on namespace and fallback (and Getting started too) should have a note that a backend is expected for the code provided.

**Comment by adrai** [comment]
https://www.i18next.com/how-to/add-or-load-translations#lazy-load-in-memory-translations

**Comment by adrai** [comment]
or simply import the files and pass them via resources option

**Comment by Maxouwell** [comment]
Thanks you for your help.
