### ISSUE TITLE
使用方法addResources动态添加数据格式错误，Using method addResources to dynamically add data format error 

### ISSUE THREAD

**Issue by 7066** [i18next/i18next#2137]
## 🐛 Bug Report
初始化后，动态加载翻译文件。 我使用 addResources 方法来动态添加数据。但是 18next 无法正常工作，检查后发现生成的数据与实际使用的数据格式不一致。

After initialization, dynamically load translation files. I use addResources method to add data dynamically. But 18next was not working properly and upon inspection it was found that the generated data was inconsistent with the actual data format used.

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
import i18n from "i18next";

// use addResources set
i18n.addResources("en", "home", { code: "2" });

console.log(i18n.translator.resourceStore.data);
// not work 😢
// {
//   en: {
//     home: {
//       code: "2";
//     }
//   }
// }

// use translator set 
i18n.translator.resourceStore.data["en"] = {
  translation: {
    home: { code: "2" },
  },
};

// can work 😊
// {
//   en: {
//     translation: {
//       home: {
//         code: "2";
//       }
//     }
//   }
// }

```

## Expected behavior

```js
// use addResources can work
i18n.addResources("en", "home", { code: "2" });
```

## Your Environment

- *runtime version*: i.e. node 18.19.0, deno, browser xy
- *i18next version*: i.e. 23.8.2
- *os*: Mac
- *any other relevant information*

**Comment by adrai** [comment]
The namespace is "translation" not "home"... so you need to call it like this:

i18n.addResources("en", "translation", { home: { code: "2" } });

**Comment by 7066** [comment]
Calling this way is invalid and nothing will happen. You can try

**Comment by adrai** [comment]
Sorry, wrong function... it's `addResourceBundle`:
`i18n.addResourceBundle("en", "translation", { home: { code: "2" } });`

**Comment by adrai** [comment]
With `addResources` you need to pass them in flat json:

`i18n.addResources("en", "translation", { "home.code": "2" });`

**Comment by 7066** [comment]
`addResources` will be more troublesome, `addResourceBundle` will be more convenient. thanks for your reply.
