### ISSUE TITLE
Add 'isInitializing' property so we're able to detect init() was already called.

### ISSUE THREAD

**Issue by koenvd** [i18next/i18next#2141]
## 🚀 Feature Proposal

I understood from different other issues we should not call the `init` function of the service twice. 

However it would be nice the service would have an `isInitializing` property indicating `init()` was called and is not yet finished (what the `isInitialized` property is telling us).  

We can then use that property to decide if we no longer are allowed to call the `init` method but just have to wait instead on the `initialized` event to detect when the service finished intializing.

## Motivation

There's still some time between calling `init` and the service becoming initialized.  In that time interval an `isInitializing` property would help to know we no longer can call `init`. 

Now we need to keep track of this ourself outside this service which is a bit painful.

**Comment by adrai** [comment]
Feel free to suggest a PR

**Comment by adrai** [comment]
included in v23.10.0

**Comment by koenvd** [comment]
Waw. Awesome @adrai !! Thanks for the fix.

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
