### ISSUE TITLE
Ideas: improve CI

### ISSUE THREAD

**Issue by marcalexiei** [i18next/i18next#2142]
As I mentioned on #2140 I have a few suggestions / ideas I would like to propose:

## 1. CI: add format check script (current `prettier` script)

During #2140 I noticed that `typescript/helpers.d.ts` wasn't formatted with prettier.
Ideally I would like to change lint_and_test workflow by dividing it in two jobs:
1. code quality: run lint + format
2. test:  run all tests like now with an additional optimisation (see next point)

## 2. CI: Reorganise test workspaces to reduce total execution time

Avoid to execute `runtime` and `compatibility` tests two times by creating separate workspace for test with coverage and typescript tests. 
This willl result in 3 workspaces:
- `runtime`: `runtime` + `compatibility` which will collect code coverage
- `typescript`: self-explanatory
- `local`: test to be executed only on a local machine

---

- [x] CI: add format check script (current `prettier` script) (#2146)
- [x] CI: Reorganise test workspaces to reduce total execution time (#2147)

**Comment by adrai** [comment]
sounds good

**Comment by marcalexiei** [comment]
`t.d.ts` dedupe moved into a separate issue (#2148)
