### ISSUE TITLE
refactor: dedupe content between t.d.ts and t.v4.d.ts

### ISSUE THREAD

**Issue by marcalexiei** [i18next/i18next#2148]
At the moment maintaining these two files in sync is a bit painful.
I would like to move the shared content in separate files to reduce maintenance efforts.

Obviously I hope that sometime, in the future, we can remove typescript v4 support 😅

---

Moved to a new issue from #2142 to avoid having tasks involving total different aspects of the project (CI vs typescript)

**Comment by marcalexiei** [comment]
I just noticed that in the typescript documentation is stated that typescript v4 is not longer supported: 

https://www.i18next.com/overview/typescript

> The newest i18next versions only support TypeScript v5. Older TypeScript versions are not supported any longer with i18next > v23.
> To use it with TypeScript v4, use i18next@22.5.1.


Changed was made in November with this commit: https://github.com/i18next/i18next-gitbook/commit/106f8671a82d4c353369fb5abd4141b9e68b5762


So I'm wondering if we can drop v4 support from the codebase, which implies:
- remove `t.v4.d.ts`
- `typesVersion` in `package.json`
-  maybe something else?

**Comment by marcalexiei** [comment]
@adrai what so you think about this?

**Comment by adrai** [comment]
Sorry, missed your question completely...
My gut feeling tells me, we should keep the v4 support st least a little bit more... but we don't need to make sure all types functionality is in line with v5 if not possible...

**Comment by marcalexiei** [comment]
> Sorry, missed your question completely...

No problem 🙂

---

> My gut feeling tells me, we should keep the v4 support at least a little bit more... but we don't need to make sure all types functionality is in line with v5 if not possible...

Gotcha. I'll leave this open open as a reminder to do that in the future 😀

**Comment by adrai** [comment]
@marcalexiei we are preparing the next breaking release... https://github.com/i18next/i18next/compare/master...i18next-drop-legacy
Do you think it's time to drop TS v4 support?

**Comment by marcalexiei** [comment]
I think it can be dropped. [The alert saying i18n typescript support has been there for some time.](https://www.i18next.com/overview/typescript)

However to avoid problems I would also add `typescript` to `peerDependencies`  (alongside [`peerDependenciesMeta.typescript.optional: true`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json?v=true#peerdependenciesmeta)).

This way we can clearly declare what typescript version(s) are supported. 
If you wish I can setup a PR with these changes when I have time.

**Comment by adrai** [comment]
> This way we can clearly declare what typescript version(s) are supported.
> If you wish I can setup a PR with these changes when I have time.

Yes, that would be awesome... just create a PR for the [i18next-drop-legacy branch](https://github.com/i18next/i18next/tree/i18next-drop-legacy)

**Comment by adrai** [comment]
https://www.i18next.com/misc/migration-guide#v23.x.x-to-v24.0.0
