### ISSUE TITLE
Interpolation of multiple datetimes doesn't respect the format params

### ISSUE THREAD

**Issue by robin-xyzt-ai** [i18next/i18next#2149]
## 🐛 Bug Report

When translating a string that contains multiple `datetime` interpolated strings, the `formatParams` argument to format the `datetimes` seems to be ignored

## To Reproduce

The following (Typescript) test can be used to reproduce the issue.

The translating of the `single_date` works as expected.
But the translating of the `multiple_dates` ignores the `formatParams`

```ts
import i18next from "i18next";

const instance = i18next.createInstance();

describe("date formatting", () => {
  beforeAll(async () => {
    await instance.init({
      lng: "en",
      resources: {
        en: {
          translation: {
            single_date: "{{val, datetime}}",
            multiple_dates: "{{first, datetime}} - {{second, datetime}}",
          },
        },
      },
    });
  });

  describe("tests", () => {
    const format: Intl.DateTimeFormatOptions = {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    };
    it("single_date", () => {
      expect(
        instance.t("single_date", { val: new Date(1708935494000), formatParams: { val: format } })
      ).toEqual("Monday, February 26, 2024");
    });
    it("multiple_dates", () => {
      expect(
        instance.t("multiple_dates", {
          first: new Date(1708935494000),
          second: new Date(1708935494000),
          formatParams: { first: format, second: format },
        })
      ).toEqual("Monday, February 26, 2024 - Monday, February 26, 2024");
    });
  });
});

```

## Expected behavior

I expect the test to succeed.

Instead, I currently get:

```
Expected: "Monday, February 26, 2024 - Monday, February 26, 2024"
Received: "Mon Feb 26 2024 09:18:14 GMT+0100 (Central European Standard Time) - Mon Feb 26 2024 09:18:14 GMT+0100 (Central European Standard Time)"
```

## Your Environment

- *runtime version*: node v12.22.9
- *i18next version*: 23.7.18
- *os*: Linux

**Comment by adrai** [comment]
seems to work: https://codesandbox.io/p/sandbox/optimistic-grothendieck-gcvnkm

try to change the variable names

**Comment by robin-xyzt-ai** [comment]
Changing the variable names indeed works, and I will do that in my project. Thanks for the quick response.

If there are any documented rules about the naming of those variables, I would appreciate a pointer to it. I searched the docs and couldn't find any.

**Comment by yann-combarnous** [comment]
> seems to work: https://codesandbox.io/p/sandbox/optimistic-grothendieck-gcvnkm
> 
> try to change the variable names

Sandbox expired, could somebody point me to the solution?
