### ISSUE TITLE
skipOnVariable not working for non key input in `t`

### ISSUE THREAD

**Issue by zemlint** [i18next/i18next#2153]
## 🐛 Bug Report

Expected Behavior: When calling `t` with a string that is not a key just the string gets returned. For example `t("This is not a key")` returns `"This is not a key"`. I could not find this behavior documented, but it kinda makes sense. 

Unexpected Behavior: If a nested variable is inside this string, the variable gets resolved, for example `t("Not a key with $t(variable)")` returns `"Not a key with <content of the variable>"`. This variable is even resolved when `{interpolation: {skipOnVariable:true}}` is explicitly set. 

## To Reproduce
Here is a minimal example of how to reproduce the behavior:

```js
import React from "https://cdn.skypack.dev/react";
import ReactDOM from "https://cdn.skypack.dev/react-dom";
import i18n from "https://cdn.skypack.dev/i18next";
import { useState } from "https://cdn.skypack.dev/react";
import {
  useTranslation,
  initReactI18next
} from "https://cdn.skypack.dev/react-i18next";

i18n
  .use(initReactI18next) 
  .init({
    resources: {
      en: {
        translation: {
          variable: "Hello World!"
        }
      },
      fr: {
        translation: {
          variable: "Bonjour Monde!"
        }
      }
    },
    lng: "en",
    fallbackLng: "en",
  });

function App() {
  const { t } = useTranslation();
  const [lang, setLang] = useState("en");

  return (
    <div>
      <h2>{t("Not a key $t(variable)", {interpolation: {skipOnVariable:true}})}</h2>
      <button
        onClick={() => {
          changeLang(lang);
        }}
      >
        Change language!
      </button>
    </div>
  );

  function changeLang(language) {
    i18n.changeLanguage(language, (err, t) => {
      if (err) return console.log("something went wrong loading", err);
      t("variable"); 
    });
    if (lang === "en") {
      setLang("fr");
    } else {
      setLang("en");
    }
  }
}

ReactDOM.render(<App />, document.getElementById("root"));
```

Running this renders `Not a key Hello World!` and `Not a key Bonjour Monde!` respectively

## Expected behavior

I would expect that the variable is not resolved if ` {interpolation: {skipOnVariable:true}}` is set. The rendered text should be `Not a key $t(variable)`

## Your Environment

- *runtime version*: v20.11.0
- *i18next version*: 23.10.0
- *react-i18next*: 14.0.5
- *os*: Mac, Linux

**Comment by adrai** [comment]
documented here: https://www.i18next.com/principles/fallback#key-fallback

what what you are referring to with $t(variable) is nesting: and is documented here: https://www.i18next.com/translation-function/nesting and works like that as expected

**Comment by zemlint** [comment]
Thanks for the quick answer!

Still I am confused why `skipOnVariable: true` does not work for the fallback. In the linked documentation 
```i18next.t('notExistingKey'); // -> "notExistingKey"```
 is written as an example for when the key is not found.
That is why I would expect 
`i18next.t("Not a key $t(variable)"; // -> "Not a key $t(variable)"` instead of 
`i18next.t("Not a key $t(variable)"; // -> "Not a key  Hello World!"`
 when  `skipOnVariable: true`

Is this wrong and I can't enable `skipOnVariable` for the fallback?

**Comment by adrai** [comment]
```js
const i18next = require('i18next')
i18next.init({
  lng: 'en',
  // interpolation: { // skipOnVariables by default true
  //   skipOnVariables: false
  // },
  resources: {
    en: {
      translation: {
        keyWithNesting: 'gets nested: $t(nested) | this is a variable: {{variable}}',
        anotherKey: 'value {{variable}}',
        nested: 'this is a nested key'
      },
    },
  },
})

console.log(i18next.t('anotherKey'))
console.log(i18next.t('anotherKey', { variable: 'whatever' }))

console.log(i18next.t('keyWithNesting', { variable: '$t(nested2)' }))

console.log(i18next.t('Not a key $t(anotherKey) | {{variable}}'))
console.log(i18next.t('Not a key $t(anotherKey) | {{variable}}', { variable: '$t(nested)' }))

```

with skipOnVariables: true (default), you will see this output:

```sh
value {{variable}}
value whatever
gets nested: $t(nested) | this is a variable: $t(nested2)
Not a key value {{variable}} | {{variable}}
Not a key $t(anotherKey) | $t(nested)
```

with skipOnVariables: false, you will see this output:

```sh
value
value whatever
gets nested: this is a nested key | this is a variable: nested2
Not a key value  |
Not a key value this is a nested key | this is a nested key
```

You see skipOnVariables only influences the nesting resolving behaviour if passed via variable...

everything that you pass to the t function is handled the same way, it doesn't matter if it is a known key or an not existing key...

so it works as designed
