### ISSUE TITLE
23.7.13 -> 23.7.14 Regression with 'Type instantiation is excessively deep and possibly infinite'

### ISSUE THREAD

**Issue by harry-gocity** [i18next/i18next#2154]
## 💥 Regression Report

I'm using `next-i18next` in a project with 7 namespaces. In upgrading that from 15.0.0 to 15.2.0 I started to see `Type instantiation is excessively deep and possibly infinite` with my `useTranslation` call.

I have narrowed this down to the underlying `i18next` dependency bumping from 23.7.13 -> 23.7.14. The issue persists with a bump to latest 23.10.0.

## Last working version

Worked up to version: 23.7.13

Stopped working in version: 23.7.14

## To Reproduce

I've tried to create a reproduction of this but have been unable to so far - but will keep trying to narrow down the issue. Sorry, I appreciate this isn't very helpful right now.

## Expected behaviour

Type definitions to work as before.

## Your Environment

- *runtime version*: Node 20 LTS
- *i18next version*: See above
- *os*: Mac
- *any other relevant information*

I saw from the release notes that the release was intended to `fix types for array access`. Are there any examples translation json structures that would be parsed differently before / after this release?

**Comment by adrai** [comment]
We really need a minimal reproducible example... 
This was the change: https://github.com/i18next/i18next/pull/2101
//cc @marcalexiei @Gotos

**Comment by Gotos** [comment]
Just as a heads-up: I'm currently sick and will likely not be able to look into this myself for at least a couple weeks; but as both of you correctly pointed out already anyway: without a minimal reproducible example, this is probably next to impossible to debug, anyway... :(

**Comment by harry-gocity** [comment]
Yep, I completely agree, I'll get a reproduction sorted. I don't expect help from maintainers until then, fwiw

**Comment by szimek** [comment]
I'm getting the same error after upgrading `i18next` and `react-i18next`. Here's a bit more about it: https://github.com/i18next/i18next/discussions/2246, but I don't have reproducible example yet. I'll see if I can create one, but it would most likely be to create a gigantic translations file (e.g. 10K values) and then see if e.g. the following code causes this error:

```ts
const t = ((key: string) => `localized ${key}`) as TFunction<'my-namespace', undefined>
```

**Comment by harry-gocity** [comment]
Going to close this as we solved this by generating a static type defintion from our content.

**Comment by fabiendem** [comment]
@harry-gocity thanks for the insight.
Could you just elaborate on _"by generating a static type defintion from our content"_ please?

For example Is `typeof` enough?
```ts
declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: "translation";
    resources: {
      someNamespace: typeof foobar;
.....
	}
}
```
where `foobar` is a Json structure.

Or do you have another solution in mind?

**Comment by harry-gocity** [comment]
We pull content from our CMS, and then use https://quicktype.io/ to generate a type def from it. Then reference that in the i18next module. Looks a bit like this:

```shell
pnpm exec quicktype public/locales/en/common.json -o src/types/i18n/common.ts -t common --prefer-const-values --prefer-types --just-types --no-combine-classes --no-maps
```

```ts
import { Common } from "@/types/i18n/common";

declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: "common";
    resources: {
      common: Common;
       .....
    }
}
```

We have a script to pull content from the CMS, and the generation script is run directly after. But you can run the generation script by yourself.
