### ISSUE TITLE
Translations are not working when network connection is down

### ISSUE THREAD

**Issue by FustaNivago** [i18next/i18next#2156]
## 🐛 Bug Report

I have an ReactJS app and I load the translation files from backend. When internet connection is down (or API does not respond for some reason) translation does not work.

## To Reproduce

Run the application, at some point disable internet connection (make backend unreachable) - you will get an keys instead of values.
Here is my configuration:

```js
i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init<HttpBackendOptions>({
    ns: [],
    defaultNS: undefined,
    fallbackLng: 'uk',
    debug: false,
    load: 'languageOnly',
    partialBundledLanguages: false,

    interpolation: {
      escapeValue: false,
    },

    initImmediate: false,

    backend: {
      loadPath: `${import.meta.env.VITE_API_BASE_URL}/media/GetLocalization?c={{lng}}&d=${new Date().getMonth()}- ${new Date().getDate()}`,
    },
  });
```

Even though i18next was inited before and i18next.store has the data it does not work

![image](https://github.com/i18next/i18next/assets/161255125/a69805dd-721c-47f4-bc5e-a77993208dda)

## Expected behavior

Temporary connection issues should not affect i18next, at least until language is switched.

## My Environment

- *runtime version*: i.e. node v18.12.1
- *i18next version*: 23.8.2
- *os*: Windows

**Comment by adrai** [comment]
it will only work if the translations have been preloaded (all required namespaces)....
alternatively have a look at: https://www.i18next.com/how-to/caching
or: https://www.i18next.com/how-to/backend-fallback

**Comment by FustaNivago** [comment]
> it will only work if the translations have been preloaded (all required namespaces).... alternatively have a look at: https://www.i18next.com/how-to/caching or: https://www.i18next.com/how-to/backend-fallback

Thank you for the response. In my case I don't have any namespaces, there is only one json "file" which obviously has been loaded before any connection issues... I thought it should work offline. Regarding the cache - it is not an option for me, as the application is supposed to have an updates quite often.

**Comment by adrai** [comment]
If the translations are loaded there should be no additional request and the translations should work...
If that's not the case, please provide a minimal reproducible example.

**Comment by FustaNivago** [comment]
Was unable to respond earlier.
My bad, the issue was in 
import { t } from 'i18next';
I didn't notice missing useTranslation hook.
Thank you for your patience)
