### ISSUE TITLE
ASCII Decoding

### ISSUE THREAD

**Issue by ChristianReguzzoniPLRM** [i18next/i18next#2157]
## 🐛 Bug Report

Decoding ASCII code not working when namespace is different from the default one.

## To Reproduce
Example input loaded in moduleA, moduleB:
```json
{
    "myKey": "N/mm&#178;"
}
```
Example code like https://www.i18next.com/principles/namespaces:
```ts
i18next.init({
  ns: ['moduleA', 'moduleB'],
  defaultNS: 'moduleA'
}, (err, t) => {
  i18next.t('myKey'); // right output as expected: N/mm²
  i18next.t('moduleB:myKey'); // unexpected output: N/mm&#178;
  i18next.t('myKey', { ns: 'moduleB' }); // unexpected output: N/mm&#178;
});
```
myKey is decoded successfully only when namespace is the default one.
## Environment

- *runtime version*: node v21.7.0
- *i18next version*: 23.10.0
- *os*: Windows

**Comment by adrai** [comment]
I'm not able to reproduce it...
In Node.js (server side) I get this:

```js
const i18next = require('i18next')

i18next.init({
  lng: 'en',
  ns: ['moduleA', 'moduleB'],
  defaultNS: 'moduleA',
  resources: {
    en: {
      moduleA: {
        myKey: 'A: N/mm&#178;'
      },
      moduleB: {
        myKey: 'B: N/mm&#178;'
      }
    }
  }
}, (err, t) => {
  console.log(i18next.t('myKey')); // A: N/mm&#178;
  console.log(i18next.t('moduleB:myKey')); // B: N/mm&#178;
  console.log(i18next.t('myKey', { ns: 'moduleB' })); // B: N/mm&#178;
});
```

in browser I get this: https://codesandbox.io/p/sandbox/kind-dubinsky-34z7k8?file=%2Fsrc%2Findex.mjs
<img width="196" alt="image" src="https://github.com/i18next/i18next/assets/1086194/904d3f91-f1a4-437f-8401-f9fade9df3fd">
