### ISSUE TITLE
Generate locale files automatically?

### ISSUE THREAD

**Issue by karellm** [i18next/i18next#216]
Hi,

Is there a way to make the locales files automatically generated every time the code run into a `t()` instance?

Coming from gettext, softwares like poedit would parse my code and maintain my catalog; letting me know which ones are not use anymore, which ones are new... 

I would use this software if it wasn't for handlebars (poedit has trouble parsing them). How do you deal with this?

**Comment by julmot** [comment]
@jamuhl Sorry for catching up on such an old issue, but I'm also asking myself on how to export a po-file that I can import into a CMS my app relies on that has already a good UI interface for translation?

I imagine a tool that does integrate with npm and catches all `t()` method calls and generates a po-file that I can use to import it manually into a CMS. Then I can use the REST API of that CMS in the application.

**Comment by jamuhl** [comment]
have a look at extraction tools here: https://www.i18next.com/plugins-and-utils.html#utils

use the gettext-converter in the same list to get a .po file from json

Or even better...have a look at https://locize.com and support the people working on i18next with a subscription -> all missings get passed to the project there, comes with export for all needed formats.
