### ISSUE TITLE
RangeError: Maximum call stack size exceeded at deepExtend

### ISSUE THREAD

**Issue by shalineepatel** [i18next/i18next#2160]
Hello,

We recently upgraded our project to react v18 and typescript v5. Also did upgrade i18next as well.  And now getting this error at deepExtend.

Below are the versions we currently have.

"i18next": "^23.8.2"
"i18next-browser-languagedetector": "^7.2.0"
"react-i18next": "^14.0.5"

![image](https://github.com/i18next/i18next/assets/61513687/e7c5d2e0-c2c0-4683-8a44-85b6dab363a4)

![image](https://github.com/i18next/i18next/assets/61513687/99acbfae-5941-40f2-9cd1-13387392cd1a)

Here is the code:

const handleCurrentLanguage = async (currentLanguage: string) => {
    sessionStorage.setItem("language", currentLanguage);
    setCurrentLanguage(currentLanguage);
    const translationKey = getLanguageByKey(currentLanguage).translationKey;
    const fileName = getLanguageByKey(currentLanguage).fileName;
    const res = await loadJson(fileName);
    if (res) {
      i18n.addResourceBundle(translationKey, "translation", res, true, true);
      i18n.changeLanguage(translationKey, () => {
        moment.locale(translationKey);
      });
    }
  };
  
 I tracked it happens at i18n.addResourceBundle. Is there any way we could fix it? Thanks in advance!

**Comment by adrai** [comment]
Please provide a reproducible example (codesandbox or repository)... not just code snippets

**Comment by shalineepatel** [comment]
Figured the issue. It was happening because the json data was having nested default key. Fixed the way were importing the data and its not happening anymore. Closing the ticket.
