### ISSUE TITLE
Get the wrong API call

### ISSUE THREAD

**Issue by StevenWang20230313** [i18next/i18next#2163]
When I use i18n.changeLanguage(value) in my react app, I input value=fr-CA, but the API call is https://xxx.com/locales/fr/translation.json. I have a folder named fr-CA in locales folder, but don't have fr folder. So, always get this error: `i18next::backendConnector: loading namespace translation for language it failed failed parsing /locales/fr/translation.json to json`. I can get the translated words, but in the console, always get the error. Why? Thank you!

**Comment by StevenWang20230313** [comment]
I found a same one.

**Comment by adrai** [comment]
define the supportedLngs option or set the load option accordingly to currentOnly
https://www.i18next.com/overview/configuration-options

**Comment by StevenWang20230313** [comment]
> define the supportedLngs option or set the load option accordingly to currentOnly https://www.i18next.com/overview/configuration-options

I solved the problem. List it here for those who need help: The reason is missing a setting in i18n.init. I did not set {load: 'currentlyOne'}. So, the package will call fr-CA and fr, but I don't have a translation file for fr. So, the call for fr always show errors.
