### ISSUE TITLE
React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render.

### ISSUE THREAD

**Issue by pj-alvarado10** [i18next/i18next#2164]
## 🐛 Bug Report

In the analysis of the sonarQube, the file of client (i18n/client) mark this issue:

`React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render.`

## To Reproduce

The code is copy of the documentation, in a Nextjs app:

```ts
export function useTranslation(lng:any, ns:any, options:any) {
  const ret = useTranslationOrg(ns, options)
  const { i18n } = ret
  if (runsOnServerSide && lng && i18n.resolvedLanguage !== lng) {
    i18n.changeLanguage(lng)
  } else {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const [activeLng, setActiveLng] = useState(i18n.resolvedLanguage)
    // eslint-disable-next-line react-hooks/rules-of-hooks
    useEffect(() => {
      if (activeLng === i18n.resolvedLanguage) return
      setActiveLng(i18n.resolvedLanguage)
    }, [activeLng, i18n.resolvedLanguage])
    // eslint-disable-next-line react-hooks/rules-of-hooks
    useEffect(() => {
React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render.
      if (!lng || i18n.resolvedLanguage === lng) return
      i18n.changeLanguage(lng)
    }, [lng, i18n])
  }
  return ret
}
```

## Expected behavior

The sonarQube must not mark the issue.

## Your Environment

- *runtime version*: node v18, nextjs 14, typescript.
- *i18next version*: latest

**Comment by jamuhl** [comment]
but that is not our useTranslation code: https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js

**Comment by pj-alvarado10** [comment]
Hi, I'm sorry, I didn't explain well. When I implement the code of the documentation in my Nexts app like the section 5. Client Side,  of this [article found in the official web](https://locize.com/blog/next-app-dir-i18n/), the code works perfectly, but in SonarQube, the issue _React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render_ is marked because useEffect is inside of an else clause.

I don't know if I must mark like false positive the issue in SonarQube or something.
Thank you so much.

**Comment by adrai** [comment]
there's a `eslint-disable-next-line react-hooks/rules-of-hooks` on purpose...

**Comment by pj-alvarado10** [comment]
Thank you for your answer!
