### ISSUE TITLE
Allow default value in nested translation

### ISSUE THREAD

**Issue by bschoenmaeckers** [i18next/i18next#2174]
## 🚀 Feature Proposal

Currently I don't think its possible to provide a default value for when a nested translations cannot be found.

## Motivation

When templating nested translations, its posible that the nested key is not present, so it would lead to a broken translation.

## Example

Given the following translation file:
```json
{
  "message": "Something went wrong: $t(error_code.{{error_type}}, {\"defaultValue\": \"Unknown error\"})"
  "error_type": {
    "it_error": "it went wrong"
  }
}
```

`t('message', {error_type: 'other_error'}) ` will translate to `"Something went wrong: error_code.other_error"` but I would like it to translate to `"Something went wrong: Unknown error"`.

**Comment by adrai** [comment]
There are 2 options:

**Option 1:** Use multiple fallback keys like described here: https://www.i18next.com/translation-function/essentials#multiple-fallback-keys

```js
import i18next from 'i18next';

i18next.init({
    fallbackLng: 'en',
    resources: {
        en: {
            translation: {
                message: "Something went wrong:",
                error: {
                    "unspecific": "$t(message) Unknown error",
                    "it_error": "$t(message) it went wrong"
                }
            }
        }
    }
})

const existingError = 'it_error'
const nonExistingError = 'other_error'

console.log(i18next.t([`error.${existingError}`, 'error.unspecific']))
console.log(i18next.t([`error.${nonExistingError}`, 'error.unspecific']))
```

**Option 2:** Update i18next to v23.11.2 ;-)

**Comment by bschoenmaeckers** [comment]
Wow that was quick. Tnx!

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
