### ISSUE TITLE
Autocompletion doesn't work on large files in webstorm

### ISSUE THREAD

**Issue by bi-zi** [i18next/i18next#2175]
## 🐛 Bug Report

If you compile all .json files into one big json with 1500+ lines, autocomplete stops working only in webstorm (everything is fine in vscode). At the same time webstorm detects the key type correctly and cusses if the key is written incorrectly.

## To Reproduce

src/@types/resources.ts
```js
import global from "public/locales/ru/global.json";

export const resources = {
    global,
} as const;
```

src/@types/i18next.d.ts
```js
import { resources } from "./resources";

declare module "i18next" {
    interface CustomTypeOptions {
        resources: typeof resources;
    }
}
```
Large json webstorm
![image](https://github.com/i18next/i18next/assets/76881636/736b281c-f96e-48ad-8e7f-1dd75360f1e4)

Small json webstorm
![image](https://github.com/i18next/i18next/assets/76881636/fa59e058-3b92-44d6-a9b1-a716d6534d8e)

Large json vscode
![image](https://github.com/i18next/i18next/assets/76881636/f5e32513-cd23-46bd-8f2f-0e82bdf9ec1b)

## Expected behavior

webstorm should display autocomplete when using large json files

## Your Environment

"i18next": "23.11.2",
"react-i18next": "14.1.0",
"typescript": "5.4.5",

**Comment by marcalexiei** [comment]
If autocomplete is not working only on webstorm I don’t see why this is a i18next issue. 
You should open an issue to your IDE bug tracker.
