### ISSUE TITLE
Unsupported language is automatically added to preload option

### ISSUE THREAD

**Issue by develohpanda** [i18next/i18next#2178]
Hi there,

On my express server, I am using the `supportedLngs` and `preload` options, and `i18next-http-backend` is configured to reload resources at a specified interval, via the `reloadInterval` option.

My array of supported languages is `['en-US', 'fr-FR']`, for example.
My `preload` array is also `['en-US', 'fr-FR']`.
I have `fallbackLng` configured such that when loading `en-NZ`, the fallback of `en-US` will be used, because `en-NZ` is not supported and my backend will return an error.

The issue I am facing is with the following line in particular, which _extends_ the `preload` array with any new languages that are encountered, even if they are unsupported.

https://github.com/i18next/i18next/blob/c9e2bf5a1eeff27dd017eb068314377b0990d081/src/i18next.js#L500

Thus, what I observe is that during normal operation where i18n has only seen requests for `en-US` or `fr-FR`, those two languages are reloaded periodically. 

But when a request comes through asking for `en-NZ` translations (perhaps via the Accept-Language header), although i18n will fallback to en-US correctly, the periodic reload continues to include `en-NZ`. Thus I see successful reloads of `en-US` and `fr-FR` as expected, but also failures of loading the translations for `en-NZ`, which will always fail as it is unsupported.

Is this a bug? Should the extension of the preload array be opt-in, or conditional on it being a part of supported languages? I'm not quite sure what the process should be here, but extending the user-configured preload array without any check feels a bit fishy. What would you suggest?

```
    "i18next": "^23.10.1",
    "i18next-http-backend": "^2.5.0",
    "i18next-http-middleware": "^3.5.0",
```

I can share a minimal reproduction if that will help. Thank you in advance!

**Comment by adrai** [comment]
Extending the preload option is expecetd... but I agree that only supportedLngs should be handled...
So v23.11.3 should address this.

**Comment by develohpanda** [comment]
Wonderful, thank you for such a quick response! I’ll test it out tomorrow 🎉

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏

**Comment by adrai** [comment]
The main question is: why are you trying to avoid those requests?
How is the error influencing your app?

**Comment by adrai** [comment]
if you have a known list of supported (regional) languages, just add them via supportedLngs...

**Comment by develohpanda** [comment]
It doesn't make a difference if I add them via `supportedLngs`.

Regardless of `supportedLngs` being `['en', 'fr']` or `['en', 'en-US', 'fr', 'fr-FR']`, the `nonExplicitSupportedLngs` property still needs to be true to accept `en-NZ`, and `fallbackLng` still needs to be set to normalize from `en-NZ -> en -> en-US`.

Here's a different question for you - is there a better way for me to normalize from `en-NZ` to `en-US`?

**Comment by adrai** [comment]
You could write your own language detector...

**Comment by adrai** [comment]
You could also just use the `convertDetectedLanguage` option...

https://github.com/i18next/i18next-browser-languageDetector

```js
convertDetectedLanguage: (lng) => {
  if (lng === 'en-NZ') return 'en-US'
  return lng
}
```

**Comment by develohpanda** [comment]
I do want to keep the bells and whistles of the i18next language detector, however `convertDetectedLanguage` may just cater for everything… I will try it out and report back! 😊

**Comment by develohpanda** [comment]
It seems `convertDetectedLanguage` isn't being hit at all on the http middleware language detector (the https://github.com/i18next/i18next-http-middleware/blob/master/lib/LanguageDetector.js within `i18next-http-middleware`) each time a new request comes in 🤔 that checks out, as I don't see any code to handle that property

**Comment by adrai** [comment]
It was not yet implemented.... please try with v3.6.0

**Comment by develohpanda** [comment]
Tried with 3.6.0 - while that does work to normalize the detected language, the original language (`en-NZ`) still does ends up in the preload array :(
