### ISSUE TITLE
Better API for plurals, for better extraction

### ISSUE THREAD

**Issue by joshhunt** [i18next/i18next#2180]
## 🚀 Feature Proposal

A new API for specifying plurals in code, with explicit default messages for all plural forms.

## Motivation

Many people's i18n workflow is to write default phrases in UI code with explicit keys with  `t()` / `<Trans />`, and then extract them with i18next-parser.

Plurals make this very awkward because there's no way to extract additional plural forms from source code, so you must write one form in code, run i18n-parser, then go edit the json messages file with the additional forms. It also means there's no single source of truth for phrases, as additional plural forms would _only_ live in the json messages file.

## Example

```ts
t.plural("inbox.new-messages", {
  other: "You have {count} new messages",
  one: "You have {count} new message"
}, { count })
```

I can't really see a great API for supporting this with the React `<Trans />`.

---

If accepted, I'm happy to work on this and contribute it to i18next, and the required changes to i18next-parser.

See also https://github.com/i18next/i18next-parser/issues/998

**Comment by jamuhl** [comment]
defaultValues already supports defining plural forms: https://www.i18next.com/translation-function/essentials#overview-options

**Comment by joshhunt** [comment]
Ahhh - good catch. I had not noticed that. 

Personally, I think that API is kind of awkward, but happy to give it a go 👍
