### ISSUE TITLE
Typescript error : can not access array elements

### ISSUE THREAD

**Issue by army-u8** [i18next/i18next#2189]
## 💥 Regression Report

 Appears  type error when I use the json file as a resource ,but translations to a object  using as const, it'll work.
<img width="484" alt="image" src="https://github.com/i18next/i18next/assets/106830983/f6e343ea-b3e6-4057-95ba-19a119afab9e">
<img width="504" alt="image" src="https://github.com/i18next/i18next/assets/106830983/1df0fbdf-f1f8-493b-afea-196e8a22416c">

## Last working version

Worked up to version: 23.11.3

Stopped working in version: 23.11.3

## To Reproduce

`HTTP.json`
```json
{
  "403": "403 Forbidden \n You don’t have permission to access this page.",
  "500": "Looks like the server is taking too long to respond, this can be caused by either poor connectivity or an error with our servers. Please try again in a while.",
  "503": "Service temporarily unavailable.",
  "501": ["a", "b", "c", "d", "e"]
}

```
```js
import HTTP from './HTTP.json';
const defaultNS = 'general';
const httpCode = {
  '403': '403 Forbidden \n You don’t have permission to access this page.',
  '500':
    'Looks like the server is taking too long to respond, this can be caused by either poor connectivity or an error with our servers. Please try again in a while.',
  '503': 'Service temporarily unavailable.',
  '501': ['a', 'b', 'c', 'd', 'e'],
} as const;
export const resources = {
  en: {
    general: {
      http: HTTP,
    },
  },
} as const;
i18next.init({
  lng: 'en',
  debug: true,
  defaultNS,
  resources,
});
```
```js
i18n.d.ts
declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: typeof defaultNS;
    resources: (typeof resources)["en"];
  }
}
```

https://stackblitz.com/edit/solidjs-templates-zghu8f?file=src%2Fi18n.ts,src%2FApp.tsx,src%2Fi18n.d.ts,src%2FHTTP.json,tsconfig.json

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 23.11.3
- *os*: Mac,

**Comment by adrai** [comment]
I don't think this was working before v23.11.3...
That's probably because of the number...

**Comment by army-u8** [comment]
And  also  type issue that if i use `snake_case` in json the generate new field as `snakease`
```json
{
    "403": "403 Forbidden \n You don’t have permission to access this page.",
    "500": "Looks like the server is taking too long to respond, this can be caused by either poor connectivity or an error with our servers. Please try again in a while.",
    "503": "Service temporarily unavailable.",
    "error_code": "error"
}
```
```js
i18next.init({
  lng: "en",
  debug: true,
  ns,
  defaultNS,
  resources,
});
```

<img width="529" alt="image" src="https://github.com/i18next/i18next/assets/106830983/d998dd4a-24c6-4962-9b9f-d7eb0efa6dc5">

**Comment by adrai** [comment]
Like said... you need the as const or an interface: https://www.i18next.com/overview/typescript#not-working-interpolation-values
