### ISSUE TITLE
Multiple namespaces not working after upgrading to version 21

### ISSUE THREAD

**Issue by fromi** [i18next/i18next#2195]
## 💥 Regression Report

I try to upgrade to from v20.6.1 to v21.10.0
This used to work:
`const { t } = useTranslation(['translation', game.boardGame.id])`
`{t('Discover')}`
`{t(`${boardGame.id}|Name`)}`
And in some sub components:
`const { t } = useTranslation([game.boardGame.id, 'translation'])`
`{t('translation|Discover')}`
`{t(`Name`)}`

Now, inside sub components, it is like I can no longer switch the default namespace defined in the parent component.
Might be a bad practice, but it stop working exactly when I try to upgrade i18next from 20.x to 21.x

## Last working version

Worked up to version: 20.6.1

Stopped working in version: 21.10.0

## Configuration

```js
export default function createI18nInstance(language = 'en') {
  const i18n = i18next.createInstance({
    lng: language,
    fallbackLng: 'en',
    keySeparator: false,
    nsSeparator: '|',
    resources: translations
  })
  return i18n
}


```

**Comment by adrai** [comment]
Please provide a minimal reproducible example repository or codesandbox... (if possible, without react-i18next)
Also have a look at: https://www.i18next.com/misc/migration-guide#v20.x.x-to-v21.0.0

**Comment by adrai** [comment]
if it's reproducible only in combination with react-i18next make sure, you use the newest versions of i18next and react-i18next

**Comment by fromi** [comment]
Hi @adrai ,
I started by migrating both i18next & react-i18next to their latest versions. I noticed the bug, so I isolated the specific upgrade that causes the regression: that's upgrading i18next from v20 to v21.
So I red carefully the migration guide for this upgrade, but there is nothing here about my issue.
I did some tests and refactoring: it turn out that what is no longer working is using multiple namespaces in the same component.
I will do codesandbox if I cannot fix the issue in a reasonable time, but any hint about why using multiple namespace could break in v21 would be nice!

**Comment by fromi** [comment]
It turn out this does not work: `t('translation|Random selection')`
But this works: `t('Random selection', {ns: 'translation'})`
[This documentation](https://react.i18next.com/guides/multiple-translation-files) says:
```
i18next.t('common:look.deep'); // not recommended with ns prefix when used in combination with natural language keys
// better use the ns option:
i18next.t('look.deep', { ns: 'common' })
```
However, I should not have that natural language detection feature, because the [migration guide](https://www.i18next.com/misc/migration-guide#natural-language-detection) says:
"In case you want to skip this natural language detection, provide a keySeparator and/or a nsSeparator option."
I have this configuration:
```
    keySeparator: false,
    nsSeparator: '|',
```
So I thing the migration guide is lacking somewhere.

**Comment by adrai** [comment]
works here: https://codesandbox.io/p/sandbox/i18next-ns-sep-test-r3sc9r?file=%2Fsrc%2Findex.mjs

**Comment by fromi** [comment]
I tried to reproduce a minimal example with react-i18next but I cannot reproduce it either.
Maybe next.js is interfering at some point... The only thing I now is that natural language detection feature causes some unexpected regression on my project. I need to rewrite some code in a different way.
