### ISSUE TITLE
Ordinals in non-english languages

### ISSUE THREAD

**Issue by isimisi** [i18next/i18next#2200]
## 🐛 Bug Report

When using ordinals in react-i18next [^1], I have issues when trying to translate to swedish - it seems like it will always default to key_ordinal_other, instead of using the provided key_ordinal_one and key_ordinal_two

I've followed [this documentation](https://www.i18next.com/translation-function/plurals#ordinal-plurals) on the matter

What actually happens using the swedish language:

```js
t("num", { count: 2, ordinal: true}) // 2:e <-- This should be 2:a
t("num", { count: 6, ordinal: true}) // 6:e
```

## To Reproduce

What I've done can be seen on [this sandbox](https://codesandbox.io/p/sandbox/react-i18next-forked-nhlflm?file=%2Fsrc%2Findex.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwhr5lld00063b6n5m2rks8m%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwhr5lld00023b6n9l85kdxb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwhr5lld00033b6nuibqg7es%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwhr5lld00053b6n2ldr5kdg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwhr5lld00023b6n9l85kdxb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwhr5lld00013b6nv0ncqhc7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwhr698n00353b6nte0fpq7w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A56%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A56%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fi18n.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwhr5lld00023b6n9l85kdxb%2522%252C%2522activeTabId%2522%253A%2522clwhr5lld00013b6nv0ncqhc7%2522%257D%252C%2522clwhr5lld00053b6n2ldr5kdg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwhr5lld00043b6nmtx54mmt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwhr5lld00053b6n2ldr5kdg%2522%252C%2522activeTabId%2522%253A%2522clwhr5lld00043b6nmtx54mmt%2522%257D%252C%2522clwhr5lld00033b6nuibqg7es%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwhr5lld00033b6nuibqg7es%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

```js
import i18n from "i18next";
import LanguageDetector from "i18next-browser-languagedetector";
import { initReactI18next } from "react-i18next";

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    // we init with resources
    resources: {
      en: {
        translations: {
          "Welcome to React": "Welcome to React and react-i18next",
          num_ordinal_one: "{{count}}st", // 1st, 21st, 31st
          num_ordinal_two: "{{count}}nd", // 2nd, 22nd, 32nd
          num_ordinal_few: "{{count}}rd", // 3rd, 23rd, 33rd
          num_ordinal_other: "{{count}}th", // 4th, 5th, 24th
        },
      },
      se: {
        translations: {
          "Welcome to React": "Välkommen till React och react-i18next",
          num_ordinal_one: "{{count}}:a", // 1:a, 21:a, 31:a
          // num_ordinal_two: "{{count}}:a", // 2:a, 22:a, 32:a [^2]
          num_ordinal_other: "{{count}}:e", // 3:e, 4:e, 5:e, 24:e
        },
      },
    },
    fallbackLng: "en",
    debug: true,

    // have a common namespace used around the full app
    ns: ["translations"],
    defaultNS: "translations",

    keySeparator: false, // we use content as keys

    interpolation: {
      escapeValue: false,
    },
  });

export default i18n;
```
[^2]

## Expected behavior

What is to be expected when using the english language (also what happens):

```js
t("num", { count: 2, ordinal: true}) // 2nd
t("num", { count: 6, ordinal: true}) // 6th
```

what is to be expected when using the swedish language:

```js
t("num", { count: 2, ordinal: true}) // 2:a
t("num", { count: 6, ordinal: true}) // 6:e
```

What actually happens using the swedish language:

```js
t("num", { count: 2, ordinal: true}) // 2:e <-- This should be 2:a
t("num", { count: 6, ordinal: true}) // 6:e
```

## Your Environment

- *runtime version*: node v20.11.1
- *i18next version*: v23.11.5
- *os*: Mac

[^1]: I know this isn't react-i18next, but the bug feels more related to i18next
[^2]: [Made aware that swedish language only has ordinal plural rule one and other](https://github.com/i18next/i18next/issues/2200#issuecomment-2127099836)

**Comment by jamuhl** [comment]
swedish does not have any ordinal plural rule beside other: https://www.unicode.org/cldr/charts/45/supplemental/language_plural_rules.html#sv

**Comment by isimisi** [comment]
> swedish does not have any ordinal plural rule beside one and other: https://www.unicode.org/cldr/charts/45/supplemental/language_plural_rules.html#sv

Well, it doesn't work with 'one' either.

1 will still be 1:e and 21 -> 21:e while they should be 1:a and 21:a

also, 2 should be 2:a not 2:e (as shown in the linked you provided, the tabel has the following: 1, **2**, 21, **22**, 31, **32**, 41, **42**, 51, **52**, 61, **62**, 71, **72**, 81, **82**, 101, 1001, …)

**Comment by jamuhl** [comment]
swedish language code is `sv` not `se`

se is nothern sami https://www.unicode.org/cldr/charts/45/supplemental/language_plural_rules.html#se (which has no ordinal)
