### ISSUE TITLE
Typescript error using t('key'), always need to specify namespace

### ISSUE THREAD

**Issue by lionel95200x** [i18next/i18next#2203]
## 🐛 Bug Report

After following exactly the document provided [here](https://www.i18next.com/overview/typescript#not-working-interpolation-values) to type correclty my translation key, i hope to use `t('key')` with a fully typed on my translation function
But on my simple stackblitz example, i always need to prefix my key with namespace , even if i import it correctly in `useTranslation('ns1')`

## To Reproduce

A [stackblitz exemple here](https://stackblitz.com/edit/react-ts-fbomdv?file=App.tsx) 

```js
const TranslationItem = () => {
  const { t } = useTranslation('ns1');

  return (
    <div>
      <div>Type Error : {t('title')}</div>
      <div>No Type Error : {t('ns1:title')}</div>
    </div>
  );
};
```

## Expected behavior

Use the key correctly when i specify a namespace, i should use the simple key without prefixing with `ns1:`

```js
const TranslationItem = () => {
  const { t } = useTranslation('ns1');

  return (
    <div>
      <div>Works well : {t('title')}</div>
    </div>
  );
};
```

## Your Environment

- *runtime version*: i.e. node v20
- *i18next version*: i.e. 19.5.3
- *os*: Mac

**Comment by adrai** [comment]
I'm not a ts pro, but I suspect a tsconfig issue?
@marcalexiei ?
