### ISSUE TITLE
Method i18next.setDefaultNamespace doesn't support array

### ISSUE THREAD

**Issue by realgvard** [i18next/i18next#2208]
## 🐛 Bug Report

I believe the type in [setDefaultNamespace](https://github.com/i18next/i18next/blob/master/index.d.ts#L360-L363) method is wrong since a namespace could be `string` and `readonly string[]`.

## Expected behavior

From my point of view this method should support arrays.

```typescript
  setDefaultNamespace(ns: string | readonly string[]): void;
```

### Your Environment

* Version **23.11.5**

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this?

**Comment by realgvard** [comment]
Will do

**Comment by adrai** [comment]
fyi: https://github.com/i18next/i18next/pull/2259

**Comment by adrai** [comment]
included in v24
