### ISSUE TITLE
Add posibility to override keyPrefix for certain translation.

### ISSUE THREAD

**Issue by Helios69** [i18next/i18next#2211]
## 🚀 Feature Proposal

Add posibility to override keyPrefix for certain translation.

## Motivation

When having very long paths (super.long.path.to.the.translation), wil be very nice to have posibility to override this keyPrefix for other translations (some common translations for example).

## Example

```
const { t } = useTranslation("translation", { keyPrefix: "super.long.path.to.the.translation" });

const prefixedTranslation = t("submit");
const unprefixedTranslaton = t("somethingCommon", { keyPrefix: "" });
```

**Comment by jamuhl** [comment]
@adrai should be rather simple: https://github.com/i18next/i18next/blob/master/src/i18next.js#L393 must be changed to allow empyt string in options.keyPrefix

**Comment by adrai** [comment]
v23.12.0 should allow that....
