### ISSUE TITLE
Nested translation resolution between languages uses the fallback language for nested translations

### ISSUE THREAD

**Issue by Jazzmanpw** [i18next/i18next#2216]
## 🐛 Bug Report

Unexpected translation resolution takes place in case of translation nesting. You can see it in the example, but in a few words: English is default, French is another language; we have the `one_dollar` key that's translated as `$$t("one")`, resulting into _$one_ in English and _$un_ in French (expectedly), but i18next actually produces _$one_ in both cases

## To Reproduce

A [codesandbox](https://codesandbox.io/p/sandbox/nostalgic-robinson-sdqy7l) example

```json
// /en/translations.json
{
  "one": "one",
  "one_dollar": "$$t(one)"
}
```

```json
// /fr/translations.json
{
  "one": "un"
}
```

```js
i18next
  .init({
    resources: {
      en: {
        translations: translationsEn,
      },
      fr: {
        translations: translationsFr,
      },
    },
    supportedLngs: ["en", "fr"],
    fallbackNS: "translations",
    defaultNS: "translations",
    fallbackLng: "en",
    defaultLng: "en",
  })
  .then((t) => {
    t("one_dollar"); // resolves to $one in both languages
  });
```

## Expected behavior

```js
// With the previous setup, expect this
t("one_dollar")
// to be $one in English and $un in French
```

## Your Environment

- *runtime version*: Chrome 126.0.6478.127
- *i18next version*: 23.11.1
- *os*: Windows

**Comment by adrai** [comment]
Not able to reproduce...

```js
i18next
  .init({
    resources: {
      en: {
        translations: {
          "one": "one",
          "one_dollar": "$$t(one)"
        },
      },
      fr: {
        translations: {
          "one": "un"
        },
      },
    },
    supportedLngs: ["en", "fr"],
    fallbackNS: "translations",
    defaultNS: "translations",
    fallbackLng: "en",
    defaultLng: "en",
  })
  .then((t) => {
    console.log('en: ' + t("one_dollar", { lng: 'en' })); // en: $one
    console.log('fr: ' + t("one_dollar", { lng: 'fr' })); // fr: $un
  });
```

**Comment by Jazzmanpw** [comment]
Sorry, I somehow copied wrong link to the codesandbox, now updated

I'm not talking about passing a language to `t` call. It's broken if I use `i18next.changeLanguage()`

**Comment by adrai** [comment]
Please try with v23.12.2

**Comment by Jazzmanpw** [comment]
yes, not it works! thank you 🙏 lightning-fast fix
