### ISSUE TITLE
Using a comma in a formatter parameter

### ISSUE THREAD

**Issue by robross0606** [i18next/i18next#2225]
## 🐛 Bug Report

As per discussion in #2125, It should be possible to create a custom formatter function where you can pass in a `separator` parameter.  So I have created this:

```js
function joinFormatter(value, lng, options = {}) {
  const { separator = DEFAULT_LIST_SEPARATOR } = options
  let retVal
  if (typeof value?.join === 'function') {
    retVal = value.join(separator)
  } else {
    retVal = value
  }
  return retVal
}
```
This works fine as long as the `separator` parameter does not itself contain a `,`.  So this works in a locale file:

```js
"All associated sections are locked: {{- unlockedSections, quote, join(separator:' | ')}}"
```
![image](https://github.com/user-attachments/assets/05ed4860-0796-456a-ac1e-2d3708b4dea2)

With resulting string of:
```
"One or more associated sections are unlocked: 'Schedule of Activities' | 'Trial Arm Elements'"
```

If you attempt to use a `,` character anywhere in the value for `separator` what ends up being passed into the custom formatter for `separator` is `NaN`.

```js
"All associated sections are locked: {{- unlockedSections, quote, join(separator:', ')}}"
```

![image](https://github.com/user-attachments/assets/7a11c048-7235-4122-a3de-bd61a5d8a356)

With resulting string of:
```
"One or more associated sections are unlocked: 'Schedule of Activities'NaN'Trial Arm Elements'"
```
## Your Environment

- *runtime version*: Node v18.20.3
- *i18next version*: 23.11.1
- *os*: Microsoft Windows [Version 10.0.19045.4717]

**Comment by robross0606** [comment]
Interestingly, if I do something like this as a test:
```
"All associated sections are locked: {{- unlockedSections, quote, join(separator:' premark,postmark  ')}}"
```
The results are:
![image](https://github.com/user-attachments/assets/df7aa5da-31c6-4aef-8883-b4f2ff3fb8e9)

```
"One or more associated sections are unlocked: 'Schedule of Activities' premar'Trial Arm Elements'"
```
Clearly the comma is being misinterpreted by the locale string parser.

**Comment by adrai** [comment]
Yes, that's because of the formatSeparator in the Formatter...

I've tried a little hack in v23.12.3

**Comment by robross0606** [comment]
"a little hack" makes me nervous. 😄 

Would that hack work properly if there was more than one formatter with the same problem in it?

**Comment by adrai** [comment]
should work... but you need to try it...
currently afk
