### ISSUE TITLE
Failed to set a embedded translation with a backend translation

### ISSUE THREAD

**Issue by JobberRT** [i18next/i18next#2228]
## 🐛 Bug Report

I want to set a predefinded translation along with a `HTTPBackend` translation. But it doesn't work.

### The things I've tried:
- [Official Doc add-or-load-translations](https://www.i18next.com/how-to/add-or-load-translations)
- [Official Doc backend-fallback](https://www.i18next.com/how-to/backend-fallback)
- https://github.com/i18next/i18next/issues/1910

### The code I've tried:
```typescript
// This code  is half way works and half way fail. The translation added by `i18n.addResourceXXX()` works, 
// but `HTTPBackend` will only load the translation once(seems it loads at init), 
// changing language won't trigger `HTTPBackend` load new translation.
//
// Trigger a fake `languageChanged` event as says https://github.com/i18next/i18next/issues/1910 also won't work

i18n
  .use(LanguageDetector)
  .use(HTTPBackend)
  .use(initReactI18next)
  .init({
    fallbackLng: fallback,
    debug: debug,
    supportedLngs: langs,
    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
    detection: {
      lookupQuerystring: LocaleKey,
      lookupCookie: LocaleKey,
      lookupLocalStorage: LocaleKey,
      lookupSessionStorage: LocaleKey,
    },
    backend: {
      loadPath: "/locales/{{lng}}.json",
    },
  })
  .then(() => {
    i18n.addResourceBundle("zht", "translation", { te: "Tet" });
    i18n.addResourceBundle("zhs", "translation", { te: "Tes" });
    i18n.addResourceBundle("en", "translation", { te: "Te" });
  });

```
```typescript
// This won't work either, because `HTTPBackend` and `resourcesToBackend()` are both "responding",
// and `ChainedBackend` switch to fallback only if backend not "responding", that means:
// - [HTTPBackend, resourcesToBackend(EmbeddedTranslations)]: `EmbeddedTranslations` not existing in `HTTPBackend`, and will display as translation key
// - [HTTPBackend, resourcesToBackend(EmbeddedTranslations)]: `HTTPBackend` not existing in `EmbeddedTranslations`, and will display as translation key
i18n
  .use(LanguageDetector)
  .use(ChainedBackend)
  .use(initReactI18next)
  .init({
    fallbackLng: fallback,
    debug: debug,
    supportedLngs: langs,
    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
    detection: {
      lookupQuerystring: LocaleKey,
      lookupCookie: LocaleKey,
      lookupLocalStorage: LocaleKey,
      lookupSessionStorage: LocaleKey,
    },
    backend: {
      backends: [HTTPBackend, resourcesToBackend(EmbeddedTranslations)],
      backendOptions: [
        {
          loadPath: "/locales/{{lng}}.json",
        },
      ],
    },
    // resources: EmbeddedTranslations
  })
  .then();
```

## To Reproduce
Use the code I provide

## Expected behavior
I can set a predefinded translation along with a dynamic translation from `Backend`, or at least,
`ChainedBackend` should switch backend based on `Translation Key Not Found` rather than `Not Responding`(BTW, if a `ChainedBackend` is not responding, doesn't that also mean `Translation Key Not Found`?)

## Your Environment

- *runtime version*: Node 20, Chrome, 
- *i18next version*: 23.14.0
- *os*: Mac, Windows, Linux
- *any other relevant information*: "i18next-chained-backend": "^4.6.2", "i18next-http-backend": "^2.6.1", "i18next-resources-to-backend": "^1.2.1",

**Comment by JobberRT** [comment]
re-edit to fix a typo whp cause markdown code block rendering fail

**Comment by JobberRT** [comment]
A use case example:
I got multiple projects requiring i18next and axios. So I want to write a helper package that provide a unified init function for these two package.
I want to embedded some axios request error translation in i18next, so my project won't have to write the same translation every time. But also, I want to provide some individual translation per project, so my idea is to embedded axios translatons in the helper package, and project translation in project's `/public/locales` directory and load with `HTTPBackend`

**Comment by JobberRT** [comment]
right now i think of a workaround: THe `i18next` init function receives a `translation` param, and inside the init function, I can merge the embedded translation with the passed translation.

This way I can even avoid using any kinds of `Backend`, but it seems like a no quite elegant solution to me

**Comment by adrai** [comment]
It's not a fallback szenario, but a partially loaded scenario: https://www.i18next.com/how-to/add-or-load-translations#combined-with-a-backend-plugin

`partialBundledLanguages: true,`

**Comment by JobberRT** [comment]
@adrai Thanks for replying , I've already tried the link, and the `			partialBundledLanguages: true` params, that will cause the `addResources` translation works, but not the `HTTPBackend` one, could you please give me a example?

**Comment by adrai** [comment]
it will only work for new namespaces, not already preloaded

**Comment by adrai** [comment]
Alternatively, you need to reload the resources similar to: https://github.com/i18next/i18next-http-backend/blob/master/example/next/pages/lazy-reload-page.js

**Comment by JobberRT** [comment]
Thanks, I will try that

**Comment by JobberRT** [comment]
@adrai I figer out my problem! `partialBundledLanguages` is indeed the param I need, the reason why my try failed is that I forget to set the `ns` array when using `useTranslation`! Forgetting that cause `i18n` will only look at the default ns `translation`! Passing an array including the embedded namespace and the HTTPBackend namespace works like a charm, even without reloading the resources, Thanks!
