### ISSUE TITLE
Use `i18next` in constant file

### ISSUE THREAD

**Issue by vanhcoder** [i18next/i18next#2236]
So i have setup i18n next and everything works as expected with useTranslation() hook in components. 

Config looks like this: 

`import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import Backend from 'i18next-http-backend';
import { initReactI18next } from 'react-i18next';

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: 'ja',
    debug: true,
    interpolation: {
      escapeValue: false,
    },
  });

export default i18n;`

Now the problem that i'am facing is when trying to translate constant file. This is how the file looks like:

`import i18n from '../i18n';

export const sec1 = {
  title: i18n.t('test.text1'),
};
`
But nothing has been translated, however if i convert it into function like this:

`export const sec1 = () => ({
  title: i18n.t('test.text1'),
});`

translation is successful and i feel there are some race conditions, have anyone faced similar issues and how manage to resolve em?

PS: I have added: 

`i18n.on('loaded', () => {
 console.log('loaded');
});`

and i can see loaded is called after constant file is executed, so how to prevent execution of this file until i18n is loaded?

**Comment by jamuhl** [comment]
read through https://github.com/i18next/react-i18next/issues/1757
