### ISSUE TITLE
Issue when awaiting in the i18n init (using React-Native)

### ISSUE THREAD

**Issue by Berchez** [i18next/i18next#2237]
## 🐛 Bug Report

The i18n.t function doesn't work for me if the function that init the i18n needs to await another function in the react-native

## To Reproduce

See:

Working code:
```
const getSavedLanguage = () => {
    return 'en-US';
}

const initI18n = async () => {
    const savedLanguage = await getSavedLanguage();

    await i18n.use(initReactI18next).init({
        compatibilityJSON: "v3",
        resources,
        lng: savedLanguage, 
        fallbackLng: DEFAULT_LANGUAGE,
        interpolation: {
            escapeValue: false,
        },
    });
};

initI18n();

export default i18n;
```

Broken code:
```
const getSavedLanguage = () => {
    return 'en-US';
}

const initI18n = async () => {
    const savedLanguage = await getSavedLanguage();

    await i18n.use(initReactI18next).init({
        compatibilityJSON: "v3",
        resources,
        lng: savedLanguage, 
        fallbackLng: DEFAULT_LANGUAGE,
        interpolation: {
            escapeValue: false,
        },
    });
};

initI18n();

export default i18n;
```

## Expected behavior

With the working code:

```
const {t} = useTranslation();
console.log('indexPage.welcome'); // returns Welcome!
```

With the broken one:

```
const {t} = useTranslation();
console.log('indexPage.welcome'); // returns indexPage.welcome
```
## Your Environment

- *runtime version*: node v20.11.1,
- *react-native*: v0.74.5
- *expo*: v~51.0.28
- *i18next version*: v23.15.1
- *react-i18next*: v15.0.2,
- *os*: Windows 10

**Comment by adrai** [comment]
That is async... so this will nit work unless you wait for the init call to be completed and then call the t function, or use Suspense or check the ready flag and show a loading spinner: https://react.i18next.com/latest/usetranslation-hook#not-using-suspense

**Comment by Berchez** [comment]
Perfect, thanks.
Thank you for the quick reply
