### ISSUE TITLE
[Typescript] Wrong key type when using context on TS5+ 

### ISSUE THREAD

**Issue by AlexKrupko** [i18next/i18next#2242]
## 🐛 Bug Report

**Typescript 5+** infers wrong keys when using keys with context. 
On TS4, everything works as expected.
<img width="759" alt="Screenshot 2024-10-05 at 00 15 22" src="https://github.com/user-attachments/assets/f602b6d9-72b5-4562-8a61-378e4fdaad3a">

## To Reproduce

```ts
import i18next from 'i18next';

const resources = {
    translation: {
        key: 'key value',
        key_context: 'key_context value',
    }
};

i18next.init({
    supportedLngs: ['en'],
    lng: 'en',
    resources: {
        en: resources,
    },
});

declare module 'i18next' {
    interface CustomTypeOptions {
        resources: typeof resources,
    }
}

const t = i18next.getFixedT('en', 'translation');

const test = t('keyontext');
//              ^ this is a valid key!
```

## Expected behavior

Only `key` and `key_context` keys should be inferred. 

## Your Environment
- *i18next version*: 23.15.1
- *typescript*: 5.6.2

**Comment by marcalexiei** [comment]
PR Welcome.
You can start from `FilterKeysByContext` type in `typescript/t.d.ts`.

**Comment by adrai** [comment]
try v23.15.2

**Comment by AlexKrupko** [comment]
Yes, it works like a charm in 23.15.2. 
Thank you @adrai, @marcalexiei!
