### ISSUE TITLE
New major release: drop v3 typescript support

### ISSUE THREAD

**Issue by marcalexiei** [i18next/i18next#2254]
I checked [i18next-drop-legacy branch](https://github.com/i18next/i18next/tree/i18next-drop-legacy) changeling and I found:

https://github.com/i18next/i18next/blob/92a36d3f07750e3cb2d961110cbfc601f5eeafda/CHANGELOG.md?plain=1#L6-L7

Could the associated types and tests  of json v3 be removed from the source code?

**Comment by marcalexiei** [comment]
Ok, so let's keep compatibility for json v3 in typescript. 

How about removing it with the next major (at least on `typescript` side)?
We can add an entry to the changelog and one in the documentation notifying user about this and keep this issue open as a reminder for the next major release.

**Comment by adrai** [comment]
I don't know... seems strange to have an old format still supported in TS but not in JS... (unless someone creates that type of compatibility layer...)

I would say, we remove them now. What do you think?

**Comment by marcalexiei** [comment]
Ok, fine for me, l'll make a separate PR based on #2253.
(Just in case that an apocalyptic scenario occur we can revert the pr commit to restore the support the support)

**Comment by adrai** [comment]
https://www.i18next.com/misc/migration-guide#v23.x.x-to-v24.0.0
