### ISSUE TITLE
Using react-i18next as a module on top of i18next not functioning as before on 23.16.x

### ISSUE THREAD

**Issue by mikhuttu** [i18next/i18next#2262]
## 🐛 Bug Report

We're using react-i18next as an additional plugin for i18next. If we move from 23.15.2 to 23.16.x of i18next, we're unable to use localisations within a json localisation file. Under the next section you may find our implementation for using i18next. After initialising i18next with the react-18next module and given localisation file (+ extra settings), we're using `useUITranslation` function for actually loading localised content within a react element.

## To Reproduce

Our i18next implementation
```js
import i18next from 'i18next'
import { initReactI18next, useTranslation } from 'react-i18next'
import uiEnUK from 'locales/en-UK/ui.json'

const nsUI = 'ui'

export const initI18n = async () => {
  const langEnUK = 'en-UK'

  await i18next.use(initReactI18next).init({
    ns: [nsUI],
    resources: {
      [langEnUK]: {
        [nsUI]: uiEnUK
      }
    },
    lng: langEnUK,
    load: 'currentOnly',
    debug: false
  })
}

export const useUITranslation = (keyPrefix?: string) => {
  return useTranslation(nsUI, { keyPrefix: keyPrefix ?? '' }).t
}
```
and use case within a tsx-file
```
const t = useUITranslation()
{t('something')}
```
That "something" within `locales/en-UK/ui.json` would be translated properly with 23.15.2 but not with a newer version of i18next.

## Your Environment

- *runtime version*: node 20.18.0, browser Chrome/Edge
- *os*: Windows

**Comment by adrai** [comment]
Sorry, I'm not able to reproduce your issue.
Please provide a minimal reproducible example repository, like here: https://github.com/i18next/react-i18next/tree/master/example/react
And not just code snippets.

**Comment by AlexWebLab** [comment]
The problem seems that 24.x.x requires TypeScript >= 5

**Comment by adrai** [comment]
> The problem seems that 24.x.x requires TypeScript >= 5. I'm still using TS 4.x.x and it's breaking the pipeline on npm install.

Then stay on v23
