### ISSUE TITLE
Plurals broken on v24.0.0 & react native

### ISSUE THREAD

**Issue by ilteoood** [i18next/i18next#2263]
## 💥 Regression Report

Unable to use plurals on react native with i18next v24.0.0

## Last working version

Worked up to version: 23.16.8

Stopped working in version: 24.0.0

## To Reproduce

```js
const {t} = useTranslation();

const translatedLabel = t('title.right', {count: data.length});
```

Result:
![image](https://github.com/user-attachments/assets/94367af4-b73f-45e1-9788-80454910a9f4)

## Expected behavior

It should correctly translate the plural. If count is = 0, the translated label should be `Incident`, otherwise it should be `Incidents`.

## Your Environment

- *runtime version*: node 22.11.0
- *i18next version*: 24.0.0.0
- *os*: Mac
- "react-native": "0.75.4", "react-i18next": "^15.1.1"

**Comment by jamuhl** [comment]
https://www.i18next.com/misc/migration-guide#v23.x.x-to-v24.0.0

v24 is major

**Comment by adrai** [comment]
Use an Intl polly fill, like described in the v24 migration guide

**Comment by ilteoood** [comment]
@jamuhl I know it's a major, and I know about the polyfill requirement as @adrai suggested, but as in v23 I expected an error message that says that the required Intl APIs are missing instead of this weird error.
I suggest you to bring it back just for a better DX
