### ISSUE TITLE
After updating to i18next 24, crash formatting string with negative number

### ISSUE THREAD

**Issue by paulschreiber** [i18next/i18next#2264]
## 🐛 Bug Report
After upgrading to i18next 24, formatting a string with a negative number causes the app to crash.

## To Reproduce
Minimal example based on expo template: https://github.com/paulschreiber/i18n-ts-test

```js
const formatCoordinate = (value: number) => {
  const locale = "en";

  return value.toLocaleString(locale, {
    maximumFractionDigits: 2,
  });
};

const coords = { latitude: 37.77161, longitude: -122.3456 }; // crashes with 24, fine with 23
const coords = { latitude: 37.77161, longitude: 122.3456 }; // fine with both
```

```jsx
<Text>
  {t("coords", {
    lat: formatCoordinate(coords.latitude),
    lng: formatCoordinate(coords.longitude),
  })}
</Text>
```

## Actual behavior
Crash
<img width="555" alt="image" src="https://github.com/user-attachments/assets/163472df-754a-46f1-b640-26634d16a069">

```
 (NOBRIDGE) ERROR  Warning: RangeError: com.facebook.hermes.intl.JSRangeErrorException: Empty subtag [at index 0]

This error is located at:
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
```

## Expected behavior
String is rendered as expected.

<img width="577" alt="image" src="https://github.com/user-attachments/assets/eb3aa6ff-e6e4-46ea-8c77-180774b00d97">

## Your Environment

- *runtime version*: node 23.3.0, expo 51 or 52
- *i18next version*: 24.0.2
- *os*: macOS 15.1.1

**Comment by adrai** [comment]
the lng option is a reserved option...
If you change it to long it works:

`coords: "{{lat}}, {{long}}",`

```js
<Text>
  {t("coords", {
    lat: formatCoordinate(coords.latitude),
    long: formatCoordinate(coords.longitude),
  })}
</Text>
```

**Comment by paulschreiber** [comment]
@adrai Is this new? This is going to cause problems for everyone working with geospatial data.

**Comment by adrai** [comment]
not really no

**Comment by adrai** [comment]
lng is the language value since always here in i18next

**Comment by paulschreiber** [comment]
If this was a reserved word before, it's weird that it broke suddenly.

**Comment by adrai** [comment]
https://www.i18next.com/translation-function/essentials#overview-options
<img width="832" alt="image" src="https://github.com/user-attachments/assets/5c8b319a-ceb9-47cf-b3a3-671bc8111810">
