### ISSUE TITLE
Allow nested interpolation `defaultVariables`

### ISSUE THREAD

**Issue by harry-gocity** [i18next/i18next#2265]
## 🚀 Feature Proposal

I would like to be able to combine interpolation default values with nesting.

## Motivation

We want to utilise nesting for one value that is used consistently in our content, but without our content editors having to understand the syntax. The idea is that the `defaultVariables` configured reference an interpolation key, similar to how nesting works, and then the normal `{{variable}}` syntax will be templated without needing to be passed to `t`.

## Example

With content

```json
{
  "brand": "Company name",
  "content": "Jobs at {{companyName}}"
}
```

And with interpolation options like:

```ts
{
  interpolation: {
    defaultVariables: {
      companyName: "$t(brand)",
    },
  }
}
```

Interpolation works without any passed variables

```ts
t("content") // Jobs at Company Name
```

**Comment by adrai** [comment]
You're talking about the "skipOnVariables" option:

```js
const i18next = require('i18next')
i18next.init({
  debug: true,
  lng: "en",
  fallbackLng: "en",

  interpolation: {
    skipOnVariables: false,
    defaultVariables: {
      companyName: "$t(brand)",
    },
  },

  resources: {
    en: {
      translation: {
        brand: "Company name",
        content: "Jobs at {{companyName}}"
      },
    },
  },
})

console.log(i18next.t('content'))
```
