### ISSUE TITLE
Intl.getCanonicalLocales throws with custom regions

### ISSUE THREAD

**Issue by ChromeQ** [i18next/i18next#2267]
## To Reproduce

I am using custom regions in my Australian locales, for example some words are different depending on which state you are in. A "Pint" of beer in most of Australia is a "Pint", but in South Australia (SA) it is known as an "Imperial Pint" along with a [bunch of others](https://notoneoffbritishisms.com/2020/03/05/schooner/).

So I have set the locale as "en-AU-SA"

```js
const { t } = useTranslation('drinkTypes', { lng: 'en-AU-SA' });
```

It throws a RangeError:  `ERROR  [RangeError: com.facebook.hermes.intl.JSRangeErrorException: Invalid subtag: SA [at index 6]]` from within the native code for Intl.getCanonicalLocales

## Expected behavior

In v23 of i18next it used to work due to the `formatLanguageCode` - https://github.com/i18next/i18next/blob/e5170ad9d024c4279e8682a21f741491316ccd9e/src/LanguageUtils.js#L33

Even after [v23.16 introduced the Intl.getCanonicalLocales](https://github.com/i18next/i18next/commit/c3742325a9be3222e7fec75aafefbebb90cf3a0a) it worked because of the try catch and fallthrough to the previous behaviour - https://github.com/i18next/i18next/blob/1736965d1f21612c80e391b25574fe657de840a6/src/LanguageUtils.js#L36

## Fix

Although I understand my region is not "correct", it should allow me to get translations as they exist in my resource translation files.

From my tinkering I believe a simple try/catch around the formatLanguageCode and returning the code should suffice. I realise it is then up to me to ensure the code is formatted correctly.

```js
formatLanguageCode(code) {
    // http://www.iana.org/assignments/language-tags/language-tags.xhtml
    if (isString(code) && code.indexOf('-') > -1) {
      try {
        let formattedCode = Intl.getCanonicalLocales(code)[0];
        if (formattedCode && this.options.lowerCaseLng) {
          formattedCode = formattedCode.toLowerCase();
        }
        if (formattedCode) return formattedCode;

        if (this.options.lowerCaseLng) {
          return code.toLowerCase();
        }
      } catch {}

      return code;
    }

    return this.options.cleanCode || this.options.lowerCaseLng ? code.toLowerCase() : code;
  }
```

## Your Environment

- *runtime version*: react-native@0.74.5
- *i18next version*: 24.0.2

**Comment by adrai** [comment]
addressed with v24.0.3
