### ISSUE TITLE
Calling `addResourceBundle` for an i18n instance cloned while using `forkResourceStore` overwrites the original resources as well

### ISSUE THREAD

**Issue by angekouf** [i18next/i18next#2270]
## 🐛 Bug Report

When I use `forkResourceStore` to clone an instance and I add a resource bundle to the cloned instance with `addResourceBundle`, the texts are added to the original i18n instance as well and the new texts overwrite the old ones. 

## To Reproduce

https://codesandbox.io/p/sandbox/trying-to-use-forkresourcestore-with-react-i18next-forked-q5lmvr

## Expected behavior

I would expect each instance to have its own resourced with the new option and adding a bundle to one of them would not affect the rest. In the code sandbox I have included the expected result along with the actual result in each use case

## Your Environment

- *node*: v20.17.0
- *i18next*: v23.11.5 (but also tested in latest version v24.0.5)
- *os*: MacOS 15.0.1

**Comment by angekouf** [comment]
@jamuhl  I thought that using the `forkResourceStore` meant that the resource store was not shared though?
I would expect this behaviour in earlier versions before the `forkResourceStore` option 🤔

**Comment by jamuhl** [comment]
@angekouf I wasn't aware of that flag...seems @adrai is already on it

**Comment by angekouf** [comment]
Works perfectly 🚀 
Thank you @adrai 

![image](https://github.com/user-attachments/assets/2ad9a374-1d11-4a07-af0f-64e1568f95f0)
