### ISSUE TITLE
Bug Report: Unsafe Behavior in i18n.t Function Leading to Potential Code Execution

### ISSUE THREAD

**Issue by ash47** [i18next/i18next#2273]
## 🐛 Bug Report

The `i18n.t` function unsafely returns JavaScript functions such as `constructor` when keys don't exist which could lead to code execution in certain scenarios.

## To Reproduce

 [codesandbox using react to show this issue](https://codesandbox.io/p/sandbox/jovial-sun-hjg2rk?file=%2Fsrc%2Fapp.js)

Call the `i18n.t` with `constructor` and a function will be returned instead of a string.

```js
// Returns a function
i18n.t('constructor')

// Shows that the type is a function
console.log(typeof(i18n.t('constructor'))) // returns 

i18n.t('constructor_test') // returns a string `constructor_test` if it doesn't exist
```

## Expected behavior

I expect `i18n.t` to always return a string, and not randomly return functions.

```js
i18n.t('constructor') // would expect it to return the string 'constructor' if it doesn't exist
```

## Your Environment

- *runtime version*: NodeJS v20.14.0
- *i18next version*: 24.1.0
- *os*: Windows
- *any other relevant information*

This kind of behaviour happens when you incorrectly check for a key in an object using either:
```js
const myObject = {};
const key = 'constructor';

if(myObject[key]) {
    return myObject[key];
}

// or

return myObject[key] || key;
```

The correct way when working with objects is:

```js
const myObject = {};
const key = 'constructor';

if(myObject.hasOwnProperty(key)) {
    return myObject[key];
} else {
    return key;
}

// OR

return myObject.hasOwnProperty(key) ? myObject[key] : key;
```

**Comment by adrai** [comment]
v24.1.1 should address this

**Comment by adrai** [comment]
impratical...
Has already been discussed with Synk team...

**Comment by jayaddison** [comment]
Thank you.  And it's reassuring to know that quirks like this are being uncovered, even so.
