### ISSUE TITLE
Is there a way to translate custom attributes?

### ISSUE THREAD

**Issue by salvador-dali** [i18next/i18next#233]
This is not really an issue with a library, it is just my inability to find a way to solve my problem. 

I am trying to translate some custom attributes like `<input placeholder="Hello" value="name">` but can not find a way to do it. I outlined the problem here http://stackoverflow.com/q/22728797/1090562 and also created a fiddle here http://jsfiddle.net/SalvadorDali/dLc7x/

**Comment by jonalxh** [comment]
Hi @jamuhl.
I'm unable to make it work in bootstrap 4 tooltips, I'm setting `data-i18n="[title]mystring"` as an attribute of my HTML element, It gets translated, but the tooltip does not appear as it should, showing the title as if element has not tooltip applied.

Do you know if there is a bug with this kind of functionalities like bootstrap tooltips?

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
