### ISSUE TITLE
Norwegian fallback does not work.

### ISSUE THREAD

**Issue by luke-john** [i18next/i18next#257]
Unfortunately the Norwegian locales do not follow the same rule as other languages and so 
https://github.com/jamuhl/i18next/blob/master/src/i18next.helpers.js#L417 == "nn-NO".split("-")[0]
does not work.

no = Norwegian
nb-NO = Norwegian (Bokm�l) - Norway
nn-NO = Norwegian (Nynorsk) - Norway

**Comment by MrSwitch** [comment]
I also had issues with Browser Detections sending `nb`, `nn`. I worked around this by linking the resource for both of these.

```js
	no: {
		translation: noNO,
	},
	// Norwegian, translation issues https://github.com/i18next/i18next/issues/257#issue-36343630
	'nb': {
		translation: noNO,
	},
	'nn': {
		translation: noNO,
	},
```

But, Is there a better way?

**Comment by jamuhl** [comment]
@MrSwitch you can define a specific fallback for nb, nn to no -> like https://www.i18next.com/principles/fallback#fallback-language

**Comment by MrSwitch** [comment]
Great, Thankyou @jamuhl

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
