### ISSUE TITLE
How do you apply localized number formatting to the count in a plural?

### ISSUE THREAD

**Issue by tiffting** [i18next/i18next#274]
If I want to apply number formatting in my count for a plural, is there a way to do that? For instance, if the count is 3018, I'd like the resulting text to be formatted like "3,018 search results" in English or "3.018 Suchergebnisse" in German.

**Comment by dessalines** [comment]
This is really unfortunate, seems like something that should be added.

**Comment by dessalines** [comment]
@jamuhl Question: If I want to use formattedCount, when I define the string:

`"number_of_users_plural": "{{formattedCount}} users"`

Will it still be smart enough to use `count` for plural, even though that isn't in the definition?

**Comment by jamuhl** [comment]
@dessalines yes, count will be used for plural anyway
