### ISSUE TITLE
Can I render/translate a JSON array?

### ISSUE THREAD

**Issue by nikolaygit** [i18next/i18next#299]
I want to render a JSON array

``` javascript
{"myArray": [ {"name": "Steve"}, {"name": "Tom"} ]}
```

in the two HTML spans:

``` javascript
<span data-i18n="...">Steve should appear here<span>
<span data-i18n="...">Tom should appear here<span>
```

What values should I set in `data-i18n` to achieve that, or can you recommend another way?

Thanks,

Nikolay

P.S. also asked here: http://stackoverflow.com/questions/25936898/i18next-render-json-array

**Comment by rosskevin** [comment]
@jamuhl I have the same need as @quentindemetz  to get the actual array, but the reference to `objecttree` referenced above no longer exists.  Is there a current reference to it in the docs?  I see something in a test: https://github.com/i18next/i18next/blob/9d27384e71a6eedd0c8fee964e321e6dc56379d7/test/backward/v1.11.1.compat.js#L1747

**Comment by rosskevin** [comment]
It appears from the [current code](https://github.com/i18next/i18next/blob/master/src/Translator.js#L78) that you need to specify the combination of: 

```
  returnObjects: true,
  joinArrays: false,
```

**Comment by jamuhl** [comment]
the doc is here: http://i18next.com/translate/objects/

joinArrays per default is false
