### ISSUE TITLE
Updating more than one attribute on the same element

### ISSUE THREAD

**Issue by MayamaTakeshi** [i18next/i18next#306]
Hello, i would like to suggest an improvement: to allow to specify more than one attribute of the same element to be translated by i18next.
Ex:

```
  <input type="password" class="form-control" required id="password" data-i18n="[placeholder]form-signin.password,[validitymsg]form-signin.invalid_password"/>
```

Because the above is not currently possible, I am wrapping the target element with a div that will update its child:

``` HTML
        <div data-i18n="[validitymsg]form-signin.invalid_password" data-i18n-target="#password">
          <input type="password" class="form-control" required id="password" data-i18n="[placeholder]form-signin.password" validitymsg=""/>
        </div>
```

Obs: i need this because i have to translate both the placeholder message and the customValidity message in case of wrong input (I will later call $('#password').setCustomValidity(validitymsg)).

Regards,
Takeshi

**Comment by danpadua** [comment]
try this:

  <input type="password" class="form-control" required id="password" data-i18n="[placeholder]form-signin.password;[validitymsg]form-signin.invalid_password"/>

**Comment by Ramu4041** [comment]
Thanks
