### ISSUE TITLE
Windows Phone 8.1 will not do i18next

### ISSUE THREAD

**Issue by malmazano** [i18next/i18next#314]
Hi:
I've been using i18next with a jquery mobile based multi-platform app (Android,iOS,WP 8, BB and even Symbian) successfully for a while.

Windows Phone was always hard to get to work as calling through ondeviceready wold not work.

However, I got it to work with WP 8.0. Now with the update to 8.1 I cannot load texts anymore and I have not been able to make it work.

Any idea why? I'm using i18next 1.7.1

Any help will be greatly appreciated as I am out of ideas.

**Comment by malmazano** [comment]
Current WP 8.1 OS incarnation seems to have reverted some of the Javascript blocking: ¡¡ i18next seems to work again !! (at least for now)

**Comment by jamuhl** [comment]
so closing this for now - and hope for the best.
