### ISSUE TITLE
Add option to get resource bundle from store

### ISSUE THREAD

**Issue by jcbvm** [i18next/i18next#334]
For my current project it would be nice to have an option to get a resource bundle from the store. 

To be in line with the other API calls ```hasResourceBundle```, ```addResourceBundle``` and ```removeResourceBundle```, I was thinking of something like ```getResourceBundle(lng, ns)``` which will return the current translations from the store for the given language and namespace (or default namespace if omitted).

I can add a PR if needed.

**Comment by danicomas** [comment]
news?

**Comment by danicomas** [comment]
https://github.com/i18next/i18next/pull/335

**Comment by jamuhl** [comment]
PR was merged
