### ISSUE TITLE
Handlebars "tr" helper doesn't escape helper options

### ISSUE THREAD

**Issue by stevewillard** [i18next/i18next#337]
The "tr" helper on http://i18next.com/pages/doc_templates.html has the following:
```
Handlebars.registerHelper('tr', function(context, options) { 
   var opts = i18n.functions.extend(options.hash, context);
   if (options.fn) opts.defaultValue = options.fn(context);
 
   var result = i18n.t(opts.key, opts);
 
   return new Handlebars.SafeString(result);
});
```

This can cause unsafe options to be passed into the resource string, which could potentially come from user input. For example:
```
{{#tr this key="trans.sample.handlebarsExtended" add="<script>alert('hello')</script>" }} {{/tr}}
```

Before calculating the result, you should make sure to escape the values of the options
```
for (var key in opts) {
    opts[key] = Handlebars.Utils.escapeExpression(opts[key]);
}
```

**Comment by jamuhl** [comment]
closing this due upcoming v2: http://i18next.github.io/i18next.com/

v2 won't explicitly mention handlebars...hope someone will come up with a plugin for that and add it here: http://i18next.github.io/i18next.com/docs/ecosystem/#frameworks
