### ISSUE TITLE
Initialization documentation typo

### ISSUE THREAD

**Issue by ArnaudRinquin** [i18next/i18next#339]
Hi,

I have spotted a typo on initialization doc:
> `i18n.addResourcea('de-CH', 'translation', additionalResources);`

Should be:
> `i18n.addResources('de-CH', 'translation', additionalResources);`

I tried to fix it myself but I can't rebuild the doc properly. It seems that the `jade` version used to compile it is quite old.

To avoid error during grunt build I had to:
* replace all `!!! 5` by `doctype html`
* add dots after all `script` tags

Unfortunately, the built website seems broken.

**Comment by jamuhl** [comment]
closing this due upcoming v2: http://i18next.github.io/i18next.com/

should be fixed there
