### ISSUE TITLE
setLng() not re-using already loaded resources

### ISSUE THREAD

**Issue by digabiadmin** [i18next/i18next#342]
At the moment call to setLng() always fetches resources from server even if same resources have already been loaded previously.

This happens because setLng() calls init() which does not check what languages have already been loaded (and saved to resStore), but fetches them again and stores them to resStore.

Is this behavior intentional? If yes, is there any way to change language without reloading resource from server?

**Comment by jamuhl** [comment]
for production you might turn on localstorage feature...that will try first loading from localstorage and if not found from server.

**Comment by jamuhl** [comment]
closing this due upcoming v2: http://i18next.github.io/i18next.com/

fixed there
