### ISSUE TITLE
CDN for i18next?

### ISSUE THREAD

**Issue by wilsonmar** [i18next/i18next#344]
Is there a CDN which hosts i18next?
What would be nice is something like MaxCDN hosting bootstrap:
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

**Comment by jamuhl** [comment]
not as i know - might be a good idea.

**Comment by jamuhl** [comment]
https://github.com/jsdelivr/jsdelivr/pull/3031#issuecomment-69574060

will update documentation asap.

**Comment by jamuhl** [comment]
see how v2 acts after release.

**Comment by jamuhl** [comment]
seems cdns catched up on v1 -> v2

closing for now
