### ISSUE TITLE
i18next don't work in javascript/Jquery.

### ISSUE THREAD

**Issue by danigonlinea** [i18next/i18next#347]
Hi guys, I want to create an issue shared in Stackoverflow that it is not answered yet.

The problem is when you try to use i18next into javascript (in HTML front-end, not for the backend), the plugin does not work.

Here more details: http://stackoverflow.com/questions/28011934/i18next-dont-work-in-jquery

**Comment by jamuhl** [comment]
the structure in the issue is unclear. is that client side - as doing node.js module stuff?

**Comment by danigonlinea** [comment]
It is not a server side issue, the problem is when I have to use i18next in Jquery or javascript in the HTML page, I get "t is not defined". This is what I do:

```javascript
$(document).ready(function() {
    var message = t('info.message');
    alert(message);
});
```
I need to handle translation sentences in Jquery but I can not be able to.I
I read [integration with Jquery](http://i18next.github.io/i18next/pages/doc_jquery.html).  I changed 't' by '$.t' but nothing, even I added `$.i18n.init();` before that as well but it seems that `$.i18n` is not recognized. Why am I doing wrong?

**Comment by jamuhl** [comment]
most important:

i18n.init(opts).done(function() {
  var x = $.t("key");
});

or

i18n.init(opts, function() { 
  var x = $.t("key");
}):

the init function is async (needs to load the data). use the on callback!

use `debug=true` to logout issues with loading resources.

see the sample: http://i18next.com/pages/sample.html

**Comment by danigonlinea** [comment]
I still have a problem Jan. I resolved using your code before but in the following code, the alert shows the string 'info.message' (so the content of var 'x' is 'info.message') instead of its real content in translation.json file.

```javascript
$(document).ready(function() {
    
   i18n.init({ lng: "en-EN" }, function() {
        var x = $.t('info.message');
        alert(x);
    });
});
```
I don't understand why, it must show its real content isn't it ? I mean, in HTML works but I can not be able to get run into Jquery... any idea?

**Comment by jamuhl** [comment]
````
$(document).ready(function() {

   i18n.init({ lng: "en-EN", debug: true }, function() {
        var x = $.t('info.message');
        alert(x);
    });
});
````

check console output for any issues ---> best guess the resourcefile could not be loaded

**Comment by danigonlinea** [comment]
You are right, Jan.

The resources files were not in the proper place that must be charge (in the public directory). In the console, I saw that I got 404 errors for the json files and when I move it to the right place, it works perfectly, in Jquery as well.

Thank you very much, i18next is awesome.

**Comment by jamuhl** [comment]
glad i could help you.
