### ISSUE TITLE
possible options for better documentation (easier to contribute)

### ISSUE THREAD

**Issue by jamuhl** [i18next/i18next#348]
https://github.com/tripit/slate (looks rather promising)

**Comment by jairovsky** [comment]
Do you plan on versioning the entire website or just the docs?
I tested Slate and it's quite easy and fast to set it up. It has an ```include``` mechanism that I think facilitates file separation and contribution. The only "problem" is that its purpose is only to build documentation pages and thus does not offer much flexibility.

If you plan to open source the entire website, I would recommend you to take a look at [Pico CMS](http://picocms.org/). Its content is managed with flat Markdown files, like Slate, but you have more control over layout. Possible downside is that it needs PHP to run (don't know if the current [i18next.com](http://i18next.com/) host runs PHP).

**Comment by jamuhl** [comment]
@jairovsky it's less about versioning the documentation. more or less i want to build the current websites information with simpler tools and more modular.

i started (tried out) slate at: https://github.com/i18next/i18next.com but like you said...i don't feel to happy about the flexibility (and obviously the visual result).

the page currently runs as gh-page - so no serverside is included - just generated files that are pushed to that branch.

**Comment by jamuhl** [comment]
closing this due upcoming v2: http://i18next.github.io/i18next.com/
