### ISSUE TITLE
Bootstrap tooltip support

### ISSUE THREAD

**Issue by WinnieK** [i18next/i18next#349]
Hello there.
I have a question about compatibility with Bootstrap tooltip.
Let's say i have this code:
```html
<div class="title" data-i18n="nav.category" data-i18n-target="span">
    <span></span>
    <i class="icon-menu" data-i18n="[title]nav.category"></i>
</div>
```

and initializing Bootstrap tooltip after translation is ready:
<code>$('.icon-menu').tooltip();</code>

It adds necessary title, but tooltip doesn't show up. Is there any way to run a tooltip in this case?
Thanks

**Comment by jamuhl** [comment]
you might get an answer over at stackoverflow....not sure someone will see this here and answer integration related questions...
