### ISSUE TITLE
fallback language isn't loaded unless I use `async: false`

### ISSUE THREAD

**Issue by chovy** [i18next/i18next#350]
The request is made, but the language isn't loaded.

It only is loaded if I use `async: false` in the init options.

```
		i18ngProvider.init({
			fallbackLng: 'en',
			fallbackToDefaultNS: true,
			debug: true,
			getAsync: false,
			cookieName: 'lang',
			resGetPath: '/locales/__lng__/__ns__.json',
			ns: {
				namespaces: ['app'],
				defaultNs: 'app'
			}
		});
```

I'm using `i18ng`

**Comment by jamuhl** [comment]
not sure...i think this is more related to the angular integration then to i18next itself:

i suggest heading over to https://github.com/mikefrey/i18ng and open the issue there.

**Comment by chovy** [comment]
ok thanks

**Comment by jamuhl** [comment]
basically must be some issue on the ng implementation - not handling that resource loading is done in async way.

closing this for now.
