### ISSUE TITLE
support for multiple browser accept languages

### ISSUE THREAD

**Issue by adammathias** [i18next/i18next#351]
Could it be that i18next does not support multiple browser accept languages (as defined in the spec http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html)?

My list looks like this: Accept-Language:ru,de-AT;q=0.8,de;q=0.6,en;q=0.4,en-US;q=0.2,es;q=0.2
My site supports de-* and en-* at the moment.

Expected: I see de (as ru is not available).
Actual: I see en (the fallback language).

(If it helps: I'm on Chrome, using Angular ie ng-i18next.)

**Comment by jamuhl** [comment]
it takes locale from navigator object depending on browser implementation: https://github.com/i18next/i18next/blob/master/src/i18next.detectLanguage.js#L35

and takes first in whitelist if defined (if not it takes the first detected). the whitelist needs to be defined - as client has no idea what resources exist on server if you want to support this case.

**Comment by adammathias** [comment]
Thanks, I had set supportedLngs
(mentioned in http://i18next.com/node/pages/doc_init.html), not lngWhitelist (mentioned in http://i18next.com/pages/doc_init.html).
