### ISSUE TITLE
i18next.jquery bugs

### ISSUE THREAD

**Issue by weibangtuo** [i18next/i18next#352]
i18next v1.7.4

```javascript
var resStore = {
    en: {
        translation: {
            'a': 'A',
            'b': 'B'
        }
    }
};

expect($.t('$t(a):$t(b)')).to.be('A:B'); //equal
expect($.t('$t(a):$t(b)', {defaultValue:''})).to.be('A:B'); // not equal
expect($.t('$t(a):$t(b)', {defaultValue:'my_default_val'})).to.be('my_default_val'); // equal

//<span id="text" data-i18n>$t(a):$t(b)</span>
//<span id="arr" data-i18n="$t(a):$t(b)"></span>
expect($("#text").text()).to.be('A:B'); //equal
expect($("#arr").text()).to.be('A:B'); // not equal
```

**Comment by jamuhl** [comment]
`$.t('$t(a):$t(b)')` the key `'$t(a):$t(b)'` does not exist.

nesting does work like this:

````
var resStore = {
    en: {
        translation: {
            'a': 'A',
            'b': 'B',
            'a:b': '$t(a):$t(b)'
        }
    }
};

$.t('a:b')
````
http://i18next.com/pages/doc_features.html#nesting

**Comment by weibangtuo** [comment]
My system is widely used string concatenation.
keys like 

```javascript
var resStore = {
    en: {
        translation: {
            'a': 'A',
            'b': 'B',
            'c': 'C'
            '...': '...'
        }
    }
};
```
than I use as
$('a+b')
$('b+a')
$('c+a')
$('c+b')
...

There are to mach key in many language. so I modify code to support string concatenation.

https://github.com/weibangtuo/i18next/blob/8320ad25dc65657603c558be9d96bce63affac1b/src/i18next.translate.js  line101

poor in english, I hope you can understand.  
:smile:

**Comment by jamuhl** [comment]
you might add a PR for this...not yet sure if i'm a huge fan of this....but might consider adding this to next version.

**Comment by jamuhl** [comment]
closing as no PR arrived. if you still interested in providing that - feel free to add the pull request.
