### ISSUE TITLE
Translation arguments issue

### ISSUE THREAD

**Issue by Ky6uk** [i18next/i18next#356]
Between https://github.com/i18next/i18next/compare/1.7.4...1.7.7 we have a regression. We can't use translation string with interpolated arguments if one of argument named "count".

```$.t('some.key', { number: 10 });``` works fine
```$.t('some.key', { count: 10 });``` will raise error "pluralize_not_found"

**Comment by jamuhl** [comment]
will check this...might be a problem to get this back up...as count is reserved for plural detection.

`$.t('some.key', { replace: { count: 10 } }` should work without fixing...

but will try to find a solution for this...will keep you updated.

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/commit/5ab950a8a20c6bb87e56def627eba9b8302916ba should solve this...would be glad if you could test with next version and provide feedback on this.

sorry that it took so long...hard on time :(

**Comment by Ky6uk** [comment]
Ya, sure. Just release a new version. :+1:
