### ISSUE TITLE
Unable to translate key that contain colon

### ISSUE THREAD

**Issue by jakubkosinski** [i18next/i18next#361]
Hi,

I am using i18next (version amd-1.7.7) with some gettext translations converted to json using i18next-conv. I am getting problems with some keys - some of them are not translated. What I found is that key is not translated when it contains a colon or ends with one or more dots. Are there any restrictions in naming keys? 

Here are some keys from one of my JSON files:
```
{
    "Nothing to do.": "Nie ma nic do zrobienia."
    "Successfully updated settings.": "Zmiany zostały zapisane.",
    "Copy": "Kopiuj",
    "Copy to...": "Kopiuj do...",
    "From:": "Od:",
    "To:": "Do:"
}

**Comment by jakubkosinski** [comment]
OK, I got it, I just needed to change `keyseparator` and `nsseparator` in options.

**Comment by xiaotaozi1127** [comment]
how to  change keyseparator and nsseparator in options in order to translate the key which contains colon?

**Comment by jakubkosinski** [comment]
@xiaotaozi1127 you can do it either in `init` options:

```js
i18next.init({
  keySeparator: '>',
  nsSeparator: '|'
});
```

or when translating:

```js
i18next.t('some.key:', {keySeparator: '>', nsSeparator: '|'})
```

Everything is described in [docs](http://i18next.com/docs/options/).

**Comment by jamuhl** [comment]
There is a extra sample for that case here: http://i18next.com/translate/keyBasedFallback/

Setting both values to false will work too!

**Comment by loxtank** [comment]
Spent ~8 hours debugging. Unable to use colon. This caused a infinite recursion in React with useless error messages.

There should be sane defaults that permit the usage of colon in translations strings...

Thanks @jakubkosinski for posting this issue and solution!

**Comment by PatrickStudi** [comment]
Since using dot at the end of a sentence is a much more common use-case than separating keys please consider changing this default setting. Or at least update https://www.i18next.com/overview/configuration-options#configuration-options to explain why it exists.

**Comment by jamuhl** [comment]
@PatrickStudi why not contributing?

**Comment by jamuhl** [comment]
@PatrickStudi and which studies tell that using natural language as keys and not separated keys is more common -> it's a matter of taste and both are used more or less equal depending on where you come from

**Comment by PatrickStudi** [comment]
Good point. A dev friendly resolution would be if there the message from the "missingKey" console debug made it clear that a nested key could not be found, with reference to the key separator position.

**Comment by jamuhl** [comment]
@PatrickStudi Open for a PR

**Comment by joe-vanleeuwen** [comment]
In case someone else blindly copies `keyseparator` like I just did, note that the key names are `keySeparator` and `nsSeparator`

https://www.i18next.com/overview/configuration-options#misc

**Comment by jamuhl** [comment]
@joe-vanleeuwen edited the comment - so hopefully others won't copy/paste the typo
