### ISSUE TITLE
Complex / formatted plurals

### ISSUE THREAD

**Issue by Robinson7D** [i18next/i18next#362]
Currently it doesn't seem possible to have a plural-friendly translation for a formatted number (e.g. `1,000,000 people` vs `1 person`)

It doesn't look like there's a way to format these numbers before calling `applyReplacement`. My instinct instead was to just format the number before passing it into the count field, but from what I can tell the `needsPlural` function depends on `count` not being a String. 

I'm not sure how common this scenario is, but it might make sense to parse `count` for a number instead.

**Comment by jamuhl** [comment]
there is no numeral parser included in i18next. i personally use numeral.js and pass parsed value and count value, like:

````
key: '__parsedCount__ item'
key_plural: '__parsedCount__ items'

i18n.t('key', {parsedCount: '1,000', count: 1000});
````

Alternatively you could add some postProcessor parsing any number in text to some formatted number.

**Comment by Robinson7D** [comment]
Awesome, that's definitely a good enough solution for me. Closing.
