### ISSUE TITLE
Update javascript translations without page refresh

### ISSUE THREAD

**Issue by adrfonseca** [i18next/i18next#363]
Hi,

I'm using i18next for the first time and it's great.

I do the init when the page load :
<code>$.i18n.init(options, function(t) {$(document).i18n();});</code>

I have also easily built a language switcher that change language without page refresh.
So, when a new language is selected I simply call :
<code>$.i18n.setLng(lang, function(t) {$(document).i18n();});</code>

And it works great to translate all <code>"data-i18n"</code> elements in the page and everything updates well when I use the language switcher, without the need to refresh the page.

My issue is with the javascript translations :
How to update javascript translations without making a page refresh ?
What do I have to call when my language switcher event is triggered so that the javascript translations are also updated (without needing a page refresh) ?

In javascript i'm using something like <code>t(key)</code> when I want a string to be translatable ...

Looking forward for some ideas and if possible examples.

Thank you, Adriano

**Comment by jamuhl** [comment]
you mean you have content that was generated by javascript and once translated. And after switching language that 'strings' need to refresh according to new language...

only option i see is to rebuild that dynamically generated content. hard to say without more details.

**Comment by adrfonseca** [comment]
Thanks for your answer. Yes, what you describe is exactly what I want to do, but I'm not seeing how to do it with i18next.

I'm using jquery validation to validate a form and I want to use i18next to translate the validation messages. I'm doing something like:
<code>
var cc = $.t("credit_card_error_required");
form.validate({
...
messages: {
                    "credit-card-number": {
                        required: cc,
...
</code>

When the page load, the validation messages have the correct translation according to the defined language, but now I don't know how to update after switching the language ...

**Comment by jamuhl** [comment]
```
var cc;

function setValidationStrings() {
 cc  = $.t("credit_card_error_required");
}

$.i18n.setLng(lang, function(t) {
  $(document).i18n();
  setValidationsStrings();
});

// later you do -- cc will be set to new lngs value
form.validate({ ... messages: { "credit-card-number": { required: cc, ... 
```

**Comment by adrfonseca** [comment]
Thanks once again for your answer. You are fast! :)

I see what you mean, it has to be done one var to each string ... I thought it would be possible to make one call that would "replace" all javascript translations, similar to what we do with the  <code>$(document).i18n();</code> call that updates all html elements.

**Comment by jamuhl** [comment]
well only other option to simplify it a little is to get an object tree and bind that to the validation:

http://i18next.com/pages/doc_features.html#objecttree

**Comment by adrfonseca** [comment]
Thank you for your ideas and examples.

**Comment by jamuhl** [comment]
you're welcome
