### ISSUE TITLE
Browserify cannot find express/jquery

### ISSUE THREAD

**Issue by leoselig** [i18next/i18next#364]
Using karma-browserify fails when trying to require i18next somewhere.
The problem is that i18next does require('jquery') in a try/catch block but browserify obviously does not know about this and tries to find it.
My workaournd was to use i18next-client (where at least express is not needed) and add jquery as a dependency in my project - not very beautiful

**Comment by jamuhl** [comment]
we're aware of this. the next version will remove the default dependency on jquery. https://github.com/i18next/i18next/commit/95ee58fa593f576f97b510e08fa7ad38a2d13fe1

i hope to get the new version out on weekend or by monday.
