### ISSUE TITLE
Conflict: register as "window.i18next" if "window.i18n" already exists

### ISSUE THREAD

**Issue by jairovsky** [i18next/i18next#365]
Hi!

I'm having conflicts with Google ```libphonenumber```, as it uses the ```window.i18n``` namespace too. A quick fix for this issue would be changing the following code (https://github.com/i18next/i18next/blob/master/i18next.js#L100) from:
```javascript
 root.i18n = root.i18n || i18n;
```

to:
```javascript
if (root.i18n) {
    root.i18next = i18n;
}
else {
    root.i18n = i18n;
}
```

Is this an appropriate fix? Or implementing something like jQuery.noConflict() is a better idea?

**Comment by jamuhl** [comment]
for me that's ok...if you like add a PR or i will do this for next version.

**Comment by jairovsky** [comment]
Hi @jamuhl!
I've sent a PR (#371).
I ended up creating a function like ```jQuery.noConflict()``` because my first suggestion wasn't testable.

**Comment by jamuhl** [comment]
PR merged
