### ISSUE TITLE
Fix package.json

### ISSUE THREAD

**Issue by kud** [i18next/i18next#366]
Could you fix the package.json in order not to have this warning?

```
npm WARN engine i18next-client@1.7.7: wanted: {"node":"~v0.4.12"} (current: {"node":"0.12.0","npm":"2.7.1"})
```

**Comment by jamuhl** [comment]
oh crazy...never looked at that...thanks for reporting....will update this for next version.

**Comment by kud** [comment]
Thank you @jamuhl ;)

**Comment by jamuhl** [comment]
should be fixed with lastest commits....will publish new version in a few minutes/hours
