### ISSUE TITLE
We need a changelog

### ISSUE THREAD

**Issue by ArnaudRinquin** [i18next/i18next#367]
As version `1.8.0` broke our app, we feel like a `CHANGELOG.md` would be super useful.

You would list:

* New features
* Existing API changes
* Deprecations

**Comment by jamuhl** [comment]
something like https://github.com/i18next/i18next/blob/master/releasenotes.md

**Comment by ArnaudRinquin** [comment]
Oh. Did not see that one. Thanks.

Please consider adding a reference in the `README` and/or renaming it to the more usual `CHANGELOG`.

**Comment by jamuhl** [comment]
sure....will do both...thanks for reporting...will help others to follow changes, too

**Comment by jamuhl** [comment]
done

**Comment by ArnaudRinquin** [comment]
Thanks :+1:
