### ISSUE TITLE
Browser caching by version

### ISSUE THREAD

**Issue by Vadorequest** [i18next/i18next#378]
The browser caching feature is a great thing, but it doesn't cover yet all needs.

As you said in the documentation at http://i18next.com/pages/doc_init.html#caching, the caching is refreshed only when the expiration time is reached. But that's not the way we need it in production.

What would be better would be to be able to set a part of the key used to store the data in the local storage. By default it would be empty but if we set it then the i18n module would look for our custom key.

This way we can manage versions easily by setting something like: `localStorageKey= 'myKey'`.

Now, i18n would look for `res_en_myKey` instead of `res_en`, as simple as that.

The key could be anything, and may be used for versions or namespacing (like avoid conflict if we develop a third part software included in a website already using i18next :)

I don't know if we should clear the local storage of previous keys manually, or if the i18next library could do it.

Also, we could have a `localStorageNamespace` to make it clearer, and to avoid deleting local storage keys that don't belong to that namespace, I believe it would be better.

What are your thoughts on this?

**Comment by jamuhl** [comment]
i like the idea. if you feel comfortable you might provide a PR for this. else i will look into this when time allows it - but without a promise that it will happen soon.

**Comment by jamuhl** [comment]
upcoming v2: http://i18next.github.io/i18next.com/ will support individual key for localStorage: https://github.com/i18next/i18next-localStorage-cache#cache-options
