### ISSUE TITLE
i18next  finds translation files while on localhost but not on prodcution server

### ISSUE THREAD

**Issue by HassenBF** [i18next/i18next#381]
Hi , 
As stated in the title i'm using i18next on my website using the Node module and everything is working fine on my dev server on localhost , the problem is that when i test on my production server , translation stops working with an error message (ENOENT , errorn 34) .
Was anyone confronted to this problem before ? or have an idea about what's causing that ? 
thank you .

**Comment by jamuhl** [comment]
set init option debug = true ---> for sure it can't access the files.
