### ISSUE TITLE
How to define custom variable placeholders?

### ISSUE THREAD

**Issue by skotchio** [i18next/i18next#385]
According to documentation we use `__val__` placeholder to substitute passed variables. Is it possible to switch i18next to use custom placeholder like `{{ val }}` instead?

**Comment by jamuhl** [comment]
http://i18next.com/pages/doc_features.html#interpolation --> see hint 1

```
i18next.init({
  interpolationPrefix: '{{',
  interpolationSuffix: '))'
});
```
