### ISSUE TITLE
Config options for timeout?

### ISSUE THREAD

**Issue by abepark01** [i18next/i18next#386]
Hello,

First, thanks for building a great library for i18n.

<strong>Question</strong>
I am loading the translation from a REST API, but I would like to be make sure I can set a timeout value.
If the service is down and X amount of milliseconds has passed, I would like to timeout the request and let i18n just display the string keys.

Is something like this possible currently?
Thank you!
Abe

**Comment by jamuhl** [comment]
PR merged
