### ISSUE TITLE
i18next.com: broken download i18next-1.9.0.zip

### ISSUE THREAD

**Issue by erwinw** [i18next/i18next#390]
Hi!

Slightly OT, but seemed the best place to notify; there's an iss with the site: the link to http://i18next.com/public/download/versions/i18next-1.9.0.zip is broken.

Cheers!
Erwin

**Comment by jamuhl** [comment]
no that's perfect...thanks for letting me know...the file is now uploaded and can be downloaded.

**Comment by erwinw** [comment]
Great, thanks!
