### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience

### ISSUE THREAD

**Issue by krnlde** [i18next/i18next#391]
I keep getting this warning by Chrome because i18next sometimes forces to make synchronous calls (see [here](https://github.com/i18next/i18next/blob/1.9.0/i18next.js#L1555) for reference)

My question is, why is this even necessary? The last issue about that was back in 2013. Should and can this approach be reconsidered and solved properly?

Cheers,
Kai

**Comment by jamuhl** [comment]
this gets only called if someone accesses t function with a language not yet loaded. as t function is synchronous the only way to load the missing resources is in synchronous way.

the only other option is to not returning the translation and throw or log an error?

if you prefer this a PR would be welcome to have an init option to disable the loading of missing lng on accessing t.

**Comment by krnlde** [comment]
Unfortunately I'm not deep enough in your code to turn the right screws for a PR. I just have to use it and feel the pain.

Tough, I can't imagine any usecase where a sync ajax is unavoidable and even wanted. I mean, one can pass everything the code has to in a callback rather than right after the synchronous call, or am I missing something?

Mentioning the "t" function: How about aborting the initial call to it, load the stuff it needs asynchronously and then call it afterwards?

**Comment by jamuhl** [comment]
if the configuration is correct and you don't access t function for a not yet loaded language namespace pair...that synchronous call does not get triggered and so the warning does not appear.

**Comment by krnlde** [comment]
The prolem only appears when switching between languages. And of course they are not loaded yet. I'm using the ng-i18next plugin which handles that. My first thought was to intercept the language switch request and first load the language into i18next. Does that sound like a good workaround or is that hacky?

**Comment by jamuhl** [comment]
than it's an issue on ng-i18next

setLng has a callback - if you don't use t function before that callback all is fine.

**Comment by krnlde** [comment]
Close in favor of i18next/ng-i18next#89
