### ISSUE TITLE
http://zphipower.com/  not support ie8?

### ISSUE THREAD

**Issue by Dreampie** [i18next/i18next#394]

**Comment by jamuhl** [comment]
Supporting IE8 is not on my personal list of things i support - like a lot other frameworks. But i'm open to PR's fixing any issues related to hopeless outdated browsers.

**Comment by Dreampie** [comment]
ok，how to support  html tags？ 
```html
"nav": {
    "home": "Home<br>Link"
}
```

**Comment by jamuhl** [comment]
eg:

```
<a id="btn1" href="#" data-i18n="[html]myKey"></a>
$("#btn1").i18n();
```

see: http://i18next.com/pages/doc_jquery.html#jqueryfc --> setting html, prepend, append content

**Comment by Dreampie** [comment]
```javascript
//init i18n
$.i18n.init(function () {
  $('.i18n').i18n();
});
```

```html
<div class="language i18n"><a href="?setLng=en" data-i18n="app.language"></a></div>
```

not work...

**Comment by Dreampie** [comment]
http://zphipower.com/product.html  in safari  offen not work

**Comment by jamuhl** [comment]
hm...strange...not having an issue on: http://i18next.com/pages/sample.html?setLng=en-US

not sure what causes this on your site.

**Comment by Dreampie** [comment]
why,what's wrong with me,how can I fix it?

**Comment by jamuhl** [comment]
nothing todo with you. as i do this in my free time i just don't have the time to checkout every project and analyse where the mistake could be.

best way to get help on this would be to head over to stackoverflow and to ask there.

**Comment by jamuhl** [comment]
closing this due upcoming v2: http://i18next.github.io/i18next.com/

PRs welcome -> will drop ie8 (shim)
