### ISSUE TITLE
Providing a key in data-i18n-options attribute for interpolation

### ISSUE THREAD

**Issue by luujam1** [i18next/i18next#395]
Is it possible to provide keys in the data-i18n-options attribute instead of strings?

more info on the issue:
http://stackoverflow.com/questions/30532647/i18next-providing-a-key-in-data-i18n-options-attribute-for-interpolation

**Comment by jamuhl** [comment]
is nesting sufficient?

```
{
    'keyOne':'I am $(item)',
    'item': 'a person'
}
```

**Comment by luujam1** [comment]
That works fine. 

On a separate note I've tried using the nesting in the html in the following but also added a non-translated string:

    <div data-i18n="$t(keyOne) normal text which won't be translated"></div>

this outputs "I am normal text which won't be translated". If I run .i18n() on the div, the keyOne string isn't translated but if I remove the string afterwards it works fine. Is this to be expected?

**Comment by jamuhl** [comment]
not expected - but seems to be the case. i know we do the replacing on key...seems we don't do the nesting.

**Comment by luujam1** [comment]
I see. So by essentially doing: 

    "$t(keyOne) normal text which won't be translated"></div>

KeyOne is already translated to the locale text specified at the time the element is rendered. Anytime the locale changes and you try to run

    $('div').i18n()

On the element, the string won't change as it doesn't utilise nesting. Is it possible to be able to do this without utilising data-i18n-options?

**Comment by jamuhl** [comment]
sorry the late answer. not sure if that is possible. to be honest i personally never used the jquery stuff in my project as i always was dependent on some templating (handlebars,..) or nowadays using react.js.

so not to sure, nor enough time to test on my side. but i would love to accept any PR helping to improve your needs.

**Comment by jamuhl** [comment]
closing this due upcoming v2: http://i18next.github.io/i18next.com/

PRs welcome: https://github.com/i18next/i18next-jquery
