### ISSUE TITLE
not loading _plural variation with double-byte languages and __count__ is not in the singular form

### ISSUE THREAD

**Issue by leereamsnyder** [i18next/i18next#397]
I have this isolated here: http://codepen.io/anon/pen/Nqgbpy?editors=101 (run with a console open)

Given resources like this:

```json
{
  'en-US': {
     "resources": {
      "adding": "Adding an instance to the group...",
      "adding_plural": "Adding __count__ instances to the group...",
    }
  },
  'zh-CN': {
    "resources": {
      "adding": "正將實例新增至群組...",
      "adding_plural": "正將 __count__ 實例新增至群組...",
    }
  },
  'zh-XX': {
    "resources": {
      "adding": "正將 __count__ 實例新增至群組...",
      "adding_plural": "正將 __count__ 實例新增至群組...",
    }
  }
}
```

With the `en-US` variant, it works as expected: calling i18n.t('adding', {count:1}) returns the singular `adding` key, whereas `i18n.t('adding', {count:5})` returns the `adding_plural` variation.

With the included `zh-CN` language, the `_plural` variant is not loading. You always get the singular `adding` key.

However, in the fake `zh-XX` variant in the sample, if I include `__count__` in the singular, it works just like the `en-US` version, with `{count:1}` returning the singular and `{count:5}` returning the `_plural` form.

**Comment by jamuhl** [comment]
http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms

`zh` rule is no plurals: nplurals=1; plural=0;

In rare cases where plural form introduces difference in personal pronoun (such as her vs. they, we vs. I), the plural form is different. => we can't auto identify the rare cases

so if you want default behaviour for plurals you could replace the rule via. `i18next.pluralExtensions.addRule(lng, obj)`

sample:
```
i18next.pluralExtension.addRule("ar", {
  "name": "Arabic", 
  "numbers": [ 0, 1, 2, 3, 11, 100 ],
  "plurals": function(n) { return Number(n === 0 ? 0 : n == 1 ? 1 : n == 2 ? 2 : n % 100 >= 3 && n % 100 <= 10 ? 3 : n % 100 >= 11 ? 4 : 5); }
});
```
