### ISSUE TITLE
i18next jquery changeLang

### ISSUE THREAD

**Issue by cbaket** [i18next/i18next#401]
Hi! I'm trying to have a menu for diferent lanuages and when i click on any language i want all my page to be translated but i need to click twice to get it translated... :(
I got the following code:

/en/translation.json:

    ...
    "currentLang":English",
    ...
     
some html: (sorry for the html, i didn't know how to place html here, replace '[' and ']' with '<' and '>'

        ...
         [a data-i18n="currentLang" href="#" ][/a]
         [ul]
                 [li][a href="#" onclick="changeLang('en');"]English[/a][/li]
                        .... more languages ....
         [/ul]
        ...

Javascript on the end of my age:

        var options = {
            lng: "en",
            debug: true,
            resGetPath: './assets/locales/__lng__/__ns__.json'
        };

        i18n.init(options, function (t) {
            $(document).i18n();
        });

        function changeLang(lang){
            i18n.setLng(lang);
            $(document).i18n();
        }

The problem is that i need to click 2 times on every link to get the page translated.. ??
I found 2 solutions for that:

1- 

        function changeLang(lang){
            i18n.setLng(lang);
            setTimeout(function(){
                 $(document).i18n();
            },100);
        }

2-

        function changeLang(lang){
            i18n.setLng(lang);
        }

        function updateLang(){
            $(document).i18n();
        }

   and on every link, i do this: 

        onmousedown="changeLang('en');" onmouseup="updateLang();"

I tried to call the original function twice but it didnt work...
I tried also to put an alert between the two calls in the original function, like that:

        function changeLang(lang){
            i18n.setLng(lang);
            alert("hi");
            $(document).i18n();
        }

but that didn't work too... :(

Couldn'f find out what is happening.... 
Are my 2 solutions ok ??

Thanks :)

**Comment by cbaket** [comment]
I forgot to say that the first time I click a link, the default translation is loaded instead of the selected language, and the second time I click the same link, te correct language is loaded.

Tnanks! ;)

**Comment by jamuhl** [comment]
correct would be to wait for the callback on setLng to wait for resources to be loaded async:

````
    function changeLang(lang) {
        i18n.setLng(lang, function() {
            $(document).i18n();
        });
    }
````

**Comment by cbaket** [comment]
lol... sorry didn't see there was a callback.. :(
