### ISSUE TITLE
Plurals with a count of 1 not updating on language change

### ISSUE THREAD

**Issue by luujam1** [i18next/i18next#404]
I'm running in to a potential issue with plurals with a count of 1 on locale change. Here's some code:

    
    <div data-i18n="app.items" data-i18n-options='{"count":1}'></div>
    <div data-i18n="app.items" data-i18n-options='{"count":5}'></div>
    <button onClick="changeLocale()">change locale</button>

    <script>
	var changeLocale = function() {
	if($.i18n.lng() !== 'DE') {
		$.i18n.setLng('DE',function() {
			$('body').i18n();
		});
		} else {
		$.i18n.setLng('en',function() {
			$('body').i18n();
		});
		}
	};

    $.i18n.init({
        useLocalStorage: false,
		ns: {
			namespaces: ['i18n'],
			defaultNs: 'i18n'
		},
		resGetPath: 'locales/__lng__/__ns__.json',
        debug: true,
		useDataAttrOptions: true,
		defaultValueFromContent: false
    }, function(t) {
		$('body').i18n();
    });
    </script>

The i18n.json file in locales/dev:

    {
        "app": {
	      "items": "an item",
	      "items_plural": "__count__ items"
        }
    }  

The i18n.json file in locales/de:

    {
        "app": {
	      "items": "GER an item",
	      "items_plural": "GER __count__ items"
        }
    }

If I start in English and click on the change locale button then it will change to the German locale. If I click on it again then the string where the count is 1 won't change back to English but the string with count 5 is fine.

If I remove the defaultValueFromContent property OR provide a locale res store in the form of an object then it seems to work fine (see jsfiddle: http://jsfiddle.net/tjav931r/)

Any help would be much appreciated.

**Comment by jamuhl** [comment]
in the jsfiddle you don't wait for the callback on calling `setLng('de', function(t) {});`. here you set lng to 'DE' which should be 'de.

but else i don't see where you do wrong...could you get up a sample with getting resources from server?

**Comment by luujam1** [comment]
So I've uploaded the example to github: git@github.com:luujam1/i18nextplurals.git

I've made the changes you've suggested - I think it's down to the locale folder names. For some reason the plurals won't change when you switch to 'en' if you define only locales/dev and locales/de. If you change locales/dev to locales/en then it works fine. However I'd expect the locale of the plurals to default to the keys in locales/dev if locales/en doesn't exist.

**Comment by jamuhl** [comment]
might be as dev language has no plural definition that it does not get resolved correctly if language fallbacks to dev. not yet had time to look at your code. sorry. hard on time here.

**Comment by jamuhl** [comment]
ok...got time today to checkout your sample...very sorry for the long delay.

found an issue i18next writes the options back to the data-i18n-options (so you can call eg. $sel.i18n(options) those get written to data-i18n-options and on setLng you can just call $sel.i18n()). But on translating with plural there are some translation calls going on with setting lngs on options ---> so long story store short...lng gets fixed to 'dev' in your case.

i will fix this asap and publish a new version.

sorry again for the delay on investigation.

**Comment by luujam1** [comment]
I'll check the new version once it's available, thanks for your time.

**Comment by jamuhl** [comment]
closing this due upcoming v2: http://i18next.github.io/i18next.com/

PRs welcome
