### ISSUE TITLE
Use just one file for all translations

### ISSUE THREAD

**Issue by kararade** [i18next/i18next#405]
I have 3 json files for the translation "en-UK", "es-ES" and "fr-FR" each one in the respective ``` json/locales/__lng__/__ns__.json```, path.

That I want to do is merge the all files on just 1 main for the translations, so I will have something like the following

```json
{
"en-UK" : {......},
"es-ES" : {......},
"fr-FR" : {......},
}
```*

how should I set the init config to make it works? I can't found anything about that..

**Comment by jamuhl** [comment]
http://i18next.com/pages/doc_init.html#getresources --> read Load resource dynamically generated on server
