### ISSUE TITLE
wrong dependency for i18next client 

### ISSUE THREAD

**Issue by kirrg001** [i18next/i18next#406]
hey,

discovered a bug for version 1.9.0

wrong
"i18next-client": "^1.9.0"

right
"i18next-client": "1.9.0"

if not, it will throw this error
2015-06-23T19:39:53.195Z - debug: ReferenceError: addJqueryLikeFunctionality is not defined
    at init (.../node_modules/i18next/node_modules/i18next-client/i18next.js:957:13)

because its version 1.10.x of i18next-client

**Comment by jamuhl** [comment]
>v1.10.1 will use fixed client version

**Comment by kirrg001** [comment]
sure, but 1.10.1 wasnt available via npm a couple of minutes ago.
now it is :+1:

**Comment by jamuhl** [comment]
haha...yes...just was publishing, so done a little patch to get that fixed once and for all. thanks for reporting.

**Comment by kirrg001** [comment]
hehe supi :+1:
