### ISSUE TITLE
sendMissing does not execute request

### ISSUE THREAD

**Issue by pezioz** [i18next/i18next#408]
I implement i18next in my project. During the initialisation I put in the option 'sendMissing: true'. I inspect the i18n object, the options is well set, but when I try to translate missing keys, there is no request made to the server.

**Comment by calamarico** [comment]
Yea, i have the same problem with ng-i18next angular component, i think the 1.10.1 version is broken

**Comment by jamuhl** [comment]
will have a look asap. but i believe that works - as the test for this is still green https://github.com/i18next/i18next/blob/master/spec/functions/functions.postmissing.spec.js

**Comment by jamuhl** [comment]
just tested with https://github.com/i18next/i18next-node/tree/master/sample --- works like expected.

**Comment by calamarico** [comment]
ok jamuhl, maybe my problem is induced by ngi18next component, i have opened an issue to ngi18next repo, thanks.

**Comment by jamuhl** [comment]
any update on this one? was the issue found?

**Comment by calamarico** [comment]
Yeah sorry!, my problem was induced by ngi18next angular component, and it had been solved.
