### ISSUE TITLE
Small error in the documentation

### ISSUE THREAD

**Issue by scarlet9** [i18next/i18next#409]
In the initialization section,

> Set language after init:
> ```js
> i18n.setLng('en-US', function(err, t) { /* loading done */ });
> ```
> you could fix the language by calling it this way:
> ```js
> i18n.setLng('en-US', { fixLng: true }, function(enUS) { /* done */ });
> ```
> every call to enUS ( enUS(key, opts) ) will return in enUS even if setLng is called again in different lng

The `fixLng` example should also have `err` as a first argument before the translation function.
Hope no one mixes up with a same issue...

**Comment by jamuhl** [comment]
thanks for reporting....will be changes asap.

**Comment by jamuhl** [comment]
closing this due upcoming v2: http://i18next.github.io/i18next.com/

PRs welcome
