### ISSUE TITLE
Can't use i18next in app when lib it depends on also uses i18next

### ISSUE THREAD

**Issue by Glenndejaeger** [i18next/i18next#410]
Hi,

In our app we use i18next and it works fine. But since a few days we depend on an external UI component that also uses i18next as well. 

Now we notice that the external component is translated correctly but the app is no longer being translated. This is due to 2 i18n.init calls, 1 in the app and 1 in the component. When we remove the init call from the component and replace it with addResourceBundle on a new namespace the initialization fails.

How can our problem be solved?

**Comment by Alex-Wauters** [comment]
What is the recommended approach to use i18next in a reusable module? (used by projects which may or may not already use i18next).

**Comment by jamuhl** [comment]
is the component under your control (done by yourself). personally i would never use i18next inside a public shared component - i would go same way as moment.js or others and provide pure js files to add.

in our own projects (react.js based) we just pass the t function to other modules. So initialising i18next is app concern while modules could use translation functions, load additional namesspaces or addResourceBundles,...

**Comment by Alex-Wauters** [comment]
The component is under our control, but will be shared with external partners.
i18n is a global variable, so I should not need to pass it on for AngularJS modules?

Thank you for your answer, I am now considering to leave initialization and placement of the resources (addResourceBundle call in the module causes AngularJS injector errors) to the app. If i18n is not set, the module will instead use a basic translation function.

**Comment by jamuhl** [comment]
might be solved in https://github.com/i18next/ng-i18next for usages in combination with angular...but as i'm not the maintainer of that i'm not to sure.

**Comment by jamuhl** [comment]
upcoming v2 of i18next will support creation of multiple instances with own configurations and resource store...the singleton will be gone...

but still v2 needs a lot of work before landing and will take some more time to get all plugins, modules using i18next to get migrated to v2.

**Comment by Alex-Wauters** [comment]
Good to hear, thanks for the update!

**Comment by jamuhl** [comment]
v2 has class support:

closing this due upcoming v2: http://i18next.github.io/i18next.com/

PRs welcome
