### ISSUE TITLE
directionality function

### ISSUE THREAD

**Issue by MartijnR** [i18next/i18next#411]
I'd like to propose adding the i18n.dir() or i18n.directionality() method which returns either 'rtl' or 'ltr' (or perhaps null).

I'm current using this regex: `/^(ar|he)/.test(i18n.lng()) ? 'rtl' : 'ltr'`.

Any interest in this? I could send PR as well if desired.

**Comment by jamuhl** [comment]
sure...if you like you can add a PR....or i will add this for next minor release

**Comment by MartijnR** [comment]
Ok, I will give it a shot. I actually personally only need this functionality in 18next-node. Would that follow once it's merged in i18next?

**Comment by jamuhl** [comment]
yes that gets exposed on i18next-node, too
