### ISSUE TITLE
Initializing i18next syncronously yields a warning

### ISSUE THREAD

**Issue by koddsson** [i18next/i18next#415]
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental 
effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
```

Seems like the async option is being deprecated. Is there another way to make sure the library has fetched everything? Or a callback for when it's done loading?

**Comment by jamuhl** [comment]
i18next.init(options, function(err, t) { /* ready */ });

i18next.setLng(lng, function(err, t) { /* ready */ });

( -- or you can use promises (when using in combination with jquery) -- )

**Comment by jamuhl** [comment]
by the way upcoming v2 will drop the option to load synchronous...

**Comment by perrin4869** [comment]
With jquery you can use `holdReady` like so: 

```js
$.holdReady(true);
i18n.init({
...
}, function() {
        $.holdReady(false);
});
```
