### ISSUE TITLE
Question about _rulesPluralsTypes

### ISSUE THREAD

**Issue by runjak** [i18next/i18next#417]
When viewing the lines 139-147 of [i18next.plurals.js](https://github.com/i18next/i18next/blob/c14864d333368cc5983b2269b230bef4c996701b/src/i18next.plurals.js#L139-L147) I see the following, similar rules:

    1: function(n) {return Number(n > 1);},
    9: function(n) {return Number(n >= 2);},

what is the difference between these two, and why are both necessary?
I'd appreciate any explanation as it would help me understand the code better.

**Comment by jamuhl** [comment]
`9: function(n) {return Number(n >= 2);},` was once added as special case for french via a PR to support decimals:

https://github.com/i18next/i18next/pull/276

basically i was very uncertain about that...as hard to judge correctly when only speaking english and german.

**Comment by runjak** [comment]
Ah, thanks for the enlightenment :)

**Comment by runjak** [comment]
Ah, thanks for the enlightenment :)
