### ISSUE TITLE
Is there any way to disabled get lng from navigator?

### ISSUE THREAD

**Issue by luoguanzhong** [i18next/i18next#418]
I want only get lng from `queryString`, I use the below settings:

```js
{
    useCookie: false,
    detectLngFromLocalStorage: false
}
```

But how can i disabled get `lng` navigator?

**Comment by jamuhl** [comment]
no there is no such option yet...feel free to add a PR or let me do this for next version.

**Comment by jamuhl** [comment]
will be in v2.

closing this due upcoming v2: http://i18next.github.io/i18next.com/

PRs welcome
