### ISSUE TITLE
Translating placeholders and html anchor elements

### ISSUE THREAD

**Issue by akulkarni9** [i18next/i18next#419]
I wrote a script for translating a web app (hybrid mobile app). I checked i18next documentation and it is nothing when compared to documentations other frameworks and libraries. 
Having said it, here is my code:  (```add jqury.js here```)

        <script src="js/i18next-1.10.1.min.js"></script>
            <p id="welcome"></p>
            <p id="please"></p>
            <p id="post"></p> 
            <script>
                $.i18n.init({
                   //lng: 'en-US',
                   ns: {
                        namespaces: ['ns.common', 'ns.special'],
                        defaultNs: 'ns.special'
                },
                useLocalStorage: false,
               debug: true
              }, function(t) {
                 $('#add').text($.t('ns.common:add'));
                 $('#appname').text($.t('app.name'));
                 $('#congrats_msg').text($.t('app.congrats', {
                     congrats: ''
                 }))
                 $('#welcome').text($.t('app.welcome', {
                     welcome: ''
                 }))
                 $('#please').text($.t('app.please', {
                     please: ''
                 }))
                 $('#post').text($.t('app.post', {
                     post: ''
                 }))
                 $('#continue_span').text($.t('app.continue_span', {
                    continue_span: ''
                 }))
            });
    </script>  
ns.special.json (id-ID):

{
    "app": {
        "name": "i18n",
        "register": " DAFTAR __register__",
        "username": "nama pengguna __username__",
        "congrats": "Selamat! __congrats__",
        "welcome": "Selamat Datang di Bistip Aplikasi Mobile __welcome__",
        "please"  : "Lengkapi profil Anda, sehingga Anda __please__",
        "post"    : "posting yang ditampilkan pada timeline. __post__",
        "continue_span" : "LANJUTKAN __continue_span__",
        "log_fb_msg" : "Masuk dengan Facebook __log_fb_msg__",
        "or_span" : " Atau __or_span__",
        "link" : "lupa kata sandi? __link__",
        "sign_in" : "MASUK __sign_in__"
    }
}  

ns.special.json (en-US):

{
    "app": {
        "name": "i18n",
        "register": " REGISTER __register__",
        "username": "User name __username__",
        "congrats": "Congratulations! __congrats__",
        "welcome" : "Welcome to Bistip Mobile Application. __welcome__",
        "please"  : "Please complete your profile, so that your __please__",
        "post"    : "post are displayed on timeline. __post__",
        "continue_span" : "CONTINUE __continue_span__",
        "log_fb_msg" : "Login with Facebook __log_fb_msg__",
        "or_span" : " Or __or_span__",
        "link" : "Forgot password? __link__",
        "sign_in" : "SIGN IN __sign_in__"
    }
}  
When I run this code, it'll translate div, p and span elements successfully. But it doesn't work for anchor tag elements and placeholders. How can I make it work for anchor tag elements and placeholders? 
Pardon me for bad editing

**Comment by jamuhl** [comment]
read: http://i18next.com/pages/doc_jquery.html if using jquery

yes documentation in other frameworks is better - feel free to improve it. this project lives on community not on my solo effort.

**Comment by jamuhl** [comment]
```
$('mySelector').attr('placeholder', $.t('myKey'));
```

for getting html from key and setting that you will need to set html on selector (not text ---> that will encode it)
