### ISSUE TITLE
Plural with variable in key

### ISSUE THREAD

**Issue by claireso** [i18next/i18next#420]
Hi,

I converted a file from .po to .json format with the i18next-conv tool.
I would like to know if it is possible to have a variable in the key definition with a plural form.

Example:
In my translation.json, I have this:
```
"%(counter)s topic": "%(counter)s sujet",
"%(counter)s topic_plural": "%(counter)s sujets"
```

In my code:
```
i18n.t('%(counter)s topic', {counter: 1})
i18n.t('%(counter)s topic', {counter: 3})
```

But the plural is not working. Am I doing something wrong ? Can i18next support this format ?

Thanx in advance

**Comment by jamuhl** [comment]
http://i18next.com/pages/doc_features.html#plurals

```
// given resources
{           
  'en-US': { 
    translation: {  
      key: '__count__  child',
      key_plural: '__count__  children' 
    } 
  }
};
 
i18n.t("key", { count: 0 }); // -> 0 children
i18n.t("key", { count: 1 }); // -> 1 child
i18n.t("key", { count: 5 }); // -> 5 children
```

**Comment by jamuhl** [comment]
%(counter) could be done by using built in sprintf support:

http://i18next.com/pages/doc_features.html#sprintf

`i18n.t('%(counter)s topic', {counter: 1, count: 1})`

**Comment by claireso** [comment]
Nice, thank you for your quick response Jan.
