### ISSUE TITLE
TypeScript tests need to be fixed for TS 1.6

### ISSUE THREAD

**Issue by DanielRosenwasser** [i18next/i18next#421]
I'm currently combing through tests that will break in TypeScript 1.6 on DefinitelyTyped as part of  https://github.com/Microsoft/TypeScript/issues/4081.

i18next's tests currently break because they object literals are being passed with a `replace` property which isn't accounted for in the `I18nextOptions` type.

I tried to fix this, but I'm unsure of how to do so because `replace` doesn't seem to be documented at all. Would it be possible for one of the maintainers here to fix it, or if not, could you give me any pointers on how I could do so?

**Comment by jamuhl** [comment]
yes...vars for replacement could be put in options itself...to avoid collision with reserved words they could be placed into an object named replace.

the typescript support once was added by a contributor but is not officially maintained by myself (as i never used typescript nor won't invest time to learn it's conventions)

any PR fixing this will be merged...

**Comment by DanielRosenwasser** [comment]
Cool - thanks for being patient with TypeScript users using your project. :smiley:

**Comment by jamuhl** [comment]
honestly i would add support by myself - but always hard to motivate myself to learn something i don't really use.

**Comment by atsu85** [comment]
@jamuhl, 
> any PR fixing this will be merged...

here You are - please merge my pull request https://github.com/i18next/i18next/pull/449 to resolve this issue

**Comment by atsu85** [comment]
Thanks @jamuhl for merging my pull request. 
Could You create a new release, so i don't have to use my custom release for my project that uses jspm package manager?

**Comment by jamuhl** [comment]
v1.11.0 is on npm and repo has updated version + on http://i18next.com

thanks for the contribution
