### ISSUE TITLE
can't find express when requiring in browserify

### ISSUE THREAD

**Issue by perython** [i18next/i18next#423]
Hello! Since [Browserify cannot find express/jquery](https://github.com/i18next/i18next/issues/364) is closed I'm wondering how is it possible to configure i18next with browserify?

I use Marionette js and browserify for building and I when I import library

```javascript
import i18n from 'i18next';
```
I get this error:

```
Cannot find module 'express' from '<project_dir>/node_modules/i18next/lib'
```

Please help me with the issue.

**Comment by jamuhl** [comment]
do you require `i18next-client` from npm? or if `i18next` that would be wrong (thats the server integration for node.js)...

more info would help...as we changed that some time ago `i18next-client` https://www.npmjs.com/package/i18next-client does not require jquery nor express!

**Comment by perython** [comment]
Yeah, I figured it out, should be '-client' version, thanks man!
