### ISSUE TITLE
i18n.addRoute 'saved missingKey'

### ISSUE THREAD

**Issue by zauker** [i18next/i18next#424]
I'm using i18next on my node application with Express.
I've a route like that:

    i18n.addRoute('/:partToTraslate/partToNotTraslate', ['it', 'en'], app, 'post', function(req, res, next) {

but when the app start i receive always the follow warning message:

    saved missingKey `partToNotTraslate` with value `partToNotTraslate` to: locales/en/new.common.json

Is not possible set friendly URLs with a static string as a part of URL?
I'm wrong something?

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-node/blob/master/lib/i18next.js#L302

basically:

- route parts will be translated
- route parts starting with `:` will be kept as param

note:
/`:`partToTranslate --> `:` does not mean translate but like in express routes - this is a param

there is right now no way to have a part of the path not translated (beside the params).

feel free to add a PR for this, like eg. prefixed paths (eg. /`__`notTranslated will not be translated.

**Comment by jamuhl** [comment]
closing this due upcoming v2: http://i18next.github.io/i18next.com/

PRs welcome
