### ISSUE TITLE
Locales load only on main page

### ISSUE THREAD

**Issue by 3rdPancake** [i18next/i18next#425]
`applyReplacement` returns strings like `locales/en/ns.json` which means if page url is `/category/page/` ajax will try to get `/category/page/locales/en/ns.json`

Do you admit that this is a bug? If yes, fix is easy, I will make a PR.

**Comment by jamuhl** [comment]
has nothing todo with applyReplacement. the default of resGetPath is set to `locales/__lng__/__ns__.json` that is overridable via init options.

but your right. changing the default to `/locales/__....` would make more sense in most application scenarios. i will change that for next version.
