### ISSUE TITLE
request for React support (hoc components - i18next can be used in react with ease)

### ISSUE THREAD

**Issue by eriknyk** [i18next/i18next#426]
Hi,
This project is awesome and it is exactly that I was looking for,
and for my case,.. 
I see that you already have an angular support impl, you thinking have something for
Facebook's React impl?

Beast Regards.

**Comment by jamuhl** [comment]
would be a great idea to have some extra for react.

at my workplace we use combination of react, webpack and i18next. As we use jsx we directly use the t function, eg.:

`<span className='label-success'>{t('common:saved')}</span>`

so basically i lack of ideas what to provide for react other then an sample app (like eg. https://github.com/lllllinli/Sample---React-i18next).

**Comment by jamuhl** [comment]
any suggestion would be welcome...as i'm really out of ideas for this but really love react!

**Comment by KJTsanaktsidis** [comment]
We have implemented something to address this use case. It's basically a react component that lets you interpolate react components inside i18n strings. So you can do something like this:
i18n string: 'Hello, here is a __link__ to something"
jsx:
````
<I18n i18nkey='the-i18n-key'>
    <a key='link'>{"some other thing in here"}</a>
</I18n>
````

The i18n component splits the i18n string around the react component interpolation, so it ends up returning to react something like
````
<span>
    {"Helllo, here is a "}
    <a>{"some other thing in here"}</a>
    {" to something"}
</span>
````

**Comment by jamuhl** [comment]
will invest more time on this after  getting out i18next v2 (https://github.com/jamuhl/i18next-playground)

**Comment by jamuhl** [comment]
@KJTsanaktsidis how did you solve initialization of i18next? did you create a container component that waits for rendering it's child until init callback of i18next.init was called?

**Comment by KJTsanaktsidis** [comment]
Actually we compile our i18n resources in the main javascript bundle, so there is no network request required.

**Comment by pronabb** [comment]
Can someone please share one code example how to use i18next with React version 0.14 in jsx.

I am able to initialize i18n from  React component's componentDidMount function  and could see in console that the callback function is printing the translated text 

 $.i18n.init(i18NOptions, function(t) {
            var appName = $.t("login.index-WelcomeMsg");
console.log(appName); 
                    }
      );

But what I am looking for how this t function can be used in jsx.

**Comment by jamuhl** [comment]
we do something like this:

```
import _ from 'lodash';
import React from 'react';
import i18n from '../i18n';

/**
 * Usage
 * -----
 *
 * import { i18n } from 'taibika-client';
 *
 * const { translated } = i18n;
 *
 *
 * export default translated('myNamespace', MyComponent);
 * export default translated(['myNamespace', 'otherNamespaceNeeded'], MyComponent);
 *
 * If you want to use `translated` with other HoC's you can do:
 *
 * const enhanced = _.compose(
 *   myHoC,
 *   translated('myNamespace')
 * );
 *
 * export default enhanced(MyComponent);
 *
 * in MyComponent
 *
 * ...
 * render() {
 *   return <span>{this.props.t('title')}</span>
 * }
 * ...
 */

const Translated = function (namespaces, Component) {
  let t;

  return React.createClass({

    getInitialState () {
      return {
        updatedAt: null
      };
    },

    componentWillMount() {
      t = i18n.getFixedT(null, namespaces);
    },

    componentDidMount() {
      this.onI18nChanged = () => {
        if (!this.isMounted()) return;

        this.setState({ updatedAt: new Date() });
      };

      i18n.on('languageChanged loaded', this.onI18nChanged);
    },

    componentWillUnmount() {
      if (this.onI18nChanged) {
        i18n.off('languageChanged', this.onI18nChanged);
        i18n.off('loaded', this.onI18nChanged);
      }
    },

    onI18nChange() {
      if (!this.isMounted()) { return; }

      this.setState({ updatedAt: new Date() });
    },

    render() {
      const { updatedAt } = this.state;
      return React.createElement(
        Component,
        { ...this.props, t, updatedAt }
      );
    }
  });
};

export default _.curry(Translated);
```

**Comment by jamuhl** [comment]
where `../i18n` is:
```

import actions from './actions';
import i18n from 'i18next/lib';
import XHR from 'i18next-xhr-backend/lib';
import Cache from 'i18next-localstorage-cache/lib';
import LanguageDetector from 'i18next-browser-languagedetector/lib';


i18n
  .use(XHR)
  .use(Cache)
  .use(LanguageDetector);

// app --> i18n
actions.changeLanguage.listen(function(lng, cb) {
  i18n.changeLanguage(lng, cb);
});


i18n.on('missingKey', function(lngs, namespace, key, defaultValue) {
  monitoring.measure('translation-missing', 1, [lngs, namespace, key]);
});

// i18n.on('initialized', function(options) {
//   //logger.log('i18n: initialized with options', i18n.options);
// });

i18n.on('loaded', function(loaded) {
  let namespaces = _.reduce(loaded, function(memo, ns) { return memo = memo.concat(ns); }, []);
  namespaces = _.uniq(namespaces);
  namespaces = _.map(namespaces, function(ns) {
    return ns.replace(i18n.options.namespacePrefix + '.', '');
  });

  actions.namespacesLoaded(namespaces);
});


module.exports = i18n;
```

**Comment by jamuhl** [comment]
but this already runs under i18next v2: http://i18next.github.io/i18next.com/docs/migration/

**Comment by pronabb** [comment]
@jamuhl  Thanks for sharing this code snippet. I have started to use i18next V2. and its working fine with Handlebar templates. For React components I have created two i18n.js Translated.js). Now  should I call i18next.init with options  from my apps.js / main.js (Note: I am already doing that for Handlebars templates in our app)? Also in our apps spread attribute ({ ...this.props, t, updatedAt }) is not working as I am getting script error from jshint-jsx grunt task.

**Comment by jamuhl** [comment]
one init call is sufficient. just share that one i18next instance around...doing i18next.createInstance will always create an empty instance that is uninitialized.

had so far no issues...but we use react only (no handlebars and no pure html)

**Comment by pronabb** [comment]
@jamuhl  From my main.js/app.js I have already initialized (i18next.init(options)) i18next.  Can you please suggest how should I use that i18next instance with this Translated React component.

**Comment by jamuhl** [comment]
@pronabb expose your initialized instance of i18next and use that in the translated hoc:

```
import _ from 'lodash';
import React from 'react';
import i18n from '../i18n'; // your instance

/**
 * Usage
 * -----
 *
 * import translated from '../translated';
 *
 * ... see above comment
```

**Comment by pronabb** [comment]
@jamuhl  Thank you for your guidance. This is now working for our application which have static html, Handlebar and React implementation. Using same instance of i18next I am able to translate the pages. :-)

**Comment by jamuhl** [comment]
cool...that's good news for me...as you using a big mix in your tech stack i18next v2 seems to be rather stable.

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next contribution, feedback very welcome.

sample: https://github.com/i18next/react-i18next/tree/master/example
