### ISSUE TITLE
Why do we need Post Processing if key not found ? <Bug?>

### ISSUE THREAD

**Issue by aceslick911** [i18next/i18next#430]
My application always uses the sprintf post processing while invoking the i18n translation.
Ex : 
      i18n.t("--%", {sprintf: {appname: 'customApp'}, postProcess: 'sprintf'})

So for a scenario where the identifier doesn't exist in my translator file and the identifier contains the special character % , I will be landing in a valid exception by sprintf "Uncaught SyntaxError: [sprintf] unexpected placeholder(…)"

But why do the _translate file need to invoke the postProcessors if the key notfound ? 

.....Source code snippet below.....

function _translate(potentialKeys, options){

if (found === undefined) {
            notFound = applyReplacement(notFound, options);
            notFound = applyReuse(notFound, options);

            if (postProcessor && postProcessors[postProcessor]) {
                var val = _getDefaultValue(key, options);
                found = postProcessors[postProcessor](val, key, options);  --Comments Do we need this?
            }
        }

}

**Comment by jamuhl** [comment]
it does this for the 'eventual existing' default value, which might be a default value or the key (in case of using gettext form keys).

solution might be:
```
if (postProcessor && postProcessors[postProcessor]) {
            var val = _getDefaultValue(key, options);
            found = value;
            try {
                found = postProcessors[postProcessor](val, key, options);  --Comments Do we need this?
           catch(e) {}
        }
```

what do you think?

**Comment by aceslick911** [comment]
Thank you for the reply jamuhl.
The better solution would be to postProcess only if it is a value but not the key.

We get the key returned whenever there is no defaultValue being provided so it dosent make sense to postProcess the key .

    if (postProcessor && postProcessors[postProcessor]) { 
                var val = _getDefaultValue(key, options);
                if(val !== key){
                    found = postProcessors[postProcessor](val, key, options);
                }
            }
Any suggestions?

**Comment by jamuhl** [comment]
post processing key makes sense...think of keys in form of defaultvalue -> where key is used as fallbackLanguage, like most gettext based tools work.

so still needs an additional option on init.

**Comment by jamuhl** [comment]
closing this due upcoming v2: http://i18next.github.io/i18next.com/

PRs welcome
