### ISSUE TITLE
loadNamespace callback sometimes fires before init callback fires

### ISSUE THREAD

**Issue by sudsy** [i18next/i18next#433]
I wanted to put together a fiddle for this, but it is a little tricky due to remote assets.

If I call init and then call loadNamespace prior to the init function callback firing, the loadNamespace callback sometimes fires prior to the translator being initialised resulting in the following error.

i18next not finished initialization. you might have called t function before loading resources finished.

In my opinion, the load namespace callback should not fire unless the library has initialised.

If you agree, I can look into this further and see if there is a simple fix.

**Comment by jamuhl** [comment]
yes sure...would be great. as i'm working on upcoming v2.0.0 i'm very thankful for your help.

**Comment by jamuhl** [comment]
closing this due upcoming v2: http://i18next.github.io/i18next.com/

PRs welcome
