### ISSUE TITLE
Interpolation like with gettext?

### ISSUE THREAD

**Issue by steevhise** [i18next/i18next#434]
I'm wondering if there's a way to set up i18next to interpolate variables within a key in a template the way a gettext-based system does.  i.e.  

a = 2
b = 4 
gettext('I have [_1] apples and [_2] oranges', a, b)  would end up as:
I have 2 apples and 4 oranges 

I've been over the docs and don't really see how to do it.

**Comment by jamuhl** [comment]
http://i18next.com/pages/doc_features.html#interpolation --> hint 1: Interpolation Prefix/Suffix
```
i18next.init({
  interpolationPrefix = '[_',
  interpolationSuffix = ']'
});
// given resources
{           
  'en-US': { translation: {  key: '[_myVar] are important' } }
};
 
i18n.t("key", { myVar: "variables" }); // -> variables are important
```

**Comment by steevhise** [comment]
Thanks for the speedy reply!  I was wondering about those settings. but you mean, don't you:
```
 interpolationPrefix: '[_',
 interpolationSuffix: ']',
```
Anyway, it doesn't seem to quite work.  you seem to be talking about within the translation catalog, but I'm talking about in the templates and/or js code.  I want to be able to put this in a jade template:

 `  = t("[_1] are important", 'variables');   //  -> variables are important `

But that's not actually getting evaluated correctly (the placeholder is just showing up literally as '[_1]'.

Also, for the record, the above settings apparently change the way the locale gets substituted into the `resGetPath`.

**Comment by steevhise** [comment]
oops.  I hadn't realized the variable had to be passed as a hash. thanks.
