### ISSUE TITLE
Pass resources manually on init or afterwards

### ISSUE THREAD

**Issue by perrin4869** [i18next/i18next#436]
I've been browsing the documentation for a while but I have not been able to find a way to achieve this... basically I want to load the json resources by myself and pass them them to i18next at init time, it would be simpler in my case.

**Comment by jamuhl** [comment]
http://i18next.com/pages/doc_init.html --> scroll down to 'options to load resources'

`i18next.init({resStore: myData});`
`i18next.addResourceBundle(lng, ns, data, [deepMerge]);

**Comment by perrin4869** [comment]
Oh damn feel stupid now, flew over my head!
btw, I'm interested in writing a simple gulp-i18next-conv plugin, however the current i18next-conv is not very gulp since it deals on the file level more than the content level. Should I send a pull request to i18next-conv first?

**Comment by jamuhl** [comment]
@perrin4869 sure

**Comment by perrin4869** [comment]
Actually, I already did a few days ago, here: https://github.com/i18next/i18next-gettext-converter/pull/24
And I already have a working gulp plugin using that pull request :)

**Comment by jamuhl** [comment]
commented there...will be merged asap.
