### ISSUE TITLE
Translate JSON

### ISSUE THREAD

**Issue by a58az** [i18next/i18next#437]
Hello, I have a json, with arrays and objects inside it, can I translate whole json at one time?

**Comment by jamuhl** [comment]
see: http://i18next.com/pages/doc_features.html#objecttree

**Comment by a58az** [comment]
I see it, but can I translate whole tree. I load translation from file, and small example of it:
```
{
  "buttons": {
    "ok": "Ok",
    "yes": "Yes",
    ...
  },
  "labels": {
    ...
  }
}


```

So can I get all translation from root, where will be labels and buttons

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/spec/translate/translate.objectValue.spec.js#L90

**Comment by jamuhl** [comment]
you need to go at least one key deep...`myNS.buttons` in your case. Only way right now would be to nest your data inside an additional level.

But a PR would be welcome to change that so one could request the root level by omitting the key.

**Comment by jamuhl** [comment]
closing this due upcoming v2: http://i18next.github.io/i18next.com/

PRs welcome
