### ISSUE TITLE
Explicit Interval Pluralization

### ISSUE THREAD

**Issue by jayS-de** [i18next/i18next#441]
It would be good to have the possibility for explicit pluralization based on a given interval. The pluralization rules will not really work out as the intervals can differ for every translation text.

Example:
```
0: There are no apples
1: There is one apple
2-99: There are __count__ apples
100-Inf: There are many apples
```
The [Symfony translator](http://symfony.com/doc/current/components/translation/usage.html#explicit-interval-pluralization) for example uses the ISO-31-11 notation for intervals like this:

```
{0} There are no apples|[20,Inf[ There are many apples|There is one apple|a_few: There are %count% apples
```

**Comment by jamuhl** [comment]
yes agree...would like this to land sooner or later. realistical it will be later...right now i'm working on v2 of i18next, might land there some day...but i don't expect it to be there on first release of v2...hardly got enough time to get v2 compatible to v1.

progress on v2 could be found here until getting more beta ready: https://github.com/jamuhl/i18next-playground

**Comment by jamuhl** [comment]
you now can use https://github.com/i18next/i18next-intervalPlural-postProcessor with i18next v2 (http://i18next.com/docs/migration/)
