### ISSUE TITLE
Get locale chosen by i18next

### ISSUE THREAD

**Issue by Fiveside** [i18next/i18next#445]
I'd like a way to get the locale that was chosen by i18next for use when localizing other libraries.

For example.  Let's say I have translations for `en` and `de` and the default set to `en`.  When a user provides a locale of `de-DE`, I'd like to get `de` back from i18next since I have a translation for it.  When I provide a locale of `es-ES`, I'd like to get back `en` back from i18next since it fell back to the default.

My goal is to have moment.js use the same locale that i18next is using (for a more consistent experience).

How can I get the locale that i18next is using?

**Comment by jamuhl** [comment]
you can take i18n.lng() - but that might be not what you won't...as it uses internally an array to lookup the translations, eg. for es-ES `['es-ES', 'es', 'en']`, while .lng() will return es-ES the lookup might go down to en resource as the key neither exists in es-ES and es.

you might reduce this by setting on init:

    lngWhitelist: ['en', 'de'], // -> only this lngs are allowed
    load: 'unspecific', // only de but not de-DE or de-CH is allowed

**Comment by jamuhl** [comment]
closing this due upcoming v2: http://i18next.github.io/i18next.com/

PRs welcome
