### ISSUE TITLE
Update translations without page reload 

### ISSUE THREAD

**Issue by crebuh** [i18next/i18next#447]
Hi, 

first of all thank you for this great library. It makes the translation of js-apps really simple!

In our application we only have one small problem. To load modules we are using require.js. Some of the modules like for example our Base "MyApp" Class is loaded only once.

        define([
        'jquery',
        'underscore',
        'backbone',
        'marionette',
        'confighandler',
        'i18n'
    ], function(
        $,
        _,
        Backbone,
        Marionette,
        vent,
        i18n
    ) {
        'use strict';
        var MyApp = {};

        //MyApp.Application
        MyApp.Application = Marionette.Application.extend({});

        // MyApp Paginator
        MyApp.Paginator = Backgrid.Extension.Paginator.extend({
            renderIndexedPageHandles: false,
            controls: {
                rewind: {
                    label: '《',
                    title: i18n.t('ui.buttons.first')
                },
                back: {
                    label: ' ' + i18n.t('ui.buttons.back') + ' ',
                    title: i18n.t('ui.buttons.back')
                },
                forward: {
                    label: ' ' + i18n.t('ui.buttons.forward') + ' ',
                    title: i18n.t('ui.buttons.forward')
                },
                fastForward: {
                    label: '》',
                    title: i18n.t('ui.buttons.last')
                }
            }
        });

        return MyApp;
    });

It works fine, the translations were loaded with the default browser language. If I set the language afterwards the translations in this are not updated. All other translations which are loaded e.g. in views, controllers (at a later point in the application) were translated to the other language. 

Does anybody has an idea how to refresh the translations also in these files?

The problem seems to be similar to this issue: https://github.com/i18next/i18next/issues/363 ... but with the difference that the modules are loaded with require.js

**Comment by jamuhl** [comment]
basically on language change you must rerender the component/template...there is no other way i know of...you might head over to stackoverflow for more people looking onto it?

**Comment by crebuh** [comment]
yes i see, i am doing this for almost all of the views in our application, but some modules were loaded just once and then the strings stay in the first selected language.

is there a possibility to reload certain modules (i know this more related to require.js)?

**Comment by jamuhl** [comment]
http://requirejs.org/docs/api.html#undef might do the trick but will trigger a reload i think...not really what you want. IDK
