### ISSUE TITLE
webpack error Cannot resolve json-loader

### ISSUE THREAD

**Issue by cch5ng** [i18next/i18next#450]
hi, I'm working on an application using react + webpack on the front-end and flask-babel on the backend. after I installed i18next, I saw webpack errors like Cannot resolve express. I installed express but is that necessary for using i18next on the client? should I be using the i18next-client with jQuery instead and can I use that syntax within react?

I'm currently getting webpack errors like:

ERROR in node_modules/i18next/lib/i18nextWrapper.js
Module not found: Error: Cannot resolve module 'json-loader' in node_modules/i18next/lib
 @ node_modules/i18next/lib/i18nextWrapper.js 8:22-48

ERROR in node_modules/i18next/lib/i18nextWrapper.js
Module not found: Error: Cannot resolve module 'json-loader' in node_modules/i18next/lib
 @ node_modules/i18next/lib/i18nextWrapper.js 9:28-66

... however, I have installed json-loader and my webpack.config.js (excerpt) looks like:

```
  module: {
    loaders: [
      { test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loaders: ['babel-loader', 'gettext-loader'],
      }
    ],
  },
  externals: {
          // Use external version of React
          'react': 'React'
      },
  resolve: {
      extensions: ['', '.js', '.jsx', '.json'],
      root: 'node_modules/',
      alias: {
          'chai': 'chai/lib/chai.js',
          'jquery': 'jquery/src/jquery.js',
          'i18next': 'i18next/lib/i18next.js',
          'require-json': 'require-json/index.js',
          'json-loader': 'json-loader/index.js'
      },
  },
  node: {
      express: 'empty',
      fs: "empty",
      net: 'empty'
    }
```  

... is there something I am missing in the config that needs to be fixed? thanks.

**Comment by jamuhl** [comment]
for client usage please `npm install i18next-client`

**Comment by brenoc** [comment]
I think json-loader is trying to act in your node_modules directory. Try excluding node_modules:

```
{
  test: /\.json$/,
  exclude: /node_modules/,
  loader: 'json-loader'
},
```

**Comment by jamuhl** [comment]
closing this due upcoming v2: http://i18next.github.io/i18next.com/

PRs welcome
