### ISSUE TITLE
Nested resources not being followed when using fallback namespaces

### ISSUE THREAD

**Issue by pconnell99** [i18next/i18next#452]
I've got two files I load (**customLoader**), 'application' and 'theme'.  'Theme' is a subset of the keys in 'application', so if it is not in default ('theme') it falls back to 'application' for the key.  This works fine.

However, I have been using internal mappings to reduce redundancy.  Example:-

`{
     "app": {
                 "key1": "Hello",
                 "key2": "$t(app.key1) World"
    }
}`

This no longer works, returning `app.key1 World` instead of `Hello World`

Am I doing it wrong?  Should this be supported - it was working when I wasn't doing a two-file namespace fallback on null.

**Comment by jamuhl** [comment]
this should work...but think that was not tested to much...not sure why it does not work as intended. right now i'm working hard on i18next v2...so a PR or further investigation why this does not work would be big help.

**Comment by pconnell99** [comment]
I'll let you know what I find.  As long as it 'should' work I'm happy to help.

**Comment by pconnell99** [comment]
It could be the `options.isFallbackLookup` boolean variable in function `_find()`.  Just cycling through the code, it looks like that is set to stop recursion, which is fine, but if it's not found in the 'default' ns it then tries the fallback - one recursion means this is set to true.  The we have a second fallback as we convert the key to a lookup of the actual key but the for loop at line 1809 is triggered to not run due to this variable being set, so no lookup and it returns the string?

Not being familiar with the codebase this is what seems to make sense, let me know, otherwise I'll keep on looking.

**Comment by jamuhl** [comment]
yes...that could be it...need resetting the flag on the lookup for nested (reuse) values.

**Comment by pconnell99** [comment]
I can try to do this, but if you have any suggestions as to where to start I'd appreciate it, as this is just one of many libraries I use in my app so I've not really got the time to dedicate to a large examination of the code to fix it - any pointers as to a beginning of a solution and I'll have a go.

**Comment by jamuhl** [comment]
think i found and fixed it...do you use i18next from npm, via bower or download? depending on that i will publish that fix for you.

**Comment by pconnell99** [comment]
I just download from the website - non-minified (I minify it myself) -  I have 1.11.0

**Comment by jamuhl** [comment]
can you search there for `delete opts.postProcess;`

```
function applyReuse(translated, options) {
    var comma = ',';
    var options_open = '{';
    var options_close = '}';

    var opts = f.extend({}, options);
    delete opts.postProcess;
   ...
```

add `delete opts.isFallbackLookup;` after that line. And try if that fixes it...will publish 1.11.1 if ok.

**Comment by pconnell99** [comment]
That appears to work in my case, yes.  Thank you very much for this.

**Comment by jamuhl** [comment]
great...1.11.1 will be on website in a few minutes...containing this change.
