### ISSUE TITLE
Default value for all missing keys

### ISSUE THREAD

**Issue by anius** [i18next/i18next#454]
Is it possible to use default value for all missing keys? 

I am wring tests with karma and jasmine and I would like to use some default value for all i18next keys without a need to use language file or use of fixtures.

I tried to use `parseMissingKey`, `missingKeyHandler` and `postProcess` functions to return some default value but without success so now I am wondering if it is possible to implement defaultValue in some way? 

I cannot pass `defaultValue` to each string as shown on i18next documentation page `i18n.t("key", { defaultValue: "my text" });`.

**Comment by jamuhl** [comment]
best for ci is setting lng to `cimode` that will return keys instead of translations. so you have a fixed value for test...
