### ISSUE TITLE
Why not have an option to load 'namespace' from different path?

### ISSUE THREAD

**Issue by luisfmsouza** [i18next/i18next#455]
Hi, I'm using JSPM + SystemJS to split my application in modules. 

So, I decided to translate my app, and now I'm facing some issues because I didn't found a beautiful way to have my namespaced file inside the module.

I've thought about it, and one of possible solutions is include a path when we declare a new namespace, like:

```
ns: { 
  namespaces: [
    {'nsModule1': 'modules/myModule1/locale/en-Us/myModule1.json'}, 
    {'nsModule2': 'modules/myModule2/locale/en-Us/myModule2.json'}
  ], 
  defaultNs: 'ns.special'
}
 ```

and the, I can use something like this:

```
$.t('nsModule1:property.value');
```

What you think?

**Comment by jamuhl** [comment]
upcoming v2 will have pluggable backend (v1 naming sync) implementations. it would be a lot easier to write a own one or extend https://github.com/i18next/i18next-xhr-backend the xhr-backend to modifiy loadPath before loading.

Also it is possible to clone or create new i18next instances so you could basically create a new instance for every module if preferred.

early migration guide can be found here: http://i18next.github.io/i18next.com/docs/migration/

for current version you might try to set `customLoad` function on init: https://github.com/i18next/i18next/blob/master/src/i18next.sync.js#L91

but looking at your build chain you really might get happier changing to v2 of i18next.

**Comment by luisfmsouza** [comment]
Thanks for your answer @jamuhl. v2 probably will help me a lot.

I've checked your advices. I couldn't use the `customLoad`, because I can't use custom options when I call ` loadNamespace `(it loads the default ones).

By now, my solution is change the custom options before `init`:
```
resGetPath: 'modules/__ns__/locales/__lng__/__ns__.json'
```

And maintain the namespace the same of the module name. It works until now :+1:

**Comment by vekexasia** [comment]
+1

**Comment by jamuhl** [comment]
v2 is out...should be rather easy to get this up by:

a) create a new instance for a module
b) write a own backend implementation

**Comment by vekexasia** [comment]
jamuhl i can't access the migration guide ...

**Comment by jamuhl** [comment]
released...now under i18next.com

http://i18next.com/docs/migration/

**Comment by vekexasia** [comment]
Thanks @jamuhl . Do you have a sample backend with all the methods that needs to be defined? and/or documentation of the backend contract?

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L67

**Comment by vekexasia** [comment]
Hello @jamuhl unfortunately it's not possible by simply creating a custom backend to pass object in `loadNamespaces`

So it's not possible to:
```javascript
i18next.loadNamespaces([{ns:'module', path:'/my/path'}], ()=>{});
```

cause ResourceStore.getResource uses `utils.getPath` which does not like the object but probably expects a string.

my backend doesn't get the `read` fn called. the full stacktrace is:

```
TypeError: key.indexOf is not a function
    at cleanKey (/home/andrea/git/ristoranti_node/lib/generics/i18n/node_modules/i18next/lib/utils.js:28:23)
    at getLastOfPath (/home/andrea/git/ristoranti_node/lib/generics/i18n/node_modules/i18next/lib/utils.js:43:8)
    at Object.getPath (/home/andrea/git/ristoranti_node/lib/generics/i18n/node_modules/i18next/lib/utils.js:68:25)
    at ResourceStore.getResource (/home/andrea/git/ristoranti_node/lib/generics/i18n/node_modules/i18next/lib/ResourceStore.js:73:20)
    at ResourceStore.hasResourceBundle (/home/andrea/git/ristoranti_node/lib/generics/i18n/node_modules/i18next/lib/ResourceStore.js:141:19)
    at /home/andrea/git/ristoranti_node/lib/generics/i18n/node_modules/i18next/lib/BackendConnector.js:182:34
    at Array.forEach (native)
    at /home/andrea/git/ristoranti_node/lib/generics/i18n/node_modules/i18next/lib/BackendConnector.js:180:26
    at Array.forEach (native)
    at /home/andrea/git/ristoranti_node/lib/generics/i18n/node_modules/i18next/lib/BackendConnector.js:179:23
```

the workaround I can think of is to expose the backend to my modules which have to register the path for their namespaces but this could look like spaghetti code. Do you have any suggestion for creating a  way where loadNamespaces accepts the path to the namespace?

**Comment by jamuhl** [comment]
i would:

`i18next.loadNamespaces('moduleNameOrPath.namespace', ()=>{});`

in the custom backend just split the given namespace. 

https://github.com/i18next/i18next-node-fs-backend/blob/master/src/index.js#L48
```
// loadPath: '{{module}}/locales/{{lng}}/{{ns}}.json',
let parts = namespace.split['.'];
let filename = this.services.interpolator.interpolate(this.options.loadPath, { lng: language, ns: parts[1], module: part[0] });
```

or even lookup path via moduleName.
