### ISSUE TITLE
Cache busting and built-in ajax loader

### ISSUE THREAD

**Issue by mattbailey** [i18next/i18next#456]
https://github.com/i18next/i18next/blob/master/src/i18next.helpers.js#L237

It would be really nice to be able to set this flag in .init() or be able to set my own cache busting QS param.

**Comment by jamuhl** [comment]
my plan is to not allow new features on current v1. just adding fixes.

try http://i18next.github.io/i18next.com/ --> PR to add cache busting would be welcome on 2.0.0 branch.

**Comment by mattbailey** [comment]
Understood, thanks!

**Comment by jamuhl** [comment]
xhr implementaion for 2.0.0 can be found here: https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js
