### ISSUE TITLE
Typo in 2.0.0?

### ISSUE THREAD

**Issue by andrewbranch** [i18next/i18next#458]
This line throws an error for me (I'm using i18next-xhr-backend@0.0.4, not sure if it makes any difference):

https://github.com/i18next/i18next/blob/2.0.0/lib/BackendConnector.js#L62
`Cannot read property 'allowMultiLoading' of undefined`

Should it be `this.backend.options.allowMultiLoading`? That's defined. Happy to open a PR if you can confirm this issue.

**Comment by jamuhl** [comment]
should be on `this.options.backend.allowMultiloading`. Not fully sure whats the issue. Did you add the XHR backend in your code but not added backend options in init:

```
i18next.init({
  backend: {...}
});
```

while writing this i see the point...you're right...when i allow setting options directly on an instance of a backend and adding that by `i18next.use` i need to use the options defined there.

Will publish an update asap. Meanwhile as a fast fix just add the backend options to the init options of i18next. Like https://github.com/i18next/i18next-xhr-backend#backend-options --> preferred way.

**Comment by jamuhl** [comment]
oh and thanks a lot for finding this...good to have this fixed in final release.

**Comment by jamuhl** [comment]
can you try with v2.0.0-beta.1...should fix this.

**Comment by andrewbranch** [comment]
Hey, forgot to respond, that did fix it. Thanks for the quick fix!

**Comment by jamuhl** [comment]
great...thanks for the confirm.
