### ISSUE TITLE
[placeholder] not supported ?

### ISSUE THREAD

**Issue by rotan1** [i18next/i18next#459]
Hi,

I try the v2.0 of i18next and I want to localize placeholder with [placeholder] attribute but it crashes with : 
JavaScript runtime error: Unable to get property 'nodeType' of undefined or null reference

I tried with [title] but it does the same. The [html] works well.

Is this a known bug ?

Thanks.

**Comment by jamuhl** [comment]
so you're using https://github.com/i18next/i18next-jquery...hm...looking at code i don't see difference from last version:

https://github.com/i18next/i18next-jquery/blob/master/src/index.js#L53

if you got time i would be glad if you could investigate what happens...else i will try to find this the next days.

**Comment by rotan1** [comment]
Bug fixed.

Here's the code. Just replace the line you sent to me by `ele.attr(attr, i18next.t(key, extendDefault(opts, ele.attr(**attr**))));`

You just had to add "attr" in the ele.attr function call

**Comment by jamuhl** [comment]
arghhh...how stupid of me...will fix this and publish a patch.

**Comment by jamuhl** [comment]
fixed in 0.0.3. thanks for fixing.

**Comment by rotan1** [comment]
You're welcome.
