### ISSUE TITLE
i18next-1.11.1 - forEach fails on IE8

### ISSUE THREAD

**Issue by lmmurphy** [i18next/i18next#460]
Upgrading from 1.7.7 to 1.11.1 causes a failure on IE8.  Looks like it is because of the forEach statements.

**Comment by jamuhl** [comment]
working on v2 right now...which will drop ie8 support.

if you can provide a PR that would help a lot. will release a v1.11.2 asap.

**Comment by lmmurphy** [comment]
Provided PR was merged.  Release 1.11.2 fixes this issue.
