### ISSUE TITLE
i18next not finished initialization

### ISSUE THREAD

**Issue by danpadua** [i18next/i18next#462]
Hello guys. I'm having this problem right after I load my page. Some translations do not appear on the screen, especially when I insert data to my DataTable. I do not know if the codes runtime, most believe that it can not be, because only the DataTable's this problem occurs. Would you have any idea how to solve this? The following error:

"i18next not finished initialization. you might have called t function before loading resources finished."

Thanks for all...

**Comment by jamuhl** [comment]
resource loading is async.

```
i18next.init(options, function(err, t) { /* loading done */ });
```

**Comment by jamuhl** [comment]
closing...if still unclear...feel free to reopen
