### ISSUE TITLE
customLoad function in i18next v2

### ISSUE THREAD

**Issue by anius** [i18next/i18next#465]
I have been using customLoad i18next v1.11 to load and process languages I need.

I am trying to migrate to i18next version 2 now and as far as I can see there is no customLoad function.

Was this function renamed or should I use custonLoad in some special way in version 2?

**Comment by jamuhl** [comment]
customLoad  functionality can be replaced by own backend implementation.

for sample see the xhr backend: https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L67

**Comment by anius** [comment]
Could you provide ES5 simple example of own backend implementation?

I was trying a very simple implementation with console.log but it doesn't seem to work:
`
var i18next = require('i18next');
var myLoader = require('myLoaderPath');

i18next
  .use(myLoader)
  .init(options, function (t) {
   console.log('Loaded');
});
`

and `myLoader`:
`
module.exports = {

    type: 'backend',

    init: function () {
      console.log('Initializing');
    }
}
`
I am not getting any console.log output. I just need a very simple example how to construct own backend loader (customLoader in i18next v1.11) in ES5 so that it works with i18next v2.

**Comment by jamuhl** [comment]
Just tried to add a test:

```
import i18next from '../src/i18next.js';

let myBackend = {

    type: 'backend',

    init: function () {
      console.log('Initializing');
    }
}

describe.only('i18next', () => {

  before(() => {
    i18next
    .use(myBackend)
    .init({
      lng: 'de',
      foo: 'bar',
      debug: false
    });
    i18next.changeLanguage('en');
  });

  it('should', () => {
    // bla
  });

});
```

outputs:
```
LOG LOG: 'Initializing'
    ✗ "before all" hook
	TypeError: 'undefined' is not a function (evaluating 'this.backend.read')
	    at read (/var/folders/vw/8_nbgrss5cx0yy76pp13nxrc0000gn/T/2a296a0266e0d7787c4dcd78397decbc.browserify:10 <- src/BackendConnector.js:9:0)
	    at /var/folders/vw/8_nbgrss5cx0yy76pp13nxrc0000gn/T/2a296a0266e0d7787c4dcd78397decbc.browserify:10 <- src/BackendConnector.js:9:0
```

=> init call seems to work (just add additional read fc).

**Comment by anius** [comment]
Thank you.

**Comment by jamuhl** [comment]
works now?

**Comment by anius** [comment]
Yes, everything works fine.

**Comment by jamuhl** [comment]
great
