### ISSUE TITLE
Some pages are down

### ISSUE THREAD

**Issue by strarsis** [i18next/i18next#466]
Some documentation/pages are down, like
http://i18next.com/node/pages/doc_express.html

Thank you and
with best regards

**Comment by jamuhl** [comment]
with v2 of i18next same code base is used. just use matching backends (eg. xhr in browser, fs in node).

for node.js basically https://github.com/i18next/i18next-express-middleware replaces i18next-node.

old pre v2 docs could still be found here: http://i18next.github.io/i18next/
