### ISSUE TITLE
Firefox is giving some warning during loading i18next.min.js

### ISSUE THREAD

**Issue by pronabb** [i18next/i18next#467]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create.

**Comment by jamuhl** [comment]
never looked at ff...will take a look...not sure where the problem is...more or less there are only es6 classes used.

**Comment by hugofqueiros** [comment]
+1

**Comment by jamuhl** [comment]
According to zloirock/core-js#46 this is not something to be concerned about. The line that throws it is injected into the top of MatrixDispatch presumably by babel: eg. https://github.com/i18next/i18next/blob/master/lib/BackendConnector.js#L19
