### ISSUE TITLE
Problems with plurals >= 3

### ISSUE THREAD

**Issue by Lonelind** [i18next/i18next#468]
Hi! I have some problems with plurals. I'm Russian, and our language has 3 plural forms: single, multiple for x2–x4 except x11–x14, that work like other multiple plurals. And sometimes I need to use parts for text formatting, like ```<a>``` or ```<mark>``` tags around some words. So, I split my text like this:

locales/ru/common.json
```json
{
    "SomeTextKey": {
        "part0": "Укажите, пожалуйста",
        "part1": "не менее",
        "part2": "предметов.",
    },
    "SomeTextKey_0": {
        "part0": "Укажите",
        "part1": "не менее",
        "part2": "предметов.",
    },
    "SomeTextKey_1": {
        "part0": "Укажите",
        "part1": "не менее",
        "part2": "предмета.",
    },
    "SomeTextKey_2": {
        "part0": "Укажите",
        "part1": "не менее",
        "part2": "предметов.",
    }
}
```

So, ```part2``` depends on ```count```.

I use React+ES7 syntax and your ```react-i18next``` plugin, so, in my component, I use this translation like

```jsx
@translate(['common'])
export default class MyComponent extends React.Component {
    render() {
        const {
            count,
            t,
            valid,
        } = this.props;

        return (
            <div>
                {t('SomeTextKey.part0', { count })}
                <mark className={`mark ${valid ? 'mark_no-style' : ''}`}>
                    {t('SomeTextKey.part1', { count })}&nbsp;{count}
                </mark>
                {t('SomeTextKey.part2', { count })}
            </div>
        );
    }
}
```

This should look like:
Укажите не менее 0 предметов.
Укажите не менее 1 предмета.
Укажите не менее 2 предметов.
...
Укажите не менее 22 предметов.

and so on...

Docs for plurals said that I need only plural keys (0, 1, 2). But this doesn't work. If I specify the default key, it works, but without plurals, because I get

Укажите, пожалуйста, не менее 1 предметов.

I used word 'пожалуйста' to know, if plurals don't work. And there it is, sadly.

**Comment by jamuhl** [comment]
the plural suffix has to be on last part of the key:

```
{
    "SomeTextKey": {
        "part0": "Укажите, пожалуйста",
        "part1": "не менее",
        "part2": "предметов.",
        "part0_0": "Укажите",
        "part1_0": "не менее",
        "part2_0": "предметов.",
        "part0_1": "Укажите",
        "part1_1": "не менее",
        "part2_1": "предмета.",
        "part0_2": "Укажите",
        "part1_2": "не менее",
        "part2_2": "предметов.",
    }
}
```

**Comment by Lonelind** [comment]
Thanks! Did this. but it doesn't work.

I made ```json``` that looks like this:

```json
{
    "SomeTextKey": {
        "part0": "Укажите",
        "part1": "не менее",
        "part2_1": "предмета.",
        "part2_2": "предметов.",
        "part2_5": "предметов."
    }
}

```

I used numbers for Russian from this file https://github.com/i18next/i18next/blob/master/src/PluralResolver.js as you described in docs. But I receive string 

Укажите не менее SomeTextKey.part2

I explicitly converted ```count``` to ```Number```, and it didn't work.

**Comment by Lonelind** [comment]
Оh! I guess, I've got it! My app, somehow, uses English instead of Russian.

**Comment by jamuhl** [comment]
to detect language from browser use http://i18next.com/docs/ecosystem/#languagedetector

**Comment by Lonelind** [comment]
Yeah, I use it, thanks!

A little offtop, but this really is problem. I use i18next to have a way to share translations between different projects (i.g., mobile version of site and iOS App, that have many texts in common). We use ```.po``` format for this transfer and I've found your i18next-conv very useful for this. Except plurals. It translates ```.json```, that works with current version of i18next, into very strange ```.po```. More proper ```.po```:

```po
msgid ""
msgstr ""
"Project-Id-Version: node-gettext\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)\n"

msgid "SomeTextKey##part2"
msgid_plural "SomeTextKey##part2"
msgstr[0] "предметов"
msgstr[1] "предмета"
msgstr[2] "предметов"

msgid "SomeTextKey##part0"
msgstr "Укажите"

msgid "SomeTextKey##part1"
msgstr "не менее"
```

converts into

```json
{
    "SomeTextKey": {
        "part2": "предметов",
        "part2_plural_2": "предмета",
        "part2_plural_5": "предметов",
        "part0": "Укажите",
        "part1": "не менее",
    }
}
```

that breaks ```count``` ("предмета" should refer to 1, not 2) and format like ```part2_i``` for every number, not plural and non-plural keys. Would you update this converter, so it corresponds new syntax, or should I write my own parser for this?

**Comment by jamuhl** [comment]
yes...the i18next-conv is not yet migrated to v2...PR would be welcome there.

**Comment by Lonelind** [comment]
If i have more time for this. Thanks.

Btw, ```t('SomeTextKey.part2', { context: 'plural', count: 1 })``` works for now.

**Comment by jamuhl** [comment]
haha...yeah...using context functionality...will see. if i got time i will try to fix i18next-conv this week.

**Comment by Lonelind** [comment]
Thanks. I'll be waiting. Or I'll try to make it myself. If this happens, I'll send you a PR.

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-gettext-converter/issues/32

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-gettext-converter/commit/593940bcb512a9486cd6594847b47ca2cde033a5 should change it to be compatible with i18next v2 format.

`npm install -g i18next-conv` (latest 2.0.0)

**Comment by Lonelind** [comment]
Thanks! Tried it and po->json conversion works pretty perfect! But json->po still parses plural numbers as contexts and I get

```po
msgid ""
msgstr ""
"Project-Id-Version: node-gettext\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)\n"

msgctxt "1"
msgid "SomeTextKey##part2"
msgstr "предмета"

msgctxt "2"
msgid "SomeTextKey##part2"
msgstr "предметов"

msgctxt "5"
msgid "SomeTextKey##part2"
msgstr "предметов"

msgid "SomeTextKey##part0"
msgstr "Укажите"

msgid "SomeTextKey##part1"
msgstr "не менее"
```

**Comment by jamuhl** [comment]
argh...let me get back to this. right now a little hard on time.

**Comment by Lonelind** [comment]
That's all right! I really appreciate your work on this huge project that makes all happy! This isn't so urgent for now. I have to use i18next on entire project before any json2po conversion becomes necessary.

**Comment by jamuhl** [comment]
you might try version 2.0.1 - that adds tests for ru - and hopefully solves the issue for converting json --> po

**Comment by Lonelind** [comment]
Thanks! Just found out that attempted to thank you but it seems that I forgot to push the button =)
