### ISSUE TITLE
How to correctly set default language in v2.x (Node.js / Express)

### ISSUE THREAD

**Issue by dsine-de** [i18next/i18next#469]
Hi,

somehow I can't figure out what I'm doing wrong when migrating to the 2.1 version and trying to set the default language.

The ```console.log``` line in the following code prints the correctly translated value for the key (language "de"):

```
var i18next = require('i18next');
var i18nextExpress = require('i18next-express-middleware');
i18next.use(require('i18next-node-fs-backend')).init({
	lng: 'de',
	fallbackLng: 'en',
	debug: true,
	backend: {
		loadPath: 'server/json/locales/{{lng}}.json'
	}
}, function (err, t) {
	console.log(t('meta.title'));
});
```

However, when I add
```
app.use(i18nextExpress.handle(i18next));
```
below, my routes show the translation for the language "en".

**Comment by jamuhl** [comment]
request do not take the lng set in i18next.options. As lng depends on the current request (more requests could be handled async - so lng must be fixed inside request).

to have the lng inside req you can set req.lng by hand or use the detector coming with the middleware: https://github.com/i18next/i18next-express-middleware#language-detection

**Comment by dsine-de** [comment]
Thanks for the fast answer. I'll try the detection.

But somehow I miss an easy option to set a default language globally besides the global fallback language for missing keys. I'll look into it, thanks!

**Comment by dsine-de** [comment]
For the record, I'm using a configuration like this now:

```
	detection: {
		order: ['header']
	},
	whitelist: [
		'de',
		'en'
	],
	load: 'languageOnly',
```

**Comment by jamuhl** [comment]
is the fallbackLng not same as default language? the fallbackLng is always taken if no lng is set. that's why it takes en in your case.

**Comment by dsine-de** [comment]
Yeah, seens like that is the right way to think of it :)

**Comment by dsine-de** [comment]
By the way, setting debug to true prints this line on server start if I omit the "lng" option:

```
i18next: languageChanged undefined
```
Everything works fine, I assume this is not a problem and I don't need to specify the "lng" option.

**Comment by jamuhl** [comment]
not a problem...but might change it to use fallbackLng if available - as that output is not nice and will raise to much questions
