### ISSUE TITLE
Can I just init i18next with a local json object, not through resGetPath?

### ISSUE THREAD

**Issue by mirekzhou** [i18next/i18next#472]
I use webpack to build my project. And when I require('data/i18n/en-us.json'), this functionality returns a local json object. And I just can not use i18next.init() to load the json object. It always reuturns an error: /locales/en-US/translation.json?_=1450317569817 404 (Not Found). 
Can anyone helps me?

**Comment by jamuhl** [comment]
you bundle the translation json files into the application? we use webpack but don't require the translations. Just let i18next-xhr-backend load them.

If you really won't to bundle the translations. Don't use a backend on i18next. initialize it. And add the resources by using. http://i18next.com/docs/api/#add-resource-bundle

**Comment by jamuhl** [comment]
or set resources on init `i18next.init({resources: myTranslations});`
