### ISSUE TITLE
no interpolation for arrays

### ISSUE THREAD

**Issue by Raigen** [i18next/i18next#473]
When I use properties in array-translations they are not replaced by the value I put into the options.
```javascript
{
  "en": {
    "translation": {
      "arrayJoin": [
        "line1",
        "{{myVar}}", // <- this goes into the result as it is, no interpolation
        "line3"
      ]
    }
  }
}
```

**Comment by jamuhl** [comment]
do you access `i18next.t(arrayJoin.1, {myVar: 'something'}` or join that array by having option joinArrays set?

**Comment by jamuhl** [comment]
should be fixed in 2.0.4

**Comment by Azzuri-UK** [comment]
This doesn't seem to be fixed in either 2.04 or 2.05.  I am joining the arrays by setting joinArrays but I still get the interpolation key rather than the value

**Comment by jamuhl** [comment]
seems deploy was not working correctly...try 2.0.8 (see sample on i18next.com --- http://i18next.com/translate/array/#joinwithinterpolation)

**Comment by Azzuri-UK** [comment]
That's working now.  Many thanks for your super fast response!
