### ISSUE TITLE
Docs for old version?

### ISSUE THREAD

**Issue by neocotic** [i18next/i18next#474]
Would it be possible to continue to host the documentation for v1? v2 is a big jump and I doubt my project will be able to make that any time soon, so I imagine the same would be said for others.

Now we're without documentation for v1, which was always a good place to go instead of digging through the source code like I am now. This is common for big upgrades like this (e.g. Bootstrap, FontAwesome).

**Comment by jamuhl** [comment]
can be found here: http://i18next.github.io/i18next/

adding a hint on i18next.com now
