### ISSUE TITLE
Is it possible to use a context and plural at the same time?

### ISSUE THREAD

**Issue by Soviut** [i18next/i18next#476]
I'm wondering if plurals and contexts can be mixed? For example

```
{
  "friend": "friend",
  "friend_plural": "friends",
  "friend_male": "boyfriend",
  "friend_male_plural": "boyfriends",
  "friend_female": "girlfriend",
  "friend_female_plural": "girlfriends"
}
```

**Comment by jamuhl** [comment]
yes it does: http://i18next.com/translate/context/#contextwithpluralcombined

**Comment by Soviut** [comment]
Oh cool, did this get added just now? I wasn't able to find any documentation on it when I asked the question originally.

**Comment by jamuhl** [comment]
this was always there...but adding it to docs does not hurt....;)
