### ISSUE TITLE
Race condition resource loading

### ISSUE THREAD

**Issue by Chris2m** [i18next/i18next#480]
There is a race condition in how resources are loaded resulting in callbacks being executed to early.

```javascript
// First call
i18next.loadNamespaces([ "mynamespace"], function() {
   console.log("Executed when resources become availble");
   console.log(i18next("key",  {ns: ["mynamespace"]}); // returns correct key mapping
});

// Second call
i18next.loadNamespaces([ "mynamespace"], function() {
   console.error("Executed immediately - although resource is still pending and not yet available");
   console.error(i18next("key",  {ns: ["mynamespace"]}); // returns key
});
```

EDIT: Giving it a second thought, this should probably be in the main project rather than in the xhr backend. Will add it there for awareness.

**Comment by jamuhl** [comment]
will see what i can do. basically the second call see's there is a pending load for requested namespace and calls the callback. will need to somehow store the callback until the pendings get loaded.

**Comment by Chris2m** [comment]
Could also easily be solved by using Promises instead of callbacks.

**Comment by jamuhl** [comment]
no difference. still need to delay until pending calls are done. basically need to change this https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L36 to some queueing of callback.

The complicated part. It can be a mix of pending loads and regular xhr requests.

**Comment by Chris2m** [comment]
When you notice, the resource is pending what about using
i18next.store.on('added', function(ns, lang){
// check if ns and lang match the pending resource and then trigger callback
});

Would that work?
Am 29.12.2015 06:13 schrieb "Jan Mühlemann" <notifications@github.com>:

**Comment by jamuhl** [comment]
would work - but only for loadNamespace. But load is called in different situations, eg. initial load can be multiple language codes and namespaces.

Might add some storage for load calls...storing an array of all needed lng.ns combinations....removing them on successful load or error and if all got removed calling the 'done' callback with (err, t).

Will work on this next week...hope that's early enough.

**Comment by jamuhl** [comment]
can you use with v2.0.11 just published on npm and repo?

**Comment by Chris2m** [comment]
Thanks for the prompt response. Will give it a try and let you know!

**Comment by jamuhl** [comment]
better try 2.0.12

**Comment by Chris2m** [comment]
Just tried the latest master branch and it was working fine except for the fact that the same files are requested multiple times, e.g. multiple xhr requests are triggered and the latter are answered from cache.  Will try again with the latest changes.

**Comment by Chris2m** [comment]
Working now and no more duplicate xhr requests!

**Comment by jamuhl** [comment]
great...thanks for checking

**Comment by Chris2m** [comment]
@jamuhl 

Sorry to say, but after re-testing and cleaning the cache it seems callbacks are still triggered too early.

I tracked it down to the line following line which will be triggered despite the fact that there are still "pending" resources in the queue:
```if (!toLoad.toLoad.length) callback();```

Any ideas?

**Comment by jamuhl** [comment]
try 2.0.13

**Comment by Chris2m** [comment]
@jamuhl Now the callback is not triggered at all.

**Comment by jamuhl** [comment]
2.0.14 hopefully does work as expected. (should add a test case for this)

**Comment by Chris2m** [comment]
It does work - even after cleaning the cache. Taking into account the complexity of the async loading mechanism a test case would make sense indeed. Thanks a lot!
