### ISSUE TITLE
Changing the data-i18n dynamically

### ISSUE THREAD

**Issue by dhana-kony** [i18next/i18next#481]
I have my translation file as follows:-
{
  app: {
            "x": "this is x",
            "y": "this is y"
            "z": "this is z"
          }
}

Inside my html I have some code like 
<div id="changer"><span data-i18n="app.x">default</span></div>

The above link displays "this is x". I want a javascript/jquery that dynamically changes the content to this is y or this is z based on the value passed. For example I want some code like:-
function(arg){
$("#changer span").attr("text", i18n.t(app.arg));
}

If I pass y it should say "this is y". If I pass z it should say "this is z".

**Comment by jamuhl** [comment]
```
function change(arg) {
  $("#changer span").attr("text", i18n.t('app.' + arg));
}

change('x'); // will call i18n.t('app.x');
change('y'); // will call i18n.t('app.y');

```

**Comment by dhana-kony** [comment]
Is there any alternative to change the content dynamically than using i18n.t?

**Comment by jamuhl** [comment]
i think you're searching https://github.com/i18next/jquery-i18next for jquery plugin.

**Comment by jamuhl** [comment]
can this be closed?

**Comment by dhana-kony** [comment]
Sorry can't make it out. 
```<div id="changer"><span data-i18n="app.x">x</span></div>```
This is my html content. I need to have a javascript function in a seperate JS file which needs to change this from app.x to app.y. Can you please give me a code snippet. I don't mind if the code is in JS or JQuery.

Sorry to trouble you.

**Comment by jamuhl** [comment]
sorry don't understand you...up there is a snipplet already doing this. `$("#changer span").attr("text", i18n.t('app.y'));`
