### ISSUE TITLE
how to create individual i18next instances for different users with node js?

### ISSUE THREAD

**Issue by aniinprni** [i18next/i18next#482]
I am new to node.js. I am using i18next for internationalization in my node application. here is the code utils.js
```
i18n.use(Backend).init({
  debug: true,
  load: ['ar','en'],
  fallbackLng: 'en',
      backend: {
      loadPath: path.join(__dirname,'/{{lng}}/{{ns}}.json')
      },
      getAsync:false
}, (err, t) => {
      return t;
});
exports.i18n=i18n;
```
For every request I am checking user language via cookies and if not matching I am trying to force the translations to that particular language.

Below is the snippet
```
app.all('*',function(req,res,next){
    var lng = utils.getLanguage;
    lng(req,res,function(data){
        var i18n = utils.i18n;
        i18n(function(i18n){
            var nodeLanguage = i18n.options.lng||i18n.options.fallbackLng;
            if(nodeLanguage == data){
                next();
            }
            else{
                console.log("not same");
                i18n.options.lng = data;
                i18n.init(i18n.options,function(){
                    next();
                });
            }
        });
    });
});
```
This code is working fine for me as i am single user.But If hit the same URL in different browsers, it is showing in user selected language but `i18next` is initializing to latest user selected language. For example:-

**case1** : In browser-1, selected `en`,then `i18next.init` method set the language to `english`.

**case2** : In browser-2, selected `fr`, then `i18next.init` method is setting to `french`.

If I hit the same `URL` in browser-1, again it is calling `i18next.init` method. How to create individual `i18next` instances to individual users so as to avoid calling `init` method keep on ? Please help me.

I don't know whether to ask this question here or not. If not please provide me where i need to ask questions.

Thanks.

**Comment by jamuhl** [comment]
first - asking questions here is alright.

- you can use http://i18next.com/docs/api/#get-fixed-t to get a t function fixed to set language.
- you can use http://i18next.com/docs/api/#load-languages to load the language resources

for implementation details have a look at the https://github.com/i18next/i18next-express-middleware

==> https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js the middleware code for express

if using express already you might just npm install i18next-express-middleware instead of using a own implementation. If doing something different - sharing to community might be a nice idea.

**Comment by aniinprni** [comment]
Hi jamuhl, Thank you for all your valuable information. But I don't understand how this `getFixedT` will going to handle each user language. what i mean to say if **user-1** using language `english` and **user-2** using `french`. consider these two users are accessing url simultaneously. so **user-1** is try to access the same url will this `getFixedT` function will call again and again because **user-2** is accessing same url with different language? How this middleware useful for my requirement? Sorry for my bad english. I was strucked for 3 days.Please help me out.

**Comment by jamuhl** [comment]
the middleware sets the fixed language for that request. inside this request handling you can access req.t which is fixed to that users language. All the req, res is functional object of the current user request - not shared state (requests are stateless)

see: https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L49

**Comment by jamuhl** [comment]
could this be closed? or still unclear?

**Comment by aniinprni** [comment]
Hi jamuhl, Sorry i couldn't see your reply as i was on occasion. Can you check this code and let me know the below code is right way of doing or not?
1. app.js
`app.use(middleware.handle(i18next.handle));`
2. index.js
```
app.all('*',function(req,res,next){
                var i18n = utils.i18next(); 
		var lng =i18n.services.languageDetector.detect(req, res);//detecting user language
		t= i18n.getFixedT(lng);
		i18n.loadLanguages(lng, function(){
			console.log(t('key'));
			next();
		});
	});
```

3. in my ejs template i am using like this `<%=t(key)%>`

Is it right way to check each and every request and translating content to request's language?

**Comment by jamuhl** [comment]
you already use the middleware.handle

so in your routes you can already access `req.t` or `req.i18n`,...

**Comment by aniinprni** [comment]
Hi jamuhl, sorry i am not clear about this. Can you please provide me some code snippet to how to achieve this? Actually i am very very new to this node.js. Please help me out

**Comment by jamuhl** [comment]
it's all boilderplated here: https://github.com/i18next/i18next-express-middleware#wire-up-i18next-to-request-object

**Comment by aniinprni** [comment]
Thank you
