### ISSUE TITLE
error handler for bad json locals?

### ISSUE THREAD

**Issue by aminnaggar** [i18next/i18next#483]
1st off, awesome work.

Now I couldn't find anything in your docs about setting up any error handlers for bad locals.
so for example I had a json file with something like this:

    {
      "test1": {
        "title": "Welcome",
      }
      "test2": "another translation"
    }

I had `missingKeyHandler` in the init file which wasn't fired either.

and it just silently failed. Is there anything you developed for this? Maybe an event handler?

**Comment by jamuhl** [comment]
ok i see...i changed that from log as error to log as warning (which gets only logged to console when i18next was initialized with debug=true).

I will change the code in backends to callback with a severity on error so we could raise more clear warnings. for now just set the debug flag on init to get the parsing error message.

**Comment by jamuhl** [comment]
regarding a i18next.on('error', function(err) {}); would you like to have this options? could add that as well - alternatively today all runs through an logger which can be overridden...

**Comment by jamuhl** [comment]
adding severity on callback would be over the top...as the second param already defines if the backend connector should retry a load.

enabling debug=true has to be good enough for now. sorry.

**Comment by aminnaggar** [comment]
@jamuhl You're awesome. That works for me, I'll try the debug option. The i18next.on('error') would be amazing so we can gracefully fail if we have to.

Keep up the great work

**Comment by jamuhl** [comment]
see https://github.com/i18next/i18next/issues/494

not highest prio - but expect it in soon future

**Comment by jamuhl** [comment]
should be reported on http://i18next.com/docs/api/#on-failedloading
