### ISSUE TITLE
Not an issue in framework, need details using i18n.t function

### ISSUE THREAD

**Issue by poloraghu** [i18next/i18next#486]
i18n.init({
			lng : lang
		}, function(err, trans) {
			$(document).i18n();	
			$('#abc').attr("href", i18n.t('app.abc'));
		});	

i18n.t is working with in the callback function of i18n.init, how to make it work outside as well.

**Comment by jamuhl** [comment]
the point outside it works as expected...just assert resources are loaded...the key point is resources get loaded via xhr asynchronous! means you need to assert you wait until that init callback gets called.

depending on framework you use there are different ways to bootstrap the application.

**Comment by jamuhl** [comment]
alternatively create a synchronous backend for xhr...more detail for that https://github.com/i18next/i18next/issues/488
