### ISSUE TITLE
question: how to get current language?

### ISSUE THREAD

**Issue by MartijnR** [i18next/i18next#489]
I couldn't find this in the new API docs:

What is the replacement for i18n.lng() to get the current (i18n) language (if in whitelist, otherwise fallback) as we were able to get from 1.x version?

**Comment by jamuhl** [comment]
sorry....missed that in docs....added now: http://i18next.com/docs/api/#language

**Comment by MartijnR** [comment]
Thanks! Great project! :+1:

**Comment by stepbeta** [comment]
Sorry for reviving this, but it doesn't work for me. I initialize i18next this way (in browser):
```javascript
i18next.use(window.i18nextXHRBackend)
    .init({
        debug: debug,
        lng: language,
        whitelist: [language, fallbackLng],
        fallbackLng: fallbackLng,
        backend: {
            loadPath: (lang, ns) => {
                return server + apiEndpoint.lng + '?lng=' + lang;
            }
        }
    }, (err, t) => {
        if (err) {
            console.error('error while initialising i18next ::: ' + JSON.stringify(err));
        }
```

My server serves only "en-US" for now so that's my fallbackLng, and if I set language="fr-CA", this is what I see in console:
```
app.js:30 error while initialising i18next ::: ["failed loading https://my.url.com/language?lng=fr-CA"]
> i18next::languageUtils: rejecting non-whitelisted language code: fr
> i18next::languageUtils: rejecting non-whitelisted language code: fr
12 > i18next::languageUtils: rejecting non-whitelisted language code: fr
> i18next::languageUtils: rejecting non-whitelisted language code: fr
2 > i18next::languageUtils: rejecting non-whitelisted language code: fr
2 > i18next::languageUtils: rejecting non-whitelisted language code: fr
2 > i18next::languageUtils: rejecting non-whitelisted language code: fr
```

In all this I see the second request to download lng=en-US going fine and i18next is actually using those translations, then.

After all this, i18next is still set to fr-CA, which isn't the currently selected language. If I don't specify lng in the init options then i18next.language is undefined.

Am I missing something?

**Comment by jamuhl** [comment]
language is always what was set or what was detected (pure as is) - doing translation i18next will go `fr-CA` -> `fr` -> `en-US`

in i18next.languages you will find an array with translation files that will be used.

you can set different options to change behaviour:

eg. 
load = 'languageOnly' => will load `fr` -> `en`
nonExplicitWhitelist = true (will eg. allow fr-CA and fr if fr is whitelisted)

the question is - what you like to achive - only loading en-US? Then just whitelist en-US....

**Comment by stepbeta** [comment]
At startup, the user will have either "navigator.language" or "en-US", and that's what I'm whitelisting.
What I'm trying to achieve is to find out which language i18next is currently using. In my use-case I  realize I could do
```javascript
i18next.use(window.i18nextXHRBackend)
    .init({
        // ...
    }, (err, t) => {
        if (err) {
            // navigator.language failed, hence it's using "en-US"
        }
```
But what happens if, for any reason, even "en-US" fails? How can i know? And what if I support more than one fallback language, how do I know which one is currently in use?

**Comment by jamuhl** [comment]
'en-US' fails? you mean a key does not even exist in that file? 

It will fallback to key (won't help the user) - but there is a missing eventhandler...

saveMissing: true will enable sending non existing keys to backend
missingKeyHandler (function(lng, ns, key, fallbackValue) { }): you could override saveMissing to backend with own implementation

so regulary (if a key is not missing in the translation file) the used language will be i18next.languages[0] with fallback to i18next.languages[1-n]

**Comment by stepbeta** [comment]
Sorry, I misspoke. With "en-US fails" I meant the network request. What if the server has problems and I can't even get that one back? Both requests will fail, but I won't know it.

And if I have a whitelist of 3-4 languages, how do I know which ones will succeed and fail and which one will be selected at the end?

I think this is the core of my question.

**Comment by jamuhl** [comment]
Ah...ok. You really mean network outage. You can listen to event: http://i18next.com/docs/api/#on-failedloading - so you know which lng, ns failed to load

For short outage there is a load retry implemented (but won't retry forever...just a few tries).

Just some hint...you could use our service tier http://locize.com - beside getting a great translation management you get your translations served by our CDN (which will not let you down ;) )

**Comment by nicgirault** [comment]
i18next.language can be undefined before initialization. Is there a way to get a promise of the language?

**Comment by jamuhl** [comment]
@nicgirault not as i know...you could wrap init into a promise?!?

**Comment by jamuhl** [comment]
@nicgirault or try calling detect function on the language detector directly

**Comment by nicgirault** [comment]
I was not very clear. Right now I have this code:

```javascript
const getLanguage = () => i18next.language || window.localStorage.i18nextLng
```

Why `i18next.language` is not initialized with window.localStorage.i18nextLng ?

**Comment by jamuhl** [comment]
because detection happens on init call - after you passed in the detector

**Comment by nicgirault** [comment]
I would say that the localstorage value is better than nothing before detection happens. What do you think about it?

**Comment by jamuhl** [comment]
i don't think that is something i would add - localstorage is specific to browser - but this runs on node.js, react-native, electron,... so if you need that upfront i see no other option than doing the get on localstorage in your code...sorry

**Comment by nicgirault** [comment]
OK, thanks for your reactivity

**Comment by jamuhl** [comment]
you're welcome...sorry for not having a solution to this

**Comment by lmenus** [comment]
Hi, related to this, what's the proper way of retrieving all translations for the current locale? I couldn't find a definitive answer. This is what I do `i18n.store.data[i18n.language]` but it doesn't feel right, is there really no method I could call?

**Comment by jamuhl** [comment]
@lmenus what's your use case to get all namespaces of one language? can't think of one -> there are functions to get namespaces: https://www.i18next.com/api.html#getresourcebundle

**Comment by lmenus** [comment]
That will do @jamuhl, thank you! I wanted to avoid digging into the library internals in case something changes in the future, this is perfect. The use case is that I have meta data inside each translation (e.g. social media accounts for each country) and I want to reference these entries within the same JSON file. Since JSON doesn't allow to reuse variables and export the final object, I inject these variables before the translation is made.

Example.

```json
{
  "meta": {
    "twitter": "@handle"
  },
  "text": "Follow us on Twitter {{ $twitter }}
}
```

**Comment by hannojg** [comment]
@jamuhl  I can't find the resources in the new docs. I feel that the link you provided once is outdated ( http://i18next.com/docs/api/#language). Can you help? :)

**Comment by jamuhl** [comment]
@hannojg https://www.i18next.com/overview/api#language

**Comment by hannojg** [comment]
thanks!

**Comment by PMudra** [comment]
> The easiest way to get this is, by accessing `props.lng`, if using the Translate HOC.

@mfc3370 Thanks, this seems to be working as ```i18n.languages[0]```. Do you have some kind of documentation of this prop? I could **not** find it here: https://react.i18next.com/components/withnamespaces

**Comment by mfc3370** [comment]
@PMudra i can't recall the docu, but i know it's used by plugins such as https://github.com/i18next/i18next-browser-languageDetector to check the current language (detected, fallback or changed) and it's always up-to-date.

Could be that it's a hack...
Doesn't i18n.languages[0] always return the first element on the array of languages?

**Comment by lmenus** [comment]
@PMudra @mfc3370 If it's of any use, I ended up doing this in the end.

```js
const getCurrentLng = () => i18n.language || window.localStorage.i18nextLng || '';
```

**Comment by WoraponU** [comment]
I found it in document

![image](https://user-images.githubusercontent.com/13904659/72596458-a22f8400-393e-11ea-9b76-6bba18157c41.png)

**Comment by adrai** [comment]
fyi: since v21 there is `i18next.resolvedLanguage` => https://www.i18next.com/overview/api#resolvedlanguage
