### ISSUE TITLE
Document plugin API

### ISSUE THREAD

**Issue by arve0** [i18next/i18next#491]
It would be nice if a few words about the plugin architecture was documented. In example, I find it hard to grok what [`BackendConnector`](https://github.com/i18next/i18next/blob/master/src/BackendConnector.js) does.

**Comment by jamuhl** [comment]
backendConnector is irrelevant, but agree that backend, cache, logger, postProcessor need to be documented at some point...hope i get to that soon.

right now just look at the code of current backend to see needed API: eg. https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js

API:
```
{
  init: function(services, options) {},
  read: function(language, namespace, callback) {},

  // optional
  readMulti: function(languages, namespaces, callback) {},
  create: function(languages, namespace, key, fallbackValue) {} // missing key
}
```

**Comment by jamuhl** [comment]
http://i18next.com/docs/ownplugin/
