### ISSUE TITLE
getResource method is unvailable

### ISSUE THREAD

**Issue by benjoz** [i18next/i18next#492]
Version: "2.0.15"

The getResource method is unvailable
It looks like the method in missing in i18next.js:170 in the storeApi array :)

Ben

**Comment by jamuhl** [comment]
you're right...will be fixed asap...thanks for finding

**Comment by jamuhl** [comment]
you need that now? if not i will publish this with next version - else i will publish patch now?

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/commit/5cef740ab55ebf5d994226ec50850daaa0455ae9

**Comment by benjoz** [comment]
To be honnest, I would really appreciate to have it now :)
I've manually fixed the code, but I can't deploy it :( 
(node dependencies are fetched online during deployment)

**Comment by jamuhl** [comment]
2.0.16 published

**Comment by benjoz** [comment]
Thanks mate
BTW, you should update CHANGELOG.md 

Thanks again
Ben

**Comment by jamuhl** [comment]
changelog updated...thanks for reminder

**Comment by benjoz** [comment]
In my package.json, I have "i18next": "^2.0.16"

With a "npm install i18next" I still have the 2.0.15 version... :(
Your package.json version is 2.0.16 but I don't see your updates (code and changelog are not updated)

**Comment by jamuhl** [comment]
https://www.npmjs.com/package/i18next

the installed version's package.json still says 2.0.15? eventual cache issue?

**Comment by benjoz** [comment]
npm install i18next --save
i18next@2.0.16 node_modules\i18next

When I look in node_modules/i18next, your package.json is 2.0.16
But, CHANGELOG.md and lib/i18next.js are not updated ! (still 2.0.15 I guess)

Very strange

**Comment by jamuhl** [comment]
changelog change was after publishing....having a view things to add right now...will publish 2.0.17 in a view minutes.

**Comment by jamuhl** [comment]
2.0.17 published

**Comment by benjoz** [comment]
Perfect :) Thanks !
