### ISSUE TITLE
init without options throws

### ISSUE THREAD

**Issue by arve0** [i18next/i18next#495]
replicate:
```
i18n.init()
```
works:
```
i18n.init({})
```
error message:
```
TypeError: Cannot read property 'compatibilityAPI' of undefined
```
[occurences](https://github.com/i18next/i18next/search?utf8=%E2%9C%93&q=compatibilityAPI)

**Comment by jamuhl** [comment]
you need this now? else it will be fixed in next version

https://github.com/i18next/i18next/commit/5cef740ab55ebf5d994226ec50850daaa0455ae9

**Comment by arve0** [comment]
> you need this now?

no

**Comment by tjwebb** [comment]
> TypeError: Cannot read property 'compatibilityAPI' of undefined

Also seeing this in [trails.js](https://github.com/trailsjs/trails]. Looking forward to seeing a fix :)

**Comment by jamuhl** [comment]
2.0.17 should fix this
