### ISSUE TITLE
"no backend defined" in version 2.0.11 and newer

### ISSUE THREAD

**Issue by tjwebb** [i18next/i18next#497]
No matter how I configure i18next, in version 2.0.11 through 2.0.17 (tested them all!) I get "no backend defined" from somewhere. It's not an `Error`, just a string that comes from somewhere as an error message.

2.0.10 works fine

**Comment by jamuhl** [comment]
did you set a backend?

**Comment by tjwebb** [comment]
I don't know what a backend is and don't see any documentation for it. Why would this change between two patch releases?

**Comment by jamuhl** [comment]
backends are for loading data from server (or filesystem for node,...)

the relevant line is: https://github.com/i18next/i18next/blob/2.0.10/src/i18next.js#L115

and did not change between 2.0.10 and 2.0.17

do you set options.resources on init?...strange

**Comment by tjwebb** [comment]
Yea, literally if I sit here and `npm install i18next@2.0.11` my app breaks with that error. If I then run `npm install i18next@2.0.10`, it works fine. We're doing a release today, I'll try to dig into it further over the weekend.

**Comment by jamuhl** [comment]
hm...not sure why it goes into that condition and finally calls backandConnector.load (https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L118).

what i can change is callback without err and just log that - as it's not really an error - it's just wrong to try loading if resources are passed in via options?

that would at least not result in wrong callback errors. but still would be glad to findout why it calls backendConnector.load.

**Comment by jamuhl** [comment]
v2.0.19 will not callback(err) but just log a warning.

**Comment by jamuhl** [comment]
by the way what are you working on...if you won't mind i might add your project to http://i18next.com/ - Projects / Companys using i18next?

**Comment by tjwebb** [comment]
@jamuhl feel free to add us to your list! [Trails.js](https://github.com/trailsjs/trails) is a modular web services framework.

**Comment by jamuhl** [comment]
is the problem solved by just log instead of callback err? (>=v2.0.19)
