### ISSUE TITLE
t is not defined error coming

### ISSUE THREAD

**Issue by aniinprni** [i18next/i18next#498]
Hi I am using `i18next` for internationalization. In `windows` OS it is working fine. but when we moved the same to `linux` OS saying `t is not defined` error. And in my browser console showing this error **"NetworkError: 500 Internal Server Error - http://xxxxx/xxxx"**. Is there any thing related os? do i  need add any extra things  for this? 

Thanks in Advance.

**Comment by jamuhl** [comment]
not that i know...500 network error seems more an issue related to your server setup then to i18next.

**Comment by aniinprni** [comment]
Thank you for valuable and immediate response. I resolved this issue as i am copying windows libs to ubantu system.
