### ISSUE TITLE
TypeError: this.options.fallbackLng is undefined

### ISSUE THREAD

**Issue by bitbeans** [i18next/i18next#499]
If i have not set: ```lng: ``` on the options (because i use the language detector) i get the following error:

```
TypeError: this.options.fallbackLng is undefined
```

**Comment by jamuhl** [comment]
should be fixed in `i18next v2.0.10` in combination with `i18next-browser-languagedetector v0.0.14`

**Comment by bitbeans** [comment]
:+1: fixed!

thank you for the fast response!
