### ISSUE TITLE
The lowerCaseLng option is not documented 

### ISSUE THREAD

**Issue by cheton** [i18next/i18next#504]
I have the following setup using i18next v2, all the language codes are in lower case like below:
```js
i18next.init({
    lowerCaseLng: true,
    whitelist: ['en', 'de', 'es', 'fr', 'it', 'ja', 'zh-cn', 'zh-tw'],
    load: 'currentOnly',
    // other options
});
```

It works well by adding `lowerCaseLng` as init options, which will be properly handled by [LanguageUtils](https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L19). However, this option seems not documented in http://i18next.com/docs/options/#init-options. The documentation may be required to update.

**Comment by jamuhl** [comment]
good finding...thanks...will add this asap

**Comment by jamuhl** [comment]
updated: http://i18next.com/docs/options/#init-options
