### ISSUE TITLE
new options for context and plural separators

### ISSUE THREAD

**Issue by justnewbee** [i18next/i18next#506]
i'd really like a 'contextSeparator' and a 'pluralSeparator' option for `init(...)`

sometimes i will have to add '_' in a key, and i want to make the separators look different

i used to change the source code which i downloaded and put in my earlier projects, however now i use package.json to take care of 3rd parties in node project, i'd really like these separators could be implemented..

thank you guys

**Comment by jamuhl** [comment]
Will be added to next version. Not a big deal.

**Comment by jamuhl** [comment]
should work in v2.0.22

**Comment by justnewbee** [comment]
wow thanks
