### ISSUE TITLE
change another language

### ISSUE THREAD

**Issue by ansonla3** [i18next/i18next#507]
I am trying to change another language from eng to zh_HK, but it did not work.

Please advise.

To initialise,

    i18next.init({
        lng: 'en',
        resources: {
          en: {
            translation: {
              "key": "hello world"
            }
          },
          zh_HK: {
            translation: {
              "key": "你好"
            }
          }
        }
      }, (err, t) => {
        // initialized and ready to go!
        const hw = i18next.t('key'); // hw = 'hello world'
      });

Change Langage part:
    i18next.changeLanguage('zh_HK', (err, t) => {
      // resources have been loaded
    });

**Comment by jamuhl** [comment]
languages need to be defined with `-` --> `zh-HK`

**Comment by ansonla3** [comment]
Ya, but how which method can change to another language during running the program?

**Comment by jamuhl** [comment]
with changeLanguage like in your sample:

```
i18next.init({
    lng: 'en',
    resources: {
      en: {
        translation: {
          "key": "hello world"
        }
      },
      zh-HK: {
        translation: {
          "key": "你好"
        }
      }
    }
  }, (err, t) => {
    // initialized and ready to go!
    const hw = i18next.t('key'); // hw = 'hello world'

    i18next.changeLanguage('zh-HK', (err, t) => {
      // resources have been loaded
      const hw = i18next.t('key'); // hw = '你好'
    });
  });
```

**Comment by jamuhl** [comment]
evtl. try init with option.debug = true....

**Comment by ansonla3** [comment]
ya, actually, I have a function call that is change to another language when the user clicks the button. The function inside is
    i18next.changeLanguage('zh_HK', (err, t) => {
      // resources have been loaded
      const hw = i18next.t('key'); // hw = '你好'
    });

but the text still showing the original one not the another language

**Comment by jamuhl** [comment]
which text...`console.log(i18next.t('key'));` or some text on your view? view won't magically be updated.

**Comment by ansonla3** [comment]
on the view, do you have any ways to update the view ?

**Comment by jamuhl** [comment]
basically on a language change you need to rerender the complete page...depending on our stack this can be very different.

simplest solution might be:

1) add the language detector https://github.com/i18next/i18next-browser-languageDetector
2) instead of changeLanguage change window.location to your route to http://your.domain.com/?lng=zh-HK

**Comment by jamuhl** [comment]
or use https://github.com/i18next/i18nextify

**Comment by ansonla3** [comment]
ya, thanks very much.
