### ISSUE TITLE
using i18next without a namespace

### ISSUE THREAD

**Issue by yagudaev** [i18next/i18next#509]
In the previous version of i18next we were able to use it without specifying a namespace. Is there a way to use it this way now?

I quite like having `locales/en.json` and then having everything in one file.

**Comment by jamuhl** [comment]
i hope you read the getting started guide for v2: http://i18next.com/docs/#add-plugins

so i asume you know you need to add a backend plugin to load resources...

see the xhr backend doc: https://github.com/i18next/i18next-xhr-backend#backend-options

you can set `loadPath: '/locales/{{lng}}.json'` to have the route you want. Default would be `'/locales/{{lng}}/{{ns}}.json'` with namespace default 'translation'

**Comment by jamuhl** [comment]
solved? can we close this?

**Comment by yagudaev** [comment]
Yes thanks, it actually works fine. The problem was that I had a trailing comma in my JSON file. The backend did give a warning about it. But it should probably do more and throw an error.
