### ISSUE TITLE
how to use i18next in client side and server side?

### ISSUE THREAD

**Issue by aniinprni** [i18next/i18next#511]
Hi i am using `i18next` lib . This is a awesome lib for translations in node js application. From server side, this is working like a charm. But now i need to use this lib in browser side.I can't able to access the lib in my html pages. So I searched internet, in that they were told to use `browserify` lib. 
1.If i try to load the translations then what will be the impact on performance ?. 
2.Will i18next load the translations twice(one is server side, another one is client side) ?
3. Without `browserify`, Is there any way to access `i18next ` lib from client side?
Is there any better way to achieve it?

**Comment by jamuhl** [comment]
1) impact...the resources need to be loaded async from server -> impact like loading other data via REST
2) yes (client needs to load over xhr)
3) i18next is exported in UMD format...if you don't use a module loader the script will append i18next to global object -> `window.i18next`

**Comment by jamuhl** [comment]
http://i18next.com/docs/ FYI

**Comment by aniinprni** [comment]
Thank you jamuhl.But i have to access module loader(`backend` module in `i18next`) in browser. How can i access `backend` module to load resources into client without `browserify` module? 
Can you give me some code snippet which would be a great help for me.

**Comment by aniinprni** [comment]
And one more thing is 
if I do `i18next.init` in template, then Is `i18next` will call `init` method on every page load ?
if yes is there any way to avoid that many times in browser level?

**Comment by jamuhl** [comment]
Thank you jamuhl.But i have to access module loader(backend module in i18next) in browser. How can i access backend module to load resources into client without browserify module? 
Can you give me some code snippet which would be a great help for me.

same for backend -> UMD -> access `window.i18nextXHRBackend` https://github.com/i18next/i18next-xhr-backend#getting-started


you need to init 18next just once -> having singlepageapp - once on bootstrapping; -> having serverside pages once on pageload -> to avoid loading of resources use https://github.com/i18next/i18next-localStorage-cache to cache resources on client

**Comment by aniinprni** [comment]
Hi jamuhl, as per your Answer i tried initializing `i18next` and `xhr` but in my browser console it is saying `i18next` is not defined. do i need to copy the `i18next` folder into public folder ?

**Comment by jamuhl** [comment]
not using a module loader you need to load the script via script tag...like every other script

**Comment by aniinprni** [comment]
Hi Jamuhl, i am not that much tech guy. can you please tell me what do you mean by module loader ?
And script tag i have written <script src="node_modules/i18next/lib/i18next.js"> it is not finding the script.

**Comment by jamuhl** [comment]
module.loader: eg. require.js, commonjs....

old school way: loading scripts on page via script tag: http://www.w3schools.com/tags/att_script_src.asp

**Comment by jamuhl** [comment]
can we close this?
