### ISSUE TITLE
Add ability to only restore pluralisation from 1.0

### ISSUE THREAD

**Issue by ntadej** [i18next/i18next#512]
You recently added pluralSeparator setting. It would be useful to be able to restore somehow only pluralisation from 1.0 (so API functionality stays 2.0).

This can be achieved by either a flag or separate pluralSeparator (for languages with more plurals) and pluralSuffix.

**Comment by jamuhl** [comment]
http://i18next.com/docs/migration/#v1-11-x--v2-0-0-comp --> `compatibilityJSON: 'v1'`

**Comment by ntadej** [comment]
This also changes API to v1 so i18n variable is defined again.

**Comment by jamuhl** [comment]
only if you set `compatibilityAPI: 'v1'` -> https://github.com/i18next/i18next/blob/master/src/i18next.js#L104

what you mean with `i18n` variable is defined again?

**Comment by ntadej** [comment]
Sorry for confusion. I interpreted the error incorrectly.

When I enable `compatibilityJSON: 'v1'` XHR backend does not accept the `loadPath` setting anymore and translations are not loaded.

**Comment by jamuhl** [comment]
v1 compatibility for json means that interpolation get's set to prefix/sufix: `__`

this also applies to replacements in the loadPath: `/locales/__lng__/__ns__.json` using `__` instead of `{{}}` should fix that.

**Comment by jamuhl** [comment]
can we close this? or still not solved?

**Comment by ntadej** [comment]
We can close this. How long to you plan to support v1 JSON?

**Comment by jamuhl** [comment]
not yet sure...might be never...as it's a rather small difference in numbering plurals and defaults in interpolation...so no big deal.

more or less one needs just set the plurals correctly and set options to old values.

so yes...i don't expect that to get removed...

i only plan to remove compatibility to v1 API...by end of year.
