### ISSUE TITLE
Is there a way to disallow keySeparator?

### ISSUE THREAD

**Issue by Gorzas** [i18next/i18next#513]
I've found a problem with the i18next library. We have a website with more than ~500 keys to translate in multiple languages and we have some keys that are conflicting between them. For example, we have a key named *category* and a different one named **category.name**, so the last one would never be translated.

If I set the parameter **keySeparator** as a falsy value in the i18n initialization it seems that the library doesn't disallows this, so I have set the parameter as a whitespace:

```
i18next.init(
  {
    keySeparator: ' ',
  },
  callback
);
```

I know that we can split the translations in different modules, but it's not a solution for us. Is there a way the disallow **keySeparator** usage in the library? If not, can we add this option when we set this parameter as a falsy value?

Thanks.

**Comment by jamuhl** [comment]
set keySeparator to something that does not exist in your keys, eg. `####`

**Comment by jamuhl** [comment]
solved?

**Comment by Gorzas** [comment]
Yes, it solves it, but I feel like we can improve this and insert an option to disallow keySeparator. I'm going to check the code and see if I can do it myself. :)

**Comment by jamuhl** [comment]
cool...PR very welcome

**Comment by megapctr** [comment]
@Gorzas :+1:
I was pulling my hair out because I couldn't debug the issue with some messages not being translated. Turns out it's because they had a dot in them!
example
```
{
  "Text": "Translated text", // Gets translated
  "Text with a dot.": "Translated text with a dot." // Won't be translated with default keySeparator
}
```

For now, I've assigned `{}` to `keySeparator`, but that's a "thereifixedit.com" solution

**Comment by jamuhl** [comment]
might be not to obvious: http://i18next.com/translate/keyBasedFallback/

any help making this more clear would be merged.

**Comment by silkentrance** [comment]
Make sure to not use ``###`` as this will be translated to ``.`` again.

See https://github.com/i18next/i18next/blob/master/src/utils.js#L14

@jamuhl Any reason for this being in there?

**Comment by jamuhl** [comment]
@silkentrance '###' should be avoided...correct...if that ever will be a problem i will make that more complex.

the utils function will not be called with a path string - it will always be an array: https://github.com/i18next/i18next/blob/master/src/ResourceStore.js#L29

**Comment by jamuhl** [comment]
in v2.1.0 you can set both separators to false on init:

```
nsSeparator: false
keySeparator: false
```

**Comment by jamuhl** [comment]
added more hints in doc:

http://i18next.com/docs/#gettext
http://i18next.com/translate/keyBasedFallback/

hope that helps in future...suggestions for more optimization still welcome
