### ISSUE TITLE
How can I use multi line strings with the i18next2?

### ISSUE THREAD

**Issue by silkentrance** [i18next/i18next#514]
How are multi line strings used with the new i18next 2 format?
Do I still use an array of multiple strings or should I use ``\n``?
And how does this integrate with keys that are multi line strings and used as fallback?

Would be nice to have the documentation cover that topic :+1: 

That being said, would the following be a correct i18next translation file and which one of the two should I use?

```
{
   "multi\nline\nfallback\nkey" : [
      "mehrere",
      "zeilen",
      "hier"
   ]
}

{
   "multi\nline\nfallback\nkey" : "mehrere\nzeilen\nhier"
}
```

**Comment by jamuhl** [comment]
basically the multiline 'feature' in v1 was just for easier writing translations directly in the json file. Writing them up in an array has nothing to do with having newlines in the view -> even `\n` only works inside a `<pre>` tag.

so for backwards compatipility or other usecases you still can use it: http://i18next.com/docs/options/#init-options `joinArray` option.

to answer your question i would use the second option...as the first is more or less constructed for better readability translating the jsons without tool support.

**Comment by jamuhl** [comment]
feel free to reopen if still missing something
