### ISSUE TITLE
i18next 2

### ISSUE THREAD

**Issue by konradjurk** [i18next/i18next#516]
Hey,

can you give further details on why you decided to completely rewrite the library and what advantages we get with i18next 2.0 when possibly migrating from 1.10.6? :)

**Comment by jamuhl** [comment]
main reason was the code base had it's age (started on 2011) and had a lot of code added. the rewrite was needed to keep the maintainability and gave the additional chance to clean stuff up, add support for creating instances (long asked feature) and update the build process to be more modern.

i put a lot of work into the rewrite to keep it compatible with the 1.1x.x versions. http://i18next.com/docs/migration/

stuff got more modulare...so we're more flexible in reusing the codebase, eg. on node. on the other hand some stuff like jquery support got excluded and moved to extensions.

migration shouldn't be to hard...

**Comment by jamuhl** [comment]
closing this...feel free to reopen if more questions arise
