### ISSUE TITLE
Namespace with option 'returnObjects'

### ISSUE THREAD

**Issue by m-hoffmann** [i18next/i18next#522]
When using the option `returnObject`, i18next v2.0 translates the object by recursively translating its properties.

Unfortunately, the namespace of the parent object's key is not included when passing the translation keys of these properties to the translation function. This results in the default namespace being used for the translation of the properties.

Example: `example.json` 

    { "foo": { "bar": "test" }}

When translating `"example:foo"`, `{  bar :  "foo.bar" }` will be returned instead of `{ bar: "test"}` when `example` is not the default namespace.

This behavior did not occur in i18next v1 with the option `returnObjectTree`.

EDIT: The problem can be avoided by passing the namespace with the `ns` option explicitly.

**Comment by jamuhl** [comment]
just checked the code...not having time right now to fix this...but will fix this tomorrow and publish a fix...hope you can wait?

**Comment by jamuhl** [comment]
should be fixed in v.2.0.23

**Comment by m-hoffmann** [comment]
The issue is indeed fixed in v.2.0.23. Thanks for the quick response and fix.

**Comment by DavidSvetlik** [comment]
Hi, I am running version 6.0.2 and I stumbled upon similar problem:

JSON:
{
	"longDateFormat": {
		"LT": "HH:mm",
		"LTS": "HH:mm:ss",
		"L": "D. M. YYYY",
		"LL": "D MMMM YYYY",
		"LLL": "D MMMM YYYY LT",
		"LLLL": "dddd D MMMM YYYY LT"
	}
}`

Script:
`i18next.t('longDateFormat', { ns: 'mynamespace', returnObjects: true })`

Returns:
```
{
L: "longDateFormat.L"
LL: "longDateFormat.LL"
LLL: "longDateFormat.LLL"
LLLL: "longDateFormat.LLLL"
LT: "longDateFormat.LT"
LTS: "longDateFormat.LTS"
}
```

Could you please help me out?
