### ISSUE TITLE
Logger breaks in Internet Explorer 9

### ISSUE THREAD

**Issue by pettereek** [i18next/i18next#523]
Internet Explorer 9 breaks here for me https://github.com/i18next/i18next/blob/master/src/logger.js#L17 with the error "Object doesn't support property or method 'apply'". Console methods cannot be accessed using the subscript operator.

**Comment by jamuhl** [comment]
IE9 is dead (like all other IE). But i understand people need to get this up for the old stuff. As i won't add that into the codebase anylonger you got two options:

a) shim console.log, eg. http://stackoverflow.com/questions/3326650/console-is-undefined-error-for-internet-explorer

b) add own logger that checks for window.console http://i18next.com/docs/ownplugin/#logger (https://github.com/i18next/i18next/blob/master/src/logger.js#L1)

I won't add the `window.` as this needs to run on non browser envs too...

**Comment by pettereek** [comment]
Totally understand, thanks for the reply!
