### ISSUE TITLE
single/plural problem 

### ISSUE THREAD

**Issue by sowacx** [i18next/i18next#530]
Hello,
I've got a problem with using single/plural form. I use recen releases of i18next and i18next-jquery.
I init i18n with that:
`init: function() {
        i18next
            .init(this.i18nv2Options, () => {
                i18nextJquery.init(i18next, $);
            });
    }`
whereas i18nv2Options are like that: 
```
i18nv2Options: {
        detectFromHeaders: false,
        lng: window.navigator.userLanguage || window.navigator.language || 'en-US',
        resources: {
            en: {
                translation: {
                    "key": "item",
                    "key_plural": "items",
                    "keyWithCount": "{{count}} item",
                    "keyWithCount_plural": "{{count}} items",
                }
            },
            pl: {
                translation: {
                    "key": "item",
                    "key_plural": "items",
                    "keyWithCount": "{{count}} item",
                    "keyWithCount_plural": "{{count}} items",                
                }
            }
        }
    },
```

My problem is that, when I'm using english browser everything works fine:
i18next.t('keyWithCount', {count: 1}); //out 1 item
i18next.t('keyWithCount', {count: 2}); //out 2 items

But when im using polish browse it works like that:
i18next.t('keyWithCount', {count: 1}); //out 1 item
i18next.t('keyWithCount', {count: 2}); //out 2 item

I was trying to add something like this to pl resource (I saw it googling, but i guess it was in older releases)
`plurals: function(n) {
                        return Number(n != 1);
                    },` 
but without result. 
Can you help me? Sorry for newbie question, but i cannot find resolution

**Comment by jamuhl** [comment]
polnish rule: https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L22
polnish number function: https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L47

plural need to be defined (as multiple pluralforms) like: http://i18next.com/translate/pluralMulti/

**Comment by sowacx** [comment]
Ok I should defined polish keys like this:
```
  "keyWithCount_1": "{{count}} item",
  "keyWithCount_2": "{{count}} itemy",
  "keyWithCount_5": "{{count}} itemow",
```

Thanks for your help!
