### ISSUE TITLE
Context with non id keys, i.e. the ones extracted via gettext tools

### ISSUE THREAD

**Issue by silkentrance** [i18next/i18next#534]
Having a key such as

```
{
    'a key _extracted_\nby gettext tool_chain': 'translation missing'
}
```

How would I be able to use contexts with that? And is it even possible? Or is the context feature limited to id based keys only? If so, would it not make sense to put that into the documentation?

**Comment by jamuhl** [comment]
you will need to add `_context` after key:
```
{
   'a key _extracted_\nby gettext tool_chain': 'fallback if no context provided',
   'a key _extracted_\nby gettext tool_chain_male': 'male',
   'a key _extracted_\nby gettext tool_chain_female': female'
}

i18n.t('a key _extracted_\nby gettext tool_chain', {context: 'male'}); --> male
```

**Comment by silkentrance** [comment]
So when extracting keys using the gettext tools one needs to make sure that the extracted key includes the relevant context information. Thanks. How about including that into the documentation as well?

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-gettext-converter is an option to convert.
