### ISSUE TITLE
possible memory leak?

### ISSUE THREAD

**Issue by leider** [i18next/i18next#536]
Hi,
in our app (softwerkskammer.de) we found that memory increases constantly. Tracing back via dumps we found lots of objects created by i18next.

We have the following scenario:
- node with translation files for 'de' and 'en'
- language requests is 'en-GB' - this will not be found, of course
- options.debug: false (maybe here is one point?)
- we have lots of entries with 'en-GB' in the dump and Error indicating that the file is not found

Currently we have a workaround stripping '-GB' from the requested language. It seems to behave much nicer now, verification to follow.

Maybe we should try to get together in a hangout about the topic to find out if there is a real issue or if we just do it wrong. :)

Have a nice weekend,
Andreas

**Comment by jamuhl** [comment]
Not really sure what should cause a leak. On load there is an object added to a queue asserting all load request get called its callback function on done. This is independent of success or error - both get removed from queue when all files where requested. One thing we could optimize is to avoid any additional load of a failed loading...

But anyway - i don't see where this could lead to a infinite memory increase. https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L100

for now - you can init with:

load: 'languageOnly',
whitelist: ['en', 'de']

this will stop loading `en-GB` plus reduce languages to `en`, `de` -> results in less errors logged.

**Comment by jamuhl** [comment]
you might try `i18next@2.0.24` - does not load lng again if once failed to load.

**Comment by leider** [comment]
previous comment obsolete then?

**Comment by jamuhl** [comment]
it's an optional optimization...does not hurt to set as you avoid try loading `de-DE, en-US, ...` once that way.

**Comment by leider** [comment]
your proposal still throws an Error in https://github.com/i18next/i18next-node-fs-backend/blob/master/src/index.js#L17

do I miss something?

**Comment by jamuhl** [comment]
does throw? should only log a warning - and only once for each language-region file not found.

you added load, whitelist options? if so, that warnings should not come at all.

**Comment by leider** [comment]
I was unprecise. Of course the callback is called. - And the error will appear each time 'en-GB' is requested, right? - Not so elegant (control-flow via exceptions). But everything else may be even costlier...

Thanks, anyway

**Comment by jamuhl** [comment]
with latest version `en-GB` should be loaded once per instance. Giving the error in callback i18next will permanently mark `en-GB` as not available and not load that again if requested.

regular control-flow based on callbacks - just before the latest version i did not mark to not load again - as in client usage that would not hurt that much - but on serverside each request in that language would trigger a retry which is useless obviously.

**Comment by leider** [comment]
welcome :+1:

**Comment by adyz** [comment]
I've got some memory leaks too in my node js app, but it seems to come from the logger.

![screen shot 2016-06-30 at 6 06 57 pm](https://cloud.githubusercontent.com/assets/611174/16493361/d354ef56-3eed-11e6-9584-4d8383f02592.png)

**Comment by jamuhl** [comment]
@adyz i don't see how there should be a leak generated. we had memory issue's on our node.js express hosts too - they gone by upgrading to node 6.

can you provide more details?

**Comment by adyz** [comment]
On my local env I have node v4.4.4 but on production is 6 something.
I will do more research.

**Comment by adyz** [comment]
@jamuhl I've commented out some code from the logger.js file, like so and now it does not leak anymore.

Also, I want to mention, that this leak is visible make also because my translation file is  greatler than 50k and it adds up


```
    'use strict';
    
    Object.defineProperty(exports, "__esModule", {
      value: true
    });
    
    var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };
    
    function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
    
    var consoleLogger = {
      type: 'logger',
    
      log: function log(args) {
        //this._output('log', args);
      },
      warn: function warn(args) {
        //this._output('warn', args);
      },
      error: function error(args) {
        //this._output('error', args);
      },
      _output: function _output(type, args) {
        //if (console && console[type]) console[type].apply(console, Array.prototype.slice.call(args));
      }
    };
    
    var Logger = function () {
      function Logger(concreteLogger) {
        var options = arguments.length <= 1 || arguments[1] === undefined ? {} : arguments[1];
    
        _classCallCheck(this, Logger);
    
        this.subs = [];
        this.init(concreteLogger, options);
      }
    
      Logger.prototype.init = function init(concreteLogger) {
        var options = arguments.length <= 1 || arguments[1] === undefined ? {} : arguments[1];
    
        this.prefix = options.prefix || 'i18next:';
        this.logger = concreteLogger || consoleLogger;
        this.options = options;
        this.debug = options.debug === false ? false : true;
      };
    
      Logger.prototype.setDebug = function setDebug(bool) {
        //this.debug = bool;
        this.subs.forEach(function (sub) {
          //sub.setDebug(bool);
        });
      };
    
      Logger.prototype.log = function log() {
        //this.forward(arguments, 'log', '', true);
      };
    
      Logger.prototype.warn = function warn() {
        //this.forward(arguments, 'warn', '', true);
      };
    
      Logger.prototype.error = function error() {
        //this.forward(arguments, 'error', '');
      };
    
      Logger.prototype.deprecate = function deprecate() {
        //this.forward(arguments, 'warn', 'WARNING DEPRECATED: ', true);
      };
    
      Logger.prototype.forward = function forward(args, lvl, prefix, debugOnly) {
        //if (debugOnly && !this.debug) return;
        //if (typeof args[0] === 'string') args[0] = prefix + this.prefix + ' ' + args[0];
        //this.logger[lvl](args);
      };
    
      Logger.prototype.create = function create(moduleName) {
       // var sub = new Logger(this.logger, _extends({ prefix: this.prefix + ':' + moduleName + ':' }, this.options));
        //this.subs.push(sub);
    
        //return sub;
      };
    
      // createInstance(options = {}) {
      //   return new Logger(options, callback);
      // }
    
      return Logger;
    }();
    
    ;
    
    exports.default = new Logger();

```

**Comment by jamuhl** [comment]
@adyz seems to me there is no leak in the code - the logger does nothing more then use console.log|warn|error - that's what you uncommented - so it might be just the logging out that's causing the leakage or memory consumption. Not sure at all.

But in production you use debug: false in option so there won't be any logging for info or warning...

Else if there is really an issue you might try to override the logger provided with a null logger doing nothing...just providing noop functions for http://i18next.com/docs/ownplugin/#logger

**Comment by adyz** [comment]
Thanks for your answers.

Debug `false` does not seem to help.

I noticed that when I have debug true, it outputs my init options.

These contain the resources JSON

**Comment by adyz** [comment]
I think I should set the language after the init, but I am new to node/express world and I am not sure how to load the JSON from a different domain.

**Comment by adyz** [comment]
How do I overwrite the log functions.

Doing this:
```
i18next
            .init({
              lng: appShell.params.lang,
              load: appShell.params.lang,
              debug: true,
                logger: {
                    type: 'logger',

                    log: function(args) {
                        return false;
                    },
                    warn: function(args) {
                        return false;
                    },
                    error: function(args) {
                        return false;
                    }
                },
              resources: {
                'ro': {
                  translation: json
                }
              }
            }, function(err, t){
              next();
            });```

does not remove the logs, how do I overwrite the logger? Not clear from the documentation

**Comment by jamuhl** [comment]
to use your logger:

```
i18next
  .use({
                    type: 'logger',

                    log: function(args) {
                        return false;
                    },
                    warn: function(args) {
                        return false;
                    },
                    error: function(args) {
                        return false;
                    }
                })
```

not sure if you really want to pass in the resources on init...why not use the fs backend: https://github.com/i18next/i18next-node-fs-backend

do you use express? might be something for you: https://github.com/i18next/i18next-express-middleware

**Comment by varunest** [comment]
Hi, 

I too am facing this issue recently. There are way too many `subs` array of logger instances in my Heap profile. 

If I comment `this.subs.push(sub)` in the Logger.prototype.create I don't see this leak happening. 

Is there any possible solution for this problem?

P.S I have tried `debug : false` and using custom Logger but nothing helps. (I think this may be happening when BackendConnector calls the create method of logger)

**Comment by leider** [comment]
Since we updated node to 6.5 we do not experience any heap problems anymore with latest versions of i18next. Since about 3 months

**Comment by jamuhl** [comment]
@varunest you use the express-middleware?

**Comment by jamuhl** [comment]
@varunest hm...forget it...nothing todo with express-middleware...not sure how that should add a leak...it once add a new logger instance to the main logger

**Comment by varunest** [comment]
@leider I am using v6.2.1. I will update and see if this problem still exists.
@jamuhl  Yes I am using i18next-express-middleware. I am also not sure why this is happening. I believe Logger.prototype.create can be the cause since it pushes the created Logger instance into subs which later on is left dangling in the heap.

**Comment by jamuhl** [comment]
the i18next instance, backendConnector and the logger in the sub exists for the complete application lifetime - so for sure it exists...but no new instances of that should be added. So it should just be the regular footprint of i18next...or do you see it being created over and over again?

**Comment by jamuhl** [comment]
well just checked the logger...only need of keeping the subs is to be able to .setDebug to true/false and that's only used in a test as it seems....so i just might remove that part...should not hurt...but still would love to hear from you if there are multiple instances being created...

**Comment by varunest** [comment]
![screen shot 2016-12-03 at 12 12 01 am](https://cloud.githubusercontent.com/assets/3609843/20845964/7601e7c6-b8ed-11e6-9cdb-f16fd0be42a5.png)

I am adding the screenshot of the heap here. You can see there are lot of Logger instances created.

**Comment by jamuhl** [comment]
i18next@4.1.1 removes subs

every submodule creates an own logger instance...that's ok. size is very small.

**Comment by varunest** [comment]
Awesome. No longer seeing this leak 👍

**Comment by varunest** [comment]
Just pushed the code to production. This was the cause for the memory leak, which is now solved. At large number of connections it gradually consumed memory and eventually crashed the app. 

Thanks for the fix.
