### ISSUE TITLE
Treat falsy translations as missing

### ISSUE THREAD

**Issue by megapctr** [i18next/i18next#538]
Currently, if we have a translations object like this:
```json
{
  "en": {
    "translation": {
      "Some text": ""
    }
  }
}
```
and we run

```
console.log(i18n.t("Some text"));
```

...we get an empty string as a result, instead of the original string.

I think this is a bug and i18next should treat falsy translations as if they were missing.

**Comment by jamuhl** [comment]
yes and no...depends on usage...both options are valid.

so you can configure this: http://i18next.com/docs/options/#init-options

returnEmptyString, returnNull,...

**Comment by megapctr** [comment]
I see, thanks!
