### ISSUE TITLE
missingKey event not triggered

### ISSUE THREAD

**Issue by Lagaffe** [i18next/i18next#543]
The missingKey isn't triggered. This my code:

```
i18next.on('missingKey', function(lngs, namespace, key, res) {
	console.log('entered missingKeyHandler');
});
```

When enabling the debug, i18next logs in the console that the key is missing. But the missingKey event isn't triggered.

**Comment by jamuhl** [comment]
only triggers if saveMissing=true in init

**Comment by Lagaffe** [comment]
That fixes it, thx!
Maybe something to add to the documentation?

**Comment by jamuhl** [comment]
added hint: http://i18next.com/docs/options/ -> init options -> missingKeyHandler

**Comment by raine** [comment]
Old issue, but I'll say it regardless. This logic makes no sense. Why should firing of event for missing key be dependent on whether missing key is "saved"?

**Comment by jamuhl** [comment]
@raine because it's not a notification event...it's only there to handle the missing - which only should be done if saveMissing is true

**Comment by raine** [comment]
Thanks. What is `missingKeyHandler` option that takes a function then, if not to handle missing keys?

`missingKey` really does seem like a notification event that you'd expect to be fired irrespective of what `saveMissing` is configured to.

**Comment by jamuhl** [comment]
@raine wasn't aware there also was an event emitted...not sure what the benefit of that event should be beside the handler...but if you like and @adrai agree - feel free to provide a PR to emit that event also if saveMissing=false https://github.com/i18next/i18next/blob/master/src/Translator.js#L265

**Comment by adrai** [comment]
I don't remember why, but it's also documented to behave like this: https://www.i18next.com/overview/api#onmissingkey
![image](https://user-images.githubusercontent.com/1086194/147948299-5bcd1cec-e536-4c92-87d3-35ba99a0a463.png)
And it is there at least since v2: https://github.com/i18next/i18next/blob/2.0.0-alpha.24/src/Translator.js#L127
Would you just change it like that?
![image](https://user-images.githubusercontent.com/1086194/147948695-137575d6-98f0-4436-bb89-764b9d0ca405.png)

**Comment by jamuhl** [comment]
@adrai idk...not sure why and how that event is used at all - for me we could even remove it...as I don't see any benefit in it (or leave things as is).

**Comment by adrai** [comment]
@raine I don't really care...
if it should be adapted, then best as I mentioned it above and adapt the documentation, this way that event would also fire if saveMissing is not set to true, but it would not fire for all resolved plural forms...
