### ISSUE TITLE
Q: namespace names

### ISSUE THREAD

**Issue by silkentrance** [i18next/i18next#548]
Is it possible to have namespace names based on a rule as 

```
NSNAME ::= NSQNAME ('.' NSQNAME)*

NSQNAME ::= [a-zA-Z0-9$_-]+
```

and thereby allowing names such as 

```
ui.config.general
$ui$config$general
```

Or are there any limitations on the file names and thus namespace names other than those imposed by the underlying filesystem?

And would it be possible to include this information in the documentation as well?

**Comment by jamuhl** [comment]
only limitation: it should not contain the nsSeparator (Default: `:`).

feel free to add a PR https://github.com/i18next/i18next.com to improve the ducumentation.
