### ISSUE TITLE
migration from v1

### ISSUE THREAD

**Issue by prtome** [i18next/i18next#552]
hello
sorry to ask a simple question. I would like to migrate from V1, and I must admit I am completely lost
I am using it with node-express , very simple setup

var i18n = require('i18next');
/ initialize internationalisation
i18n.init({
    saveMissing: true,  // save keys not found in a file
    sendMissingTo: 'all',  // the dir where it saves the missing keys
   // preload: ['en', 'es', 'de', 'fr', 'it', 'dev'],  // not pre loading for now
    lng: '',  // none at startup, first connection is browser lang
    fallbackLng : 'it-IT',   // lang to display if the one in browser not found - 
    ignoreRoutes: ['img/', 'public/', 'css/', 'js/'],
    useCookie: true,
    debug: true
});
app.use(i18n.handle);
i18n.registerAppHelper(app);

and then in my routes I use  req.i18n.t('key.value')

I see everything has changed, I tried moving bluntly to next version but got an error message:
"no backend defined" 

I read the docs, but I hate to admit I am not understanding what I should be doing.
Another question is, must I change my JSON files or not?
if all this is in the docs, could you point me to the correct parts ? Thanks - I am really lost

**Comment by jamuhl** [comment]
read getting started on i18next.com -> plugins

json files need no migration. read migration guide.

**Comment by prtome** [comment]
thanks, I read, I don't get it at all. 
 I will stay for now in v1 which I control better
