### ISSUE TITLE
`fetchOne` equivalent?

### ISSUE THREAD

**Issue by mathieumg** [i18next/i18next#562]
I'm in the process of migrating from v1.11 to v2.1 and I have a hard time figuring out the right backend for the task. This is my v1 code:

```js
i18n.backend({
  fetchOne: (language, namespace, callback) => {
      // Custom async logic that calls "callback" with the fetched keys.
  },
});
i18n.init(i18nextOptions);
app.use(i18n.handle);
```

Now I reckon the v2 equivalent should look something like:

```js
i18next
  .use(i18nextMiddleware.LanguageDetector)
  .use(/* the right backend */) 
  .init(i18nextOptions);
app.use(i18nextMiddleware.handle(i18next));
```

When looking at the available backends (http://i18next.com/docs/ecosystem/#backends) they all seem too specialized for the task. Does it mean I now have to develop my own `Backend` and pass callback options to the `read` method if I want a "callback-based" backend? Otherwise, sorry if I missed something obvious.

Thanks for the great library!

**Edit:** I realize I have a very similar question for the frontend part, that is, what is the v2 equivalent for `customLoad` in v1?

**Comment by mathieumg** [comment]
I ended up implementing this, works for both the server-side and the client-side:

```js
// Backend to allow "custom loading" in i18next.
export default class CustomLoadBackend {
  static type = "backend";

  constructor(...args) {
    this.init(...args);
  }

  customLoad(language, namespace, callback) {
    callback(new Error(
      `You must provide a "customLoad" option with the "CustomLoadBackend".`,
    ));
  }

  init(services, options = {}, i18nextOptions = {}) {
    this.options = {
      customLoad: this.customLoad,
      ...i18nextOptions,
      ...options,
    };
  }

  read(...args) {
    this.options.customLoad(...args);
  }
}
```

Is this a backend you would be interested in officially supporting?

Thanks!

**Comment by jamuhl** [comment]
The point is customLoad was more or less replaced by the backend implementation...which was reduced to a customLoad function ;) (and a write for missings if one needs that)...

so, personally i won't support all the variations of backend, even less all the db backends v1 offered...that's just to much work to be done beside job and family.

if you plan to publish your backend you can add it here: https://github.com/i18next/i18next.com/blob/master/pages/docs/ecosystem/index.md so others can easily find it.

**Comment by mathieumg** [comment]
I wasn't asking if you would support all variations of backends, I was wondering if you were open to support a more generic one (like above) where only a callback is needed as an option. This gives liberty to the user to fallback on that implementation if the required backend isn't available. In my case, I have a scenario where the loading function is very specific to the use case and even varies whether I'm in development or in production.

I don't mind publishing that `CustomCallbackBackend` however, I was just curious whether you would rather have it under the i18next org. I imagine I can add entry points for custom "multiLoad" and custom "write" while I'm at it, just to validate, it's not possible to combine backends, is it? Because if it is, I won't provide defaults that error (like above) in case another backend is handling the other operations (multi, write).

Thanks again!

**Comment by jamuhl** [comment]
the point i don't get...this will be a `CustomCallbackBackend` which instead of just implement a `CustomBackend` allows you to pass in your `CustomBackendFunctions` inside the options.

So it's injecting functions to read data instead of implementing a backends interface, which in simplest case is only an object like:

```
var myBackend = {
  type: 'backend,
  init: function() { // might not even be needed, as does not need options from i18next --> possible noop},
  read: function(lng, ns, callback) { // this is basically what you pass in via options to CustomCallbackBackend}
}
```

but back to your questions:

- it's not possible to combine backends (readMulti is only an option for eg. xhr to load all needed data in one request instead lng.ns combinations one by one)
- right now i really don't see the benefit of it...might miss the point some how
- adding to i18next.com and add `i18next.backend` to npm keywords should be sufficient - no need to push under i18next org...but if you prefer i can create you a repo there or you can move it later to i18next org

**Comment by mathieumg** [comment]
The main idea is that all configuration remains in the configuration object, which is located and managed in two completely different parts of the code. For instance, the part of the code that does bootstrapping of libraries, middleware, etc. looks like the following if I water it down a bit:

```js
i18next
.use(CustomCallbackBackend)
.use(/* other middleware */)
.init(require("./externalConfig"));
```

The `externalConfig` file exports the `i18next` configuration object and has different settings depending on the environment (development, production) and on other settings. The custom callback is different (I can elaborate on the specific scenarios if you're curious) depending on the environment, so to me it makes more sense to keep the "config forking" in one location rather than duplicate the same code-fork logic in the library bootstrapping code above. 

I imagine I could hack something together that looks like:

```js
import externalConfig from "./externalConfig";

i18next
.use(externalConfig.backend)
.use(/* other middleware */)
.init(externalConfig.settings);
```

But that seems more cumbersome and not as clear, in my opinion anyway. I'll go ahead and publish a standalone version of the  ̀CustomCallbackBackend`, in case folks want to use it! In my initial implementation, I didn't provide an `init` method and things crashed, so I imagine it do is necessary. :)

Thanks!

**Comment by jamuhl** [comment]
agree...let me know when you published this...so i can add it to i18next.com

`init` is not optional right now...will add a check for init exist on backend and only call it in that case...so one more function not needed.

**Comment by mathieumg** [comment]
Thank you! I'll try to look into it this weekend.

**Comment by jamuhl** [comment]
v2.2.0 published - now init is optional on backend
