### ISSUE TITLE
getFixedT and overloadTranslationOptionHandler

### ISSUE THREAD

**Issue by perrin4869** [i18next/i18next#565]
I'm using the `sprintf` `overloadTranslationOptionHandler` in my current project, I tried outputting a translator function using `getFixedT`, but unlike with `i18next.t`, running the fixed function in the following manner gives off the following error in the console:

```javascript
fixedT("Your current waiting position is %d", 1)
```

results in: `Uncaught TypeError: Cannot assign to read only property 'lng' of 1`

This errors points to the following line: `return t = t || {}, t.lng = t.lng || o.lng, t.ns = t.ns || o.ns, n.t(e, t);` inside the definition of `getFixedT`.

I can setup a demo repo reproducing the problem if it'll help you!

**Comment by jamuhl** [comment]
fixedT: fixes t by passing {lng: fixedLng } as options to t: https://github.com/i18next/i18next/blob/master/src/i18next.js#L196

So you can't use it like t with overloadTranslationOptionHandler as that would loose the fixed language in options.

In this cases you need to use sprintf like: https://github.com/i18next/i18next-sprintf-postProcessor#usage-sample

can not think of a proper way to support both in getFixedT.

**Comment by perrin4869** [comment]
I haven't tested it yet at all, and I am not very familiar with the codebase, but at first glance, it looks to me as though you could just do something like:

```javascript
  getFixedT(lng, ns) {
    let fixedT = (key, options) => {
      options = options || {};
      options.lng = options.lng || fixedT.lng;
      options.ns = options.ns || fixedT.ns;
      options.postProcess = options.postProcess || Object.keys(postProcessor.processors);
      return this.t(key, options);
    };
    fixedT.lng = lng;
    fixedT.ns = ns;
    return fixedT;
  }
```

I can send a pull request after testing if you think it could work.

**Comment by jamuhl** [comment]
hm...could be more in line with: https://github.com/i18next/i18next/blob/master/src/Translator.js#L48

**Comment by perrin4869** [comment]
I see the problem now!
Hm... how about changing the way `overloadTranslationOptionHandler` works? You change:

```javascript
    if (typeof options !== 'object') {
      options = this.options.overloadTranslationOptionHandler(arguments);
    } else if (this.options.compatibilityAPI === 'v1') {
      options = compat.convertTOptions(options);
    }
```

to

```javascript
    if (this.options.overloadTranslationOptionHandler) {
      options = this.options.overloadTranslationOptionHandler(arguments);
    } else if (this.options.compatibilityAPI === 'v1') {
      options = compat.convertTOptions(options);
    }
```

Then, it is the responsibity of `overloadTranslationOptionHandler` to handle the second argument as an object. For example, in the case of `sprintf` (modified from https://github.com/i18next/i18next-sprintf-postProcessor/blob/master/src/index.js#L19):

```javascript
  overloadTranslationOptionHandler(key, options, ...args) {
    if(typeof options !== "object") {
      args = [options, ...args];
      options = {};
    }

    return {
      ...options,
      postProcess: 'sprintf',
      sprintf: args
    };
  }
```

Hm... This might be a breaking change though...

**Comment by perrin4869** [comment]
Hm... I decided to ditch `sprintf-postprocessor` in favor of `sprintf-js`. You can close this issue if you want.
