### ISSUE TITLE
where is the dir() function exposed?

### ISSUE THREAD

**Issue by MartijnR** [i18next/i18next#567]
I think I'm missing something very obvious, but I can't seem to figure out how to access the dir() function. An example would be very helpful.

**Comment by jamuhl** [comment]
i18next.dir() --- or is it about access in express middleware on request object?

**Comment by MartijnR** [comment]
Oops. I could have sworn it wasn't there yesterday. Sorry!

I have an issue using it without an argument (Cannot read property 'indexOf' of undefined). It doesn't seem to get a value for the current language and I don't seem to be able to retrieve the current language and pass it as a parameter. However, I'll look further and open another issue when necessary. 

Thanks!
