### ISSUE TITLE
size

### ISSUE THREAD

**Issue by mbrevda** [i18next/i18next#571]
V2.0 definitely seems a lot nice from a code point of view. Being modular, I was wondering if there was anything that could be made optional? When using with browserify, i18next adds about 80k (minified) to the bundle size. This is a huge cost for a SPA. Is everything that's included really necessary for a minimum viable build?

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/i18next.min.js minimized 43kb

agree on it could be smaller. i invested a lot of time to get the size down  from v1 to v2 while keeping in compatible as much as possible (hopefully not adding to much to the current js fatigue).

it comes with it's size...true...but has other benefits. when not needing a complete i18n solution one might be better of with some smaller solution -> there are a lot out there. but if you like to know the framework gonna stay and is flexible enough to run with the next big thing the 43kb might be not such a big price.

- removing the compatibiity parts later this year will reduce the size a little. but won't be getting down to 10kb.
- if you don't need caching nor backend connection (loading via xhr,...) you can remove backend and cache connector.
- not needing plurals that could be removed

anyway...i'm not the greatest programmer out there...any pull request helping to get the size down would be merged thankfully.

**Comment by SalahAdDin** [comment]
It never got smaller, isn't it?

**Comment by jamuhl** [comment]
@SalahAdDin sure it did, compare:

https://bundlephobia.com/package/i18next@2.0.0
https://bundlephobia.com/package/i18next@12.0.0

but like said in this thread before...if you are a pro and can magically reduce the size...feel free to contribute...just spamming old issues about size does not make it better
