### ISSUE TITLE
webpack build broke in 2.2.0

### ISSUE THREAD

**Issue by globexdesigns** [i18next/i18next#575]
After upgrading from 2.1.0 to 2.2.0, i18next no longer works for webpack builds. I get the following error:

```
Uncaught ReferenceError: require is not defined
```

Which is coming from this file:

```
'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _i18next = require('./i18next');

var _i18next2 = _interopRequireDefault(_i18next);

exports['default'] = _i18next2['default'];
module.exports = exports['default'];

/*****************
 ** WEBPACK FOOTER
 ** ./~/i18next/lib/index.js
 ** module id = 346
 ** module chunks = 0
 **/
```

Anything special I need to do to support the new version?

**Comment by jamuhl** [comment]
not aware of this...we changed the entry point in package.json to `/lib`. Not sure what causes this.

Will have a look tomorrow...

Sorry for the troubles.

**Comment by jamuhl** [comment]
not having an issue in our production env...are you on webpack 2 already - as i don't see this with webpack 1?

**Comment by globexdesigns** [comment]
I had this in my webpack config:
```
noParse: [
	/[\/\\]node_modules[\/\\]i18next/
]
```

To make things work in some previous versions of i18next. I've removed it and we're all good now.

Sorry for wasting your time.

**Comment by jamuhl** [comment]
all green....glad it's no issue.
