### ISSUE TITLE
404 Error for unneeded locales

### ISSUE THREAD

**Issue by kazzkiq** [i18next/i18next#578]
I have a `"pt-BR"` locale. When I call it, it works as expected, downloading the `/pt-BR/locale.json` file as expected. But when I open the console there are two 404 requests calling for `"dev"` and `"pt"`.

<img width="506" alt="captura de tela 2016-02-23 as 07 11 19" src="https://cloud.githubusercontent.com/assets/1953194/13248347/7f7d0c0c-d9fc-11e5-8762-730f24c5dbc0.png">

Is it a normal behavior? By calling only `"pt-BR"` should't it just request that specific file?

**Comment by jamuhl** [comment]
default behaviour of i18next is to resolve translations in order:

1) de-DE (lng plus regional diffs)
2) de (lng)
3) en (defined fallbackLng)

so getting that not found is 'normal'.

you can change that behaviour with options:
- fallbackLng = false
- load = 'currentOnly'

**Comment by kazzkiq** [comment]
@jamuhl worked as expected. Thanks :+1:
