### ISSUE TITLE
SEO friendly routes in Express

### ISSUE THREAD

**Issue by stefanotto** [i18next/i18next#579]
Is this not supported anymore?

**Comment by jamuhl** [comment]
express related stuff moved to i18next-express-middleware. https://github.com/i18next/i18next-express-middleware

seo routes was not added there yet. feel free to add a pr.

**Comment by jamuhl** [comment]
just needs copying this over to middleware: https://github.com/i18next/i18next-node/blob/master/lib/i18next.js#L288
