### ISSUE TITLE
Most basic example of using i18next

### ISSUE THREAD

**Issue by Superdominik** [i18next/i18next#591]
I've tried to get i18next to work for 20 hours, but I just can't get it to output anything.

I've tried to reduce myself to the most basic and simple example, but I still don't get it. The getting started code from the docs seems to be ES6 and I've read that it doesn't run if I don't use a transpiler. All the third party examples are for v1.x of i18next and every example does the init differently. I've tried many different ways to init and no backend/plugins, with and without xhr and the json files.

It would be really great if you could provide a very simple, but complete, example "Hello world!" project for i18next.

This is what I have right now with just an `index.html` and the `i18next.min.js`:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test Site</title>
</head>
<body>
<div data-i18n="key"></div>
<script src="i18next.min.js">
    import i18next from 'i18next';

    i18next.init({
        lng: 'en',
        resources: {
            en: {
                translation: {
                    "key": "hello world"
                }
            }
        }
    }, (err, t) => {
        // initialized and ready to go!
        const hw = i18next.t('key'); // hw = 'hello world'
    });
</script>
</body>
</html>
```
I would expect this to simply output `hello world` in the `div`. I've also tried it with another init I've seen at answers on stackoverflow that were for v1.x and not ES6, like this one:
```javascript
    $(document).ready(function () {
        i18n.init({
            "lng": 'en',
            resources: {
                en: {
                    translation: {
                        "key": "hello world"
                    }
                }
            },
            "fallbackLng" : 'en'
        }, function (t) {
            $(document).i18n();
        });
     });
```

Could you please elaborate on this? I think it would also help a lot of other beginners that are stuck at the first steps.

Thank you very much in advance.

**Comment by jamuhl** [comment]
Your example is correct and working...you just miss one point. 

Reading the docs migration guide v1 -> v2 would have clearified that: http://i18next.com/docs/migration/#v1-11-x--v2-0-0-depr

jquery or any other UI library support is removed from the core. There is https://github.com/i18next/jquery-i18next to get the jquery functionality.

**Comment by Superdominik** [comment]
Thanks for your reply.

I've read every bit of the documentation so much, I think I can recite it by heart now. :)

I can make the jQuery init from the op work with v1.x, but not with v2.x, even when I use jquery-i18next. I'd actually like to get it to run without jQuery though.
I think the first example doesn't work because of the ES6? So I've tried this translated code:
```html
<!DOCTYPE html>
<html>
<head>
    <script src="i18next.min.js"></script>
    <meta charset="utf-8">
    <title>Test</title>
</head>
<body>

<div data-i18n="key"></div>

<script>
    i18next.init({
        lng: 'en',
        resources: {
            en: {
                translation: {
                    "key": "hello world"
                }
            }
        }
    }, function (err, t) {
        // initialized and ready to go!
        var hw = i18next.t('key'); // hw = 'hello world'
    });
</script>
</body>
</html>
```
When I run this in my browser, I get an empty page. I'm a bit embarassed to be stuck at this basic problem, but I think I'm going nuts.

**Comment by jamuhl** [comment]
i18next.t('key'); will only return translation. there is no magic assign it to the div.

that's what the jquery plugin would do: there is even a sample: https://github.com/i18next/jquery-i18next/blob/master/example/sample.html

if you want magic use: https://github.com/i18next/i18nextify

**Comment by Superdominik** [comment]
Thank you, I have it running now. I can successfully run this with v2.x and jQuery now.
```html
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/i18next/2.0.22/i18next.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-i18next/0.0.14/i18next-jquery.min.js" ></script>
</head>
<body>

<div data-i18n="key"></div>

<script>
    i18next.init({
        lng: 'en',
        resources: {
            en: {
                translation: {
                    key: "Hello World!"
                }
            }
        }
    }, function(err, t) {
        i18nextJquery.init(i18next, $);
        $(document).localize();
    });
</script>
</body>
</html>
```
This is exactly what I was looking for. It's exactly the code that let's me have a working "something" to get started from.

I think it would be great to have exactly this "Hello World!"-page on the "Getting Started"-page in the docs. Especially for people like me with only very basic knowledge about JS.

Thanks for the great and fast support and this great open source framework that will enable me to offer my static AWS S3 hosted website in multiple languages.

I'm so happy right now. This saved my weekend. The suffering hasn't been in vain. :D

**Comment by jamuhl** [comment]
might add some links to getting started combined with tech (jquery, react, angular, backbone) some day.
