### ISSUE TITLE
Redis Backend

### ISSUE THREAD

**Issue by aniinprni** [i18next/i18next#593]
Hi  jamuhl, I am using `i18next`. Till now we are reading translations from `fs` backend module. Is there any plugin that read translations from redis ? If not Kindly tell me is there any way to achieve the reading translations from Redis ? 

Thank you.

**Comment by jamuhl** [comment]
there are backends for mongodb, couchbase right now: http://i18next.com/docs/ecosystem/#backends

you just need to implement: http://i18next.com/docs/ownplugin/#backend for redis

you might lookup how to in the mongodb backend: https://github.com/gian788/i18next-node-mongodb-backend

would be great if you like to provide a backend for redis to share the repo link / npm module name

**Comment by aniinprni** [comment]
Hi jamuhl, Thank you for reply. i will give a try for that. Now i am currently facing an issue with `i18next` module. The Scenario is like this : In my linux system, i had an node application which is using `i18next` working perfectly till now. Now i typed `npm install` / `npm i` (as i removed `node_modules` folder). Then it is showing exception   `TypeError: i18next.use is not a function`. So i went into my application `node_modules` folder and the working application `node_modules` folder and compared package.json. i found some differences. Please kindly check for the attachment for the differences. What needs to be done ? 
Please kindly help me. 

Thanks

**Comment by aniinprni** [comment]
Hi jamuhl, any update on this ?

**Comment by jamuhl** [comment]
should be fixed in latest >= v2.2.1...was an issue introduced by migration from babel 5 to babel 6 which does handle export default different.

**Comment by jamuhl** [comment]
closing...if not solved please reopen this issue
