### ISSUE TITLE
Crash when saveMissing try to assign to a read only property

### ISSUE THREAD

**Issue by anthonybriand** [i18next/i18next#605]
Hi,

I use the i18next-node-fs-backend, when I try to add property to a existing key, value combination via the saveMissing option, that cause a crash of Node an it's impossible to catch.

The sample JSON :
`{
  "Register": "Register"
}`

The requested key :
`i18next.t("Register.a");`

Automatically the saveMissing behavior attempt to add "a" in "Register" and this cause a crash.

The trace :
`/Users/XXXX/node_modules/i18next-node-fs-backend/lib/utils.js:56
  obj[k] = newValue;`

`TypeError: Cannot assign to read only property 'a' of Register`
`at Object.setPath (/Users/XXXX/node_modules/i18next-node-fs-backend/lib/utils.js:56:10)`
`at /Users/XXXX/node_modules/i18next-node-fs-backend/lib/index.js:130:19`
`at Array.forEach (native)`
`at /Users/XXXX/node_modules/i18next-node-fs-backend/lib/index.js:129:20`
`at /Users/XXXX/node_modules/i18next-node-fs-backend/lib/index.js:53:7`
`at tryToString (fs.js:414:3)`
`at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)`

**Comment by jamuhl** [comment]
will fix this...when i get to it. not highest prio in my opinion.

as you can't have `t(Register')` and `t(Register.a)` side by side

sample json should be:

`{ "Register": { title: 'Register' } }`

**Comment by anthonybriand** [comment]
Yes absolutely, I have just reported this error, to have a good error handling and prevent a nodejs crash

**Comment by jamuhl** [comment]
closing this in favour of the issue in node-fs-backend (which sadly is still open)
