### ISSUE TITLE
serveClientScript in v2?

### ISSUE THREAD

**Issue by nicoxxie** [i18next/i18next#614]
Hi, 
Before v2 I would use serveClientScript to serve the client side script for /i18next/i18next.js.
i18n.init(i18n_options);
app.use(i18n.handle);
i18n.serveClientScript(app); 

Seems like serveClientScript is gone now, wonder how I can achieve this in v2?
Here is my setup:

i18next
  .use(i18middleware.LanguageDetector)
  .use(i18backend)
  .use(i18sprintf)
  .init(i18n_options);
app.use(i18middleware.handle(i18next));

**Comment by jamuhl** [comment]
like...https://github.com/i18next/i18next-node/blob/master/lib/i18next.js#L151

**Comment by nicoxxie** [comment]
@jamuhl That's what I've used before V2, is there something similar in V2/ https://github.com/i18next/i18next ?

**Comment by jamuhl** [comment]
no. but thats the code to add it.

**Comment by jamuhl** [comment]
but why not just take the scripts fom cdn if not using rollup, webpack or browserify or requirejs to bundle a client?

**Comment by nicoxxie** [comment]
ok I took the scripts and made some customization, thank you.
