### ISSUE TITLE
How to use i18next in client side ?

### ISSUE THREAD

**Issue by TitaneBoy** [i18next/i18next#618]
Hello Team

I found your i18next module recently and I'm trying to use it for personal purpose. First of all, thank your for your great job you have done with your module.

I've successfully tried to use it in the server-side and It works perfectly.
Now, I'm trying to use it in the client-side and I unfortunetly don't understand how it must works. I read all the documentation in the i18next.com web site and I didn't find (or understand) a way to use 18next module in the client side. I cannot find enough documentation to use your module in HTML files and I was wondering if you could help me.

Here is what I'm trying to do:

I have the following HTML web site:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
<script type="text/javascript" src="lib/i18next.js"></script>
<script>
window.onload = function() {
    i18next.init({
        load:['en-US', 'fr', 'es'],
        fallbackLng: 'en-US',
        ns:'Web_Server',
        defaultNS:'Web_Server',
        backend: {
           loadPath: '/language/static/{{lng}}/{{ns}}.json'
       },
       getAsync:false
    },function(t) {
        var translate = i18next.t("Hello");
        console.log("translate variable = " + translate);
    });
};
</script>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf8" />
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>My First Translated Page</title>
        <link rel="stylesheet" href="lib/bootstrap-3.1.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="lib/bootstrap-3.1.1/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="css/style.css"/>
    </head>

    <body background="./img/MS_homepageNEW_bg3.jpg">

	<font color="yellow">
    <h1 align="center"> Welcome to My Web Server !!! <br><br> </h1>
	</font>

    <p style="text-align:center"><img src = "img/Family.jpg"> </img></p>
	<font color="yellow">
    <h2 align="center"> <br> <br> Choose your favorite application: </h2>
	</font>

    <p style="text-align:center">
      <button type="button" class="btn btn-success"> <a href="/user/login"> Application <br> by Me</a></button>
      <button type="button" class="btn btn-warning divider"> <a href="/user/#/RECEPTION"> WebMail <br> by User 2 </button>
    </p>
    </body>
</html>

```
The following section:
```
<script type="text/javascript" src="lib/i18next.js"></script>
<script>
window.onload = function() {
    i18next.init({
        load:['en-US', 'fr', 'es'],
        fallbackLng: 'en-US',
        ns:'Web_Server',
        defaultNS:'Web_Server',
        backend: {
           loadPath: '/language/static/{{lng}}/{{ns}}.json'
       },
       getAsync:false
    },function(t) {
        var translate = i18next.t("Hello");
        console.log("translate variable = " + translate);
    });
};
</script>
```
 is what I tried to do (by searching examples on google) but when I execute that, the "Hello" string I'm trying to translate has the same value when executing the web page (So the string is not translated and I get in return the original string).

Can you please tell me what i'm doing wrong or what I have to do to get it work ? Must I install some module in the server side ? Is it possible to store the translations in the client side and if yes, how to do it and how to access to these translations ?

What configuration (server-side or client-side) i must have to be able, in my html example, to translate the strings (like for example the string in the title of the html page "My First Translated Page", and so on)? I have already the translated strings in json format. As I said, I can easily translate strings in the server-side.

Thank you very much for your help.

**Comment by jamuhl** [comment]
on clientside you will need to use i18next-xhr-backend to load resources from server (or add them on init or addResourceBundle). http://i18next.com/docs/#add-plugins

script should be in head or body section!

for using with backbone you might use some template engine (when all running) eg. http://i18next.github.io/i18next/pages/doc_templates.html (old doc of v1 - just use the template samples not more)

**Comment by TitaneBoy** [comment]
Hi jamuhl. Well...Thanks for the tips about that script should be in head or body section.

I added, with my comprehension , the  i18next-xhr-backend module in my html
This is what I tried:

```
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
    <head>
      <script type="text/javascript" src="lib/i18next.js"></script>
      <script type="text/javascript" src="lib/i18nextXHRBackend.js"></script>
      <script type="text/javascript">
        i18nextOptions = {
                          load:['en-US', 'fr', 'es'],
                          fallbackLng: 'en-US',
                          ns:'My_Web_Server',
                          defaultNS:'My_Web_Server',
                          backend: {loadPath: '/language/static/{{lng}}/{{ns}}.json'},
                          getAsync:false
                        };
        i18next
          .use(i18nextXHRBackend)
          .init(i18nextOptions);

        console.log("Translated value = " + i18next.t("Hello"));
      </script>

      <meta http-equiv="Content-Type" content="text/html; charset=utf8" />
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <title>My First translated page</title>
      <link rel="stylesheet" href="lib/bootstrap-3.1.1/css/bootstrap.min.css">
      <link rel="stylesheet" href="lib/bootstrap-3.1.1/css/bootstrap-theme.min.css">
      <link rel="stylesheet" href="css/style.css"/>

    </head>
```

But when I ouput translated string in the console log:
(in the previous html)
`  console.log("Translated value = " + i18next.t("Hello"));`
the string "Hello" is not translated (I checked in the json resource files and it is there.)

Can you tell me please what is wrong with my code ?

And I can get the string in the title translated ?:
`<title>My First translated page</title>`

Thank you again for your precious Help.

**Comment by TitaneBoy** [comment]
Another question : Do I need to add data-i18n = "MyString" attribute inside element (like div, title, p, span, etc.) to get strings inside this element translated ?

I'm asking that because I still don't understand how to get strings  translated inside html elements (see my previous post)

Thank you for your answer.

**Comment by jamuhl** [comment]
don't mix v1 and v2 options
```
        var i18nextOptions = {
                                // load:['en-US', 'fr', 'es'],
                                preload:['en-US', 'fr', 'es'], // but preloading on client does not make much sense only load neeeded user language
                                fallbackLng: 'en-US',
                                ns:'My_Web_Server',
                                defaultNS:'My_Web_Server',
                                backend: {loadPath: '/language/static/{{lng}}/{{ns}}.json'},
                                // getAsync:false --> no non-async loading in v2
                              };
```

`backend: {loadPath: '/language/static/{{lng}}/{{ns}}.json'},`

rather sure this loading path does not reach your server -> add `debug=true` on init and check your console.log

for getting your html content translated:
a) use i18nextify https://github.com/i18next/i18nextify
b) use jquery-i18next https://github.com/i18next/jquery-i18next
c) use html5 selectors and change the content

**Comment by TitaneBoy** [comment]
Hi jamuhl.

Thank you again for your input and tips... I just forgot about the option "debug" and now it's help very much to see the big picture.

What I saw in the console log, is that i18next loaded correctly the json resource files. The path was reached correctly.  But what happened when I was trying to translate the "Hello" string, was the asynchrone side I forgot to consider. I was trying to translate the string before everything was loaded.

By adding a callback function in the init, I could see my string translated. Yyééé.. :-D

Now I'm trying to use your last tips... One question: Must I use all your 3 tips in the same time to get string translated in HTML tags ? (i.e a) and b) and c) ) or I can just choose one of these 3 tips ?

About the c) tip, I'm not sure to understand it. Can you give me please some little example ?

Thank you very much again for your help and your answer. I will try to add a) and b) in my project and I will keep you in touch soon .

**Comment by jamuhl** [comment]
it one of a, b or c

c) is basically like jquery-i18next without using jquery but html5 selectors: was in v1.11.x of i18next but i never redone that for v2...code of v1 would be here: https://github.com/i18next/i18next/blob/1.11.x/src/i18next.nojquery.js

**Comment by digeomel** [comment]
I'm sorry @jamuhl , just to clarify, you're saying that if we want to use i18next with the jQuery plugin we need to use v1.11.x?
Because I've also been struggling to get i18next v2 to work with the latest jQuery plugin for a few hours now and I'm banging my head on the wall!
Plus, v1 vs v2 configuration parameters are also very confusing, I am not sure whether I should specify the AJAX loading path as backend.loadPath or resGetPath...

**Comment by jamuhl** [comment]
nope...the plugin is v2 only...just use all in v2 (forget v1)

c) is only sample in v1, plain html5 version of the jquery functionality, which we don't migrate to v2 plugin structure

**Comment by digeomel** [comment]
But this is not working, I'm having similar problems to @TitaneBoy ... :disappointed: 

This is a sample of my code (remember, we're talking on the browser/client, NOT node.js!):

`<script src="/afis/web/resources/scripts/i18next.js"></script>
<script src="/afis/web/resources/scripts/jquery-i18next.js"></script>

<script>
	i18next.init({
		'debug': true,
		'lng': 'en',
		'fallbackLng': 'en',
		'resGetPath': '/afis/web/resources/locales/apfweb.en.json'
	}, function() {
		jqueryI18next.init(i18next, $);
		$('body').localize();
	});
</script>
`

What am I doing wrong?

**Comment by TitaneBoy** [comment]
@digeomel: I think you have some issue with pasting your code. We cannot see any line of code.

**Comment by jamuhl** [comment]
`'resGetPath': '/afis/web/resources/locales/apfweb.en.json'` is not v2, read the docs not some outdated stackoverflow answers:

configuring i18next with jquery plugin sample:
https://github.com/i18next/jquery-i18next/blob/master/example/sample.html#L19

adding xhr:
https://github.com/i18next/i18next-xhr-backend#backend-options 


```
<script src="/afis/web/resources/scripts/i18next.js"></script>
<script src="/afis/web/resources/scripts/i18nextXHRBackend.js"></script>
<script src="/afis/web/resources/scripts/jquery-i18next.js"></script>
<script>
i18next.use(i18nextXHRBackend);
i18next.init({
    'debug': true,
    'lng': 'en',
    'fallbackLng': 'en',
    backend: {
      loadPath: '/afis/web/resources/locales/{{ns}}.{{lng}}.json'
    }
}, function() {
    jqueryI18next.init(i18next, $);
    $('body').localize();
});
</script>
```

**Comment by digeomel** [comment]
Thanks @jamuhl ! :smile: :+1: 
I will try your solution some other time, in the meantime I just copied version 1.8.0 from another project that a colleague was working on, it's only one integrated script to load. It's a bit of an overkill to have to load 3 scripts on the client just for i18n.

**Comment by jamuhl** [comment]
modern time...nowadays you can use browserify, rollup, webpack or whatever to bundle your javascript.

**Comment by wd0401** [comment]
i'm a new software engineer ,i use the i18n like this code,but it din't run correct ,so i'd like to you help me to see my code and give me some suggest,thank you very  much!! @jamuhl 
``` <!DOCTYPE html>
<html lang="en">
<head>
    <script src="js/i18next.js"></script>
    <script src="js/i18nextXHRBackend.js"></script>
    <script src="js/jquery-i18next.js"></script>
    <script>
        i18next.use(i18nextXHRBackend);
        i18next.init({
            'debug': true,
            'lng': 'en',
            'fallbackLng': 'en',
            backend: {
                loadPath: 'locales/{{ns}}.{{lng}}.json'
            }
        }, function() {
            jqueryI18next.init(i18next, $);
            $('body').localize();
        });
    </script>
</head>
<body>
<ul class="nav">
    <li><a href="#" data-i18n="nav.home"></a></li>
    <li><a href="#" data-i18n="nav.page1"></a></li>
    <li><a href="#" data-i18next="nav.page2"></a></li>
</ul>
<h2 data-i18n="app.name"></h2>
</body>
</html>
```
this is my json file(locales/translation.json):
```
{
  "app": {
    "name": "i18next"
  },
  "nav": {
    "home": "Home",
    "page1": "Page One",
    "page2": "Page Two"
  }
}
```

**Comment by jamuhl** [comment]
looks like https://github.com/i18next/jquery-i18next/blob/master/example/sample.html just changing to use the xhr backend -> first thing to look at is if the translation files get loaded from locales/{{ns}}.{{lng}}.json open your dev console in browser - does it say stuff got loaded or do you get an error?

**Comment by wd0401** [comment]
thanks @jamuhl l! in my cosole in browser ,i find this , but i don't know what's wrong with it .
![image](https://cloud.githubusercontent.com/assets/19731985/20702992/eb987414-b654-11e6-8f04-3c05d575daf5.png)

**Comment by jamuhl** [comment]
```
   <script src="js/i18next.js"></script>
    <script src="js/i18nextXHRBackend.js"></script>
    <script src="js/jquery-i18next.js"></script>
```

seems you do not serve that files as it returns a html page (not found) or something like that.

**Comment by wd0401** [comment]
thanks very much @jamuhl  .i find there is something wrong of js file ,and then  i got it .

**Comment by yoavgecht** [comment]
I have a translation json file that sits on one of the client side directories.
I tried to load it on init but translations are not showing. 
how can I make it work?

**Comment by jamuhl** [comment]
@yoavgecht loading via xhr those files must be exposed on server you must be able to call that route in your browser

**Comment by yoavgecht** [comment]
thanks 
I installed it with npm
so which do I need to load?

/node_modules/i18next/i18next.js

I don't see 
i18nextXHRBackend.js
jquery-i18next.js

something very strange is going on...

**Comment by yoavgecht** [comment]
But you said that anyway everyone needs the xhr. even to load it from a client side directory.
so why put it in separate package? 
also the documentation is not clear at all

**Comment by jamuhl** [comment]
because you only need xhr if you need to load translations from server.

you also can just pass it in like: https://www.i18next.com/overview/getting-started#basic-sample

**Comment by jamuhl** [comment]
Or just read: https://www.i18next.com/how-to/add-or-load-translations

But don't tell documentation is not clear if not read through it

**Comment by jamuhl** [comment]
import or require your json and add it to resources

**Comment by yoavgecht** [comment]
Ok but it didn't work. Maybe I'm doing something wrong.
Can you show me in the i18next.init ?

**Comment by jamuhl** [comment]
make a jsfiddle or similar with your code...i can't guess how your project looks, if you're using webpack, requirejs,...

and if you do not use a bundler -> there is not something like a .json file on the clientside! I guess you will need to learn how things work.

**Comment by yoavgecht** [comment]
I'm using grunt and uglify
but I'm not near it now so I can't make a jsfiddle.
On Sunday or Monday I will write you.

Thanks for your help! :)

**Comment by yoavgecht** [comment]
Hey jamuhl,

i'm trying to load my translation.json in the init like this
i18next.init({
						lng: lang,
						resources: {
							translation: "/admin/locales/en/translation.json"
						}
					},
					function(err, t) {
                                          .....

but can't see the translations.

**Comment by jamuhl** [comment]
"/admin/locales/en/translation.json" is just a string you assign....you need to pass in the loaded translations.

If you're not using a module bundler (webpack, requirejs, ...) you can't. You will need to load resources from server using xhr.

Or provide the translations as .js files you load as regular scripts.

I would suggest asking this question over at stackoverflow or ask directly some of your friends having some basic knowledge of webdevelopment - this isn't an issue with i18next. I'm really sorry but i got not the time to teach people basics of development in my free time.

**Comment by yoavgecht** [comment]
I just want to do a simple thing. load it from a CLIENT SIDE directory.

The documentation is not showing how to do it. Only how to load it from a server.

I just want to load it like it used to be loaded on the old package.

resGetPath: "/admin/locales/__lng__/translation.json"

what is so hard to understand??

**Comment by jamuhl** [comment]
Do you know how server - client work -> how can those translations be in your clientside folder -> which is just a browser cache - the files are not on the clientside ... it's in your clientside folder in your project...but not....i give up...

At least....resGetPath...read the docs i posted before. https://www.i18next.com/how-to/add-or-load-translations#load-using-a-backend-plugin

or have look at the extended sample of the getting started guide: https://jsfiddle.net/jamuhl/ferfywyf/#tabs=js,result,html

or just check options for backends: https://www.i18next.com/overview/plugins-and-utils#backends

"The documentation is not showing how to do it" - do you read it - again i give up....sorry

**Comment by yoavgecht** [comment]
dude, its just a regular json file like any other file.
it bundels with the rest of the client side folders! like any js script
why I don't need an XHR call here

resGetPath: "/admin/locales/__lng__/translation.json"

it bundels it like the rest of the scripts

**Comment by jamuhl** [comment]
If you bundle that json file you can either require or import it - like any other file in "your clientfolder" and add it to resources like done here: https://github.com/dormakaba-digital/digital-reactnative-demo/blob/master/js/App.js#L9

**Comment by jamuhl** [comment]
You can provide me your code and i will make it work...my hourly rate is $140. Or you can read documentation - follow the endless samples i web. Read the migration guide for migration from 1.x.x to latest: https://www.i18next.com/misc/migration-guide

Please understand that a module maintainers job is not to teach you how to program. I really had more patience than needed with you pointing you into the direction to make it work. But you really do not understand anything, can't read docs, can't follow samples...you just copy half baked snippets here stating YOUR code does not work.

So do not take it personal if i do stop reply to your questions here. But i do not further waste my time for free.

**Comment by yoavgecht** [comment]
Wow 140$ hour i’m impressed..real Mark Tzuckerbeg. You are full of shit.
There is not even one example of how to load a json file from client side like the old resGetPath worked.

You pointed me to a stupid react example the uses the old i18n. Have fun being an ass hole

**Comment by jamuhl** [comment]
No need to be rude...one time you like to to add to resources using your bundled json - then you like using resGetPath like in old i18next which was a config for the xhr in v1.x.x.

I pasted you the link to https://jsfiddle.net/jamuhl/ferfywyf/#tabs=js,result,html which uses getResPath with the new name loadPath in the xhr backend: https://github.com/i18next/i18next-xhr-backend#backend-options

and $140 is a normal hour rate here in switzerland...sorry that i live in one of the most expensive countries in the world.

**Comment by jamuhl** [comment]
Plus that stupid react-sample uses latest version of i18next and was just the sample for using import/require as you stated you bundled the json with your clientscript....

**Comment by gregbown** [comment]
@jamuhl Thank you for the information here. It was instrumental in setting up my client side solution.
[Server AND Client setup in Express application](https://gist.github.com/gregbown/1b02096766606b6d80703a6c416c1ea5)

**Comment by EMMWIS** [comment]
rest but all solution and set is side name emm || wis the here do it up as in for local john
