### ISSUE TITLE
app.use(i18n.handle) error

### ISSUE THREAD

**Issue by barisusanmaz** [i18next/i18next#634]
Hello,
I am trying to use i18next library in my nodejs project.
Let me explain what I did step by step.
- In app.js I wrote `var i18n = require('i18next');`
- Also before `var app=express() `
```
i18n.init({
    lng: 'en',
    preload: ['en', 'tr'],
    fallbackLng: 'en',
    saveMissing: true,
    sendMissingTo: 'en',
    debug: true,
    useCookie: false,
    setJqueryExt: false,
    detectLngFromHeaders: false,
    ns: {
        namespaces: ['translation'],
        defaultNs: 'translation'
    }
});
```
- When I write `app.use(i18n.handle);` I get error below.

> app.use() requires middleware functions
- Also `registerAppHelper` gives same error.

```
var i18n = require('i18next');

i18n.init({
    lng: 'en',
    preload: ['en', 'tr'],
    fallbackLng: 'en',
    saveMissing: true,
    sendMissingTo: 'en',
    debug: true,
    useCookie: false,
    setJqueryExt: false,
    detectLngFromHeaders: false,
    ns: {
        namespaces: ['translation'],
        defaultNs: 'translation'
    }
});
        
var app = express();

app.use(i18n.handle);
i18n.registerAppHelper(app);
```
- How can I use your library in nodejs apps? Do you have any documents that explains this process?

Thanks.

**Comment by jamuhl** [comment]
i don't know where you got this configuration from...but that is the old configuration:

for new have a look here:
- https://github.com/i18next/i18next-express-middleware
- http://i18next.com/docs/migration/

**Comment by jamuhl** [comment]
feel free to reopen if any other problem arise...glad to help
