### ISSUE TITLE
how to use i18next.changeLanguage

### ISSUE THREAD

**Issue by jackple** [i18next/i18next#635]
the browser told me that "Cannot read property 'changeLanguage' of undefined" and then I console the i18next object,there is not changeLanguage in it !
should I load a plugin about changeLanguage?
how to fixed this problem?

**Comment by jamuhl** [comment]
changeLanguage is a function directly on i18next instance...so if that is not found you might not access i18next. Seems you have some undefined object you try to use. how you import i18next?

**Comment by jackple** [comment]
I think I put it a wrong position. Now I have fixed this problem. Thank you...
