### ISSUE TITLE
Synchronous init?

### ISSUE THREAD

**Issue by megapctr** [i18next/i18next#636]
Hi, is there a proper way to initialize i18next synchronously?

I import my translations from a json file (via webpack), so they're available instantly. Therefore I'd expect `i18n.t` to be ready to use as soon as `i18n.init` is called. Instead, I have to wait for callback to be called.

By browsing through the source code, I came up with this:

<pre>
i18n.init({
    resources: translations,
    lng: language,
    ...
})
<b>i18n.changeLanguage(language)</b>
</pre>

It's more of a hack than a solution -- is there a proper way to do this?

**Comment by jamuhl** [comment]
hm...i see...will call changeLanguage immediatly when passing in resources...will keep you uptodate.

**Comment by jamuhl** [comment]
can you try v2.4.1?

https://github.com/i18next/i18next/commit/0b5ac34374b099e8f27d2ce8280919a0f73fcac3#diff-e171f9b8b4e0f5df027bd8bd7b962f1bR1724

**Comment by megapctr** [comment]
Works, thanks :)

**Comment by bppr** [comment]
This is not working for me -- it appears that the callback is being called before `i18next` is finished setting itself up.

```
const opts = {
  resources: { en: { translations: { 'a-key': 'a-value' }}}
  lng: 'en'
};

const cb = (err, t) => {
  t('a-key');   // => 'a-key'
};

i18next.init(opts, cb);
```

**Comment by AlexandrDobrovolskiy** [comment]
Is there any way to call init synchronously? I'm using static form configs with localization, and sometimes strings are not loading (`i18next.t('some.key')` returns `undefined`), here is the example:

```
export default {
  // huge form config
  field: {
    defaultValue: i18next.t('some.key')
  }
}
```

It works well with React components because it probably calls .t before init, but not in configs because they're called once at the first stack execution.

**Comment by jamuhl** [comment]
@AlexandrDobrovolskiy you need a backend that load translations all on init and all sync/blocking or add them in resources on init (= load it initial with all other js stuff)

But better would be:
https://github.com/i18next/react-i18next/issues/1042

Or as a long story:
https://github.com/i18next/react-i18next/issues/909

**Comment by AlexandrDobrovolskiy** [comment]
@jamuhl Thanks for the quick reply :) I already have them in resources, anyway the issue is gone and I can't reproduce it anymore (maybe it was in our code and someone of my teammates' accidentally fixed it). I'll write to you if it will appear again.
