### ISSUE TITLE
Interpolate question

### ISSUE THREAD

**Issue by nathanredblur** [i18next/i18next#637]
Hi, How can I solve this?

I use Angular and I hace a key that could have different values depend where is render. 

suppose that I have this

```
key1: "Nice text say: {{hello}}"
```

and some case I need JADE render with value from server

```
h1=t("key1", {hello: server.sayHello})
// output <h1>Nice text say: yo! Bro</h1>
```

But some times I need that Angular.js render in client time, angular has the same interpolate system "{{var}}

```
h1=t("key1", {hello: "{{client.sayHello}}"})
```

I spect 

```
 <h1>Nice text say: {{client.sayHello}}</h1>
```

but I'm getting this and some log that say : 
```i18next::interpolator: missed to pass in variable```

```
 <h1>Nice text say: </h1>
```

Thank for your help. (And this awesome and very useful tool)

**Comment by nathanredblur** [comment]
I needed a quick answer, the I figure out another way. This my solution:

```
h1=t("key1", {hello: "var1"}).replace("var1", "{{client.sayHello}}")
```

I someone has a better solution :)

**Comment by jamuhl** [comment]
we do something similar in react-i18next interpolation component:

https://github.com/i18next/react-i18next/blob/master/src/interpolate.js#L15

our solution is to call `t` with another interpolation suffix, prefix:

`h1=t("key1", { interpolation: { suffix: '*#$', prefix: '*#$' }))`

basically you can create a overridden t function...

**Comment by jamuhl** [comment]
what you think? should we add some option to not remove unmatched vars?

**Comment by nathanredblur** [comment]
I try your solution but doesn't work for me. 
Because I need interpolate the value of the KEY but not interpolate the value to interpolate.

interpolate this: ```"Nice text say: {{hello}}"```
not that: ```{{client.sayHello}}```

and when I do your approach, no works any interpolation. 

will be nice an option to prevent this.

**Comment by nathanredblur** [comment]
-_- My easy solution was use the old standard 

```
i18nextOptions = {
  backend:{
      loadPath: config.root + '/locales/__lng__/__ns__.json',
      addPath: config.root + '/locales/__lng__/__ns__.missing.json'
    },

    interpolation:{
      prefix: "__",
      suffix: "__"
    }
}
```

**Comment by nathanredblur** [comment]
Will be good idea to help to someone (like me) that want to migrate from old standard to new one support two different prefix and suffix.
```
interpolation:{
    prefix: ["__", "{{"],
    suffix: ["__","}}"]
}
```
In that way we can do an smooth transition.
and some option to not interpolate options, like.

```
h1=t("key1", {hello: "{{client.sayHello}}", interpolation: { interpolateOptions: false }})
\\ or
h1=t("key1", {hello: "##{{client.sayHello}} budy", interpolation: { noInterpolatePrefix: '##' }})
```

**Comment by jamuhl** [comment]
for 'old standard' there is http://i18next.com/docs/migration/#v1-11-x--v2-0-0-comp

while i will remove apiCompatibility in future the jsonCompatibility will stay
