### ISSUE TITLE
Question: How to translate a JSON object

### ISSUE THREAD

**Issue by TitaneBoy** [i18next/i18next#644]
Hi again.

I have a question: Is there a way (easy or not) to translate a json object (or json schema object) with your awesome tool  and to get as a result a translated Json object ?

For example, I have this JSON object:

```
{
        "Key 1" : "First Sentence to translate", 
        "Key 2" : "Second Sentence to translate"
}
```

And I would like to apply a function on it and to have has an output this JSON object:

```
{
      "Key 1" : "First Sentence TRANSLATED", 
      "Key 2" : "Second Sentence TRANSLATED"
}

```
An other picture:

|   JSON OBJECT  |     -------->  Function / Process/ other...   ----------> |  TRANSLATED  JSON OBJECT  |

Thank you for your answer :-)

**Comment by jamuhl** [comment]
what you search might be this: http://i18next.com/translate/objects/

**Comment by TitaneBoy** [comment]
Hi Jamuhl. Unfortunetly, this is not what I am looking for. I want to translate each Key's value of an entire custom Json object.

For example, This is what I have loaded in my i18next module (for French language):
```
{
     "Hello": "Bonjour",
     "Good-Bye": "Aurevoir"
}

```
And from somewhere in my software, I get a json object which is:

```
Custom_Json_Object = 
{
   "Key1": "Hello",
   "Key2": "Good-Bye",
   "Key3":"Custom Value"
}
```

Then I want to take this custom json object, pass it as a parameter in a function (or process or something else), like this:

| Custom_Json_Object  | --------> Function / Process/ other... ----------> | Custom_Translated_Json_Object |

 and to have the following json object as the result:

```
Custom_Translated_Json_Object = 
{
  "Key1": "Bonjour",
   "Key2": "Aurevoir",
   "Key3":"Custom Value"
}
```
As you can see in the resulted json object, the key values: "Hello", "Good-Bye" have been translated in the new returned json object. But this returned json object is not in my loaded json resources file, only the key values (i.e "Bonjour" and "Aurevoir")

Your suggestion returns a json object which is inside the i18next json loaded resources files (For example, from your example at [http://i18next.com/translate/objects/](url) , the "{"res":"added"}" is an object value of the key "Tree" in the loaded resources. But this is not what I am looking for, as you can see in my previous example.

Do you think it is possible to do what I am looking for ?

Thank you for your answer

**Comment by jamuhl** [comment]
there is no built in function for that, but you basically can loop over your object and create a new translated one:

```
var Custom_Json_Object = {
   "Key1": "Hello",
   "Key2": "Good-Bye",
   "Key3":"Custom Value"
};

var Translated_JSON_Object;
for (var m in Custom_Json_Object) {
  Translated_JSON_Object[m] = i18next.t(m);
}
```

**Comment by TitaneBoy** [comment]
Well..This is what I thought. The idea is great but the problem is a litter more complex than just looping the custom json object. But the main idea still remain. Thank you very much for your answer, jamuhl..:-)

**Comment by TitaneBoy** [comment]
Hi Again. For those who will hit the same issue than me, I found a great util: `traverse` ([https://github.com/substack/js-traverse](url))

It will loop for you inside your custom json object. With it, you can check each key value and perform an operation on it ( like to traduce the string ;-) )

```
var traverse = require('traverse');
var jsonObject = {"key1":"_value1_to_translate", "key2": {"key2_1":"_value2_1_to_translate"}}
var jsonToTranslate = JSON.parse(jsonObject);

// Each string beginning with "_" will be translated
traverse(jsonToTranslate).forEach(function(original_string){
    if (typeof original_string === 'string' && original_string.startsWith('_')){
      this.update(i18next.t(original_string.substr(1), 'fr'));
    }
  });

// In this example, I updated directly the json object with translated string. You can get a new json object by using "=" 
// operator before the call of the function "traverse" and put the result inside a new variable 
// (like: var newTranslatedJsonObject = traverse(jsonToTranslate).forEach ...)  
```

Enjoy :-)
