### ISSUE TITLE
Connector.load triggers re-save of localStorage for every namespace

### ISSUE THREAD

**Issue by jonapgar** [i18next/i18next#646]
Connector.load calls addResourceBundle for each namespace, which triggers the "added" event to fire on the resourceStore, which re-saves the cache. 

In effect, this causes a re-save for every language*namespace loaded from the cache. This means if you have 25 namespaces, localStorage is being written to 25 times (and thus the cache is being stringified 25 times). This is expensive.

**Comment by jamuhl** [comment]
debounce the write would solve this...could add this to the i18next-localstorage-cache (think it should be the caching modules responsibility to find a efficient balance).

will add this for next version of the cache module.

**Comment by jamuhl** [comment]
could you try i18next-localstorage-cache@0.3.0 it will debounce write on a 10s timing.

**Comment by jamuhl** [comment]
feel free to reopen if still an issue...
