### ISSUE TITLE
Regression in 2.3.5 -> 2.4 update

### ISSUE THREAD

**Issue by mathieumg** [i18next/i18next#650]
Since updating from v2.3.5 to v2.4.0 (v2.4.1 changed nothing so the bug is in 2.4), I have the following issue:

If I try to access a key using `t("a::b.c")` (a is the namespace, b is the key and c is the subkey), I get the `b.c` string. Previously, it correctly returned the value of c in the `a.json` (namespace) file:

```js
{
  "b": {
    "c": "My translated value"
  }
}
```

This happens in the front-end. I can post my configuration if you need further information to help pinpoint the issue. Thanks!

**Comment by jamuhl** [comment]
when do you access `t("a::b.c")` seems like you do not wait for the callback `i18next.init(opts, callback)` ?

**Comment by mathieumg** [comment]
`i18next.init(opts)` is called without callback because all options are known ahead of time and there is no asynchronous operation to perform. Isn't that the idea behind it? Thanks for the quick reply!

**Comment by mathieumg** [comment]
It might have to do with the `setTimeout` loading introduced in 2.4. I think that instead of sniffing if resources are provided, like in https://github.com/i18next/i18next/commit/0b5ac34374b099e8f27d2ce8280919a0f73fcac3 the `setTimeout()` call should be avoided whenever there is no `callback` provided.

Once the code hits https://github.com/i18next/i18next/blob/0b5ac34374b099e8f27d2ce8280919a0f73fcac3/src/i18next.js#L40 it sets a noop callback as default (like it does now) but it also flips a boolean that is inspected on https://github.com/i18next/i18next/blob/0b5ac34374b099e8f27d2ce8280919a0f73fcac3/src/i18next.js#L115. What do you think? Do you want me to submit the PR?

**Comment by jamuhl** [comment]
does not make a difference if no callback is provided. it's about having time to do something before load gets triggered:

```
i18next.init();
i18next.addResourceBundle(...);

// loading takes place after addResourceBundle 
```

**Comment by jamuhl** [comment]
i18next.init(opts) is called without callback because all options are known ahead of time and there is no asynchronous operation to perform.

--> only if there is no need to load resources...which is only clear if added inside options

**Comment by mathieumg** [comment]
> only if there is no need to load resources...which is only clear if added inside options

No, there are other scenarios where `init` is used synchronously. All the plugins (xhr, local storage, etc.) load the resources as they're needed, but `i18next.init()` doesn't need to be async for that to work.

**Comment by jamuhl** [comment]
how you load resources not async?

**Comment by mathieumg** [comment]
Resources are loaded async on-demand, but the `i18next.init` call itself is sync.

**Comment by jamuhl** [comment]
you override the loading in xhr to be synchronous...? well then the only option i see is a new init flag `initSync: true` default false

**Comment by mathieumg** [comment]
Hi, sorry for the delay! I don't override anything, what I'm saying is, when you use async stuff such as XHR, it loads namespaces on demand using AJAX, correct? So if a page only uses a few namespaces, it would only load those when the appropriate translation calls are made (and it realizes it has to fetch it over the wire). If that is correct (I could have got the whole thing wrong), it's perfectly reasonable to believe that upon loading the page, the resource store would be empty. 

Essentially, configuring i18next initially is sync because there is no remote fetching, whereas fetching a resource can be async depending if it was already fetched or not.

Instead of the `initSync` option, why wouldn't sniffing if there's a callback be sufficient? (Like it's already done when missing) Another solution could be to point users to something like https://github.com/caolan/async#ensureAsync instead of relying on the `setTimeout` from within.

Thanks!

**Comment by jamuhl** [comment]
nope...translations calls do not trigger the loading of resources:

calling t function is completely sync: i18next.t -> return value

loads are triggered by:
- init
- change language
- load namespaces
- load languages

**Comment by mathieumg** [comment]
Ok, I stand corrected! Then, it must be falling under the case where the callback I use to load resources is sync. (Webpack chunk, but it also applies for local storage, for instance) So, which of the solutions would you prefer? Custom `initSync` option, callback sniffing for the `setTimeout`, or revert to no `setTimeout` and refer users to third-party to ensure the init call is not sync. (It's really what the `setTimeout` does.) If `init` is reverted to the previous iteration, it becomes possible for a user to make it "be async" from the outside if the callback chain is sync, whereas the other way around (make the current version "be sync") is not possible.

**Comment by jamuhl** [comment]
the init call is by design is async. as it has an optional callback - the callbacks presence does not define if async or sync - just states if you're interested in the information that loading is done - which highly depends on your demands.

so basically the init call in older versions was async too, just worked sync as there where no async operations needed.

the new timeout just enables operations between init and load...like adding resourceBundles.

so only option i see is adding a new option on init - which i hoped to avoid.

**Comment by mathieumg** [comment]
> just worked sync as there where no async operations needed

And that is fine when it is what is wanted, no?

To enable operations between init and load, can't you defer the callback from outside?

```js
i18n.init(/* ... */, () => setTimeout(() => myCallback())); // Ensures async.
i18n.addResourceBundle(/* ... */);
```

This allows the following to still work:

```js
i18n.init(/* ... */); // Sync.
i18n.t(/* ... */); // Returns the value correctly.
```

**Comment by jamuhl** [comment]
does not work. the call to changeLanguage would be before return from init. just passing a timeout function as callback won't make a difference.

really only save way is to add a flag for cases like yours. nothing agaist that. but default will be async as it makes most sence.

**Comment by jamuhl** [comment]
i18next@2.5.0 - init with option `initImmediate: false` to trigger "sync" init...

**Comment by mathieumg** [comment]
I just saw that! Thanks for the quick action, I'll test it and report back.

**Comment by mathieumg** [comment]
Works as expected! Thanks again.

**Comment by jamuhl** [comment]
glad...we got a solution...thank you for your patient.
