### ISSUE TITLE
Question: How to handle HTML?

### ISSUE THREAD

**Issue by Superdominik** [i18next/i18next#657]
Hello, I've got i18next working perfectly. Thank you very much for this framework. There's just one last thing in my website that I'm not sure how to handle correctly with i18next.

I've got an address block like this
```
<address>
  <strong>Company</strong><br>
  Street<br>
  City<br>
  COUNTRY
</address>
```
and I was wondering how to handle this. I couldn't find anything about this in the documentation.

Here is what I've tried 
```
<address data-i18n="address">
  <strong>Company</strong><br>
  Street<br>
  City<br>
  COUNTRY
</address>
```
with these 2 different things in my JSON file
```
"address": "<strong>Company</strong><br>Street<br>City<br>COUNTRY"
```
```
"addressHTML": "<strong>Company</strong><br>Street<br>City<br>COUNTRY"
```
The first one did translate the HTML to clear text and the second one didn't work at all. Probably because it's ng only?

It would be great if you could help me out on this one. 

Thank you very much in advance.

**Comment by jamuhl** [comment]
this is for jquery-i18next plugin? right?

did you try: https://github.com/i18next/jquery-i18next#set-innerhtml-attributes

**Comment by Superdominik** [comment]
Thank you very much. That's all I needed. I didn't think about looking on the jQuery-specific page. It already works.

**Comment by jamuhl** [comment]
perfect...

**Comment by isld** [comment]
How should I handle a very similar situation, but in React? 

What I'm trying to do is translating "Total: \<strong>{{amount}}\</strong>" string. My init looks like:

```
i18n
	.use( XHR )
	.init({
		lng: appLanguage,
		whitelist: [ 'en', 'bg' ],
		load: 'languageOnly',
		ns: [ 'common' ],
		defaultNS: 'common',
		fallbackLng: false,
		nsSeparator: '::',
		contextSeparator: false,
		keySeparator: false,
		debug: true,
		returnEmptyString: false,
		interpolation: {
			escapeValue: false
		},
	});
```

I also tried translating "Total: {{amount}}" and concatenating the \<strong> tags to the value, but I couldn't make it work either.

Am I doing something wrong (again) and what is the best practice in this case?

**Comment by jamuhl** [comment]
you can use the interpolate component of react-i18next: https://github.com/i18next/react-i18next#interpolate-component

**Comment by isld** [comment]
A-ha, so there we go again with me not reading carefully all the documentation...

Now another problem showed up - it turns out that i18n-parser doesn't extract the keys from interpolate components. Should I open an issue there or should I try to fix it and open a PR?

**Comment by jamuhl** [comment]
i18n-parser is not maintained by me - so you might open an issue and/or add a PR there.
