### ISSUE TITLE
Question about Key Based fallback (in Client-Side)

### ISSUE THREAD

**Issue by TitaneBoy** [i18next/i18next#658]
Hi jamuhl.

I have a question:

In client side, when I use i18next modules with options, I can't undersand why I need a fallback language when I want to use the key based fallback feature [http://i18next.com/translate/keyBasedFallback/](url)

So for this, I set these options:

```
nsSeparator: false,
keySeparator: false,
```

So I expect that if the kjey does not exist in the specified language, it should return the key. So basically, if all my keys are in english, it means that I do not need to have an english json file resource, right ??

If I have this in the end of my html body:

```
<script type="text/javascript">
        var i18nextOptions = {
                              preload:['fr','es'],
                              whitelist:['fr','es'],
                              ns:'My_Web_Server',
                              defaultNS:'My_Web_Server',
                              nsSeparator: false,
                              keySeparator: false,
                              backend: {loadPath: '/language/static/{{lng}}/{{ns}}.json', addPath: 'language/static/add/{{lng}}/{{ns}}.json'},
                              detection: {order: ['querystring', 'cookie', 'navigator', 'localStorage'],
                                          lookupQuerystring: 'lng',
                                          lookupCookie: 'i18next',
                                          lookupLocalStorage: 'i18nextLng',
                                          caches: ['localStorage', 'cookie'],
                                          cookieMinutes: 5},
                              debug: true
                             };
        i18next
          .use(i18nextXHRBackend)
          .use(i18nextBrowserLanguageDetector)
          .use(i18nextSprintfPostProcessor)
          .init(i18nextOptions, function(err, t){

            jqueryI18next.init(i18next, $, {useOptionsAttr:true});
            $('.MyTest').localize({lng:'en-US'});
          });
</script>
```

Notice here that no "en-US" is reploaded in options, is not in the white-list and no "fallbackLng" is specified. And at the end, I,m doing this: `$('.MyTest').localize({lng:'en-US'});`. I want to force it to translate strings in a language that doesn't exist in my resources. So I thought that the keys will be returned but at the end, nothing is returned. No strings are visible, even original strings (i.e keys). 

Can you tell me please why I absolutly need to preload "en-US" language and to put it in whitelist (and of course to have all the key strings inside en-US json resource file)  to make things work ? If I want a Key Based fallback behavior, are you agree with me that we do not need en-US language resources file and to specify it in options ?

With gettext, you do not need to have english po/mo files. If the string/key does not exist in language resource file, it returns automatically the key as the result.

In my web page, I have a dropdown box with different language value that the user can choose. If he load the page in french for example and then want to choose english language, I thought that I could use the key based fallback behavior to return original english strings (All my keys are basically in english). But even I specified the 2 options to have the Key based fallback, it looks to not working in client side. I absolutely need to have english json resource file and to add the "en-US" value in "preload" and "whitelist"  to have the key original strings.

Can you help me please to resolve that ?

Thank you in advance.

**Comment by jamuhl** [comment]
set fallbackLng to false

**Comment by TitaneBoy** [comment]
Hi jamuhl.
I've tried to set fallbackLng to false but nothing happens: No translation (or key-based fallback) is done. If the first load of the page is in language different from english and then if I switch to english, no english (key) strings are returned: only previous selected language string values are shown.

**Comment by jamuhl** [comment]
might be the jqueryI18next using `parseDefaultValueFromContent: true`that would parse default values from current content, but only guessing:

try `jqueryI18next.init(i18next, $, {useOptionsAttr:true, parseDefaultValueFromContent: false});`

**Comment by TitaneBoy** [comment]
Wonderfull..It works !

Thank you very much for your help :-)
