### ISSUE TITLE
Crash of the server when trying to translate in an inexistant language

### ISSUE THREAD

**Issue by TitaneBoy** [i18next/i18next#666]
Hi. I have a server crash when I'm trying to translate a string in a language that is not loaded in 18next resources.

Here is my server configuration:

```
var i18nextMiddleware = require('i18next-express-middleware');
var i18nextBackend = require('i18next-node-fs-backend');
var i18nextOptions = {debug:false, preload: ['es','fr', 'zh-HANS'], fallbackLng:false, whitelist:['fr', 'es', 'zh-HANS'], load:'currentOnly', saveMissingTo:'all',
                      saveMissing:true, ns:'My_Web_Server', defaultNS:'My_Web_Server', nsSeparator: false, keySeparator: false,
                      backend:{loadPath: 'language/static/{{lng}}/{{ns}}.json', addPath: 'language/static/{{lng}}/{{ns}}.missing.json', jsonIndent: 2}};

var port = 80;
var app = express();

i18next
  .use(i18nextMiddleware.LanguageDetector)
  .use(i18nextBackend)
  .init(i18nextOptions);

app.use(i18nextMiddleware.handle(i18next, {removeLngFromUrl: false}));

```
Notice here that "fallbackLng" is set to false, same as "nsSeparator" and "keySeparator". Notice too that no 'en' language is preloaded and is not added in the whitelist. My main idea is to use the key fallback behavior of i18next (aka I want that i18next returns me the key if it doesn't find the translation in the given language (which does not exist in our example) )

But when i'm trying to translate a string in a given language:

```
var languageToTranslate = 'en';
var translatedString = req.t("My string to translate", {lng: languageToTranslate});
```

It crash completly the server with this error in the console log

```
c:\MyApp\node_modules\i18next\dist\commonjs\ResourceStore.js:84
    if (lng.indexOf('.') > -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at ResourceStore.addResource (c:\MyApp\node_modules\i18next\dist\commonjs\ResourceStore.js:84:12)
    at Connector.saveMissing (c:\MyApp\node_modules\i18next\dist\commonjs\BackendConnector.js:257:16)
    at Translator.translate (c:\MyApp\node_modules\i18next\dist\commonjs\Translator.js:183:39)
    at I18n.t (c:\MyApp\node_modules\i18next\dist\commonjs\i18next.js:307:57)
    at IncomingMessage.t (c:\MyApp\node_modules\i18next-express-middleware\lib\index.js:56:22)
```

Can you help me with this, please ?

Thank you for your answer.

**Comment by jamuhl** [comment]
as key is fallback in your case you should turn of saveMissing - your key always exists so there is no missing.

**Comment by jamuhl** [comment]
but will add a fix to not trigger that if no lng in saveMissing call

**Comment by TitaneBoy** [comment]
Thank you :-)

**Comment by TitaneBoy** [comment]
It will be anyway great to save missing key for available languages, even if the key will be the fallback. It could help us to know what are the missing keys we need to translate in the future.

**Comment by jamuhl** [comment]
change option sendMissingTo = 'current' for your i18next init options -> will send missing to current lng instead of fallback (which is undefined in your case)

**Comment by TitaneBoy** [comment]
Hi jamuhl. I've tried to apply your last tip (change sendMissingTo from "true" to "current" and the problem still remain.

```
C:\MyApp\node_modules\i18next\dist\commonjs\ResourceStore.js:84
    if (lng.indexOf('.') > -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at ResourceStore.addResource (C:\MyApp\node_modules\i18next\dist\commonjs\ResourceStore.js:84:12)
    at Connector.saveMissing (C:\MyApp\node_modules\i18next\dist\commonjs\BackendConnector.js:257:16)
    at Translator.translate (C:\MyApp\node_modules\i18next\dist\commonjs\Translator.js:183:39)
    at I18n.t (C:\MyApp\node_modules\i18next\dist\commonjs\i18next.js:307:57)
    at IncomingMessage.t (C:\MyApp\node_modules\i18next-express-middleware\lib\index.js:56:22)
```

**Comment by jamuhl** [comment]
hm...https://github.com/i18next/i18next/blob/master/src/Translator.js#L124 lng is `en` and passed in options

```
var languageToTranslate = 'en';
var translatedString = req.t("My string to translate", {lng: languageToTranslate});
```

so saveMissing will be called with `['en']` which will call addResource with `lng='en'`

https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L180

can't reproduce this. could you add some console.log and try to find the cause...

**Comment by TitaneBoy** [comment]
Hi jamuhl.
Sorry..That was my mistake... I changed the value of "saveMissing" instead of "saveMissingTo". Now I've changed "saveMissingTo" to 'current' value, everything looks to work great. :-) I do not need to preload english language and I can now use the key fallback behavior.  Thank you for your support.

**Comment by jamuhl** [comment]
👍
