### ISSUE TITLE
i18next does not work with requireJs

### ISSUE THREAD

**Issue by mkarpinski** [i18next/i18next#684]
It is said that it should be bundled as UMD module compatible with require but it does not work.

require.config({
    paths: {
        "jquery": "lib/jquery/jquery-2.2.0.min",
        "bootstrap": "lib/bootstrap-3.3.6/js/bootstrap.min",
        "i18n": "lib/i18next/i18next.min"
    },
    shim : {
        "bootstrap": { "deps": ["jquery"] },
        "datetimepicker": { "deps": ["moment","bootstrap"] },
        "i18n": { "deps": ["jquery"] }
    },
    
    waitSeconds: 30
});

After this require("i18n") returns undefined.

**Comment by jamuhl** [comment]
see https://github.com/i18next/i18next/blob/master/i18next.js

there is no longer a dependency on jquery. might be export changed slightly from old version to this. as we use rollup for that.

**Comment by jamuhl** [comment]
any update on this?

**Comment by mkarpinski** [comment]
The issue was that it is a named module and I had some differences in my naming/dirs.
Require suggests that unnamed modules should be preferred over named ones to avoid portability problems

**Comment by jamuhl** [comment]
will deploy i18next v3.0.0 today...will change build to unnamed module export.
