### ISSUE TITLE
Multiple plural forms not working

### ISSUE THREAD

**Issue by eugen35** [i18next/i18next#686]
**Multiple plural forms not working ( **

i use node v5.5.0, "express": "4.13.4", "i18next": "2.5.1",  "i18next-node-fs-backend": "0.1.2"

```
var i18next = require('i18next')
var Backend = require('i18next-node-fs-backend')
i18next
    .use(Backend)
    .init({
      debug: true,
      lng: "ru",      
      ns: 'translation',     
      backend:{
        // path where resources get loaded from
        loadPath: './locales/{{lng}}/{{ns}}.json'        
      }
    }, (err, t) => {     
      console.log('signin '+i18next.t('signin') )
      for (let i=0;i<15;i++) console.log( i + ' ' + i18next.t('object', {count:i} ) )    
    })
```
locales/en/translation.json:
```
{
    "signin": "русский",
    "object_0": "bb sing",
    "object_1": "bb pl1",
    "object_2": "bb pl2"
}
```

In console i will take this output:

> signin русский
> i18next::translator: missingKey ru translation object object
> 0 object
> 1 bb pl1
> 2 bb pl2
> 3 bb pl2
> 4 bb pl2
> i18next::translator: missingKey ru translation object object
> 5 object
> i18next::translator: missingKey ru translation object object
> 6 object
> i18next::translator: missingKey ru translation object object
> 7 object
> i18next::translator: missingKey ru translation object object
> 8 object
> i18next::translator: missingKey ru translation object object
> 9 object
> i18next::translator: missingKey ru translation object object
> 10 object
> i18next::translator: missingKey ru translation object object
> 11 object
> i18next::translator: missingKey ru translation object object
> 12 object
> i18next::translator: missingKey ru translation object object
> 13 object
> i18next::translator: missingKey ru translation object object
> 14 object

**What is the matter?**

**Comment by eugen35** [comment]
But with "ar" language all working good:
```
{
  "key_0": "zero",
  "key_1": "singular",
  "key_2": "two",
  "key_3": "few",
  "key_11": "many",
  "key_100": "plural"
}

```
in console:

> 0 zero
> 1 singular
> 2 two
> 3 few
> 4 few
> 5 few
> 6 few
> 7 few
> 8 few
> 9 few
> 10 few
> 11 many
> 12 many
> 13 many
> 14 many
> 

**May be there is in russian pluralResolver mistake?**

**Comment by jamuhl** [comment]
numbers for russian are: 1,2,5 https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L18

we use the numbers not the index of the number like gettext does!

```
{
    "signin": "русский",
    "object_1": "bb sing",
    "object_2": "bb pl1",
    "object_5": "bb pl2"
}
```

**Comment by evgenosiptsov** [comment]
> numbers for russian are: 1,2,5
Well, there is mistake in website documentations:
![screenshot 2016-08-17 06 54 18](https://cloud.githubusercontent.com/assets/17506504/17724096/d60ffdf6-6447-11e6-9871-340a6fa8d1ee.png)

**Comment by evgenosiptsov** [comment]
And cool be nice have possibility to get missed plurual numbers in missingKeyHandler function

**Comment by jamuhl** [comment]
numbers where used in v2.x.x on the way to v3.x.x we made a big change to use not anylonger this numbers - as they have no real sense. Using the pure index is fully compatible to gettext style.

for backwards compatibility: http://i18next.com/docs/jsons/#v2

for the missingKeyHandler extension, please open a new issue - we might pass the options there too - so one could use the function to get the plural suffix on the i18next.services.pluralResolver.
