### ISSUE TITLE
Suggestion: fallbackLng default value - undefined

### ISSUE THREAD

**Issue by San7hos** [i18next/i18next#693]
I was setting up i18next yesterday. It works nice, but I have spend quite some time to figure out why the engine does 3 calls for these langs:
- en-US
- en
- **dev**

I am using the library with the xhr backend plugin (and localstorage plugin) and I wanted to load the resources just using the backend. Finally, I have figured out that I need to use these options:
- load: 'currentOnly'
- fallbackLng: undefined,
- optionally use whitelist

Current default for load is 'all' and fallbackLng is 'dev'. I think it is rather confusing than helping/straight forward, especially the fallbackLng.

Therefore I suggest the default value for the fallback undefined (and optionally for load 'currentOnly').

**Comment by jamuhl** [comment]
not providing a fallback is dangerous...what if a user comes on your page and has a language you don't provide? show nothing? or better eg. en fallback?

what are the cost of the 3 calls? if the file does not exist it's an immidiate 404 at no bandwidth cost.

this way you can even just provide 'en' for both en-US and en-GB, optionally replace keys that differ only in the en-GB file.

so:
- setting fallbackLng to `false` or `undefined` would mean no content for non resolvable user language (this might be ok if you set language based on some user information you got in your system - but not when using language detector)
- setting load to `currentOnly` would result in issues if you just change the keys that differ in lng-Region vs. lng

Would it help to describe the changes you mention on http://i18next.com/translate/ ?

**Comment by San7hos** [comment]
I guess my use case is narrower because my site supports just two languages that I definitely know they are there. So as you mention I do not use language detector and I also provide the lng parameter so I know exactly how it looks.

My init is quite simple:
```
let language = "something I get from backend";
...
.init({
    debug: false,
    load: 'currentOnly',
    lng: language,
    preload: [language],
    fallbackLng: undefined,
    resources: undefined,
    //whitelist: ['en-US', 'nb-NO'],
    backend: {
        loadPath: "/Localisation/Get/{{lng}}",
        allowMultiLoading: false,
        crossDomain: false,
    },
    cache: {
        enabled: true,
        prefix: "i18next_res_",
        expirationTime: 12 * 60 * 60 * 1000
    }
});
```

However, I was surprised that even when I specified en-US all of the three calls (en-US, en, dev) were made. Then, I found the "load" option. I feel it is not too clear from the documentation. Otherwise, I think the lib is very good.

Last thing that is bothering me is that the i18next object does not emit the events or I am not sure how to turn that on.

```
i18next.on('missingKey' function() { console.log('hi'); });
i18next.t("fireMissingKeyBecauseThisKeyDefinitelyDoesNotExist"); // shows nothing in the console
```

I tried to emit the 'missingKey' even manually in Chrome console calling `i18next.emit('missingKey')` and that has worked.

**Comment by jamuhl** [comment]
missingKey only fires when option saveMissing is true - this is more or less the case to allow devs to have this turned on during development and turned off in production...

**Comment by San7hos** [comment]
I see, I thought I would use it in production in case I missed some key and bound application insights tracking to the event.

**Comment by jamuhl** [comment]
sure...we do the same on our application...but there are others prefer to have it only turned on for development.

**Comment by jamuhl** [comment]
i18next@3.1.0 will trigger missingKey independent of the saveMissing setting - think that is better - if people want only saveMissing behaviour they could still use missingKeyHandler on init.

**Comment by jamuhl** [comment]
updated http://i18next.com/translate/
