### ISSUE TITLE
saveMissingTo: "all" does not save missing translation in all languages files

### ISSUE THREAD

**Issue by eajimmy** [i18next/i18next#696]
Hello all,
thanks for this awesome module!!
I have a problem with the "saveMissingTo" option: when it is set to "all", I expect that the missing keys will be save to all languages files, but only the current and fallback languages files update.
Am I missing something on how should it works?

This is my i18n init options:

`{
whitelist: ['it', 'en', 'es'],
fallbackLng: 'it',

ns: ['common'],
defaultNS: 'common',

debug: true,
saveMissing: true,
saveMissingTo: 'all',

interpolation: {
  escapeValue: false // not needed for react!!
},

backend: {
  loadPath: 'locales/{{lng}}/{{ns}}.json',
  addPath: 'locales/{{lng}}/{{ns}}.missing.json',
  jsonIndent: 2
}
}`

Thanks!

**Comment by jamuhl** [comment]
Save missing all does just send to all languages in the current resolve hierarchy. Eg. Not found for en- US it will send it to en-US, en and fallback. The cient can't know if there are other languages missing this key as it did not load nor used them to translate. 

We currently work on a saas tier complementing i18next to keep overview. We'rw close to beta. Check out locize.com. If interested we might onboard you into private beta.
