### ISSUE TITLE
Reset / reload current language

### ISSUE THREAD

**Issue by mroseboom** [i18next/i18next#707]
Hi, 

In our application we are using SignalR to "signal" the application to reset / reload the current language. A request to the backed will be called and the languages will be updated. We're using still v1.11.x and using the following code for this `i18next.sync.reload();`

I was trying to migrate to version 2, but the method from above isn't available anymore. Can you tell how i can archieve this with the v2 version of this plugin?

**Comment by jamuhl** [comment]
right now there is no such functionality but you can call for each namespace following fc:

```
      const lng = yourLanguage;
      const backendConnector = i18next.services.backendConnector;
      i18next.options.ns.forEach(ns => {
        backendConnector.read(lng, ns, 'read', null, null, (err, data) => {
          if (err) logger.warn(`loading namespace ${ns} for language ${lng} failed`, err);
          if (!err && data) logger.log(`loaded namespace ${ns} for language ${lng}`, data);

          backendConnector.loaded(`${lng}|${ns}`, err, data);
        });
      });
```

that will reload and merge the new data. Not sure why you need to reset the resources? if really needed we could add a reload function.

**Comment by mroseboom** [comment]
@jamuhl Thanks for your quick answer!

Within our application it will be possible to edit the values of the language keys (multiple languages). When the translation changes are saved, all the clients with the same language will receive a signal through SignalR to retrieve the "updated / new" translations.

I hope i've explained it clear enough.

**Comment by jamuhl** [comment]
if you need it fast you can use the above code temporary...will add a reloadResources function - but might take some days...as right now i'm rather hard on time.

**Comment by mroseboom** [comment]
@jamuhl Alright awesome, take your time ;)  For now i'll use the above code snippet.

**Comment by jamuhl** [comment]
i18next@3.2.0 adds `i18next.reloadResources()`, or optional with params `i18next.reloadResources(lngs, ns)`
