### ISSUE TITLE
Preserve HTML tags in translations

### ISSUE THREAD

**Issue by pavlosadovyi** [i18next/i18next#712]
Hi! I'm using i18next on Node.js backend with Express.js
Here is my config:
```js
var i18next = require('i18next');
var FilesystemBackend = require('i18next-node-fs-backend');
var middleware = require('i18next-express-middleware');

// Initialize multilanguage
i18next
  .use(middleware.LanguageDetector)
  .use(FilesystemBackend)
  .init({
    debug: false,
    fallbackLng: 'dev',
    fallbackNS: 'translation',
    interpolation: {
      escapeValue: false,
      //interpolateOptions: false -- I tried to set this also
    },
    backend: {
      loadPath: 'locales/{{lng}}/{{ns}}.json'
    }
  });
app.use(middleware.handle(i18next));
```

and my translations looks like:
```json
...
"LANDING_FEATURE3_DESCRIPTION": "It doesn't matter you have <b>PC</b>, <b>Mac</b> or <b>mobile device</b> it works everywhere.",
```

I trying to preserve html tags in my translation in SEO purpose. But I can't reach it. Am I doing something wrnog?

Thank you for help!

**Comment by jamuhl** [comment]
how do you translate your html templates? are you using pug (jade) with locals t function?

**Comment by pavlosadovyi** [comment]
Yes, you're right, I'm using t function in my .pug templates I also tried to do something like that:
```jade
p= t('KEY', {interpolation: {escape: false}})
```
with no result

**Comment by jamuhl** [comment]
hm...looks all ok to me...just turn debug = true -> do you get some error?

might be the backend path to resources is wrong, try:

`loadPath: __dirname + '/locales/{{lng}}/{{ns}}.json'`

**Comment by pavlosadovyi** [comment]
this is the out for debug:true

```json
i18next: initialized { debug: true,
  initImmediate: true,
  ns: [ 'translation' ],
  defaultNS: [ 'translation' ],
  fallbackLng: [ 'dev' ],
  fallbackNS: [ 'translation' ],
  whitelist: false,
  load: 'all',
  preload: false,
  keySeparator: '.',
  nsSeparator: ':',
  pluralSeparator: '_',
  contextSeparator: '_',
  saveMissing: false,
  saveMissingTo: 'fallback',
  missingKeyHandler: false,
  postProcess: false,
  returnNull: true,
  returnEmptyString: true,
  returnObjects: false,
  joinArrays: false,
  returnedObjectHandler: [Function: returnedObjectHandler],
  parseMissingKeyHandler: false,
  appendNamespaceToMissingKey: false,
  overloadTranslationOptionHandler: [Function: overloadTranslationOptionHandler],
  interpolation: { escapeValue: false },
  backend: { loadPath: 'locales/{{lng}}/{{ns}}.json' } }
```

**Comment by jamuhl** [comment]
ah gosh...know i got what you mean...sorry for my not understanding.

the translation stuff works - you just get not html for the `<b>`...

the escaping that i18next does is just a extra tier of security if you're using some framework that does not escape stuff.

you need to use unescaping in pug `tag!=something`!!!

```
p!= t('KEY', {interpolation: {escape: false}})
```

**Comment by pavlosadovyi** [comment]
Oh, so this pug "feature"? Thank you! It's working now

**Comment by mahaben** [comment]
@jamuhl  Please can you explain how to use the pug feature?
Thanks,

**Comment by jamuhl** [comment]
@mahaben what you need to know...pug is more or less used in views and mostly on node.js express:

https://github.com/i18next/i18next-express-middleware

has samples too

**Comment by dobeerman** [comment]
How to escape translation string in nodejs?
I've string like that `{ speed: "Max speed: {{speed}}km/h" }`
How to escape `/`? 

`i18next.t('speed', {val: '300', interpolation: { escape: false });`

doesn't works. It returns `Vax speed: 300km&#x2F;h`

**Comment by jamuhl** [comment]
do you get `Max speed: 300km&#x2F;h` in your view?

**Comment by dobeerman** [comment]
I send it via telegram bot to channel

**Comment by jamuhl** [comment]
try `i18next.t('speed', {speed: '300', interpolation: { escapeValue: false });`

**Comment by dobeerman** [comment]
`escapeValue: false` doesn't wors too (

**Comment by jamuhl** [comment]
https://www.i18next.com/interpolation.html#additional-options > escape is a function for custom escaping

not working...strange...rather sure than someone else does escaping...but will test later today when back at home

**Comment by jamuhl** [comment]
just was confused...we do not escape this...only inside the passed in variable `speed` (300) we would escape...not the text overall...so must be related to your code after using t function

**Comment by traikinhbac** [comment]
Make sure using set `html` or `text` (if you using jquery) on selector.
I just out this problem.

**Comment by vaibhavsawhney** [comment]
i18next.t('speed', {speed: '300', interpolation: { escapeValue: false }) worked for me as suggested by @jamuhl
