### ISSUE TITLE
Suggestion: escaping of prefix and suffix

### ISSUE THREAD

**Issue by huan086** [i18next/i18next#722]
There is no way to display `{{` or `}}` in the localized string. Changing the prefix and suffix might not be an option in some cases.

It would be good if we can provide callbacks to Interpolator to extract the tokens ourselves.

**Comment by jamuhl** [comment]
What is the usecase...seems like an edge case that could be solved by passing interpolation options to `t` function.

**Comment by huan086** [comment]
It opens up the possibility for .NET like interpolation using single brace, i.e.

```
{ key: "When you use {{var}}, it will output {var}" }

t("key", { var: 42 });
```

outputs

When you use {{var}}, it will output 42

**Comment by jamuhl** [comment]
i really don't understand it...why not change interpolation prefix/suffix to `{` / `}` if you need that for .net

**Comment by huan086** [comment]
But that would mean there's no way for my localized string to contain `{` or `}`. In order to allow them, I'll need them escaped.

In .NET, the template is `{}`, and escaped by doubling the brace `{{}}``

In JavaScript, the template is `${}` and escaped by putting a backslash `\${}` or `$\{}`.

There's currently no way to have any kind of escape sequence now

**Comment by jamuhl** [comment]
there is escapePrefix/Suffix

**Comment by jamuhl** [comment]
ah you mean you can't have `{` `}` in regular text? hm...then .net choosing { } for interpolation might be bad choice ;)

suggestion...don't interpolate and use a postProcessor to do customInterpolation

**Comment by huan086** [comment]
How to go about turning interpolation off?

**Comment by jamuhl** [comment]
there is no options...set prefix/suffix to something non existing like we do here for react-i18next interpolator component: https://github.com/i18next/react-i18next/blob/master/src/interpolate.js#L15

**Comment by jamuhl** [comment]
by the way...there is a translation management system built on top of i18next we launched a weeks days ago...you might give that a try http://locize.com

**Comment by huan086** [comment]
Looks like https://github.com/jquery/globalize/blob/master/doc/api/message/message-formatter.md is a better library as it supports escaping, ordinals and uses the latest CLDR data

**Comment by jamuhl** [comment]
well, no one forces you to use i18next...go ahead use message-formatter if you like the api more.
