### ISSUE TITLE
Is there a way to use a post-processor to access plural and context using an object format instead of using translation key?

### ISSUE THREAD

**Issue by cheton** [i18next/i18next#745]
As i18next has provided support for the <b>Key-based fallback</b> and the `returnObjects` option to return an object as value, may I know if there is a way to use a post-processor to access `plural` and `context` using an object format instead of using translation key? For example:
```json
{
  "en": {
    "translation": {
      "A friend": {
        "default": "A friend",
        "male": "A boyfriend",
        "female": "A girlfriend",
        "male_plural": "{{count}} boyfriends",
        "female_plural": "{{count}} girlfriends"
      }
    }
  }
}
```

Then I can do something like this:
```js
i18next.init({ ...options, returnObjects: true });

i18n.t('A friend', { plural: 'male', count: 10 });
// → "10 boyfriends"
i18n.t('A friend', { context: 'male' });
// → "A boyfriend"
i18n.t('A friend', { context: 'female' });
// → "A girlfriend"
```

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-intervalPlural-postProcessor should be able to do this...not yet tried in combination with context...but hopefully will work

**Comment by cheton** [comment]
I will try to add a postProcessor like this. Thanks!
