### ISSUE TITLE
unescape replacement fails if multiple unescaped keys are present

### ISSUE THREAD

**Issue by de-robat** [i18next/i18next#747]
Hello,
first of all - awesome library! I make use of i18next in several projects and never came across any issues (obv. until now :) ). So it's really stable and a lot of fun to work with.

Recently i discovered an issue if you have a interpolation string of the following type:

"{{- test1 }} {{- test2 }} {{- test3}}" and your are feeding it with a data object of the following type {test1: "", test2: "something", test3: ""} the interpolation process fails.

this is due to the fact, that the interpolation uses a regexp within a while loop to extract all the unescaped keys within the string but concurrently also manipulates the string in question. Therefore the regexp fails extracting the correct amounts of unescaped keys.

this problem has been solved within the case of escaped values by resetting the regexp internal lastIndex to zero everytime an replacement has been made

```javascript
while (match = this.regexp.exec(str)) {
      value = utils.getPath(data, match[1].trim());
      if (typeof value !== 'string') value = utils.makeString(value);
      if (!value) {
        this.logger.warn('missed to pass in variable ' + match[1] + ' for interpolating ' + str);
        value = '';
      }
      value = this.escapeValue ? regexSafe(utils.escape(value)) : regexSafe(value);
      str = str.replace(match[0], value);
      this.regexp.lastIndex = 0; // <<<<<<<<< this fixes the issue for escape values
    }
```

but this ist missing in the case of unescaped values
```javascript
while(match = this.regexpUnescape.exec(str)) {
      let value = utils.getPath(data, match[1].trim());
      str = str.replace(match[0], value);
    }
```

Probably messing with the regexp internals isn't such a good idea anyways and should be altered to a less intrusive way of string replacement. Due to the while loop leaving the regexp always at lastindex 0 when been fully run, i suggest to do the replacements on a temporary string and replacing the string directly after each loop. 

I opened this pull request https://github.com/i18next/i18next/pull/746 with the corresponding tests added and the suggested fix applied. I'd need this bugfix as soon as possible if that somehow is within your power right now, i'd really like to see an updated release in the npm registry.

Thank you very much!

**Comment by jamuhl** [comment]
By the way...you might give http://locize.com a try in future projects (using locize directly supports the future development of i18next)
