### ISSUE TITLE
Is it possible to lower/upper case an interpolated translation?

### ISSUE THREAD

**Issue by JoshMcCullough** [i18next/i18next#765]
For example:

```
{
    "user": "User",
    "user_not_found": "Sorry, we couldn't find that $t(user).lower()."
}
```

So, `user_not_found` would be translated to:

> Sorry, we couldn't find that user.

**Comment by JoshMcCullough** [comment]
Okay, thanks.

**Comment by decademoon** [comment]
There's no guarantee "user" will not be at the start of the sentence for some other language, so you shouldn't force-lowercase it for every translation.

**Comment by jamuhl** [comment]
@decademoon just as a hint: nowadays there are formatters you can use: https://www.i18next.com/translation-function/formatting#adding-custom-format-function that way it is possible to leave that option to the translator

**Comment by JoshMcCullough** [comment]
> There's no guarantee "user" will not be at the start of the sentence for some other language, so you shouldn't force-lowercase it for every translation.

@jamuhl's example is only lower-casing "User" for that one translation, `user_not_found`, not all translations.

**Comment by decademoon** [comment]
@JoshMcCullough What I mean is "User" will be lowercased _for all languages_, it needs to be done per-language because in some languages it may be at the start of the sentence and should be capitalized. jamuhl's suggestion to use the formatter is the modern solution to this.

**Comment by JoshMcCullough** [comment]
Yes, now I get it -- thanks.
