### ISSUE TITLE
Lazyload languages

### ISSUE THREAD

**Issue by Perde1989** [i18next/i18next#771]
Hello I have a modular project structure in my webapp. Means:

```
- index.html
-moduleA
-- lang
---- de.json
---- en.json
- moduleB
-- lang 
---- de.json
---- en.json
...
```

This means I dont have a main language json where all languages are stored in but I splitted them.
Can I lazy load languages? Will it work if I change the language? Have you example code?

**Comment by jamuhl** [comment]
i18next is built for that:

see namespaces: http://i18next.com/translate/namespace/

you can load lng and/or namespaces lazy:
- http://i18next.com/docs/api/#change-language
- http://i18next.com/docs/api/#load-namespaces

both provide a callback when loaded, or use the event hooks

hopefully that helps - feel free to ask more, we are here to help

**Comment by Perde1989** [comment]
Thanks for the response.

Maybe I should show some code.
```
                 // File: languageLoader.js
			function loadLanguage(langKey, loadPath, callback) {
                                // I use the backend plugin
				i18next.use(XHR)
					.init({
						debug : true,
						lng : langKey,
						fallbackLng : false,
						backend: {
							loadPath: loadPath
						}
					}, function() {
						callback();
					});
			}
```
                      
                        // moduleA.js
                        function start() {
                             loadLanguage('en', 'moduleA/lang/{{lng}}.json');
                        }

                        // moduleB.js
                        function start() {
                             loadLanguage('en', 'moduleB/lang/{{lng}}.json');
                        }

The problem is that only 1 language json file will be loaded. Can I use namespaces without changing my project structure?

**Comment by jamuhl** [comment]
you should init globally like:

```
{
  "debug": true,
  "lng": "en",
  "fallbackLng": "en",
  "ns": [
    "module1",
    "module2",
    "common"
  ],
  "defaultNS": "module1",
  "fallbackNS": "common",
  "backend": {
    "loadPath": "locales/{{lng}}/{{ns}}.json"
  }
}
```

if you don't want to load module1/2 resources on bootstrapping you app use loadNamespace and trigger that on loading you modules.

inside you module you can use `i18next.t(module1:key)` to get translation for that namespace or use http://i18next.com/docs/api/#get-fixed-t to get a t function fixed to that namesapce

**Comment by Perde1989** [comment]
Can I add namespaces on the fly?

**Comment by jamuhl** [comment]
yes....just use the `i18next.addNamespace` function

**Comment by Perde1989** [comment]
Hmm strange, I cant find the addNamespace method in the i18next source code? I use version 3.3.1.
My workaround is currently : i18next.options.ns.push('moduleA')

**Comment by jamuhl** [comment]
sorry it's loadNamespace

**Comment by Perde1989** [comment]
Okay I rewrote the code:

```
            // File: languageLoader.js
            function loadLanguage(langKey, namespace, callback) {
                // I use the backend plugin
                i18next.use(XHR)
                    .init({
                        debug : true,
                        ns : [],
                        lng : langKey,
                        fallbackLng : false,
                        backend: {
                            loadPath: '{{ns}}/lang/{{lng}}.json'
                        }
                    }, function() {
                        callback();
                    });

		          i18next.loadNamespaces(namespace, function() {
			        callback();
		         });
            }
```

In moduleA.js and moduleB.js nothing has changed and the project structure is still the same. In the console I see that it still only loads the first json language file. What could be my mistake?
```
                    // moduleA.js
                    function start() {
                         loadLanguage('en', 'moduleA');
                    }

                    // moduleB.js
                    function start() {
                         loadLanguage('en', 'moduleB');
                    }
```

**Comment by jamuhl** [comment]
// I use the backend plugin
                i18next.use(XHR)
                    .init({
                        debug : true,
                        ns : [],
                        lng : 'en',
                        fallbackLng : false,
                        backend: {
                            loadPath: '{{ns}}/lang/{{lng}}.json'
                        }
                    }, function() {
                        callback();
                    });

   
                   // moduleA.js
                    function start() {
                         i18next.loadNamespaces('moduleA', function() {
                    callback();
                 });

                    }

                    // moduleB.js
                    function start() {
                         i18next.loadNamespaces('moduleB', function() {
                    callback();
                 });

for users language detection you can use: https://github.com/i18next/i18next-browser-languageDetector

**Comment by Perde1989** [comment]
Okay, but did you removed the loadLanguage-method? Because it had the `callback` parameter.

**Comment by jamuhl** [comment]
EDIT: right...that's the point

**Comment by Perde1989** [comment]
Ok nice. Now my last problem is how to get my html updated. I am using the jquery plugin from the i18next ecosystem. I call $('blabla').localize() in the callback of the loadNamespaces-method. 
Obviously thats not enough. What do you recommend?

**Comment by jamuhl** [comment]
👍

**Comment by Perde1989** [comment]
Ok works fine! Thanks for the quick response and help :-)

**Comment by jamuhl** [comment]
you're welcome...if you encounter any other problem just contact me here or via email.

and checkout http://locize.com our localization service

**Comment by sesam** [comment]
I found a way to use react-i18next and enable webpack's code splitting by creating a minimal Backend that just uses `import().then(...)` and this seems fine, with just one noticed inconvenience that I need to have <React.Suspense> wrapping the component <LanguageSetter /> that triggers `i18n.changeLanguage` (this LanguageSetter is a workaround to enable some other unrelated things)

Approximate patch as seen in 
https://gist.github.com/sesam/c978f77c3ccf5629f5a753ef299b82a2
