### ISSUE TITLE
String formatting for Dates etc

### ISSUE THREAD

**Issue by LodewijkSioen** [i18next/i18next#774]
Given the following:
```
{
  "en": {
    "translation": {
      "test": "hello, it is now {{date}}"
    }
  }
}
```
This code will:
```
i18next.t('test',  { date: new Date()  });
```
produce `hello, it is now Fri Jul 08 2016 16:39:38 GMT+0200 (Romance (standaardtijd))`.

However, we would like to format our dates in a more user-friendly way. I've browsed the source, but I could not find a hook to do such a thing. How would I go around doing this?

**Comment by jamuhl** [comment]
you will need to pass in already formatted time (using moment.js or equal)....we might use Intl API in future to fill this https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl

**Comment by LodewijkSioen** [comment]
That's what we thought. The Intl API doesn't look like it would solve our requirements, though. We now transform our objects to stringyfied versions before passing them in i18next.

Can I make a suggestion as an alternative to the Intl API? How about this as resource:
```
"test": "hello, it is now {{date, dd/MM/yyyy}}"
```
and have an extension point where a function can be plugged in like this (pseudocode):
```
function(value, formatting){
    if(value instanceof Date){
        return moment(value).format(formatting);
    }
    return value.toString();
}
```

**Comment by jamuhl** [comment]
honestly....let me think....loving it. i always struggled with this problem, as i did not want to include moment.js or numeral.js or even less a own implementation for that. But your suggestion is just perfect...nice formatting but still no need to include something fix to i18next - and devs get enough power to extend to support formatting...

very well.....now i just need the time to add this ;)

**Comment by jamuhl** [comment]
so here's the plan:

we create something like post processor plugins with interface looking like:

```
{
  type: 'formatter',
  name: 'momentFormatter',
  format: function(value, format) {
    /* return manipulated value */
  },
  changeLanguage: function(lng) {
    /* change language on moment, evtl. load the resource file */
  }
}
```

in interpolator we check if matching to the defined patter https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L43 (like nest function below this one) and call all formatters appended by `i18next.use(myFormatter)`

**Comment by LodewijkSioen** [comment]
I'm glad that you like my suggestion. To be honest, this method is the way string interpolation with formatting is done in .net and some other languages. In .net we do `$"Today is {date:dd/MM/yyyy}"´ and other languages have a similar construct. Most languages use a colon (`:`) to separate the formatting, so I've edited my example above.

About your plugin interface: what is the `changeLanguage` method for? Shouldn't it be an overload for the `format(value, format)`-function?

**Comment by jamuhl** [comment]
changeLanguage is optional -> eg. when using moment you can set language on moment (evtl. one even need to load that language file for moment) - but you are right...we need to pass language on the format function itself too - as one could do that on the outer t function, too.

hm...loading that locales for eg. moment https://github.com/moment/moment/tree/develop/locale or numeral will be the biggest issue i think as that's an async operation in a sync function call....

**Comment by jamuhl** [comment]
so we might end in just let devs pass in a function on init like you initial suggested:

```
function(value, formatting, lng){
    if(value instanceof Date){
        return moment(value).format(formatting);
    }
    return value.toString();
}
```

So loading correct locales for moment stays in control of the developer integrating i18next to his project - which might be very different from project to project (using webpack, requirejs,...).

Solving this in form of plugins would only make sense if one could publish that for reuse - but basically i think this would only work for simple formatters not needing own locales files.

**Comment by LodewijkSioen** [comment]
I agree that just having a function would give more flexibility then a plugin.

**Comment by jamuhl** [comment]
in v3.4.0:

```
i18next.init({
  interpolation: {
    formatSeparator: ',',
    format: function(value, formatting, lng){
       if(value instanceof Date) return moment(value).format(formatting);
       return value.toString();
    }
  }
});
```

```
"test": "hello, it is now {{date, dd/MM/yyyy}}"
```

```
i18next.t('test',  { date: new Date()  }); // -> hello, it is now 13/07/2016
```

**Comment by LodewijkSioen** [comment]
Brilliant! Thanks a lot for this!

**Comment by jamuhl** [comment]
thank you for bringing up the topic again and for directing to the solution.

**Comment by msreddy09** [comment]
i18next.t('test',  { date: new Date()  });

is it possible to send the format(DD/MM/YYYY or MM/DD/YYYY ) from above line itself, instead of specify the format in json file.

**Comment by jamuhl** [comment]
Rather sure we could extend that to pass the format from:

https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L85

`value = handleFormat(match[1].trim(), data.format);`

here to:

https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L63

```
    const handleFormat = (key, format) => {
      if (key.indexOf(this.formatSeparator) < 0) return utils.getPath(data, key);

      const p = key.split(this.formatSeparator);
      const k = p.shift().trim();
      const f = p.join(this.formatSeparator).trim();

      return this.format(utils.getPath(data, k), format || f, lng);
    };
```

Or just pass the formatted string to interpolation? 

Not really sure why you like to pass the format from code - as it depend on language. Could you tell me what your use case is?

**Comment by msreddy09** [comment]
Appreciate your quick response :-)

I tried by passing the formatted string to interpolation, but I was unable to get the correct result.
I would like to pass the format as below.

`i18next.t('test', { date: new Date(), format: 'MM/DD/YY' });`
   
I just wanted to print different date formats on the page with same key, rather than maintain separate keys for every format. I am looking for the same in the context of numbers format too.

**Comment by jamuhl** [comment]
i would suggest doing something like:

`i18next.t('test', { date: i18next.options.format(new Date(), 'MM/DD/YY') });`

as providing: 

`i18next.t('test', { date: new Date(), format: 'MM/DD/YY', aNumber: 10.4566 });`

where do i know to which value the format belongs?

**Comment by msreddy09** [comment]
I am using **react-i18next**

I tried  as below. 

`t('ns:datekey', { datevalue: i18next.options.format(new Date(), 'MM/DD/YY') });`

`//json key is`

 `{
   "datekey": " Today is {{date}} "
}`

I also tried to as below
`t('ns:datekey', { datevalue: new Date(), format: 'MM/DD/YYYY' });`

`//json key is`
`{
   "datekey": " Today is {{date, format}} "
}`

// formater function as below
`if (value instanceof Date) return moment(value).format(format);`


Just I wanted to pass the format from view it self, instead of mention it in json file key.


or Suggest me the approach, how I can handle the scenario.

Thank you.

**Comment by jamuhl** [comment]
`{ "datekey": " Today is {{date}} " }`

your passed value need to  be date not dateValue `t('ns:datekey', { date: i18next.options.format(new Date(), 'MM/DD/YY') });`

**Comment by msreddy09** [comment]
Yeah, I used correct one, unfortunately mentioned wrong in previous comment. I used 'date' only.

But I noticed that `format` method  available in `i18next.options.interpolation` not in `i18next.options`
This was my mistake earlier. Now its working as expected. 
Thanks for your help.  :-)

**Comment by jamuhl** [comment]
@msreddy09 arghh...right...under interpolation -> might be a good idea to expose that on i18next.format when calling init...makes it easier to use

**Comment by msreddy09** [comment]
Yes, You are right.

**Comment by msreddy09** [comment]
I am getting the following error when I dint specify the format in json file. Is it necessary to mention format in json file key.

Code is a below: 

used `{ "datekey": " Today is {{date}} " }`  **instead of**  `{ "datekey": " Today is {{date, someformat}} " }`  
`{t('ns:datekey', { date: i18next.options.format(new Date(), 'MM/DD/YYYY') })}`


Error: 

 **Uncaught Error: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]…029%202017%2015%3A31%3A15%20GMT%2B0530%20(India%20Standard%20Time)&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (app.js:4736)
    at traverseAllChildrenImpl (app.js:26817)
    at traverseAllChildrenImpl (app.js:26766)
    at traverseAllChildren (app.js:26845)
    at Object.instantiateChildren (app.js:37406)
    at ReactDOMComponent._reconcilerInstantiateChildren (app.js:41499)
    at ReactDOMComponent.mountChildren (app.js:41532)
    at ReactDOMComponent._createInitialChildren (app.js:39247)
    at ReactDOMComponent.mountComponent (app.js:39066)
    at Object.mountComponent (app.js:7459)**

**Comment by jamuhl** [comment]
`{ "datekey": " Today is {{date}} " }` and `{t('ns:datekey', { date: i18next.options.interpolation.format(new Date(), 'MM/DD/YYYY') })}` should be correct if not providing format in translation
