### ISSUE TITLE
Interpolation formatting when format contains formatseparator

### ISSUE THREAD

**Issue by LodewijkSioen** [i18next/i18next#787]
See this line: https://github.com/i18next/i18next/commit/d3cc9ba8ab3a81d472c0ef3dca56392fae492f47#diff-e171f9b8b4e0f5df027bd8bd7b962f1bR1230

I use `:` as formatSeparator.
My translationfile contains: `key: "It is now {date:dd/MM/yyyy HH:mm}"`

This is the output for `i18next.t("key", new Date())`:
```
It is now 17/07/2016 10
```

As you can see, due to `string.split()` on formatseparator, everything after the second `:` is dropped.

**Comment by jamuhl** [comment]
ok will provide a patch asap

**Comment by jamuhl** [comment]
try i18next@3.4.1

**Comment by LodewijkSioen** [comment]
Again, brilliant. I'm now getting `It is now 17/07/2016 10:13`

:shipit:
