### ISSUE TITLE
ignore handlebars

### ISSUE THREAD

**Issue by DominicBoettger** [i18next/i18next#788]
I want to nest the handlebars helpers to be able to use different dateformats. Actually i know this handling from gettext and it works very well.

It always fails and the translate helper only returns test and removes the handlebars syntax. I tried a lot of different stuff like interpolationsettings and compiling handlebars in the translate helper again but i think my main pain point is that i18next removes then handlebars syntax and i am not able to find out how i can prevent the system from removing the handlebars.

translation file
````js
{
"mydate": "test {{dateformat survey.rentaldate 'll'}} {{translate 'hello}}"
}
````

handlebars helpers:
```js
                        handlebarsinstance.registerHelper('translate', function (translatestring) {
                            let translation = translate(translatestring);
                            console.log(translation);
                            return translation;
                        });
                        handlebarsinstance.registerHelper('dateformat', function (datestring, dateformat) {
                            if(!dateformat) {
                              dateformat = 'll';
                            }
                            let date = datestring;
                            if(typeof datestring !== 'object') {
                              date = new Date(datestring);
                            }
                            let momdate = moment(date).format(dateformat);
                            return 'test';
                        });
```

template:
```js
{{{translate "mydate"}}}
```

Is something like that possible or will i have to split up my translations into different strings?

Thanks
Best regards
Dominic

**Comment by jamuhl** [comment]
try http://i18next.com/translate/formatting/ which was added in v3.4.x

**Comment by DominicBoettger** [comment]
That helped a lot.... 

Thank you very much!
