### ISSUE TITLE
Empty string causes fallback

### ISSUE THREAD

**Issue by mblanchette** [i18next/i18next#80]
It appears having the value for a key as an empty string causes the fallback value to be returned instead.

Value returned is from the fallbackLng locale instead of the specified.
Data is loaded as JSON from resGetPath, containing key/values such as:
  "info":"",

Expected outcome is only for fallback to occur when the key is actually missing.
If the key has any value, it is expected to be returned (including for empty string).

**Comment by isld** [comment]
What is your opinion about adding an option to init() for enabling/disabling fallback to key if it exists in the translation, but corresponds to an empty string?

In my case this "feature" is more like a bug - I'm using i18next-parse to extract all strings to JSON and i18next-gettext-convert to convert between JSON and .po files and in my case empty string means a missing translation in which case I need a fallback to key.

If nobody has the time to deal with that but you like the idea, I'll try to do it and open a PR. Any suggestions are more than welcome.

**Comment by jamuhl** [comment]
did you try setting: `returnEmptyString: false` on init? that should do the trick as it does not accept empty string as valid translation.

**Comment by isld** [comment]
Crap. I've slept over this one in the docs. Sorry for the disturbance, it works like a charm.

**Comment by jamuhl** [comment]
@isld no problem...there are tons of options and ways to use i18next - easy to miss one.
