### ISSUE TITLE
Inconsistent documentation regarding nesting

### ISSUE THREAD

**Issue by latenssi** [i18next/i18next#801]
In http://i18next.com/docs/jsons nesting is described to work with braces (wrong way):

`"keyNesting": "reuse $t{keyDeep.inner}"`

and in http://i18next.com/translate/nesting/ with brackets (correct way):

`"nesting1": "1 $t(nesting2)"`

**Comment by jamuhl** [comment]
second is correct - will need to fix docu asap. thanks for finding.

**Comment by jamuhl** [comment]
corrected...thanks again
