### ISSUE TITLE
Fetching the values without interpolation

### ISSUE THREAD

**Issue by AgronKabashi** [i18next/i18next#802]
Is there a way to fetch the values without them being interpolated or the placeholders deleted?

For instance, I have the following:

```
{
  ...
  "range": "[{{minValue}}..{{maxValue}}]"
  ...
}
```

The localization is loaded during application boot with `i18next.t('localizationfile')`. This will attempt to inject values into the placeholders but since I'm not passing in anything the placeholders will be removed entirely.

This means that when I want to use this string during runtime to set the values:
```
const rangeLabel = i18next.t(localization.range, {
  minValue: this.model.get('minValue'),
  maxValue: this.model.get('maxValue')
});
```

it won't work since localization.range would be `[..]` at that point.

I could use a different prefix/suffix but that would lead to inconsistency so I'd like to avoid that.

**Comment by jamuhl** [comment]
just added a test case: https://github.com/i18next/i18next/blob/master/test/translator/translator.translate.returnObject.spec.js#L58 not encounter that issue

not sure why this should not work...the value in resources do not get overwritten:
https://github.com/i18next/i18next/blob/master/src/Translator.js#L84

could you cross check this again...can't reproduce this.

**Comment by AgronKabashi** [comment]
Here's an example:

```
i18next.init({
  lng: "en",
  returnObjects: true,
  interpolation: {
    prefix: "{{",
    suffix: "}}"
  },
  resources: {
    en: {
      translation: {
        stream: {
          fpsRange: "[{{minValue}}..{{maxValue}}] fps"
        }
      }
    }
  },
  $
}, localizationLoaded); 

function localizationLoaded () {
  // This will remove all placeholders since we're calling translate
  var lang = i18next.t("stream");
  
  // Since the placeholders are no longer inside fpsRange key the following
  // will simply output [..] fps
  console.log(i18next.t(lang.fpsRange, {
    minValue: 0,
    maxValue: 30
  }));
}
```
https://plnkr.co/edit/aiv5Q4QxQOPBY8KqkmPt?p=preview

We load our feature specific localization files during boot and then in some instances we want to use a key as a template for dynamically building the translation (like above). The problem is that the placeholders are removed when we run i18next.t().

**Comment by jamuhl** [comment]
why you get `var lang = i18next.t("stream")` at all - you don't use it.

you can't pass lang.fpsRange to t function `(i18next.t(lang.fpsRange, ...` that's not a key - that's a already translated value...

why not just:
```
console.log(i18next.t(lang.stream.fpsRange, {
    minValue: 0,
    maxValue: 30
  }));
```

**Comment by AgronKabashi** [comment]
First of all, thanks for taking your time looking into this.

That was just a simple test case to illustrate our little problem. Here's how we use i18next:

```
// Fetches the translations for the stream features in the current language
const localization = i18next.t('streamLocalization');

export const SpecDefinition = {
  groups: [{
    label: localization.stream, 
    components: [{
      label: localization.resolution, 
      type: 'select'
    },
    {
      label: localization.compression,
      type: 'input'
    },
    {
      label: localization.mirror,
      type: 'toggle'
    },
    {
      label: localization.fps,
      type: 'input',
      
      //Here's our special use case, we wan't to keep the placeholders if possible since they will be
      //replaced much later on when we have access to the data. 
      unitLabel: localization.fpsRate 
    }]
  ...
  }]
};
```

We have to use i18next.t() to fetch the whole stream group so we can assign the translations to labels, but in that one particular case we don't want the placeholders to be translated/removed. So my question is if it is possible to prevent that by using escaping the value (\{ didn't work), passing an argument to .t() without having to use custom suffix/prefix or some other way to extract the untranslated values?

**Comment by jamuhl** [comment]
ok i see, only option is to call:

```
// Fetches the translations for the stream features in the current language
const localization = i18next.t('streamLocalization', { interpolation: { suffix: '###', prefix: '### } );
```

there is right now no option to not do the interpolation. but you can add a PR if you like...

**Comment by AgronKabashi** [comment]
I suppose that's the only way for now, thanks for your input!

**Comment by jeyashree-n** [comment]
If it is possible to add two value to the prefix. I am have '%{' and '% {' as prefix. 

````
interpolation: {
    prefix: "%{",
    suffix: "}"
  },
````

**Comment by jamuhl** [comment]
@jeyashree-n no that is not possible and won't be added...

**Comment by jeyashree-n** [comment]
@jamuhl  Is there any way to avoid space in prefix ?
