### ISSUE TITLE
i18next appends the default translation namespace to my namespaces

### ISSUE THREAD

**Issue by cerealBoxx** [i18next/i18next#804]
This is my configuration:

`return instance.setup({
    backend: {
      loadPath: 'assets/locales/{{lng}}/{{ns}}.json',
    },
    detectFromHeaders: false,
    lng: 'bg',
    fallbackLng: 'bg',
    ns: ['app', 'dp', 'management'],
    defaultNS: 'app',
    fallbackNS:'app',
    attributes: ['t', 'i18n'],
    useCookie: false,
    getAsync: false,
    debug: false
  });`

I am using aurelia i18n which is a wrapper around i18next. For some reason when I call the setLanguage function which in turn calls changeLanguage() in i18next, i18next appends the default translation namespace to my namespaces array and makes a call to the backend which results in error. Is there a way I can disable this behavior?

**Comment by jamuhl** [comment]
which default namespace? `translation` ?

if so this is not done by changeLanguage i think...look here https://github.com/i18next/i18next/blob/master/src/i18next.js#L185

seems more that your options do not get passed to i18next.init....

and detection options should be in own object detection

```
{
    detection: options
}
```
