### ISSUE TITLE
Translation locale

### ISSUE THREAD

**Issue by dbendy** [i18next/i18next#806]
I am using the latest version of `i18next` in my `express` app, without using the express middleware.  Is there a function within `i18next` that I can use that will take in a locale as an argument and return the actual locale, based on the available translation resources, that `i18next` will use?  For example, if my translation resources have `es` and I pass in `es-MX` to said function, it will return `es`.

**Comment by jamuhl** [comment]
There is no such function, but you can use:

`i18next.languages` will give you an array of the languages i18next will use for ordered lookup of translations.

`i18next.services.resourceStore.data` will be the currently loaded data. Where you can look up `if (i18next.services.resourceStore.data[i18next.languages[0]]) { ... }`
