### ISSUE TITLE
Combining initialization with resources and dynamic loading

### ISSUE THREAD

**Issue by danielwagner** [i18next/i18next#807]
I would like to pre-configure i18next with the translations for my application's default language to avoid the additional request at startup while still allowing translations for other languages to be loaded using the XHR backend. This is my configuration:

```javascript
i18next
  .use(i18nextXHRBackend)
  .init({
    debug: true,
    lng: 'de',
    fallbackLng: 'de',
    resources: {
      de: {
        translation: {
          //...
        },
      }
    }
  });
```

When a user selects a different language, this code is called:

```javascript
i18n.changeLanguage('en');
```

but this has no effect since i18n.loadResources does nothing if this.options.resources is truthy. Is there some other way to achieve my goal?

**Comment by jamuhl** [comment]
Use i18next.addResourceBundle() to add them. Sorrry on holiday and on phone. So just a short reply. 

Von meinem iPhone gesendet

**Comment by danielwagner** [comment]
Works great, thanks!
