### ISSUE TITLE
No $(document).i18next() or $(document).i18n() function available

### ISSUE THREAD

**Issue by bhaskerchari** [i18next/i18next#808]
Hi @jamuhl,

Can you please help in getting this resolved?

After upgrading to the latest i18next 3.4.1 version I don't see any method where I can localize on a particular DOM element or on whole document.

Basically this seems to be missing in recent versions.

Working fiddle with older version https://jsfiddle.net/bhaskerchari/xo78j2of/4/

Not working with latest i18next: https://jsfiddle.net/bhaskerchari/oe7b0Lwb/2/

So I have mainly below two questions:

1) How we can localize only specific to few DOM elements using latest versions?
     ex: $("#divId").i18next() or $("document").i18next()
2) Is there no support available for data-i18n and data-i18n-options in latest versions, the way it use to work in earlier versions with out using any wrapper?

Please refer to the fiddle 1: https://jsfiddle.net/bhaskerchari/xo78j2of/4/ where it used to work without using any wrapper on top of i18next.

Thanks In Advance.

**Comment by jamuhl** [comment]
http://i18next.com/docs/ecosystem/ Have a look for jquery plugin or use i18nextify. Or even better get a complete solution using http://locize.com
