### ISSUE TITLE
$t() gets appended when we don't pass any option object

### ISSUE THREAD

**Issue by siddharthpalgit** [i18next/i18next#811]
Hi,

Consider my resource as 
{
	"dashboard": "Dashboard",
	"key": "Delete $t({{entity}})"
}
i18next.t("key",{entity :"dashboard"}) // outputs Delete Dashboard

i18next.t("key",{entity :"report"}) // outputs Delete report

But let's say I want only "Delete" to be printed without any suffix then I am not sending any option but it is resulting me like **"Delete $t()"** with console warning **i18next::interpolator: missed to pass in variable entity for interpolating Delete $t({{entity}})**
i18next.t("key") // outputs Delete $t() 

Note: Basically I want to reuse my "key" by passing dynamic values and if I don't pass any value then it should give as empty string("Delete").

Thanks & Regards
Siddharth Pal

**Comment by jamuhl** [comment]
it was never meant to use interpolation inside nesting...even i think while it looks cool on paper it makes it harder to translate in the end.

why not write the stuff out:

```
{
   "delete.dashboard": "Delete Dashboard",
   "delete.report": "Delete Report",
   "delete": "Delete",
}
```

and access it like: `t([`delete.${mySection}`, 'delete'])`
