### ISSUE TITLE
Rejecting non-whitelisted language code issue

### ISSUE THREAD

**Issue by TitaneBoy** [i18next/i18next#813]
Hi @jamuhl . I hope you are going fine.

I found a strange issue while using your module. For a reason I don't understand (may be because of updates), I was not able to load a single resource in the backend. 

The language resource code is 'zh-HANS'. In the backend, this is what I loaded (with other languages of course). This is my initialisation code:

```
var i18nextOptions = {debug:true, preload: ['es','fr', 'zh-HANS'], fallbackLng:false, whitelist:['fr', 'es', 'zh-HANS'], load:'currentOnly', saveMissingTo:'current',
                      saveMissing:true, ns:'My_Web_Server', defaultNS:'My_Web_Server', nsSeparator: false, keySeparator: false,
                      backend:{loadPath: 'language/static/{{lng}}/{{ns}}.json', addPath: 'language/static/{{lng}}/{{ns}}.missing.json', jsonIndent: 2}};
```

Well ...This worked for me a while ago. But one day, I wanted to test again my site and I could not load the 'zh-HANS' translations. After activating the debug option, I got this message:

**i18next::languageUtils: rejecting non-whitelisted language code: zh-Hans**

But before, It worked like a charm and I didn't change a bite of code.
So I tried to change in my preload and whitelist options 'zh-HANS' to 'zh-Hans' and this works again and I can now load this resource. But in the front-end (Html page), the resource is loaded only if I use 'zh-HANS' in preload and whitelist option (Obviously, I had a previous version of i18next in the front-end). The version of my i18next module in the backend is up to date (**3.4.1**) and when I updated the i18next files in the front-end to the last version (3.4.1), I got exactly the same issue. 

So I was wondering if there is an issue with last versions of this module or if it's a new behavior that I don't know. Why with **'HANS'** (in big capital) it doesn't work but with **'Hans'**, it works ? Note that in my directory, the name of the resource directory is 'zh-HANS'.

Thank you for your answer.

**Comment by jamuhl** [comment]
We changed to me more flexible in using languages: http://www.iana.org/assignments/language-tags/language-tags.xhtml not only supporting language - region but also script languages.

So correct is `zh-Hans`, `zh-Hans-CN`, ...

I could change whitelist code to support ignoring case - but even then the backend won't load it as it still uses `zh-Hans` and not `zh-HANS` to load the file from server.

Best would be to rename your resource directory to `zh-Hans`.

**Comment by TitaneBoy** [comment]
Ok...I understand.. 
Thank you for your answer..
