### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by minimok** [i18next/i18next#815]
Any chance of seeing an example of how to use this in an HTML page where React, Knockout, Meteor, Polymer etc are NOT present? i.e. vanilla javascript. 

Only solution I found is to map all my elements to i18n keys e.g.
`{elementId: 'myPageTitle', textValue: 'ns.common:pageTitleText'}`
`{elementId: 'myHelpLink', textValue: 'ns.common:helpLinkText', hrefTitle: 'ns.common:helpLinkTitle'}`

On every render, I can get the element by id, match it to the correct text, and set its textContent, title, placeholder values with javascript. e.g.
`document.getElementById('pageTitle').textContent = map['myPageTitle'].textValue`

But in a large app the code to do this will be larger than the main application itself :-)

I suspect you may have a better method? Just not documented yet?

**Comment by jamuhl** [comment]
no the only thing you could do is rebuild the jquery-i18next functionality in html5 or use i18nextify https://github.com/i18next/i18nextify

**Comment by minimok** [comment]
Aha. OK. That's good to know. I was looking everywhere for such an example. No wonder i couldn't find one :-) I think porting the jquery functionality route looks like the way to go. Thx!

**Comment by jamuhl** [comment]
Hm if you do so you might consider sharing that to the i18next ecosystem!!?!? Would help others...
