### ISSUE TITLE
Some function (like 'on' and setters) don't return this and are not chainable

### ISSUE THREAD

**Issue by emileber** [i18next/i18next#816]
i18next is extensively using chaining in its example:

``` javascript
var i18n = i18next
  .use(...)
  .use(...)
  .init(...);
```

But a lot of other function who could return `this` don't return anything. 

This example will make `i18n` undefined:

``` javascript
var i18n = i18next
  .use(...)
  .use(...)
  .init(...)
  .on('languageChanged' function(lng) {...});
```

Setters and event related functions could be made to return `this` without any impact, but I would like your opinion before taking the time to make a pull request.

**Comment by emileber** [comment]
This issue is related to #542

**Comment by jamuhl** [comment]
Feel free to provide a PR...nothing against making it more comfortable ;)

**Comment by jamuhl** [comment]
closing for now due inactivity - still open for PR.
