### ISSUE TITLE
Better documentation needed

### ISSUE THREAD

**Issue by mrtnbroder** [i18next/i18next#817]
The documentation for all the options i18next allows is really bad.

They are telling us a default value and a short description, but HOW do I replace default values with other settings? What values do they expect?

For example the description for `resources`

`resources  undefined   resources to initialize with`

Okay... but what does resources expect from me? an array? a key-value map? what would be the format? what other options do I have?

I have to google now for my answers, it would be great if this can be improved with example code.

**Comment by jamuhl** [comment]
most values state what they expect - agree resources are not documented well.

it's an object:

```
{
  lng: {
    namespace: {
      key: 'value
    }
  }
}
```

Feel free to contribute to the documentation: https://github.com/i18next/i18next.com
