### ISSUE TITLE
i18next looks not working with Internet Explorer

### ISSUE THREAD

**Issue by TitaneBoy** [i18next/i18next#818]
Hi There. I think that i18next module looks to have an issue with Internet Explorer web browser.
My code works very fine with Firefox and Chrome, but crashes my application when using it with Internet Explorer.

This is the callback context I got:

```
TypeError: Cannot read property 'indexOf' of undefined
    at LanguageUtil.getLanguagePartFromCode (c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\i18next\dist\commonjs\LanguageUtils.js:30:13)
    at I18n.dir (c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\i18next\dist\commonjs\i18next.js:364:56)
    at options (c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\i18next-express-middleware\lib\index.js:69:40)
    at Layer.handle [as handle_request] (c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\express\lib\router\index.js:312:13)
    at c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\express\lib\router\index.js:330:12)
    at next (c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\express\lib\router\index.js:271:10)
    at urlencodedParser (c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\body-parser\lib\types\urlencoded.js:91:7)
    at Layer.handle [as handle_request] (c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\express\lib\router\index.js:312:13)
    at c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\express\lib\router\index.js:330:12)
    at next (c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\express\lib\router\index.js:271:10)
    at jsonParser (c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\body-parser\lib\types\json.js:103:7)
    at Layer.handle [as handle_request] (c:\Personal_Data\Project_Setup\Node.js\Express\ProjectDemoApp\node_modules\express\lib\router\layer.js:95:5) 
```

Here are the versions I am currently using:

**Versions:
-Internet Explorer 10
-i18next: 3.4.1
-i18next-express-middleware: 1.0.1
-i18next-node-fs-backend: 0.1.2
-i18next-xhr-backend: 1.1.0
-Express: 4.14.0
-node: 6.4.0**

Can you help me please with this issue ?

Thank you

**Comment by jamuhl** [comment]
to you call i18next.dir() before having a language set? That's the only way i see this could go wrong....

https://github.com/i18next/i18next/blob/master/src/i18next.js#L261
https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L15

might need to add some check there if code is defined...but that still not explains why it runs on chrome and not on IE...could you set breakpoints and check if code is set?

**Comment by TitaneBoy** [comment]
Actually, I don't have any manual call (i.e writted by myself) to i18next.dir() in my code.

After debugging as you suggested, the "code" parameter in the LanguageUtils.js file:

`getLanguagePartFromCode(code)`
is undefined

The call to:
`function dir(lng)`
in the i18next.js file has the "lng" parameter set to **false**. Then in the next line:
`if (!lng) lng = this.language;`
the **lng** variable is set to **undefined** , which means that **this.language** is "undefined"

**Comment by TitaneBoy** [comment]
With chrome and Firefox, the code and lng variables are set correctly ("fr" in my case).

**Comment by TitaneBoy** [comment]
When I'm breaking in i18next.js file in the `function changeLanguage(lng, callback)` function at this line:
`if (!lng && this.services.languageDetector) lng = this.services.languageDetector.detect();`
the call to `this.services.languageDetector.detect()` returns **undefined**. This is why the `this.language` variable are undefined. But I don't understand why `this.services.languageDetector.detect()` returns undefined in Internet Explorer.

**Comment by TitaneBoy** [comment]
When i'm breaking in LanguageDetector.js file, at the beginning of the function `detect(req, res, detectionOrder)`, the line `if (arguments.length < 2) return;` makes me go out of this function (because arguments.length is equal to **0**.

So I guess that the main problem here is that the variable "lng" or "language" variable are somehow undefined. Something is telling me that with Internet Explorer, when we are changing the language in client side (with `i18next.changeLanguage`), i18next (maybe in client side) is not selling correctly the "language" value to the i18next backend side. But maybe I am wrong somewhere in my analysis.

**Comment by jamuhl** [comment]
i18next (maybe in client side) is not selling correctly the "language" value to the i18next backend side?!? what you mean by that? there is no connection between serverside and clientside (or at least only if you use cookie and specific languageDetectors both on client and express)...

but looking through the callstack of your error i get to this line:
https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L46

=> i will change the code in i18next to return rtl for undefined lng

but you still need to figure out why you get no proper language on express: do you use the languageDetector from middleware https://github.com/i18next/i18next-express-middleware#language-detection ?

**Comment by TitaneBoy** [comment]
I think you are right about communication between client-side and server-side...I thought there were some communication because of the issue on Internet Explorer and not in other web browsers.
But I am not using cookies for languages or other specific languageDetectors.

I am using the languageDetector you provided in your middleware, the same as https://github.com/i18next/i18next-express-middleware#language-detection 

This is my configuration:

```
var i18next = require('i18next');
var i18nextMiddleware = require('i18next-express-middleware');
var i18nextBackend = require('i18next-node-fs-backend');
var i18nextOptions = {debug:false, preload: ['es','fr', 'zh-Hans'], fallbackLng:false, whitelist:['fr', 'es', 'zh-Hans'], load:'currentOnly', saveMissingTo:'current',
                      saveMissing:true, ns:'My_Web_Server', defaultNS:'My_Web_Server', nsSeparator: false, keySeparator: false,
                      backend:{loadPath: 'language/static/{{lng}}/{{ns}}.json', addPath: 'language/static/{{lng}}/{{ns}}.missing.json', jsonIndent: 2}};

i18next
  .use(i18nextMiddleware.LanguageDetector)
  .use(i18nextBackend)
  .init(i18nextOptions);

var app = express();
app.use(i18nextMiddleware.handle(i18next, {removeLngFromUrl: false}));
```

**Comment by TitaneBoy** [comment]
By debugging, I found this:

https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L19

You are doing `var lng = req.lng;`
which initialize lng variable to **undefined** because req.lng value is undefined.
Then after, in the next line:
https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L20
we call : `i18next.services.languageDetector.detect(req, res);`

Then in this function, at:
https://github.com/i18next/i18next-express-middleware/blob/master/src/LanguageDetector.js#L59
with detectorName as "header", I have "detections" value set to "fr-CA" (it's an array of 1 element).  But with Firefox and Chrome, I have at the same point an array of 3 elements: ["fr", "en-US", "en"].

In the case of Internet Explorer, the "fr-CA" is not in my whitelist option. But with Firefox and Chrome, "fr" is in my whitelist option.

And then after, at the line:
https://github.com/i18next/i18next-express-middleware/blob/master/src/LanguageDetector.js#L71
the function returns false because of `this.allOptions.fallbackLng` which is set to false, which later is making the code crash because of this line:
https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L16

My question is: Why i18next is looking for languages in request headers ? Is it because of the following initialization ? `i18next
  .use(i18nextMiddleware.LanguageDetector)`

If it is, can I remove the languageDetector ? Because actually, I manually force the language I want to use...and I don't need to get the browser language

**Comment by TitaneBoy** [comment]
As you can see in my i18next option configuration, the fallbacklng option is set to false. It explains why lng is set to "false" in the `function dir(lng)`call

In previous discussion, you said me to put fallbacklng option to false if I wanted that i18next fallback to original string (i.e keys) if it doesn't find a string traduction. 

But I still don't understand why i18next is looking for languages in request "headers". When the code crashes, I don't have made any manual call to i18next module. Something in background is firing i18next to be executed.

**Comment by jamuhl** [comment]
the language detector offers following options to detect language and options:
https://github.com/i18next/i18next-express-middleware#detector-options

if you do not need the detection you can add a middleware before i18next.handle adding lng to req => `req.lng`

so still the only thing i need to fix is asserting the call with undefined returns save from `dir` function

**Comment by jamuhl** [comment]
And what causes the crash is the detection gets triggered on all requests -> every request is handled for its own - to avoid race conditions in language changes...

**Comment by TitaneBoy** [comment]
I am not sure about what you suggested to me to do if I do not need the detection.

Do you want me to do something like:

```
i18next.
  .use(function(req, res, next){
       req.lng = 'en';
       next();
   })
  .use(i18nextMiddleware.LanguageDetector)
  .use(i18nextBackend)
  .init(i18nextOptions);
```

?

**Comment by jamuhl** [comment]
If it is, can I remove the languageDetector ? Because actually, I manually force the language I want to use...and I don't need to get the browser language

=> you can set it manually on req.lng

so yes that what you did is correct, just replace the `en` with however you load users language

**Comment by TitaneBoy** [comment]
This is what I've done in my i18next initialization:

```
i18next
  .use(function(req, res, next){
    req.lng = 'fr';
    next();
  })
  .use(i18nextBackend)
  .init(i18nextOptions);
```

but I got my application crashed for the same reasons... Looks like req.lng is not initialized and is undefined, even with the new middleware as described previously

**Comment by jamuhl** [comment]
ah now i see...no

```
...
var app = express();
app.use(function(req, res, next){
  req.lng = 'fr';
  next();
});
app.use(i18nextMiddleware.handle(i18next, {removeLngFromUrl: false}));
```

the middleware is for express not i18next

**Comment by TitaneBoy** [comment]
Great...Thank you...It looks to work well...:-)  Thank you again for your support...

But something deep inside me is telling me that this "patch" looks not so "clean". Do you think there is another way to resolve this issue without adding this middleware to express ?

**Comment by jamuhl** [comment]
more proper would be to create a custom detector...https://github.com/i18next/i18next-express-middleware#adding-own-detection-functionality but i guess you load the language async from db - so to not load it every time an option would be storing it in session and use the detector again with settings for session https://github.com/i18next/i18next-express-middleware#detector-options

**Comment by TitaneBoy** [comment]
Well, in the backend, I receive requests with some datas, which language value is in. In the front-end, the user can choose itself in which language he want to display web page.

**Comment by jamuhl** [comment]
simplest option might be to set clientside language detector to save in cookie and backend to read from cookie

**Comment by jamuhl** [comment]
which might be what you had on start - but cause of the dir issue failed...so let me fix that and then you can check again...meanwhile you got a working workaround

**Comment by TitaneBoy** [comment]
Ok..I will wait for your fix and will test it after.. Meanwhile, I will think about the custom detector solution or maybe something else will rise in my mind.

Thank you :-)

**Comment by jamuhl** [comment]
published i18next@3.4.2 which should not crash

**Comment by TitaneBoy** [comment]
Hi @jamuhl. I've tried your new 3.4.2 i18next version. I've tried it without the "patch" in express we have talked previously. It unfortunetly crashes the application because when i18next-express-middleware executes this:
https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L52
req.lng still undefined. Then later, in this line:
https://github.com/i18next/i18next/blob/00c5bc76dafe1635e26e6b0963c8c04a66593ff7/i18next.js#L2004
 the application crashes because the variable "lngs" is undefined.

**Comment by jamuhl** [comment]
but that's finally an issue when lng is not set by you via middleware req.lng or language detector is unable to locate a lng.

Could extend the express-middleware to not call `loadLanguages` if not detected any lng - that will bullet proof it - but not sure if that is the thing you want? Hopefully it will return key as nothing was found and not break into more errors ;)

**Comment by jamuhl** [comment]
try i18next-express-middleware@1.0.2

**Comment by TitaneBoy** [comment]
:-) It looks a great idea..I've tried it right now and it looks to work fine, and without any patch...The perfect world :-)

**Comment by TitaneBoy** [comment]
Perfect !! Works fine...:-)  Thank you very much for your great support :-D

**Comment by jamuhl** [comment]
you're welcome
