### ISSUE TITLE
Lost support for joined arrays

### ISSUE THREAD

**Issue by ugonnanwosu** [i18next/i18next#821]
http://i18next.com/translate/array/

```json
{
  "en": {
    "arrayJoin": [
      "line1",
      "line2",
      "line3"
    ],
  }
}
```

```javascript
i18next.t('arrayJoin'); // output: 'undefined'
```

**Comment by jamuhl** [comment]
`i18next.t('arrayJoin'); // output: 'line1+line2+line3' (by option joinArray: "+")`

for me...what browser do you use?

**Comment by ugonnanwosu** [comment]
I'm seeing undefined in Chrome, Firefox and Safari on OSX using v3.4.3
http://codepen.io/anon/pen/dpWNBK?editors=1010#0

**Comment by jamuhl** [comment]
you need to specify how to join arrays: init option `joinArrays: ','`

http://i18next.com/translate/array/ scroll down and check the init options
