### ISSUE TITLE
keySeparator option

### ISSUE THREAD

**Issue by scherler** [i18next/i18next#825]
Hi all,

I am currently working on the integration of this library into jenkinsci blueocean-plugin. One specification is that I need to support the currently existing locale file like e.g.
https://github.com/jenkinsci/ssh-slaves-plugin/blob/master/src/main/resources/hudson/plugins/sshslaves/Messages.properties

You will find keys such as:

```
SSHLauncher.DescriptorDisplayName=Launch slave agents via SSH
```

This properties files are getting transformed from REST service to 

```
{
  status: "ok",
  data: {
    // ...
    SSHLauncher.DescriptorDisplayName: "Launch slave agents on Unix machines via SSH",
    // ...
  }
}
```

I tried with the following init options:

```
/**
 * configure the backend for our locale
 */
const xhr = new XHR(null, {
  loadPath: '/jenkins/i18n/resourceBundle?language=##lng##&baseName=##ns##',
  allowMultiLoading: false,
  parse: function (data) {
    const response = JSON.parse(data);
    return response.data;
  },
});

i18n
  .use(xhr)
  .use(lngDetector)
  .init({
    fallbackLng: 'en',
    // have a common namespace used around the full app
    ns: ['org.jenkinsci.plugins.blueocean.web.Messages', 'hudson.plugins.sshslaves.Messages'],
    defaultNS: 'org.jenkinsci.plugins.blueocean.web.Messages',
    preload: ['en', 'de'],
    keySeparator: '#',
    debug: true,
    load: 'all',
    interpolation: {
      prefix: '##',
      suffix: '##',
      escapeValue: false // not needed for react!!
    },

  });
```

I thought changing the ```keySeparator``` to ```#``` would allow me to access keys like ```SSHLauncher.DescriptorDisplayName``` however all keys with DOT are not found. All keys without the DOT are resolved as expected. 

Did I misunderstood the documentation or what do I need to do to support keys with a DOT?

**Comment by jamuhl** [comment]
ciau thorsten...try setting keySeparator and nsSeparator to `false`, eg. http://i18next.com/translate/keyBasedFallback/

**Comment by scherler** [comment]
hi @jamuhl hope you are well. Thank you for you speedy answer, will try that now!

**Comment by jamuhl** [comment]
all green ;) just ping me if still not working...not sure should have worked with you config too...

**Comment by scherler** [comment]
@jamuhl good to hear. greetings to everyone that is still around there. ;)

![screenshot from 2016-10-13 16-38-59](https://cloud.githubusercontent.com/assets/596701/19353401/9ae7e63c-9163-11e6-9a5b-2b3c29c80bcb.png)

As you hopefully can see from the screenshot, the resources will be read correctly from the backend connector but then reported as missing key. See as well that I added both attributes as you suggested.

What is the best place to debug the problem?

**Comment by jamuhl** [comment]
missing key is searched on: org.jenkinsci.plugins... but actually is inside hudson.plugins....

you access that key from wrong namespace file

**Comment by jamuhl** [comment]
a) append namespace on accessing that key (without setting nsSeparator to false)
b) fallback to that namespace
c) create a i18next.fixedT(null, 'hudson.plugins...') and use that to access keys inside hudson ns file

**Comment by scherler** [comment]
@jamuhl awesome catch. You are right 

```
const namespaces = ['org.jenkinsci.plugins.blueocean.web.Messages', 'hudson.plugins.sshslaves.Messages'];
    const routeProps = {
        path: "/",
        component: translate(namespaces, { wait: true })(App)
    };
```
on my component works like a charm as well with the ```keySeparator: '#',```

Thank you very much for the quick help and sorry for the noise.

**Comment by jamuhl** [comment]
you're welcome...

**Comment by jamuhl** [comment]
hi thorsten...let me know when you're definitively use i18next in blueocean...would be great if you could send me a logo then so i can add you to the "Projects / Companys using i18next" section on i18next.com - would be cool.
