### ISSUE TITLE
What happened to old documentation?

### ISSUE THREAD

**Issue by neocotic** [i18next/i18next#829]
For a long time I've been able to view the old documentation [here](http://i18next.github.io/i18next/), as directed to in #474, but recently it's returning a 404. Was this planned or has something simply gone wrong?

Personally, I'd like to see the old docs maintained, even if it's part of a separate repository. Sadly, it's unlikely that we're going to get to upgrade to 2.x or 3.x anytime soon so we'll be using 1.x for a while and therefore rely on this documentation.

If you'd like to avoid hosting the old documentation on your website, I'd be willing to try and rewrite it for your wiki.

**Comment by jamuhl** [comment]
sorry...seems i accidentally deleted the gh-pages branch...should be ok again: http://i18next.github.io/i18next/

**Comment by neocotic** [comment]
Perfect! Thanks for the quick response.
