### ISSUE TITLE
Wrong key selection?

### ISSUE THREAD

**Issue by smiith** [i18next/i18next#831]
Hello!
Let look at this simple example:

```
var i18next = require('i18next');

i18next.init({
  lng: 'ko',
  resources: {
    ko: {
      translation: {
        "key": "{{count}} day without suffix",
        "key_0": "{{count}} day with _0 suffix"
      }
    }
  }
}, function(err, t){
  const day = i18next.t( 'key', { count:1 });
  console.log("result:",day);
});
```
When it run on nodejs with i18next v3.4.4, it returns this:

> result: 1 day without suffix

But by documentation http://i18next.com/docs/plurals/ , translation  in v3.x.x should use "key_0", not "key".
I see this effect for all locales with 1 plural form and key_0 suffix.

Is it typo in documentation or bug?

**Comment by jamuhl** [comment]
correct is `key` without suffix -> will need to update the documentation (seems i missed the locales not having pluralforms).

Thank you for reporting.

**Comment by smiith** [comment]
You are welcome! Thank you for fast response.

**Comment by jamuhl** [comment]
http://i18next.com/docs/plurals/ fixed -> might need a cache refresh to see change.

**Comment by smiith** [comment]
I can see the changes. Thanks!
