### ISSUE TITLE
Why do not create an new Translator instance when invoke cloneInstance?

### ISSUE THREAD

**Issue by anson0370** [i18next/i18next#833]
```js
  cloneInstance(options = {}, callback) {
    let clone = new I18n({...options, ...this.options, ...{isClone: true}}, callback);
    const membersToCopy = ['store', 'translator', 'services', 'language'];
    membersToCopy.forEach(m => {
      clone[m] = this[m];
    });

    return clone;
  }
```

Every clone of i18next have the same translator instance. If I use some code like below:
```js
const i18n = i18next.cloneInstance()
i18n.changeLanguage(someDetectedLanguage)
await someAsyncActionHere()
i18n.t('translate text')
```
The behavior is unpredictable. Because all requests change the same translator's language.

**Comment by jamuhl** [comment]
Makes sense...if you like you might provide a PR? Else i will try to change this for a future release...but honestly might take some time - as i'm hard on time.

**Comment by anson0370** [comment]
Of cause. I'll make a PR this days. 😄

**Comment by jamuhl** [comment]
merged
