### ISSUE TITLE
Crash when param not exist

### ISSUE THREAD

**Issue by popod** [i18next/i18next#835]
If passing an undefined param to i18next.t(), nothing is displaying.. Change this by displaying the text with "xxx" or "undefined" in place of the undefined param ?

**Comment by jamuhl** [comment]
sorry not getting what you want...could you provide some more code...passing undefined param as second param in t call for interpolation or what?

**Comment by popod** [comment]
Yes, for interpolation. Here is some code

```
var test = "test";
i18next.t('key', {param_ok: test, param_no_ok: undefined_var});
```

this wil display the translated text for "key" with param_ok="test", but nothing for param_no_ok..

Is it more clear ?

**Comment by jamuhl** [comment]
But there is no crash like stated in title. it will replace the var {{param_no_ok}} in the translation with an empty string and log out a warning - that would be the expected behaviour. Might be some change broke that...will need to check that later.

**Comment by jamuhl** [comment]
there is a test for `null` but non for undefined....will need to check...thanks for reporting.

**Comment by jamuhl** [comment]
just tested the undefined case:

```
key: 'test {{ test }}'
i18n.t('key', { test: undefined }); -> 'test '
```

seems to work - not sure - what you want to be displayed?

**Comment by popod** [comment]
Yes this works now ! I had an other error in my i18next setup that trig an error in my code.. Sorry and thanks for help !
