### ISSUE TITLE
i18next.languages is undefined

### ISSUE THREAD

**Issue by Programmix** [i18next/i18next#839]
Perhaps this could be something on my end, but it seems that i18next isn't populating the languages array; instead, it's undefined.

Using latest version.

**Comment by jamuhl** [comment]
can you past some code sample..your init, where you expect languages to be defined...

**Comment by Programmix** [comment]
Yes, my apologies.
![image](https://cloud.githubusercontent.com/assets/13167687/20271186/d37158c8-aa3e-11e6-92d0-32ece99acde6.png)

Here's where I initialize i18next. Other namespaces besides the ones provided are dynamically loaded in later in execution.

**Comment by jamuhl** [comment]
you neither set lng on init nor use a languageDetector. i see you coming from node.js - there is only a detector for express - https://github.com/i18next/i18next-express-middleware#language-detection

**Comment by Programmix** [comment]
All right. Since I'm not developing a web app, I used `lng` on init and it worked fine.
Perhaps you should note this in the docs to help other users.

Thanks for your help. 😄
