### ISSUE TITLE
Any changes in version 4?

### ISSUE THREAD

**Issue by PavelVanecek** [i18next/i18next#840]
I noticed that there is version 4.0.0 published since Nov 9. Major version bump suggests breaking changes. Are there any? How does one migrate? CHANGELOG.md still has info about 3.5.2 only.

**Comment by jamuhl** [comment]
Sorry...didn't notice i did not have pushed the changelog update...done now. the breaking change is only important for users using webpack2 beta and was related to this issue: https://github.com/i18next/i18next/issues/836

if not using webpack2 beta...nothing is breaking...

**Comment by jamuhl** [comment]
And don't forget...http://locize.com is our service tier....which supports future development of i18next...you might give it a try to boost localization to a new level

**Comment by PavelVanecek** [comment]
Thanks!
