### ISSUE TITLE
`x.default.use` is not a function

### ISSUE THREAD

**Issue by luisherranz** [i18next/i18next#841]
I'm having the `default.use is not a function` error with webpack `1.13.3` and i18next `3.5.2` when webpack is used with `-p`. 

I tried going back to previous versions (`3.1.0`, `3.2.0`...) but that didn't work either. Is there some cache I should purge?

Oh, and I can't disable modules in my app (`{ "modules": false }`) because that breaks other parts.

Strange thing is that if I modify my `node_modules/i18next/index.js` and I add a console.log it works:

```javascript
console.log('3.5.2');
module.exports = require('./dist/commonjs/index.js').default;
```

I added it to see if I was using the correct version (and not a cached version) but now it turns out that if I leave that console.log, it works, but if I remove it, it breaks again. Same version `3.5.2`.

It looks like adding any random code is enough to make this work:

This fails:
```javascript
module.exports = require('./dist/commonjs/index.js').default;
```

This works:
```javascript
var a;
module.exports = require('./dist/commonjs/index.js').default;
```

Is this a i18next or a webpack problem?

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/issues/836 for full read:

3.5.2 should work like before - 4.0.0 starts using module entry point

**Comment by jamuhl** [comment]
means 4.0.0 points webpack to es modules , 3.5.2 to commonjs

**Comment by jamuhl** [comment]
basically i think you should stop using require statements with webpack2 or at least not mix those

**Comment by luisherranz** [comment]
I'm not using webpack2, I'm using webpack 1.13.3. i18next 3.5.2 works on my machine in development mode, but not in production. I'll try to deactivate the production plugins to see if any of those is causing the issue.

**Comment by jamuhl** [comment]
no idea...for webpack1 there is no know issue. But as it runs in development it might be some production issue related to some webpack plugin (i assume)

**Comment by luisherranz** [comment]
It looks like the offending plugin is [Dedupe](https://github.com/webpack/docs/wiki/optimization#deduplication). I will try to create an isolated repository.

**Comment by jamuhl** [comment]
we use that too...so not sure...but isolating it might be a good idea

**Comment by luisherranz** [comment]
There you go:
https://github.com/luisherranz/i18next-webpack-dedupe-problem

It looks like the problem appears when a combination of these things happens:

- A vendors bundled with `DllPlugin` containing at least `i18next`, `i18next-xhr-backend` and `react-dom`.
- Version of `react-dom` is 15.4.0.
- Both plugins `DedupePlugin` and `FixModuleIdAndChunkIdPlugin` are used in the vendors bundle.

If you remove any of the above conditions, the problem disappears. For example, it works again if you:

- Downgrade `react-dom` to 15.3.2 (or remove it).
- Remove the `DedupePlugin` of the vendors build process.
- Remove the `FixModuleIdAndChunkIdPlugin` of the vendors build process.

It happens with any version of i18next, even 3.1.0 so it's not related with the webpack2 problem.

It can be solved if you add "something" to the node_modules/i18next/index.js file, like this:

```javascript
var a;
module.exports = require('./dist/commonjs/index.js').default;
```

Any small change, not matter what, is enough to make it work fine.

Any ideas?

PS: This is the changelog of react-dom 15.4.0: https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html#react-dom

**Comment by jamuhl** [comment]
thanks for taking the time to reproduce it...very strange...honestly i got no idea what's happening but might be some edge-case in webpack. Very confusing.

**Comment by luisherranz** [comment]
Although this started like a i18next issue and it looked surprisingly similar to the webpack2 problem, I now think it's an issue of the combination of Dedupe and FixModuleIdAndChunkId. I also think I know the cause so I'll try to fix it tomorrow. Thanks for your help anyway :)

**Comment by jamuhl** [comment]
okey...would be great if you keep me uptodate...

**Comment by luisherranz** [comment]
My solution didn't work so I'm just dropping FixModuleIdAndChunkId. My only advice is not to use these combination of things together.

I'll close this now, thanks for your support @jamuhl.

**Comment by jamuhl** [comment]
sorry to hear that...best for your project....thanks for keeping me uptodate.
