### ISSUE TITLE
Nesting keys from different namespaces

### ISSUE THREAD

**Issue by Programmix** [i18next/i18next#842]
Hi there. Right now I'm trying to use nesting, but there isn't too much documentation surrounding it, so I'm trying to work it out myself. However, when trying to use this string with nesting:
`"success": "$t(phrases.success, { \"action\": \"created\" }) poll (id: **{{poll.id}}**)",`
the library sends a warning that the key `phrases.success` does not exist. That specific phrase is specified in a different namespace. Can keys from different namespaces be accessed via nesting? Let me know if I'm doing something wrong. :)

Side-note: There's currently an open issue that requests `'` be a valid option for quoting inside of nesting keys. I'm not sure if there was an issue with that or something, but that would be a very nice feature.

**Comment by jamuhl** [comment]
accessing another namespace is like always - just prepend `ns:`

`"success": "$t(MYNAMESPACE:phrases.success, { \"action\": \"created\" }) poll (id: **{{poll.id}}**)",`

the open request - there is no issue with that - just not to high on my prio list. Would be a easy todo PR: https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L113

**Comment by Programmix** [comment]
Ah, wasn't aware of that. Thank you.
I poked around the code a bit; are you saying it's as simple as replacing `'` with `"` before passing the string to the interpolator?

**Comment by jamuhl** [comment]
not tested...but something like that should do the trick...in the end it must be parsable json
