### ISSUE TITLE
escape->escapeValue in docs

### ISSUE THREAD

**Issue by mull** [i18next/i18next#844]
I was scratching my head quite a bit at http://i18next.com/translate/interpolation/ until I realized you probably mean `escapeValue: false` rather than `escape: false`, right? I'm not sure which repository this is held in so I'm just creating an issue. Feel free to point me to the repo and I'll give you a PR.

**Comment by jamuhl** [comment]
argh....missed that. absolutely right...changed and published update.

sorry for that...
