### ISSUE TITLE
reloadResources Reloading content when language is changed

### ISSUE THREAD

**Issue by Elyorito** [i18next/i18next#845]
Hi,

I have a little concern about the method reloadResources().
It is said:

> Reloads resources on given state. Optionally you can pass an array of languages and namespaces as params if you don’t want to relaod all.

If I give nothing, what happen? Because I'm getting an error saying  `Cannot read property 'options' of undefined` for `i18next.reloadResources();`

It is not a "hot" reloading right? maybe I misunderstand something, I read a lot about the "v1" and I'm trying to get the same function as this [jsfiddle](http://jsfiddle.net/SalvadorDali/dLc7x/)
He's using i18n() that does not exist anymore I believe in the v2.

Thank you

**Comment by jamuhl** [comment]
no...reloadResources does reload the resources from backend (xhr, fs, whatever):
a) all
b) the one specified

what you search is the https://github.com/i18next/jquery-i18next or without jquery https://github.com/mthh/loc-i18next

**Comment by Elyorito** [comment]
Thank you, yes it is exactly what I want.
Actually, I'm trying to implement your solution with my handlebars template. I believe those helpers can work only with attribute like `data-i18n="[href]nav.page1"`
