### ISSUE TITLE
Is it possible to ignore nested HTML tags?

### ISSUE THREAD

**Issue by yduman** [i18next/i18next#846]
Hi,

Lets assume I have a HTML like `<li><a href="#" id="some-id" data-i18n="key"><span class="some-class"> </span>some text</a></li>`.

Is it possible to ignore the `<span class="some-class"> </span>` inside the a-tag? I know that you could insert the span to the value of the key and call it properly with `data-i18n="[html]key"`, but I try to look for easier ways, if possible :)

**Comment by jamuhl** [comment]
try using append `data-i18n="[append]key"`

**Comment by yduman** [comment]
Maybe my question was not clear enough (sorry my bad). If I want to translate `some text`, then I can't use `append` am I right? Because this would just add the value of the key after `some text` and I would have something like ``some text appended text`. 

My goal is to translate `some text`, but with i18next only recognizing the text part of the a-tag.

**Comment by jamuhl** [comment]
remove some text have that coming from translation

**Comment by yduman** [comment]
alright thank you for that suggestion! 
is there also a possibility without removing `some text`? just wondering :)

**Comment by jamuhl** [comment]
if you can wrap some text into an additional span you might set https://github.com/i18next/jquery-i18next#translate-some-inner-element but might not be what you really want...so no...i not know how to achieve that.

**Comment by yduman** [comment]
Alright no problem 👍 thank you for your time and patience! I can work with the information you've provided :)
