### ISSUE TITLE
Typescript definitions for version 4.1.1?

### ISSUE THREAD

**Issue by jmathew** [i18next/i18next#848]
Is there a  pre-existing typescript definition file for 4.1.1? The only one I see Definitely Typed is one for 2.3.4.

Along the same lines, would that 2.3.4 definition file be a good starting point to write the defs for 4.1.1, or would a complete rewrite be better?

Thanks!

**Comment by jamuhl** [comment]
2.3.4 should more or less do the job...v3 was a change to plural index, v4 was a change to entry point which might break builds done with webpack2. so more or less API of 2.x.x is same as in 4.x.x. Hope that helps.
