### ISSUE TITLE
option argument is ignored

### ISSUE THREAD

**Issue by strarsis** [i18next/i18next#850]
I try to use a different language for a particular key using
```js
i18n.exists('some-key', {lng: 'specific-language'});
````
However, in debug log it still tries to fetch the translation for the language i18n has been initialized with (en) 
and also returns true - although debug log indicates that it is missing (and it is also added to missing list).
````
i18next::translator: missingKey en content some-ns:some-key:some-key
````

**Comment by jamuhl** [comment]
`i18n.exists` does the same as i18n.t - if you have a fallback lng defined it will use that (rather sure you have that defined to `en`)

exists also does not trigger an missing call.

**Comment by strarsis** [comment]
Correct, it was caused by an unnoticed further invocation of t(...) that caused the extra logs.

In case the translation keys are already in a language (e.g. 'en'), how can I configure i18next to use the original keys and not note them as missing when that language ('en') is actually used?

**Comment by jamuhl** [comment]
access to `t('key')`will not trigger a missing if existing...if it states it is missing it is missing...looking at the key you requested `i18next::translator: missingKey en content some-ns:some-key:some-key` i'm rather sure you called something wrong as that has two `:` which separates namespace from key.

**Comment by strarsis** [comment]
Thanks.
