### ISSUE TITLE
some hack for support ie8

### ISSUE THREAD

**Issue by ruoqianfengshao** [i18next/i18next#852]
I try i18next in my application,. It's wonderful to use.
And to support ie8, there are some code need to hack.

![image](https://cloud.githubusercontent.com/assets/2928664/21445940/2fc15d6e-c8fb-11e6-9619-bc6e90dc3618.png)
![image](https://cloud.githubusercontent.com/assets/2928664/21445946/413d995e-c8fb-11e6-978c-565a85085e07.png)               

It will throw error in ie8 if these two place use declaring function and I  replace anonymous function to it works fine.

**Comment by jamuhl** [comment]
hope you understand that we long ago dropped support for ie8 - so my support for that is limited.

i made a change to change this functions: i18next@4.1.3 could you try that?

**Comment by ruoqianfengshao** [comment]
@jamuhl thx, i will try this version and give u next report.
