### ISSUE TITLE
i18next.reloadResources is not working.

### ISSUE THREAD

**Issue by aniinprni** [i18next/i18next#856]
Hi,
    i am using **i18next** for internalization. i am using **mongodb** plugin to translate. I want to reload translations dynmically when ever changes happened in db. for reloading the resources i have written below code:

```
i18next.reloadResources(["en","ar"]);
```
In my localhost it is working fine, but when i deployed it in production it is not working. I have kept consoles to check whether languages are loading or not in **reloadResources** method. It is reloading , but it is not effecting in browser when the refresh the same page. Kindly suggest me what need to be done. I have been struck for 2 days. kindly help me out please.

Thanks & Regards,
Anil.

**Comment by jamuhl** [comment]
What you mean by working on localhost but not in production...reloadResources does only do the reload (assuming the reload does not end in some cached loading) - and does not anyhow magically rerender your page.

Beside having a caching issue i can't see what should be different on localhost.

Even more it's unclear to me why you trigger a reload based on changes in your backend db - what is your use case for doing that?

**Comment by jamuhl** [comment]
really need some more details to help you...

**Comment by jamuhl** [comment]
closing for now....feel free to reopen with more details

**Comment by aniinprni** [comment]
Hi jamuhl,
     Sorry i couldn't able to get back to you as i was in sick leave (suffering with typhoid). We have one application where we update the existing translations. Now i need to reload those translations on the fly with out stopping the server and it should reflect in the browser when i refresh the page. In my local(windows system) it is working fine if i use 
``i18next.reloadResources(["en","ar"]);``
But when i deploy the same thing in Linux machine, it is not working **(means updated translations are not coming, retaining old translations only in the browser. But when i restart the server it is working fine..)**. Kindly advise regarding this issue.
