### ISSUE TITLE
There's a way to format fallback keys?

### ISSUE THREAD

**Issue by victornpb** [i18next/i18next#857]
There's any way to format the returned value if the key is missing from the dictionary?
```
fallbackFormater = function(key){
     return "!_"+key.toUpperCase()+"_!";
}
```

    
    i18next.t('welcomeMsg') "!_WELCOMEMSG_!"

To make it easier to spot when a translation is missing.

**Comment by jamuhl** [comment]
http://i18next.com/docs/options/#init-options

```
  i18next.init({
    parseMissingKeyHandler: function(key){
      return "!_"+key.toUpperCase()+"_!";
    }
  });
```

**Comment by victornpb** [comment]
@jamuhl Thanks! I just found it on i18next.js:958

          // parseMissingKeyHandler
          if (usedKey && this.options.parseMissingKeyHandler) res = this.options.parseMissingKeyHandler(res);
