### ISSUE TITLE
i18next on jade

### ISSUE THREAD

**Issue by Fr4ncx** [i18next/i18next#858]
Hi! I'm using i18next in NodeJS with express, everything works well except the t object inside jade.
Here is my config:
```
          i18next
		.use(Backend)
		.init({
		      "whitelist": ["en", "it"],
	               "preload": ["en", "it"],
	               "ns": [
	                   "api", "common"
	                 ],
	               "defaultNS": "api",
	               "debug": true,
	               "interpolation": {
	                  "escapeValue": false
	               },
	              "backend": {
	                   "loadPath": "/locales/{{lng}}/{{ns}}.json"
	              },
	             "detection": {
	                  "order": ["querystring", "path", "header"],
	                 "lookupQuerystring": "lng",
	                 "lookupPath": "lng"
	              }
		});
```

	app.use(middleware.handle(i18next, {
	    removeLngFromUrl: false
	}));`

TEST.JADE

`div=t('test')`

> t is not a function

Thank you!

**Comment by jamuhl** [comment]
do you have a repo i could checkout....should work...at least i'm not aware of an issue yet.

**Comment by Fr4ncx** [comment]
i'm sorry i don't have.... maybe the problem is with jade.. and i have to use pug instead?

**Comment by jamuhl** [comment]
shouldn't make a difference i think...but honestly i do not test against latest express, jade/pug - as i personally do not use this module...

**Comment by jamuhl** [comment]
simplest would be you publish your progress on github and let me see the code and test that.

**Comment by Fr4ncx** [comment]
With pug everything works! Thank you :) 👍

**Comment by jamuhl** [comment]
good to know...thank you for sharing your finding.

**Comment by oskarrough** [comment]
I just stumbled into this and the issue for me wasn't jade or pug but rather how you pass the `i18next.t` function to the templating layer. So for anyone ending up here:

```js
pug({
  locals: {
    // t: i18next.t // doesn't work
    t: i18next.t.bind(i18next) // works
  }
})
```

and then in templates

```pug
p= t('myKey')
```

**Comment by jamuhl** [comment]
@oskarrough if not using `req.t` from i18next-express-middleware i just can warn you that this won't work - you will end in race conditions as soon async stuff gets performed ending in mixed languages as you use i18next.t which is a singleton and not safe to use during requests....

https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L13

**Comment by oskarrough** [comment]
@jamuhl thanks for the warning. In this case, I'm not using Express rather building some static templates where the language can not be changed dynamically so I assume it should be ok here :)
