### ISSUE TITLE
i18next.reloadResources is not working. #856

### ISSUE THREAD

**Issue by aniinprni** [i18next/i18next#861]
Hi jamuhl,
Sorry i couldn't able to get back to you as i was in sick leave (suffering with typhoid). We have one application where we update the existing translations. Now i need to reload those translations on the fly with out stopping the server and it should reflect in the browser when i refresh the page. In my local(windows system) it is working fine if i use
``i18next.reloadResources(["en","ar"]);``
But when i deploy the same thing in Linux machine, it is not working **(means updated translations are not coming, retaining old translations only in the browser. But when i restart the server it is working fine..)**. Kindly advise regarding this issue. I don't know how to reopen the issue .So i created new issue. 

Thanks in Advance,
B.Anil kumar

**Comment by jamuhl** [comment]
Hope you're better now.

Got no idea - we more or less use the same code fragments for locize.com (https://github.com/locize/i18next-node-locize-backend/blob/master/src/index.js#L53) - and there it works.

Can you set debug = true on init of i18next and check if reloadResources triggers a load of the updated data?

**Comment by aniinprni** [comment]
Hai jamuhl,
  Thank you for giving me some hints. I will try and let you know.

**Comment by aniinprni** [comment]
Hai jamuhl,

   i tried with debug=true and backend languages are loading properly. But in the browser i can see only old translations. If i keep on refreshing the page, then it is giving me latest modified translation for the first time and next time onwards showing old translation only. And i am using ``i18next`` version is **4.1.4** and backend module is ``i18next-node-mongodb-backend`` plugin.
I have changed the **read** function little bit.
here is the change:
``` 
collection.find().toArray(function(err, items) {
              var data={};
              data = items.reduce(function(result, item) {
            	  var key = item.translationKey; 
            	  result[key] = item.translations[language];
            	  return result;
            	}, {});
            //  console.log("data ========",data["home"]);
              callback(null, data);
              db.close();
          });
```
As my **translations** db structure is little bit different. Is this impacting ?. Kindly suggest me.

**Comment by jamuhl** [comment]
no i don't think it's related to that change you made to read.

so you tell me the new resources get loaded and updated but the client gets only the old ones?

do you use it with the i18next-express-middleware? might be it's more related to caching:

you use the getResourcesHandler: https://github.com/i18next/i18next-express-middleware#add-routes ?!?

you might play with options.cache and options.maxAge on that function call (if really related to caching)

**Comment by aniinprni** [comment]
Thank you jamuhl. i will try this and let you know..

**Comment by aniinprni** [comment]
Hai Jamuhl,

   i tried with ``addRoute`` . Still i can see same old translations in the browser. I am using ``middlewear``  . And my application environment variable name is ``preprod``.  Kindly look into this piece of code of i18next initialization.

```

i18next.use(Backend).use(middleware.LanguageDetector).init({
		debug: true,
		load: ['ar','en'],
		fallbackLng: 'ar',
		backend: { 
			uri: 'mongodb://localhost/test',
			collection: 'translations'
		},
		getAsync:false,
		detection:{
			  order: ['path','cookie'],
			  lookupFromPathIndex: 0,
			  lookupCookie: 'selectedLanguage'
		}
	}, (err, t) => {
		return t;
});


app.use(middleware.handle(i18next, {}));
```

Is there any mistake while initializing ?.. Kindly suggest me

**Comment by jamuhl** [comment]
looks correct.

just getAsync does not exist anymore...what repo you use as backend for mongo? https://github.com/gian788/i18next-node-mongodb-backend ? 

that seems to support adding.

Did you register the routes? https://github.com/i18next/i18next-express-middleware#add-routes

**Comment by aniinprni** [comment]
Hai jamuhl, 

   i added a route in my routes files. isn't that meaning registering ? 
" **https://github.com/gian788/i18next-node-mongodb-backend** " i used this repo.
i can see the translations loaded perfectly but that didn't reflect in firefox browser.  Kindly suggest me.

**Comment by jamuhl** [comment]
do you reload them in browser, too?

**Comment by aniinprni** [comment]
jamuhl, i am not doing reload in browser. as we are ejs rendering the translations from server.

**Comment by jamuhl** [comment]
run console.log(i18next.store.data) before and after reloadResources. If having new data after the reload in the logged output...reloading works and it must have to do with caching or whatever...really hard to say without debugging the project.

**Comment by aniinprni** [comment]
ok jamuhl i will check that one

**Comment by aniinprni** [comment]
hi jamuhl, logs also showing updated data only . kindly suggest me.

**Comment by jamuhl** [comment]
If data is updated after reloadResources it's indeed a caching (between server and browser) issue or something inside express...but honestly i'm not the expert on that...might head over to stackoverflow or express to get more details on that...

**Comment by aniinprni** [comment]
ok jamuhl. thank you
