### ISSUE TITLE
Show namespace in cimode

### ISSUE THREAD

**Issue by aray12** [i18next/i18next#862]
Would it be possible to implement `cimode` so it also gives namespace. I understand that namespace isn't 1 to 1 usually (due to fallback). But I would expect it to provide the initial namespace it looked in. So if the default namespace is changed for an instance of `t` then it would provide that. Or if an explicit namespace was provide in the `t` call e.g. `t('special_namspace:some_key')` it would provide `special_namespace`

Also I would expect the same format as when you provide an explicit namespace when invoking `t`
e.g.
`special_namspace:some_key`

Thoughts?

**Comment by jamuhl** [comment]
Sure possible:

https://github.com/i18next/i18next/blob/master/src/Translator.js#L61 -> returns the value for cimode

move that below: https://github.com/i18next/i18next/blob/master/src/Translator.js#L68 so you got the namespace

add an option `appendNamespaceToCIMode = false` here: https://github.com/i18next/i18next/blob/master/src/defaults.js#L32

evaluate that on returning value for CIMode (having set appendNamespaceToCIMode to true) and your good.

PR would be welcome...else i will add this change for one of the next versions.

**Comment by jamuhl** [comment]
done

**Comment by oliviertassinari** [comment]
@jamuhl Thanks for adding this `appendNamespaceToCIMode` option. It's exactly what I have been looking for.
