### ISSUE TITLE
Fallback callback?

### ISSUE THREAD

**Issue by codeandcats** [i18next/i18next#864]
It seems by default i18n falls back to the translation key if no translation was found for the key, e.g.

```javascript
// No translation defined for CANCEL yet
i18next.t('CANCEL') // Returns 'CANCEL'
```

If no translation is found for the key, I would prefer to fallback to a distinctive message that makes it obvious that we've missed a translation or mistyped a translation key. Preferably mentioning the key in the message e.g.

```javascript
// No translation defined for CANCEL yet
i18next.t('CANCEL') // Returns 'No translation found for "CANCEL"'
```

Some sort of fallback callback function would be ideal because then we could also log to console/remote service any missing translations.

How can I achieve something like this using the i18next library?

**Comment by jamuhl** [comment]
there is a option on init `missingKeyHandler = function(lng, ns, key, fallbackValue) { }` to modify the output.

Preferred would be to use the saveMissing feature so the missing keys get send to your backend. Or not having that option in your backend you might give http://locize.com - our localization as a service platform a try - does the savemissing and autopublish stuff for more efficient continuous localization.

**Comment by jamuhl** [comment]
closing for now...if the solution does not meet your demand feel free to reopen it.

**Comment by codeandcats** [comment]
Hi @jamuhl, thanks for your response and sorry for the late reply.

If I assign a function to `missingKeyHandler`, it doesn't matter what I return from the function, it doesn't change the value that gets returned. Instead it just defaults to the fallback (either the value in the fallback language or the key).

However, it seems if I return a value from the `parseMissingKeyHandler` function, that value will get used.

But the problem is, the `parseMissingKeyHandler` function does not get passed the language and namespace, like `missingKeyHandler` does, so I can't include that information.

(Note that I do not wish to make use of the saveMissing functionality where it makes a web request to notify of missing keys)

**Comment by jamuhl** [comment]
ah right...sorry...parseMissingKeyHandler is the right one.

feel free to add a PR adding lng, ns to the call. https://github.com/i18next/i18next/blob/master/src/Translator.js#L153

**Comment by codeandcats** [comment]
Cool, thanks for your help 👍

**Comment by codeandcats** [comment]
Actually, I've noticed one other related issue. If a key is missing because there is no file for the namespace at all (i.e. http request for namespace returns a 404) then it will not use the value returned from `parseMissingKeyHandler` at all, instead it just returns the key. 😢

**Comment by jamuhl** [comment]
hm...there should not be a special treatment for that...or i do not remember right...loading and lookup is completely separated stuff.

**Comment by codeandcats** [comment]
Hmm interesting... I ended up simply returning an empty JSON object from my server if the namespace file doesn't exist, then it was happy. Everything is working well now. Cheers

**Comment by jamuhl** [comment]
that's what we do on http://locize.com too
