### ISSUE TITLE
Missing `services` guard or otherwise

### ISSUE THREAD

**Issue by mathieumg** [i18next/i18next#865]
I'm not an expert regarding i18next internals (though I'm slowly starting to become one), so I'm not sure whether this is a small omission or a bigger problem.

I have a i18next instance with no resources on it, and I pass it to `i18next-express-middleware`'s `handle` function to get back my middleware:

```js
express().use(handle(i18nextInstance));
```

If we follow the code, we see that the `handle` function clones the i18next instance:

https://github.com/i18next/i18next-express-middleware/blob/v1.0.2/src/index.js#L13

Which leads us back in this module, where we create a "clone instance":

https://github.com/i18next/i18next/blob/v6.0.1/src/i18next.js#L280

Lines of interest:

https://github.com/i18next/i18next/blob/v6.0.1/src/i18next.js#L21 initializes `services` to an empty object.

https://github.com/i18next/i18next/blob/v6.0.1/src/i18next.js#L25 moves on to next step.

Next step:

Does not enter the https://github.com/i18next/i18next/blob/v6.0.1/src/i18next.js#L51 condition since `isClone` is true. (I presume there is a reason for this, potentially not get many copies of these services everywhere, but shouldn't they rather use the services from the original instance then, instead of being empty?)

Next step: 

https://github.com/i18next/i18next/blob/v6.0.1/src/i18next.js#L108-L122 means we call `changeLanguage` no matter what.

Next step:

We can start seeing problems, https://github.com/i18next/i18next/blob/v6.0.1/src/i18next.js#L196 guards for the case where `this.services.languageDetector` doesn't exist, but https://github.com/i18next/i18next/blob/v6.0.1/src/i18next.js#L198-L200 doesn't.

Since that doesn't crash for me, I must have no `lng` and we know we don't have a `languageDetector` since `this.services` is still `{}`.

Next step:

https://github.com/i18next/i18next/blob/v6.0.1/src/i18next.js#L128 since we have no resources. This is where I crash: https://github.com/i18next/i18next/blob/v6.0.1/src/i18next.js#L133-L140 since `this.services.languageUtils` is `undefined`, `this.services.languageUtils.toResolveHierarchy` explodes.

So, is this simply about guarding that statement, or is there something deeper that was overlooked? I think you would know it best, at least I've done my homework! :smile: 

P.S. If you didn't notice by the URLs, I'm using `i18next` v6.0.1 and `i18next-express-middleware` v1.0.2.

**Comment by jamuhl** [comment]
before we did not call init on clones...might be time to check this for the express-middleware case (which is a little different). Will have a deeper look later today/tomorrow. Thanks for digging that deep into i18next.

**Comment by mathieumg** [comment]
Thanks! For what it's worth, to confirm everything I just tried by setting `resources: {}` and the problem doesn't occur in that scenario because we don't go in https://github.com/i18next/i18next/blob/v6.0.1/src/i18next.js#L128

Will wait to hear back, thanks again for the quick reply! :+1:

**Comment by jamuhl** [comment]
could you try with i18next@6.0.2

**Comment by mathieumg** [comment]
It does solve the problem! Thank you for the quick fix.

**Comment by jamuhl** [comment]
great to hear that worked...
