### ISSUE TITLE
Conditional translation - possible feature request

### ISSUE THREAD

**Issue by musicmunky** [i18next/i18next#867]
Is it possible to translate based on the format of the text inside an html tag?  Here's an example of what I mean:  
  
Say you have a span that looks like this:  
`<span class="quantity" data-i18n="quantity">Quantity</span>`  
  
After the user updates a text input, that tag will now look like this:  
`<span class="quantity" data-i18n="quantity">234</span>`  
  
If the user then switches languages, that number is overwritten with the translation for "Quantity" - would it be possible to have it ignore, or, not translate, based on the value/format of the text?  Eg, if the innerHTML is a number, don't perform the translation?  
  
I apologize if this feature already exists - I haven't been able to figure out how to do it if so!  
  
Thank you!

**Comment by jamuhl** [comment]
sorry to give an answer i need to know what you're using...jquery-i18next, i18nextify, loc-i18next?

i18next itself does no dom-manipulation - so it's not a question of i18next being able to do so - but of the framework-agnostic wrapper you use.

**Comment by musicmunky** [comment]
Great question, my apologies for not including that in the initial question!  
We are using jquery-i18next.

**Comment by jamuhl** [comment]
currently not possible...but a PR for some generic solution would be welcome.

**Comment by musicmunky** [comment]
Okay cool, no worries - I'll find a work-around for what we're doing on that for now.  
  
I'll fork a branch at some point soon and work on a possible generic implementation of that feature.  
  
Thanks!

**Comment by jamuhl** [comment]
closing for now...looking forward to PR on jquery-i18next
