### ISSUE TITLE
[Feature] Add an "adapter" to plugin type

### ISSUE THREAD

**Issue by perrin4869** [i18next/i18next#868]
First of all, here's the motivation behind this feature request.

I'm trying to use i18next in the Service Worker context, however, it is not a trivial thing to get working. The reason is that "ServiceWorker state is not persisted across the termination/restart cycle, so each event handler should assume it's being invoked with a bare, default global state." (see [here](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope)).

The solution to this problem would be to create a new layer, which we can call an `adapter` layer, similar to what `socket.io` [adapters](https://github.com/socketio/socket.io-adapter) do: they define where state is stored. In this way, you could have a memory adapter, similar to what you have right now, and an `IndexedDB` adapter, which would store state like current language, translations, etc, in `IndexedDB`, and could be accessed even after a ServiceWorker is restarted. There could be other use-cases for this too. One that I thought about would be to cache options after doing `i18n.init`, and then calling `init` only if needed.

One hurdle I can already see coming is that this new adapter API would need to be async, preferably using `Promises`, although `Promise` support wouldn't be a must. This could increase code complexity a little.

I don't have all this figured out yet, but I could try implementing this in the coming days/weekend, but first I wanted to check what you think of this idea. Does it make sense? Maybe it's over-engineering?

**Comment by jamuhl** [comment]
not sure if this could be solved by using the cache layer of i18next (eg. localStorage implementation: https://github.com/i18next/i18next-localStorage-cache) which is called by https://github.com/i18next/i18next/blob/master/src/CacheConnector.js (async as backend calls).

then do a init call with persisted options so only first load (or if resources are not loaded) will touch the backend.

Second option would be calling init with resources in options (which could be rehydrated from i18next.services.resourceStore.data). Best would be to solve this with an module wrapping i18next - so we could keep the i18next core as small as possible.

**Comment by perrin4869** [comment]
Hm... Interesting! Yeah the cache layer is a way in the right direction, would need to implement an `i18next-indexeddb-cache` plugin though (as long as all the cache calls are async it should be fine).

The biggest problem that needs solving is the fact that you don't have any service worker callback for termination/restart, so there is no opportunity to call `init` on `i18next`...

**Comment by jamuhl** [comment]
As long we do not add to much complexity in the core i'm open to accept PRs on that.

**Comment by jamuhl** [comment]
Is this still an issue or should we close this after a year of no progress?

**Comment by perrin4869** [comment]
Yeah, sorry for abandoning this, but I'm abandoning this approach after all
