### ISSUE TITLE
Electron App + Client localization?

### ISSUE THREAD

**Issue by mgatelabs** [i18next/i18next#869]
I'm starting down the road to localize my little Electron app and i'm wondering whats the best strategy for translation strings from the app and client-side via JavaScript.

I understand I can load a instance in the nodejs app file that can be used to translate strings from the app side.  But for the client-side part of electron whats recommended?  Load the client side of it?  Share the app instance via a remote?

**Comment by jamuhl** [comment]
@neruchev who built the electron-languagedetector might be the right person to give some insights here. Not yet had the chance to build an electron app - so i'm more lost then you with this question ;)

what we do in react-native apps is using http://locize.com as translation management and to host our translationfiles - so we load our translations from there plus use an asyncStorage caching layer. Think electron is close to that...so personally i would do the translation on clientside only (but like said...i'm never build something with electron...just guessing)

**Comment by mgatelabs** [comment]
I got i18next it to work on my client side electron app

Client side file **/js/lang.js**
```
var i18next = require('i18next');
var Backend = require('i18next-sync-fs-backend');
 
i18next
  .use(Backend)
  .init({
    lng: 'en',
    ns:'translation',
    initImmediate: false,
    backend: {
    // path where resources get loaded from 
    loadPath: __dirname + '/locales/{{lng}}/{{ns}}.json',
    
    // path to post missing resources 
    addPath: __dirname +  '/locales/{{lng}}/{{ns}}.missing.json',
    
    // jsonIndent to use when storing json files 
    jsonIndent: 2
    }
  });

  $(function(){
      $('[i18n-text]').each(function(){
          var node = $(this), key = node.attr('i18n-text');
          node.text(i18next.t(key));
      });
      $('[i18n-title]').each(function(){
          var node = $(this), key = node.attr('i18n-title');
          node.attr('title', i18next.t(key));
      });
  });
```

And in my web page I started to write tags like:

```
<h1 i18n-text="page.dash.welcome"><!--Welcome--></h1>
<li role="presentation" id="presetEditLink" i18n-title="page.detail.tabs.presetTitle">...</li>
```

**Comment by terhuerne** [comment]
Hi @mgatelabs,

I would also like to add support for various languages to my React + Electron app. I've tried to use your approach but had problems with the path for the application. Do you have an idea how to implement the path? I'm using the [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate) 

When launching the app, I get this warning:

`loading namespace general for language en failed Error: UNKNOWN: unknown error, open '\\locales\de\general.json'`
 

Do you have an idea?

**Comment by mgatelabs** [comment]
Well my backend code is [here](https://github.com/mgatelabs/DesktopTourManager/blob/master/app/main.js).  the code segment is:

```
i18next
    .use(Backend)
    .init({
      debug:false,
      lng: 'en',
      lngs: ['en', 'dev'],
      ns:'main',
      defaultNS:'main',
      initImmediate: false,
      backend: {
        // path where resources get loaded from 
        loadPath: path.join(__dirname, 'locales', '{{lng}}','{{ns}}.json')
      }
    }, function(err, t){
      if (env.devTools && err) {
        console.log(err);
      }
      // Only create the window when the languages are ready
      createWindow();
    });
```

And since it takes a bit to load, I have it create the window when it's done loading.

**Comment by BenBach** [comment]
@terhuerne Hi we have the exact same problem. Could you maybe share your solution? We would really appreciate your help.

We also use electron-react-boilerplate.

Thank you very much in advance

**Comment by reZach** [comment]
@mgatelabs @terhuerne @BenBach This is kinda late, but My Budget is using the electron-react-boilerplate and I have implemented localization using this default template: https://github.com/reZach/my-budget
