### ISSUE TITLE
Custom reading JSON translation

### ISSUE THREAD

**Issue by jamalsoueidan** [i18next/i18next#871]
Hello,

My translation files/name-spaces looks like this:

/en/application_navigation.json

`{
  "application_navigation":{
    "crodwin":"working",
    "now":"Nu",
    "recent_hours":"Sidste 16 timer",
    "choose_period":"Vælge period...",
    "dry":"Tørt",
    "reverse":"blah",
    "alert_types":"Alarm-typer",
    "leak":"Haha"
  }
}`

But i18next want them like this:

`{
    "crodwin":"working",
    "now":"Nu",
    "recent_hours":"Sidste 16 timer",
    "choose_period":"Vælge period...",
    "dry":"Tørt",
    "reverse":"blah",
    "alert_types":"Alarm-typer",
    "leak":"Haha"
}`

Is there any options to handle this? 
Instead of manipulating the files to remove the first key in all files?

Thank you

**Comment by jamuhl** [comment]
accessing with `i18next.t('application_navigation.crodwin');` is no option to access them?

an option would be to create a helper:

```
  const prefixedTFunction = (prepend) => {
    let t = (key, opts = {}) => {
      return i18next.t(prepend + '.' + key, options);
    };
    return t;
  }
```

**Comment by jamalsoueidan** [comment]
I can go with the first option, thank you +1
