### ISSUE TITLE
Get detected language?

### ISSUE THREAD

**Issue by mathieumg** [i18next/i18next#872]
How would one go about getting the detected language? `i18next.language` seems to simply return the value it was provided in `lng` when initialized.

Thank you!

**Comment by jamuhl** [comment]
`i18next.languages` will contain the locals detected to fallback local in order of prio...

**Comment by mathieumg** [comment]
`i18next.languages` is `undefined` as well when I don't specify a `lng` in my `init`. I skimmed a bit through the code and I figured that https://github.com/i18next/i18next/blob/v6.1.1/src/i18next.js#L196-L199 would set the `language` property to the right value. Am I missing something? Thank you.

**Comment by jamuhl** [comment]
hm strange...init will call changeLanguage...which will detect if no lng provided...if detected it will set both language and languages.

If languages is undefined...there was nothing detected...or you're using the express-middleware?

**Comment by mathieumg** [comment]
Yeah this is using the Express middleware, sorry for not specifying.

**Comment by jamuhl** [comment]
On express middleware it's a little different. https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L23

you got language and languages on the request (req) object.

**Comment by mathieumg** [comment]
If I have set `fallbackLng` and not `lng`, shouldn't `i18next.language` be the same as `fallbackLng` even before any detection takes place? Or is it only used as a last resort if the language couldn't be detected during the request and such?

That being said, I understand the reasoning since it makes little to no sense of having the language be separate from the request in the backend, so I'll just refactor my code a bit to move the `getCurrentLanguage` logic of my code to the frontend half of it.

If you're ever curious about the wrapper I'm developing, I can post back here once I publish it on GitHub later this week. :stuck_out_tongue: In any event, thanks for the help and the quick answers! :tada:

**Comment by jamuhl** [comment]
fallbackLng is the last used...req.language as i18next.language will be the detected one req.languages will be detected and eventual the language part of a local+region plus fallbackLng.

sure always happy to see stuff people create around i18next...chance to see, learn and for getting inspiration.

**Comment by mathieumg** [comment]
Ok, so as I suspected it do is used as a last resort if the language couldn't be detected during the request. 

I'll report back later this week with the link! :grin:

**Comment by mathieumg** [comment]
Just following up! The module I talked about is https://github.com/Novivia/modules.localization if you were curious. It wraps `i18next`, `moment.js` and the `Intl` API (with a polyfill when necessary) both in the frontend and in the backend. It's a little bit rough around the edges for now, but it'll allow us to easily reuse and keep i18next (and the other dependencies) updated across our different initiatives. :grin:

**Comment by jamuhl** [comment]
you're not using the new format option: http://i18next.com/translate/formatting/ right? But looks as a good base for doing more projects (using locize.com in the mix would be great if a customer would be have interest in translation management for easier localization process)

**Comment by mathieumg** [comment]
We're not using the formatting yet, that could change! It would be easy to integrate in the module I posted above, as well.

As for the locales management, it's something we haven't tackled yet since we're still pretty small and only have in-house French/English translations for the moment. Once that changes we'll sure look into Locize for either locale management and perhaps even for the translation services. :smile: 

By the way the privacy link in the footer (regarding cookie usage) is broken: http://locize.com/privacy/ :stuck_out_tongue:

**Comment by jamuhl** [comment]
great would love to see more people using locize...thank you for reporting the broken link...we will fix that asap.
