### ISSUE TITLE
webpack 2.x i18next destructure

### ISSUE THREAD

**Issue by bookman25** [i18next/i18next#873]
We currently destructure i18next imports, but when upgrading to webpack 2.0 (es6 modules) the functions are no longer present.  It looks like there is only `export default i18next`.

Would it be possible to export the other functions at the same level for the es6 modules?
`export const t = i18next.t` or something similar?

**Comment by jamuhl** [comment]
so you like to get that shiny `import { t } from 'i18next'` sounds good to me...adding those to https://github.com/i18next/i18next/blob/master/src/index.js should be sufficient.

If you like you might provide a PR to speed this up...or i will add those in the next days.

Thanks for the suggestion...
