### ISSUE TITLE
Interpolator#nest -- converting circular structure to JSON

### ISSUE THREAD

**Issue by Programmix** [i18next/i18next#875]
I've noticed a strange issue that started occurring without me really updating the library or anything. I updated to see if it would fix the issue, but it seems to still be occurring. I find that after a few minutes/hours of uptime, the library will begin to throw `TypeError: Converting circular structure to JSON` when trying to call the `t` function. Specifically, this occurs when the options param for the function has an object that is circular. However, the error seems to be caused by the library trying to clone the options object.

Here's the error I'm getting:
![putty_2017-02-03_20-09-22](https://cloud.githubusercontent.com/assets/13167687/22615617/2ed62bfa-ea4d-11e6-9709-48886729cde2.png)

**Comment by jamuhl** [comment]
the cause is this line...https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L97

will try to change that to a shallow clone function - that should solve this...and hopefully be good enough to not introduce sideeffects.

**Comment by Programmix** [comment]
As far as I know, all options that can be passed are either primitive types or arrays. Since you're only changing one value (a boolean, which is a primitive type), cloning should work just fine. I can PR this if you don't have time; just let me know.

**Comment by jamuhl** [comment]
Doing a version in the next days...so no problem...will add that, no big change so no extra PR needed.

**Comment by Programmix** [comment]
All right, awesome. 👍

**Comment by jamuhl** [comment]
published in i18next@7.0.0
