### ISSUE TITLE
Duplicate function in LanguageUtils.

### ISSUE THREAD

**Issue by npelletm** [i18next/i18next#881]
Just a copy/paste of `getLanguagePartFromCode` function  https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L15-L20
Sorry for not provide a PR.

**Comment by jamuhl** [comment]
haha...how did that happen...will be removed ;)

**Comment by jamuhl** [comment]
will be removed in next version: https://github.com/i18next/i18next/commit/f98fe3927ff8a9de3533880d3e459fd6f2b2a87d

thanks again for reporting
