### ISSUE TITLE
Lazdy loading of resources ?

### ISSUE THREAD

**Issue by Ziker22** [i18next/i18next#882]
Hi guys,
Is there a way of lazy loading static resources? 
The reason is that i cannot use backend due to some limitations on my project 
and as my localization files are quiet big i dont think its wise to load them all to browser

thx in advance

**Comment by jamuhl** [comment]
sorry but i do not understand. you can't use a backend plugin (eg. xhr backend on i18next) and also can't add them on init as they are to big. So you want them to load lazy.

Hm...i think what you ask is can i load additional namespace files later (after initialization) - answer is yes use http://i18next.com/docs/api/#load-namespaces

hope that is what you meant i hope it helps...else please try to give me more detail...rather sure i18next can handle that.

**Comment by Ziker22** [comment]
Thanks for superquick reply
this is my init file

> let detectorOptions = {
>     order: ['htmlTag'],
>     htmlTag: document.documentElement,
> }
> i18n
>     .use(LngDetector)
>     .init({
>         detection: detectorOptions,
>         resources: {
>             "en-US": {
>                 "translation": require('../locale/constants_en_US.json'),
>             },
>             "cs-CZ": {
>                 "translation": require('../locale/constants_cs_CZ.json'),
>             },
>         },
> ... more languages & more options

Lets say i have 20 languages with every one of them containing some 3000 keys (yes its app rewrite to React :))

Now the problem is that i18next object after init contains all 3000x20 keys
What i want to achieve is that if for example en-US is detected i want to load en-US and then somehow if user switches to i.e cs-CZ i18next will only add it to resources

Im not sure if namespaces can handle this

**Comment by jamuhl** [comment]
then why not using the backend - it's exactly what it does. https://github.com/i18next/i18next-xhr-backend

**Comment by jamuhl** [comment]
Closing for now...feel free to reopen if you think there is still something unclear.
