### ISSUE TITLE
Load translations from multiple files

### ISSUE THREAD

**Issue by rogerhnn** [i18next/i18next#886]
I am trying to load my translations from multiple files for each language.

Here is my function:

```
$(document).ready(function() {
	var language = "en";
	if (localStorage.getItem("language") != null) language = localStorage.getItem("language");
	
    i18n.init({
        lng: language,
        resGetPath: 'atlas/js/languages/__lng__.json',
        fallbackLng: "en"
    }, function(o) {
        $(document).i18n()
    }); 
	$(".lang").click(function() {
        var o = $(this).attr("data-lang");
		localStorage.setItem("language", o);
        i18n.init({
            lng: o
        }, function(o) {
            $(document).i18n()
        })
    })
});
```
and my files are inside this folder: 
`http://atlas-rogerhnn.codeanyapp.com/atlas/js/languages/`
Example for en: `http://atlas-rogerhnn.codeanyapp.com/atlas/js/languages/en.json`

And my files are like this:
en.json:
```
"translation": {
  "AddYourNote": "Add Your Note"
}
```
What am I missing?

**Comment by jamuhl** [comment]
What version of i18next are you using...the options you're using are of version 1.x.x?!?

Further for > v2.x.x:
- to change language use i18n.changeLanguage -> no need to init again
- use the language detector: https://github.com/i18next/i18next-browser-languageDetector
- for backend options for loading translations see: https://github.com/i18next/i18next-xhr-backend

**Comment by rogerhnn** [comment]
Hi Jamuhl, I was using version 1.6.3 which was the only one I found working examples in jsfiddle, codepen and around the web. (I am new to Javascript so I was looking fo working examples).

So how should I proceed to use the latest version of i18next?

Also in my current project I was handling the translations in html like this:

`<span datai18n="language">Language</span>`

Do I need to change it using the latest version?

**Comment by jamuhl** [comment]
for using with jquery follow the instruction on: https://github.com/i18next/jquery-i18next

if you're not used to javascript you might try http://locize.com it's our localization as a service offering...getting your website translated is easy as dropping one line of code to it.

**Comment by rogerhnn** [comment]
Ok I will try the instructions there and adapt my function to work.

Thanks for the suggestion, but my problem is with javascript function only. I already have all the content and it's translations.

**Comment by jamuhl** [comment]
you might set debug: true on init for your current version -> just see if something went wrong in console => might be your translations can not be loaded...

**Comment by rogerhnn** [comment]
Also when you say "use it with jquery" what's the difference between the normal version and this jquery one?

Isn't the same process to translate? I mean, the html should contain the data-i18n="wordForTranslate" and then in the translation file: "wordForTranslate": "Translation for Word for Translate"

Or do I have to include this in every element I want to translate: $(".nav").localize();

Because I find the way it was with 1.6.3 much easier.
(sorry if the question sounds dumb, but I am a noob with javascript, still learning).

**Comment by jamuhl** [comment]
jquery version: let's say it's a jquery plugin. while v1 was build with jquery plugin in core - v2 has removed that to be more open to other frameworks. angular, react, vue,...and beside those jquery too.

agree on 1.6.3 was easier...just for the one use case with jquery. with v2 we started to give more control, make i18next plugable to all the ui frameworks, nodejs, ... 

i mean you could get 1.6.3 to work for sure...just from your config i do not see what could be wrong...sorry...adding the debug flag might give you more insights.

http://atlas-rogerhnn.codeanyapp.com/atlas/js/languages/en.json i can't load that...but might be normal (i get a gateway timeout)

**Comment by rogerhnn** [comment]
Sorry, my devbox is offline, so it won't load the file.
I will turn it on and test with the link.

But my config is right for v 1.6.3 ?

**Comment by jamuhl** [comment]
looks ok to me...http://i18next.github.io/i18next/pages/doc_init.html

not sure if not using namespace in `resGetPath` does make it not work..you might try changing that to:

`resGetPath: 'atlas/js/languages/__lng__-__ns__.json',`

and name the files: `en-translation.json``

v1 is very old...sorry for not remembering all in detail.

**Comment by rogerhnn** [comment]
Okay, I turned my devbox on, and it loads from that link: http://atlas-rogerhnn.codeanyapp.com/atlas/js/languages/en.json

I will try the new config now!

**Comment by rogerhnn** [comment]
Strange.

updated the function as you said: 

```
$(document).ready(function() {
	var language = "en";
	if (localStorage.getItem("language") != null) language = localStorage.getItem("language");
	
    i18n.init({
        lng: language,
        resGetPath: '/atlas/js/languages/__lng__-__ns__.json',
        fallbackLng: "en"
    }, function(o) {
        $(document).i18n()
    }); 
	$(".lang").click(function() {
        var o = $(this).attr("data-lang");
		
		localStorage.setItem("language", o);
		
        i18n.init({
            lng: o
        }, function(o) {
            $(document).i18n()
        })
    })
});
```

And I can load the translations from the link: 

http://atlas-rogerhnn.codeanyapp.com/atlas/js/languages/en-translation.json

And I don't have any erros in console. Strange

**Comment by jamuhl** [comment]
no man's sky...nice. played that for a while.

just saw something - your json file is not valid:

```
"translation": {
  "AddYourNote": "Add Your Note"
}
```

should be:

```
{
  "AddYourNote": "Add Your Note"
}
```

for use in: `<span data-i18n="AddYourNote"></span>`

**Comment by rogerhnn** [comment]
lol I love that game!

I thought that too.
So, if I want to load the translations from: '/js/languages/__lng__-__ns__.json',
the file should be: /js/languages/en-translation.json
and the json: {"AddYourNote": "Add Your Note"}

but if I want to use the namespace on the file the resGetPath should be: '/js/languages/__lng__.json'
if I understand it right?

**Comment by jamuhl** [comment]
no

your json will alway be: {"AddYourNote": "Add Your Note"}

the namespace is default to translation - if using more then one file you will need to name that by using: `'/atlas/js/languages/__lng__-__ns__.json'` having just one you might work with `'/atlas/js/languages/__lng__.json'`

**Comment by rogerhnn** [comment]
Okay, so I think everything is right, as you said:

```
$(document).ready(function() {
	var language = "en";
	if (localStorage.getItem("language") != null) language = localStorage.getItem("language");
	
    i18n.init({
        lng: language,
        resGetPath: '/atlas/languages/__lng__.json',
        fallbackLng: "en",
    }, function(o) {
        $(document).i18n()
    }); 
	$(".lang").click(function() {
        var o = $(this).attr("data-lang");
		
		localStorage.setItem("language", o);
		
        i18n.init({
            lng: o
        }, function(o) {
            $(document).i18n()
        })
    })
});
```

and the json file: 
```
{
  "AddYourNote": "Add Your Note",
}
```
you can see the file here: http://atlas-rogerhnn.codeanyapp.com/atlas/languages/en.json

But I think I am missing something in the config? Because still don't work

**Comment by rogerhnn** [comment]
It's strange, because before I used this:

```
$(document).ready(function() {
	var language = "en";
	if (localStorage.getItem("language") != null) language = localStorage.getItem("language");
	
    i18n.init({
        lng: language,
        resStore: itemslang,
        fallbackLng: "en"
    }, function(o) {
        $(document).i18n()
    }); 
	$(".lang").click(function() {
        var o = $(this).attr("data-lang");
		
		localStorage.setItem("language", o);
		
        i18n.init({
            lng: o
        }, function(o) {
            $(document).i18n()
        })
    })
});
```

And loaded the file languages.js with this:

```
var itemslang = {
  // English
    "en": {
        "translation": {
		  "Value": "Value",
        }
    },
  // French
    "fr": {
      "translation": {
        "Value": "Valeur",
      }
    },
  // Italian
    "it": {
        "translation": {
          "Value": "Valore",
        }
    },
  // German
    "de": {
        "translation": {
          "Value": "Wert",
        }
    },
  // Spanish
    "es": {
        "translation": {
          "Value": "Valor",
        }
    },
  // Russian
    "ru": {
        "translation": {
          "Value": "Стоимость",
        }
    },
  // Polish
    "pl": {
        "translation": {
          "Value": "Wartość",
        }
    },
  // Dutch
    "nl": {
        "translation": {
          "Value": "Waarde",
        }
    },
  // Brazilian
    "br": {
        "translation": {
          "Value": "Valor",
        }
    },
  // Simplified Chinese
    "cn": {
        "translation": {
          "Value": "值",
        }
    },
  // Korean
    "ko": {
        "translation": {
          "Value": "값",
        }
    },
  // Japanese
    "ja": {
        "translation": {
          "Value": "値",
        }
    },
};
```

And everything worked fine. 

What I want now is just load the languages from separated files to minimize the load time.

**Comment by jamuhl** [comment]
putting that stuff in resStore via init is different...there you need the nesting language -> namespace -> translations

When loading that from backend the route already has language and namespace in it - so no need to have that inside the json. So you only need the 
```
{
    "Value": "値",
 }
```

**Comment by jamuhl** [comment]
just assert it's valid json: http://jsonlint.com/

**Comment by rogerhnn** [comment]
Whooops. Big mistake, I didn't know that I can't use comments in json like I use in js files `// Comment here`

After removing the comments it works now!

Thank you very much jamuhl!

Also, do you think that I should upgrade to the latest version of i18next or I can use this one with no problem?

**Comment by jamuhl** [comment]
if working for you there is no real need to upgrade - beside v1.6.3 is outdated. So if not using it for enterprise application you could stay on the old version.

nope...loading js isn't supported and unsafe.

Beside that you can migrate without issues in future to newer version: there are compatibility flags: http://i18next.com/docs/migration/#v1-11-x--v2-0-0

**Comment by rogerhnn** [comment]
Any notable difference between v.1.6.3 and the latest v.1xx which is 1.11.5 ?

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/CHANGELOG.md hard to say...

**Comment by jamuhl** [comment]
But upgrading should be possible without breaking

**Comment by rogerhnn** [comment]
Alright! I will try it.

Thank you very much Jamuhl!

**Comment by jamuhl** [comment]
you're welcome...just ping me if encounter some issues - here to help.
