### ISSUE TITLE
plural is not working for arabic language

### ISSUE THREAD

**Issue by aniinprni** [i18next/i18next#887]
Hi,
    i am using ``i18next``  for two languages ``en`` and ``ar``. For ``english``  **Adult** plural, i have written the key like this **"adult_plural":"Adults"** . It is working fine for English. For ``arabic`` also i have given the same key like below **"adult_plural":"أطفال"** , But for Arabic it is showing as **طفل**. in Ejs Template i am calling like this ``t('adult',{count:2})`` . Kindly help me out regarding this.

**Comment by jamuhl** [comment]
arabic is one of the many languages not having just a singular and a plural -> you need to define every form like: http://i18next.com/translate/pluralMulti/

for suffixes of locals checkout: http://i18next.com/docs/plurals/

**Comment by aniinprni** [comment]
Hi jamuhl,

   Is it possible to change Rule for arabic ? like this code below:

```
i18n.services.pluralResolver.addRule('ar', {
    "numbers": [
        1,
        2
    ], 
    "plurals": function(n) { return Number(n != 1); }
});
```
If yes , i have kept console to check whether rule is adding or not. And it was adding, but while 'getSuffix' method i can see the default rule only coming. 

Please suggest me on this

**Comment by jamuhl** [comment]
should work...but not looked at that for long...will need to run tests later to see.

**Comment by jamuhl** [comment]
at least code looks ok:

add -> https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L88

get -> https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L92

might be a timing issue?!?

**Comment by aniinprni** [comment]
Hi jamuhl, it is indeed working. Thank you for your time. Actually while server start up i am re initiating the I18next. That is why it is not reflecting.

Thank you once again.

**Comment by jamuhl** [comment]
argh...good you found that...a hard one to spot for sure
