### ISSUE TITLE
Callback fired multiple times in 7.0.1?

### ISSUE THREAD

**Issue by mathieumg** [i18next/i18next#888]
This change introduced in v7.0.1 creates issues for me, I'm not sure if it's because it was broken before or if it's because it's broken now:

https://github.com/i18next/i18next/blob/v7.0.1/src/i18next.js#L134

Basically I think I get my callback triggered multiple times, but I'm not exactly sure. To reproduce you can checkout https://github.com/Novivia/modules.localization and run `npm t`. If you then comment out the line I linked to above (introduced in v7.0.1), the problem goes away. Thanks for helping me shed some light on this!

**Comment by jamuhl** [comment]
Hi mathieu, i think the behaviour now is correct...

i tried to reproduce the issue by:

```
i18next
          .use({
            type: 'backend',
            init: function() {},
            read: function(language, namespace, callback) { callback('failed'); },

            // optional
            readMulti: function(languages, namespaces, callback) { callback('failed');  },
            create: function(languages, namespace, key, fallbackValue) { /* save the missing translation */ }
          })
          .init({
            foo: 'bar',
            debug: false
          }, (err, t) => {
            console.log('init', err)
            i18next.changeLanguage('en', (err, t) => { console.log('change', err) });

          });
```

which results in:

```
LOG LOG: 'init', undefined
LOG LOG: 'change', ['failed', 'failed']
```

init -> no lng => nothing loaded direct callback without any issue as nothing was to load
change -> new lng 'en' => loading 'en' and 'dev' (defaultFallback)

runs through https://github.com/i18next/i18next/blob/v7.0.1/src/BackendConnector.js#L76 giving:

```
LOG LOG: 'en|translation', 'failed'
LOG LOG: 'dev|translation', 'failed'
```

=> which gets merged into an error array and returned to callback: https://github.com/i18next/i18next/blob/v7.0.1/src/BackendConnector.js#L92

As before the change you mention we would have appended/loaded [undefined, fallbackLng] on the init case without providing a lng => the second call on changeLanguage would only load 'en' and not the fallback as that was loaded on init => only one error in array.

to fix your test you could provide a lng on init so at least the fallback will get loaded.

Additional i would like to hear your opinion - should we load fallbackLng anyway even if not providing a local to load? Personally i think yes?

**Comment by mathieumg** [comment]
First, thank you for your extremly quick reply, really appreciate it! :grin: 

I just pushed a fix in https://github.com/Novivia/modules.localization/pull/1/files#diff-8b18e1b9587b5a72c13346a040c44bc2R1032

It seems odd to me that changing the whitelist changes the loading behaviour, I thought the whitelist only meant "these languages are allowed if requested" and that the `fallbackLng` served the purpose of languages to try to load, in order.

> should we load fallbackLng anyway even if not providing a local to load? Personally i think yes?

Yes, absolutely. I don't think, however, that all the whitelist should try to get loaded. I presume it's what happens because the only place I have two languages specified in the default options is the whitelist, and setting it to English only fixes the test. (https://github.com/Novivia/modules.localization/blob/v0.1.1/config/i18next/common.js#L21-L24) Is this by design?

**Comment by jamuhl** [comment]
hm...currently fallbackLng runs through the whitelist check too, so basically setting whitelist to ['en'] -> makes the test load 'en' only and not ['en', 'dev'] (where dev is defaultFallbackLng)....

whitelist only acts as filter - it does not load them all - there is a preload array which enables that.

the test passes if only one lng get loaded on the changeLanguage, which could be achieved by:
- excluding 'dev' by setting whitelist
- setting lng to 'en' -> will load en before the change call -> so only 'dev' will be loaded on change language

think i will change to load at least fallback - if no language defined on init and non detected. But seems an edge case only get hits on running tests...in normal usage one will set some lng or let i18next detect one.

**Comment by jamuhl** [comment]
reminder to myself: at least load fallback if no lng defined

**Comment by jamuhl** [comment]
i18next@7.2.0 - loads fallback independent on language detection
