### ISSUE TITLE
Language files loaded twice each time language changed

### ISSUE THREAD

**Issue by TheTFo** [i18next/i18next#889]
I'm seeing an issue upon loading where my language files are being loaded more than once.  Here's a screen shot in the chrome network pane:

![image](https://cloud.githubusercontent.com/assets/530080/23325104/acee84be-fac0-11e6-8a8f-4518ce9d03a3.png)

Also note: en.json shouldn't be loaded at all.

I'm using: 

i18next - 7.0.1
i18next-xhr-backend - 1.3.0
react-i18next - 2.2.0

Here's my config:

```

import i18n from 'i18next';
import Backend from 'i18next-xhr-backend';

i18n
  .use(Backend)
  .init({
    fallbackLng: false,
    lng: 'en-US',
    backend: {
      loadPath: 'i18n/lang/{{lng}}.json',
      allowMultiLoading: false,
      crossDomain: false,
      withCredentials: false,
    }
  });

export default i18n;

```

It also seems every time I change languages that it loads the language twice.

Any help is appreciated!

**Comment by jamuhl** [comment]
i tried to verify using the react example: https://github.com/i18next/react-i18next

but was not able to reproduce.

why `en.json` should not be loaded => default behaviour to load and resolve translations is: locale with region (en-US) -> language (en) -> fallbackLanguage

you can change this by using options:
- whitelist: ['en-US']
- fallbackLng: false
- load: 'currentOnly'

for details please refer the documentation: http://i18next.com/docs/options/

Back to you main issue stuff being loaded twice:

Do you use multiple namespaces in the translate HOC?!? `translate(['defaultNamespace', 'anotherNamespace'], { wait: true })(TranslatableView);`

--> would load defaultNamespace and anotherNamespace; which will fail by the loadPath you did set: `'i18n/lang/{{lng}}.json'`

or you only use `translate('translation')(Comp)` ?!?

**Comment by TheTFo** [comment]
It was the namespacing.  I broken them out into separate files and now it's working properly.

**Comment by jamuhl** [comment]
Ok...if you encounter any other problem just let us know...here to help...by the way we also have a localization as a service tier http://locize.com great addition to i18next to reach the freedom of continuous localization ;)

**Comment by afiorenza** [comment]
@jamuhl I am facing this issue right now. Each time i change the language it is being loaded twice.

This is my i18n configuration:

```
import LanguageDetector from 'i18next-browser-languagedetector'
import XHR from 'i18next-xhr-backend'
import i18next from 'i18next'
import { initReactI18next } from 'react-i18next'
import { languages } from '~/statics/languages'

const i18nConfig = {
  backend: {
    jsonIndent: 2,
    loadPath: '/locales/{{lng}}.json'
  },
  detection: {
    caches: ['localStorage', 'cookie'],
    lookupCookie: 'language',
    lookupLocalStorage: 'language'
  },
  fallbackLng: 'en',
  interpolation: {
    escapeValue: false
  },
  load: 'languageOnly',
  react: {
    useSuspense: false
  },
  whitelist: languages
}

i18next
  .use(XHR)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init(i18nConfig)

export { i18nConfig }

export default i18next
```

![Screenshot 2020-01-29 at 17 47 36](https://user-images.githubusercontent.com/9002162/73377555-85406c80-42bf-11ea-9516-d77d0ca38eab.png)

Can you help me? Thanks

**Comment by jamuhl** [comment]
@afiorenza change load path to include {{ns}} for test -> rather sure you're loading two different namespaces as @TheTFo did

**Comment by afiorenza** [comment]
But i don't have namespaces... Are they mandatory?

**Comment by jamuhl** [comment]
there is always one namespace `translation` that is used as default...but you don't see that as it defaults to it

**Comment by jamuhl** [comment]
try setting `debug: true` on init options - check the console.log if there are some strange backend loaded fails

**Comment by semihraifgurel** [comment]
```typescript
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

import Backend from 'i18next-http-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
// don't want to use this?
// have a look at the Quick start guide
// for passing in lng and translations on init

// eslint-disable-next-line import/no-named-as-default-member
i18n
	// load translation using http -> see /public/locales (i.e. https://github.com/i18next/react-i18next/tree/master/example/react/public/locales)
	// learn more: https://github.com/i18next/i18next-http-backend
	// want your translations to be loaded from a professional CDN? => https://github.com/locize/react-tutorial#step-2---use-the-locize-cdn
	.use(Backend)
	// detect user language
	// learn more: https://github.com/i18next/i18next-browser-languageDetector
	.use(LanguageDetector)
	// pass the i18n instance to react-i18next.
	.use(initReactI18next)
	// init i18next
	// for all options read: https://www.i18next.com/overview/configuration-options
	.init({
		fallbackLng: 'en-US',
		debug: true,

		interpolation: {
			escapeValue: false, // not needed for react as it escapes by default
		},
		react: {
			useSuspense: true,
		},
	});

export default i18n;
```

<img width="276" alt="Ekran Resmi 2022-10-27 18 36 47" src="https://user-images.githubusercontent.com/29544960/198334871-bcf0fe28-1976-4898-bbaf-18f1f300881b.png">

Can you help me?

**Comment by semihraifgurel** [comment]
As far as I understand, the ways of two different requests are different.
Request URL: http://localhost:3001/locales/en-US/translation.json
Request URL: http://localhost:3001/locales/en/translation.json
