### ISSUE TITLE
addResourceBundle

### ISSUE THREAD

**Issue by stuartbloom** [i18next/i18next#890]
Hi there and sorry if this is a silly question.

I am using the aurelia plugin that uses your control.

I have it setup in the application as per the documentation, i.e.:
`.plugin('aurelia-i18n', (instance) => {
        // register backend plugin
        instance.i18next.use(Backend);

        // adapt options to your needs (see http://i18next.com/docs/options/)
        // make sure to return the promise of the setup method, in order to guarantee proper loading
        return instance.setup({
          backend: {                                  // <-- configure backend settings
            loadPath: './locales/{{lng}}/{{ns}}.json', // <-- XHR settings for where to get the files from
          },
          lng : 'en',
          attributes : ['t','i18n'],
          fallbackLng : 'en',
          debug : false
        });
      })`

I want to have an individual file for each of my ViewModels, however if I call `i18next.addResourceBundle('en', 'dashboard')` for example, I cannot seem to get the new bundle added.

Is there anything I am doing wrong?

Thanks in advance

**Comment by jamuhl** [comment]
hm...if `instance` is a own instance of i18next adding ResourceBundle on i18next main instance won't have an effect...but i'm not knowing the internals of the aurelia-plugin.

**Comment by jamuhl** [comment]
oh...and 8next.addResourceBundle('en', 'dashboard') has a different call:

http://i18next.com/docs/api/#add-resource-bundle

**Comment by stuartbloom** [comment]
jamuhl

thank you so much; can you just explain what myData is?

**Comment by jamuhl** [comment]
an object containing all the translations for 'en' and namespace 'dashboard'

```
{
  'someKey': 'some value'
}
```

**Comment by stuartbloom** [comment]
ah, thank you; is there anyway to load all translations?

**Comment by jamuhl** [comment]
define all namespaces on init: http://i18next.com/docs/options/

ns: ['all', 'my', 'namespaces']

**Comment by stuartbloom** [comment]
ok, not sure if that is what i mean.

I have loaded all resources in a namespace, called common.

Now, I have a viewmodel call dashboard that i want to also load all resources in the dashboard.json file.

can that be achieved?

**Comment by jamuhl** [comment]
Sure...but that is not an i18next topic...i do not know how that is done in aurelia...as i do not maintain that...would be better to ask the question over there....

in i18next you would:

`i18next.t('dashboard:myKey')` to access that...or creating a fixed t function

**Comment by stuartbloom** [comment]
ok, thanks i will ping the aurelia git forum
