### ISSUE TITLE
Arrays with php

### ISSUE THREAD

**Issue by alexfrad** [i18next/i18next#891]
Hi, my coworker have been working with your plugin for a while now and we just started using arrays on the same key. For some reason, getting the key element 0 is not working when passing from php. Every other positions is ok but 0 is not working. Doing the same thing from a js file is working fine though. 
Here's a example: 
`"test" : ["foo", "bar" ]`
Call on php side:
```
 i18next::getTranslation("test.0"); // Display test.0
 i18next::getTranslation("test.1"); // Display bar
```
Call on js side:
```
 i18next.t("test.0"); // Display foo
 i18next.t("test.1"); // Display bar
```
Thanks for your help!

**Comment by jamuhl** [comment]
What plugin you use to use i18next in PHP?

**Comment by alexfrad** [comment]
kopfwelt/i18next-php : https://github.com/kopfwelt/i18next-php

**Comment by jamuhl** [comment]
hm...as the problem is inside the php plugin and not on the js core repo - you might need to ask your question there. Hopefully they could fix the issue there...

**Comment by alexfrad** [comment]
Ok thank you. It's just that the plugin haven't change in one year so i thought you might know something about it. 
Well thank you again and sorry for inconvenience.

**Comment by jamuhl** [comment]
sorry for that...but i'm not knowing every community plugin in detail....hopefully they can help you
