### ISSUE TITLE
Inconsistency between pluralisation of languages

### ISSUE THREAD

**Issue by vass-david** [i18next/i18next#893]
I'm solving pluralisation in our application which supports polish and english language. For english languages my keys must look like this:
```
"key": "singular form",
"key_plural": "plural form",
```

For polish it's
```
"key": "singular form",
"key_1": "plural form for numbers from 2 to 4",
"key_2": "plural form for rest",
```

Is it possible to make it consistent? I mean to use `_1` as plural in english as well or `_plural` for rest of number in polish? Anyway `_1` does not tell me that it's used for numbers 2-4. I instinctively wanted to use `_2` when I first tried it and it took me some time of trial and error to set correct suffixes.

**Comment by jamuhl** [comment]
suffixes are the same as used in gettext and documented here: http://i18next.com/docs/plurals/

no currently there is no option to use _0 and _1 for plurals in locals only having one...if you need that you might provide a PR

**Comment by vass-david** [comment]
Ok, thanks. Will think about MR.

**Comment by jamuhl** [comment]
i18next@7.2.0 -> you now can set simplifyPluralSuffix to false on init so only numbers are used as suffix
