### ISSUE TITLE
Label http://i18next.github.io/i18next/ as out of date

### ISSUE THREAD

**Issue by jcoyne** [i18next/i18next#894]
I stumbled upon http://i18next.github.io/i18next/ looking for documentation, and was very confused as this documentation is not for 7.1.1. It would be nice if there was a banner warning that this is for an old version.

**Comment by jamuhl** [comment]
yes the official is on http://i18next.com - you're right with the banner - will try to add that if having time. Thank you.

**Comment by jamuhl** [comment]
done
