### ISSUE TITLE
Special characters cannot be used as interpolation format separators

### ISSUE THREAD

**Issue by SpeedoDevo** [i18next/i18next#895]
Strings containing regex special characters cannot be used as interpolation format separators, as they are [regex escaped](https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L25), even though the separator is [not used as a regex](https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L60-L68).

**Comment by jamuhl** [comment]
good catch...will be fixed for the next version...thanks for reporting
