### ISSUE TITLE
Cannot set default UnescapeSuffix/UnescapePrefix to undefined

### ISSUE THREAD

**Issue by bparish628** [i18next/i18next#897]
If setting the default interpolation option `{ unescapePrefix: undefined }`, it still will apply the `-` to the unescapePrefix in the interpolator.

Is there any reason why the interpolator is checking each other [here](https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L29)?

**Comment by jamuhl** [comment]
why you want to set that to undefined? if want to disable escaping generally set escape to false globally. or what is your use case for this?

**Comment by bparish628** [comment]
Back in the day, we used 1.7 and it didn't seem to apply this prefix. The key `__page__-__total__` would work fine. With the current version it doesn't interpolate that. We ran into a case where we want to be able to do that without adding spaces in between them, so that is why I thought it would be kosher to change the prefix.

**Comment by jamuhl** [comment]
basically that's for v1 compatibility: https://github.com/i18next/i18next/blob/master/src/compatibility/v1.js#L6 where you can set a suffix if no prefix is set (old was no prefix but suffix HTML).

Basically you could set the suffix (or init with compatibility flag for json) -> http://i18next.com/docs/migration/#v1-11-x--v2-0-0-comp

this will also backwards enable your plural suffixes!

**Comment by bparish628** [comment]
Oh cool! Thanks for that compatibility blob! It's very helpful. Since that compatibility flag will eventually go away, I assume it would be better just to set the suffix to what that blob does. 👍

**Comment by jamuhl** [comment]
json will stay for very long...has no cost...api compatibility might get removed some day in future

**Comment by jamuhl** [comment]
and even if removed...you still could set the needed values in options ;)
