### ISSUE TITLE
Allow users to change language in ng2-i18next-rc3-master

### ISSUE THREAD

**Issue by K69G4JRA725W** [i18next/i18next#898]
I downloaded example "ng2-i18next-rc3-master" and made it to work. But I would like to have the option for user to change language. I tried but can not figure out. Please help! My email:  858190729@qq.com . Thanks a lot!

**Comment by jamuhl** [comment]
you will need to ask this request over at the ng2-i18next: https://github.com/actimeo/ng2-i18next thank you...
