### ISSUE TITLE
Golbal defaultValue t options

### ISSUE THREAD

**Issue by jagu-sayan** [i18next/i18next#901]
Hello,

A cool feature it's to have a placeholder when the application load the locale.

By default we see the key in t. But in my project I have generic key like `app.welcome` or `menuFooter.appointmentMessage` (I don't know the text in advance) 
I want to see square placeholder "▢▢▢▢▢" and not the key `app.welcome` or `menuFooter.appointmentMessage`

To do that I can set defaultValue t option to "▢▢▢▢▢" in every translation I do.
Can be cool to have a global defaultValue option set in init options  ?

**Comment by jamuhl** [comment]
you can use: 

```
i18next.init({
  parseMissingKeyHandler: function(key) { return '▢▢▢▢▢'; }
});
```

**Comment by jagu-sayan** [comment]
It work, thank you very much !
