### ISSUE TITLE
i18next怎么配合jquery完成前端多语言国际化？

### ISSUE THREAD

**Issue by RelaxLiu** [i18next/i18next#902]
<head>

	<script type="text/javascript" src="./node_modules/jquery/dist/jquery.min.js"></script>

    <script type="text/javascript" src="./node_modules/i18next/i18next.min.js"></script>

     <script type="text/javascript">

  	  i18next.init({
		  lng: 'en',
		  resources: {
		    en: {
		      translation: {
		        "key": "hello world"
		      }
		    }
		  }
		}, (err, t) => {
		  // initialized and ready to go!
		  const hw = i18next.t('key'); // hw = 'hello world'
		});
     </script>
</head>

![Uploading WechatIMG1.jpeg…]()

最简单的demo，可是出不来国际化的东东，文档看的也不是很明白，不知道有没有大神可以指点指点，万分感谢！！！

**Comment by RelaxLiu** [comment]
html部分的代码传不上来就是ul标签里边三个li标签包裹三个a标签，属性是：data-i18next="translation.hw"

**Comment by jamuhl** [comment]
Sorry completely not understanding what you're writing...english might work better ;)

Guessing what you search is the jquery plugin for i18next - can be found here: https://github.com/i18next/jquery-i18next

**Comment by jamuhl** [comment]
closing for now...please feel free to reopen with clearification
