### ISSUE TITLE
Documentation for previous releases

### ISSUE THREAD

**Issue by nmschulte** [i18next/i18next#903]
Is there documentation available for previous releases?  It seems the website only hosts information pertinent to the current release.  I couldn't find any documentation for v3.4.4, hosted or otherwise.

**Comment by jamuhl** [comment]
if i remember right there is not much changed from v3 to v7...more or less major versions where due to edge cases (eg. webpack2 users on that time): http://i18next.com/docs/migration/

so the current docs should be still valid for 3.4.4.

**Comment by nmschulte** [comment]
Thanks.  I couldn't get the interpolation configuration override at call-site example to work w/ v3.4.4; the third example here: http://i18next.com/translate/interpolation/#escaping

**Comment by jamuhl** [comment]
Should work...but might be that was introduced sometime between 3.x and 7.x - but honestly it should be save to update from 3.4.4 to 7.x without bigger pains.

**Comment by nmschulte** [comment]
While it should be safe, I cannot upgrade unless I know it's safe, and that's not something I can ensure at the moment.

Clarification about the supported releases would go a long way, if documentation for prior releases is not intended to be available.

Configuring the escaping for interpolation via the key definition seems to work on v3.4.4, but not the special `interpolation: { ... }` property of the interpolation arguments that the third example in the current documentation shows.  This is either a bug or something that changed since v3.4.4 and wasn't disclosed.

Thanks for your support!

**Comment by jamuhl** [comment]
My recommendation is to update to latest if you need that feature. I can't reproduce if that worked or worked not on 3.4.4. Even if there would be a bug there wouldn't be a release 3.4.5 i do not have the time to support more then latest version. I hope you understand that...

**Comment by nmschulte** [comment]
I understand the difficulty, indeed.

> Clarification about the supported releases would go a long way, if documentation for prior releases is not intended to be available.

Perhaps this warrants a new issue?  I'll let you decide how to proceed.  Thanks again.
