### ISSUE TITLE
Problem using XHR backend with jquery-i18next

### ISSUE THREAD

**Issue by miyakoj** [i18next/i18next#905]
I've been having a lot of trouble getting i18next to work when using the XHR backend and jquery-i18next. I can get i18next + jquery-i18next to work when I add the translations as JSON to the page, but I need to have the translations in files. I get the same error for each key: i18next::translator: missingKey undefined translation [key]. My test en-US.json file is being successfully loaded. How do I handle this problem?

Here's the code I'm using:

```
i18next.use(window.i18nextXHRBackend)
.init({
	debug: true,
	whitelist: ['en-US', 'es'],
	fallbackLng: 'en-US',
	backend: {
		loadPath: 'langs/{{lng}}.json'
	}
}, (err, t) => {		
	jqueryI18next.init(i18next, $);
	$(document).localize();
});
```

Thanks in advance.

**Comment by jamuhl** [comment]
does the console state it did load the files successfully?

rather sure it does not load them...as path is wrong?!

**Comment by miyakoj** [comment]
The console says "[HTTP/1.1 200 OK 0ms]".

**Comment by jamuhl** [comment]
no i mean i18next - does console log state it loaded successful or failed?

does i18next.store.data contain your loaded resources?!?

```
	}
}, (err, t) => {		
   console.warn(i18next.store.data);
	jqueryI18next.init(i18next, $);
	$(document).localize();
});
```

**Comment by miyakoj** [comment]
Yes.

i18next::backendConnector: loaded namespace translation for language en-US Object { en-US: Object }

**Comment by jamuhl** [comment]
just saw your language is undefined - use the language detector plugin: https://github.com/i18next/i18next-browser-languageDetector

but that is not the cause as it will fallback to `en-US` in your setup.

what does `console.warn(i18next.store.data);` say? does it have some data...? rather strange...

**Comment by miyakoj** [comment]
It says: Object { en-US: Object }

This is the structure:

```
translation
  en-US
    translation
      footer
        desc
      header
        greeting
      main
        content
```

**Comment by jamuhl** [comment]
those missing are logged after loading success - really can see the mistake...missing only logs if missing - so i'm 100% that data is missing.

a) calling locize to early
b) calling on keys not in en-US file
c) idk

**Comment by miyakoj** [comment]
Well, here's the entire HTML page:

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Test Page</title>
</head>

<body>
<header><h2 data-i18n="header.greeting"></h2></header>
<main><p data-i18n="main.content"></p></main>
<footer><p data-i18n="footer.desc"></p></footer>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript" src="js/i18next.min.js"></script>
<script type="text/javascript" src="js/jquery-i18next.min.js"></script>
<script type="text/javascript" src="js/i18nextXHRBackend.min.js"></script>
<script type="text/javascript" src="js/i18nextBrowserLanguageDetector.min.js"></script>
<script type="text/javascript" src="js/i18nextLocalStorageCache.min.js"></script>

<script>
i18next.use(window.i18nextXHRBackend)
.init({
	debug: true,
	whitelist: ['en-US', 'es'],
	fallbackLng: 'en-US',
	backend: {
		loadPath: 'langs/{{lng}}.json'
	}
}, (err, t) => {		
	jqueryI18next.init(i18next, $);
	$(document).localize();
});
</script>
</body>
</html>
```

And here's the structure of the language file:

```
{
	"en-US": {
		"translation": {
			"header": {
				"greeting": "Hello World!"
			},
			"main": {
				"content": "This is my content."
			},
			"footer": {
				"desc": "This is a i18next test page."
			}
		}
	}
}
```

**Comment by jamuhl** [comment]
change your json to:

```
{
			"header": {
				"greeting": "Hello World!"
			},
			"main": {
				"content": "This is my content."
			},
			"footer": {
				"desc": "This is a i18next test page."
			}
		}
```

The loading route already has the language and namespace set - so no need to provide that in json files

**Comment by miyakoj** [comment]
Okay, that fixed it. Thanks for all your help.

**Comment by ferryMJ** [comment]
Internationalized to achieve, but the first page to load is the Chinese language, and wait a small minute under the refresh into English, how is this going on? Is there a good solution?please

**Comment by jamuhl** [comment]
there for sure is a solution - you just need to find it

**Comment by ferryMJ** [comment]
$(document).ready(function() {
i18n.init({
        lng: navigator.language,
        ns: { namespaces: ['translation', 'translation_js', 'agreement'], defaultNs: 'translation'},
        resGetPath: '/register/js/locales/__lng__/__ns__.json'
    }, function(t) {
        $('head').i18n();
        $('body').i18n();
    });
});
This is my main function.Please help to look at it and point out the problem,thank you!

**Comment by jamuhl** [comment]
you first see the original chinese that's in your html - solution might be removing innerHtml, text, ... from the nodes translated - so there is no initial content to show. so first thing a user sees is en as soon stuff is loaded and translation triggered.

**Comment by ferryMJ** [comment]
ok,thank you. and i find the problem that after loaded original html, loading jquery.js spends a lot time because it can not find dev, en...translate file. in my opintion(1.11.1), this version jquery i use will explore some stable files. after i add these files, the speed become fast obviously.

**Comment by ferryMJ** [comment]
sorry, jquery-1.11.1.min.js

**Comment by jamuhl** [comment]
hm...the only thing i could think of is your server not returning a 404 for the files not found -> if not getting a success or not found http status - i18next will try to reload that file until final failure - which would take some extra time. Getting a 404 it should be as fast as getting a 200 success (just being unable to translate). You might need to profile and search where the delay come from..

**Comment by sapnavyas** [comment]
Hi,

I am getting this error i18next::translator: missingKey undefined translation key 

here is my code..it is same as @miyakoj 's code ,
var backend = {
	loadPath: '/api/Locales'
};

var i18nOptions = {
	whitelist: ['en'],
	fallbackLng: 'en',
	debug: true,
	backend: backend
};

i18next.use(i18nextXHRBackend);
i18next.init(i18nOptions, function (err, t) {
	jqueryI18next.init(i18next, $);
	$("*[data-i18n]").localize();
});	

HTML - 	<button id="btn" data-i18n="key"></button>

my api server returns the following response ,
{"001":"Header","002":"Footer","003":"Content","004":"GoOnThen"}

I have tried by adding "en" and "translation" in the response but it isnt helping. 
i18next.store.data contains the same api response object. 

if I dont use backend and simple define recource property in init options it is working fine in html.
resources: {
		en: {
			translation: {
				"key": "hello world"
			}
		}
	}
Could please help me identify the issue? 

Thank you in Advance!

**Comment by jamuhl** [comment]
you server needs to return the same as you pass in resources.en.translation and you can't have the route omitting the language and namespace -> it needs to load one file per language and namespace pair.

means `/api/Locales/en/translation` should return

```
{
  "key": "hello world"
}
```

if you like to load all translations in all languages via `/api/Locales` (not recommended as you load to much) you can set `allowMultiLoading: true` in backend options https://github.com/i18next/i18next-xhr-backend and json has to look like:

```
en: {
translation: {
"key": "hello world"
}
}
```

**Comment by sapnavyas** [comment]
Thanks @jamuhl. 

I changed backend option to ,
var backend = {
	loadPath: '/api/Locales',
	allowMultiLoading: true
};
I don't have much data here so keeping everything in a single file. 

Also, I changed api to return the following response,
{"en":{"translation":{"001":"Header","002":"Footer"}}}

I am getting same "i18next::translator: missingKey undefined translation key" error.

**Comment by jamuhl** [comment]
"i18next::translator: missingKey undefined translation key" looks like you call `t(undefinded)` can you paste your complete sample or create a jsbin?

**Comment by sapnavyas** [comment]
I was using incorrect key. I forgot to change it after making changes for "allowMultiLoading: true". it is working with the suggestions you made. Thanks for you help!

**Comment by sapnavyas** [comment]
I am using i18nextChainedBackend for backend and to store api response into browser's memory. but do I have to call   i18next.init() on each page load? it doesnt work if I dont call it every timr my page is refreshed,

**Comment by jamuhl** [comment]
As long you do not have a single page application you need to call init on all pages (it's like good old stuff the complete page loads new)

**Comment by AleksandrBracyuk** [comment]
Please write in what form and how to download data. Such a good program and NO description - everyone guesses!
