### ISSUE TITLE
Deep/inner/nested keys do not work if key coincides with a string function.

### ISSUE THREAD

**Issue by rally25rs** [i18next/i18next#906]
If you have a translation json file that contains:

```
{
  "action": {
    "add": "Add",
    "search": "Search",
    "length": "Length"
  }
}
```

and you try to resolve "add", it works correctly:

```
i18next.t('action.add'); // "Add"
```

However, if you try to resolve "search" it actually returns the `string.search` function:

```
i18next.t('action.search'); // function search() { [native code] }
```

Same with "length":

```
i18next.t('action.length'); // 7
```

You can test that the returned value is actually the `string.search` function:

```
"".search === i18next.t('action.search'); // true
```

**Comment by jamuhl** [comment]
Thanks for reporting...rather interesting...will have a look asap and fix this.

**Comment by rally25rs** [comment]
So it seems that this does not happen if you use plain i18next. I think it is actually an issue with the XHR backend. I created an issue for them here: https://github.com/i18next/i18next-xhr-backend/issues/258
