### ISSUE TITLE
Namespaces documentation is not up to date

### ISSUE THREAD

**Issue by jzhang300** [i18next/i18next#907]
On the Namespace page (http://i18next.com/translate/namespace/)...

![screen shot 2017-04-12 at 11 12 30 am](https://cloud.githubusercontent.com/assets/1449523/24967830/fa774b4c-1f70-11e7-859d-056a223adb0a.jpg)

...there should be no space after colons.

**Acceptance Criteria**
- [x] Fix code samples to remove spaces after colon

**Comment by jamuhl** [comment]
will see what i can do

**Comment by jamuhl** [comment]
fixed now. thanks for reporting.
