### ISSUE TITLE
Creating a custom locale

### ISSUE THREAD

**Issue by zewa666** [i18next/i18next#910]
Hi there, first of all thanks for that awesome library. Its powering the [aurelia-i18n plugin](https://github.com/aurelia/i18n) and makes all of that nice and shiny things possible.

Now recently I was talking to one of our users about the possibility to create a custom locale, specifically to support local dialects. As an example in Austria the Styrian, Carinthian and Vorarlberg dialects do heavily differentiate in some specifics which would be well handled inside a custom locale. While doing so it would be also great to define multiple count possibilities instead of relying on the default plural forms. E.g.
0 -> none
1 -> a single
2 -> a pair
5 -> a bunch
1000+ -> a legion :)

When defining a new locale, it might make sense to fork them off existing ones, so as an example `de-AT` could be forked into `de-ST` or if that's a viable approach `de-AT-ST` for Styrian dialect.

**Comment by jamuhl** [comment]
i think https://www.w3.org/International/articles/bcp47/ is a great write up

correct would be de-AT-st i think...but honestly just guessing.

The problem with this is we currently just support scripts like `zh-Hans-HK`. Not sure if we have a problem in building a hierarchy on `de-AT-st` but i believe that should work to - but never tried. But for sure we could get that to work side by side.

Regarding plurals would be possible to extend that to search first for a specific language code and than for the less specific languages. https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L91

But honestly why...does styrian have different plural rules? i just now it from swissgerman dialects...all a little different but plural still is simple singular/plural?!?

regarding this topic we could have that open - would accept PR on this, or do it when a lot of free time - but very low on my personal list of stuff to support - as providing pages in local dialects is rather over the top i believe...not saying not valid...

**Comment by zewa666** [comment]
I'm totally with you with regards to priority, this is a rather low-prio feature request. The variant idea (of the provided link) is really interesting and would be a great way to achieve that.

Dialects actually do not have different plurals, this was more of a side question, since I wanted to be able to express counts in words using different locales.

0. keins
2. ein Paar
3. einige
10. ein Haufen (dialect)

**Comment by jamuhl** [comment]
For the special treatment of plurals there is some post processor called interval plural which might be what you search: http://i18next.com/translate/pluralInterval/

**Comment by zewa666** [comment]
Oh perfect, ok so we can scratch that of the request here. Thats exactly what I've been looking for, can't understand how I've overseen that one.

**Comment by zewa666** [comment]
Ok I've tried out the variant approach and it does work. Even with fallbacks from `de-AT-st` to `de-AT`.

**Comment by jamuhl** [comment]
hm...cool...didn't expect it ;)
