### ISSUE TITLE
nonExplicitWhitelist - rejecting non-whitelisted language warning

### ISSUE THREAD

**Issue by omaksi** [i18next/i18next#911]
My init params are ```{
whitelist: ['en'],
nonExplicitWhitelist: true,
lowerCaseLng: true
}```

I get the following warning for en-GB:

`i18next::languageUtils: rejecting non-whitelisted language code: en-gb`

Afterwards, the `en` language is loaded successfully

**Comment by jamuhl** [comment]
should work...can you paste your complete init code?

**Comment by omaksi** [comment]
`i18n
  .use(LanguageDetector)
  .init({
      whitelist: ['de', 'en'],
      nonExplicitWhitelist: true,
      lowerCaseLng: true,
      fallbackLng: {
          default: ['en']
      },
      detection: {
          caches: [],
          order: ['navigator', 'htmlTag'],
      },
      resources: {
          de: { translation: de },
          en: { translation: en },
      },
      debug: true,
  });`

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/pull/741

Not anymore clear what the use case of the behaviour was. But i personally nowadays would expect that en-GB passes whitelist test and gets loaded true.

but your code only provides en - so basically you would use load: 'languageOnly' and it would stay the same and just load 'en'

**Comment by omaksi** [comment]
I have kept `load: all` (default) So I expect the logic to be 

detected (en-GB) -> 
pass whitelist because of nonExplicit && contains 'en', no warning thrown, (en-GB) ->
lowerCaseLng: true (en-gb)->
load: all tries loading resource 'en-gb', doesn't find it, so loads 'en'.

**Comment by jamuhl** [comment]
sorry not had time to solve this...hopefully i find time to change this so nonExplicitWhitelist to pass for not only fallbacks (like it is now). Will need to make a major version as this might break behaviour on productive systems.

**Comment by jamuhl** [comment]
changes published in i18next@8.0.0
