### ISSUE TITLE
Load fallback language only when needed

### ISSUE THREAD

**Issue by anissaSanadtech** [i18next/i18next#912]
i'm setting the fallbackLng to 'en' but the fallback language's files seem to load even if there is no missing key, is there a way to specify that i need that fallbacklng file to be loaded only when needed ?

**Comment by jamuhl** [comment]
the point is - at that stage - you are too late...as loading is async. If you're sure not needing fallback - you can turn that completely off by setting fallbackLng to false

**Comment by anissaSanadtech** [comment]
i want to keep the fallback language but only load it if there's a missing key

**Comment by jamuhl** [comment]
on time you get a missing key - there is no way to load the resources and display that fallback...as that call is async while t function is sync.

so there is no way (technically) to achieve what you like - or at least i'm not aware of one. but still if someone able to provide a PR doing so - that would be more than welcome.

**Comment by anissaSanadtech** [comment]
thank you for your help and quick response

**Comment by Jessidhia** [comment]
It would be nice to be able to provide this through a plugin. It's now possible to tap into this with `react-i18next` v10 with Suspense enabled, at least -- as long as the invocation is during the render pass instead of an effect/lifecycle.

**Comment by jamuhl** [comment]
@Jessidhia just too much added complexity...and only works for react. If you need it - make sure you got 100% translated and you're good to go.
