### ISSUE TITLE
Missing not work

### ISSUE THREAD

**Issue by nanom1t** [i18next/i18next#914]
Hello.

I'm trying to integrate i18next to my Express.js application. The library looks really good and powerful. However a documentation is poor :(. Please add more examples and detailed description of params / functions.

For example, I'm using `i18next`, `i18next-node-fs-backend` and `i18next-express-middleware` in my Node.js app. I found saveMissing option in documentation and added it to my configuration.

```
var configs = require('../configs');
var i18next = require('i18next');
var i18nextFsBackend = require('i18next-node-fs-backend');
var i18nextMiddleware = require('i18next-express-middleware');

var options = {
    lng: 'ru-RU',
    lngWhitelist: ['en-US', 'ru-RU'],
    ns: ['common'],
    defaultNs: 'common',
    fallbackNS: 'common',
    fallbackLng: 'en-US',
    fallbackOnNull: true,
    fallbackOnEmpty: true,
    **saveMissing: true,
    saveMissingTo: 'current',**
    useCookie: true,
    cookieName: 'lang',
    backend: {
        **loadPath: configs.APP_ROOT + '/../configs/locales/{{lng}}/{{ns}}.json',
        addPath: configs.APP_ROOT + '/../configs/locales/{{lng}}/{{ns}}.missing.json'**
    },
    detection: {},
    ignoreRoutes: ['img/']
};

i18next
    .use(i18nextFsBackend)
    .init(options);
```
Also I've added middleware and routes:
```
app.use(i18nextMiddleware.handle(i18next, {}));
app.get('/locales/resources.json', i18nextMiddleware.getResourcesHandler(i18next));
app.post('/locales/add/:lng/:ns', i18nextMiddleware.missingKeyHandler(i18next));
```
Localization works well, locales are loading from Node.js app and resource routes. However I cannot imitate saveMissing feature or it does not work for me. In my Jade template I'm trying to load non-existing key from locales:
```
= t('common:NAVIGATION_PROFILE_SETTINGS222')
```
`NAVIGATION_PROFILE_SETTINGS222` - does not exists in my locales. I've enabled saveMissing option and added addPath, so I'm expecting to get new missing file here: `/locales/{{lng}}/{{ns}}.missing.json`, but it does not appear there. What is wrong or how does this feature work?

Thanks

**Comment by jamuhl** [comment]
Should work. At least i don't see an issue with your configuration at first sight. Try adding debug: true to your i18next options and have an eye on console.log - does it state that the key `NAVIGATION_PROFILE_SETTINGS222` is missing?

**Comment by jamuhl** [comment]
Regarding the lack of documentation...i'm aware of this. But this is OSS - everyone is invited to improve. As i have a life beside i18next, family, a job...that's the best i could provide for now.

**Comment by nanom1t** [comment]
Thanks for your response. Here is my output from console with debug option:
```
i18next: languageChanged ru-RU
i18next: initialized { debug: true,
  initImmediate: true,
  ns: [ 'common', 'labels' ],
  defaultNS: 'common',
  fallbackLng: [ 'ru-RU' ],
  fallbackNS: [ 'common' ],
  whitelist: false,
  nonExplicitWhitelist: false,
  load: 'all',
  preload: false,
  simplifyPluralSuffix: true,
  keySeparator: '.',
  nsSeparator: ':',
  pluralSeparator: '_',
  contextSeparator: '_',
  saveMissing: true,
  saveMissingTo: 'current',
  missingKeyHandler: false,
  postProcess: false,
  returnNull: true,
  returnEmptyString: true,
  returnObjects: false,
  joinArrays: false,
  returnedObjectHandler: [Function: returnedObjectHandler],
  parseMissingKeyHandler: false,
  appendNamespaceToMissingKey: false,
  appendNamespaceToCIMode: false,
  overloadTranslationOptionHandler: [Function: overloadTranslationOptionHandler],
  interpolation: 
   { escapeValue: true,
     format: [Function: format],
     prefix: '{{',
     suffix: '}}',
     formatSeparator: ',',
     unescapePrefix: '-',
     nestingPrefix: '$t(',
     nestingSuffix: ')',
     defaultVariables: undefined },
  lng: 'ru-RU',
  lngWhitelist: [ 'ru-RU' ],
  fallbackOnNull: true,
  fallbackOnEmpty: true,
  useCookie: true,
  cookieName: 'lang',
  backend: 
   { loadPath: '/vagrant/configs/../app/../configs/locales/{{lng}}/{{ns}}.json',
     addPath: '/vagrant/configs/../app/../configs/locales/{{lng}}/{{ns}}.missing.json' },
  detection: {},
  ignoreRoutes: [ 'img/' ] }
```
`NAVIGATION_PROFILE_SETTINGS222` is missing as well as any other not existing key
```
= t('common:NOT_EXISTING_KEY')
```
Also I do not see any errors about missing key in console with debug mode. Maybe, `saveMissing` option does not work in Jade(pug) templates? Is it work only for front-end version (not for templates) ?

Thanks

**Comment by nanom1t** [comment]
I've found solution :) The problem was with folder permissions. This feature require write permission. Maybe this requirement should be added to documentation.

Thanks for your time.
