### ISSUE TITLE
Keys used for translation instead of values

### ISSUE THREAD

**Issue by webdevbe** [i18next/i18next#915]
Hi Jan,

Perhaps I'm missing something but currently the DOM elements I've marked for translation (by adding the data-i18n attribute are not being translated correctly on render. My init code looks like this:
`i18n.init({
        lng: 'en',
        debug: true,
        fallbackLng: 'en',
        resGetPath: "/locales/__ns__-__lng__.json",
        ns: {
            namespaces: ['translation']
        }
    }, function() {
        Backbone.history.start({pushState: true, root: '/'});
    });`

The browser console logs:
`currentLng set to: en`
`loaded: /locales/translation-en.json``

The JSON structure is like this:
`{ "username": "it works"}`

The HTML attribute looks like this:
`<label for="username" data-i18n="username"></label>`

Yet, when I call translation on render : `this.$el.html(this.template()).i18n();`
The key(username) is put as text instead of the value (It works)

As I said before, it might be something simple, but could not find it till this time.
Thanks for the help!

Ps. version = 1.6.3

**Comment by jamuhl** [comment]
what version of i18next are you using?

**Comment by jamuhl** [comment]
ah sorry 1.6.3 i see now...hm

**Comment by jamuhl** [comment]
loading is ok...rather sure calling `i18next.t('username')` will give you "it works" back.

honestly did no backbone for ages...do you use handlebars or mustache for templates? if so i would suggest not using those jquery translation stuff but adding t helpers to your template engine: http://i18next.github.io/i18next/pages/doc_templates.html

**Comment by boymngdata** [comment]
Hmm calling this: `console.log(i18n.t('username'))` also logs 'username' (I'm including i18next with require as i18n)

**Comment by jamuhl** [comment]
you call console.log(i18n.t('username')) in the init callback?

**Comment by webdevbe** [comment]
Hmm calling this: console.log(i18n.t('username')) also logs 'username' (I'm including i18next with require as i18n). At first I thought it was a timing issue but running : $('label[for="username"]').i18n(); in the console, made no difference.

I'm using Handlebars, let me just try your advice on that.

**Comment by webdevbe** [comment]
Yes, that's right. the console log was run in the init callback.

**Comment by jamuhl** [comment]
try:

```
i18n.init({ 
lng: 'en', 
debug: true, 
fallbackLng: 'en', 
resGetPath: "/locales/__ns__-__lng__.json", 
ns: { namespaces: ['translation'], defaultNs: 'translation' } }, 
function() { Backbone.history.start({pushState: true, root: '/'}); });
```

defaultNs in ns option, think that is missing

**Comment by webdevbe** [comment]
That did the trick, thank you so much for the quick support!

**Comment by jamuhl** [comment]
you're welcome

**Comment by muhsalaa** [comment]
how can i get key from translation? something like t('Welcome home') will result to its key, e.g  'welcome.text'

**Comment by jamuhl** [comment]
@muhsalaa did you follow   https://www.i18next.com/overview/getting-started

**Comment by adrai** [comment]
@muhsalaa do you mean reverse? A specific key from a given vaue?
Why do you need this? Maybe setting language to cimode is what you are looking for.

**Comment by muhsalaa** [comment]
@adrai yes, I want to reverse translation to its key. My case is I have a dropdown component in which the selected value is a translated string. However, when I change the language, only the dropdown options changed, not the currently selected value. My idea is, I can convert the translated string to its key, then translate it again to current language

**Comment by jamuhl** [comment]
@muhsalaa you already have the key - you call the t function with it. Beside that...bad idea to use translated values as selected value...`<option value="key">value</option>`

**Comment by muhsalaa** [comment]
@jamuhl yup. that was the first thing come to my mind when dealing with this case. My problem is I'm just a maintainer of the already big codebase. when I put the `t` inside the component, I should change options in all pages. Thanks for the warm and fast responses, I think I should propose for code refactoring.
