### ISSUE TITLE
Using a translation in a javascript string only works when using a return statement

### ISSUE THREAD

**Issue by webdevbe** [i18next/i18next#916]
Hi Jan,

I've been trying i18next today which looks cool with my Handlebars templates but there is just one thing I can't get my head around, neither can I find a solution online. Whenever I try to use a translated variable in e.g. a Javascript string, I have to use a return statement to effectively get it. 

E.g. this piece of code won't work:
`nameEmpty: {`
    `message:  i18n.t('errors.validation.general.nameEmpty');`
    `class: 'name'`
`},`

But this will:
`nameEmpty: {`
    `message: function() {`
        `return i18n.t('errors.validation.general.nameEmpty');`
    `},`
    `class: 'name'`
`},`

It looks like there is no default return what makes me feel like I'm missing something here.
Could you have a look please?

Thanks!

**Comment by jamuhl** [comment]
the only difference i see in your code is timing.

on second you will call nameEmpty.message() to get the value. On first it will t will be called already and the value is on nameEmpty.message

if first returns the key or empty string i'm rather sure that was called to early when i18next did not yet initialize (loaded translations)

**Comment by jamuhl** [comment]
any more insights on this...? could you please provide a sample to reproduce this?

**Comment by jamuhl** [comment]
closing for now...feel free to reopen if still an issue
