### ISSUE TITLE
Recursive nesting at interpolation

### ISSUE THREAD

**Issue by DarkerTV** [i18next/i18next#917]
Hi, I'm currently developing a little Node JS application and I were using your nice library when I noticed a potential problem in nesting. Currently if you do this
```js
i18next.t('test', {
  input: '$t(test)',
});
```
with this json file
```json
{
  "test": "{{input}}"
}
```
You get this error `RangeError: Maximum call stack size exceeded`. 

Obviously this is different in my application but I wanted to simplify the problem. Is there any way to solve this problem, like avoid to process nesting from interpolation.

**Comment by jamuhl** [comment]
You interpolate a nesting construct into a value and don't want it to be executed? Sorry i don't get that use case?

I know there can be circular nestings - but only thing i could do there would be to break that. So better get an error.

**Comment by DarkerTV** [comment]
As I said this is a very simplified case, let me explain better. Currently my code look like this
```js
i18next.t('result', {
  userInput: args,
  result,
});
```
```json
{
    "result": "Your input is {{userInput}} and the execution result is {{result}}"
}
```
My application code will be public so anyone will be able to look how my translations are done, and I'm afraid of this problem because if the userInput contains a nesting it get processed and some malicious user can try to use this.

A way to avoid this problem could be add an option to disable the nesting at interpolations at initialize or at TranslationFunction.

**Comment by jamuhl** [comment]
Wouldn't it be saver to input your userinput...?

**Comment by jamuhl** [comment]
but anyway...would be rather easy to implement: https://github.com/i18next/i18next/blob/master/src/Translator.js#L176

just add a `if (options.nest !== false)` in front and call `t('key', { nest: false });`

if you like you can provide a PR or i will add this for the next version (no big deal).

**Comment by DarkerTV** [comment]
Yes, I only mean that it would be and useful option in some cases, if you don't think like me I can do something like you have in your code.
```js
const userInput = args.replace(/\$/g, '$$$$');
```
Just for some reason I don't feel right to modify the original user content.

**Comment by DarkerTV** [comment]
I can send the PR in some hours :)

**Comment by jamuhl** [comment]
awesome...will try to publish an updated version asap.
