### ISSUE TITLE
Little change in the body of your method "getResource" about "keySeparator"

### ISSUE THREAD

**Issue by workzer** [i18next/i18next#921]
Hi, I just had a problem apparently because the condition:
```javascript 
if (keySeparator === undefined) keySeparator = '.';
```
isn't enough, I called this method with a sting like:
```javascript
console.info(window.i18next.getResource(window.i18next.language, window.i18next.options.ns[0], $(element).attr("data-i18n"));
```

$(element).attr("data-i18n") is respectively: __testtitle2Ori.test2__
catched inside a external file like:
```json
{
"testtitleOri": {
    "test1": "plop (en)",
    "test2": "plop test (en) 2"
  }
}
```
After the test for 'keySeparator' (mentioned  above), the value of __keySeparator__ is __false__
so I just add a supplement:
```javascript
if (keySeparator === undefined || !keySeparator) keySeparator = '.';
```
Everything is ok now.

Final method:
```javascript
  ResourceStore.prototype.getResource = function getResource(lng, ns, key) {
    var options = arguments.length > 3 && arguments[3] !== undefined ? arguments[3] : {};

    var keySeparator = options.keySeparator || this.options.keySeparator;

    if (keySeparator === undefined || !keySeparator) keySeparator = '.';

    var path = [lng, ns];
    if (key && typeof key !== 'string') path = path.concat(key);
    if (key && typeof key === 'string') path = path.concat(keySeparator && key.indexOf(keySeparator) > -1? key.split(keySeparator) : key);

    if (lng.indexOf('.') > -1) {
      path = lng.split('.');
    }

    return getPath(this.data, path);
  };
```
I added one more test ` && key.indexOf(keySeparator) > -1`to be sure for each browser, I didn't have time to make all tests.

Cordially.

**Comment by jamuhl** [comment]
if keySeparator is false we should not set it to `.` as this would lead to wrong behaviour (setting it to false means you have keys that might reflect source language having a lot of puctuation).

But there is an issue...we should check if there is `!keySeparator` and in this case not split the key.

**Comment by workzer** [comment]
Thank you for your answer, so finally there is no default value for `keySeparator` because of the diversity of languages ? (understandable)

So finally the only good way is to use the option `keySeparator` for each case.

*But there is an issue...we should check if there is !keySeparator and in this case not split the key.*

we have nothing to change at your code for that, it's the actual comportment, if I don't define the option `keySeparator`, my string __testtitle2Ori.test2__ isn't splitted.

It's just that when I saw this part: `    if (keySeparator === undefined) keySeparator = '.';`
I thought that you would a default value and if it's true, maybe the good thing is to define it like I explain before and for us, if we use a special sources language (with a lot of punctuation), we have just to define the option in the third parameter.
 
am i wrong ?

**Comment by jamuhl** [comment]
it's all about this:  http://i18next.com/translate/keyBasedFallback/

another question - what is your usecase to use `i18next.getResource` ? we more or less use that just internal inside the `t` function - the getResource function is public and can be used, so just asking to learn how people use i18next...

**Comment by workzer** [comment]
Hi, thank your for your informations.
I use `getResource` to make my own code to catching all attribut __data-i18n__  then get the associated value and change DOM.

I'm gonna see to maybe integer: https://github.com/i18next/jquery-i18next
or https://github.com/i18next/i18nextify like recommended by you.

Thank you, all of this was because all exemples that I found online show simple code to translate `t` and elements with attribute `data-i18n`, it was confuse for me.

P.S: I appreciate really the public access to i18next.getResource.

Thank you again.

**Comment by jamuhl** [comment]
Could be closed i think...if not let me know...so we could reopen.
