### ISSUE TITLE
Do we have to use ecosystem framework for data-i18n

### ISSUE THREAD

**Issue by workzer** [i18next/i18next#922]
All is in my title, I spent a lot of time today to try to understand what I have to do to change value of all my html elements which have the attribute __data-i18n__.

Apparently after the version 1, you decided to separate jquery of your main page.

My question is, if I just add just your main document (i18next.min.js) to my web[site|app] and that I expect change all my 'data-i18n', do I have to make my own code using `getResource` or use another file like 'jquery-i18next' ?

My question can appear very easy but I found a lot of resources online with old code (old version) and nothing >= 2.

Cordially.

**Comment by jamuhl** [comment]
yes...that old samples are a little of a problem.

the i18next.js itself is just a core...to use it with more comfort in react, angular, ... there are the plugin

means for your case yes...if you like that data-i18n stuff + jquery you need https://github.com/i18next/jquery-i18next

or the even more modern approach using a virtualdom implementation: https://github.com/i18next/i18nextify

and if you like to support us in future you might even have a look at http://locize.com - "i18n as a service" layer
