### ISSUE TITLE
No backend was added via i18next.use. Will not load resources.

### ISSUE THREAD

**Issue by leeshuang** [i18next/i18next#923]
excuse me，I use framwork7 to build my project，but I can not load resources from my jason object,
It reuturns an error: No backend was added via i18next.use. Will not load resources.
```
i18next.init({
        "debug": true,
        "initImmediate": true,
        "lng": "en",
        //        "fallbackLng": "en",
        "prefix": "{",
        "suffix": "}",
        "backend": {
            "loadPath": "locales/{lng}/{ns}.json"
        }
    }, function (err, t) {
        i18next.t('title');
    })
```
and the console show message"missingKey en translation title title"
I dont know how to solve it .
Any help is appreciated!

**Comment by jamuhl** [comment]
you will need to add the xhr backend to load resources: http://i18next.com/docs/#add-plugins

https://github.com/i18next/i18next-xhr-backend

**Comment by leeshuang** [comment]
it runs.Thank you very much

**Comment by AleksandrBracyuk** [comment]
Please write in what form and how to download data. Such a good program and NO description - everyone guesses!
