### ISSUE TITLE
how to use html tags in translations?

### ISSUE THREAD

**Issue by bonesoul** [i18next/i18next#924]
i've checked docs and stackoverflow but can't find a solution;

`"rules": "<a href='/sartlar/' target='_blank'><strong>Kullanım şartlarına</strong></a> uygun olmayan yorumlar, moderasyon ekibimiz tarafından silinecektir."`

i can't get it working by;

```
i18n.t('comment:labels.rules', { escapeInterpolation: true })
i18n.t('comment:labels.rules', { interpolation: { escapeValue: false } })
```

any ideas?

**Comment by jamuhl** [comment]
there is no interpolation done for that string.

i18n.t('comment:labels.rules') does return `<a href='/sartlar/' target='_blank'><strong>Kullanım şartlarına</strong></a> uygun olmayan yorumlar, moderasyon ekibimiz tarafından silinecektir.`

where do you use that? react.js or any other framework escaping content?

**Comment by jamuhl** [comment]
do a `console.log(i18n.t('comment:labels.rules'))` rather sure returned value is correct. Just the framework you use for view rendering saves you from possible xss.

**Comment by bonesoul** [comment]
@jamuhl you are right, i've fixed it with nunjucks "| safe " attribute.
