### ISSUE TITLE
nested `"$t(key)"` Object lookup, inside of returned Object?

### ISSUE THREAD

**Issue by foxtree** [i18next/i18next#925]
Hi, is it possible to use `{returnObjects: true}` such that the values of nested `"$t()"` properties can yield either an `Object` or an `Array` -- and not be stringified?

e.g., in my locales `.json` file, I have something like:
```
{
  "translation": {
    "nested-array": [
      {
        "title": "AAA",
        "value": "XXXXX"
      },
      {
        "title": "BBB",
        "value": "YYYYY"
      },
      {
        "title": "CCC",
        "value": "ZZZZZ"
      }
    ]
  },
 "another-thing": {
    "foo": "bar",
    "lookup-something-else": "$t(nested-array)"
  }
}
```

Invoking `i18next.t('another-thing') ` will return:
```
{
  "foo":"bar",
  "lookup-something-else": "[object Object],[object Object],[object Object]"
}
```

Thanks!

**Comment by jamuhl** [comment]
did you try: `i18next.t('another-thing', { returnObjects: true })` ? that should work i think: https://github.com/i18next/i18next/blob/master/src/Translator.js#L102

did you set joinArray option to `,`?!? if so set that to false for the t call...seems it joins those values.

Let me know if this solves the issue...else i will dig deeper into this.

**Comment by foxtree** [comment]
The documented  `{ returnObjects: true }` functionality works -- however, it seems I may be asking about a feature that is not supported:

Can the returned `Object`, itself, reference other Objects, using the `"$t(<key-references-array>)"` notation?   

It seems that *nested* references are stringified -- and:  "`t$(<key-references-array>)`" is possibly too ambiguous for what I'm asking, b/c maybe it *should* return a String?

**Comment by foxtree** [comment]
It seems that  [this line of code](https://github.com/i18next/i18next/blob/4caedbf610fe48c347b3448d76b703a9b07dfaed/src/Interpolator.js#L127)
``` if (typeof value !== 'string') value = utils.makeString(value);```

**Comment by foxtree** [comment]
It seems that  stringification occurs via [this line of code](https://github.com/i18next/i18next/blob/4caedbf610fe48c347b3448d76b703a9b07dfaed/src/Interpolator.js#L127)
``` if (typeof value !== 'string') value = utils.makeString(value);```

**Comment by jamuhl** [comment]
sorry should have written you before...looking into it right now...

will add: `if (value && match[0] === str && typeof value !== 'string') return value;` before makeString call

that passes the test...will run other tests and publish an update soon

**Comment by jamuhl** [comment]
try with i18next@8.3.0

**Comment by jamuhl** [comment]
works?

**Comment by foxtree** [comment]
Yes, it works -- and support for such nested lookup of keys is awesome.
