### ISSUE TITLE
http://www.i18next.com/ is down

### ISSUE THREAD

**Issue by niieani** [i18next/i18next#926]
The website (and docs) are currently not functional. The server (62.116.130.8) is responding (200) with the message:

```
Sorry, no Host found
```

**Comment by jamuhl** [comment]
updated dns to link to new documentations...could you ping me again if not working in a few minutes (works at my place already)

**Comment by jamuhl** [comment]
seems dns changes get not stored proper on registrar...will fix asap

**Comment by eko24ive** [comment]
@jamuhl still can't reach it.
wish you luck to fix it !

**Comment by jamuhl** [comment]
for both: http://www.i18next.com and http://i18next.com ?!?

**Comment by niieani** [comment]
It's fixed! Thanks for the prompt action.

**Comment by p-j** [comment]
For me at the moment:
http://www.i18next.com :white_check_mark: 
http://i18next.com :x:

**Comment by jamuhl** [comment]
good to hear...thanks for the update

**Comment by jamuhl** [comment]
@p-j yes...had to change to domain forwarding for using gitbook...that might need some extra time to propagate through all caches :(

**Comment by eko24ive** [comment]
same situation as @p-j wrote

**Comment by jamuhl** [comment]
keeping this open until stable - so others can find the info

**Comment by webpn** [comment]
**www.i18next.com** is OK
**i18next.com** is still DOWN (https://www.whatsmydns.net/#A/i18next.com)

**Comment by bigset1** [comment]
For me at the moment:
http://www.i18next.com ❌
http://i18next.com ❌

**Comment by jamuhl** [comment]
better now?

**Comment by eko24ive** [comment]
@jamuhl both is up for me, but loading speed is slow: ~15sec passed until complete DOM render

**Comment by webpn** [comment]
https://i18next.com/  **DOWN**
http://i18next.com/ UP (redirects to https://www.i18next.com/)

https://www.i18next.com/  UP
http://www.i18next.com/ UP (redirects to https://www.i18next.com/)

**Comment by webpn** [comment]
It seems to be an SSL issue: DNS propagated correctly.

**Comment by jamuhl** [comment]
seems like that could not be solved that easy...seems to be not working on the web forwarding service which forwards i18next.com to www.i18next.com

**Comment by jamuhl** [comment]
@eko24ive replaced the movie on the start page with an image...better now?

**Comment by niieani** [comment]
For me i18next.com stopped working. When going to www.i18next.com though, it works.

**Comment by eko24ive** [comment]
@jamuhl yes, much better !
Both websites loads in a moment, thank you !

**Comment by jamuhl** [comment]
closing for now...seems stable beside no https for the i18next.com
