### ISSUE TITLE
loadPath and URL problem

### ISSUE THREAD

**Issue by obykoo** [i18next/i18next#927]
```
 backend: {
            // path where resources get loaded from
            loadPath: 'assets/locales/{{lng}}/{{ns}}.json',

            // path to post missing resources
            addPath: 'assets/locales/{{lng}}/{{ns}}.missing.json',

            // jsonIndent to use when storing json files
            //  jsonIndent: 2
        },
```

When I am on http://mydomain/something , then correct resources are loaded from http://mydomain/assets/locales/...json , but when I am on  http://mydomain/something/something , then resources are loaded from http://mydomain/something/assets/locales/...json which is incorrect

How to fix this without using windows.location ?

**Comment by jamuhl** [comment]
is that for xhr-backend? the config looks like from fs-backend for node.

https://github.com/i18next/i18next-xhr-backend#backend-options

`loadPath: '/assets/locales/{{lng}}/{{ns}}.json',` <- add a `/` on front

**Comment by obykoo** [comment]
Oh yeah you are right I posted it into wrong repository. I am sorry for this.

And adding "/" does not seem to help anyway thanks.

**Comment by jamuhl** [comment]
if it should be fs-backend you might do `__dirname + your path`
