### ISSUE TITLE
Disable the backend i18next cookie, sometimes

### ISSUE THREAD

**Issue by laurentdebricon** [i18next/i18next#929]
Hello,
for all my routes like :
i18nextMiddleware.addRoute(i18next, '/:lng/hello

the backend always return with a i18next cookie.
In some case, for exemple i'm on the website in english, but i want some data by ajax from a french route, i don't want my browser to receive a cookie i18next (set at 'fr').

I could do in the ajax call
`res.clearCookie('i18next');`

but it is not what I want, because it is informing the client to delete the cookie.
Do you know how i can remove this cookie ?

Best regards.

**Comment by jamuhl** [comment]
the only way i would see is to set some flag on req (eg. req.noCacheLng) and then in that case not write the cache the lng (eg. to cookie):

https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L18
https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L52

you would than have to add a middleware setting that before the i18next.handle middleware

**Comment by laurentdebricon** [comment]
Ok, 

so with express it's not possible to undo a 
`cookies.set()`

in the same request.
Thanks for your work and the code lines. I'll do something else :)

**Comment by jamuhl** [comment]
closing for now...feel free to reopen
