### ISSUE TITLE
i18n for JS in Nashorn

### ISSUE THREAD

**Issue by plata** [i18next/i18next#931]
Is it possible to use i18next to translate Strings in JavaScript executed by Nashorn?

I managed to get it running with a slightly modified version of <https://unpkg.com/i18next/i18next.js> (which is linked on <https://www.i18next.com/getting-started.html>). I removed
```Javascript
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(global.i18next = factory());
}(this, (function () { 'use strict';
```
and the content of `consoleLogger:output`.

Is there a better way to use i18next with Nashorn?

**Comment by jamuhl** [comment]
in the dist folder you find commonjs and es6 builds those have no UMD export of the module.

Regarding the logger you can add a own logger: https://www.i18next.com/misc/creating-own-plugins.html#logger

`i18next.use(yourLogger);` so there are no console.log

**Comment by plata** [comment]
Thanks. I will have a look.
