### ISSUE TITLE
Plurals cannot be found

### ISSUE THREAD

**Issue by aubrey-fowler** [i18next/i18next#932]
In my json I have the following:
{
                        "DAYWithCount": "{{count}} Day",
                        "DAYWithCount_plural": "{{count}} Days",
}

When I do this
            console.log($i18next.t('DAYWithCount', { count: 1 }));
            console.log($i18next.t('DAYWithCount', { count: 2 }));

I get this error:

i18next::pluralResolver: no plural rule found for en

**Comment by jamuhl** [comment]
only way to get that would be to have a non initialized instance i think:

pluralResolver gets created here: https://github.com/i18next/i18next/blob/master/src/i18next.js#L75 inside the init call

pluralResolver creates rules on instance creation: https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L85

en is here: https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L9

and the error you get comes from: https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L138 when no rule was found...which is strange in your case...

did you init the instance? `i18next.init(...)`

**Comment by aubrey-fowler** [comment]
Yes, I did the init:

    window.i18next.init({
        debug: true,
        lng: _actual, // If not given, i18n will detect the browser language.
        fallbackLng: _default, // Default is dev
        resources: _resources,
        useCookie: false,
        useLocalStorage: false,
        joinArrays: '<br />'
    });

**Comment by jamuhl** [comment]
is that the same instance as $i18next? do you overwrite plural rules...

can you `console.log($i18next.services.pluralResolver.rules` rather sure it's undefined

**Comment by aubrey-fowler** [comment]
Instead of 'en' I am using 'English'. There is an application-specific reason why. How can I use the rules?

Here is the output of console.log($i18next.i18n)

I18n {observers: Object, options: Object, services: Object, logger: Logger, modules: Object…}
addResource
:
function ()
addResourceBundle
:
function ()
addResources
:
function ()
format
:
function format(value, _format, lng)
getResource
:
function ()
getResourceBundle
:
function ()
hasResourceBundle
:
function ()
isInitialized
:
true
language
:
"English"
languages
:
Array(1)
logger
:
Logger
modules
:
Object
observers
:
Object
options
:
Object
removeResourceBundle
:
function ()
services
:
Object
backendConnector
:
Connector
cacheConnector
:
Connector
interpolator
:
Interpolator
languageUtils
:
LanguageUtil
logger
:
Logger
pluralResolver
:
PluralResolver
languageUtils
:
LanguageUtil
logger
:
Logger
options
:
Object
rules
:
Object
__proto__
:
Object
resourceStore
:
ResourceStore
__proto__
:
Object
store
:
ResourceStore
translator
:
Translator
__proto__
:
EventEmitter

**Comment by jamuhl** [comment]
i don't need console.log($i18next.i18n) i need `console.log($i18next.i18n.services.pluralResolver.rules)`

Why you need to work with English ?!? map that to `en` all i18n frameworks work with language codes...not with names

**Comment by aubrey-fowler** [comment]
Well I need to have separation between en-GB and en-US and en-CA. There are specific spellings and phrases that are specific to the three. Will that work with the plural rules?

console.log($i18next.i18n.services.pluralResolver.rules)
Here it is:

Object {ach: Object, ak: Object, am: Object, arn: Object, br: Object…}ach: Objectaf: Objectak: Objectam: Objectan: Objectar: Objectarn: Objectast: Objectay: Objectaz: Objectbe: Objectbg: Objectbn: Objectbo: Objectbr: Objectbs: Objectca: Objectcgg: Objectcs: Objectcsb: Objectcy: Objectda: Objectde: Objectdev: Objectdz: Objectel: Objecten: Objecteo: Objectes: Objectes_ar: Objectet: Objecteu: Objectfa: Objectfi: Objectfil: Objectfo: Objectfr: Objectfur: Objectfy: Objectga: Objectgd: Objectgl: Objectgu: Objectgun: Objectha: Objecthe: Objecthi: Objecthr: Objecthu: Objecthy: Objectia: Objectid: Objectis: Objectit: Objectja: Objectjbo: Objectjv: Objectka: Objectkk: Objectkm: Objectkn: Objectko: Objectku: Objectkw: Objectky: Objectlb: Objectln: Objectlo: Objectlt: Objectlv: Objectmai: Objectmfe: Objectmg: Objectmi: Objectmk: Objectml: Objectmn: Objectmnk: Objectmr: Objectms: Objectmt: Objectnah: Objectnap: Objectnb: Objectne: Objectnl: Objectnn: Objectno: Objectnso: Objectoc: Objector: Objectpa: Objectpap: Objectpl: Objectpms: Objectps: Objectpt: Objectpt_br: Objectrm: Objectro: Objectru: Objectsah: Objectsco: Objectse: Objectsi: Objectsk: Objectsl: Objectso: Objectson: Objectsq: Objectsr: Objectsu: Objectsv: Objectsw: Objectta: Objectte: Objecttg: Objectth: Objectti: Objecttk: Objecttr: Objecttt: Objectug: Objectuk: Objectur: Objectuz: Objectvi: Objectwa: Objectwo: Objectyo: Objectzh: Object__proto__: Object
i18next.js:167 i18next::pluralResolver: no plural rule found for: English
output @ i18next.js:167
warn @ i18next.js:158
forward @ i18next.js:227
warn @ i18next.js:205
getSuffix @ i18next.js:1251
(anonymous) @ i18next.js:927
(anonymous) @ i18next.js:920
(anonymous) @ i18next.js:917
resolve @ i18next.js:904
translate @ i18next.js:780
t @ i18next.js:2112
I18nTranslateService.translate @ ng-i18next.js:308
I18nTranslateService.t @ ng-i18next.js:265
$scope.display @ balance.controller.js:442
fn @ VM294:4
(anonymous) @ ionic.bundle.min.js:159
$digest @ ionic.bundle.min.js:174
$apply @ ionic.bundle.min.js:177
(anonymous) @ ionic.bundle.min.js:190
e @ ionic.bundle.min.js:79
(anonymous) @ ionic.bundle.min.js:82

**Comment by jamuhl** [comment]
all english variants have the same language and because of that the same rule for plurals.

even more i18next does fallback from `en-US` to `en` if a key was not found in en-US: https://www.i18next.com/principles/fallback.html#locals-resolving

console output looks ok...just use the language codes: `en-US`, `en-CA`, ... `en`

**Comment by aubrey-fowler** [comment]
OK thanks for your help!
