### ISSUE TITLE
Dynamically loaded translations not found with addResourceBundle

### ISSUE THREAD

**Issue by aubrey-fowler** [i18next/i18next#934]
In my app Angular 1.5.3 my user will login and get the translations when the login response comes back from the server. I get JSON with the translations.

Here is my language service:
`(function () {

    "use strict";

    angular
        .module('myApp')
        .service('languageService', ['$i18next',
            function ($i18next) {

                var languageService = {};

                languageService.save = function (langObj) {

                    for (var i = 0; i < langObj.languages.length; i++) {
                        $i18next.i18n.addResourceBundle(langObj.languages[i], 'translations', langObj[langObj.languages[i]]);
                    }

                    console.log('      ', $i18next.t('ABSENCE_DETAIL')); //prints out ABSENCE_DETAIL

                    if ($i18next.i18n.language !== langObj.actual) {
                        $i18next.i18n.changeLanguage(lng);
                    }

                    console.log('      resources: ', $i18next.i18n.options.resources); // prints out English -> translations -> ABSENCE_DETAIL: 'Absence Detail' ... and others
                    console.log('      made it this far: ', $i18next.t('ABSENCE_DETAIL')); //prints out ABSENCE_DETAIL
                };

                //here is defined the languagues in localStorage
                languageService.setDefault = function (data) {
                    console.log('> > > > > SET DEFAULT < < < < < ');

                    // Return a new promise.
                    return new Promise(function (resolve, reject) {
                        try {
                            languageService.save(data);
                            resolve(1);
                        }
                        catch (err) {
                            reject(err);
                        }
                    });
                };

                return languageService;
            }])

})();`

I don't know why the translations are not available after I have added the resource bundle.

**Comment by jamuhl** [comment]
try change `$i18next.t` with `$i18next.i18n.t` the only thing i could think of those are different instances of i18next...

**Comment by aubrey-fowler** [comment]
It didn't work. I got the same error. I have initialized my i18next like this in app.js:

    window.i18next.init({
        debug: true,
        lng: _actual, // If not given, i18n will detect the browser language.
        fallbackLng: _default, // Default is dev
        resources: _resources,
        useCookie: false,
        useLocalStorage: false,
        joinArrays: '<br />'
    });

**Comment by jamuhl** [comment]
You still using `English` instead of `en`?

**Comment by aubrey-fowler** [comment]
Yes.

**Comment by jamuhl** [comment]
try debugging through the $i18next.t call ... a) lng is wrong on resolving the key b) the key does not exist where it should

**Comment by jamuhl** [comment]
beside that stop trying to get it work for 'English' -> language detection, plurals, .... will fail

**Comment by jamuhl** [comment]
my current guess is: we format language codes to be correct -> means you set `lng = 'English'` we will format that to `english`.

try changing the language in resources to `english` and use `english` on addResourceBundle

lowercase that everywhere

**Comment by aubrey-fowler** [comment]
I switched to 'en' and it still doesn't work. 

```
			languageService.save = function (langObj) {

				//for (var i = 0; i < langObj.languages.length; i++) {
					$i18next.i18n.addResourceBundle('en', 'translations', langObj[langObj.languages[0]]);
				//}

				console.log($i18next.t('ABSENCE_DETAIL')); //prints out ABSENCE_DETAIL
				console.log('resources: ', $i18next.i18n.options.resources); // prints out English -> translations -> ABSENCE_DETAIL: 'Absence Detail' ... and others
				console.log('made it this far: ', $i18next.t('ABSENCE_DETAIL')); //prints out ABSENCE_DETAIL
			};
```

Also in the init

**Comment by jamuhl** [comment]
$i18next.i18n.options.resources still English -> translations ?!?

**Comment by aubrey-fowler** [comment]
Nope i updated the comment.

**Comment by jamuhl** [comment]
than i give up...would have to debug your code

**Comment by aubrey-fowler** [comment]
Even this Plunkr doesn't work.

http://plnkr.co/edit/ML2XJxUhWPvym1mYwVCZ?p=preview

**Comment by jamuhl** [comment]
what should i do with the plunkr - or what do you expect me to see? that has no i18next integrated? and i'm by far not an angular expert - prefer reactjs

**Comment by aubrey-fowler** [comment]
http://plnkr.co/edit/7oI13bNJVqVgTEFOT6bk?p=preview

**Comment by jamuhl** [comment]
http://plnkr.co/edit/0BqE5dAAnXKxmwpomNvk?p=preview

-> namespace is `tanslation` not `translations`
-> $i18next.i18n.t will work - while $i18next.t not

**Comment by aubrey-fowler** [comment]
OK I got that to work. What about the directives on html pages?
ng-i18next="" should still work?

**Comment by aubrey-fowler** [comment]
This is really strange. `function MyCtrl($scope, $i18next) {
  $scope.name = 'Superhero';


  $i18next.i18n.addResourceBundle('en', 'translation', {
    HELLO: 'hiya'
  });

  console.log($i18next.i18n.t('HELLO'));
  console.log($i18next.t('HELLO'));
}`

Now both consoles are printing out hiya

**Comment by jamuhl** [comment]
right...rather strange...best would be you ask that over at the ng-i18next repo...as that is not a problem of the i18next core - and i personally have no background in using angular...so can't help with that...

**Comment by aubrey-fowler** [comment]
OK thanks for your help!

**Comment by aubrey-fowler** [comment]
Actually I found out it's not to do with t or i18n.t it's when i try to access it before it's added to the resource bundle. I don't think it should break the instance doing this though.

**Comment by jamuhl** [comment]
yes...strange...made some test:

```
function MyCtrl($scope, $i18next) {
  $scope.name = 'Superhero';
  console.log($i18next);
  console.log($i18next.t('HELLO', 'hi'));
console.warn(JSON.stringify($i18next.i18n.services.resourceStore.data))
  $i18next.i18n.addResourceBundle('en', 'translation', {
    'HELLO': 'hiya'
  }, true, true);
console.warn(JSON.stringify($i18next.i18n.services.resourceStore.data))
  console.log($i18next.i18n.t('HELLO'));
  console.log($i18next.t('HELLO'));
}
```

seems the data itself in i18next are ok...just it somehow stores missing keys on the scoped $18next thingy...really no idea what and why

**Comment by aubrey-fowler** [comment]
Do you know if anyone is active on ng-i18next?

**Comment by jamuhl** [comment]
idk...honestly...should be...at least used to be

**Comment by Zarinia** [comment]
you should add this for add resource bundle
```
if (!i18next.isInitialized) {
							// wait for initalization
							i18next.on('initialized', async () => {
								if (i18next.options) {
									let jsonLang = require(langPath);
									await i18next.addResourceBundle('en', 'translation', data, true, true);
								}
							});
						} else {
							console.log(false);
						}
```
