### ISSUE TITLE
strings don't update when the language is changed

### ISSUE THREAD

**Issue by aubrey-fowler** [i18next/i18next#935]
0
down vote
favorite
I am integrating the i18next library with my Angular 1.5.3 project.

https://github.com/i18next/ng-i18next

When I use the changeLanguage feature the strings on my page don't update to the correct language.

Here's my html:

```
<!DOCTYPE html>
<html lang="en">

  <head>
    <script data-require="angular.js@1.5.3" data-semver="1.5.3" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.3/angular-sanitize.min.js"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/i18next/8.4.1/i18next.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ng-i18next/1.0.4/ng-i18next.min.js"></script>
    <script src="app.js"></script>
    <meta charset="utf-8" />
  </head>

  <body ng-app="myApp">
    <div ng-controller="MyCtrl">
      Hello, {{name}}!
      <div ng-i18next="HELLO"></div> <!-- doesn't update -->
      <button ng-click="change()">change lng</button>
    </div>
  </body>

</html>
```
Here's my app.js
```

if (window.i18next) {
  window.i18next.init({
    debug: true,
    lng: 'en', // If not given, i18n will detect the browser language.
    fallbackLng: 'en', // Default is dev
    resources: {},
    useCookie: false,
    useLocalStorage: false,
    joinArrays: '<br />'
  });
}

var myApp = angular.module('myApp', ['ngSanitize', 'jm.i18next']);
myApp.controller('MyCtrl', MyCtrl);

function MyCtrl($scope, $i18next) {
  $scope.name = 'Superhero';

  $scope.change = function() {
    $i18next.i18n.changeLanguage('fr', function(err, t) {
      console.log(t('HELLO')); //prints out bonjour
    });
    console.log($i18next.t('HELLO')); //prints out hiya
  };

  $i18next.i18n.addResourceBundle('en', 'translation', {
    'HELLO': 'hiya'
  });

  $i18next.i18n.addResourceBundle('fr', 'translation', {
    'HELLO': 'bonjour'
  });

  console.log($i18next.t('HELLO')); //prints out hiya
}
```
Plunkr: https://plnkr.co/edit/7oI13bNJVqVgTEFOT6bk

I don't know how I can 'refresh' my page to get the correct translations.

**Comment by jamuhl** [comment]
Again an issue of ng-i18next - i18next itself has no idea what framework you use so has no idea how to trigger a rerender. eg. in jquery-i18next you have to call .locize() again. for react-i18next the translate higher order component is aware of language changes and will rerender without extra code.

Find out how to rerender in angular.

**Comment by aubrey-fowler** [comment]
It works perfectly fine with the filter and not the directive. <div>{{'HELLO' | i18next}}</div>

Is there any downside to using the filter?

**Comment by jamuhl** [comment]
no idea...like said...i don't work with angular...so i have no idea what the difference of a filter and a directive is. Using react you got one concept of components and done...

**Comment by LaraMo** [comment]
@jamuhl I am using react and I have the same issue.

Assume I have a component like so:
`<h1>(i18n.t('welcome'))</h1>`

Now I have a set of buttons that on click will call: **changeLanguage**  from french to english and vice-versa.
```
const changeLanguage = lng => {
			i18n.changeLanguage(lng);
			console.log(i18n.t('welcome '));
}
```

Each time I click on the button and it console logs:
 `welcome` --> (if language is in english)  
  OR
 `bienvenue` -- > (if language is in french)

However, my h1 element remains the same. 
How would I fix that? 

Thanks in advance for your help :)

**Comment by jamuhl** [comment]
@LaraMo you already use react-i18next -> the hook, HOC, ... are responsible for rerendering on language change -> the t function only returns translations and has no info/connection to any rendering
