### ISSUE TITLE
multiple-fallback-keys not workig

### ISSUE THREAD

**Issue by emauricio** [i18next/i18next#937]
Hi there, 
I hope this is the correct place to ask for this :)

I'm trying to use one of the examples from the documentation.
(https://www.i18next.com/essentials.html#multiple-fallback-keys)
but somehow it does't work.

got the basic example from the express plugin
(https://github.com/i18next/i18next-express-middleware/tree/master/examples/basic-pug)

but no luck to make it work, i dont know if i miss something.
```
-  var error = '404';
    p=error  // -> 404 
    p=`error.${error}` // -> error.404
    P= t([`error.${error}`, 'error'])  // -> Something went wrong.
```
an calling `error.404` directly will display an error because it doesn't exist as deep key.

also tried with one of the fiddle from the documentation
https://jsfiddle.net/ay37Lau0/1/

maybe i'm too sleepy right now to see if i miss something 😛 

thank you in advance.

**Comment by jamuhl** [comment]
uh...no the sample is wrong...my fault. Sorry.

should be:

`t([`error.${error}`, 'error.unspecific'])` so json can be:

```
{
  error: {
    unspecific: 'some error',
    404: '404 error'
  }
}
```

will fix the documentation asap.

**Comment by emauricio** [comment]
argggg hahahah, i just started to check the code to see where was the point for that example.. hahahaha, now make more sense. yup, that was it.

**Comment by jamuhl** [comment]
sorry for the troubles...

**Comment by emauricio** [comment]
no worries, thank you for the quick answer :)
