### ISSUE TITLE
"Bad Request Upload failed." error when uploading to google apps script

### ISSUE THREAD

**Issue by nodirashidov** [i18next/i18next#938]
when I import i18next:

`import i18next from 'i18next';`

 gapps upload command stops with the following error.

> gapps upload
> Pushing back up to Google Drive...
> An error occured while running upload command: Bad Request
> Upload failed.

I tried pasting the browserified code to google apps script, GAS is having issues with all 
 the `default`s in node_modules/i18n.js

Is there a way to overcome the issue?

**Comment by jamuhl** [comment]
did you try `import { default as i18next }` from 'i18next'`?

**Comment by nodirashidov** [comment]
just did. Still getting the same error..

**Comment by jamuhl** [comment]
Got no experience with GAS / browserify transpilation. Might be browserify does take the commonjs build or only support require?!?

`var i18next = require('i18next').default;`

**Comment by nodirashidov** [comment]
> Invalid property ID. (Line 32, file "main")

Line32:
`function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }`

**Comment by jamuhl** [comment]
no idea...without the chance to debug through your code. Evtl. someone else with experience using similar setup could help more? Posting this to stackoverflow might help?

**Comment by jamuhl** [comment]
https://stackoverflow.com/questions/44536574/getting-an-unexpected-token-esprima-js-error-when-using-i18n-with-gasify seems you already did...or at least looks similar

**Comment by jamuhl** [comment]
beside that: npm i18n is not i18next!! https://www.npmjs.com/package/i18n

**Comment by nodirashidov** [comment]
I see. Yes that was my question, I tried using  i18n before i18next, the build wasnt working. So I came across i18next and the build and everything was great, i even finished translating my project into several languages but now cant upload to GAS to get it to actually work

**Comment by nodirashidov** [comment]
I noticed that there is a "es" folder in "dist" . Is there a way to use files in that instead of the "commonjs" ones?

**Comment by jamuhl** [comment]
`import { default as i18next } from 'i18next/dist/es'` i think

but package.json includes entry point definitions for that cases: https://github.com/i18next/i18next/blob/master/package.json#L6

**Comment by jamuhl** [comment]
closing for now...feel free to reopen
