### ISSUE TITLE
Using plural in jsfiddle

### ISSUE THREAD

**Issue by Yvanovitch** [i18next/i18next#939]
Hi,
I was testing i18next in jsfiddle and didn't manage to execute the plural, did I do something wrong ?
http://jsfiddle.net/xhx00x4e/
I'm using i18next 8.4.2 and I based myself on [an old jsfiddle](http://jsfiddle.net/veggiemonk/zf7f7e2x/) I found
Thanks

**Comment by Yvanovitch** [comment]
Oh, it seems it was because of the "edn" language, which is unknown. I don't know why the original creator put it. 
Sorry for the inconveniance

**Comment by jamuhl** [comment]
Sorry just saw your issue right now...but already solved. glad you found the problem and solution.
