### ISSUE TITLE
"sub" language fallback ? eg. zh-CN -> zh

### ISSUE THREAD

**Issue by GongT** [i18next/i18next#940]
language whitelist: zh, zh-cn, zh-tw, en
fallback: en

I want to fallback like this:
> zh-CN -> zh -> en

dose it supported?

**Comment by jamuhl** [comment]
that's the default. https://www.i18next.com/principles/fallback.html#locals-resolving

if not set to load lng only it will always lookup eg. `de-CH` -> `de` -> `en` or in your case `zh-CN` -> `zh` -> `en`

you can even set different fallbacks for different regions like: https://www.i18next.com/principles/fallback.html#fallback-language

**Comment by GongT** [comment]
* I configure i18next with 
`
"nonExplicitWhitelist":"en",
"whitelist":["en","zh"],
"preload":["en","zh"],
"fallbackLng":"en"
`
* write a "console.log" to node-fs backend's code
* set `lng=zh-tw` from GET

I got a log, it try to load language "zh-tw" and failed, and return a "english" page.

if I set "lng=zh", I will get a "chinese" page. or set "lng=en", I will get a "english" page.

**Comment by jamuhl** [comment]
Set nonExplicitWhitelist to true.  Not en. 

Von meinem iPhone gesendet

**Comment by GongT** [comment]
I found a big problem, It not even fallback. wait I will create new issue on `i18next-express-middleware`

**Comment by GongT** [comment]
see: https://github.com/i18next/i18next-express-middleware/issues/128

**Comment by jamuhl** [comment]
closing in favour of i18next-express-middleware issue
