### ISSUE TITLE
Apply HTML tags from interpolation

### ISSUE THREAD

**Issue by MaxLeiter** [i18next/i18next#943]
`"colored_text": "{{colorRange}}"`

`i18nInst.t("colored_text", {{ interpolation: { escapeValue: false }, colorRange: "<code>0-15</code>" });`

Expected: `0-15`
Actual: \<code>0-15\</code>

**Comment by jamuhl** [comment]
Interpolation out of security reasons (xss) escapes all tags. Set https://www.i18next.com/interpolation.html#additional-options escape to false. 

If i see it right you opened this also on react-i18next - be aware react itself does not allow inserting html into nodes for the same reason. You will need to https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml for this to work.

What we personally use a lot is a component that renders markdown for such cases.

**Comment by MaxLeiter** [comment]
I'm not using react - I created it there by accident.

**Comment by jamuhl** [comment]
ok than just setting escape option to false on init or on that `t` call should be enough

**Comment by MaxLeiter** [comment]
Do you mean `escapeValue: false`? Or are you sure `escape: false`?

**Comment by jamuhl** [comment]
yes escapeValue....sorry was for very long just escape...always get it wrong

`escapeValue: false`
