### ISSUE TITLE
Can I use any other number formatting library

### ISSUE THREAD

**Issue by msreddy09** [i18next/i18next#944]
As per the documentation,  we can use numeral js for number formatting.
But as numeral js is not a es6 module,  It is not supporting tree shaking when we do bundle. So I am looking for any other es6 based library for number formatting which is fully compatible to  i18next

Thanks.

**Comment by jamuhl** [comment]
did you already look at: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

**Comment by msreddy09** [comment]
Thanks for your quick reply. Yes, I have gone through it. But it does not have IE 10 support.  Can you suggest any other library.

**Comment by jamuhl** [comment]
there is a polyfill for intl api: https://www.npmjs.com/package/intl-polyfill

beside that i'm not aware of alternatives to numeral.js

**Comment by jamuhl** [comment]
closing for now...feel free to reopen
