### ISSUE TITLE
How to allow partial backend load failures?

### ISSUE THREAD

**Issue by bttmly** [i18next/i18next#950]
It seems like the `BackendConnector.prototype.queueLoad` fails if at least one of possibly several resources fails to load. Is there any way to allow partial failures? For instance, if a client requests three resources and we can only serve two, it would be far better to serve those two than to serve none and error out.

**Comment by jamuhl** [comment]
I guess you already found it will serve that two...just pass an error for information.

**Comment by bttmly** [comment]
Yeah it was an issue specific to the backend I was using. Just need to swallow the ENOENT errors on first try for a missing key.
