### ISSUE TITLE
I would like to use i18n.t all over my application, but it just only works inside that init function. I dont know how to make it globally available through the application.

### ISSUE THREAD

**Issue by sri94** [i18next/i18next#951]
import React from 'react';
import ReactDOM from 'react-dom';
import './../index.css';
import i18n from 'i18next';
import i18nextXHRBackend from 'i18next-xhr-backend';
import moment from 'moment';
import Datetime from 'react-datetime';
class Board extends React.Component {
  render() {
  const title = "new";
  i18n.use(i18nextXHRBackend)
	  .init({
						lng: navigator.language,
						debug: true,
						interpolation: {
             format: function(value, format, lng) {
            if(value instanceof Date) return moment(value).format(format);
            return value;
						}},
						getAsync: false,
						backend: {
								loadPath: 'locales/{{lng}}/{{ns}}.json',
	  }},function(err, t){
						updateContent();
						}
						);
function updateContent() {
 var title_i18n = i18n.t('key');
 console.log(title_i18n);
//  document.getElementById('root').innerHTML = i18n.t('key');
  document.getElementById('date_time').innerHTML = i18n.t('date_format',  {date: new Date()} );
document.getElementById('plural').innerHTML = i18n.t('plural', {count: 0});
document.getElementById('title').innerHTML = i18n.t('title', {"tech": "i18next"});
}
						
   return (
<div>{i18n.t('title')}</div>
    );
	
  }
}
export default Board;

I am a novice engineer.Please explain me clearly. @jamuhl 
This is my sample code. I just tried using i18n , the title_i18n inside console.log works fine.but i want it to work fine outside the function. Now i need my title in the render function be externalized and be returned inside the return inside that {i18n.t('title'}} ... 
Gone through : 
https://github.com/i18next/i18next/issues/618
https://github.com/i18next/i18next/issues/39

but i dont understand.

**Comment by jamuhl** [comment]
using react you should have a look at: https://github.com/i18next/react-i18next

there are plenty of samples: https://github.com/i18next/react-i18next/tree/master/example

-> docs: https://react.i18next.com
-> webpackbin: https://www.webpackbin.com/bins/-KoCD3kvA-4QJNaHpkxi

if still unclear please reach out again...we get you there.

**Comment by sri94** [comment]
yeah solved :) thank u !
