### ISSUE TITLE
i18next::backendconnector failed to load json from the backend

### ISSUE THREAD

**Issue by premagopu** [i18next/i18next#955]
I'm trying to load the json from the backend using i18nextXHRBackend. But it throws the following error.

i18next::backendConnector: loading namespace special for language en failed failed parsing /locales/en/special.json to json

Java Spring boot project folder structure

Project
     src/main/resources
             locales
                 en
                    special.json
                es
                    special.json
File
 special.json
 {
    	        "key": "hello world"      
} 

File
Sample.html

```
<html>
<head>
<script src="../js/i18nextXHRBackend.js"></script> 
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript" src="../js/i18next.min.js"></script>
<script th:inline="javascript">

$(document).ready(function() {
 i18next
	   .use(i18nextXHRBackend) 
	  .init({
		lng: mdCurrLocale,
	    fallbackLng: 'en',
	    debug: true,
	    ns: ['special'],
	    "keySeparator": false,
       "nsSeparator": false,
        getAsync: false,
        defaultNS: 'special',
	       backend: {
	      loadPath: "/locales/{{lng}}/{{ns}}.json",
	      crossDomain: false
	     }  
	      
	  }, function(err, t) {
		  var text = i18next.t('Key');
		  alert(text);
 }); 
 </script>

</head>
</html>


```

The i18nextXHRBackend is unable to load  the json file from the project folder(project/src/main/resources/locales/en/special.json)

Where the json file should be placed inside the project folder in order to make this work?

**Comment by jamuhl** [comment]
you need to assert:

a) the file is public reachable -> eg. http://localhost:3000/en/special.json (or domain your app runs)
b) the file needs to be valid json format

i18next::backendConnector: loading namespace special for language en failed failed parsing /locales/en/special.json to json

says what ever was loaded was not in valid json -> check devtools in eg. chrome for the content that was loaded.

**Comment by priyankadb** [comment]
the problem I am facing is that the json is not always loaded from the backend using i18nextXHRBackend
it loads sometimes and doesn't load sometimes. I am using it the same way as mentioned by **premagopu**
Anything specific that need to be done?

**Comment by jamuhl** [comment]
@priyankadb really a problem of you server - just make sure that works reliable. The i18next client will retry a few times to reload...but after 5 times having error on the request it will give up.

**Comment by priyankadb** [comment]
I am using Spring Boot and MVC architecture. I am loading the files from resources/static/js/<filename>. It is really strange that at times it doesn't pick up the files when I run the project. I have to restart the application. Any pointers ?

**Comment by jamuhl** [comment]
from the errors above it really looks like your server does not always provide those json files reliable. As much i would love to help you there i can't do anything as it is not related to i18next and i got no java knowhow. You might ask over at stackoverflow why your server does not serve those files proper.

The only alternative i could offer you is having a look at https://locize.com -> our localization as a service offering which supports i18next development - you can use that as translation management and directly load your translations from there using the locize-backend.

**Comment by priyankadb** [comment]
thanks for the reply. I will have a look.

**Comment by jamuhl** [comment]
closing for now...hope you could solve the issue...else feel free to reopen

**Comment by idajimenez** [comment]
Hi @jamuhl, I am also encountering this warning when the path is something like `/sample/route` but when the path is just `/sample`, it's working fine. All of the json files are in the public directory.

**Comment by jamuhl** [comment]
@idajimenez can you give some more information? There is no magic. a) the path is correct set and works or b) it's wrong and it does not work...there is nothing in between.

If your server host translations on `/sample/route` your path must be something like that in i18next.options.backend.loadPath: `/sample/route/locales/{{lng}}/{{ns}}.json` or whatever the route is on your website to load that...just type in the route on your browsers addressbar and check if translations can be loaded.

**Comment by manasi9** [comment]
Hi , i am receiving the warning -
 i18next::backendConnector: loading namespace translation for language chi failed failed parsing /src/public/locales/en/translation.json to json
then, 
i18next: initialized 
i18next::translator: missingKey chi translation example.data example.data

the locales folder is placed inside root-directory/src/public/locales/chi/translation.json
and the backend options is set as-
 backend: {
      loadPath: "/src/public/locales/{{lng}}/{{ns}}.json",
    }


could you please help

**Comment by jamuhl** [comment]
@manasi9 why not checking the network tab of your developer toolbar in the browser and check the content of your translation.json -> it's always the same issue...I today can't tell how often I had to write this down....

If you got this error you have an error -> your file is not valid JSON or not reachable as your path is wrong.

**Comment by manasi9** [comment]
@jamuhl in the response i could only see the index.html file

**Comment by jamuhl** [comment]
@manasi9 so you have the problem located at its root...there is no way I can fix this for you...

**Comment by premagopu** [comment]
<script  src="../jquery/3.1.1/jquery.min.js"></script>
<script src="../jquery/jquery-1.12.3.js"></script>
<script src="../jquery/jquery-1.12.3.min.js"></script>

<script src="../js/i18nextXHRBackend.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/i18next/8.4.3/i18next.js"></script>
<script type="text/javascript" src="../js/i18next.min.js"></script>
<script type="text/javascript" src="../js/jquery-i18next.min.js"></script>
<script type="text/javascript" src="../js/i18nextBrowserLanguageDetector.min.js"></script>
<script type="text/javascript" src="../js/i18nextLocalStorageCache.min.js"></script>
<script type="text/javascript" src="../js/i18next.js"></script>
<script th:inline="javascript">
//<![CDATA[
    var currLocale = [[${mdCurrLocale}]];
	var genericCommentMessage='genericCommentMessage';  
//]]>
$(document).ready(
		function() {
			//<![CDATA[		    
		    var i18nextOptions = {
		    		'debug': true,
                    load:['en','es'],
                    lng: currLocale,
                    fallbackLng: 'en',
                    ns:'login',
                    defaultNS:'login',
                    backend: {loadPath: '/js/login_{{lng}}.json'},
                  };
			
		    i18next
				.use(i18nextXHRBackend)
				.init(i18nextOptions);
 }); 
 </script>

@manasi9 I used this code and it worked. 

Something with different versions of jQuery and ns name if I remember correctly.

Hope this helps!

**Comment by nilamsavani** [comment]
Hi @jamuhl ,

I am adding it into react application and to upload code on production I am using command npm run build and then I upload content of build folder into AWS S3 bucket.

I tried by 
`
backend: {
      loadPath: '/locales/{{lng}}/{{ns}}.json',
    },
`
But, I am getting an error as  loading namespace translation for language en failed failed loading /locales/en/translation.json.

Any suggestion?

**Comment by adrai** [comment]
@nilamsavani Check the network tab in your browser and verify if there is a json file served from your s3 bucket on that path

**Comment by nilamsavani** [comment]
@adrai Thank you for your reply. No it is not. 

What I should I add in my `loadpath` so that it can get served from my S3 bucket? I have created a file at locales/en/{{file}}

**Comment by adrai** [comment]
@nilamsavani it depends on how you uploaded it to s3... can you share a url?

**Comment by nilamsavani** [comment]
I added post build script to copy my locales folder into my build folder and now its working. Thank you for your help @adrai

**Comment by jothbc** [comment]
My JSON fails because the key contains spaces and dot. What would be the best solution for this?
example:
{
  "Approvals Center" : "ES - Centro de Aprobaciones - BRF",
  "Oops .. Something went wrong. Try again later.": "Oops.. Algo salió mal. Inténtalo de nuevo más tarde.",
  "Success in approving": "Aprobación exitosa"
 }

**Comment by jamuhl** [comment]
@jothbc  https://www.i18next.com/overview/configuration-options#others have a look at keySeparator (setting it to false will work)

**Comment by mahmoudelshenawy123** [comment]
the solution is just add / before the path in loadPath in i18n initi 
just like this 
 loadPath: '/assets/locales/{{lng}}/translation.json',

**Comment by Bekbol-frontend** [comment]
backend: {
      loadPath: "/src/public/locales/{{lng}}/translation.json",
 },


is ok ;)
