### ISSUE TITLE
Cannot set property 'innerHTML' of null， changeLng is not defined

### ISSUE THREAD

**Issue by anlexN** [i18next/i18next#956]
i surely use browserify/brunch/webpack build tool to let my source code run in the environment. but i18next still can not sucess!
![4](https://user-images.githubusercontent.com/8686739/29564018-a077159a-8772-11e7-9959-02bc25e8046b.PNG)

![default](https://user-images.githubusercontent.com/8686739/29563931-4cf5fc06-8772-11e7-8f37-e088f88e9047.PNG)
![1](https://user-images.githubusercontent.com/8686739/29563932-4cf6c4a6-8772-11e7-89cb-04b6485aae0f.PNG)
![2](https://user-images.githubusercontent.com/8686739/29563935-4da6cebe-8772-11e7-9fc5-565a79a9e3f3.PNG)

**Comment by jamuhl** [comment]
the first one: cannot set property 'innerHTML' of null

-> you're to early i think - the dom not yet contains that element output -> move the script tag to end of your body

the second one: changeLng is not defined

-> that function is scoped in browserify/webpack whatever - you will need to expose that on window `window.changeLng = changeLng` to be accessible from dom

**Comment by anlexN** [comment]
@team, could you please showcase your demo using js build tool?

**Comment by jamuhl** [comment]
did you try the recommended changes?

**Comment by anlexN** [comment]
the first problem is solved, but the second problem, how to expose changLng to window  gracefully? window.changeLng = changeLng , directly write to source code , a little silly.

**Comment by jamuhl** [comment]
than give the button an id and bind it's onClick event by code.

```
var button = document.getElementById("myButton");
button.addEventListener("click", function(e) {
    changeLng('en');
}, false);
```

**Comment by anlexN** [comment]
if this, this will add many more code. could you be more easier to expose?

**Comment by jamuhl** [comment]
sorry but this is not related to i18next - it's just web and javascript...you have this two options expose to global scope or bind the event listener.

hm, options c) use http://locize.com and the oneliner script - drop it on your page - done.

**Comment by anlexN** [comment]
After that, i recommend you can provide webpack or browserify or brunch build tool example that showcase your great i18next

**Comment by jamuhl** [comment]
we have such samples based on eg. react -> https://github.com/i18next/react-i18next/tree/master/example
