### ISSUE TITLE
I18next stops working at localize

### ISSUE THREAD

**Issue by CoderStefan** [i18next/i18next#957]
Hello,

i have the following key:
  resources: {
    en: {
      translation: {
        "key": "hello world {{name}}"
      }
    },
    de: {
      translation: {
        "key": "hello welt {{name}}"
      }
    }
  }

when i use i18next with this:
  document.getElementById('output').innerHTML = i18next.t('key', { name: 'i18next '}); 
then its works

but i use this:
document.getElementById('output').innerHTML = i18next.t('key', { name: 'i18next {{name}}'});
then i18next stops working

demo:
https://jsfiddle.net/6x1897te/

**Comment by jamuhl** [comment]
this causes an endless loop

name: 'i18next {{name}}' -> interpolates name again which interpolates name again and again and again -> endless loop

**Comment by CoderStefan** [comment]
Is there a setting or mechanism to interrupt the endless loop?

**Comment by jamuhl** [comment]
beside fixing it in the translation?

`i18next.t('key', { name: 'i18next {{otherName}}', otherName: 'theOtherName' })`

**Comment by CoderStefan** [comment]
My problem is also that in some cases unfortunately also a user input.

**Comment by jamuhl** [comment]
you expect users to input a {{yourVariable}} hm...might happen....

A) replace those {{ }} in user input
B) choose another prefix/suffix users never will guess
C) provide a PR:

https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L77
https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L84

setting a counter and exit after eg. 1000 replaces ;) -> but still if handling it graceful in code the UI will run crazy ;)

**Comment by jamuhl** [comment]
thank you for the awesome PR
