### ISSUE TITLE
translate for a specific language

### ISSUE THREAD

**Issue by obedm503** [i18next/i18next#959]
does i18next allow you to translate a key for a specific language? Sometimes the case arises when I need to display the same translated string in multiple languages, and it seems like i18next doesn't yet support that. Can anyone point me to documentation for it? or, if this is not yet a feature,  should it be added?

**Comment by jamuhl** [comment]
not sure what you mean, but guessing:

```js
i18next.t('key', { lng: 'en' });
i18next.t('key', { lng: 'de' });
```

**Comment by dixonsiu** [comment]
I had the same question. Just found out that you simply need to do either of the followings.
1. make sure the language's json is available  
    - preload the language in init, OR  

           i18next.init({ preload: ['de'] });

    - load the language after initialization.  

          i18next.loadLanguages(['de']);

1. translate for a specific language  

       i18next.t'('key', { lng: 'de' });

**Comment by obedm503** [comment]
confirmed that preloading the languages solves it. thanks

**Comment by codingyourlife** [comment]
Nice. But how do I do this for the `<Trans />` component?

**Comment by jamuhl** [comment]
@codingyourlife creating a fixedT https://www.i18next.com/overview/api#getfixedt and passing it to Trans as props https://react.i18next.com/latest/trans-component#trans-props should work

```js
const t = i18n.getFixedT(lng);

<Trans t={t} />
```
