### ISSUE TITLE
get language from url

### ISSUE THREAD

**Issue by osvaldoM** [i18next/i18next#961]
Hi,

Im facing an issue with retrieving the language either from cookies or query string.
as the docs in http://i18next.github.io/i18next/pages/doc_init.html state, passing the param `detectLngQS: 'lang' `   to the init function should cause the library to fetch the language specified in the query string param.
moreover adding the param `cookieName: 'lang'` should load the language specified in the cookies, however that is not what happens when i Load the page. am I doing something wrong?
here is a snippet of how I'm loading the lib
``` i18next
    i18next
      .use(i18nextXHRBackend)
      .init({
        detectLngQS: 'lang',
        cookieName: 'lang',
        fallbackLng:false,
        nsSeparator: false,
        keySeparator: false,
        useOptionsAttr:true,
        debug:true,
        parseDefaultValueFromContent: false,
        backend: {
            loadPath: 'locales/{{lng}}/{{ns}}.json'
        }
      }, function(err, t) {
        jqueryI18next.init(i18next, $);
        updateContent();
      });
```

```function updateContent(){
    function updateContent(){
        $('.primary-nav').localize();
        $('.section-footer').localize()
        $('.translate').localize()
      }```

**Comment by jamuhl** [comment]
Please use the documentation published on https://locize.com

the link you posted is from the old v1

for language detection there is a plugin like the xhr-backend: https://github.com/i18next/i18next-browser-languageDetector

**Comment by osvaldoM** [comment]
Thank you for the help @jamuhl . I think maybe there should be a warning or something in the URL or on the page clearly stating that the docs are for V1.

**Comment by jamuhl** [comment]
We have that warning on the start page http://i18next.github.io/i18next/ but not on each individual page. Personally i would have pulled that down a long time ago...but there are to many projects still relying on that version.
