### ISSUE TITLE
Uncaught TypeError: translatelanguage.updatecontent is not a function

### ISSUE THREAD

**Issue by anlexN** [i18next/i18next#962]
i use " browserify app/index.js -o app/bundle.js"

#html
![default](https://user-images.githubusercontent.com/8686739/30265956-6104f5e6-9710-11e7-8487-559dfd34b63d.PNG)
#index.js
![1](https://user-images.githubusercontent.com/8686739/30265961-61201baa-9710-11e7-95ae-4bd3b0d3e475.PNG)
![2](https://user-images.githubusercontent.com/8686739/30265958-61092094-9710-11e7-8293-38fec10b5002.PNG)
#bundle.js
![4](https://user-images.githubusercontent.com/8686739/30265959-6110fb34-9710-11e7-86da-1004b2ee7f0b.PNG)
#error
![5](https://user-images.githubusercontent.com/8686739/30265957-61076e5c-9710-11e7-9828-e86ab3f9eb64.PNG)

**Comment by jamuhl** [comment]
you missed that `translatelanguage` is a class not an instance. You first will need to create an instance of that class and access the function on that.

`const tl = new translatelanguage(); tl.updateconent();`
