### ISSUE TITLE
Check if a language is valid

### ISSUE THREAD

**Issue by TimoRuetten** [i18next/i18next#963]
I am currently working on an express app which is using I18next. In our case we want to have the lang code in our URL like this:

`/en/...` or `/en-GB/...`.

In our initialisation of I18next we are setting the whiteList and set it to `['en']` and set `nonExplicitWhitelist` to `true`. At the end our I18next setup looks like this:

```
...
fallbackLng: 'en',
    whiteList: [
      'en',
    ],
    nonExplicitWhitelist: true,
    ns: [
      'ui',
    ],
    defaultNS: 'ui',
    react: {
      wait: false,
      withRef: false,
      bindI18n: 'languageChanged loaded',
      bindStore: 'added removed',
      nsMode: 'default',
    },
...
```

Our goal is now that we detect the language with the LanguageDetecter (which works great) and using the middleware so we can access the req.language property. But before we render our HTML we will check if the langCode is given in the URL. If there is no langCode given we will take req.language and do a redirect. But if smth is given we want to check if its a valid language or if not.

```
...
const lang = req.url.split('/')[1];
  if (
    lang.length &&
    i18nextInstance.options.whiteList.indexOf(lang) !== -1
  ) {
    req.i18n.changeLanguage(lang);
    next();
  }
...

```

If our langCode now would be en-GB this would not work, because in whiteList is only en. Of course we could split the langCode with "-" and always use the first parameter - but I am wondering if is there a "correct" way of testing a valid language code for the given i18next instance or a recommended way to work with langCodes in express in combination with i18next.

As far as I understood the `nonExplicitWhitelist` it would add the localisation specifications by itself - but it does not. Maybe I am getting smth wrong ?

**Comment by TimoRuetten** [comment]
Additional: As far as I see does the language set in the languageDetector and assigned to the `req` is not checked with the whiteList property. So the req.language could be a language which is not available in the whiteList. Shouldnt set req.language to the fallbackLanguage if not available ?

**Comment by jamuhl** [comment]
you can require the language util and use https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L61

it takes the language part from the locale and checks with that

req.language is always the detected one
req.languages is what is used (https://www.i18next.com/api.html#language)

so req.languages[0] might be what you want

**Comment by TimoRuetten** [comment]
Thanks for the hint with the LanguageUtils. But I am not sure if I get it what you mean with language and languages.

"
req.language is always the detected one
req.languages is what is used (https://www.i18next.com/api.html#language)
"

in my case I am logging both and this is the result:

```
[ 'de-DE', 'de', 'en' ] // req.languages
de-DE // req.language
```

But in my whitelist there is just en. So as far as I understand I still have to check if the detected language is available in my whiteList, correct ? So I would have to map the array req.languages until I find a language which is supported in my whiteList and if there is no result I have to use the defaultLanguage and set it.

**Comment by jamuhl** [comment]
https://www.i18next.com/configuration-options.html#languages-namespaces-resources

options: whitelist not whiteList

**Comment by TimoRuetten** [comment]
God damn.. I am sorry for this! What a embarrassing bug on my side!

Thanks for the fast response and your hard work on this package 👍

**Comment by jamuhl** [comment]
you're welcome
