### ISSUE TITLE
how to auto render every page?

### ISSUE THREAD

**Issue by XingdaLee** [i18next/i18next#965]
Hi:
   jquery how to set all the pages automatically render, rather than every page to use $ (document) .localize ()?
Thanks!!

**Comment by XingdaLee** [comment]
Added: My program is a single page application, how to do automatic rendering ？

**Comment by jamuhl** [comment]
Depends on your implementation. Is your SPA based on jquery only? Or backbone, react, angular, vue?!?

Anyway in the end you might need to hook into your router and trigger .localize() on page change event.
