### ISSUE TITLE
site: addition to `plugins and utils`

### ISSUE THREAD

**Issue by rosskevin** [i18next/i18next#966]
Hello @jamuhl,

I recently switched from an xhr-backend to bundling, and I was surprised that I didn't quite find anything amongst the two or three loaders that fit my case very well (we do a lot of white labeling).  I started with one of the current plugins and modified it to our case.  It supports webpacking both yaml and json, with overrides.

I'm still iterating on small changes, but it has a decent test suite with CI and it seems good to go.

if you find it worthy, you might add it to the `Plugins and Utils` page on the site:
https://github.com/alienfast/i18next-loader

**Comment by jamuhl** [comment]
great...just added and published an update: https://www.i18next.com/plugins-and-utils.html
