### ISSUE TITLE
Tool to merge json files

### ISSUE THREAD

**Issue by Vincz** [i18next/i18next#967]
Hi! I was wondering if there is a tool in your stack to merge keys & values from one file to another ?
I have everything setup well, my namespace is "messages" and my application is populating my messages.missing.json file for missing translation when in development. 
At some point, I'd like to merge all missing key/value from messages.missing.json into messages.json.
I saw a lot of tools and there is a lot of repositories with i18next but I wasn't able to find a tools to do that.
Any idea?

**Comment by jamuhl** [comment]
good question...i do not know a free tool doing that...but on our service tier https://locize.com you would be able to merge files - but as missings are completely supported there you would not need to merge anymore.

you might use i18next itself...https://www.i18next.com/api.html#addresourcebundle just load as regular merge the missing file over and get it again....
