### ISSUE TITLE
missing keys during loading changeLanguage() from backends

### ISSUE THREAD

**Issue by melounek** [i18next/i18next#968]
I made an example of the issue here: https://www.webpackbin.com/bins/-KuxsDAcwJ2azm0S41y-
On the first changeLanguage() (click "de") when it should write to the console t('title') right after changing the language => it returns me "missing key error"

If I am using react + redux + etc... and my App is actively rerendering on every form change, this causes it displays constants (or fallbackLng) during the loading a resorce (0.5s - 1s) which look bad.

I already reported this to i18next-xhr-backend https://github.com/i18next/i18next-xhr-backend/issues/266#issuecomment-332210256 but it looks its an issue of every backend with loading delay.

I know there are ways how to avoid rerendering before the resource from backend is ready, but I think there should not be any moment, during  changing language, when `t()` returns an error, because it's loading the resource. There can be many other processes which can run some part of javascript with translate and it should not return the error, but the language which was there before `changeLanguage()` was triggered. 

Maybe `changeLanguage()` should not change the `i18n.language` property immediately, but after the resource is loaded or something like that.

**Comment by jamuhl** [comment]
might be enough to move https://github.com/i18next/i18next/blob/master/src/i18next.js#L210 to line  197 - but need to check for possible side effects.

**Comment by jamuhl** [comment]
Could you check if that would solve your issue?

**Comment by melounek** [comment]
Well I tried to swich i18n-xhr-backend to this type "3rdParty", but it just stopped work, and there probably more things to change to properly migrate to this type.

But this will not solve the issue anyway...

**Comment by jamuhl** [comment]
The change mentioned is not related to changing type on the xhr-backend - how do you come to that idea?

Just go to node_modules/i18next/dist/es and find the line mentioned and move it to the callback part

**Comment by melounek** [comment]
Ahh sorry... I was confused by the lines, if 210 or 197...

But I put the line 210 into the callback and now it's working well.

Here is the snippet from node_modules/i18next/dist/es:

```
    var setLng = function setLng(l) {
      if (l) {
        _this4.language = l;
        _this4.languages = _this4.services.languageUtils.toResolveHierarchy(l);

        if (_this4.services.languageDetector) _this4.services.languageDetector.cacheUserLanguage(l);
      }

      _this4.loadResources(function (err) {
        _this4.translator.changeLanguage(l);
        done(err, l);
      });
    };
```

I also tested also unexisting language and everything looks fine.

Let me know I should do pull-request too. Thanks

**Comment by jamuhl** [comment]
So this solves your issue...no need for a PR...the change is done rather simple...

Just need to think about possible side effects...give me some time for testing a little deeper...but seems like a non breaking change.

Just need to be more confident we do not break stuff for existing users.

**Comment by jamuhl** [comment]
changed in i18next@9.0.1 - please verify and close if ok for you.

**Comment by melounek** [comment]
now it's alright. thanks
