### ISSUE TITLE
Possible infinite loop using 'context' and interpolation.nestingPrefix

### ISSUE THREAD

**Issue by tiriana** [i18next/i18next#969]
When you have structures like this:
```
"someKey: {
    "baseValue": "the context is: "
     "baseValue_context1": "$t(someKey.baseValue) context1",
}
```

when trying to get translation for `.t("someKey.baseValue", {context: "context1"})`

```
RangeError: Maximum call stack size exceeded. in build/js/vendors/i18next.js (line 324)
	getLastOfPath@build/js/vendors/i18next.js:324:23
	getPath@build/js/vendors/i18next.js:355:38
	getResource@build/js/vendors/i18next.js:448:19
	getResource@build/js/vendors/i18next.js:960:42
	build/js/vendors/i18next.js:943:41
```
I did some debuging in 'Translator.prototype.resolve' method:

```
console.log("finalKeys",  finalKeys);

          while (possibleKey = finalKeys.pop()) {
            if (!_this3.isValidLookup(found)) {
              found = _this3.getResource(code, ns, possibleKey, options);
            }
          }
```

gave me these results: 

```
...
LOG LOG: 'finalKeys', ['someKey.baseValue', 'someKey.baseValue_context1']
LOG LOG: 'finalKeys', ['someKey.baseValue', 'someKey.baseValue_context1']
LOG LOG: 'finalKeys', ['someKey.baseValue', 'someKey.baseValue_context1']
LOG LOG: 'finalKeys', ['someKey.baseValue', 'someKey.baseValue_context1']
LOG LOG: 'finalKeys', ['someKey.baseValue', 'someKey.baseValue_context1']
LOG LOG: 'finalKeys', ['someKey.baseValue', 'someKey.baseValue_context1']
LOG LOG: 'finalKeys', ['someKey.baseValue', 'someKey.baseValue_context1']
LOG LOG: 'finalKeys', ['someKey.baseValue', 'someKey.baseValue_context1']
...

```

**Comment by jamuhl** [comment]
can build in a maxLoop like for interpolate: https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L104

but still you will need to fix your json:

processing: `"$t(someKey.baseValue) context1"` -> will nest the someKey.baseValue with options given -> results in using the key `someKey.baseValue_context1` --> therefor loops endless

not sure what you like to achive? you will have to change it to something like:

```
"someKey: {
  "base": "the context is: ",
  "baseValue: "",
  "baseValue_context1": "$t(someKey.base) context1"
}
```

**Comment by jamuhl** [comment]
context is like select in icu messageformat - used to change translation based on eg. gender...or whatever.

**Comment by tiriana** [comment]
@jamuhl Ok, so from what I understand I have 2 options now: 
* change my jsons
* update i18next to v9, with backward compability: (https://github.com/i18next/i18next/blob/master/test/backward/v1.11.1.compat.js#L45-L52), and then make use of `maxReplaces`.

Is that correct?

**Comment by jamuhl** [comment]
no you will have to change your json.

even if i make a new version with maxReplaces used in nesting too - it will just avoid that your browser stack does not explode but still the output would be:

`the context is: context1 context1 context1 context1 context1 context1 context1 context1 context1 context1 context1 context1 context1 context1 context1 context1 context1 context1 context1 context1 context1 context1 ...`

**Comment by tiriana** [comment]
:(

ok, we'll have to refactor our jsons than.

Thx
