### ISSUE TITLE
Customize  Language outside i18

### ISSUE THREAD

**Issue by webmobiles** [i18next/i18next#970]
can I create a new language ? by example 'en-children' , 'en-adult' , or 'fr-formal',  'fr-slang'.
I mean because it's a translator i'd like to have differents  languages but no standard.

**Comment by jamuhl** [comment]
yes should work...won't be detected as official using browser language detection...

**Comment by webmobiles** [comment]
nice,thanks

**Comment by jamuhl** [comment]
i18next will just uppercase per default so it will be en-CHILDREN...but nothing will block you from doing so...

if you encounter any issue let me know

**Comment by webmobiles** [comment]
yes it's working , i don't use detect language, and second part in Upper Case. thanks

here my i18n.js
```

import i18n from 'i18next';
import Backend from 'i18next-xhr-backend';
import { reactI18nextModule } from 'react-i18next';

i18n
  .use(Backend)
  .use(reactI18nextModule)
  .init({
    fallbackLng: 'fr-PELE',
    ns: ['translations'],
    defaultNS: 'translations',
    debug: true,
    interpolation: {
      escapeValue: false,
    },
    react: {
      wait: true,
    },
  });

export default i18n;

```

**Comment by webmobiles** [comment]
I've had to add    
```
i18n
.lng: 'fr-CHILDREN',
```
that's the right default
