### ISSUE TITLE
Jquery i18next in the handlebars the value of how to use?

### ISSUE THREAD

**Issue by XingdaLee** [i18next/i18next#972]
This handlebars Html Code:
`      <input level="1" name="unit1" type="text" args="{{user.unit1Id}}" value="{{#if user.unit1Id}}{{user.unit1}}"{{else}}hello world " class="selectinput" {{/if}} readonly="true">
`
How can i use i18next instead of hello world  this field? Thank you！！

**Comment by jamuhl** [comment]
https://www.google.ch/search?q=i18next+handlebars&oq=i18next+handlebars&aqs=chrome..69i57j69i60j0l3.3166j0j7&sourceid=chrome&ie=UTF-8

**Comment by XingdaLee** [comment]
`Handlebars.registerHelper('t', function(i18n_key) {
  // var result = i18n.t(i18n_key);
  var result = i18next.t(i18n_key);
  return new Handlebars.SafeString(result);
});`
Because before the use of i18n.t so lead to failure, now changed to i18next.t Well, thank you
