### ISSUE TITLE
whitelist issue

### ISSUE THREAD

**Issue by shaosh** [i18next/i18next#973]
Hi there,

Today I am trying to use whitelist to find zh resources when zh_HK resources are not available. Howerver this attempt failed because of the getLanguagePartFromCode() in i18next/src/LanguageUtils.js only consider dash like zh-HK, but not underscore like zh_HK. Is there any chance to include the underscore situation in getLanguagePartFromCode()?

Thanks,
shaosh

**Comment by jamuhl** [comment]
why you use underlines? every detector will give you a - as separator

**Comment by jamuhl** [comment]
if that comes from you backend i would suggest converting _ to - before passing it to i18next -> there are endless code parts and plugins that rely on that.

**Comment by shaosh** [comment]
Thanks for your quick answer. 
The browserDetector part is which I am uncertain - I am not sure that every detector uses -  as separator, so I think I should prepare for both _ and -.

**Comment by jamuhl** [comment]
detectors coming with i18next always use locals separated with `-` eg. `en-US`
