### ISSUE TITLE
 utf-8 route support

### ISSUE THREAD

**Issue by laurentdebricon** [i18next/i18next#975]
My route
website.com/pt/verificação-de-email

and all utf-8 route don't work :(

Best regards

**Comment by jamuhl** [comment]
what you mean by does not work?

can urls nowadays have such characters...i just know of the domain names could...and urls need to be encoded

**Comment by laurentdebricon** [comment]
Hello ok i found my answer ... I thought express was already supporting it ...
https://stackoverflow.com/a/15314157/212702

but no. Thank you for your work.
