### ISSUE TITLE
Consecutive calls to addResouceBundle

### ISSUE THREAD

**Issue by oliviertassinari** [i18next/i18next#976]
It seems that `addResouceBundle()` can only be called once given that following code branch:

https://github.com/i18next/i18next/blob/7edc9936586d5d50e81f8bc28b23642c85345d6c/src/i18next.js#L127-L128

I had to use the following logic to make my backend dynamically loading the right translations:
```js
        i18n.options.resources = null
        i18n.loadNamespaces(namespaces, errs => {
```

This might be a broader issue where [i18next-express-middleware](https://github.com/i18next/i18next-express-middleware) doesn't correctly isolate the requests as the `i18n.options.resources` variable leak between them.

**Comment by jamuhl** [comment]
a) you pass in resources on init -> you need to handle all loading and addResources

b) you do not pass in resources on init -> i18next does handle load resources

not sure what you mean by leak?

**Comment by oliviertassinari** [comment]
I'm not passing any resources server side to i18next.

> not sure what you mean by leak?

The leak is coming from this line. I would suggest you to use [deepmerge](https://github.com/KyleAMathews/deepmerge).

https://github.com/i18next/i18next/blob/7edc9936586d5d50e81f8bc28b23642c85345d6c/src/i18next.js#L301

**Comment by oliviertassinari** [comment]
Wait, I need to dig a bit more into the issue.

**Comment by oliviertassinari** [comment]
Ok, I confirm the source of the leak, it can be reproduced with:
```js
const options = { resources: { fr: 'fr' } }
const options2 = { ...options }
```

**Comment by jamuhl** [comment]
ok...but then still is just an issue if resources get set on init...evtl. doing a deepclone of options.resources would help...

**Comment by oliviertassinari** [comment]
@jamuhl I have added some comment in the previous comment.

**Comment by jamuhl** [comment]
so in this case memory got not free after request...as options share resources.

but still only relevant if passing in resources on init...loadResources does not set options.resources

**Comment by jamuhl** [comment]
but still...why there is a memory leak...express middleware does a clone...so the resourceStore is shared anyway. https://github.com/i18next/i18next/blob/master/src/i18next.js#L303

**Comment by oliviertassinari** [comment]
> so in this case memory got not free after request

@jamuhl Yes, the `i18next` object is a singleton. It can't be garbage collected. 

> but still...why there is a memory leak...express middleware does a clone...

The issue lies in the `cloneInstance()` method, I have provided a "reproduction" example simulating what's going on [in my previous comment](https://github.com/i18next/i18next/issues/976#issuecomment-339929246).
Sorry, but I don't know what else I could do to better explain the issue.
Actually, you should be able to easily reproduce the behavior with a failing tests under:
https://github.com/i18next/i18next/blob/ac314338bfc8b6955d9002a961c9596ee401acc2/test/i18next.spec.js#L30

**Comment by jamuhl** [comment]
question is more if memory does not get free over time -> garbage collection is not immediate

we do not have this behaviour in our production...but will look into it if i find time

**Comment by jamuhl** [comment]
PR would be welcome - to solve this. Currently not getting time to do this.

**Comment by jamuhl** [comment]
Closing this for now...there was another issue which was also guessing a memory leak in express-middleware but finally was an issue in userland.
