### ISSUE TITLE
new distribution for import via browser as es modules

### ISSUE THREAD

**Issue by daKmoR** [i18next/i18next#978]
hey,

maybe I'm doing something wrong but there is no distribution that allows for loading of i18next via es modules in the browser?

doing `import i18next from '../i18next/dist/es/index.js';`
will complain that it's written like
`import i18next from './i18next';`
and not as it would be needed in the browser with
`import i18next from './i18next.js';`

maybe provide an additional distribution like `es-browser`?

**Comment by jamuhl** [comment]
oh boy....amd, umd, commonjs, es for browserify, webpack and now es-browser? what the hell is es-browser?

you can either import:

`import { default as i18next } from '../i18next/dist/es/index.js';`

or individual functions:

`import { t } from '../i18next/dist/es/index.js';`

**Comment by daKmoR** [comment]
it's the es module support "native" to the browser? since chrome 61, safari 10.1, edge 16
http://caniuse.com/#search=module

would be awesome to not need any build step at all :)

sadly `import baseLogger from './logger';` inside `i18next/dist/es/index.js` does not work inside chrome 62... maybe just renaming it to `./logger.js` will work on browser, node, browserify, ...?

**Comment by jamuhl** [comment]
would you mind doing a PR?

**Comment by daKmoR** [comment]
there we go... 
https://github.com/i18next/i18next/pull/980

works fine for me in chrome 62 like that... let's see what travis has to say as currently my PhantomJS does not want to cooperate.

**Comment by jamuhl** [comment]
i18next@10.0.6 merged your PR - if still something to change just reopen this issue...thank you
