### ISSUE TITLE
cloneInstance will not respect defaultNS 

### ISSUE THREAD

**Issue by daKmoR** [i18next/i18next#979]
See the following example on jsfiddle:
https://jsfiddle.net/bLr88duq/

here are the important parts
```
i18next.init({
  defaultNS: 'something',
  resources: {
    en: {
      other: {
        "key": "hello world"
      }
    },
    de: {
      other: {
        "key": "hello welt"
      }
    }
  }
});

var myCopy = i18next.cloneInstance();
myCopy.init({
	defaultNS: 'other'
});

console.log(myCopy.t('key'));
// will return ''
// Error: i18next::translator: missingKey en something key key
```

that should work right? or do I misunderstand cloneInstance?

**Comment by jamuhl** [comment]
seems only:

```
var myCopy = i18next.cloneInstance({ defaultNS: 'other' });
myCopy.init(function() {
	updateContent();
});
```

works correctly...will need to check deeper and see what i can do.

**Comment by jamuhl** [comment]
updated docs to reflect it. basically a clone should just be a copy which could have override on lng, defaultNS so a API like `i18next.cloneInstance(opts)` should be sufficient.

https://www.i18next.com/api.html#cloneinstance

**Comment by daKmoR** [comment]
fair enough :)

works fine for me :) thx :)

**Comment by jamuhl** [comment]
hoped to get the createInstance and init afterwards to work too (like on createInstance) - but basically clones work rather different - as they do not create all the helpers (translator, backend, detector, lngHelpers,...) so there is no way to init and pass the new options to them...would be possible by extending all those classes to support some sort of reinit...but seems a little over the top regarding what clones should be used for....?!?

**Comment by daKmoR** [comment]
for me passing the initial options on clone is totally fine... I'm just
wondering does the setDefaultNS function works on a clone then?

also is any other way to change options? (that is probably very useful for
a clone as well)

sorry can't look it up or test it right now as I'm in the train :p

**Comment by jamuhl** [comment]
nope...setDefaultNS won't work...but https://www.i18next.com/api.html#getfixedt does more or less the same...

changing options after init is not possible of non clone instances neither - beside setting defaultNS
