### ISSUE TITLE
Please make enable to use ":" character in translation key

### ISSUE THREAD

**Issue by kochizufan** [i18next/i18next#981]
Hi

Currently, if I use ":" character in translation key, previous string of ":" looks be ignored.
(I think they may considered as namespace)

But I want to use ":" in translation key, because I want to use URL (like http://...) as translation key.
Would you please add some option or grammar to allow using ":" in translation key?

Just an idea, for example: if ":" is escaped by "\\", not considering it as namespace divider.

**Comment by jamuhl** [comment]
you could `t('key', { ns: 'yourNS', nsSeparator: false })` for this case: https://www.i18next.com/essentials.html#overview-options

But i'm open for a PR enabling escaping for nsSeparator, keySeparator

**Comment by kochizufan** [comment]
Does "nsSeparator" option work not only with "t" function but also "exists" or "addResource" function?
I checked them by quick test, but it looks not working with "exists" or "addResource"...

**Comment by jamuhl** [comment]
should work with `exists` and addResource takes ns as param https://github.com/i18next/i18next/blob/master/src/ResourceStore.js#L39

**Comment by kochizufan** [comment]
At last, "nsSeparator" option works, but not with false value but with some dummy value.

Thank you!
