### ISSUE TITLE
Replace the locize gif in the readme with a quieter version

### ISSUE THREAD

**Issue by sra448** [i18next/i18next#982]
Hi. I realise this is not your usual issue.

I feel like the gif ad for locize in the readme is very distracting. It doesn't feel nice as there is to much rapid movement going on. I suggest replacing it with a still version, or a gif that is less distracting and more professional feeling.

**Comment by jamuhl** [comment]
no....i need you to click there...not growing with locize i can't provide i18next OSS forever ;)

just joking...agree with you...might be the right time to calm that request for support a little down...

**Comment by sra448** [comment]
There is no shame in the ad itself, leave it there. But make it better (less action, more information).
It would maybe even help you with conversion rate.

**Comment by jamuhl** [comment]
finally done - hope you like this one better

**Comment by jamuhl** [comment]
still no marketing pro - but trying my best
