### ISSUE TITLE
Hungarian plural form is incorrect.

### ISSUE THREAD

**Issue by bvarga256** [i18next/i18next#984]
Using the language code: "hu" (Hungarian), i18next yields incorrect plural form results.

0 should resolve to "key", not "key_plural".

Even though in English, it is correct to say that:
1 apple,
but 0 apple**s**

In Hungarian, zero shouldn't considered as a plural form, it should be working like this:
{
    key: "apple",     <--- for both **zero and one**
    key_plural: "apples"    <--- for numbers **greater than** one (2, 3, 4, 5, ... etc)
}

**Comment by jamuhl** [comment]
the rule we use is https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L42

cldr says the same: http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#hu
and here: http://mlocati.github.io/cldr-to-gettext-plural-rules/
and here: http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html

**Comment by bvarga256** [comment]
See https://github.com/translate/l10n-guide/issues/66

**Comment by bvarga256** [comment]
Closed in favor of https://github.com/i18next/i18next/issues/985
