### ISSUE TITLE
More specialized keys should have a priority over generic keys.

### ISSUE THREAD

**Issue by bvarga256** [i18next/i18next#985]
**More specialized keys should have a priority over generic keys.**

Let's have a look at this simple json localization file (this is only for demonstration purposes):

```
{
    "apple": "X",
    "apple_plural": "Y",
    "apple_0": "Z"
}
```
Code:
`i18next.t("apple", {count: 0});`

apple_0 should have a greater precedence over apple_plural, because it is more specific,
and the code above should yield Z as a result, not Y.

**Comment by jamuhl** [comment]
Hm...in languages having "just" singular and plural the rule is singular has no suffix and plural the `_plural` -> the `_0` acts not as plural and would more or less just be interpreted as context in this case: https://www.i18next.com/context.html

If you prefer using numbers you can toggle `simplifyPluralSuffix: false` https://www.i18next.com/configuration-options.html#translation-defaults -> but in that case `0` = singular, `1` = plural

What you like to achieve is showing something special in case of zero i guess. You can do so using our intervalPlural extension: https://www.i18next.com/plurals.html#interval-plurals

```
{
    "apple": "{{count}} apple",
    "apple_plural": "{{count}} apples",
    "apple_interval": "(0){no apples}"
}

i18next.t('apple_interval', {postProcess: 'interval', count: 1})
```
