### ISSUE TITLE
loadNamespaces throw no file or directory for all registered namespaces

### ISSUE THREAD

**Issue by iocast** [i18next/i18next#986]
Hi

When I try to load a single namespace after initialisation phase, I get a list of errors belonging to all namespaces that couldn't be loaded.

let's say this namespace (file) does not exist.
```
this.i18next.loadNamespaces('test', (err, t) => {
  if(err) throw err;
  // do something
});
```
the error then looks like
```
[ { Error: ENOENT: no such file or directory, open '/.../en/test.json'
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/.../en/test.json' } ]
```

so when I now try to load an existing namespace
```
this.i18next.loadNamespaces('user', (err, t) => {
  if(err) throw err;
  // do something
});
```
I will get the the same error.

In this case I expect not getting an error, because the requesting namespace exists or to get the namespaces as attribute on the error object, so that I can evaluate if the error belongs to the requested namespace.

I think only returning the errors belonging to the requested namespaces is the way to go, because we can still listen to the `failedLoading` event to take action if a file is missing

Or do I miss something and you have a solution for that.
Thanks

**Comment by jamuhl** [comment]
are you sure namespace exists...i18next does not load namespace already loaded...looks more like your path is wrong and nothing gets loaded at all.

**Comment by iocast** [comment]
in my example the first namespace does not exists and the second one exists. when I load the second one it loads correctly. However I get the error from the first try, because I think the first namespace is [added to the `ns` array](https://github.com/i18next/i18next/blob/master/src/i18next.js#L267).

Because I need to load things dynamically I do not load any ns upfront. Depending on what I request in my logic I add the namespaces. So when I try to add a namespace that doesn't exist, I want to throw an error.

**Comment by jamuhl** [comment]
yes...loadNamespaces just adds that to the list of namespaces used and loads those. https://github.com/i18next/i18next/blob/master/src/i18next.js#L262

you might directly call i18next.services.backendConnector.load https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L131

`i18next.services.backendConnector.load(i18next.languages, ['user'], (err) => {});` if you just like to load one namespace

if you think it makes sense we could also add a function to i18next to load one namespace...should be similar to https://github.com/i18next/i18next/blob/master/src/i18next.js#L161 -> if you like you could provide a PR for that...?

**Comment by iocast** [comment]
it doesn't really change anything. The queue holds all errors. When first loading a namespace that doesn't exist and then loading one that exists, I still get the error from the first load.

So I first now check if the namespace exists as a folder  `fs.stat(tmplRoot, (err, stats) => { ...` and then I load the namespace `i18next.loadNamespaces(...`

I think the change in the lib is to big compared to first checking if the folder exist using standard node lib.
