### ISSUE TITLE
Enumerate a namespace ?

### ISSUE THREAD

**Issue by purell** [i18next/i18next#988]
Hi,

Is there a way to enumerate all entries of a namespace ?

```json
{
  "main": {
    "french": "Français",
    "english": "Anglais"
  }
}
```

Something like `enumerate('main.`)` ? That could returns
```
[
    { "french": "Français" },
    { "english": "Anglais" }
]
```

**Comment by jamuhl** [comment]
no but you can turn on returnObjects (on init or in t options) https://www.i18next.com/essentials.html#overview-options

that will allow you to return main as an object -> `i18next.t('main', { returnObjects: true })`

returns:

```
{
    "french": "Français",
    "english": "Anglais"
}
```

from there you could use Object.keys() to get all keys...

**Comment by purell** [comment]
It make sense.
Thank you so much :)
