### ISSUE TITLE
New i18next framework for .NET written in C#

### ISSUE THREAD

**Issue by leonardobaggio** [i18next/i18next#990]
Hi folks!

I just love i18next and am currently using in our Frontend written in Javascript/React. In the past days we needed to implement a feature that requires to use the same localization texts at our Backend, that is coded mainly in C#.

The first thought was "well, lets use something that already does the job for C# and life goes on". But after some research, I did not came across to any framework that provide the exact same behavior then i18next and also could let me share the same localization files across platforms...

And then, I made this:

https://github.com/leonardobaggio/i18next-net

I've implemented just the basic functionalities, but it is just good enough for my current needs. Hope you guys enjoy, and feel free to contribute, ask questions or give any kind of advises.

**Comment by jamuhl** [comment]
Hey @leonardobaggio that's awesome...direct support in .net. What we did in https://locize.com (our service tier of i18next) was adding resx support for exports - so one could export both json or resx.

Added i18next-net to https://www.i18next.com/supported-frameworks.html and will do a few tweets on monday.

Thanks a lot to contribute this to the i18next ecosystem...

**Comment by jamuhl** [comment]
was added to docs and we did some tweets and linkedin promotion for it...looking forward to see .net developers using it...will keep an eye on it. thanks again for adding this to the ecosystem of i18next.

**Comment by nstubi** [comment]
Hello,

It looks great.
Any plans to release a nuget package?

I have just seen that there is a package i18next written by Jan Mühlemann.

Best Regards,
Nicolas

**Comment by jamuhl** [comment]
@leonardobaggio might be a question for you...
