### ISSUE TITLE
Interpolation format function value is undefined

### ISSUE THREAD

**Issue by daKmoR** [i18next/i18next#991]
See the Example
https://jsfiddle.net/mz71wjza/

Important bits
```js
i18next.init({
  //...
  interpolation: {
    format: function(value, format, language) {
      console.log(value); // is undefined
      return value;
    }
  }
});
```

**Comment by jamuhl** [comment]
https://www.i18next.com/formatting.html#basic

value is the based in variable -> your fiddle does not interpolate a value

**Comment by daKmoR** [comment]
ooohhh you can only format variables...
