### ISSUE TITLE
Failed to load JSON file in loadPath

### ISSUE THREAD

**Issue by Akki4141** [i18next/i18next#993]
Hi I am new to 18next module and trying to learn it. I have made very simple page to understand the working. My Directory structure is :
```
|--languages
   |--locales
      |--en.json
      |--de.json
|--main.html
|-myscript.js
```
Here are the following files: 

main.html:
```
<script src="https://unpkg.com/i18next/i18next.js"></script>
<script src="https://unpkg.com/i18next-xhr-backend/i18nextXHRBackend.js"></script>
<script src="https://unpkg.com/i18next-browser-languagedetector/i18nextBrowserLanguageDetector.js"></script>
<script src="./myscript.js"></script>
<div style="height: 150px">
  <button onclick="i18next.changeLanguage('en')">
  english
  </button>
  <button onclick="i18next.changeLanguage('de')">
  german
  </button>
  <li id="text">HELLO</li>
</div>
```
myscript.js:

```
i18next
.use(i18nextXHRBackend)
.use(i18nextBrowserLanguageDetector)
.init({
  lng: 'en',
  debug: true,
  backend: {
    loadPath: './languages/locales/{{lng}}.json',
  }
}, function(err, t) {
  // init set content
  updateContent();
});


function updateContent() {
    console.log(document.getElementById('text').textContent);
    document.getElementById('text').textContent = i18next.t(document.getElementById('text').textContent);
}

function changeLng(lng) {
i18next.changeLanguage(lng);
}

i18next.on('languageChanged', () => {
updateContent();
});
```
en.json:
```
{
    "HELLO": "HELLO"
}
```
de.json:

```
{
  "HELLO":"HOLA"
}
```
But on the browser, the error is coming that it is failing to load resources and the text is also not changing. Can somebody tell where I am going wrong?

**Comment by jamuhl** [comment]
If it stating it can't load - there is something wrong. Could you load that files by entering the path yourself in the addressbar of your browser?

**Comment by Akki4141** [comment]
I am attaching a screenshot where the errors are coming. Yes, the file when clicked it is loading in the browser.
![i18nextexample](https://user-images.githubusercontent.com/17117586/32784111-8396f99e-c913-11e7-9462-dd7ff6203262.png)

Also, I don't know in the error, the error for en.json is coming but I don't know why instead of de.json it is stating dev.json.

**Comment by jamuhl** [comment]
`dev` is default defined as fallbackLng (developer english ;)) -> https://www.i18next.com/principles/fallback.html#fallback-language

and your xhr for sure does not work -> no xhr works when opening a html file from filesystem.

use a standalone webserver: eg: https://www.npmjs.com/package/http-server

**Comment by Akki4141** [comment]
okay say I put the logic in the application using Node and Express, because that uses localhost when loading the application, it should work?

**Comment by Akki4141** [comment]
Surely, I will give it a try.
