### ISSUE TITLE
Official Angular 2+ Repo?

### ISSUE THREAD

**Issue by k-schneider** [i18next/i18next#997]
Hello,

I see there are i18next managed repos for both React and AngularJS but nothing for Angular 2+.  Is anything planned?

Thanks.

**Comment by jamuhl** [comment]
https://github.com/Romanchuk/angular-i18next should work

https://github.com/actimeo/ng2-i18next (should work too i guess - not to deep into angular myself)

**Comment by k-schneider** [comment]
Yep I'm aware of these 2 libraries but they only have a few stars each and I'm not sure how maintained they are. Was hoping i18next had something planned that they would maintain but I understand if you don't at this point.  Thanks.

**Comment by jamuhl** [comment]
the point is most framework specific integrations (beside the one for react, jquery - which were used by myself) are completely driven by the amazing community. Most of those integrations are small enough to be maintained by oneself - as all the core functionality is provided by i18next.

**Comment by jamuhl** [comment]
Plus stars is a rather weird metric...better look for last commit and open issues - stars nowadays are often lead by pure popularity retweets of tech influencers. Getting stars by natural grow is rather hard...took i18next over 6 years to get were it is know - while one retweet can give you 1000+ stars in a day.
