### ISSUE TITLE
Uses defaultLang instead of the provided language when localisation is available.

### ISSUE THREAD

**Issue by TimoRuetten** [i18next/i18next#998]
We are facing a problem with i18next which causes problems for our SSR React-Based app. We are using your Provider and HOC for translating our Components. It works as it should except for one case.

We allow normal language urls like /en and /de but also location based urls like /en-GB and /de-CH. Sometimes we have the en-GB file but in some cases we only have the en file. In generell it works as expected. So if the language is en-GB and we do not have the key inside our en-GB.json file or we do not have the file i18next will search for the key in the en.json file. So everything seems to be fine. 

But the problem is when we use SSR. On Server we do the translations and send the payload of the i18next store back to the client.  The payload looks like this:

```
{
  de: {
    ui: {
      helloWorld: 'Hallo Welt',
    },
  },
  en: {
    ui: {
      helloWorld: 'Hello World',
    },
  },
}
```

The defaultLanguage is set to `en`
In the client settings we use the XHR Backend (later we only wants to send the payload which is needed).

This is what will happen when we call this url: **/de-CH/an-article**
1. On Server it will load the content and translate it. Because it will not find the de-CH file it will use the de file. So the Server content is fine!
2. The client will get the content and the payload. 
3. I18next tries to load the de-CH translation from payload with the key which is needed. For example 'ui.helloWorld'.
4. i18next does not find this in payload
5. i18next uses defaultLanguage 'en'
6. i18next tries to load de-CH.json
7. because file does not exists i18next uses now 'de'

To the problem is number 5. i18next uses 'en' as default because de-CH was not found even when de is available. This will cause a markup error in react.

Solutions:
1) The solution is to deactivate the backend for client - because then the client only use whats in the payload. 
2) The other solution would be to assign to the payload the de-DE (if not provided) and clone the de object.

Currently we have deactivated the backend for client and later we will use solution 2. But I think this is just a dirty fix for us. As we think it would be more logic if i18n will load 'de' as default when 'de-CH' is not available and will later replace the 'de' translation with the 'de-CH' if the backend was able to load the file.

**Comment by jamuhl** [comment]
not sure how your configuration looks...but finding `de-CH` as user language in regular mode i18next will first lookup a translation in de-CH if not found there in de and finally in the fallback...

how do you append the payload from server to i18next? via addResourceBundle or as init options.resources?

**Comment by TimoRuetten** [comment]
We are using your Provider for React. It looks like this:



```
<I18nextProvider
            i18n={i18nextInstance}
            initialI18nStore={window.initialI18nStore || false}
            initialLanguage={window.initialI18nLanguage}
          >
            <AppRouter />
</I18nextProvider>
```

The i18nextinstance is the normal i18n instance (with or without XHR). The initialI18nStore looks like in the example:


```
{
  de: {
    ui: {
      helloWorld: 'Hallo Welt',
    },
  },
  en: {
    ui: {
      helloWorld: 'Hello World',
    },
  },
}
```

And the initialI18nLanguage is 'de-CH'.

**Comment by TimoRuetten** [comment]
Maybe this problem is related to the provider ? I will try to make a simple setup - maybe the problem is somewhere else and not on the side of i18next.

**Comment by TimoRuetten** [comment]
By the way, this is our configuration:

```
    fallbackLng: 'en',
    whitelist: [
      'en',
      'de',
      'pt',
      'es',
      'fr',
    ],
    nonExplicitWhitelist: true,
    ns: [
      'ui',
    ],
    load: [
      'de',
      'en',
    ],
    defaultNS: 'ui',
```

**Comment by TimoRuetten** [comment]
Hey @jamuhl , I've create a repository. You can find it here:

https://github.com/TimoRuetten/i18next-problem-in-boilerplate

This is a setup like our app has (just without our app related stuff). If you have the time maybe you can take a look. I've wrote in the Readme how to test the problem with i18next.

I would appreciate if you could take a look at it and maybe help us out. I hope the setup I've made for you will be work and you are able to see our problem.

**Comment by jamuhl** [comment]
@TimoRuetten that's awesome...sure will take a look later today...thank you for taking the time to provide a full sample to reproduce - helps a lot.

**Comment by jamuhl** [comment]
@TimoRuetten i did some debugging and found the cause - in react-i18next we wait for loading dones - that way this issue does not hit there.

https://github.com/i18next/i18next/blob/master/src/i18next.js#L197

change language in the translator get's only set after loading is done -> we do that to avoid renderings before the translations get loaded.

The fix i did for test was:

https://github.com/i18next/i18next/blob/master/src/i18next.js#L209

there languages get set on i18next - but not on translator, adding `if (!this.translator.language) this.translator.changeLanguage(l);` does set the initial language as needed.

Will add this and publish a new i18next version immediately - would be awesome to get your feedback when done.

Thanks again for taking the time to setup the full sample - wouldn't have been able to help a lot without it.

**Comment by jamuhl** [comment]
Could you please try with: i18next@10.1.0

if not working i will need to digg deeper...

**Comment by TimoRuetten** [comment]
awesome @jamuhl - give me a few minutes I will test it and write you after.

**Comment by TimoRuetten** [comment]
And again you are very fast in helping and supporting :) Thanks a lot for your hard work in your awesome projects! Keep it up! Your fix did the job.

**Comment by jamuhl** [comment]
great to hear it worked...awesome...if anything else arise - let me know.
